DeepView: corecvs::FiltersCollection Class Reference
corecvs::FiltersCollection Class Reference
#include <filtersCollection.h>
Classes
class CompoundFilterType
Public Types
enum FilterTypes {
GAIN_OFFSET_FILTER = 0, BIT_SELECTOR_FILTER, SOBEL_FILTER, CANNY_FILTER,
BACKGROUND_FILTER, OPERATION_FILTER, TXT_FILTER, INPUT_FILTER,
OUTPUT_FILTER, BINARIZE_BLOCK, MASK_FILTER_BLOCK, THICKENING_BLOCK
}
Public Member Functions
FiltersCollection ()
~FiltersCollection ()
void getContainedBlocks (const char *xml, int n)
void getContainedBlocks (XMLDocument *doc, int n)
int getRowByName (const char *)
FilterBlock * getBlockFromRow (const int row, int id=-1)
FilterBlock * getBlockFromName (const char *type, int id=-1)
void addFilterType (const char *_name, const char *_filename)
void recalculateDependencies ()
bool dependsOnMe (int me, int filter)
void saveCompoundFilters (void)
Static Public Member Functions
static unsigned int numberOfFilterTypes ()
Public Attributes
bool changed
vector< CompoundFilterType > compoundFilters
Static Public Attributes
static const char * typenames []
Detailed Description
Definition at line 13 of file filtersCollection.h.
Member Enumeration Documentation
enum corecvs::FiltersCollection::FilterTypes
Enumerator:
GAIN_OFFSET_FILTER
BIT_SELECTOR_FILTER
SOBEL_FILTER
CANNY_FILTER
BACKGROUND_FILTER
OPERATION_FILTER
TXT_FILTER
INPUT_FILTER
OUTPUT_FILTER
BINARIZE_BLOCK
MASK_FILTER_BLOCK
THICKENING_BLOCK
Definition at line 16 of file filtersCollection.h.
                    { GAIN_OFFSET_FILTER = 0
                    , BIT_SELECTOR_FILTER
                    , SOBEL_FILTER
                    , CANNY_FILTER
                    , BACKGROUND_FILTER
                    , OPERATION_FILTER
                    , TXT_FILTER
                    , INPUT_FILTER
                    , OUTPUT_FILTER
                    , BINARIZE_BLOCK
                    , MASK_FILTER_BLOCK
                    , THICKENING_BLOCK
    };
Constructor & Destructor Documentation
corecvs::FiltersCollection::FiltersCollection ()
Definition at line 41 of file filtersCollection.cpp.
References tinyxml2::XMLElement::Attribute(), compoundFilters, tinyxml2::XMLNode::FirstChild(), getContainedBlocks(), tinyxml2::XMLElement::IntAttribute(), tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLNode::NextSibling(), recalculateDependencies(), tinyxml2::XMLNode::ToElement(), and tinyxml2::XML_SUCCESS.
                                     : changed(false)
{
    XMLDocument doc;
    XMLError err = doc.LoadFile("collection.conf");
    if (err != XML_SUCCESS)  return;
    XMLNode* p1 = doc.FirstChild();
    while(p1)
    {   compoundFilters.push_back(CompoundFilterType(p1->ToElement()->IntAttribute("id"),
                                                     p1->ToElement()->Attribute("typename"),
                                                     p1->ToElement()->Attribute("filename")));
        p1 = p1->NextSibling();
    }
    for (unsigned int i = 0; i < compoundFilters.size(); i++)
    {
        XMLError err = doc.LoadFile(compoundFilters[i].filename.c_str());
        if (err != XML_SUCCESS)
            continue;
        getContainedBlocks(&doc, i);
    }
    recalculateDependencies();
}
corecvs::FiltersCollection::~FiltersCollection ()
Definition at line 92 of file filtersCollection.cpp.
References changed, and saveCompoundFilters().
{
    if (!changed)
        return;
    saveCompoundFilters();
}
Member Function Documentation
void corecvs::FiltersCollection::addFilterType (const char * _name, const char * _filename) [inline]
Definition at line 41 of file filtersCollection.h.
References compoundFilters, getContainedBlocks(), tinyxml2::XMLDocument::LoadFile(), recalculateDependencies(), and tinyxml2::XML_SUCCESS.
Referenced by FilterGraphPresentation::saveAsClicked().
    {
        XMLDocument doc;
        XMLError err = doc.LoadFile(_filename);
        if (err != XML_SUCCESS)  return;
        CompoundFilterType ct((int)compoundFilters.size(), _name, _filename);
        compoundFilters.push_back(ct);
        getContainedBlocks(&doc, (int)(compoundFilters.size() - 1));
        recalculateDependencies();
////        changed = true;
    }
bool corecvs::FiltersCollection::dependsOnMe (int me, int filter)
Definition at line 210 of file filtersCollection.cpp.
References compoundFilters.
{
    return compoundFilters[me].dependOnMe.find(filter) != compoundFilters[me].dependOnMe.end();
}
FilterBlock * corecvs::FiltersCollection::getBlockFromName (const char * type, int id = -1)
Definition at line 165 of file filtersCollection.cpp.
References getBlockFromRow(), and getRowByName().
{
    int row = getRowByName(type);
    return getBlockFromRow(row, id);
}
FilterBlock * corecvs::FiltersCollection::getBlockFromRow (const int row, int id = -1)
Definition at line 130 of file filtersCollection.cpp.
References BACKGROUND_FILTER, BINARIZE_BLOCK, BIT_SELECTOR_FILTER, CANNY_FILTER, GAIN_OFFSET_FILTER, INPUT_FILTER, MASK_FILTER_BLOCK, numberOfFilterTypes(), OPERATION_FILTER, OUTPUT_FILTER, SOBEL_FILTER, THICKENING_BLOCK, and TXT_FILTER.
Referenced by FilterGraphPresentation::addFilter(), and getBlockFromName().
{
    switch (row)
    {
    case -1:
        return NULL;
    case GAIN_OFFSET_FILTER:
        return new GainOffsetFilter(id);
    case BIT_SELECTOR_FILTER:
        return new BitSelectorFilter(id);
    case SOBEL_FILTER:
        return new SobelFilter(id);
    case CANNY_FILTER:
        return new CannyFilter(id);
    case BACKGROUND_FILTER:
        return new BackgroundFilter(id);
    case OPERATION_FILTER:
        return new OperationFilter(id);
    case TXT_FILTER:
        return new TxtFilter(id);
    case INPUT_FILTER:
        return new InputFilter(id);
    case OUTPUT_FILTER:
        return new OutputFilter(id);
    case BINARIZE_BLOCK:
        return new BinarizeBlock(id);
    case MASK_FILTER_BLOCK:
        return new MaskFilterBlock(id);
    case THICKENING_BLOCK:
        return new ThickeningBlock(id);
    default:
        return new CompoundFilter(this, row - numberOfFilterTypes(), id);
    } // switch
}
void corecvs::FiltersCollection::getContainedBlocks (const char * xml, int n)
Definition at line 80 of file filtersCollection.cpp.
References tinyxml2::XMLDocument::Error(), and tinyxml2::XMLDocument::Parse().
Referenced by addFilterType(), and FiltersCollection().
{
    XMLDocument doc;
    XMLError errorId = doc.Parse(xml);
    if (doc.Error())
    {
        cout << "Parsing Error: " << errorId << endl;
        return;
    }
    getContainedBlocks(&doc, n);
}
void corecvs::FiltersCollection::getContainedBlocks (XMLDocument * doc, int n)
Definition at line 64 of file filtersCollection.cpp.
References tinyxml2::XMLElement::Attribute(), compoundFilters, tinyxml2::XMLNode::FirstChild(), getRowByName(), tinyxml2::XMLNode::NextSibling(), numberOfFilterTypes(), and tinyxml2::XMLNode::ToElement().
{
    XMLNode* p1 = doc->FirstChild();
    while(p1)
    {
        int row = getRowByName(p1->ToElement()->Attribute("type"));
        if (row == -1) {
            continue;
        }
        if ((uint)row >= numberOfFilterTypes()) {
            compoundFilters[n].contain.insert(row - numberOfFilterTypes());
        }
        p1 = p1->NextSibling();
    }
}
int corecvs::FiltersCollection::getRowByName (const char * type)
Definition at line 113 of file filtersCollection.cpp.
References compoundFilters, numberOfFilterTypes(), and typenames.
Referenced by getBlockFromName(), getContainedBlocks(), and FilterGraphPresentation::restoreFromGraph().
{
    for (unsigned int row = 0; row < numberOfFilterTypes(); row++)
    {
        if (!strcmp(typenames[row], type))
            return row;
    }
    for (unsigned int row = 0; row < compoundFilters.size(); row++)
    {
        if (!strcmp(compoundFilters[row].name.c_str(), type))
            return row + numberOfFilterTypes();
    }
    return -1;
}
unsigned int corecvs::FiltersCollection::numberOfFilterTypes () [static]
Definition at line 36 of file filtersCollection.cpp.
References typenames.
Referenced by getBlockFromRow(), getContainedBlocks(), and getRowByName().
{
    return sizeof(typenames)/sizeof(char*);
}
void corecvs::FiltersCollection::recalculateDependencies ()
Definition at line 178 of file filtersCollection.cpp.
References changed, and compoundFilters.
Referenced by FilterGraphPresentation::addFilter(), addFilterType(), and FiltersCollection().
{
    for (unsigned int i = 0; i < compoundFilters.size(); i++){
        compoundFilters[i].dependOnMe.clear();
        compoundFilters[i].dependOnMe.insert(i/*compoundFilters[i].id*/);
    }
    // Relation "depends on" is defined by two properties as follows:
    // 1) Each block depends on itself;
    // 2) If A contains B then A depends on each block B depends on
    // set dependOnMe for a given block - set of all blocks which depend on the given block
    // Here for each block i and for each block j which is contained in i we put
    // all blocks, which depend on block i into j-th block dependencies
\
    int counter;
    do
    {  counter = 0;
       for (unsigned int i = 0; i < compoundFilters.size(); i++)
         for (set<int>::iterator itcontained = compoundFilters[i].contain.begin();
              itcontained != compoundFilters[i].contain.end();
              ++itcontained)
            for (set<int>::iterator itdepend = compoundFilters[i].dependOnMe.begin();
                 itdepend != compoundFilters[i].dependOnMe.end();
                 ++itdepend)
               if (compoundFilters[*itcontained].dependOnMe.insert(*itdepend).second)
                   counter++;
    }while(counter > 0);
    changed = true;
}
void corecvs::FiltersCollection::saveCompoundFilters (void)
Definition at line 100 of file filtersCollection.cpp.
References compoundFilters, tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLDocument::SaveFile(), and tinyxml2::XMLElement::SetAttribute().
Referenced by FilterGraphPresentation::saveAsClicked(), and ~FiltersCollection().
{
    XMLDocument doc;
    for (unsigned int i = 0; i < compoundFilters.size(); i++)
    {
        XMLElement* type = doc.NewElement("filter");
        type->SetAttribute("typename", compoundFilters[i].name.c_str());
        type->SetAttribute("filename", compoundFilters[i].filename.c_str());
        doc.InsertEndChild(type);
    }
    doc.SaveFile("collection.conf");
}
Member Data Documentation
bool corecvs::FiltersCollection::changed
Definition at line 76 of file filtersCollection.h.
Referenced by recalculateDependencies(), and ~FiltersCollection().
vector<CompoundFilterType> corecvs::FiltersCollection::compoundFilters
Definition at line 77 of file filtersCollection.h.
Referenced by FilterGraphPresentation::addFilter(), addFilterType(), corecvs::CompoundFilter::CompoundFilter(), dependsOnMe(), FilterGraphPresentation::FilterGraphPresentation(), FiltersCollection(), getContainedBlocks(), FilterGraphPresentation::getGraphFileName(), getRowByName(), corecvs::CompoundFilter::loadGraph(), FilterPresentationsCollection::presentationByName(), recalculateDependencies(), and saveCompoundFilters().
const char * corecvs::FiltersCollection::typenames [static]
Initial value:
{
     "Gain Offset"
    ,"Bit Selector"
    ,"Sobel Filter"
    ,"Canny Filter"
    ,"Background Filter"
    ,"Operation Filter"
    ,"Text Filter"
    ,"Input"
    ,"Output"
    ,"Binarize Block"
    ,"Mask Filter Block"
    ,"Thickening Block"
}
Definition at line 29 of file filtersCollection.h.
Referenced by getRowByName(), corecvs::TxtFilter::getTypeName(), corecvs::BitSelectorFilter::getTypeName(), corecvs::BackgroundFilter::getTypeName(), corecvs::SobelFilter::getTypeName(), corecvs::GainOffsetFilter::getTypeName(), corecvs::CannyFilter::getTypeName(), corecvs::InputFilter::getTypeName(), corecvs::OutputFilter::getTypeName(), corecvs::OperationFilter::getTypeName(), and numberOfFilterTypes().
The documentation for this class was generated from the following files:
core/filters/filtersCollection.h
core/filters/filtersCollection.cpp