DeepView: BinarizeParametersControlWidget Class Reference
BinarizeParametersControlWidget Class Reference
#include <binarizeParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
BinarizeParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~BinarizeParametersControlWidget ()
BinarizeParameters * createParameters () const
void setParameters (const BinarizeParameters &input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual void setParametersVirtual (void *input)
Private Attributes
Ui_BinarizeParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 11 of file binarizeParametersControlWidget.h.
Constructor & Destructor Documentation
BinarizeParametersControlWidget::BinarizeParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file binarizeParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::BinarizeParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->thresholdSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
BinarizeParametersControlWidget::~BinarizeParametersControlWidget ()
Definition at line 26 of file binarizeParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void BinarizeParametersControlWidget::changeParameters () [inline, slot]
Definition at line 33 of file binarizeParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
BinarizeParameters * BinarizeParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 48 of file binarizeParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    BinarizeParameters *result = new BinarizeParameters(
          mUi->thresholdSpinBox->value()
    );
    return result;
}
virtual BaseReflectionStatic* BinarizeParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 22 of file binarizeParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void BinarizeParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 32 of file binarizeParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    BinarizeParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void BinarizeParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by BinarizeParametersControlWidget(), and setParameters().
void BinarizeParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 40 of file binarizeParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    BinarizeParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void BinarizeParametersControlWidget::setParameters (const BinarizeParameters & input)
Definition at line 62 of file binarizeParametersControlWidget.cpp.
References mUi, paramsChanged(), and BinarizeParameters::threshold().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->thresholdSpinBox->setValue(input.threshold());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void BinarizeParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 71 of file binarizeParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    BinarizeParameters *inputCasted = static_cast<BinarizeParameters *>(input);
    setParameters(*inputCasted);
}
void BinarizeParametersControlWidget::valueChanged () [signal]
Referenced by BinarizeParametersControlWidget().
Member Data Documentation
bool BinarizeParametersControlWidget::autoInit [private]
Definition at line 44 of file binarizeParametersControlWidget.h.
Ui_BinarizeParametersControlWidget* BinarizeParametersControlWidget::mUi [private]
Definition at line 43 of file binarizeParametersControlWidget.h.
Referenced by BinarizeParametersControlWidget(), createParameters(), setParameters(), and ~BinarizeParametersControlWidget().
QString BinarizeParametersControlWidget::rootPath [private]
Definition at line 45 of file binarizeParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/binarizeParametersControlWidget.h
utils/filters/ui/binarizeParametersControlWidget.cpp