DeepView: BaseFilter Class Reference
BaseFilter Class Reference
#include <basefilter.h>
Signals
void parametersChanged (void)
Public Member Functions
BaseFilter (QWidget *parent=0)
~BaseFilter ()
virtual QString getInstanceName ()
virtual G12Buffer * filter (G12Buffer *input)
Static Public Member Functions
static QString getName ()
Private Attributes
Ui_BaseFilterClass ui
Detailed Description
Definition at line 10 of file basefilter.h.
Constructor & Destructor Documentation
BaseFilter::BaseFilter (QWidget * parent = 0)
Definition at line 7 of file basefilter.cpp.
References ui.
    : QWidget(parent)
{
    ui.setupUi(this);
}
BaseFilter::~BaseFilter ()
Definition at line 19 of file basefilter.cpp.
{
}
Member Function Documentation
G12Buffer * BaseFilter::filter (G12Buffer * input) [virtual]
Reimplemented in ScaleFilter, GainOffset, BitSelector, and SobelFilter.
Definition at line 13 of file basefilter.cpp.
{
    G12Buffer *toReturn = new G12Buffer(input);
    return toReturn;
}
virtual QString BaseFilter::getInstanceName () [inline, virtual]
Reimplemented in GainOffset, BitSelector, ScaleFilter, and SobelFilter.
Definition at line 26 of file basefilter.h.
    {
        return QString("Base");
    };
static QString BaseFilter::getName () [inline, static]
Reimplemented in GainOffset, BitSelector, ScaleFilter, and SobelFilter.
Definition at line 21 of file basefilter.h.
    {
        return QString("Base");
    };
void BaseFilter::parametersChanged (void) [signal]
Referenced by BitSelector::maskChanged(), BitSelector::shiftChanged(), GainOffset::updateGainSlider(), GainOffset::updateGainText(), ScaleFilter::updateHeight(), GainOffset::updateOffsetSlider(), GainOffset::updateOffsetText(), ScaleFilter::updateWidth(), ScaleFilter::updateXScale(), ScaleFilter::updateXShift(), ScaleFilter::updateYScale(), and ScaleFilter::updateYShift().
Member Data Documentation
Ui_BaseFilterClass BaseFilter::ui [private]
Reimplemented in GainOffset, ScaleFilter, BitSelector, and SobelFilter.
Definition at line 37 of file basefilter.h.
Referenced by BaseFilter().
The documentation for this class was generated from the following files:
utils/filters/legacy/basefilter.h
utils/filters/legacy/basefilter.cpp