DeepView: corecvs::CameraIntrinsics Class Reference
corecvs::CameraIntrinsics Class Reference
This class describes the parameters of the ideal pin-hole camera TODO: Should be a child of a DeformMap or something similar.
#include <cameraParameters.h>
Public Member Functions
CameraIntrinsics ()
CameraIntrinsics (Vector2dd _resolution, Vector2dd _center, double _f, double _k)
Matrix44 getKMatrix () const
We will denote it by matrix .
Matrix44 getInvKMatrix () const
Returns inverse of K matrix.
Matrix33 getKMatrix33 () const
Matrix33 getInvKMatrix33 () const
double getVFov () const
double getHFov () const
template<class VisitorType >
void accept (VisitorType &visitor)
Public Attributes
Vector2dd resolution
Imager resolution (in pixel)
Vector2dd center
Principal point of optical axis on image plane (in pixel).
double f
Focal length (in mm)
double k
Pixel size (in mm)
Detailed Description
This class describes the parameters of the ideal pin-hole camera TODO: Should be a child of a DeformMap or something similar.
Camera intrinsics scale and shift the image.
Definition at line 27 of file cameraParameters.h.
Constructor & Destructor Documentation
corecvs::CameraIntrinsics::CameraIntrinsics () [inline]
Definition at line 35 of file cameraParameters.h.
                       :
        resolution(0.0)
      , center(0.0)
      , f(1.0)
      , k(1.0)
    {};
corecvs::CameraIntrinsics::CameraIntrinsics (Vector2dd _resolution, Vector2dd _center, double _f, double _k) [inline]
Definition at line 42 of file cameraParameters.h.
      :
        resolution(_resolution)
      , center(_center)
      , f(_f)
      , k(_k)
    {};
Member Function Documentation
template<class VisitorType > void corecvs::CameraIntrinsics::accept (VisitorType & visitor) [inline]
Definition at line 66 of file cameraParameters.h.
References center, f, k, and resolution.
    {
        visitor.visit(resolution, Vector2dd(0.0), "resolution");
        visitor.visit(center, Vector2dd(0.0), "center");
        visitor.visit(f, 1.0, "focalMM");
        visitor.visit(k, 1.0, "pixelMM");
    }
double corecvs::CameraIntrinsics::getHFov () const
Definition at line 81 of file cameraParameters.cpp.
References f, k, resolution, and corecvs::Vector2d< ElementType >::x().
Referenced by StereoCameraScene::drawMyself().
{
    double focal = f / k;
    return atan((resolution.x() / 2.0) / focal) * 2.0;
}
Matrix44 corecvs::CameraIntrinsics::getInvKMatrix () const
Returns inverse of K matrix.
For K matrix read CameraIntrinsics::getKMatrix()
Definition at line 42 of file cameraParameters.cpp.
References center, f, k, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::FCostFunction::getBMatrix(), and corecvs::FCostFunction::getInvDMatrix().
{
    double invFocal = k / f;
    return Matrix44 (
       invFocal,  0.0,    -center.x() * invFocal, 0.0,
          0.0,  invFocal, -center.y() * invFocal, 0.0,
          0.0,    0.0,               1.0,         0.0,
          0.0,    0.0,               0.0,         1.0
    );
}
Matrix33 corecvs::CameraIntrinsics::getInvKMatrix33 () const
Definition at line 65 of file cameraParameters.cpp.
References center, f, k, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by UniversalRectifier::recalculate(), and corecvs::Triangulator::Triangulator().
{
    double invFocal = k / f;
    return Matrix33 (
       invFocal,  0.0,    -center.x() * invFocal,
          0.0,  invFocal, -center.y() * invFocal,
          0.0,    0.0,               1.0
    );
}
Matrix44 corecvs::CameraIntrinsics::getKMatrix () const
We will denote it by matrix .
This matrix transform the 3D points form camera coordinate system to image coordinate system
Definition at line 27 of file cameraParameters.cpp.
References center, f, k, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::FCostFunction::getBMatrix(), and corecvs::FCostFunction::getDMatrix().
{
    double focal = f / k;
    return Matrix44 (
        focal,   0.0, center.x(), 0.0,
        0.0,   focal, center.y(), 0.0,
        0.0,     0.0,    1.0,     0.0,
        0.0,     0.0,    0.0,     1.0
    );
}
Matrix33 corecvs::CameraIntrinsics::getKMatrix33 () const
Definition at line 54 of file cameraParameters.cpp.
References center, f, k, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::RectificationResult::getRectifiedProjectionLeft(), and corecvs::RectificationResult::getRectifiedProjectionRight().
{
    double focal = f / k;
    return Matrix33 (
       focal,   0.0, center.x(),
       0.0,   focal, center.y(),
       0.0,     0.0,    1.0
    );
}
double corecvs::CameraIntrinsics::getVFov () const
Definition at line 75 of file cameraParameters.cpp.
References f, k, resolution, and corecvs::Vector2d< ElementType >::y().
Referenced by Scene3D::commonSetup(), and StereoCameraScene::drawMyself().
{
    double focal = f / k;
    return atan((resolution.y() / 2.0) / focal) * 2.0;
}
Member Data Documentation
Vector2dd corecvs::CameraIntrinsics::center
Principal point of optical axis on image plane (in pixel).
Usually center of imager
Definition at line 31 of file cameraParameters.h.
Referenced by accept(), getInvKMatrix(), getInvKMatrix33(), getKMatrix(), getKMatrix33(), and corecvs::FlowSimuator::simulateFlow().
double corecvs::CameraIntrinsics::f
Focal length (in mm)
Definition at line 32 of file cameraParameters.h.
Referenced by accept(), getHFov(), getInvKMatrix(), getInvKMatrix33(), getKMatrix(), getKMatrix33(), and getVFov().
double corecvs::CameraIntrinsics::k
Pixel size (in mm)
Definition at line 33 of file cameraParameters.h.
Referenced by accept(), getHFov(), getInvKMatrix(), getInvKMatrix33(), getKMatrix(), getKMatrix33(), and getVFov().
Vector2dd corecvs::CameraIntrinsics::resolution
Imager resolution (in pixel)
Definition at line 30 of file cameraParameters.h.
Referenced by accept(), Scene3D::commonSetup(), getHFov(), and getVFov().
The documentation for this class was generated from the following files:
core/cammodel/cameraParameters.h
core/cammodel/cameraParameters.cpp