DeepView: OutputFilterParametersControlWidget Class Reference
OutputFilterParametersControlWidget Class Reference
#include <outputFilterParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
OutputFilterParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~OutputFilterParametersControlWidget ()
OutputFilterParameters * createParameters () const
void setParameters (const OutputFilterParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_OutputFilterParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file outputFilterParametersControlWidget.h.
Constructor & Destructor Documentation
OutputFilterParametersControlWidget::OutputFilterParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file outputFilterParametersControlWidget.cpp.
References mUi, and paramsChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::OutputFilterParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->outputTypeComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
}
OutputFilterParametersControlWidget::~OutputFilterParametersControlWidget ()
Definition at line 26 of file outputFilterParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void OutputFilterParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file outputFilterParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
OutputFilterParameters * OutputFilterParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 48 of file outputFilterParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    OutputFilterParameters *result = new OutputFilterParameters(
          static_cast<OutputType::OutputType>(mUi->outputTypeComboBox->currentIndex())
    );
    return result;
}
virtual BaseReflectionStatic* OutputFilterParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 25 of file outputFilterParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void OutputFilterParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 32 of file outputFilterParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    OutputFilterParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void OutputFilterParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by OutputFilterParametersControlWidget(), and setParameters().
void OutputFilterParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 40 of file outputFilterParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    OutputFilterParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void OutputFilterParametersControlWidget::setParameters (const OutputFilterParameters & input)
Definition at line 62 of file outputFilterParametersControlWidget.cpp.
References mUi, OutputFilterParameters::outputType(), and paramsChanged().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->outputTypeComboBox->setCurrentIndex(input.outputType());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void OutputFilterParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 71 of file outputFilterParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    OutputFilterParameters *inputCasted = static_cast<OutputFilterParameters *>(input);
    setParameters(*inputCasted);
}
void OutputFilterParametersControlWidget::valueChanged () [signal]
Member Data Documentation
bool OutputFilterParametersControlWidget::autoInit [private]
Definition at line 45 of file outputFilterParametersControlWidget.h.
Ui_OutputFilterParametersControlWidget* OutputFilterParametersControlWidget::mUi [private]
Definition at line 44 of file outputFilterParametersControlWidget.h.
Referenced by createParameters(), OutputFilterParametersControlWidget(), setParameters(), and ~OutputFilterParametersControlWidget().
QString OutputFilterParametersControlWidget::rootPath [private]
Definition at line 46 of file outputFilterParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/outputFilterParametersControlWidget.h
utils/filters/ui/outputFilterParametersControlWidget.cpp