DeepView: ColorTimer Class Reference
ColorTimer Class Reference
#include <colorTimer.h>
Signals
void colorTimeout (QDoubleSpinBox *box, int timeoutNum)
Public Member Functions
ColorTimer (QDoubleSpinBox *box)
~ColorTimer ()
Private Slots
void emitSignal ()
Private Attributes
QDoubleSpinBox * mBox
int mTimeoutNum
Detailed Description
Definition at line 7 of file colorTimer.h.
Constructor & Destructor Documentation
ColorTimer::ColorTimer (QDoubleSpinBox * box)
Definition at line 3 of file colorTimer.cpp.
References emitSignal(), and mTimeoutNum.
                                          :
    QTimer(box),
    mBox(box)
{
    mTimeoutNum = 0;
    connect(this, SIGNAL(timeout()), this, SLOT(emitSignal()));
}
ColorTimer::~ColorTimer ()
Definition at line 11 of file colorTimer.cpp.
References mBox.
{
    mBox = NULL;
}
Member Function Documentation
void ColorTimer::colorTimeout (QDoubleSpinBox * box, int timeoutNum) [signal]
Referenced by emitSignal().
void ColorTimer::emitSignal () [private, slot]
Definition at line 16 of file colorTimer.cpp.
References colorTimeout(), mBox, and mTimeoutNum.
Referenced by ColorTimer().
{
    mTimeoutNum ++;
    emit colorTimeout(mBox, mTimeoutNum);
}
Member Data Documentation
QDoubleSpinBox* ColorTimer::mBox [private]
Definition at line 21 of file colorTimer.h.
Referenced by emitSignal(), and ~ColorTimer().
int ColorTimer::mTimeoutNum [private]
Definition at line 22 of file colorTimer.h.
Referenced by ColorTimer(), and emitSignal().
The documentation for this class was generated from the following files:
utils/camcalc/colorTimer.h
utils/camcalc/colorTimer.cpp