DeepView: corecvs::BMPLoader Class Reference
corecvs::BMPLoader Class Reference
#include <bmpLoader.h>
Public Member Functions
BMPLoader ()
virtual ~BMPLoader ()
virtual bool acceptsFile (string name)
virtual G12Buffer * load (string name)
virtual RGB24Buffer * loadRGB (string name)
virtual bool save (string name, RGB24Buffer *buffer)
TODO: Add error handling.
virtual bool save (string name, G12Buffer *buffer)
virtual bool save (string name, G8Buffer *buffer)
Private Member Functions
int parseBMP (string &name, BMPHeader *header, uint8_t **dataPtr)
Static Private Attributes
static string prefix1
Detailed Description
Definition at line 42 of file bmpLoader.h.
Constructor & Destructor Documentation
corecvs::BMPLoader::BMPLoader ()
Definition at line 21 of file bmpLoader.cpp.
{
}
corecvs::BMPLoader::~BMPLoader () [virtual]
Definition at line 207 of file bmpLoader.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
bool corecvs::BMPLoader::acceptsFile (string name) [virtual]
Implements corecvs::BufferLoader< G12Buffer >.
Definition at line 25 of file bmpLoader.cpp.
References prefix1.
{
    return (name.compare(name.length() - prefix1.length(), prefix1.length(), prefix1) == 0);
}
G12Buffer * corecvs::BMPLoader::load (string name) [virtual]
Implements corecvs::BufferLoader< G12Buffer >.
Definition at line 139 of file bmpLoader.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::BMPHeader::h, corecvs::BMPHeader::lineLength, corecvs::RGBColor::luma12(), parseBMP(), and corecvs::BMPHeader::w.
{
    uint8_t *data = NULL;
    BMPHeader header;
    G12Buffer *toReturn = NULL;
    if (parseBMP(name, &header, &data) != 0)
        goto fail;
    toReturn = new G12Buffer(header.h, header.w);
    for (unsigned i = 0; i < header.h; i++)
    {
        uint8_t  *src = &(data[header.lineLength * (header.h - i - 1)]);
        uint16_t *dest = &toReturn->element(i,0);
        for (unsigned j = 0; j < header.w; j++)
        {
            uint8_t b = src[0];
            uint8_t g = src[1];
            uint8_t r = src[2];
            uint16_t gray = RGBColor(r,g,b).luma12();
            *dest = gray;
            src += 3;
            dest++;
        }
    }
fail:
    if (data)
        delete[] data;
    return toReturn;
}
RGB24Buffer * corecvs::BMPLoader::loadRGB (string name) [virtual]
Definition at line 174 of file bmpLoader.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::BMPHeader::h, corecvs::BMPHeader::lineLength, parseBMP(), and corecvs::BMPHeader::w.
{
    uint8_t *data = NULL;
    BMPHeader header;
    RGB24Buffer *toReturn = NULL;
    if (parseBMP(name, &header, &data) != 0)
        goto fail;
    toReturn = new RGB24Buffer(header.h, header.w);
    for (unsigned i = 0; i < header.h; i++)
    {
        uint8_t  *src =  &(data[header.lineLength * (header.h - i - 1)]);
        RGBColor *dest = &toReturn->element(i,0);
        for (unsigned j = 0; j < header.w; j++)
        {
            uint32_t b = src[0];
            uint32_t g = src[1];
            uint32_t r = src[2];
            *dest = RGBColor(r,g,b);
            src+=3;
            dest++;
        }
    }
fail:
    if (data)
        delete[] data;
    return toReturn;
}
int corecvs::BMPLoader::parseBMP (string & name, BMPHeader * header, uint8_t ** dataPtr) [private]
Definition at line 104 of file bmpLoader.cpp.
References corecvs::BMPHeader::dataLen, and corecvs::BMPHeader::parseHeader().
Referenced by load(), and loadRGB().
{
    int status = -1;
    FILE *fp = NULL;
    size_t result = 0;
    uint8_t *data = NULL;
    fp = fopen(name.c_str(), "rb");
    if (fp == NULL)
       goto fail;
    if (header->parseHeader(fp) != 0)
       goto fail;
    data = new uint8_t[header->dataLen];
    if (data == NULL)
       goto fail;
    result = fread(data, sizeof(uint8_t), header->dataLen, fp);
    if (result != header->dataLen)
       goto fail;
    *dataPtr = data;
    data = NULL;
    status = 0;
fail:
    if (fp != NULL)
        fclose(fp);
    if (data != NULL)
        delete data;
    return status;
}
bool corecvs::BMPLoader::save (string name, RGB24Buffer * buffer) [virtual]
TODO: Add error handling.
Definition at line 234 of file bmpLoader.cpp.
References ASSERT_TRUE, corecvs::RGBColor::b(), corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::RGBColor::g(), corecvs::AbstractBufferParams::h, corecvs::BMPHeader::HEADER_SIGNATURE, corecvs::BMPHeader::HEADER_SIZE, corecvs::RGBColor::r(), and corecvs::AbstractBufferParams::w.
Referenced by UniversalRectifier::iterativeMethod(), and save().
{
    ASSERT_TRUE(buffer != NULL, "Null buffer could not be saved");
    FILE *fp = fopen(name.c_str(), "wb");
    if (fp == NULL)
        return false;
    int w = buffer->w;
    int h = buffer->h;
    /*Line length in BMP is always 32bit aligned*/
    int lineLength = w * 3;
    lineLength = (lineLength % 4) ? (lineLength | 0x3) + 1 : lineLength;
    int fileSize = BMPHeader::HEADER_SIZE + h * lineLength;
    uint8_t *data = new uint8_t[fileSize];
    if (!data)
    {
        fclose(fp);
        return false;
    }
    memset(data, 0, BMPHeader::HEADER_SIZE /*fileSize*/);
    data[0x0] = BMPHeader::HEADER_SIGNATURE[0];
    data[0x1] = BMPHeader::HEADER_SIGNATURE[1];
    *((uint32_t *)(data + 0x2)) =  h * lineLength + BMPHeader::HEADER_SIZE;
    data[0x6] = 0;
    data[0x7] = 0;
    *((uint32_t *)(data + 0xA))  = BMPHeader::HEADER_SIZE;
    *((uint32_t *)(data + 0xE))  = 0x28;
    *((uint32_t *)(data + 0x12)) = w;
    *((uint32_t *)(data + 0x16)) = h;
    *((uint16_t *)(data + 0x1A)) = 1;
    *((uint16_t *)(data + 0x1C)) = 24;
    *((uint32_t *)(data + 0x1E)) = 0;
    *((uint32_t *)(data + 0x22)) = lineLength * h;
    *((uint32_t *)(data + 0x26)) = 0x0000B013;
    *((uint32_t *)(data + 0x2A)) = 0x0000B013;
    *((uint32_t *)(data + 0x2E)) = 0x0;
    *((uint32_t *)(data + 0x32)) = 0x0;
    for (int i = 0; i < h; i++)
    {
        uint8_t *offset = data + BMPHeader::HEADER_SIZE + (lineLength * (h - 1 - i));   // lines are flipped vertically there
        int j;
        for (j = 0; j < w; j++)
        {
            RGBColor pixel = buffer->element(i, j);
            *offset++ = pixel.b();
            *offset++ = pixel.g();
            *offset++ = pixel.r();
        }
        // Put in predictable padding values
        for (int k = j * 3; k < lineLength; k++)
        {
            *offset++ = 0;
        }
    }
    fwrite(data, sizeof(uint8_t), fileSize, fp);
    fclose(fp);
    delete[] data;
    return true;
}
bool corecvs::BMPLoader::save (string name, G12Buffer * buffer) [virtual]
Definition at line 213 of file bmpLoader.cpp.
References save().
{
    RGB24Buffer *toSave = new RGB24Buffer(buffer);
    bool result = save(name, toSave);
    delete toSave;
    return result;
}
bool corecvs::BMPLoader::save (string name, G8Buffer * buffer) [virtual]
Definition at line 221 of file bmpLoader.cpp.
References corecvs::RGB24Buffer::drawG8Buffer(), corecvs::AbstractBuffer< ElementType, IndexType >::getSize(), and save().
{
    RGB24Buffer *toSave = new RGB24Buffer(buffer->getSize());
    toSave->drawG8Buffer(buffer);
    bool result = save(name, toSave);
    delete toSave;
    return result;
}
Member Data Documentation
string corecvs::BMPLoader::prefix1 [static, private]
Definition at line 44 of file bmpLoader.h.
Referenced by acceptsFile().
The documentation for this class was generated from the following files:
core/fileformats/bmpLoader.h
core/fileformats/bmpLoader.cpp