DeepView: InputFilterParametersControlWidget Class Reference
InputFilterParametersControlWidget Class Reference
#include <inputFilterParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
InputFilterParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~InputFilterParametersControlWidget ()
InputFilterParameters * createParameters () const
void setParameters (const InputFilterParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_InputFilterParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file inputFilterParametersControlWidget.h.
Constructor & Destructor Documentation
InputFilterParametersControlWidget::InputFilterParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file inputFilterParametersControlWidget.cpp.
References mUi, and paramsChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::InputFilterParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->inputTypeComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
}
InputFilterParametersControlWidget::~InputFilterParametersControlWidget ()
Definition at line 26 of file inputFilterParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void InputFilterParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file inputFilterParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
InputFilterParameters * InputFilterParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 48 of file inputFilterParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    InputFilterParameters *result = new InputFilterParameters(
          static_cast<InputType::InputType>(mUi->inputTypeComboBox->currentIndex())
    );
    return result;
}
virtual BaseReflectionStatic* InputFilterParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 25 of file inputFilterParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void InputFilterParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 32 of file inputFilterParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    InputFilterParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void InputFilterParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by InputFilterParametersControlWidget(), and setParameters().
void InputFilterParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 40 of file inputFilterParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    InputFilterParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void InputFilterParametersControlWidget::setParameters (const InputFilterParameters & input)
Definition at line 62 of file inputFilterParametersControlWidget.cpp.
References InputFilterParameters::inputType(), mUi, and paramsChanged().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->inputTypeComboBox->setCurrentIndex(input.inputType());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void InputFilterParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 71 of file inputFilterParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    InputFilterParameters *inputCasted = static_cast<InputFilterParameters *>(input);
    setParameters(*inputCasted);
}
void InputFilterParametersControlWidget::valueChanged () [signal]
Member Data Documentation
bool InputFilterParametersControlWidget::autoInit [private]
Definition at line 45 of file inputFilterParametersControlWidget.h.
Ui_InputFilterParametersControlWidget* InputFilterParametersControlWidget::mUi [private]
Definition at line 44 of file inputFilterParametersControlWidget.h.
Referenced by createParameters(), InputFilterParametersControlWidget(), setParameters(), and ~InputFilterParametersControlWidget().
QString InputFilterParametersControlWidget::rootPath [private]
Definition at line 46 of file inputFilterParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/inputFilterParametersControlWidget.h
utils/filters/ui/inputFilterParametersControlWidget.cpp