DeepView: DiagramScene Class Reference
DiagramScene Class Reference
#include <diagramscene.h>
Public Types
enum Mode { InsertItem, InsertLine, InsertText, MoveItem }
Public Slots
void setMode (Mode mode)
Signals
void blockItemSelected (QGraphicsItem *item)
void pinItemSelected (QGraphicsItem *item)
void graphChanged ()
Public Member Functions
DiagramScene (QObject *parent=0)
QFont font () const
QColor textColor () const
QColor itemColor () const
QColor lineColor () const
DiagramItem * diagramItemByPin (Pin *pin)
void setFont (const QFont &font)
void setFilterGraph (FilterGraph *graph)
void addArrow (DiagramItem *startItem, DiagramItem *endItem, QGraphicsItem *parent=0)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseMoveEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *mouseEvent)
Private Member Functions
bool isItemChange (int type)
Private Attributes
FilterGraph * filterGraph
Mode myMode
bool leftButtonDown
QPointF startPoint
QGraphicsLineItem * line
QFont myFont
DiagramTextItem * textItem
QColor myTextColor
QColor myItemColor
QColor myLineColor
Detailed Description
Definition at line 49 of file diagramscene.h.
Member Enumeration Documentation
enum DiagramScene::Mode
Enumerator:
InsertItem
InsertLine
InsertText
MoveItem
Definition at line 54 of file diagramscene.h.
{ InsertItem, InsertLine, InsertText, MoveItem };
Constructor & Destructor Documentation
DiagramScene::DiagramScene (QObject * parent = 0)
Definition at line 46 of file diagramscene.cpp.
References line, MoveItem, myItemColor, myLineColor, myMode, myTextColor, and textItem.
    : QGraphicsScene(parent)
{
    myMode = MoveItem;
    line = 0;
    textItem = 0;
    myItemColor = Qt::white;
    myTextColor = Qt::black;
    myLineColor = Qt::black;
}
Member Function Documentation
void DiagramScene::addArrow (DiagramItem * startItem, DiagramItem * endItem, QGraphicsItem * parent = 0)
Definition at line 282 of file diagramscene.cpp.
References DiagramItem::addArrow(), myLineColor, and Arrow::setColor().
Referenced by FilterPinPresentation::FilterPinPresentation(), and mouseReleaseEvent().
{
    Arrow *arrow = new Arrow(startItem, endItem, parent, this);
    arrow->setColor(myLineColor);
    startItem->addArrow(arrow);
    endItem->addArrow(arrow);
    arrow->setZValue(-1000.0);
}
void DiagramScene::blockItemSelected (QGraphicsItem * item) [signal]
Referenced by mousePressEvent().
DiagramItem * DiagramScene::diagramItemByPin (Pin * pin)
Definition at line 291 of file diagramscene.cpp.
References FilterPinPresentation::mPin, and DiagramItem::Type.
Referenced by FilterPinPresentation::FilterPinPresentation(), and CompoundBlockPresentation::removePin().
{
    QList<QGraphicsItem *> listItems = items();
    for(int i = 0; i < listItems.size(); i++)
    {
        if (listItems.value(i)->type() != DiagramItem::Type)
            continue;
        FilterPinPresentation *item = dynamic_cast<FilterPinPresentation*>(listItems.value(i));
        if (item != NULL && item->mPin == pin)
            return item;
    }
    return NULL;
}
QFont DiagramScene::font () const [inline]
Definition at line 57 of file diagramscene.h.
References myFont.
Referenced by FilterBlockPresentation::drawBlockName(), FilterPinPresentation::drawPinName(), G12PinPresentation::G12PinPresentation(), setFont(), and TxtPinPresentation::TxtPinPresentation().
{ return myFont; }
void DiagramScene::graphChanged () [signal]
Referenced by mouseReleaseEvent().
bool DiagramScene::isItemChange (int type) [private]
Definition at line 307 of file diagramscene.cpp.
Referenced by setFont().
{
    foreach (QGraphicsItem *item, selectedItems()) {
        if (item->type() == type)
            return true;
    }
    return false;
}
QColor DiagramScene::itemColor () const [inline]
Definition at line 59 of file diagramscene.h.
References myItemColor.
Referenced by FilterPinPresentation::draw(), and FilterBlockPresentation::drawBlock().
{ return myItemColor; }
QColor DiagramScene::lineColor () const [inline]
Definition at line 60 of file diagramscene.h.
References myLineColor.
{ return myLineColor; }
void DiagramScene::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 242 of file diagramscene.cpp.
References CompoundBlockPresentation::child, CompoundBlockPresentation::compoundFilter, FilterPresentationsCollection::filterIsEdited(), FilterGraphPresentation::filterPresentations, FilterBlockPresentation::mBlock, FilterPresentationsCollection::openedFilters, CompoundBlockPresentation::parent, FilterGraphPresentation::restoreFromGraph(), corecvs::FilterBlock::sort, and corecvs::CompoundFilter::typeId.
{
//    cout << "DiagramScene::mouseDoubleClickEvent" << endl;
    QList<QGraphicsItem *> listItems = items(mouseEvent->scenePos());
    for (int i = 0; i < listItems.size(); i++)
    {
        FilterBlockPresentation *item = dynamic_cast<FilterBlockPresentation *>(listItems.value(i));
        if (item == NULL)  continue;
        if (item->mBlock->sort != FilterBlock::COMPOUND_FILTER)  continue;
//        cout << "FilterBlock::COMPOUND_FILTER" << endl;
        CompoundBlockPresentation* compoundFilterPresentation = dynamic_cast<CompoundBlockPresentation*>(item);
        if (compoundFilterPresentation == NULL)
            continue;
        if (compoundFilterPresentation->parent->filterPresentations->filterIsEdited(compoundFilterPresentation->compoundFilter->typeId))
            continue;
        FilterGraphPresentation* filterGraphPresentation;
        if (compoundFilterPresentation->child != NULL)
            filterGraphPresentation = compoundFilterPresentation->child;
        else
        {   filterGraphPresentation = new FilterGraphPresentation(compoundFilterPresentation->parent->filterPresentations,
                                                                  compoundFilterPresentation);
            compoundFilterPresentation->child = filterGraphPresentation;
        }
        filterGraphPresentation->restoreFromGraph();
        filterGraphPresentation->show();
//        filterGraphPresentation->setAttribute(Qt::WA_DeleteOnClose);
        compoundFilterPresentation->parent->filterPresentations->openedFilters.insert(
                    compoundFilterPresentation->compoundFilter->typeId);
    }
    QGraphicsScene::mouseDoubleClickEvent(mouseEvent);
}
void DiagramScene::mouseMoveEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 167 of file diagramscene.cpp.
References InsertLine, line, MoveItem, and myMode.
{
//    cout<<"mouseMoveEvent"<<endl;
    if (myMode == InsertLine && line != 0) {
        QLineF newLine(line->line().p1(), mouseEvent->scenePos());
        line->setLine(newLine);
    } else if (myMode == MoveItem) {
        QGraphicsScene::mouseMoveEvent(mouseEvent);
    }
}
void DiagramScene::mousePressEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 75 of file diagramscene.cpp.
References blockItemSelected(), InsertItem, InsertLine, InsertText, line, MoveItem, myFont, myLineColor, myMode, myTextColor, pinItemSelected(), setMode(), textItem, DiagramItem::Type, and Arrow::Type.
{
//    cout<<"DiagramScene::mousePressEvent"<<endl;
    if (mouseEvent->button() != Qt::LeftButton)
        return;
    QList<QGraphicsItem *> listItems = items(mouseEvent->scenePos());
    bool pinSelected   = false;
    bool blockSelected = false;
    for(int i = 0; i < listItems.size(); i++)
    {
        if (listItems.value(i)->type() != DiagramItem::Type)
            continue;
        FilterPinPresentation *item = dynamic_cast<FilterPinPresentation *>(listItems.value(i));
        if (item != NULL)
            pinSelected = true;
        else
        {
            FilterBlockPresentation *item = dynamic_cast<FilterBlockPresentation *>(listItems.value(i));
            if (item != NULL)
                blockSelected = true;
        }
    }
    if (pinSelected)
        myMode = InsertLine;
    else if (blockSelected)
        myMode = InsertItem;
    switch (myMode) {
        case InsertItem:
            setMode(DiagramScene::MoveItem);
            break;
        case InsertLine:
            line = new QGraphicsLineItem(QLineF(mouseEvent->scenePos(),
                                        mouseEvent->scenePos()));
            line->setPen(QPen(myLineColor, 2));
            addItem(line);
            break;
        case InsertText:
            textItem = new DiagramTextItem(0, this);
            textItem->setFont(myFont);
            textItem->setTextInteractionFlags(Qt::TextEditorInteraction);
            textItem->setZValue(1000.0);
            textItem->setDefaultTextColor(myTextColor);
            textItem->setPos(mouseEvent->scenePos());
            setMode(DiagramScene::InsertText);
    default:
        ;
    } // switch
    QGraphicsScene::mousePressEvent(mouseEvent);
    QList<QGraphicsItem *> listSelectedItems = selectedItems();
    if (listSelectedItems.size() == 0){
        emit blockItemSelected(NULL);
        QRectF rect(mouseEvent->scenePos().x()-10, mouseEvent->scenePos().y()-10, 20, 20);
        QList<QGraphicsItem *> listItems = items(rect);
        if (listItems.size() == 1)
        {
            if (listItems.value(0)->type() == Arrow::Type)
            {
                if (listItems.value(0)->isSelected())
                    listItems.value(0)->setSelected(false);
                else
                    listItems.value(0)->setSelected(true);
            }
        }
    }
    else
    {
        FilterBlockPresentation *item = dynamic_cast<FilterBlockPresentation *>(listSelectedItems.value(0));
        if (item != NULL){
            emit blockItemSelected(item);
        }
        FilterPinPresentation *pinItem = dynamic_cast<FilterPinPresentation *>(listSelectedItems.value(0));
        if (pinItem != NULL){
            emit pinItemSelected(pinItem);
        }
    }
} // mousePressEvent
void DiagramScene::mouseReleaseEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 178 of file diagramscene.cpp.
References addArrow(), corecvs::FilterGraph::breakConnection(), corecvs::FilterGraph::connect(), filterGraph, graphChanged(), InsertLine, line, FilterBlockPresentation::mBlock, FilterPinPresentation::mPin, myMode, corecvs::Pin::setPin(), corecvs::FilterBlock::x, and corecvs::FilterBlock::y.
{
    bool changeOccurred = false;
//    cout<<"mouseReleaseEvent"<<endl;
    if (line != NULL && myMode == InsertLine) {
        QList<QGraphicsItem *> startItems = items(line->line().p1());
        QList<QGraphicsItem *> endItems = items(line->line().p2());
        for (int i = 0; i < startItems.size(); i++)
        {
            if (startItems.value(i) == line)
                continue;
            FilterPinPresentation *startItem = dynamic_cast<FilterPinPresentation*>(startItems.value(i));
            if (startItem == NULL)  continue;
            for (int j = 0; j < endItems.size(); j++)
            {
                if (endItems.value(j) == line)
                    continue;
                FilterPinPresentation *endItem = dynamic_cast<FilterPinPresentation*>(endItems.value(j));
                if (endItem == NULL)       continue;
                if (startItem == endItem)  continue;
                if (!filterGraph->connect(startItem->mPin, endItem->mPin))
                {
                    cout<<"Couldn't connect physically!"<<endl;
                    continue;
                }
                if (!endItem->mPin->setPin(startItem->mPin))
                {
                    cout<<"Pin types mismatch!"<<endl;
                    filterGraph->breakConnection(startItem->mPin, endItem->mPin);
                    continue;
                }
                addArrow(startItem, endItem);
                changeOccurred = true;
            } // for j
        } // for i
        removeItem(line);
        delete_safe(line);
    } // if
    //fill x and y for filterBlocks
    QList<QGraphicsItem *> listItems = items(mouseEvent->scenePos());
    for (int i = 0; i < listItems.size(); i++)
    {
        FilterBlockPresentation *diagramItem = dynamic_cast<FilterBlockPresentation*>(listItems.value(i));
        if (diagramItem == NULL)          continue;
        if (diagramItem->mBlock == NULL)  continue;
        diagramItem->mBlock->x = diagramItem->pos().x();
        diagramItem->mBlock->y = diagramItem->pos().y();
    }
    QGraphicsScene::mouseReleaseEvent(mouseEvent);
    if (changeOccurred)  emit graphChanged();
} // mouseReleaseEvent
void DiagramScene::pinItemSelected (QGraphicsItem * item) [signal]
Referenced by mousePressEvent().
void DiagramScene::setFilterGraph (FilterGraph * graph) [inline]
Definition at line 63 of file diagramscene.h.
References filterGraph.
Referenced by FilterGraphPresentation::FilterGraphPresentation().
{ filterGraph = graph; }
void DiagramScene::setFont (const QFont & font)
Definition at line 57 of file diagramscene.cpp.
References font(), isItemChange(), myFont, and DiagramTextItem::Type.
{
    myFont = font;
    if (isItemChange(DiagramTextItem::Type)) {
        QGraphicsTextItem *item =
            dynamic_cast<DiagramTextItem *>(selectedItems().first());
        //At this point the selection can change so the first selected item might not be a DiagramTextItem
        if (item)
            item->setFont(myFont);
    }
}
void DiagramScene::setMode (Mode mode) [slot]
Definition at line 70 of file diagramscene.cpp.
References myMode.
Referenced by mousePressEvent().
{
    myMode = mode;
}
QColor DiagramScene::textColor () const [inline]
Definition at line 58 of file diagramscene.h.
References myTextColor.
Referenced by FilterBlockPresentation::drawBlockName(), FilterPinPresentation::drawPinName(), G12PinPresentation::G12PinPresentation(), and TxtPinPresentation::TxtPinPresentation().
{ return myTextColor; }
Member Data Documentation
FilterGraph* DiagramScene::filterGraph [private]
Definition at line 84 of file diagramscene.h.
Referenced by mouseReleaseEvent(), and setFilterGraph().
bool DiagramScene::leftButtonDown [private]
Definition at line 86 of file diagramscene.h.
QGraphicsLineItem* DiagramScene::line [private]
Definition at line 88 of file diagramscene.h.
Referenced by DiagramScene(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QFont DiagramScene::myFont [private]
Definition at line 89 of file diagramscene.h.
Referenced by font(), mousePressEvent(), and setFont().
QColor DiagramScene::myItemColor [private]
Definition at line 92 of file diagramscene.h.
Referenced by DiagramScene(), and itemColor().
QColor DiagramScene::myLineColor [private]
Definition at line 93 of file diagramscene.h.
Referenced by addArrow(), DiagramScene(), lineColor(), and mousePressEvent().
Mode DiagramScene::myMode [private]
Definition at line 85 of file diagramscene.h.
Referenced by DiagramScene(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setMode().
QColor DiagramScene::myTextColor [private]
Definition at line 91 of file diagramscene.h.
Referenced by DiagramScene(), mousePressEvent(), and textColor().
QPointF DiagramScene::startPoint [private]
Definition at line 87 of file diagramscene.h.
DiagramTextItem* DiagramScene::textItem [private]
Definition at line 90 of file diagramscene.h.
Referenced by DiagramScene(), and mousePressEvent().
The documentation for this class was generated from the following files:
utils/filters/graph/diagramscene.h
utils/filters/graph/diagramscene.cpp