DeepView: corecvs::RAWLoader Class Reference
corecvs::RAWLoader Class Reference
#include <rawLoader.h>
Public Member Functions
RAWLoader (int _defaultH, int _defaultW, RawFileType _defaultType)
RAWLoader ()
virtual ~RAWLoader ()
RawFileType typeByParams (int bits, char type)
uint16_t transform (RAWLoader::RawFileType type, uint8_t byte1, uint8_t byte2)
virtual bool acceptsFile (string name)
virtual G12Buffer * load (string name)
Private Types
enum RawFileType {
TYPE_8_BIT, TYPE_12_BIT_LOW, TYPE_12_BIT_HIGH, TYPE_16_BIT_LOW,
TYPE_16_BIT_HIGH, TYPE_16_BIT_LOW_ONLY, TYPE_16_BIT_HIGH_ONLY, TYPE_INVALID
}
Private Member Functions
void _init (int _defaultH, int _defaultW, RawFileType _defaultType)
Private Attributes
int defaultH
int defaultW
RawFileType defaultType
Static Private Attributes
static string prefix1
Detailed Description
Definition at line 21 of file rawLoader.h.
Member Enumeration Documentation
enum corecvs::RAWLoader::RawFileType [private]
Enumerator:
TYPE_8_BIT
Format 8 bits for point D7 D6 D5 D4 D3 D2 D1 D0.
TYPE_12_BIT_LOW
Format 16/12 bits for point X X X X D11 D10 D9 D8 D7 D6 D5 D4 D3 D2 D1 D0.
TYPE_12_BIT_HIGH
TYPE_16_BIT_LOW
TYPE_16_BIT_HIGH
TYPE_16_BIT_LOW_ONLY
TYPE_16_BIT_HIGH_ONLY
TYPE_INVALID
Definition at line 25 of file rawLoader.h.
                 {
        TYPE_8_BIT,                 /**< Format  8 bits for point      D7  D6  D5  D4  D3  D2  D1  D0 */
        TYPE_12_BIT_LOW,            /**< Format 16/12 bits for point   X   X   X   X   D11 D10 D9  D8  D7  D6  D5  D4  D3  D2  D1  D0 */
        TYPE_12_BIT_HIGH,
        TYPE_16_BIT_LOW,
        TYPE_16_BIT_HIGH,
        TYPE_16_BIT_LOW_ONLY,
        TYPE_16_BIT_HIGH_ONLY,
        TYPE_INVALID
    } RawFileType;
Constructor & Destructor Documentation
corecvs::RAWLoader::RAWLoader (int _defaultH, int _defaultW, RawFileType _defaultType) [inline]
Definition at line 49 of file rawLoader.h.
References _init().
    {
        _init(_defaultH, _defaultW, _defaultType);
    }
corecvs::RAWLoader::RAWLoader () [inline]
Definition at line 54 of file rawLoader.h.
References _init(), and TYPE_12_BIT_HIGH.
    {
        _init(480, 640, RAWLoader::TYPE_12_BIT_HIGH);
    }
virtual corecvs::RAWLoader::~RAWLoader () [inline, virtual]
Definition at line 59 of file rawLoader.h.
{}
Member Function Documentation
void corecvs::RAWLoader::_init (int _defaultH, int _defaultW, RawFileType _defaultType) [inline, private]
Definition at line 40 of file rawLoader.h.
References defaultH, defaultType, and defaultW.
Referenced by RAWLoader().
    {
        this->defaultH    = _defaultH;
        this->defaultW    = _defaultW;
        this->defaultType = _defaultType;
    }
bool corecvs::RAWLoader::acceptsFile (string name) [virtual]
Implements corecvs::BufferLoader< G12Buffer >.
Definition at line 17 of file rawLoader.cpp.
References prefix1.
{
    return (name.compare(name.length() - prefix1.length(), prefix1.length(), prefix1) == 0);
}
G12Buffer * corecvs::RAWLoader::load (string name) [virtual]
Implements corecvs::BufferLoader< G12Buffer >.
Definition at line 71 of file rawLoader.cpp.
References defaultH, defaultType, defaultW, corecvs::AbstractBuffer< ElementType, IndexType >::element(), transform(), TYPE_8_BIT, TYPE_INVALID, and typeByParams().
{
    FILE* fp = NULL;
    G12Buffer *toReturn = NULL;
    uint8_t *data = NULL;
    long counter = 0;
    int h;
    int w;
    int bits;
    int bytes = 1;
    char typeChar;
    RawFileType type;
    string filename = name.substr(name.rfind('/') + 1);
    printf("Getting metainfo from filename %s\n", filename.c_str());
    if (sscanf(filename.c_str(), "%dx%d_%d%c_", &w, &h, &bits, &typeChar ) != 4)
    {
        h = defaultH;
        w = defaultW;
        type = defaultType;
    } else {
        type = typeByParams(bits, typeChar);
    }
    if (type == TYPE_INVALID)
    {
        printf("Wrong raw name pattern: %s\n", name.c_str());
        goto cleanup;
    }
    bytes = (type == TYPE_8_BIT) ? 1 : 2;
    //Open file for Reading in Binary Mode
    fp = fopen(name.c_str(), "rb");
    if (fp == NULL) {
        printf("Image %s does not exist \n", name.c_str());
        goto cleanup;
    }
    fseek(fp, 0, SEEK_END);
    counter = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    if (counter != h * w * bytes)
    {
        printf("Image file %s does not contain a valid ST image \n", name.c_str());
        goto cleanup;
    }
    data = new uint8_t[h * w * bytes];
    if (data == NULL)
    {
        printf("Could not allocate memory");
        goto cleanup;
    }
    if (fread(data, bytes, h * w, fp) == 0)
        throw "fread() call failed";
    toReturn = new G12Buffer(h, w, false);
    if (bytes == 1)
    {
        for (int i = 0; i < h; i++)
            for (int j = 0; j < w; j++)
                toReturn->element(i,j) = data[i * w + j];
    } else {
        for (int i = 0; i < h; i++)
            for (int j = 0; j < w; j++)
            {
                uint16_t byte1 = data[(i * w + j) * 2];
                uint16_t byte2 = data[(i * w + j) * 2 + 1];
                toReturn->element(i,j) = transform(type, (uint8_t)byte1, (uint8_t)byte2);
            }
    }
cleanup:
    if (fp != NULL)
        fclose(fp);
    if (data != NULL)
        delete[] data;
    return toReturn;
}
uint16_t corecvs::RAWLoader::transform (RAWLoader::RawFileType type, uint8_t byte1, uint8_t byte2)
Definition at line 49 of file rawLoader.cpp.
References ASSERT_TRUE, TYPE_12_BIT_HIGH, TYPE_12_BIT_LOW, TYPE_16_BIT_HIGH, TYPE_16_BIT_HIGH_ONLY, TYPE_16_BIT_LOW, and TYPE_16_BIT_LOW_ONLY.
Referenced by load().
{
    switch (type)
    {
        case RAWLoader::TYPE_12_BIT_HIGH :
            return ((uint16_t)byte1 << 4) | ((uint16_t)byte2 >> 4);
        case RAWLoader::TYPE_12_BIT_LOW :
            return ((uint16_t)byte1 >> 4) | ((uint16_t)byte2 << 4);
        case RAWLoader::TYPE_16_BIT_HIGH :
            return ((uint16_t)byte1 << 8) | ((uint16_t)byte2);
        case RAWLoader::TYPE_16_BIT_LOW :
            return ((uint16_t)byte1)      | ((uint16_t)byte2 << 8);
        case RAWLoader::TYPE_16_BIT_HIGH_ONLY :
            return ((uint16_t)byte1 << 4);
        case RAWLoader::TYPE_16_BIT_LOW_ONLY :
            return ((uint16_t)byte2 << 4);
        default:
            ASSERT_TRUE(false, "Internal Error");
    }
    return 0;
}
RAWLoader::RawFileType corecvs::RAWLoader::typeByParams (int bits, char type)
Definition at line 22 of file rawLoader.cpp.
References TYPE_12_BIT_HIGH, TYPE_12_BIT_LOW, TYPE_16_BIT_HIGH, TYPE_16_BIT_HIGH_ONLY, TYPE_16_BIT_LOW, TYPE_16_BIT_LOW_ONLY, TYPE_8_BIT, and TYPE_INVALID.
Referenced by load().
{
    if (bits == 8)
        return TYPE_8_BIT;
    if (bits == 12)
    {
        if (type == 'l')
            return TYPE_12_BIT_LOW;
        if (type == 'h')
            return TYPE_12_BIT_HIGH;
    }
    if (bits == 16)
    {
        if (type == 'l')
            return TYPE_16_BIT_LOW;
        if (type == 'h')
            return TYPE_16_BIT_HIGH;
        if (type == 'b')
            return TYPE_16_BIT_LOW_ONLY;
        if (type == 't')
            return TYPE_16_BIT_HIGH_ONLY;
    }
    return TYPE_INVALID;
}
Member Data Documentation
int corecvs::RAWLoader::defaultH [private]
Definition at line 36 of file rawLoader.h.
Referenced by _init(), and load().
RawFileType corecvs::RAWLoader::defaultType [private]
Definition at line 38 of file rawLoader.h.
Referenced by _init(), and load().
int corecvs::RAWLoader::defaultW [private]
Definition at line 37 of file rawLoader.h.
Referenced by _init(), and load().
string corecvs::RAWLoader::prefix1 [static, private]
Definition at line 23 of file rawLoader.h.
Referenced by acceptsFile().
The documentation for this class was generated from the following files:
core/fileformats/rawLoader.h
core/fileformats/rawLoader.cpp