DeepView: corecvs::BaseKernel< Algebra > Class Template Reference
corecvs::BaseKernel< Algebra > Class Template Reference
A base class for FastKernel kernels.
#include <baseKernel.h>
Public Types
typedef Algebra AlgebraType
typedef Algebra::Type BaseType
Public Member Functions
BaseKernel (BaseKernel &other)
Every implementation should contain copy constructor To be used with OpenMP (this reason is currently outdated)
BaseKernel ()
void setAlgebra (Algebra *_algebra)
void process ()
Static Public Member Functions
static int getCenterX ()
static int getCenterY ()
static int getSizeX ()
static int getSizeY ()
Public Attributes
Algebra * algebra
Detailed Description
template<typename Algebra>
class corecvs::BaseKernel< Algebra >
A base class for FastKernel kernels.
FastKernels use static polymorphism and that you may not inherit this class, but it's a demo of what methods are expected.
Definition at line 24 of file baseKernel.h.
Member Typedef Documentation
template<typename Algebra > typedef Algebra corecvs::BaseKernel< Algebra >::AlgebraType
Definition at line 27 of file baseKernel.h.
template<typename Algebra > typedef Algebra::Type corecvs::BaseKernel< Algebra >::BaseType
Definition at line 36 of file baseKernel.h.
Constructor & Destructor Documentation
template<typename Algebra > corecvs::BaseKernel< Algebra >::BaseKernel (BaseKernel< Algebra > & other) [inline]
Every implementation should contain copy constructor To be used with OpenMP (this reason is currently outdated)
Definition at line 42 of file baseKernel.h.
References corecvs::BaseKernel< Algebra >::algebra, and corecvs::BaseKernel< Algebra >::setAlgebra().
{
        setAlgebra(other.algebra);
    }
template<typename Algebra > corecvs::BaseKernel< Algebra >::BaseKernel () [inline]
Definition at line 46 of file baseKernel.h.
References corecvs::BaseKernel< Algebra >::setAlgebra().
                 {
        setAlgebra(NULL);
    }
Member Function Documentation
template<typename Algebra > static int corecvs::BaseKernel< Algebra >::getCenterX () [inline, static]
Definition at line 31 of file baseKernel.h.
{ return 0; }
template<typename Algebra > static int corecvs::BaseKernel< Algebra >::getCenterY () [inline, static]
Definition at line 32 of file baseKernel.h.
{ return 0; }
template<typename Algebra > static int corecvs::BaseKernel< Algebra >::getSizeX () [inline, static]
Definition at line 33 of file baseKernel.h.
{ return 1; }
template<typename Algebra > static int corecvs::BaseKernel< Algebra >::getSizeY () [inline, static]
Definition at line 34 of file baseKernel.h.
{ return 1; }
template<typename Algebra > void corecvs::BaseKernel< Algebra >::process () [inline]
Definition at line 54 of file baseKernel.h.
                   {
    }
template<typename Algebra > void corecvs::BaseKernel< Algebra >::setAlgebra (Algebra * _algebra) [inline]
Definition at line 50 of file baseKernel.h.
References corecvs::BaseKernel< Algebra >::algebra.
Referenced by corecvs::BaseKernel< Algebra >::BaseKernel().
{
        this->algebra = _algebra;
    }
Member Data Documentation
template<typename Algebra > Algebra* corecvs::BaseKernel< Algebra >::algebra
Definition at line 29 of file baseKernel.h.
Referenced by corecvs::BaseKernel< Algebra >::BaseKernel(), and corecvs::BaseKernel< Algebra >::setAlgebra().
The documentation for this class was generated from the following file:
core/buffers/kernels/fastkernel/baseKernel.h