DeepView: corecvs::UpperUnitaryMatrix Class Reference
corecvs::UpperUnitaryMatrix Class Reference
This class holds the upper part of the triangular unitary matrix.
#include <upperUnitaryMatrix.h>
Public Member Functions
int getUpperSize ()
UpperUnitaryMatrix (int _size, bool shouldInit=true)
double & u (int row, int column)
double a (int row, int column)
Matrix * toMatrix () const
double det ()
virtual ~UpperUnitaryMatrix ()
Static Public Member Functions
static int getUpperSizeFor (int size)
Public Attributes
int size
int memSize
double * elements
Private Member Functions
int internalOffset (int row, int column)
Friends
ostream & operator<< (ostream &out, const UpperUnitaryMatrix &matrix)
Detailed Description
This class holds the upper part of the triangular unitary matrix.
    |  0   1   2   3   4   5   6 | 7
    |----------------------------|---
  0 |  x   0   1   2   3   4   5 |
  1 |      x   6   7   8   9  10 |
  2 |          x  11  12  13  14 |
  3 |       -      x  15  16  17 |
  4 |      | |         x  18  19 |
  5 |      | |             x  20 |
  6 |       -                  x |
    |-----------------------------
  7
For matrix of size NxN we will have to store (N-1)(N-2)/2 elements. (ie. for 7x7 matrix 7*6/2 = 21 element 0..20)
To get the offset of the element at i,j (j>i) ((N-1) + (N - 1 - (i - 1))) / 2 * i + j - i - 1 = (2N - 1 - i) * i / 2 + j - i - 1
(i.e for element (3,4) -> (6 + 6 - 2) / 2 * 3 + 4 - 3 - 1 = 15)
TODO: Make indexing columnwise
    |  0   1   2   3   4   5   6 | 7
    |----------------------------|---
  0 |  x   0   1   3   6  10  15 |
  1 |      x   2   4   7  11  16 |
  2 |          x   5   8  12  17 |
  3 |       -      x   9  13  18 |
  4 |      | |         x  14  19 |
  5 |      | |             x  20 |
  6 |       -                  x |
    |-----------------------------
  7
  (i,j) -> (j * (j - 1)) / 2 + i;
  (6,3) -> 6*5/2 + 3 = 18
Definition at line 70 of file upperUnitaryMatrix.h.
Constructor & Destructor Documentation
corecvs::UpperUnitaryMatrix::UpperUnitaryMatrix (int _size, bool shouldInit = true) [inline]
Definition at line 87 of file upperUnitaryMatrix.h.
References elements, getUpperSizeFor(), and memSize.
                                                          :
        size(_size)
    {
        memSize = getUpperSizeFor(_size);
        elements = new double[memSize];
        if (shouldInit)
        {
            memset(elements, 0, sizeof(double) * memSize);
        }
    };
virtual corecvs::UpperUnitaryMatrix::~UpperUnitaryMatrix () [inline, virtual]
Definition at line 175 of file upperUnitaryMatrix.h.
References elements, and size.
    {
        delete[] elements;
        size = 0;
        elements = NULL;
    }
Member Function Documentation
double corecvs::UpperUnitaryMatrix::a (int row, int column) [inline]
Definition at line 110 of file upperUnitaryMatrix.h.
References ASSERT_TRUE_P, DOTRACE, elements, internalOffset(), and memSize.
Referenced by corecvs::Cholesky::udutDecompose().
    {
        if (row == column)
            return 1.0;
        if (row > column)
            return 0.0;
        int offset = internalOffset(row, column);
        DOTRACE(("R:%d C:%d off:%d\n", row, column, offset));
        ASSERT_TRUE_P(offset < memSize, ("Overflow in Upper Unitary %d >= %d\n", offset, memSize));
        return elements[offset];
    }
double corecvs::UpperUnitaryMatrix::det () [inline]
Definition at line 145 of file upperUnitaryMatrix.h.
    {
        return 1.0;
    }
int corecvs::UpperUnitaryMatrix::getUpperSize () [inline]
Definition at line 82 of file upperUnitaryMatrix.h.
References getUpperSizeFor(), and size.
    {
      return getUpperSizeFor(size);
    }
static int corecvs::UpperUnitaryMatrix::getUpperSizeFor (int size) [inline, static]
Definition at line 77 of file upperUnitaryMatrix.h.
Referenced by getUpperSize(), and UpperUnitaryMatrix().
    {
      return ((size - 1) * size) / 2;
    }
int corecvs::UpperUnitaryMatrix::internalOffset (int row, int column) [inline, private]
Definition at line 183 of file upperUnitaryMatrix.h.
Referenced by a(), and u().
    {
        //return ((2 * size - 1 - row) / 2) * row + column - row - 1;
        return (column * (column - 1)) / 2 + row;
    }
Matrix* corecvs::UpperUnitaryMatrix::toMatrix () const [inline]
Definition at line 122 of file upperUnitaryMatrix.h.
References corecvs::Matrix::a(), elements, and size.
    {
        Matrix *toReturn = new Matrix(size, size, false);
        int count = 0;
        for (int i = 0; i < size; i++)
        {
            for (int j = 0; j < size; j++)
            {
                if (i > j)
                {
                    toReturn->a(i, j) = 0.0;
                } else if (i == j)
                {
                    toReturn->a(i, j) = 1.0;
                } else
                {
                    toReturn->a(i, j) = elements[count++];
                }
            }
        }
        return toReturn;
    }
double& corecvs::UpperUnitaryMatrix::u (int row, int column) [inline]
Definition at line 98 of file upperUnitaryMatrix.h.
References ASSERT_TRUE_P, DOTRACE, elements, internalOffset(), and memSize.
Referenced by corecvs::Cholesky::udutDecompose().
    {
        if (row > column)
        {
            int tmp = row; row = column; column = tmp;
        }
        int offset = internalOffset(row, column);
        DOTRACE(("R:%d C:%d off:%d\n", row, column, offset));
        ASSERT_TRUE_P(offset < memSize, ("Overflow in Upper Unitary %d >= %d\n", offset, memSize));
        return elements[offset];
     }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, const UpperUnitaryMatrix & matrix) [friend]
Definition at line 150 of file upperUnitaryMatrix.h.
    {
        streamsize wasPrecision = out.precision(6);
        int count = 0;
        for (int i = 0; i < matrix.size; i++)
        {
            int j = 0;
            out << "[";
            for (; j < i; j++){
                out.width(9);
                out << 0.0 << " ";
            }
            out.width(9);
            out << 1.0 << " ";
            for (j ++; j < matrix.size; j++)
            {
                out.width(9);
                out << matrix.elements[count++] << " ";
            }
            out << "]\n";
        }
        out.precision(wasPrecision);
        return out;
    }
Member Data Documentation
double* corecvs::UpperUnitaryMatrix::elements
Definition at line 75 of file upperUnitaryMatrix.h.
Referenced by a(), toMatrix(), u(), UpperUnitaryMatrix(), and ~UpperUnitaryMatrix().
int corecvs::UpperUnitaryMatrix::memSize
Definition at line 74 of file upperUnitaryMatrix.h.
Referenced by a(), u(), and UpperUnitaryMatrix().
int corecvs::UpperUnitaryMatrix::size
Definition at line 73 of file upperUnitaryMatrix.h.
Referenced by getUpperSize(), toMatrix(), and ~UpperUnitaryMatrix().
The documentation for this class was generated from the following file:
core/kalman/upperUnitaryMatrix.h