DeepView: corecvs::RansacEstimator Class Reference
corecvs::RansacEstimator Class Reference
#include <ransacEstimator.h>
Public Member Functions
RansacEstimator (unsigned _trySize, unsigned _maxIterations, double _treshold)
Matrix33 getFundamentalRansac1 (CorrespondanceList *list)
Matrix33 getEssentialRansac1 (CorrespondanceList *list)
Matrix33 getFundamentalRansac (vector< Correspondance * > *data)
Matrix33 getEssentialRansac (vector< Correspondance * > *data)
Public Attributes
unsigned trySize
unsigned maxIterations
double treshold
Detailed Description
Definition at line 21 of file ransacEstimator.h.
Constructor & Destructor Documentation
corecvs::RansacEstimator::RansacEstimator (unsigned _trySize, unsigned _maxIterations, double _treshold) [inline]
Definition at line 29 of file ransacEstimator.h.
                               :
        trySize(_trySize),
        maxIterations(_maxIterations),
        treshold(_treshold)
    {};
Member Function Documentation
Matrix33 corecvs::RansacEstimator::getEssentialRansac (vector< Correspondance * > * data)
Definition at line 116 of file ransacEstimator.cpp.
References corecvs::Ransac< SampleType, ModelType >::bestSamples, corecvs::Ransac< SampleType, ModelType >::data, corecvs::Model8Point::fits(), corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_FAILER, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_IS_BASED_ON, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_PASSER, corecvs::Ransac< SampleType, ModelType >::getModelRansac(), corecvs::Ransac< SampleType, ModelType >::inliersPercent, corecvs::Ransac< SampleType, ModelType >::inlierThreshold, corecvs::Ransac< SampleType, ModelType >::iterationsNumber, maxIterations, corecvs::Model8Point::model, treshold, and trySize.
Referenced by getEssentialRansac1().
{
    Ransac<Correspondance, ModelEssential8Point>
        ransac(trySize);
    ransac.data = data;
    ransac.inlierThreshold = treshold;
    ransac.inliersPercent = 1.0;
    ransac.iterationsNumber = maxIterations;
    ModelEssential8Point result = ransac.getModelRansac();
    for (unsigned i = 0; i < data->size(); i++)
    {
        bool fits = result.fits(*(data->operator[](i)), treshold);
        data->operator[](i)->flags |= (fits ? Correspondance::FLAG_PASSER : Correspondance::FLAG_FAILER);
    }
    for (unsigned i = 0; i < ransac.bestSamples.size(); i++)
    {
        ransac.bestSamples[i]->flags  |= Correspondance::FLAG_IS_BASED_ON;
    }
    return result.model;
}
Matrix33 corecvs::RansacEstimator::getEssentialRansac1 (CorrespondanceList * list)
Definition at line 105 of file ransacEstimator.cpp.
References getEssentialRansac().
Referenced by UniversalRectifier::ransacMethod().
{
    vector<Correspondance *> data;
    data.reserve(list->size());
    for(unsigned i = 0; i < list->size(); i++)
        data.push_back(&(list->at(i)));
    return getEssentialRansac(&data);
}
Matrix33 corecvs::RansacEstimator::getFundamentalRansac (vector< Correspondance * > * data)
Definition at line 79 of file ransacEstimator.cpp.
References corecvs::Ransac< SampleType, ModelType >::bestSamples, corecvs::Ransac< SampleType, ModelType >::data, corecvs::Model8Point::fits(), corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_FAILER, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_IS_BASED_ON, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_PASSER, corecvs::Ransac< SampleType, ModelType >::getModelRansac(), corecvs::Ransac< SampleType, ModelType >::inliersPercent, corecvs::Ransac< SampleType, ModelType >::inlierThreshold, corecvs::Ransac< SampleType, ModelType >::iterationsNumber, maxIterations, corecvs::Model8Point::model, treshold, and trySize.
Referenced by getFundamentalRansac1().
{
    Ransac<Correspondance, ModelFundamental8Point>
        ransac(trySize);
    ransac.data = data;
    ransac.inlierThreshold = treshold;
    ransac.inliersPercent = 1.0;
    ransac.iterationsNumber = maxIterations;
    ModelFundamental8Point result = ransac.getModelRansac();
    for (unsigned i = 0; i < data->size(); i++)
    {
        bool fits = result.fits(*(data->operator[](i)), treshold);
        data->operator[](i)->flags |= (fits ? Correspondance::FLAG_PASSER : Correspondance::FLAG_FAILER);
    }
    for (unsigned i = 0; i < ransac.bestSamples.size(); i++)
    {
        ransac.bestSamples[i]->flags  |= Correspondance::FLAG_IS_BASED_ON;
    }
    return result.model;
}
Matrix33 corecvs::RansacEstimator::getFundamentalRansac1 (CorrespondanceList * list)
Definition at line 69 of file ransacEstimator.cpp.
References getFundamentalRansac().
Referenced by UniversalRectifier::ransacMethod().
{
    vector<Correspondance *> data;
    data.reserve(list->size());
    for(unsigned i = 0; i < list->size(); i++)
        data.push_back(&(list->at(i)));
    return getFundamentalRansac(&data);
}
Member Data Documentation
unsigned corecvs::RansacEstimator::maxIterations
Definition at line 25 of file ransacEstimator.h.
Referenced by getEssentialRansac(), and getFundamentalRansac().
double corecvs::RansacEstimator::treshold
Definition at line 26 of file ransacEstimator.h.
Referenced by getEssentialRansac(), and getFundamentalRansac().
unsigned corecvs::RansacEstimator::trySize
Definition at line 24 of file ransacEstimator.h.
Referenced by getEssentialRansac(), and getFundamentalRansac().
The documentation for this class was generated from the following files:
core/rectification/ransacEstimator.h
core/rectification/ransacEstimator.cpp