DeepView: UEyeCaptureInterface::SpinThread Class Reference
UEyeCaptureInterface::SpinThread Class Reference
Public Member Functions
SpinThread (UEyeCaptureInterface *_capInterface)
void run (void)
Public Attributes
UEyeCaptureInterface * capInterface
Detailed Description
Definition at line 58 of file uEyeCapture.h.
Constructor & Destructor Documentation
UEyeCaptureInterface::SpinThread::SpinThread (UEyeCaptureInterface * _capInterface) [inline]
Definition at line 63 of file uEyeCapture.h.
                                                        :
            capInterface(_capInterface)
        {}
Member Function Documentation
void UEyeCaptureInterface::SpinThread::run (void)
Definition at line 416 of file uEyeCapture.cpp.
References BufferDescriptorType::buffer, capInterface, UEyeCaptureInterface::currentLeft, UEyeCaptureInterface::currentRight, UEyeCaptureInterface::FRAME_HARD_SYNC, UEyeCaptureInterface::frameDelay, UEyeCameraDescriptor::getDescriptorByAddress(), BufferDescriptorType::internalTimestamp, UEyeCaptureInterface::lastFrameTime, UEyeCaptureInterface::leftCamera, UEyeCameraDescriptor::mCamera, ImageCaptureInterface::notifyAboutNewFrame(), BufferDescriptorType::pcTimestamp, UEyeCaptureInterface::protectFrame, UEyeCaptureInterface::rightCamera, UEyeCaptureInterface::shouldStopSpinThread, UEyeCaptureInterface::skippedCount, UEyeCaptureInterface::SOFT_SYNC, UEyeCaptureInterface::spinRunning, UEyeCaptureInterface::sync, SYNC_PRINT, frame_data_t::timestamp, UEyeCaptureInterface::triggerSkippedCount, UEyeCaptureInterface::ueyeTrace(), BufferDescriptorType::usecsTimeStamp(), corecvs::PreciseTimer::usecsTo(), corecvs::PreciseTimer::usecsToNow(), and UEyeCameraDescriptor::waitUEyeFrameEvent().
{
    qDebug("new frame thread running");
    while (capInterface->spinRunning.tryLock()) {
        //usleep(20000);
        if (capInterface->sync == SOFT_SYNC || capInterface->sync == FRAME_HARD_SYNC) {
           // printf("Both cameras fire!!!\n");
            ueyeTrace(is_FreezeVideo (capInterface->rightCamera.mCamera, IS_DONT_WAIT));
            ueyeTrace(is_FreezeVideo (capInterface->leftCamera .mCamera, IS_DONT_WAIT));
        }
        int result = IS_SUCCESS;
        while ((result = capInterface->rightCamera.waitUEyeFrameEvent(INFINITE)) != IS_SUCCESS)
        {
            SYNC_PRINT(("WaitFrameEvent failed for right camera\n"));
            ueyeTrace(result);
        }
        //SYNC_PRINT(("Got right frame\n"));
        while ((result = capInterface->leftCamera .waitUEyeFrameEvent(INFINITE)) != IS_SUCCESS)
        {
            SYNC_PRINT(("WaitFrameEvent failed for left camera\n"));
            ueyeTrace(result);
        }
        //SYNC_PRINT(("Got left frame\n"));
        /* If we are here seems like both new cameras produced frames*/
        int bufIDL, bufIDR;
        char *rawBufferLeft  = NULL;
        char *rawBufferRight = NULL;
        HIDS mCameraLeft;
        HIDS mCameraRight;
        mCameraLeft = capInterface->leftCamera.mCamera;
        is_GetActSeqBuf(mCameraLeft, &bufIDL, NULL, &rawBufferLeft);
        is_LockSeqBuf (mCameraLeft, IS_IGNORE_PARAMETER, rawBufferLeft);
        mCameraRight = capInterface->rightCamera.mCamera;
        is_GetActSeqBuf(mCameraRight, &bufIDR, NULL, &rawBufferRight);
        is_LockSeqBuf (mCameraRight, IS_IGNORE_PARAMETER, rawBufferRight);
       // SYNC_PRINT(("We have locked buffers [%d and %d]\n", bufIDL, bufIDR));
        /* Now exchange the buffer that is visible from */
        capInterface->protectFrame.lock();
            UEYEIMAGEINFO imageInfo;
            if (capInterface->currentLeft)
                is_UnlockSeqBuf (mCameraLeft, IS_IGNORE_PARAMETER, (char *)capInterface->currentLeft->buffer);
            is_GetImageInfo (mCameraLeft, bufIDL, &imageInfo, sizeof(UEYEIMAGEINFO));
            capInterface->currentLeft = capInterface->leftCamera.getDescriptorByAddress(rawBufferLeft);
            capInterface->currentLeft->internalTimestamp = imageInfo.u64TimestampDevice;
            capInterface->currentLeft->pcTimestamp = imageInfo.TimestampSystem;
            if (capInterface->currentRight)
                is_UnlockSeqBuf (mCameraRight, IS_IGNORE_PARAMETER, (char *)capInterface->currentRight->buffer);
            is_GetImageInfo (mCameraRight, bufIDR, &imageInfo, sizeof(UEYEIMAGEINFO));
            capInterface->currentRight = capInterface->rightCamera.getDescriptorByAddress(rawBufferRight);
            capInterface->currentRight->internalTimestamp = imageInfo.u64TimestampDevice;
            capInterface->currentRight->pcTimestamp = imageInfo.TimestampSystem;
            capInterface->skippedCount++;
            capInterface->triggerSkippedCount = is_CameraStatus (mCameraRight, IS_TRIGGER_MISSED, IS_GET_STATUS);
        capInterface->protectFrame.unlock();
       /* For statistics */
        if (capInterface->lastFrameTime.usecsTo(PreciseTimer()) != 0)
        {
           capInterface->frameDelay = capInterface->lastFrameTime.usecsToNow();
        }
        capInterface->lastFrameTime = PreciseTimer::currentTime();
        frame_data_t frameData;
        frameData.timestamp = (capInterface->currentLeft->usecsTimeStamp() / 2) + (capInterface->currentRight->usecsTimeStamp() / 2);
        capInterface->notifyAboutNewFrame(frameData);
        capInterface->spinRunning.unlock();
        if (capInterface->shouldStopSpinThread)
        {
            qDebug("Break command received");
            break;
        }
    }
    qDebug("new frame thread finished");
}
Member Data Documentation
UEyeCaptureInterface* UEyeCaptureInterface::SpinThread::capInterface
Definition at line 61 of file uEyeCapture.h.
Referenced by run().
The documentation for this class was generated from the following files:
utils/framesources/uEyeCapture.h
utils/framesources/uEyeCapture.cpp