DeepView: G12Image Class Reference
G12Image Class Reference
#include <g12Image.h>
Public Member Functions
G12Image (G12Buffer *buffer)
G12Image (G12Buffer *buffer, int newH, int newW)
G12Image (G12Buffer *buffer, bool mirror)
virtual ~G12Image ()
Detailed Description
Definition at line 21 of file g12Image.h.
Constructor & Destructor Documentation
G12Image::G12Image (G12Buffer * buffer)
Definition at line 11 of file g12Image.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
                                    : QImage (buffer->w, buffer->h, QImage::Format_RGB32){
    int i,j;
    uint8_t *data = bits();
    int bpl = bytesPerLine();
    //int depth = image.depth;
    for (i = 0; i < buffer->h; i++ )
        for (j = 0; j < buffer->w; j++ )
        {
            uint8_t c = buffer->element(i, j) >> 4;
            uint32_t value = c | (c << 8) | (c << 16) | (0xFF << 24);
            ((uint32_t *)(data + i * bpl))[j] = value;
        }
}
G12Image::G12Image (G12Buffer * buffer, int newH, int newW)
Definition at line 25 of file g12Image.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element().
                                                        : QImage (newW, newH, QImage::Format_RGB32){
    int i,j;
    uint8_t *data = bits();
    int bpl = bytesPerLine();
    //int depth = image.depth;
    for (i = 0; i < newH; i++ )
        for (j = 0; j < newW; j++ )
        {
            uint32_t value;
            if (i < buffer->h && j < buffer->w)
            {
                uint8_t c = buffer->element(i, j) >> 4;
                value = c | (c << 8) | (c << 16) | (0xFF << 24);
            } else
            {
                value = 0xFF000000UL;
            }
            ((uint32_t *)(data + i * bpl))[j] = value;
        }
}
G12Image::G12Image (G12Buffer * buffer, bool mirror)
Definition at line 49 of file g12Image.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
                                                 : QImage (buffer->w, buffer->h, QImage::Format_RGB32){
    int i,j;
    uint8_t *data = bits();
    int bpl = bytesPerLine();
    //int depth = image.depth;
    for (i = 0; i < buffer->h; i++ )
        for (j = 0; j < buffer->w; j++ )
        {
            uint8_t c;
            if (!mirror) {
                c = buffer->element(i, j) >> 4;
            } else {
                c = buffer->element(i, buffer->w - 1 - j  ) >> 4;
            }
            uint32_t value = c | (c << 8) | (c << 16) | (0xFF << 24);
            ((uint32_t *)(data + i * bpl))[j] = value;
        }
}
G12Image::~G12Image () [virtual]
Definition at line 69 of file g12Image.cpp.
                    {
}
The documentation for this class was generated from the following files:
utils/corestructs/g12Image.h
utils/corestructs/g12Image.cpp