DeepView: MainWindow Class Reference
MainWindow Class Reference
#include <mainWindow.h>
Signals
void pauseCalculation ()
void resumeCalculation ()
Public Member Functions
MainWindow (BaseHostDialog *dialog, const QString &source, const MainWindowParameters &params, bool isRgb=false, QWidget *parent=0)
~MainWindow ()
void closeEvent (QCloseEvent *event)
void keyPressEvent (QKeyEvent *event)
Private Slots
void updateCaptureStatus (bool isOn)
void updateSingleStateStatus ()
void updateCalculationStatus (bool isOn)
Private Member Functions
void connectActions ()
void createAdditionalMenu ()
Private Attributes
Ui::MainWindow * mUi
BaseHostDialog * mMainDialog
Detailed Description
Definition at line 40 of file mainWindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (BaseHostDialog * dialog, const QString & source, const MainWindowParameters & params, bool isRgb = false, QWidget * parent = 0) [explicit]
Definition at line 4 of file mainWindow.cpp.
References MainWindowParameters::autoPlay, connectActions(), createAdditionalMenu(), BaseHostDialog::init(), BaseHostDialog::initCapture(), Log::mLogDrains, mMainDialog, mUi, MainWindowParameters::startMini, and BaseHostDialog::windowTitle().
    : QMainWindow(parent)
    , mUi(new Ui::MainWindow)
    , mMainDialog(dialog)
{
    mUi->setupUi(this);
    Log::mLogDrains.push_back(mUi->loggingWidget);
    mMainDialog->init(mUi->widget);
//    mMainDialog->init(mUi->scrollAreaWidgetContents);
    mMainDialog->initCapture(source, isRgb);
    mMainDialog->show();
    setCentralWidget(mMainDialog);
    showMaximized();
    setWindowTitle(mMainDialog->windowTitle());
    if (params.autoPlay)
    {
        QTimer::singleShot(600, mMainDialog, SLOT(play()));
    }
    if (params.startMini)
    {
        QTimer::singleShot(600, mMainDialog, SLOT(showMinimized()));
    }
    connectActions();
    createAdditionalMenu();
    // Hide log by default
    mUi->loggingDockWidget->setVisible(false);
}
MainWindow::~MainWindow ()
Definition at line 40 of file mainWindow.cpp.
References BaseHostDialog::deinit(), mMainDialog, and mUi.
{
    mMainDialog->deinit();
    delete_safe(mUi);
    delete_safe(mMainDialog);
}
Member Function Documentation
void MainWindow::closeEvent (QCloseEvent * event)
Definition at line 82 of file mainWindow.cpp.
{
    Q_UNUSED(event)
    qApp->quit();
}
void MainWindow::connectActions () [private]
Definition at line 47 of file mainWindow.cpp.
References mMainDialog, mUi, pauseCalculation(), resumeCalculation(), updateCalculationStatus(), updateCaptureStatus(), and updateSingleStateStatus().
Referenced by MainWindow().
{
    connect(mUi->actionShowLog,         SIGNAL(triggered(bool)), mUi->loggingDockWidget, SLOT(setVisible(bool)));
    connect(mUi->actionToggleAdvanced,  SIGNAL(triggered(bool)), mMainDialog, SLOT(toggleAdvanced(bool)));
    connect(mUi->action_OpenInput,         SIGNAL(triggered()), mMainDialog, SLOT(showInputSelectorDialog()));
    connect(mUi->actionStatistics,         SIGNAL(triggered()), mMainDialog, SLOT(showStatistics()));
    connect(mUi->actionHistogram,          SIGNAL(triggered()), mMainDialog, SLOT(showHistogram()));
    connect(mUi->action3DHistogram,        SIGNAL(triggered()), mMainDialog, SLOT(show3DHistogram()));
    connect(mUi->actionCameraSettings,     SIGNAL(triggered()), mMainDialog, SLOT(showCaptureSettings()));
    connect(mUi->actionRectify,            SIGNAL(triggered()), mMainDialog, SLOT(showRectificationDialog()));
    connect(mUi->actionAbout,              SIGNAL(triggered()), mMainDialog, SLOT(showAboutDialog()));
    connect(mUi->actionDO,                 SIGNAL(triggered()), mMainDialog, SLOT(doRectify()));
    connect(mUi->actionResetRectification, SIGNAL(triggered()), mMainDialog, SLOT(resetRectification()));
    connect(mUi->actionSaveParameters,     SIGNAL(triggered()), mMainDialog, SLOT(doSaveParams()));
    connect(mUi->actionLoadParameters,     SIGNAL(triggered()), mMainDialog, SLOT(doLoadParams()));
    connect(mUi->actionCorrectDistortion,  SIGNAL(triggered()), mMainDialog, SLOT(showDistortionCorrectorDialog()));
    connect(mUi->actionCameraCalculator,   SIGNAL(triggered()), mMainDialog, SLOT(showCameraCalculatorDialog()));
    connect(mUi->actionAbout_Qt,           SIGNAL(triggered()), qApp, SLOT(aboutQt()));
    connect(mUi->actionStartCapture,       SIGNAL(triggered()), mMainDialog, SLOT(play()));
    connect(mUi->actionNextFrame,          SIGNAL(triggered()), mMainDialog, SLOT(nextFrame()));
    connect(mUi->actionStepMode,           SIGNAL(triggered()), mMainDialog, SLOT(stopCapture()));
    connect(mUi->actionPauseCalculation,   SIGNAL(triggered(bool)), this, SLOT(updateCalculationStatus(bool)));
    connect(mMainDialog, SIGNAL(captureStatusUpdated(bool)), this, SLOT(updateCaptureStatus(bool)));
    connect(mMainDialog, SIGNAL(singleStepStatusUpdated()), this, SLOT(updateSingleStateStatus()));
    connect(mMainDialog, SIGNAL(updatePauseCalculationAction(bool)), mUi->actionPauseCalculation, SLOT(setEnabled(bool)));
    connect(this, SIGNAL(pauseCalculation()),  mMainDialog, SIGNAL(pauseCalculator()));
    connect(this, SIGNAL(resumeCalculation()), mMainDialog, SIGNAL(resumeCalculator()));
}
void MainWindow::createAdditionalMenu () [private]
Definition at line 98 of file mainWindow.cpp.
References BaseHostDialog::additionalMenus(), mMainDialog, and mUi.
Referenced by MainWindow().
{
    QList<QMenu *> menuList = mMainDialog->additionalMenus();
    foreach (QMenu *menu, menuList)
    {
        menuBar()->insertMenu(mUi->menuHelp->menuAction(), menu);
        // create additional toolbar with actions from current menu
        mUi->toolBar->addSeparator();
        mUi->toolBar->addActions(menu->actions());
    }
}
void MainWindow::keyPressEvent (QKeyEvent * event)
Definition at line 88 of file mainWindow.cpp.
{
    if (event->modifiers() == Qt::AltModifier && event->key() == Qt::Key_X)
    {
        close();
    }
    event->ignore();
}
void MainWindow::pauseCalculation () [signal]
Referenced by connectActions(), and updateCalculationStatus().
void MainWindow::resumeCalculation () [signal]
Referenced by connectActions(), and updateCalculationStatus().
void MainWindow::updateCalculationStatus (bool isOn) [private, slot]
Definition at line 123 of file mainWindow.cpp.
References pauseCalculation(), and resumeCalculation().
Referenced by connectActions().
{
    if (isOn)
        emit pauseCalculation();
    else
        emit resumeCalculation();
}
void MainWindow::updateCaptureStatus (bool isOn) [private, slot]
Definition at line 111 of file mainWindow.cpp.
References mUi.
Referenced by connectActions().
{
    mUi->actionStartCapture->setEnabled(isOn);
}
void MainWindow::updateSingleStateStatus () [private, slot]
Definition at line 116 of file mainWindow.cpp.
References mUi.
Referenced by connectActions().
{
    bool isSingleStep = !mUi->actionStepMode->isChecked();
    mUi->actionStepMode->setText(isSingleStep ? "Run" : "Step Mode");
    mUi->actionNextFrame->setEnabled(isSingleStep);
}
Member Data Documentation
BaseHostDialog* MainWindow::mMainDialog [private]
Definition at line 70 of file mainWindow.h.
Referenced by connectActions(), createAdditionalMenu(), MainWindow(), and ~MainWindow().
Ui::MainWindow* MainWindow::mUi [private]
Definition at line 69 of file mainWindow.h.
Referenced by connectActions(), createAdditionalMenu(), MainWindow(), updateCaptureStatus(), updateSingleStateStatus(), and ~MainWindow().
The documentation for this class was generated from the following files:
applications/base/mainWindow.h
applications/base/mainWindow.cpp