DeepView: FilterGraphPresentation Class Reference
FilterGraphPresentation Class Reference
#include <filterGraphPresentation.h>
Classes
class FilterListIdWidgetItem
class FilterListWidgetItem
Public Types
enum FilterTypes {
GAIN_OFFSET_FILTER = 0, BIT_SELECTOR_FILTER, SOBEL_FILTER, CANNY_FILTER,
BACKGROUND_FILTER, OPERATION_FILTER, TXT_FILTER, INPUT_FILTER,
OUTPUT_FILTER
}
Public Slots
void addFilter ()
void drawGraphClicked ()
void serializeClicked ()
void saveAsClicked ()
void nameChanged ()
void graphChangedSlot ()
void zoom (int delta)
void zoomReset ()
void zoomChanged ()
void closeEvent (QCloseEvent *)
Signals
void graphChanged (tinyxml2::XMLDocument *)
void GraphPresentationClosed (const char *)
Public Member Functions
FilterGraphPresentation (FilterPresentationsCollection *fcollection, CompoundBlockPresentation *compoundfilterpresentation=NULL, QWidget *parent=0)
virtual ~FilterGraphPresentation ()
template<typename T , int size>
int GetArrLength (T(&)[size])
FilterBlockPresentation * presentationByBlock (FilterBlock *block)
DiagramItem * diagramItemByPin (Pin *pin)
void drawGraph (void)
void saveGraphToFile (void)
const char * getGraphFileName (void)
void restoreFromGraph ()
void renewCompoundFilters (int _typeid)
void updateGraph ()
FilterGraphPresentation * rootParent ()
Public Attributes
FilterGraph * filterGraph
FilterPresentationsCollection * filterPresentations
Static Public Attributes
static const char * names []
Private Slots
void deleteItem ()
void blockItemSelected (QGraphicsItem *item)
void pinItemSelected (QGraphicsItem *item)
Private Attributes
Ui_FilterGraphPresentationClass ui
QVector
< FilterBlockPresentation * > filters
QWidget * currentWidget
QPushButton * deleteButton
QPushButton * drawGraphButton
QPushButton * serializeButton
QGraphicsView * graphicsView
DiagramScene * scene
QColor myTextColor
QAction * deleteAction
XMLPrinter * stream
tinyxml2::XMLDocument * doc
CompoundFilter * mCompoundFilter
CompoundBlockPresentation * mCompoundBlockPresentation
int mFilterType
Detailed Description
Definition at line 10 of file filterGraphPresentation.h.
Member Enumeration Documentation
enum FilterGraphPresentation::FilterTypes
Enumerator:
GAIN_OFFSET_FILTER
BIT_SELECTOR_FILTER
SOBEL_FILTER
CANNY_FILTER
BACKGROUND_FILTER
OPERATION_FILTER
TXT_FILTER
INPUT_FILTER
OUTPUT_FILTER
Definition at line 21 of file filterGraphPresentation.h.
                    {GAIN_OFFSET_FILTER = 0
                    ,BIT_SELECTOR_FILTER
                    ,SOBEL_FILTER
                    ,CANNY_FILTER
                    ,BACKGROUND_FILTER
                    ,OPERATION_FILTER
                    ,TXT_FILTER
                    ,INPUT_FILTER
                    ,OUTPUT_FILTER
    };
Constructor & Destructor Documentation
FilterGraphPresentation::FilterGraphPresentation (FilterPresentationsCollection * fcollection, CompoundBlockPresentation * compoundfilterpresentation = NULL, QWidget * parent = 0)
Definition at line 4 of file filterGraphPresentation.cpp.
References addFilter(), blockItemSelected(), FilterBlockPresentation::blockName, CompoundBlockPresentation::compoundFilter, corecvs::FiltersCollection::compoundFilters, currentWidget, deleteAction, deleteItem(), corecvs::CompoundFilter::dependsOnMe(), doc, drawGraphClicked(), FilterPresentationsCollection::fCollection, filterGraph, filterPresentations, getGraphFileName(), corecvs::CompoundFilter::getTypeName(), corecvs::CompoundFilter::graph, graphChanged(), graphChangedSlot(), graphicsView, mCompoundBlockPresentation, mCompoundFilter, mFilterType, nameChanged(), pinItemSelected(), saveAsClicked(), scene, serializeClicked(), DiagramScene::setFilterGraph(), stream, corecvs::CompoundFilter::typeId, ui, zoomChanged(), and zoomReset().
    : QWidget(parent),
      filterPresentations(fpcollection),
      mCompoundFilter(NULL),
      mCompoundBlockPresentation(compoundfilterpresentation)
{
    ui.setupUi(this);
    connect(ui.useButton,       SIGNAL(released()), this, SLOT(addFilter()));
    connect(ui.drawGraphButton, SIGNAL(released()), this, SLOT(drawGraphClicked()));
    connect(ui.serializeButton, SIGNAL(released()), this, SLOT(serializeClicked()));
    connect(ui.saveAsButton,    SIGNAL(released()), this, SLOT(saveAsClicked()));
    connect(ui.allFiltersWidget,SIGNAL(itemDoubleClicked(QListWidgetItem*)),
            this,               SLOT(addFilter()));
    connect(ui.nameLineEdit,    SIGNAL(textChanged(QString)), this, SLOT(nameChanged()));
    deleteAction = new QAction(parent);
    deleteAction->setShortcut(QKeySequence(Qt::Key_Delete));
    ui.graphicsView->addAction(deleteAction);
    connect(deleteAction, SIGNAL(triggered()), this, SLOT(deleteItem()));
    currentWidget = NULL;
    stream = new XMLPrinter();
    doc = new tinyxml2::XMLDocument();
    if (mCompoundBlockPresentation) {
        mCompoundFilter = mCompoundBlockPresentation->compoundFilter;
    }
    mFilterType = (mCompoundFilter) ? mCompoundFilter->typeId : -1;
    const char* filename = getGraphFileName();
    if (mCompoundBlockPresentation) {
        setWindowTitle(QString("Filter type: \"")
                      +QString(mCompoundFilter->getTypeName())
                      +QString("\" ")
                      +QString(mCompoundBlockPresentation->blockName)
                      +QString(" ")
                      +QString(filename));
    } else {
        setWindowTitle(QString("Main Graph: ")+QString(filename));
    }
    int len = FiltersCollection::numberOfFilterTypes();
    for (int i = 0; i < len; i++) {
        ui.allFiltersWidget->addItem(new FilterListIdWidgetItem(FiltersCollection::typenames[i]));
    }
    for (unsigned int i = 0; i < filterPresentations->fCollection->compoundFilters.size(); i++)
    {
        bool needRedColor = false;
        string itemName = filterPresentations->fCollection->compoundFilters[i].name;
        if (mCompoundBlockPresentation)
             if ( mCompoundBlockPresentation->compoundFilter->dependsOnMe(i) )
             {
                 itemName = "[ " + itemName + " ]";
                 needRedColor = true;
             }
        ui.allFiltersWidget->addItem(new FilterListIdWidgetItem(itemName.c_str()));
        if (needRedColor)
            ui.allFiltersWidget->item(ui.allFiltersWidget->count()-1)->setForeground(Qt::red);
    }
 /*   QVBoxLayout *layout;
    layout = new QVBoxLayout(ui.widget);
    expSpinBox = new ExponentialSlider(ui.widget);
    expSpinBox->setObjectName(QString::fromUtf8("expSpinBox"));
    expSpinBox->setMinimumSize(QSize(40, 0));
    connect(expSpinBox, SIGNAL(valueChanged(double)), this, SLOT(zoomChanged()));
    layout->addWidget(expSpinBox);*/
    connect(ui.zoomWidget     , SIGNAL(valueChanged(double)), this, SLOT(zoomChanged()));
    connect(ui.resetZoomButton, SIGNAL(released())          , this, SLOT(zoomReset()));
    if (mCompoundFilter == NULL) {
        filterGraph = new FilterGraph(filterPresentations->fCollection, NULL);
    } else {
        filterGraph = mCompoundFilter->graph;
    }
    scene = new DiagramScene(parent);
    scene->setFilterGraph(filterGraph);
    scene->setSceneRect(QRectF(0, 0, 500, 500));
    connect(scene, SIGNAL(blockItemSelected(QGraphicsItem*)),
            this,  SLOT  (blockItemSelected(QGraphicsItem*)));
    connect(scene, SIGNAL(pinItemSelected(QGraphicsItem*)),
            this,  SLOT  (pinItemSelected(QGraphicsItem*)));
    connect(scene, SIGNAL(graphChanged()),
            this,  SLOT  (graphChangedSlot()));
    graphicsView = ui.graphicsView;
    graphicsView->setScene(scene);
   // layout->addWidget(graphicsView);
}
FilterGraphPresentation::~FilterGraphPresentation () [virtual]
Definition at line 258 of file filterGraphPresentation.cpp.
References deleteAction, doc, filterGraph, filterPresentations, filters, scene, and stream.
{
    for (int i = 0; i < filters.size(); i++)
    {
        delete_safe(filters[i]->widget);
        delete_safe(filters[i]);
    }
    filters.clear();
    delete_safe(deleteAction);
    delete_safe(scene);
    delete_safe(filterGraph);
    delete_safe(stream);
    delete_safe(doc);
    delete filterPresentations;
}
Member Function Documentation
void FilterGraphPresentation::addFilter (void) [slot]
Definition at line 199 of file filterGraphPresentation.cpp.
References corecvs::FilterGraph::addBlock(), CompoundBlockPresentation::addInputPin(), corecvs::CompoundFilter::addInputPin(), CompoundBlockPresentation::addOutputPin(), corecvs::CompoundFilter::addOutputPin(), corecvs::FiltersCollection::compoundFilters, corecvs::CompoundFilter::dependsOnMe(), FilterBlockPresentation::draw(), FilterPresentationsCollection::fCollection, filterGraph, filterPresentations, filters, corecvs::FiltersCollection::getBlockFromRow(), corecvs::CompoundFilter::graph, graphChangedSlot(), corecvs::FilterBlock::inputPins, mCompoundBlockPresentation, mCompoundFilter, mFilterType, corecvs::FilterBlock::outputPins, FilterPresentationsCollection::presentationByName(), corecvs::FiltersCollection::recalculateDependencies(), renewCompoundFilters(), corecvs::FilterGraph::renewCompoundFilters(), rootParent(), saveGraphToFile(), scene, corecvs::FilterBlock::sort, corecvs::CompoundFilter::typeId, ui, and corecvs::FilterGraph::ultimateParent().
Referenced by FilterGraphPresentation().
{
    int row = ui.allFiltersWidget->currentRow();
    if (row >= (int)FiltersCollection::numberOfFilterTypes())
       if (mCompoundBlockPresentation)
           if ( mCompoundFilter->dependsOnMe(row - FiltersCollection::numberOfFilterTypes()) )
               return;
    FilterBlock* filter = filterPresentations->fCollection->getBlockFromRow(row);
    if (filter == NULL)
        return;
    filterGraph->addBlock(filter);
    FilterBlockPresentation *presentation = filterPresentations->presentationByName(row, filter, this, scene);
    connect(presentation, SIGNAL(paramsChanged()), this,  SLOT(graphChangedSlot()));
    filters.push_back(presentation);
    if (mCompoundBlockPresentation)
    {
        if (filter->sort == FilterBlock::INPUT_FILTER)
        {   mCompoundFilter->addInputPin(filter->inputPins[0]);
            mCompoundBlockPresentation->addInputPin(filter->inputPins[0]);
        }
        if (filter->sort == FilterBlock::OUTPUT_FILTER)
        {   mCompoundFilter->addOutputPin(filter->outputPins[0]);
            mCompoundBlockPresentation->addOutputPin(filter->outputPins[0]);
        }
        saveGraphToFile();
        mCompoundFilter->graph->ultimateParent()->renewCompoundFilters(mCompoundFilter->typeId, mCompoundFilter);
        rootParent()->renewCompoundFilters(mCompoundFilter->typeId);
        if (filter->sort == FilterBlock::COMPOUND_FILTER)
        {
            filterPresentations->fCollection->compoundFilters[mFilterType].contain.insert( row - FiltersCollection::numberOfFilterTypes() );
            filterPresentations->fCollection->recalculateDependencies();
        }
    }
//-------- graphical part ----------
    int x = 0;
    int y = 0;
    QList<QGraphicsItem*> listItems = scene->items();
    for (int i = 0; i < listItems.size(); i++)
    {   x += listItems.value(i)->pos().x();
        y += listItems.value(i)->pos().y();
    }
    if (listItems.size() > 0)
    {   x = (int)(x / listItems.size());
        y = (int)(y / listItems.size());
    }
    x += 120;
    y += 50;
    presentation->draw(x, y);
    graphChangedSlot();
}
void FilterGraphPresentation::blockItemSelected (QGraphicsItem * item) [private, slot]
Definition at line 325 of file filterGraphPresentation.cpp.
References FilterBlockPresentation::blockName, currentWidget, FilterBlockPresentation::mBlock, mCompoundBlockPresentation, corecvs::FilterBlock::sort, ui, and FilterBlockPresentation::widget.
Referenced by FilterGraphPresentation().
{
    FilterBlockPresentation *presentation =
    dynamic_cast<FilterBlockPresentation *>(item);
    if (currentWidget != NULL)
    {
        ui.gridLayout->removeWidget(currentWidget);
        currentWidget->setParent(NULL);
        currentWidget = NULL;
        ui.nameLineEdit->clear();
    }
    if (presentation != NULL)
    {
        if (presentation->widget != NULL)
        {
            if (!(mCompoundBlockPresentation != NULL &&
                 (presentation->mBlock->sort == FilterBlock::INPUT_FILTER ||
                  presentation->mBlock->sort == FilterBlock::OUTPUT_FILTER)))
            {
                currentWidget = presentation->widget;
                QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Preferred);
                currentWidget->setSizePolicy(sizePolicy);
                ui.verticalLayout->insertWidget(ui.verticalLayout->count()-1,currentWidget);
            }
        }
        ui.nameLineEdit->setText(QString(presentation->blockName));
        this->update();
    }
}
void FilterGraphPresentation::closeEvent (QCloseEvent * event) [slot]
Definition at line 448 of file filterGraphPresentation.cpp.
References CompoundBlockPresentation::child, filterPresentations, corecvs::CompoundFilter::graph, mCompoundBlockPresentation, mCompoundFilter, mFilterType, FilterPresentationsCollection::openedFilters, corecvs::FilterGraph::renewCompoundFilters(), saveGraphToFile(), corecvs::CompoundFilter::typeId, and corecvs::FilterGraph::ultimateParent().
{
    saveGraphToFile();
    if (mCompoundFilter)
    {   mCompoundFilter->graph->ultimateParent()->renewCompoundFilters(mCompoundFilter->typeId, mCompoundFilter);
//        rootParent()->renewCompoundFilters(mCompoundFilter->typeId);
        filterPresentations->openedFilters.erase(mFilterType);
        mCompoundBlockPresentation->child = NULL;
    }
    QWidget::closeEvent(event);
}
void FilterGraphPresentation::deleteItem () [private, slot]
Definition at line 277 of file filterGraphPresentation.cpp.
References corecvs::FilterGraph::breakConnection(), Arrow::endItem(), filterGraph, filters, corecvs::CompoundFilter::graph, graphChangedSlot(), corecvs::FilterBlock::inputPins, FilterBlockPresentation::mBlock, mCompoundBlockPresentation, mCompoundFilter, FilterPinPresentation::mPin, corecvs::FilterBlock::outputPins, DiagramItem::removeArrow(), DiagramItem::removeArrows(), corecvs::FilterGraph::removeBlock(), CompoundBlockPresentation::removeInputPin(), corecvs::CompoundFilter::removeInputPin(), CompoundBlockPresentation::removeOutputPin(), corecvs::CompoundFilter::removeOutputPin(), renewCompoundFilters(), corecvs::FilterGraph::renewCompoundFilters(), rootParent(), saveGraphToFile(), scene, corecvs::FilterBlock::sort, Arrow::startItem(), corecvs::CompoundFilter::typeId, and corecvs::FilterGraph::ultimateParent().
Referenced by FilterGraphPresentation().
{
    bool changeOccurred = (scene->selectedItems().size() > 0);
    foreach (QGraphicsItem *item, scene->selectedItems())
    {   Arrow* arrow = dynamic_cast<Arrow*>(item);
        if (arrow)
        {   FilterPinPresentation* startItem = dynamic_cast<FilterPinPresentation*>(arrow->startItem());
            FilterPinPresentation* endItem = dynamic_cast<FilterPinPresentation*>(arrow->endItem());
            filterGraph->breakConnection(startItem->mPin, endItem->mPin);
            arrow->startItem()->removeArrow(arrow);
            arrow->endItem()->removeArrow(arrow);
        }
        FilterBlockPresentation *presentation = dynamic_cast<FilterBlockPresentation*>(item);
        if (presentation)
        {   foreach (QGraphicsItem *child, presentation->childItems())
            {   DiagramItem *diagramChild = dynamic_cast<DiagramItem*>(child);
                if (diagramChild)  diagramChild->removeArrows();
            }
            filterGraph->removeBlock(presentation->mBlock);
            QVector<FilterBlockPresentation*>::iterator filtersIterator
                     = std::find(filters.begin(), filters.end(), presentation);
            if (filtersIterator != filters.end())  filters.erase(filtersIterator);
            if (mCompoundBlockPresentation)
            {
                if (presentation->mBlock->sort == FilterBlock::INPUT_FILTER)
                {   mCompoundBlockPresentation->removeInputPin(presentation->mBlock->inputPins[0]);
                    mCompoundFilter->removeInputPin(presentation->mBlock->inputPins[0]);
                }
                if (presentation->mBlock->sort == FilterBlock::OUTPUT_FILTER)
                {   mCompoundBlockPresentation->removeOutputPin(presentation->mBlock->outputPins[0]);
                    mCompoundFilter->removeOutputPin(presentation->mBlock->outputPins[0]);
                }
                saveGraphToFile();
                mCompoundFilter->graph->ultimateParent()->renewCompoundFilters(mCompoundFilter->typeId, mCompoundFilter);
                rootParent()->renewCompoundFilters(mCompoundFilter->typeId);
            }
            delete_safe(presentation->mBlock);
        } // if
        scene->removeItem(item);
        delete item;
    } // foreach
    if (changeOccurred)  graphChangedSlot();
} // deleteItem
DiagramItem* FilterGraphPresentation::diagramItemByPin (Pin * pin)
void FilterGraphPresentation::drawGraph (void)
Definition at line 134 of file filterGraphPresentation.cpp.
References corecvs::FilterGraph::blocks, FilterBlockPresentation::draw(), filterGraph, filters, corecvs::FilterBlock::inputPins, FilterBlockPresentation::level, FilterBlockPresentation::mBlock, presentationByBlock(), and corecvs::FilterGraph::topologicSort().
Referenced by drawGraphClicked().
{
    if (!filterGraph->topologicSort())
    {
        cout<<"Can't do filterGraph->topologicSort()"<<endl;
        return;
    }
    int dx = 220;
    int dy = 150;
    int x0 = 120;
    int y0 = 50;
    FilterBlock* block;
    FilterBlockPresentation* presentation;
    //init levels
    for (int i = 0; i < filters.size(); i++) {
        filters[i]->level = 0;
    }
    //fill levels
    for (int i = 0; i < filters.size(); i++)
    {
        presentation = filters[i];
        if (presentation == NULL) continue;
        block = presentation->mBlock;
        if (block == NULL) continue;
        for (unsigned int j = 0; j < block->inputPins.size(); j++)
        {
            if (block->inputPins[j] == NULL) continue;
            if (block->inputPins[j]->takeFrom == NULL)  continue;
            if (block->inputPins[j]->takeFrom->parent == NULL) continue;
            FilterBlockPresentation* parentPresentation = presentationByBlock(block->inputPins[j]->takeFrom->parent);
            if (parentPresentation == NULL) continue;
            int parentLevel = parentPresentation->level;
            if ( (parentLevel+1) > presentation->level )
                presentation->level = parentLevel + 1;
        }
    }
    int* levels = new int[filterGraph->blocks.size()];
    for (unsigned int i = 0; i < filterGraph->blocks.size(); i++)
        levels[i] = 0;
    //for each node of topologic tree
    for (unsigned int i = 0; i < filterGraph->blocks.size(); i++)
    {
        block        = filterGraph->blocks[i];
        if (block == NULL) continue;
        presentation = presentationByBlock(block);
        if (presentation == NULL) continue;
        int level    = presentation->level;
        int x = x0 + dx * levels[level];
        int y = y0 + dy * level;
        presentation->draw(x, y);
        levels[level]++;
    } // for i
} // drawGraph
void FilterGraphPresentation::drawGraphClicked (void) [slot]
Definition at line 384 of file filterGraphPresentation.cpp.
References drawGraph().
Referenced by FilterGraphPresentation().
{
    drawGraph();
}
template<typename T , int size> int FilterGraphPresentation::GetArrLength (T(&) [size]) [inline]
Definition at line 33 of file filterGraphPresentation.h.
{return size;}
const char * FilterGraphPresentation::getGraphFileName (void)
Definition at line 466 of file filterGraphPresentation.cpp.
References corecvs::FiltersCollection::compoundFilters, FilterPresentationsCollection::fCollection, filterPresentations, and mFilterType.
Referenced by FilterGraphPresentation(), and saveGraphToFile().
{
    if (mFilterType == -1)
         return "graph.conf";
    else return filterPresentations->fCollection->compoundFilters[mFilterType].filename.c_str();
}
void FilterGraphPresentation::graphChanged (tinyxml2::XMLDocument *) [signal]
Referenced by FilterGraphPresentation(), and graphChangedSlot().
void FilterGraphPresentation::graphChangedSlot (void) [slot]
Definition at line 108 of file filterGraphPresentation.cpp.
References doc, filterGraph, graphChanged(), and corecvs::FilterGraph::serialize().
Referenced by addFilter(), deleteItem(), FilterGraphPresentation(), BaseHostDialog::initGraphPresentation(), and restoreFromGraph().
{
    printf("FilterGraphPresentation::Child widget changed. Emitting params changed.\n");
//    delete stream;
//    stream = new XMLPrinter();
//    cout << "---------------------------" << endl;
//    filterGraph->serialize(stream);
//    cout << stream->CStr() << endl;
//    cout << "---------------------------" << endl;
//    emit graphChanged(stream->CStr());
    delete doc;
    doc = filterGraph->serialize();
    emit graphChanged(doc);
}
void FilterGraphPresentation::GraphPresentationClosed (const char *) [signal]
void FilterGraphPresentation::nameChanged () [slot]
Definition at line 473 of file filterGraphPresentation.cpp.
References FilterBlockPresentation::blockName, FilterBlockPresentation::drawBlockName(), FilterPinPresentation::drawPinName(), corecvs::Pin::instanceName, FilterBlockPresentation::mBlock, FilterPinPresentation::mPin, FilterPinPresentation::pinName, scene, corecvs::FilterBlock::setInstanceName(), and ui.
Referenced by FilterGraphPresentation().
{
    if (ui.nameLineEdit->text().isEmpty())
        return;
    QList<QGraphicsItem *> items = scene->selectedItems();
    for (int i = 0; i < items.size(); i++)
    {   FilterBlockPresentation *blockItem = dynamic_cast<FilterBlockPresentation*>(items[i]);
        if (blockItem != NULL)
        {   blockItem->blockName = strdup(ui.nameLineEdit->text().toStdString().c_str());
            blockItem->mBlock->setInstanceName(blockItem->blockName);
            blockItem->drawBlockName();
        }
        FilterPinPresentation *pinItem = dynamic_cast<FilterPinPresentation*>(items[i]);
        if (pinItem != NULL)
        {   delete_safe(pinItem->pinName);
            pinItem->pinName = strdup(ui.nameLineEdit->text().toStdString().c_str());
            pinItem->mPin->instanceName = pinItem->pinName;
            pinItem->drawPinName();
        }
    } // for i
} // nameChanged
void FilterGraphPresentation::pinItemSelected (QGraphicsItem * item) [private, slot]
Definition at line 360 of file filterGraphPresentation.cpp.
References currentWidget, FilterPinPresentation::pinName, and ui.
Referenced by FilterGraphPresentation().
{
    FilterPinPresentation *presentation =
    dynamic_cast<FilterPinPresentation *>(item);
    if (!ui.nameLineEdit->text().isEmpty())
    {   if (currentWidget != NULL)
        {
            ui.gridLayout->removeWidget(currentWidget);
            currentWidget->setParent(NULL);
            currentWidget = NULL;
        }
        ui.nameLineEdit->clear();
    }
    CompoundBlockPresentation* compound = dynamic_cast<CompoundBlockPresentation *>(presentation->parentItem());
    ui.nameLineEdit->setReadOnly(compound != NULL);
    if (presentation != NULL)
    {   ui.nameLineEdit->setText(QString(presentation->pinName));
        this->update();
    }
}
FilterBlockPresentation * FilterGraphPresentation::presentationByBlock (FilterBlock * block)
Definition at line 126 of file filterGraphPresentation.cpp.
References filters.
Referenced by drawGraph().
{
    for (int i = 0; i < filters.size(); i++)
       if (block == filters[i]->mBlock)  return filters[i];
    return NULL;
}
void FilterGraphPresentation::renewCompoundFilters (int _typeid)
Definition at line 532 of file filterGraphPresentation.cpp.
References CompoundBlockPresentation::child, CompoundBlockPresentation::compoundFilter, filters, renewCompoundFilters(), corecvs::CompoundFilter::typeId, FilterBlockPresentation::updateBlock(), and updateGraph().
Referenced by addFilter(), deleteItem(), and renewCompoundFilters().
{
//    cout << "renewCompoundFilters" << endl;
    for (int i = 0; i < filters.size(); i++)
    {
        CompoundBlockPresentation* p = dynamic_cast<CompoundBlockPresentation*>(filters[i]);
        if (p == NULL || p->compoundFilter == NULL)
            continue;
        p->updateBlock();
        if (p->child == NULL)
            continue;
        if (p->compoundFilter->typeId == _typeid)
            p->child->updateGraph();
        else
            p->child->renewCompoundFilters(_typeid);
    }
}
void FilterGraphPresentation::restoreFromGraph ()
Definition at line 432 of file filterGraphPresentation.cpp.
References corecvs::FilterGraph::blocks, FilterBlockPresentation::draw(), FilterPresentationsCollection::fCollection, filterGraph, filterPresentations, filters, corecvs::FiltersCollection::getRowByName(), graphChangedSlot(), FilterPresentationsCollection::presentationByName(), scene, FilterParametersControlWidgetBase::setParametersVirtual(), and FilterBlockPresentation::widget.
Referenced by BaseHostDialog::initGraphPresentation(), and DiagramScene::mouseDoubleClickEvent().
{
    for (unsigned int i = 0; i < filterGraph->blocks.size(); i++)
    {   FilterBlockPresentation* presentation = filterPresentations->presentationByName(
                    filterPresentations->fCollection->getRowByName(filterGraph->blocks[i]->getTypeName()),
                    filterGraph->blocks[i],
                    this,
                    scene);
        if (presentation->widget)
            presentation->widget->setParametersVirtual(filterGraph->blocks[i]->getParameters());
        connect(presentation, SIGNAL(paramsChanged()), this,  SLOT(graphChangedSlot()));
        presentation->draw(filterGraph->blocks[i]->x, filterGraph->blocks[i]->y);
        filters.push_back(presentation);
    } // for i
} // restoreFromGraph
FilterGraphPresentation * FilterGraphPresentation::rootParent ()
Definition at line 522 of file filterGraphPresentation.cpp.
References mCompoundBlockPresentation, and CompoundBlockPresentation::parent.
Referenced by addFilter(), and deleteItem().
{
    FilterGraphPresentation* p = this;
    while (p->mCompoundBlockPresentation != NULL)
        p = p->mCompoundBlockPresentation->parent;
    return p;
}
void FilterGraphPresentation::saveAsClicked (void) [slot]
Definition at line 498 of file filterGraphPresentation.cpp.
References corecvs::FiltersCollection::addFilterType(), FilterPresentationsCollection::fCollection, filterGraph, filterPresentations, corecvs::FiltersCollection::saveCompoundFilters(), corecvs::FilterGraph::saveToFile(), and ui.
Referenced by FilterGraphPresentation().
{
    QFileDialog dialog(this);
    QString fileName = dialog.getSaveFileName(this,
                                              tr("Save graph to file"),
                                              "",
                                              tr("Graph configurations *.conf (*.conf)"));
    if (fileName.isEmpty())  return;
    bool ok;
    QString filterName = QInputDialog::getText(this,
                                               tr("Enter filter name"),
                                               tr("New filter name:"), QLineEdit::Normal,
                                               tr("New filter"), &ok);
    if (!ok || filterName.isEmpty())  return;
    filterGraph->saveToFile(fileName.toStdString().c_str());
    filterPresentations->fCollection->addFilterType(filterName.toStdString().c_str(), fileName.toStdString().c_str());
    filterPresentations->fCollection->saveCompoundFilters();
    ui.allFiltersWidget->addItem(new FilterListIdWidgetItem(filterName.toStdString().c_str()));
}
void FilterGraphPresentation::saveGraphToFile (void)
Definition at line 460 of file filterGraphPresentation.cpp.
References filterGraph, getGraphFileName(), and corecvs::FilterGraph::saveToFile().
Referenced by addFilter(), closeEvent(), and deleteItem().
{
    const char* filename = getGraphFileName();
    filterGraph->saveToFile(filename);
}
void FilterGraphPresentation::serializeClicked (void) [slot]
Definition at line 389 of file filterGraphPresentation.cpp.
References tinyxml2::XMLPrinter::CStr(), corecvs::FilterGraph::deserialize(), FilterPresentationsCollection::fCollection, filterGraph, filterPresentations, corecvs::FilterGraph::serialize(), and stream.
Referenced by FilterGraphPresentation().
{
    cout << "serializeClicked" << endl;
    XMLPrinter* stream = new XMLPrinter();
    filterGraph->serialize(stream);
    cout << "---------------------------" << endl;
    cout << "Initial graph serialization" << endl;
    cout << "---------------------------" << endl;
    cout << stream->CStr() << endl;
    FilterGraph* newFilterGraph = new FilterGraph(filterPresentations->fCollection, NULL);
    newFilterGraph->deserialize(stream->CStr());
    XMLPrinter* stream1 = new XMLPrinter();
    newFilterGraph->serialize(stream1);
    cout << "-----------------------------" << endl;
    cout << "Secondary graph serialization" << endl;
    cout << "-----------------------------" << endl;
    cout << stream1->CStr() << endl;
}
void FilterGraphPresentation::updateGraph ()
Definition at line 554 of file filterGraphPresentation.cpp.
References filters, and FilterBlockPresentation::updateBlock().
Referenced by renewCompoundFilters().
{
//    cout << "updateGraph()" << endl;
    for (int i = 0; i < filters.size(); i++)
    {
        FilterBlockPresentation* presentation = filters[i];
        presentation->updateBlock();
    }
} // updateGraph
void FilterGraphPresentation::zoom (int delta) [slot]
Definition at line 412 of file filterGraphPresentation.cpp.
{
}
void FilterGraphPresentation::zoomChanged () [slot]
Definition at line 423 of file filterGraphPresentation.cpp.
References graphicsView, and ui.
Referenced by FilterGraphPresentation(), and zoomReset().
{
    double newScale = ui.zoomWidget->value();
    QMatrix oldMatrix = graphicsView->matrix();
    graphicsView->resetMatrix();
    graphicsView->translate(oldMatrix.dx(), oldMatrix.dy());
    graphicsView->scale(newScale, newScale);
}
void FilterGraphPresentation::zoomReset () [slot]
Definition at line 417 of file filterGraphPresentation.cpp.
References ui, and zoomChanged().
Referenced by FilterGraphPresentation().
{
    ui.zoomWidget->setValue(1.0);
    zoomChanged();
}
Member Data Documentation
QWidget* FilterGraphPresentation::currentWidget [private]
Definition at line 111 of file filterGraphPresentation.h.
Referenced by blockItemSelected(), FilterGraphPresentation(), and pinItemSelected().
QAction* FilterGraphPresentation::deleteAction [private]
Definition at line 122 of file filterGraphPresentation.h.
Referenced by FilterGraphPresentation(), and ~FilterGraphPresentation().
QPushButton* FilterGraphPresentation::deleteButton [private]
Definition at line 113 of file filterGraphPresentation.h.
tinyxml2::XMLDocument* FilterGraphPresentation::doc [private]
Definition at line 125 of file filterGraphPresentation.h.
Referenced by FilterGraphPresentation(), graphChangedSlot(), and ~FilterGraphPresentation().
QPushButton* FilterGraphPresentation::drawGraphButton [private]
Definition at line 114 of file filterGraphPresentation.h.
FilterGraph* FilterGraphPresentation::filterGraph
Definition at line 103 of file filterGraphPresentation.h.
Referenced by addFilter(), deleteItem(), drawGraph(), FilterGraphPresentation(), graphChangedSlot(), BaseHostDialog::initGraphPresentation(), restoreFromGraph(), saveAsClicked(), saveGraphToFile(), serializeClicked(), and ~FilterGraphPresentation().
FilterPresentationsCollection* FilterGraphPresentation::filterPresentations
Definition at line 104 of file filterGraphPresentation.h.
Referenced by addFilter(), closeEvent(), FilterGraphPresentation(), getGraphFileName(), DiagramScene::mouseDoubleClickEvent(), restoreFromGraph(), saveAsClicked(), serializeClicked(), and ~FilterGraphPresentation().
QVector<FilterBlockPresentation*> FilterGraphPresentation::filters [private]
Definition at line 109 of file filterGraphPresentation.h.
Referenced by addFilter(), deleteItem(), drawGraph(), presentationByBlock(), renewCompoundFilters(), restoreFromGraph(), updateGraph(), and ~FilterGraphPresentation().
QGraphicsView* FilterGraphPresentation::graphicsView [private]
Definition at line 117 of file filterGraphPresentation.h.
Referenced by FilterGraphPresentation(), and zoomChanged().
CompoundBlockPresentation* FilterGraphPresentation::mCompoundBlockPresentation [private]
Definition at line 128 of file filterGraphPresentation.h.
Referenced by addFilter(), blockItemSelected(), closeEvent(), deleteItem(), FilterGraphPresentation(), and rootParent().
CompoundFilter* FilterGraphPresentation::mCompoundFilter [private]
Definition at line 127 of file filterGraphPresentation.h.
Referenced by addFilter(), closeEvent(), deleteItem(), and FilterGraphPresentation().
int FilterGraphPresentation::mFilterType [private]
Definition at line 129 of file filterGraphPresentation.h.
Referenced by addFilter(), closeEvent(), FilterGraphPresentation(), and getGraphFileName().
QColor FilterGraphPresentation::myTextColor [private]
Definition at line 120 of file filterGraphPresentation.h.
const char* FilterGraphPresentation::names[] [static]
Definition at line 35 of file filterGraphPresentation.h.
DiagramScene* FilterGraphPresentation::scene [private]
Definition at line 118 of file filterGraphPresentation.h.
Referenced by addFilter(), deleteItem(), FilterGraphPresentation(), nameChanged(), restoreFromGraph(), and ~FilterGraphPresentation().
QPushButton* FilterGraphPresentation::serializeButton [private]
Definition at line 115 of file filterGraphPresentation.h.
XMLPrinter* FilterGraphPresentation::stream [private]
Definition at line 124 of file filterGraphPresentation.h.
Referenced by FilterGraphPresentation(), serializeClicked(), and ~FilterGraphPresentation().
Ui_FilterGraphPresentationClass FilterGraphPresentation::ui [private]
Definition at line 107 of file filterGraphPresentation.h.
Referenced by addFilter(), blockItemSelected(), FilterGraphPresentation(), nameChanged(), pinItemSelected(), saveAsClicked(), zoomChanged(), and zoomReset().
The documentation for this class was generated from the following files:
utils/filters/graph/filterGraphPresentation.h
utils/filters/graph/filterGraphPresentation.cpp