DeepView: tinyxml2::MemPoolT< SIZE > Class Template Reference
tinyxml2::MemPoolT< SIZE > Class Template Reference
#include <tinyxml2.h>
Classes
struct Block
union Chunk
Public Types
enum { SIZECOUNT = 1024/SIZE }
Public Member Functions
MemPoolT ()
~MemPoolT ()
virtual int ItemSize () const
int CurrentAllocs () const
virtual void * Alloc ()
virtual void Free (void *mem)
void Trace (const char *name)
void SetTracked ()
int Untracked () const
Private Attributes
DynArray< Block *, 10 > _blockPtrs
Chunk * _root
int _currentAllocs
int _nAllocs
int _maxAllocs
int _nUntracked
Detailed Description
template<int SIZE>
class tinyxml2::MemPoolT< SIZE >
Definition at line 296 of file tinyxml2.h.
Member Enumeration Documentation
template<int SIZE> anonymous enum
Enumerator:
SIZECOUNT
Definition at line 363 of file tinyxml2.h.
{ SIZECOUNT = 1024/SIZE }; // Some compilers do not accept to use COUNT in private part if COUNT is private
Constructor & Destructor Documentation
template<int SIZE> tinyxml2::MemPoolT< SIZE >::MemPoolT () [inline]
Definition at line 300 of file tinyxml2.h.
: _root(0), _currentAllocs(0), _nAllocs(0), _maxAllocs(0), _nUntracked(0)   {}
template<int SIZE> tinyxml2::MemPoolT< SIZE >::~MemPoolT () [inline]
Definition at line 301 of file tinyxml2.h.
                {
        // Delete the blocks.
        for( int i=0; i<_blockPtrs.Size(); ++i ) {
            delete _blockPtrs[i];
        }
    }
Member Function Documentation
template<int SIZE> virtual void* tinyxml2::MemPoolT< SIZE >::Alloc () [inline, virtual]
Implements tinyxml2::MemPool.
Definition at line 315 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLDocument::NewUnknown(), and tinyxml2::XMLElement::ParseAttributes().
{
        if ( !_root ) {
            // Need a new block.
            Block* block = new Block();
            _blockPtrs.Push( block );
            for( int i=0; i<SIZECOUNT-1; ++i ) {
                block->chunk[i].next = &block->chunk[i+1];
            }
            block->chunk[SIZECOUNT-1].next = 0;
            _root = block->chunk;
        }
        void* result = _root;
        _root = _root->next;
        ++_currentAllocs;
        if ( _currentAllocs > _maxAllocs ) {
            _maxAllocs = _currentAllocs;
        }
        _nAllocs++;
        _nUntracked++;
        return result;
    }
template<int SIZE> int tinyxml2::MemPoolT< SIZE >::CurrentAllocs () const [inline]
Definition at line 311 of file tinyxml2.h.
Referenced by tinyxml2::XMLDocument::~XMLDocument().
{
        return _currentAllocs;
    }
template<int SIZE> virtual void tinyxml2::MemPoolT< SIZE >::Free (void * mem) [inline, virtual]
Implements tinyxml2::MemPool.
Definition at line 338 of file tinyxml2.h.
{
        if ( !mem ) {
            return;
        }
        --_currentAllocs;
        Chunk* chunk = (Chunk*)mem;
#ifdef DEBUG
        memset( chunk, 0xfe, sizeof(Chunk) );
#endif
        chunk->next = _root;
        _root = chunk;
    }
template<int SIZE> virtual int tinyxml2::MemPoolT< SIZE >::ItemSize () const [inline, virtual]
Implements tinyxml2::MemPool.
Definition at line 308 of file tinyxml2.h.
{
        return SIZE;
    }
template<int SIZE> void tinyxml2::MemPoolT< SIZE >::SetTracked () [inline, virtual]
Implements tinyxml2::MemPool.
Definition at line 355 of file tinyxml2.h.
                      {
        _nUntracked--;
    }
template<int SIZE> void tinyxml2::MemPoolT< SIZE >::Trace (const char * name) [inline]
Definition at line 350 of file tinyxml2.h.
{
        printf( "Mempool %s watermark=%d [%dk] current=%d size=%d nAlloc=%d blocks=%d\n",
                name, _maxAllocs, _maxAllocs*SIZE/1024, _currentAllocs, SIZE, _nAllocs, _blockPtrs.Size() );
    }
template<int SIZE> int tinyxml2::MemPoolT< SIZE >::Untracked () const [inline]
Definition at line 359 of file tinyxml2.h.
Referenced by tinyxml2::XMLDocument::~XMLDocument().
{
        return _nUntracked;
    }
Member Data Documentation
template<int SIZE> DynArray< Block*, 10 > tinyxml2::MemPoolT< SIZE >::_blockPtrs [private]
Definition at line 373 of file tinyxml2.h.
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::~MemPoolT().
template<int SIZE> int tinyxml2::MemPoolT< SIZE >::_currentAllocs [private]
Definition at line 376 of file tinyxml2.h.
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::CurrentAllocs(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Free(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace().
template<int SIZE> int tinyxml2::MemPoolT< SIZE >::_maxAllocs [private]
Definition at line 378 of file tinyxml2.h.
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace().
template<int SIZE> int tinyxml2::MemPoolT< SIZE >::_nAllocs [private]
Definition at line 377 of file tinyxml2.h.
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace().
template<int SIZE> int tinyxml2::MemPoolT< SIZE >::_nUntracked [private]
Definition at line 379 of file tinyxml2.h.
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::SetTracked(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Untracked().
template<int SIZE> Chunk* tinyxml2::MemPoolT< SIZE >::_root [private]
Definition at line 374 of file tinyxml2.h.
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Free().
The documentation for this class was generated from the following file:
core/tinyxml/tinyxml2.h