DeepView: UniversalRectifier Class Reference
UniversalRectifier Class Reference
#include <universalRectifier.h>
Public Member Functions
UniversalRectifier (RectifyParameters *_params)
void recalculate (void)
virtual ~UniversalRectifier ()
Public Attributes
RectifyParameters params
CorrespondanceList * inputList
The input list.
DerivedCorrespondanceList * list
This is a local copy of the input that we will alter with KLT, or any other improvement algorithm.
DerivedCorrespondanceList * postKlt
This is a local copy of the input that we will alter with KLT, or any other improvement algorithm.
DerivedCorrespondanceList * filteredList
This is a local copy of the input that we will hold the filtered by length values.
DerivedCorrespondanceList * normalList
This is a local copy of the input that we will hold the filtered by length values.
vector< Correspondance * > * data
Data in the format the estimators understand.
G12Buffer * left
This is used for KLT only and should be brought out of the class TODO: Move this out.
G12Buffer * right
Vector3dd direction
Z direction for rectification.
RectificationResult result
Vector3dd E1
Vector3dd E2
QImage * zGraph
QImage * topView
QString status
int code
Private Member Functions
void filter (void)
void ransacMethod (double scale)
void iterativeMethod (void)
void manualMethod (void)
void getZ (void)
void decomposeEssential (void)
Detailed Description
Definition at line 25 of file universalRectifier.h.
Constructor & Destructor Documentation
UniversalRectifier::UniversalRectifier (RectifyParameters * _params) [inline]
Definition at line 98 of file universalRectifier.h.
                                                  :
        params(*_params),
        inputList(NULL),
        list(NULL),
        postKlt(NULL),
        filteredList(NULL),
        normalList(NULL),
        data(NULL),
        left(NULL),
        right(NULL),
        zGraph(NULL),
        topView(NULL),
        code(0)
    {};
UniversalRectifier::~UniversalRectifier () [virtual]
Definition at line 491 of file universalRectifier.cpp.
References data, filteredList, list, normalList, and postKlt.
{
    delete_safe(data);
    delete_safe(list);
    delete_safe(filteredList);
    delete_safe(postKlt);
    delete_safe(normalList);
}
Member Function Documentation
void UniversalRectifier::decomposeEssential (void) [private]
Definition at line 188 of file universalRectifier.cpp.
References corecvs::EssentialMatrix::decompose(), corecvs::RectificationResult::decomposition, corecvs::RectificationResult::F, corecvs::EssentialDecomposition::getScaler(), normalList, and result.
Referenced by recalculate().
{
    EssentialDecomposition decomposition[4];
    double cost[4];
    cout << "=============================================================" << endl;
    EssentialMatrix(result.F).decompose(decomposition);
    int selected = 0;
    for (selected = 0; selected < 4; selected++)
    {
         cout << "Decomposition " << selected << endl << decomposition[selected] << endl;
        double d1;
        double d2;
        double err;
        cost[selected] = 0.0;
        EssentialDecomposition *dec = &(decomposition[selected]);
        for (unsigned i = 0; i < normalList->size(); i++)
        {
            dec->getScaler(normalList->at(i), d1, d2, err);
            if (d1 > 0.0 && d2 > 0.0)
                cost[selected]++;
        }
        cout << "decomposition cost:" << cost[selected] << endl;
    }
    double maxCost = 0.0;
    int finalSelection = 0;
    for (selected = 0; selected < 4; selected++)
    {
        if (cost[selected] > maxCost)
        {
            maxCost = cost[selected];
            finalSelection = selected;
        }
    }
    cout << endl;
    result.decomposition = decomposition[finalSelection];
    cout << "Chosen decomposition" << endl << result.decomposition << endl;
}
void UniversalRectifier::filter (void) [private]
void UniversalRectifier::getZ (void) [private]
Definition at line 127 of file universalRectifier.cpp.
References RectifyParameters::autoZ(), direction, corecvs::RectificationResult::F, corecvs::CorrespondanceList::getSize(), inputList, params, corecvs::VectorOperationsBase< RealType, ElementType >::println(), result, RectifyParameters::zdirX(), RectifyParameters::zdirY(), RectifyParameters::zdirZ(), and zGraph.
Referenced by recalculate().
{
    if (!params.autoZ())
    {
        direction = Vector3dd(params.zdirX(), params.zdirY(), params.zdirZ());
        return;
    }
    printf("Autoguessing best Z\n");
    const unsigned GRANULARITY = 800;
    double distL[GRANULARITY];
    double distR[GRANULARITY];
    double min =  numeric_limits<double>::max();
    double max = -numeric_limits<double>::max();
    double minsum = numeric_limits<double>::max();
    double minindex  = 0;
    direction =  StereoAligner::getBestZ(result.F, inputList->getSize(), GRANULARITY, distL, distR);
    for (unsigned i = 0; i < GRANULARITY; i++)
    {
        if (min > distL[i])  min = distL[i];
        if (min > distR[i])  min = distR[i];
        if (max < distL[i])  max = distL[i];
        if (max < distR[i])  max = distR[i];
        if (distL[i] + distR[i] <  minsum)
        {
            minsum = distL[i] + distR[i];
            minindex = i;
        }
    }
    int graphH = 500;
    zGraph = new QImage(GRANULARITY, graphH,  QImage::Format_RGB32);
    zGraph->fill(0);
    {
        QPainter painter(zGraph);
        max = min + 10000;
        for (unsigned i = 0; i < GRANULARITY; i++)
        {
            int y;
            painter.setPen(QColor(255,255,0));
            // TODO: Use LERP helpers here
            y = (distL[i] - min) / (max - min) * graphH;
            painter.drawPoint(i, graphH - y - 1);
            painter.setPen(QColor(255,0,255));
            y = (distR[i] - min) / (max - min) * graphH;
            painter.drawPoint(i, graphH - y - 1);
        }
        painter.setPen(QColor(0,255,0));
        painter.drawLine(minindex,0,minindex,graphH - 1);
    }
    printf("Guessed direction:");
    direction.println();
}
void UniversalRectifier::iterativeMethod (void) [private]
Definition at line 68 of file universalRectifier.cpp.
References data, corecvs::RGB24Buffer::drawLineSimple(), corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, corecvs::RectificationResult::F, filteredList, RectifyParameters::iterativeFactorSigma(), RectifyParameters::iterativeInitialSigma(), RectifyParameters::iterativeIterations(), RectifyParameters::iterativeMethod(), params, corecvs::Matrix33::print(), RectifyParameters::priorFocal(), result, right, corecvs::BMPLoader::save(), corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start, and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::value.
Referenced by recalculate().
{
    EssentialEstimator::OptimisationMethod method = EssentialEstimator::METHOD_DEFAULT;
    switch (params.iterativeMethod())
    {
        case 0: method = EssentialEstimator::METHOD_SVD_LSE;          break;
        case 1: method = EssentialEstimator::METHOD_GRAD_DESC;        break;
        case 2: method = EssentialEstimator::METHOD_MARQ_LEV;         break;
        case 3: method = EssentialEstimator::METHOD_CLASSIC_KALMAN;   break;
        case 4: method = EssentialEstimator::METHOD_ITERATIVE_KALMAN; break;
        default: break;
    }
    // itertive essential estimation
    IterativeEstimator iterativeEstimator(
          params.iterativeIterations()
        , params.iterativeInitialSigma() / params.priorFocal()
        , params.iterativeFactorSigma()
        , method
    );
    result.F = iterativeEstimator.getEssential(*data);
    printf("Essential:\n");
    result.F.print();
    /* Move this somewhere */
    RGB24Buffer *buffer = new RGB24Buffer(right);
    for (unsigned i = 0 ; i < data->size(); i++)
    {
        Correspondance *corr    = data->at(i);
        Correspondance *corrPos = &(filteredList->at(i));
        double value = corr->value / (double)params.iterativeIterations();
        buffer->drawLineSimple(
            corrPos->start.x(),
            corrPos->start.y(),
            corrPos->end.x(),
            corrPos->end.y(),
            RGBColor::rainbow(value)
        );
    }
    BMPLoader().save("iterations.bmp", buffer);
    delete_safe(buffer);
}
void UniversalRectifier::manualMethod (void) [private]
Definition at line 115 of file universalRectifier.cpp.
References direction, corecvs::RectificationResult::F, RectifyParameters::manualPitch(), RectifyParameters::manualRoll(), RectifyParameters::manualX(), RectifyParameters::manualY(), RectifyParameters::manualYaw(), RectifyParameters::manualZ(), corecvs::VectorOperationsBase< RealType, ElementType >::normalise(), params, corecvs::Matrix33::print(), and result.
Referenced by recalculate().
{
    CameraAngles euler(params.manualPitch(), params.manualYaw(), params.manualRoll());
    Matrix33 R = euler.toMatrix();
    Vector3dd direction(params.manualX(), params.manualY(), params.manualZ());
    direction.normalise();
    result.F = EssentialMatrix::compose(R, direction);
    printf("Essential:\n");
    result.F.print();
}
void UniversalRectifier::ransacMethod (double scale) [private]
Definition at line 51 of file universalRectifier.cpp.
References RectifyParameters::computeEssential(), corecvs::RectificationResult::F, corecvs::RansacEstimator::getEssentialRansac1(), corecvs::RansacEstimator::getFundamentalRansac1(), corecvs::iterations, normalList, params, RectifyParameters::ransacIterations(), RectifyParameters::ransacTestSize(), RectifyParameters::ransacThreshold(), and result.
Referenced by recalculate().
{
    int trySize         = params.ransacTestSize();
    int iterations      = params.ransacIterations();
    double threshold    = params.ransacThreshold();
    if (params.computeEssential())
    {
        RansacEstimator ransacEstimator(trySize, iterations, threshold);
        result.F = ransacEstimator.getEssentialRansac1(normalList);
        return;
    }
    RansacEstimator ransacEstimator(trySize, iterations, threshold * scale);
    result.F = ransacEstimator.getFundamentalRansac1(normalList);
}
void UniversalRectifier::recalculate (void)
Clear the flags
Definition at line 232 of file universalRectifier.cpp.
References RectifyParameters::autoShift(), corecvs::RectificationResult::baseline, RectifyParameters::baselineLength(), code, RectifyParameters::computeEssential(), data, decomposeEssential(), corecvs::RectificationResult::decomposition, direction, E1, E2, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, RectifyParameters::estimationMethod(), corecvs::RectificationResult::F, filteredList, RectifyParameters::filterMinimumLength(), corecvs::EssentialEstimator::CostFunction7to1::getCost(), corecvs::CameraIntrinsics::getInvKMatrix33(), corecvs::CorrespondanceList::getMeanDifference(), corecvs::CorrespondanceList::getNormalizingTransform(), corecvs::EssentialDecomposition::getScaler(), corecvs::CorrespondanceList::getSize(), getZ(), RectifyParameters::guessShiftThreshold(), corecvs::CorrespondanceList::h, inputList, iterativeMethod(), left, corecvs::RectificationResult::leftCamera, corecvs::RectificationResult::leftTransform, list, corecvs::CorrespondanceList::makePrecise(), manualMethod(), RectifyParameters::normalise(), normalList, corecvs::EssentialMatrix::nullspaces(), params, postKlt, RectifyParameters::preShift(), corecvs::Matrix33::print(), RectifyParameters::priorFocal(), RectifyParameters::priorFocal2(), corecvs::DerivedCorrespondanceList::propagateData(), corecvs::radToDeg(), ransacMethod(), corecvs::CorrespondanceList::resetFlags(), result, right, corecvs::RectificationResult::rightCamera, corecvs::RectificationResult::rightTransform, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start, status, corecvs::DerivedCorrespondanceList::toArrayOfPointers(), topView, corecvs::CorrespondanceList::transform(), corecvs::Matrix33::transposed(), RectifyParameters::useKLT(), corecvs::CorrespondanceList::w, corecvs::Vector2d< ElementType >::x(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector2d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
    //emit matchNeeded();
    if (inputList == NULL) {
        code = 1;
        status = "Could not rectificate. No input matches.";
        return;
    }
    if (inputList->size() < 5)
    {
        code = 3;
        status = "Too few matches at input";
        return;
    }
    list = new DerivedCorrespondanceList(inputList);
    /**
     * Clear the flags
     **/
    inputList->resetFlags();
    list->resetFlags();
    // TODO: Clean this up
    bool normalize     = params.normalise() && (params.estimationMethod() == 0);
    bool useKLT        = params.useKLT();
    double userShift   = params.preShift();
    bool useAutoShift  = params.autoShift();
    bool essntialOnly  = params.computeEssential();
    double focalRight  = params.priorFocal();
    double focalLeft   = params.priorFocal2();
    /* First prepare the common output */
    CameraIntrinsics cameraLeft (inputList->getSize(), inputList->getSize() / 2.0, focalLeft , 1.0);
    CameraIntrinsics cameraRight(inputList->getSize(), inputList->getSize() / 2.0, focalRight, 1.0);
#if 0
    PrinterVisitor visitor;
    camera.accept<PrinterVisitor>(visitor);
    qDebug("Setting focal to %lf and fov to %lfdeg, buffer [%lfx%lf]", focal, radToDeg(camera.getHFov()), inputList->getSize().x(), inputList->getSize().y() );
#endif
    result.leftCamera  = cameraLeft;
    result.rightCamera = cameraRight;
    result.baseline = params.baselineLength();
    /* Then comes KLT block */
    if (useKLT)
    {
        if (left == NULL || right == NULL) {
            code = 2;
            status = "Could not use KLT no gray value provided";
            return;
        }
        list->makePrecise(right, left);
    }
    RemoveFilteredPredicate kltFiltered;
    postKlt = new DerivedCorrespondanceList(
            list,
            kltFiltered,
            (int)Correspondance::FLAG_FILTERED_KLT);
    /* Then length filtering */
    LengthFilterPredicate lenFilter(params.filterMinimumLength());
    filteredList = new DerivedCorrespondanceList(
            postKlt,
            lenFilter,
            (int)Correspondance::FLAG_FILTERED_SHORT);
    /* Filtering finished we can select correspondences that are left and form input data */
    cout << "Input " << list->size() << " correspondences" << endl;
    cout << "After Klt Filtering " << postKlt->size()      << " correspondences" << endl;
    cout << "After Len Filtering " << filteredList->size() << " correspondences" << endl;
    normalList = new DerivedCorrespondanceList(filteredList);
    data = normalList->toArrayOfPointers();
    /* In case of essential estimation data should be transformed to the view of normalized camera */
    /* In case of fundamental normalizing transform is used for math optimization */
    Matrix33 rightNormalizer(1.0);
    Matrix33 leftNormalizer (1.0);
    double scale = 1.0;
    if (essntialOnly)
    {
        rightNormalizer = result.rightCamera.getInvKMatrix33();
        leftNormalizer  = result.leftCamera .getInvKMatrix33();
    }
    if (normalize) {
        normalList->getNormalizingTransform(rightNormalizer, leftNormalizer, &scale);
    }
    if (normalize || essntialOnly) {
        normalList->transform(rightNormalizer, leftNormalizer);
    }
    qDebug("Normalized mean x: %lf\n", normalList->getMeanDifference().x());
    switch (params.estimationMethod())
    {
        case 0:
            srand(0x5EED);
            ransacMethod(scale);
            break;
        case 1:
            iterativeMethod();
            break;
        case 2:
        default:
            manualMethod();
    }
    decomposeEssential();
    /* Return back to original coordinates*/
    if (normalize || essntialOnly) {
        result.F = rightNormalizer.transposed() * result.F * leftNormalizer;
    }
    printf("Global Fundamental Matrix:\n");
    result.F.print();
    printf("Global Fundamental Matrix cost:");
    vector<Correspondance *> inputListPtr;
    for (unsigned i = 0; i < inputList->size(); i++) {
        inputListPtr.push_back(&(inputList->at(i)));
    }
    EssentialEstimator::CostFunction7to1 cost(&inputListPtr);
    cout << "Error:" << cost.getCost(result.F) << endl;
    cout << "Sq per point:" << (cost.getCost(result.F) / inputListPtr.size()) << endl;
    cout << "Error per point:" << sqrt(cost.getCost(result.F) / inputListPtr.size()) << "px" << endl;
    /* Find epipoles as the debug result */
    EssentialMatrix(result.F).nullspaces(&E1, &E2);
    /* Find a transformation that aligns the rows */
    getZ();
    StereoAligner::getAlignmentTransformation(
            result.F,
            &(result.rightTransform),
            &(result.leftTransform),
            direction);
    cout << "Sanity check" << endl;
    EssentialMatrix Ix;
    cout << (result.rightTransform.transposed() * Ix * result.leftTransform) / result.F << endl;
    /* Adapt the transformation to make a center of the image a fixed point */
    Vector2dd center = inputList->getSize() / 2.0;
    StereoAligner::getLateralCorrectionFixPoint(&(result.rightTransform), &(result.leftTransform), center);
    /* Shift images for best overlapping */
    if (useAutoShift)
    {
        StereoAligner::getLateralCorrection(&(result.rightTransform), &(result.leftTransform), postKlt, params.guessShiftThreshold());
    } else {
        result.rightTransform = Matrix33::ShiftProj( userShift / 2.0, 0.0) * result.rightTransform;
        result.leftTransform  = Matrix33::ShiftProj(-userShift / 2.0, 0.0) * result.leftTransform;
    }
    /* One more cost computation */
    vector<Correspondance>   alignedList;
    vector<Correspondance *> alignedPtrList;
    for (unsigned i = 0; i < inputList->size(); i++)
    {
        Correspondance input = inputList->at(i);
        Correspondance output;
        output.start = result.rightTransform * input.start;
        output.end   = result.leftTransform  * input.end;
        alignedList.push_back(output);
    }
    for (unsigned i = 0; i < inputList->size(); i++)
    {
        alignedPtrList.push_back(&(alignedList[i]));
    }
    EssentialEstimator::CostFunction7to1 costAligned(&alignedPtrList);
    cout << "Error:" << costAligned.getCost(Ix) << endl;
    cout << "Sq per point:" << (costAligned.getCost(Ix) / alignedPtrList.size()) << endl;
    cout << "Error per point:" << sqrt(costAligned.getCost(Ix) / alignedPtrList.size()) << endl;
    if (essntialOnly)
    {
        vector<Vector3dd> points3d;
        double zMax = 0;
        for (unsigned i = 0; i < normalList->size(); i++)
        {
            double d1, d2, err;
            Correspondance corr = normalList->at(i);
            result.decomposition.getScaler(corr , d1, d2, err);
            Vector3dd point(corr.start, 1.0);
            point *= d1;
            point *= params.baselineLength();
            points3d.push_back(point);
            if (zMax < d1) zMax = d1;
        }
        topView = new QImage(800,800, QImage::Format_RGB32);
        topView->fill(0);
        QPainter painter(topView);
        for (unsigned i = 0; i < points3d.size(); i++)
        {
            double x = points3d[i].x();
            double z = points3d[i].z();
            int ix = x + topView->width() / 2;
            int iz = topView->height() - 1 - z;
            painter.setPen(QColor(0xF0, 0xF0, 0xF0));
            painter.drawPoint(ix, iz);
        }
        /* Draw camera lines */
        {
            Vector3dd ll = result.leftCamera .getInvKMatrix33() * Vector3dd(         0.0, inputList->h / 2, 1.0);
            Vector3dd rl = result.leftCamera .getInvKMatrix33() * Vector3dd(inputList->w, inputList->h / 2, 1.0);
            ll *= 100;
            rl *= 100;
            int ix, iz;
            ix = ll.x() + topView->width() / 2;
            iz = topView->height() - 1 - ll.z();
            painter.setPen(QColor(0xFF, 0x00, 0x00));
            painter.drawPoint(ix, iz);
            ix = rl.x() + topView->width() / 2;
            iz = topView->height() - 1 - rl.z();
            painter.setPen(QColor(0xFF, 0x00, 0x00));
            painter.drawPoint(ix, iz);
        }
        FILE *Points = fopen("points.txt", "wt");
        for (unsigned i = 0; i < points3d.size(); i++)
        {
            fprintf(Points, "%lf %lf %lf\n", points3d[i].x(), points3d[i].y(), points3d[i].z());
        }
        fclose(Points);
    }
    /*Finally copy back the flag information*/
    normalList->propagateData();
    filteredList->propagateData();
    postKlt->propagateData();
    list->propagateData();
}
Member Data Documentation
int UniversalRectifier::code
Definition at line 96 of file universalRectifier.h.
Referenced by recalculate().
vector<Correspondance *>* UniversalRectifier::data
Data in the format the estimators understand.
Definition at line 64 of file universalRectifier.h.
Referenced by iterativeMethod(), recalculate(), and ~UniversalRectifier().
Vector3dd UniversalRectifier::direction
Z direction for rectification.
Definition at line 78 of file universalRectifier.h.
Referenced by getZ(), manualMethod(), and recalculate().
Vector3dd UniversalRectifier::E1
Definition at line 86 of file universalRectifier.h.
Referenced by recalculate().
Vector3dd UniversalRectifier::E2
Definition at line 87 of file universalRectifier.h.
Referenced by recalculate().
DerivedCorrespondanceList* UniversalRectifier::filteredList
This is a local copy of the input that we will hold the filtered by length values.
Definition at line 52 of file universalRectifier.h.
Referenced by iterativeMethod(), recalculate(), and ~UniversalRectifier().
CorrespondanceList* UniversalRectifier::inputList
The input list.
Right to Left correspondances. For rectified pair all end.x() - start.x() should be positive After recalculation it will be altered with new flags
Definition at line 36 of file universalRectifier.h.
Referenced by getZ(), and recalculate().
G12Buffer* UniversalRectifier::left
This is used for KLT only and should be brought out of the class TODO: Move this out.
Definition at line 71 of file universalRectifier.h.
Referenced by recalculate().
DerivedCorrespondanceList* UniversalRectifier::list
This is a local copy of the input that we will alter with KLT, or any other improvement algorithm.
Definition at line 41 of file universalRectifier.h.
Referenced by recalculate(), and ~UniversalRectifier().
DerivedCorrespondanceList* UniversalRectifier::normalList
This is a local copy of the input that we will hold the filtered by length values.
Definition at line 58 of file universalRectifier.h.
Referenced by decomposeEssential(), ransacMethod(), recalculate(), and ~UniversalRectifier().
RectifyParameters UniversalRectifier::params
Definition at line 28 of file universalRectifier.h.
Referenced by getZ(), iterativeMethod(), manualMethod(), ransacMethod(), and recalculate().
DerivedCorrespondanceList* UniversalRectifier::postKlt
This is a local copy of the input that we will alter with KLT, or any other improvement algorithm.
Definition at line 47 of file universalRectifier.h.
Referenced by recalculate(), and ~UniversalRectifier().
RectificationResult UniversalRectifier::result
Definition at line 80 of file universalRectifier.h.
Referenced by decomposeEssential(), getZ(), iterativeMethod(), manualMethod(), ransacMethod(), and recalculate().
G12Buffer* UniversalRectifier::right
Definition at line 72 of file universalRectifier.h.
Referenced by iterativeMethod(), and recalculate().
QString UniversalRectifier::status
Definition at line 95 of file universalRectifier.h.
Referenced by recalculate().
QImage* UniversalRectifier::topView
Definition at line 90 of file universalRectifier.h.
Referenced by recalculate().
QImage* UniversalRectifier::zGraph
Definition at line 89 of file universalRectifier.h.
Referenced by getZ().
The documentation for this class was generated from the following files:
utils/rectifier/universalRectifier.h
utils/rectifier/universalRectifier.cpp