DeepView: OSDBaseWidget Class Reference
OSDBaseWidget Class Reference
#include <osdBaseWidget.h>
Signals
void resetState ()
Public Member Functions
OSDBaseWidget (QWidget *parent=0)
virtual ~OSDBaseWidget ()
void paintEvent (QPaintEvent *)
void offscreenChanged (QImage *newOffscreen)
void keyPressEvent (QKeyEvent *event)
Private Member Functions
void runOnTopCommand ()
Private Attributes
QImage * offscreen
Detailed Description
Definition at line 6 of file osdBaseWidget.h.
Constructor & Destructor Documentation
OSDBaseWidget::OSDBaseWidget (QWidget * parent = 0)
Definition at line 19 of file osdBaseWidget.cpp.
References runOnTopCommand().
                                            :
        QWidget(parent,  Qt::FramelessWindowHint),
        offscreen(NULL)
{
    setAccessibleName("OSD");
    setWindowTitle("ViMouse OSD");
    setWindowFlags(windowFlags() | Qt::WindowStaysOnTopHint);
    //showMaximized();
    setGeometry(QApplication::desktop()->screenGeometry(-1));
#ifdef Q_OS_WIN
    runOnTopCommand();
#endif
    setAttribute(Qt::WA_TranslucentBackground);
    show();
#ifdef Q_OS_LINUX
    QRect relativeWidgetRect = this->contentsRect();
    QRect absoluteWidgetRect = QRect(QWidget::mapToGlobal(relativeWidgetRect.topLeft()), QWidget::mapToGlobal(relativeWidgetRect.bottomRight()));
    XRectangle xrect = {0,0,1,1};
    QX11Info qX11Info = this->x11Info();
    Display *display = qX11Info.display ();
    Window winId = (Window)this->winId();
    XShapeCombineRectangles (
         display,
         winId,
         ShapeInput,
         absoluteWidgetRect.x(),absoluteWidgetRect.y(),
         &xrect, 1,
         ShapeSet,
         YXBanded );
#endif
// FIXME
    hide();
}
OSDBaseWidget::~OSDBaseWidget () [virtual]
Definition at line 59 of file osdBaseWidget.cpp.
References offscreen.
{
    delete_safe(offscreen);
}
Member Function Documentation
void OSDBaseWidget::keyPressEvent (QKeyEvent * event)
Definition at line 113 of file osdBaseWidget.cpp.
References resetState().
{
    if (event->key() == Qt::Key_F10)
    {
        emit resetState();
    }
    event->ignore();
}
void OSDBaseWidget::offscreenChanged (QImage * newOffscreen)
Definition at line 91 of file osdBaseWidget.cpp.
References offscreen, and runOnTopCommand().
{
    QImage *oldOffscreen = offscreen;
    offscreen = newOffscreen;
    delete oldOffscreen;
    Qt::WindowFlags flags = windowFlags();
    flags |= Qt::WindowStaysOnTopHint;
    setWindowFlags( flags );
/*#ifdef Q_OS_WIN*/
    static int hackCount = 0;
    if ((hackCount % 20) == 0)
    {
        runOnTopCommand();
    }
    hackCount++;
/*#endif*/
    this->update();
}
void OSDBaseWidget::paintEvent (QPaintEvent *)
Definition at line 125 of file osdBaseWidget.cpp.
References offscreen.
{
    QPainter painter(this);
    if (offscreen == 0)
    {
        QFont font;
        font.setPixelSize(70);
        painter.setFont(font);
        QRect rect = this->rect();
        painter.drawText(rect, Qt::AlignHCenter | Qt::AlignVCenter, "No Information");
    } else {
        painter.drawImage(0,0,*offscreen);
    }
}
void OSDBaseWidget::resetState () [signal]
Referenced by keyPressEvent().
void OSDBaseWidget::runOnTopCommand () [private]
Referenced by offscreenChanged(), and OSDBaseWidget().
Member Data Documentation
QImage* OSDBaseWidget::offscreen [private]
Definition at line 24 of file osdBaseWidget.h.
Referenced by offscreenChanged(), paintEvent(), and ~OSDBaseWidget().
The documentation for this class was generated from the following files:
utils/uis/osdBaseWidget.h
utils/uis/osdBaseWidget.cpp