DeepView: corecvs::Triangulator Class Reference
corecvs::Triangulator Class Reference
Swarm point is a class that holds the information about single point in space Associated with color and etc.
#include <triangulator.h>
Public Member Functions
Triangulator (const RectificationResult &_rectifierData)
Vector3dd triangulate (const Vector2dd &start, const Vector2dd &shift) const
Vector3dd triangulate (const Vector2dd &start, double shift) const
double getDepth (const Vector2dd &start, const Vector2dd &shift) const
double getDepth (const Vector2dd &start, double shift) const
double getDisparity (const Vector3dd &point) const
Cloud * triangulate (DisparityBuffer *input, int density, bool enforceRectify=false) const
Input is right to left.
Cloud * triangulate (FloatFlowBuffer *input, int density, bool enforceRectify=false) const
Cloud * triangulate (SixDBuffer *input, int density) const
DepthBuffer * triangulateToDB (DisparityBuffer *input, bool enforceRectify=false) const
Public Attributes
RectificationResult rectifierData
Matrix33 rectifiedToCameraFrameLeft
Matrix33 rectifiedToCameraFrameRight
Private Member Functions
template<class InputType >
Cloud * triangulateHelper (InputType *input, int density, bool enforceRectify) const
template<class InputType >
Cloud * triangulateHelperParallel (InputType *input, int density, bool enforceRectify) const
Detailed Description
Swarm point is a class that holds the information about single point in space Associated with color and etc.
Definition at line 114 of file triangulator.h.
Constructor & Destructor Documentation
corecvs::Triangulator::Triangulator (const RectificationResult & _rectifierData)
Definition at line 13 of file triangulator.cpp.
References corecvs::CameraIntrinsics::getInvKMatrix33(), corecvs::Matrix33::inv(), rectifiedToCameraFrameLeft, rectifiedToCameraFrameRight, rectifierData, corecvs::RectificationResult::rightCamera, and corecvs::RectificationResult::rightTransform.
                                                                    :
    rectifierData(_rectifierData)
{
    rectifiedToCameraFrameLeft =
            rectifierData. leftCamera.getInvKMatrix33() * rectifierData. leftTransform.inv();
    rectifiedToCameraFrameRight =
            rectifierData.rightCamera.getInvKMatrix33() * rectifierData.rightTransform.inv();
}
Member Function Documentation
double corecvs::Triangulator::getDepth (const Vector2dd & start, const Vector2dd & shift) const
Definition at line 56 of file triangulator.cpp.
References corecvs::RectificationResult::baseline, corecvs::RectificationResult::decomposition, corecvs::EssentialDecomposition::getScaler(), rectifiedToCameraFrameLeft, rectifiedToCameraFrameRight, and rectifierData.
Referenced by getDepth(), and triangulateToDB().
{
    Vector2dd end = start + shift;
    Vector2dd startInCameraFrame = rectifiedToCameraFrameRight * start;
    Vector2dd endInCameraFrame   = rectifiedToCameraFrameLeft  * end;
    double d1, d2, err;
    Vector3dd start3d(startInCameraFrame, 1.0);
    Vector3dd end3d  (  endInCameraFrame, 1.0);
    rectifierData.decomposition.getScaler(start3d, end3d, d1, d2, err);
    return d1 * rectifierData.baseline;
}
double corecvs::Triangulator::getDepth (const Vector2dd & start, double shift) const
Definition at line 72 of file triangulator.cpp.
References getDepth().
{
    return getDepth(start, Vector2dd(shift, 0));
}
double corecvs::Triangulator::getDisparity (const Vector3dd & point) const
Definition at line 77 of file triangulator.cpp.
References corecvs::RectificationResult::getRectifiedProjectionLeft(), corecvs::RectificationResult::getRectifiedProjectionRight(), rectifierData, and corecvs::Vector2d< ElementType >::x().
{
    Vector2dd projectRight = rectifierData.getRectifiedProjectionRight(point);
    Vector2dd projectLeft  = rectifierData.getRectifiedProjectionLeft (point);
    return projectLeft.x() - projectRight.x();
}
Vector3dd corecvs::Triangulator::triangulate (const Vector2dd & start, const Vector2dd & shift) const
Definition at line 24 of file triangulator.cpp.
References corecvs::RectificationResult::baseline, corecvs::RectificationResult::decomposition, corecvs::EssentialDecomposition::getDistance(), corecvs::EssentialDecomposition::getScaler(), corecvs::VectorOperationsBase< RealType, ElementType >::normalised(), rectifiedToCameraFrameLeft, rectifiedToCameraFrameRight, and rectifierData.
Referenced by corecvs::ParallelTriangulate< InputType >::operator()(), triangulate(), and triangulateHelper().
{
    Vector2dd end = start + shift;
    Vector2dd startInCameraFrame = rectifiedToCameraFrameRight * start;
    Vector2dd endInCameraFrame   = rectifiedToCameraFrameLeft  * end;
    double d1;
    double d2;
    double err;
    Vector3dd start3d(startInCameraFrame, 1.0);
    Vector3dd end3d  (  endInCameraFrame, 1.0);
    Vector3dd point;
    if (0 /*Old style triangulation*/) {
        rectifierData.decomposition.getScaler(start3d, end3d, d1, d2, err);
        point = (start3d * d1) * rectifierData.baseline;
    } else {
        rectifierData.decomposition.getDistance(start3d, end3d, d1, d2, err);
        point = (start3d.normalised() * d1) * rectifierData.baseline;
    }
    return point;
}
Vector3dd corecvs::Triangulator::triangulate (const Vector2dd & start, double shift) const
Definition at line 50 of file triangulator.cpp.
References triangulate().
{
    return triangulate(start, Vector2dd(shift, 0));
}
Cloud* corecvs::Triangulator::triangulate (DisparityBuffer * input, int density, bool enforceRectify = false) const
Input is right to left.
Cloud * corecvs::Triangulator::triangulate (FloatFlowBuffer * input, int density, bool enforceRectify = false) const
Definition at line 217 of file triangulator.cpp.
References triangulateHelper(), and triangulateHelperParallel().
{
#ifdef WITH_TBB
    return triangulateHelperParallel(input, density, enforceRectify);
#endif
    return triangulateHelper(input,  density, enforceRectify);
}
Cloud * corecvs::Triangulator::triangulate (SixDBuffer * input, int density) const
Definition at line 285 of file triangulator.cpp.
References corecvs::Element6D::disp, corecvs::Element6D::dispPrev, corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::Element6D::flow, corecvs::AbstractBufferParams::h, corecvs::Element6D::hasDisp(), corecvs::Element6D::hasFlow(), corecvs::Element6D::hasPrevDisp(), corecvs::SwarmPoint::is6D, corecvs::SwarmPoint::point, corecvs::SwarmPoint::speed, corecvs::SwarmPoint::texCoor, triangulate(), corecvs::AbstractBufferParams::w, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    Cloud *result = new Cloud();
    result->reserve(density);
    for (int i = 0; i < input->h; i++)
    {
        for (int j = 0; j < input->w; j++)
        {
            const Element6D &element = input->element(i,j);
            if (!element.hasDisp() || element.disp <= 0)
                continue;
            /* Point in right frame*/
            Vector2dd start(j,i);
            Vector2dd shift = Vector2dd(element.disp, 0);
            SwarmPoint swarmPoint;
            Vector3dd current3d = triangulate(start, shift);
            swarmPoint.point = current3d;
            swarmPoint.texCoor = start;
            /* Now 6D */
            if (element.hasFlow())
            {
                /*Position at previous frame */
                Vector2dd start1(start.x() + element.flow.x(), start.y() + element.flow.y());
                Vector3dd old3d = current3d;
                if (element.hasPrevDisp() && element.dispPrev > 0)
                {
                    Vector2dd shift1 = Vector2dd(element.dispPrev, 0);
                    old3d = triangulate(start1, shift1);
                    swarmPoint.is6D = true;
                } else {
                    //Vector2dd normalisedEnd1 = rectifiedToNormalizedRight * end1;
                    //old3d = Vector3dd(normalisedEnd1, 1.0) * current3d.z();
                    //old3d = current3d;
                }
                swarmPoint.speed = current3d - old3d;
            }
            result->push_back(swarmPoint);
        }
    }
    return result;
}
template<class InputType > Cloud * corecvs::Triangulator::triangulateHelper (InputType * input, int density, bool enforceRectify) const [private]
Definition at line 181 of file triangulator.cpp.
References corecvs::SwarmPoint::point, corecvs::SwarmPoint::texCoor, triangulate(), and corecvs::Vector2d< ElementType >::y().
Referenced by triangulate().
{
    Cloud *result = new Cloud();
    result->reserve(density);
    for (int i = 0; i < input->h; i++)
    {
        for (int j = 0; j < input->w; j++)
        {
            if (!input->isElementKnown(i, j))
                continue;
            /* Point in right frame*/
            Vector2dd start(j,i);
            Vector2dd shift;
            shift = getInputDisparity<InputType>(input, i,j);
            if (enforceRectify) {
                shift.y() = 0;
            }
            SwarmPoint cloudPoint;
            cloudPoint.point = triangulate(start, shift);
            cloudPoint.texCoor = start;
            result->push_back(cloudPoint);
        }
    }
    return result;
}
template<class InputType > Cloud * corecvs::Triangulator::triangulateHelperParallel (InputType * input, int density, bool enforceRectify) const [private]
Definition at line 171 of file triangulator.cpp.
References corecvs::parallelable_reduce(), and corecvs::ParallelTriangulate< InputType >::result.
Referenced by triangulate().
{
    ParallelTriangulate<InputType> tr(this, input, density, enforceRectify);
    parallelable_reduce(0, input->h, tr);
    return new Cloud(*(tr.result));
}
DepthBuffer * corecvs::Triangulator::triangulateToDB (DisparityBuffer * input, bool enforceRectify = false) const
Definition at line 333 of file triangulator.cpp.
References corecvs::DepthBuffer::DEPTH_UNKNOWN, corecvs::AbstractBuffer< ElementType, IndexType >::element(), getDepth(), corecvs::AbstractBufferParams::h, corecvs::AbstractBufferParams::w, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    if (input != NULL) {
        return NULL;
    }
    DepthBuffer *result = new DepthBuffer(input->h, input->w, false);
    for (int i = 0; i < result->h; i++)
    {
        for (int j = 0; j < result->w; j++)
        {
            if (!input->isElementKnown(i, j)) {
                result->element(i,j) = DepthBuffer::DEPTH_UNKNOWN;
                continue;
            }
            FlowElement *flowElement = &input->element(i,j);
            /* Point in right frame*/
            Vector2dd start(j,i);
            Vector2dd shift(flowElement->x(), enforceRectify ? 0 : flowElement->y());
            result->element(i,j) = getDepth(start, shift);
        }
    }
    return result;
}
Member Data Documentation
Matrix33 corecvs::Triangulator::rectifiedToCameraFrameLeft
Definition at line 118 of file triangulator.h.
Referenced by getDepth(), triangulate(), and Triangulator().
Matrix33 corecvs::Triangulator::rectifiedToCameraFrameRight
Definition at line 119 of file triangulator.h.
Referenced by getDepth(), triangulate(), and Triangulator().
RectificationResult corecvs::Triangulator::rectifierData
Definition at line 117 of file triangulator.h.
Referenced by getDepth(), getDisparity(), triangulate(), and Triangulator().
The documentation for this class was generated from the following files:
core/rectification/triangulator.h
core/rectification/triangulator.cpp