DeepView: OpenCVBMParametersControlWidget Class Reference
OpenCVBMParametersControlWidget Class Reference
#include <openCVBMParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
OpenCVBMParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~OpenCVBMParametersControlWidget ()
OpenCVBMParameters * createParameters () const
void setParameters (const OpenCVBMParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_OpenCVBMParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file openCVBMParametersControlWidget.h.
Constructor & Destructor Documentation
OpenCVBMParametersControlWidget::OpenCVBMParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file openCVBMParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::OpenCVBMParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->blockSizeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->disparitySearchSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->preFilterCapSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->minDisparitySpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->textureThresholdSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->uniquenessRatioSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->speckleWindowSizeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->speckleRangeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->disp12MaxDiffSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
OpenCVBMParametersControlWidget::~OpenCVBMParametersControlWidget ()
Definition at line 34 of file openCVBMParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void OpenCVBMParametersControlWidget::changeParameters () [inline, slot]
Definition at line 29 of file openCVBMParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
OpenCVBMParameters * OpenCVBMParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 56 of file openCVBMParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    OpenCVBMParameters *result = new OpenCVBMParameters(
          mUi->blockSizeSpinBox->value()
        , mUi->disparitySearchSpinBox->value()
        , mUi->preFilterCapSpinBox->value()
        , mUi->minDisparitySpinBox->value()
        , mUi->textureThresholdSpinBox->value()
        , mUi->uniquenessRatioSpinBox->value()
        , mUi->speckleWindowSizeSpinBox->value()
        , mUi->speckleRangeSpinBox->value()
        , mUi->disp12MaxDiffSpinBox->value()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void OpenCVBMParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 40 of file openCVBMParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    OpenCVBMParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void OpenCVBMParametersControlWidget::paramsChanged () [signal]
Referenced by OpenCVBMParametersControlWidget(), and setParameters().
void OpenCVBMParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 48 of file openCVBMParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    OpenCVBMParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void OpenCVBMParametersControlWidget::setParameters (const OpenCVBMParameters & input)
Definition at line 78 of file openCVBMParametersControlWidget.cpp.
References OpenCVBMParameters::blockSize(), OpenCVBMParameters::disp12MaxDiff(), OpenCVBMParameters::disparitySearch(), OpenCVBMParameters::minDisparity(), mUi, paramsChanged(), OpenCVBMParameters::preFilterCap(), OpenCVBMParameters::speckleRange(), OpenCVBMParameters::speckleWindowSize(), OpenCVBMParameters::textureThreshold(), and OpenCVBMParameters::uniquenessRatio().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->blockSizeSpinBox->setValue(input.blockSize());
    mUi->disparitySearchSpinBox->setValue(input.disparitySearch());
    mUi->preFilterCapSpinBox->setValue(input.preFilterCap());
    mUi->minDisparitySpinBox->setValue(input.minDisparity());
    mUi->textureThresholdSpinBox->setValue(input.textureThreshold());
    mUi->uniquenessRatioSpinBox->setValue(input.uniquenessRatio());
    mUi->speckleWindowSizeSpinBox->setValue(input.speckleWindowSize());
    mUi->speckleRangeSpinBox->setValue(input.speckleRange());
    mUi->disp12MaxDiffSpinBox->setValue(input.disp12MaxDiff());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void OpenCVBMParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 95 of file openCVBMParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    OpenCVBMParameters *inputCasted = static_cast<OpenCVBMParameters *>(input);
    setParameters(*inputCasted);
}
void OpenCVBMParametersControlWidget::valueChanged () [signal]
Referenced by OpenCVBMParametersControlWidget().
Member Data Documentation
bool OpenCVBMParametersControlWidget::autoInit [private]
Definition at line 40 of file openCVBMParametersControlWidget.h.
Ui_OpenCVBMParametersControlWidget* OpenCVBMParametersControlWidget::mUi [private]
Definition at line 39 of file openCVBMParametersControlWidget.h.
Referenced by createParameters(), OpenCVBMParametersControlWidget(), setParameters(), and ~OpenCVBMParametersControlWidget().
QString OpenCVBMParametersControlWidget::rootPath [private]
Definition at line 41 of file openCVBMParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/corestructs/libWidgets/openCVBMParametersControlWidget.h
utils/corestructs/libWidgets/openCVBMParametersControlWidget.cpp