DeepView: GraphPlotParametersControlWidget Class Reference
GraphPlotParametersControlWidget Class Reference
#include <graphPlotParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
GraphPlotParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~GraphPlotParametersControlWidget ()
GraphPlotParameters * createParameters () const
void setParameters (const GraphPlotParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_GraphPlotParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 11 of file graphPlotParametersControlWidget.h.
Constructor & Destructor Documentation
GraphPlotParametersControlWidget::GraphPlotParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file graphPlotParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::GraphPlotParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
mUi->yScaleSlider->setMaxZoom(1000);
    QObject::connect(mUi->graphStyleComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->widthSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->centerAtSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->xGridCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->yGridCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->xScaleSlider, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->yScaleSlider, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->contrastSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->selectGraphCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fixTimeValueButton, SIGNAL(clicked(bool)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fixGridValueButton, SIGNAL(clicked(bool)), this, SIGNAL(paramsChanged()));
}
GraphPlotParametersControlWidget::~GraphPlotParametersControlWidget ()
Definition at line 38 of file graphPlotParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void GraphPlotParametersControlWidget::changeParameters () [inline, slot]
Definition at line 28 of file graphPlotParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
GraphPlotParameters * GraphPlotParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 60 of file graphPlotParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    GraphPlotParameters *result = new GraphPlotParameters(
          static_cast<GraphStyle::GraphStyle>(mUi->graphStyleComboBox->currentIndex())
        , mUi->widthSpinBox->value()
        , mUi->centerAtSpinBox->value()
        , mUi->xGridCheckBox->isChecked()
        , mUi->yGridCheckBox->isChecked()
        , mUi->xScaleSlider->value()
        , mUi->yScaleSlider->value()
        , mUi->contrastSpinBox->value()
        , mUi->selectGraphCheckBox->isChecked()
        , mUi->fixTimeValueButton->isChecked()
        , mUi->fixGridValueButton->isChecked()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void GraphPlotParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 44 of file graphPlotParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    GraphPlotParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void GraphPlotParametersControlWidget::paramsChanged () [signal]
Referenced by GraphPlotParametersControlWidget(), and setParameters().
void GraphPlotParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 52 of file graphPlotParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    GraphPlotParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void GraphPlotParametersControlWidget::setParameters (const GraphPlotParameters & input)
Definition at line 84 of file graphPlotParametersControlWidget.cpp.
References GraphPlotParameters::centerAt(), GraphPlotParameters::contrast(), GraphPlotParameters::fixGridValue(), GraphPlotParameters::fixTimeValue(), GraphPlotParameters::graphStyle(), mUi, paramsChanged(), GraphPlotParameters::selectGraph(), GraphPlotParameters::width(), GraphPlotParameters::xGrid(), GraphPlotParameters::xScale(), GraphPlotParameters::yGrid(), and GraphPlotParameters::yScale().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->graphStyleComboBox->setCurrentIndex(input.graphStyle());
    mUi->widthSpinBox->setValue(input.width());
    mUi->centerAtSpinBox->setValue(input.centerAt());
    mUi->xGridCheckBox->setChecked(input.xGrid());
    mUi->yGridCheckBox->setChecked(input.yGrid());
    mUi->xScaleSlider->setValue(input.xScale());
    mUi->yScaleSlider->setValue(input.yScale());
    mUi->contrastSpinBox->setValue(input.contrast());
    mUi->selectGraphCheckBox->setChecked(input.selectGraph());
    mUi->fixTimeValueButton->setChecked(input.fixTimeValue());
    mUi->fixGridValueButton->setChecked(input.fixGridValue());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void GraphPlotParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 103 of file graphPlotParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    GraphPlotParameters *inputCasted = static_cast<GraphPlotParameters *>(input);
    setParameters(*inputCasted);
}
void GraphPlotParametersControlWidget::valueChanged () [signal]
Referenced by GraphPlotParametersControlWidget().
Member Data Documentation
bool GraphPlotParametersControlWidget::autoInit [private]
Definition at line 39 of file graphPlotParametersControlWidget.h.
Ui_GraphPlotParametersControlWidget* GraphPlotParametersControlWidget::mUi [private]
Definition at line 38 of file graphPlotParametersControlWidget.h.
Referenced by createParameters(), GraphPlotParametersControlWidget(), setParameters(), and ~GraphPlotParametersControlWidget().
QString GraphPlotParametersControlWidget::rootPath [private]
Definition at line 40 of file graphPlotParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/widgets/graphPlotParametersControlWidget.h
utils/widgets/generated/graphPlotParametersControlWidget.cpp