DeepView: SaveableWidget Class Reference
SaveableWidget Class Reference
#include <parametersControlWidgetBase.h>
Public Member Functions
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
virtual void loadParamWidget (WidgetLoader &)
virtual void saveParamWidget (WidgetSaver &)
Detailed Description
Definition at line 100 of file parametersControlWidgetBase.h.
Member Function Documentation
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
virtual void SaveableWidget::loadParamWidget (WidgetLoader &) [inline, virtual]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 119 of file parametersControlWidgetBase.h.
Referenced by loadFromQSettings().
{}
virtual void SaveableWidget::saveParamWidget (WidgetSaver &) [inline, virtual]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 120 of file parametersControlWidgetBase.h.
Referenced by saveToQSettings().
{}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
The documentation for this class was generated from the following file:
utils/corestructs/parametersControlWidgetBase.h