DeepView: ExponentialSlider Class Reference
ExponentialSlider Class Reference
#include <exponentialSlider.h>
Public Slots
void expTextChanged (double value)
void expSliderChanged (int val)
Signals
void valueChanged (double value)
Public Member Functions
ExponentialSlider (QWidget *parent=0)
~ExponentialSlider ()
void setMaxZoom (double value, double sliderSteps=100)
double minimum (void)
double maximum (void)
double value (void)
void setValue (double value)
void stepUp ()
void stepDown ()
Private Attributes
Ui::ExponentialSliderClass ui
int sliderSteps
double sliderExp
Detailed Description
Definition at line 7 of file exponentialSlider.h.
Constructor & Destructor Documentation
ExponentialSlider::ExponentialSlider (QWidget * parent = 0)
Definition at line 7 of file exponentialSlider.cpp.
References setMaxZoom(), and ui.
    : QWidget(parent)
    , sliderSteps(100)
    , sliderExp(1.05)
{
    ui.setupUi(this);
    setMaxZoom(100);
}
ExponentialSlider::~ExponentialSlider ()
Definition at line 16 of file exponentialSlider.cpp.
{
}
Member Function Documentation
void ExponentialSlider::expSliderChanged (int val) [slot]
Definition at line 79 of file exponentialSlider.cpp.
References M_E, sliderExp, ui, value(), and valueChanged().
{
    double value = pow(M_E, sliderExp * val);
    bool blocked = ui.expSpinBox->blockSignals(true);
    ui.expSpinBox->setValue(value);
    ui.expSpinBox->blockSignals(blocked);
    emit valueChanged(value);
}
void ExponentialSlider::expTextChanged (double value) [slot]
Definition at line 67 of file exponentialSlider.cpp.
References sliderExp, ui, and valueChanged().
{
    double loge = log(value);
    double val  = loge / sliderExp;
    bool blocked = ui.expSlider->blockSignals(true);
    ui.expSlider->setValue(val);
    ui.expSlider->blockSignals(blocked);
    emit valueChanged(value);
}
double ExponentialSlider::maximum (void)
Definition at line 39 of file exponentialSlider.cpp.
References ui.
{
    return ui.expSpinBox->maximum();
}
double ExponentialSlider::minimum (void)
Definition at line 34 of file exponentialSlider.cpp.
References ui.
{
    return ui.expSpinBox->minimum();
}
void ExponentialSlider::setMaxZoom (double value, double sliderSteps = 100)
Definition at line 21 of file exponentialSlider.cpp.
References sliderExp, sliderSteps, and ui.
Referenced by ExponentialSlider().
{
    ui.expSpinBox->setMaximum(      value);
    ui.expSpinBox->setMinimum(1.0 / value);
    ui.expSlider->setMaximum( sliderSteps);
    ui.expSlider->setMinimum(-sliderSteps);
    double power = log(value);
    double powerStep = power / sliderSteps;
    sliderExp = powerStep;
}
void ExponentialSlider::setValue (double value)
Definition at line 52 of file exponentialSlider.cpp.
References ui.
{
    ui.expSpinBox->setValue(value);
}
void ExponentialSlider::stepDown ()
Definition at line 62 of file exponentialSlider.cpp.
References ui.
{
    ui.expSlider->setValue(ui.expSlider->value() - 1);
}
void ExponentialSlider::stepUp ()
Definition at line 57 of file exponentialSlider.cpp.
References ui.
{
    ui.expSlider->setValue(ui.expSlider->value() + 1);
}
double ExponentialSlider::value (void)
Definition at line 44 of file exponentialSlider.cpp.
References ui.
Referenced by expSliderChanged().
{
    if (ui.expSpinBox->value() == 0.0) {
        qDebug("ExponentialSlider::value(): Oops crash possible returing zero\n");
    }
    return ui.expSpinBox->value();
}
void ExponentialSlider::valueChanged (double value) [signal]
Referenced by expSliderChanged(), and expTextChanged().
Member Data Documentation
double ExponentialSlider::sliderExp [private]
Definition at line 36 of file exponentialSlider.h.
Referenced by expSliderChanged(), expTextChanged(), and setMaxZoom().
int ExponentialSlider::sliderSteps [private]
Definition at line 35 of file exponentialSlider.h.
Referenced by setMaxZoom().
Ui::ExponentialSliderClass ExponentialSlider::ui [private]
Definition at line 34 of file exponentialSlider.h.
Referenced by ExponentialSlider(), expSliderChanged(), expTextChanged(), maximum(), minimum(), setMaxZoom(), setValue(), stepDown(), stepUp(), and value().
The documentation for this class was generated from the following files:
utils/widgets/exponentialSlider.h
utils/widgets/exponentialSlider.cpp