DeepView: Log::MessageScoped Class Reference
Log::MessageScoped Class Reference
If we want to use qDebug style for debugging we need an object that will be destroyed when leaving the scope.
#include <log.h>
Public Member Functions
MessageScoped (Log *log, LogLevel level, cchar *originFileName=NULL, int originLineNumber=-1, cchar *originFunctionName=NULL)
~MessageScoped ()
template<typename T >
MessageScoped & operator<< (const T &t)
Public Attributes
Message message
Detailed Description
If we want to use qDebug style for debugging we need an object that will be destroyed when leaving the scope.
This will trigger the flush.
Definition at line 116 of file log.h.
Constructor & Destructor Documentation
Log::MessageScoped::MessageScoped (Log * log, LogLevel level, cchar * originFileName = NULL, int originLineNumber = -1, cchar * originFunctionName = NULL) [inline]
Definition at line 121 of file log.h.
References corecvs::ObjectRef< Type >::allocate(), corecvs::ObjectRef< Type >::get(), and message.
        {
            message.allocate();
            message.get()->mLevel              = level;
            message.get()->mLog                = log;
            message.get()->mOriginFileName     = originFileName;
            message.get()->mOriginFunctionName = originFunctionName;
            message.get()->mOriginLineNumber   = originLineNumber;
            time(&message.get()->rawtime);
        }
Log::MessageScoped::~MessageScoped () [inline]
Definition at line 137 of file log.h.
References DOTRACE, corecvs::ObjectRef< Type >::get(), message, and Log::shouldWrite().
        {
            DOTRACE(("Scope is closing, sending data to log\n"));
            if (Log::shouldWrite(message.get()->mLevel)) {
                message.get()->mLog->message(message);
            }
            DOTRACE(("Scope is closed, data sent\n"));
        }
Member Function Documentation
template<typename T > MessageScoped& Log::MessageScoped::operator<< (const T & t) [inline]
Definition at line 146 of file log.h.
References corecvs::ObjectRef< Type >::get(), and message.
{
            (*message.get()) << t;
            return *this;
        }
Member Data Documentation
Message Log::MessageScoped::message
Definition at line 119 of file log.h.
Referenced by MessageScoped(), operator<<(), and ~MessageScoped().
The documentation for this class was generated from the following file:
core/utils/log.h