DeepView: corecvs::VoxelBufferBase< RealType, ElementType > Class Template Reference
corecvs::VoxelBufferBase< RealType, ElementType > Class Template Reference
#include <voxelBuffer.h>
Public Types
typedef ElementType InternalElementType
Public Member Functions
VoxelBufferBase (int _l, int _h, int _w)
ElementType & element (const IndexType z, const IndexType y, const IndexType x)
The element getter.
const ElementType & element (const IndexType z, const IndexType y, const IndexType x) const
ElementType & element (const Vector3d32 &p)
The element getter.
const ElementType & element (const Vector3d32 &p) const
bool isValidCoord (const IndexType z, const IndexType y, const IndexType x) const
Checks if coordinate lies within the buffer area.
bool isValidCoord (const Vector2d< IndexType > &p) const
Checks if coordinate lies within the buffer area.
bool hasSameSize (const VoxelBufferBase *other) const
Checks if this buffer has the same size as the other.
bool hasSameSize (const IndexType &otherL, const IndexType &otherH, const IndexType &otherW) const
Checks if this buffer has the same size as the parameters given.
IndexType getL () const
Length getter.
IndexType getH () const
Height getter.
IndexType getW () const
Width getter.
Vector2d32 getSize () const
~FixedArrayBase ()
Public Attributes
MemoryBlockRef memoryBlock
Memory block that holds the data.
ElementType * element
The array of the data elements.
int l
int h
int w
int size
Private Member Functions
void _init (int _l, int _h, int _w)
Detailed Description
template<typename RealType, typename ElementType>
class corecvs::VoxelBufferBase< RealType, ElementType >
              * * * * *      ^  Z (L)
              * * * * *     /
              * * * * *    /
              * * * * *   /
                         /
         * * * * *      /
         * * * * *     /
         * * * * *    /
         * * * * *   /
                    /
  | * * * * *      /
  | * * * * *     /
  | * * * * *    /
  | * * * * *
  |  --------> X (W)
  v
 Y (H)
Definition at line 49 of file voxelBuffer.h.
Member Typedef Documentation
template<typename RealType , typename ElementType > typedef ElementType corecvs::VoxelBufferBase< RealType, ElementType >::InternalElementType
Definition at line 52 of file voxelBuffer.h.
Constructor & Destructor Documentation
template<typename RealType , typename ElementType > corecvs::VoxelBufferBase< RealType, ElementType >::VoxelBufferBase (int _l, int _h, int _w) [inline]
Definition at line 71 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::_init().
{
        _init(_l, _h, _w);
    }
template<typename RealType , typename ElementType > corecvs::VoxelBufferBase< RealType, ElementType >::~FixedArrayBase () [inline]
Definition at line 184 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::element, and corecvs::VoxelBufferBase< RealType, ElementType >::size.
    {
        if (this->element)
        {
            for (int i = 0; i < size; i++)
            {
                element[i].~ElementType();
            }
        }
        this->element = NULL;
    }
Member Function Documentation
template<typename RealType , typename ElementType > void corecvs::VoxelBufferBase< RealType, ElementType >::_init (int _l, int _h, int _w) [inline, private]
Definition at line 198 of file voxelBuffer.h.
References corecvs::ObjectRef< Type >::allocate(), corecvs::VoxelBufferBase< RealType, ElementType >::element, corecvs::ObjectRef< Type >::getAlignedStart(), corecvs::VoxelBufferBase< RealType, ElementType >::h, corecvs::VoxelBufferBase< RealType, ElementType >::l, corecvs::VoxelBufferBase< RealType, ElementType >::memoryBlock, corecvs::VoxelBufferBase< RealType, ElementType >::size, and corecvs::VoxelBufferBase< RealType, ElementType >::w.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::VoxelBufferBase().
    {
        this->l = _l;
        this->h = _h;
        this->w = _w;
        this->size = this->l * this->h * this->w;
        memoryBlock.allocate(this->size * sizeof(ElementType), 0x0);
        this->element = new(memoryBlock.getAlignedStart(0x0)) ElementType[this->size];
    }
template<typename RealType , typename ElementType > ElementType& corecvs::VoxelBufferBase< RealType, ElementType >::element (const IndexType z, const IndexType y, const IndexType x) [inline]
The element getter.
A common practice in this project is for the y coordinate come first
Definition at line 94 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::element, corecvs::VoxelBufferBase< RealType, ElementType >::h, and corecvs::VoxelBufferBase< RealType, ElementType >::w.
    {
        return element[z * w * h + y * w + x];
    };
template<typename RealType , typename ElementType > const ElementType& corecvs::VoxelBufferBase< RealType, ElementType >::element (const IndexType z, const IndexType y, const IndexType x) const [inline]
Definition at line 99 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::element, corecvs::VoxelBufferBase< RealType, ElementType >::h, and corecvs::VoxelBufferBase< RealType, ElementType >::w.
    {
        return element[z * w * h + y * w + x];
    };
template<typename RealType , typename ElementType > ElementType& corecvs::VoxelBufferBase< RealType, ElementType >::element (const Vector3d32 & p) [inline]
The element getter.
Definition at line 107 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::element, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
    {
        return element(p.z(), p.y(), p.x());
    };
template<typename RealType , typename ElementType > const ElementType& corecvs::VoxelBufferBase< RealType, ElementType >::element (const Vector3d32 & p) const [inline]
Definition at line 112 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::element, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
    {
        return element(p.z(), p.y(), p.x());
    };
template<typename RealType , typename ElementType > IndexType corecvs::VoxelBufferBase< RealType, ElementType >::getH () const [inline]
Height getter.
Definition at line 166 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::h.
    {
        return h;
    }
template<typename RealType , typename ElementType > IndexType corecvs::VoxelBufferBase< RealType, ElementType >::getL () const [inline]
Length getter.
Definition at line 158 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::l.
    {
        return l;
    }
template<typename RealType , typename ElementType > Vector2d32 corecvs::VoxelBufferBase< RealType, ElementType >::getSize () const [inline]
Definition at line 179 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::h, corecvs::VoxelBufferBase< RealType, ElementType >::l, and corecvs::VoxelBufferBase< RealType, ElementType >::w.
    {
        return Vector2d32(w, h, l);
    }
template<typename RealType , typename ElementType > IndexType corecvs::VoxelBufferBase< RealType, ElementType >::getW () const [inline]
Width getter.
Definition at line 174 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::w.
    {
        return w;
    }
template<typename RealType , typename ElementType > bool corecvs::VoxelBufferBase< RealType, ElementType >::hasSameSize (const VoxelBufferBase< RealType, ElementType > * other) const [inline]
Checks if this buffer has the same size as the other.
Definition at line 138 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::h, corecvs::VoxelBufferBase< RealType, ElementType >::l, and corecvs::VoxelBufferBase< RealType, ElementType >::w.
    {
        return (this->h == other->h) &&
               (this->w == other->w) &&
               (this->l == other->l);
    };
template<typename RealType , typename ElementType > bool corecvs::VoxelBufferBase< RealType, ElementType >::hasSameSize (const IndexType & otherL, const IndexType & otherH, const IndexType & otherW) const [inline]
Checks if this buffer has the same size as the parameters given.
Definition at line 148 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::h, corecvs::VoxelBufferBase< RealType, ElementType >::l, and corecvs::VoxelBufferBase< RealType, ElementType >::w.
    {
        return (this->l == otherL) &&
               (this->h == otherH) &&
               (this->w == otherW);
    };
template<typename RealType , typename ElementType > bool corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord (const IndexType z, const IndexType y, const IndexType x) const [inline]
Checks if coordinate lies within the buffer area.
Definition at line 120 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::h, corecvs::VoxelBufferBase< RealType, ElementType >::l, and corecvs::VoxelBufferBase< RealType, ElementType >::w.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord().
    {
        return (x >= 0) && (x < w) &&
               (y >= 0) && (y < h) &&
               (z >= 0) && (z < l);
    };
template<typename RealType , typename ElementType > bool corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord (const Vector2d< IndexType > & p) const [inline]
Checks if coordinate lies within the buffer area.
Definition at line 130 of file voxelBuffer.h.
References corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        return isValidCoord(p.z(), p.y(), p.x());
    };
Member Data Documentation
template<typename RealType , typename ElementType > ElementType* corecvs::VoxelBufferBase< RealType, ElementType >::element
The array of the data elements.
Definition at line 62 of file voxelBuffer.h.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::_init(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), and corecvs::VoxelBufferBase< RealType, ElementType >::~FixedArrayBase().
template<typename RealType , typename ElementType > int corecvs::VoxelBufferBase< RealType, ElementType >::h
Definition at line 65 of file voxelBuffer.h.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::_init(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::VoxelBufferBase< RealType, ElementType >::getH(), corecvs::VoxelBufferBase< RealType, ElementType >::getSize(), corecvs::VoxelBufferBase< RealType, ElementType >::hasSameSize(), and corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord().
template<typename RealType , typename ElementType > int corecvs::VoxelBufferBase< RealType, ElementType >::l
Definition at line 64 of file voxelBuffer.h.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::_init(), corecvs::VoxelBufferBase< RealType, ElementType >::getL(), corecvs::VoxelBufferBase< RealType, ElementType >::getSize(), corecvs::VoxelBufferBase< RealType, ElementType >::hasSameSize(), and corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord().
template<typename RealType , typename ElementType > MemoryBlockRef corecvs::VoxelBufferBase< RealType, ElementType >::memoryBlock
Memory block that holds the data.
Definition at line 57 of file voxelBuffer.h.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::_init().
template<typename RealType , typename ElementType > int corecvs::VoxelBufferBase< RealType, ElementType >::size
Definition at line 68 of file voxelBuffer.h.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::_init(), and corecvs::VoxelBufferBase< RealType, ElementType >::~FixedArrayBase().
template<typename RealType , typename ElementType > int corecvs::VoxelBufferBase< RealType, ElementType >::w
Definition at line 66 of file voxelBuffer.h.
Referenced by corecvs::VoxelBufferBase< RealType, ElementType >::_init(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::VoxelBufferBase< RealType, ElementType >::getSize(), corecvs::VoxelBufferBase< RealType, ElementType >::getW(), corecvs::VoxelBufferBase< RealType, ElementType >::hasSameSize(), and corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord().
The documentation for this class was generated from the following file:
core/buffers/voxels/voxelBuffer.h