DeepView: FilterSelector Class Reference
FilterSelector Class Reference
#include <filterSelector.h>
Public Slots
void addFilter (void)
void deleteFilter (void)
void activateFilter (QListWidgetItem *)
void upFilter (void)
void downFilter (void)
void parametersChangedSlot (void)
Signals
void parametersChanged (void)
Public Member Functions
FilterSelector (QString name=QString("FilterSelector"), QWidget *parent=0)
~FilterSelector ()
FilterSelectorParameters * getParameters ()
Static Public Member Functions
static
FilterParametersControlWidgetBase * widgetFromName (const char *name)
static AbstractFilter * executerFromName (const char *name)
static QVector< const char * > getFilterNames ()
Private Attributes
Ui_FilterSelectorClass ui
QVector
< FilterParametersControlWidgetBase * > mFilters
QVector< const char * > mAllFilters
QWidget * currentWidget
bool isContinious
Detailed Description
Definition at line 74 of file filterSelector.h.
Constructor & Destructor Documentation
FilterSelector::FilterSelector (QString name = QString("FilterSelector"), QWidget * parent = 0)
Definition at line 19 of file filterSelector.cpp.
References activateFilter(), addFilter(), currentWidget, deleteFilter(), downFilter(), getFilterNames(), mAllFilters, ui, and upFilter().
    : QWidget(parent)
{
    ui.setupUi(this);
    connect(ui.useButton, SIGNAL(released()), this, SLOT(addFilter()));
    connect(ui.deleteButton, SIGNAL(released()), this, SLOT(deleteFilter()));
    connect(ui.filtersWidget, SIGNAL(itemActivated(QListWidgetItem *)), this, SLOT(activateFilter(QListWidgetItem *)));
    connect(ui.upButton, SIGNAL(released()), this, SLOT(upFilter()));
    connect(ui.downButton, SIGNAL(released()), this, SLOT(downFilter()));
    currentWidget = NULL;
//    input = NULL;
    mAllFilters = getFilterNames();
    QVector<const char *>::iterator iterator;
    int i = 0;
    for (iterator = mAllFilters.begin(); iterator != mAllFilters.end(); ++iterator, ++i)
    {
        ui.allFiltersWidget->addItem(new FilterListIdWidgetItem(*iterator));
    }
    this->setWindowTitle(QString("Filter Selector:") + name);
}
FilterSelector::~FilterSelector () [inline]
Definition at line 95 of file filterSelector.h.
{}
Member Function Documentation
void FilterSelector::activateFilter (QListWidgetItem * item) [slot]
Definition at line 153 of file filterSelector.cpp.
References currentWidget, and ui.
Referenced by FilterSelector().
{
    if (currentWidget != NULL)
    {
        //printf("Removing current widget: %s\n", currentWidget->getInstanceName().toAscii().constData());
        ui.gridLayout->removeWidget(currentWidget);
        currentWidget->setParent(NULL);
        currentWidget = NULL;
    } else {
        printf("Not removing current widget:\n");
    }
    currentWidget = ((FilterListWidgetItem *)item)->parametersWidget;
    //printf("Adding current widget: %s\n", currentWidget->getInstanceName().toAscii().constData());
    ui.gridLayout->addWidget(currentWidget, 4, 0, 1, 2);
    this->update();
}
void FilterSelector::addFilter (void) [slot]
Definition at line 51 of file filterSelector.cpp.
References mFilters, FilterListIdWidgetItem::name, parametersChanged(), parametersChangedSlot(), ui, and widgetFromName().
Referenced by FilterSelector().
{
    qDebug("FilterSelector::addFilter() called\n");
    QList<QListWidgetItem *> items = ui.allFiltersWidget->selectedItems();
    QList<QListWidgetItem *>::iterator addItems;
    for (addItems = items.begin(); addItems != items.end(); ++addItems)
    {
        const FilterListIdWidgetItem *item = static_cast<const FilterListIdWidgetItem *>(*addItems);
        const char* filterName = item->name;
        qDebug("Adding filter:%s\n", filterName );
        FilterParametersControlWidgetBase *filter = widgetFromName(filterName);
        if (filter == NULL) {
            continue;
        }
        mFilters.append(filter);
        QListWidgetItem *newItem = new FilterListWidgetItem(filter, filterName);
        ui.filtersWidget->addItem(newItem);
        connect(filter, SIGNAL(paramsChanged()), this, SLOT(parametersChangedSlot()));
    }
    if (items.size() != 0)
    {
        qDebug("FilterAdded: Emitting params changed...\n");
        ui.filtersWidget->update();
        emit parametersChanged();
    }
}
void FilterSelector::deleteFilter (void) [slot]
Definition at line 84 of file filterSelector.cpp.
References currentWidget, mFilters, parametersChanged(), parametersChangedSlot(), and ui.
Referenced by FilterSelector().
{
    QList<QListWidgetItem *> items = ui.filtersWidget->selectedItems();
    QList<QListWidgetItem *>::iterator itemIterator;
    QList<QListWidgetItem *> toDelete;
    for (itemIterator = items.begin(); itemIterator != items.end(); ++itemIterator)
    {
        QListWidgetItem *item = (*itemIterator);
        FilterParametersControlWidgetBase *filter = ((FilterListWidgetItem *) item)->parametersWidget;
        if (filter == currentWidget)
        {
            ui.gridLayout->removeWidget(currentWidget);
            currentWidget->setParent(NULL);
            currentWidget  = NULL;
        }
        int index = mFilters.indexOf(filter);
        mFilters.remove(index);
        toDelete.append(item);
        disconnect(filter, SIGNAL(paramsChanged()), this, SLOT(parametersChangedSlot()));
    }
    for (itemIterator = toDelete.begin(); itemIterator != toDelete.end(); ++itemIterator)
    {
        ui.filtersWidget->removeItemWidget(*itemIterator);
        delete_safe(*itemIterator);
    }
    if (items.size() != 0)
    {
        qDebug("Filters Deleted: Emitting params changed...\n");
        emit parametersChanged();
    }
}
void FilterSelector::downFilter (void) [slot]
Definition at line 137 of file filterSelector.cpp.
References mFilters, parametersChanged(), and ui.
Referenced by FilterSelector().
{
    int index = ui.filtersWidget->currentIndex().row();
    if (index == ui.filtersWidget->count() - 1)
        return;
    QListWidgetItem *toSwap = ui.filtersWidget->takeItem(index + 1);
    ui.filtersWidget->insertItem(index, toSwap);
    FilterParametersControlWidgetBase *currentFilter = mFilters.at(index);
    mFilters.remove(index);
    mFilters.insert(index + 1, currentFilter);
    printf("Filter Moved Down: Emitting params changed...\n");
    emit parametersChanged();
}
AbstractFilter * FilterSelector::executerFromName (const char * name) [static]
Definition at line 201 of file filterSelector.cpp.
Referenced by corecvs::FilterExecuter::setParameters().
{
    (void)name;
//    if (name == QString(GainOffsetFilter::getName()))
//       return new GainOffsetFilter();
//    if (name == QString(BitSelectorFilter::getName()))
//       return new BitSelectorFilter();
//    if (name == QString(SobelFilter::getTypeName()))
//       return new SobelFilter();
//    if (name == QString(CannyFilter::getName()))
//       return new CannyFilter();
//#ifdef WITH_OPENCV
//    if (name == QString(OpenCVFilter::getName()))
//       return new OpenCVFilter();
//#endif
//    if (name == QString(BackgroundFilter::getName()))
//        return new BackgroundFilter();
    return NULL;
}
QVector< const char * > FilterSelector::getFilterNames () [static]
Definition at line 221 of file filterSelector.cpp.
Referenced by FilterSelector().
{
    QVector<const char *> list;
//    list.append(GainOffsetFilter::getName());
//    list.append(BitSelectorFilter::getName());
//    list.append(SobelFilter::getTypeName());
//    list.append(CannyFilter::getName());
//#ifdef WITH_OPENCV
//    list.append(OpenCVFilter::getName());
//#endif
//    list.append(BackgroundFilter::getName());
    return list;
}
FilterSelectorParameters * FilterSelector::getParameters ()
Definition at line 235 of file filterSelector.cpp.
References FilterSelectorParameters::addFilter(), FilterParametersControlWidgetBase::createParametersVirtual(), mFilters, FilterListWidgetItem::name, and ui.
{
    qDebug("FilterSelector::getParameters(): called\n");
    FilterSelectorParameters *toReturn = new FilterSelectorParameters();
    for (int i = 0; i < mFilters.size(); i++)
    {
        FilterParametersControlWidgetBase *filter = mFilters[i];
        BaseReflectionStatic *params = filter->createParametersVirtual();
        FilterListWidgetItem *item = static_cast<FilterListWidgetItem *>(ui.filtersWidget->item(i));
        toReturn->addFilter(item->name, params);
        if (params == NULL)
        {
            qDebug() << "We have recieved NULL parameters from " << item->name << endl;
        }
        //toReturn->filters.push_back(filter->create);
    }
    return toReturn;
}
void FilterSelector::parametersChanged (void) [signal]
Referenced by addFilter(), deleteFilter(), downFilter(), parametersChangedSlot(), and upFilter().
void FilterSelector::parametersChangedSlot (void) [slot]
Definition at line 45 of file filterSelector.cpp.
References parametersChanged().
Referenced by addFilter(), and deleteFilter().
{
    qDebug("FilterSelector::Child widget changed. Emitting params changed...\n");
    emit parametersChanged();
}
void FilterSelector::upFilter (void) [slot]
Definition at line 121 of file filterSelector.cpp.
References mFilters, parametersChanged(), and ui.
Referenced by FilterSelector().
{
    int index = ui.filtersWidget->currentIndex().row();
    if (index == 0)
        return;
    QListWidgetItem *toSwap = ui.filtersWidget->takeItem(index - 1);
    ui.filtersWidget->insertItem(index, toSwap);
    FilterParametersControlWidgetBase *currentFilter = mFilters.at(index);
    mFilters.remove(index);
    mFilters.insert(index - 1, currentFilter);
    printf("Filter Moved Up: Emitting params changed...\n");
    emit parametersChanged();
}
FilterParametersControlWidgetBase * FilterSelector::widgetFromName (const char * name) [static]
Definition at line 181 of file filterSelector.cpp.
Referenced by addFilter().
{
    (void)name;
//    if (name == QString(GainOffsetFilter::getName()))
//       return new GainOffsetParametersControlWidget();
//    if (name == QString(BitSelectorFilter::getName()))
//       return new BitSelectorParametersControlWidget();
//    if (name == QString(SobelFilter::getTypeName()))
//       return new SobelParametersControlWidget();
//    if (name == QString(CannyFilter::getName()))
//       return new CannyParametersControlWidget();
//#ifdef WITH_OPENCV
//    if (name == QString(OpenCVFilter::getName()))
//       return new OpenCVFilterParametersControlWidget();
//#endif
//    if (name == QString(BackgroundFilter::getName()))
//        return new BackgroundFilterParametersControlWidget();
   return NULL;
}
Member Data Documentation
QWidget* FilterSelector::currentWidget [private]
Definition at line 110 of file filterSelector.h.
Referenced by activateFilter(), deleteFilter(), and FilterSelector().
bool FilterSelector::isContinious [private]
Definition at line 112 of file filterSelector.h.
QVector<const char *> FilterSelector::mAllFilters [private]
Definition at line 107 of file filterSelector.h.
Referenced by FilterSelector().
QVector<FilterParametersControlWidgetBase *> FilterSelector::mFilters [private]
Definition at line 106 of file filterSelector.h.
Referenced by addFilter(), deleteFilter(), downFilter(), getParameters(), and upFilter().
Ui_FilterSelectorClass FilterSelector::ui [private]
Definition at line 104 of file filterSelector.h.
Referenced by activateFilter(), addFilter(), deleteFilter(), downFilter(), FilterSelector(), getParameters(), and upFilter().
The documentation for this class was generated from the following files:
utils/filters/filterSelector.h
utils/filters/filterSelector.cpp