DeepView: DefaultSetterOld Class Reference
DefaultSetterOld Class Reference
#include <defaultSetterOld.h>
Public Member Functions
template<class Type >
void visit (Type &field, Type defaultValue, const char *fieldName)
template<typename FieldReflectionType >
void visit (typename FieldReflectionType::CPPType &field, const FieldReflectionType *fieldDescriptor)
template<>
void visit (int &intField, int defaultValue, const char *)
template<>
void visit (double &doubleField, double defaultValue, const char *)
template<>
void visit (bool &boolField, bool defaultValue, const char *)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
template<>
void visit (void *&field, const PointerField *)
template<>
void visit (EnumField::CPPType &field, const EnumField *fieldDescriptor)
template<>
void visit (int &intField, int defaultValue, const char *)
template<>
void visit (double &doubleField, double defaultValue, const char *)
template<>
void visit (bool &boolField, bool defaultValue, const char *)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
template<>
void visit (void *&field, const PointerField *fieldDescriptor)
template<>
void visit (EnumField::CPPType &field, const EnumField *fieldDescriptor)
string getCurrentPath ()
string getChildPath (string child)
void pushChild (const string child)
void popChild ()
Public Attributes
string separator
T elements
STL member.
Static Public Attributes
static string SEPARATOR_DEFAULT = "."
Detailed Description
Definition at line 7 of file defaultSetterOld.h.
Member Function Documentation
string corecvs::BasePathVisitor::getChildPath (string child) [inline, inherited]
Definition at line 35 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getCurrentPath(), and corecvs::BasePathVisitor::separator.
Referenced by corecvs::BasePathVisitor::pushChild().
    {
       string newPath = getCurrentPath();
       if (!newPath.empty())
           newPath.append(separator);
       newPath.append(child);
       return newPath;
    }
string corecvs::BasePathVisitor::getCurrentPath () [inline, inherited]
Definition at line 28 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
    {
        if (empty())
            return "";
        return back();
    }
void corecvs::BasePathVisitor::popChild () [inline, inherited]
Definition at line 55 of file basePathVisitor.h.
Referenced by visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        pop_back();
    }
void corecvs::BasePathVisitor::pushChild (const string child) [inline, inherited]
Definition at line 50 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getChildPath().
Referenced by visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        push_back(getChildPath(child));
    }
template<> void DefaultSetterOld::visit (int & intField, int defaultValue, const char *)
Definition at line 5 of file defaultSetterOld.cpp.
{
    intField = defaultValue;
}
template<class Type > void DefaultSetterOld::visit (Type & field, Type defaultValue, const char * fieldName)
Definition at line 23 of file defaultSetterOld.cpp.
References corecvs::BasePathVisitor::popChild(), and corecvs::BasePathVisitor::pushChild().
{
    pushChild(fieldName);
        field.accept(*this);
    popChild();
}
template<> void DefaultSetterOld::visit (double & doubleField, double defaultValue, const char *)
Definition at line 11 of file defaultSetterOld.cpp.
{
    doubleField = defaultValue;
}
template<typename FieldReflectionType > void DefaultSetterOld::visit (typename FieldReflectionType::CPPType & field, const FieldReflectionType * fieldDescriptor)
Definition at line 72 of file defaultSetterOld.cpp.
{
    field.accept(*this);
}
template<> void DefaultSetterOld::visit (bool & boolField, bool defaultValue, const char *)
Definition at line 17 of file defaultSetterOld.cpp.
{
    boolField = defaultValue;
}
template<> void DefaultSetterOld::visit (int & intField, int defaultValue, const char *)
template<> void DefaultSetterOld::visit (double & doubleField, double defaultValue, const char *)
template<> void DefaultSetterOld::visit (bool & boolField, bool defaultValue, const char *)
template<> void DefaultSetterOld::visit (int & field, const IntField * fieldDescriptor)
template<> void DefaultSetterOld::visit (int & field, const IntField * fieldDescriptor)
Definition at line 31 of file defaultSetterOld.cpp.
{
    field = fieldDescriptor->defaultValue;
}
template<> void DefaultSetterOld::visit (double & field, const DoubleField * fieldDescriptor)
template<> void DefaultSetterOld::visit (bool & field, const BoolField * fieldDescriptor)
template<> void DefaultSetterOld::visit (double & field, const DoubleField * fieldDescriptor)
Definition at line 39 of file defaultSetterOld.cpp.
{
    field = fieldDescriptor->defaultValue;
}
template<> void DefaultSetterOld::visit (void *& field, const PointerField * fieldDescriptor)
template<> void DefaultSetterOld::visit (EnumField::CPPType & field, const EnumField * fieldDescriptor)
template<> void DefaultSetterOld::visit (bool & field, const BoolField * fieldDescriptor)
Definition at line 47 of file defaultSetterOld.cpp.
{
    field = fieldDescriptor->defaultValue;
}
template<> void DefaultSetterOld::visit (void *& field, const PointerField *)
Definition at line 55 of file defaultSetterOld.cpp.
{
    field = NULL;
}
template<> void DefaultSetterOld::visit (EnumField::CPPType & field, const EnumField * fieldDescriptor)
Definition at line 63 of file defaultSetterOld.cpp.
{
    field = fieldDescriptor->defaultValue;
}
Member Data Documentation
template<typename T> T std::deque< T >::elements [inherited]
STL member.
string corecvs::BasePathVisitor::separator [inherited]
Definition at line 26 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
string corecvs::BasePathVisitor::SEPARATOR_DEFAULT = "." [static, inherited]
Definition at line 24 of file basePathVisitor.h.
The documentation for this class was generated from the following files:
utils/visitors/defaultSetterOld.h
utils/visitors/defaultSetterOld.cpp