DeepView: corecvs::BaseSegment< ThisType > Class Template Reference
corecvs::BaseSegment< ThisType > Class Template Reference
This is a generic class that desribes the part of the whole connected component.
#include <segmentator.h>
Public Member Functions
BaseSegment ()
Default constructor initializes father to NULL which means that this is a top element.
ThisType * getFather ()
Getter for father.
bool isTop ()
Checks if it is a child segment or not.
ThisType * getTopFather ()
This method returns a topmost segment in a father tree.
void markMerge (ThisType *other)
This method merges two trees of child segments.
void dadify ()
Public Attributes
ThisType * father
The father segment in a merge tree during the merge phase TODO: Make this private.
Detailed Description
template<typename ThisType>
class corecvs::BaseSegment< ThisType >
This is a generic class that desribes the part of the whole connected component.
It is advised that the real segment inherit form this class.
Definition at line 35 of file segmentator.h.
Constructor & Destructor Documentation
template<typename ThisType> corecvs::BaseSegment< ThisType >::BaseSegment () [inline]
Default constructor initializes father to NULL which means that this is a top element.
Definition at line 46 of file segmentator.h.
    {
        father = NULL;
    }
Member Function Documentation
template<typename ThisType> void corecvs::BaseSegment< ThisType >::dadify () [inline]
Reimplemented in corecvs::CornerSegment, and corecvs::TileSegment.
Definition at line 81 of file segmentator.h.
    {
        if (!isTop())
            father = getTopFather();
    }
template<typename ThisType> ThisType* corecvs::BaseSegment< ThisType >::getFather () [inline]
Getter for father.
Definition at line 52 of file segmentator.h.
    {
        return father;
    };
template<typename ThisType> ThisType* corecvs::BaseSegment< ThisType >::getTopFather () [inline]
This method returns a topmost segment in a father tree.
Definition at line 64 of file segmentator.h.
Referenced by corecvs::Clustering3D::_clustering(), corecvs::Clustering3D::clustering(), corecvs::BaseSegment< CornerSegment >::dadify(), and corecvs::BaseSegment< CornerSegment >::markMerge().
    {
        ThisType *toReturn = (ThisType *)this;
        while (toReturn->getFather() != NULL)
            toReturn = toReturn->getFather();
        return toReturn;
    }
template<typename ThisType> bool corecvs::BaseSegment< ThisType >::isTop () [inline]
Checks if it is a child segment or not.
Definition at line 58 of file segmentator.h.
Referenced by corecvs::Clustering3D::_clustering(), corecvs::Clustering3D::clustering(), and corecvs::BaseSegment< CornerSegment >::dadify().
    {
        return (father == NULL);
    }
template<typename ThisType> void corecvs::BaseSegment< ThisType >::markMerge (ThisType * other) [inline]
This method merges two trees of child segments.
Definition at line 73 of file segmentator.h.
Referenced by corecvs::Clustering3D::_clustering(), and corecvs::Clustering3D::clustering().
    {
        ThisType *thisTopFather  = this->getTopFather();
        ThisType *otherTopFather = other->getTopFather();
        if (otherTopFather != thisTopFather)
            otherTopFather->father = thisTopFather;
    }
Member Data Documentation
template<typename ThisType> ThisType* corecvs::BaseSegment< ThisType >::father
The father segment in a merge tree during the merge phase TODO: Make this private.
Definition at line 43 of file segmentator.h.
Referenced by corecvs::BaseSegment< CornerSegment >::BaseSegment(), corecvs::BaseSegment< CornerSegment >::dadify(), corecvs::BaseSegment< CornerSegment >::getFather(), and corecvs::BaseSegment< CornerSegment >::isTop().
The documentation for this class was generated from the following file:
core/segmentation/segmentator.h