DeepView: corecvs::DirectRemapper::ParallelRemap Class Reference
corecvs::DirectRemapper::ParallelRemap Class Reference
#include <displacementBuffer.h>
Public Member Functions
void operator() (const BlockedRange< int > &r) const
ParallelRemap (G12Buffer *_result, G12Buffer *_input, DirectRemapper *_remapper)
Private Attributes
G12Buffer * result
G12Buffer * input
DirectRemapper * remapper
Detailed Description
Definition at line 178 of file displacementBuffer.h.
Constructor & Destructor Documentation
corecvs::DirectRemapper::ParallelRemap::ParallelRemap (G12Buffer * _result, G12Buffer * _input, DirectRemapper * _remapper) [inline]
Definition at line 198 of file displacementBuffer.h.
                                                                                        :
        result(_result), input(_input), remapper(_remapper)
        {}
Member Function Documentation
void corecvs::DirectRemapper::ParallelRemap::operator() (const BlockedRange< int > & r) const [inline]
Definition at line 185 of file displacementBuffer.h.
References corecvs::BlockedRange< IndexType >::begin(), corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::BlockedRange< IndexType >::end(), input, corecvs::DirectRemapper::mOffsets, corecvs::DirectRemapper::mOutputW, remapper, and result.
        {
            for (int i = r.begin(); i < r.end(); i++)
            {
                uint16_t *offsetResult = &result->element(i, 0);
                Vector2d32 *offsetMap  = &remapper->mOffsets[i * remapper->mOutputW];
                for (int j = 0; j < remapper->mOutputW; j++)
                {
                    Vector2d32 oldCoord = *offsetMap++;
                    *offsetResult++ = input->element(oldCoord);
                }
            }
        }
Member Data Documentation
G12Buffer* corecvs::DirectRemapper::ParallelRemap::input [private]
Definition at line 181 of file displacementBuffer.h.
Referenced by operator()().
DirectRemapper* corecvs::DirectRemapper::ParallelRemap::remapper [private]
Definition at line 182 of file displacementBuffer.h.
Referenced by operator()().
G12Buffer* corecvs::DirectRemapper::ParallelRemap::result [private]
Definition at line 180 of file displacementBuffer.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
core/buffers/displacementBuffer.h