DeepView: InputBlockPresentation Class Reference
InputBlockPresentation Class Reference
#include <inputBlockPresentation.h>
Public Types
enum { Type = UserType + 15 }
Public Slots
void parametersChanged ()
Signals
void paramsChanged ()
Public Member Functions
InputBlockPresentation (FilterBlock *_block, FilterParametersControlWidgetBase *_widget, DiagramScene *_scene)
virtual void draw (int x, int y)
*---------------------------------------------* | | |< >| | Type | |< >| | Name | | >| | | *---------------------------------------------*
void createPinPresentations ()
void clearPinPresentations ()
void clearPinPresentations (vector< FilterPinPresentation * > &vec)
void drawBlock (int x, int y)
void drawInputPins ()
void drawOutputPins ()
void drawBlockName ()
void updateBlock ()
void finishInit ()
void removeArrow (Arrow *arrow)
void removeArrows ()
QPolygonF polygon () const
void addArrow (Arrow *arrow)
int type () const
virtual void foo ()
Public Attributes
FilterBlock * mBlock
FilterParametersControlWidgetBase * widget
char * blockName
int level
DiagramScene * scene
vector< FilterPinPresentation * > mInputPins
vector< FilterPinPresentation * > mOutputPins
DiagramTextItem * textItem
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Protected Attributes
QPolygonF myPolygon
Detailed Description
Definition at line 6 of file inputBlockPresentation.h.
Member Enumeration Documentation
anonymous enum [inherited]
Enumerator:
Type
Definition at line 55 of file diagramitem.h.
{ Type = UserType + 15 };
Constructor & Destructor Documentation
InputBlockPresentation::InputBlockPresentation (FilterBlock * _block, FilterParametersControlWidgetBase * _widget, DiagramScene * _scene) [inline]
Definition at line 9 of file inputBlockPresentation.h.
                                                :
        FilterBlockPresentation(_block, _widget, _scene)
    {}
Member Function Documentation
void DiagramItem::addArrow (Arrow * arrow) [inherited]
Definition at line 73 of file diagramitem.cpp.
References DiagramItem::arrows.
Referenced by DiagramScene::addArrow().
{
    arrows.append(arrow);
}
void FilterBlockPresentation::clearPinPresentations () [inherited]
Definition at line 108 of file filterBlockPresentation.cpp.
References FilterBlockPresentation::mInputPins, and FilterBlockPresentation::mOutputPins.
Referenced by FilterBlockPresentation::updateBlock(), and FilterBlockPresentation::~FilterBlockPresentation().
{
    clearPinPresentations(mInputPins);
    clearPinPresentations(mOutputPins);
//    for (unsigned int i = 0; i < mInputPins.size(); i++)
//    {   scene->removeItem(mInputPins[i]);
//        delete_safe(mInputPins[i]);
//    }
//    mInputPins.clear();
//    for (unsigned int i = 0; i < mOutputPins.size(); i++)
//    {   scene->removeItem(mOutputPins[i]);
//        delete_safe(mOutputPins[i]);
//    }
//    mOutputPins.clear();
}
void FilterBlockPresentation::clearPinPresentations (vector< FilterPinPresentation * > & vec) [inherited]
Definition at line 125 of file filterBlockPresentation.cpp.
References FilterBlockPresentation::scene.
{
    for (unsigned int i = 0; i < vec.size(); i++)
    {   scene->removeItem(vec[i]);
        delete_safe(vec[i]);
    }
    vec.clear();
}
void FilterBlockPresentation::createPinPresentations () [inherited]
Definition at line 97 of file filterBlockPresentation.cpp.
References FilterPinPresentation::getPinByType(), corecvs::FilterBlock::inputPins, FilterBlockPresentation::mBlock, FilterBlockPresentation::mInputPins, FilterBlockPresentation::mOutputPins, corecvs::FilterBlock::outputPins, FilterBlockPresentation::scene, and corecvs::FilterBlock::sort.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), and FilterBlockPresentation::updateBlock().
{
    if (mBlock->sort != FilterBlock::INPUT_FILTER)
        for (unsigned int i = 0; i < mBlock->inputPins.size(); i++)
            mInputPins.push_back(FilterPinPresentation::getPinByType(mBlock->inputPins[i], scene, this));
    if (mBlock->sort != FilterBlock::OUTPUT_FILTER)
        for (unsigned int i = 0; i < mBlock->outputPins.size(); i++)
            mOutputPins.push_back(FilterPinPresentation::getPinByType(mBlock->outputPins[i], scene, this));
}
void FilterBlockPresentation::draw (int x, int y) [virtual, inherited]
*---------------------------------------------* | | |< >| | Type | |< >| | Name | | >| | | *---------------------------------------------*
Definition at line 38 of file filterBlockPresentation.cpp.
References FilterBlockPresentation::drawBlock(), FilterBlockPresentation::drawInputPins(), and FilterBlockPresentation::drawOutputPins().
Referenced by FilterGraphPresentation::addFilter(), FilterGraphPresentation::drawGraph(), FilterGraphPresentation::restoreFromGraph(), and FilterBlockPresentation::updateBlock().
{
    drawBlock(x, y);
    drawInputPins();
    drawOutputPins();
} // draw
void FilterBlockPresentation::drawBlock (int x, int y) [inherited]
Definition at line 45 of file filterBlockPresentation.cpp.
References DiagramScene::itemColor(), FilterBlockPresentation::mBlock, FilterBlockPresentation::scene, corecvs::FilterBlock::x, and corecvs::FilterBlock::y.
Referenced by FilterBlockPresentation::draw().
{
    mBlock->x = x;
    mBlock->y = y;
    setBrush(scene->itemColor());
    setPos(x, y);
}
void FilterBlockPresentation::drawBlockName () [inherited]
Definition at line 134 of file filterBlockPresentation.cpp.
References FilterBlockPresentation::blockName, DiagramScene::font(), corecvs::FilterBlock::getTypeName(), FilterBlockPresentation::mBlock, FilterBlockPresentation::scene, DiagramScene::textColor(), and FilterBlockPresentation::textItem.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), and FilterGraphPresentation::nameChanged().
{
    textItem->setFont(scene->font());
    textItem->setZValue(1000.0);
    textItem->setPlainText(QString("\"")+ QString(mBlock->getTypeName()) + QString("\" ") + QString(blockName));
    textItem->setDefaultTextColor(scene->textColor());
    double hRect = textItem->boundingRect().right() - textItem->boundingRect().left();
    double wRect = textItem->boundingRect().top()   - textItem->boundingRect().bottom();
    textItem->setPos(-hRect/2, wRect/2);
}
void FilterBlockPresentation::drawInputPins () [inherited]
Definition at line 54 of file filterBlockPresentation.cpp.
References FilterBlockPresentation::mInputPins, DiagramItem::polygon(), and FilterBlockPresentation::scene.
Referenced by CompoundBlockPresentation::addInputPin(), FilterBlockPresentation::draw(), and CompoundBlockPresentation::removeInputPin().
{
    int xPin, yPin;
    double left   = polygon()[0].x();
    double top    = polygon()[0].y();
    double right  = -left;
    double width  = right - left;
    int totalInputPins  = (int)mInputPins.size();
    int inputStep       = (int)(width / (totalInputPins + 1));
    for (int i = 0; i < totalInputPins; i++)
    {
        xPin = left + inputStep*(i+1);
        yPin = top;
        mInputPins[i]->draw(scene, this, xPin, yPin);
        mInputPins[i]->drawInputPinName();
    }
}
void FilterBlockPresentation::drawOutputPins () [inherited]
Definition at line 75 of file filterBlockPresentation.cpp.
References FilterBlockPresentation::mOutputPins, DiagramItem::polygon(), and FilterBlockPresentation::scene.
Referenced by CompoundBlockPresentation::addOutputPin(), FilterBlockPresentation::draw(), and CompoundBlockPresentation::removeOutputPin().
{
    int xPin, yPin;
    double left   = polygon()[0].x();
    double top    = polygon()[0].y();
    double right  = -left;
    double bottom = -top;
    double width  = right - left;
    int totalOutputPins = (int)mOutputPins.size();
    int outputStep      = (int)(width / (totalOutputPins + 1));
    for (int i = 0; i < totalOutputPins; i++)
    {
        xPin = left + outputStep*(i+1);
        yPin = bottom;
        mOutputPins[i]->draw(scene, this, xPin, yPin);
        mOutputPins[i]->drawOutputPinName();
    }
}
void DiagramItem::finishInit () [inherited]
Definition at line 47 of file diagramitem.cpp.
References DiagramItem::myPolygon.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), and FilterPinPresentation::FilterPinPresentation().
{
    setPolygon(myPolygon);
    setFlag(QGraphicsItem::ItemSendsGeometryChanges, true);
}
virtual void DiagramItem::foo () [inline, virtual, inherited]
Definition at line 70 of file diagramitem.h.
{}
QVariant DiagramItem::itemChange (GraphicsItemChange change, const QVariant & value) [protected, inherited]
Definition at line 78 of file diagramitem.cpp.
References DiagramItem::arrows, and Arrow::updatePosition().
{
    if (change == QGraphicsItem::ItemPositionChange)
        foreach (Arrow *arrow, arrows)
            arrow->updatePosition();
    return value;
}
void FilterBlockPresentation::parametersChanged (void) [inline, slot, inherited]
Definition at line 62 of file filterBlockPresentation.h.
References FilterParametersControlWidgetBase::createParametersVirtual(), FilterBlockPresentation::mBlock, FilterBlockPresentation::paramsChanged(), corecvs::FilterBlock::setParameters(), and FilterBlockPresentation::widget.
   {
       mBlock->setParameters(widget->createParametersVirtual());
       emit paramsChanged();
   }
void FilterBlockPresentation::paramsChanged () [signal, inherited]
Referenced by FilterBlockPresentation::parametersChanged().
QPolygonF DiagramItem::polygon () const [inline, inherited]
Definition at line 66 of file diagramitem.h.
Referenced by FilterBlockPresentation::drawInputPins(), FilterBlockPresentation::drawOutputPins(), and Arrow::paint().
        { return myPolygon; }
void DiagramItem::removeArrow (Arrow * arrow) [inherited]
Definition at line 53 of file diagramitem.cpp.
References DiagramItem::arrows.
Referenced by FilterGraphPresentation::deleteItem(), and DiagramItem::removeArrows().
{
    int index = arrows.indexOf(arrow);
    if (index != -1)  arrows.removeAt(index);
}
void DiagramItem::removeArrows () [inherited]
Definition at line 59 of file diagramitem.cpp.
References DiagramItem::arrows, Arrow::endItem(), DiagramItem::removeArrow(), and Arrow::startItem().
Referenced by FilterGraphPresentation::deleteItem(), and DiagramItem::~DiagramItem().
{
    foreach (Arrow *arrow, arrows)
    {   arrow->startItem()->removeArrow(arrow);
        arrow->endItem()->removeArrow(arrow);
        delete_safe(arrow);
    }
}
int DiagramItem::type () const [inline, inherited]
Definition at line 69 of file diagramitem.h.
{ return Type;}
void FilterBlockPresentation::updateBlock () [inherited]
Definition at line 146 of file filterBlockPresentation.cpp.
References FilterBlockPresentation::blockName, FilterBlockPresentation::clearPinPresentations(), FilterBlockPresentation::createPinPresentations(), FilterBlockPresentation::draw(), corecvs::FilterBlock::getInstanceName(), FilterBlockPresentation::mBlock, corecvs::FilterBlock::x, and corecvs::FilterBlock::y.
Referenced by FilterGraphPresentation::renewCompoundFilters(), and FilterGraphPresentation::updateGraph().
{
    clearPinPresentations();
    createPinPresentations();
    blockName = mBlock->getInstanceName();
    draw(mBlock->x, mBlock->y);
}
Member Data Documentation
char* FilterBlockPresentation::blockName [inherited]
Definition at line 19 of file filterBlockPresentation.h.
Referenced by FilterGraphPresentation::blockItemSelected(), FilterBlockPresentation::drawBlockName(), FilterBlockPresentation::FilterBlockPresentation(), FilterGraphPresentation::FilterGraphPresentation(), FilterGraphPresentation::nameChanged(), and FilterBlockPresentation::updateBlock().
int FilterBlockPresentation::level [inherited]
Definition at line 20 of file filterBlockPresentation.h.
Referenced by FilterGraphPresentation::drawGraph().
FilterBlock* FilterBlockPresentation::mBlock [inherited]
Definition at line 17 of file filterBlockPresentation.h.
Referenced by FilterGraphPresentation::blockItemSelected(), CompoundBlockPresentation::CompoundBlockPresentation(), FilterBlockPresentation::createPinPresentations(), FilterGraphPresentation::deleteItem(), FilterBlockPresentation::drawBlock(), FilterBlockPresentation::drawBlockName(), FilterGraphPresentation::drawGraph(), FilterBlockPresentation::FilterBlockPresentation(), DiagramScene::mouseDoubleClickEvent(), DiagramScene::mouseReleaseEvent(), FilterGraphPresentation::nameChanged(), FilterBlockPresentation::parametersChanged(), and FilterBlockPresentation::updateBlock().
vector<FilterPinPresentation*> FilterBlockPresentation::mInputPins [inherited]
Definition at line 23 of file filterBlockPresentation.h.
Referenced by CompoundBlockPresentation::addInputPin(), FilterBlockPresentation::clearPinPresentations(), FilterBlockPresentation::createPinPresentations(), FilterBlockPresentation::drawInputPins(), and CompoundBlockPresentation::removeInputPin().
vector<FilterPinPresentation*> FilterBlockPresentation::mOutputPins [inherited]
Definition at line 24 of file filterBlockPresentation.h.
Referenced by CompoundBlockPresentation::addOutputPin(), FilterBlockPresentation::clearPinPresentations(), FilterBlockPresentation::createPinPresentations(), FilterBlockPresentation::drawOutputPins(), and CompoundBlockPresentation::removeOutputPin().
QPolygonF DiagramItem::myPolygon [protected, inherited]
Definition at line 76 of file diagramitem.h.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), FilterPinPresentation::FilterPinPresentation(), and DiagramItem::finishInit().
DiagramScene* FilterBlockPresentation::scene [inherited]
Definition at line 21 of file filterBlockPresentation.h.
Referenced by CompoundBlockPresentation::addPin(), FilterBlockPresentation::clearPinPresentations(), FilterBlockPresentation::createPinPresentations(), FilterBlockPresentation::drawBlock(), FilterBlockPresentation::drawBlockName(), FilterBlockPresentation::drawInputPins(), FilterBlockPresentation::drawOutputPins(), FilterBlockPresentation::FilterBlockPresentation(), and CompoundBlockPresentation::removePin().
DiagramTextItem* FilterBlockPresentation::textItem [inherited]
Definition at line 57 of file filterBlockPresentation.h.
Referenced by FilterBlockPresentation::drawBlockName(), FilterBlockPresentation::FilterBlockPresentation(), and FilterBlockPresentation::~FilterBlockPresentation().
FilterParametersControlWidgetBase* FilterBlockPresentation::widget [inherited]
Definition at line 18 of file filterBlockPresentation.h.
Referenced by FilterGraphPresentation::blockItemSelected(), FilterBlockPresentation::parametersChanged(), and FilterGraphPresentation::restoreFromGraph().
The documentation for this class was generated from the following file:
utils/filters/graph/inputBlockPresentation.h