DeepView: GraphPlotDialog Class Reference
GraphPlotDialog Class Reference
#include <graphPlotDialog.h>
Public Slots
void childRepaint (QPaintEvent *event, QWidget *who)
void exportToCSV ()
void setGraphVisibility (int currentVisibility)
void selectGraph (QTableWidgetItem *, QTableWidgetItem *)
void closePrevItemEditor (QTableWidgetItem *, QTableWidgetItem *)
void editGraphName (QTableWidgetItem *)
void saveGraphName (QTableWidgetItem *)
void saveSettingsToFile ()
void loadSettingsFromFile ()
void resetSettings ()
void graphPlotParametersChanged ()
void setSnapshotValue (QMouseEvent *)
Signals
void askParentRepaint (QPaintEvent *event, QWidget *who)
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (QResizeEvent *event)
void notifyKeyPressEvent (QKeyEvent *event)
void notifyKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
GraphPlotDialog (QWidget *parent=0)
~GraphPlotDialog ()
unsigned getGraphId (QString name)
QString getGraphName (unsigned id)
void addGraphPoint (unsigned graphId, double value, bool isValid=true)
void addGraphPoint (QString graphName, double value, bool isValid=true)
void addMotionIntensity (const vector< double > &mData)
void update (void)
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
void setSavingRoot (const QString &root)
virtual void paintEvent (QPaintEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void loadParamWidget (WidgetLoader &)
virtual void saveParamWidget (WidgetSaver &)
Private Member Functions
void drawGrid (QPainter &painter)
void drawGridFixLine (QPainter &painter)
void setItemColor (QTableWidgetItem *)
void showGraphsValue (QTableWidget *)
Private Attributes
Ui::GraphPlotDialogClass mUi
QSharedPointer
< GraphPlotParameters > mGraphPlotParameters
vector< GraphHistory > mData
deque< vector< double > > mIntensity
int mMouseClickedValue
int mGraphShowPoint
QSignalMapper * mUpDownMapper
QString mRootPath
Static Private Attributes
static QColor mGraphPallete [] = { Qt::red, Qt::darkGreen, Qt::cyan, Qt::darkRed, Qt::darkBlue, Qt::darkMagenta }
Detailed Description
Definition at line 32 of file graphPlotDialog.h.
Constructor & Destructor Documentation
GraphPlotDialog::GraphPlotDialog (QWidget * parent = 0)
Definition at line 14 of file graphPlotDialog.cpp.
References ViAreaWidget::askParentRepaint(), childRepaint(), closePrevItemEditor(), editGraphName(), exportToCSV(), graphPlotParametersChanged(), loadSettingsFromFile(), mGraphPlotParameters, mGraphShowPoint, mMouseClickedValue, mUi, mUpDownMapper, ViAreaWidget::notifyParentMouseRelease(), resetSettings(), saveGraphName(), saveSettingsToFile(), selectGraph(), setGraphVisibility(), and setSnapshotValue().
        : ViAreaWidget(parent)
{
    mUi.setupUi(this);
    connect(mUi.loadButton,      SIGNAL(released()),     this, SLOT(loadSettingsFromFile()));
    connect(mUi.saveButton,      SIGNAL(released()),     this, SLOT(saveSettingsToFile()));
    connect(mUi.resetButton,     SIGNAL(released()),     this, SLOT(resetSettings()));
    connect(mUi.exportCSVButton, SIGNAL(released()),     this, SLOT(exportToCSV()));
    connect(mUi.widget,          SIGNAL(notifyParentMouseRelease(QMouseEvent*)),
            this,               SLOT(setSnapshotValue(QMouseEvent*)));
    connect(mUi.visibleGraph,    SIGNAL(currentItemChanged(QTableWidgetItem*,QTableWidgetItem*)),
            this,               SLOT(selectGraph(QTableWidgetItem*,QTableWidgetItem*)));
    connect(mUi.visibleGraph,    SIGNAL(itemDoubleClicked(QTableWidgetItem*)),
            this,               SLOT(editGraphName(QTableWidgetItem*)));
    connect(mUi.visibleGraph,    SIGNAL(itemChanged(QTableWidgetItem*)),
            this,               SLOT(saveGraphName(QTableWidgetItem*)));
    connect(mUi.invisibleGraph,  SIGNAL(currentItemChanged(QTableWidgetItem*,QTableWidgetItem*)),
            this,               SLOT(closePrevItemEditor(QTableWidgetItem*,QTableWidgetItem*)));
    connect(mUi.invisibleGraph,  SIGNAL(itemDoubleClicked(QTableWidgetItem*)),
            this,               SLOT(editGraphName(QTableWidgetItem*)));
    connect(mUi.invisibleGraph,  SIGNAL(itemChanged(QTableWidgetItem*)),
            this,               SLOT(saveGraphName(QTableWidgetItem*)));
    connect(mUi.widget, SIGNAL(askParentRepaint(QPaintEvent *, QWidget *)),
                              this, SLOT(childRepaint(QPaintEvent *, QWidget *)));
    mUpDownMapper = new QSignalMapper(this);
    connect(mUi.up, SIGNAL(released()), mUpDownMapper, SLOT(map()));
    mUpDownMapper->setMapping(mUi.up, 0);
    connect(mUi.down, SIGNAL(released()), mUpDownMapper, SLOT(map()));
    mUpDownMapper->setMapping(mUi.down, 1);
    connect(mUpDownMapper, SIGNAL(mapped(int)), this, SLOT(setGraphVisibility(int)));
    connect(mUi.parametersWidget, SIGNAL(paramsChanged()),
             this,                SLOT(graphPlotParametersChanged()));
    mGraphPlotParameters = QSharedPointer<GraphPlotParameters>(mUi.parametersWidget->createParameters());
    //Set default params to trace graph values
    mMouseClickedValue =  mUi.widget->width() / 2;
    mGraphShowPoint = -1;
}
GraphPlotDialog::~GraphPlotDialog ()
Definition at line 481 of file graphPlotDialog.cpp.
References mUpDownMapper.
{
    //    saveSettings(QString("graphConfig.xml"));
    delete_safe(mUpDownMapper);
    //delete mParamMapper;
}
Member Function Documentation
void GraphPlotDialog::addGraphPoint (unsigned graphId, double value, bool isValid = true)
Definition at line 355 of file graphPlotDialog.cpp.
References corecvs::fround(), mData, mGraphPlotParameters, mGraphShowPoint, mMouseClickedValue, mUi, and setItemColor().
Referenced by addGraphPoint(), and DistortionWidget::updateAdditionalData().
{
    if (mUi.pauseButton->isChecked())
        return;
    if (graphId >= mData.size()) {
        mData.resize(graphId + 1);
        mData[graphId].isSelected = false;
        mData[graphId].name = QString("Graph %2").arg(graphId);
        QTableWidgetItem* graphItem = new QTableWidgetItem(mData[graphId].name);
        graphItem->setData(Qt::UserRole, QVariant(graphId));
        setItemColor(graphItem);
        int rowCount = mUi.visibleGraph->rowCount();
        mUi.visibleGraph->setRowCount(rowCount + 1);
        mUi.visibleGraph->setItem(rowCount, 0, graphItem);
        QTableWidgetItem* valueItem = new QTableWidgetItem();
        valueItem->setForeground(graphItem->foreground());
        valueItem->setData(Qt::UserRole, QVariant(graphId));
        mUi.visibleGraph->setItem(rowCount, 1, valueItem);
   }
    mData[graphId].push_front(GraphValue(value, isValid));
    while (mData[graphId].size() > 1000) {
        mData[graphId].pop_back();
    }
    if (graphId == 0) {
        double gainX = mGraphPlotParameters->xScale();
        if (mGraphPlotParameters->fixGridValue())
        {
            mGraphShowPoint = fround(double(mMouseClickedValue) / gainX);
            if (mGraphShowPoint >= (int)mData[0].size()) {
                mGraphShowPoint = (int)(mData[0].size() - mGraphShowPoint - 1);
            }
        } else {
            if (mGraphShowPoint < 0) {
                mMouseClickedValue = fround(double(mData[0].size() - mGraphShowPoint - 1) * gainX);
            }
            else {
                mGraphShowPoint++;
                mMouseClickedValue = fround(double(mGraphShowPoint) * gainX);
            }
            if (mMouseClickedValue >= mUi.widget->width()) {
                mGraphShowPoint = 0;
                mMouseClickedValue = 0;
            }
        }
    }
}
void GraphPlotDialog::addGraphPoint (QString graphName, double value, bool isValid = true)
Definition at line 408 of file graphPlotDialog.cpp.
References addGraphPoint(), getGraphId(), and mUi.
{
    if (mUi.pauseButton->isChecked())
        return;
    unsigned graphId = getGraphId(graphName);
    addGraphPoint(graphId, value, isValid);
}
void GraphPlotDialog::addMotionIntensity (const vector< double > & mData)
Definition at line 416 of file graphPlotDialog.cpp.
References mIntensity, and mUi.
{
    if (mUi.pauseButton->isChecked())
        return;
    mIntensity.push_front(data);
    while (mIntensity.size() > 200) {
            mIntensity.pop_back();
    }
}
void ViAreaWidget::askParentRepaint (QPaintEvent * event, QWidget * who) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog(), and ViAreaWidget::paintEvent().
void GraphPlotDialog::childRepaint (QPaintEvent * event, QWidget * who) [slot]
Definition at line 127 of file graphPlotDialog.cpp.
References drawGrid(), drawGridFixLine(), corecvs::fround(), mData, mGraphPlotParameters, mGraphShowPoint, mMouseClickedValue, mUi, showGraphsValue(), and ViAreaWidget::ui.
Referenced by GraphPlotDialog().
{
    if (!who)
        return;
    QPainter painter(who);
    unsigned h = who->height();
    unsigned w = who->width();
    painter.setPen(Qt::gray);
    painter.setBrush(Qt::darkGray);
    painter.drawRect(0, 0, w - 1, h - 1);
    int zero = h / 2;
    /* Draw oscilloscope
     *
     */
    double offset = mGraphPlotParameters->centerAt();
    double gainY = mGraphPlotParameters->yScale();
    double gainX = mGraphPlotParameters->xScale();
#if 0
    double oscContrast = ui.oscContrastSpinBox->value();
    deque<vector<double> >::iterator it;
    unsigned i = 0;
    for (it = intensity.begin(); it != intensity.end() && i < w; ++it, i++)
    {
        vector<int> line(h);
        const vector<double> &slice = *it;
        for (unsigned j = 0; j < slice.size(); j++)
        {
            double value = slice[j];
            double toShow = (value - offset) * gainY;
            unsigned bin = fround(zero - toShow);
            if (bin >= h)
                continue;
            line[bin]++;
        }
        for (unsigned j = 0; j < h; j++)
        {
            int val = line[j];
            val *= oscContrast;
            if (val > 255)
                val = 255;
            QPen pen;
            pen.setColor(QColor(0, val, val));
            painter.setPen(pen);
            painter.drawPoint(i, j);
        }
    }
#endif
    drawGrid(painter);
    drawGridFixLine(painter);
    QPen axisPen(Qt::DashLine);
    axisPen.setColor(Qt::blue);
    painter.setPen(axisPen);
    painter.drawLine(0, zero, w - 1, zero);
    int style = mGraphPlotParameters->graphStyle();
    for (int visId = 0; visId < mUi.visibleGraph->rowCount(); visId++) {
        QTableWidgetItem * item = mUi.visibleGraph->item(visId, 0);
        unsigned graphId = item->data(Qt::UserRole).toUInt();
        GraphHistory &graph = mData[graphId];
        QPen pen;
        pen.setColor(item->foreground().color());
        if (mData[graphId].isSelected && mGraphPlotParameters->selectGraph()) {
            pen.setWidth(mGraphPlotParameters->width() + 2);
        }
        else {
            pen.setWidth(mGraphPlotParameters->width());
        }
        painter.setPen(pen);
        unsigned i = 0;
        double x = 0;
        switch (style)
        {
        case 0:
            for (; i < graph.size() - 1 && x < w - 1; i++, x += gainX) {
                if (!graph[i].isValid || !graph[i + 1].isValid)
                    continue;
                double value1 = graph[i].value;
                double value2 = graph[i + 1].value;
                double toShow1 = (value1 - offset) * gainY;
                double toShow2 = (value2 - offset) * gainY;
                painter.drawLine(fround(x), zero - toShow1, fround(x + gainX), zero - toShow2);
            }
            break;
        case 1:
            for (; i < graph.size() && x < w - 1; i++, x += gainX) {
                if (!graph[i].isValid)
                    continue;
                double value = graph[i].value;
                double toShow = (value - offset) * gainY;
                painter.drawPoint(fround(x), zero - toShow);
            }
        }
    }
    // Calculate values for paused widget
    if (mUi.pauseButton->isChecked()) {
        if (mGraphPlotParameters->fixGridValue()) {
            mGraphShowPoint = fround(double(mMouseClickedValue) / gainX);
            if (mGraphShowPoint >= (int)mData[0].size()) {
                mGraphShowPoint = (int)(mData[0].size() - mGraphShowPoint - 1);
            }
        }
        else {
            if (mGraphShowPoint < 0) {
                mMouseClickedValue = fround(double(mData[0].size() - mGraphShowPoint - 1) * gainX);
            }
            else {
                mMouseClickedValue = fround(double(mGraphShowPoint) * gainX);
            }
            if (mMouseClickedValue >= mUi.widget->width()) {
                mMouseClickedValue = -1;
            }
        }
    }
    showGraphsValue(mUi.visibleGraph);
    showGraphsValue(mUi.invisibleGraph);
}
void GraphPlotDialog::closePrevItemEditor (QTableWidgetItem * , QTableWidgetItem * prev) [slot]
Definition at line 532 of file graphPlotDialog.cpp.
References mUi.
Referenced by GraphPlotDialog().
{
    if (prev == NULL) {
        return;
    }
    mUi.invisibleGraph->closePersistentEditor(prev);
}
void GraphPlotDialog::drawGrid (QPainter & painter) [private]
Definition at line 64 of file graphPlotDialog.cpp.
References mGraphPlotParameters, and mUi.
Referenced by childRepaint().
{
    unsigned i;
    unsigned lineNumber;
    unsigned w = mUi.widget->width();
    unsigned h = mUi.widget->height();
    QPen gridPen(Qt::DashDotLine);
    QPen subgridPen (Qt::DotLine);
    subgridPen.setColor(Qt::darkGreen);
    gridPen.setColor(Qt::green);
    if (mGraphPlotParameters->xGrid()) {
        double gainX = mGraphPlotParameters->xScale();
        while (gainX > 100) {
            gainX /= 10;
        }
        while (gainX < 10) {
            gainX *= 10;
        }
        unsigned stepX = gainX * 2;
        lineNumber = w / stepX;
        painter.setPen(gridPen);
        for (i = 0; i < lineNumber; i++) {
            if (stepX > 50) {
                painter.setPen(subgridPen);
                painter.drawLine(i * stepX  + stepX / 2, 0, i * stepX + stepX / 2, h - 1);
                painter.setPen(gridPen);
            }
            painter.drawLine((i + 1) * stepX, 0, (i + 1) * stepX, h - 1);
        }
    }
    if (mGraphPlotParameters->yGrid() && mGraphPlotParameters->yScale() > 0.005) {
        double gainY = mGraphPlotParameters->yScale();
        while (gainY > 100) {
            gainY /= 10;
        }
        while (gainY < 10) {
            gainY *= 10;
        }
        unsigned stepY = gainY * 2;
        lineNumber = w / stepY;
        painter.setPen(gridPen);
        for (i = 0; i < h / 2; i += stepY) {
            if (stepY > 50) {
                painter.setPen(subgridPen);
                painter.drawLine(0, h / 2 + i + stepY / 2, w - 1, h / 2 + i + stepY / 2);
                painter.drawLine(0, h / 2 - i - stepY / 2, w - 1, h / 2 - i - stepY / 2);
                painter.setPen(gridPen);
            }
            painter.drawLine(0, h / 2 + i + stepY, w - 1, h / 2 + i + stepY);
            painter.drawLine(0, h / 2 - i - stepY, w - 1, h / 2 - i - stepY);
        }
    }
}
void GraphPlotDialog::drawGridFixLine (QPainter & painter) [private]
Definition at line 541 of file graphPlotDialog.cpp.
References mGraphPlotParameters, mMouseClickedValue, and mUi.
Referenced by childRepaint().
{
    if (mMouseClickedValue < 0) {
        return;
    }
    QPen gridPen(Qt::SolidLine);
    mGraphPlotParameters->fixTimeValue() ? gridPen.setColor(Qt::yellow) : gridPen.setColor(Qt::blue);
    painter.setPen(gridPen);
    painter.drawLine(mMouseClickedValue, 0,
                     mMouseClickedValue, mUi.widget->height() - 1);
}
void GraphPlotDialog::editGraphName (QTableWidgetItem * item) [slot]
Definition at line 337 of file graphPlotDialog.cpp.
Referenced by GraphPlotDialog().
{
    QTableWidget *graphList = (QTableWidget*)sender();
    if (item != NULL && graphList->column(item) == 0) {
        QTableWidget *graphList = (QTableWidget*)sender();
        graphList->openPersistentEditor(item);
    }
}
void GraphPlotDialog::exportToCSV () [slot]
Definition at line 263 of file graphPlotDialog.cpp.
References mData, mGraphPlotParameters, and mUi.
Referenced by GraphPlotDialog().
{
    unsigned w = mUi.widget->width();
    printf("Export To CSV slot called...\n");
    char name[100];
    snprintf2buf(name, "exported.csv");
    printf("Dumping current graph to <%s>...", name);
    fstream file(name, fstream::out);
    double gainX = mGraphPlotParameters->xScale();
    for (unsigned graphId = 0; graphId < mData.size(); graphId++) {
        GraphHistory &graph = mData[graphId];
        GraphHistory::iterator it;
        double x = 0;
        for (it = graph.begin(); it != graph.end() && x < w - 1; ++it, x += gainX) {
            if ((*it).isValid) {
                file << (*it).value;
            }
            file << ",";
        }
        file << endl;
    }
    file.close();
    printf("done\n");
}
unsigned GraphPlotDialog::getGraphId (QString name)
Definition at line 489 of file graphPlotDialog.cpp.
References mData, and mUi.
Referenced by addGraphPoint().
{
    unsigned graphId = 0;
    while (graphId < mData.size()) {
        if (mData[graphId].name == name) {
            return graphId;
        }
        graphId++;
    }
    mData.resize(graphId + 1);
    mData[graphId].isSelected = false;
    mData[graphId].name = name;
    QTableWidgetItem* graphItem = new QTableWidgetItem(name);
    graphItem->setData(Qt::UserRole, QVariant(graphId));
    mUi.visibleGraph->setItem(mUi.visibleGraph->rowCount(), 0, graphItem);
    return graphId;
}
QString GraphPlotDialog::getGraphName (unsigned id)
Definition at line 515 of file graphPlotDialog.cpp.
References mData.
{
    if (id >= mData.size())
        return "";
    return mData[id].name;
}
void GraphPlotDialog::graphPlotParametersChanged () [slot]
Definition at line 509 of file graphPlotDialog.cpp.
References mGraphPlotParameters, and mUi.
Referenced by GraphPlotDialog().
{
    mGraphPlotParameters = QSharedPointer<GraphPlotParameters>(mUi.parametersWidget->createParameters());
    mUi.widget->update();
}
void ViAreaWidget::keyPressEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 53 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyPressEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyPressEvent(event);
}
void ViAreaWidget::keyReleaseEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 59 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyReleaseEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyReleaseEvent(event);
}
void GraphPlotDialog::loadFromQSettings (const QString & fileName, QString _root) [virtual]
Reimplemented from SaveableWidget.
Definition at line 432 of file graphPlotDialog.cpp.
References mRootPath, and mUi.
{
    mUi.parametersWidget->loadFromQSettings(fileName, _root + mRootPath);
}
virtual void SaveableWidget::loadParamWidget (WidgetLoader &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 119 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::loadFromQSettings().
{}
void GraphPlotDialog::loadSettingsFromFile () [slot]
Definition at line 443 of file graphPlotDialog.cpp.
References mUi.
Referenced by GraphPlotDialog().
{
    QString filename = QFileDialog::getOpenFileName(
                this,
                tr("Load settings"),
                "./",
                tr("XML files(*.xml)"));
    mUi.parametersWidget->loadFromQSettings(filename, "GraphPlotConfiguration");
}
void ViAreaWidget::mouseDoubleClickEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 35 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mouseMoveEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 16 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mousePressEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 22 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, ViAreaWidget::notifyParentMouseMove(), and ViAreaWidget::notifyParentMousePress().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
    emit notifyParentMousePress(event);
}
void ViAreaWidget::mouseReleaseEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 41 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseRelease().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseRelease(event);
}
void ViAreaWidget::notifyKeyPressEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyPressEvent().
void ViAreaWidget::notifyKeyReleaseEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyReleaseEvent().
void ViAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), ViAreaWidget::mouseDoubleClickEvent(), ViAreaWidget::mouseMoveEvent(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog(), and ViAreaWidget::mouseReleaseEvent().
void ViAreaWidget::notifyParentResize (QResizeEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::resizeEvent().
void ViAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::wheelEvent().
void ViAreaWidget::paintEvent (QPaintEvent * event) [virtual, inherited]
Reimplemented in ImageWidget.
Definition at line 10 of file viAreaWidget.cpp.
References ViAreaWidget::askParentRepaint(), and ViAreaWidget::mForwardEvents.
{
    if (!mForwardEvents) return;
    emit askParentRepaint(event, this);
}
void GraphPlotDialog::resetSettings () [slot]
Definition at line 465 of file graphPlotDialog.cpp.
References GraphStyle::DRAW_LINES, mUi, GraphPlotParameters::setCenterAt(), GraphPlotParameters::setContrast(), GraphPlotParameters::setGraphStyle(), GraphPlotParameters::setSelectGraph(), GraphPlotParameters::setWidth(), GraphPlotParameters::setXGrid(), GraphPlotParameters::setXScale(), GraphPlotParameters::setYGrid(), and GraphPlotParameters::setYScale().
Referenced by GraphPlotDialog().
{
    GraphPlotParameters defaultParameters;
    defaultParameters.setGraphStyle(GraphStyle::DRAW_LINES);
    defaultParameters.setWidth(1);
    defaultParameters.setCenterAt(0.0);
    defaultParameters.setXGrid(false);
    defaultParameters.setYGrid(false);
    defaultParameters.setXScale(1.0);
    defaultParameters.setYScale(1.0);
    defaultParameters.setContrast(50.0);
    defaultParameters.setSelectGraph(false);
    mUi.parametersWidget->setParameters(defaultParameters);
}
void ViAreaWidget::resizeEvent (QResizeEvent * event) [virtual, inherited]
Definition at line 29 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentResize().
{
    if (!mForwardEvents) return;
    emit notifyParentResize(event);
}
void GraphPlotDialog::saveGraphName (QTableWidgetItem * item) [slot]
Definition at line 345 of file graphPlotDialog.cpp.
References mData.
Referenced by GraphPlotDialog().
{
    QTableWidget *graphList = (QTableWidget*)sender();
    if (item != NULL && graphList->column(item) == 0) {
        unsigned graphId = item->data(Qt::UserRole).toUInt();
        mData[graphId].name = item->text();
        graphList->closePersistentEditor(item);
    }
}
virtual void SaveableWidget::saveParamWidget (WidgetSaver &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 120 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::saveToQSettings().
{}
void GraphPlotDialog::saveSettingsToFile () [slot]
Definition at line 454 of file graphPlotDialog.cpp.
References mUi.
Referenced by GraphPlotDialog().
{
    QString filename = QFileDialog::getSaveFileName(
                this,
                tr("Save settings"),
                "./GraphSettings.xml",
                tr("XML files(*.xml)"));
    mUi.parametersWidget->saveToQSettings(filename, "GraphPlotConfiguration");
}
void GraphPlotDialog::saveToQSettings (const QString & fileName, QString _root) [virtual]
Reimplemented from SaveableWidget.
Definition at line 437 of file graphPlotDialog.cpp.
References mRootPath, and mUi.
{
    mUi.parametersWidget->saveToQSettings(fileName, _root + mRootPath);
}
void GraphPlotDialog::selectGraph (QTableWidgetItem * current, QTableWidgetItem * prev) [slot]
Definition at line 324 of file graphPlotDialog.cpp.
References mData, and mUi.
Referenced by GraphPlotDialog().
{
    if (prev != NULL) {
        unsigned graphId = prev->data(Qt::UserRole).toUInt();
        mData[graphId].isSelected = false;
        mUi.visibleGraph->closePersistentEditor(prev);
    }
    if (current != NULL) {
        unsigned graphId = current->data(Qt::UserRole).toUInt();
        mData[graphId].isSelected = true;
    }
}
void GraphPlotDialog::setGraphVisibility (int currentVisibility) [slot]
Definition at line 294 of file graphPlotDialog.cpp.
References mData, and mUi.
Referenced by GraphPlotDialog().
{
    QTableWidget *currentList = NULL;
    QTableWidget *endList = NULL;
    if (currentVisibility == 1) {
        currentList = mUi.visibleGraph;
        endList = mUi.invisibleGraph;
    }
    else if (currentVisibility == 0) {
        currentList = mUi.invisibleGraph;
        endList = mUi.visibleGraph;
    }
    else {
        return;
    }
    QTableWidgetItem *item = currentList->takeItem(currentList->currentRow(), 0);
    QTableWidgetItem *valueItem = currentList->takeItem(currentList->currentRow(), 1);
    if (!item || !valueItem) {
        return;
    }
    currentList->removeRow(currentList->currentRow());
    unsigned graphId = item->data(Qt::UserRole).toUInt();
    mData[graphId].isSelected = false;
    int rowCount = endList->rowCount();
    endList->setRowCount(rowCount + 1);
    endList->setItem(rowCount, 0, item);
    endList->setItem(rowCount, 1, valueItem);
}
void GraphPlotDialog::setItemColor (QTableWidgetItem * item) [private]
Definition at line 523 of file graphPlotDialog.cpp.
References CORE_COUNT_OF, and mGraphPallete.
Referenced by addGraphPoint().
{
    unsigned graphId = item->data(Qt::UserRole).toUInt();
    int colornum = CORE_COUNT_OF(mGraphPallete);
    QBrush brush;
    brush.setColor(mGraphPallete[graphId % colornum]);
    item->setForeground(brush);
}
void GraphPlotDialog::setSavingRoot (const QString & root) [inline]
Definition at line 113 of file graphPlotDialog.h.
Referenced by BaseHostDialog::createAdditionalWindow().
    {
        mRootPath = root;
    }
void GraphPlotDialog::setSnapshotValue (QMouseEvent * mouseEvent) [slot]
Definition at line 570 of file graphPlotDialog.cpp.
References corecvs::fround(), mData, mGraphPlotParameters, mGraphShowPoint, mMouseClickedValue, and mUi.
Referenced by GraphPlotDialog().
{
    if (mData.size() == 0) {
        return;
    }
    // Update snapshot point
    mMouseClickedValue = mouseEvent->x();
    mGraphShowPoint = fround(double(mMouseClickedValue) / mGraphPlotParameters->xScale());
    if (mGraphShowPoint >= (int)mData[0].size()) {
       mGraphShowPoint = (int)(mData[0].size() - mGraphShowPoint - 1);
    }
    mUi.widget->update();
}
void GraphPlotDialog::showGraphsValue (QTableWidget * graphTable) [private]
Definition at line 554 of file graphPlotDialog.cpp.
References mData, and mGraphShowPoint.
Referenced by childRepaint().
{
    for (int i = 0; i < graphTable->rowCount(); i++) {
        unsigned graphId = graphTable->item(i, 0)->data(Qt::UserRole).toUInt();
        GraphHistory &graph = mData[graphId];
        QTableWidgetItem *item = graphTable->item(i, 1);
        if (mGraphShowPoint >= 0 && graph[mGraphShowPoint].isValid) {
            item->setText(QString("%1").arg(graph[mGraphShowPoint].value, 0, 'g', 3));
        }
        else {
            item->setText(QString(""));
        }
    }
}
void GraphPlotDialog::update (void)
Definition at line 427 of file graphPlotDialog.cpp.
References mUi.
Referenced by DistortionWidget::updateAdditionalData().
{
    mUi.widget->update();
}
void ViAreaWidget::wheelEvent (QWheelEvent * event) [virtual, inherited]
Definition at line 47 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentWheelEvent().
{
    if (!mForwardEvents) return;
    emit notifyParentWheelEvent(event);
}
Member Data Documentation
vector<GraphHistory> GraphPlotDialog::mData [private]
Definition at line 91 of file graphPlotDialog.h.
Referenced by addGraphPoint(), childRepaint(), exportToCSV(), getGraphId(), getGraphName(), saveGraphName(), selectGraph(), setGraphVisibility(), setSnapshotValue(), and showGraphsValue().
QColor GraphPlotDialog::mGraphPallete = { Qt::red, Qt::darkGreen, Qt::cyan, Qt::darkRed, Qt::darkBlue, Qt::darkMagenta } [static, private]
Definition at line 88 of file graphPlotDialog.h.
Referenced by setItemColor().
QSharedPointer<GraphPlotParameters> GraphPlotDialog::mGraphPlotParameters [private]
Definition at line 85 of file graphPlotDialog.h.
Referenced by addGraphPoint(), childRepaint(), drawGrid(), drawGridFixLine(), exportToCSV(), GraphPlotDialog(), graphPlotParametersChanged(), and setSnapshotValue().
int GraphPlotDialog::mGraphShowPoint [private]
Definition at line 98 of file graphPlotDialog.h.
Referenced by addGraphPoint(), childRepaint(), GraphPlotDialog(), setSnapshotValue(), and showGraphsValue().
deque<vector<double> > GraphPlotDialog::mIntensity [private]
Definition at line 92 of file graphPlotDialog.h.
Referenced by addMotionIntensity().
int GraphPlotDialog::mMouseClickedValue [private]
Definition at line 95 of file graphPlotDialog.h.
Referenced by addGraphPoint(), childRepaint(), drawGridFixLine(), GraphPlotDialog(), and setSnapshotValue().
QString GraphPlotDialog::mRootPath [private]
Definition at line 111 of file graphPlotDialog.h.
Referenced by loadFromQSettings(), and saveToQSettings().
Ui::GraphPlotDialogClass GraphPlotDialog::mUi [private]
Definition at line 84 of file graphPlotDialog.h.
Referenced by addGraphPoint(), addMotionIntensity(), childRepaint(), closePrevItemEditor(), drawGrid(), drawGridFixLine(), exportToCSV(), getGraphId(), GraphPlotDialog(), graphPlotParametersChanged(), loadFromQSettings(), loadSettingsFromFile(), resetSettings(), saveSettingsToFile(), saveToQSettings(), selectGraph(), setGraphVisibility(), setSnapshotValue(), and update().
QSignalMapper* GraphPlotDialog::mUpDownMapper [private]
Definition at line 104 of file graphPlotDialog.h.
Referenced by GraphPlotDialog(), and ~GraphPlotDialog().
The documentation for this class was generated from the following files:
utils/uis/graphPlotDialog.h
utils/uis/graphPlotDialog.cpp