DeepView: ParameterSelector Class Reference
ParameterSelector Class Reference
#include <parameterSelector.h>
Public Slots
void currentIndexChanged (int value)
Signals
void valueChanged (int value)
void autoToggled ()
void resetPressed ()
Public Member Functions
ParameterSelector (QWidget *parent=0)
~ParameterSelector ()
virtual double minimum (void)
virtual double maximum (void)
virtual double value (void)
virtual void setValue (double value)
virtual void pushOption (QString name, int value)
virtual void setAutoSupported (bool value)
virtual void stepUp ()
virtual void stepDown ()
virtual void setName (QString name)
Private Member Functions
void regenComboBox ()
Private Attributes
Ui::ParameterSelectorClass ui
vector< int > mIndexToValue
Detailed Description
Definition at line 13 of file parameterSelector.h.
Constructor & Destructor Documentation
ParameterSelector::ParameterSelector (QWidget * parent = 0)
Definition at line 6 of file parameterSelector.cpp.
References resetPressed(), and ui.
    : ParameterEditorWidget(parent)
{
    ui.setupUi(this);
    connect(ui.resetButton, SIGNAL(released()), this, SIGNAL(resetPressed()));
}
ParameterSelector::~ParameterSelector ()
Definition at line 88 of file parameterSelector.cpp.
{
}
Member Function Documentation
void ParameterSelector::autoToggled () [signal]
void ParameterSelector::currentIndexChanged (int value) [slot]
Definition at line 72 of file parameterSelector.cpp.
References value(), and valueChanged().
{
    emit valueChanged(value());
}
double ParameterSelector::maximum (void) [virtual]
Implements ParameterEditorWidget.
Definition at line 28 of file parameterSelector.cpp.
References mIndexToValue.
{
    return mIndexToValue[mIndexToValue.size() - 1];
}
double ParameterSelector::minimum (void) [virtual]
Implements ParameterEditorWidget.
Definition at line 23 of file parameterSelector.cpp.
References mIndexToValue.
{
    return mIndexToValue[0];
}
void ParameterSelector::pushOption (QString name, int value) [virtual]
Definition at line 56 of file parameterSelector.cpp.
References mIndexToValue, and ui.
Referenced by CapSettingsDialog::refreshDialog().
{
    ui.comboBox->addItem(name);
    mIndexToValue.push_back(value);
}
void ParameterSelector::regenComboBox () [private]
void ParameterSelector::resetPressed () [signal]
Referenced by ParameterSelector().
void ParameterSelector::setAutoSupported (bool value) [virtual]
Implements ParameterEditorWidget.
Definition at line 18 of file parameterSelector.cpp.
References ui.
{
    ui.autoBox->setEnabled(value);
}
void ParameterSelector::setName (QString name) [virtual]
Implements ParameterEditorWidget.
Definition at line 13 of file parameterSelector.cpp.
References ui.
{
    ui.label->setText(name);
}
void ParameterSelector::setValue (double value) [virtual]
Implements ParameterEditorWidget.
Definition at line 43 of file parameterSelector.cpp.
References mIndexToValue, and ui.
{
    for (unsigned i = 0; i < mIndexToValue.size(); i++ )
    {
        if (mIndexToValue[i] == value)
        {
            ui.comboBox->setCurrentIndex(i);
            return;
        }
    }
    ui.comboBox->setCurrentIndex(0);
}
void ParameterSelector::stepDown () [virtual]
Implements ParameterEditorWidget.
Definition at line 67 of file parameterSelector.cpp.
References ui.
{
    ui.comboBox->setCurrentIndex(ui.comboBox->currentIndex() - 1);
}
void ParameterSelector::stepUp () [virtual]
Implements ParameterEditorWidget.
Definition at line 62 of file parameterSelector.cpp.
References ui.
{
    ui.comboBox->setCurrentIndex(ui.comboBox->currentIndex() + 1);
}
double ParameterSelector::value (void) [virtual]
Implements ParameterEditorWidget.
Definition at line 33 of file parameterSelector.cpp.
References mIndexToValue, and ui.
Referenced by currentIndexChanged().
{
    int index = ui.comboBox->currentIndex();
    if (index < (int)mIndexToValue.size())
        return mIndexToValue[index];
    else
        return 0;
}
void ParameterSelector::valueChanged (int value) [signal]
Referenced by currentIndexChanged().
Member Data Documentation
vector<int> ParameterSelector::mIndexToValue [private]
Definition at line 50 of file parameterSelector.h.
Referenced by maximum(), minimum(), pushOption(), setValue(), and value().
Ui::ParameterSelectorClass ParameterSelector::ui [private]
Definition at line 49 of file parameterSelector.h.
Referenced by ParameterSelector(), pushOption(), setAutoSupported(), setName(), setValue(), stepDown(), stepUp(), and value().
The documentation for this class was generated from the following files:
utils/widgets/parameterSelector.h
utils/widgets/parameterSelector.cpp