DeepView: corecvs::DeserializerVisitor Class Reference
corecvs::DeserializerVisitor Class Reference
#include <deserializerVisitor.h>
Public Member Functions
DeserializerVisitor (XMLElement *_element)
string NoSpaces (const char *)
template<typename inputType , typename reflectionType >
void visit (inputType &field, const reflectionType *fieldDescriptor)
template<class Type >
void visit (Type &field, Type defaultValue, const char *fieldName)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (float &field, const FloatField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
template<>
void visit (string &field, const StringField *fieldDescriptor)
template<>
void visit (char *&field, const PointerField *fieldDescriptor)
template<>
void visit (int &field, const EnumField *fieldDescriptor)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (float &field, const FloatField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
template<>
void visit (string &field, const StringField *fieldDescriptor)
template<>
void visit (char *&field, const PointerField *fieldDescriptor)
template<>
void visit (void *&field, const PointerField *fieldDescriptor)
template<>
void visit (int &field, const EnumField *fieldDescriptor)
Public Attributes
XMLElement * element
Detailed Description
Definition at line 12 of file deserializerVisitor.h.
Constructor & Destructor Documentation
corecvs::DeserializerVisitor::DeserializerVisitor (XMLElement * _element) [inline, explicit]
Definition at line 17 of file deserializerVisitor.h.
                                                        :
        element(_element)
    {}
Member Function Documentation
string corecvs::DeserializerVisitor::NoSpaces (const char * str)
Definition at line 6 of file deserializerVisitor.cpp.
{
    string toReturn(str);
//    toReturn.erase(remove_if(toReturn.begin(), toReturn.end(), isspace), toReturn.end());
    toReturn.erase(remove(toReturn.begin(), toReturn.end(), ' '), toReturn.end());
    return toReturn;
}
template<> void corecvs::DeserializerVisitor::visit (int & field, const IntField * fieldDescriptor)
Definition at line 24 of file deserializerVisitor.cpp.
References tinyxml2::XMLNode::FirstChildElement(), and tinyxml2::XMLElement::IntAttribute().
{
    XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
    field = param->IntAttribute("value");
}
template<typename inputType , typename reflectionType > void corecvs::DeserializerVisitor::visit (inputType & field, const reflectionType * fieldDescriptor) [inline]
Definition at line 25 of file deserializerVisitor.h.
References tinyxml2::XMLElement::Attribute(), and tinyxml2::XMLNode::FirstChildElement().
    {
        XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
        field = param->Attribute("value");
    }
template<> void corecvs::DeserializerVisitor::visit (double & field, const DoubleField * fieldDescriptor)
Definition at line 31 of file deserializerVisitor.cpp.
References tinyxml2::XMLElement::DoubleAttribute(), and tinyxml2::XMLNode::FirstChildElement().
{
    XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
    field = param->DoubleAttribute("value");
}
template<class Type > void corecvs::DeserializerVisitor::visit (Type & field, Type defaultValue, const char * fieldName) [inline]
Definition at line 32 of file deserializerVisitor.h.
    {
        field.accept(*this);
    }
template<> void corecvs::DeserializerVisitor::visit (int & field, const IntField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (float & field, const FloatField * fieldDescriptor)
Definition at line 38 of file deserializerVisitor.cpp.
References tinyxml2::XMLNode::FirstChildElement(), and tinyxml2::XMLElement::FloatAttribute().
{
    XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
    field = param->FloatAttribute("value");
}
template<> void corecvs::DeserializerVisitor::visit (double & field, const DoubleField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (float & field, const FloatField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (bool & field, const BoolField * fieldDescriptor)
Definition at line 45 of file deserializerVisitor.cpp.
References tinyxml2::XMLElement::BoolAttribute(), and tinyxml2::XMLNode::FirstChildElement().
{
    XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
    field = param->BoolAttribute("value");
}
template<> void corecvs::DeserializerVisitor::visit (bool & field, const BoolField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (string & field, const StringField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (string & field, const StringField * fieldDescriptor)
Definition at line 52 of file deserializerVisitor.cpp.
References tinyxml2::XMLElement::Attribute(), and tinyxml2::XMLNode::FirstChildElement().
{
    XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
    field = string(param->Attribute("value"));
}
template<> void corecvs::DeserializerVisitor::visit (char *& field, const PointerField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (void *& field, const PointerField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (int & field, const EnumField * fieldDescriptor)
template<> void corecvs::DeserializerVisitor::visit (char *& field, const PointerField * fieldDescriptor)
Definition at line 59 of file deserializerVisitor.cpp.
References tinyxml2::XMLElement::Attribute(), and tinyxml2::XMLNode::FirstChildElement().
{
    XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
    const char* str = param->Attribute("value");
    field = new char[strlen(str)+1];
    strcpy(field, str);
}
template<> void corecvs::DeserializerVisitor::visit (int & field, const EnumField * fieldDescriptor)
Definition at line 68 of file deserializerVisitor.cpp.
References tinyxml2::XMLNode::FirstChildElement(), and tinyxml2::XMLElement::IntAttribute().
{
    XMLElement* param = element->FirstChildElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
    field = param->IntAttribute("value");
}
Member Data Documentation
XMLElement* corecvs::DeserializerVisitor::element
Definition at line 15 of file deserializerVisitor.h.
The documentation for this class was generated from the following files:
core/reflection/deserializerVisitor.h
core/reflection/deserializerVisitor.cpp