DeepView: BitSelectorParametersControlWidget Class Reference
BitSelectorParametersControlWidget Class Reference
#include <bitSelectorParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
BitSelectorParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
virtual ~BitSelectorParametersControlWidget ()
BitSelectorParameters * createParameters () const
virtual BaseReflectionStatic * createParametersVirtual () const
void setParameters (const BitSelectorParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_BitSelectorParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 11 of file bitSelectorParametersControlWidget.h.
Constructor & Destructor Documentation
BitSelectorParametersControlWidget::BitSelectorParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file bitSelectorParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::BitSelectorParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->shiftSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit0CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit1CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit2CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit3CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit4CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit5CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit6CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit7CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit8CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit9CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit10CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit11CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit12CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit13CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit14CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bit15CheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
}
BitSelectorParametersControlWidget::~BitSelectorParametersControlWidget () [virtual]
Definition at line 42 of file bitSelectorParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void BitSelectorParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file bitSelectorParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
BitSelectorParameters * BitSelectorParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 64 of file bitSelectorParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    BitSelectorParameters *result = new BitSelectorParameters(
          mUi->shiftSpinBox->value()
        , mUi->bit0CheckBox->isChecked()
        , mUi->bit1CheckBox->isChecked()
        , mUi->bit2CheckBox->isChecked()
        , mUi->bit3CheckBox->isChecked()
        , mUi->bit4CheckBox->isChecked()
        , mUi->bit5CheckBox->isChecked()
        , mUi->bit6CheckBox->isChecked()
        , mUi->bit7CheckBox->isChecked()
        , mUi->bit8CheckBox->isChecked()
        , mUi->bit9CheckBox->isChecked()
        , mUi->bit10CheckBox->isChecked()
        , mUi->bit11CheckBox->isChecked()
        , mUi->bit12CheckBox->isChecked()
        , mUi->bit13CheckBox->isChecked()
        , mUi->bit14CheckBox->isChecked()
        , mUi->bit15CheckBox->isChecked()
    );
    return result;
}
virtual BaseReflectionStatic* BitSelectorParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 20 of file bitSelectorParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void BitSelectorParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 48 of file bitSelectorParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    BitSelectorParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void BitSelectorParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by BitSelectorParametersControlWidget(), and setParameters().
void BitSelectorParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 56 of file bitSelectorParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    BitSelectorParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void BitSelectorParametersControlWidget::setParameters (const BitSelectorParameters & input)
Definition at line 94 of file bitSelectorParametersControlWidget.cpp.
References BitSelectorParameters::bit0(), BitSelectorParameters::bit1(), BitSelectorParameters::bit10(), BitSelectorParameters::bit11(), BitSelectorParameters::bit12(), BitSelectorParameters::bit13(), BitSelectorParameters::bit14(), BitSelectorParameters::bit15(), BitSelectorParameters::bit2(), BitSelectorParameters::bit3(), BitSelectorParameters::bit4(), BitSelectorParameters::bit5(), BitSelectorParameters::bit6(), BitSelectorParameters::bit7(), BitSelectorParameters::bit8(), BitSelectorParameters::bit9(), mUi, paramsChanged(), and BitSelectorParameters::shift().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->shiftSpinBox->setValue(input.shift());
    mUi->bit0CheckBox->setChecked(input.bit0());
    mUi->bit1CheckBox->setChecked(input.bit1());
    mUi->bit2CheckBox->setChecked(input.bit2());
    mUi->bit3CheckBox->setChecked(input.bit3());
    mUi->bit4CheckBox->setChecked(input.bit4());
    mUi->bit5CheckBox->setChecked(input.bit5());
    mUi->bit6CheckBox->setChecked(input.bit6());
    mUi->bit7CheckBox->setChecked(input.bit7());
    mUi->bit8CheckBox->setChecked(input.bit8());
    mUi->bit9CheckBox->setChecked(input.bit9());
    mUi->bit10CheckBox->setChecked(input.bit10());
    mUi->bit11CheckBox->setChecked(input.bit11());
    mUi->bit12CheckBox->setChecked(input.bit12());
    mUi->bit13CheckBox->setChecked(input.bit13());
    mUi->bit14CheckBox->setChecked(input.bit14());
    mUi->bit15CheckBox->setChecked(input.bit15());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void BitSelectorParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 119 of file bitSelectorParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    BitSelectorParameters *inputCasted = static_cast<BitSelectorParameters *>(input);
    setParameters(*inputCasted);
}
void BitSelectorParametersControlWidget::valueChanged () [signal]
Referenced by BitSelectorParametersControlWidget().
Member Data Documentation
bool BitSelectorParametersControlWidget::autoInit [private]
Definition at line 45 of file bitSelectorParametersControlWidget.h.
Ui_BitSelectorParametersControlWidget* BitSelectorParametersControlWidget::mUi [private]
Definition at line 44 of file bitSelectorParametersControlWidget.h.
Referenced by BitSelectorParametersControlWidget(), createParameters(), setParameters(), and ~BitSelectorParametersControlWidget().
QString BitSelectorParametersControlWidget::rootPath [private]
Definition at line 46 of file bitSelectorParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/bitSelectorParametersControlWidget.h
utils/filters/ui/bitSelectorParametersControlWidget.cpp