DeepView: ViAreaWidget Class Reference
ViAreaWidget Class Reference
#include <viAreaWidget.h>
Signals
void askParentRepaint (QPaintEvent *event, QWidget *who)
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (QResizeEvent *event)
void notifyKeyPressEvent (QKeyEvent *event)
void notifyKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
ViAreaWidget (QWidget *parent=0, bool forwardEvents=true)
~ViAreaWidget ()
virtual void paintEvent (QPaintEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
Private Attributes
Ui_ViAreaWidgetClass ui
bool mForwardEvents
Detailed Description
Definition at line 6 of file viAreaWidget.h.
Constructor & Destructor Documentation
ViAreaWidget::ViAreaWidget (QWidget * parent = 0, bool forwardEvents = true)
Definition at line 3 of file viAreaWidget.cpp.
References ui.
    : QWidget(parent),
      mForwardEvents(forwardEvents)
{
    ui.setupUi(this);
}
ViAreaWidget::~ViAreaWidget ()
Definition at line 66 of file viAreaWidget.cpp.
{
}
Member Function Documentation
void ViAreaWidget::askParentRepaint (QPaintEvent * event, QWidget * who) [signal]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and paintEvent().
void ViAreaWidget::keyPressEvent (QKeyEvent * event) [virtual]
Reimplemented in CloudViewDialog.
Definition at line 53 of file viAreaWidget.cpp.
References mForwardEvents, and notifyKeyPressEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyPressEvent(event);
}
void ViAreaWidget::keyReleaseEvent (QKeyEvent * event) [virtual]
Reimplemented in CloudViewDialog.
Definition at line 59 of file viAreaWidget.cpp.
References mForwardEvents, and notifyKeyReleaseEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyReleaseEvent(event);
}
void ViAreaWidget::mouseDoubleClickEvent (QMouseEvent * event) [virtual]
Definition at line 35 of file viAreaWidget.cpp.
References mForwardEvents, and notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mouseMoveEvent (QMouseEvent * event) [virtual]
Definition at line 16 of file viAreaWidget.cpp.
References mForwardEvents, and notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mousePressEvent (QMouseEvent * event) [virtual]
Definition at line 22 of file viAreaWidget.cpp.
References mForwardEvents, notifyParentMouseMove(), and notifyParentMousePress().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
    emit notifyParentMousePress(event);
}
void ViAreaWidget::mouseReleaseEvent (QMouseEvent * event) [virtual]
Definition at line 41 of file viAreaWidget.cpp.
References mForwardEvents, and notifyParentMouseRelease().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseRelease(event);
}
void ViAreaWidget::notifyKeyPressEvent (QKeyEvent * event) [signal]
Referenced by keyPressEvent().
void ViAreaWidget::notifyKeyReleaseEvent (QKeyEvent * event) [signal]
Referenced by keyReleaseEvent().
void ViAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), mouseDoubleClickEvent(), mouseMoveEvent(), and mousePressEvent().
void ViAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and mousePressEvent().
void ViAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and mouseReleaseEvent().
void ViAreaWidget::notifyParentResize (QResizeEvent * event) [signal]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and resizeEvent().
void ViAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and wheelEvent().
void ViAreaWidget::paintEvent (QPaintEvent * event) [virtual]
Reimplemented in ImageWidget.
Definition at line 10 of file viAreaWidget.cpp.
References askParentRepaint(), and mForwardEvents.
{
    if (!mForwardEvents) return;
    emit askParentRepaint(event, this);
}
void ViAreaWidget::resizeEvent (QResizeEvent * event) [virtual]
Definition at line 29 of file viAreaWidget.cpp.
References mForwardEvents, and notifyParentResize().
{
    if (!mForwardEvents) return;
    emit notifyParentResize(event);
}
void ViAreaWidget::wheelEvent (QWheelEvent * event) [virtual]
Definition at line 47 of file viAreaWidget.cpp.
References mForwardEvents, and notifyParentWheelEvent().
{
    if (!mForwardEvents) return;
    emit notifyParentWheelEvent(event);
}
Member Data Documentation
bool ViAreaWidget::mForwardEvents [private]
Definition at line 39 of file viAreaWidget.h.
Referenced by keyPressEvent(), keyReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), resizeEvent(), and wheelEvent().
Ui_ViAreaWidgetClass ViAreaWidget::ui [private]
Reimplemented in PaintImageWidget, StatisticsDialog, and TextLabelWidget.
Definition at line 38 of file viAreaWidget.h.
Referenced by GraphPlotDialog::childRepaint(), and ViAreaWidget().
The documentation for this class was generated from the following files:
utils/viAreaWidget.h
utils/viAreaWidget.cpp