DeepView: ResultImage Class Reference
ResultImage Class Reference
#include <resultImage.h>
Public Member Functions
ResultImage ()
virtual ~ResultImage ()
void drawImage (QImage *image)
unsigned layerNum () const
const ResultLayerBase * layer (unsigned number) const
void addLayer (ResultLayerBase *layer)
int height () const
int width () const
void setHeight (int height)
void setWidth (int width)
void print ()
Private Attributes
vector< ResultLayerBase * > mLayers
int mHeight
int mWidth
Detailed Description
Definition at line 66 of file resultImage.h.
Constructor & Destructor Documentation
ResultImage::ResultImage () [inline]
Definition at line 74 of file resultImage.h.
                  :
        mHeight(0)
    ,   mWidth (0)
    {}
virtual ResultImage::~ResultImage () [inline, virtual]
Definition at line 79 of file resultImage.h.
References mLayers.
    {
        for (unsigned i = 0; i < mLayers.size(); i++)
        {
            delete_safe(mLayers[i]);
        }
    }
Member Function Documentation
void ResultImage::addLayer (ResultLayerBase * layer) [inline]
Definition at line 114 of file resultImage.h.
References mLayers.
Referenced by BaseCalculationThread::initData(), and RecorderThread::processNewData().
    {
        mLayers.push_back(layer);
    }
void ResultImage::drawImage (QImage * image) [inline]
Definition at line 87 of file resultImage.h.
References mLayers.
Referenced by RecorderDialog::processResult(), and BaseHostDialog::processResult().
    {
        if (image == NULL)
            return;
        for (unsigned i = 0; i < mLayers.size(); i++)
        {
            if (mLayers[i] != NULL)
            {
//              qDebug("Applying layer %d of type %d", i, mLayers[i]->getType());
                mLayers[i]->drawImage(image);
            } else {
//              qDebug("Layer %d is NULL", i);
            }
        }
    }
int ResultImage::height () const [inline]
Definition at line 119 of file resultImage.h.
References mHeight, and mLayers.
Referenced by RecorderDialog::processResult(), BaseHostDialog::processResult(), and setHeight().
    {
        int maxHeight = mHeight;
        for (unsigned i = 0; i < mLayers.size(); i++)
        {
            if (mLayers[i] == NULL)
                continue;
            int newHeight = mLayers[i]->modifyHeight(mHeight);
            maxHeight = std::max(newHeight, maxHeight);
        }
        return maxHeight;
    }
const ResultLayerBase* ResultImage::layer (unsigned number) const [inline]
Definition at line 109 of file resultImage.h.
References mLayers.
Referenced by print().
    {
        return mLayers[number];
    }
unsigned ResultImage::layerNum () const [inline]
Definition at line 104 of file resultImage.h.
References mLayers.
Referenced by print().
    {
        return (unsigned)mLayers.size();
    }
void ResultImage::print () [inline]
Definition at line 154 of file resultImage.h.
References layer(), ResultLayerBase::LAYER_TYPE_NAMES, and layerNum().
    {
        printf("Result Image: %d layers", layerNum());
        for (unsigned i = 0; i < layerNum(); i++)
        {
            printf("  %s\n", ResultLayerBase::LAYER_TYPE_NAMES[layer(i)->getType()]);
        }
    }
void ResultImage::setHeight (int height) [inline]
Definition at line 150 of file resultImage.h.
References height(), and mHeight.
Referenced by BaseCalculationThread::initData(), and RecorderThread::processNewData().
{ mHeight = height; }
void ResultImage::setWidth (int width) [inline]
Definition at line 152 of file resultImage.h.
References mWidth, and width().
Referenced by BaseCalculationThread::initData(), and RecorderThread::processNewData().
{ mWidth = width;   }
int ResultImage::width () const [inline]
Definition at line 135 of file resultImage.h.
References mLayers, and mWidth.
Referenced by RecorderDialog::processResult(), BaseHostDialog::processResult(), and setWidth().
    {
        int maxWidth = mWidth;
        for (unsigned i = 0; i < mLayers.size(); i++)
        {
            if (mLayers[i] == NULL)
               continue;
            int newWidth = mLayers[i]->modifyWidth(mWidth);
            maxWidth = std::max(newWidth, maxWidth);
        }
        return maxWidth;
    }
Member Data Documentation
int ResultImage::mHeight [private]
Definition at line 70 of file resultImage.h.
Referenced by height(), and setHeight().
vector<ResultLayerBase *> ResultImage::mLayers [private]
Definition at line 68 of file resultImage.h.
Referenced by addLayer(), drawImage(), height(), layer(), layerNum(), width(), and ~ResultImage().
int ResultImage::mWidth [private]
Definition at line 71 of file resultImage.h.
Referenced by setWidth(), and width().
The documentation for this class was generated from the following file:
applications/base/layers/resultImage.h