DeepView: BinarizeParameters Class Reference
BinarizeParameters Class Reference
Binarize Parameters Binarize Parameters.
#include <binarizeParameters.h>
Public Types
enum FieldId { THRESHOLD_ID, BINARIZE_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
int threshold () const
void setThreshold (int threshold)
template<class VisitorType >
void accept (VisitorType &visitor)
BinarizeParameters ()
BinarizeParameters (int threshold)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mThreshold
Section with variables.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, BinarizeParameters &toSave)
Detailed Description
Binarize Parameters Binarize Parameters.
Definition at line 38 of file binarizeParameters.h.
Member Enumeration Documentation
enum BinarizeParameters::FieldId
Enumerator:
THRESHOLD_ID
BINARIZE_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file binarizeParameters.h.
                 {
        THRESHOLD_ID,
        BINARIZE_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
BinarizeParameters::BinarizeParameters () [inline]
Definition at line 81 of file binarizeParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
BinarizeParameters::BinarizeParameters (int threshold) [inline]
Definition at line 87 of file binarizeParameters.h.
    {
        mThreshold = threshold;
    }
Member Function Documentation
template<class VisitorType > void BinarizeParameters::accept (VisitorType & visitor) [inline]
Definition at line 76 of file binarizeParameters.h.
Referenced by corecvs::BinarizeBlock::deserialize(), and corecvs::BinarizeBlock::serialize().
    {
        visitor.visit(mThreshold,                 static_cast<const IntField *>     (fields()[THRESHOLD_ID]));
    }
static const char* corecvs::BaseReflection< BinarizeParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< BinarizeParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< BinarizeParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* BinarizeParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 58 of file binarizeParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< BinarizeParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< BinarizeParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< BinarizeParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void BinarizeParameters::print () [inline]
Definition at line 101 of file binarizeParameters.h.
    {
        cout << *this;
    }
void BinarizeParameters::setThreshold (int threshold) [inline]
Definition at line 68 of file binarizeParameters.h.
    {
        mThreshold = threshold;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int BinarizeParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file binarizeParameters.cpp.
References corecvs::BaseReflection< BinarizeParameters >::fields(), mThreshold, corecvs::BaseReflection< BinarizeParameters >::naming(), and THRESHOLD_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Binarize Parameters",
        "Binarize Parameters",
        ""
    );
    fields().push_back(
        new IntField
        (
          BinarizeParameters::THRESHOLD_ID,
          offsetof(BinarizeParameters, mThreshold),
          2000,
          "Threshold",
          "Threshold",
          "Threshold"
        )
    );
   return 0;
}
int BinarizeParameters::threshold () const [inline]
Definition at line 62 of file binarizeParameters.h.
Referenced by corecvs::BinarizeBlock::operator()(), and BinarizeParametersControlWidget::setParameters().
    {
        return mThreshold;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, BinarizeParameters & toSave) [friend]
Definition at line 94 of file binarizeParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< BinarizeParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int BinarizeParameters::mThreshold
Section with variables.
Threshold Threshold
Definition at line 52 of file binarizeParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< BinarizeParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/binarizeParameters.h
core/xml/generated/binarizeParameters.cpp