DeepView: corecvs::SerializerVisitor Class Reference
corecvs::SerializerVisitor Class Reference
#include <serializerVisitor.h>
Public Member Functions
SerializerVisitor (XMLNode *_node)
std::string NoSpaces (const char *str)
template<typename inputType , typename reflectionType >
void visit (inputType &field, const reflectionType *fieldDescriptor)
template<class Type >
void visit (const char *tagName, Type &field, const char *fieldName)
* Old style visitor */
template<class Type >
void visit (const char *tagName, int fieldsNum, Type *field[], const char *fieldName[])
Public Attributes
XMLNode * node
Detailed Description
Definition at line 13 of file serializerVisitor.h.
Constructor & Destructor Documentation
corecvs::SerializerVisitor::SerializerVisitor (XMLNode * _node) [inline, explicit]
Definition at line 18 of file serializerVisitor.h.
                                                :
        node(_node)
    {}
Member Function Documentation
string corecvs::SerializerVisitor::NoSpaces (const char * str)
Definition at line 6 of file serializerVisitor.cpp.
{
    string toReturn(str);
//    toReturn.erase(remove_if(toReturn.begin(), toReturn.end(), isspace), toReturn.end());
    toReturn.erase(remove(toReturn.begin(), toReturn.end(), ' '), toReturn.end());
    return toReturn;
}
template<typename inputType , typename reflectionType > void corecvs::SerializerVisitor::visit (inputType & field, const reflectionType * fieldDescriptor) [inline]
Definition at line 25 of file serializerVisitor.h.
References tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLDocument::NewElement(), and tinyxml2::XMLElement::SetAttribute().
    {
        XMLElement* param = node->GetDocument()->NewElement( NoSpaces(fieldDescriptor->getSimpleName()).c_str() );
        param->SetAttribute("value", field);
        node->InsertEndChild(param);
    }
template<class Type > void corecvs::SerializerVisitor::visit (const char * tagName, Type & field, const char * fieldName) [inline]
* Old style visitor */
Definition at line 34 of file serializerVisitor.h.
References tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLDocument::NewElement(), and tinyxml2::XMLElement::SetAttribute().
    {
        XMLElement* param = node->GetDocument()->NewElement( NoSpaces(tagName).c_str() );
        if (strlen(fieldName))  param->SetAttribute(NoSpaces(fieldName).c_str(), field);
        node->InsertEndChild(param);
//        field.accept(*this);
    }
template<class Type > void corecvs::SerializerVisitor::visit (const char * tagName, int fieldsNum, Type * field[], const char * fieldName[]) [inline]
Definition at line 42 of file serializerVisitor.h.
References tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLDocument::NewElement(), and tinyxml2::XMLElement::SetAttribute().
    {
        XMLElement* param = node->GetDocument()->NewElement( NoSpaces(tagName).c_str() );
        for (int i = 0; i < fieldsNum; i++)
            if (strlen(fieldName[i]))
                param->SetAttribute(NoSpaces(fieldName[i]).c_str(), *field[i]);
        node->InsertEndChild(param);
//        field.accept(*this);
    }
Member Data Documentation
XMLNode* corecvs::SerializerVisitor::node
Definition at line 16 of file serializerVisitor.h.
The documentation for this class was generated from the following files:
core/reflection/serializerVisitor.h
core/reflection/serializerVisitor.cpp