DeepView: corecvs::TxtPin Class Reference
corecvs::TxtPin Class Reference
#include <pins.h>
Public Types
enum PinType { INPUT_PIN, OUTPUT_PIN }
Public Member Functions
TxtPin (FilterBlock *_parent, PinType _type, bool auto_init, const char *name="none")
virtual void setInstanceId (int id)
virtual void clear ()
virtual ~TxtPin ()
virtual const char * getTypeName () const
virtual bool isEmpty ()
virtual bool setPin (Pin *source, bool shouldCopy=false)
virtual bool getPin (char *&data, bool shouldCopy=false)
virtual void initPin (char *&data)
char *& getData ()
virtual void deserialize (XMLNode *)
int getInstanceId () const
void breakConnection ()
virtual bool getPin (G12Buffer *&, bool=false)
virtual void initPin (G12Buffer *)
virtual XMLNode * serialize (XMLNode *doc, bool outerPin)
Public Attributes
char * instanceName
PinType type
FilterBlock * parent
int instanceId
Pin * takeFrom
Private Attributes
char * inout
Static Private Attributes
static int instanceCounter = 0
Detailed Description
Definition at line 127 of file pins.h.
Member Enumeration Documentation
enum corecvs::Pin::PinType [inherited]
Enumerator:
INPUT_PIN
OUTPUT_PIN
Definition at line 23 of file pins.h.
                {
        INPUT_PIN,
        OUTPUT_PIN
   };
Constructor & Destructor Documentation
corecvs::TxtPin::TxtPin (FilterBlock * _parent, PinType _type, bool auto_init, const char * name = "none") [inline]
Definition at line 130 of file pins.h.
                                                                                          :
       Pin(_parent, _type, name),
       inout(NULL)
   {
       if (auto_init)  instanceId = ++instanceCounter;
   }
virtual corecvs::TxtPin::~TxtPin () [inline, virtual]
Definition at line 144 of file pins.h.
{}
Member Function Documentation
void corecvs::Pin::breakConnection () [inline, inherited]
Reimplemented in corecvs::OutputPin, and corecvs::InputPin.
Definition at line 43 of file pins.h.
{ takeFrom = NULL; }
virtual void corecvs::TxtPin::clear () [inline, virtual]
Reimplemented from corecvs::Pin.
Definition at line 143 of file pins.h.
{ delete_safe(inout); }
void corecvs::TxtPin::deserialize (XMLNode * node) [virtual]
Reimplemented from corecvs::Pin.
Definition at line 56 of file pins.cpp.
{
    Pin::deserialize(node);
}
char* & corecvs::TxtPin::getData () [inline]
Definition at line 168 of file pins.h.
{ return inout; }
int corecvs::Pin::getInstanceId () const [inline, inherited]
Definition at line 38 of file pins.h.
Referenced by corecvs::FilterBlock::IdPredicate::operator()().
{ return instanceId; }
virtual bool corecvs::Pin::getPin (G12Buffer *& , bool = false) [inline, virtual, inherited]
Reimplemented in corecvs::OutputPin, and corecvs::G12Pin.
Definition at line 54 of file pins.h.
Referenced by corecvs::G12Pin::setPin(), setPin(), and corecvs::ExtraTxtPin< TypeOfPin >::setPin().
   {   std::cerr << "error G12\n";
       return false;
   }
virtual bool corecvs::TxtPin::getPin (char *& data, bool shouldCopy = false) [inline, virtual]
Reimplemented from corecvs::Pin.
Definition at line 157 of file pins.h.
   {
       if (shouldCopy)
       {    data = new char[strlen(inout)+1];
            strncpy(data, inout, 10000);
       }
       else data = inout;
       return true;
   }
virtual const char* corecvs::TxtPin::getTypeName () const [inline, virtual]
Reimplemented from corecvs::Pin.
Definition at line 146 of file pins.h.
{ return "TxtPin"; }
virtual void corecvs::Pin::initPin (G12Buffer *) [inline, virtual, inherited]
Reimplemented in corecvs::G12Pin.
Definition at line 64 of file pins.h.
{ std::cerr << "error G12 initPin"; }
virtual void corecvs::TxtPin::initPin (char *& data) [inline, virtual]
Definition at line 167 of file pins.h.
{ inout = data; }
virtual bool corecvs::TxtPin::isEmpty () [inline, virtual]
Reimplemented from corecvs::Pin.
Definition at line 148 of file pins.h.
{ return inout == NULL; }
XMLNode * corecvs::Pin::serialize (XMLNode * doc, bool outerPin) [virtual, inherited]
Reimplemented in corecvs::OutputPin, and corecvs::InputPin.
Definition at line 17 of file pins.cpp.
References tinyxml2::XMLNode::GetDocument(), corecvs::FilterBlock::getFullName(), corecvs::Pin::getTypeName(), tinyxml2::XMLNode::InsertEndChild(), corecvs::Pin::instanceId, corecvs::Pin::instanceName, tinyxml2::XMLDocument::NewElement(), corecvs::Pin::parent, tinyxml2::XMLElement::SetAttribute(), and corecvs::Pin::takeFrom.
{
    XMLElement* mPin = node->GetDocument()->NewElement("pin");
    mPin->SetAttribute("type", getTypeName());
    mPin->SetAttribute("id", instanceId);
    mPin->SetAttribute("name", instanceName);
    if (!isOuterPin && takeFrom)
    {   mPin->SetAttribute("takeFromBlock", takeFrom->parent->getFullName().c_str());
        mPin->SetAttribute("takeFromPin",   takeFrom->instanceId);
    }
    XMLNode* element = node->InsertEndChild(mPin);
    return element;
}
virtual void corecvs::TxtPin::setInstanceId (int id) [inline, virtual]
Reimplemented from corecvs::Pin.
Definition at line 137 of file pins.h.
   {
       instanceId = id;
       instanceCounter = max(instanceCounter, instanceId);
   }
virtual bool corecvs::TxtPin::setPin (Pin * source, bool shouldCopy = false) [inline, virtual]
Reimplemented from corecvs::Pin.
Definition at line 150 of file pins.h.
References corecvs::Pin::getPin().
   {
       if (NULL != source)
            return source->getPin(inout, shouldCopy);
       else return false;
   }
Member Data Documentation
char* corecvs::TxtPin::inout [private]
Definition at line 173 of file pins.h.
int corecvs::TxtPin::instanceCounter = 0 [static, private]
Definition at line 174 of file pins.h.
int corecvs::Pin::instanceId [inherited]
Definition at line 72 of file pins.h.
Referenced by corecvs::Pin::serialize().
char* corecvs::Pin::instanceName [inherited]
Definition at line 69 of file pins.h.
Referenced by corecvs::Pin::deserialize(), FilterPinPresentation::FilterPinPresentation(), FilterGraphPresentation::nameChanged(), corecvs::FilterBlock::NamePredicate::operator()(), corecvs::Pin::serialize(), and corecvs::Pin::~Pin().
FilterBlock* corecvs::Pin::parent [inherited]
Definition at line 71 of file pins.h.
Referenced by corecvs::CompoundFilter::addPin(), corecvs::Pin::deserialize(), FilterPinPresentation::FilterPinPresentation(), and corecvs::Pin::serialize().
Pin* corecvs::Pin::takeFrom [inherited]
Reimplemented in corecvs::InputPin.
Definition at line 73 of file pins.h.
Referenced by corecvs::FilterGraph::breakConnection(), corecvs::FilterGraph::connect(), corecvs::Pin::deserialize(), FilterPinPresentation::FilterPinPresentation(), and corecvs::Pin::serialize().
PinType corecvs::Pin::type [inherited]
Definition at line 70 of file pins.h.
Referenced by corecvs::FilterGraph::connect(), FilterPinPresentation::drawPinName(), and corecvs::FilterBlock::isOuterPin().
The documentation for this class was generated from the following files:
core/filters/blocks/pins.h
core/filters/blocks/pins.cpp