DeepView: corecvs::ModelToRadialCorrection Class Reference
corecvs::ModelToRadialCorrection Class Reference
#include <radialFunc.h>
Public Member Functions
ModelToRadialCorrection (const RadialCorrection &lockedDimentions, bool guessCenter, bool guessTangent, int polynomPower)
RadialCorrection getRadial (const double in[]) const
void getModel (const RadialCorrection &correction, double in[]) const
int getModelSize () const
Public Attributes
RadialCorrection mLockedDimentions
bool mGuessCenter
bool mGuessTangent
int mPolynomPower
Detailed Description
Definition at line 8 of file radialFunc.h.
Constructor & Destructor Documentation
corecvs::ModelToRadialCorrection::ModelToRadialCorrection (const RadialCorrection & lockedDimentions, bool guessCenter, bool guessTangent, int polynomPower) [inline]
Definition at line 25 of file radialFunc.h.
      :
        mLockedDimentions(lockedDimentions),
        mGuessCenter(guessCenter),
        mGuessTangent(guessTangent),
        mPolynomPower(polynomPower)
    {}
Member Function Documentation
void corecvs::ModelToRadialCorrection::getModel (const RadialCorrection & correction, double in[]) const
Definition at line 29 of file radialFunc.cpp.
References corecvs::LensCorrectionParametres::center, corecvs::LensCorrectionParametres::koeff, mGuessCenter, mGuessTangent, corecvs::RadialCorrection::mParams, mPolynomPower, corecvs::LensCorrectionParametres::p1, corecvs::LensCorrectionParametres::p2, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    int count = 0;
    if (mGuessCenter) {
        in[count++] = correction.mParams.center.x();
        in[count++] = correction.mParams.center.y();
    }
    if (mGuessTangent) {
        in[count++] = correction.mParams.p1;
        in[count++] = correction.mParams.p2;
    }
    for (int i = 0; i < mPolynomPower; i++) {
        in[count++] = correction.mParams.koeff[i];
    }
}
int corecvs::ModelToRadialCorrection::getModelSize () const [inline]
Definition at line 40 of file radialFunc.h.
References mGuessCenter, mGuessTangent, and mPolynomPower.
    {
        return mPolynomPower +
               (mGuessCenter  ? 2 : 0) +
               (mGuessTangent ? 2 : 0);
    }
RadialCorrection corecvs::ModelToRadialCorrection::getRadial (const double in[]) const
Definition at line 10 of file radialFunc.cpp.
References corecvs::LensCorrectionParametres::center, corecvs::LensCorrectionParametres::koeff, mGuessCenter, mGuessTangent, mLockedDimentions, corecvs::RadialCorrection::mParams, mPolynomPower, corecvs::LensCorrectionParametres::p1, corecvs::LensCorrectionParametres::p2, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::AnglePointsFunction::operator()(), and corecvs::DistPointsFunction::operator()().
{
    int count = 0;
    RadialCorrection result = mLockedDimentions;
    if (mGuessCenter) {
        result.mParams.center.x() = in[count++];
        result.mParams.center.y() = in[count++];
    }
    if (mGuessTangent) {
        result.mParams.p1 = in[count++];
        result.mParams.p2 = in[count++];
    }
    result.mParams.koeff.clear();
    for (int i = 0; i < mPolynomPower; i++) {
        result.mParams.koeff.push_back(in[count++]);
    }
    return result;
}
Member Data Documentation
bool corecvs::ModelToRadialCorrection::mGuessCenter
Definition at line 11 of file radialFunc.h.
Referenced by getModel(), getModelSize(), and getRadial().
bool corecvs::ModelToRadialCorrection::mGuessTangent
Definition at line 12 of file radialFunc.h.
Referenced by getModel(), getModelSize(), and getRadial().
RadialCorrection corecvs::ModelToRadialCorrection::mLockedDimentions
Definition at line 10 of file radialFunc.h.
Referenced by corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), and getRadial().
int corecvs::ModelToRadialCorrection::mPolynomPower
Definition at line 13 of file radialFunc.h.
Referenced by getModel(), getModelSize(), and getRadial().
The documentation for this class was generated from the following files:
core/alignment/radialFunc.h
core/alignment/radialFunc.cpp