DeepView: corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier > Class Template Reference
corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier > Class Template Reference
Template for generic AdaBoost algorithm.
#include <adaBoost.h>
Private Types
typedef
ClassifierGenerator::Classifier SimpleClassifierType
typedef
ClassifierGenerator::InputType InputType
Private Member Functions
AdaBoost ()
AdaBoostedClassifier
< SimpleClassifierType > * getBoostedClassifier (AdaBoostInput< InputType > &inputs, ClassifierGenerator &generator)
virtual ~AdaBoost ()
Private Attributes
int maxIterations
double errorPersent
Detailed Description
template<typename ClassifierGenerator, typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>>
class corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >
Template for generic AdaBoost algorithm.
Definition at line 202 of file adaBoost.h.
Member Typedef Documentation
template<typename ClassifierGenerator , typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>> typedef ClassifierGenerator::InputType corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::InputType [private]
Definition at line 205 of file adaBoost.h.
template<typename ClassifierGenerator , typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>> typedef ClassifierGenerator::Classifier corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::SimpleClassifierType [private]
Definition at line 204 of file adaBoost.h.
Constructor & Destructor Documentation
template<typename ClassifierGenerator , typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>> corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::AdaBoost () [inline, private]
Definition at line 207 of file adaBoost.h.
{};
template<typename ClassifierGenerator , typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>> virtual corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::~AdaBoost () [inline, private, virtual]
Definition at line 282 of file adaBoost.h.
{};
Member Function Documentation
template<typename ClassifierGenerator , typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>> AdaBoostedClassifier<SimpleClassifierType>* corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::getBoostedClassifier (AdaBoostInput< InputType > & inputs, ClassifierGenerator & generator) [inline, private]
Definition at line 214 of file adaBoost.h.
References corecvs::AdaBoostedClassifier< _SimpleClassifierType >::addClassifier(), corecvs::ClassifierStatistics::addValue(), corecvs::AdaBoostedClassifier< _SimpleClassifierType >::children, corecvs::AdaBoostedClassifier< _SimpleClassifierType >::classify(), corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::errorPersent, corecvs::ClassifierStatistics::falseNegative, corecvs::ClassifierStatistics::falsePositive, corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::maxIterations, corecvs::AdaBoostInput< InputType >::normalizeWeigths(), corecvs::ClassifierStatistics::trueNegative, and corecvs::ClassifierStatistics::truePositive.
    {
        AdaBoostedClassifier<SimpleClassifierType> *classifier = new
                AdaBoostedClassifier<SimpleClassifierType>();
        for (int iteration = 0; iteration < maxIterations; iteration++)
        {
            double classifierCost;
            SimpleClassifierType *simpleClassifier =
                   generator.getBestClassifier(inputs, &classifierCost);
            double alpha = 0.5 * log ((1.0 - classifierCost) / classifierCost);
            double alphaExp = exp(alpha);
            /*Regenerate the results*/
            ClassifierStatistics stats;
            typename AdaBoostInput<InputType>::iterator it;
            for (it = inputs.begin(); it != inputs.end(); it++)
            {
                bool prediction = simpleClassifier->classify((*it).x);
                /* If guess was wrong we will increase the weight */
//                double alphaRes = (prediction == (*it).y) ? (1.0f / alphaExp) : (alphaExp);
                (*it).weight *= alphaExp;
                stats.addValue(prediction, (*it).y);
            }
            /*Inputs are corrected now*/
            inputs.normalizeWeigths();
    //        printf("Result so far TP=%d TN=%d FP=%d FN=%d\n", stats.truePositive, stats.trueNegative, stats.falsePositive, stats.falseNegative);
            classifier->addClassifier(simpleClassifier, alpha);
            /*Test for total boosted*/
            ClassifierStatistics totalStats;
            fstream outbreaks;
            outbreaks.open("outbreaks", fstream::out);
            for (unsigned i = 0; i < inputs.size(); i++)
            {
                bool isPositive = inputs[i].y;
                bool prediction = classifier->classify(inputs[i].x);
                totalStats.addValue(prediction, isPositive);
                if (isPositive != prediction)
                {
                    if (isPositive)
                        outbreaks << "FN " << i << "\n";
                    else
                        outbreaks << "FP " << i << "\n";
                }
            }
            outbreaks.close();
            printf("Boosted Result %zu classifiers so far TP=%d TN=%d FP=%d FN=%d\n",
                   classifier->children.size(),
                   totalStats.truePositive, totalStats.trueNegative,
                   totalStats.falsePositive, totalStats.falseNegative);
            if ((double)(totalStats.falsePositive + totalStats.falseNegative) / inputs.size() < errorPersent )
                break;
       }
    }
Member Data Documentation
template<typename ClassifierGenerator , typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>> double corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::errorPersent [private]
Definition at line 210 of file adaBoost.h.
Referenced by corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::getBoostedClassifier().
template<typename ClassifierGenerator , typename RealBoostedClassifier = AdaBoostedClassifier<typename ClassifierGenerator::Classifier>> int corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::maxIterations [private]
Definition at line 207 of file adaBoost.h.
Referenced by corecvs::AdaBoost< ClassifierGenerator, RealBoostedClassifier >::getBoostedClassifier().
The documentation for this class was generated from the following file:
core/boosting/adaBoost.h