DeepView: CapSettingsDialog Class Reference
CapSettingsDialog Class Reference
#include <capSettingsDialog.h>
Public Slots
void parameterChanged (int id)
void resetPressed (int id)
void resetAllPressed ()
void refreshLimitsPressed ()
Public Member Functions
CapSettingsDialog (QWidget *parent=0, ImageCaptureInterface *pInterface=0)
~CapSettingsDialog ()
void clearDialog ()
void refreshDialog ()
ParameterEditorWidget * getParameter (int i)
virtual void loadFromQSettings (const QString &fileName, const QString &_root)
virtual void saveToQSettings (const QString &fileName, const QString &_root)
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
virtual void loadParamWidget (WidgetLoader &)
virtual void saveParamWidget (WidgetSaver &)
Protected Member Functions
void changeEvent (QEvent *e)
void showEvent (QShowEvent *e)
Private Attributes
Ui_CapSettingsDialog * mUi
ImageCaptureInterface * mCaptureInterface
QSignalMapper * signalMapper
QSignalMapper * resetSignalMapper
QMap< int,
ParameterEditorWidget * > sliders
CameraParameters mLeftCameraParameters
CameraParameters mRightCameraParameters
Detailed Description
Definition at line 20 of file capSettingsDialog.h.
Constructor & Destructor Documentation
CapSettingsDialog::CapSettingsDialog (QWidget * parent = 0, ImageCaptureInterface * pInterface = 0)
Definition at line 11 of file capSettingsDialog.cpp.
References mUi, and refreshDialog().
                                                                                       :
        QWidget(parent),
        mUi(new Ui::CapSettingsDialog),
        mCaptureInterface(pInterface),
        signalMapper(NULL),
        resetSignalMapper(NULL)
{
    mUi->setupUi(this);
    setWindowFlags(windowFlags() ^ Qt::WindowMinimizeButtonHint);
    refreshDialog();
}
CapSettingsDialog::~CapSettingsDialog ()
Definition at line 189 of file capSettingsDialog.cpp.
References clearDialog(), mCaptureInterface, and mUi.
{
    clearDialog();
    mCaptureInterface = NULL;
    delete_safe(mUi);
}
Member Function Documentation
void CapSettingsDialog::changeEvent (QEvent * e) [protected]
Definition at line 230 of file capSettingsDialog.cpp.
References mUi.
{
    QWidget::changeEvent(e);
    switch (e->type()) {
    case QEvent::LanguageChange:
        mUi->retranslateUi(this);
        break;
    default:
        break;
    }
}
void CapSettingsDialog::clearDialog ()
Definition at line 25 of file capSettingsDialog.cpp.
References mUi, resetSignalMapper, and signalMapper.
Referenced by refreshLimitsPressed(), and ~CapSettingsDialog().
{
    delete_safe(signalMapper);
    delete_safe(resetSignalMapper);
    QLayout *layout = mUi->scrollAreaWidgetContents->layout();
    QLayoutItem *item;
    while ((item = layout->takeAt(0)) != 0)
    {
        delete item->widget();
        delete_safe(item);
    }
}
ParameterEditorWidget* CapSettingsDialog::getParameter (int i) [inline]
Definition at line 29 of file capSettingsDialog.h.
References sliders.
    {
        return sliders[i];
    }
void CapSettingsDialog::loadFromQSettings (const QString & fileName, const QString & _root) [virtual]
Definition at line 110 of file capSettingsDialog.cpp.
References ImageCaptureInterface::getInterfaceName(), mCaptureInterface, CameraParameters::names, ParameterEditorWidget::setValue(), sliders, and ParameterEditorWidget::value().
Referenced by BaseHostDialog::initCapture().
{
    if (mCaptureInterface == NULL)
    {
        return;
    }
    QString interfaceName = mCaptureInterface->getInterfaceName();
    if (interfaceName.isEmpty())
    {
        qDebug("CapSettingsDialog::loadFromQSettings(): Loading won't happen. Interface is NULL");
        return;
    }
    qDebug() << "CapSettingsDialog::loadFromQSettings(): Interface name: " << interfaceName;
    QSettings *mSettings = new QSettings(fileName, QSettings::IniFormat);
    mSettings->beginGroup(_root + ":" + interfaceName + ":");
    QMapIterator<int, ParameterEditorWidget *> i(sliders);
    while (i.hasNext())
    {
        i.next();
        int id = i.key();
        const char *name = CameraParameters::names[id];
        ParameterEditorWidget *widget = i.value();
        double value = widget->value();
        double newValue = mSettings->value(name, value).toDouble();
        qDebug() << "   " << QString(name).leftJustified(16, ' ') << ": " << value << " -> " << newValue;
        widget->setValue(newValue);
    }
    mSettings->endGroup();
    delete mSettings;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
virtual void SaveableWidget::loadParamWidget (WidgetLoader &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 119 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::loadFromQSettings().
{}
void CapSettingsDialog::parameterChanged (int id) [slot]
Definition at line 196 of file capSettingsDialog.cpp.
References mCaptureInterface, ImageCaptureInterface::setCaptureProperty(), and sliders.
Referenced by refreshDialog().
{
    //printf("Changed: %d\n", id);
    /*if (id == 0)
    {
        sliders[1]->setValue(0);
    }*/
    mCaptureInterface->setCaptureProperty(id, sliders[id]->value());
}
void CapSettingsDialog::refreshDialog ()
Definition at line 39 of file capSettingsDialog.cpp.
References CaptureParameter::active(), CaptureParameter::autoSupported(), CameraParameters::FIRST, ImageCaptureInterface::getCaptureProperty(), CaptureParameter::getMenuItem(), CaptureParameter::getMenuItemNumber(), CaptureParameter::getMenuValue(), CaptureParameter::hasMenuItems(), CaptureParameter::isMenu(), CameraParameters::LAST, CaptureParameter::maximum(), CameraParameters::mCameraControls, mCaptureInterface, CaptureParameter::minimum(), mLeftCameraParameters, mRightCameraParameters, mUi, CameraParameters::names, parameterChanged(), ParameterSelector::pushOption(), ImageCaptureInterface::queryCameraParameters(), resetPressed(), resetSignalMapper, ParameterEditorWidget::setAutoSupported(), ParameterSlider::setMaximum(), ParameterSlider::setMinimum(), ParameterEditorWidget::setName(), ParameterEditorWidget::setValue(), signalMapper, and sliders.
Referenced by CapSettingsDialog(), and refreshLimitsPressed().
{
   if (mCaptureInterface == NULL)
   {
       return;
   }
    //ImageCaptureInterface::CapErrorCode resLeft =
   mCaptureInterface->queryCameraParameters(mLeftCameraParameters);
   //ImageCaptureInterface::CapErrorCode resRight =
   mCaptureInterface->queryCameraParameters(mRightCameraParameters);
   QLayout *layout = mUi->scrollAreaWidgetContents->layout();
   signalMapper = new QSignalMapper(this);
   resetSignalMapper = new QSignalMapper(this);
   for (int i = CameraParameters::FIRST; i < CameraParameters::LAST; i++)
   {
       CaptureParameter &params = mLeftCameraParameters.mCameraControls[i];
       if (!params.active()) {
           continue;
       }
       ParameterEditorWidget *paramEditor = NULL;
       if (!params.isMenu() || !params.hasMenuItems())
       {
           ParameterSlider* paramSlider = new ParameterSlider(this);
           paramSlider->setMinimum(params.minimum());
           paramSlider->setMaximum(params.maximum());
           paramEditor = paramSlider;
       } else {
           ParameterSelector* paramSelector = new ParameterSelector(this);
           for (unsigned index = 0; index < params.getMenuItemNumber(); index++)
           {
               paramSelector->pushOption(
                   params.getMenuItem(index),
                   params.getMenuValue(index));
           }
           paramEditor = paramSelector;
       }
       paramEditor->setName(QString(CameraParameters::names[i]));
       paramEditor->setAutoSupported(params.autoSupported());
       paramEditor->setEnabled(params.active());
       int value;
       mCaptureInterface->getCaptureProperty(i, &value);
       paramEditor->setValue(value);
       layout->addWidget(paramEditor);
       sliders.insert(i, paramEditor);
       connect(paramEditor, SIGNAL(valueChanged(int)), signalMapper, SLOT(map()));
       signalMapper->setMapping(paramEditor, i);
       connect(paramEditor, SIGNAL(resetPressed()), resetSignalMapper, SLOT(map()));
       resetSignalMapper->setMapping(paramEditor, i);
   }
   layout->addItem(new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Expanding));
   //layout->addChildLayout()(new QSpacerItem(0,0));
   connect(signalMapper,      SIGNAL(mapped(int)), this, SLOT(parameterChanged(int)));
   connect(resetSignalMapper, SIGNAL(mapped(int)), this, SLOT(resetPressed(int)));
}
void CapSettingsDialog::refreshLimitsPressed () [slot]
Definition at line 182 of file capSettingsDialog.cpp.
References clearDialog(), and refreshDialog().
{
    clearDialog();
    refreshDialog();
}
void CapSettingsDialog::resetAllPressed () [slot]
Definition at line 219 of file capSettingsDialog.cpp.
References CaptureParameter::active(), CameraParameters::FIRST, CameraParameters::LAST, CameraParameters::mCameraControls, mLeftCameraParameters, and resetPressed().
{
    for (int i = CameraParameters::FIRST; i < CameraParameters::LAST; i++)
    {
        CaptureParameter &params = mLeftCameraParameters.mCameraControls[i];
        if (!params.active())
            continue;
        resetPressed(i);
    }
}
void CapSettingsDialog::resetPressed (int id) [slot]
Definition at line 206 of file capSettingsDialog.cpp.
References CaptureParameter::defaultValue(), CameraParameters::mCameraControls, mCaptureInterface, mLeftCameraParameters, ImageCaptureInterface::setCaptureProperty(), and sliders.
Referenced by refreshDialog(), and resetAllPressed().
{
    if (mCaptureInterface == NULL)
    {
        return;
    }
    //printf("Changed: %d\n", id);
    mCaptureInterface->setCaptureProperty(id, mLeftCameraParameters.mCameraControls[id].defaultValue());
    sliders[id]->setValue(mLeftCameraParameters.mCameraControls[id].defaultValue());
}
virtual void SaveableWidget::saveParamWidget (WidgetSaver &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 120 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::saveToQSettings().
{}
void CapSettingsDialog::saveToQSettings (const QString & fileName, const QString & _root) [virtual]
Definition at line 147 of file capSettingsDialog.cpp.
References ImageCaptureInterface::getInterfaceName(), mCaptureInterface, CameraParameters::names, sliders, and ParameterEditorWidget::value().
{
    if (mCaptureInterface == NULL)
    {
        return;
    }
    QString interfaceName = mCaptureInterface->getInterfaceName();
    if (interfaceName.isEmpty())
    {
        return;
    }
    qDebug() << "CapSettingsDialog::saveToQSettings(): Interface name: " << interfaceName;
    QSettings *mSettings = new QSettings(fileName, QSettings::IniFormat);
    mSettings->beginGroup(_root + ":" + interfaceName + ":");
    QMapIterator<int, ParameterEditorWidget *> i(sliders);
    while (i.hasNext())
    {
        i.next();
        int id = i.key();
        const char *name = CameraParameters::names[id];
        ParameterEditorWidget *widget = i.value();
        double value = widget->value();
        mSettings->setValue(name, value);
        qDebug() << "   " << QString(name).leftJustified(16, ' ') << ": " << value;
    }
    mSettings->endGroup();
    delete mSettings;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void CapSettingsDialog::showEvent (QShowEvent * e) [protected]
Definition at line 242 of file capSettingsDialog.cpp.
References mUi.
{
    Q_UNUSED(e);
#if 0
    if (!disabledAlertShown  && !(mUi->aeEnabledCheckBox->isEnabled()))
    {
        disabledAlertShown = true;
        QMessageBox msgBox;
        msgBox.setText("Error querying camera exposure properties. You will not be able to modify exposure settings.\n"
                       "This may occur because you are using different camera devices or because your cameras do not support"
                       "exposure settings.");
        msgBox.exec();
    }
#endif
}
Member Data Documentation
ImageCaptureInterface* CapSettingsDialog::mCaptureInterface [private]
Definition at line 50 of file capSettingsDialog.h.
Referenced by loadFromQSettings(), parameterChanged(), refreshDialog(), resetPressed(), saveToQSettings(), and ~CapSettingsDialog().
CameraParameters CapSettingsDialog::mLeftCameraParameters [private]
Definition at line 56 of file capSettingsDialog.h.
Referenced by refreshDialog(), resetAllPressed(), and resetPressed().
CameraParameters CapSettingsDialog::mRightCameraParameters [private]
Definition at line 57 of file capSettingsDialog.h.
Referenced by refreshDialog().
Ui_CapSettingsDialog* CapSettingsDialog::mUi [private]
Definition at line 49 of file capSettingsDialog.h.
Referenced by CapSettingsDialog(), changeEvent(), clearDialog(), refreshDialog(), showEvent(), and ~CapSettingsDialog().
QSignalMapper* CapSettingsDialog::resetSignalMapper [private]
Definition at line 53 of file capSettingsDialog.h.
Referenced by clearDialog(), and refreshDialog().
QSignalMapper* CapSettingsDialog::signalMapper [private]
Definition at line 52 of file capSettingsDialog.h.
Referenced by clearDialog(), and refreshDialog().
QMap<int, ParameterEditorWidget *> CapSettingsDialog::sliders [private]
Definition at line 54 of file capSettingsDialog.h.
Referenced by getParameter(), loadFromQSettings(), parameterChanged(), refreshDialog(), resetPressed(), and saveToQSettings().
The documentation for this class was generated from the following files:
utils/uis/capSettingsDialog.h
utils/uis/capSettingsDialog.cpp