DeepView: Draw3dCameraParametersControlWidget Class Reference
Draw3dCameraParametersControlWidget Class Reference
#include <draw3dCameraParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
Draw3dCameraParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~Draw3dCameraParametersControlWidget ()
Draw3dCameraParameters * createParameters () const
void setParameters (const Draw3dCameraParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_Draw3dCameraParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file draw3dCameraParametersControlWidget.h.
Constructor & Destructor Documentation
Draw3dCameraParametersControlWidget::Draw3dCameraParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 17 of file draw3dCameraParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::Draw3dCameraParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->fovHSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fovVSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->nearPlaneSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->farPlaneSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->styleComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->colorControlWidget, SIGNAL(paramsChanged()), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->secondaryColorControlWidget, SIGNAL(paramsChanged()), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->textureCorrodinatesComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->textureAlphaSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->textureScaleSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalMatrixTypeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalLeftCamCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalLeftAlphaSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalRightCamCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalRightAlphaSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
Draw3dCameraParametersControlWidget::~Draw3dCameraParametersControlWidget ()
Definition at line 42 of file draw3dCameraParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void Draw3dCameraParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file draw3dCameraParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
Draw3dCameraParameters * Draw3dCameraParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 64 of file draw3dCameraParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    RgbColorParameters *tmp5 = NULL;
    RgbColorParameters *tmp6 = NULL;
    Draw3dCameraParameters *result = new Draw3dCameraParameters(
          mUi->fovHSpinBox->value()
        , mUi->fovVSpinBox->value()
        , mUi->nearPlaneSpinBox->value()
        , mUi->farPlaneSpinBox->value()
        , static_cast<Draw3dStyle::Draw3dStyle>(mUi->styleComboBox->currentIndex())
        , * (tmp5 = mUi->colorControlWidget->createParameters())
        , * (tmp6 = mUi->secondaryColorControlWidget->createParameters())
        , static_cast<Draw3dTextureGen::Draw3dTextureGen>(mUi->textureCorrodinatesComboBox->currentIndex())
        , mUi->textureAlphaSpinBox->value()
        , mUi->textureScaleSpinBox->value()
        , mUi->decalMatrixTypeSpinBox->value()
        , mUi->decalLeftCamCheckBox->isChecked()
        , mUi->decalLeftAlphaSpinBox->value()
        , mUi->decalRightCamCheckBox->isChecked()
        , mUi->decalRightAlphaSpinBox->value()
    );
    delete tmp5;
    delete tmp6;
    return result;
}
virtual BaseReflectionStatic* Draw3dCameraParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from ParametersControlWidgetBase.
Definition at line 25 of file draw3dCameraParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void Draw3dCameraParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 48 of file draw3dCameraParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    Draw3dCameraParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void Draw3dCameraParametersControlWidget::paramsChanged () [signal]
Referenced by Draw3dCameraParametersControlWidget(), and setParameters().
void Draw3dCameraParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 56 of file draw3dCameraParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    Draw3dCameraParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void Draw3dCameraParametersControlWidget::setParameters (const Draw3dCameraParameters & input)
Definition at line 96 of file draw3dCameraParametersControlWidget.cpp.
References Draw3dCameraParameters::color(), Draw3dCameraParameters::decalLeftAlpha(), Draw3dCameraParameters::decalLeftCam(), Draw3dCameraParameters::decalMatrixType(), Draw3dCameraParameters::decalRightAlpha(), Draw3dCameraParameters::decalRightCam(), Draw3dCameraParameters::farPlane(), Draw3dCameraParameters::fovH(), Draw3dCameraParameters::fovV(), mUi, Draw3dCameraParameters::nearPlane(), paramsChanged(), Draw3dCameraParameters::secondaryColor(), Draw3dCameraParameters::style(), Draw3dCameraParameters::textureAlpha(), Draw3dCameraParameters::textureCorrodinates(), and Draw3dCameraParameters::textureScale().
Referenced by CameraScene::getContolWidget(), loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->fovHSpinBox->setValue(input.fovH());
    mUi->fovVSpinBox->setValue(input.fovV());
    mUi->nearPlaneSpinBox->setValue(input.nearPlane());
    mUi->farPlaneSpinBox->setValue(input.farPlane());
    mUi->styleComboBox->setCurrentIndex(input.style());
    mUi->colorControlWidget->setParameters(input.color());
    mUi->secondaryColorControlWidget->setParameters(input.secondaryColor());
    mUi->textureCorrodinatesComboBox->setCurrentIndex(input.textureCorrodinates());
    mUi->textureAlphaSpinBox->setValue(input.textureAlpha());
    mUi->textureScaleSpinBox->setValue(input.textureScale());
    mUi->decalMatrixTypeSpinBox->setValue(input.decalMatrixType());
    mUi->decalLeftCamCheckBox->setChecked(input.decalLeftCam());
    mUi->decalLeftAlphaSpinBox->setValue(input.decalLeftAlpha());
    mUi->decalRightCamCheckBox->setChecked(input.decalRightCam());
    mUi->decalRightAlphaSpinBox->setValue(input.decalRightAlpha());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void Draw3dCameraParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 119 of file draw3dCameraParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    Draw3dCameraParameters *inputCasted = static_cast<Draw3dCameraParameters *>(input);
    setParameters(*inputCasted);
}
void Draw3dCameraParametersControlWidget::valueChanged () [signal]
Referenced by Draw3dCameraParametersControlWidget().
Member Data Documentation
bool Draw3dCameraParametersControlWidget::autoInit [private]
Definition at line 45 of file draw3dCameraParametersControlWidget.h.
Ui_Draw3dCameraParametersControlWidget* Draw3dCameraParametersControlWidget::mUi [private]
Definition at line 44 of file draw3dCameraParametersControlWidget.h.
Referenced by createParameters(), Draw3dCameraParametersControlWidget(), setParameters(), and ~Draw3dCameraParametersControlWidget().
QString Draw3dCameraParametersControlWidget::rootPath [private]
Definition at line 46 of file draw3dCameraParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/3d/draw3dCameraParametersControlWidget.h
utils/3d/generated/draw3dCameraParametersControlWidget.cpp