DeepView: DistortionParameters Class Reference
DistortionParameters Class Reference
#include <distortionParameters.h>
Public Member Functions
DistortionParameters ()
DistortionParameters (double rad, double scale)
Vector2dd getCentre ()
vector< Vector2dd > getPoints ()
void setCentre (Vector2dd const &centre)
void addPoint (Vector2dd const &point)
void clear ()
bool needCalculateParams ()
double getRadius ()
double getScale ()
Private Attributes
Vector2dd mCentre
vector< Vector2dd > mStraightPoints
double mRad
double mScale
bool mNeedCalculateRad
Detailed Description
Definition at line 7 of file distortionParameters.h.
Constructor & Destructor Documentation
DistortionParameters::DistortionParameters () [inline]
Definition at line 10 of file distortionParameters.h.
{
        mRad = 300;
        mScale = 500;
        mNeedCalculateRad = true;
    }
DistortionParameters::DistortionParameters (double rad, double scale) [inline]
Definition at line 15 of file distortionParameters.h.
    {
        mRad = rad;
        mScale = scale;
        mNeedCalculateRad = false;
    }
Member Function Documentation
void DistortionParameters::addPoint (Vector2dd const & point) [inline]
Definition at line 34 of file distortionParameters.h.
    {
        mStraightPoints.insert(mStraightPoints.begin(), point);
    }
void DistortionParameters::clear () [inline]
Definition at line 38 of file distortionParameters.h.
    {
        mStraightPoints.clear();
    }
Vector2dd DistortionParameters::getCentre () [inline]
Definition at line 22 of file distortionParameters.h.
    {
        return mCentre;
    }
vector<Vector2dd> DistortionParameters::getPoints () [inline]
Definition at line 26 of file distortionParameters.h.
Referenced by DistortionWidget::doInversionTransform().
    {
        return mStraightPoints;
    }
double DistortionParameters::getRadius () [inline]
Definition at line 47 of file distortionParameters.h.
Referenced by DistortionWidget::doInversionTransform().
    {
        return mRad;
    }
double DistortionParameters::getScale () [inline]
Definition at line 51 of file distortionParameters.h.
Referenced by DistortionWidget::doInversionTransform().
    {
        return mScale;
    }
bool DistortionParameters::needCalculateParams () [inline]
Definition at line 43 of file distortionParameters.h.
Referenced by DistortionWidget::doInversionTransform().
    {
        return mNeedCalculateRad;
    }
void DistortionParameters::setCentre (Vector2dd const & centre) [inline]
Definition at line 30 of file distortionParameters.h.
    {
        mCentre = centre;
    }
Member Data Documentation
Vector2dd DistortionParameters::mCentre [private]
Definition at line 57 of file distortionParameters.h.
bool DistortionParameters::mNeedCalculateRad [private]
Definition at line 61 of file distortionParameters.h.
double DistortionParameters::mRad [private]
Definition at line 59 of file distortionParameters.h.
double DistortionParameters::mScale [private]
Definition at line 60 of file distortionParameters.h.
vector<Vector2dd> DistortionParameters::mStraightPoints [private]
Definition at line 58 of file distortionParameters.h.
The documentation for this class was generated from the following file:
utils/distortioncorrector/distortionParameters.h