DeepView: corecvs::FilterBlock Class Reference
corecvs::FilterBlock Class Reference
#include <filterBlock.h>
Classes
class IdPredicate
class NamePredicate
Public Types
enum SortOfBlock { INPUT_FILTER, OUTPUT_FILTER, PROCESSING_FILTER, COMPOUND_FILTER }
Public Member Functions
FilterBlock (int id=-1)
virtual void setInstanceName (char *name)
virtual char * getInstanceName ()
virtual int getInstanceId () const
virtual const char * getTypeName () const
virtual string getFullName ()
virtual int operator() (void)
virtual bool setParameters (const void *newParameters)
virtual void * getParameters ()
bool isOuterPin (Pin *pin)
Pin * PinByName (vector< Pin * > &vec, const char *name)
Pin * inPinByName (const char *name)
Pin * outPinByName (const char *name)
Pin * PinById (vector< Pin * > &vec, int id)
Pin * inPinById (int id)
Pin * outPinById (int id)
virtual XMLNode * serialize (XMLNode *)
virtual void deserialize (XMLNode *, bool force=true)
virtual void clear ()
virtual ~FilterBlock ()
Public Attributes
int x
int y
FilterGraph * parent
int instanceId
int inLinks
SortOfBlock sort
vector< Pin * > inputPins
vector< Pin * > outputPins
Protected Attributes
char * instanceName
Private Member Functions
void deserializePins (vector< Pin * > &vec, XMLNode *node, bool force)
Detailed Description
Definition at line 27 of file filterBlock.h.
Member Enumeration Documentation
enum corecvs::FilterBlock::SortOfBlock
Enumerator:
INPUT_FILTER
OUTPUT_FILTER
PROCESSING_FILTER
COMPOUND_FILTER
Definition at line 30 of file filterBlock.h.
    {   INPUT_FILTER,
        OUTPUT_FILTER,
        PROCESSING_FILTER,
        COMPOUND_FILTER
    };
Constructor & Destructor Documentation
corecvs::FilterBlock::FilterBlock (int id = -1)
Definition at line 15 of file filterBlock.cpp.
                                 :
//    parent(_parent),
    parent(NULL),
    instanceId(id),
    inLinks(0),
    sort(PROCESSING_FILTER),
    instanceName(NULL)
{
//    if (parent)
//    {  if (instanceId == -1)
//            instanceId = ++parent->blockCounter;
//       else parent->blockCounter = max(parent->blockCounter, instanceId);
//    }
}
corecvs::FilterBlock::~FilterBlock () [virtual]
Definition at line 30 of file filterBlock.cpp.
References COMPOUND_FILTER, inputPins, instanceName, outputPins, and sort.
{
    free(instanceName);
    instanceName = NULL;
    if (sort == COMPOUND_FILTER)  return;
    vector<Pin*>::iterator itPins;
    for (itPins = inputPins.begin(); itPins != inputPins.end(); ++itPins)
        /*if (!isOuterPin(*itPins))*/  delete_safe(*itPins);
    for (itPins = outputPins.begin(); itPins != outputPins.end(); ++itPins)
        /*if (!isOuterPin(*itPins))*/  delete_safe(*itPins);
}
Member Function Documentation
void corecvs::FilterBlock::clear () [virtual]
Reimplemented in corecvs::CompoundFilter.
Definition at line 109 of file filterBlock.cpp.
References outputPins.
Referenced by corecvs::FilterGraph::execute(), and corecvs::OutputFilter::~OutputFilter().
{
    for (unsigned int i = 0; i < outputPins.size(); i++)
        outputPins[i]->clear();
}
void corecvs::FilterBlock::deserialize (XMLNode * node, bool force = true) [virtual]
Reimplemented in corecvs::OperationFilter, corecvs::CompoundFilter, corecvs::OutputFilter, corecvs::InputFilter, corecvs::CannyFilter, corecvs::BackgroundFilter, corecvs::BitSelectorFilter, corecvs::GainOffsetFilter, corecvs::SobelFilter, corecvs::MaskFilterBlock, corecvs::BinarizeBlock, and corecvs::ThickeningBlock.
Definition at line 77 of file filterBlock.cpp.
References tinyxml2::XMLElement::Attribute(), deserializePins(), tinyxml2::XMLNode::FirstChild(), inputPins, tinyxml2::XMLElement::IntAttribute(), tinyxml2::XMLNode::NextSibling(), outputPins, setInstanceName(), tinyxml2::XMLNode::ToElement(), x, and y.
Referenced by corecvs::FilterGraph::deserialize(), and corecvs::CompoundFilter::loadGraph().
{
    XMLNode* p1 = node->FirstChild();
    XMLNode* p2 = p1->FirstChild();
    setInstanceName( strdup(p2->ToElement()->Attribute("value")) );
    p2 = p2->NextSibling();
    x = p2->ToElement()->IntAttribute("value");
    p2 = p2->NextSibling();
    y = p2->ToElement()->IntAttribute("value");
    p1 = p1->NextSibling();
    deserializePins(inputPins, p1, force);
    p1 = p1->NextSibling();
    deserializePins(outputPins, p1, force);
} // deserialize
void corecvs::FilterBlock::deserializePins (vector< Pin * > & vec, XMLNode * node, bool force) [private]
Definition at line 95 of file filterBlock.cpp.
References corecvs::Pin::deserialize(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLElement::IntAttribute(), tinyxml2::XMLNode::NextSibling(), PinById(), and tinyxml2::XMLNode::ToElement().
Referenced by deserialize().
{
    unsigned int s = node->ToElement()->IntAttribute("size");
    XMLNode* p2 = node->FirstChild();
    for (unsigned int j = 0; j < s; j++)
    {   Pin* pin = NULL;
        if (force)
        {    if (j < vec.size())  pin = vec[j]; }
        else pin = PinById(vec, p2->ToElement()->IntAttribute("id"));
        if (pin)  pin->deserialize(p2);
        p2 = p2->NextSibling();
    }
}
virtual string corecvs::FilterBlock::getFullName () [inline, virtual]
Definition at line 73 of file filterBlock.h.
References getInstanceId(), and getTypeName().
Referenced by corecvs::FilterGraph::execute(), FilterBlockPresentation::FilterBlockPresentation(), corecvs::FilterGraph::NamePredicate::operator()(), and corecvs::Pin::serialize().
    {
        std::ostringstream oss;
        oss << getTypeName() << " " << getInstanceId();
        return oss.str();
    }
virtual int corecvs::FilterBlock::getInstanceId () const [inline, virtual]
Reimplemented in corecvs::OperationFilter, corecvs::OutputFilter, corecvs::InputFilter, corecvs::CannyFilter, corecvs::SobelFilter, corecvs::BackgroundFilter, corecvs::BitSelectorFilter, corecvs::MaskFilterBlock, corecvs::BinarizeBlock, corecvs::ThickeningBlock, corecvs::TxtFilter, and corecvs::CompoundFilter.
Definition at line 70 of file filterBlock.h.
Referenced by getFullName().
{ return -1; }
virtual char* corecvs::FilterBlock::getInstanceName () [inline, virtual]
Reimplemented in OpenCVFilter.
Definition at line 44 of file filterBlock.h.
References instanceName.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), and FilterBlockPresentation::updateBlock().
{ return instanceName; }
virtual void* corecvs::FilterBlock::getParameters () [inline, virtual]
Reimplemented in corecvs::OperationFilter, corecvs::OutputFilter, corecvs::InputFilter, corecvs::CannyFilter, corecvs::BackgroundFilter, corecvs::BitSelectorFilter, corecvs::GainOffsetFilter, corecvs::SobelFilter, corecvs::CompoundFilter, corecvs::MaskFilterBlock, corecvs::BinarizeBlock, and corecvs::ThickeningBlock.
Definition at line 92 of file filterBlock.h.
    {
        printf("Getting parameters\n");
        return NULL;
    }
virtual const char* corecvs::FilterBlock::getTypeName () const [inline, virtual]
Reimplemented in corecvs::OperationFilter, corecvs::OutputFilter, corecvs::InputFilter, corecvs::CannyFilter, corecvs::GainOffsetFilter, corecvs::SobelFilter, corecvs::BackgroundFilter, corecvs::BitSelectorFilter, corecvs::MaskFilterBlock, corecvs::TxtFilter, corecvs::BinarizeBlock, corecvs::ThickeningBlock, and corecvs::CompoundFilter.
Definition at line 71 of file filterBlock.h.
Referenced by FilterBlockPresentation::drawBlockName(), getFullName(), and serialize().
{ return "none"; }
Pin* corecvs::FilterBlock::inPinById (int id) [inline]
Definition at line 123 of file filterBlock.h.
References inputPins, and PinById().
{ return PinById(inputPins,  id); }
Pin* corecvs::FilterBlock::inPinByName (const char * name) [inline]
Definition at line 112 of file filterBlock.h.
References inputPins, and PinByName().
{ return PinByName(inputPins,  name); }
bool corecvs::FilterBlock::isOuterPin (Pin * pin) [inline]
Definition at line 98 of file filterBlock.h.
References INPUT_FILTER, corecvs::Pin::INPUT_PIN, OUTPUT_FILTER, corecvs::Pin::OUTPUT_PIN, sort, and corecvs::Pin::type.
Referenced by serialize().
    {
        return (sort == INPUT_FILTER  && pin->type == Pin::INPUT_PIN) ||
               (sort == OUTPUT_FILTER && pin->type == Pin::OUTPUT_PIN);
    }
virtual int corecvs::FilterBlock::operator() (void) [inline, virtual]
Reimplemented in corecvs::OperationFilter, corecvs::OutputFilter, corecvs::InputFilter, corecvs::CannyFilter, corecvs::BitSelectorFilter, corecvs::GainOffsetFilter, corecvs::SobelFilter, corecvs::BackgroundFilter, corecvs::CompoundFilter, corecvs::TxtFilter, corecvs::MaskFilterBlock, corecvs::BinarizeBlock, corecvs::ThickeningBlock, and OpenCVFilter.
Definition at line 80 of file filterBlock.h.
References instanceName.
    {
        printf("FilterBlock::Executing block %s\n", instanceName);
        return 0;
    }
Pin* corecvs::FilterBlock::outPinById (int id) [inline]
Definition at line 124 of file filterBlock.h.
References outputPins, and PinById().
Referenced by corecvs::Pin::deserialize().
{ return PinById(outputPins, id); }
Pin* corecvs::FilterBlock::outPinByName (const char * name) [inline]
Definition at line 113 of file filterBlock.h.
References outputPins, and PinByName().
{ return PinByName(outputPins, name); }
Pin* corecvs::FilterBlock::PinById (vector< Pin * > & vec, int id) [inline]
Definition at line 115 of file filterBlock.h.
Referenced by deserializePins(), inPinById(), and outPinById().
    {
        vector<Pin*>::iterator pin = std::find_if(vec.begin(), vec.end(), IdPredicate(id));
        if (pin == vec.end())  return NULL;
        return *pin;
    }
Pin* corecvs::FilterBlock::PinByName (vector< Pin * > & vec, const char * name) [inline]
Definition at line 104 of file filterBlock.h.
Referenced by inPinByName(), and outPinByName().
    {
        vector<Pin*>::iterator pin = std::find_if(vec.begin(), vec.end(), NamePredicate(name));
        if (pin == vec.end())  return NULL;
        return *pin;
    }
XMLNode * corecvs::FilterBlock::serialize (XMLNode * node) [virtual]
Reimplemented in corecvs::OperationFilter, corecvs::CompoundFilter, corecvs::OutputFilter, corecvs::InputFilter, corecvs::CannyFilter, corecvs::BackgroundFilter, corecvs::BitSelectorFilter, corecvs::GainOffsetFilter, corecvs::SobelFilter, corecvs::MaskFilterBlock, corecvs::BinarizeBlock, and corecvs::ThickeningBlock.
Definition at line 43 of file filterBlock.cpp.
References tinyxml2::XMLNode::GetDocument(), getTypeName(), inputPins, tinyxml2::XMLNode::InsertEndChild(), instanceId, instanceName, isOuterPin(), tinyxml2::XMLDocument::NewElement(), outputPins, tinyxml2::XMLElement::SetAttribute(), x, and y.
Referenced by corecvs::CompoundFilter::loadGraph().
{
    XMLElement* block = node->GetDocument()->NewElement("block");
    block->SetAttribute("type", getTypeName());
    block->SetAttribute("id", instanceId);
    XMLNode* blockNode = node->InsertEndChild(block);
    XMLNode* presentationNode = blockNode->InsertEndChild(node->GetDocument()->NewElement("presentation"));
    XMLElement* presentation[] = { node->GetDocument()->NewElement("name"),
                                   node->GetDocument()->NewElement("x"),
                                   node->GetDocument()->NewElement("y") };
    presentation[0]->SetAttribute("value", instanceName);
    presentation[1]->SetAttribute("value", x);
    presentation[2]->SetAttribute("value", y);
    for (unsigned int j = 0; j < 3; j++)
        presentationNode->InsertEndChild(presentation[j]);
    XMLElement* in = node->GetDocument()->NewElement("inputPins");
    in->SetAttribute("size", (int)inputPins.size());
    XMLNode* ins = blockNode->InsertEndChild(in);
    for (unsigned int j = 0; j < inputPins.size(); j++)
        inputPins[j]->serialize(ins, isOuterPin(inputPins[j]));
    XMLElement* out = node->GetDocument()->NewElement("outputPins");
    out->SetAttribute("size", (int)outputPins.size());
    XMLNode* outs = blockNode->InsertEndChild(out);
    for (unsigned int j = 0; j < outputPins.size(); j++)
        outputPins[j]->serialize(outs, isOuterPin(outputPins[j]));
    return blockNode;
} // serialize
virtual void corecvs::FilterBlock::setInstanceName (char * name) [inline, virtual]
Reimplemented in corecvs::OutputFilter, and corecvs::InputFilter.
Definition at line 39 of file filterBlock.h.
References instanceName.
Referenced by deserialize(), FilterBlockPresentation::FilterBlockPresentation(), corecvs::CompoundFilter::loadGraph(), and FilterGraphPresentation::nameChanged().
    {
        if (instanceName)  free(instanceName);
        instanceName = name;
    }
virtual bool corecvs::FilterBlock::setParameters (const void * newParameters) [inline, virtual]
Reimplemented in corecvs::OperationFilter, corecvs::OutputFilter, corecvs::InputFilter, corecvs::CannyFilter, corecvs::BackgroundFilter, corecvs::BitSelectorFilter, corecvs::GainOffsetFilter, corecvs::SobelFilter, corecvs::CompoundFilter, corecvs::TxtFilter, corecvs::MaskFilterBlock, corecvs::BinarizeBlock, corecvs::ThickeningBlock, and OpenCVFilter.
Definition at line 86 of file filterBlock.h.
Referenced by FilterBlockPresentation::parametersChanged().
    {
        printf("Setting parameters %p\n", newParameters);
        return false;
    }
Member Data Documentation
int corecvs::FilterBlock::inLinks
Definition at line 141 of file filterBlock.h.
vector<Pin*> corecvs::FilterBlock::inputPins
Definition at line 143 of file filterBlock.h.
Referenced by corecvs::FilterGraph::addBlock(), FilterGraphPresentation::addFilter(), FilterBlockPresentation::createPinPresentations(), FilterGraphPresentation::deleteItem(), deserialize(), FilterGraphPresentation::drawGraph(), corecvs::FilterGraph::execute(), FilterPinPresentation::FilterPinPresentation(), inPinById(), inPinByName(), corecvs::InputFilter::InputFilter(), corecvs::CompoundFilter::loadGraph(), corecvs::BinarizeBlock::operator()(), corecvs::ThickeningBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::SobelFilter::operator()(), corecvs::GainOffsetFilter::operator()(), corecvs::BitSelectorFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::InputFilter::operator()(), corecvs::OutputFilter::operator()(), corecvs::OutputFilter::OutputFilter(), corecvs::FilterGraph::removeBlock(), serialize(), corecvs::InputFilter::setInstanceName(), corecvs::CompoundFilter::stealPinsFromGraph(), corecvs::CompoundFilter::~CompoundFilter(), and ~FilterBlock().
int corecvs::FilterBlock::instanceId
Definition at line 140 of file filterBlock.h.
Referenced by corecvs::CompoundFilter::CompoundFilter(), corecvs::TxtFilter::getInstanceId(), corecvs::InputFilter::getInstanceId(), corecvs::OutputFilter::getInstanceId(), corecvs::InputFilter::InputFilter(), corecvs::OutputFilter::OutputFilter(), serialize(), and corecvs::TxtFilter::TxtFilter().
char* corecvs::FilterBlock::instanceName [protected]
Definition at line 146 of file filterBlock.h.
Referenced by getInstanceName(), operator()(), serialize(), corecvs::InputFilter::setInstanceName(), corecvs::OutputFilter::setInstanceName(), setInstanceName(), and ~FilterBlock().
vector<Pin*> corecvs::FilterBlock::outputPins
Definition at line 144 of file filterBlock.h.
Referenced by corecvs::FilterGraph::addBlock(), FilterGraphPresentation::addFilter(), clear(), FilterBlockPresentation::createPinPresentations(), FilterGraphPresentation::deleteItem(), deserialize(), corecvs::InputFilter::InputFilter(), corecvs::CompoundFilter::loadGraph(), corecvs::BinarizeBlock::operator()(), corecvs::ThickeningBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::SobelFilter::operator()(), corecvs::GainOffsetFilter::operator()(), corecvs::BitSelectorFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::InputFilter::operator()(), corecvs::OutputFilter::operator()(), outPinById(), outPinByName(), corecvs::OutputFilter::OutputFilter(), corecvs::FilterGraph::removeBlock(), serialize(), corecvs::OutputFilter::setInstanceName(), corecvs::CompoundFilter::stealPinsFromGraph(), corecvs::TxtFilter::TxtFilter(), corecvs::CompoundFilter::~CompoundFilter(), and ~FilterBlock().
FilterGraph* corecvs::FilterBlock::parent
Definition at line 139 of file filterBlock.h.
Referenced by corecvs::FilterGraph::addBlock(), corecvs::CompoundFilter::CompoundFilter(), corecvs::Pin::deserialize(), FilterPinPresentation::FilterPinPresentation(), and corecvs::CompoundFilter::loadGraph().
SortOfBlock corecvs::FilterBlock::sort
Definition at line 142 of file filterBlock.h.
Referenced by corecvs::FilterGraph::addBlock(), FilterGraphPresentation::addFilter(), FilterGraphPresentation::blockItemSelected(), corecvs::CompoundFilter::CompoundFilter(), FilterBlockPresentation::createPinPresentations(), FilterGraphPresentation::deleteItem(), corecvs::Pin::deserialize(), corecvs::InputFilter::InputFilter(), isOuterPin(), DiagramScene::mouseDoubleClickEvent(), corecvs::OutputFilter::OutputFilter(), and ~FilterBlock().
int corecvs::FilterBlock::x
Definition at line 136 of file filterBlock.h.
Referenced by deserialize(), FilterBlockPresentation::drawBlock(), DiagramScene::mouseReleaseEvent(), serialize(), and FilterBlockPresentation::updateBlock().
int corecvs::FilterBlock::y
Definition at line 137 of file filterBlock.h.
Referenced by deserialize(), FilterBlockPresentation::drawBlock(), DiagramScene::mouseReleaseEvent(), serialize(), and FilterBlockPresentation::updateBlock().
The documentation for this class was generated from the following files:
core/filters/blocks/filterBlock.h
core/filters/blocks/filterBlock.cpp