DeepView: MaskingParametersControlWidget Class Reference
MaskingParametersControlWidget Class Reference
#include <maskingParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
MaskingParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~MaskingParametersControlWidget ()
MaskingParameters * createParameters () const
void setParameters (const MaskingParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_MaskingParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 11 of file maskingParametersControlWidget.h.
Constructor & Destructor Documentation
MaskingParametersControlWidget::MaskingParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file maskingParametersControlWidget.cpp.
References mUi, and paramsChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::MaskingParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->invertCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
}
MaskingParametersControlWidget::~MaskingParametersControlWidget ()
Definition at line 26 of file maskingParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void MaskingParametersControlWidget::changeParameters () [inline, slot]
Definition at line 32 of file maskingParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
MaskingParameters * MaskingParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 48 of file maskingParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    MaskingParameters *result = new MaskingParameters(
          mUi->invertCheckBox->isChecked()
    );
    return result;
}
virtual BaseReflectionStatic* MaskingParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 23 of file maskingParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void MaskingParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 32 of file maskingParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    MaskingParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void MaskingParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by MaskingParametersControlWidget(), and setParameters().
void MaskingParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 40 of file maskingParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    MaskingParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void MaskingParametersControlWidget::setParameters (const MaskingParameters & input)
Definition at line 62 of file maskingParametersControlWidget.cpp.
References MaskingParameters::invert(), mUi, and paramsChanged().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->invertCheckBox->setChecked(input.invert());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void MaskingParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 71 of file maskingParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    MaskingParameters *inputCasted = static_cast<MaskingParameters *>(input);
    setParameters(*inputCasted);
}
void MaskingParametersControlWidget::valueChanged () [signal]
Member Data Documentation
bool MaskingParametersControlWidget::autoInit [private]
Definition at line 43 of file maskingParametersControlWidget.h.
Ui_MaskingParametersControlWidget* MaskingParametersControlWidget::mUi [private]
Definition at line 42 of file maskingParametersControlWidget.h.
Referenced by createParameters(), MaskingParametersControlWidget(), setParameters(), and ~MaskingParametersControlWidget().
QString MaskingParametersControlWidget::rootPath [private]
Definition at line 44 of file maskingParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/maskingParametersControlWidget.h
utils/filters/ui/maskingParametersControlWidget.cpp