DeepView: FoldableWidget Class Reference
FoldableWidget Class Reference
#include <foldableWidget.h>
Public Slots
void changeFolding ()
Public Member Functions
FoldableWidget (QWidget *parent=0, QString const &name="", QWidget *centralWidget=0, bool startFolded=true, bool isAdvanced=false)
~FoldableWidget ()
void setMainWidget (QWidget *widget)
bool isFolded ()
Private Attributes
Ui::Widget * ui
bool mIsFolded
QString mName
QSize mCurrentSize
QSize mPrevSize
Detailed Description
Definition at line 9 of file foldableWidget.h.
Constructor & Destructor Documentation
FoldableWidget::FoldableWidget (QWidget * parent = 0, QString const & name = "", QWidget * centralWidget = 0, bool startFolded = true, bool isAdvanced = false) [explicit]
Definition at line 7 of file foldableWidget.cpp.
References changeFolding(), ConfigManager::configName(), mName, setMainWidget(), and ui.
                           :
    QWidget(parent),
    ui(new Ui::Widget),
    mIsFolded(false),
    mName(name)
{
    ui->setupUi(this);
    ui->foldLabel->setText("Fold " + mName);
    connect(ui->foldButton, SIGNAL(clicked()), this, SLOT(changeFolding()));
    setMainWidget(centralWidget);
    QSettings settings(ConfigManager::configName(), QSettings::IniFormat);
    settings.beginGroup("foldedWidgets");
    startFolded = settings.value(name, true).toBool();
    settings.endGroup();
    if (startFolded)
    {
        changeFolding();
    }
    if (isAdvanced)
    {
        setProperty("tags", QString("advanced"));
    }
}
FoldableWidget::~FoldableWidget ()
Definition at line 41 of file foldableWidget.cpp.
References ConfigManager::configName(), mIsFolded, mName, and ui.
{
    QSettings settings(ConfigManager::configName(), QSettings::IniFormat);
    settings.beginGroup("foldedWidgets");
    settings.setValue(mName, mIsFolded);
    settings.endGroup();
    delete ui;
}
Member Function Documentation
void FoldableWidget::changeFolding () [slot]
Definition at line 51 of file foldableWidget.cpp.
References mCurrentSize, mIsFolded, mName, mPrevSize, and ui.
Referenced by FoldableWidget().
{
    mIsFolded = !mIsFolded;
    mCurrentSize = mPrevSize;
    mPrevSize = size();
    resize(mCurrentSize);
    if (mIsFolded) {
        ui->foldButton->setArrowType(Qt::RightArrow);
        ui->foldLabel->setText("Unfold " + mName);
    }
    else {
        ui->foldButton->setArrowType(Qt::DownArrow);
        ui->foldLabel->setText("Fold " + mName);
    }
    ui->placeholder->setVisible(!mIsFolded);
    ui->placeholder->setEnabled(!mIsFolded);
}
bool FoldableWidget::isFolded () [inline]
Definition at line 20 of file foldableWidget.h.
References mIsFolded.
{ return mIsFolded; }
void FoldableWidget::setMainWidget (QWidget * widget)
Definition at line 72 of file foldableWidget.cpp.
References ui.
Referenced by FoldableWidget().
{
    ui->placeholder->setLayout(new QVBoxLayout());
    ui->placeholder->layout()->addWidget(widget);
    ui->placeholder->layout()->setContentsMargins(0, 0, 0, 0);
    updateGeometry();
}
Member Data Documentation
QSize FoldableWidget::mCurrentSize [private]
Definition at line 31 of file foldableWidget.h.
Referenced by changeFolding().
bool FoldableWidget::mIsFolded [private]
Definition at line 27 of file foldableWidget.h.
Referenced by changeFolding(), isFolded(), and ~FoldableWidget().
QString FoldableWidget::mName [private]
Definition at line 29 of file foldableWidget.h.
Referenced by changeFolding(), FoldableWidget(), and ~FoldableWidget().
QSize FoldableWidget::mPrevSize [private]
Definition at line 32 of file foldableWidget.h.
Referenced by changeFolding().
Ui::Widget* FoldableWidget::ui [private]
Definition at line 26 of file foldableWidget.h.
Referenced by changeFolding(), FoldableWidget(), setMainWidget(), and ~FoldableWidget().
The documentation for this class was generated from the following files:
utils/widgets/foldableWidget.h
utils/widgets/foldableWidget.cpp