DeepView: corecvs::LevenbergMarquardt Class Reference
corecvs::LevenbergMarquardt Class Reference
#include <levenmarq.h>
Public Member Functions
LevenbergMarquardt (int _maxIterations=25, double _startLambda=10, double _lambdaFactor=2.0)
vector< double > fit (const vector< double > &input, const vector< double > &output)
Marquardt-Levenberg algoritim is a fast optimisation algorithm.
Public Attributes
FunctionArgs * f
FunctionArgs * normalisation
double startLambda
double lambdaFactor
int maxIterations
Detailed Description
Definition at line 23 of file levenmarq.h.
Constructor & Destructor Documentation
corecvs::LevenbergMarquardt::LevenbergMarquardt (int _maxIterations = 25, double _startLambda = 10, double _lambdaFactor = 2.0) [inline]
Definition at line 32 of file levenmarq.h.
                                                                                                      :
        f(NULL),
        normalisation(NULL),
        startLambda(_startLambda),
        lambdaFactor(_lambdaFactor),
        maxIterations(_maxIterations)
        {};
Member Function Documentation
vector< double > corecvs::LevenbergMarquardt::fit (const vector< double > & input, const vector< double > & output)
Marquardt-Levenberg algoritim is a fast optimisation algorithm.
<Will hold the current function result
<Will hold current difference to traget
Definition at line 22 of file levenmarq.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, ASSERT_TRUE_P, f, corecvs::FunctionArgs::getJacobian(), corecvs::AbstractBufferParams::h, corecvs::FunctionArgs::inputs, corecvs::Matrix::inv(), corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric(), lambdaFactor, maxIterations, normalisation, corecvs::FunctionArgs::outputs, corecvs::FixedArrayBase< RealType, ElementType >::size(), startLambda, corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElementsSq(), and corecvs::Matrix::t().
Referenced by corecvs::DisplacementBuffer::CacheInverse(), DistortionWidget::doLinesTransform(), DistortionWidget::doTransformLM(), corecvs::HomographyReconstructor::getBestHomographyLM(), and corecvs::EssentialEstimator::getEssentialLM().
{
#ifdef TRACE_PROGRESS
    cout << "================== Starting LM fit ================== " << endl;
    cout << "[" << flush;
#endif
    Vector beta(input);
    Vector target(output);
    ASSERT_TRUE  ( f != NULL, "Function is NULL");
    ASSERT_TRUE_P( beta.size() == f->inputs, ("input guess has wrong dimension %d instead of %d\n", beta.size(), f->inputs));
    ASSERT_TRUE_P( (int)output.size() == f->outputs, ("output has wrong dimension %d instead of %d\n", (int)output.size(), f->outputs));
    Vector y(f->outputs);    /**<Will hold the current function result*/
    Vector diff(f->outputs); /**<Will hold current difference to traget*/
    Vector delta(f->inputs);
    Vector yNew(f->outputs);
    Vector diffNew(f->outputs);
    FunctionArgs &F = *f;
    bool converged = false;
    double lambda = startLambda;
    for (int g = 0; g < maxIterations && lambda < std::numeric_limits<double>::max() && !converged; g++)
    {
#ifdef TRACE_PROGRESS
        if ((g % ((maxIterations / 100) + 1) == 0))
        {
            cout << "#" << flush;
        }
#endif
        Matrix J = f->getJacobian(&(beta[0]));
#ifdef TRACE
        cout << "New Jacobian:" << endl << J << endl;
#endif
        Matrix JT = J.t();
        Matrix JTJ = JT * J;
        F(beta, y);
        diff = target - y;
        Vector d = JT * diff;
        double norm = diff.sumAllElementsSq();
#ifdef TRACE
        cout << "Now  :" <<  norm << " " << lambda << endl;
#endif
        while (true)
        {
            if (norm == 0.0)
            {
#ifdef TRACE_PROGRESS
                cout << "Algorithm fully converged" << endl;
#endif
                converged = true;
                break;
            }
            if (!(lambda < std::numeric_limits<double>::max()))
            {
#ifdef TRACE_PROGRESS
                cout << "Algorithm seem to be trapped at point: " << endl;
                cout << "After: " << g << " iterations" << endl;
                cout << beta << endl;
#endif
#ifdef TRACE
                cout << "Current Jacobian:" << endl << J << endl;
                cout << "Current JTJ:" << endl << JTJ << endl;
                cout << "previous delta was:" << endl << delta << endl;
                int old = cout.precision(30);
                cout << "guess:" << endl << beta << endl;
                F(beta, yNew);
                cout << "value:" << endl << yNew.l2Metric() << endl;
                F(beta + delta, yNew);
                cout << "value at +step:" << endl << yNew.l2Metric() << endl;
                F(beta - delta, yNew);
                cout << "value at -step:" << endl << yNew.l2Metric() << endl;
                for (int i = 0; i < delta.size(); i++)
                {
                    delta[i] = 0.0001 * J.a(0,i);
                }
                F(beta + delta, yNew);
                cout << "value at +J:" << endl << yNew.l2Metric() << endl;
                F(beta - delta, yNew);
                cout << "value at -J:" << endl << yNew.l2Metric() << endl;
                cout.precision(old);
#endif
                break;
            }
            // Make a temporary copy
            Matrix A(JTJ);
            Vector B(d);
            for (int j = 0; j < A.h; j++)
            {
                double a = A.a(j, j) + lambda;
                //double b = A.a(j, j) * (1.0 + lambda);
                A.a(j, j) = a;
            }
            delta = A.inv() * B;
            F(beta + delta, yNew);
            diffNew = target - yNew;
            double normNew = diffNew.sumAllElementsSq();
#ifdef TRACE
            cout << "  Guess:" <<  normNew << " - ";
#endif
            if (normNew < norm) // If the current solution is better
            {
#ifdef TRACE
                cout << "Accepted" << endl;
#endif
                lambda /= lambdaFactor;
                norm = normNew;
                beta += delta;
                if (normalisation != NULL)
                {
                    Vector normBeta(beta.size());
                    normalisation->operator()(beta, normBeta);
                    beta = normBeta;
                }
                break;
            }
            else
            {
#ifdef TRACE
                cout << "Rejected lambda up" << endl;
#endif
                lambda *= lambdaFactor;// Current solution is worse. Try new lambda
            }
        }
    }
#ifdef TRACE_PROGRESS
    cout << "]" << endl;
#endif
    vector<double> result;
    result.reserve(f->inputs);
    for (int i = 0; i < f->inputs; i++)
        result.push_back(beta[i]);
    return result;
}
Member Data Documentation
FunctionArgs* corecvs::LevenbergMarquardt::f
Definition at line 26 of file levenmarq.h.
Referenced by corecvs::DisplacementBuffer::CacheInverse(), DistortionWidget::doLinesTransform(), DistortionWidget::doTransformLM(), fit(), corecvs::HomographyReconstructor::getBestHomographyLM(), and corecvs::EssentialEstimator::getEssentialLM().
double corecvs::LevenbergMarquardt::lambdaFactor
Definition at line 29 of file levenmarq.h.
Referenced by fit(), and corecvs::EssentialEstimator::getEssentialLM().
int corecvs::LevenbergMarquardt::maxIterations
Definition at line 30 of file levenmarq.h.
Referenced by fit(), corecvs::HomographyReconstructor::getBestHomographyLM(), and corecvs::EssentialEstimator::getEssentialLM().
FunctionArgs* corecvs::LevenbergMarquardt::normalisation
Definition at line 27 of file levenmarq.h.
Referenced by fit(), and corecvs::EssentialEstimator::getEssentialLM().
double corecvs::LevenbergMarquardt::startLambda
Definition at line 28 of file levenmarq.h.
Referenced by fit(), and corecvs::EssentialEstimator::getEssentialLM().
The documentation for this class was generated from the following files:
core/math/levenmarq.h
core/math/levenmarq.cpp