DeepView: BackgroundFilterParametersControlWidget Class Reference
BackgroundFilterParametersControlWidget Class Reference
#include <backgroundFilterParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
BackgroundFilterParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~BackgroundFilterParametersControlWidget ()
BackgroundFilterParameters * createParameters () const
void setParameters (const BackgroundFilterParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_BackgroundFilterParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 11 of file backgroundFilterParametersControlWidget.h.
Constructor & Destructor Documentation
BackgroundFilterParametersControlWidget::BackgroundFilterParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file backgroundFilterParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::BackgroundFilterParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->thresholdSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
BackgroundFilterParametersControlWidget::~BackgroundFilterParametersControlWidget ()
Definition at line 26 of file backgroundFilterParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void BackgroundFilterParametersControlWidget::changeParameters () [inline, slot]
Definition at line 33 of file backgroundFilterParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
BackgroundFilterParameters * BackgroundFilterParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 48 of file backgroundFilterParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    BackgroundFilterParameters *result = new BackgroundFilterParameters(
          mUi->thresholdSpinBox->value()
    );
    return result;
}
virtual BaseReflectionStatic* BackgroundFilterParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 24 of file backgroundFilterParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void BackgroundFilterParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 32 of file backgroundFilterParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    BackgroundFilterParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void BackgroundFilterParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by BackgroundFilterParametersControlWidget(), and setParameters().
void BackgroundFilterParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 40 of file backgroundFilterParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    BackgroundFilterParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void BackgroundFilterParametersControlWidget::setParameters (const BackgroundFilterParameters & input)
Definition at line 62 of file backgroundFilterParametersControlWidget.cpp.
References mUi, paramsChanged(), and BackgroundFilterParameters::threshold().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->thresholdSpinBox->setValue(input.threshold());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void BackgroundFilterParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 71 of file backgroundFilterParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    BackgroundFilterParameters *inputCasted = static_cast<BackgroundFilterParameters *>(input);
    setParameters(*inputCasted);
}
void BackgroundFilterParametersControlWidget::valueChanged () [signal]
Referenced by BackgroundFilterParametersControlWidget().
Member Data Documentation
bool BackgroundFilterParametersControlWidget::autoInit [private]
Definition at line 44 of file backgroundFilterParametersControlWidget.h.
Ui_BackgroundFilterParametersControlWidget* BackgroundFilterParametersControlWidget::mUi [private]
Definition at line 43 of file backgroundFilterParametersControlWidget.h.
Referenced by BackgroundFilterParametersControlWidget(), createParameters(), setParameters(), and ~BackgroundFilterParametersControlWidget().
QString BackgroundFilterParametersControlWidget::rootPath [private]
Definition at line 45 of file backgroundFilterParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/backgroundFilterParametersControlWidget.h
utils/filters/ui/backgroundFilterParametersControlWidget.cpp