DeepView: tinyxml2::XMLHandle Class Reference
tinyxml2::XMLHandle Class Reference
A XMLHandle is a class that wraps a node pointer with null checks; this is an incredibly useful thing.
#include <tinyxml2.h>
Public Member Functions
XMLHandle (XMLNode *node)
Create a handle from any node (at any depth of the tree.) This can be a null pointer.
XMLHandle (XMLNode &node)
Create a handle from a node.
XMLHandle (const XMLHandle &ref)
Copy constructor.
XMLHandle & operator= (const XMLHandle &ref)
Assignment.
XMLHandle FirstChild ()
Get the first child of this handle.
XMLHandle FirstChildElement (const char *value=0)
Get the first child element of this handle.
XMLHandle LastChild ()
Get the last child of this handle.
XMLHandle LastChildElement (const char *_value=0)
Get the last child element of this handle.
XMLHandle PreviousSibling ()
Get the previous sibling of this handle.
XMLHandle PreviousSiblingElement (const char *_value=0)
Get the previous sibling element of this handle.
XMLHandle NextSibling ()
Get the next sibling of this handle.
XMLHandle NextSiblingElement (const char *_value=0)
Get the next sibling element of this handle.
XMLNode * ToNode ()
Safe cast to XMLNode. This can return null.
XMLElement * ToElement ()
Safe cast to XMLElement. This can return null.
XMLText * ToText ()
Safe cast to XMLText. This can return null.
XMLUnknown * ToUnknown ()
Safe cast to XMLUnknown. This can return null.
XMLDeclaration * ToDeclaration ()
Safe cast to XMLDeclaration. This can return null.
Private Attributes
XMLNode * _node
Detailed Description
A XMLHandle is a class that wraps a node pointer with null checks; this is an incredibly useful thing.
Note that XMLHandle is not part of the TinyXML DOM structure. It is a separate utility class.
Take an example:
    <Document>
        <Element attributeA = "valueA">
            <Child attributeB = "value1" />
            <Child attributeB = "value2" />
        </Element>
    </Document>
Assuming you want the value of "attributeB" in the 2nd "Child" element, it's very easy to write a *lot* of code that looks like:
    XMLElement* root = document.FirstChildElement( "Document" );
    if ( root )
    {
        XMLElement* element = root->FirstChildElement( "Element" );
        if ( element )
        {
            XMLElement* child = element->FirstChildElement( "Child" );
            if ( child )
            {
                XMLElement* child2 = child->NextSiblingElement( "Child" );
                if ( child2 )
                {
                    // Finally do something useful.
And that doesn't even cover "else" cases. XMLHandle addresses the verbosity of such code. A XMLHandle checks for null pointers so it is perfectly safe and correct to use:
    XMLHandle docHandle( &document );
    XMLElement* child2 = docHandle.FirstChild( "Document" ).FirstChild( "Element" ).FirstChild().NextSibling().ToElement();
    if ( child2 )
    {
        // do something useful
Which is MUCH more concise and useful.
It is also safe to copy handles - internally they are nothing more than node pointers.
    XMLHandle handleCopy = handle;
See also XMLConstHandle, which is the same as XMLHandle, but operates on const objects.
Definition at line 1614 of file tinyxml2.h.
Constructor & Destructor Documentation
tinyxml2::XMLHandle::XMLHandle (XMLNode * node) [inline]
Create a handle from any node (at any depth of the tree.) This can be a null pointer.
Definition at line 1618 of file tinyxml2.h.
References _node.
Referenced by FirstChild(), FirstChildElement(), LastChild(), LastChildElement(), NextSibling(), NextSiblingElement(), PreviousSibling(), and PreviousSiblingElement().
{
        _node = node;
    }
tinyxml2::XMLHandle::XMLHandle (XMLNode & node) [inline]
Create a handle from a node.
Definition at line 1622 of file tinyxml2.h.
References _node.
{
        _node = &node;
    }
tinyxml2::XMLHandle::XMLHandle (const XMLHandle & ref) [inline]
Copy constructor.
Definition at line 1626 of file tinyxml2.h.
References _node.
{
        _node = ref._node;
    }
Member Function Documentation
XMLHandle tinyxml2::XMLHandle::FirstChild () [inline]
Get the first child of this handle.
Definition at line 1636 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::FirstChild(), and XMLHandle().
{
        return XMLHandle( _node ? _node->FirstChild() : 0 );
    }
XMLHandle tinyxml2::XMLHandle::FirstChildElement (const char * value = 0) [inline]
Get the first child element of this handle.
Definition at line 1640 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::FirstChildElement(), and XMLHandle().
{
        return XMLHandle( _node ? _node->FirstChildElement( value ) : 0 );
    }
XMLHandle tinyxml2::XMLHandle::LastChild () [inline]
Get the last child of this handle.
Definition at line 1644 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::LastChild(), and XMLHandle().
{
        return XMLHandle( _node ? _node->LastChild() : 0 );
    }
XMLHandle tinyxml2::XMLHandle::LastChildElement (const char * _value = 0) [inline]
Get the last child element of this handle.
Definition at line 1648 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::LastChildElement(), and XMLHandle().
{
        return XMLHandle( _node ? _node->LastChildElement( _value ) : 0 );
    }
XMLHandle tinyxml2::XMLHandle::NextSibling () [inline]
Get the next sibling of this handle.
Definition at line 1660 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::NextSibling(), and XMLHandle().
{
        return XMLHandle( _node ? _node->NextSibling() : 0 );
    }
XMLHandle tinyxml2::XMLHandle::NextSiblingElement (const char * _value = 0) [inline]
Get the next sibling element of this handle.
Definition at line 1664 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::NextSiblingElement(), and XMLHandle().
{
        return XMLHandle( _node ? _node->NextSiblingElement( _value ) : 0 );
    }
XMLHandle& tinyxml2::XMLHandle::operator= (const XMLHandle & ref) [inline]
Assignment.
Definition at line 1630 of file tinyxml2.h.
References _node.
{
        _node = ref._node;
        return *this;
    }
XMLHandle tinyxml2::XMLHandle::PreviousSibling () [inline]
Get the previous sibling of this handle.
Definition at line 1652 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::PreviousSibling(), and XMLHandle().
{
        return XMLHandle( _node ? _node->PreviousSibling() : 0 );
    }
XMLHandle tinyxml2::XMLHandle::PreviousSiblingElement (const char * _value = 0) [inline]
Get the previous sibling element of this handle.
Definition at line 1656 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::PreviousSiblingElement(), and XMLHandle().
{
        return XMLHandle( _node ? _node->PreviousSiblingElement( _value ) : 0 );
    }
XMLDeclaration* tinyxml2::XMLHandle::ToDeclaration () [inline]
Safe cast to XMLDeclaration. This can return null.
Definition at line 1685 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToDeclaration().
{
        return ( ( _node && _node->ToDeclaration() ) ? _node->ToDeclaration() : 0 );
    }
XMLElement* tinyxml2::XMLHandle::ToElement () [inline]
Safe cast to XMLElement. This can return null.
Definition at line 1673 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToElement().
{
        return ( ( _node && _node->ToElement() ) ? _node->ToElement() : 0 );
    }
XMLNode* tinyxml2::XMLHandle::ToNode () [inline]
Safe cast to XMLNode. This can return null.
Definition at line 1669 of file tinyxml2.h.
References _node.
{
        return _node;
    }
XMLText* tinyxml2::XMLHandle::ToText () [inline]
Safe cast to XMLText. This can return null.
Definition at line 1677 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToText().
{
        return ( ( _node && _node->ToText() ) ? _node->ToText() : 0 );
    }
XMLUnknown* tinyxml2::XMLHandle::ToUnknown () [inline]
Safe cast to XMLUnknown. This can return null.
Definition at line 1681 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToUnknown().
{
        return ( ( _node && _node->ToUnknown() ) ? _node->ToUnknown() : 0 );
    }
Member Data Documentation
XMLNode* tinyxml2::XMLHandle::_node [private]
Definition at line 1690 of file tinyxml2.h.
Referenced by FirstChild(), FirstChildElement(), LastChild(), LastChildElement(), NextSibling(), NextSiblingElement(), operator=(), PreviousSibling(), PreviousSiblingElement(), ToDeclaration(), ToElement(), ToNode(), ToText(), ToUnknown(), and XMLHandle().
The documentation for this class was generated from the following file:
core/tinyxml/tinyxml2.h