DeepView: tinyxml2::StrPair Class Reference
tinyxml2::StrPair Class Reference
#include <tinyxml2.h>
Public Types
enum {
NEEDS_ENTITY_PROCESSING = 0x01, NEEDS_NEWLINE_NORMALIZATION = 0x02, COLLAPSE_WHITESPACE = 0x04, TEXT_ELEMENT = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
TEXT_ELEMENT_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_NAME = 0, ATTRIBUTE_VALUE = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_VALUE_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION,
COMMENT = NEEDS_NEWLINE_NORMALIZATION
}
Public Member Functions
StrPair ()
~StrPair ()
void Set (char *start, char *end, int flags)
const char * GetStr ()
bool Empty () const
void SetInternedStr (const char *str)
void SetStr (const char *str, int flags=0)
char * ParseText (char *in, const char *endTag, int strFlags)
char * ParseName (char *in)
Private Types
enum { NEEDS_FLUSH = 0x100, NEEDS_DELETE = 0x200 }
Private Member Functions
void Reset ()
void CollapseWhitespace ()
Private Attributes
int _flags
char * _start
char * _end
Detailed Description
Definition at line 124 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
NEEDS_ENTITY_PROCESSING
NEEDS_NEWLINE_NORMALIZATION
COLLAPSE_WHITESPACE
TEXT_ELEMENT
TEXT_ELEMENT_LEAVE_ENTITIES
ATTRIBUTE_NAME
ATTRIBUTE_VALUE
ATTRIBUTE_VALUE_LEAVE_ENTITIES
COMMENT
Definition at line 127 of file tinyxml2.h.
         {
        NEEDS_ENTITY_PROCESSING         = 0x01,
        NEEDS_NEWLINE_NORMALIZATION     = 0x02,
        COLLAPSE_WHITESPACE             = 0x04,
        TEXT_ELEMENT                    = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
        TEXT_ELEMENT_LEAVE_ENTITIES     = NEEDS_NEWLINE_NORMALIZATION,
        ATTRIBUTE_NAME                  = 0,
        ATTRIBUTE_VALUE                 = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
        ATTRIBUTE_VALUE_LEAVE_ENTITIES  = NEEDS_NEWLINE_NORMALIZATION,
        COMMENT                         = NEEDS_NEWLINE_NORMALIZATION
    };
anonymous enum [private]
Enumerator:
NEEDS_FLUSH
NEEDS_DELETE
Definition at line 170 of file tinyxml2.h.
         {
        NEEDS_FLUSH = 0x100,
        NEEDS_DELETE = 0x200
    };
Constructor & Destructor Documentation
tinyxml2::StrPair::StrPair () [inline]
Definition at line 140 of file tinyxml2.h.
: _flags(0), _start(0), _end(0) {}
tinyxml2::StrPair::~StrPair ()
Definition at line 85 of file tinyxml2.cpp.
{
    Reset();
}
Member Function Documentation
void tinyxml2::StrPair::CollapseWhitespace () [private]
Definition at line 158 of file tinyxml2.cpp.
{
    // Trim leading space.
    _start = XMLUtil::SkipWhiteSpace( _start );
    if ( _start && *_start ) {
        char* p = _start;   // the read pointer
        char* q = _start;   // the write pointer
        while( *p ) {
            if ( XMLUtil::IsWhiteSpace( *p )) {
                p = XMLUtil::SkipWhiteSpace( p );
                if ( *p == 0 ) {
                    break;    // don't write to q; this trims the trailing space.
                }
                *q = ' ';
                ++q;
            }
            *q = *p;
            ++q;
            ++p;
        }
        *q = 0;
    }
}
bool tinyxml2::StrPair::Empty () const [inline]
Definition at line 152 of file tinyxml2.h.
References _end, and _start.
Referenced by tinyxml2::XMLNode::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
                       {
        return _start == _end;
    }
const char * tinyxml2::StrPair::GetStr ()
Definition at line 185 of file tinyxml2.cpp.
References tinyxml2::COLLAPSE_WHITESPACE, CR, tinyxml2::entities, tinyxml2::Entity::length, LF, tinyxml2::NUM_ENTITIES, TIXMLASSERT, and tinyxml2::Entity::value.
Referenced by tinyxml2::XMLAttribute::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLNode::Value(), and tinyxml2::XMLAttribute::Value().
{
    if ( _flags & NEEDS_FLUSH ) {
        *_end = 0;
        _flags ^= NEEDS_FLUSH;
        if ( _flags ) {
            char* p = _start;   // the read pointer
            char* q = _start;   // the write pointer
            while( p < _end ) {
                if ( (_flags & NEEDS_NEWLINE_NORMALIZATION) && *p == CR ) {
                    // CR-LF pair becomes LF
                    // CR alone becomes LF
                    // LF-CR becomes LF
                    if ( *(p+1) == LF ) {
                        p += 2;
                    }
                    else {
                        ++p;
                    }
                    *q++ = LF;
                }
                else if ( (_flags & NEEDS_NEWLINE_NORMALIZATION) && *p == LF ) {
                    if ( *(p+1) == CR ) {
                        p += 2;
                    }
                    else {
                        ++p;
                    }
                    *q++ = LF;
                }
                else if ( (_flags & NEEDS_ENTITY_PROCESSING) && *p == '&' ) {
                    // Entities handled by tinyXML2:
                    // - special entities in the entity table [in/out]
                    // - numeric character reference [in]
                    //   &#20013; or &#x4e2d;
                    if ( *(p+1) == '#' ) {
                        char buf[10] = { 0 };
                        int len;
                        p = const_cast<char*>( XMLUtil::GetCharacterRef( p, buf, &len ) );
                        for( int i=0; i<len; ++i ) {
                            *q++ = buf[i];
                        }
                        TIXMLASSERT( q <= p );
                    }
                    else {
                        int i=0;
                        for(; i<NUM_ENTITIES; ++i ) {
                            if (    strncmp( p+1, entities[i].pattern, entities[i].length ) == 0
                                    && *(p+entities[i].length+1) == ';' ) {
                                // Found an entity convert;
                                *q = entities[i].value;
                                ++q;
                                p += entities[i].length + 2;
                                break;
                            }
                        }
                        if ( i == NUM_ENTITIES ) {
                            // fixme: treat as error?
                            ++p;
                            ++q;
                        }
                    }
                }
                else {
                    *q = *p;
                    ++p;
                    ++q;
                }
            }
            *q = 0;
        }
        // The loop below has plenty going on, and this
        // is a less useful mode. Break it out.
        if ( _flags & COLLAPSE_WHITESPACE ) {
            CollapseWhitespace();
        }
        _flags = (_flags & NEEDS_DELETE);
    }
    return _start;
}
char * tinyxml2::StrPair::ParseName (char * in)
Definition at line 133 of file tinyxml2.cpp.
Referenced by tinyxml2::XMLAttribute::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
{
    char* start = p;
    if ( !start || !(*start) ) {
        return 0;
    }
    while( *p && (
                XMLUtil::IsAlphaNum( (unsigned char) *p )
                || *p == '_'
                || *p == ':'
                || (*p == '-' && p>start )      // can be in a name, but not lead it.
                || (*p == '.' && p>start ) )) { // can be in a name, but not lead it.
        ++p;
    }
    if ( p > start ) {
        Set( start, p, 0 );
        return p;
    }
    return 0;
}
char * tinyxml2::StrPair::ParseText (char * in, const char * endTag, int strFlags)
Definition at line 113 of file tinyxml2.cpp.
References TIXMLASSERT.
Referenced by tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), and tinyxml2::XMLAttribute::ParseDeep().
{
    TIXMLASSERT( endTag && *endTag );
    char* start = p;    // fixme: hides a member
    char  endChar = *endTag;
    size_t length = strlen( endTag );
    // Inner loop of text parsing.
    while ( *p ) {
        if ( *p == endChar && strncmp( p, endTag, length ) == 0 ) {
            Set( start, p, strFlags );
            return p + length;
        }
        ++p;
    }
    return 0;
}
void tinyxml2::StrPair::Reset () [private]
Definition at line 91 of file tinyxml2.cpp.
Referenced by Set(), and SetInternedStr().
{
    if ( _flags & NEEDS_DELETE ) {
        delete [] _start;
    }
    _flags = 0;
    _start = 0;
    _end = 0;
}
void tinyxml2::StrPair::Set (char * start, char * end, int flags) [inline]
Definition at line 143 of file tinyxml2.h.
References _end, _flags, _start, NEEDS_FLUSH, and Reset().
{
        Reset();
        _start  = start;
        _end    = end;
        _flags  = flags | NEEDS_FLUSH;
    }
void tinyxml2::StrPair::SetInternedStr (const char * str) [inline]
Definition at line 156 of file tinyxml2.h.
References _start, and Reset().
Referenced by tinyxml2::XMLNode::SetValue().
{
        Reset();
        _start = const_cast<char*>(str);
    }
void tinyxml2::StrPair::SetStr (const char * str, int flags = 0)
Definition at line 102 of file tinyxml2.cpp.
Referenced by tinyxml2::XMLAttribute::SetAttribute(), tinyxml2::XMLAttribute::SetName(), and tinyxml2::XMLNode::SetValue().
{
    Reset();
    size_t len = strlen( str );
    _start = new char[ len+1 ];
    memcpy( _start, str, len+1 );
    _end = _start + len;
    _flags = flags | NEEDS_DELETE;
}
Member Data Documentation
char* tinyxml2::StrPair::_end [private]
Definition at line 178 of file tinyxml2.h.
Referenced by Empty(), and Set().
int tinyxml2::StrPair::_flags [private]
Definition at line 176 of file tinyxml2.h.
Referenced by Set().
char* tinyxml2::StrPair::_start [private]
Definition at line 177 of file tinyxml2.h.
Referenced by Empty(), Set(), and SetInternedStr().
The documentation for this class was generated from the following files:
core/tinyxml/tinyxml2.h
core/tinyxml/tinyxml2.cpp