DeepView: FlowColorer Class Reference
FlowColorer Class Reference
#include <flowColorer.h>
Public Member Functions
FlowColorer (const DrawColoring _style=drawHeatColoring)
virtual QColor getColor (Vector2d16 &point)
virtual uint32_t getPacked (Vector2d16 &point)
bool shouldDrawEllipses (int disp)
QColor ellipsesColor ()
Static Public Member Functions
static int hsvCacheInit ()
static uint32_t packRGB (unsigned r, unsigned g, unsigned b)
Public Attributes
DrawColoring style
Static Public Attributes
static QColor * hsvColorCache
static uint32_t * hsvPackedCache
static int dummy = AbstractFlowColorer::hsvCacheInit()
Detailed Description
Definition at line 5 of file flowColorer.h.
Constructor & Destructor Documentation
FlowColorer::FlowColorer (const DrawColoring _style = drawHeatColoring) [inline]
Definition at line 8 of file flowColorer.h.
                                                              :
        AbstractFlowColorer(_style ) {};
Member Function Documentation
QColor FlowColorer::ellipsesColor () [virtual]
Implements AbstractFlowColorer.
Definition at line 47 of file flowColorer.cpp.
{
    return QColor(0, 0, 255);
}
QColor FlowColorer::getColor (Vector2d16 & point) [virtual]
Implements AbstractFlowColorer.
Definition at line 6 of file flowColorer.cpp.
References drawBlue, drawHeatColoring, drawSimpleColoring, AbstractFlowColorer::hsvColorCache, AbstractFlowColorer::style, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    QColor color;
    if (style == drawBlue) {
        color = QColor(0, 0, 255);
    } else if (style == drawSimpleColoring)
    {
        int hue = (abs((int)point.x()) + abs((int)point.y())) * 300 / 50;
        if (hue > 255) hue = 255;
        color = hsvColorCache[hue];
    } else if (style == drawHeatColoring)
    {
        int hue = (abs((int)point.x()) + abs((int)point.y())) * 300 / 30;
        if (hue > 255) hue = 255;
        color = QColor(hue, 0, 255 - hue);
    }
    return color;
}
uint32_t FlowColorer::getPacked (Vector2d16 & point) [virtual]
Implements AbstractFlowColorer.
Definition at line 25 of file flowColorer.cpp.
References drawHeatColoring, drawSimpleColoring, AbstractFlowColorer::hsvPackedCache, AbstractFlowColorer::packRGB(), AbstractFlowColorer::style, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    if (style == drawSimpleColoring)
    {
        int hue = (abs((int)point.x()) + abs((int)point.y())) * 300 / 50;
        if (hue > 255) hue = 255;
        return hsvPackedCache[hue];
    } else if (style == drawHeatColoring)
    {
        int hue = (abs((int)point.x()) + abs((int)point.y())) * 300 / 30;
        if (hue > 255) hue = 255;
        return (hue << 16) | (255 - hue);
    }
    return packRGB(0,0,0xFF);
}
int AbstractFlowColorer::hsvCacheInit () [static, inherited]
Definition at line 17 of file abstractFlowColorer.cpp.
References AbstractFlowColorer::hsvColorCache, AbstractFlowColorer::hsvPackedCache, and AbstractFlowColorer::packRGB().
{
    hsvColorCache  = new QColor[256];
    hsvPackedCache = new uint32_t[256];
    for (unsigned i = 0; i < 256; i++)
    {
        QColor color;
        color.setHsv(i, 255, 255, 255);
        uint32_t r = color.red();
        uint32_t g = color.green();
        uint32_t b = color.blue();
        hsvColorCache [i] = color;
        hsvPackedCache[i] = packRGB(r,g,b);
    }
    return 0;
}
static uint32_t AbstractFlowColorer::packRGB (unsigned r, unsigned g, unsigned b) [inline, static, inherited]
Definition at line 29 of file abstractFlowColorer.h.
Referenced by getPacked(), StereoColorer::getPacked(), and AbstractFlowColorer::hsvCacheInit().
    {
        return (0xFF << 24) | (r << 16) | (g << 8) | (b);
    }
bool FlowColorer::shouldDrawEllipses (int disp) [virtual]
Implements AbstractFlowColorer.
Definition at line 41 of file flowColorer.cpp.
{
    Q_UNUSED(disp)
    return false;
}
Member Data Documentation
int AbstractFlowColorer::dummy = AbstractFlowColorer::hsvCacheInit() [static, inherited]
Definition at line 21 of file abstractFlowColorer.h.
QColor * AbstractFlowColorer::hsvColorCache [static, inherited]
Definition at line 19 of file abstractFlowColorer.h.
Referenced by getColor(), StereoColorer::getColor(), and AbstractFlowColorer::hsvCacheInit().
uint32_t * AbstractFlowColorer::hsvPackedCache [static, inherited]
Definition at line 20 of file abstractFlowColorer.h.
Referenced by getPacked(), StereoColorer::getPacked(), and AbstractFlowColorer::hsvCacheInit().
DrawColoring AbstractFlowColorer::style [inherited]
Definition at line 24 of file abstractFlowColorer.h.
Referenced by getColor(), and getPacked().
The documentation for this class was generated from the following files:
utils/flowcolorers/flowColorer.h
utils/flowcolorers/flowColorer.cpp