DeepView: ViGLAreaWidget Class Reference
ViGLAreaWidget Class Reference
#include <viGLAreaWidget.h>
Signals
void askParentInitialize ()
void askParentRepaint ()
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (int width, int height)
void notifyParentKeyPressEvent (QKeyEvent *event)
void notifyParentKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
ViGLAreaWidget (QWidget *parent=0)
~ViGLAreaWidget ()
Private Member Functions
virtual void initializeGL ()
virtual void resizeGL (int width, int height)
virtual void paintGL ()
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
Private Attributes
Ui_ViGLAreaWidgetClass ui
Detailed Description
Definition at line 12 of file viGLAreaWidget.h.
Constructor & Destructor Documentation
ViGLAreaWidget::ViGLAreaWidget (QWidget * parent = 0)
Definition at line 8 of file viGLAreaWidget.cpp.
References ui.
                                              :
    QGLWidget(parent)
{
    ui.setupUi(this);
}
ViGLAreaWidget::~ViGLAreaWidget ()
Definition at line 64 of file viGLAreaWidget.cpp.
{
}
Member Function Documentation
void ViGLAreaWidget::askParentInitialize () [signal]
Referenced by initializeGL().
void ViGLAreaWidget::askParentRepaint () [signal]
Referenced by paintGL().
void ViGLAreaWidget::initializeGL () [private, virtual]
Definition at line 14 of file viGLAreaWidget.cpp.
References askParentInitialize().
{
    emit askParentInitialize();
}
void ViGLAreaWidget::keyPressEvent (QKeyEvent * event) [private, virtual]
Definition at line 51 of file viGLAreaWidget.cpp.
References notifyParentKeyPressEvent().
{
//    cout << "ViGLAreaWidget::keyPressEvent" << endl;
    emit notifyParentKeyPressEvent(event);
}
void ViGLAreaWidget::keyReleaseEvent (QKeyEvent * event) [private, virtual]
Definition at line 57 of file viGLAreaWidget.cpp.
References notifyParentKeyReleaseEvent().
{
//    cout << "ViGLAreaWidget::keyReleaseEvent" << endl;
    emit notifyParentKeyReleaseEvent(event);
}
void ViGLAreaWidget::mouseMoveEvent (QMouseEvent * event) [private, virtual]
Definition at line 25 of file viGLAreaWidget.cpp.
References notifyParentMouseMove().
{
    emit notifyParentMouseMove(event);
}
void ViGLAreaWidget::mousePressEvent (QMouseEvent * event) [private, virtual]
Definition at line 30 of file viGLAreaWidget.cpp.
References notifyParentMousePress().
{
    emit notifyParentMousePress(event);
}
void ViGLAreaWidget::mouseReleaseEvent (QMouseEvent * event) [private, virtual]
Definition at line 35 of file viGLAreaWidget.cpp.
References notifyParentMouseRelease().
{
    emit notifyParentMouseRelease(event);
}
void ViGLAreaWidget::notifyParentKeyPressEvent (QKeyEvent * event) [signal]
Referenced by keyPressEvent().
void ViGLAreaWidget::notifyParentKeyReleaseEvent (QKeyEvent * event) [signal]
Referenced by keyReleaseEvent().
void ViGLAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal]
Referenced by mouseMoveEvent().
void ViGLAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal]
Referenced by mousePressEvent().
void ViGLAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal]
Referenced by mouseReleaseEvent().
void ViGLAreaWidget::notifyParentResize (int width, int height) [signal]
Referenced by resizeGL().
void ViGLAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal]
Referenced by wheelEvent().
void ViGLAreaWidget::paintGL () [private, virtual]
Definition at line 40 of file viGLAreaWidget.cpp.
References askParentRepaint().
{
    emit askParentRepaint();
}
void ViGLAreaWidget::resizeGL (int width, int height) [private, virtual]
Definition at line 19 of file viGLAreaWidget.cpp.
References notifyParentResize().
{
    emit notifyParentResize(width, height);
}
void ViGLAreaWidget::wheelEvent (QWheelEvent * event) [private, virtual]
Definition at line 45 of file viGLAreaWidget.cpp.
References notifyParentWheelEvent().
{
//    cout << "ViGLAreaWidget::wheelEvent" << endl;
    emit notifyParentWheelEvent(event);
}
Member Data Documentation
Ui_ViGLAreaWidgetClass ViGLAreaWidget::ui [private]
Definition at line 34 of file viGLAreaWidget.h.
Referenced by ViGLAreaWidget().
The documentation for this class was generated from the following files:
utils/viGLAreaWidget.h
utils/viGLAreaWidget.cpp