DeepView: Arrow Class Reference
Arrow Class Reference
[0]
#include <arrow.h>
Public Types
enum { Type = UserType + 4 }
Public Member Functions
Arrow (DiagramItem *startItem, DiagramItem *endItem, QGraphicsItem *parent=0, QGraphicsScene *scene=0)
[0]
int type () const
QRectF boundingRect () const
[0]
QPainterPath shape () const
[1]
void setColor (const QColor &color)
DiagramItem * startItem () const
DiagramItem * endItem () const
void updatePosition ()
[2]
Protected Member Functions
void paint (QPainter *painter, const QStyleOptionGraphicsItem *, QWidget *widget=0)
[3]
Private Attributes
DiagramItem * myStartItem
DiagramItem * myEndItem
QColor myColor
QPolygonF arrowHead
Detailed Description
[0]
Definition at line 58 of file arrow.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 61 of file arrow.h.
{ Type = UserType + 4 };
Constructor & Destructor Documentation
Arrow::Arrow (DiagramItem * startItem, DiagramItem * endItem, QGraphicsItem * parent = 0, QGraphicsScene * scene = 0)
[0]
Definition at line 51 of file arrow.cpp.
References endItem(), myColor, myEndItem, myStartItem, and startItem().
    : QGraphicsLineItem(parent, scene)
{
//    cout<<"Arrow::Arrow"<<endl;
    myStartItem = startItem;
    myEndItem   = endItem;
    setFlag(QGraphicsItem::ItemIsSelectable, true);
    myColor = Qt::black;
    setPen(QPen(myColor, 2, Qt::SolidLine, Qt::RoundCap, Qt::RoundJoin));
}
Member Function Documentation
QRectF Arrow::boundingRect () const
[0]
[1]
Definition at line 67 of file arrow.cpp.
{
//    cout<<"Arrow::boundingRect()"<<endl;
    qreal extra = (pen().width() + 20) / 2.0;
    return QRectF(line().p1(), QSizeF(line().p2().x() - line().p1().x(),
                                      line().p2().y() - line().p1().y()))
        .normalized()
        .adjusted(-extra, -extra, extra, extra);
}
DiagramItem* Arrow::endItem () const [inline]
Definition at line 74 of file arrow.h.
References myEndItem.
Referenced by Arrow(), FilterGraphPresentation::deleteItem(), and DiagramItem::removeArrows().
        { return myEndItem; }
void Arrow::paint (QPainter * painter, const QStyleOptionGraphicsItem * , QWidget * widget = 0) [protected]
[3]
[4]
Definition at line 100 of file arrow.cpp.
References arrowHead, myColor, myEndItem, myStartItem, Pi, and DiagramItem::polygon().
{
    QColor currentColor;
    if (isSelected())
        currentColor = Qt::red;
    else
        currentColor = myColor;
    if (myStartItem->collidesWithItem(myEndItem))
    {
        cout<<"myStartItem->collidesWithItem(myEndItem)"<<endl;
//        cout<<"paint line return "<<line().x1()<<" "<<line().y1()<<" "<<line().x2()<<" "<<line().y2()<<endl;
        return;
    }
    QPen myPen = pen();
    myPen.setColor(currentColor);
    qreal arrowSize = 20;
    painter->setPen(myPen);
    painter->setBrush(currentColor);
    QPointF startPos = mapFromItem(myStartItem, 0, 0);
    QPointF endPos   = mapFromItem(myEndItem,   0, 0);
    QLineF centerLine(startPos, endPos);
//    cout<<"startPos = "<<startPos.x()<<" "<<startPos.y()<< endl;
//    cout<<"endPos   = "<<endPos.x()  <<" "<<endPos.y()  << endl;
    QPolygonF endPolygon = myEndItem->polygon();
    endPolygon = mapFromItem(myEndItem, myEndItem->polygon());
    QPointF p1 = endPolygon.first();
//    cout<<"p1 = "<<p1.x()<<" "<<p1.y()<<endl;
    QPointF p2;
    QPointF intersectPoint;
    for (int i = 1; i < endPolygon.count(); ++i) {
        p2 = endPolygon.at(i);
//        cout<<"p2 = "<<p2.x()<<" "<<p2.y()<<endl;
        QLineF polyLine = QLineF(p1, p2);
        QLineF::IntersectType intersectType =
        polyLine.intersect(centerLine, &intersectPoint);
        if (intersectType == QLineF::BoundedIntersection)
            break;
        p1 = p2;
    }
    setLine(QLineF(intersectPoint, startPos));
//    cout<<"paint line setLine "<<line().x1()<<" "<<line().y1()<<" "<<line().x2()<<" "<<line().y2()<<endl;
    double angle = ::acos(line().dx() / line().length());
    if (line().dy() >= 0)
        angle = (Pi * 2) - angle;
    QPointF arrowP1 = line().p1() + QPointF(sin(angle + Pi / 3) * arrowSize,
                                    cos(angle + Pi / 3) * arrowSize);
    QPointF arrowP2 = line().p1() + QPointF(sin(angle + Pi - Pi / 3) * arrowSize,
                                    cos(angle + Pi - Pi / 3) * arrowSize);
    arrowHead.clear();
    arrowHead << line().p1() << arrowP1 << arrowP2;
    painter->drawLine(line());
    painter->drawPolygon(arrowHead);
    if (isSelected()) {
        painter->setPen(QPen(currentColor, 1, Qt::DashLine));
        QLineF myLine = line();
        myLine.translate(0, 4.0);
        painter->drawLine(myLine);
        myLine.translate(0,-8.0);
        painter->drawLine(myLine);
    }
}
void Arrow::setColor (const QColor & color) [inline]
Definition at line 70 of file arrow.h.
References myColor.
Referenced by DiagramScene::addArrow().
        { myColor = color; }
QPainterPath Arrow::shape () const
[1]
[2]
Definition at line 80 of file arrow.cpp.
References arrowHead.
{
//    cout<<"Arrow::shape()"<<endl;
    QPainterPath path = QGraphicsLineItem::shape();
    path.addPolygon(arrowHead);
    return path;
}
DiagramItem* Arrow::startItem () const [inline]
Definition at line 72 of file arrow.h.
References myStartItem.
Referenced by Arrow(), FilterGraphPresentation::deleteItem(), and DiagramItem::removeArrows().
        { return myStartItem; }
int Arrow::type () const [inline]
Definition at line 66 of file arrow.h.
References Type.
        { return Type; }
void Arrow::updatePosition ()
[2]
[3]
Definition at line 90 of file arrow.cpp.
Referenced by DiagramItem::itemChange().
{
//    cout<<"Arrow::updatePosition()"<<endl;
//    QLineF line(mapFromItem(myStartItem, 0, 0), mapFromItem(myEndItem, 0, 0));
//    setLine(line);?????
//    cout<<"line "<<line.x1()<<" "<<line.y1()<<" "<<line.x2()<<" "<<line.y2()<<endl;
}
Member Data Documentation
QPolygonF Arrow::arrowHead [private]
Definition at line 87 of file arrow.h.
Referenced by paint(), and shape().
QColor Arrow::myColor [private]
Definition at line 86 of file arrow.h.
Referenced by Arrow(), paint(), and setColor().
DiagramItem* Arrow::myEndItem [private]
Definition at line 85 of file arrow.h.
Referenced by Arrow(), endItem(), and paint().
DiagramItem* Arrow::myStartItem [private]
Definition at line 84 of file arrow.h.
Referenced by Arrow(), paint(), and startItem().
The documentation for this class was generated from the following files:
utils/filters/graph/arrow.h
utils/filters/graph/arrow.cpp