DeepView: DirectShowCaptureDecoupleInterface Class Reference
DirectShowCaptureDecoupleInterface Class Reference
#include <directShowCaptureDecouple.h>
Public Types
typedef
ImageCaptureInterface::CapErrorCode CapErrorCode
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
void memberCallback (DSCapDeviceId dev, FrameData data)
DirectShowCaptureDecoupleInterface (string _devname)
virtual ~DirectShowCaptureDecoupleInterface ()
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual CapErrorCode queryCameraParameters (CameraParameters &parameters)
Check if a specific property can be set/read and what values it can take.
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&format)
virtual FramePair getFrameRGB24 ()
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static void callback (void *thiz, DSCapDeviceId dev, FrameData data)
static int devicesNumber ()
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Public Attributes
int compressed
DecoupleYUYV::ImageCouplingType coupling
QMutex protectFrame
string devname
Stores the device name.
DirectShowCameraDescriptor cameras [2]
int width
int height
PreciseTimer lastFrameTime
int skippedCount
int isRunning
unsigned int delay
Static Public Attributes
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Private Member Functions
void setFromCameraParam (CaptureParameter &param, CameraParameter &camParam)
Detailed Description
Definition at line 6 of file directShowCaptureDecouple.h.
Member Typedef Documentation
typedef ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::CapErrorCode
Reimplemented from ImageCaptureInterface.
Definition at line 9 of file directShowCaptureDecouple.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
Constructor & Destructor Documentation
DirectShowCaptureDecoupleInterface::DirectShowCaptureDecoupleInterface (string _devname)
Definition at line 15 of file directShowCaptureDecouple.cpp.
References OutputStyle::ANAGLYPH_RC, callback(), cameras, DirectShowCameraDescriptor::codec_names, compressed, DirectShowCameraDescriptor::COMPRESSED_FAST_JPEG, DirectShowCameraDescriptor::COMPRESSED_JPEG, coupling, DirectShowCameraDescriptor::deviceHandle, devname, height, isRunning, OutputStyle::SIDEBYSIDE_STEREO, skippedCount, DirectShowCameraDescriptor::UNCOMPRESSED_RGB, DirectShowCameraDescriptor::UNCOMPRESSED_YUV, and width.
{
    this->devname = _devname;
    //     Group Number                   1       2 3      4       56        7       8         9 10     11     1213    14
    QRegExp deviceStringPattern(QString("^([^,:]*)(:(\\d*)/(\\d*))?((:mjpeg)|(:yuyv)|(:fjpeg))?(:(\\d*)x(\\d*))?((:rc)|(:rc2)|(:sbs)|(:rcf))?$"));
    static const int DeviceGroup      = 1;
    static const int FpsNumGroup      = 3;
    static const int FpsDenumGroup    = 4;
    static const int CompressionGroup = 5;
    static const int WidthGroup       = 10;
    static const int HeightGroup      = 11;
    static const int CouplingGroup    = 12;
    printf ("Input string %s\n", _devname.c_str());
    QString qdevname(_devname.c_str());
    int result = deviceStringPattern.indexIn(qdevname);
    if (result == -1)
    {
        printf("Error in device string format:%s\n", _devname.c_str());
        return;
    }
    printf (
                "Parsed data:\n"
                "Device =%s\n"
                "FPS %s/%s\n"
                "Size [%sx%s]\n"
                "Compressing: %s\n"
                "Coupling: <%s>\n",
                deviceStringPattern.cap(DeviceGroup).toAscii().constData(),
                deviceStringPattern.cap(FpsNumGroup).toAscii().constData(),
                deviceStringPattern.cap(FpsDenumGroup).toAscii().constData(),
                deviceStringPattern.cap(WidthGroup).toAscii().constData(),
                deviceStringPattern.cap(HeightGroup).toAscii().constData(),
                deviceStringPattern.cap(CompressionGroup).toAscii().constData(),
                deviceStringPattern.cap(CouplingGroup).toAscii().constData()
    );
    int cameraName =  deviceStringPattern.cap(DeviceGroup).toInt();
    bool err;
    int fpsnum = deviceStringPattern.cap(FpsNumGroup).toInt(&err);
    if (!err) fpsnum = 1;
    int fpsdenum = deviceStringPattern.cap(FpsDenumGroup).toInt(&err);
    if (!err) fpsdenum = 10;
    width = deviceStringPattern.cap(WidthGroup).toInt(&err);
    if (!err || width <= 0) width = 800;
    height = deviceStringPattern.cap(HeightGroup).toInt(&err);
    if (!err || height <= 0) height = 600;
    compressed = DirectShowCameraDescriptor::UNCOMPRESSED_YUV;
    int formatId = CAP_YUV;
    if (!deviceStringPattern.cap(CompressionGroup).isEmpty())
    {
       if        (!deviceStringPattern.cap(CompressionGroup).compare(QString(":rgb"))) {
           compressed = DirectShowCameraDescriptor::UNCOMPRESSED_RGB;
           formatId = CAP_RGB;
       } else if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":mjpeg"))) {
           compressed = DirectShowCameraDescriptor::COMPRESSED_JPEG;
           formatId = CAP_MJPEG;
       } else if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":fjpeg"))) {
           compressed = DirectShowCameraDescriptor::COMPRESSED_FAST_JPEG;
           formatId = CAP_MJPEG;
       }
    }
    coupling = DecoupleYUYV::ANAGLYPH_RC;
    if (!deviceStringPattern.cap(CouplingGroup).compare(QString(":sbs"))) {
        coupling = DecoupleYUYV::SIDEBYSIDE_STEREO;
    }
    if (!deviceStringPattern.cap(CouplingGroup).compare(QString(":rc2"))) {
        coupling = DecoupleYUYV::ANAGLYPH_RC_X2;
    }
    if (!deviceStringPattern.cap(CouplingGroup).compare(QString(":rcf"))) {
        coupling = DecoupleYUYV::ANAGLYPH_RC_FAST;
    }
    printf("Capture Right device: DShow %d\n", cameraName );
    printf("Format is: %s\n", DirectShowCameraDescriptor::codec_names[compressed]);
    printf("Coupling is: %d\n", coupling);
    /* TODO: Make cycle here */
    cameras[0].deviceHandle = DirectShowCapDll_initCapture(cameraName);
    CaptureTypeFormat format1 = {formatId, height, width, (int)((double)fpsdenum / fpsnum) }; // FixMe: probably round should be here?
    DirectShowCapDll_setFormat(cameras[0].deviceHandle, &format1);
    printf("Real Formats:\n");
    DirectShowCapDll_printSimpleFormat(&format1); printf("\n");
    height = format1.height;
    width  = format1.width;
    DirectShowCapDll_setFrameCallback(cameras[0].deviceHandle, this, DirectShowCaptureDecoupleInterface::callback);
    skippedCount = 0;
    isRunning = false;
}
DirectShowCaptureDecoupleInterface::~DirectShowCaptureDecoupleInterface () [virtual]
Definition at line 203 of file directShowCaptureDecouple.cpp.
References cameras, and isRunning.
{
    if (isRunning)
    {
        /*
            Callback is set safe and synchronously,
            so after the call of the callback reset, we will never again
            receive a frame. So it will be safe to destroy the object
        */
        DirectShowCapDll_setFrameCallback(cameras[0].deviceHandle, NULL, NULL);
        DirectShowCapDll_stop(cameras[0].deviceHandle);
    }
    isRunning = false;
}
Member Function Documentation
void DirectShowCaptureDecoupleInterface::callback (void * thiz, DSCapDeviceId dev, FrameData data) [static]
Definition at line 120 of file directShowCaptureDecouple.cpp.
References memberCallback().
Referenced by DirectShowCaptureDecoupleInterface().
{
//    printf("Received new frame in a callback\n");
    DirectShowCaptureDecoupleInterface *pInterface = (DirectShowCaptureDecoupleInterface *)thiz;
    pInterface->memberCallback(dev, data);
}
int DirectShowCaptureDecoupleInterface::devicesNumber () [static]
Definition at line 238 of file directShowCaptureDecouple.cpp.
{
    int num = 0;
    DirectShowCapDll_devicesNumber(&num);
    return num;
}
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::getCaptureName (QString & value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 245 of file directShowCaptureDecouple.cpp.
References cameras, and ImageCaptureInterface::SUCCESS.
{
    char *name = NULL;
    DirectShowCapDll_deviceName(cameras[0].deviceHandle, &name);
    string str;
    int k = 0;
    while (name[k] != '\0')
    {
        str += name[k];
        k += 2;
    }
    value = strdup(str.c_str());
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::getCaptureProperty (int id, int * value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 232 of file directShowCaptureDecouple.cpp.
References cameras, DirectShowCameraDescriptor::getCaptureProperty(), and ImageCaptureInterface::SUCCESS.
{
    cameras[0].getCaptureProperty(id, value);
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getDeviceName (int num, QString & name) [virtual, inherited]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented in DirectShowCaptureInterface, and V4L2CaptureInterface.
Definition at line 186 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::getFormats (int * num, CameraFormat *& format) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 260 of file directShowCaptureDecouple.cpp.
References cameras, ImageCaptureInterface::CameraFormat::fps, ImageCaptureInterface::CameraFormat::height, ImageCaptureInterface::SUCCESS, and ImageCaptureInterface::CameraFormat::width.
{
    DirectShowCapDll_getFormatNumber(cameras[0].deviceHandle, num);
    int number = *num;
    CaptureTypeFormat* captureTypeFormats = new CaptureTypeFormat[number];
    delete format;
    format = new CameraFormat[number];
    DirectShowCapDll_getFormats(cameras[0].deviceHandle, number, captureTypeFormats);
    for (int i = 0; i < number; i ++)
    {
        format[i].fps    = captureTypeFormats[i].fps;
        format[i].width  = captureTypeFormats[i].width;
        format[i].height = captureTypeFormats[i].height;
    }
    delete[] captureTypeFormats;
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::FramePair DirectShowCaptureDecoupleInterface::getFrame () [virtual]
Main function to request frames from image interface.
Implements ImageCaptureInterface.
Definition at line 174 of file directShowCaptureDecouple.cpp.
References cameras, coupling, height, ImageCaptureInterface::FramePair::leftTimeStamp, protectFrame, DirectShowCameraDescriptor::rawBuffer, ImageCaptureInterface::FramePair::rightTimeStamp, DirectShowCameraDescriptor::timestamp, and width.
{
    protectFrame.lock();
    FramePair result(NULL, NULL);
    uint8_t *ptr = cameras[0].rawBuffer;
    DecoupleYUYV::decouple(height, width, ptr, coupling, result);
    result.leftTimeStamp = cameras[0].timestamp;
    result.rightTimeStamp = cameras[0].timestamp;
    protectFrame.unlock();
    return result;
}
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual, inherited]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
QString ImageCaptureInterface::getInterfaceName () [virtual, inherited]
Return the interface device string.
Reimplemented in V4L2CaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 181 of file imageCaptureInterface.cpp.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
{
    return "";
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::initCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 188 of file directShowCaptureDecouple.cpp.
References ImageCaptureInterface::SUCCESS.
{
    return ImageCaptureInterface::SUCCESS;
}
ALIGN_STACK_SSE void DirectShowCaptureDecoupleInterface::memberCallback (DSCapDeviceId dev, FrameData data)
Definition at line 127 of file directShowCaptureDecouple.cpp.
References cameras, CORE_UNUSED, DirectShowCameraDescriptor::decodeTime, CaptureStatistics::DECODING_TIME, CaptureStatistics::DESYNC_TIME, DirectShowCameraDescriptor::gotBuffer, CaptureStatistics::INTERFRAME_DELAY, lastFrameTime, ImageCaptureInterface::newFrameReady(), ImageCaptureInterface::newStatisticsReady(), protectFrame, DirectShowCameraDescriptor::rawBuffer, corecvs::roundDivUp(), frame_data_t::timestamp, DirectShowCameraDescriptor::timestamp, corecvs::PreciseTimer::usecsTo(), corecvs::PreciseTimer::usecsToNow(), and CaptureStatistics::values.
Referenced by callback().
{
    CORE_UNUSED(dev);
//    SYNC_PRINT(("Received new frame in a member %d\n", dev));
    protectFrame.lock();
    DirectShowCameraDescriptor *camera = &cameras[0];
    PreciseTimer timer = PreciseTimer::currentTime();
    camera->gotBuffer = true;
    camera->timestamp = roundDivUp(data.timestamp, 10);
    delete camera->rawBuffer;
    camera->rawBuffer = new uint8_t[data.format.height * data.format.width * 2];
    if (data.format.type == CAP_YUV)
    {
        memcpy(camera->rawBuffer, data.data, data.format.height * data.format.width * 2);
//        SYNC_PRINT(("Got new frame %dx%d\n", data.format.height, data.format.width));
    } else {
        memset(camera->rawBuffer, 0, data.format.height * data.format.width * 2);
    }
    camera->decodeTime = timer.usecsToNow();
    /* If both frames are in place */
    cameras[0].gotBuffer = false;
    CaptureStatistics stats;
    stats.values[CaptureStatistics::DESYNC_TIME] = 0;
    stats.values[CaptureStatistics::DECODING_TIME] = cameras[0].decodeTime;
    if (lastFrameTime.usecsTo(PreciseTimer()) != 0)
    {
        stats.values[CaptureStatistics::INTERFRAME_DELAY] = lastFrameTime.usecsToNow();
    }
    lastFrameTime = PreciseTimer::currentTime();
    frame_data_t frameData;
    frameData.timestamp = cameras[0].timestamp;
    newFrameReady(frameData);
    newStatisticsReady(stats);
    protectFrame.unlock();
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by memberCallback(), DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::queryCameraParameters (CameraParameters & parameter) [virtual]
Check if a specific property can be set/read and what values it can take.
Reimplemented from ImageCaptureInterface.
Definition at line 220 of file directShowCaptureDecouple.cpp.
References cameras, DirectShowCameraDescriptor::queryCameraParameters(), and ImageCaptureInterface::SUCCESS.
{
    cameras[0].queryCameraParameters(parameters);
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::setCaptureProperty (int id, int value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 226 of file directShowCaptureDecouple.cpp.
References cameras, DirectShowCameraDescriptor::setCaptureProperty(), and ImageCaptureInterface::SUCCESS.
Referenced by startCapture().
{
    cameras[0].setCaptureProperty(id, value);
    return ImageCaptureInterface::SUCCESS;
}
void DirectShowCaptureDecoupleInterface::setFromCameraParam (CaptureParameter & param, CameraParameter & camParam) [private]
ImageCaptureInterface::CapErrorCode DirectShowCaptureDecoupleInterface::startCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 193 of file directShowCaptureDecouple.cpp.
References cameras, isRunning, CameraParameters::SATURATION, setCaptureProperty(), and ImageCaptureInterface::SUCCESS.
{
    isRunning = true;
    DirectShowCapDll_start(cameras[0].deviceHandle);
    setCaptureProperty(CameraParameters::SATURATION, 0);
    //spin.start();
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
Member Data Documentation
DirectShowCameraDescriptor DirectShowCaptureDecoupleInterface::cameras[2]
Definition at line 17 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface(), getCaptureName(), getCaptureProperty(), getFormats(), getFrame(), memberCallback(), queryCameraParameters(), setCaptureProperty(), startCapture(), and ~DirectShowCaptureDecoupleInterface().
int DirectShowCaptureDecoupleInterface::compressed
Definition at line 11 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface().
DecoupleYUYV::ImageCouplingType DirectShowCaptureDecoupleInterface::coupling
Definition at line 12 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface(), and getFrame().
unsigned int DirectShowCaptureDecoupleInterface::delay
Definition at line 28 of file directShowCaptureDecouple.h.
string DirectShowCaptureDecoupleInterface::devname
Stores the device name.
Definition at line 16 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface().
int DirectShowCaptureDecoupleInterface::height
Definition at line 20 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface(), and getFrame().
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
int DirectShowCaptureDecoupleInterface::isRunning
Definition at line 25 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface(), startCapture(), and ~DirectShowCaptureDecoupleInterface().
PreciseTimer DirectShowCaptureDecoupleInterface::lastFrameTime
Definition at line 23 of file directShowCaptureDecouple.h.
Referenced by memberCallback().
QMutex DirectShowCaptureDecoupleInterface::protectFrame
Definition at line 15 of file directShowCaptureDecouple.h.
Referenced by getFrame(), and memberCallback().
int DirectShowCaptureDecoupleInterface::skippedCount
Definition at line 24 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface().
int DirectShowCaptureDecoupleInterface::width
Definition at line 19 of file directShowCaptureDecouple.h.
Referenced by DirectShowCaptureDecoupleInterface(), and getFrame().
The documentation for this class was generated from the following files:
utils/framesources/directShow/directShowCaptureDecouple.h
utils/framesources/directShow/directShowCaptureDecouple.cpp