DeepView: corecvs::CloudCluster Class Reference
corecvs::CloudCluster Class Reference
#include <cloudCluster.h>
Public Member Functions
void getMean ()
void getStat ()
CloudCluster * getFather ()
Getter for father.
bool isTop ()
Checks if it is a child segment or not.
CloudCluster * getTopFather ()
This method returns a topmost segment in a father tree.
void markMerge (CloudCluster *other)
This method merges two trees of child segments.
void dadify ()
Public Attributes
EllipticalApproximationUnified
< Vector3dd > mEllipse
SwarmPoint mClusterInfo
int m6Dpoints
Vector3dd mMean
SwarmPoint elements
STL member.
CloudCluster * father
The father segment in a merge tree during the merge phase TODO: Make this private.
Detailed Description
Definition at line 15 of file cloudCluster.h.
Member Function Documentation
void corecvs::BaseSegment< CloudCluster >::dadify () [inline, inherited]
Definition at line 81 of file segmentator.h.
    {
        if (!isTop())
            father = getTopFather();
    }
CloudCluster * corecvs::BaseSegment< CloudCluster >::getFather () [inline, inherited]
Getter for father.
Definition at line 52 of file segmentator.h.
    {
        return father;
    };
void corecvs::CloudCluster::getMean ()
Definition at line 5 of file cloudCluster.cpp.
References mMean.
Referenced by getStat().
{
    Vector3dd sum = Vector3dd(0, 0, 0);
    for (CloudCluster::iterator it = this->begin(); it != this->end(); ++it)
    {
        sum = sum + (*it).point;
    }
    mMean = sum / this->size();
}
void corecvs::CloudCluster::getStat ()
Definition at line 15 of file cloudCluster.cpp.
References corecvs::EllipticalApproximationUnified< ElementType >::addPoint(), corecvs::EllipticalApproximationUnified< ElementType >::getEllipseParameters(), getMean(), m6Dpoints, mClusterInfo, mEllipse, mMean, corecvs::SwarmPoint::point, corecvs::SwarmPoint::speed, and corecvs::SwarmPoint::texCoor.
{
    m6Dpoints = 0;
    mClusterInfo.point   = Vector3dd(0);
    mClusterInfo.texCoor = Vector2dd(0);
    mClusterInfo.speed   = Vector3dd(0);
    getMean();
    for (CloudCluster::iterator it = this->begin(); it != this->end(); ++it)
    {
        mClusterInfo.point   += (*it).point;   /* find 3D center of cluster */
        mClusterInfo.texCoor += (*it).texCoor; /* find 2D center of cluster */
        if ((*it).is6D)
        {
            mClusterInfo.speed += (*it).speed; /* find mean flow of cluster */
            m6Dpoints++;
        }
        mEllipse.addPoint((*it).point - mMean);        /* find ellipse approximation */
    }
    mClusterInfo.point   /= (double)this->size();
    mClusterInfo.texCoor /= (double)this->size();
    if (m6Dpoints != 0)
        mClusterInfo.speed /= m6Dpoints;
    mEllipse.getEllipseParameters();
}
CloudCluster * corecvs::BaseSegment< CloudCluster >::getTopFather () [inline, inherited]
This method returns a topmost segment in a father tree.
Definition at line 64 of file segmentator.h.
    {
        ThisType *toReturn = (ThisType *)this;
        while (toReturn->getFather() != NULL)
            toReturn = toReturn->getFather();
        return toReturn;
    }
bool corecvs::BaseSegment< CloudCluster >::isTop () [inline, inherited]
Checks if it is a child segment or not.
Definition at line 58 of file segmentator.h.
    {
        return (father == NULL);
    }
void corecvs::BaseSegment< CloudCluster >::markMerge (CloudCluster * other) [inline, inherited]
This method merges two trees of child segments.
Definition at line 73 of file segmentator.h.
    {
        ThisType *thisTopFather  = this->getTopFather();
        ThisType *otherTopFather = other->getTopFather();
        if (otherTopFather != thisTopFather)
            otherTopFather->father = thisTopFather;
    }
Member Data Documentation
SwarmPoint std::vector< SwarmPoint >::elements [inherited]
STL member.
CloudCluster * corecvs::BaseSegment< CloudCluster >::father [inherited]
The father segment in a merge tree during the merge phase TODO: Make this private.
Definition at line 43 of file segmentator.h.
int corecvs::CloudCluster::m6Dpoints
Definition at line 27 of file cloudCluster.h.
Referenced by getStat().
SwarmPoint corecvs::CloudCluster::mClusterInfo
Definition at line 26 of file cloudCluster.h.
Referenced by getStat().
EllipticalApproximationUnified<Vector3dd> corecvs::CloudCluster::mEllipse
Definition at line 25 of file cloudCluster.h.
Referenced by getStat().
Vector3dd corecvs::CloudCluster::mMean
Definition at line 28 of file cloudCluster.h.
Referenced by getMean(), and getStat().
The documentation for this class was generated from the following files:
core/clustering3d/cloudCluster.h
core/clustering3d/cloudCluster.cpp