DeepView: corecvs::Mesh3D Class Reference
corecvs::Mesh3D Class Reference
#include <mesh3d.h>
Public Member Functions
void addAOB (Vector3dd corner1, Vector3dd corner2)
void addAOB (const AxisAlignedBoxParameters &box)
void addAOB (const AxisAlignedBox3d &box)
void addSphere (Vector3dd center, double radius, int step)
Public Attributes
vector< Vector3dd > vertexes
vector< Vector3d32 > faces
vector< Vector2dd > textureCoords
Detailed Description
Definition at line 110 of file mesh3d.h.
Member Function Documentation
void corecvs::Mesh3D::addAOB (Vector3dd corner1, Vector3dd corner2)
Definition at line 11 of file mesh3d.cpp.
References faces, textureCoords, vertexes, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by addAOB(), and CloudViewDialog::CloudViewDialog().
{
    int vectorIndex = (int)vertexes.size();
    Vector3d32 startId(vectorIndex, vectorIndex, vectorIndex);
    vertexes.push_back(Vector3dd(c1.x(), c1.y(), c1.z()));
    vertexes.push_back(Vector3dd(c2.x(), c1.y(), c1.z()));
    vertexes.push_back(Vector3dd(c2.x(), c2.y(), c1.z()));
    vertexes.push_back(Vector3dd(c1.x(), c2.y(), c1.z()));
    vertexes.push_back(Vector3dd(c1.x(), c1.y(), c2.z()));
    vertexes.push_back(Vector3dd(c2.x(), c1.y(), c2.z()));
    vertexes.push_back(Vector3dd(c2.x(), c2.y(), c2.z()));
    vertexes.push_back(Vector3dd(c1.x(), c2.y(), c2.z()));
    faces.push_back(startId + Vector3d32(0, 1, 2));
    faces.push_back(startId + Vector3d32(0, 1, 2));
    faces.push_back(startId + Vector3d32(2, 3, 0));
    faces.push_back(startId + Vector3d32(7, 6, 5));
    faces.push_back(startId + Vector3d32(5, 4, 7));
    faces.push_back(startId + Vector3d32(0, 4, 5));
    faces.push_back(startId + Vector3d32(5, 1, 0));
    faces.push_back(startId + Vector3d32(1, 5, 6));
    faces.push_back(startId + Vector3d32(6, 2, 1));
    faces.push_back(startId + Vector3d32(2, 6, 7));
    faces.push_back(startId + Vector3d32(7, 3, 2));
    faces.push_back(startId + Vector3d32(3, 7, 4));
    faces.push_back(startId + Vector3d32(4, 0, 3));
    textureCoords.push_back(Vector2dd(0.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,1.0));
    textureCoords.push_back(Vector2dd(0.0,1.0));
    textureCoords.push_back(Vector2dd(0.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,1.0));
    textureCoords.push_back(Vector2dd(0.0,1.0));
}
void corecvs::Mesh3D::addAOB (const AxisAlignedBoxParameters & box)
Definition at line 51 of file mesh3d.cpp.
References addAOB(), AxisAlignedBoxParameters::depth(), AxisAlignedBoxParameters::height(), AxisAlignedBoxParameters::width(), AxisAlignedBoxParameters::x(), AxisAlignedBoxParameters::y(), and AxisAlignedBoxParameters::z().
{
    Vector3dd measure(box.width(), box.height(), box.depth());
    Vector3dd center (box.x()    , box.y()     , box.z    ());
    addAOB(center - measure / 2.0, center + measure / 2.0);
}
void corecvs::Mesh3D::addAOB (const AxisAlignedBox3d & box)
Definition at line 60 of file mesh3d.cpp.
References addAOB(), corecvs::AxisAlignedBox3d::high(), and corecvs::AxisAlignedBox3d::low().
{
    addAOB(box.low(), box.high());
}
void corecvs::Mesh3D::addSphere (Vector3dd center, double radius, int step)
Definition at line 65 of file mesh3d.cpp.
References M_PI, and vertexes.
{
    int vectorIndex = (int)vertexes.size();
    Vector3d32 startId(vectorIndex, vectorIndex, vectorIndex);
    double dphy =     M_PI / (step + 1);
    double dpsi = 2 * M_PI / (step + 1);
    for (int i = 0; i < step; i++)
    {
        for (int j = 0; j < step; j++)
        {
            double phi = dphy * i;
            double psi = dpsi * j;
            double x = radius * sin(phi) * sin(psi);
            double y = radius * sin(phi) * cos(psi);
            double z = radius * cos(phi);
            vertexes.push_back(center + Vector3dd(x,y,z));
        }
    }
}
Member Data Documentation
vector<Vector3d32> corecvs::Mesh3D::faces
Definition at line 113 of file mesh3d.h.
Referenced by addAOB(), Mesh3DScene::drawMyself(), and PLYLoader::loadPLY().
vector<Vector2dd> corecvs::Mesh3D::textureCoords
Definition at line 114 of file mesh3d.h.
Referenced by addAOB(), and Mesh3DScene::drawMyself().
vector<Vector3dd> corecvs::Mesh3D::vertexes
Definition at line 112 of file mesh3d.h.
Referenced by addAOB(), addSphere(), Mesh3DScene::drawMyself(), and PLYLoader::loadPLY().
The documentation for this class was generated from the following files:
core/geometry/mesh3d.h
core/geometry/mesh3d.cpp