DeepView: ImageCaptureInterface Class Reference
ImageCaptureInterface Class Reference
#include <imageCaptureInterface.h>
Classes
struct CameraFormat
struct fps_t
This structure will hold the rational number for the FPS.
struct frame_dims_t
class FramePair
This will hold the pair of frames.
Public Types
enum CapErrorCode { SUCCESS = 0, SUCCESS_1CAM = 1, FAILURE = 2 }
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
ImageCaptureInterface ()
virtual ~ImageCaptureInterface ()
virtual FramePair getFrame ()=0
Main function to request frames from image interface.
virtual FramePair getFrameRGB24 ()
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&)
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode queryCameraParameters (CameraParameters &parameter)
Check if a specific property can be set/read and what values it can take.
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Static Public Attributes
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Detailed Description
Definition at line 67 of file imageCaptureInterface.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapErrorCode
Enumerator:
SUCCESS
SUCCESS_1CAM
FAILURE
Reimplemented in DirectShowCaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 72 of file imageCaptureInterface.h.
    {
        SUCCESS       = 0,
        SUCCESS_1CAM  = 1,
        FAILURE      = 2
    };
enum ImageCaptureInterface::CapPropertyAccessType
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
Constructor & Destructor Documentation
ImageCaptureInterface::ImageCaptureInterface ()
Definition at line 151 of file imageCaptureInterface.cpp.
{
   qRegisterMetaType<frame_data_t>("frame_data_t");
}
ImageCaptureInterface::~ImageCaptureInterface () [virtual]
Definition at line 156 of file imageCaptureInterface.cpp.
{
    return;
}
Member Function Documentation
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureName (QString & value) [virtual]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 171 of file imageCaptureInterface.cpp.
References FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureProperty (int id, int * value) [virtual]
Reimplemented in DirectShowCaptureInterface, DirectShowCaptureDecoupleInterface, V4L2CaptureInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 166 of file imageCaptureInterface.cpp.
References FAILURE.
Referenced by CapSettingsDialog::refreshDialog().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getDeviceName (int num, QString & name) [virtual]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented in DirectShowCaptureInterface, and V4L2CaptureInterface.
Definition at line 186 of file imageCaptureInterface.cpp.
References FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getFormats (int * num, CameraFormat *&) [virtual]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 176 of file imageCaptureInterface.cpp.
References FAILURE.
{
    return FAILURE;
}
virtual FramePair ImageCaptureInterface::getFrame () [pure virtual]
Main function to request frames from image interface.
Implemented in OpenCVCaptureInterface, DirectShowCaptureInterface, FilePreciseCapture, DirectShowCaptureDecoupleInterface, V4L2CaptureInterface, UEyeCaptureInterface, V4L2CaptureDecoupleInterface, FileCaptureInterface, OpenCvFileCapture, and AbstractFileCapture.
Referenced by Frames::fetchNewFrames().
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
QString ImageCaptureInterface::getInterfaceName () [virtual]
Return the interface device string.
Reimplemented in V4L2CaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 181 of file imageCaptureInterface.cpp.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
{
    return "";
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::initCapture () [virtual]
Reimplemented in OpenCVCaptureInterface, DirectShowCaptureInterface, V4L2CaptureInterface, UEyeCaptureInterface, V4L2CaptureDecoupleInterface, DirectShowCaptureDecoupleInterface, FileCaptureInterface, and AbstractFileCapture.
Definition at line 191 of file imageCaptureInterface.cpp.
References FAILURE.
Referenced by BaseHostDialog::initCapture().
{
    return FAILURE;
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), and notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal]
Referenced by DirectShowCaptureInterface::memberCallback(), and notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References newFrameReady(), and newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::queryCameraParameters (CameraParameters & parameter) [virtual]
Check if a specific property can be set/read and what values it can take.
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, DirectShowCaptureDecoupleInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 211 of file imageCaptureInterface.cpp.
References SUCCESS.
Referenced by CapSettingsDialog::refreshDialog().
{
    Q_UNUSED(parameter)
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::setCaptureProperty (int id, int value) [virtual]
Reimplemented in OpenCVCaptureInterface, DirectShowCaptureInterface, DirectShowCaptureDecoupleInterface, V4L2CaptureInterface, UEyeCaptureInterface, V4L2CaptureDecoupleInterface, and AbstractFileCapture.
Definition at line 161 of file imageCaptureInterface.cpp.
References FAILURE.
Referenced by CapSettingsDialog::parameterChanged(), and CapSettingsDialog::resetPressed().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::startCapture () [virtual]
Reimplemented in OpenCVCaptureInterface, DirectShowCaptureInterface, V4L2CaptureInterface, UEyeCaptureInterface, V4L2CaptureDecoupleInterface, DirectShowCaptureDecoupleInterface, FileCaptureInterface, AbstractFileCapture, and OpenCvFileCapture.
Definition at line 196 of file imageCaptureInterface.cpp.
References FAILURE.
Referenced by BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::streamPaused () [signal]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
Member Data Documentation
bool ImageCaptureInterface::isRgb = false [static]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by fabric(), and Frames::fetchNewFrames().
The documentation for this class was generated from the following files:
utils/framesources/imageCaptureInterface.h
utils/framesources/imageCaptureInterface.cpp