DeepView: OutputFilterParameters Class Reference
OutputFilterParameters Class Reference
Output Filter Parameters Output Filter Parameters.
#include <outputFilterParameters.h>
Public Types
enum FieldId { OUTPUT_TYPE_ID, OUTPUT_FILTER_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
OutputType::OutputType outputType () const
void setOutputType (OutputType::OutputType outputType)
template<class VisitorType >
void accept (VisitorType &visitor)
OutputFilterParameters ()
OutputFilterParameters (OutputType::OutputType outputType)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mOutputType
Section with variables.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, OutputFilterParameters &toSave)
Detailed Description
Output Filter Parameters Output Filter Parameters.
Definition at line 39 of file outputFilterParameters.h.
Member Enumeration Documentation
enum OutputFilterParameters::FieldId
Enumerator:
OUTPUT_TYPE_ID
OUTPUT_FILTER_PARAMETERS_FIELD_ID_NUM
Definition at line 42 of file outputFilterParameters.h.
                 {
        OUTPUT_TYPE_ID,
        OUTPUT_FILTER_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
OutputFilterParameters::OutputFilterParameters () [inline]
Definition at line 82 of file outputFilterParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
OutputFilterParameters::OutputFilterParameters (OutputType::OutputType outputType) [inline]
Definition at line 88 of file outputFilterParameters.h.
    {
        mOutputType = outputType;
    }
Member Function Documentation
template<class VisitorType > void OutputFilterParameters::accept (VisitorType & visitor) [inline]
Definition at line 77 of file outputFilterParameters.h.
Referenced by corecvs::OutputFilter::deserialize(), and corecvs::OutputFilter::serialize().
    {
        visitor.visit((int &)mOutputType,         static_cast<const EnumField *>    (fields()[OUTPUT_TYPE_ID]));
    }
static const char* corecvs::BaseReflection< OutputFilterParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< OutputFilterParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< OutputFilterParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* OutputFilterParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 59 of file outputFilterParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< OutputFilterParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< OutputFilterParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< OutputFilterParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
OutputType::OutputType OutputFilterParameters::outputType () const [inline]
Definition at line 63 of file outputFilterParameters.h.
Referenced by BaseCalculationThread::executeFilterGraph(), and OutputFilterParametersControlWidget::setParameters().
    {
        return static_cast<OutputType::OutputType>(mOutputType);
    }
void OutputFilterParameters::print () [inline]
Definition at line 102 of file outputFilterParameters.h.
    {
        cout << *this;
    }
void OutputFilterParameters::setOutputType (OutputType::OutputType outputType) [inline]
Definition at line 69 of file outputFilterParameters.h.
    {
        mOutputType = outputType;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int OutputFilterParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file outputFilterParameters.cpp.
References corecvs::BaseReflection< OutputFilterParameters >::fields(), mOutputType, corecvs::BaseReflection< OutputFilterParameters >::naming(), and OUTPUT_TYPE_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Output Filter Parameters",
        "Output Filter Parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          OutputFilterParameters::OUTPUT_TYPE_ID,
          offsetof(OutputFilterParameters, mOutputType),
          0,
          "Output Type",
          "Output Type",
          "Output Type",
           NULL
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, OutputFilterParameters & toSave) [friend]
Definition at line 95 of file outputFilterParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< OutputFilterParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int OutputFilterParameters::mOutputType
Section with variables.
Output Type Output Type
Definition at line 53 of file outputFilterParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< OutputFilterParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/outputFilterParameters.h
core/xml/generated/outputFilterParameters.cpp