DeepView: TxtPinPresentation Class Reference
TxtPinPresentation Class Reference
#include <txtPinPresentation.h>
Public Types
enum { Type = UserType + 15 }
Public Member Functions
TxtPinPresentation (Pin *pin, DiagramScene *scene, DiagramItem *parent=0)
virtual ~TxtPinPresentation ()
virtual void draw (DiagramScene *scene, DiagramItem *blockItem, int x, int y)
void drawInputPinName ()
void drawOutputPinName ()
void drawPinName ()
void finishInit ()
void removeArrow (Arrow *arrow)
void removeArrows ()
QPolygonF polygon () const
void addArrow (Arrow *arrow)
int type () const
virtual void foo ()
Static Public Member Functions
static FilterPinPresentation * getPinByType (Pin *pin, DiagramScene *scene, DiagramItem *parent=0)
Public Attributes
Pin * mPin
char * pinName
DiagramScene * scene
Protected Member Functions
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Protected Attributes
QPolygonF myPolygon
Private Attributes
DiagramTextItem * textItem
Detailed Description
Definition at line 6 of file txtPinPresentation.h.
Member Enumeration Documentation
anonymous enum [inherited]
Enumerator:
Type
Definition at line 55 of file diagramitem.h.
{ Type = UserType + 15 };
Constructor & Destructor Documentation
TxtPinPresentation::TxtPinPresentation (Pin * pin, DiagramScene * scene, DiagramItem * parent = 0) [inline]
Definition at line 11 of file txtPinPresentation.h.
References DiagramScene::font(), DiagramScene::textColor(), and textItem.
                                                                              :
        FilterPinPresentation(pin, scene, parent)
    {
        textItem = new DiagramTextItem(this, scene);
        textItem->setFont(scene->font());
        textItem->setZValue(1000.0);
        textItem->setPlainText("T");
        textItem->setDefaultTextColor(scene->textColor());
        double hRect = textItem->boundingRect().right() - textItem->boundingRect().left();
        double wRect = textItem->boundingRect().top()   - textItem->boundingRect().bottom();
        textItem->setPos(-hRect/2, wRect/2);
    }
virtual TxtPinPresentation::~TxtPinPresentation () [inline, virtual]
Definition at line 25 of file txtPinPresentation.h.
References textItem.
    {
        delete_safe(textItem);
    }
Member Function Documentation
void DiagramItem::addArrow (Arrow * arrow) [inherited]
Definition at line 73 of file diagramitem.cpp.
References DiagramItem::arrows.
Referenced by DiagramScene::addArrow().
{
    arrows.append(arrow);
}
void FilterPinPresentation::draw (DiagramScene * scene, DiagramItem * blockItem, int x, int y) [virtual, inherited]
Definition at line 51 of file filterPinPresentation.cpp.
References DiagramScene::itemColor().
{
    if (scene == NULL || blockItem == NULL)  return;
//    cout<<"FilterPinPresentation::draw"<<endl;
    setBrush(scene->itemColor());
    setPos(x, y);
}
void FilterPinPresentation::drawInputPinName () [inherited]
Definition at line 60 of file filterPinPresentation.cpp.
References FilterPinPresentation::pinNameItem.
Referenced by FilterPinPresentation::drawPinName().
{
    double hRect = pinNameItem->boundingRect().right() - pinNameItem->boundingRect().left();
    double wRect = pinNameItem->boundingRect().top()   - pinNameItem->boundingRect().bottom();
    pinNameItem->setPos(-hRect/2, wRect/2+20);
}
void FilterPinPresentation::drawOutputPinName () [inherited]
Definition at line 67 of file filterPinPresentation.cpp.
References FilterPinPresentation::pinNameItem.
Referenced by FilterPinPresentation::drawPinName().
{
    double hRect = pinNameItem->boundingRect().right() - pinNameItem->boundingRect().left();
    double wRect = pinNameItem->boundingRect().top()   - pinNameItem->boundingRect().bottom();
    pinNameItem->setPos(-hRect/2, wRect/2-20);
}
void FilterPinPresentation::drawPinName () [inherited]
Definition at line 85 of file filterPinPresentation.cpp.
References FilterPinPresentation::drawInputPinName(), FilterPinPresentation::drawOutputPinName(), DiagramScene::font(), FilterPinPresentation::mPin, FilterPinPresentation::pinName, FilterPinPresentation::pinNameItem, FilterPinPresentation::scene, DiagramScene::textColor(), and corecvs::Pin::type.
Referenced by FilterPinPresentation::FilterPinPresentation(), and FilterGraphPresentation::nameChanged().
{
    pinNameItem->setFont(scene->font());
    pinNameItem->setZValue(1000.0);
    pinNameItem->setPlainText(pinName);
    pinNameItem->setDefaultTextColor(scene->textColor());
    if (mPin->type == Pin::INPUT_PIN)
        drawInputPinName();
    if (mPin->type == Pin::OUTPUT_PIN)
        drawOutputPinName();
}
void DiagramItem::finishInit () [inherited]
Definition at line 47 of file diagramitem.cpp.
References DiagramItem::myPolygon.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), and FilterPinPresentation::FilterPinPresentation().
{
    setPolygon(myPolygon);
    setFlag(QGraphicsItem::ItemSendsGeometryChanges, true);
}
virtual void DiagramItem::foo () [inline, virtual, inherited]
Definition at line 70 of file diagramitem.h.
{}
FilterPinPresentation * FilterPinPresentation::getPinByType (Pin * pin, DiagramScene * scene, DiagramItem * parent = 0) [static, inherited]
Definition at line 74 of file filterPinPresentation.cpp.
References FilterPinPresentation::FilterPinPresentation().
Referenced by CompoundBlockPresentation::addPin(), and FilterBlockPresentation::createPinPresentations().
{
    if (dynamic_cast<G12Pin*>(pin))
         return new G12PinPresentation(pin, scene, parent);
    else if (dynamic_cast<TxtPin*>(pin))
         return new TxtPinPresentation(pin, scene, parent);
    else return new FilterPinPresentation(pin, scene, parent);
}
QVariant DiagramItem::itemChange (GraphicsItemChange change, const QVariant & value) [protected, inherited]
Definition at line 78 of file diagramitem.cpp.
References DiagramItem::arrows, and Arrow::updatePosition().
{
    if (change == QGraphicsItem::ItemPositionChange)
        foreach (Arrow *arrow, arrows)
            arrow->updatePosition();
    return value;
}
void FilterPinPresentation::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) [protected, inherited]
Definition at line 98 of file filterPinPresentation.cpp.
{
//    cout << "FilterPinPresentation::paint ";
    DiagramItem::paint(painter, option, widget);
//    if ((mPin->type == Pin::INPUT_PIN) && (mPin->takeFrom == NULL))
//        painter->fillRect(option->rect, Qt::red);
}
QPolygonF DiagramItem::polygon () const [inline, inherited]
Definition at line 66 of file diagramitem.h.
Referenced by FilterBlockPresentation::drawInputPins(), FilterBlockPresentation::drawOutputPins(), and Arrow::paint().
        { return myPolygon; }
void DiagramItem::removeArrow (Arrow * arrow) [inherited]
Definition at line 53 of file diagramitem.cpp.
References DiagramItem::arrows.
Referenced by FilterGraphPresentation::deleteItem(), and DiagramItem::removeArrows().
{
    int index = arrows.indexOf(arrow);
    if (index != -1)  arrows.removeAt(index);
}
void DiagramItem::removeArrows () [inherited]
Definition at line 59 of file diagramitem.cpp.
References DiagramItem::arrows, Arrow::endItem(), DiagramItem::removeArrow(), and Arrow::startItem().
Referenced by FilterGraphPresentation::deleteItem(), and DiagramItem::~DiagramItem().
{
    foreach (Arrow *arrow, arrows)
    {   arrow->startItem()->removeArrow(arrow);
        arrow->endItem()->removeArrow(arrow);
        delete_safe(arrow);
    }
}
int DiagramItem::type () const [inline, inherited]
Definition at line 69 of file diagramitem.h.
{ return Type;}
Member Data Documentation
Pin* FilterPinPresentation::mPin [inherited]
Definition at line 10 of file filterPinPresentation.h.
Referenced by FilterGraphPresentation::deleteItem(), DiagramScene::diagramItemByPin(), FilterPinPresentation::drawPinName(), FilterPinPresentation::FilterPinPresentation(), DiagramScene::mouseReleaseEvent(), and FilterGraphPresentation::nameChanged().
QPolygonF DiagramItem::myPolygon [protected, inherited]
Definition at line 76 of file diagramitem.h.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), FilterPinPresentation::FilterPinPresentation(), and DiagramItem::finishInit().
char* FilterPinPresentation::pinName [inherited]
Definition at line 11 of file filterPinPresentation.h.
Referenced by FilterPinPresentation::drawPinName(), FilterPinPresentation::FilterPinPresentation(), FilterGraphPresentation::nameChanged(), and FilterGraphPresentation::pinItemSelected().
DiagramScene* FilterPinPresentation::scene [inherited]
Definition at line 12 of file filterPinPresentation.h.
Referenced by FilterPinPresentation::drawPinName(), and FilterPinPresentation::FilterPinPresentation().
DiagramTextItem* TxtPinPresentation::textItem [private]
Definition at line 32 of file txtPinPresentation.h.
Referenced by TxtPinPresentation(), and ~TxtPinPresentation().
The documentation for this class was generated from the following file:
utils/filters/graph/txtPinPresentation.h