DeepView: corecvs::RadialCorrection Class Reference
corecvs::RadialCorrection Class Reference
#include <radialCorrection.h>
Public Types
typedef Vector2d< int32_t > InputPoint
typedef Vector2d< double > OutputPoint
Public Member Functions
RadialCorrection (const LensCorrectionParametres &params=LensCorrectionParametres())
virtual ~RadialCorrection ()
Vector2dd map (Vector2dd const &v) const
double radialScale (double r) const
Vector2dd map (int y, int x) const
Vector2dd map (double y, double x) const
Apply the lens distortion correction.
virtual void operator() (const double in[], double out[])
Operator that computes funсtion.
G12Buffer * doCorrectionTransform (G12Buffer *inputBuffer)
OutputPoint map (const int32_t &, const int32_t &)
virtual void operator() (const Vector &in, Vector &out)
virtual Matrix getJacobian (const double in[], double delta=1e-7)
This function computes Jacobian
.
virtual Matrix getJacobian (const Vector &in, double delta=1e-7)
Public Attributes
LensCorrectionParametres mParams
int inputs
int outputs
Detailed Description
Definition at line 104 of file radialCorrection.h.
Member Typedef Documentation
typedef Vector2d<int32_t > corecvs::DeformMap< int32_t , double >::InputPoint [inherited]
Definition at line 81 of file abstractBuffer.h.
typedef Vector2d<double > corecvs::DeformMap< int32_t , double >::OutputPoint [inherited]
Definition at line 82 of file abstractBuffer.h.
Constructor & Destructor Documentation
corecvs::RadialCorrection::RadialCorrection (const LensCorrectionParametres & params = LensCorrectionParametres()) [explicit]
Definition at line 16 of file radialCorrection.cpp.
                                                                         :
        FunctionArgs(2,2),
        mParams(params)
{
}
corecvs::RadialCorrection::~RadialCorrection () [virtual]
Definition at line 22 of file radialCorrection.cpp.
{
}
Member Function Documentation
G12Buffer * corecvs::RadialCorrection::doCorrectionTransform (G12Buffer * inputBuffer)
Definition at line 55 of file radialCorrection.cpp.
References corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformationBl(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    return inputBuffer->doReverseDeformationBl<G12Buffer, RadialCorrection>
                         (this, inputBuffer->h, inputBuffer->w);
}
virtual Matrix corecvs::FunctionArgs::getJacobian (const double in[], double delta = 1e-7) [inline, virtual, inherited]
This function computes Jacobian
.
TODO: Bring differencing out and use following information http://en.wikipedia.org/wiki/Numerical_differentiation#Practical_considerations_using_floating_point_arithmetic
Reimplemented in corecvs::IdentityFunction, corecvs::EssentialEstimator::CostFunction7to1, corecvs::RadialFunc, corecvs::DistPointsFunction, corecvs::AnglePointsFunction, corecvs::AngleFunction, corecvs::StraightFunc, corecvs::CurvatureFunc, and corecvs::CamerasCalibrationFunc.
Definition at line 68 of file function.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::FunctionArgs::inputs, corecvs::FunctionArgs::operator()(), and corecvs::FunctionArgs::outputs.
Referenced by corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::FunctionArgs::getJacobian(), corecvs::GradientDescent::minimise(), corecvs::ClassicKalman::predict(), and corecvs::ClassicKalman::update().
    {
        Matrix result(outputs, inputs);
        vector<double> xc(inputs);
        vector<double> y_minus(outputs);
        vector<double> y_plus (outputs);
        for (int i = 0; i < inputs; i++)
        {
            xc[i] = in[i];
        }
        for (int i = 0; i < inputs; i++)
        {
            xc[i] = in[i] - delta;
            operator()(&xc[0], &y_minus[0]);
            xc[i] = in[i] + delta;
            operator()(&xc[0], &y_plus[0]);
            xc[i] = in[i];
            for (int j = 0; j < outputs; j++)
            {
                result.element(j,i) = (y_plus[j] - y_minus[j]) / (2.0 * delta);
            }
        }
        return result;
    }
virtual Matrix corecvs::FunctionArgs::getJacobian (const Vector & in, double delta = 1e-7) [inline, virtual, inherited]
Definition at line 96 of file function.h.
References corecvs::FixedArrayBase< RealType, ElementType >::element, and corecvs::FunctionArgs::getJacobian().
    {
        return getJacobian(in.element, delta);
    }
OutputPoint corecvs::DeformMap< int32_t , double >::map (const int32_t & , const int32_t &) [inline, inherited]
Definition at line 85 of file abstractBuffer.h.
{}
Vector2dd corecvs::RadialCorrection::map (Vector2dd const & v) const [inline]
Definition at line 110 of file radialCorrection.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::DisplacementBuffer::CacheInverse(), corecvs::DisplacementBuffer::DisplacementBuffer(), map(), corecvs::AnglePointsFunction::operator()(), corecvs::DistPointsFunction::operator()(), operator()(), and DistortionWidget::showBufferChanged().
    {
        return map(v.y(), v.x());
    }
Vector2dd corecvs::RadialCorrection::map (int y, int x) const [inline]
Definition at line 128 of file radialCorrection.h.
References map().
    {
        return map((double)y, (double)x);
    }
Vector2dd corecvs::RadialCorrection::map (double y, double x) const [inline]
Apply the lens distortion correction.
For details see LensCorrectionParametres
Parameters:
y y position of the point to be mapped
x x position of the point to be mapped
Returns:
A corrected buffer
Definition at line 143 of file radialCorrection.h.
References corecvs::LensCorrectionParametres::aspect, corecvs::LensCorrectionParametres::center, corecvs::LensCorrectionParametres::focal, mParams, corecvs::LensCorrectionParametres::p1, corecvs::LensCorrectionParametres::p2, radialScale(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        double dpx = (x - mParams.center.x()) * mParams.aspect;
        double dpy = (y - mParams.center.y());
        double dx = dpx / mParams.focal;
        double dy = dpy / mParams.focal;
        double dxsq = dx * dx;
        double dysq = dy * dy;
        double dxdy = dx * dy;
        double rsq = dxsq + dysq;
        double r = sqrt(rsq);
        double radialCorrection = radialScale(r);
//        SYNC_PRINT(("RadialCorrection::map (): [%lf %lf ] %lf %lf\n", x, y, rsq, radialCorrection));
        double radialX = (double)dx * radialCorrection;
        double radialY = (double)dy * radialCorrection;
        double tangentX = 2 * mParams.p1 * dxdy + mParams.p2 * ( rsq + 2 * dxsq );
        double tangentY = mParams.p1 * (rsq + 2 * dysq) + 2 * mParams.p2 * dxdy;
        return Vector2dd(
                x + ((radialX + tangentX) / mParams.aspect * mParams.focal),
                y + ((radialY + tangentY)                  * mParams.focal));
    }
virtual void corecvs::FunctionArgs::operator() (const Vector & in, Vector & out) [inline, virtual, inherited]
Definition at line 46 of file function.h.
References corecvs::FixedArrayBase< RealType, ElementType >::element, and corecvs::FunctionArgs::operator()().
    {
        return operator()(in.element, out.element);
    }
virtual void corecvs::RadialCorrection::operator() (const double in[], double out[]) [inline, virtual]
Operator that computes funсtion.
Implements corecvs::FunctionArgs.
Definition at line 174 of file radialCorrection.h.
References map(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        Vector2dd result = map(in[1], in[0]);
        out[1] = result.y();
        out[0] = result.x();
    }
double corecvs::RadialCorrection::radialScale (double r) const [inline]
Definition at line 115 of file radialCorrection.h.
References corecvs::LensCorrectionParametres::koeff, and mParams.
Referenced by map(), and DistortionWidget::updateAdditionalData().
    {
        double rpow = r;
        double radialCorrection = 0;
        for (unsigned i = 0; i < mParams.koeff.size(); i ++)
        {
            radialCorrection += mParams.koeff[i] * rpow;
            rpow *= r;
        }
        return radialCorrection;
    }
Member Data Documentation
int corecvs::FunctionArgs::inputs [inherited]
Definition at line 32 of file function.h.
Referenced by corecvs::ClassicKalman::ClassicKalman(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawIsolines(), corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::CamerasCalibrationFunc::getJacobian(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::FunctionArgs::getJacobian(), corecvs::IdentityFunction::getJacobian(), corecvs::LengthFunction::LengthFunction(), corecvs::GradientDescent::minimise(), corecvs::IdentityFunction::operator()(), and corecvs::ScalerFunction::ScalerFunction().
LensCorrectionParametres corecvs::RadialCorrection::mParams
Definition at line 186 of file radialCorrection.h.
Referenced by DistortionWidget::doManualTransform(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::ModelToRadialCorrection::getModel(), corecvs::ModelToRadialCorrection::getRadial(), map(), radialScale(), and DistortionWidget::updateAdditionalData().
int corecvs::FunctionArgs::outputs [inherited]
Definition at line 33 of file function.h.
Referenced by corecvs::ClassicKalman::ClassicKalman(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawIsolines(), corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::CamerasCalibrationFunc::getJacobian(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::FunctionArgs::getJacobian(), corecvs::IdentityFunction::getJacobian(), corecvs::LengthFunction::LengthFunction(), corecvs::GradientDescent::minimise(), corecvs::ScalerFunction::operator()(), corecvs::LengthFunction::operator()(), and corecvs::ScalerFunction::ScalerFunction().
The documentation for this class was generated from the following files:
core/alignment/radialCorrection.h
core/alignment/radialCorrection.cpp