DeepView: GainOffsetParametersControlWidget Class Reference
GainOffsetParametersControlWidget Class Reference
#include <gainOffsetParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
GainOffsetParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
virtual ~GainOffsetParametersControlWidget ()
GainOffsetParameters * createParameters () const
virtual BaseReflectionStatic * createParametersVirtual () const
void setParameters (const GainOffsetParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_GainOffsetParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file gainOffsetParametersControlWidget.h.
Constructor & Destructor Documentation
GainOffsetParametersControlWidget::GainOffsetParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file gainOffsetParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::GainOffsetParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->gainSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->offsetSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
}
GainOffsetParametersControlWidget::~GainOffsetParametersControlWidget () [virtual]
Definition at line 27 of file gainOffsetParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void GainOffsetParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file gainOffsetParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
GainOffsetParameters * GainOffsetParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 49 of file gainOffsetParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    GainOffsetParameters *result = new GainOffsetParameters(
          mUi->gainSpinBox->value()
        , mUi->offsetSpinBox->value()
    );
    return result;
}
virtual BaseReflectionStatic* GainOffsetParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 20 of file gainOffsetParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void GainOffsetParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 33 of file gainOffsetParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    GainOffsetParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void GainOffsetParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by GainOffsetParametersControlWidget(), and setParameters().
void GainOffsetParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 41 of file gainOffsetParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    GainOffsetParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void GainOffsetParametersControlWidget::setParameters (const GainOffsetParameters & input)
Definition at line 64 of file gainOffsetParametersControlWidget.cpp.
References GainOffsetParameters::gain(), mUi, GainOffsetParameters::offset(), and paramsChanged().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->gainSpinBox->setValue(input.gain());
    mUi->offsetSpinBox->setValue(input.offset());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void GainOffsetParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 74 of file gainOffsetParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    GainOffsetParameters *inputCasted = static_cast<GainOffsetParameters *>(input);
    setParameters(*inputCasted);
}
void GainOffsetParametersControlWidget::valueChanged () [signal]
Referenced by GainOffsetParametersControlWidget().
Member Data Documentation
bool GainOffsetParametersControlWidget::autoInit [private]
Definition at line 45 of file gainOffsetParametersControlWidget.h.
Ui_GainOffsetParametersControlWidget* GainOffsetParametersControlWidget::mUi [private]
Definition at line 44 of file gainOffsetParametersControlWidget.h.
Referenced by createParameters(), GainOffsetParametersControlWidget(), setParameters(), and ~GainOffsetParametersControlWidget().
QString GainOffsetParametersControlWidget::rootPath [private]
Definition at line 46 of file gainOffsetParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/gainOffsetParametersControlWidget.h
utils/filters/ui/gainOffsetParametersControlWidget.cpp