DeepView: corecvs::EssentialEstimator::CostFunctionBase Class Reference
corecvs::EssentialEstimator::CostFunctionBase Class Reference
This is a class that describe the translation form state in form of the array of doubles into an Essential matrix.
#include <essentialEstimator.h>
Public Types
enum InputVector2Model {
ROTATION_Q_X = 0, ROTATION_Q_Y, ROTATION_Q_Z, ROTATION_Q_T,
TRANSLATION_X, TRANSLATION_Y, TRANSLATION_Z, VECTOR_SIZE
}
Public Member Functions
CostFunctionBase (int outputs)
virtual void operator() (const double in[], double out[])=0
Operator that computes funсtion.
virtual void operator() (const Vector &in, Vector &out)
virtual Matrix getJacobian (const double in[], double delta=1e-7)
This function computes Jacobian
.
virtual Matrix getJacobian (const Vector &in, double delta=1e-7)
Static Public Member Functions
static Quaternion getRotationQ (const double in[])
static Matrix33 getRotationM (const double in[])
static Vector3dd getTranslation (const double in[])
static EssentialMatrix getEssential (const double in[])
static double getRotationAngle (const double in[])
static Vector3dd getRotationAxis (const double in[])
static void packState (double out[], const Quaternion &q, const Vector3dd &t)
Public Attributes
int inputs
int outputs
Detailed Description
This is a class that describe the translation form state in form of the array of doubles into an Essential matrix.
Definition at line 39 of file essentialEstimator.h.
Member Enumeration Documentation
enum corecvs::EssentialEstimator::CostFunctionBase::InputVector2Model
Enumerator:
ROTATION_Q_X
ROTATION_Q_Y
ROTATION_Q_Z
ROTATION_Q_T
TRANSLATION_X
TRANSLATION_Y
TRANSLATION_Z
VECTOR_SIZE
Definition at line 42 of file essentialEstimator.h.
{
            ROTATION_Q_X = 0,
            ROTATION_Q_Y,
            ROTATION_Q_Z,
            ROTATION_Q_T,
            TRANSLATION_X,
            TRANSLATION_Y,
            TRANSLATION_Z,
            VECTOR_SIZE
        };
Constructor & Destructor Documentation
corecvs::EssentialEstimator::CostFunctionBase::CostFunctionBase (int outputs) [inline]
Definition at line 55 of file essentialEstimator.h.
                                      :
            FunctionArgs(VECTOR_SIZE, outputs)
        {}
Member Function Documentation
EssentialMatrix corecvs::EssentialEstimator::CostFunctionBase::getEssential (const double in[]) [static]
Definition at line 430 of file essentialEstimator.cpp.
References corecvs::EssentialMatrix::compose().
Referenced by corecvs::EssentialEstimator::getEssentialGrad(), corecvs::EssentialEstimator::getEssentialGradToRm(), corecvs::EssentialEstimator::getEssentialLM(), and corecvs::EssentialEstimator::getEssentialSimpleKalman().
{
    return EssentialMatrix::compose(getRotationM(in), getTranslation(in));
}
virtual Matrix corecvs::FunctionArgs::getJacobian (const double in[], double delta = 1e-7) [inline, virtual, inherited]
This function computes Jacobian
.
TODO: Bring differencing out and use following information http://en.wikipedia.org/wiki/Numerical_differentiation#Practical_considerations_using_floating_point_arithmetic
Reimplemented in corecvs::IdentityFunction, corecvs::EssentialEstimator::CostFunction7to1, corecvs::RadialFunc, corecvs::DistPointsFunction, corecvs::AnglePointsFunction, corecvs::AngleFunction, corecvs::StraightFunc, corecvs::CurvatureFunc, and corecvs::CamerasCalibrationFunc.
Definition at line 68 of file function.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::FunctionArgs::inputs, corecvs::FunctionArgs::operator()(), and corecvs::FunctionArgs::outputs.
Referenced by corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::FunctionArgs::getJacobian(), corecvs::GradientDescent::minimise(), corecvs::ClassicKalman::predict(), and corecvs::ClassicKalman::update().
    {
        Matrix result(outputs, inputs);
        vector<double> xc(inputs);
        vector<double> y_minus(outputs);
        vector<double> y_plus (outputs);
        for (int i = 0; i < inputs; i++)
        {
            xc[i] = in[i];
        }
        for (int i = 0; i < inputs; i++)
        {
            xc[i] = in[i] - delta;
            operator()(&xc[0], &y_minus[0]);
            xc[i] = in[i] + delta;
            operator()(&xc[0], &y_plus[0]);
            xc[i] = in[i];
            for (int j = 0; j < outputs; j++)
            {
                result.element(j,i) = (y_plus[j] - y_minus[j]) / (2.0 * delta);
            }
        }
        return result;
    }
virtual Matrix corecvs::FunctionArgs::getJacobian (const Vector & in, double delta = 1e-7) [inline, virtual, inherited]
Definition at line 96 of file function.h.
References corecvs::FixedArrayBase< RealType, ElementType >::element, and corecvs::FunctionArgs::getJacobian().
    {
        return getJacobian(in.element, delta);
    }
double corecvs::EssentialEstimator::CostFunctionBase::getRotationAngle (const double in[]) [static]
Definition at line 420 of file essentialEstimator.cpp.
{
    return getRotationQ(in).getAngle();
}
Vector3dd corecvs::EssentialEstimator::CostFunctionBase::getRotationAxis (const double in[]) [static]
Definition at line 425 of file essentialEstimator.cpp.
{
    return getRotationQ(in).getAxis();
}
Matrix33 corecvs::EssentialEstimator::CostFunctionBase::getRotationM (const double in[]) [static]
Definition at line 415 of file essentialEstimator.cpp.
{
    return getRotationQ(in).toMatrix();
}
Quaternion corecvs::EssentialEstimator::CostFunctionBase::getRotationQ (const double in[]) [static]
Definition at line 405 of file essentialEstimator.cpp.
References ROTATION_Q_T, ROTATION_Q_X, ROTATION_Q_Y, and ROTATION_Q_Z.
Referenced by corecvs::EssentialEstimator::NormalizeFunction::operator()().
{
    return Quaternion(in[ROTATION_Q_X], in[ROTATION_Q_Y], in[ROTATION_Q_Z], in[ROTATION_Q_T]).normalised();
}
Vector3dd corecvs::EssentialEstimator::CostFunctionBase::getTranslation (const double in[]) [static]
Definition at line 410 of file essentialEstimator.cpp.
References corecvs::VectorOperationsBase< RealType, ElementType >::normalised().
Referenced by corecvs::EssentialEstimator::NormalizeFunction::operator()().
{
    return Vector3dd(in[TRANSLATION_X], in[TRANSLATION_Y], in[TRANSLATION_Z]).normalised();
}
virtual void corecvs::FunctionArgs::operator() (const double in[], double out[]) [pure virtual, inherited]
Operator that computes funсtion.
Implemented in corecvs::LengthFunction, corecvs::RadialCorrection, corecvs::Map2DFunction< Map2D >, corecvs::ScalerFunction, corecvs::EssentialEstimator::CostFunction7toN, corecvs::IdentityFunction, corecvs::EssentialEstimator::NormalizeFunction, corecvs::HomographyReconstructor::CostFunctionWize, corecvs::HomographyReconstructor::CostFunction, corecvs::EssentialEstimator::CostFunction7to1, corecvs::RadialFunc, corecvs::RosenbrockFunction, corecvs::DistPointsFunction, corecvs::AnglePointsFunction, corecvs::AngleFunction, corecvs::StraightFunc, corecvs::CurvatureFunc, and corecvs::CamerasCalibrationFunc.
Referenced by corecvs::FunctionArgs::getJacobian(), and corecvs::FunctionArgs::operator()().
virtual void corecvs::FunctionArgs::operator() (const Vector & in, Vector & out) [inline, virtual, inherited]
Definition at line 46 of file function.h.
References corecvs::FixedArrayBase< RealType, ElementType >::element, and corecvs::FunctionArgs::operator()().
    {
        return operator()(in.element, out.element);
    }
void corecvs::EssentialEstimator::CostFunctionBase::packState (double out[], const Quaternion & q, const Vector3dd & t) [static]
Definition at line 435 of file essentialEstimator.cpp.
References ROTATION_Q_T, ROTATION_Q_X, ROTATION_Q_Y, ROTATION_Q_Z, corecvs::GenericQuaternion< ElementType >::t(), TRANSLATION_X, TRANSLATION_Y, TRANSLATION_Z, corecvs::GenericQuaternion< ElementType >::x(), corecvs::Vector3d< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), corecvs::Vector3d< ElementType >::y(), corecvs::GenericQuaternion< ElementType >::z(), and corecvs::Vector3d< ElementType >::z().
Referenced by corecvs::EssentialEstimator::getEssentialGrad(), corecvs::EssentialEstimator::getEssentialGradToRm(), corecvs::EssentialEstimator::getEssentialLM(), corecvs::EssentialEstimator::getEssentialSimpleKalman(), and corecvs::EssentialEstimator::NormalizeFunction::operator()().
{
    out[CostFunctionBase::ROTATION_Q_X]  = q.x();
    out[CostFunctionBase::ROTATION_Q_Y]  = q.y();
    out[CostFunctionBase::ROTATION_Q_Z]  = q.z();
    out[CostFunctionBase::ROTATION_Q_T]  = q.t();
    out[CostFunctionBase::TRANSLATION_X] = t.x();
    out[CostFunctionBase::TRANSLATION_Y] = t.y();
    out[CostFunctionBase::TRANSLATION_Z] = t.z();
}
Member Data Documentation
int corecvs::FunctionArgs::inputs [inherited]
Definition at line 32 of file function.h.
Referenced by corecvs::ClassicKalman::ClassicKalman(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawIsolines(), corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::CamerasCalibrationFunc::getJacobian(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::FunctionArgs::getJacobian(), corecvs::IdentityFunction::getJacobian(), corecvs::LengthFunction::LengthFunction(), corecvs::GradientDescent::minimise(), corecvs::IdentityFunction::operator()(), and corecvs::ScalerFunction::ScalerFunction().
int corecvs::FunctionArgs::outputs [inherited]
Definition at line 33 of file function.h.
Referenced by corecvs::ClassicKalman::ClassicKalman(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawIsolines(), corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::CamerasCalibrationFunc::getJacobian(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::FunctionArgs::getJacobian(), corecvs::IdentityFunction::getJacobian(), corecvs::LengthFunction::LengthFunction(), corecvs::GradientDescent::minimise(), corecvs::ScalerFunction::operator()(), corecvs::LengthFunction::operator()(), and corecvs::ScalerFunction::ScalerFunction().
The documentation for this class was generated from the following files:
core/rectification/essentialEstimator.h
core/rectification/essentialEstimator.cpp