DeepView: corecvs::CameraAngles Class Reference
corecvs::CameraAngles Class Reference
As rotation depends on the order of application of the rotations of Euler angles this class specifies one of possible orders that will be used for camera rotation description.
#include <eulerAngles.h>
Public Member Functions
CameraAngles (double pitch, double yaw, double roll)
double pitch () const
void setPitch (double pitch)
double yaw () const
void setYaw (double yaw)
double roll () const
void setRoll (double roll)
Matrix33 toMatrix () const
template<class VisitorType >
void accept (VisitorType &visitor)
Static Public Member Functions
static CameraAngles FromQuaternion (Quaternion &Q)
Public Attributes
double alpha
Rotation around X axis.
double beta
Rotation around Y axis.
double gamma
Rotation around Z axis.
Friends
ostream & operator<< (ostream &out, const EulerAngles &angels)
Detailed Description
As rotation depends on the order of application of the rotations of Euler angles this class specifies one of possible orders that will be used for camera rotation description.
-to the right of the image (from top left to the top right corner)
-downwards (from top left to the bottom left corner)
-orthogonal, goes from the camera into the scene
          ^ Z
         /
        /
       /
      /
     O----------------->  X
     |
     |
     |
     |
     |
     v  Y
Definition at line 78 of file eulerAngles.h.
Constructor & Destructor Documentation
corecvs::CameraAngles::CameraAngles (double pitch, double yaw, double roll) [inline]
Definition at line 81 of file eulerAngles.h.
Referenced by FromQuaternion().
                                                        :
        EulerAngles(pitch, yaw, roll)
    {}
Member Function Documentation
template<class VisitorType > void corecvs::CameraAngles::accept (VisitorType & visitor) [inline]
Definition at line 146 of file eulerAngles.h.
References corecvs::EulerAngles::alpha, corecvs::EulerAngles::beta, and corecvs::EulerAngles::gamma.
    {
        visitor.visit(alpha, 0.0, "pitch");
        visitor.visit(beta , 0.0, "yaw"  );
        visitor.visit(gamma, 0.0, "roll" );
    }
static CameraAngles corecvs::CameraAngles::FromQuaternion (Quaternion & Q) [inline, static]
Definition at line 136 of file eulerAngles.h.
References CameraAngles(), pitch(), roll(), corecvs::GenericQuaternion< ElementType >::t(), corecvs::GenericQuaternion< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), yaw(), and corecvs::GenericQuaternion< ElementType >::z().
    {
        double pitch = atan2 (2.0 * (Q.t() * Q.x() + Q.y() * Q.z()),1.0 - 2.0 * (Q.x() * Q.x() + Q.y() * Q.y()));
        double yaw   = asin  (2.0 * (Q.t() * Q.y() - Q.z() * Q.x()));
        double roll  = atan2 (2.0 * (Q.t() * Q.z() + Q.x() * Q.y()),1.0 - 2.0 * (Q.y() * Q.y() + Q.z() * Q.z()));
        return CameraAngles(pitch, yaw, roll);
    };
double corecvs::CameraAngles::pitch () const [inline]
Definition at line 85 of file eulerAngles.h.
References corecvs::EulerAngles::alpha.
Referenced by FromQuaternion(), RectifyParametersControlWidget::setManualTab(), setPitch(), and toMatrix().
    {
        return alpha;
    }
double corecvs::CameraAngles::roll () const [inline]
Definition at line 105 of file eulerAngles.h.
References corecvs::EulerAngles::gamma.
Referenced by FromQuaternion(), RectifyParametersControlWidget::setManualTab(), setRoll(), and toMatrix().
    {
        return gamma;
    }
void corecvs::CameraAngles::setPitch (double pitch) [inline]
Definition at line 90 of file eulerAngles.h.
References corecvs::EulerAngles::alpha, and pitch().
    {
        alpha = pitch;
    }
void corecvs::CameraAngles::setRoll (double roll) [inline]
Definition at line 110 of file eulerAngles.h.
References corecvs::EulerAngles::gamma, and roll().
    {
        gamma = roll;
    }
void corecvs::CameraAngles::setYaw (double yaw) [inline]
Definition at line 100 of file eulerAngles.h.
References corecvs::EulerAngles::beta, and yaw().
    {
        beta = yaw;
    }
Matrix33 corecvs::CameraAngles::toMatrix () const [inline]
Definition at line 115 of file eulerAngles.h.
References pitch(), roll(), corecvs::Matrix33::RotationX(), corecvs::Matrix33::RotationY(), corecvs::Matrix33::RotationZ(), and yaw().
    {
        return
            Matrix33::RotationZ(roll()) *
            Matrix33::RotationY(yaw()) *
            Matrix33::RotationX(pitch());
    }
double corecvs::CameraAngles::yaw () const [inline]
Definition at line 95 of file eulerAngles.h.
References corecvs::EulerAngles::beta.
Referenced by FromQuaternion(), RectifyParametersControlWidget::setManualTab(), setYaw(), and toMatrix().
    {
        return beta;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, const EulerAngles & angels) [friend, inherited]
Definition at line 38 of file eulerAngles.h.
    {
        out << "[alpha=" << angels.alpha << ", beta=" << angels.beta <<  ", gamma=" << angels.gamma  << "]";
        return out;
    }
Member Data Documentation
double corecvs::EulerAngles::alpha [inherited]
Rotation around X axis.
Definition at line 22 of file eulerAngles.h.
Referenced by accept(), corecvs::FCostFunction::getBMatrix(), corecvs::FCostFunction::getInvDMatrix(), corecvs::FCostFunction::GetMatrixForTransform(), corecvs::FCostFunction::getMMatrix(), pitch(), and setPitch().
double corecvs::EulerAngles::beta [inherited]
Rotation around Y axis.
Definition at line 23 of file eulerAngles.h.
Referenced by accept(), corecvs::FCostFunction::getBMatrix(), corecvs::FCostFunction::getInvDMatrix(), corecvs::FCostFunction::GetMatrixForTransform(), corecvs::FCostFunction::getMMatrix(), setYaw(), and yaw().
double corecvs::EulerAngles::gamma [inherited]
Rotation around Z axis.
Definition at line 24 of file eulerAngles.h.
Referenced by accept(), corecvs::FCostFunction::getBMatrix(), corecvs::FCostFunction::getInvDMatrix(), corecvs::FCostFunction::GetMatrixForTransform(), corecvs::FCostFunction::getMMatrix(), roll(), and setRoll().
The documentation for this class was generated from the following file:
core/math/eulerAngles.h