DeepView: MaskingParameters Class Reference
MaskingParameters Class Reference
Masking Parameters Masking Parameters.
#include <maskingParameters.h>
Public Types
enum FieldId { INVERT_ID, MASKING_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
bool invert () const
void setInvert (bool invert)
template<class VisitorType >
void accept (VisitorType &visitor)
MaskingParameters ()
MaskingParameters (bool invert)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
bool mInvert
Section with variables.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, MaskingParameters &toSave)
Detailed Description
Masking Parameters Masking Parameters.
Definition at line 38 of file maskingParameters.h.
Member Enumeration Documentation
enum MaskingParameters::FieldId
Enumerator:
INVERT_ID
MASKING_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file maskingParameters.h.
                 {
        INVERT_ID,
        MASKING_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
MaskingParameters::MaskingParameters () [inline]
Definition at line 81 of file maskingParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
MaskingParameters::MaskingParameters (bool invert) [inline]
Definition at line 87 of file maskingParameters.h.
    {
        mInvert = invert;
    }
Member Function Documentation
template<class VisitorType > void MaskingParameters::accept (VisitorType & visitor) [inline]
Definition at line 76 of file maskingParameters.h.
Referenced by corecvs::MaskFilterBlock::deserialize(), and corecvs::MaskFilterBlock::serialize().
    {
        visitor.visit(mInvert,                    static_cast<const BoolField *>    (fields()[INVERT_ID]));
    }
static const char* corecvs::BaseReflection< MaskingParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< MaskingParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< MaskingParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* MaskingParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 58 of file maskingParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< MaskingParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
bool MaskingParameters::invert () const [inline]
Definition at line 62 of file maskingParameters.h.
Referenced by MaskingParametersControlWidget::setParameters().
    {
        return mInvert;
    }
static const char* corecvs::BaseReflection< MaskingParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< MaskingParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void MaskingParameters::print () [inline]
Definition at line 101 of file maskingParameters.h.
    {
        cout << *this;
    }
void MaskingParameters::setInvert (bool invert) [inline]
Definition at line 68 of file maskingParameters.h.
    {
        mInvert = invert;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int MaskingParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file maskingParameters.cpp.
References corecvs::BaseReflection< MaskingParameters >::fields(), INVERT_ID, mInvert, and corecvs::BaseReflection< MaskingParameters >::naming().
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Masking Parameters",
        "Masking Parameters",
        ""
    );
    fields().push_back(
        new BoolField
        (
          MaskingParameters::INVERT_ID,
          offsetof(MaskingParameters, mInvert),
          false,
          "Invert",
          "Invert",
          "Invert"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, MaskingParameters & toSave) [friend]
Definition at line 94 of file maskingParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< MaskingParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
bool MaskingParameters::mInvert
Section with variables.
Invert Invert
Definition at line 52 of file maskingParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< MaskingParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/maskingParameters.h
core/xml/generated/maskingParameters.cpp