DeepView: corecvs::AbstractFilter Class Reference
corecvs::AbstractFilter Class Reference
#include <abstractFilter.h>
Public Member Functions
AbstractFilter ()
virtual const char * getInstanceName ()
virtual bool setParameters (const void *newParameters)=0
virtual G12Buffer * filter (G12Buffer *input)=0
virtual ~AbstractFilter ()
Static Public Member Functions
static const char * getName ()
Detailed Description
Definition at line 17 of file abstractFilter.h.
Constructor & Destructor Documentation
corecvs::AbstractFilter::AbstractFilter ()
Definition at line 14 of file abstractFilter.cpp.
{
    // TODO Auto-generated constructor stub
}
corecvs::AbstractFilter::~AbstractFilter () [virtual]
Definition at line 20 of file abstractFilter.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
virtual G12Buffer* corecvs::AbstractFilter::filter (G12Buffer * input) [pure virtual]
Implemented in corecvs::FilterExecuter.
virtual const char* corecvs::AbstractFilter::getInstanceName () [inline, virtual]
Definition at line 28 of file abstractFilter.h.
References getName().
    {
        return AbstractFilter::getName();
    }
static const char* corecvs::AbstractFilter::getName () [inline, static]
Definition at line 23 of file abstractFilter.h.
Referenced by corecvs::FilterExecuter::filter(), and getInstanceName().
    {
        return "Base";
    }
virtual bool corecvs::AbstractFilter::setParameters (const void * newParameters) [pure virtual]
Implemented in corecvs::FilterExecuter.
Referenced by corecvs::FilterExecuter::setParameters().
The documentation for this class was generated from the following files:
core/filters/abstractFilter.h
core/filters/abstractFilter.cpp