DeepView: corecvs::LUTGenerator Class Reference
corecvs::LUTGenerator Class Reference
#include <lutAlgebra.h>
Classes
struct Deviations
Public Member Functions
LUTable * generate (SpeedupFunction &input, string name, unsigned tableSize)
Deviations deviations (LUTable *table, SpeedupFunction &input)
Detailed Description
Definition at line 71 of file lutAlgebra.h.
Member Function Documentation
LUTGenerator::Deviations corecvs::LUTGenerator::deviations (LUTable * table, SpeedupFunction & input)
Definition at line 105 of file lutAlgebra.cpp.
References corecvs::LUTable::approxF(), corecvs::SpeedupFunction::f(), corecvs::LUTable::high, and corecvs::LUTable::low.
Referenced by corecvs::test1Main().
{
    double sumDevs = 0;
    double sumSqDevs = 0;
    double maxDevs = 0;
    int valMax = 0;
    for (int i = table->low; i <= table->high; i++)
    {
        double dev = table->approxF(i) - input.f(i);
        dev = fabs(dev);
        sumDevs += dev;
        sumSqDevs += dev * dev;
        if (dev > maxDevs)
        {
            valMax = i;
            maxDevs = dev;
        }
    }
    Deviations devs = {sumDevs, sumSqDevs, maxDevs, valMax, table->high - table->low};
    return devs;
}
LUTable * corecvs::LUTGenerator::generate (SpeedupFunction & input, string name, unsigned tableSize)
Definition at line 56 of file lutAlgebra.cpp.
References corecvs::LUTable::data, corecvs::LUTable::division, corecvs::SpeedupFunction::f(), corecvs::SpeedupFunction::getDomainHigh(), corecvs::SpeedupFunction::getDomainLow(), corecvs::LUTable::high, corecvs::LUTable::low, corecvs::LUTable::name, corecvs::LUTable::shift, and corecvs::LUTable::tailLen.
Referenced by corecvs::test1Main().
{
    LUTable *luttable = new LUTable();
    luttable->name = name;
    luttable->data.resize(tableSize);
    unsigned low  = input.getDomainLow();
    unsigned high = input.getDomainHigh();
    unsigned interval = high - low;
    luttable->shift = 22;
    luttable->division = 16;
    luttable->tailLen = 15;
    printf("interval = %u\n", interval);
    for (unsigned i = 0; i < tableSize; i++)
    {
        uint32_t start = i * (interval / tableSize);
        uint32_t end   = (i + 1)  * (interval / tableSize);
        uint32_t sqrtstart = input.f(start);
        uint32_t sqrtend   = input.f(end);
        double slope = ((double)sqrtend - sqrtstart) / ((double)interval / tableSize);
        //uint32_t middle = (start + end) / 2;
        //double
        uint32_t packedStart = (uint32_t) sqrtstart;
        uint32_t packedSlope = (uint32_t) ceil(slope * (1 << luttable->shift));
        if (packedSlope > (1U << luttable->division))
        {
            printf("Overflow in slope, reduce SHIFT\n");
            exit(0);
        }
        luttable->data[i] = (packedStart << luttable->division) | packedSlope;
        printf("Start = %u, End = %u, slope = %2.5lf, 0x%x\n ", start, end, slope, packedSlope);
    }
    luttable->high = high;
    luttable->low  = low;
    return luttable;
}
The documentation for this class was generated from the following files:
core/math/lutAlgebra.h
core/math/lutAlgebra.cpp