DeepView: PresentationParameters Class Reference
PresentationParameters Class Reference
Presentation parameters Presentation parameters.
#include <presentationParameters.h>
Public Types
enum FieldId {
LEFTFRAME_ID, RIGHTFRAME_ID, STEREO_ID, FLOW_ID,
OUTPUT_ID, SHOWCLUSTERS_ID, SHOWHISTOGRAM_ID, AUTO_UPDATE_HISTOGRAM_ID,
SHOWAREAOFINTEREST_ID, PRODUCE3D_ID, PRODUCE6D_ID, DUMP3D_ID,
PRESENTATION_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
bool leftFrame () const
bool rightFrame () const
StereoStyle::StereoStyle stereo () const
FlowStyle::FlowStyle flow () const
OutputStyle::OutputStyle output () const
bool showClusters () const
bool showHistogram () const
bool autoUpdateHistogram () const
bool showAreaOfInterest () const
bool produce3D () const
bool produce6D () const
bool dump3D () const
void setLeftFrame (bool leftFrame)
void setRightFrame (bool rightFrame)
void setStereo (StereoStyle::StereoStyle stereo)
void setFlow (FlowStyle::FlowStyle flow)
void setOutput (OutputStyle::OutputStyle output)
void setShowClusters (bool showClusters)
void setShowHistogram (bool showHistogram)
void setAutoUpdateHistogram (bool autoUpdateHistogram)
void setShowAreaOfInterest (bool showAreaOfInterest)
void setProduce3D (bool produce3D)
void setProduce6D (bool produce6D)
void setDump3D (bool dump3D)
template<class VisitorType >
void accept (VisitorType &visitor)
PresentationParameters ()
PresentationParameters (bool leftFrame, bool rightFrame, StereoStyle::StereoStyle stereo, FlowStyle::FlowStyle flow, OutputStyle::OutputStyle output, bool showClusters, bool showHistogram, bool autoUpdateHistogram, bool showAreaOfInterest, bool produce3D, bool produce6D, bool dump3D)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
bool mLeftFrame
Section with variables.
bool mRightFrame
rightFrame rightFrame
int mStereo
Stereo Stereo.
int mFlow
Flow Flow.
int mOutput
Output Output.
bool mShowClusters
showClusters showClusters
bool mShowHistogram
showHistogram showHistogram
bool mAutoUpdateHistogram
Auto Update Histogram Auto Update Histogram.
bool mShowAreaOfInterest
showAreaOfInterest showAreaOfInterest
bool mProduce3D
produce3D produce3D
bool mProduce6D
produce6D produce6D
bool mDump3D
dump3D dump3D
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, PresentationParameters &toSave)
Detailed Description
Presentation parameters Presentation parameters.
Definition at line 41 of file presentationParameters.h.
Member Enumeration Documentation
enum PresentationParameters::FieldId
Enumerator:
LEFTFRAME_ID
RIGHTFRAME_ID
STEREO_ID
FLOW_ID
OUTPUT_ID
SHOWCLUSTERS_ID
SHOWHISTOGRAM_ID
AUTO_UPDATE_HISTOGRAM_ID
SHOWAREAOFINTEREST_ID
PRODUCE3D_ID
PRODUCE6D_ID
DUMP3D_ID
PRESENTATION_PARAMETERS_FIELD_ID_NUM
Definition at line 44 of file presentationParameters.h.
                 {
        LEFTFRAME_ID,
        RIGHTFRAME_ID,
        STEREO_ID,
        FLOW_ID,
        OUTPUT_ID,
        SHOWCLUSTERS_ID,
        SHOWHISTOGRAM_ID,
        AUTO_UPDATE_HISTOGRAM_ID,
        SHOWAREAOFINTEREST_ID,
        PRODUCE3D_ID,
        PRODUCE6D_ID,
        DUMP3D_ID,
        PRESENTATION_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
PresentationParameters::PresentationParameters () [inline]
Definition at line 282 of file presentationParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
PresentationParameters::PresentationParameters (bool leftFrame, bool rightFrame, StereoStyle::StereoStyle stereo, FlowStyle::FlowStyle flow, OutputStyle::OutputStyle output, bool showClusters, bool showHistogram, bool autoUpdateHistogram, bool showAreaOfInterest, bool produce3D, bool produce6D, bool dump3D) [inline]
Definition at line 288 of file presentationParameters.h.
    {
        mLeftFrame = leftFrame;
        mRightFrame = rightFrame;
        mStereo = stereo;
        mFlow = flow;
        mOutput = output;
        mShowClusters = showClusters;
        mShowHistogram = showHistogram;
        mAutoUpdateHistogram = autoUpdateHistogram;
        mShowAreaOfInterest = showAreaOfInterest;
        mProduce3D = produce3D;
        mProduce6D = produce6D;
        mDump3D = dump3D;
    }
Member Function Documentation
template<class VisitorType > void PresentationParameters::accept (VisitorType & visitor) [inline]
Definition at line 266 of file presentationParameters.h.
    {
        visitor.visit(mLeftFrame,                 static_cast<const BoolField *>    (fields()[LEFTFRAME_ID]));
        visitor.visit(mRightFrame,                static_cast<const BoolField *>    (fields()[RIGHTFRAME_ID]));
        visitor.visit((int &)mStereo,             static_cast<const EnumField *>    (fields()[STEREO_ID]));
        visitor.visit((int &)mFlow,               static_cast<const EnumField *>    (fields()[FLOW_ID]));
        visitor.visit((int &)mOutput,             static_cast<const EnumField *>    (fields()[OUTPUT_ID]));
        visitor.visit(mShowClusters,              static_cast<const BoolField *>    (fields()[SHOWCLUSTERS_ID]));
        visitor.visit(mShowHistogram,             static_cast<const BoolField *>    (fields()[SHOWHISTOGRAM_ID]));
        visitor.visit(mAutoUpdateHistogram,       static_cast<const BoolField *>    (fields()[AUTO_UPDATE_HISTOGRAM_ID]));
        visitor.visit(mShowAreaOfInterest,        static_cast<const BoolField *>    (fields()[SHOWAREAOFINTEREST_ID]));
        visitor.visit(mProduce3D,                 static_cast<const BoolField *>    (fields()[PRODUCE3D_ID]));
        visitor.visit(mProduce6D,                 static_cast<const BoolField *>    (fields()[PRODUCE6D_ID]));
        visitor.visit(mDump3D,                    static_cast<const BoolField *>    (fields()[DUMP3D_ID]));
    }
bool PresentationParameters::autoUpdateHistogram () const [inline]
Definition at line 177 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mAutoUpdateHistogram;
    }
static const char* corecvs::BaseReflection< PresentationParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
bool PresentationParameters::dump3D () const [inline]
Definition at line 197 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mDump3D;
    }
static int corecvs::BaseReflection< PresentationParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< PresentationParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
FlowStyle::FlowStyle PresentationParameters::flow () const [inline]
Definition at line 157 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return static_cast<FlowStyle::FlowStyle>(mFlow);
    }
const void* PresentationParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 138 of file presentationParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< PresentationParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
bool PresentationParameters::leftFrame () const [inline]
Definition at line 142 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mLeftFrame;
    }
static const char* corecvs::BaseReflection< PresentationParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< PresentationParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
OutputStyle::OutputStyle PresentationParameters::output () const [inline]
Definition at line 162 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return static_cast<OutputStyle::OutputStyle>(mOutput);
    }
void PresentationParameters::print () [inline]
Definition at line 324 of file presentationParameters.h.
    {
        cout << *this;
    }
bool PresentationParameters::produce3D () const [inline]
Definition at line 187 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mProduce3D;
    }
bool PresentationParameters::produce6D () const [inline]
Definition at line 192 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mProduce6D;
    }
bool PresentationParameters::rightFrame () const [inline]
Definition at line 147 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mRightFrame;
    }
void PresentationParameters::setAutoUpdateHistogram (bool autoUpdateHistogram) [inline]
Definition at line 238 of file presentationParameters.h.
    {
        mAutoUpdateHistogram = autoUpdateHistogram;
    }
void PresentationParameters::setDump3D (bool dump3D) [inline]
Definition at line 258 of file presentationParameters.h.
    {
        mDump3D = dump3D;
    }
void PresentationParameters::setFlow (FlowStyle::FlowStyle flow) [inline]
Definition at line 218 of file presentationParameters.h.
    {
        mFlow = flow;
    }
void PresentationParameters::setLeftFrame (bool leftFrame) [inline]
Definition at line 203 of file presentationParameters.h.
    {
        mLeftFrame = leftFrame;
    }
void PresentationParameters::setOutput (OutputStyle::OutputStyle output) [inline]
Definition at line 223 of file presentationParameters.h.
    {
        mOutput = output;
    }
void PresentationParameters::setProduce3D (bool produce3D) [inline]
Definition at line 248 of file presentationParameters.h.
    {
        mProduce3D = produce3D;
    }
void PresentationParameters::setProduce6D (bool produce6D) [inline]
Definition at line 253 of file presentationParameters.h.
    {
        mProduce6D = produce6D;
    }
void PresentationParameters::setRightFrame (bool rightFrame) [inline]
Definition at line 208 of file presentationParameters.h.
    {
        mRightFrame = rightFrame;
    }
void PresentationParameters::setShowAreaOfInterest (bool showAreaOfInterest) [inline]
Definition at line 243 of file presentationParameters.h.
    {
        mShowAreaOfInterest = showAreaOfInterest;
    }
void PresentationParameters::setShowClusters (bool showClusters) [inline]
Definition at line 228 of file presentationParameters.h.
    {
        mShowClusters = showClusters;
    }
void PresentationParameters::setShowHistogram (bool showHistogram) [inline]
Definition at line 233 of file presentationParameters.h.
    {
        mShowHistogram = showHistogram;
    }
void PresentationParameters::setStereo (StereoStyle::StereoStyle stereo) [inline]
Definition at line 213 of file presentationParameters.h.
    {
        mStereo = stereo;
    }
bool PresentationParameters::showAreaOfInterest () const [inline]
Definition at line 182 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mShowAreaOfInterest;
    }
bool PresentationParameters::showClusters () const [inline]
Definition at line 167 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mShowClusters;
    }
bool PresentationParameters::showHistogram () const [inline]
Definition at line 172 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return mShowHistogram;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int PresentationParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file presentationParameters.cpp.
References AUTO_UPDATE_HISTOGRAM_ID, DUMP3D_ID, corecvs::BaseReflection< PresentationParameters >::fields(), FLOW_ID, LEFTFRAME_ID, mAutoUpdateHistogram, mDump3D, mFlow, mLeftFrame, mOutput, mProduce3D, mProduce6D, mRightFrame, mShowAreaOfInterest, mShowClusters, mShowHistogram, mStereo, corecvs::BaseReflection< PresentationParameters >::naming(), OUTPUT_ID, PRODUCE3D_ID, PRODUCE6D_ID, RIGHTFRAME_ID, SHOWAREAOFINTEREST_ID, SHOWCLUSTERS_ID, SHOWHISTOGRAM_ID, and STEREO_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Presentation Parameters",
        "Presentation parameters",
        ""
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::LEFTFRAME_ID,
          offsetof(PresentationParameters, mLeftFrame),
          false,
          "leftFrame",
          "leftFrame",
          "leftFrame"
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::RIGHTFRAME_ID,
          offsetof(PresentationParameters, mRightFrame),
          true,
          "rightFrame",
          "rightFrame",
          "rightFrame"
        )
    );
    fields().push_back(
        new EnumField
        (
          PresentationParameters::STEREO_ID,
          offsetof(PresentationParameters, mStereo),
          0,
          "Stereo",
          "Stereo",
          "Stereo",
           NULL
        )
    );
    fields().push_back(
        new EnumField
        (
          PresentationParameters::FLOW_ID,
          offsetof(PresentationParameters, mFlow),
          0,
          "Flow",
          "Flow",
          "Flow",
           NULL
        )
    );
    fields().push_back(
        new EnumField
        (
          PresentationParameters::OUTPUT_ID,
          offsetof(PresentationParameters, mOutput),
          0,
          "Output",
          "Output",
          "Output",
           NULL
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::SHOWCLUSTERS_ID,
          offsetof(PresentationParameters, mShowClusters),
          true,
          "showClusters",
          "showClusters",
          "showClusters"
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::SHOWHISTOGRAM_ID,
          offsetof(PresentationParameters, mShowHistogram),
          true,
          "showHistogram",
          "showHistogram",
          "showHistogram"
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::AUTO_UPDATE_HISTOGRAM_ID,
          offsetof(PresentationParameters, mAutoUpdateHistogram),
          false,
          "Auto Update Histogram",
          "Auto Update Histogram",
          "Auto Update Histogram"
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::SHOWAREAOFINTEREST_ID,
          offsetof(PresentationParameters, mShowAreaOfInterest),
          true,
          "showAreaOfInterest",
          "showAreaOfInterest",
          "showAreaOfInterest"
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::PRODUCE3D_ID,
          offsetof(PresentationParameters, mProduce3D),
          false,
          "produce3D",
          "produce3D",
          "produce3D"
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::PRODUCE6D_ID,
          offsetof(PresentationParameters, mProduce6D),
          false,
          "produce6D",
          "produce6D",
          "produce6D"
        )
    );
    fields().push_back(
        new BoolField
        (
          PresentationParameters::DUMP3D_ID,
          offsetof(PresentationParameters, mDump3D),
          false,
          "dump3D",
          "dump3D",
          "dump3D"
        )
    );
   return 0;
}
StereoStyle::StereoStyle PresentationParameters::stereo () const [inline]
Definition at line 152 of file presentationParameters.h.
Referenced by PresentationParametersControlWidget::setParameters().
    {
        return static_cast<StereoStyle::StereoStyle>(mStereo);
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, PresentationParameters & toSave) [friend]
Definition at line 317 of file presentationParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< PresentationParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
bool PresentationParameters::mAutoUpdateHistogram
Auto Update Histogram Auto Update Histogram.
Definition at line 108 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mDump3D
dump3D dump3D
Definition at line 132 of file presentationParameters.h.
Referenced by staticInit().
int PresentationParameters::mFlow
Flow Flow.
Definition at line 84 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mLeftFrame
Section with variables.
leftFrame leftFrame
Definition at line 66 of file presentationParameters.h.
Referenced by staticInit().
int PresentationParameters::mOutput
Output Output.
Definition at line 90 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mProduce3D
produce3D produce3D
Definition at line 120 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mProduce6D
produce6D produce6D
Definition at line 126 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mRightFrame
rightFrame rightFrame
Definition at line 72 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mShowAreaOfInterest
showAreaOfInterest showAreaOfInterest
Definition at line 114 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mShowClusters
showClusters showClusters
Definition at line 96 of file presentationParameters.h.
Referenced by staticInit().
bool PresentationParameters::mShowHistogram
showHistogram showHistogram
Definition at line 102 of file presentationParameters.h.
Referenced by staticInit().
int PresentationParameters::mStereo
Stereo Stereo.
Definition at line 78 of file presentationParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< PresentationParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
applications/base/generatedParameters/presentationParameters.h
applications/base/generatedParameters/presentationParameters.cpp