DeepView: CameraCalculatorWidget Class Reference
CameraCalculatorWidget Class Reference
#include <cameraCalculatorWidget.h>
Public Slots
void sensorPresetChanged ()
Block corresponding to sensor.
void resolutionChanged ()
void aspectChanged ()
void aspectAutoChanged ()
void sensorHorizontalChanged ()
void sensorVerticalChanged ()
void sensorDiagonalChanged ()
void lensPresetChanged ()
Block corresponding to lens.
void lensFocalChanged ()
void lensNominalAngleChanged ()
void lensRealAngleChanged ()
void objectSizeChanged ()
void objectPxSizeChanged ()
void objectDistanceChanged ()
void stereoBaseLineChanged ()
void stereoAlgorithPrecisionChanged ()
Public Member Functions
CameraCalculatorWidget (QWidget *parent=0)
~CameraCalculatorWidget ()
Static Public Attributes
static SensorPreset sensorPresets []
static const int sensorPresetsSize = 34
static LensPreset lensPersets []
static const int lensPresetsSize = 7
Private Slots
void setColor (QDoubleSpinBox *changedValueBox, int timeoutNum)
void setDisparity ()
Private Member Functions
void setNewValue (QDoubleSpinBox *box, double value)
void updateSensorStats (void)
void updateLensStats (void)
void updateStereoStats (void)
void startTimer (QDoubleSpinBox *spinBox)
double getPixelHeight ()
double getPixelWidth ()
double getAlgorithmPrecision ()
Static Private Member Functions
static void setValueBlocking (QDoubleSpinBox *box, double value)
Private Attributes
Ui::CameraCalculatorWidgetClass ui
std::vector< ColorTimer * > mTimers
Detailed Description
Definition at line 23 of file cameraCalculatorWidget.h.
Constructor & Destructor Documentation
CameraCalculatorWidget::CameraCalculatorWidget (QWidget * parent = 0)
Definition at line 69 of file cameraCalculatorWidget.cpp.
References aspectChanged(), lensFocalChanged(), lensNominalAngleChanged(), lensPersets, lensPresetChanged(), lensPresetsSize, lensRealAngleChanged(), objectDistanceChanged(), objectPxSizeChanged(), objectSizeChanged(), resolutionChanged(), sensorDiagonalChanged(), sensorHorizontalChanged(), sensorPresetChanged(), sensorPresets, sensorPresetsSize, sensorVerticalChanged(), setDisparity(), stereoAlgorithPrecisionChanged(), stereoBaseLineChanged(), and ui.
    : QWidget(parent)
{
    ui.setupUi(this);
    for (int i = 0; i < sensorPresetsSize; i++)
    {
        ui.sensorPresetComboBox->addItem(QString(sensorPresets[i].name));
        ui.lensNominalSensorComboBox->addItem(QString(sensorPresets[i].name));
    }
    for (int i = 0; i < lensPresetsSize; i++)
    {
        ui.lensPresetComboBox->addItem(QString(lensPersets[i].name));
    }
    /* Sensors */
    connect(ui.sensorPresetComboBox, SIGNAL(currentIndexChanged(int)), this, SLOT(sensorPresetChanged()));
    connect(ui.xResolutionSpinBox, SIGNAL(valueChanged(int)), this, SLOT(resolutionChanged()));
    connect(ui.yResolutionSpinBox, SIGNAL(valueChanged(int)), this, SLOT(resolutionChanged()));
    connect(ui.aspectSpinBox, SIGNAL(valueChanged(double)), this, SLOT(aspectChanged()));
    connect(ui.horizontalSizeSpinBox, SIGNAL(valueChanged(double)), this, SLOT(sensorHorizontalChanged()));
    connect(ui.verticalSizeSpinBox  , SIGNAL(valueChanged(double)), this, SLOT(sensorVerticalChanged()));
    connect(ui.diagonalSizeSpinBox  , SIGNAL(valueChanged(double)), this, SLOT(sensorDiagonalChanged()));
    /* Lens */
    connect(ui.lensPresetComboBox    , SIGNAL(currentIndexChanged(int)), this, SLOT(lensPresetChanged()));
    connect(ui.lensFocalLengthSpinBox, SIGNAL(valueChanged(double)), this, SLOT(lensFocalChanged()));
    connect(ui.lensAOVSpinBox        , SIGNAL(valueChanged(double)), this, SLOT(lensNominalAngleChanged()));
    connect(ui.sensorAOVSpinBox      , SIGNAL(valueChanged(double)), this, SLOT(lensRealAngleChanged()));
    /* Object */
    connect(ui.objectSizeSpinBox     , SIGNAL(valueChanged(double)), this, SLOT(objectSizeChanged()));
    connect(ui.objectPixelSizeSpinBox, SIGNAL(valueChanged(double)), this, SLOT(objectPxSizeChanged()));
    connect(ui.objectDistanceSpinBox , SIGNAL(valueChanged(double)), this, SLOT(objectDistanceChanged()));
    /* Stereo */
    connect(ui.objectSizeSpinBox     , SIGNAL(valueChanged(double))    , this, SLOT(stereoBaseLineChanged()));
    connect(ui.lensPresetComboBox    , SIGNAL(currentIndexChanged(int)), this, SLOT(stereoAlgorithPrecisionChanged()));
    connect(ui.baseLineSpinBox       , SIGNAL(valueChanged(double))   , this, SLOT(setDisparity()));
}
CameraCalculatorWidget::~CameraCalculatorWidget ()
Definition at line 329 of file cameraCalculatorWidget.cpp.
References mTimers.
{
    foreach (QTimer *timer, mTimers)
    {
        delete timer;
    }
}
Member Function Documentation
void CameraCalculatorWidget::aspectAutoChanged () [slot]
Definition at line 190 of file cameraCalculatorWidget.cpp.
References ui.
{
    ui.aspectSpinBox->setEnabled(ui.aspectAutoCheckBox->isChecked());
}
void CameraCalculatorWidget::aspectChanged () [slot]
Definition at line 185 of file cameraCalculatorWidget.cpp.
References sensorDiagonalChanged().
Referenced by CameraCalculatorWidget().
{
    sensorDiagonalChanged();
}
double CameraCalculatorWidget::getAlgorithmPrecision () [private]
Definition at line 348 of file cameraCalculatorWidget.cpp.
References ui.
Referenced by updateStereoStats().
{
   switch (ui.stereoAlgorithmPrecBox->currentIndex())
   {
       default:
       case 0: return 1.0;
       case 1: return 1.0 / 2.0;
       case 2: return 1.0 / 4.0;
       case 3: return 1.0 / 8.0;
   }
}
double CameraCalculatorWidget::getPixelHeight () [private]
Definition at line 338 of file cameraCalculatorWidget.cpp.
References ui.
Referenced by updateSensorStats().
{
    return ui.verticalSizeSpinBox->value() / ui.yResolutionSpinBox->value();
}
double CameraCalculatorWidget::getPixelWidth () [private]
Definition at line 343 of file cameraCalculatorWidget.cpp.
References ui.
Referenced by objectDistanceChanged(), objectPxSizeChanged(), objectSizeChanged(), updateSensorStats(), and updateStereoStats().
{
    return ui.horizontalSizeSpinBox->value() / ui.xResolutionSpinBox->value();
}
void CameraCalculatorWidget::lensFocalChanged () [slot]
Definition at line 209 of file cameraCalculatorWidget.cpp.
References SensorPreset::imagerW, corecvs::radToDeg(), sensorPresets, setNewValue(), and ui.
Referenced by CameraCalculatorWidget().
{
    double focal = ui.lensFocalLengthSpinBox->value();
    int sensId = ui.lensNominalSensorComboBox->currentIndex();
    SensorPreset *preset = &(sensorPresets[sensId]);
    double sensorHor = preset->imagerW;
    double angle = 2.0 * atan2(sensorHor / 2.0, focal);
    setNewValue(ui.lensAOVSpinBox, corecvs::radToDeg(angle));
    sensorHor = ui.horizontalSizeSpinBox->value();
    angle = 2.0 * atan2(sensorHor / 2.0, focal);
    setNewValue(ui.sensorAOVSpinBox, corecvs::radToDeg(angle));
}
void CameraCalculatorWidget::lensNominalAngleChanged () [slot]
Definition at line 225 of file cameraCalculatorWidget.cpp.
References corecvs::degToRad(), SensorPreset::imagerW, sensorPresets, setNewValue(), and ui.
Referenced by CameraCalculatorWidget().
{
    int sensId = ui.lensNominalSensorComboBox->currentIndex();
    SensorPreset *preset = &(sensorPresets[sensId]);
    double sensorHor = preset->imagerW;
    double tana2 = tan(corecvs::degToRad((double)(ui.lensAOVSpinBox->value()) / 2.0));
    double focal = (sensorHor / 2.0) / tana2;
    setNewValue(ui.lensFocalLengthSpinBox, focal);
}
void CameraCalculatorWidget::lensPresetChanged () [slot]
Block corresponding to lens.
Definition at line 200 of file cameraCalculatorWidget.cpp.
References LensPreset::focal, lensPersets, LensPreset::matrixPreset, startTimer(), and ui.
Referenced by CameraCalculatorWidget().
{
    int id = ui.lensPresetComboBox->currentIndex();
    LensPreset *preset = &(lensPersets[id]);
    ui.lensFocalLengthSpinBox->setValue(preset->focal);
    startTimer(ui.lensFocalLengthSpinBox);
    ui.lensNominalSensorComboBox->setCurrentIndex(preset->matrixPreset);
}
void CameraCalculatorWidget::lensRealAngleChanged () [slot]
Definition at line 236 of file cameraCalculatorWidget.cpp.
References corecvs::degToRad(), setDisparity(), setNewValue(), and ui.
Referenced by CameraCalculatorWidget().
{
    double sensorHor = ui.horizontalSizeSpinBox->value();
    double tana2 = tan(corecvs::degToRad((double)(ui.lensAOVSpinBox->value()) / 2.0));
    double focal = (sensorHor / 2.0) / tana2;
    setNewValue(ui.lensFocalLengthSpinBox, focal);
    setDisparity();
}
void CameraCalculatorWidget::objectDistanceChanged () [slot]
Definition at line 247 of file cameraCalculatorWidget.cpp.
References getPixelWidth(), setNewValue(), ui, and updateStereoStats().
Referenced by CameraCalculatorWidget().
{
    double distance   = ui.objectDistanceSpinBox->value();
    double objectSize = ui.objectSizeSpinBox->value();
    double focal      = ui.lensFocalLengthSpinBox->value();
    double sizeOnSensor = (objectSize / distance) * focal;
    double sizeInPx = sizeOnSensor / getPixelWidth();
    setNewValue(ui.objectPixelSizeSpinBox, sizeInPx);
    updateStereoStats();
}
void CameraCalculatorWidget::objectPxSizeChanged () [slot]
Definition at line 274 of file cameraCalculatorWidget.cpp.
References getPixelWidth(), setNewValue(), and ui.
Referenced by CameraCalculatorWidget().
{
    double distance     = ui.objectDistanceSpinBox->value();
    double objectPxSize = ui.objectSizeSpinBox->value();
    double focal        = ui.lensFocalLengthSpinBox->value();
    double sizeOnSensor = objectPxSize * getPixelWidth();
    double objectSize = sizeOnSensor / focal * distance;
    setNewValue(ui.objectSizeSpinBox, objectSize);
}
void CameraCalculatorWidget::objectSizeChanged () [slot]
Definition at line 261 of file cameraCalculatorWidget.cpp.
References getPixelWidth(), setNewValue(), and ui.
Referenced by CameraCalculatorWidget().
{
    double distance   = ui.objectDistanceSpinBox->value();
    double objectSize = ui.objectSizeSpinBox->value();
    double focal      = ui.lensFocalLengthSpinBox->value();
    double sizeOnSensor = (objectSize / distance) * focal;
    double sizeInPx = sizeOnSensor / getPixelWidth();
    setNewValue(ui.objectPixelSizeSpinBox, sizeInPx);
}
void CameraCalculatorWidget::resolutionChanged () [slot]
Definition at line 143 of file cameraCalculatorWidget.cpp.
References setDisparity(), startTimer(), and ui.
Referenced by CameraCalculatorWidget().
{
    if (ui.aspectAutoCheckBox->isChecked())
    {
        ui.aspectSpinBox->setValue((double)ui.xResolutionSpinBox->value() / ui.yResolutionSpinBox->value());
        startTimer(ui.aspectSpinBox);
    }
    setDisparity();
}
void CameraCalculatorWidget::sensorDiagonalChanged () [slot]
Definition at line 174 of file cameraCalculatorWidget.cpp.
References setNewValue(), and ui.
Referenced by aspectChanged(), and CameraCalculatorWidget().
{
    double const diagonal = ui.diagonalSizeSpinBox->value();
    double const ctg = ui.aspectSpinBox->value();
    double const sin = 1 / sqrt(1 + ctg * ctg);
    double const cos = ctg / sqrt(1 + ctg * ctg);
    setNewValue(ui.horizontalSizeSpinBox, diagonal * cos);
    setNewValue(ui.verticalSizeSpinBox, diagonal * sin);
}
void CameraCalculatorWidget::sensorHorizontalChanged () [slot]
Definition at line 154 of file cameraCalculatorWidget.cpp.
References setNewValue(), ui, and updateSensorStats().
Referenced by CameraCalculatorWidget().
{
    double horSize = ui.horizontalSizeSpinBox->value();
    double vertSize = horSize / ui.aspectSpinBox->value();
    setNewValue(ui.verticalSizeSpinBox,vertSize);
    double diagSize = sqrt(horSize * horSize + vertSize * vertSize);
    setNewValue(ui.diagonalSizeSpinBox,diagSize);
    updateSensorStats();
}
void CameraCalculatorWidget::sensorPresetChanged () [slot]
Block corresponding to sensor.
Definition at line 131 of file cameraCalculatorWidget.cpp.
References SensorPreset::imagerDiag, SensorPreset::imagerH, SensorPreset::imagerW, sensorPresets, setNewValue(), ui, and updateSensorStats().
Referenced by CameraCalculatorWidget().
{
    int id = ui.sensorPresetComboBox->currentIndex();
    SensorPreset *preset = &(sensorPresets[id]);
    setNewValue(ui.horizontalSizeSpinBox, preset->imagerW);
    setNewValue(ui.verticalSizeSpinBox  , preset->imagerH);
    setNewValue(ui.diagonalSizeSpinBox  , preset->imagerDiag);
    setNewValue(ui.aspectSpinBox        , (double)preset->imagerH / preset->imagerW);
    updateSensorStats();
}
void CameraCalculatorWidget::sensorVerticalChanged () [slot]
Definition at line 164 of file cameraCalculatorWidget.cpp.
References setNewValue(), ui, and updateSensorStats().
Referenced by CameraCalculatorWidget().
{
    double vertSize = ui.verticalSizeSpinBox->value();
    double horSize = vertSize * ui.aspectSpinBox->value();
    setNewValue(ui.horizontalSizeSpinBox,horSize);
    double diagSize = sqrt(horSize * horSize + vertSize * vertSize);
    setNewValue(ui.diagonalSizeSpinBox,diagSize);
    updateSensorStats();
}
void CameraCalculatorWidget::setColor (QDoubleSpinBox * changedValueBox, int timeoutNum) [private, slot]
Definition at line 360 of file cameraCalculatorWidget.cpp.
Referenced by startTimer().
{
    if (timeoutNum > 6)
    {
        return;
    }
    Qt::GlobalColor color = (timeoutNum % 2 == 1) ? Qt::red : Qt::black;
    QPalette palette = changedValueBox->palette();
    palette.setColor(QPalette::Text, color);
    changedValueBox->setPalette(palette);
}
void CameraCalculatorWidget::setDisparity () [private, slot]
Definition at line 380 of file cameraCalculatorWidget.cpp.
References setNewValue(), and ui.
Referenced by CameraCalculatorWidget(), lensRealAngleChanged(), and resolutionChanged().
{
    double const pixelSize = atan(ui.sensorAOVSpinBox->value()) * 2.0 / ui.xResolutionSpinBox->value();
    double const baseline = ui.baseLineSpinBox->value();
    setNewValue(ui.disparitySpinBox, (sqrt(pixelSize * pixelSize + 4 * pixelSize * baseline) - pixelSize) * 0.5);
}
void CameraCalculatorWidget::setNewValue (QDoubleSpinBox * box, double value) [private]
Definition at line 121 of file cameraCalculatorWidget.cpp.
References setValueBlocking(), and startTimer().
Referenced by lensFocalChanged(), lensNominalAngleChanged(), lensRealAngleChanged(), objectDistanceChanged(), objectPxSizeChanged(), objectSizeChanged(), sensorDiagonalChanged(), sensorHorizontalChanged(), sensorPresetChanged(), sensorVerticalChanged(), and setDisparity().
{
    setValueBlocking(box, value);
    startTimer(box);
}
void CameraCalculatorWidget::setValueBlocking (QDoubleSpinBox * box, double value) [static, private]
Definition at line 114 of file cameraCalculatorWidget.cpp.
Referenced by setNewValue().
{
    bool wasBlocked = box->blockSignals(true);
    box->setValue(value);
    box->blockSignals(wasBlocked);
}
void CameraCalculatorWidget::startTimer (QDoubleSpinBox * spinBox) [private]
Definition at line 372 of file cameraCalculatorWidget.cpp.
References mTimers, and setColor().
Referenced by lensPresetChanged(), resolutionChanged(), and setNewValue().
{
    ColorTimer *timer = new ColorTimer(spinBox);
    connect(timer, SIGNAL(colorTimeout(QDoubleSpinBox*, int)), this, SLOT(setColor(QDoubleSpinBox*, int)));
    timer->start(150);
    mTimers.push_back(timer);
}
void CameraCalculatorWidget::stereoAlgorithPrecisionChanged () [slot]
Definition at line 294 of file cameraCalculatorWidget.cpp.
References updateStereoStats().
Referenced by CameraCalculatorWidget().
{
    qDebug() << "CameraCalculatorWidget::stereoAlgorithPrecisionChanged called";
    updateStereoStats();
}
void CameraCalculatorWidget::stereoBaseLineChanged () [slot]
Definition at line 288 of file cameraCalculatorWidget.cpp.
References updateStereoStats().
Referenced by CameraCalculatorWidget().
{
    qDebug() << "CameraCalculatorWidget::stereoBaseLineChanged called";
    updateStereoStats();
}
void CameraCalculatorWidget::updateLensStats (void) [private]
void CameraCalculatorWidget::updateSensorStats (void) [private]
Definition at line 301 of file cameraCalculatorWidget.cpp.
References getPixelHeight(), getPixelWidth(), and ui.
Referenced by sensorHorizontalChanged(), sensorPresetChanged(), and sensorVerticalChanged().
{
    QString sensorStats;
    double sensorAreaSize = ui.verticalSizeSpinBox->value() * ui.horizontalSizeSpinBox->value();
    sensorStats += QString("Sensor Area: %1 mm^2\n").arg(sensorAreaSize);
    sensorStats += QString("Pixel Width: %1 mm\n").arg(getPixelWidth());
    sensorStats += QString("Pixel Height: %1 mm\n").arg(getPixelHeight());
    ui.sensorInfoLabel->setText(sensorStats);
}
void CameraCalculatorWidget::updateStereoStats (void) [private]
Definition at line 314 of file cameraCalculatorWidget.cpp.
References getAlgorithmPrecision(), getPixelWidth(), and ui.
Referenced by objectDistanceChanged(), stereoAlgorithPrecisionChanged(), and stereoBaseLineChanged().
{
    double distance = ui.objectDistanceSpinBox->value();
    double baseline = ui.baseLineSpinBox->value();
    double precision = getAlgorithmPrecision();
    double pixelSize = getPixelWidth();
    double zPrec = (baseline / ((baseline / distance) - precision * pixelSize)) - distance;
    QString stereoStats;
    stereoStats += QString("Z precision: %1 mm\n").arg(zPrec);
    ui.stereoInfoLabel->setText(stereoStats);
}
Member Data Documentation
LensPreset CameraCalculatorWidget::lensPersets [static]
Initial value:
{
        {"Kowa LM 6NCM", 6.0, 10},
        {"NoName 6mm 1/2\" F1.4 Manual Iris", 6.0, 10},
        {"NoName black 1/2\" 25mm", 25.0 , 10},
        {"PRO-18M1050MP3IR (wide)", 10.0 , 11},
        {"PRO-18M1050MP3IR (tele)", 50.0 , 11},
        {"Guess C600"             ,  5.40, 32},
        {"Guess 1920x1080"        , 14.76, 33},
}
Definition at line 31 of file cameraCalculatorWidget.h.
Referenced by CameraCalculatorWidget(), and lensPresetChanged().
const int CameraCalculatorWidget::lensPresetsSize = 7 [static]
Definition at line 32 of file cameraCalculatorWidget.h.
Referenced by CameraCalculatorWidget().
std::vector<ColorTimer *> CameraCalculatorWidget::mTimers [private]
Definition at line 76 of file cameraCalculatorWidget.h.
Referenced by startTimer(), and ~CameraCalculatorWidget().
SensorPreset CameraCalculatorWidget::sensorPresets [static]
Definition at line 28 of file cameraCalculatorWidget.h.
Referenced by CameraCalculatorWidget(), lensFocalChanged(), lensNominalAngleChanged(), and sensorPresetChanged().
const int CameraCalculatorWidget::sensorPresetsSize = 34 [static]
Definition at line 29 of file cameraCalculatorWidget.h.
Referenced by CameraCalculatorWidget().
Ui::CameraCalculatorWidgetClass CameraCalculatorWidget::ui [private]
Definition at line 64 of file cameraCalculatorWidget.h.
Referenced by aspectAutoChanged(), CameraCalculatorWidget(), getAlgorithmPrecision(), getPixelHeight(), getPixelWidth(), lensFocalChanged(), lensNominalAngleChanged(), lensPresetChanged(), lensRealAngleChanged(), objectDistanceChanged(), objectPxSizeChanged(), objectSizeChanged(), resolutionChanged(), sensorDiagonalChanged(), sensorHorizontalChanged(), sensorPresetChanged(), sensorVerticalChanged(), setDisparity(), updateSensorStats(), and updateStereoStats().
The documentation for this class was generated from the following files:
utils/camcalc/cameraCalculatorWidget.h
utils/camcalc/cameraCalculatorWidget.cpp