DeepView: Transform3DSelector Class Reference
Transform3DSelector Class Reference
#include <transform3DSelector.h>
Public Slots
void parametersChangedSlot (void)
Signals
void parametersChanged (void)
Public Member Functions
Transform3DSelector (QWidget *parent=0)
~Transform3DSelector ()
Matrix44 getTransform ()
template<class Visitor >
void accept (Visitor &visitor)
Private Attributes
Ui::Transform3DSelectorClass ui
Detailed Description
Definition at line 12 of file transform3DSelector.h.
Constructor & Destructor Documentation
Transform3DSelector::Transform3DSelector (QWidget * parent = 0)
Definition at line 10 of file transform3DSelector.cpp.
References ui.
    : QWidget(parent)
{
    ui.setupUi(this);
}
Transform3DSelector::~Transform3DSelector ()
Definition at line 44 of file transform3DSelector.cpp.
{
}
Member Function Documentation
template<class Visitor > void Transform3DSelector::accept (Visitor & visitor) [inline]
Definition at line 24 of file transform3DSelector.h.
References ui.
    {
        bool scaleLocked = ui.lockScaleToolButton->isChecked();
        double rotateZ = ui.rotateZSpinBox->value();
        double rotateY = ui.rotateYSpinBox->value();
        double rotateX = ui.rotateXSpinBox->value();
        double scaleZ = ui.scaleZSpinBox->value();
        double scaleY = ui.scaleYSpinBox->value();
        double scaleX = ui.scaleXSpinBox->value();
        double shiftZ = ui.shiftZSpinBox->value();
        double shiftY = ui.shiftYSpinBox->value();
        double shiftX = ui.shiftXSpinBox->value();
        visitor.visit(scaleLocked, true, "scaleLocked");
        visitor.visit(rotateZ, 0.0, "rotateZ");
        visitor.visit(rotateY, 0.0, "rotateY");
        visitor.visit(rotateX, 0.0, "rotateX");
        visitor.visit(scaleZ, 1.0, "scaleZ");
        visitor.visit(scaleY, 1.0, "scaleY");
        visitor.visit(scaleX, 1.0, "scaleX");
        visitor.visit(shiftZ, 0.0, "shiftZ");
        visitor.visit(shiftY, 0.0, "shiftY");
        visitor.visit(shiftX, 0.0, "shiftX");
        ui.lockScaleToolButton->setChecked(scaleLocked);
        ui.rotateZSpinBox->setValue(rotateZ);
        ui.rotateYSpinBox->setValue(rotateY);
        ui.rotateXSpinBox->setValue(rotateX);
        ui.scaleZSpinBox->setValue(scaleZ);
        ui.scaleYSpinBox->setValue(scaleY);
        ui.scaleXSpinBox->setValue(scaleX);
        ui.shiftZSpinBox->setValue(shiftZ);
        ui.shiftYSpinBox->setValue(shiftY);
        ui.shiftXSpinBox->setValue(shiftX);
    }
Matrix44 Transform3DSelector::getTransform ()
Definition at line 17 of file transform3DSelector.cpp.
References corecvs::degToRad(), and ui.
Referenced by TreeSceneController::transformationChanged().
{
    bool scaleLocked = ui.lockScaleToolButton->isChecked();
    Matrix33 A =
        Matrix33::RotationZ(degToRad(ui.rotateZSpinBox->value())) *
        Matrix33::RotationY(degToRad(ui.rotateYSpinBox->value())) *
        Matrix33::RotationX(degToRad(ui.rotateXSpinBox->value())) *
        Matrix33::Scale3(Vector3dd(
            ui.scaleXSpinBox->value(),
            scaleLocked ? ui.scaleXSpinBox->value() : ui.scaleYSpinBox->value(),
            scaleLocked ? ui.scaleXSpinBox->value() : ui.scaleZSpinBox->value()
        ));
    return Matrix44(A, Vector3dd(
            ui.shiftXSpinBox->value(),
            ui.shiftYSpinBox->value(),
            ui.shiftZSpinBox->value()
    ));
}
void Transform3DSelector::parametersChanged (void) [signal]
Referenced by parametersChangedSlot().
void Transform3DSelector::parametersChangedSlot (void) [slot]
Definition at line 39 of file transform3DSelector.cpp.
References parametersChanged().
{
    emit parametersChanged();
}
Member Data Documentation
Ui::Transform3DSelectorClass Transform3DSelector::ui [private]
Definition at line 75 of file transform3DSelector.h.
Referenced by accept(), getTransform(), and Transform3DSelector().
The documentation for this class was generated from the following files:
utils/widgets/transform3DSelector.h
utils/widgets/transform3DSelector.cpp