DeepView: ContentStatistics Class Reference
ContentStatistics Class Reference
#include <contentStatistics.h>
Public Types
typedef map< string, UnitedStat > StatsMap
Public Slots
void transition (int newId, QString name)
Public Member Functions
ContentStatistics ()
virtual void reset ()
virtual void addSingleStat (string name, const SingleStat &stat)
virtual void addStatistics (Statistics &stats)
virtual int maximumCaptionLength () const
template<class StreamType >
void printStats (StreamType &stream) const
virtual void printSimple ()
virtual void printAdvanced ()
virtual void printWiki ()
Public Attributes
int currentId
QString name
PreciseTimer timer
StatsMap sumValues
vector< OrderFilter * > mOrderFilters
Static Public Attributes
static const int EMPTY_ID = -1
Detailed Description
Definition at line 19 of file contentStatistics.h.
Member Typedef Documentation
typedef map<string, UnitedStat> corecvs::BaseTimeStatisticsCollector::StatsMap [inherited]
Definition at line 134 of file calculationStats.h.
Constructor & Destructor Documentation
ContentStatistics::ContentStatistics () [inline]
Definition at line 30 of file contentStatistics.h.
                        :
        currentId(EMPTY_ID)
    {
    }
Member Function Documentation
virtual void corecvs::BaseTimeStatisticsCollector::addSingleStat (string name, const SingleStat & stat) [inline, virtual, inherited]
Definition at line 178 of file calculationStats.h.
References corecvs::UnitedStat::addValue(), and corecvs::BaseTimeStatisticsCollector::sumValues.
Referenced by corecvs::BaseTimeStatisticsCollector::addStatistics(), and transition().
    {
        UnitedStat unitedStat;
        //typename map<string, UnitedStat>::iterator uit;
        map<string, UnitedStat>::iterator uit;
        uit = sumValues.find(name);
        if (uit != sumValues.end())
        {
           unitedStat = uit->second;
        }
        unitedStat.addValue(stat);
        sumValues[name] = unitedStat;
    }
virtual void corecvs::BaseTimeStatisticsCollector::addStatistics (Statistics & stats) [inline, virtual, inherited]
Definition at line 194 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::addSingleStat(), and corecvs::Statistics::values.
Referenced by StatisticsDialog::addStats().
    {
        /* New style */
        map<string, SingleStat>::iterator it;
        for (it = stats.values.begin(); it != stats.values.end(); ++it )
        {
            string name = it->first;
            SingleStat stat = it->second;
            addSingleStat(name, stat);
        }
    }
virtual int corecvs::BaseTimeStatisticsCollector::maximumCaptionLength () const [inline, virtual, inherited]
Definition at line 206 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::sumValues.
Referenced by corecvs::BaseTimeStatisticsCollector::printStats().
    {
        //typename StatsMap::const_iterator uit;
        StatsMap::const_iterator uit;
        int maxCaptionLen = 0;
        for (uit = this->sumValues.begin(); uit != this->sumValues.end(); ++uit )
        {
            int len = (int)uit->first.length();
            if (len > maxCaptionLen)
            {
                maxCaptionLen = len;
            }
        }
        return maxCaptionLen;
    }
virtual void corecvs::BaseTimeStatisticsCollector::printAdvanced () [inline, virtual, inherited]
Definition at line 325 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::printStats().
    {
        printf("=============================================================\n");
        AdvancedPrinter printer;
        printStats(printer);
        printf("=============================================================\n");
    }
virtual void corecvs::BaseTimeStatisticsCollector::printSimple () [inline, virtual, inherited]
Definition at line 294 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::printStats().
    {
        printf("=============================================================\n");
        SimplePrinter printer;
        printStats(printer);
        printf("=============================================================\n");
    }
template<class StreamType > void corecvs::BaseTimeStatisticsCollector::printStats (StreamType & stream) const [inline, inherited]
Definition at line 224 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::OrderFilter::filter(), corecvs::BaseTimeStatisticsCollector::maximumCaptionLength(), corecvs::BaseTimeStatisticsCollector::mOrderFilters, and corecvs::BaseTimeStatisticsCollector::sumValues.
Referenced by corecvs::BaseTimeStatisticsCollector::printAdvanced(), corecvs::BaseTimeStatisticsCollector::printSimple(), and corecvs::BaseTimeStatisticsCollector::printWiki().
    {
        typename StatsMap::const_iterator uit;
        /* Get caption width */
        int maxCaptionLen = maximumCaptionLength();
        /* Flags */
        int size = this->sumValues.size();
        bool *isPrinted = new bool[size];
        for (int i = 0; i < size; i++)
        {
            isPrinted[i] = false;
        }
        int printCount = 0;
        /* First show all filters */
        //printf("Totaly we have %d filters\n", mOrderFilters.size());
        for (unsigned i = 0; i < mOrderFilters.size(); i++)
        {
            OrderFilter *filter = mOrderFilters[i];
            int j = 0;
            for (uit = this->sumValues.begin(); uit != this->sumValues.end(); ++uit, j++ )
            {
                if (isPrinted[j])
                {
                    continue;
                }
                if (filter->filter(uit->first))
                {
                    isPrinted[j] = true;
                    stream.printUnitedStat(uit->first, maxCaptionLen, uit->second, printCount);
                    printCount++;
                }
            }
        }
        int j = 0;
        for (uit = this->sumValues.begin(); uit != this->sumValues.end(); ++uit, j++ )
        {
            if (isPrinted[j])
            {
                continue;
            }
            stream.printUnitedStat(uit->first, maxCaptionLen, uit->second, printCount);
            printCount++;
        }
        deletearr_safe(isPrinted);
    }
virtual void corecvs::BaseTimeStatisticsCollector::printWiki () [inline, virtual, inherited]
Definition at line 342 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::printStats().
    {
        printf("|");
/*        for (unsigned i = 0; i < Statistics::SIZE; i++)
        {
            printf("%s|", Statistics::getNames()[i]);
        }*/
        printf("\n");
        printf("====================Paste this to  wiki======================\n");
        const char *withsse = "";
#ifdef WITH_SSE
        withsse = "!y.png!";
#endif
        const char *withtbb = "";
#ifdef WITH_TBB
        withtbb = "!y.png!";
#endif
        const char *osId = "!l.png!";
#ifdef Q_OS_WIN
        osId = "!w.png!";
#endif
#ifdef Q_OS_MAC
        osId = "!a.png!"
#endif
        const char *is64bit = "!3.png!";
#ifdef __x86_64
    is64bit = "!6.png!";
#endif
        const char *compiler = "unkn";
#if defined (__GNUC__) && defined (__GNUC_MINOR__)
#define GCC_XSTR(value) GCC_STR(value)
#define GCC_STR(value) #value
        compiler = "g" GCC_XSTR(__GNUC__) "." GCC_XSTR(__GNUC_MINOR__);
#undef GCC_STR
#undef GCC_XSTR
#elif defined (__clang__)
        compiler = "clan";
#elif defined (_MSC_VER)
        compiler = "msvc";
#elif defined (__MINGW32__)
        compiler = "mgw";
#elif defined (__INTEL_COMPILER)
        compiler = "icc";
#endif
               //       OS  bits comp tbb  sse
        printf("|%-15s|%-7s|%-7s|%-4s|%-7s|%-7s|", " ", osId, is64bit, compiler, withtbb, withsse);
        WikiPrinter printer;
        printStats(printer);
        printf("\n");
        printf("=============================================================\n");
    }
virtual void corecvs::BaseTimeStatisticsCollector::reset (void) [inline, virtual, inherited]
Definition at line 173 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::sumValues.
Referenced by StatisticsDialog::reset().
    {
        sumValues.clear();
    }
void ContentStatistics::transition (int newId, QString name) [inline, slot]
Definition at line 38 of file contentStatistics.h.
References corecvs::BaseTimeStatisticsCollector::addSingleStat(), currentId, EMPTY_ID, name, timer, and corecvs::PreciseTimer::usecsToNow().
    {
        qDebug() << "New content: " << newId  << " " << name;
        /* Could be moved comewhere */
        QString postfix = "";
        /* If no name use old style H&M*/
        if (name.isEmpty())
        {
            if (currentId != EMPTY_ID)
            {
                if (currentId >= 1000 && currentId < 2000)
                {
                    postfix = " (details)";
                    currentId = currentId - 1000;
                }
                switch(currentId) {
                    case    0: name = "Dress 999 RUR";                    break;
                    case    1: name = "Trousers (dark red) 1499 RUR";     break;
                    case    2: name = "Shoes (dark red) 1999 RUR";        break;
                    case    3: name = "Sweater (light red) 1299 RUR";     break;
                    case    4: name = "Dress (violet & white) 1499 RUR";  break;
                    case    5: name = "Boots (grey) 1499 RUR";            break;
                    case    6: name = "Leggins (violet & white) 499 RUR"; break;
                    case    7: name = "Boots (brown) 1999 RUR";           break;
                    case    8: name = "Trousers (black) 1499 RUR";        break;
                    case    9: name = "Jeans Skinny";                     break;
                    case   10: name = "Earrings 399 RUR";                 break;
                    case   11: name = "Shoes (black) 1499 RUR";           break;
                    case   12: name = "Gloves (black)";                   break;
                    case   13: name = "Collar 2499 RUR";                  break;
                    case 2000: name = "Where to buy map";                 break;
                    case 1000000: name = "Intro Movie";                   break;
                    default: name = "OTHER";                            break;
                }
                name += postfix;
            }
        }
        addSingleStat(name.toStdString(), SingleStat(timer.usecsToNow()));
        currentId = newId;
        timer = PreciseTimer::currentTime();
    }
Member Data Documentation
int ContentStatistics::currentId
Definition at line 25 of file contentStatistics.h.
Referenced by transition().
const int ContentStatistics::EMPTY_ID = -1 [static]
Definition at line 24 of file contentStatistics.h.
Referenced by transition().
vector<OrderFilter *> corecvs::BaseTimeStatisticsCollector::mOrderFilters [inherited]
Definition at line 166 of file calculationStats.h.
Referenced by corecvs::BaseTimeStatisticsCollector::printStats().
QString ContentStatistics::name
Definition at line 26 of file contentStatistics.h.
Referenced by transition().
StatsMap corecvs::BaseTimeStatisticsCollector::sumValues [inherited]
Definition at line 136 of file calculationStats.h.
Referenced by corecvs::BaseTimeStatisticsCollector::addSingleStat(), corecvs::BaseTimeStatisticsCollector::maximumCaptionLength(), corecvs::BaseTimeStatisticsCollector::printStats(), and corecvs::BaseTimeStatisticsCollector::reset().
PreciseTimer ContentStatistics::timer
Definition at line 28 of file contentStatistics.h.
Referenced by transition().
The documentation for this class was generated from the following file:
utils/statistics/contentStatistics.h