DeepView: TestbedMainWindow Class Reference
TestbedMainWindow Class Reference
#include <testbedMainWindow.h>
Public Slots
void loadImage ()
void pointSelected (int toolID, QPoint point)
void updateViewImage (void)
void toggleMask (void)
void resetMask (void)
void undoMask (void)
void maskHue (int hue1, int hue2)
void maskTolerance (QPoint point)
void maskTolerance1 (QPoint point)
void recursiveTolerance (RGBColor startColor, int tolerance, int x, int y)
Public Member Functions
TestbedMainWindow (QWidget *parent=0)
~TestbedMainWindow ()
void closeEvent (QCloseEvent *event)
void keyPressEvent (QKeyEvent *event)
Public Attributes
RGB24Buffer * mImage
G8Buffer * mMask
bool mMaskChange
deque< G8Buffer * > mUndoList
Private Member Functions
void connectActions ()
Private Attributes
Ui::TestbedMainWindowClass * mUi
AdvancedImageWidget * mImageWidget
Detailed Description
Definition at line 13 of file testbedMainWindow.h.
Constructor & Destructor Documentation
TestbedMainWindow::TestbedMainWindow (QWidget * parent = 0)
Definition at line 10 of file testbedMainWindow.cpp.
References AdvancedImageWidget::addPointTool(), connectActions(), mImageWidget, and mUi.
    : QMainWindow(parent)
    , mUi(new Ui::TestbedMainWindowClass)
    , mImageWidget(NULL)
    , mImage(NULL)
    , mMask(NULL)
{
    mUi->setupUi(this);
    mImageWidget = new AdvancedImageWidget(this);
    setCentralWidget(mImageWidget);
    mImageWidget->addPointTool(0, QString("Select point"), QIcon(":/new/prefix1/lightning.png"));
    showMaximized();
    setWindowTitle("Testbed");
    connectActions();
}
TestbedMainWindow::~TestbedMainWindow ()
Definition at line 290 of file testbedMainWindow.cpp.
References mImageWidget, and mUi.
{
    delete_safe(mImageWidget);
    delete_safe(mUi);
}
Member Function Documentation
void TestbedMainWindow::closeEvent (QCloseEvent * event)
Definition at line 28 of file testbedMainWindow.cpp.
{
    Q_UNUSED(event)
    qApp->quit();
}
void TestbedMainWindow::connectActions () [private]
Definition at line 35 of file testbedMainWindow.cpp.
References loadImage(), mImageWidget, mUi, pointSelected(), resetMask(), toggleMask(), undoMask(), and updateViewImage().
Referenced by TestbedMainWindow().
{
    connect(mUi->actionOpen, SIGNAL(triggered()), this, SLOT(loadImage()));
    connect(mImageWidget,    SIGNAL(newPointSelected(int, QPoint)), this, SLOT(pointSelected(int, QPoint)));
    connect(mUi->actionShowMask,  SIGNAL(toggled(bool)), this, SLOT(toggleMask()));
    connect(mUi->actionResetMask, SIGNAL(triggered(bool)), this, SLOT(resetMask()));
    connect(mUi->actionUndoMask,  SIGNAL(triggered(bool)), this, SLOT(undoMask()));
    connect(mUi->maskAlphaSpinBox, SIGNAL(valueChanged (int)), this, SLOT(updateViewImage()));
    connect(mUi->maskColorWidget,  SIGNAL(valueChanged()), this, SLOT(updateViewImage()));
    connect(mUi->showEdgeCheckBox, SIGNAL(toggled(bool)), this, SLOT(updateViewImage()));
}
void TestbedMainWindow::keyPressEvent (QKeyEvent * event)
Definition at line 52 of file testbedMainWindow.cpp.
{
    if (event->modifiers() == Qt::AltModifier && event->key() == Qt::Key_X)
    {
        close();
    }
    event->ignore();
}
void TestbedMainWindow::loadImage (void) [slot]
Definition at line 62 of file testbedMainWindow.cpp.
References drawCircle(), corecvs::AbstractBuffer< ElementType, IndexType >::getSize(), corecvs::AbstractBufferParams::h, mImage, mMask, QTFileLoader::RGB24BufferFromQImage(), updateViewImage(), and corecvs::AbstractBufferParams::w.
Referenced by connectActions().
{
    QString filename = QFileDialog::getOpenFileName(
        this,
        "Choose an file name",
        ".",
        "Text (*.bmp *.jpg *.png *.gif)"
    );
    QImage *qImage = new QImage(filename);
    if (qImage == NULL) {
        return;
    }
    delete_safe(mImage);
    delete_safe(mMask);
    mImage = QTFileLoader::RGB24BufferFromQImage(qImage);
    mMask = new G8Buffer(mImage->getSize());
    AbstractPainter<G8Buffer>(mMask).drawCircle(mImage->w / 2, mImage->h / 2, (!mImage->getSize()) / 4, 255);
    delete_safe(qImage);
    updateViewImage();
}
void TestbedMainWindow::maskHue (int hue1, int hue2) [slot]
Definition at line 164 of file testbedMainWindow.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBufferParams::h, mImage, mMask, and corecvs::AbstractBufferParams::w.
Referenced by pointSelected().
{
    for (int i = 0; i < mImage->h; i++)
    {
       for (int j = 0; j < mImage->w; j++)
       {
           bool result = false;
           int hue = mImage->element(i,j).hue();
           if (hue1 <= hue2)
           {
               if (hue > hue1 && hue < hue2 )
                   result = true;
           } else {
               if (hue < hue2 || hue > hue1 )
                   result = true;
           }
           mMask->element(i,j) = result;
       }
    }
}
void TestbedMainWindow::maskTolerance (QPoint point) [slot]
Definition at line 240 of file testbedMainWindow.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord(), mImage, mMask, mUi, and recursiveTolerance().
Referenced by pointSelected().
{
    int x = point.x();
    int y = point.y();
    if (!mMask->isValidCoord(y,x))
        return;
    RGBColor currentColor = mImage->element(y,x);
    recursiveTolerance(currentColor, mUi->toleranceSpinBox->value(), x, y);
}
void TestbedMainWindow::maskTolerance1 (QPoint point) [slot]
Definition at line 252 of file testbedMainWindow.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord(), mImage, mMask, and mUi.
Referenced by pointSelected().
{
    int x = point.x();
    int y = point.y();
    if (!mMask->isValidCoord(y,x))
        return;
    RGBColor currentColor = mImage->element(y,x);
    TolerancePredicate predicate(mMask, currentColor, mUi->toleranceSpinBox->value());
    AbstractPainter<RGB24Buffer> painter(mImage);
    painter.floodFill(x,y, predicate);
}
void TestbedMainWindow::pointSelected (int toolID, QPoint point) [slot]
Definition at line 266 of file testbedMainWindow.cpp.
References maskHue(), maskTolerance(), maskTolerance1(), mMask, mUi, and updateViewImage().
Referenced by connectActions().
{
    qDebug() << "Point Selected" << point;
    mUndoList.push_back(new G8Buffer(mMask));
    if (mUndoList.size() > 20) {
        delete_safe(mUndoList.front());
        mUndoList.pop_front();
    }
    switch (mUi->maskComboBox->currentIndex())
    {
        case 0:
            maskHue(mUi->hue1SpinBox->value(), mUi->hue2SpinBox->value());
            break;
        case 1:
            maskTolerance(point);
            break;
        case 2:
            maskTolerance1(point);
            break;
    }
    updateViewImage();
}
void TestbedMainWindow::recursiveTolerance (RGBColor startColor, int tolerance, int x, int y) [slot]
Definition at line 217 of file testbedMainWindow.cpp.
References corecvs::RGBColor::b(), corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::RGBColor::g(), corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord(), mImage, mMask, and corecvs::RGBColor::r().
Referenced by maskTolerance().
{
    if (!mMask->isValidCoord(y,x))
        return;
    if (mMask->element(y,x))
        return;
    RGBColor currentColor = mImage->element(y,x);
    int r = (int)currentColor.r() - (int)startColor.r();
    int g = (int)currentColor.g() - (int)startColor.g();
    int b = (int)currentColor.b() - (int)startColor.b();
    int sum = abs(r) + abs(g) + abs(b);
    if (sum > tolerance)
        return;
    mMask->element(y,x) = 255;
    recursiveTolerance(startColor, tolerance, x - 1, y    );
    recursiveTolerance(startColor, tolerance, x + 1, y    );
    recursiveTolerance(startColor, tolerance, x    , y + 1);
    recursiveTolerance(startColor, tolerance, x    , y - 1);
}
void TestbedMainWindow::resetMask (void) [slot]
Definition at line 89 of file testbedMainWindow.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::getSize(), mImage, mMask, mUndoList, and updateViewImage().
Referenced by connectActions().
{
    mUndoList.push_back(mMask);
    if (mUndoList.size() > 20) {
        delete_safe(mUndoList.front());
        mUndoList.pop_front();
    }
    mMask = new G8Buffer(mImage->getSize());
    updateViewImage();
}
void TestbedMainWindow::toggleMask (void) [slot]
Definition at line 84 of file testbedMainWindow.cpp.
References updateViewImage().
Referenced by connectActions().
{
    updateViewImage();
}
void TestbedMainWindow::undoMask (void) [slot]
Definition at line 101 of file testbedMainWindow.cpp.
References mMask, mUndoList, and updateViewImage().
Referenced by connectActions().
{
    if (mUndoList.empty()) {
        return;
    }
    delete_safe(mMask);
    mMask = mUndoList.back();
    mUndoList.pop_back();
    updateViewImage();
}
void TestbedMainWindow::updateViewImage (void) [slot]
Definition at line 115 of file testbedMainWindow.cpp.
References corecvs::RGBColor::b(), corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::RGBColor::g(), corecvs::AbstractBufferParams::h, corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord(), mImage, mImageWidget, mMask, mUi, corecvs::RGBColor::r(), AdvancedImageWidget::setImage(), and corecvs::AbstractBufferParams::w.
Referenced by connectActions(), loadImage(), pointSelected(), resetMask(), toggleMask(), and undoMask().
{
    RGB24Buffer *toDraw = new RGB24Buffer(mImage);
    RGBColor maskColor = mUi->maskColorWidget->getColor();
    double alpha = (mUi->maskAlphaSpinBox->value()) / 100.0;
    if (mUi->actionShowMask->isChecked())
    {
        for (int i = 0; i < toDraw->h; i++)
        {
            for (int j = 0; j < toDraw->w; j++)
            {
                bool hasmask = false;
                bool hasnomask = false;
                /* so far no optimization here */
                if (mUi->showEdgeCheckBox->isChecked()) {
                    for (int dx = -1; dx <= 1; dx++)
                    {
                        for (int dy = -1; dy <= 1; dy++)
{
                            if (!mMask->isValidCoord(i + dy, j + dx))
                                continue;
                            if (mMask->element(i + dy, j + dx)) {
                                hasmask = true;
                            } else {
                                hasnomask = true;
                            }
                        }
                    }
                }
                if (mMask->element(i,j)) {
                    if (hasmask && hasnomask) {
                        toDraw->element(i,j) = maskColor;
                    } else {
                        toDraw->element(i,j).r() += (maskColor.r() - toDraw->element(i,j).r()) * alpha;
                        toDraw->element(i,j).g() += (maskColor.g() - toDraw->element(i,j).g()) * alpha;
                        toDraw->element(i,j).b() += (maskColor.b() - toDraw->element(i,j).b()) * alpha;
                    }
                }
            }
        }
    }
    QImage *qImage = new RGB24Image(toDraw);
    mImageWidget->setImage(QSharedPointer<QImage>(qImage));
    delete_safe(toDraw);
}
Member Data Documentation
RGB24Buffer* TestbedMainWindow::mImage
Definition at line 48 of file testbedMainWindow.h.
Referenced by loadImage(), maskHue(), maskTolerance(), maskTolerance1(), recursiveTolerance(), resetMask(), and updateViewImage().
AdvancedImageWidget* TestbedMainWindow::mImageWidget [private]
Definition at line 28 of file testbedMainWindow.h.
Referenced by connectActions(), TestbedMainWindow(), updateViewImage(), and ~TestbedMainWindow().
G8Buffer* TestbedMainWindow::mMask
Definition at line 49 of file testbedMainWindow.h.
Referenced by loadImage(), maskHue(), maskTolerance(), maskTolerance1(), pointSelected(), recursiveTolerance(), resetMask(), undoMask(), and updateViewImage().
bool TestbedMainWindow::mMaskChange
Definition at line 50 of file testbedMainWindow.h.
Ui::TestbedMainWindowClass* TestbedMainWindow::mUi [private]
Definition at line 26 of file testbedMainWindow.h.
Referenced by connectActions(), maskTolerance(), maskTolerance1(), pointSelected(), TestbedMainWindow(), updateViewImage(), and ~TestbedMainWindow().
deque<G8Buffer *> TestbedMainWindow::mUndoList
Definition at line 51 of file testbedMainWindow.h.
Referenced by resetMask(), and undoMask().
The documentation for this class was generated from the following files:
applications/testbed/testbedMainWindow.h
applications/testbed/testbedMainWindow.cpp