DeepView: TreeSceneModel Class Reference
TreeSceneModel Class Reference
#include <treeSceneController.h>
Public Types
enum ColumnNameing { NAME_COLUMN, FLAG_COLUMN, PARAMETER_COLUMN, MAX_COLUMN }
Public Slots
bool clicked (const QModelIndex &index)
Signals
void modelChanged ()
Public Member Functions
TreeSceneModel (QObject *parent=0)
~TreeSceneModel ()
TreeSceneController * addObject (QString name, QSharedPointer< Scene3D > object, bool visible=true)
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant data (const QModelIndex &index, int role) const
bool setData (const QModelIndex &index, const QVariant &value, int role)
int rowCount (const QModelIndex &parent) const
int columnCount (const QModelIndex &parent) const
QVariant headerData (int section, Qt::Orientation orientation, int role) const
QModelIndex index (int row, int column, const QModelIndex &parent) const
QModelIndex parent (const QModelIndex &index) const
int getRow (const QModelIndex &index) const
void packPath (QModelIndex index, QDataStream &stream) const
QModelIndex unpackPath (QDataStream &stream) const
QStringList mimeTypes () const
QMimeData * mimeData (const QModelIndexList &indexes) const
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Qt::DropActions supportedDropActions () const
Public Attributes
TreeSceneController * mTopItem
Private Member Functions
TreeSceneController * indexToScene (const QModelIndex &index) const
Static Private Attributes
static const QString MIME_TYPE = "application/x-vimouse-internal"
Detailed Description
Definition at line 103 of file treeSceneController.h.
Member Enumeration Documentation
enum TreeSceneModel::ColumnNameing
Enumerator:
NAME_COLUMN
FLAG_COLUMN
PARAMETER_COLUMN
MAX_COLUMN
Definition at line 110 of file treeSceneController.h.
                       {
        NAME_COLUMN,
        FLAG_COLUMN,
        PARAMETER_COLUMN,
        MAX_COLUMN
    };
Constructor & Destructor Documentation
TreeSceneModel::TreeSceneModel (QObject * parent = 0)
Definition at line 279 of file treeSceneController.cpp.
References mTopItem.
                                               :
    QAbstractItemModel(parent),
    mTopItem(NULL)
{
    mTopItem = new TreeSceneController(
        "root",
        QSharedPointer<CoordinateFrame>(new CoordinateFrame()),
        this,
        true);
}
TreeSceneModel::~TreeSceneModel ()
Definition at line 290 of file treeSceneController.cpp.
References mTopItem.
{
    delete_safe(mTopItem);
}
Member Function Documentation
TreeSceneController * TreeSceneModel::addObject (QString name, QSharedPointer< Scene3D > object, bool visible = true)
Definition at line 295 of file treeSceneController.cpp.
References TreeSceneController::addChildObjectRecursive(), TreeSceneController::mChildren, and mTopItem.
Referenced by CloudViewDialog::addSubObject().
{
    if (mTopItem == NULL)
    {
        return NULL;
    }
    beginInsertRows(QModelIndex(), (int)mTopItem->mChildren.size(), (int)mTopItem->mChildren.size());
    //TreeSceneController *result = mTopItem->addChildObject(name, object, visible);
    TreeSceneController *result = mTopItem->addChildObjectRecursive(name, object, this, visible);
    endInsertRows();
    return result;
}
bool TreeSceneModel::clicked (const QModelIndex & index) [slot]
Definition at line 686 of file treeSceneController.cpp.
References indexToScene(), and PARAMETER_COLUMN.
{
    if (index.column() == PARAMETER_COLUMN)
    {
        TreeSceneController *object = indexToScene(index);
        object->clicked();
    }
    return true;
}
int TreeSceneModel::columnCount (const QModelIndex & parent) const
Definition at line 464 of file treeSceneController.cpp.
References MAX_COLUMN.
{
    return MAX_COLUMN;
}
QVariant TreeSceneModel::data (const QModelIndex & index, int role) const
Definition at line 336 of file treeSceneController.cpp.
References FLAG_COLUMN, indexToScene(), TreeSceneController::mName, TreeSceneController::mObject, NAME_COLUMN, and PARAMETER_COLUMN.
{
    if (!index.isValid())
    {
        return QVariant();
    }
    TreeSceneController *scene = indexToScene(index);
    if (role == Qt::DisplayRole)
    {
        switch (index.column())
        {
        case NAME_COLUMN:
            return scene->mName;
        case FLAG_COLUMN:
            return scene->mObject->visible ? "ON" : "OFF";
        default:
            break;
        }
    } else if (role == Qt::ToolTipRole)
    {
        switch (index.column())
        {
        case NAME_COLUMN:
            return QString("The name of the object.");
        case FLAG_COLUMN:
            return QString("ON/OFF Flag");
        case PARAMETER_COLUMN:
            return QString("Parameters");
        default:
            break;
        }
    } else if ( role == Qt::CheckStateRole )
    {
        switch (index.column())
        {
            case FLAG_COLUMN:
            {
                if (scene->mObject) {
//                    qDebug("data called: returning %d", scene->mObject->visible);
                    return scene->mObject->visible ? Qt::Checked : Qt::Unchecked;
                }
            }
            default:
                break;
        }
    } else  if (role == Qt::DecorationRole)
    {
        if (index.column() == NAME_COLUMN)
        {
            if (scene->mObject->isComplexObject()) {
                return QIcon(":/new/prefix1/workspace.png");
            } else {
                return QIcon(":/new/our/our/3D.png");
            }
        }
        if (index.column() == PARAMETER_COLUMN)
        {
            return QIcon(":/new/prefix1/advanced.png");
        }
    }
    return QVariant();
}
bool TreeSceneModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent)
Definition at line 577 of file treeSceneController.cpp.
References getRow(), indexToScene(), TreeSceneController::mChildren, MIME_TYPE, TreeSceneController::mName, TreeSceneController::mObject, TreeSceneController::mParentController, mTopItem, parent(), TreeSceneController::print(), and unpackPath().
{
    if (action == Qt::IgnoreAction)
    {
        return true;
    }
    if (!data->hasFormat(MIME_TYPE))
    {
        return false;
    }
    QByteArray encodedData = data->data(MIME_TYPE);
    QDataStream stream(&encodedData, QIODevice::ReadOnly);
    QModelIndex pathIter = unpackPath(stream);
    if (pathIter == QModelIndex())
    {
        qDebug() << "Source path is root. Returning";
        return false;
    }
    /* Detaching old data */
    TreeSceneController *controller             = indexToScene(pathIter);
    QSharedPointer<Scene3D> scene               = controller->mObject;
    TreeSceneController *parentController       = controller->mParentController;
    QSharedPointer<CoordinateFrame> parentScene = parentController->mObject.staticCast<CoordinateFrame>();
    /* A Place to add new data */
    qDebug() << "Position to paste " << row << " " << column;
    TreeSceneController *targetController = indexToScene(target);
    if (targetController->mObject.isNull())
    {
        return false;
    }
    QModelIndex insertParent = target;
    if (!targetController->mObject->isComplexObject())
    {
        qDebug() << targetController->mName << " is not a frame. Going to parent";
        insertParent = parent(target);
        qDebug() << "Controller name:" << targetController->mName;
        row = getRow(target);
        qDebug() << "Getting new parent controller";
        targetController = indexToScene(insertParent);
    }
    QSharedPointer<CoordinateFrame> targetScene = targetController->mObject.staticCast<CoordinateFrame>();
    qDebug() << "Paste request to " << targetController->mName << " row=" << row << " column=" << column;
    /* Deleting link in scene */
    qDebug() << "Object to be moved:" << controller->mName;
    /* Deleting link in the controller */
    unsigned indexToDetach = 0;
    for (; indexToDetach < parentController->mChildren.size(); indexToDetach++)
    {
        if (parentController->mChildren[indexToDetach] == controller)
        {
            break;
        }
    }
    if (indexToDetach >= parentController->mChildren.size())
        return false;
    beginRemoveRows(parent(pathIter), indexToDetach, indexToDetach);
    parentController->mChildren.erase (parentController->mChildren.begin() + indexToDetach);
    for (unsigned i = 0; i < parentScene->mChildren.size(); i++)
    {
        if (parentScene->mChildren[i] == scene)
        {
            parentScene->mChildren.erase (parentScene->mChildren.begin() + i);
            break;
        }
    }
    endRemoveRows();
    /* Adding back */
    if (row == -1) {
        row = (int)targetController->mChildren.size();
    }
    qDebug() << "Adding child to:"          << targetController->mName;
    qDebug() << "Child name:" << controller->mName;
    beginInsertRows(insertParent, row, row);
    targetController->mChildren.insert(targetController->mChildren.begin() + row, controller);
    controller->mParentController = targetController;
    targetScene->mChildren.insert(targetScene->mChildren.begin() + row, scene);
    endInsertRows();
    qDebug() << "Finally tree looks like this\n" << mTopItem->print();
    return true;
}
Qt::ItemFlags TreeSceneModel::flags (const QModelIndex & index) const
Definition at line 312 of file treeSceneController.cpp.
References FLAG_COLUMN, and NAME_COLUMN.
{
    Qt::ItemFlags flags = Qt::ItemIsEnabled | Qt::ItemIsSelectable ;
    if (index.column() == FLAG_COLUMN)
    {
        flags |= Qt::ItemIsUserCheckable | Qt::ItemIsEditable;
    }
    if (index.column() == NAME_COLUMN)
    {
        flags |= Qt::ItemIsDragEnabled;
        flags |= Qt::ItemIsDropEnabled;
        flags |= Qt::ItemIsEditable;
    }
    if (index == QModelIndex())
    {
        flags |= Qt::ItemIsDropEnabled;
    }
    return flags;
}
int TreeSceneModel::getRow (const QModelIndex & index) const
Definition at line 513 of file treeSceneController.cpp.
Referenced by dropMimeData().
{
    return index.row();
}
QVariant TreeSceneModel::headerData (int section, Qt::Orientation orientation, int role) const
Definition at line 432 of file treeSceneController.cpp.
{
    if( role != Qt::DisplayRole || orientation != Qt::Horizontal )
        return QVariant();
    switch( section )
    {
    case 0:
        return QString( "Object" );
    case 1:
        return QString( "ON/OFF" );
    default:
        return QVariant();
    }
}
QModelIndex TreeSceneModel::index (int row, int column, const QModelIndex & parent) const
Definition at line 470 of file treeSceneController.cpp.
References indexToScene(), TreeSceneController::mChildren, and mTopItem.
Referenced by packPath(), and unpackPath().
{
    if (!hasIndex(row, column, parent))
    {
        return QModelIndex();
    }
    TreeSceneController *parentController = (!parent.isValid() ? mTopItem : indexToScene(parent));
    if( row < (int)parentController->mChildren.size() )
    {
        return createIndex( row, column, parentController->mChildren[row]);
    }
    return QModelIndex();
}
TreeSceneController * TreeSceneModel::indexToScene (const QModelIndex & index) const [private]
Definition at line 696 of file treeSceneController.cpp.
References mTopItem.
Referenced by clicked(), data(), dropMimeData(), index(), parent(), rowCount(), and setData().
{
    if (index != QModelIndex())
    {
        return static_cast<TreeSceneController*>( index.internalPointer() );
    } else {
        return mTopItem;
    }
}
QMimeData * TreeSceneModel::mimeData (const QModelIndexList & indexes) const
Definition at line 560 of file treeSceneController.cpp.
References MIME_TYPE, and packPath().
{
    //qDebug() << "Packing object to mime";
    QMimeData *mimeData = new QMimeData();
    QByteArray encodedData;
    QDataStream stream(&encodedData, QIODevice::WriteOnly);
    if (indexes.size() == 0)
    {
        return NULL;
    }
    packPath(indexes[0], stream);
    mimeData->setData(MIME_TYPE, encodedData);
    return mimeData;
}
QStringList TreeSceneModel::mimeTypes () const
Definition at line 520 of file treeSceneController.cpp.
References MIME_TYPE.
{
    QStringList types;
    types << MIME_TYPE;
    return types;
}
void TreeSceneModel::modelChanged () [signal]
Referenced by setData().
void TreeSceneModel::packPath (QModelIndex index, QDataStream & stream) const
Definition at line 528 of file treeSceneController.cpp.
References index(), and parent().
Referenced by mimeData().
{
    vector<int> path;
    QModelIndex pathIter = index;
    while (pathIter != QModelIndex())
    {
        path.push_back(pathIter.row());
        pathIter = parent(pathIter);
    }
    for (unsigned i = 0; i < path.size(); i++)
    {
        stream << path[path.size() - 1 - i ];
    }
}
QModelIndex TreeSceneModel::parent (const QModelIndex & index) const
Definition at line 488 of file treeSceneController.cpp.
References indexToScene(), TreeSceneController::mChildren, TreeSceneController::mParentController, and mTopItem.
Referenced by dropMimeData(), and packPath().
{
    if( !index.isValid() )
    {
        return QModelIndex();
    }
    TreeSceneController *indexObject = indexToScene(index);
    TreeSceneController *parentObject = indexObject->mParentController;
    if( parentObject == mTopItem )
        return QModelIndex();
    TreeSceneController *grandParentObject = parentObject->mParentController;
    unsigned int row = 0;
    for (; row < grandParentObject->mChildren.size(); row++ )
    {
        if (grandParentObject->mChildren[row] == parentObject)
            break;
    }
    return createIndex( row, 0, parentObject );
}
int TreeSceneModel::rowCount (const QModelIndex & parent) const
Definition at line 448 of file treeSceneController.cpp.
References indexToScene(), TreeSceneController::mChildren, and mTopItem.
{
    TreeSceneController *parentObject = NULL;
    if (!parent.isValid()) {
        parentObject = mTopItem;
    } else {
        parentObject = indexToScene(parent);
    }
    if (parentObject == NULL)
        return 0;
    return (int)parentObject->mChildren.size();
}
bool TreeSceneModel::setData (const QModelIndex & index, const QVariant & value, int role)
Definition at line 402 of file treeSceneController.cpp.
References indexToScene(), TreeSceneController::mObject, and modelChanged().
{
    if (!index.isValid())
    {
        return false;
    }
    qDebug("setData called:");
    if (role == Qt::CheckStateRole)
    {
        TreeSceneController *scene = indexToScene(index);
        Qt::CheckState checkState = static_cast<Qt::CheckState>(value.toInt());
        if (scene->mObject)
        {
            scene->mObject->visible = checkState;
            qDebug("setData called: returning true");
            emit modelChanged();
          //  emit dataChanged(index, index);
            qDebug() << scene->mObject->name <<
                    "(" << scene->mObject.data() << ")" <<
                    " is now:" << scene->mObject->visible;
            return true;
        }
    }
    qDebug("setData called: returning false");
    return false;
}
Qt::DropActions TreeSceneModel::supportedDropActions () const
Definition at line 681 of file treeSceneController.cpp.
{
    return Qt::MoveAction;
}
QModelIndex TreeSceneModel::unpackPath (QDataStream & stream) const
Definition at line 544 of file treeSceneController.cpp.
References index().
Referenced by dropMimeData().
{
    QModelIndex pathIter;
    qDebug() << "Got data:";
    QString prefix = ">";
    while (!stream.atEnd())
    {
        int origRow = 0;
        stream >> origRow;
        pathIter = index(origRow, 0, pathIter);
        qDebug() << prefix << "[" << origRow << "]";
        prefix += ">";
    }
    return pathIter;
}
Member Data Documentation
const QString TreeSceneModel::MIME_TYPE = "application/x-vimouse-internal" [static, private]
Definition at line 161 of file treeSceneController.h.
Referenced by dropMimeData(), mimeData(), and mimeTypes().
TreeSceneController* TreeSceneModel::mTopItem
Definition at line 117 of file treeSceneController.h.
Referenced by addObject(), dropMimeData(), index(), indexToScene(), CloudViewDialog::initializeGLSlot(), CloudViewDialog::loadParameters(), parent(), CloudViewDialog::repaintGLSlot(), rowCount(), CloudViewDialog::saveParameters(), TreeSceneModel(), and ~TreeSceneModel().
The documentation for this class was generated from the following files:
utils/uis/cloudview/treeSceneController.h
utils/uis/cloudview/treeSceneController.cpp