DeepView: corecvs::Plane3d Class Reference
corecvs::Plane3d Class Reference
#include <line.h>
Public Types
typedef FixedVector< double, 4 > Vector4dd
typedef double InnerElementType
typedef ReflectionHelper
< double >::Type ReflectionType
Public Member Functions
Plane3d ()
Plane3d (const double &_a, const double &_b, const double &_c, const double &_d)
Plane3d (const Vector3dd &_n, const double &_c=0.0)
void normalise (void)
Normalizes the normal vector without changing the plane itself.
Plane3d normalised (void) const
Return a normalized copy of vector.
Vector3dd normal (void) const
double last (void) const
Ray3d intersectWith (const Plane3d &other, bool *hasIntersection=NULL) const
Intersect result of two planes is a ray.
Vector3dd intersectWith (const Ray3d &ray, bool *hasIntersection=NULL) const
Intersect result of plane and a ray is a point.
double pointWeight (const Vector3dd &point) const
double distanceTo (const Vector3dd &point) const
double sqDistanceTo (const Vector3dd &point) const
double deviationTo (const Vector3dd &point) const
Vector3dd projectPointTo (const Vector3dd &point) const
projecting a point to the current plane
int size () const
double & operator[] (int n)
const double & operator[] (int n) const
double & at (int n)
const double & at (int n) const
FixedVector< double, length > createVector (int) const
FixedVector< double, length > * realThis ()
Static cast functions.
const FixedVector< double,
length > * realThis () const
bool operator== (const FixedVector< double, length > &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const FixedVector< double, length > &that) const
Inequality operator.
bool notTooFar (const FixedVector< double, length > &that, const double &epsilon=double(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const FixedVector< double, length > &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const FixedVector< double, length > &V)
VectorOperationsBase & operator*= (const double &c)
VectorOperationsBase & operator/= (const double &c)
FixedVector< double, length > operator- () const
Negative operator.
double sumAllElements () const
Sum of the elements of the vector.
double mulAllElements () const
Product of all elements of the vector.
double sumAllElementsSq () const
Sum of the squares of element of the vector.
double l2Metric () const
Euclidean distance.
double operator! () const
Another alias for Euclidean distance.
FixedVector< double, length > cloneVector () const
Return copy of vector.
double l1Metric () const
Sum of the absolute values of element of the vector.
double lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
double minimum () const
double maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
void accept (VisitorType &visitor)
Static Public Member Functions
static Plane3d FormNormal (const Vector3dd &normal)
Construct a plane from normal.
static Plane3d FormNormalAndPoint (const Vector3dd &normal, const Vector3dd &point)
Construct the Plane from normal and a point.
static Plane3d FromPoints (const Vector3dd &p, const Vector3dd &q, const Vector3dd &r)
Construct the Plane from 3 points.
static Plane3d FromPointAndVectors (const Vector3dd &p, const Vector3dd &v1, const Vector3dd &v2)
Construct the Plane from а point and two vectors inside a plane.
Public Attributes
double element [length]
Static Public Attributes
static const int LENGTH
Protected Types
typedef FixedVectorBase
< FixedVector< double, length >
, double, length > BaseClass
Friends
FixedVector< double, length > operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
FixedVector< double, length > operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
FixedVector< double, length > operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
FixedVector< double, length > operator* (const double &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
FixedVector< double, length > operator* (const VectorOperationsBase &V, const double &c)
FixedVector< double, length > operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
FixedVector< double, length > operator/ (const VectorOperationsBase &V, const double &c)
Operator * does the component-specific multiplication by constant
.
double operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
Definition at line 491 of file line.h.
Member Typedef Documentation
typedef FixedVectorBase<FixedVector<double , length>, double , length> corecvs::FixedVector< double , length >::BaseClass [protected, inherited]
Reimplemented from corecvs::FixedVectorBase< FixedVector< double, length >, double, length >.
Definition at line 128 of file fixedVector.h.
typedef double corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<double >::Type corecvs::VectorOperationsBase< FixedVector< double, length > , double >::ReflectionType [inherited]
Definition at line 561 of file vectorOperations.h.
typedef FixedVector<double, 4> corecvs::Plane3d::Vector4dd
Definition at line 494 of file line.h.
Constructor & Destructor Documentation
corecvs::Plane3d::Plane3d () [inline]
Definition at line 496 of file line.h.
Referenced by FormNormal(), and FormNormalAndPoint().
{};
corecvs::Plane3d::Plane3d (const double & _a, const double & _b, const double & _c, const double & _d) [inline]
Definition at line 498 of file line.h.
    {
        (*this)[0] = _a;
        (*this)[1] = _b;
        (*this)[2] = _c;
        (*this)[3] = _d;
    }
corecvs::Plane3d::Plane3d (const Vector3dd & _n, const double & _c = 0.0) [inline]
Definition at line 506 of file line.h.
                                                         :
        Vector4dd((const FixedVector<double, 3> &)_n, _c)
    {}
Member Function Documentation
void corecvs::VectorOperationsBase< FixedVector< double, length > , double >::accept (VisitorType & visitor) [inline, inherited]
Definition at line 578 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            const ReflectionType fieldDescriptor(i, defaultValue, name);
            visitor.visit(_at(i), &fieldDescriptor);
        }
    }
void corecvs::VectorOperationsBase< FixedVector< double, length > , double >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
double & corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
Referenced by normalise().
    {
        return element[n];
    }
const double & corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
FixedVector< double, length > corecvs::VectorOperationsBase< FixedVector< double, length > , double >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
FixedVector< double, length > corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
double corecvs::Plane3d::deviationTo (const Vector3dd & point) const [inline]
Definition at line 643 of file line.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric(), normal(), and pointWeight().
     {
         double d = pointWeight(point);
         double l = normal().l2Metric();
         return (d / l);
     }
double corecvs::Plane3d::distanceTo (const Vector3dd & point) const [inline]
Definition at line 616 of file line.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric(), normal(), and pointWeight().
     {
         double d = pointWeight(point);
         if (d < 0) d = -d;
         double l = normal().l2Metric();
         return (d / l);
     }
static Plane3d corecvs::Plane3d::FormNormal (const Vector3dd & normal) [inline, static]
Construct a plane from normal.
Definition at line 667 of file line.h.
References Plane3d().
    {
        return Plane3d(normal);
    };
static Plane3d corecvs::Plane3d::FormNormalAndPoint (const Vector3dd & normal, const Vector3dd & point) [inline, static]
Construct the Plane from normal and a point.
Definition at line 682 of file line.h.
References Plane3d().
Referenced by FromPointAndVectors(), and FromPoints().
    {
        return Plane3d(normal, -(normal & point));
    };
static Plane3d corecvs::Plane3d::FromPointAndVectors (const Vector3dd & p, const Vector3dd & v1, const Vector3dd & v2) [inline, static]
Construct the Plane from а point and two vectors inside a plane.
Definition at line 703 of file line.h.
References FormNormalAndPoint().
    {
        return FormNormalAndPoint( v1 ^ v2, p);
    }
static Plane3d corecvs::Plane3d::FromPoints (const Vector3dd & p, const Vector3dd & q, const Vector3dd & r) [inline, static]
Construct the Plane from 3 points.
Definition at line 694 of file line.h.
References FormNormalAndPoint().
    {
        return FormNormalAndPoint( (p - q) ^ (p - r), p);
    }
Ray3d corecvs::Plane3d::intersectWith (const Plane3d & other, bool * hasIntersection = NULL) const [inline]
Intersect result of two planes is a ray.
Ray
Normal:
Some point: closest to zero
Definition at line 560 of file line.h.
References last(), normal(), and corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElementsSq().
    {
        Vector3dd a = (this->normal() ^ other.normal());
        Vector3dd p1 = (other.last() * this->normal() - this->last() * other.normal());
        Vector3dd p = (p1 ^ a) / a.sumAllElementsSq();
        if (hasIntersection != NULL)
            *hasIntersection = (a == Vector3dd(0.0));
        return Ray3d(a, p);
    }
Vector3dd corecvs::Plane3d::intersectWith (const Ray3d & ray, bool * hasIntersection = NULL) const [inline]
Intersect result of plane and a ray is a point.
point -
plane -
Finding intersection
Definition at line 587 of file line.h.
References corecvs::BaseRay< RealType, VectorType >::a, corecvs::BaseRay< RealType, VectorType >::getPoint(), last(), normal(), and corecvs::BaseRay< RealType, VectorType >::p.
    {
        double denum = normal() & ray.a;
        bool intersects = (denum != 0.0);
        if (hasIntersection) *hasIntersection = intersects;
        if (!intersects)
            return Vector3dd(0.0);
        double t = ((normal() & ray.p) + last()) / denum;
        return ray.getPoint(t);
    }
bool corecvs::VectorOperationsBase< FixedVector< double, length > , double >::isInHypercube (const VectorOperationsBase< FixedVector< double, length >, double > & low, const VectorOperationsBase< FixedVector< double, length >, double > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
double corecvs::Plane3d::last (void) const [inline]
Definition at line 537 of file line.h.
References corecvs::FixedVectorBase< FixedVector< double, length >, double, length >::element.
Referenced by intersectWith(), and pointWeight().
    {
        return element[3];
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
Vector3dd corecvs::Plane3d::normal (void) const [inline]
Definition at line 532 of file line.h.
References corecvs::FixedVectorBase< FixedVector< double, length >, double, length >::element.
Referenced by deviationTo(), distanceTo(), intersectWith(), pointWeight(), projectPointTo(), and sqDistanceTo().
    {
        return Vector3dd(element[0], element[1], element[2]);
    }
void corecvs::Plane3d::normalise (void) [inline]
Normalizes the normal vector without changing the plane itself.
With such a line it is easier to compute distance to the plane
Reimplemented from corecvs::VectorOperationsBase< FixedVector< double, length >, double >.
Definition at line 515 of file line.h.
References corecvs::FixedVectorBase< FixedVector< double, length >, double, length >::at(), corecvs::VectorOperationsBase< FixedVector< double, length >, double >::operator/=(), and corecvs::FixedVectorBase< FixedVector< double, length >, double, length >::size().
Referenced by normalised().
    {
        double sum(0);
        for (int i = 0; i < size() - 1; i++)
            sum += at(i) * at(i);
        double l = sqrt(sum);
        if (l == 0.0) return;
        operator /=(l);
    }
Plane3d corecvs::Plane3d::normalised (void) const [inline]
Return a normalized copy of vector.
Reimplemented from corecvs::VectorOperationsBase< FixedVector< double, length >, double >.
Definition at line 525 of file line.h.
References normalise().
    {
        Plane3d result = *this;
        result.normalise();
        return result;
    }
bool corecvs::VectorOperationsBase< FixedVector< double, length > , double >::notTooFar (const FixedVector< double, length > & that, const double & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator!= (const FixedVector< double, length > & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator*= (const double & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator+= (const FixedVector< double, length > & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
FixedVector< double, length > corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator-= (const FixedVector< double, length > & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator/= (const double & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
Referenced by normalise().
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< FixedVector< double, length > , double >::operator== (const FixedVector< double, length > & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
double & corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
const double & corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
double corecvs::Plane3d::pointWeight (const Vector3dd & point) const [inline]
Definition at line 606 of file line.h.
References last(), and normal().
Referenced by deviationTo(), distanceTo(), projectPointTo(), and sqDistanceTo().
     {
         return (normal() & point) + last();
     }
void corecvs::VectorOperationsBase< FixedVector< double, length > , double >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< FixedVector< double, length > , double >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
Vector3dd corecvs::Plane3d::projectPointTo (const Vector3dd & point) const [inline]
projecting a point to the current plane
Definition at line 655 of file line.h.
References normal(), pointWeight(), and corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElementsSq().
     {
         double d = pointWeight(point);
         double l2 = normal().sumAllElementsSq();
         double t = (d / l2);
         return point - t * normal();
     }
FixedVector< double, length > * corecvs::VectorOperationsBase< FixedVector< double, length > , double >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const FixedVector< double, length > * corecvs::VectorOperationsBase< FixedVector< double, length > , double >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
int corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
Referenced by normalise().
    {
        return length;
    }
double corecvs::Plane3d::sqDistanceTo (const Vector3dd & point) const [inline]
Definition at line 629 of file line.h.
References normal(), pointWeight(), and corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElementsSq().
     {
         double d = pointWeight(point);
         d *= d;
         double lsq = normal().sumAllElementsSq();
         return (d / lsq);
     }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
double corecvs::VectorOperationsBase< FixedVector< double, length > , double >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
Friends And Related Function Documentation
double operator& (const VectorOperationsBase< FixedVector< double, length >, double > & V1, const VectorOperationsBase< FixedVector< double, length >, double > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
FixedVector< double, length > operator* (const VectorOperationsBase< FixedVector< double, length >, double > & V1, const VectorOperationsBase< FixedVector< double, length >, double > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
FixedVector< double, length > operator* (const double & c, const VectorOperationsBase< FixedVector< double, length >, double > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
FixedVector< double, length > operator* (const VectorOperationsBase< FixedVector< double, length >, double > & V, const double & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
FixedVector< double, length > operator+ (const VectorOperationsBase< FixedVector< double, length >, double > & V1, const VectorOperationsBase< FixedVector< double, length >, double > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
FixedVector< double, length > operator- (const VectorOperationsBase< FixedVector< double, length >, double > & V1, const VectorOperationsBase< FixedVector< double, length >, double > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
FixedVector< double, length > operator/ (const VectorOperationsBase< FixedVector< double, length >, double > & V1, const VectorOperationsBase< FixedVector< double, length >, double > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
FixedVector< double, length > operator/ (const VectorOperationsBase< FixedVector< double, length >, double > & V, const double & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< FixedVector< double, length >, double > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, VectorOperationsBase< FixedVector< double, length >, double > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
Member Data Documentation
double corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
Referenced by last(), and normal().
const int corecvs::FixedVectorBase< FixedVector< double, length > , double , length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
The documentation for this class was generated from the following file:
core/geometry/line.h