DeepView: Log Class Reference
Log Class Reference
Class that controls the log.
#include <log.h>
Classes
class MessageInternal
This class describes message of the log.
class MessageScoped
If we want to use qDebug style for debugging we need an object that will be destroyed when leaving the scope.
Public Types
enum LogLevel {
LEVEL_FIRST = 0, LEVEL_DETAILED_DEBUG = LEVEL_FIRST, LEVEL_DEBUG, LEVEL_INFO,
LEVEL_WARNING, LEVEL_ERROR, LEVEL_LAST
}
Log detail level.
typedef ObjectRef
< MessageInternal > Message
Message is a smart pointer to MessageInternal.
Public Member Functions
Log (const LogLevel maxLocalLevel=LEVEL_ERROR)
~Log ()
MessageScoped error (const char *fileName=NULL, int lineNumber=-1, const char *functionName=NULL)
MessageScoped warning (const char *fileName=NULL, int lineNumber=-1, const char *functionName=NULL)
Create warning.
MessageScoped info (const char *fileName=NULL, int lineNumber=-1, const char *functionName=NULL)
Create info.
MessageScoped debug (const char *fileName=NULL, int lineNumber=-1, const char *functionName=NULL)
Create debug trace.
MessageScoped ddebug (const char *fileName=NULL, int lineNumber=-1, const char *functionName=NULL)
Create detailed debug trace.
void message (Message &message)
Log a message.
Static Public Member Functions
static std::string formatted (const char *format,...)
static std::string msgBufToString (const char *message)
static bool shouldWrite (LogLevel messageLevel)
static int staticInit ()
This is a static init function.
Static Public Attributes
static const char * level_names []
static LogLevel mMinLogLevel = LEVEL_FIRST
It is impossible to tell when this function will be executed, so you should not log from static initializers.
static std::vector< LogDrain * > mLogDrains
static int mDummy = Log::staticInit()
Detailed Description
Class that controls the log.
Definition at line 45 of file log.h.
Member Typedef Documentation
typedef ObjectRef<MessageInternal> Log::Message
Message is a smart pointer to MessageInternal.
MessageInternal is usually accessed only through this structure
Definition at line 110 of file log.h.
Member Enumeration Documentation
enum Log::LogLevel
Log detail level.
Enumerator:
LEVEL_FIRST
LEVEL_DETAILED_DEBUG
Detailed log.
LEVEL_DEBUG
Debugging information is outputed.
LEVEL_INFO
Normal information messages are outputed.
LEVEL_WARNING
Only warnings are reported.
LEVEL_ERROR
Only errors are reported.
LEVEL_LAST
Last enum value for iterating.
Definition at line 49 of file log.h.
                  {
          LEVEL_FIRST = 0
        , LEVEL_DETAILED_DEBUG = LEVEL_FIRST  /**< Detailed log */
        , LEVEL_DEBUG                         /**< Debugging information is outputed */
        , LEVEL_INFO                          /**< Normal information messages are outputed */
        , LEVEL_WARNING                       /**< Only warnings are reported */
        , LEVEL_ERROR                         /**< Only errors are reported */
        , LEVEL_LAST                          /**< Last enum value for iterating */
    };
Constructor & Destructor Documentation
Log::Log (const LogLevel maxLocalLevel = LEVEL_ERROR)
Definition at line 47 of file log.cpp.
{
}
Log::~Log ()
Definition at line 51 of file log.cpp.
{
}
Member Function Documentation
MessageScoped Log::ddebug (const char * fileName = NULL, int lineNumber = -1, const char * functionName = NULL) [inline]
Create detailed debug trace.
Definition at line 185 of file log.h.
References LEVEL_DETAILED_DEBUG.
    {
        return MessageScoped(this,  LEVEL_DETAILED_DEBUG, fileName, lineNumber, functionName);
    }
MessageScoped Log::debug (const char * fileName = NULL, int lineNumber = -1, const char * functionName = NULL) [inline]
Create debug trace.
Definition at line 177 of file log.h.
References LEVEL_DEBUG.
    {
        return MessageScoped(this,  LEVEL_DEBUG, fileName, lineNumber, functionName);
    }
MessageScoped Log::error (const char * fileName = NULL, int lineNumber = -1, const char * functionName = NULL) [inline]
Definition at line 153 of file log.h.
References LEVEL_ERROR.
    {
        return MessageScoped(this, LEVEL_ERROR, fileName, lineNumber, functionName);
    }
std::string Log::formatted (const char * format, ...) [static]
Definition at line 67 of file log.cpp.
{
    std::string result;
    va_list marker;
    va_start(marker, format);
        size_t len = vsnprintf(NULL, 0, format, marker) + 1;    // to add a nul symbol
    va_end(marker);
    va_list marker2;
    va_start(marker2, format);
#if 1
        char* buf = new char[len];
        vsnprintf(buf, len, format, marker2);
        result.assign(buf);
        delete[] buf;
#else
        // TODO: this code inserts one dummy symbol at begin of the result?!!
        result.resize(len);
      //vsnprintf(result._Myptr(), len, format, marker2);
        vsnprintf(&result[0], len, format, marker2);
#endif
    va_end(marker2);
    return result;
}
MessageScoped Log::info (const char * fileName = NULL, int lineNumber = -1, const char * functionName = NULL) [inline]
Create info.
Definition at line 169 of file log.h.
References LEVEL_INFO.
    {
        return MessageScoped(this,  LEVEL_INFO, fileName, lineNumber, functionName);
    }
void Log::message (Message & message)
Log a message.
Definition at line 39 of file log.cpp.
References mLogDrains.
Referenced by msgBufToString().
{
    for(unsigned int i = 0; i < mLogDrains.size(); i++)
    {
        mLogDrains[i]->drain(message);
    }
}
std::string Log::msgBufToString (const char * message) [static]
Definition at line 55 of file log.cpp.
References message().
{
    std::string message(msg);
    if (message.size() != 0 && message[message.size() - 1] == '\n') {
        message.resize(message.size() - 1);
    }
    return message;
}
static bool Log::shouldWrite (LogLevel messageLevel) [inline, static]
Definition at line 199 of file log.h.
References mMinLogLevel.
Referenced by Log::MessageScoped::~MessageScoped().
{
        return messageLevel >= mMinLogLevel;
    }
int Log::staticInit () [static]
This is a static init function.
Definition at line 31 of file log.cpp.
References mLogDrains.
{
    LogDrain *defaultDrain = new StdStreamLogDrain(std::cout);
    mLogDrains.push_back(defaultDrain);
//  logStream.reset(new std::ofstream(fileName.c_str(), std::ios::out | std::ios::app));
    return 0;
}
MessageScoped Log::warning (const char * fileName = NULL, int lineNumber = -1, const char * functionName = NULL) [inline]
Create warning.
Definition at line 161 of file log.h.
References LEVEL_WARNING.
    {
        return MessageScoped(this, LEVEL_WARNING, fileName, lineNumber, functionName);
    }
Member Data Documentation
const char * Log::level_names [static]
Initial value:
{
   "Det. Debug",
   "Debug",
   "Info",
   "Warning",
   "Error"
}
Definition at line 59 of file log.h.
Referenced by StdStreamLogDrain::drain().
int Log::mDummy = Log::staticInit() [static]
Definition at line 205 of file log.h.
std::vector< LogDrain * > Log::mLogDrains [static]
Definition at line 204 of file log.h.
Referenced by MainWindow::MainWindow(), message(), and staticInit().
Log::LogLevel Log::mMinLogLevel = LEVEL_FIRST [static]
It is impossible to tell when this function will be executed, so you should not log from static initializers.
Definition at line 203 of file log.h.
Referenced by shouldWrite().
The documentation for this class was generated from the following files:
core/utils/log.h
core/utils/log.cpp