DeepView: corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber > Class Template Reference
corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber > Class Template Reference
ScalarAlgebraMulti is a crucial part of fastKernels.
#include <scalarAlgebra.h>
Public Types
typedef _InputTraits InputTraits
typedef _OutputTraits OutputTraits
typedef ScalarAlgebraMulti FallbackAlgebra
typedef BaseAlgebraMulti
< typename
_InputTraits::InternalType,
typename
_OutputTraits::InternalType,
1, inputNumber, outputNumber > BaseClass
typedef InputTraits::Type InputType
This algebra is scalar because it's internal type is equal to the processing type.
typedef InputTraits::SignedType InputSignedType
typedef OutputTraits::Type OutputType
typedef OutputTraits::SignedType OutputSignedType
typedef _InputTraits::InternalType InternalInputType
typedef _OutputTraits::InternalType InternalOutputType
Public Member Functions
STATIC_ASSERT ((_InputTraits::step==1), scalar_algebra_supports_only_single_step_input)
STATIC_ASSERT ((_OutputTraits::step==1), scalar_algebra_supports_only_single_step_output)
ScalarAlgebraMulti ()
ScalarAlgebraMulti (const ScalarAlgebraMulti &other)
Copy constructor.
InputType getInput (int input, int y, int x)
void putOutput (int output, int y, int x, const OutputType &result)
InputType getInput (int y, int x)
void putOutput (int y, int x, const OutputType &result)
template<int y, int x>
InputType getInput ()
template<int y, int x>
void putOutput (const OutputType &result)
void copyPos (const OtherAlgebra &other)
void setInputStride (int _strideI, int input=0)
void setOutputStride (int _strideO, int output=0)
void setInputPos (void *_ptrI, int input=0)
void setOutputPos (void *_ptrO, int output=0)
InternalInputType * getInputPos (int input=0) const
InternalInputType * getInputPos (int input, int y, int x) const
InternalOutputType * getOutputPos (int output=0) const
InternalOutputType * getOutputPos (int output, int y, int x) const
void advance ()
Static Public Member Functions
static int step ()
static DividableType div (const DividableType &val)
static _InputTraits::InternalType mul (const _InputTraits::InternalType &val)
static _InputTraits::InternalType branchlessMask (const _InputTraits::InternalType &val)
static _InputTraits::InternalType selector (const _InputTraits::InternalType &condition, const _InputTraits::InternalType &ifTrue, const _InputTraits::InternalType &ifFalse)
static InputType max (const InputType &left, const InputType &right)
static InputType min (const InputType &left, const InputType &right)
static _InputTraits::InternalType difference (const _InputTraits::InternalType &left, const _InputTraits::InternalType &right)
static _InputTraits::InternalType difference15bit (const _InputTraits::InternalType &left, const _InputTraits::InternalType &right)
static InputType abs (const InputType &value)
static _InputTraits::InternalType andNot (const _InputTraits::InternalType &left, const _InputTraits::InternalType &right)
Public Attributes
InternalInputType * ptrI [inputNumber]
InternalOutputType * ptrO [outputNumber]
int strideI [inputNumber]
int strideO [outputNumber]
Detailed Description
template<typename _InputTraits, typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1>
class corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >
ScalarAlgebraMulti is a crucial part of fastKernels.
This algebra allows fallback to generic types such as int, double, float ...
Definition at line 40 of file scalarAlgebra.h.
Member Typedef Documentation
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef BaseAlgebraMulti< typename _InputTraits::InternalType, typename _OutputTraits::InternalType, 1, inputNumber, outputNumber > corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::BaseClass
Definition at line 60 of file scalarAlgebra.h.
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef ScalarAlgebraMulti corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::FallbackAlgebra
Definition at line 55 of file scalarAlgebra.h.
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef InputTraits::SignedType corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::InputSignedType
Definition at line 67 of file scalarAlgebra.h.
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef _InputTraits corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::InputTraits
Definition at line 51 of file scalarAlgebra.h.
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef InputTraits::Type corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::InputType
This algebra is scalar because it's internal type is equal to the processing type.
Definition at line 66 of file scalarAlgebra.h.
typedef _InputTraits::InternalType corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::InternalInputType [inherited]
Definition at line 61 of file baseAlgebra.h.
typedef _OutputTraits::InternalType corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::InternalOutputType [inherited]
Definition at line 62 of file baseAlgebra.h.
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef OutputTraits::SignedType corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::OutputSignedType
Definition at line 70 of file scalarAlgebra.h.
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef _OutputTraits corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::OutputTraits
Definition at line 52 of file scalarAlgebra.h.
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> typedef OutputTraits::Type corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::OutputType
Definition at line 69 of file scalarAlgebra.h.
Constructor & Destructor Documentation
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::ScalarAlgebraMulti () [inline]
Definition at line 72 of file scalarAlgebra.h.
{}
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::ScalarAlgebraMulti (const ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber > & other) [inline]
Copy constructor.
It is absolutely crucial to overload copy constructor if you want to use OpenMP.
Definition at line 78 of file scalarAlgebra.h.
References DOTRACE_ALG.
                                                        :
        BaseClass(other)
    {
        DOTRACE_ALG(("Scalar Algebra Copy constructor called (in %d, out %d)\n", inputNumber, outputNumber));
    }
Member Function Documentation
static InputType corecvs::GenericMath< _InputTraits::InternalType >::abs (const InputType & value) [inline, static, inherited]
Definition at line 70 of file genericMath.h.
References corecvs::GenericMath< Type >::max().
{
        return max(value, InputType(-value));
    }
void corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::advance () [inline, inherited]
Definition at line 142 of file baseAlgebra.h.
References in, corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrI, and corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrO.
    {
        for (int in = 0; in < inputNumber; in++)
        {
            ptrI[in] += stepSize;
        }
        for (int out = 0; out < outputNumber; out++)
        {
            ptrO[out] += stepSize;
        }
    }
static _InputTraits::InternalType corecvs::GenericMath< _InputTraits::InternalType >::andNot (const _InputTraits::InternalType & left, const _InputTraits::InternalType & right) [inline, static, inherited]
Definition at line 75 of file genericMath.h.
{
        return (left & (~right));
    }
static _InputTraits::InternalType corecvs::GenericMath< _InputTraits::InternalType >::branchlessMask (const _InputTraits::InternalType & val) [inline, static, inherited]
void corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::copyPos (const OtherAlgebra & other) [inline, inherited]
Definition at line 92 of file baseAlgebra.h.
References in, corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::setInputPos(), and corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::setOutputPos().
    {
        for (int in = 0; in < inputNumber; in++)
        {
            this->setInputPos (other.getInputPos(in), in);
        }
        for (int out = 0; out < outputNumber; out++)
        {
            this->setOutputPos(other.getOutputPos(out), out);
        }
    }
static _InputTraits::InternalType corecvs::GenericMath< _InputTraits::InternalType >::difference (const _InputTraits::InternalType & left, const _InputTraits::InternalType & right) [inline, static, inherited]
Definition at line 60 of file genericMath.h.
{
        if (left > right) return left - right;
        return right - left;
    }
static _InputTraits::InternalType corecvs::GenericMath< _InputTraits::InternalType >::difference15bit (const _InputTraits::InternalType & left, const _InputTraits::InternalType & right) [inline, static, inherited]
Definition at line 65 of file genericMath.h.
References corecvs::GenericMath< Type >::difference().
{
        return difference(left, right);
    }
static DividableType corecvs::GenericMath< _InputTraits::InternalType >::div (const DividableType & val) [inline, static, inherited]
Definition at line 28 of file genericMath.h.
    {
        return DividableType(val / divisor);
    }
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> InputType corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::getInput (int input, int y, int x) [inline]
Definition at line 85 of file scalarAlgebra.h.
References DOTRACE_ALG, corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::getInputPos(), corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::ptrI, and corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::strideI.
    {
        DOTRACE_ALG(("Read  SC (%d)[%d x %d] %x %d\n", input, x, y, this->ptrI[input], this->strideI[input]));
        return *BaseClass::getInputPos(input, y, x);
    }
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> InputType corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::getInput (int y, int x) [inline]
Definition at line 98 of file scalarAlgebra.h.
References corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::ptrI, and corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::strideI.
    {
        return *(this->ptrI[0] + y * this->strideI[0]  + x);
    }
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> template<int y, int x> InputType corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::getInput () [inline]
Definition at line 110 of file scalarAlgebra.h.
References corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::ptrI, and corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::strideI.
    {
        return *(this->ptrI[0] + y * this->strideI[0]  + x);
    }
InternalInputType* corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::getInputPos (int input = 0) const [inline, inherited]
Definition at line 125 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrI.
{
        return ptrI[input];
    }
InternalInputType* corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::getInputPos (int input, int y, int x) const [inline, inherited]
Definition at line 133 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrI, and corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::strideI.
{
        //printf(" %p %p\n", this->ptrI[0], this->ptrI[1]);
        return this->ptrI[input] + y * this->strideI[input]  + x;
    }
InternalOutputType* corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::getOutputPos (int output = 0) const [inline, inherited]
Definition at line 129 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrO.
{
        return ptrO[output];
    }
InternalOutputType* corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::getOutputPos (int output, int y, int x) const [inline, inherited]
Definition at line 138 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrO, and corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::strideO.
{
        return this->ptrO[output] + y * this->strideO[output] + x;
    }
static InputType corecvs::GenericMath< _InputTraits::InternalType >::max (const InputType & left, const InputType & right) [inline, static, inherited]
Definition at line 48 of file genericMath.h.
    {
        return (left > right) ? left : right;
    }
static InputType corecvs::GenericMath< _InputTraits::InternalType >::min (const InputType & left, const InputType & right) [inline, static, inherited]
Definition at line 54 of file genericMath.h.
    {
        return (left > right) ? right : left;
    }
static _InputTraits::InternalType corecvs::GenericMath< _InputTraits::InternalType >::mul (const _InputTraits::InternalType & val) [inline, static, inherited]
Definition at line 34 of file genericMath.h.
    {
        return Type(val * multiplier);
    }
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> void corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::putOutput (int output, int y, int x, const OutputType & result) [inline]
Definition at line 91 of file scalarAlgebra.h.
References DOTRACE_ALG, corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::getOutputPos(), corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::ptrO, and corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::strideO.
    {
        DOTRACE_ALG(("Write SC (%d)[%d x %d] %x %d\n", output, x, y, this->ptrO[output], this->strideO[output]));
        *BaseClass::getOutputPos(output, y, x) = result;
    }
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> void corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::putOutput (int y, int x, const OutputType & result) [inline]
Definition at line 103 of file scalarAlgebra.h.
References corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::ptrO, and corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::strideO.
    {
        *(this->ptrO[0] + y * this->strideO[0] + x) = result;
    }
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> template<int y, int x> void corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::putOutput (const OutputType & result) [inline]
Definition at line 116 of file scalarAlgebra.h.
References corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::ptrO, and corecvs::BaseAlgebraMulti< _InputTraits::InternalType, _OutputTraits::InternalType, 1, inputNumber, outputNumber >::strideO.
    {
        *(this->ptrO[0] + y * this->strideO[0] + x) = result;
    }
static _InputTraits::InternalType corecvs::GenericMath< _InputTraits::InternalType >::selector (const _InputTraits::InternalType & condition, const _InputTraits::InternalType & ifTrue, const _InputTraits::InternalType & ifFalse) [inline, static, inherited]
Definition at line 42 of file genericMath.h.
    {
        return condition ? ifTrue : ifFalse;
    }
void corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::setInputPos (void * _ptrI, int input = 0) [inline, inherited]
Definition at line 117 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrI.
{
        ptrI[input] = (InternalInputType *)_ptrI;
    }
void corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::setInputStride (int _strideI, int input = 0) [inline, inherited]
Definition at line 109 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::strideI.
{
        strideI[input] = _strideI;
    }
void corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::setOutputPos (void * _ptrO, int output = 0) [inline, inherited]
Definition at line 121 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::ptrO.
{
        ptrO[output] = (InternalOutputType *)_ptrO;
    }
void corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::setOutputStride (int _strideO, int output = 0) [inline, inherited]
Definition at line 113 of file baseAlgebra.h.
References corecvs::BaseAlgebraMulti< _InternalTypeInput, _InternalTypeOutput, stepSize, inputNumber, outputNumber >::strideO.
{
        strideO[output] = _strideO;
    }
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::STATIC_ASSERT ((_InputTraits::step==1) , scalar_algebra_supports_only_single_step_input)
template<typename _InputTraits , typename _OutputTraits = _InputTraits, int inputNumber = 1, int outputNumber = 1> corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::STATIC_ASSERT ((_OutputTraits::step==1) , scalar_algebra_supports_only_single_step_output)
static int corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::step () [inline, static, inherited]
Definition at line 104 of file baseAlgebra.h.
    {
        return stepSize;
    }
Member Data Documentation
InternalInputType* corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::ptrI[inputNumber] [inherited]
Definition at line 64 of file baseAlgebra.h.
Referenced by corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::getInput().
InternalOutputType* corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::ptrO[outputNumber] [inherited]
Definition at line 65 of file baseAlgebra.h.
Referenced by corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::putOutput().
int corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::strideI[inputNumber] [inherited]
Definition at line 67 of file baseAlgebra.h.
Referenced by corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::getInput().
int corecvs::BaseAlgebraMulti< _InputTraits::InternalType , _OutputTraits::InternalType , stepSize, inputNumber, outputNumber >::strideO[outputNumber] [inherited]
Definition at line 68 of file baseAlgebra.h.
Referenced by corecvs::ScalarAlgebraMulti< _InputTraits, _OutputTraits, inputNumber, outputNumber >::putOutput().
The documentation for this class was generated from the following file:
core/buffers/kernels/fastkernel/scalarAlgebra.h