DeepView: corecvs::PolynomInterpolator Class Reference
corecvs::PolynomInterpolator Class Reference
#include <interpolator.h>
Static Public Member Functions
static double interpolate (double y, double x, G12Buffer *buffer)
Detailed Description
Definition at line 141 of file interpolator.h.
Member Function Documentation
static double corecvs::PolynomInterpolator::interpolate (double y, double x, G12Buffer * buffer) [inline, static]
Definition at line 144 of file interpolator.h.
References ASSERT_TRUE_P, corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBuffer< ElementType, IndexType >::getH(), corecvs::AbstractBuffer< ElementType, IndexType >::getW(), and corecvs::AbstractContiniousBuffer< ElementType, IndexType >::isValidCoordBl().
    {
        int32_t i = floor(y);
        int32_t j = floor(x);
        int w = buffer->getW();
        int h = buffer->getH();
        ASSERT_TRUE_P(buffer->isValidCoordBl(y,x),
                      ("Invalid coordinate in AbstractContiniousBuffer::elementBl(double y=%lf, double x=%lf) buffer sizes is [%dx%d]",
                       y, x, w, h));
        double a0 = (double)buffer->element(max(0, i - 1), max(0, j - 1));
        double a1 = (double)buffer->element(i, max(0, j - 1));
        double a2 = (double)buffer->element(min(i + 1, h - 1), max(0, j - 1));
        double a3 = (double)buffer->element(max(0, i - 1), j);
        double a4 = (double)buffer->element(i, j);
        double a5 = (double)buffer->element(min(i + 1, h - 1), j);
        double a6 = (double)buffer->element(max(0, i - 1), min(j + 1, w - 1));
        double a7 = (double)buffer->element(i, min(j + 1, w -1));
        double a8 = (double)buffer->element(min(i + 1, h - 1), min(j + 1, w - 1));
        x -= j;
        y -= i;
        double res = a4 +
            (-0.5 * a3 + 0.5 * a5) * x +
            (0.5 * a3 - a4 + 0.5 * a5) * x * x +
            (-0.5 * a1 + 0.5 * a7) * y +
            (0.25 * a0 - 0.25 * a2 - 0.25 * a6 + 0.25 * a8) * y * x +
            (-0.25 * a0 + 0.5 * a1 - 0.25 * a2 + 0.25 * a6 - 0.5 * a7 + 0.25 * a8) * y * x * x +
            (0.5 * a1 - a4 + 0.5 * a7) * y * y +
            (-0.25 * a0 + 0.25 * a2 + 0.5 * a3 - 0.5 * a5 - 0.25 * a6 + 0.25 * a8) * y * y * x +
            (0.25 * a0 - 0.5 * a1 + 0.25 * a2 - 0.5 * a3 + a4 - 0.5 * a5 + 0.25 * a6 -0.5 * a7 + 0.25 * a8) * y * y * x * x;
        return res;
    }
The documentation for this class was generated from the following file:
core/buffers/interpolator.h