DeepView: corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType > Class Template Reference
corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType > Class Template Reference
#include <abstractContiniousBuffer.h>
Public Member Functions
ParallelDoReverseDeformation (ReturnType *_toReturn, DeformMapType &_map, AbstractContiniousBuffer< ElementType, IndexType > *_buf)
void operator() (const BlockedRange< IndexType > &r) const
Private Attributes
ReturnType * toReturn
DeformMapType & map
AbstractContiniousBuffer
< ElementType, IndexType > * buf
Detailed Description
template<typename ElementType, typename IndexType = int32_t>
template<class ReturnType, class DeformMapType>
class corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >
Definition at line 351 of file abstractContiniousBuffer.h.
Constructor & Destructor Documentation
template<typename ElementType, typename IndexType = int32_t> template<class ReturnType , class DeformMapType > corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::ParallelDoReverseDeformation (ReturnType * _toReturn, DeformMapType & _map, AbstractContiniousBuffer< ElementType, IndexType > * _buf) [inline]
Definition at line 358 of file abstractContiniousBuffer.h.
                                                                    :
        toReturn(_toReturn), map(_map), buf(_buf)
        {}
Member Function Documentation
template<typename ElementType, typename IndexType = int32_t> template<class ReturnType , class DeformMapType > void corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator() (const BlockedRange< IndexType > & r) const [inline]
Definition at line 365 of file abstractContiniousBuffer.h.
References corecvs::BlockedRange< IndexType >::begin(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::buf, corecvs::BlockedRange< IndexType >::end(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::map, corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::toReturn, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
        {
            IndexType j;
            IndexType newW = toReturn->w;
            for (IndexType i = r.begin(); i < r.end(); i++)
            {
                for (j = 0; j < newW - 1; j++)
                {
                    Vector2dd p = map.map(i,j);
                    if (buf->isValidCoord(p.y(), p.x()) && buf->isValidCoord(p.y() + 1, p.x() + 1) )
                        toReturn->element(i,j) = buf->element(p.y(), p.x());
                    else
                        toReturn->element(i,j) = typename ReturnType::InternalElementType(0x0);
                }
            }
        }
Member Data Documentation
template<typename ElementType, typename IndexType = int32_t> template<class ReturnType , class DeformMapType > AbstractContiniousBuffer<ElementType, IndexType>* corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::buf [private]
Definition at line 355 of file abstractContiniousBuffer.h.
Referenced by corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator()().
template<typename ElementType, typename IndexType = int32_t> template<class ReturnType , class DeformMapType > DeformMapType& corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::map [private]
Definition at line 354 of file abstractContiniousBuffer.h.
Referenced by corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator()().
template<typename ElementType, typename IndexType = int32_t> template<class ReturnType , class DeformMapType > ReturnType* corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::toReturn [private]
Definition at line 353 of file abstractContiniousBuffer.h.
Referenced by corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator()().
The documentation for this class was generated from the following file:
core/buffers/abstractContiniousBuffer.h