DeepView: corecvs::Line2d Class Reference
corecvs::Line2d Class Reference
This class represents the line in 2D space.
#include <line.h>
Public Types
typedef ElementType InnerElementType
typedef ReflectionHelper
< ElementType >::Type ReflectionType
Public Member Functions
Line2d ()
Line2d (const double &_a, const double &_b, const double &_c)
Line2d (const Vector3dd &_line)
Line2d (const Vector2dd &_n, const double &_c=0.0)
Line2d (const Segment2d &segment)
Construct the Line form 2 points.
Line2d (const Ray2d &ray)
Construct the Line form 2 points.
Vector2dd normal (void) const
double last (void) const
void normalise (void)
Normalizes the normal vector without changing the line itself.
Line2d normalised (void) const
Return a normalized copy of vector.
Vector3dd intersectWith (const Line2d &other) const
Projective coordinates of the lines intersection is a cross product of the projective presentation of the line.
Vector2dd intersectWith (const Line2d &other, bool *hasIntersection=NULL) const
Intersect result of two lines is a point.
double pointWeight (const Vector2dd &point) const
double distanceTo (const Vector2dd &point) const
double sqDistanceTo (const Vector2dd &point) const
Vector2d< ElementType > xy () const
Vector2d< ElementType > xz () const
Vector2d< ElementType > yz () const
operator Vector2d< ElementType > ()
Do the conversion form projective coordinates to the 2D ones.
Vector3d< ElementType > normalizeProjective ()
Add xy(), yz() and other sub-methods.
bool isInCube (const Vector3d< ElementType > &low, const Vector3d< ElementType > &high) const
template<class VisitorType >
void accept (VisitorType &visitor)
int size () const
ElementType & operator[] (int n)
const ElementType & operator[] (int n) const
ElementType & at (int n)
const ElementType & at (int n) const
Vector3d< ElementType > createVector (int) const
Vector3d< ElementType > * realThis ()
Static cast functions.
const Vector3d< ElementType > * realThis () const
bool operator== (const Vector3d< ElementType > &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const Vector3d< ElementType > &that) const
Inequality operator.
bool notTooFar (const Vector3d< ElementType > &that, const ElementType &epsilon=ElementType(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const Vector3d< ElementType > &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const Vector3d< ElementType > &V)
VectorOperationsBase & operator*= (const ElementType &c)
VectorOperationsBase & operator/= (const ElementType &c)
Vector3d< ElementType > operator- () const
Negative operator.
ElementType sumAllElements () const
Sum of the elements of the vector.
ElementType mulAllElements () const
Product of all elements of the vector.
ElementType sumAllElementsSq () const
Sum of the squares of element of the vector.
ElementType l2Metric () const
Euclidean distance.
ElementType operator! () const
Another alias for Euclidean distance.
Vector3d< ElementType > cloneVector () const
Return copy of vector.
ElementType l1Metric () const
Sum of the absolute values of element of the vector.
ElementType lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
ElementType minimum () const
ElementType maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
ElementType & x ()
Helper functions to access elements.
ElementType & y ()
ElementType & z ()
const ElementType & x () const
Constant versions of helper functions for read-only form constant vectors.
const ElementType & y () const
const ElementType & z () const
Static Public Member Functions
static Line2d fromRay (const Ray2d &ray)
static Line2d fromSegment (const Segment2d &segment)
static Line2d FormNormal (const Vector2dd &normal)
static Line2d FormNormalAndPoint (const Vector2dd &normal, const Vector2dd &point)
Public Attributes
ElementType element [length]
Static Public Attributes
static const int LENGTH
Protected Types
typedef FixedVectorBase
< Vector3d< ElementType >
, ElementType, 3 > BaseClass
Private Member Functions
void _init (const Vector2dd &_n, const double &_c=1.0)
Friends
Vector3d operator^ (const Vector3d &V, const Vector3d &U)
This function implements the vector cross product (See http://en.wikipedia.org/wiki/Vector_product).
Vector3d< ElementType > operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
Vector3d< ElementType > operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
Vector3d< ElementType > operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
Vector3d< ElementType > operator* (const ElementType &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
Vector3d< ElementType > operator* (const VectorOperationsBase &V, const ElementType &c)
Vector3d< ElementType > operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
Vector3d< ElementType > operator/ (const VectorOperationsBase &V, const ElementType &c)
Operator * does the component-specific multiplication by constant
.
ElementType operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
This class represents the line in 2D space.
The most obvious presentation of the line:
in this case is some point, and a normal for the line
But this is not the most compact presentation. This class uses the following presentation:
This can be reformulated as:
Which allows to think of the 2D line, as a line in a projective space. That is how we would think of the line.
- is a 3D vector. In 3D denotes a plane that pass throw the 0 point.
Definition at line 322 of file line.h.
Member Typedef Documentation
template<typename ElementType> typedef FixedVectorBase<Vector3d<ElementType>, ElementType, 3> corecvs::Vector3d< ElementType >::BaseClass [protected, inherited]
Reimplemented from corecvs::FixedVectorBase< Vector3d< ElementType >, ElementType, 3 >.
Definition at line 30 of file vector3d.h.
typedef ElementType corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<ElementType>::Type corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::ReflectionType [inherited]
Definition at line 561 of file vectorOperations.h.
Constructor & Destructor Documentation
corecvs::Line2d::Line2d () [inline]
Definition at line 325 of file line.h.
Referenced by FormNormal(), FormNormalAndPoint(), and fromRay().
{};
corecvs::Line2d::Line2d (const double & _a, const double & _b, const double & _c) [inline]
Definition at line 327 of file line.h.
    {
        (*this)[0] = _a;
        (*this)[1] = _b;
        (*this)[2] = _c;
    }
corecvs::Line2d::Line2d (const Vector3dd & _line) [inline]
Definition at line 334 of file line.h.
: Vector3dd(_line) {};
corecvs::Line2d::Line2d (const Vector2dd & _n, const double & _c = 0.0) [inline]
Definition at line 336 of file line.h.
                                                        :
        Vector3dd(_n, _c)
    {}
corecvs::Line2d::Line2d (const Segment2d & segment) [inline]
Construct the Line form 2 points.
Definition at line 343 of file line.h.
References fromSegment().
    {
       (*this) = fromSegment(segment);
    };
corecvs::Line2d::Line2d (const Ray2d & ray) [inline]
Construct the Line form 2 points.
Definition at line 351 of file line.h.
References fromRay().
    {
       (*this) = fromRay(ray);
    };
Member Function Documentation
void corecvs::Line2d::_init (const Vector2dd & _n, const double & _c = 1.0) [inline, private]
Definition at line 480 of file line.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        (*this)[0] = _n.x();
        (*this)[1] = _n.y();
        (*this)[2] = _c;
    }
template<typename ElementType> template<class VisitorType > void corecvs::Vector3d< ElementType >::accept (VisitorType & visitor) [inline, inherited]
Reimplemented from corecvs::VectorOperationsBase< Vector3d< ElementType >, ElementType >.
Definition at line 174 of file vector3d.h.
    {
        visitor.visit(x(), ElementType(0), "x");
        visitor.visit(y(), ElementType(0), "y");
        visitor.visit(z(), ElementType(0), "z");
    }
void corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
Vector3d< ElementType > corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
Vector3d< ElementType > corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
double corecvs::Line2d::distanceTo (const Vector2dd & point) const [inline]
Definition at line 449 of file line.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric(), normal(), and pointWeight().
Referenced by corecvs::EssentialMatrix::epipolarDistance().
    {
        double d = pointWeight(point);
        if (d < 0) d = -d;
        double l = normal().l2Metric();
        return (d / l);
    }
static Line2d corecvs::Line2d::FormNormal (const Vector2dd & normal) [inline, static]
Definition at line 468 of file line.h.
References Line2d().
    {
        return Line2d(normal);
    };
static Line2d corecvs::Line2d::FormNormalAndPoint (const Vector2dd & normal, const Vector2dd & point) [inline, static]
Definition at line 473 of file line.h.
References Line2d().
    {
        return Line2d(normal, -(normal & point));
    };
static Line2d corecvs::Line2d::fromRay (const Ray2d & ray) [inline, static]
Definition at line 356 of file line.h.
References corecvs::BaseRay< RealType, VectorType >::a, corecvs::Vector2d< ElementType >::leftNormal(), Line2d(), and corecvs::BaseRay< RealType, VectorType >::p.
Referenced by fromSegment(), and Line2d().
    {
       Vector2dd a = ray.a;
       Vector2dd p = ray.p;
       Vector2dd n = p.leftNormal();
       return Line2d(n, -(a & n));
    }
static Line2d corecvs::Line2d::fromSegment (const Segment2d & segment) [inline, static]
Definition at line 364 of file line.h.
References corecvs::Segment< VectorType >::a, corecvs::Segment< VectorType >::b, and fromRay().
Referenced by Line2d().
    {
        return fromRay(Ray2d(segment.a, segment.b - segment.a));
    }
Vector3dd corecvs::Line2d::intersectWith (const Line2d & other) const [inline]
Projective coordinates of the lines intersection is a cross product of the projective presentation of the line.
Actually line is an intersection of the planes and is
Which make obvious the way the intersection is computed.
Definition at line 411 of file line.h.
    {
        return (*this) ^ other;
    }
Vector2dd corecvs::Line2d::intersectWith (const Line2d & other, bool * hasIntersection = NULL) const [inline]
Intersect result of two lines is a point.
Definition at line 419 of file line.h.
References corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
    {
        double d = x() * other.y() - y() * other.x();
        bool intersects = (d != 0.0);
        if (hasIntersection) *hasIntersection = intersects;
        if (!intersects)
            return Vector2dd(0);
        double dx = x() * other.z() - other.x() * z();
        double dy = y() * other.z() - other.y() * z();
        return Vector2dd(dx, dy) / d;
    }
template<typename ElementType> bool corecvs::Vector3d< ElementType >::isInCube (const Vector3d< ElementType > & low, const Vector3d< ElementType > & high) const [inline, inherited]
Definition at line 162 of file vector3d.h.
Referenced by corecvs::AxisAlignedBox3d::contains(), and PLYLoader::loadPLY().
    {
        return this->isInHypercube(low, high);
    }
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::isInHypercube (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & low, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
Referenced by corecvs::Vector3d< double >::isInCube().
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
double corecvs::Line2d::last (void) const [inline]
Definition at line 374 of file line.h.
References corecvs::FixedVectorBase< Vector3d< ElementType >, ElementType, 3 >::element.
Referenced by pointWeight().
    {
        return element[2];
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
Vector2dd corecvs::Line2d::normal (void) const [inline]
Definition at line 369 of file line.h.
References corecvs::FixedVectorBase< Vector3d< ElementType >, ElementType, 3 >::element.
Referenced by distanceTo(), normalise(), pointWeight(), and sqDistanceTo().
    {
        return Vector2dd(element[0], element[1]);
    }
void corecvs::Line2d::normalise (void) [inline]
Normalizes the normal vector without changing the line itself.
With such a line it is easier to compute distance to the line
Reimplemented from corecvs::VectorOperationsBase< Vector3d< ElementType >, ElementType >.
Definition at line 384 of file line.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric(), normal(), and corecvs::VectorOperationsBase< Vector3d< ElementType >, ElementType >::operator/=().
Referenced by normalised().
    {
        double l = normal().l2Metric();
        if (l == 0.0) return;
        operator /=(l);
    }
Line2d corecvs::Line2d::normalised (void) const [inline]
Return a normalized copy of vector.
Reimplemented from corecvs::VectorOperationsBase< Vector3d< ElementType >, ElementType >.
Definition at line 391 of file line.h.
References normalise().
Referenced by corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), and corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif().
    {
        Line2d result = *this;
        result.normalise();
        return result;
    }
template<typename ElementType> Vector3d<ElementType> corecvs::Vector3d< ElementType >::normalizeProjective () [inline, inherited]
Add xy(), yz() and other sub-methods.
Definition at line 152 of file vector3d.h.
Referenced by corecvs::StereoAligner::getBestZ().
    {
        if (this->z() == 0.0)
        {
            return Vector3d<ElementType>(0.0);
        }
        return Vector3d<ElementType>(this->x() / this->z(), this->y() / this->z(), ElementType(1.0));
    }
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::notTooFar (const Vector3d< ElementType > & that, const ElementType & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
template<typename ElementType> corecvs::Vector3d< ElementType >::operator Vector2d< ElementType > () [inline, inherited]
Do the conversion form projective coordinates to the 2D ones.
TODO: Should not do this as an automatic conversion
Definition at line 136 of file vector3d.h.
References corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
    {
        if (this->z() == 0.0)
        {
            return Vector2d<ElementType>(0.0,0.0);
        }
        return Vector2d<ElementType>(this->x() / this->z(), this->y() / this->z());
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator!= (const Vector3d< ElementType > & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator*= (const ElementType & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator+= (const Vector3d< ElementType > & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
Vector3d< ElementType > corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator-= (const Vector3d< ElementType > & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator/= (const ElementType & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
Referenced by normalise().
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator== (const Vector3d< ElementType > & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
double corecvs::Line2d::pointWeight (const Vector2dd & point) const [inline]
Definition at line 439 of file line.h.
References last(), and normal().
Referenced by distanceTo(), and sqDistanceTo().
    {
        return (normal() & point) + last();
    }
void corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
Vector3d< ElementType > * corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const Vector3d< ElementType > * corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
int corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
double corecvs::Line2d::sqDistanceTo (const Vector2dd & point) const [inline]
Definition at line 458 of file line.h.
References normal(), pointWeight(), and corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElementsSq().
    {
        double d = pointWeight(point);
        d *= d;
        double lsq = normal().sumAllElementsSq();
        return (d / lsq);
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
template<typename ElementType> ElementType& corecvs::Vector3d< ElementType >::x () [inline, inherited]
Helper functions to access elements.
Definition at line 52 of file vector3d.h.
Referenced by corecvs::DirectRemapper::_init(), corecvs::AxisAlignedBox3d::_initByLowHigh(), corecvs::Vector3d< double >::accept(), corecvs::Mesh3D::addAOB(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::Matrix33::CrossProductLeft(), OpenGLTools::drawDiamond(), OpenGLTools::drawWiredBox(), Scene3DMouse::dumpPCD(), Scene3DMouse::dumpPLY(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::SpatialGradient::findCornerPoints(), corecvs::Matrix33::FromColumns(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::AxisAlignedBox3d::getPoints(), corecvs::EssentialDecomposition::getScaler(), OpenGLTools::glTranslateVector3dd(), OpenGLTools::glVertexVector3dd(), intersectWith(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), PLYLoader::loadPLY(), corecvs::Matrix33::Matrix33(), corecvs::Matrix44::Matrix44(), corecvs::Vector3d< double >::normalizeProjective(), corecvs::Vector3d< ElementType >::operator Vector2d< ElementType >(), corecvs::SortSwarmPointX::operator()(), corecvs::operator*(), corecvs::EssentialEstimator::CostFunctionBase::packState(), DistortionWidget::printVectorPair(), UniversalRectifier::recalculate(), CloudViewDialog::resetCamera(), corecvs::Rotate(), RectifyParametersControlWidget::setManualTab(), corecvs::Matrix44::Shift(), corecvs::Matrix33::VectorByVector(), corecvs::AxisAlignedBox3d::width(), corecvs::Vector3d< double >::xy(), and corecvs::Vector3d< double >::xz().
    {
        return (*this)[0];
    }
template<typename ElementType> const ElementType& corecvs::Vector3d< ElementType >::x () const [inline, inherited]
Constant versions of helper functions for read-only form constant vectors.
Definition at line 72 of file vector3d.h.
    {
        return (*this)[0];
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector3d< ElementType >::xy () const [inline, inherited]
Definition at line 88 of file vector3d.h.
    {
        return Vector2d<ElementType>(x(), y());
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector3d< ElementType >::xz () const [inline, inherited]
Definition at line 93 of file vector3d.h.
    {
        return Vector2d<ElementType>(x(), z());
    }
template<typename ElementType> ElementType& corecvs::Vector3d< ElementType >::y () [inline, inherited]
Definition at line 57 of file vector3d.h.
Referenced by corecvs::DirectRemapper::_init(), corecvs::AxisAlignedBox3d::_initByLowHigh(), corecvs::Vector3d< double >::accept(), corecvs::Mesh3D::addAOB(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::Matrix33::CrossProductLeft(), OpenGLTools::drawDiamond(), Scene3DMouse::drawMyself(), OpenGLTools::drawWiredBox(), Scene3DMouse::dumpPCD(), Scene3DMouse::dumpPLY(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::SpatialGradient::findCornerPoints(), corecvs::Matrix33::FromColumns(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::AxisAlignedBox3d::getPoints(), corecvs::EssentialDecomposition::getScaler(), OpenGLTools::glTranslateVector3dd(), corecvs::AxisAlignedBox3d::height(), intersectWith(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), PLYLoader::loadPLY(), corecvs::Matrix33::Matrix33(), corecvs::Matrix44::Matrix44(), corecvs::Vector3d< double >::normalizeProjective(), corecvs::Vector3d< ElementType >::operator Vector2d< ElementType >(), corecvs::SortSwarmPointY::operator()(), corecvs::operator*(), corecvs::EssentialEstimator::CostFunctionBase::packState(), DistortionWidget::printVectorPair(), CloudViewDialog::resetCamera(), corecvs::Rotate(), RectifyParametersControlWidget::setManualTab(), corecvs::Matrix44::Shift(), corecvs::Matrix33::VectorByVector(), corecvs::Vector3d< double >::xy(), and corecvs::Vector3d< double >::yz().
    {
        return (*this)[1];
    }
template<typename ElementType> const ElementType& corecvs::Vector3d< ElementType >::y () const [inline, inherited]
Definition at line 77 of file vector3d.h.
    {
        return (*this)[1];
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector3d< ElementType >::yz () const [inline, inherited]
Definition at line 98 of file vector3d.h.
    {
        return Vector2d<ElementType>(y(), z());
    }
template<typename ElementType> ElementType& corecvs::Vector3d< ElementType >::z () [inline, inherited]
Definition at line 62 of file vector3d.h.
Referenced by corecvs::DirectRemapper::_init(), corecvs::AxisAlignedBox3d::_initByLowHigh(), corecvs::Vector3d< double >::accept(), corecvs::Mesh3D::addAOB(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::Matrix33::CrossProductLeft(), corecvs::AxisAlignedBox3d::depth(), OpenGLTools::drawDiamond(), Scene3DMouse::drawMyself(), OpenGLTools::drawWiredBox(), Scene3DMouse::dumpPCD(), Scene3DMouse::dumpPLY(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::SpatialGradient::findCornerPoints(), corecvs::Matrix33::FromColumns(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::AxisAlignedBox3d::getPoints(), corecvs::EssentialDecomposition::getScaler(), OpenGLTools::glTranslateVector3dd(), intersectWith(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), PLYLoader::loadPLY(), corecvs::Matrix33::Matrix33(), corecvs::Matrix44::Matrix44(), corecvs::Vector3d< double >::normalizeProjective(), corecvs::Vector3d< ElementType >::operator Vector2d< ElementType >(), corecvs::SortSwarmPointZ::operator()(), corecvs::operator*(), corecvs::EssentialEstimator::CostFunctionBase::packState(), DistortionWidget::printVectorPair(), UniversalRectifier::recalculate(), CloudViewDialog::resetCamera(), corecvs::Rotate(), RectifyParametersControlWidget::setManualTab(), corecvs::Matrix44::Shift(), corecvs::FlowSimuator::simulateFlow(), corecvs::Matrix33::VectorByVector(), corecvs::Vector3d< double >::xz(), and corecvs::Vector3d< double >::yz().
    {
        return (*this)[2];
    }
template<typename ElementType> const ElementType& corecvs::Vector3d< ElementType >::z () const [inline, inherited]
Definition at line 82 of file vector3d.h.
    {
        return (*this)[2];
    }
Friends And Related Function Documentation
ElementType operator& (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
Vector3d< ElementType > operator* (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
Vector3d< ElementType > operator* (const ElementType & c, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
Vector3d< ElementType > operator* (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
Vector3d< ElementType > operator+ (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
Vector3d< ElementType > operator- (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
Vector3d< ElementType > operator/ (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
Vector3d< ElementType > operator/ (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, VectorOperationsBase< Vector3d< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
template<typename ElementType> Vector3d operator^ (const Vector3d< ElementType > & V, const Vector3d< ElementType > & U) [friend, inherited]
This function implements the vector cross product (See http://en.wikipedia.org/wiki/Vector_product).
It is computed as follows:
Parameters:
[in] V the first vector
[in] U the second vector
Returns:
vector
Definition at line 121 of file vector3d.h.
    {
        ElementType x, y, z;
        x = V.y() * U.z() - U.y() * V.z();
        y = U.x() * V.z() - U.z() * V.x();
        z = U.y() * V.x() - U.x() * V.y();
        return Vector3d(x, y, z);
    }
Member Data Documentation
ElementType corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
Referenced by last(), and normal().
const int corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
The documentation for this class was generated from the following file:
core/geometry/line.h