DeepView: SobelParametersControlWidget Class Reference
SobelParametersControlWidget Class Reference
#include <sobelParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
SobelParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~SobelParametersControlWidget ()
SobelParameters * createParameters () const
void setParameters (const SobelParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_SobelParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file sobelParametersControlWidget.h.
Constructor & Destructor Documentation
SobelParametersControlWidget::SobelParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file sobelParametersControlWidget.cpp.
References mUi, and paramsChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::SobelParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->mixingTypeComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->horizontalCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->verticalCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
}
SobelParametersControlWidget::~SobelParametersControlWidget ()
Definition at line 28 of file sobelParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void SobelParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file sobelParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
SobelParameters * SobelParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 50 of file sobelParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    SobelParameters *result = new SobelParameters(
          static_cast<SobelMixingType::SobelMixingType>(mUi->mixingTypeComboBox->currentIndex())
        , mUi->horizontalCheckBox->isChecked()
        , mUi->verticalCheckBox->isChecked()
    );
    return result;
}
virtual BaseReflectionStatic* SobelParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 25 of file sobelParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void SobelParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 34 of file sobelParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    SobelParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void SobelParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by setParameters(), and SobelParametersControlWidget().
void SobelParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 42 of file sobelParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    SobelParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void SobelParametersControlWidget::setParameters (const SobelParameters & input)
Definition at line 66 of file sobelParametersControlWidget.cpp.
References SobelParameters::horizontal(), SobelParameters::mixingType(), mUi, paramsChanged(), and SobelParameters::vertical().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->mixingTypeComboBox->setCurrentIndex(input.mixingType());
    mUi->horizontalCheckBox->setChecked(input.horizontal());
    mUi->verticalCheckBox->setChecked(input.vertical());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void SobelParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 77 of file sobelParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    SobelParameters *inputCasted = static_cast<SobelParameters *>(input);
    setParameters(*inputCasted);
}
void SobelParametersControlWidget::valueChanged () [signal]
Member Data Documentation
bool SobelParametersControlWidget::autoInit [private]
Definition at line 45 of file sobelParametersControlWidget.h.
Ui_SobelParametersControlWidget* SobelParametersControlWidget::mUi [private]
Definition at line 44 of file sobelParametersControlWidget.h.
Referenced by createParameters(), setParameters(), SobelParametersControlWidget(), and ~SobelParametersControlWidget().
QString SobelParametersControlWidget::rootPath [private]
Definition at line 46 of file sobelParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/sobelParametersControlWidget.h
utils/filters/ui/sobelParametersControlWidget.cpp