DeepView: OpenCvFileCapture::SpinThread Class Reference
OpenCvFileCapture::SpinThread Class Reference
Public Member Functions
SpinThread (AbstractFileCapture *pInterface, int delay, ImageCaptureInterface::FramePair &framePair, cv::VideoCapture &capture, string const &path)
virtual bool grabFramePair ()
virtual void run ()
void togglePause ()
void nextFrame ()
Protected Member Functions
void pause ()
Protected Attributes
ImageCaptureInterface::FramePair & mFramePair
AbstractFileCapture * mInterface
Private Attributes
cv::VideoCapture & mCapture
string const & mPath
int mTry
Static Private Attributes
static cint maxNumberOfTries = 5
Detailed Description
Definition at line 19 of file openCvFileCapture.h.
Constructor & Destructor Documentation
OpenCvFileCapture::SpinThread::SpinThread (AbstractFileCapture * pInterface, int delay, ImageCaptureInterface::FramePair & framePair, cv::VideoCapture & capture, string const & path)
Definition at line 44 of file openCvFileCapture.cpp.
    : AbstractFileCaptureSpinThread(pInterface, delay, framePair)
    , mCapture(capture)
    , mPath(path)
    , mTry(0)
{
}
Member Function Documentation
bool OpenCvFileCapture::SpinThread::grabFramePair () [virtual]
Implements AbstractFileCaptureSpinThread.
Definition at line 57 of file openCvFileCapture.cpp.
References OpenCvHelper::captureImageCopyToBuffer(), and OpenCvFileCapture::mCapture.
{
    uint width  = mCapture.get(CV_CAP_PROP_FRAME_WIDTH);
    uint height = mCapture.get(CV_CAP_PROP_FRAME_HEIGHT);
    delete mFramePair.bufferLeft;
    delete mFramePair.bufferRight;
    mFramePair.bufferLeft = new G12Buffer(height, width, false);
    mFramePair.bufferRight = NULL;
    // OpenCV does not set timestamps for the frames
    mFramePair.leftTimeStamp  = 0;
    mFramePair.rightTimeStamp = 0;
    if (OpenCvHelper::captureImageCopyToBuffer(mCapture, mFramePair.bufferLeft))
    {
        mFramePair.bufferRight = new G12Buffer(mFramePair.bufferLeft);
        mTry = 0;
        return true;
    }
    // Restart capture
    pause();
    mCapture.release();
    mCapture.open(mPath);
    ++mTry;
    if (mTry < maxNumberOfTries)
        return grabFramePair();
    return false;
}
void AbstractFileCaptureSpinThread::nextFrame () [inherited]
Definition at line 63 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::mNextFrameNeeded.
Referenced by AbstractFileCapture::nextFrame().
{
    mNextFrameNeeded = true;
}
void AbstractFileCaptureSpinThread::pause () [protected, inherited]
Definition at line 68 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::mInterface, AbstractFileCaptureSpinThread::mPaused, and AbstractFileCapture::notifyAboutStreamPaused().
{
    mPaused = true;
    mInterface->notifyAboutStreamPaused();
}
void AbstractFileCaptureSpinThread::run () [virtual, inherited]
Definition at line 17 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::grabFramePair(), AbstractFileCaptureSpinThread::mDelay, AbstractFileCaptureSpinThread::mInterface, AbstractFileCaptureSpinThread::mNextFrameNeeded, AbstractFileCaptureSpinThread::mPaused, AbstractFileCapture::mTimeStamp, ImageCaptureInterface::notifyAboutNewFrame(), AbstractFileCapture::protectFrameMutex(), AbstractFileCapture::shouldStopSpinThread, AbstractFileCapture::spinThreadRunMutex(), and frame_data_t::timestamp.
{
    if (!grabFramePair())  // We must get a frame before querying for properties
    {
        printf("No frames.\n");
        return;
    }
    frame_data_t frameData;
    frameData.timestamp = mInterface->mTimeStamp;
    mInterface->notifyAboutNewFrame(frameData);
    while (mInterface->spinThreadRunMutex().tryLock())
    {
        if (mDelay != 0)
            msleep(mDelay);
        if (!mPaused || mNextFrameNeeded)
        {
            mNextFrameNeeded = false;
            mInterface->protectFrameMutex().lock();
                if (!grabFramePair()) {
                    printf("No more frames.\n");
                }
                else {
                    frame_data_t frameData;
                    frameData.timestamp = mInterface->mTimeStamp;
                    mInterface->notifyAboutNewFrame(frameData);
                }
            mInterface->protectFrameMutex().unlock();
        }
        mInterface->spinThreadRunMutex().unlock();
        if (mInterface->shouldStopSpinThread) {
            break;
        }
    }
}
void AbstractFileCaptureSpinThread::togglePause () [inherited]
Definition at line 58 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::mPaused.
Referenced by AbstractFileCapture::pauseCapture().
{
    mPaused = !mPaused;
}
Member Data Documentation
cint OpenCvFileCapture::SpinThread::maxNumberOfTries = 5 [static, private]
Definition at line 31 of file openCvFileCapture.h.
cv::VideoCapture& OpenCvFileCapture::SpinThread::mCapture [private]
Definition at line 33 of file openCvFileCapture.h.
ImageCaptureInterface::FramePair& AbstractFileCaptureSpinThread::mFramePair [protected, inherited]
Definition at line 22 of file abstractFileCaptureSpinThread.h.
AbstractFileCapture* AbstractFileCaptureSpinThread::mInterface [protected, inherited]
Definition at line 23 of file abstractFileCaptureSpinThread.h.
Referenced by AbstractFileCaptureSpinThread::pause(), and AbstractFileCaptureSpinThread::run().
string const& OpenCvFileCapture::SpinThread::mPath [private]
Definition at line 34 of file openCvFileCapture.h.
int OpenCvFileCapture::SpinThread::mTry [private]
Definition at line 35 of file openCvFileCapture.h.
The documentation for this class was generated from the following files:
utils/framesources/openCvFileCapture.h
utils/framesources/openCvFileCapture.cpp