DeepView: corecvs::Pin Class Reference
corecvs::Pin Class Reference
#include <pins.h>
Public Types
enum PinType { INPUT_PIN, OUTPUT_PIN }
Public Member Functions
Pin (FilterBlock *_parent, PinType _type, const char *name="none")
virtual ~Pin ()
int getInstanceId () const
virtual void setInstanceId (int)
virtual void clear ()
void breakConnection ()
virtual const char * getTypeName () const
virtual bool isEmpty ()
virtual bool setPin (Pin *, bool=false)
virtual bool getPin (G12Buffer *&, bool=false)
virtual bool getPin (char *&, bool=false)
virtual void initPin (G12Buffer *)
virtual XMLNode * serialize (XMLNode *doc, bool outerPin)
virtual void deserialize (XMLNode *)
Public Attributes
char * instanceName
PinType type
FilterBlock * parent
int instanceId
Pin * takeFrom
Detailed Description
Definition at line 20 of file pins.h.
Member Enumeration Documentation
enum corecvs::Pin::PinType
Enumerator:
INPUT_PIN
OUTPUT_PIN
Definition at line 23 of file pins.h.
                {
        INPUT_PIN,
        OUTPUT_PIN
   };
Constructor & Destructor Documentation
corecvs::Pin::Pin (FilterBlock * _parent, PinType _type, const char * name = "none") [inline]
Definition at line 28 of file pins.h.
                                                                       :
       type(_type),
       parent(_parent),
       takeFrom(NULL)
   {
       instanceName = strdup(name);
   }
corecvs::Pin::~Pin () [virtual]
Definition at line 10 of file pins.cpp.
References clear(), and instanceName.
{
//   if (!parent->isOuterPin(this))  free(instanceName);
   free(instanceName);
   clear();
}
Member Function Documentation
void corecvs::Pin::breakConnection () [inline]
Reimplemented in corecvs::OutputPin, and corecvs::InputPin.
Definition at line 43 of file pins.h.
{ takeFrom = NULL; }
virtual void corecvs::Pin::clear () [inline, virtual]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 41 of file pins.h.
Referenced by ~Pin().
{}
void corecvs::Pin::deserialize (XMLNode * node) [virtual]
Reimplemented in corecvs::OutputPin, corecvs::InputPin, corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 32 of file pins.cpp.
References tinyxml2::XMLElement::Attribute(), corecvs::FilterGraph::blockByName(), corecvs::FilterBlock::COMPOUND_FILTER, instanceName, tinyxml2::XMLElement::IntAttribute(), corecvs::FilterBlock::outPinById(), parent, corecvs::FilterBlock::parent, setInstanceId(), corecvs::FilterBlock::sort, takeFrom, and tinyxml2::XMLNode::ToElement().
Referenced by corecvs::FilterBlock::deserializePins().
{
    XMLElement* mPin = node->ToElement();
    setInstanceId(mPin->IntAttribute("id"));
    if (parent->sort != FilterBlock::COMPOUND_FILTER)
    {   free(instanceName);
        instanceName = strdup(mPin->Attribute("name"));
    }
    if ( mPin->Attribute("takeFromBlock") &&
         parent &&
         parent->parent )
    {
        FilterBlock* block = parent->parent->blockByName(mPin->Attribute("takeFromBlock"));
        if (block)
            takeFrom = block->outPinById(mPin->IntAttribute("takeFromPin"));
    }
}
int corecvs::Pin::getInstanceId () const [inline]
Definition at line 38 of file pins.h.
Referenced by corecvs::FilterBlock::IdPredicate::operator()().
{ return instanceId; }
virtual bool corecvs::Pin::getPin (G12Buffer *& , bool = false) [inline, virtual]
Reimplemented in corecvs::OutputPin, and corecvs::G12Pin.
Definition at line 54 of file pins.h.
Referenced by corecvs::G12Pin::setPin(), corecvs::TxtPin::setPin(), and corecvs::ExtraTxtPin< TypeOfPin >::setPin().
   {   std::cerr << "error G12\n";
       return false;
   }
virtual bool corecvs::Pin::getPin (char *& , bool = false) [inline, virtual]
Reimplemented in corecvs::OutputPin, and corecvs::TxtPin.
Definition at line 58 of file pins.h.
   {   std::cerr << "error Txt\n";
       return false;
   }
virtual const char* corecvs::Pin::getTypeName () const [inline, virtual]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 47 of file pins.h.
Referenced by serialize().
{ return "none"; }
virtual void corecvs::Pin::initPin (G12Buffer *) [inline, virtual]
Reimplemented in corecvs::G12Pin.
Definition at line 64 of file pins.h.
{ std::cerr << "error G12 initPin"; }
virtual bool corecvs::Pin::isEmpty () [inline, virtual]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 49 of file pins.h.
{ return false; }
XMLNode * corecvs::Pin::serialize (XMLNode * doc, bool outerPin) [virtual]
Reimplemented in corecvs::OutputPin, and corecvs::InputPin.
Definition at line 17 of file pins.cpp.
References tinyxml2::XMLNode::GetDocument(), corecvs::FilterBlock::getFullName(), getTypeName(), tinyxml2::XMLNode::InsertEndChild(), instanceId, instanceName, tinyxml2::XMLDocument::NewElement(), parent, tinyxml2::XMLElement::SetAttribute(), and takeFrom.
{
    XMLElement* mPin = node->GetDocument()->NewElement("pin");
    mPin->SetAttribute("type", getTypeName());
    mPin->SetAttribute("id", instanceId);
    mPin->SetAttribute("name", instanceName);
    if (!isOuterPin && takeFrom)
    {   mPin->SetAttribute("takeFromBlock", takeFrom->parent->getFullName().c_str());
        mPin->SetAttribute("takeFromPin",   takeFrom->instanceId);
    }
    XMLNode* element = node->InsertEndChild(mPin);
    return element;
}
virtual void corecvs::Pin::setInstanceId (int) [inline, virtual]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 39 of file pins.h.
Referenced by deserialize().
{}
virtual bool corecvs::Pin::setPin (Pin * , bool = false) [inline, virtual]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 50 of file pins.h.
Referenced by DiagramScene::mouseReleaseEvent().
   {   std::cerr << "error Abstract\n";
       return false;
   }
Member Data Documentation
int corecvs::Pin::instanceId
Definition at line 72 of file pins.h.
Referenced by serialize().
char* corecvs::Pin::instanceName
Definition at line 69 of file pins.h.
Referenced by deserialize(), FilterPinPresentation::FilterPinPresentation(), FilterGraphPresentation::nameChanged(), corecvs::FilterBlock::NamePredicate::operator()(), serialize(), and ~Pin().
FilterBlock* corecvs::Pin::parent
Definition at line 71 of file pins.h.
Referenced by corecvs::CompoundFilter::addPin(), deserialize(), FilterPinPresentation::FilterPinPresentation(), and serialize().
Pin* corecvs::Pin::takeFrom
Reimplemented in corecvs::InputPin.
Definition at line 73 of file pins.h.
Referenced by corecvs::FilterGraph::breakConnection(), corecvs::FilterGraph::connect(), deserialize(), FilterPinPresentation::FilterPinPresentation(), and serialize().
PinType corecvs::Pin::type
Definition at line 70 of file pins.h.
Referenced by corecvs::FilterGraph::connect(), FilterPinPresentation::drawPinName(), and corecvs::FilterBlock::isOuterPin().
The documentation for this class was generated from the following files:
core/filters/blocks/pins.h
core/filters/blocks/pins.cpp