DeepView: corecvs::Vector2d< ElementType > Class Template Reference
corecvs::Vector2d< ElementType > Class Template Reference
#include <vector2d.h>
Public Types
enum FieldId { FIELD_X = 0, FIELD_Y = 1 }
typedef ReflectionHelper
< ElementType >::Type ReflectionType
typedef ElementType InnerElementType
Public Member Functions
Vector2d (const ElementType &_x, const ElementType &_y)
Vector2d (const BaseClass &V)
Vector2d (const ElementType &x)
Vector2d ()
ElementType & x ()
ElementType & y ()
const ElementType & x () const
const ElementType & y () const
double getLengthStable () const
double argument () const
Vector2d< ElementType > leftNormal () const
Vector2d< ElementType > rightNormal () const
double sineTo (const Vector2d &other) const
double cosineTo (const Vector2d &other) const
double parallelogramOrientedAreaTo (const Vector2d &other)
The oriented area of the parallelogram built on the two vectors: this, and the given one.
double triangleOrientedAreaTo (const Vector2d &other)
void mapToRect (const Vector2d< ElementType > &low, const Vector2d< ElementType > &high)
bool isInRect (const Vector2d< ElementType > &low, const Vector2d< ElementType > &high) const
template<class VisitorType >
void accept (VisitorType &visitor)
int size () const
ElementType & operator[] (int n)
const ElementType & operator[] (int n) const
ElementType & at (int n)
const ElementType & at (int n) const
Vector2d< ElementType > createVector (int) const
Vector2d< ElementType > * realThis ()
Static cast functions.
const Vector2d< ElementType > * realThis () const
bool operator== (const Vector2d< ElementType > &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const Vector2d< ElementType > &that) const
Inequality operator.
bool notTooFar (const Vector2d< ElementType > &that, const ElementType &epsilon=ElementType(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const Vector2d< ElementType > &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const Vector2d< ElementType > &V)
VectorOperationsBase & operator*= (const ElementType &c)
VectorOperationsBase & operator/= (const ElementType &c)
Vector2d< ElementType > operator- () const
Negative operator.
ElementType sumAllElements () const
Sum of the elements of the vector.
ElementType mulAllElements () const
Product of all elements of the vector.
ElementType sumAllElementsSq () const
Sum of the squares of element of the vector.
ElementType l2Metric () const
Euclidean distance.
ElementType operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
Vector2d< ElementType > normalised () const
Return a normalized copy of vector.
Vector2d< ElementType > cloneVector () const
Return copy of vector.
ElementType l1Metric () const
Sum of the absolute values of element of the vector.
ElementType lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
ElementType minimum () const
ElementType maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
Static Public Member Functions
static Vector2d FromPolar (double angle, double length=1.0)
Return the vector from angle and length.
static Reflection staticInit ()
Public Attributes
ElementType element [length]
Static Public Attributes
static Reflection reflect = Vector2d<ElementType>::staticInit()
static const int LENGTH
Protected Types
typedef FixedVectorBase
< Vector2d< ElementType >
, ElementType, 2 > BaseClass
Friends
Vector2d< ElementType > operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
Vector2d< ElementType > operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
Vector2d< ElementType > operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
Vector2d< ElementType > operator* (const ElementType &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
Vector2d< ElementType > operator* (const VectorOperationsBase &V, const ElementType &c)
Vector2d< ElementType > operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
Vector2d< ElementType > operator/ (const VectorOperationsBase &V, const ElementType &c)
Operator * does the component-specific multiplication by constant
.
ElementType operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
template<typename ElementType>
class corecvs::Vector2d< ElementType >
Definition at line 28 of file vector2d.h.
Member Typedef Documentation
template<typename ElementType> typedef FixedVectorBase<Vector2d<ElementType>, ElementType, 2> corecvs::Vector2d< ElementType >::BaseClass [protected]
Reimplemented from corecvs::FixedVectorBase< Vector2d< ElementType >, ElementType, 2 >.
Reimplemented in Triangulation::Point.
Definition at line 31 of file vector2d.h.
typedef ElementType corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
template<typename ElementType> typedef ReflectionHelper<ElementType>::Type corecvs::Vector2d< ElementType >::ReflectionType
Reimplemented from corecvs::VectorOperationsBase< Vector2d< ElementType >, ElementType >.
Definition at line 172 of file vector2d.h.
Member Enumeration Documentation
template<typename ElementType> enum corecvs::Vector2d::FieldId
Enumerator:
FIELD_X
FIELD_Y
Definition at line 34 of file vector2d.h.
                 {
        FIELD_X = 0,
        FIELD_Y = 1
    };
Constructor & Destructor Documentation
template<typename ElementType> corecvs::Vector2d< ElementType >::Vector2d (const ElementType & _x, const ElementType & _y) [inline]
Definition at line 39 of file vector2d.h.
    {
        (*this)[0] = _x;
        (*this)[1] = _y;
    }
template<typename ElementType> corecvs::Vector2d< ElementType >::Vector2d (const BaseClass & V) [inline]
Definition at line 46 of file vector2d.h.
: BaseClass(V) {}
template<typename ElementType> corecvs::Vector2d< ElementType >::Vector2d (const ElementType & x) [inline, explicit]
Definition at line 47 of file vector2d.h.
: BaseClass(x) {}
template<typename ElementType> corecvs::Vector2d< ElementType >::Vector2d () [inline]
Definition at line 48 of file vector2d.h.
Referenced by corecvs::Vector2d< Int32x4 >::argument(), corecvs::Vector2d< Int32x4 >::FromPolar(), corecvs::Vector2d< Int32x4 >::leftNormal(), and corecvs::Vector2d< Int32x4 >::rightNormal().
: BaseClass() {}
Member Function Documentation
template<typename ElementType> template<class VisitorType > void corecvs::Vector2d< ElementType >::accept (VisitorType & visitor) [inline]
Reimplemented from corecvs::VectorOperationsBase< Vector2d< ElementType >, ElementType >.
Definition at line 184 of file vector2d.h.
    {
        visitor.visit(x(), static_cast<const ReflectionType *>(reflect.fields[FIELD_X]));
        visitor.visit(y(), static_cast<const ReflectionType *>(reflect.fields[FIELD_Y]));
    }
void corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
template<typename ElementType> double corecvs::Vector2d< ElementType >::argument () const [inline]
Definition at line 88 of file vector2d.h.
    {
        if (*this == Vector2d(0.0))
            return 0.0;
        return atan2(y(),x());
    }
ElementType& corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
Vector2d< ElementType > corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
template<typename ElementType> double corecvs::Vector2d< ElementType >::cosineTo (const Vector2d< ElementType > & other) const [inline]
Definition at line 123 of file vector2d.h.
Referenced by Triangulation::Edge::cosAngle().
    {
        double thisLength  = !(*this);
        double otherLength = !other;
        if (thisLength == 0 || otherLength == 0)
          return 0;
        return ((*this) & other) / (thisLength * otherLength);
    }
Vector2d< ElementType > corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
template<typename ElementType> static Vector2d corecvs::Vector2d< ElementType >::FromPolar (double angle, double length = 1.0) [inline, static]
Return the vector from angle and length.
Definition at line 151 of file vector2d.h.
    {
        return Vector2d(cos(angle), sin(angle)) * length;
    }
template<typename ElementType> double corecvs::Vector2d< ElementType >::getLengthStable () const [inline]
Definition at line 70 of file vector2d.h.
Referenced by corecvs::Matrix::svd().
    {
        double ma = (x() > 0) ? x() : -x();
        double mb = (y() > 0) ? y() : -y();
        if (ma == 0 && mb == 0) return 0;
        if (ma > mb)
        {
            double div = (mb / ma);
            return ma * sqrt(1.0 + div * div );
        }
        else
        {
            double div = (ma / mb);
            return mb * sqrt(1.0 + div * div );
        }
    }
bool corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::isInHypercube (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & low, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
Referenced by corecvs::Vector2d< Int32x4 >::isInRect().
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
template<typename ElementType> bool corecvs::Vector2d< ElementType >::isInRect (const Vector2d< ElementType > & low, const Vector2d< ElementType > & high) const [inline]
Definition at line 164 of file vector2d.h.
Referenced by corecvs::FlowSimuator::simulateFlow().
    {
        return this->isInHypercube(low, high);
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector2d< ElementType >::leftNormal () const [inline]
Definition at line 102 of file vector2d.h.
Referenced by corecvs::Line2d::fromRay(), corecvs::Buffer3d::getNearestPoint(), corecvs::DistPointsFunction::operator()(), corecvs::Vector2d< Int32x4 >::parallelogramOrientedAreaTo(), and corecvs::Vector2d< Int32x4 >::triangleOrientedAreaTo().
    {
      return Vector2d(-y(),x());
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
template<typename ElementType> void corecvs::Vector2d< ElementType >::mapToRect (const Vector2d< ElementType > & low, const Vector2d< ElementType > & high) [inline]
Definition at line 156 of file vector2d.h.
Referenced by corecvs::KLTGenerator< InterpolationType >::kltIteration().
    {
        if (this->element[0] <  low.element[0]) this->element[0] =  low.element[0];
        if (this->element[1] <  low.element[1]) this->element[1] =  low.element[1];
        if (this->element[0] > high.element[0]) this->element[0] = high.element[0];
        if (this->element[1] > high.element[1]) this->element[1] = high.element[1];
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
void corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Definition at line 407 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
Vector2d< ElementType > corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Definition at line 420 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
bool corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::notTooFar (const Vector2d< ElementType > & that, const ElementType & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator!= (const Vector2d< ElementType > & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator*= (const ElementType & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator+= (const Vector2d< ElementType > & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
Vector2d< ElementType > corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator-= (const Vector2d< ElementType > & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator/= (const ElementType & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::operator== (const Vector2d< ElementType > & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
ElementType& corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
template<typename ElementType> double corecvs::Vector2d< ElementType >::parallelogramOrientedAreaTo (const Vector2d< ElementType > & other) [inline]
The oriented area of the parallelogram built on the two vectors: this, and the given one.
Definition at line 138 of file vector2d.h.
    {
        return *this & other.leftNormal();
    }
void corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
Vector2d< ElementType > * corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const Vector2d< ElementType > * corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector2d< ElementType >::rightNormal () const [inline]
Definition at line 107 of file vector2d.h.
Referenced by corecvs::Vector2d< Int32x4 >::sineTo().
    {
      return Vector2d(y(),-x());
    }
template<typename ElementType> double corecvs::Vector2d< ElementType >::sineTo (const Vector2d< ElementType > & other) const [inline]
Definition at line 112 of file vector2d.h.
Referenced by corecvs::AnglePointsFunction::operator()().
    {
        double thisLength  = !(*this);
        double otherLength = !other;
        if (thisLength == 0.0 || otherLength == 0.0)
          return 0.0;
        double tangentCross = (*this) & other.rightNormal();
        return tangentCross / (thisLength * otherLength);
    }
int corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
template<typename ElementType> static Reflection corecvs::Vector2d< ElementType >::staticInit () [inline, static]
Definition at line 174 of file vector2d.h.
    {
        Reflection reflection;
        reflection.fields.push_back( new ReflectionType(FIELD_X, ElementType(0), "x") );
        reflection.fields.push_back( new ReflectionType(FIELD_Y, ElementType(0), "y") );
        return reflection;
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector2d< ElementType > , ElementType >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
template<typename ElementType> double corecvs::Vector2d< ElementType >::triangleOrientedAreaTo (const Vector2d< ElementType > & other) [inline]
Definition at line 143 of file vector2d.h.
Referenced by Triangulation::orientation().
    {
        return (*this & other.leftNormal()) / 2;
    }
template<typename ElementType> ElementType& corecvs::Vector2d< ElementType >::x () [inline]
Definition at line 50 of file vector2d.h.
Referenced by corecvs::Line2d::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::Vector2d< Int32x4 >::accept(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSE(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSEUnif(), corecvs::Buffer3d::addPoints(), corecvs::Vector2d< Int32x4 >::argument(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), Triangulation::classify(), corecvs::Rectangle< ElementType >::clipCohenSutherland(), Scene3D::commonSetup(), corecvs::SegmentPayload::compensateDesync(), corecvs::DirectRemapper::DirectRemapper(), DistortionWidget::doManualTransform(), FlowDrawer::draw(), drawArc(), drawCircle(), corecvs::RGB24Buffer::drawCorrespondanceList(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer3(), drawLine(), corecvs::RGB24Buffer::drawLine(), corecvs::VJSimpleClassifier::drawPattern(), drawPie(), drawSquare(), corecvs::FlowBuffer::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), corecvs::FCostFunction::function(), corecvs::FCostFunction::functionPro(), corecvs::G12Buffer3d::G12Buffer3d(), corecvs::StereoAligner::getAlignmentTransformation(), FlowColorer::getColor(), StereoColorer::getColor(), corecvs::EllipticalApproximation::getDeviationSquare(), corecvs::Triangulator::getDisparity(), corecvs::StereoAligner::getDistortion(), corecvs::EllipticalApproximation::getEllipseAxis(), corecvs::EllipticalApproximation::getEllipseAxisSquare(), corecvs::EllipticalApproximation::getEllipseOrientation(), corecvs::EssentialEstimator::getEssentialLSE(), corecvs::CameraIntrinsics::getHFov(), corecvs::getInputDisparity< DisparityBuffer >(), corecvs::CameraIntrinsics::getInvKMatrix(), corecvs::CameraIntrinsics::getInvKMatrix33(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::CameraIntrinsics::getKMatrix(), corecvs::CameraIntrinsics::getKMatrix33(), corecvs::StereoAligner::getLateralCorrection(), corecvs::Buffer3d::getLength(), corecvs::Vector2d< Int32x4 >::getLengthStable(), corecvs::EllipticalApproximation::getMainDirection(), corecvs::ModelToRadialCorrection::getModel(), corecvs::Buffer3d::getNearestPoint(), corecvs::CorrespondanceList::getNormalizingTransform(), FlowColorer::getPacked(), StereoColorer::getPacked(), corecvs::EllipticalApproximation::getPerAxisDeviation(), corecvs::Rectangle< ElementType >::getPointCode(), corecvs::ModelToRadialCorrection::getRadial(), corecvs::Element6D::hasFlow(), corecvs::FlowBuffer::invert(), corecvs::FlowBuffer::isElementKnown(), corecvs::PunchedBufferOperations< SixDBuffer, SixDBufferBase::InternalElementType >::isElementKnownVec(), Triangulation::PointGroup::isNear(), corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord(), corecvs::AbstractBuffer< SegmentType * >::isValidCoord(), corecvs::AbstractContiniousBuffer< double, int >::isValidCoordBl(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::Vector2d< Int32x4 >::leftNormal(), DistortionWidget::loadPoints(), corecvs::CorrespondanceList::makePrecise(), corecvs::CorrespondanceList::makePreciseCopy(), corecvs::DistortionCorrectTransform::map(), corecvs::RadialCorrection::map(), Triangulation::mate(), corecvs::EllipticalApproximation::mu11(), corecvs::Matrix33::mulBy2dLeft(), corecvs::Matrix33::mulBy2dRight(), corecvs::HomographyReconstructor::noramlisePoints(), corecvs::CamerasCalibrationFunc::operator()(), corecvs::StraightFunc::operator()(), corecvs::AngleFunction::operator()(), corecvs::AnglePointsFunction::operator()(), corecvs::DistPointsFunction::operator()(), corecvs::CFlowBufferToucherOperator< swap >::operator()(), corecvs::RadialFunc::operator()(), corecvs::SortSwarmPointTexX::operator()(), corecvs::Map2DFunction< Map2D >::operator()(), corecvs::RadialCorrection::operator()(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator()(), Triangulation::Point::operator<(), Triangulation::Point::operator=(), Triangulation::Point::operator>(), corecvs::FloatFlowBuffer::preciseFlowCalc(), DistortionWidget::printVectorPair(), corecvs::Matrix33::Projective(), corecvs::Matrix33::ProjectiveByPoints(), Triangulation::PointGroup::push_back(), Core2Qt::QPointFromVector2d32(), Core2Qt::QPointFromVector2dd(), UniversalRectifier::recalculate(), corecvs::Vector2d< Int32x4 >::rightNormal(), Triangulation::Edge::rot(), corecvs::VJPattern::scale(), corecvs::Matrix33::Scale2(), corecvs::FlowBuffer::setElementUnknown(), corecvs::PunchedBufferOperations< SixDBuffer, SixDBufferBase::InternalElementType >::setElementUnknownVec(), corecvs::DistortionCorrectTransform::setRadius(), corecvs::DistortionCorrectTransform::setZ(), corecvs::Matrix33::ShiftProj(), DistortionWidget::showBufferChanged(), corecvs::SixDBuffer::SixDBuffer(), corecvs::FlowBuffer::toVectorForm(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateToDB(), and DistortionWidget::updateAdditionalData().
    {
        return (*this)[0];
    }
template<typename ElementType> const ElementType& corecvs::Vector2d< ElementType >::x () const [inline]
Definition at line 60 of file vector2d.h.
    {
        return (*this)[0];
    }
template<typename ElementType> ElementType& corecvs::Vector2d< ElementType >::y () [inline]
Definition at line 55 of file vector2d.h.
Referenced by corecvs::Line2d::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::Vector2d< Int32x4 >::accept(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSE(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSEUnif(), corecvs::Buffer3d::addPoints(), corecvs::Vector2d< Int32x4 >::argument(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), Triangulation::classify(), corecvs::Rectangle< ElementType >::clipCohenSutherland(), Scene3D::commonSetup(), corecvs::DirectRemapper::DirectRemapper(), DistortionWidget::doManualTransform(), FlowDrawer::draw(), drawArc(), drawCircle(), corecvs::RGB24Buffer::drawCorrespondanceList(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer3(), drawLine(), corecvs::RGB24Buffer::drawLine(), corecvs::VJSimpleClassifier::drawPattern(), drawPie(), drawSquare(), corecvs::FlowBuffer::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), corecvs::FCostFunction::function(), corecvs::FCostFunction::functionPro(), corecvs::G12Buffer3d::G12Buffer3d(), corecvs::StereoAligner::getAlignmentTransformation(), FlowColorer::getColor(), StereoColorer::getColor(), corecvs::EllipticalApproximation::getDeviationSquare(), corecvs::StereoAligner::getDistortion(), corecvs::EllipticalApproximation::getEllipseAxis(), corecvs::EllipticalApproximation::getEllipseAxisSquare(), corecvs::EllipticalApproximation::getEllipseOrientation(), corecvs::EssentialEstimator::getEssentialLSE(), corecvs::getInputDisparity< DisparityBuffer >(), corecvs::CameraIntrinsics::getInvKMatrix(), corecvs::CameraIntrinsics::getInvKMatrix33(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::CameraIntrinsics::getKMatrix(), corecvs::CameraIntrinsics::getKMatrix33(), corecvs::Buffer3d::getLength(), corecvs::Vector2d< Int32x4 >::getLengthStable(), corecvs::ModelToRadialCorrection::getModel(), corecvs::Buffer3d::getNearestPoint(), corecvs::CorrespondanceList::getNormalizingTransform(), FlowColorer::getPacked(), StereoColorer::getPacked(), corecvs::EllipticalApproximation::getPerAxisDeviation(), corecvs::Rectangle< ElementType >::getPointCode(), corecvs::ModelToRadialCorrection::getRadial(), corecvs::CameraIntrinsics::getVFov(), corecvs::Element6D::hasFlow(), corecvs::FlowBuffer::invert(), corecvs::FlowBuffer::isElementKnown(), corecvs::PunchedBufferOperations< SixDBuffer, SixDBufferBase::InternalElementType >::isElementKnownVec(), Triangulation::PointGroup::isNear(), corecvs::VoxelBufferBase< RealType, ElementType >::isValidCoord(), corecvs::AbstractBuffer< SegmentType * >::isValidCoord(), corecvs::AbstractContiniousBuffer< double, int >::isValidCoordBl(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::Vector2d< Int32x4 >::leftNormal(), DistortionWidget::loadPoints(), corecvs::CorrespondanceList::makePrecise(), corecvs::CorrespondanceList::makePreciseCopy(), corecvs::DistortionCorrectTransform::map(), corecvs::RadialCorrection::map(), Triangulation::mate(), corecvs::EllipticalApproximation::mu11(), corecvs::Matrix33::mulBy2dLeft(), corecvs::Matrix33::mulBy2dRight(), corecvs::HomographyReconstructor::noramlisePoints(), corecvs::CamerasCalibrationFunc::operator()(), corecvs::StraightFunc::operator()(), corecvs::AngleFunction::operator()(), corecvs::AnglePointsFunction::operator()(), corecvs::DistPointsFunction::operator()(), corecvs::CFlowBufferToucherOperator< swap >::operator()(), corecvs::RadialFunc::operator()(), corecvs::SortSwarmPointTexY::operator()(), corecvs::ParallelTriangulate< InputType >::operator()(), corecvs::Map2DFunction< Map2D >::operator()(), corecvs::RadialCorrection::operator()(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator()(), Triangulation::Point::operator<(), Triangulation::Point::operator=(), Triangulation::Point::operator>(), corecvs::FloatFlowBuffer::preciseFlowCalc(), DistortionWidget::printVectorPair(), corecvs::Matrix33::Projective(), corecvs::Matrix33::ProjectiveByPoints(), Triangulation::PointGroup::push_back(), Core2Qt::QPointFromVector2d32(), Core2Qt::QPointFromVector2dd(), UniversalRectifier::recalculate(), corecvs::Vector2d< Int32x4 >::rightNormal(), Triangulation::Edge::rot(), corecvs::VJPattern::scale(), corecvs::Matrix33::Scale2(), corecvs::FlowBuffer::setElementUnknown(), corecvs::PunchedBufferOperations< SixDBuffer, SixDBufferBase::InternalElementType >::setElementUnknownVec(), corecvs::DistortionCorrectTransform::setRadius(), corecvs::DistortionCorrectTransform::setZ(), corecvs::Matrix33::ShiftProj(), DistortionWidget::showBufferChanged(), corecvs::SixDBuffer::SixDBuffer(), corecvs::FlowBuffer::toVectorForm(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateHelper(), corecvs::Triangulator::triangulateToDB(), and DistortionWidget::updateAdditionalData().
    {
        return (*this)[1];
    }
template<typename ElementType> const ElementType& corecvs::Vector2d< ElementType >::y () const [inline]
Definition at line 65 of file vector2d.h.
    {
        return (*this)[1];
    }
Friends And Related Function Documentation
ElementType operator& (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
Vector2d< ElementType > operator* (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
Vector2d< ElementType > operator* (const ElementType & c, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
Vector2d< ElementType > operator* (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
Vector2d< ElementType > operator+ (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
Vector2d< ElementType > operator- (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
Vector2d< ElementType > operator/ (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
Vector2d< ElementType > operator/ (const VectorOperationsBase< Vector2d< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< Vector2d< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, VectorOperationsBase< Vector2d< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
Member Data Documentation
ElementType corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
Referenced by corecvs::Vector2d< Int32x4 >::mapToRect().
const int corecvs::FixedVectorBase< Vector2d< ElementType > , ElementType, length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
template<typename ElementType> Reflection corecvs::Vector2d< ElementType >::reflect = Vector2d<ElementType>::staticInit() [static]
Definition at line 170 of file vector2d.h.
Referenced by corecvs::Vector2d< Int32x4 >::accept().
The documentation for this class was generated from the following file:
core/math/vector/vector2d.h