DeepView: ParameterSlider Class Reference
ParameterSlider Class Reference
#include <parameterSlider.h>
Public Slots
virtual void textChanged (int value)
virtual void sliderChanged (int value)
Signals
void valueChanged (int value)
void autoToggled ()
void resetPressed ()
Public Member Functions
ParameterSlider (QWidget *parent=0)
~ParameterSlider ()
virtual double minimum (void)
virtual double maximum (void)
virtual double value (void)
virtual void setValue (double value)
virtual void setMinimum (double value)
virtual void setMaximum (double value)
virtual void setStep (double value)
virtual void setAutoSupported (bool value)
virtual void stepUp ()
virtual void stepDown ()
virtual void setName (QString name)
Private Attributes
Ui::ParameterSliderClass ui
Detailed Description
Definition at line 8 of file parameterSlider.h.
Constructor & Destructor Documentation
ParameterSlider::ParameterSlider (QWidget * parent = 0)
Definition at line 7 of file parameterSlider.cpp.
References resetPressed(), and ui.
    : ParameterEditorWidget(parent)
{
    ui.setupUi(this);
    ui.autoBox->hide();
    connect(ui.resetButton, SIGNAL(released()), this, SIGNAL(resetPressed()));
}
ParameterSlider::~ParameterSlider ()
Definition at line 15 of file parameterSlider.cpp.
{
}
Member Function Documentation
void ParameterSlider::autoToggled () [signal]
double ParameterSlider::maximum (void) [virtual]
Implements ParameterEditorWidget.
Definition at line 36 of file parameterSlider.cpp.
References ui.
{
    return ui.spinBox->maximum();
}
double ParameterSlider::minimum (void) [virtual]
Implements ParameterEditorWidget.
Definition at line 31 of file parameterSlider.cpp.
References ui.
{
    return ui.spinBox->minimum();
}
void ParameterSlider::resetPressed () [signal]
Referenced by ParameterSlider().
void ParameterSlider::setAutoSupported (bool value) [virtual]
Implements ParameterEditorWidget.
Definition at line 26 of file parameterSlider.cpp.
References ui.
{
    ui.autoBox->setEnabled(value);
}
void ParameterSlider::setMaximum (double value) [virtual]
Definition at line 58 of file parameterSlider.cpp.
References ui.
Referenced by CapSettingsDialog::refreshDialog().
{
    ui.spinBox->setMaximum(value);
    ui.slider->setMaximum(value);
    ui.maxLabel->setText(QString::number(value));
}
void ParameterSlider::setMinimum (double value) [virtual]
Definition at line 51 of file parameterSlider.cpp.
References ui.
Referenced by CapSettingsDialog::refreshDialog().
{
    ui.spinBox->setMinimum(value);
    ui.slider->setMinimum(value);
    ui.minLabel->setText(QString::number(value));
}
void ParameterSlider::setName (QString name) [virtual]
Implements ParameterEditorWidget.
Definition at line 21 of file parameterSlider.cpp.
References ui.
{
    ui.label->setText(name);
}
void ParameterSlider::setStep (double value) [virtual]
Definition at line 65 of file parameterSlider.cpp.
References ui.
{
    ui.spinBox->setSingleStep(value);
    ui.slider->setSingleStep(value);
}
void ParameterSlider::setValue (double value) [virtual]
Implements ParameterEditorWidget.
Definition at line 46 of file parameterSlider.cpp.
References ui.
{
    ui.spinBox->setValue(value);
}
void ParameterSlider::sliderChanged (int value) [virtual, slot]
Definition at line 90 of file parameterSlider.cpp.
References ui, and valueChanged().
{
    bool blocked = ui.spinBox->blockSignals(true);
    ui.spinBox->setValue(value);
    ui.spinBox->blockSignals(blocked);
    emit valueChanged(value);
}
void ParameterSlider::stepDown () [virtual]
Implements ParameterEditorWidget.
Definition at line 76 of file parameterSlider.cpp.
References ui.
{
    ui.slider->setValue(ui.slider->value() - 1);
}
void ParameterSlider::stepUp () [virtual]
Implements ParameterEditorWidget.
Definition at line 71 of file parameterSlider.cpp.
References ui.
{
    ui.slider->setValue(ui.slider->value() + 1);
}
void ParameterSlider::textChanged (int value) [virtual, slot]
Definition at line 81 of file parameterSlider.cpp.
References ui, and valueChanged().
{
    bool blocked = ui.slider->blockSignals(true);
    ui.slider->setValue(value);
    ui.slider->blockSignals(blocked);
    emit valueChanged(value);
}
double ParameterSlider::value (void) [virtual]
Implements ParameterEditorWidget.
Definition at line 41 of file parameterSlider.cpp.
References ui.
{
    return ui.spinBox->value();
}
void ParameterSlider::valueChanged (int value) [signal]
Referenced by sliderChanged(), and textChanged().
Member Data Documentation
Ui::ParameterSliderClass ParameterSlider::ui [private]
Definition at line 41 of file parameterSlider.h.
Referenced by maximum(), minimum(), ParameterSlider(), setAutoSupported(), setMaximum(), setMinimum(), setName(), setStep(), setValue(), sliderChanged(), stepDown(), stepUp(), textChanged(), and value().
The documentation for this class was generated from the following files:
utils/widgets/parameterSlider.h
utils/widgets/parameterSlider.cpp