DeepView: Core2Qt Class Reference
Core2Qt Class Reference
#include <painterHelpers.h>
Static Public Member Functions
static QPoint QPointFromVector2d32 (const Vector2d32 &point)
static QPointF QPointFromVector2dd (const Vector2dd &point)
static QRect QRectFromRectangle (const Rectangle32 &rect)
Detailed Description
Definition at line 26 of file painterHelpers.h.
Member Function Documentation
static QPoint Core2Qt::QPointFromVector2d32 (const Vector2d32 & point) [inline, static]
Definition at line 29 of file painterHelpers.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        return QPoint(point.x(), point.y());
    }
static QPointF Core2Qt::QPointFromVector2dd (const Vector2dd & point) [inline, static]
Definition at line 34 of file painterHelpers.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by PaintImageWidget::currentPoint(), PaintImageWidget::imageToWidgetF(), and PaintImageWidget::widgetToImageF().
    {
        return QPointF(point.x(), point.y());
    }
static QRect Core2Qt::QRectFromRectangle (const Rectangle32 & rect) [inline, static]
Definition at line 39 of file painterHelpers.h.
References corecvs::Rectangle< ElementType >::corner, and corecvs::Rectangle< ElementType >::size.
    {
        return QRect(
            rect.corner.x(),  rect.corner.y(),
            rect.size.x(),    rect.size.y());
    }
The documentation for this class was generated from the following file:
utils/corestructs/painterHelpers.h