DeepView: corecvs::BlurProcessor Class Reference
corecvs::BlurProcessor Class Reference
#include <blurProcessor.h>
Static Public Member Functions
static void prepareBlurBuffers (G12IntegralBuffer *integral, G12Buffer *blur[4])
The image below represents the geometry of the things to happen A, B, C, D - elements of the blur buffers.
static void prepareBlurBuffers (G12IntegralBuffer *integral, unsigned blurH, unsigned blurW, unsigned stepH, unsigned stepW, G12Buffer **blur)
Static Public Attributes
static const int BLUR_RADIUS = 2
static const int xshift [4] = {0,1,0,1}
static const int yshift [4] = {0,0,1,1}
Detailed Description
Definition at line 19 of file blurProcessor.h.
Member Function Documentation
void corecvs::BlurProcessor::prepareBlurBuffers (G12IntegralBuffer * integral, G12Buffer * blur[4]) [static]
The image below represents the geometry of the things to happen A, B, C, D - elements of the blur buffers.
                  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
                          0       1       2       3       4       5       6
                          0   1   2   3   4   5   6   7   8   9   10  11
              +---------------------------------------------------------------+
  0           |   +   +   +   +   +                       +   +   +   +   +   |
  1           |   +   +   +   +   +                       +   +   +   +   +   |
  2   0   0   |   +   +   A   B   A   B   A   B   A   B   A   B   A   +   +   |
  3       1   |   +   +   C   D   C   D   C   D   C   D   C   D   C   +   +   |
  4   1   2   |   +   +   A   B   A  \B/  A   B   A   B   A   B   A   +   +   |
  5       3   |           C   D   C  -D-  C   D   C   D   C   D   C           |
  6   2   4   |           A   B   A  /B\  A   B   A   B   A   B   A           |
  7       5   |           C   D   C   D   C   D   C   D   C   D   C           |
  8   3   6   |           A   B   A   B   A   B   A   B   A   B   A           |
  9       7   |   +   +   C   D   C   D   C   D   C   D   C   D   C   +   +   |
  10  4   8   |   +   +   A   B   A   B   A   B   A   B   A   B   A   +   +   |
  11      9   |   +   +   C   D   C   D   C   D   C   D   C   D   C   +   +   |
  12  5   10  |   +   +   +   +   +                       +   +   +   +   +   |
  13          |   +   +   +   +   +                       +   +   +   +   +   |
  14          +---------------------------------------------------------------+
Definition at line 88 of file blurProcessor.cpp.
References BLUR_RADIUS, corecvs::IntegralBuffer< ElementType, BaseElementType, IndexType >::getEffectiveH(), corecvs::IntegralBuffer< ElementType, BaseElementType, IndexType >::getEffectiveW(), corecvs::AbstractBufferParams::h, xshift, and yshift.
{
    const unsigned h = integral->getEffectiveH();
    const unsigned w = integral->getEffectiveW();
    unsigned g;
    // shifts of the coordinate system for 4 types of points 2*2
    const unsigned patternsH = h - BLUR_RADIUS * 2;
    const unsigned patternsW = w - BLUR_RADIUS * 2;
    const unsigned patternHhalf = patternsH  / 2;// (h-4)/2
    const unsigned patternWhalf = patternsW  / 2;
    int patternLowerH = patternHhalf;
    int patternLowerW = patternWhalf;
    if (patternsH & 0x1)
        patternLowerH++;
    if (patternsW & 0x1)
        patternLowerW++;
    blur[0] = new G12Buffer(patternLowerH, patternLowerW, false);
    blur[1] = new G12Buffer(patternLowerH, patternWhalf,  false);
    blur[2] = new G12Buffer(patternHhalf,  patternLowerW, false);
    blur[3] = new G12Buffer(patternHhalf,  patternWhalf,  false);
    /*Accurately fill blurred buffers with data */
    for (g = 0; g < 4; g++)
    {
        parallelable_for<int, ParallelPrepareBlurBuffers>
          (0, blur[g]->h, ParallelPrepareBlurBuffers(integral, blur[g], yshift[g], xshift[g]));
    }
}
void corecvs::BlurProcessor::prepareBlurBuffers (G12IntegralBuffer * integral, unsigned blurH, unsigned blurW, unsigned stepH, unsigned stepW, G12Buffer ** blur) [static]
Definition at line 126 of file blurProcessor.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBufferParams::h, corecvs::IntegralBuffer< ElementType, BaseElementType, IndexType >::rectangularBlur(), and corecvs::AbstractBufferParams::w.
{
    G12Buffer *blurred = integral->rectangularBlur<G12Buffer>(blurH, blurW);
    for (unsigned i = 0; i < stepH; i++)
    {
        for (unsigned j = 0; j < stepW; j++)
        {
            int h = (blurred->h / stepH);
            int w = (blurred->w / stepW);
            if ((h * stepH + i) < (unsigned)blurred->h) h++;
            if ((w * stepW + j) < (unsigned)blurred->w) w++;
            G12Buffer *small = new G12Buffer(h, w);
            for (int y = 0; y < h; y++)
            {
                for (int x = 0; x < w; x++)
                {
                    small->element(y,x) = blurred->element(i + y * stepH, j + x * stepW);
                }
            }
            blur[i * stepW + j] = small;
        }
    }
    delete blurred;
}
Member Data Documentation
const int corecvs::BlurProcessor::BLUR_RADIUS = 2 [static]
Definition at line 22 of file blurProcessor.h.
Referenced by corecvs::ParallelPrepareBlurBuffers::operator()(), and prepareBlurBuffers().
const int corecvs::BlurProcessor::xshift = {0,1,0,1} [static]
Definition at line 37 of file blurProcessor.h.
Referenced by prepareBlurBuffers().
const int corecvs::BlurProcessor::yshift = {0,0,1,1} [static]
Definition at line 38 of file blurProcessor.h.
Referenced by prepareBlurBuffers().
The documentation for this class was generated from the following files:
core/buffers/kernels/blurProcessor.h
core/buffers/kernels/blurProcessor.cpp