DeepView: StdStreamLogDrain Class Reference
StdStreamLogDrain Class Reference
#include <log.h>
Public Member Functions
StdStreamLogDrain (std::ostream &outputStream)
virtual void drain (Log::Message &message)
Protected Member Functions
cchar * time2str (time_t &time)
Protected Attributes
char timeBuffer [32]
Private Attributes
std::ostream & mOutputStream
Detailed Description
Definition at line 233 of file log.h.
Constructor & Destructor Documentation
StdStreamLogDrain::StdStreamLogDrain (std::ostream & outputStream) [inline]
Definition at line 238 of file log.h.
        : mOutputStream(outputStream)
    {}
Member Function Documentation
void StdStreamLogDrain::drain (Log::Message & message) [virtual]
Implements LogDrain.
Definition at line 109 of file log.cpp.
References corecvs::ObjectRef< Type >::get(), Log::level_names, mOutputStream, and LogDrain::time2str().
{
    //static const std::string sLevels[] = { "    ", "    ", "    ", "WRN ", "ERR " };
    std::ostringstream prefix;
    prefix << time2str(message.get()->rawtime)   << ":"
           << Log::level_names[message.get()->mLevel]
           << message.get()->mOriginFileName     << ":"
           << message.get()->mOriginLineNumber   << " "
           << message.get()->mOriginFunctionName << "() ";
    size_t len = prefix.str().size();
    mOutputStream << prefix.str();
    const std::string &messageString = message.get()->s.str();
    size_t pos = 0;
    do {
        if (pos != 0) {
            mOutputStream << std::string(len, ' ');
        }
        size_t posBr = messageString.find('\n', pos);
        mOutputStream << messageString.substr(pos, posBr - pos) << std::endl;
        if (posBr == std::string::npos)
            break;
        pos = posBr + 1;
    } while (true);
}
cchar * LogDrain::time2str (time_t & time) [protected, inherited]
Definition at line 94 of file log.cpp.
References LogDrain::timeBuffer.
Referenced by LoggerWidget::doDrain(), and drain().
{
    struct tm *timeinfo = localtime(&time);
    snprintf2buf(timeBuffer, "%d, %d %d %02d:%02d:%02d",
        timeinfo->tm_year + 1900,
        timeinfo->tm_mon  + 1,
        timeinfo->tm_mday,
        timeinfo->tm_hour,
        timeinfo->tm_min,
        timeinfo->tm_sec
        );
    return timeBuffer;
}
Member Data Documentation
std::ostream& StdStreamLogDrain::mOutputStream [private]
Definition at line 235 of file log.h.
Referenced by drain().
char LogDrain::timeBuffer[32] [protected, inherited]
Definition at line 229 of file log.h.
Referenced by LogDrain::time2str().
The documentation for this class was generated from the following files:
core/utils/log.h
core/utils/log.cpp