DeepView: Serializer Class Reference
Serializer Class Reference
#include <serializer.h>
Static Public Member Functions
static void serialize (QWidget const &widget)
static void deserialize (QWidget *widget)
Static Private Member Functions
static QString getPath (QWidget const &widget)
Detailed Description
Definition at line 4 of file serializer.h.
Member Function Documentation
void Serializer::deserialize (QWidget * widget) [static]
Definition at line 76 of file serializer.cpp.
References checkBoxName, comboBoxName, doubleSpinBoxName, getPath(), nameAttribute, pushButtonName, and spinBoxName.
{
    QFile file(getPath(*widget));
    if (!file.exists() || !file.open(QIODevice::ReadWrite))
        return;
    QDomDocument doc("document");
    doc.setContent(&file);
    file.close();
    bool isInt = false;
    QDomNodeList pushButtonElements = doc.elementsByTagName(pushButtonName);
    for (int i = 0; i < pushButtonElements.size(); i++)
    {
        QDomElement element = pushButtonElements.at(i).toElement();
        QString name = element.attribute(nameAttribute, "");
        QPushButton * button = widget->findChild<QPushButton *>(name);
        QString isDown = element.attribute("isDown", "");
        button->setDown(isDown == "true");
    }
    QDomNodeList comboBoxElements = doc.elementsByTagName(comboBoxName);
    for (int i = 0; i < comboBoxElements.size(); i++)
    {
        QDomElement element = comboBoxElements.at(i).toElement();
        QString name = element.attribute(nameAttribute, "");
        QComboBox * cBox = widget->findChild<QComboBox *>(name);
        int index = element.attribute("index", "0").toInt(&isInt, 0);
        cBox->setCurrentIndex(index);
    }
    QDomNodeList spinBoxElements = doc.elementsByTagName(spinBoxName);
    for (int i = 0; i < spinBoxElements.size(); i ++)
    {
        QDomElement element = spinBoxElements.at(i).toElement();
        QString name = element.attribute(nameAttribute, "no such attribute");
        QSpinBox * sBox = widget->findChild<QSpinBox *>(name);
        int value = element.attribute("value", "0").toInt(&isInt, 0);
        sBox->setValue(value);
    }
    QDomNodeList doubleSpinBoxElements = doc.elementsByTagName(doubleSpinBoxName);
    for (int i = 0; i < doubleSpinBoxElements.size(); i ++)
    {
        QDomElement element = doubleSpinBoxElements.at(i).toElement();
        QString name = element.attribute(nameAttribute, "no such attribute");
        QDoubleSpinBox * sBox = widget->findChild<QDoubleSpinBox *>(name);
        int value = element.attribute("value", "0").toInt(&isInt, 0);
        sBox->setValue(value);
    }
    QDomNodeList checkBoxElements = doc.elementsByTagName(checkBoxName);
    for (int i = 0; i < checkBoxElements.size(); i ++)
    {
        QDomElement element = checkBoxElements.at(i).toElement();
        QString name = element.attribute(nameAttribute, "");
        QCheckBox * cBox = widget->findChild<QCheckBox *>(name);
        QString isChecked = element.attribute("isChecked", "");
        cBox->setChecked(isChecked == "1");
    }
}
QString Serializer::getPath (QWidget const & widget) [static, private]
Definition at line 133 of file serializer.cpp.
References pathToFile.
Referenced by deserialize(), and serialize().
{
    return pathToFile + widget.objectName() + "Data.xml";
}
void Serializer::serialize (QWidget const & widget) [static]
Definition at line 20 of file serializer.cpp.
References checkBoxName, comboBoxName, doubleSpinBoxName, getPath(), nameAttribute, pushButtonName, and spinBoxName.
Referenced by SerializedWidget::~SerializedWidget().
{
    QString const pathToXml = getPath(widget);
    QFile file(pathToXml);
    if (!file.open(QFile::ReadWrite))
    {
        return;
    }
    QTextStream textStream(&file);
    QDomDocument document;
    QDomElement root = document.createElement("WidgetsParameters");
    document.appendChild(root);
    QList<QPushButton *> pushButtons = widget.findChildren<QPushButton *>();
    foreach (QPushButton * button, pushButtons)
    {
        QDomElement element = document.createElement(pushButtonName);
        element.setAttribute("isDown", button->isDown());
        element.setAttribute(nameAttribute, button->objectName());
        root.appendChild(element);
    }
    QList<QComboBox *> comboBoxes = widget.findChildren<QComboBox *>();
    foreach (QComboBox * cBox, comboBoxes)
    {
        QDomElement element = document.createElement(comboBoxName);
        element.setAttribute(nameAttribute, cBox->objectName());
        element.setAttribute("index", cBox->currentIndex());
        root.appendChild(element);
    }
    QList<QSpinBox *> spinBoxes = widget.findChildren<QSpinBox *>();
    foreach (QSpinBox * sBox, spinBoxes)
    {
        QDomElement element = document.createElement(spinBoxName);
        element.setAttribute(nameAttribute, sBox->objectName());
        element.setAttribute("value", sBox->value());
        root.appendChild(element);
    }
    QList<QDoubleSpinBox *> doubleSpinBoxes = widget.findChildren<QDoubleSpinBox *>();
    foreach (QDoubleSpinBox * dsBox, doubleSpinBoxes)
    {
        QDomElement element = document.createElement(doubleSpinBoxName);
        element.setAttribute(nameAttribute, dsBox->objectName());
        element.setAttribute("value", dsBox->value());
        root.appendChild(element);
    }
    QList<QCheckBox *> checkBoxes = widget.findChildren<QCheckBox *>();
    foreach (QCheckBox * cBox, checkBoxes)
    {
        QDomElement element = document.createElement(checkBoxName);
        element.setAttribute(nameAttribute, cBox->objectName());
        element.setAttribute("isChecked", cBox->isChecked());
        root.appendChild(element);
    }
    document.save(textStream, 2);
    file.close();
}
The documentation for this class was generated from the following files:
utils/serializer/serializer.h
utils/serializer/serializer.cpp