DeepView: corecvs::DerivedCorrespondanceList Class Reference
corecvs::DerivedCorrespondanceList Class Reference
DerivedCorrespondanceList is a wrapper around CorrespondanceList that allows to modify the contense, yet remembering the pointer to the origin.
#include <correspondanceList.h>
Public Member Functions
DerivedCorrespondanceList (CorrespondanceList *list)
template<class Predicate >
DerivedCorrespondanceList (CorrespondanceList *list, Predicate &predicate, int flag)
void propagateData (void)
vector< Correspondance * > * toArrayOfPointers ()
void getNormalizingTransform (Matrix33 &transformRight, Matrix33 &transformLeft, double *scale)
void transform (const ProjectiveTransform &transformRight, const ProjectiveTransform &transformLeft)
CorrespondanceList * makePreciseCopy (G12Buffer *first, G12Buffer *second)
void makePrecise (G12Buffer *first, G12Buffer *second)
void resetFlags (void)
Vector2dd getSize () const
Vector2dd getMeanDifference ()
Public Attributes
CorrespondanceList * parent
vector< int > map
int h
int w
T elements
STL member.
Detailed Description
DerivedCorrespondanceList is a wrapper around CorrespondanceList that allows to modify the contense, yet remembering the pointer to the origin.
Definition at line 123 of file correspondanceList.h.
Constructor & Destructor Documentation
corecvs::DerivedCorrespondanceList::DerivedCorrespondanceList (CorrespondanceList * list) [inline]
Definition at line 129 of file correspondanceList.h.
References map, and parent.
                                                        :
        CorrespondanceList(*list),
        parent(list)
    {
        map.reserve(parent->size());
        for (unsigned i = 0; i < parent->size(); i++)
            map.push_back(i);
    }
template<class Predicate > corecvs::DerivedCorrespondanceList::DerivedCorrespondanceList (CorrespondanceList * list, Predicate & predicate, int flag) [inline]
Definition at line 139 of file correspondanceList.h.
References map, and parent.
                                                                                        :
        parent(list)
    {
        /* Some extra memory used */
        unsigned parentSize = (unsigned)parent->size();
        reserve(parentSize);
        map.reserve(parentSize);
        for (unsigned i = 0; i < parentSize; i++)
        {
            if (!predicate(parent->at(i)))
            {
                parent->at(i).flags |= flag;
                continue;
            }
            map.push_back(i);
            push_back(parent->at(i));
        }
    }
Member Function Documentation
Vector2dd corecvs::CorrespondanceList::getMeanDifference () [inline, inherited]
Definition at line 104 of file correspondanceList.h.
References corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start.
Referenced by UniversalRectifier::recalculate().
    {
      Vector2dd mean (0.0);
      for (unsigned i = 0; i < size(); i++)
      {
        Correspondance *corr = &(at(i));
        mean += (corr->end - corr->start);
      }
      return (size() != 0) ? mean / size() : Vector2dd(0.0);
    }
void corecvs::CorrespondanceList::getNormalizingTransform (Matrix33 & transformRight, Matrix33 & transformLeft, double * scale) [inherited]
Definition at line 60 of file correspondanceList.cpp.
References corecvs::Matrix33::ScaleProj(), corecvs::Matrix33::ShiftProj(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by UniversalRectifier::recalculate().
{
    Vector2dd rightMean(0.0);
    Vector2dd rightMeanSq(0.0);
    Vector2dd leftMean(0.0);
    Vector2dd leftMeanSq(0.0);
    for (unsigned  i = 0; i < this->size(); i++)
    {
        rightMean   += (*this)[i].start;
        rightMeanSq += ((*this)[i].start) * ((*this)[i].start);
        leftMean   += (*this)[i].end;
        leftMeanSq += ((*this)[i].end) * ((*this)[i].end);
    }
    int count = (this->size() == 0) ? 1 : (int)this->size();
    rightMean   /= count;
    rightMeanSq /= count;
    leftMean    /= count;
    leftMeanSq  /= count;
    Vector2dd rightSqMean = rightMean * rightMean;
    Vector2dd leftSqMean  = leftMean * leftMean;
    double rightScaler = sqrt (rightMeanSq.x() - rightSqMean.x()  + rightMeanSq.y() - rightSqMean.y());
    double leftScaler  = sqrt (leftMeanSq.x()  - leftSqMean.x()   + leftMeanSq.y()  - leftSqMean.y());
    if (rightScaler < 1e-15) rightScaler = 1.0;
    if (leftScaler < 1e-15) leftScaler = 1.0;
    transformRight = Matrix33::ScaleProj(sqrt(2.0) / rightScaler) * Matrix33::ShiftProj(-rightMean);
    transformLeft  = Matrix33::ScaleProj(sqrt(2.0) / leftScaler ) * Matrix33::ShiftProj(-leftMean);
    if (scale != NULL )
        *scale = sqrt(2.0f) / ((rightScaler + leftScaler) * 2.0) ;
}
Vector2dd corecvs::CorrespondanceList::getSize () const [inline, inherited]
Definition at line 99 of file correspondanceList.h.
References corecvs::CorrespondanceList::h, and corecvs::CorrespondanceList::w.
Referenced by UniversalRectifier::getZ(), and UniversalRectifier::recalculate().
    {
        return Vector2dd(w, h);
    }
void corecvs::CorrespondanceList::makePrecise (G12Buffer * first, G12Buffer * second) [inherited]
Definition at line 173 of file correspondanceList.cpp.
References corecvs::KLTCalculationContext::first, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_FILTERED_KLT, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::flags, corecvs::KLTCalculationContext::gradient, corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::KLTCalculationContext::second, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by UniversalRectifier::recalculate().
{
    SpatialGradient *sg = new SpatialGradient(first);
    SpatialGradientIntegralBuffer *gradient = new SpatialGradientIntegralBuffer(sg);
    delete sg;
    KLTCalculationContext context;
    context.first = first;
    context.second = second;
    context.gradient = gradient;
    KLTGenerator<BilinearInterpolator> kltGenerator;
    for (unsigned i = 0; i < this->size(); i++)
    {
        // TODO: Be careful with this.
        Vector2dd start = Vector2dd(at(i).start.x(),at(i).start.y());
        Vector2dd guess = at(i).end - at(i).start;
        bool status = kltGenerator.kltIterationSubpixel(context, start, &guess, 2);
        if (status)
        {
            Correspondance corr(
                    Vector2dd(start.x(),start.y()),
                    Vector2dd(start.x() + guess.x(),start.y() + guess.y())
                    );
            int oldFlags = at(i).flags;
            at(i) = corr;
            at(i).flags = oldFlags;
        } else {
            at(i).flags |= Correspondance::FLAG_FILTERED_KLT;
        }
    }
    delete gradient;
}
CorrespondanceList * corecvs::CorrespondanceList::makePreciseCopy (G12Buffer * first, G12Buffer * second) [inherited]
Definition at line 133 of file correspondanceList.cpp.
References corecvs::CorrespondanceList::CorrespondanceList(), corecvs::KLTCalculationContext::first, corecvs::fround(), corecvs::KLTCalculationContext::gradient, corecvs::CorrespondanceList::h, corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::KLTCalculationContext::second, corecvs::CorrespondanceList::w, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    SpatialGradient *sg = new SpatialGradient(first);
    SpatialGradientIntegralBuffer *gradient = new SpatialGradientIntegralBuffer(sg);
    delete sg;
    KLTCalculationContext context;
    context.first = first;
    context.second = second;
    context.gradient = gradient;
    KLTGenerator<BilinearInterpolator> kltGenerator;
    CorrespondanceList *toReturn = new CorrespondanceList();
    toReturn->h = this->h;
    toReturn->w = this->w;
    for (unsigned i = 0; i < this->size(); i++)
    {
        // TODO: Be careful with this.
        Vector2dd start = Vector2dd(
                    fround(at(i).start.x()),
                    fround(at(i).start.y())
                  );
        Vector2dd guess = at(i).end - at(i).start;
        bool status = kltGenerator.kltIterationSubpixel(context, start, &guess, 2);
        if (status)
        {
            Correspondance corr(
                    Vector2dd(start.x(),start.y()),
                    Vector2dd(start.x() + guess.x(),start.y() + guess.y())
                    );
            toReturn->push_back(corr);
        }
    }
    delete gradient;
    return toReturn;
}
void corecvs::DerivedCorrespondanceList::propagateData (void) [inline]
Definition at line 159 of file correspondanceList.h.
References map, and parent.
Referenced by UniversalRectifier::recalculate().
    {
        for (unsigned i = 0; i < size(); i++)
        {
            parent->at(map[i]).value = operator [](i).value;
            parent->at(map[i]).flags = operator [](i).flags;
        }
    }
void corecvs::CorrespondanceList::resetFlags (void) [inline, inherited]
Definition at line 90 of file correspondanceList.h.
Referenced by UniversalRectifier::recalculate().
    {
        iterator it;
        for (it = begin(); it != end(); ++it)
        {
            (*it).clearFlags();
        }
    }
vector<Correspondance *>* corecvs::DerivedCorrespondanceList::toArrayOfPointers () [inline]
Definition at line 168 of file correspondanceList.h.
Referenced by UniversalRectifier::recalculate().
    {
        vector<Correspondance *> *result = new vector<Correspondance *>();
        result->reserve(this->size());
        for(unsigned i = 0; i < this->size(); i++)
        {
            result->push_back(&(at(i)));
        }
        return result;
    }
void corecvs::CorrespondanceList::transform (const ProjectiveTransform & transformRight, const ProjectiveTransform & transformLeft) [inherited]
Definition at line 100 of file correspondanceList.cpp.
References corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start.
Referenced by UniversalRectifier::recalculate().
{
    for (unsigned i = 0; i < this->size(); i++)
    {
        Correspondance *corr = &((*this)[i]);
        corr->start = transformRight (corr->start);
        corr->end   = transformLeft  (corr->end);
    }
}
Member Data Documentation
template<typename T> T std::vector< T >::elements [inherited]
STL member.
int corecvs::CorrespondanceList::h [inherited]
Definition at line 72 of file correspondanceList.h.
Referenced by corecvs::CorrespondanceList::getSize(), PointsRectificationWidget::initCorrespondancePoints(), corecvs::CorrespondanceList::makePreciseCopy(), and UniversalRectifier::recalculate().
vector<int> corecvs::DerivedCorrespondanceList::map
Definition at line 127 of file correspondanceList.h.
Referenced by DerivedCorrespondanceList(), and propagateData().
CorrespondanceList* corecvs::DerivedCorrespondanceList::parent
Definition at line 126 of file correspondanceList.h.
Referenced by DerivedCorrespondanceList(), and propagateData().
int corecvs::CorrespondanceList::w [inherited]
Definition at line 73 of file correspondanceList.h.
Referenced by corecvs::CorrespondanceList::getSize(), PointsRectificationWidget::initCorrespondancePoints(), corecvs::CorrespondanceList::makePreciseCopy(), and UniversalRectifier::recalculate().
The documentation for this class was generated from the following file:
core/rectification/correspondanceList.h