DeepView: AxisAlignedBoxParametersControlWidget Class Reference
AxisAlignedBoxParametersControlWidget Class Reference
#include <axisAlignedBoxParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
AxisAlignedBoxParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~AxisAlignedBoxParametersControlWidget ()
AxisAlignedBoxParameters * createParameters () const
void setParameters (const AxisAlignedBoxParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_AxisAlignedBoxParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file axisAlignedBoxParametersControlWidget.h.
Constructor & Destructor Documentation
AxisAlignedBoxParametersControlWidget::AxisAlignedBoxParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file axisAlignedBoxParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::AxisAlignedBoxParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->xSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->ySpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->zSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->widthSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->heightSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->depthSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
}
AxisAlignedBoxParametersControlWidget::~AxisAlignedBoxParametersControlWidget ()
Definition at line 31 of file axisAlignedBoxParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void AxisAlignedBoxParametersControlWidget::changeParameters () [inline, slot]
Definition at line 29 of file axisAlignedBoxParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
AxisAlignedBoxParameters * AxisAlignedBoxParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 53 of file axisAlignedBoxParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    AxisAlignedBoxParameters *result = new AxisAlignedBoxParameters(
          mUi->xSpinBox->value()
        , mUi->ySpinBox->value()
        , mUi->zSpinBox->value()
        , mUi->widthSpinBox->value()
        , mUi->heightSpinBox->value()
        , mUi->depthSpinBox->value()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void AxisAlignedBoxParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 37 of file axisAlignedBoxParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    AxisAlignedBoxParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void AxisAlignedBoxParametersControlWidget::paramsChanged () [signal]
Referenced by AxisAlignedBoxParametersControlWidget(), and setParameters().
void AxisAlignedBoxParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 45 of file axisAlignedBoxParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    AxisAlignedBoxParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void AxisAlignedBoxParametersControlWidget::setParameters (const AxisAlignedBoxParameters & input)
Definition at line 72 of file axisAlignedBoxParametersControlWidget.cpp.
References AxisAlignedBoxParameters::depth(), AxisAlignedBoxParameters::height(), mUi, paramsChanged(), AxisAlignedBoxParameters::width(), AxisAlignedBoxParameters::x(), AxisAlignedBoxParameters::y(), and AxisAlignedBoxParameters::z().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->xSpinBox->setValue(input.x());
    mUi->ySpinBox->setValue(input.y());
    mUi->zSpinBox->setValue(input.z());
    mUi->widthSpinBox->setValue(input.width());
    mUi->heightSpinBox->setValue(input.height());
    mUi->depthSpinBox->setValue(input.depth());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void AxisAlignedBoxParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 86 of file axisAlignedBoxParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    AxisAlignedBoxParameters *inputCasted = static_cast<AxisAlignedBoxParameters *>(input);
    setParameters(*inputCasted);
}
void AxisAlignedBoxParametersControlWidget::valueChanged () [signal]
Referenced by AxisAlignedBoxParametersControlWidget().
Member Data Documentation
bool AxisAlignedBoxParametersControlWidget::autoInit [private]
Definition at line 40 of file axisAlignedBoxParametersControlWidget.h.
Ui_AxisAlignedBoxParametersControlWidget* AxisAlignedBoxParametersControlWidget::mUi [private]
Definition at line 39 of file axisAlignedBoxParametersControlWidget.h.
Referenced by AxisAlignedBoxParametersControlWidget(), createParameters(), setParameters(), and ~AxisAlignedBoxParametersControlWidget().
QString AxisAlignedBoxParametersControlWidget::rootPath [private]
Definition at line 41 of file axisAlignedBoxParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.h
utils/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.cpp