DeepView: Draw3dViMouseParametersControlWidget Class Reference
Draw3dViMouseParametersControlWidget Class Reference
#include <draw3dViMouseParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
Draw3dViMouseParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~Draw3dViMouseParametersControlWidget ()
Draw3dViMouseParameters * createParameters () const
void setParameters (const Draw3dViMouseParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_Draw3dViMouseParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file draw3dViMouseParametersControlWidget.h.
Constructor & Destructor Documentation
Draw3dViMouseParametersControlWidget::Draw3dViMouseParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file draw3dViMouseParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::Draw3dViMouseParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->redDistSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->blueDistSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->flowZoomSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->pointColorTypeComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->flowColorTypeComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
}
Draw3dViMouseParametersControlWidget::~Draw3dViMouseParametersControlWidget ()
Definition at line 30 of file draw3dViMouseParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void Draw3dViMouseParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file draw3dViMouseParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
Draw3dViMouseParameters * Draw3dViMouseParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 52 of file draw3dViMouseParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    Draw3dViMouseParameters *result = new Draw3dViMouseParameters(
          mUi->redDistSpinBox->value()
        , mUi->blueDistSpinBox->value()
        , mUi->flowZoomSpinBox->value()
        , static_cast<ViMouse3dStereoStyle::ViMouse3dStereoStyle>(mUi->pointColorTypeComboBox->currentIndex())
        , static_cast<ViMouse3dFlowStyle::ViMouse3dFlowStyle>(mUi->flowColorTypeComboBox->currentIndex())
    );
    return result;
}
virtual BaseReflectionStatic* Draw3dViMouseParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from ParametersControlWidgetBase.
Definition at line 25 of file draw3dViMouseParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void Draw3dViMouseParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 36 of file draw3dViMouseParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    Draw3dViMouseParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void Draw3dViMouseParametersControlWidget::paramsChanged () [signal]
Referenced by Draw3dViMouseParametersControlWidget(), and setParameters().
void Draw3dViMouseParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 44 of file draw3dViMouseParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    Draw3dViMouseParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void Draw3dViMouseParametersControlWidget::setParameters (const Draw3dViMouseParameters & input)
Definition at line 70 of file draw3dViMouseParametersControlWidget.cpp.
References Draw3dViMouseParameters::blueDist(), Draw3dViMouseParameters::flowColorType(), Draw3dViMouseParameters::flowZoom(), mUi, paramsChanged(), Draw3dViMouseParameters::pointColorType(), and Draw3dViMouseParameters::redDist().
Referenced by Scene3DMouse::getContolWidget(), loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->redDistSpinBox->setValue(input.redDist());
    mUi->blueDistSpinBox->setValue(input.blueDist());
    mUi->flowZoomSpinBox->setValue(input.flowZoom());
    mUi->pointColorTypeComboBox->setCurrentIndex(input.pointColorType());
    mUi->flowColorTypeComboBox->setCurrentIndex(input.flowColorType());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void Draw3dViMouseParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 83 of file draw3dViMouseParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    Draw3dViMouseParameters *inputCasted = static_cast<Draw3dViMouseParameters *>(input);
    setParameters(*inputCasted);
}
void Draw3dViMouseParametersControlWidget::valueChanged () [signal]
Referenced by Draw3dViMouseParametersControlWidget().
Member Data Documentation
bool Draw3dViMouseParametersControlWidget::autoInit [private]
Definition at line 45 of file draw3dViMouseParametersControlWidget.h.
Ui_Draw3dViMouseParametersControlWidget* Draw3dViMouseParametersControlWidget::mUi [private]
Definition at line 44 of file draw3dViMouseParametersControlWidget.h.
Referenced by createParameters(), Draw3dViMouseParametersControlWidget(), setParameters(), and ~Draw3dViMouseParametersControlWidget().
QString Draw3dViMouseParametersControlWidget::rootPath [private]
Definition at line 46 of file draw3dViMouseParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/3d/draw3dViMouseParametersControlWidget.h
utils/3d/generated/draw3dViMouseParametersControlWidget.cpp