DeepView: AngleEditBox Class Reference
AngleEditBox Class Reference
#include <angleEditBox.h>
Public Slots
void updateDegreeAngles ()
void updateRagAngles ()
void reset ()
Signals
void valueChanged (double)
Public Member Functions
AngleEditBox (QWidget *parent=0)
~AngleEditBox ()
double value ()
void setValue (double val)
Private Attributes
Ui::AngleEditBoxClass ui
Detailed Description
Definition at line 6 of file angleEditBox.h.
Constructor & Destructor Documentation
AngleEditBox::AngleEditBox (QWidget * parent = 0)
Definition at line 9 of file angleEditBox.cpp.
References reset(), ui, updateDegreeAngles(), updateRagAngles(), and valueChanged().
    : QWidget(parent)
{
    ui.setupUi(this);
    connect(ui.radSpinBox,  SIGNAL(valueChanged(double)), this, SLOT(updateDegreeAngles ()));
    connect(ui.degSpinBox,  SIGNAL(valueChanged(double)), this, SLOT(updateRagAngles ()));
    connect(ui.resetButton, SIGNAL(released()), this, SLOT(reset()));
}
AngleEditBox::~AngleEditBox ()
Definition at line 37 of file angleEditBox.cpp.
{
}
Member Function Documentation
void AngleEditBox::reset (void) [slot]
Definition at line 31 of file angleEditBox.cpp.
References ui.
Referenced by AngleEditBox().
{
    ui.radSpinBox->setValue(0.0);
}
void AngleEditBox::setValue (double val) [inline]
Definition at line 19 of file angleEditBox.h.
References ui, and updateDegreeAngles().
    {
        ui.radSpinBox->setValue(val);
        updateDegreeAngles();
    }
void AngleEditBox::updateDegreeAngles (void) [slot]
Definition at line 19 of file angleEditBox.cpp.
References corecvs::radToDeg(), setValueBlocking(), ui, and valueChanged().
Referenced by AngleEditBox(), and setValue().
{
    setValueBlocking(ui.degSpinBox, radToDeg(ui.radSpinBox->value()));
    emit valueChanged(ui.radSpinBox->value());
}
void AngleEditBox::updateRagAngles (void) [slot]
Definition at line 25 of file angleEditBox.cpp.
References corecvs::degToRad(), setValueBlocking(), ui, and valueChanged().
Referenced by AngleEditBox().
{
    setValueBlocking(ui.radSpinBox, degToRad(ui.degSpinBox->value()));
    emit valueChanged(ui.radSpinBox->value());
}
double AngleEditBox::value () [inline]
Definition at line 14 of file angleEditBox.h.
References ui.
    {
        return ui.radSpinBox->value();
    }
void AngleEditBox::valueChanged (double) [signal]
Referenced by AngleEditBox(), updateDegreeAngles(), and updateRagAngles().
Member Data Documentation
Ui::AngleEditBoxClass AngleEditBox::ui [private]
Definition at line 35 of file angleEditBox.h.
Referenced by AngleEditBox(), reset(), setValue(), updateDegreeAngles(), updateRagAngles(), and value().
The documentation for this class was generated from the following files:
utils/widgets/angleEditBox.h
utils/widgets/angleEditBox.cpp