DeepView: corecvs::Int32x8 Class Reference
corecvs::Int32x8 Class Reference
#include <int32x8.h>
Public Types
enum FieldId
typedef ReflectionHelper
< Int32x4 >::Type ReflectionType
typedef Int32x4 InnerElementType
Public Member Functions
Int32x8 (const Int32x4 &lowAddr, const Int32x4 &highAddr)
Int32x8 (int32_t value)
Int32x8 (const int32x4_t &_data0, const int32x4_t &_data1)
Int32x8 & operator/= (int c)
Int32x8 (const Int32x4 &lowAddr, const Int32x4 &highAddr)
Int32x8 (int32_t value)
Int32x8 (const __m128i &_data0, const __m128i &_data1)
Int32x8 & operator/= (int c)
Int32x4 & x ()
const Int32x4 & x () const
Int32x4 & y ()
const Int32x4 & y () const
double getLengthStable () const
double argument () const
Vector2d< Int32x4 > leftNormal () const
Vector2d< Int32x4 > rightNormal () const
double sineTo (const Vector2d &other) const
double cosineTo (const Vector2d &other) const
double parallelogramOrientedAreaTo (const Vector2d &other)
The oriented area of the parallelogram built on the two vectors: this, and the given one.
double triangleOrientedAreaTo (const Vector2d &other)
void mapToRect (const Vector2d< Int32x4 > &low, const Vector2d< Int32x4 > &high)
bool isInRect (const Vector2d< Int32x4 > &low, const Vector2d< Int32x4 > &high) const
void accept (VisitorType &visitor)
int size () const
Int32x4 & operator[] (int n)
const Int32x4 & operator[] (int n) const
Int32x4 & at (int n)
const Int32x4 & at (int n) const
Vector2d< Int32x4 > createVector (int) const
Vector2d< Int32x4 > * realThis ()
Static cast functions.
const Vector2d< Int32x4 > * realThis () const
bool operator== (const Vector2d< Int32x4 > &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const Vector2d< Int32x4 > &that) const
Inequality operator.
bool notTooFar (const Vector2d< Int32x4 > &that, const Int32x4 &epsilon=Int32x4(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const Vector2d< Int32x4 > &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const Vector2d< Int32x4 > &V)
VectorOperationsBase & operator*= (const Int32x4 &c)
VectorOperationsBase & operator/= (const Int32x4 &c)
Vector2d< Int32x4 > operator- () const
Negative operator.
Int32x4 sumAllElements () const
Sum of the elements of the vector.
Int32x4 mulAllElements () const
Product of all elements of the vector.
Int32x4 sumAllElementsSq () const
Sum of the squares of element of the vector.
Int32x4 l2Metric () const
Euclidean distance.
Int32x4 operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
Vector2d< Int32x4 > normalised () const
Return a normalized copy of vector.
Vector2d< Int32x4 > cloneVector () const
Return copy of vector.
Int32x4 l1Metric () const
Sum of the absolute values of element of the vector.
Int32x4 lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
Int32x4 minimum () const
Int32x4 maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
Static Public Member Functions
static Vector2d FromPolar (double angle, double length=1.0)
Return the vector from angle and length.
static Reflection staticInit ()
Public Attributes
Int32x4 element [length]
Static Public Attributes
static Reflection reflect
static const int LENGTH
Protected Types
typedef FixedVectorBase
< Vector2d< Int32x4 >, Int32x4, 2 > BaseClass
Friends
Int32x8 operator>> (const Int32x8 &left, uint32_t count)
TODO: Bring this to FixedVector.
Int32x8 operator>>= (Int32x8 &left, uint32_t count)
Int32x8 operator>> (const Int32x8 &left, uint32_t count)
TODO: Bring this to FixedVector.
Int32x8 operator>>= (Int32x8 &left, uint32_t count)
Vector2d< Int32x4 > operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
Vector2d< Int32x4 > operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
Vector2d< Int32x4 > operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
Vector2d< Int32x4 > operator* (const Int32x4 &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
Vector2d< Int32x4 > operator* (const VectorOperationsBase &V, const Int32x4 &c)
Vector2d< Int32x4 > operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
Vector2d< Int32x4 > operator/ (const VectorOperationsBase &V, const Int32x4 &c)
Operator * does the component-specific multiplication by constant
.
Int32x4 operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
Definition at line 15 of file int32x8.h.
Member Typedef Documentation
typedef FixedVectorBase<Vector2d<Int32x4 >, Int32x4 , 2> corecvs::Vector2d< Int32x4 >::BaseClass [protected, inherited]
Reimplemented from corecvs::FixedVectorBase< Vector2d< Int32x4 >, Int32x4, 2 >.
Definition at line 31 of file vector2d.h.
typedef Int32x4 corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<Int32x4 >::Type corecvs::Vector2d< Int32x4 >::ReflectionType [inherited]
Reimplemented from corecvs::VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 >.
Definition at line 172 of file vector2d.h.
Member Enumeration Documentation
enum corecvs::Vector2d::FieldId [inherited]
Definition at line 34 of file vector2d.h.
                 {
        FIELD_X = 0,
        FIELD_Y = 1
    };
Constructor & Destructor Documentation
corecvs::Int32x8::Int32x8 (const Int32x4 & lowAddr, const Int32x4 & highAddr) [inline, explicit]
Definition at line 18 of file int32x8.h.
: Vector2d<Int32x4>(lowAddr, highAddr){};
corecvs::Int32x8::Int32x8 (int32_t value) [inline, explicit]
Definition at line 20 of file int32x8.h.
: Vector2d<Int32x4>(Int32x4(value)){};
corecvs::Int32x8::Int32x8 (const int32x4_t & _data0, const int32x4_t & _data1) [inline, explicit]
Definition at line 22 of file int32x8.h.
References corecvs::Int32x4::data, and corecvs::FixedVectorBase< Vector2d< Int32x4 >, Int32x4, 2 >::element.
    {
        element[0].data = _data0;
        element[1].data = _data1;
    }
corecvs::Int32x8::Int32x8 (const Int32x4 & lowAddr, const Int32x4 & highAddr) [inline, explicit]
Definition at line 21 of file int32x8.h.
: Vector2d<Int32x4>(lowAddr, highAddr) {}
corecvs::Int32x8::Int32x8 (int32_t value) [inline, explicit]
Definition at line 23 of file int32x8.h.
: Vector2d<Int32x4>(Int32x4(value)) {}
corecvs::Int32x8::Int32x8 (const __m128i & _data0, const __m128i & _data1) [inline, explicit]
Definition at line 25 of file int32x8.h.
References corecvs::Int32x4::data, and corecvs::FixedVectorBase< Vector2d< Int32x4 >, Int32x4, 2 >::element.
    {
        element[0].data = _data0;
        element[1].data = _data1;
    }
Member Function Documentation
void corecvs::Vector2d< Int32x4 >::accept (VisitorType & visitor) [inline, inherited]
Reimplemented from corecvs::VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 >.
Definition at line 184 of file vector2d.h.
References corecvs::Vector2d< ElementType >::FIELD_X, corecvs::Vector2d< ElementType >::FIELD_Y, corecvs::Reflection::fields, corecvs::Vector2d< ElementType >::reflect, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        visitor.visit(x(), static_cast<const ReflectionType *>(reflect.fields[FIELD_X]));
        visitor.visit(y(), static_cast<const ReflectionType *>(reflect.fields[FIELD_Y]));
    }
void corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
double corecvs::Vector2d< Int32x4 >::argument () const [inline, inherited]
Definition at line 88 of file vector2d.h.
References corecvs::Vector2d< ElementType >::Vector2d(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        if (*this == Vector2d(0.0))
            return 0.0;
        return atan2(y(),x());
    }
Int32x4 & corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
    {
        return element[n];
    }
const Int32x4 & corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
Vector2d< Int32x4 > corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
double corecvs::Vector2d< Int32x4 >::cosineTo (const Vector2d< Int32x4 > & other) const [inline, inherited]
Definition at line 123 of file vector2d.h.
    {
        double thisLength  = !(*this);
        double otherLength = !other;
        if (thisLength == 0 || otherLength == 0)
          return 0;
        return ((*this) & other) / (thisLength * otherLength);
    }
Vector2d< Int32x4 > corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
static Vector2d corecvs::Vector2d< Int32x4 >::FromPolar (double angle, double length = 1.0) [inline, static, inherited]
Return the vector from angle and length.
Definition at line 151 of file vector2d.h.
References corecvs::Vector2d< ElementType >::Vector2d().
    {
        return Vector2d(cos(angle), sin(angle)) * length;
    }
double corecvs::Vector2d< Int32x4 >::getLengthStable () const [inline, inherited]
Definition at line 70 of file vector2d.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        double ma = (x() > 0) ? x() : -x();
        double mb = (y() > 0) ? y() : -y();
        if (ma == 0 && mb == 0) return 0;
        if (ma > mb)
        {
            double div = (mb / ma);
            return ma * sqrt(1.0 + div * div );
        }
        else
        {
            double div = (ma / mb);
            return mb * sqrt(1.0 + div * div );
        }
    }
bool corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::isInHypercube (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & low, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
bool corecvs::Vector2d< Int32x4 >::isInRect (const Vector2d< Int32x4 > & low, const Vector2d< Int32x4 > & high) const [inline, inherited]
Definition at line 164 of file vector2d.h.
References corecvs::VectorOperationsBase< Vector2d< ElementType >, ElementType >::isInHypercube().
    {
        return this->isInHypercube(low, high);
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
Vector2d<Int32x4 > corecvs::Vector2d< Int32x4 >::leftNormal () const [inline, inherited]
Definition at line 102 of file vector2d.h.
References corecvs::Vector2d< ElementType >::Vector2d(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
      return Vector2d(-y(),x());
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
void corecvs::Vector2d< Int32x4 >::mapToRect (const Vector2d< Int32x4 > & low, const Vector2d< Int32x4 > & high) [inline, inherited]
Definition at line 156 of file vector2d.h.
References corecvs::FixedVectorBase< Vector2d< ElementType >, ElementType, 2 >::element.
    {
        if (this->element[0] <  low.element[0]) this->element[0] =  low.element[0];
        if (this->element[1] <  low.element[1]) this->element[1] =  low.element[1];
        if (this->element[0] > high.element[0]) this->element[0] = high.element[0];
        if (this->element[1] > high.element[1]) this->element[1] = high.element[1];
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
void corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Definition at line 407 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
Vector2d< Int32x4 > corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Definition at line 420 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
bool corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::notTooFar (const Vector2d< Int32x4 > & that, const Int32x4 & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator!= (const Vector2d< Int32x4 > & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator*= (const Int32x4 & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator+= (const Vector2d< Int32x4 > & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
Vector2d< Int32x4 > corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator-= (const Vector2d< Int32x4 > & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
Int32x8& corecvs::Int32x8::operator/= (int c) [inline]
Definition at line 34 of file int32x8.h.
References corecvs::FixedVectorBase< Vector2d< Int32x4 >, Int32x4, 2 >::element.
    {
        this->element[0] /= c;
        this->element[1] /= c;
        return *this;
    }
Int32x8& corecvs::Int32x8::operator/= (int c) [inline]
Definition at line 37 of file int32x8.h.
References corecvs::FixedVectorBase< Vector2d< Int32x4 >, Int32x4, 2 >::element.
    {
        this->element[0] /= c;
        this->element[1] /= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator/= (const Int32x4 & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::operator== (const Vector2d< Int32x4 > & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
Int32x4 & corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
const Int32x4 & corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
double corecvs::Vector2d< Int32x4 >::parallelogramOrientedAreaTo (const Vector2d< Int32x4 > & other) [inline, inherited]
The oriented area of the parallelogram built on the two vectors: this, and the given one.
Definition at line 138 of file vector2d.h.
References corecvs::Vector2d< ElementType >::leftNormal().
    {
        return *this & other.leftNormal();
    }
void corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
Vector2d< Int32x4 > * corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const Vector2d< Int32x4 > * corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
Vector2d<Int32x4 > corecvs::Vector2d< Int32x4 >::rightNormal () const [inline, inherited]
Definition at line 107 of file vector2d.h.
References corecvs::Vector2d< ElementType >::Vector2d(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
      return Vector2d(y(),-x());
    }
double corecvs::Vector2d< Int32x4 >::sineTo (const Vector2d< Int32x4 > & other) const [inline, inherited]
Definition at line 112 of file vector2d.h.
References corecvs::Vector2d< ElementType >::rightNormal().
    {
        double thisLength  = !(*this);
        double otherLength = !other;
        if (thisLength == 0.0 || otherLength == 0.0)
          return 0.0;
        double tangentCross = (*this) & other.rightNormal();
        return tangentCross / (thisLength * otherLength);
    }
int corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
static Reflection corecvs::Vector2d< Int32x4 >::staticInit () [inline, static, inherited]
Definition at line 174 of file vector2d.h.
References corecvs::Vector2d< ElementType >::FIELD_X, corecvs::Vector2d< ElementType >::FIELD_Y, and corecvs::Reflection::fields.
    {
        Reflection reflection;
        reflection.fields.push_back( new ReflectionType(FIELD_X, ElementType(0), "x") );
        reflection.fields.push_back( new ReflectionType(FIELD_Y, ElementType(0), "y") );
        return reflection;
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
Int32x4 corecvs::VectorOperationsBase< Vector2d< Int32x4 > , Int32x4 >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
double corecvs::Vector2d< Int32x4 >::triangleOrientedAreaTo (const Vector2d< Int32x4 > & other) [inline, inherited]
Definition at line 143 of file vector2d.h.
References corecvs::Vector2d< ElementType >::leftNormal().
    {
        return (*this & other.leftNormal()) / 2;
    }
Int32x4 & corecvs::Vector2d< Int32x4 >::x () [inline, inherited]
Definition at line 50 of file vector2d.h.
    {
        return (*this)[0];
    }
const Int32x4 & corecvs::Vector2d< Int32x4 >::x () const [inline, inherited]
Definition at line 60 of file vector2d.h.
    {
        return (*this)[0];
    }
Int32x4 & corecvs::Vector2d< Int32x4 >::y () [inline, inherited]
Definition at line 55 of file vector2d.h.
    {
        return (*this)[1];
    }
const Int32x4 & corecvs::Vector2d< Int32x4 >::y () const [inline, inherited]
Definition at line 65 of file vector2d.h.
    {
        return (*this)[1];
    }
Friends And Related Function Documentation
Int32x4 operator& (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V1, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
Vector2d< Int32x4 > operator* (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V1, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
Vector2d< Int32x4 > operator* (const Int32x4 & c, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
Vector2d< Int32x4 > operator* (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V, const Int32x4 & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
Vector2d< Int32x4 > operator+ (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V1, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
Vector2d< Int32x4 > operator- (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V1, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
Vector2d< Int32x4 > operator/ (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V1, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
Vector2d< Int32x4 > operator/ (const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & V, const Int32x4 & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
Int32x8 operator>> (const Int32x8 & left, uint32_t count) [friend]
TODO: Bring this to FixedVector.
Definition at line 43 of file int32x8.h.
{
    return Int32x8 ( left[0] >> count, left[1] >> count);
}
Int32x8 operator>> (const Int32x8 & left, uint32_t count) [friend]
TODO: Bring this to FixedVector.
Definition at line 43 of file int32x8.h.
{
    return Int32x8 ( left[0] >> count, left[1] >> count);
}
istream& operator>> (istream & in, VectorOperationsBase< Vector2d< Int32x4 >, Int32x4 > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
Int32x8 operator>>= (Int32x8 & left, uint32_t count) [friend]
Definition at line 48 of file int32x8.h.
{
    left[0] >>= count;
    left[1] >>= count;
    return left;
}
Int32x8 operator>>= (Int32x8 & left, uint32_t count) [friend]
Definition at line 48 of file int32x8.h.
{
    left[0] >>= count;
    left[1] >>= count;
    return left;
}
Member Data Documentation
Int32x4 corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
Referenced by Int32x8(), and operator/=().
const int corecvs::FixedVectorBase< Vector2d< Int32x4 > , Int32x4 , length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
Reflection corecvs::Vector2d< Int32x4 >::reflect [static, inherited]
Definition at line 170 of file vector2d.h.
The documentation for this class was generated from the following files:
core/math/neon/int32x8.h
core/math/sse/int32x8.h