DeepView: V4L2CameraDescriptor Class Reference
V4L2CameraDescriptor Class Reference
A wrapper over V4L2 to access the camera.
#include <V4L2.h>
Classes
struct ParamIdMapStruct
Public Types
enum State { UNINITIALIZED, STOPPED, STARTED, STATE_NUMBER }
Public Member Functions
V4L2CameraDescriptor ()
void allocBuffers (int _count)
Allocates given number of userside buffer structures.
int initCamera (string deviceName, int h, int w, int fpsnum, int fpsdenum, bool compressed)
int initCamera (string deviceName, const V4L2CameraMode &mode)
int initBuffers (unsigned loopQueueBufferNumber=LoopQueueBufferNumberDefault, unsigned loopQueueBufferNumberMin=LoopQueueBufferNumberMinDefault)
int start ()
int stop ()
int dequeue (V4L2BufferDescriptor &buffer)
int enqueue (V4L2BufferDescriptor buffer)
int queryCameraParameters (CameraParameters &params)
int setCaptureProperty (int id, int value)
int getCaptureProperty (int id, int *value)
int getCaptureName (string &name)
int getCaptureFormats (int *num, ImageCaptureInterface::CameraFormat *&formats)
~V4L2CameraDescriptor ()
Static Public Member Functions
static uint32_t getPropIdByVi (CameraParameters::CameraControls viId)
static
CameraParameters::CameraControls getViIdByProp (uint32_t v4l2Id)
Public Attributes
int state
string camFileName
name of the camera device (a UNIX path)
int deviceHandle
int formatH
int formatW
V4L2UsersideBuffer * buffers
unsigned count
number of buffers associated with current descriptor
unsigned queued
Static Public Attributes
static const unsigned LoopQueueBufferNumberDefault = 8
static const unsigned LoopQueueBufferNumberMinDefault = 5
static const int INVALID_HANDLE = -1
static const char * STATE_NAMES []
static const ParamIdMapStruct paramIdMap []
static const int paramIdMapSize = 17
Private Member Functions
int deinitCamera ()
int deinitBuffers ()
int queryParmeter (const uint32_t propID, v4l2_queryctrl &request) const
int setParmeter (const uint32_t propID, int value) const
int getParmeter (const uint32_t propID, int *value) const
void setFromQueryCtrl (CaptureParameter &param, v4l2_queryctrl &ctrl)
Detailed Description
A wrapper over V4L2 to access the camera.
Definition at line 72 of file V4L2.h.
Member Enumeration Documentation
enum V4L2CameraDescriptor::State
Enumerator:
UNINITIALIZED
STOPPED
STARTED
STATE_NUMBER
Definition at line 80 of file V4L2.h.
               {
        UNINITIALIZED,
        STOPPED,
        STARTED,
        STATE_NUMBER
    };
Constructor & Destructor Documentation
V4L2CameraDescriptor::V4L2CameraDescriptor () [inline]
Definition at line 100 of file V4L2.h.
                           :
        state(UNINITIALIZED),
        camFileName(""),
        deviceHandle(INVALID_HANDLE),
        formatH(0),
        formatW(0),
        buffers(NULL),
        count(0),
        queued(0)
    {}
V4L2CameraDescriptor::~V4L2CameraDescriptor ()
Definition at line 234 of file V4L2.cpp.
References buffers, deinitBuffers(), deinitCamera(), stop(), and SYNC_PRINT.
{
    stop();
    SYNC_PRINT(("V4L2CameraDescriptor::Deiniting camera structures\n"));
    deinitBuffers();
    SYNC_PRINT(("V4L2CameraDescriptor::Closing cameras\n"));
    deinitCamera();
    deletearr_safe(buffers);
}
Member Function Documentation
void V4L2CameraDescriptor::allocBuffers (int _count) [inline]
Allocates given number of userside buffer structures.
Definition at line 114 of file V4L2.h.
References buffers, and count.
Referenced by initBuffers().
    {
        count = _count;
        buffers = new V4L2UsersideBuffer[count];
    }
int V4L2CameraDescriptor::deinitBuffers () [private]
Definition at line 212 of file V4L2.cpp.
References buffers, camFileName, count, V4L2UsersideBuffer::length, V4L2UsersideBuffer::start, and SYNC_PRINT.
Referenced by ~V4L2CameraDescriptor().
{
    for (unsigned i = 0; i < count; i++)
    {
        V4L2UsersideBuffer *buffer = &(buffers[i]);
        if (buffer->start == NULL) {
            continue;
        }
        int result = munmap(buffer->start, buffer->length);
        if (result == -1)
        {
            SYNC_PRINT(("V4L2CameraDescriptor::deinitCamera(): Unable to close handle for camera %s \n", camFileName.c_str()));
            return 1;
        }
        buffer->length = 0;
        buffer->start  = NULL;
    }
    count = 0;
    return 0;
}
int V4L2CameraDescriptor::deinitCamera () [private]
Definition at line 103 of file V4L2.cpp.
References camFileName, deviceHandle, INVALID_HANDLE, and SYNC_PRINT.
Referenced by ~V4L2CameraDescriptor().
{
    if (deviceHandle == INVALID_HANDLE) {
        return 0;
    }
    SYNC_PRINT(("V4L2CameraDescriptor::deinitCamera(): closing camera %s \n", camFileName.c_str()));
    int result = close(deviceHandle);
    if (result == -1) {
        SYNC_PRINT(("V4L2CameraDescriptor::deinitCamera(): Unable to close handle for camera %s \n", camFileName.c_str()));
        return 1;
    }
    deviceHandle = INVALID_HANDLE;
    return 0;
}
int V4L2CameraDescriptor::dequeue (V4L2BufferDescriptor & buffer)
Definition at line 294 of file V4L2.cpp.
References camFileName, count, deviceHandle, INVALID_HANDLE, V4L2BufferDescriptor::isFilled, queued, and TRACE_DEQUEUE.
Referenced by V4L2CaptureDecoupleInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    if (deviceHandle == INVALID_HANDLE) {
        return 1;
    }
    bufferDescr.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    bufferDescr.memory = V4L2_MEMORY_MMAP;
    bufferDescr.isFilled = false;
    if (ioctl (deviceHandle, VIDIOC_DQBUF, &bufferDescr) == -1)
    {
        printf ("Unable to dequeue buffer (%d) on camera %s(handle 0x%X). Error:%s\n",
                errno,
                camFileName.c_str(),
                deviceHandle,
                strerror(errno));
        return 1;
    }
    if (bufferDescr.index >= count)
    {
        printf("Dequeue returned buffer id %d (expcted number < %d) for camera %s(handle 0x%X).\n",
               bufferDescr.index, count,
               camFileName.c_str(),
               deviceHandle);
        return 1;
    }
    queued--;
    TRACE_DEQUEUE(("Dequeued %d (%x) [%d]\n", bufferDescr.index, cam->deviceHandle, cam->queued));
    bufferDescr.isFilled = true;
    return 0;
}
int V4L2CameraDescriptor::enqueue (V4L2BufferDescriptor buffer)
Definition at line 329 of file V4L2.cpp.
References deviceHandle, INVALID_HANDLE, V4L2BufferDescriptor::isFilled, queued, and TRACE_DEQUEUE.
Referenced by V4L2CaptureDecoupleInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    if (deviceHandle == INVALID_HANDLE) {
        return 1;
    }
    if (!buffer.isFilled)
    {
        printf("Empty Buffer. Will not enqueue\n");
        return 0;
    }
    if (ioctl (deviceHandle, VIDIOC_QBUF, &buffer) == -1)
    {
        printf ("Unable to requeue buffer (%d).\n", errno);
        return 1;
    }
    queued++;
    TRACE_DEQUEUE(("Enqueued %d (%x) [%d]\n", buffer.index, cam->deviceHandle,  cam->queued));
    return 0;
}
int V4L2CameraDescriptor::getCaptureFormats (int * num, ImageCaptureInterface::CameraFormat *& formats)
Definition at line 575 of file V4L2.cpp.
References deviceHandle, ImageCaptureInterface::CameraFormat::fps, ImageCaptureInterface::CameraFormat::height, INVALID_HANDLE, and ImageCaptureInterface::CameraFormat::width.
Referenced by V4L2CaptureInterface::getFormats().
{
    if (deviceHandle == INVALID_HANDLE) {
        return -1;
    }
    vector<ImageCaptureInterface::CameraFormat> cameraFormats;
    struct v4l2_fmtdesc fmt;
    memset(&fmt, 0, sizeof(fmt));
    fmt.index = 0;
    fmt.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    while (ioctl(deviceHandle, VIDIOC_ENUM_FMT, &fmt) == 0)
    {
        struct v4l2_frmsizeenum fsize;
        memset(&fsize, 0, sizeof(fsize));
        fsize.index = 0;
        fsize.pixel_format = fmt.pixelformat;
        while (ioctl(deviceHandle, VIDIOC_ENUM_FRAMESIZES, &fsize) == 0)
        {
            if (fsize.type != V4L2_FRMSIZE_TYPE_DISCRETE)
            {
                break;
            }
            struct v4l2_frmivalenum fival;
            memset(&fival, 0, sizeof(fival));
            fival.index = 0;
            fival.pixel_format = fmt.pixelformat;
            fival.width = fsize.discrete.width;
            fival.height = fsize.discrete.height;
            while (ioctl(deviceHandle, VIDIOC_ENUM_FRAMEINTERVALS, &fival) == 0)
            {
                if (fival.type != V4L2_FRMIVAL_TYPE_DISCRETE)
                {
                    break;
                }
                ImageCaptureInterface::CameraFormat cameraFormat;
                cameraFormat.height = fsize.discrete.height;
                cameraFormat.width = fsize.discrete.width;
                cameraFormat.fps = fival.discrete.denominator / fival.discrete.numerator;
                cameraFormats.push_back(cameraFormat);
                fival.index++;
            }
            fsize.index++;
        }
        fmt.index++;
    }
    *num = cameraFormats.size();
    formats = new ImageCaptureInterface::CameraFormat[cameraFormats.size()];
    for (unsigned i = 0; i < cameraFormats.size(); i ++)
    {
        formats[i] = cameraFormats[i];
    }
    return 0;
}
int V4L2CameraDescriptor::getCaptureName (string & name)
Definition at line 562 of file V4L2.cpp.
References deviceHandle, and INVALID_HANDLE.
Referenced by V4L2CaptureInterface::getCaptureName().
{
    struct v4l2_capability video_cap;
    if (deviceHandle == INVALID_HANDLE || ioctl(deviceHandle, VIDIOC_QUERYCAP, &video_cap) == -1)
    {
        printf("Couldn't get name of camera with handle %d\n", deviceHandle);
        return -1;
    }
    name = (char *)video_cap.card;
    return 0;
}
int V4L2CameraDescriptor::getCaptureProperty (int id, int * value)
Definition at line 548 of file V4L2.cpp.
References deviceHandle, CameraParameters::getName(), getParmeter(), getPropIdByVi(), and SYNC_PRINT.
Referenced by V4L2CaptureDecoupleInterface::getCaptureProperty(), and V4L2CaptureInterface::getCaptureProperty().
{
    uint32_t v4l2Id = getPropIdByVi((CameraParameters::CameraControls)id);
    if(getParmeter(v4l2Id, value) != 0)
    {
        SYNC_PRINT(("V4L2CameraDescriptor::getCaptureProperty(): Failed to get %s for device (%d)\n",
            CameraParameters::getName((CameraParameters::CameraControls)id),
            deviceHandle
        ));
    }
    return 0;
}
int V4L2CameraDescriptor::getParmeter (const uint32_t propID, int * value) const [private]
Definition at line 396 of file V4L2.cpp.
References deviceHandle, and INVALID_HANDLE.
Referenced by getCaptureProperty().
{
    if (deviceHandle == INVALID_HANDLE) {
        return -1;
    }
    v4l2_control request;
    request.id = propID;
    request.value = 0;
    int result = ioctl( deviceHandle, VIDIOC_G_CTRL, &request);
    if ( result != 0 )
    {
        printf( "V4L2CameraDescriptor::getParmeter():VIDIOC_S_CTRL for %d with value %d failed. (%s)\n", propID, request.value, strerror(errno) );
        return -1;
    }
    *value = request.value;
    return 0;
}
uint32_t V4L2CameraDescriptor::getPropIdByVi (CameraParameters::CameraControls viId) [static]
Definition at line 495 of file V4L2.cpp.
References paramIdMap, paramIdMapSize, and V4L2CameraDescriptor::ParamIdMapStruct::v4l2PropID.
Referenced by getCaptureProperty(), and setCaptureProperty().
{
    for (int i = 0; i < paramIdMapSize; i++) {
        if (viId == paramIdMap[i].viParamId) {
            return paramIdMap[i].v4l2PropID;
        }
    }
    return 0;
}
CameraParameters::CameraControls V4L2CameraDescriptor::getViIdByProp (uint32_t v4l2Id) [static]
Definition at line 506 of file V4L2.cpp.
References Operation::FIRST, paramIdMap, paramIdMapSize, and V4L2CameraDescriptor::ParamIdMapStruct::viParamId.
{
    for (int i = 0; i < paramIdMapSize; i++) {
        if (v4l2Id == paramIdMap[i].v4l2PropID) {
            return paramIdMap[i].viParamId;
        }
    }
    return CameraParameters::FIRST;
}
int V4L2CameraDescriptor::initBuffers (unsigned loopQueueBufferNumber = LoopQueueBufferNumberDefault, unsigned loopQueueBufferNumberMin = LoopQueueBufferNumberMinDefault)
Definition at line 118 of file V4L2.cpp.
References allocBuffers(), buffers, camFileName, count, deviceHandle, V4L2UsersideBuffer::length, queued, V4L2UsersideBuffer::start, state, and STOPPED.
Referenced by V4L2CaptureDecoupleInterface::initCapture(), and V4L2CaptureInterface::initCapture().
{
    /* Now we need to create buffers and tell driver about them */
    struct v4l2_requestbuffers reqbuf;
    memset (&reqbuf, 0, sizeof (reqbuf));
    reqbuf.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    reqbuf.memory = V4L2_MEMORY_MMAP;
    reqbuf.count = loopQueueBufferNumber;
    if (ioctl (deviceHandle, VIDIOC_REQBUFS, &reqbuf) == -1)
    {
        printf ("Unable to allocate buffers in kernel for camera %s (handle 0x%X)"
                ". VIDIOC_REQBUFS failure (%d): %s.\n",
                camFileName.c_str(),
                deviceHandle,
                errno,
                strerror(errno));
        return -1;
    }
    /* We want at least five buffers. */
    if (reqbuf.count < loopQueueBufferNumberMin)
    {
        printf ("Not enough buffer memory (requested %d got %d)in kernel for camera %s (handle 0x%X)\n",
                loopQueueBufferNumberMin,
                reqbuf.count,
                camFileName.c_str(),
                deviceHandle
                );
        return -1;
    }
    printf("Allocated %d kernel buffers for camera %s (handle 0x%X)\n",
           reqbuf.count,
           camFileName.c_str(),
           deviceHandle);
    allocBuffers(reqbuf.count);
    /*Map kernel buffers to user side ones */
    for (unsigned i = 0; i < count; i++)
    {
        struct v4l2_buffer buffer;
        memset (&buffer, 0, sizeof (buffer));
        buffer.type = reqbuf.type;
        buffer.memory = V4L2_MEMORY_MMAP;
        buffer.index = i;
        if (ioctl (deviceHandle, VIDIOC_QUERYBUF, &buffer) == -1)
        {
            printf ("VIDIOC_QUERYBUF request failed\n");
            return -1;
        }
        buffers[i].length = buffer.length; /* remember for munmap() */
        void *ptr = mmap (NULL, buffer.length,
                          PROT_READ | PROT_WRITE, /* recommended */
                          MAP_SHARED,             /* recommended */
                          deviceHandle, buffer.m.offset);
        if (ptr == MAP_FAILED)
        {
            printf ("Memmap failed\n");
            return -1;
        }
        buffers[i].start = ptr;
    }
    /* Queue the buffers. */
    for (unsigned i = 0; i < count; i++) {
        struct v4l2_buffer buffer;
        memset (&buffer, 0, sizeof (struct v4l2_buffer));
        buffer.index = i;
        buffer.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
        buffer.memory = V4L2_MEMORY_MMAP;
        if (ioctl (deviceHandle, VIDIOC_QBUF, &buffer) == -1)
        {
            printf ("Unable to queue buffer (%d).\n", errno);
            return -1;
        }
    }
    queued = count;
    state = STOPPED;
    /* TODO: release resources on failure */
    return 0;
}
int V4L2CameraDescriptor::initCamera (string deviceName, int h, int w, int fpsnum, int fpsdenum, bool compressed)
Definition at line 38 of file V4L2.cpp.
References camFileName, deviceHandle, formatH, formatW, INVALID_HANDLE, and SYNC_PRINT.
Referenced by V4L2CaptureInterface::getAllCameras(), initCamera(), V4L2CaptureDecoupleInterface::initCapture(), and V4L2CaptureInterface::initCapture().
{
    camFileName = std::string(deviceName);
    deviceHandle = open( deviceName.c_str(), O_RDWR );
    if (deviceHandle == -1)
    {
        SYNC_PRINT(("Video open error for device %s\n", deviceName.c_str()));
        deviceHandle = INVALID_HANDLE;
        return 1;
    }
    /* Setting input format */
    struct v4l2_format format;
    memset (&format, 0, sizeof (struct v4l2_format));
    format.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    format.fmt.pix.width  = w;
    format.fmt.pix.height = h;
    format.fmt.pix.pixelformat = compressed ? V4L2_PIX_FMT_MJPEG: V4L2_PIX_FMT_YUYV;
    format.fmt.pix.field = V4L2_FIELD_ANY;
    if (ioctl (deviceHandle, VIDIOC_S_FMT, &format) == -1) {
        SYNC_PRINT(("Unable to set %d format for camera %s. Error: %s\n", V4L2_BUF_TYPE_VIDEO_CAPTURE, deviceName.c_str(), strerror(errno)));
        return 2;
    }
    formatH = format.fmt.pix.height;
    formatW = format.fmt.pix.width;
    printf("Set dimensions [%d x %d] for camera %s\n", format.fmt.pix.width, format.fmt.pix.height, deviceName.c_str());
    /* Setting up FPS */
    struct v4l2_streamparm streamparm;
    memset (&streamparm, 0, sizeof (streamparm ));
    streamparm.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    streamparm.parm.capture.timeperframe.numerator = fpsnum;
    streamparm.parm.capture.timeperframe.denominator = fpsdenum;
    if(ioctl( deviceHandle, VIDIOC_S_PARM, &streamparm) == -1)
    {
        SYNC_PRINT(("Unable to set FPS for camera %s \n", deviceName.c_str()));
        return 3;
    }
    /*
    v4l2_control req;
    req.id = V4L2_CID_EXPOSURE_AUTO;
    req.value = V4L2_EXPOSURE_APERTURE_PRIORITY;
    if (ioctl(deviceID, VIDIOC_S_CTRL, &req))
        printf("VIDIOC_S_CTRL for V4L2_CID_EXPOSURE_AUTO failed. (%s) for %s\n", strerror(errno), deviceName.c_str());
    req.id = V4L2_CID_AUTOGAIN;
    req.value = true;
    if (ioctl(deviceID, VIDIOC_S_CTRL, &req))
        printf("VIDIOC_S_CTRL for V4L2_CID_AUTOGAIN failed. (%s) for %s\n", strerror(errno), deviceName.c_str());
    */
    return 0;
}
int V4L2CameraDescriptor::initCamera (string deviceName, const V4L2CameraMode & mode)
Definition at line 33 of file V4L2.cpp.
References V4L2CameraMode::compressed, V4L2CameraMode::fpsdenum, V4L2CameraMode::fpsnum, V4L2CameraMode::height, initCamera(), and V4L2CameraMode::width.
{
    return initCamera(deviceName, mode.height, mode.width, mode.fpsnum, mode.fpsdenum, mode.compressed);
}
int V4L2CameraDescriptor::queryCameraParameters (CameraParameters & params)
Definition at line 517 of file V4L2.cpp.
References CameraParameters::mCameraControls, paramIdMap, paramIdMapSize, queryParmeter(), setFromQueryCtrl(), and V4L2CameraDescriptor::ParamIdMapStruct::viParamId.
Referenced by V4L2CaptureDecoupleInterface::queryCameraParameters(), and V4L2CaptureInterface::queryCameraParameters().
{
    v4l2_queryctrl ctrl;
    for (int i = 0; i < paramIdMapSize; i++)
    {
        int result = queryParmeter(paramIdMap[i].v4l2PropID, ctrl);
        if (result == 0) {
            setFromQueryCtrl(params.mCameraControls[paramIdMap[i].viParamId], ctrl);
        } else {
            /*SYNC_PRINT(("\tThe parameter %d (%s) is either non-existent or not supported.\n",
                    paramIdMap[i].v4l2PropID,
                    CameraParameters::getName(paramIdMap[i].viParamId)));*/
        }
    }
    return true;
}
int V4L2CameraDescriptor::queryParmeter (const uint32_t propID, v4l2_queryctrl & request) const [private]
Definition at line 354 of file V4L2.cpp.
References deviceHandle, DOTRACE, and INVALID_HANDLE.
Referenced by queryCameraParameters().
{
    if (deviceHandle == INVALID_HANDLE) {
        return -1;
    }
    //printf("Querying the attributes of %s parameter\n", text);
    memset(&request, 0, sizeof (v4l2_queryctrl));
    request.id = propID;
    if (ioctl(deviceHandle, VIDIOC_QUERYCTRL, &request))
    {
        if (EINVAL == errno) {
            DOTRACE(("\tThe parameter %d is either non-existent or not supported.\n", propID));
        } else {
            printf("VIDIOC_QUERYCTRL request failed. (%s)\n", strerror(errno));
        }
        return -1;
    }
    return 0;
}
int V4L2CameraDescriptor::setCaptureProperty (int id, int value)
Definition at line 535 of file V4L2.cpp.
References deviceHandle, CameraParameters::getName(), getPropIdByVi(), setParmeter(), and SYNC_PRINT.
Referenced by V4L2CaptureDecoupleInterface::setCaptureProperty(), and V4L2CaptureInterface::setCaptureProperty().
{
    uint32_t v4l2Id = getPropIdByVi((CameraParameters::CameraControls)id);
    if (setParmeter(v4l2Id, value) != 0)
    {
        SYNC_PRINT(("V4L2CameraDescriptor::setCaptureProperty(): Failed to set %s for device (%d)\n",
            CameraParameters::getName((CameraParameters::CameraControls)id),
            deviceHandle
            ));
    }
    return 0;
}
void V4L2CameraDescriptor::setFromQueryCtrl (CaptureParameter & param, v4l2_queryctrl & ctrl) [private]
Definition at line 417 of file V4L2.cpp.
References deviceHandle, CaptureParameter::pushMenuItem(), CaptureParameter::setActive(), CaptureParameter::setDefaultValue(), CaptureParameter::setIsMenu(), CaptureParameter::setMaximum(), and CaptureParameter::setMinimum().
Referenced by queryCameraParameters().
{
    param = CaptureParameter();
    param.setMinimum(ctrl.minimum);
    param.setMaximum(ctrl.maximum);
    param.setDefaultValue(ctrl.default_value);
    if (ctrl.type == V4L2_CTRL_TYPE_MENU)
    {
        param.setIsMenu(true);
        if (ctrl.id != V4L2_CID_EXPOSURE_AUTO)
        {
            /* Query menu items */
            for (int index = ctrl.minimum; index <= ctrl.maximum; index++ )
            {
                struct v4l2_querymenu menuRequest;
                memset(&menuRequest, 0, sizeof(menuRequest));
                menuRequest.id = ctrl.id;
                menuRequest.index = index;
                int result = ioctl( deviceHandle, VIDIOC_QUERYMENU, &menuRequest);
                if ( result != 0 )
                {
                    printf( "VIDIOC_QUERYMENU for %d with index %d failed. (%s)\n", ctrl.id, index, strerror(errno) );
                    return;
                } else {
                 //   printf( "       MenuItem: %s\n", menuRequest.name);
                    param.pushMenuItem(QString("%1").arg((const char *)menuRequest.name), index);
                }
            }
        } else {
            printf( "   Menu V4L2_EXPOSURE\n");
            param.pushMenuItem(QString("Manual Exposture"),             V4L2_EXPOSURE_MANUAL);
            param.pushMenuItem(QString("Auto Exposture"),               V4L2_EXPOSURE_AUTO);
            param.pushMenuItem(QString("Shutter Priotiry Exposture"),   V4L2_EXPOSURE_SHUTTER_PRIORITY);
            param.pushMenuItem(QString("Apperture Priority Exposture"), V4L2_EXPOSURE_APERTURE_PRIORITY);
        }
    }
    if (ctrl.type == V4L2_CTRL_TYPE_BOOLEAN)
    {
        param.setIsMenu(true);
        param.pushMenuItem(QString("False"), 0);
        param.pushMenuItem(QString("True") , 1);
    }
    if (!(ctrl.flags & (V4L2_CTRL_FLAG_DISABLED | V4L2_CTRL_FLAG_GRABBED | V4L2_CTRL_FLAG_READ_ONLY | V4L2_CTRL_FLAG_INACTIVE)))
    {
        param.setActive(true);
    }
}
int V4L2CameraDescriptor::setParmeter (const uint32_t propID, int value) const [private]
Definition at line 377 of file V4L2.cpp.
References deviceHandle, and INVALID_HANDLE.
Referenced by setCaptureProperty().
{
    if (deviceHandle == INVALID_HANDLE) {
        return -1;
    }
    v4l2_control request;
    request.id = propID;
    request.value = value;
    int result = ioctl( deviceHandle, VIDIOC_S_CTRL, &request);
    if ( result != 0 )
    {
        printf( "V4L2CameraDescriptor::setParmeter(): VIDIOC_S_CTRL for %d with value %d failed. (%s)\n", propID, value, strerror(errno) );
        return -1;
    }
    return 0;
}
int V4L2CameraDescriptor::start ()
Definition at line 244 of file V4L2.cpp.
References camFileName, deviceHandle, STARTED, state, STATE_NAMES, STOPPED, and SYNC_PRINT.
Referenced by V4L2CaptureDecoupleInterface::startCapture(), and V4L2CaptureInterface::startCapture().
{
    if (state != STOPPED) {
        SYNC_PRINT(("V4L2CameraDescriptor::Trying to start camera in state <%s>\n", STATE_NAMES[state]));
        return -1;
    }
    uint32_t type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    //printf ( "Device 0x%X is about to start video capture.\n", cam->deviceHandle);
    if (ioctl (deviceHandle, VIDIOC_STREAMON, &type) == -1) {
        printf ( "Unable to start capture: %d on camera %s (handle 0x%X):%s\n",
                errno,
                camFileName.c_str(),
                deviceHandle,
                strerror(errno));
        return -1;
    }
    state = STARTED;
    return 0;
}
int V4L2CameraDescriptor::stop ()
Definition at line 267 of file V4L2.cpp.
References camFileName, deviceHandle, INVALID_HANDLE, STARTED, state, STATE_NAMES, STOPPED, and SYNC_PRINT.
Referenced by ~V4L2CameraDescriptor(), V4L2CaptureDecoupleInterface::~V4L2CaptureDecoupleInterface(), and V4L2CaptureInterface::~V4L2CaptureInterface().
{
    if (deviceHandle == INVALID_HANDLE) {
        return 0;
    }
    if (state != STARTED) {
        SYNC_PRINT(("V4L2CameraDescriptor::Trying to stop camera that is in state <%s>\n", STATE_NAMES[state]));
        return -1;
    }
    uint32_t type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    //printf ( "Device 0x%X is about to stop video capture.\n", cam->deviceHandle);
    if (ioctl (deviceHandle, VIDIOC_STREAMOFF, &type) == -1) {
        printf ( "Unable to stop capture: %d on camera %s (handle 0x%X).\n",
                 errno,
                 camFileName.c_str(),
                 deviceHandle);
        return -1;
    }
    state = STOPPED;
    return 0;
}
Member Data Documentation
V4L2UsersideBuffer* V4L2CameraDescriptor::buffers
Definition at line 96 of file V4L2.h.
Referenced by allocBuffers(), V4L2CaptureInterface::decodeData(), V4L2CaptureInterface::decodeDataRGB24(), deinitBuffers(), V4L2CaptureDecoupleInterface::getFrame(), initBuffers(), and ~V4L2CameraDescriptor().
string V4L2CameraDescriptor::camFileName
name of the camera device (a UNIX path)
Definition at line 90 of file V4L2.h.
Referenced by deinitBuffers(), deinitCamera(), dequeue(), initBuffers(), initCamera(), start(), and stop().
unsigned V4L2CameraDescriptor::count
number of buffers associated with current descriptor
Definition at line 97 of file V4L2.h.
Referenced by allocBuffers(), deinitBuffers(), dequeue(), and initBuffers().
int V4L2CameraDescriptor::deviceHandle
Definition at line 91 of file V4L2.h.
Referenced by deinitCamera(), dequeue(), enqueue(), getCaptureFormats(), getCaptureName(), getCaptureProperty(), getParmeter(), initBuffers(), initCamera(), queryParmeter(), V4L2CaptureInterface::SpinThread::run(), setCaptureProperty(), setFromQueryCtrl(), setParmeter(), start(), and stop().
int V4L2CameraDescriptor::formatH
Definition at line 93 of file V4L2.h.
Referenced by initCamera(), V4L2CaptureDecoupleInterface::initCapture(), and V4L2CaptureInterface::initCapture().
int V4L2CameraDescriptor::formatW
Definition at line 94 of file V4L2.h.
Referenced by initCamera(), V4L2CaptureDecoupleInterface::initCapture(), and V4L2CaptureInterface::initCapture().
const int V4L2CameraDescriptor::INVALID_HANDLE = -1 [static]
Definition at line 78 of file V4L2.h.
Referenced by deinitCamera(), dequeue(), enqueue(), getCaptureFormats(), getCaptureName(), getParmeter(), initCamera(), queryParmeter(), V4L2CaptureInterface::SpinThread::run(), setParmeter(), and stop().
const unsigned V4L2CameraDescriptor::LoopQueueBufferNumberDefault = 8 [static]
Definition at line 75 of file V4L2.h.
const unsigned V4L2CameraDescriptor::LoopQueueBufferNumberMinDefault = 5 [static]
Definition at line 76 of file V4L2.h.
const V4L2CameraDescriptor::ParamIdMapStruct V4L2CameraDescriptor::paramIdMap [static]
Initial value:
{
        {V4L2_CID_EXPOSURE_ABSOLUTE, CameraParameters::EXPOSURE},
        {V4L2_CID_EXPOSURE_AUTO    , CameraParameters::EXPOSURE_AUTO},
        {V4L2_CID_EXPOSURE         , CameraParameters::EXPOSURE_REL},
        {V4L2_CID_GAIN             , CameraParameters::GAIN},
        {V4L2_CID_AUTOGAIN         , CameraParameters::GAIN_AUTO},
        {V4L2_CID_BRIGHTNESS       , CameraParameters::BRIGHTNESS},
        {V4L2_CID_CONTRAST         , CameraParameters::CONTRAST},
        {V4L2_CID_SATURATION       , CameraParameters::SATURATION},
        {V4L2_CID_HUE              , CameraParameters::HUE},
        {V4L2_CID_SHARPNESS        , CameraParameters::SHARPNESS},
        {V4L2_CID_GAMMA            , CameraParameters::GAMMA},
        {V4L2_CID_POWER_LINE_FREQUENCY     , CameraParameters::POWER_LINE_FREQUENCY},
        {V4L2_CID_BACKLIGHT_COMPENSATION   , CameraParameters::BACKLIGHT_COMPENSATION},
        {V4L2_CID_WHITE_BALANCE_TEMPERATURE, CameraParameters::WHITE_BALANCE},
        {V4L2_CID_AUTO_WHITE_BALANCE, CameraParameters::AUTO_WHITE_BALANCE},
        {V4L2_CID_HFLIP, CameraParameters::HORIZONTAL_FLIP},
        {V4L2_CID_VFLIP, CameraParameters::VERTICAL_FLIP}
}
Definition at line 159 of file V4L2.h.
Referenced by getPropIdByVi(), getViIdByProp(), and queryCameraParameters().
const int V4L2CameraDescriptor::paramIdMapSize = 17 [static]
Definition at line 160 of file V4L2.h.
Referenced by getPropIdByVi(), getViIdByProp(), and queryCameraParameters().
unsigned V4L2CameraDescriptor::queued
Definition at line 98 of file V4L2.h.
Referenced by dequeue(), enqueue(), and initBuffers().
int V4L2CameraDescriptor::state
Definition at line 89 of file V4L2.h.
Referenced by initBuffers(), start(), and stop().
const char * V4L2CameraDescriptor::STATE_NAMES [static]
Initial value:
{
    "UNINITIALIZED",
    "STOPPED",
    "STARTED"
}
Definition at line 87 of file V4L2.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
utils/framesources/v4l2/V4L2.h
utils/framesources/v4l2/V4L2.cpp