DeepView: CannyParameters Class Reference
CannyParameters Class Reference
Canny Parameters Canny Parameters.
#include <cannyParameters.h>
Public Types
enum FieldId { SHOULD_EDGE_DETECT_ID, MINIMUM_THRESHOLD_ID, MAXIMUM_THRESHOLD_ID, CANNY_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
bool shouldEdgeDetect () const
int minimumThreshold () const
int maximumThreshold () const
void setShouldEdgeDetect (bool shouldEdgeDetect)
void setMinimumThreshold (int minimumThreshold)
void setMaximumThreshold (int maximumThreshold)
template<class VisitorType >
void accept (VisitorType &visitor)
CannyParameters ()
CannyParameters (bool shouldEdgeDetect, int minimumThreshold, int maximumThreshold)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
bool mShouldEdgeDetect
Section with variables.
int mMinimumThreshold
Minimum threshold Minimum threshold.
int mMaximumThreshold
Maximum threshold Maximum threshold.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, CannyParameters &toSave)
Detailed Description
Canny Parameters Canny Parameters.
Definition at line 38 of file cannyParameters.h.
Member Enumeration Documentation
enum CannyParameters::FieldId
Enumerator:
SHOULD_EDGE_DETECT_ID
MINIMUM_THRESHOLD_ID
MAXIMUM_THRESHOLD_ID
CANNY_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file cannyParameters.h.
                 {
        SHOULD_EDGE_DETECT_ID,
        MINIMUM_THRESHOLD_ID,
        MAXIMUM_THRESHOLD_ID,
        CANNY_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
CannyParameters::CannyParameters () [inline]
Definition at line 117 of file cannyParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
CannyParameters::CannyParameters (bool shouldEdgeDetect, int minimumThreshold, int maximumThreshold) [inline]
Definition at line 123 of file cannyParameters.h.
    {
        mShouldEdgeDetect = shouldEdgeDetect;
        mMinimumThreshold = minimumThreshold;
        mMaximumThreshold = maximumThreshold;
    }
Member Function Documentation
template<class VisitorType > void CannyParameters::accept (VisitorType & visitor) [inline]
Definition at line 110 of file cannyParameters.h.
Referenced by corecvs::CannyFilter::deserialize(), and corecvs::CannyFilter::serialize().
    {
        visitor.visit(mShouldEdgeDetect,          static_cast<const BoolField *>    (fields()[SHOULD_EDGE_DETECT_ID]));
        visitor.visit(mMinimumThreshold,          static_cast<const IntField *>     (fields()[MINIMUM_THRESHOLD_ID]));
        visitor.visit(mMaximumThreshold,          static_cast<const IntField *>     (fields()[MAXIMUM_THRESHOLD_ID]));
    }
static const char* corecvs::BaseReflection< CannyParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< CannyParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< CannyParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* CannyParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 72 of file cannyParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< CannyParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
int CannyParameters::maximumThreshold () const [inline]
Definition at line 86 of file cannyParameters.h.
Referenced by corecvs::CannyFilter::operator()(), and CannyParametersControlWidget::setParameters().
    {
        return mMaximumThreshold;
    }
int CannyParameters::minimumThreshold () const [inline]
Definition at line 81 of file cannyParameters.h.
Referenced by corecvs::CannyFilter::operator()(), and CannyParametersControlWidget::setParameters().
    {
        return mMinimumThreshold;
    }
static const char* corecvs::BaseReflection< CannyParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< CannyParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void CannyParameters::print () [inline]
Definition at line 141 of file cannyParameters.h.
    {
        cout << *this;
    }
void CannyParameters::setMaximumThreshold (int maximumThreshold) [inline]
Definition at line 102 of file cannyParameters.h.
    {
        mMaximumThreshold = maximumThreshold;
    }
void CannyParameters::setMinimumThreshold (int minimumThreshold) [inline]
Definition at line 97 of file cannyParameters.h.
    {
        mMinimumThreshold = minimumThreshold;
    }
void CannyParameters::setShouldEdgeDetect (bool shouldEdgeDetect) [inline]
Definition at line 92 of file cannyParameters.h.
    {
        mShouldEdgeDetect = shouldEdgeDetect;
    }
bool CannyParameters::shouldEdgeDetect () const [inline]
Definition at line 76 of file cannyParameters.h.
Referenced by corecvs::CannyFilter::operator()(), and CannyParametersControlWidget::setParameters().
    {
        return mShouldEdgeDetect;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int CannyParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file cannyParameters.cpp.
References corecvs::BaseReflection< CannyParameters >::fields(), MAXIMUM_THRESHOLD_ID, MINIMUM_THRESHOLD_ID, mMaximumThreshold, mMinimumThreshold, mShouldEdgeDetect, corecvs::BaseReflection< CannyParameters >::naming(), and SHOULD_EDGE_DETECT_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Canny Parameters",
        "Canny Parameters",
        ""
    );
    fields().push_back(
        new BoolField
        (
          CannyParameters::SHOULD_EDGE_DETECT_ID,
          offsetof(CannyParameters, mShouldEdgeDetect),
          false,
          "Should edge detect",
          "Should edge detect",
          "Should edge detect"
        )
    );
    fields().push_back(
        new IntField
        (
          CannyParameters::MINIMUM_THRESHOLD_ID,
          offsetof(CannyParameters, mMinimumThreshold),
          500,
          "Minimum threshold",
          "Minimum threshold",
          "Minimum threshold"
        )
    );
    fields().push_back(
        new IntField
        (
          CannyParameters::MAXIMUM_THRESHOLD_ID,
          offsetof(CannyParameters, mMaximumThreshold),
          1500,
          "Maximum threshold",
          "Maximum threshold",
          "Maximum threshold"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, CannyParameters & toSave) [friend]
Definition at line 134 of file cannyParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< CannyParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int CannyParameters::mMaximumThreshold
Maximum threshold Maximum threshold.
Definition at line 66 of file cannyParameters.h.
Referenced by staticInit().
int CannyParameters::mMinimumThreshold
Minimum threshold Minimum threshold.
Definition at line 60 of file cannyParameters.h.
Referenced by staticInit().
bool CannyParameters::mShouldEdgeDetect
Section with variables.
Should edge detect Should edge detect
Definition at line 54 of file cannyParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< CannyParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/cannyParameters.h
core/xml/generated/cannyParameters.cpp