DeepView: Recorder Class Reference
Recorder Class Reference
Recorder parameters Recorder parameters.
#include <recorder.h>
Public Types
enum FieldId { PATH_ID, FILETEMPLATE_ID, RECORDER_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
std::string path () const
std::string fileTemplate () const
void setPath (std::string path)
void setFileTemplate (std::string fileTemplate)
template<class VisitorType >
void accept (VisitorType &visitor)
Recorder ()
Recorder (std::string path, std::string fileTemplate)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
std::string mPath
Section with variables.
std::string mFileTemplate
fileTemplate fileTemplate
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, Recorder &toSave)
Detailed Description
Recorder parameters Recorder parameters.
Definition at line 38 of file recorder.h.
Member Enumeration Documentation
enum Recorder::FieldId
Enumerator:
PATH_ID
FILETEMPLATE_ID
RECORDER_FIELD_ID_NUM
Definition at line 41 of file recorder.h.
                 {
        PATH_ID,
        FILETEMPLATE_ID,
        RECORDER_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
Recorder::Recorder () [inline]
Definition at line 99 of file recorder.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
Recorder::Recorder (std::string path, std::string fileTemplate) [inline]
Definition at line 105 of file recorder.h.
    {
        mPath = path;
        mFileTemplate = fileTemplate;
    }
Member Function Documentation
template<class VisitorType > void Recorder::accept (VisitorType & visitor) [inline]
Definition at line 93 of file recorder.h.
    {
        visitor.visit(mPath,                      static_cast<const StringField *>  (fields()[PATH_ID]));
        visitor.visit(mFileTemplate,              static_cast<const StringField *>  (fields()[FILETEMPLATE_ID]));
    }
static const char* corecvs::BaseReflection< Recorder >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< Recorder >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< Recorder >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
std::string Recorder::fileTemplate () const [inline]
Definition at line 74 of file recorder.h.
Referenced by RecorderControlWidget::setParameters().
    {
        return mFileTemplate;
    }
const void* Recorder::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 65 of file recorder.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< Recorder >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< Recorder >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< Recorder >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
std::string Recorder::path () const [inline]
Definition at line 69 of file recorder.h.
Referenced by RecorderControlWidget::setParameters().
    {
        return mPath;
    }
void Recorder::print () [inline]
Definition at line 121 of file recorder.h.
    {
        cout << *this;
    }
void Recorder::setFileTemplate (std::string fileTemplate) [inline]
Definition at line 85 of file recorder.h.
    {
        mFileTemplate = fileTemplate;
    }
void Recorder::setPath (std::string path) [inline]
Definition at line 80 of file recorder.h.
    {
        mPath = path;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int Recorder::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file recorder.cpp.
References corecvs::BaseReflection< Recorder >::fields(), FILETEMPLATE_ID, mFileTemplate, mPath, corecvs::BaseReflection< Recorder >::naming(), and PATH_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Recorder",
        "Recorder parameters",
        ""
    );
    fields().push_back(
        new StringField
        (
          Recorder::PATH_ID,
          offsetof(Recorder, mPath),
          "",
          "path",
          "path",
          "path"
        )
    );
    fields().push_back(
        new StringField
        (
          Recorder::FILETEMPLATE_ID,
          offsetof(Recorder, mFileTemplate),
          "sequence_%04d_c%d.pgm",
          "fileTemplate",
          "fileTemplate",
          "fileTemplate"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, Recorder & toSave) [friend]
Definition at line 114 of file recorder.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< Recorder >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
std::string Recorder::mFileTemplate
fileTemplate fileTemplate
Definition at line 59 of file recorder.h.
Referenced by staticInit().
std::string Recorder::mPath
Section with variables.
path path
Definition at line 53 of file recorder.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< Recorder >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
applications/recorder/generatedParameters/recorder.h
applications/recorder/generatedParameters/recorder.cpp