DeepView: FilePreciseCapture::FileSpinThread Class Reference
FilePreciseCapture::FileSpinThread Class Reference
Public Member Functions
FileSpinThread (AbstractFileCapture *pInterface, int delay, ImageCaptureInterface::FramePair &framePair)
virtual bool grabFramePair ()
virtual void run ()
void togglePause ()
void nextFrame ()
Protected Member Functions
void pause ()
Protected Attributes
ImageCaptureInterface::FramePair & mFramePair
AbstractFileCapture * mInterface
Detailed Description
Definition at line 48 of file fileCapture.h.
Constructor & Destructor Documentation
FilePreciseCapture::FileSpinThread::FileSpinThread (AbstractFileCapture * pInterface, int delay, ImageCaptureInterface::FramePair & framePair)
Definition at line 127 of file fileCapture.cpp.
    : AbstractFileCaptureSpinThread(pInterface, delay, framePair)
{
}
Member Function Documentation
bool FilePreciseCapture::FileSpinThread::grabFramePair () [virtual]
Implements AbstractFileCaptureSpinThread.
Definition at line 132 of file fileCapture.cpp.
References ASSERT_TRUE, ImageFileCaptureInterface::getImageFileName(), ImageFileCaptureInterface::increaseImageFileCounter(), ImageFileCaptureInterface::mCount, FilePreciseCapture::mCurrentCount, AbstractFileCapture::mDelay, AbstractFileCapture::mShouldSkipUnclaimed, AbstractFileCapture::mTimeStamp, ImageFileCaptureInterface::mVerbose, and ImageFileCaptureInterface::resetImageFileCounter().
{
    FilePreciseCapture *pInterface = static_cast<FilePreciseCapture *>(mInterface);
    if (pInterface->mShouldSkipUnclaimed)
    {
        pInterface->increaseImageFileCounter();
        pInterface->mTimeStamp += pInterface->mDelay * 1000;
    }
    if ((int)pInterface->mCount != pInterface->mCurrentCount)
    {
        string leftFileName  = pInterface->getImageFileName(pInterface->mCount, 0);
        string rightFileName = pInterface->getImageFileName(pInterface->mCount, 1);
        if (QFile::exists(leftFileName.c_str()) &&
            QFile::exists(rightFileName.c_str()))
        {
            pInterface->mCurrentCount = pInterface->mCount;
            pInterface->mTimeStamp   += pInterface->mDelay * 1000;
            if (pInterface->mVerbose)
                printf("prec: Notification about frame %d : [%s|%s]\n",
                    pInterface->mCurrentCount,
                    leftFileName.c_str(),
                    rightFileName.c_str());
        }
        else
        {
            if (pInterface->mVerbose)
                printf("prec: File <%s> or <%s> not found, resetting to first image in the sequence\n",
                    leftFileName .c_str(),
                    rightFileName.c_str());
            // Protection from the stack overflow, when there're no files at the given path
            //
            if (pInterface->mCurrentCount < 0) {
                ASSERT_TRUE(pInterface->mCount == 1, "wrong image counting");
                return false;                               // there's no chance to detect the right path to files
            }
            pInterface->resetImageFileCounter();
            return grabFramePair();
        }
    }
    return true;
}
void AbstractFileCaptureSpinThread::nextFrame () [inherited]
Definition at line 63 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::mNextFrameNeeded.
Referenced by AbstractFileCapture::nextFrame().
{
    mNextFrameNeeded = true;
}
void AbstractFileCaptureSpinThread::pause () [protected, inherited]
Definition at line 68 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::mInterface, AbstractFileCaptureSpinThread::mPaused, and AbstractFileCapture::notifyAboutStreamPaused().
{
    mPaused = true;
    mInterface->notifyAboutStreamPaused();
}
void AbstractFileCaptureSpinThread::run () [virtual, inherited]
Definition at line 17 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::grabFramePair(), AbstractFileCaptureSpinThread::mDelay, AbstractFileCaptureSpinThread::mInterface, AbstractFileCaptureSpinThread::mNextFrameNeeded, AbstractFileCaptureSpinThread::mPaused, AbstractFileCapture::mTimeStamp, ImageCaptureInterface::notifyAboutNewFrame(), AbstractFileCapture::protectFrameMutex(), AbstractFileCapture::shouldStopSpinThread, AbstractFileCapture::spinThreadRunMutex(), and frame_data_t::timestamp.
{
    if (!grabFramePair())  // We must get a frame before querying for properties
    {
        printf("No frames.\n");
        return;
    }
    frame_data_t frameData;
    frameData.timestamp = mInterface->mTimeStamp;
    mInterface->notifyAboutNewFrame(frameData);
    while (mInterface->spinThreadRunMutex().tryLock())
    {
        if (mDelay != 0)
            msleep(mDelay);
        if (!mPaused || mNextFrameNeeded)
        {
            mNextFrameNeeded = false;
            mInterface->protectFrameMutex().lock();
                if (!grabFramePair()) {
                    printf("No more frames.\n");
                }
                else {
                    frame_data_t frameData;
                    frameData.timestamp = mInterface->mTimeStamp;
                    mInterface->notifyAboutNewFrame(frameData);
                }
            mInterface->protectFrameMutex().unlock();
        }
        mInterface->spinThreadRunMutex().unlock();
        if (mInterface->shouldStopSpinThread) {
            break;
        }
    }
}
void AbstractFileCaptureSpinThread::togglePause () [inherited]
Definition at line 58 of file abstractFileCaptureSpinThread.cpp.
References AbstractFileCaptureSpinThread::mPaused.
Referenced by AbstractFileCapture::pauseCapture().
{
    mPaused = !mPaused;
}
Member Data Documentation
ImageCaptureInterface::FramePair& AbstractFileCaptureSpinThread::mFramePair [protected, inherited]
Definition at line 22 of file abstractFileCaptureSpinThread.h.
AbstractFileCapture* AbstractFileCaptureSpinThread::mInterface [protected, inherited]
Definition at line 23 of file abstractFileCaptureSpinThread.h.
Referenced by AbstractFileCaptureSpinThread::pause(), and AbstractFileCaptureSpinThread::run().
The documentation for this class was generated from the following files:
utils/framesources/fileCapture.h
utils/framesources/fileCapture.cpp