DeepView: GainOffsetParameters Class Reference
GainOffsetParameters Class Reference
Gain Offset Parameters Gain Offset Parameters.
#include <gainOffsetParameters.h>
Public Types
enum FieldId { GAIN_ID, OFFSET_ID, GAIN_OFFSET_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
double gain () const
double offset () const
void setGain (double gain)
void setOffset (double offset)
template<class VisitorType >
void accept (VisitorType &visitor)
GainOffsetParameters ()
GainOffsetParameters (double gain, double offset)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
double mGain
Section with variables.
double mOffset
offset offset
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, GainOffsetParameters &toSave)
Detailed Description
Gain Offset Parameters Gain Offset Parameters.
Definition at line 38 of file gainOffsetParameters.h.
Member Enumeration Documentation
enum GainOffsetParameters::FieldId
Enumerator:
GAIN_ID
OFFSET_ID
GAIN_OFFSET_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file gainOffsetParameters.h.
                 {
        GAIN_ID,
        OFFSET_ID,
        GAIN_OFFSET_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
GainOffsetParameters::GainOffsetParameters () [inline]
Definition at line 99 of file gainOffsetParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
GainOffsetParameters::GainOffsetParameters (double gain, double offset) [inline]
Definition at line 105 of file gainOffsetParameters.h.
    {
        mGain = gain;
        mOffset = offset;
    }
Member Function Documentation
template<class VisitorType > void GainOffsetParameters::accept (VisitorType & visitor) [inline]
Definition at line 93 of file gainOffsetParameters.h.
Referenced by corecvs::GainOffsetFilter::deserialize(), and corecvs::GainOffsetFilter::serialize().
    {
        visitor.visit(mGain,                      static_cast<const DoubleField *>  (fields()[GAIN_ID]));
        visitor.visit(mOffset,                    static_cast<const DoubleField *>  (fields()[OFFSET_ID]));
    }
static const char* corecvs::BaseReflection< GainOffsetParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
References corecvs::BaseReflection< RealThis >::fields().
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< GainOffsetParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
References corecvs::BaseReflection< RealThis >::fields().
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< GainOffsetParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
References corecvs::Reflection::fields, and corecvs::BaseReflection< RealThis >::getReflection().
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
double GainOffsetParameters::gain () const [inline]
Definition at line 69 of file gainOffsetParameters.h.
Referenced by corecvs::GainOffsetFilter::operator()(), and GainOffsetParametersControlWidget::setParameters().
    {
        return mGain;
    }
const void* GainOffsetParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 65 of file gainOffsetParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< GainOffsetParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
References corecvs::BaseReflection< RealThis >::reflection().
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< GainOffsetParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
References corecvs::BaseReflection< RealThis >::fields().
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< GainOffsetParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
References corecvs::BaseReflection< RealThis >::getReflection(), and corecvs::Reflection::name.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
double GainOffsetParameters::offset () const [inline]
Definition at line 74 of file gainOffsetParameters.h.
Referenced by corecvs::GainOffsetFilter::operator()(), and GainOffsetParametersControlWidget::setParameters().
    {
        return mOffset;
    }
void GainOffsetParameters::print () [inline]
Definition at line 121 of file gainOffsetParameters.h.
    {
        cout << *this;
    }
void GainOffsetParameters::setGain (double gain) [inline]
Definition at line 80 of file gainOffsetParameters.h.
    {
        mGain = gain;
    }
void GainOffsetParameters::setOffset (double offset) [inline]
Definition at line 85 of file gainOffsetParameters.h.
    {
        mOffset = offset;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int GainOffsetParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file gainOffsetParameters.cpp.
References corecvs::BaseReflection< GainOffsetParameters >::fields(), GAIN_ID, mGain, mOffset, corecvs::BaseReflection< GainOffsetParameters >::naming(), and OFFSET_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Gain Offset Parameters",
        "Gain Offset Parameters",
        ""
    );
    fields().push_back(
        new DoubleField
        (
          GainOffsetParameters::GAIN_ID,
          offsetof(GainOffsetParameters, mGain),
          1,
          "gain",
          "gain",
          "gain"
        )
    );
    fields().push_back(
        new DoubleField
        (
          GainOffsetParameters::OFFSET_ID,
          offsetof(GainOffsetParameters, mOffset),
          0,
          "offset",
          "offset",
          "offset"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, GainOffsetParameters & toSave) [friend]
Definition at line 114 of file gainOffsetParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< GainOffsetParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
double GainOffsetParameters::mGain
Section with variables.
gain gain
Definition at line 53 of file gainOffsetParameters.h.
Referenced by staticInit().
double GainOffsetParameters::mOffset
offset offset
Definition at line 59 of file gainOffsetParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< GainOffsetParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/gainOffsetParameters.h
core/xml/generated/gainOffsetParameters.cpp