DeepView: RectifyParametersControlWidget Class Reference
RectifyParametersControlWidget Class Reference
#include <rectifyParametersControlWidget.h>
Signals
void paramsChanged ()
Public Member Functions
RectifyParametersControlWidget (QWidget *parent, bool _autoInit, QString _rootPath)
~RectifyParametersControlWidget ()
QPushButton * getRectifyButton ()
QPushButton * getResetButton ()
QPushButton * getPointsMatchingButton ()
void setManualTab (CameraAngles &angle, Vector3dd &dir)
RectifyParameters * createParameters () const
void setParameters (const RectifyParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Protected Attributes
Ui_RectifyParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 15 of file rectifyParametersControlWidget.h.
Constructor & Destructor Documentation
RectifyParametersControlWidget::RectifyParametersControlWidget (QWidget * parent, bool _autoInit, QString _rootPath)
Definition at line 15 of file rectifyParametersControlWidget.cpp.
References mUi, and paramsChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::RectifyParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->matchingMethodComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->hessianThresholdSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->octavesSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->octaveLayersSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->extendedCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->filterMinimumLengthSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->useKLTCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->computeEssentialCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->priorFocalSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->priorFocal2SpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->baselineLengthSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fovAngleSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->estimationMethodComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->normaliseCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->ransacIterationsSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->ransacTestSizeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->ransacThresholdSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->baselineXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->baselineYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->baselineZSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->iterativeMethodComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->iterativeIterationsSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->iterativeInitialSigmaSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->iterativeFactorSigmaSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->manualXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->manualYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->manualZSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->manualPitchSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->manualYawSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->manualRollSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->zdirXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->zdirYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->zdirZSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->autoZCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->autoShiftCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->preShiftSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->guessShiftThresholdSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
RectifyParametersControlWidget::~RectifyParametersControlWidget ()
Definition at line 62 of file rectifyParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
RectifyParameters * RectifyParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 84 of file rectifyParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    RectifyParameters *result = new RectifyParameters(
          static_cast<MatchingMethodType::MatchingMethodType>(mUi->matchingMethodComboBox->currentIndex())
        , mUi->hessianThresholdSpinBox->value()
        , mUi->octavesSpinBox->value()
        , mUi->octaveLayersSpinBox->value()
        , mUi->extendedCheckBox->isChecked()
        , mUi->filterMinimumLengthSpinBox->value()
        , mUi->useKLTCheckBox->isChecked()
        , mUi->computeEssentialCheckBox->isChecked()
        , mUi->priorFocalSpinBox->value()
        , mUi->priorFocal2SpinBox->value()
        , mUi->baselineLengthSpinBox->value()
        , mUi->fovAngleSpinBox->value()
        , static_cast<EstimationMethodType::EstimationMethodType>(mUi->estimationMethodComboBox->currentIndex())
        , mUi->normaliseCheckBox->isChecked()
        , mUi->ransacIterationsSpinBox->value()
        , mUi->ransacTestSizeSpinBox->value()
        , mUi->ransacThresholdSpinBox->value()
        , mUi->baselineXSpinBox->value()
        , mUi->baselineYSpinBox->value()
        , mUi->baselineZSpinBox->value()
        , static_cast<OptimizationMethodType::OptimizationMethodType>(mUi->iterativeMethodComboBox->currentIndex())
        , mUi->iterativeIterationsSpinBox->value()
        , mUi->iterativeInitialSigmaSpinBox->value()
        , mUi->iterativeFactorSigmaSpinBox->value()
        , mUi->manualXSpinBox->value()
        , mUi->manualYSpinBox->value()
        , mUi->manualZSpinBox->value()
        , mUi->manualPitchSpinBox->value()
        , mUi->manualYawSpinBox->value()
        , mUi->manualRollSpinBox->value()
        , mUi->zdirXSpinBox->value()
        , mUi->zdirYSpinBox->value()
        , mUi->zdirZSpinBox->value()
        , mUi->autoZCheckBox->isChecked()
        , mUi->autoShiftCheckBox->isChecked()
        , mUi->preShiftSpinBox->value()
        , mUi->guessShiftThresholdSpinBox->value()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
QPushButton* RectifyParametersControlWidget::getPointsMatchingButton () [inline]
Definition at line 33 of file rectifyParametersControlWidget.h.
    {
        return mUi->bPointsMatching;
    }
QPushButton* RectifyParametersControlWidget::getRectifyButton () [inline]
Definition at line 23 of file rectifyParametersControlWidget.h.
    {
        return mUi->rectifyButton;
    }
QPushButton* RectifyParametersControlWidget::getResetButton () [inline]
Definition at line 28 of file rectifyParametersControlWidget.h.
    {
        return mUi->resetButton;
    }
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void RectifyParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 68 of file rectifyParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    RectifyParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void RectifyParametersControlWidget::paramsChanged () [signal]
Referenced by RectifyParametersControlWidget(), and setParameters().
void RectifyParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 76 of file rectifyParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    RectifyParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void RectifyParametersControlWidget::setManualTab (CameraAngles & angle, Vector3dd & dir) [inline]
Definition at line 38 of file rectifyParametersControlWidget.h.
References corecvs::CameraAngles::pitch(), corecvs::CameraAngles::roll(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), corecvs::CameraAngles::yaw(), and corecvs::Vector3d< ElementType >::z().
    {
        mUi->manualPitchSpinBox->setValue(angle.pitch());
        mUi->manualYawSpinBox  ->setValue(angle.yaw());
        mUi->manualRollSpinBox ->setValue(angle.roll());
        mUi->manualXSpinBox->setValue(dir.x());
        mUi->manualYSpinBox->setValue(dir.y());
        mUi->manualZSpinBox->setValue(dir.z());
    }
void RectifyParametersControlWidget::setParameters (const RectifyParameters & input)
Definition at line 134 of file rectifyParametersControlWidget.cpp.
References RectifyParameters::autoShift(), RectifyParameters::autoZ(), RectifyParameters::baselineLength(), RectifyParameters::baselineX(), RectifyParameters::baselineY(), RectifyParameters::baselineZ(), RectifyParameters::computeEssential(), RectifyParameters::estimationMethod(), RectifyParameters::extended(), RectifyParameters::filterMinimumLength(), RectifyParameters::fovAngle(), RectifyParameters::guessShiftThreshold(), RectifyParameters::hessianThreshold(), RectifyParameters::iterativeFactorSigma(), RectifyParameters::iterativeInitialSigma(), RectifyParameters::iterativeIterations(), RectifyParameters::iterativeMethod(), RectifyParameters::manualPitch(), RectifyParameters::manualRoll(), RectifyParameters::manualX(), RectifyParameters::manualY(), RectifyParameters::manualYaw(), RectifyParameters::manualZ(), RectifyParameters::matchingMethod(), mUi, RectifyParameters::normalise(), RectifyParameters::octaveLayers(), RectifyParameters::octaves(), paramsChanged(), RectifyParameters::preShift(), RectifyParameters::priorFocal(), RectifyParameters::priorFocal2(), RectifyParameters::ransacIterations(), RectifyParameters::ransacTestSize(), RectifyParameters::ransacThreshold(), RectifyParameters::useKLT(), RectifyParameters::zdirX(), RectifyParameters::zdirY(), and RectifyParameters::zdirZ().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->matchingMethodComboBox->setCurrentIndex(input.matchingMethod());
    mUi->hessianThresholdSpinBox->setValue(input.hessianThreshold());
    mUi->octavesSpinBox->setValue(input.octaves());
    mUi->octaveLayersSpinBox->setValue(input.octaveLayers());
    mUi->extendedCheckBox->setChecked(input.extended());
    mUi->filterMinimumLengthSpinBox->setValue(input.filterMinimumLength());
    mUi->useKLTCheckBox->setChecked(input.useKLT());
    mUi->computeEssentialCheckBox->setChecked(input.computeEssential());
    mUi->priorFocalSpinBox->setValue(input.priorFocal());
    mUi->priorFocal2SpinBox->setValue(input.priorFocal2());
    mUi->baselineLengthSpinBox->setValue(input.baselineLength());
    mUi->fovAngleSpinBox->setValue(input.fovAngle());
    mUi->estimationMethodComboBox->setCurrentIndex(input.estimationMethod());
    mUi->normaliseCheckBox->setChecked(input.normalise());
    mUi->ransacIterationsSpinBox->setValue(input.ransacIterations());
    mUi->ransacTestSizeSpinBox->setValue(input.ransacTestSize());
    mUi->ransacThresholdSpinBox->setValue(input.ransacThreshold());
    mUi->baselineXSpinBox->setValue(input.baselineX());
    mUi->baselineYSpinBox->setValue(input.baselineY());
    mUi->baselineZSpinBox->setValue(input.baselineZ());
    mUi->iterativeMethodComboBox->setCurrentIndex(input.iterativeMethod());
    mUi->iterativeIterationsSpinBox->setValue(input.iterativeIterations());
    mUi->iterativeInitialSigmaSpinBox->setValue(input.iterativeInitialSigma());
    mUi->iterativeFactorSigmaSpinBox->setValue(input.iterativeFactorSigma());
    mUi->manualXSpinBox->setValue(input.manualX());
    mUi->manualYSpinBox->setValue(input.manualY());
    mUi->manualZSpinBox->setValue(input.manualZ());
    mUi->manualPitchSpinBox->setValue(input.manualPitch());
    mUi->manualYawSpinBox->setValue(input.manualYaw());
    mUi->manualRollSpinBox->setValue(input.manualRoll());
    mUi->zdirXSpinBox->setValue(input.zdirX());
    mUi->zdirYSpinBox->setValue(input.zdirY());
    mUi->zdirZSpinBox->setValue(input.zdirZ());
    mUi->autoZCheckBox->setChecked(input.autoZ());
    mUi->autoShiftCheckBox->setChecked(input.autoShift());
    mUi->preShiftSpinBox->setValue(input.preShift());
    mUi->guessShiftThresholdSpinBox->setValue(input.guessShiftThreshold());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void RectifyParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 179 of file rectifyParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    RectifyParameters *inputCasted = static_cast<RectifyParameters *>(input);
    setParameters(*inputCasted);
}
Member Data Documentation
bool RectifyParametersControlWidget::autoInit [protected]
Definition at line 62 of file rectifyParametersControlWidget.h.
Ui_RectifyParametersControlWidget* RectifyParametersControlWidget::mUi [protected]
Definition at line 61 of file rectifyParametersControlWidget.h.
Referenced by createParameters(), RectifyParametersControlWidget(), setParameters(), and ~RectifyParametersControlWidget().
QString RectifyParametersControlWidget::rootPath [protected]
Definition at line 63 of file rectifyParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/rectifier/rectifyParametersControlWidget.h
utils/rectifier/rectifyParametersControlWidget.cpp