DeepView: corecvs::Vector3d< ElementType > Class Template Reference
corecvs::Vector3d< ElementType > Class Template Reference
#include <vector3d.h>
Public Types
typedef ElementType InnerElementType
typedef ReflectionHelper
< ElementType >::Type ReflectionType
Public Member Functions
Vector3d (const ElementType &_x, const ElementType &_y, const ElementType &_z)
Vector3d (const BaseClass &V)
Vector3d (const ElementType &x)
Vector3d ()
Vector3d (const Vector2d< ElementType > &V, const ElementType &x)
Vector2d< ElementType > xy () const
Vector2d< ElementType > xz () const
Vector2d< ElementType > yz () const
operator Vector2d< ElementType > ()
Do the conversion form projective coordinates to the 2D ones.
Vector3d< ElementType > normalizeProjective ()
Add xy(), yz() and other sub-methods.
bool isInCube (const Vector3d< ElementType > &low, const Vector3d< ElementType > &high) const
template<class VisitorType >
void accept (VisitorType &visitor)
int size () const
ElementType & operator[] (int n)
const ElementType & operator[] (int n) const
ElementType & at (int n)
const ElementType & at (int n) const
Vector3d< ElementType > createVector (int) const
Vector3d< ElementType > * realThis ()
Static cast functions.
const Vector3d< ElementType > * realThis () const
bool operator== (const Vector3d< ElementType > &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const Vector3d< ElementType > &that) const
Inequality operator.
bool notTooFar (const Vector3d< ElementType > &that, const ElementType &epsilon=ElementType(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const Vector3d< ElementType > &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const Vector3d< ElementType > &V)
VectorOperationsBase & operator*= (const ElementType &c)
VectorOperationsBase & operator/= (const ElementType &c)
Vector3d< ElementType > operator- () const
Negative operator.
ElementType sumAllElements () const
Sum of the elements of the vector.
ElementType mulAllElements () const
Product of all elements of the vector.
ElementType sumAllElementsSq () const
Sum of the squares of element of the vector.
ElementType l2Metric () const
Euclidean distance.
ElementType operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
Vector3d< ElementType > normalised () const
Return a normalized copy of vector.
Vector3d< ElementType > cloneVector () const
Return copy of vector.
ElementType l1Metric () const
Sum of the absolute values of element of the vector.
ElementType lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
ElementType minimum () const
ElementType maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
ElementType & x ()
Helper functions to access elements.
ElementType & y ()
ElementType & z ()
const ElementType & x () const
Constant versions of helper functions for read-only form constant vectors.
const ElementType & y () const
const ElementType & z () const
Public Attributes
ElementType element [length]
Static Public Attributes
static const int LENGTH
Protected Types
typedef FixedVectorBase
< Vector3d< ElementType >
, ElementType, 3 > BaseClass
Friends
Vector3d operator^ (const Vector3d &V, const Vector3d &U)
This function implements the vector cross product (See http://en.wikipedia.org/wiki/Vector_product).
Vector3d< ElementType > operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
Vector3d< ElementType > operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
Vector3d< ElementType > operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
Vector3d< ElementType > operator* (const ElementType &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
Vector3d< ElementType > operator* (const VectorOperationsBase &V, const ElementType &c)
Vector3d< ElementType > operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
Vector3d< ElementType > operator/ (const VectorOperationsBase &V, const ElementType &c)
Operator * does the component-specific multiplication by constant
.
ElementType operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
template<typename ElementType>
class corecvs::Vector3d< ElementType >
Definition at line 27 of file vector3d.h.
Member Typedef Documentation
template<typename ElementType> typedef FixedVectorBase<Vector3d<ElementType>, ElementType, 3> corecvs::Vector3d< ElementType >::BaseClass [protected]
Reimplemented from corecvs::FixedVectorBase< Vector3d< ElementType >, ElementType, 3 >.
Definition at line 30 of file vector3d.h.
typedef ElementType corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<ElementType>::Type corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::ReflectionType [inherited]
Definition at line 561 of file vectorOperations.h.
Constructor & Destructor Documentation
template<typename ElementType> corecvs::Vector3d< ElementType >::Vector3d (const ElementType & _x, const ElementType & _y, const ElementType & _z) [inline]
Definition at line 33 of file vector3d.h.
    {
        (*this)[0] = _x;
        (*this)[1] = _y;
        (*this)[2] = _z;
    }
template<typename ElementType> corecvs::Vector3d< ElementType >::Vector3d (const BaseClass & V) [inline]
Definition at line 40 of file vector3d.h.
: BaseClass(V) {}
template<typename ElementType> corecvs::Vector3d< ElementType >::Vector3d (const ElementType & x) [inline, explicit]
Definition at line 41 of file vector3d.h.
: BaseClass((ElementType)x) {}
template<typename ElementType> corecvs::Vector3d< ElementType >::Vector3d () [inline]
Definition at line 42 of file vector3d.h.
: BaseClass() {}
template<typename ElementType> corecvs::Vector3d< ElementType >::Vector3d (const Vector2d< ElementType > & V, const ElementType & x) [inline]
Definition at line 44 of file vector3d.h.
                                                                          :
        BaseClass(V,x)
    {}
Member Function Documentation
template<typename ElementType> template<class VisitorType > void corecvs::Vector3d< ElementType >::accept (VisitorType & visitor) [inline]
Reimplemented from corecvs::VectorOperationsBase< Vector3d< ElementType >, ElementType >.
Definition at line 174 of file vector3d.h.
    {
        visitor.visit(x(), ElementType(0), "x");
        visitor.visit(y(), ElementType(0), "y");
        visitor.visit(z(), ElementType(0), "z");
    }
void corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
Vector3d< ElementType > corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
Vector3d< ElementType > corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
template<typename ElementType> bool corecvs::Vector3d< ElementType >::isInCube (const Vector3d< ElementType > & low, const Vector3d< ElementType > & high) const [inline]
Definition at line 162 of file vector3d.h.
Referenced by corecvs::AxisAlignedBox3d::contains(), and PLYLoader::loadPLY().
    {
        return this->isInHypercube(low, high);
    }
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::isInHypercube (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & low, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
Referenced by corecvs::Vector3d< double >::isInCube().
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
void corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Reimplemented in corecvs::Line2d.
Definition at line 407 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
Vector3d< ElementType > corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Reimplemented in corecvs::Line2d.
Definition at line 420 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
template<typename ElementType> Vector3d<ElementType> corecvs::Vector3d< ElementType >::normalizeProjective () [inline]
Add xy(), yz() and other sub-methods.
Definition at line 152 of file vector3d.h.
Referenced by corecvs::StereoAligner::getBestZ().
    {
        if (this->z() == 0.0)
        {
            return Vector3d<ElementType>(0.0);
        }
        return Vector3d<ElementType>(this->x() / this->z(), this->y() / this->z(), ElementType(1.0));
    }
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::notTooFar (const Vector3d< ElementType > & that, const ElementType & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
template<typename ElementType> corecvs::Vector3d< ElementType >::operator Vector2d< ElementType > () [inline]
Do the conversion form projective coordinates to the 2D ones.
TODO: Should not do this as an automatic conversion
Definition at line 136 of file vector3d.h.
References corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
    {
        if (this->z() == 0.0)
        {
            return Vector2d<ElementType>(0.0,0.0);
        }
        return Vector2d<ElementType>(this->x() / this->z(), this->y() / this->z());
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator!= (const Vector3d< ElementType > & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator*= (const ElementType & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator+= (const Vector3d< ElementType > & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
Vector3d< ElementType > corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator-= (const Vector3d< ElementType > & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator/= (const ElementType & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
Referenced by corecvs::Line2d::normalise().
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::operator== (const Vector3d< ElementType > & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
    {
        return element[n];
    }
void corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
Vector3d< ElementType > * corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const Vector3d< ElementType > * corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
int corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< Vector3d< ElementType > , ElementType >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
template<typename ElementType> ElementType& corecvs::Vector3d< ElementType >::x () [inline]
Helper functions to access elements.
Definition at line 52 of file vector3d.h.
Referenced by corecvs::DirectRemapper::_init(), corecvs::AxisAlignedBox3d::_initByLowHigh(), corecvs::Vector3d< double >::accept(), corecvs::Mesh3D::addAOB(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::Matrix33::CrossProductLeft(), OpenGLTools::drawDiamond(), OpenGLTools::drawWiredBox(), Scene3DMouse::dumpPCD(), Scene3DMouse::dumpPLY(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::SpatialGradient::findCornerPoints(), corecvs::Matrix33::FromColumns(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::AxisAlignedBox3d::getPoints(), corecvs::EssentialDecomposition::getScaler(), OpenGLTools::glTranslateVector3dd(), OpenGLTools::glVertexVector3dd(), corecvs::Line2d::intersectWith(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), PLYLoader::loadPLY(), corecvs::Matrix33::Matrix33(), corecvs::Matrix44::Matrix44(), corecvs::Vector3d< double >::normalizeProjective(), corecvs::Vector3d< ElementType >::operator Vector2d< ElementType >(), corecvs::SortSwarmPointX::operator()(), corecvs::operator*(), corecvs::EssentialEstimator::CostFunctionBase::packState(), DistortionWidget::printVectorPair(), UniversalRectifier::recalculate(), CloudViewDialog::resetCamera(), corecvs::Rotate(), RectifyParametersControlWidget::setManualTab(), corecvs::Matrix44::Shift(), corecvs::Matrix33::VectorByVector(), corecvs::AxisAlignedBox3d::width(), corecvs::Vector3d< double >::xy(), and corecvs::Vector3d< double >::xz().
    {
        return (*this)[0];
    }
template<typename ElementType> const ElementType& corecvs::Vector3d< ElementType >::x () const [inline]
Constant versions of helper functions for read-only form constant vectors.
Definition at line 72 of file vector3d.h.
    {
        return (*this)[0];
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector3d< ElementType >::xy () const [inline]
Definition at line 88 of file vector3d.h.
    {
        return Vector2d<ElementType>(x(), y());
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector3d< ElementType >::xz () const [inline]
Definition at line 93 of file vector3d.h.
    {
        return Vector2d<ElementType>(x(), z());
    }
template<typename ElementType> ElementType& corecvs::Vector3d< ElementType >::y () [inline]
Definition at line 57 of file vector3d.h.
Referenced by corecvs::DirectRemapper::_init(), corecvs::AxisAlignedBox3d::_initByLowHigh(), corecvs::Vector3d< double >::accept(), corecvs::Mesh3D::addAOB(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::Matrix33::CrossProductLeft(), OpenGLTools::drawDiamond(), Scene3DMouse::drawMyself(), OpenGLTools::drawWiredBox(), Scene3DMouse::dumpPCD(), Scene3DMouse::dumpPLY(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::SpatialGradient::findCornerPoints(), corecvs::Matrix33::FromColumns(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::AxisAlignedBox3d::getPoints(), corecvs::EssentialDecomposition::getScaler(), OpenGLTools::glTranslateVector3dd(), corecvs::AxisAlignedBox3d::height(), corecvs::Line2d::intersectWith(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), PLYLoader::loadPLY(), corecvs::Matrix33::Matrix33(), corecvs::Matrix44::Matrix44(), corecvs::Vector3d< double >::normalizeProjective(), corecvs::Vector3d< ElementType >::operator Vector2d< ElementType >(), corecvs::SortSwarmPointY::operator()(), corecvs::operator*(), corecvs::EssentialEstimator::CostFunctionBase::packState(), DistortionWidget::printVectorPair(), CloudViewDialog::resetCamera(), corecvs::Rotate(), RectifyParametersControlWidget::setManualTab(), corecvs::Matrix44::Shift(), corecvs::Matrix33::VectorByVector(), corecvs::Vector3d< double >::xy(), and corecvs::Vector3d< double >::yz().
    {
        return (*this)[1];
    }
template<typename ElementType> const ElementType& corecvs::Vector3d< ElementType >::y () const [inline]
Definition at line 77 of file vector3d.h.
    {
        return (*this)[1];
    }
template<typename ElementType> Vector2d<ElementType> corecvs::Vector3d< ElementType >::yz () const [inline]
Definition at line 98 of file vector3d.h.
    {
        return Vector2d<ElementType>(y(), z());
    }
template<typename ElementType> ElementType& corecvs::Vector3d< ElementType >::z () [inline]
Definition at line 62 of file vector3d.h.
Referenced by corecvs::DirectRemapper::_init(), corecvs::AxisAlignedBox3d::_initByLowHigh(), corecvs::Vector3d< double >::accept(), corecvs::Mesh3D::addAOB(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::Matrix33::CrossProductLeft(), corecvs::AxisAlignedBox3d::depth(), OpenGLTools::drawDiamond(), Scene3DMouse::drawMyself(), OpenGLTools::drawWiredBox(), Scene3DMouse::dumpPCD(), Scene3DMouse::dumpPLY(), corecvs::VoxelBufferBase< RealType, ElementType >::element(), corecvs::SpatialGradient::findCornerPoints(), corecvs::Matrix33::FromColumns(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::AxisAlignedBox3d::getPoints(), corecvs::EssentialDecomposition::getScaler(), OpenGLTools::glTranslateVector3dd(), corecvs::Line2d::intersectWith(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), PLYLoader::loadPLY(), corecvs::Matrix33::Matrix33(), corecvs::Matrix44::Matrix44(), corecvs::Vector3d< double >::normalizeProjective(), corecvs::Vector3d< ElementType >::operator Vector2d< ElementType >(), corecvs::SortSwarmPointZ::operator()(), corecvs::operator*(), corecvs::EssentialEstimator::CostFunctionBase::packState(), DistortionWidget::printVectorPair(), UniversalRectifier::recalculate(), CloudViewDialog::resetCamera(), corecvs::Rotate(), RectifyParametersControlWidget::setManualTab(), corecvs::Matrix44::Shift(), corecvs::FlowSimuator::simulateFlow(), corecvs::Matrix33::VectorByVector(), corecvs::Vector3d< double >::xz(), and corecvs::Vector3d< double >::yz().
    {
        return (*this)[2];
    }
template<typename ElementType> const ElementType& corecvs::Vector3d< ElementType >::z () const [inline]
Definition at line 82 of file vector3d.h.
    {
        return (*this)[2];
    }
Friends And Related Function Documentation
ElementType operator& (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
Vector3d< ElementType > operator* (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
Vector3d< ElementType > operator* (const ElementType & c, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
Vector3d< ElementType > operator* (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
Vector3d< ElementType > operator+ (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
Vector3d< ElementType > operator- (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
Vector3d< ElementType > operator/ (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V1, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
Vector3d< ElementType > operator/ (const VectorOperationsBase< Vector3d< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< Vector3d< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, VectorOperationsBase< Vector3d< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
template<typename ElementType> Vector3d operator^ (const Vector3d< ElementType > & V, const Vector3d< ElementType > & U) [friend]
This function implements the vector cross product (See http://en.wikipedia.org/wiki/Vector_product).
It is computed as follows:
Parameters:
[in] V the first vector
[in] U the second vector
Returns:
vector
Definition at line 121 of file vector3d.h.
    {
        ElementType x, y, z;
        x = V.y() * U.z() - U.y() * V.z();
        y = U.x() * V.z() - U.z() * V.x();
        z = U.y() * V.x() - U.x() * V.y();
        return Vector3d(x, y, z);
    }
Member Data Documentation
ElementType corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
Referenced by corecvs::Line2d::last(), and corecvs::Line2d::normal().
const int corecvs::FixedVectorBase< Vector3d< ElementType > , ElementType, length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
The documentation for this class was generated from the following file:
core/math/vector/vector3d.h