DeepView: GainOffset Class Reference
GainOffset Class Reference
#include <gainoffset.h>
Classes
struct GainParameters_TAG
Public Slots
void updateOffsetSlider (double value)
void updateOffsetText (int val)
void updateGainSlider (double value)
void updateGainText (int val)
Signals
void parametersChanged (void)
Public Member Functions
GainOffset (QWidget *parent=0)
~GainOffset ()
virtual G12Buffer * filter (G12Buffer *input)
virtual QString getInstanceName ()
Static Public Member Functions
static QString getName ()
Private Types
typedef struct
GainOffset::GainParameters_TAG GainParameters
Private Attributes
Ui_GainOffsetClass ui
GainParameters gParams
Static Private Attributes
static QString name = QString("Gain&Offset")
Detailed Description
Definition at line 10 of file gainoffset.h.
Member Typedef Documentation
typedef struct GainOffset::GainParameters_TAG GainOffset::GainParameters [private]
Constructor & Destructor Documentation
GainOffset::GainOffset (QWidget * parent = 0)
Definition at line 15 of file gainoffset.cpp.
References GainOffset::GainParameters_TAG::gain, gParams, GainOffset::GainParameters_TAG::offset, ui, updateGainSlider(), updateGainText(), updateOffsetSlider(), and updateOffsetText().
    : BaseFilter(parent)
{
    ui.setupUi(this);
    gParams.offset = 0;
    ui.offsetEdit->setValue(gParams.offset);
    ui.offsetEdit  ->setMaximum( G12Buffer::BUFFER_MAX_VALUE);
    ui.offsetEdit  ->setMinimum(-G12Buffer::BUFFER_MAX_VALUE);
    ui.offsetSlider->setMaximum( G12Buffer::BUFFER_MAX_VALUE);
    ui.offsetSlider->setMinimum(-G12Buffer::BUFFER_MAX_VALUE);
    ui.offsetSlider->setValue(gParams.offset);
    connect(ui.offsetEdit, SIGNAL(valueChanged(double)), this, SLOT(updateOffsetSlider(double)));
    connect(ui.offsetSlider, SIGNAL(valueChanged(int)), this, SLOT(updateOffsetText(int)));
    gParams.gain = 1;
    ui.gainEdit->setValue(gParams.gain);
    ui.gainSlider->setMaximum(100);
    ui.gainSlider->setMinimum(-100);
    ui.gainSlider->setValue(0);
    connect(ui.gainEdit, SIGNAL(valueChanged(double)), this, SLOT(updateGainSlider(double)));
    connect(ui.gainSlider, SIGNAL(valueChanged(int)), this, SLOT(updateGainText(int)));
}
GainOffset::~GainOffset ()
Definition at line 99 of file gainoffset.cpp.
{
}
Member Function Documentation
G12Buffer * GainOffset::filter (G12Buffer * input) [virtual]
Reimplemented from BaseFilter.
Definition at line 42 of file gainoffset.cpp.
References GainOffset::GainParameters_TAG::gain, gParams, corecvs::AbstractBuffer< ElementType, IndexType >::mapOperationElementwize(), and GainOffset::GainParameters_TAG::offset.
{
    G12Buffer *toReturn = new G12Buffer(input);
    GainOffsetMapper gom(gParams.gain, gParams.offset);
    toReturn->mapOperationElementwize<GainOffsetMapper>(gom);
    return toReturn;
}
virtual QString GainOffset::getInstanceName () [inline, virtual]
Reimplemented from BaseFilter.
Definition at line 43 of file gainoffset.h.
     {
         return name;
     };
static QString GainOffset::getName () [inline, static]
Reimplemented from BaseFilter.
Definition at line 38 of file gainoffset.h.
Referenced by FilterFabric::createFilterInstance(), and FilterFabric::getFilterNames().
     {
         return name;
     };
void BaseFilter::parametersChanged (void) [signal, inherited]
Referenced by BitSelector::maskChanged(), BitSelector::shiftChanged(), updateGainSlider(), updateGainText(), ScaleFilter::updateHeight(), updateOffsetSlider(), updateOffsetText(), ScaleFilter::updateWidth(), ScaleFilter::updateXScale(), ScaleFilter::updateXShift(), ScaleFilter::updateYScale(), and ScaleFilter::updateYShift().
void GainOffset::updateGainSlider (double value) [slot]
Definition at line 72 of file gainoffset.cpp.
References GainOffset::GainParameters_TAG::gain, gParams, BaseFilter::parametersChanged(), and ui.
Referenced by GainOffset().
{
    double loge = log(value);
    double log1_05 = log(1.05);
    value = loge / log1_05;
    bool blocked = ui.gainSlider->blockSignals(true);
    ui.gainSlider->setValue(value);
    ui.gainSlider->blockSignals(blocked);
    gParams.gain = value;
    emit parametersChanged();
//    notifyRecalculate();
}
void GainOffset::updateGainText (int val) [slot]
Definition at line 87 of file gainoffset.cpp.
References GainOffset::GainParameters_TAG::gain, gParams, BaseFilter::parametersChanged(), and ui.
Referenced by GainOffset().
{
    double value = pow(1.05, val);
    bool blocked = ui.gainEdit->blockSignals(true);
    ui.gainEdit->setValue(value);
    ui.gainEdit->blockSignals(blocked);
    gParams.gain = value;
    emit parametersChanged();
//    notifyRecalculate();
}
void GainOffset::updateOffsetSlider (double value) [slot]
Definition at line 51 of file gainoffset.cpp.
References gParams, GainOffset::GainParameters_TAG::offset, BaseFilter::parametersChanged(), and ui.
Referenced by GainOffset().
{
    bool blocked = ui.offsetSlider->blockSignals(true);
    ui.offsetSlider->setValue(value);
    ui.offsetSlider->blockSignals(blocked);
    gParams.offset = value;
    emit parametersChanged();
    //notifyRecalculate();
}
void GainOffset::updateOffsetText (int val) [slot]
Definition at line 61 of file gainoffset.cpp.
References gParams, GainOffset::GainParameters_TAG::offset, BaseFilter::parametersChanged(), and ui.
Referenced by GainOffset().
{
    bool blocked = ui.offsetEdit->blockSignals(true);
    ui.offsetEdit->setValue(val);
    ui.offsetEdit->blockSignals(blocked);
    gParams.offset = val;
    emit parametersChanged();
    //notifyRecalculate();
}
Member Data Documentation
GainParameters GainOffset::gParams [private]
Definition at line 50 of file gainoffset.h.
Referenced by filter(), GainOffset(), updateGainSlider(), updateGainText(), updateOffsetSlider(), and updateOffsetText().
QString GainOffset::name = QString("Gain&Offset") [static, private]
Definition at line 22 of file gainoffset.h.
Ui_GainOffsetClass GainOffset::ui [private]
Reimplemented from BaseFilter.
Definition at line 46 of file gainoffset.h.
Referenced by GainOffset(), updateGainSlider(), updateGainText(), updateOffsetSlider(), and updateOffsetText().
The documentation for this class was generated from the following files:
utils/filters/legacy/gainoffset.h
utils/filters/legacy/gainoffset.cpp