DeepView: corecvs::GradientDescent Class Reference
corecvs::GradientDescent Class Reference
#include <gradientDescent.h>
Public Member Functions
GradientDescent (int _maxIterations=25, double _lambda=0.1)
vector< double > minimise (const vector< double > &input)
vector< double > fit (const vector< double > &input, const vector< double > &output)
Public Attributes
FunctionArgs * f
FunctionArgs * normalisation
double lambda
int maxIterations
double minGradient
Detailed Description
Definition at line 18 of file gradientDescent.h.
Constructor & Destructor Documentation
corecvs::GradientDescent::GradientDescent (int _maxIterations = 25, double _lambda = 0.1) [inline]
Definition at line 27 of file gradientDescent.h.
                                                                   :
        f(NULL),
        normalisation(NULL),
        lambda(_lambda),
        maxIterations(_maxIterations),
        minGradient(std::numeric_limits<double>::min())
        {};
Member Function Documentation
vector< double > corecvs::GradientDescent::fit (const vector< double > & input, const vector< double > & output)
Definition at line 77 of file gradientDescent.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, ASSERT_TRUE_P, f, corecvs::FunctionArgs::getJacobian(), corecvs::FunctionArgs::inputs, lambda, maxIterations, normalisation, corecvs::FunctionArgs::outputs, and corecvs::FixedArrayBase< RealType, ElementType >::size().
{
    cout << "================== Starting Gradient fit ================== " << endl;
    Vector beta(input);
    ASSERT_TRUE  ( f != NULL, "Function is NULL");
    ASSERT_TRUE  ( f->outputs == 1, "Function should map to 1 dimentional space");
    ASSERT_TRUE_P( beta.size() == f->inputs, ("input guess has wrong dimension %d instead of %d\n", beta.size(), f->inputs));
    ASSERT_TRUE_P( (int)output.size() == f->outputs, ("output has wrong dimension %d instead of %d\n", (int)output.size(), f->outputs));
    for (int g = 0; g < maxIterations; g++)
    {
        Matrix J = f->getJacobian(&(beta[0]));
#ifdef TRACE
        cout << "Current Value:" << endl << beta << endl;
        cout << "Current Gradient:" << endl << J << endl;
#endif
        Vector y(1);
        f->operator ()(beta, y);
        double difference = y[0] - output[0];
#ifdef TRACE
        cout << "Difference:" << difference << endl;
#endif
        for (int i = 0; i < beta.size(); i++)
        {
            beta[i] -= lambda * J.a(0, i) * (difference);
        }
        if (normalisation != NULL)
        {
            Vector normBeta(beta.size());
            normalisation->operator()(beta, normBeta);
            beta = normBeta;
        }
    }
    vector<double> result;
    result.reserve(f->inputs);
    for (int i = 0; i < f->inputs; i++)
        result.push_back(beta[i]);
    return result;
}
vector< double > corecvs::GradientDescent::minimise (const vector< double > & input)
Definition at line 15 of file gradientDescent.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, ASSERT_TRUE_P, f, corecvs::FunctionArgs::getJacobian(), corecvs::FunctionArgs::inputs, lambda, maxIterations, minGradient, normalisation, corecvs::FunctionArgs::outputs, and corecvs::FixedArrayBase< RealType, ElementType >::size().
Referenced by corecvs::EssentialEstimator::getEssentialGrad().
{
    cout << "================== Starting DG minimize ================== " << endl;
    cout << "Lambda is: "<< lambda << endl;
    cout << "[" << flush;
    Vector beta(input);
    ASSERT_TRUE  ( f != NULL, "Function is NULL");
    ASSERT_TRUE  ( f->outputs == 1, "Function should map to 1 dimentional space");
    ASSERT_TRUE_P( beta.size() == f->inputs, ("input guess has wrong dimension %d instead of %d\n", beta.size(), f->inputs));
    for (int g = 0; g < maxIterations; g++)
    {
        if ((g % ((maxIterations / 100) + 1) == 0))
        {
//            double d;
            cout << "#" << flush;
//            f->operator ()(&(beta[0]), &d);
//            streamsize wasPrecision = cout.precision(10);
//            cout << d << endl;
//            cout.precision(wasPrecision);
        }
//        cout << "Current Value:" << endl << beta << endl;
        Matrix J = f->getJacobian(&(beta[0]));
//        cout << "Current Gradient:" << endl << J << endl;
        double addition = 0.0;
        double gradNorm = 0.0;
        for (int i = 0; i < beta.size(); i++)
        {
            double gradx = J.a(0, i);
            double delta = lambda * gradx;
            gradNorm += gradx * gradx;
            addition += fabs(delta);
            beta[i] -= delta;
        }
        if (normalisation != NULL)
        {
            Vector normBeta(beta.size());
            normalisation->operator()(beta, normBeta);
            beta = normBeta;
        }
        if (addition == 0.0 ||  gradNorm < minGradient)
        {
            cout << "Algorithm reached saddle point or converged" << endl;
            break;
        }
    }
    vector<double> result;
    result.reserve(f->inputs);
    for (int i = 0; i < f->inputs; i++)
        result.push_back(beta[i]);
    cout << "]" << endl;
    return result;
}
Member Data Documentation
FunctionArgs* corecvs::GradientDescent::f
Definition at line 21 of file gradientDescent.h.
Referenced by fit(), corecvs::EssentialEstimator::getEssentialGrad(), and minimise().
double corecvs::GradientDescent::lambda
Definition at line 23 of file gradientDescent.h.
Referenced by fit(), corecvs::EssentialEstimator::getEssentialGrad(), and minimise().
int corecvs::GradientDescent::maxIterations
Definition at line 24 of file gradientDescent.h.
Referenced by fit(), corecvs::EssentialEstimator::getEssentialGrad(), and minimise().
double corecvs::GradientDescent::minGradient
Definition at line 25 of file gradientDescent.h.
Referenced by minimise().
FunctionArgs* corecvs::GradientDescent::normalisation
Definition at line 22 of file gradientDescent.h.
Referenced by fit(), corecvs::EssentialEstimator::getEssentialGrad(), and minimise().
The documentation for this class was generated from the following files:
core/math/gradientDescent.h
core/math/gradientDescent.cpp