DeepView: corecvs::FilterExecuter Class Reference
corecvs::FilterExecuter Class Reference
#include <filterExecuter.h>
Public Member Functions
FilterExecuter (const FilterSelectorParameters &params)
FilterExecuter ()
virtual bool setParameters (const void *newParameters)
virtual G12Buffer * filter (G12Buffer *input)
void clear ()
virtual ~FilterExecuter ()
Public Attributes
vector< AbstractFilter * > mFilters
Private Member Functions
virtual const char * getInstanceName ()
Static Private Member Functions
static const char * getName ()
Detailed Description
Definition at line 17 of file filterExecuter.h.
Constructor & Destructor Documentation
corecvs::FilterExecuter::FilterExecuter (const FilterSelectorParameters & params)
Definition at line 14 of file filterExecuter.cpp.
References setParameters().
{
    setParameters(&params);
}
corecvs::FilterExecuter::FilterExecuter ()
Definition at line 19 of file filterExecuter.cpp.
{}
corecvs::FilterExecuter::~FilterExecuter () [virtual]
Definition at line 70 of file filterExecuter.cpp.
References clear().
{
    clear();
}
Member Function Documentation
void corecvs::FilterExecuter::clear ()
Definition at line 58 of file filterExecuter.cpp.
References mFilters.
Referenced by setParameters(), and ~FilterExecuter().
{
    vector<AbstractFilter *>::iterator filterIterator;
    for (filterIterator = mFilters.begin(); filterIterator != mFilters.end(); ++filterIterator)
    {
        delete (*filterIterator);
        *filterIterator = NULL;
    }
    mFilters.clear();
}
G12Buffer * corecvs::FilterExecuter::filter (G12Buffer * input) [virtual]
Implements corecvs::AbstractFilter.
Definition at line 37 of file filterExecuter.cpp.
References corecvs::AbstractFilter::getName(), mFilters, and corecvs::G12Buffer::verify().
Referenced by setParameters(), and BaseCalculationThread::transformInputFrames().
{
    qDebug("FilterExecuter::filter() called");
    G12Buffer *result = input;
    for (unsigned i = 0; i < mFilters.size(); i ++)
    {
        G12Buffer *processed = mFilters[i]->filter(result);
        if (result != input)
        {
            delete result;
        }
        if (!processed->verify())
            cout << "Executer::filter() executed " << mFilters[i]->getName() << " returned invalid result" << endl;
        result = processed;
    }
    return result;
}
virtual const char* corecvs::AbstractFilter::getInstanceName () [inline, virtual, inherited]
Definition at line 28 of file abstractFilter.h.
References corecvs::AbstractFilter::getName().
    {
        return AbstractFilter::getName();
    }
static const char* corecvs::AbstractFilter::getName () [inline, static, inherited]
Definition at line 23 of file abstractFilter.h.
Referenced by filter(), and corecvs::AbstractFilter::getInstanceName().
    {
        return "Base";
    }
bool corecvs::FilterExecuter::setParameters (const void * newParameters) [virtual]
Implements corecvs::AbstractFilter.
Definition at line 22 of file filterExecuter.cpp.
References clear(), FilterSelector::executerFromName(), filter(), FilterSelectorParameters::filters, mFilters, FilterSelectorParameters::parameters, and corecvs::AbstractFilter::setParameters().
Referenced by FilterExecuter().
{
    clear();
    FilterSelectorParameters *params = (FilterSelectorParameters*) newParameters;
    for (unsigned i = 0; i < params->filters.size(); i ++)
    {
        //printf("Adding filter:%s\n", params->filters[i]);
        AbstractFilter *filter = FilterSelector::executerFromName(params->filters[i]);
        filter->setParameters(params->parameters[i]);
        mFilters.push_back(filter);
    }
    return true;
}
Member Data Documentation
vector<AbstractFilter *> corecvs::FilterExecuter::mFilters
Definition at line 23 of file filterExecuter.h.
Referenced by clear(), filter(), and setParameters().
The documentation for this class was generated from the following files:
utils/filters/filterExecuter.h
utils/filters/filterExecuter.cpp