DeepView: PaintImageWidget Class Reference
PaintImageWidget Class Reference
#include <paintImageWidget.h>
Classes
struct Vertex
struct VertexPath
Public Types
typedef Vector2dd * TargetPoint
Public Slots
virtual void toolButtonReleased (QWidget *button)
This could be reimplemented to add additional tools.
virtual void childRepaint (QPaintEvent *event, QWidget *who)
virtual void childMouseMoved (QMouseEvent *)
virtual void childMousePressed (QMouseEvent *)
virtual void childMouseReleased (QMouseEvent *)
void clickToolButton (ToolButtonType type)
void freezeImage ()
void saveImageToFile ()
void startSaveFlow ()
void stopSaveFlow ()
virtual void childWheelEvent (QWheelEvent *)
virtual void childResized (QResizeEvent *)
void zoomIn ()
void zoomOut ()
void zoomReset ()
void zoomChanged ()
void fitToggled ()
void setInfoString (QString info)
bool addSelectionTool (int toolID, QString name, QIcon icon)
bool addLineTool (int toolID, QString name, QIcon icon)
bool addPointTool (int toolID, QString name, QIcon icon)
void changeZoom (double zoom)
void changeCenterPoint (QPoint point)
Signals
void newPointFSelected (int, QPointF)
void existedPointSelected (int, QPointF)
void editPoint (QPointF, QPointF)
void newPolygonPointSelected (int, QPointF)
void toolButtonClicked (ToolButtonType type)
void vectorDataChanged ()
void newAreaSelected (int toolID, QRect area)
void newPointSelected (int toolID, QPoint point)
void newLineSelected (int toolID, QLine line)
void pointToolMoved (int toolID, QPoint point)
void notifyZoomChanged (double zoom)
void notifyCenterPointChanged (QPoint point)
void askParentRepaint (QPaintEvent *event, QWidget *who)
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (QResizeEvent *event)
void notifyKeyPressEvent (QKeyEvent *event)
void notifyKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
PaintImageWidget (QWidget *parent=0)
~PaintImageWidget ()
void clear ()
void setCurrentPoint (QPointF const &currentPoint)
QPointF currentPoint ()
void setSelectedPoint (QPointF const &point, bool isSelected)
vector< vector< Vector2dd > > getPaths ()
Vector2dd widgetToImageF (const Vector2dd &p)
Vector2dd imageToWidgetF (const Vector2dd &p)
void addSelection (Vertex &vertex)
void removeSelection (Vertex &vertex)
void deselectAllPoints ()
Vertex * findClosest (const Vector2dd &position)
void deselectAllPath ()
void addVertexToPath (Vertex *vertex, VertexPath *path)
void addSelection (VertexPath &path)
void deleteVertex (Vertex *vertex)
void deleteVertex (const Vector2dd &point)
void deleteVertex (int num)
void addVertex (const Vertex &vertex)
void addVertex (const Vector2dd &point)
void drawPath (QPainter *painter, const PointPath &path)
void setImage (QSharedPointer< QImage > _image)
QWidget * getWidget ()
QFrame * getToolsFrame ()
void setInfoValueLabel (QString &string)
void setSavingRoot (const QString &root)
virtual void paintEvent (QPaintEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void loadParamWidget (WidgetLoader &)
virtual void saveParamWidget (WidgetSaver &)
Public Attributes
QList< Vertex > mPoints
Points.
QList< Vertex * > mSelectedPoints
QList< VertexPath > mPaths
Pathes.
QList< VertexPath * > mSelectedPaths
QToolButton * mSelectButton
QToolButton * mAddPointButton
QToolButton * mDeletePointButton
QSharedPointer< QImage > mImage
Protected Types
enum ToolClass {
NO_TOOL, ZOOM_SELECT_TOOL, PAN_TOOL, INFO_TOOL,
RECT_SELECTION_TOOLS, LINE_SELECTION_TOOLS, POINT_SELECTION_TOOLS, TOOL_CLASS_LAST
}
Protected Member Functions
void drawResized (QPainter &painter)
QToolButton * addToolButton (QString name, QIcon icon, bool checkable=true)
QPointF widgetToImageF (const QPointF &p)
QPointF imageToWidgetF (const QPointF &p)
QPoint widgetToImage (const QPoint &p)
QRect computeInputRect ()
void recomputeRects ()
void saveFlowImage (QImage *image)
void recalculateZoomCenter ()
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Protected Attributes
bool mIsFreezed
QIcon mFreezeIcon
QIcon mContinueIcon
bool mSaveProcStarted
unsigned int mImageNumber
QString mImageSavePath
SaveFlowSettings * mSaveDialog
Ui_advancedImageWidget * mUi
QPoint mZoomCenter
QRect mOutputRect
QRect mInputRect
bool mIsMousePressed
QPoint mSelectionStart
QPoint mSelectionEnd
QImage * mResizeCache
ToolClass mCurrentToolClass
vector< WidgetToolButton > mSelectionButtons
int mCurrentSelectionButton
vector< WidgetToolButton > mPointButtons
int mCurrentPointButton
vector< WidgetToolButton > mLineButtons
int mCurrentLineButton
QSignalMapper mToolMapper
QSize mImageSize
QString mRootPath
Private Types
enum PaintToolClass { SELECT_TOOL = TOOL_CLASS_LAST, ADD_POINT_TOOL, DEL_POINT_TOOL, PAINT_TOOL_CLASS_LAST }
enum ToolButtonType { selectButton, panButton, infoButton, selectZoomButton }
Private Member Functions
void clickOnToolButton (const QWidget *button, const QWidget *targetButton, ToolButtonType type)
Private Attributes
Ui::PaintImageWidget * ui
bool mEventFromOtherWidget
Static Private Attributes
static double SELECTION_RADIUS = 5.0
Detailed Description
Definition at line 12 of file paintImageWidget.h.
Member Typedef Documentation
typedef Vector2dd* PaintImageWidget::TargetPoint
Definition at line 87 of file paintImageWidget.h.
Member Enumeration Documentation
enum PaintImageWidget::PaintToolClass [private]
Enumerator:
SELECT_TOOL
ADD_POINT_TOOL
DEL_POINT_TOOL
PAINT_TOOL_CLASS_LAST
Definition at line 18 of file paintImageWidget.h.
    {
        SELECT_TOOL = TOOL_CLASS_LAST,
        ADD_POINT_TOOL,
        DEL_POINT_TOOL,
        PAINT_TOOL_CLASS_LAST
    };
enum PaintImageWidget::ToolButtonType [private]
Enumerator:
selectButton
panButton
infoButton
selectZoomButton
Definition at line 26 of file paintImageWidget.h.
    {
        selectButton,
        panButton,
        infoButton,
        selectZoomButton
    };
enum AdvancedImageWidget::ToolClass [protected, inherited]
Enumerator:
NO_TOOL
ZOOM_SELECT_TOOL
PAN_TOOL
INFO_TOOL
RECT_SELECTION_TOOLS
LINE_SELECTION_TOOLS
POINT_SELECTION_TOOLS
TOOL_CLASS_LAST
Definition at line 112 of file advancedImageWidget.h.
                   {
        NO_TOOL,
        ZOOM_SELECT_TOOL,
        PAN_TOOL,
        INFO_TOOL,
        RECT_SELECTION_TOOLS,
        LINE_SELECTION_TOOLS,
        POINT_SELECTION_TOOLS,
        TOOL_CLASS_LAST
    };
Constructor & Destructor Documentation
PaintImageWidget::PaintImageWidget (QWidget * parent = 0) [explicit]
Definition at line 8 of file paintImageWidget.cpp.
References AdvancedImageWidget::addToolButton(), mAddPointButton, mDeletePointButton, mSelectButton, and ui.
                                                  :
    AdvancedImageWidget(parent),
    ui(new Ui::PaintImageWidget)
{
    mSelectButton      = addToolButton("Select",            QIcon(":/new/prefix1/select_by_color.png"));
    mAddPointButton    = addToolButton("Add Point To Path", QIcon(":/new/prefix1/vector_add.png"), false);
    mDeletePointButton = addToolButton("Delete Point",      QIcon(":/new/prefix1/vector_delete.png"), false);
    ui->setupUi(this);
}
PaintImageWidget::~PaintImageWidget ()
Definition at line 75 of file paintImageWidget.cpp.
References ui.
{
    delete_safe(ui);
}
Member Function Documentation
bool AdvancedImageWidget::addLineTool (int toolID, QString name, QIcon icon) [slot, inherited]
Definition at line 689 of file advancedImageWidget.cpp.
References AdvancedImageWidget::addToolButton(), and AdvancedImageWidget::mLineButtons.
{
//    qDebug("AdvancedImageWidget::addLineTool(%d, _ , _)", toolID);
    QToolButton *toolButton = addToolButton(name, icon);
    WidgetToolButton toolRef(toolID, toolButton);
    mLineButtons.push_back(toolRef);
    return true;
}
bool AdvancedImageWidget::addPointTool (int toolID, QString name, QIcon icon) [slot, inherited]
Definition at line 699 of file advancedImageWidget.cpp.
References AdvancedImageWidget::addToolButton(), and AdvancedImageWidget::mPointButtons.
Referenced by TestbedMainWindow::TestbedMainWindow().
{
//    qDebug("AdvancedImageWidget::addPointTool(%d, _ , _)", toolID);
    QToolButton *toolButton = addToolButton(name, icon);
    WidgetToolButton toolRef(toolID, toolButton);
    mPointButtons.push_back(toolRef);
    return true;
}
void PaintImageWidget::addSelection (Vertex & vertex) [inline]
Definition at line 93 of file paintImageWidget.h.
References PaintImageWidget::Vertex::isSelected, and mSelectedPoints.
Referenced by childMousePressed().
    {
        mSelectedPoints.append(&vertex);
        vertex.isSelected = true;
    }
void PaintImageWidget::addSelection (VertexPath & path) [inline]
Definition at line 155 of file paintImageWidget.h.
References PaintImageWidget::VertexPath::isSelected, and mSelectedPaths.
    {
        mSelectedPaths.append(&path);
        path.isSelected = true;
    }
bool AdvancedImageWidget::addSelectionTool (int toolID, QString name, QIcon icon) [slot, inherited]
Definition at line 679 of file advancedImageWidget.cpp.
References AdvancedImageWidget::addToolButton(), and AdvancedImageWidget::mSelectionButtons.
{
//    qDebug("AdvancedImageWidget::addSelectionTool(%d, _ , _)", toolID);
    QToolButton *toolButton = addToolButton(name, icon);
    WidgetToolButton toolRef(toolID, toolButton);
    mSelectionButtons.push_back(toolRef);
    return true;
}
QToolButton * AdvancedImageWidget::addToolButton (QString name, QIcon icon, bool checkable = true) [protected, inherited]
Definition at line 657 of file advancedImageWidget.cpp.
References AdvancedImageWidget::getToolsFrame(), and AdvancedImageWidget::mToolMapper.
Referenced by AdvancedImageWidget::addLineTool(), AdvancedImageWidget::addPointTool(), AdvancedImageWidget::addSelectionTool(), and PaintImageWidget().
{
    QFrame* holder = getToolsFrame();
    QToolButton *toolButton = new QToolButton();
    toolButton->setIcon(icon);
    toolButton->setText(name);
    toolButton->setToolTip(name);
    toolButton->setIconSize(QSize(24,24));
    if (checkable)
    {
        toolButton->setAutoExclusive(true);
        toolButton->setCheckable(true);
        toolButton->setAutoRaise(true);
    }
    holder->layout()->addWidget(toolButton);
    connect(toolButton, SIGNAL(released()),&mToolMapper, SLOT(map()));
    mToolMapper.setMapping(toolButton, toolButton);
    //connect(toolButton, SIGNAL(released()), this, SLOT(toolButtonReleased()));
    return toolButton;
}
void PaintImageWidget::addVertex (const Vertex & vertex)
Definition at line 256 of file paintImageWidget.cpp.
References mPoints.
Referenced by addVertex(), and DistortionWidget::loadPoints().
{
    mPoints.append(vertex);
    mPoints.last().ownerPath = NULL;
}
void PaintImageWidget::addVertex (const Vector2dd & point)
Definition at line 262 of file paintImageWidget.cpp.
References addVertex().
{
    addVertex(Vertex(point));
}
void PaintImageWidget::addVertexToPath (Vertex * vertex, VertexPath * path) [inline]
Definition at line 149 of file paintImageWidget.h.
References PaintImageWidget::Vertex::ownerPath, and PaintImageWidget::VertexPath::vertexes.
Referenced by DistortionWidget::loadPoints(), and toolButtonReleased().
    {
        path->vertexes.append(vertex);
        vertex->ownerPath = path;
    }
void ViAreaWidget::askParentRepaint (QPaintEvent * event, QWidget * who) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::paintEvent().
void AdvancedImageWidget::changeCenterPoint (QPoint point) [slot, inherited]
Definition at line 538 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mZoomCenter, AdvancedImageWidget::notifyCenterPointChanged(), and AdvancedImageWidget::recomputeRects().
{
    mZoomCenter = point;
    recomputeRects();
    emit notifyCenterPointChanged(mZoomCenter);
}
void AdvancedImageWidget::changeZoom (double zoom) [slot, inherited]
Definition at line 532 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi, and AdvancedImageWidget::zoomChanged().
{
    mUi->expSpinBox->setValue(zoom);
    zoomChanged();
}
void PaintImageWidget::childMouseMoved (QMouseEvent * event) [virtual, slot]
Reimplemented from AdvancedImageWidget.
Definition at line 210 of file paintImageWidget.cpp.
References currentPoint(), AdvancedImageWidget::mCurrentToolClass, AdvancedImageWidget::mIsMousePressed, mSelectedPoints, AdvancedImageWidget::mSelectionEnd, AdvancedImageWidget::mUi, SELECT_TOOL, Qt2Core::Vector2ddFromQPoint(), and widgetToImageF().
{
    //qDebug() << "Doing the drag";
    switch (mCurrentToolClass)
    {
    case SELECT_TOOL:
    {
        //   qDebug() << "Drag in selected tool";
        if (!mIsMousePressed)
            break;
        Vector2dd dragStart    = widgetToImageF(Qt2Core::Vector2ddFromQPoint(mSelectionEnd));
        Vector2dd currentPoint = widgetToImageF(Qt2Core::Vector2ddFromQPoint(event->pos()));
        Vector2dd shift = (dragStart - currentPoint);
        for (int i = 0; i < mSelectedPoints.size(); i++)
        {
            mSelectedPoints[i]->position -= shift;
        }
        mUi->widget->update();
    }
    default:
        break;
    }
    AdvancedImageWidget::childMouseMoved(event);
}
void PaintImageWidget::childMousePressed (QMouseEvent * event) [virtual, slot]
Reimplemented from AdvancedImageWidget.
Definition at line 169 of file paintImageWidget.cpp.
References addSelection(), deselectAllPath(), deselectAllPoints(), findClosest(), imageToWidgetF(), PaintImageWidget::Vertex::isInPath(), AdvancedImageWidget::mCurrentToolClass, mPoints, AdvancedImageWidget::mUi, PaintImageWidget::Vertex::ownerPath, PaintImageWidget::Vertex::position, SELECT_TOOL, SELECTION_RADIUS, and widgetToImageF().
{
    AdvancedImageWidget::childMousePressed(event);
    if ((PaintImageWidget::PaintToolClass)mCurrentToolClass == SELECT_TOOL)
    {
        Vector2dd releasePoint = Vector2dd(event->x(), event->y());
        bool shiftPressed = event->modifiers().testFlag(Qt::ShiftModifier);
        mUi->widget->update();
        Vector2dd imagePoint = widgetToImageF(releasePoint);
        Vertex *vertex = findClosest(imagePoint);
        if (vertex != NULL)
        {
            double dist = (releasePoint - imageToWidgetF(vertex->position)).l2Metric();
            if (dist < SELECTION_RADIUS)
            {
                if (!shiftPressed)
                {
                    deselectAllPoints();
                    deselectAllPath();
                }
                addSelection(*vertex);
                if (vertex->isInPath())
                {
                    addSelection(*vertex->ownerPath);
                }
                return;
            }
        }
        mPoints.append(Vertex(widgetToImageF(releasePoint)));
        if (!shiftPressed)
        {
            deselectAllPoints();
            deselectAllPath();
        }
        addSelection(mPoints[mPoints.size() - 1]);
    }
}
void PaintImageWidget::childMouseReleased (QMouseEvent * event) [virtual, slot]
Reimplemented from AdvancedImageWidget.
Definition at line 237 of file paintImageWidget.cpp.
{
    AdvancedImageWidget::childMouseReleased(event);
}
void PaintImageWidget::childRepaint (QPaintEvent * event, QWidget * who) [virtual, slot]
Reimplemented from AdvancedImageWidget.
Definition at line 19 of file paintImageWidget.cpp.
References corecvs::RGBColor::b(), drawCircle(), drawLine(), drawSquare(), corecvs::RGBColor::g(), imageToWidgetF(), PaintImageWidget::Vertex::isSelected, PaintImageWidget::VertexPath::isSelected, AdvancedImageWidget::mImage, mPaths, mPoints, PaintImageWidget::Vertex::ownerPath, corecvs::RGBColor::r(), PaintImageWidget::VertexPath::vertexes, and PaintImageWidget::Vertex::weight.
{
    AdvancedImageWidget::childRepaint(event, who);
    if (mImage.isNull())
    {
        return;
    }
    /* Now the points */
    QPainter painter(who);
    for (int i = 0; i < mPoints.size(); i ++)
    {
        Vertex *vertex = &mPoints[i];
        painter.setPen(vertex->isSelected ? Qt::red : Qt::green);
        if (vertex->ownerPath == NULL)
        {
            drawCircle(painter, imageToWidgetF(mPoints[i].position), 5);
        }
        else
        {
            drawSquare(painter, imageToWidgetF(mPoints[i].position), 5);
        }
        if (vertex->weight >= 0.0)
        {
            RGBColor color = RGBColor::rainbow1(vertex->weight);
            painter.setPen(QColor(color.r(), color.g(), color.b()));
            drawCircle(painter, imageToWidgetF(mPoints[i].position), 7);
        }
    }
    for (int i = 0; i < mPaths.size(); i++)
    {
        VertexPath *path = &mPaths[i];
        painter.setPen(path->isSelected ? Qt::yellow : Qt::green);
        for (int i = 1; i < path->vertexes.size(); i++)
        {
            Vector2dd point1 = path->vertexes[i    ]->position;
            Vector2dd point2 = path->vertexes[i - 1]->position;
            drawLine(painter, imageToWidgetF(point1), imageToWidgetF(point2));
        }
    }
}
void AdvancedImageWidget::childResized (QResizeEvent *) [virtual, slot, inherited]
Definition at line 562 of file advancedImageWidget.cpp.
References AdvancedImageWidget::fitToggled().
Referenced by AdvancedImageWidget::AdvancedImageWidget().
{
   fitToggled();
   // printf("Child resize called to %d %d\n", event->size().width(), event->size().height());
}
void AdvancedImageWidget::childWheelEvent (QWheelEvent * event) [virtual, slot, inherited]
Definition at line 339 of file advancedImageWidget.cpp.
References corecvs::fround(), AdvancedImageWidget::mUi, AdvancedImageWidget::mZoomCenter, AdvancedImageWidget::notifyCenterPointChanged(), AdvancedImageWidget::recomputeRects(), AdvancedImageWidget::widgetToImageF(), AdvancedImageWidget::zoomIn(), and AdvancedImageWidget::zoomOut().
Referenced by AdvancedImageWidget::AdvancedImageWidget().
{
   // qDebug("AdvancedImageWidget::childWheelEvent() delta=%d\n", event->delta());
    QPointF scrollWidgetPoint = event->pos();
    QPointF scrollImagePoint = widgetToImageF(scrollWidgetPoint);
    if (event->delta() > 0)
    {
        for (int i = 0; i < event->delta() / 60; i++) {
            zoomIn();
        }
    }
    if (event->delta() < 0)
    {
        for (int i = 0; i < -event->delta() / 60; i++) {
            zoomOut();
        }
    }
    QPointF newScrollImagePoint = widgetToImageF(scrollWidgetPoint);
    QPointF shift = newScrollImagePoint - scrollImagePoint;
    mZoomCenter -= QPoint(fround(shift.x()), fround(shift.y()));
    recomputeRects();
    emit notifyCenterPointChanged(mZoomCenter);
    mUi->widget->update();
}
void PaintImageWidget::clear ()
Definition at line 65 of file paintImageWidget.cpp.
References mPaths, mPoints, mSelectedPaths, and mSelectedPoints.
{
    mSelectedPaths.clear();
    mSelectedPoints.clear();
    mPaths.clear();
    mPoints.clear();
    update();
}
void PaintImageWidget::clickOnToolButton (const QWidget * button, const QWidget * targetButton, ToolButtonType type) [private]
Definition at line 80 of file paintImageWidget.cpp.
References mEventFromOtherWidget, and toolButtonClicked().
Referenced by toolButtonReleased().
{
    if (button == targetButton)
    {
        if (mEventFromOtherWidget)
            mEventFromOtherWidget = false;
        else
            emit toolButtonClicked(buttonType);
    }
}
void PaintImageWidget::clickToolButton (PaintImageWidget::ToolButtonType type) [slot]
Definition at line 242 of file paintImageWidget.cpp.
References infoButton, mEventFromOtherWidget, mSelectButton, AdvancedImageWidget::mUi, panButton, selectButton, and selectZoomButton.
{
    mEventFromOtherWidget = true;
    switch (type)
    {
    case selectButton: mSelectButton->click(); break;
    case panButton: mUi->panButton->click(); break;
    case infoButton: mUi->infoButton->click(); break;
    case selectZoomButton: mUi->selectZoomButton->click(); break;
    default: break;
    }
}
QRect AdvancedImageWidget::computeInputRect () [protected, inherited]
Definition at line 568 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mImage, AdvancedImageWidget::mUi, and AdvancedImageWidget::mZoomCenter.
Referenced by AdvancedImageWidget::recomputeRects().
{
    if (mImage == NULL)
    {
        return QRect();
    }
    double zoomFactor = mUi->expSpinBox->value();
    QSize size = mImage->rect().normalized().size() / zoomFactor;
    if (size.isNull())
    {
        size = QSize(1,1);
    }
    QPoint topLeft = mZoomCenter - QPoint(size.width(), size.height()) / 2.0;
    return QRect (topLeft, size);
}
QPointF PaintImageWidget::currentPoint ()
Definition at line 329 of file paintImageWidget.cpp.
References mSelectedPoints, and Core2Qt::QPointFromVector2dd().
Referenced by childMouseMoved().
{
    if (mSelectedPoints.isEmpty())
    {
        return QPointF();
    }
    return Core2Qt::QPointFromVector2dd(mSelectedPoints.last()->position);
}
void PaintImageWidget::deleteVertex (Vertex * vertex)
Definition at line 267 of file paintImageWidget.cpp.
References mPoints.
Referenced by deleteVertex(), and toolButtonReleased().
{
    for (int i = 0; i < mPoints.size(); i++)
    {
        if (&mPoints[i] == vertex)
        {
            deleteVertex(i);
            return;
        }
    }
}
void PaintImageWidget::deleteVertex (const Vector2dd & point)
Definition at line 279 of file paintImageWidget.cpp.
References deleteVertex(), mPoints, AdvancedImageWidget::mUi, and removeSelection().
{
    QList<Vertex*> toDelete;
    for (int i = 0; i < mPoints.size(); i++)
    {
        if (mPoints[i].position == point)
        {
            toDelete.append(&mPoints[i]);
        }
    }
    foreach (Vertex *vertex, toDelete)
    {
        removeSelection(*vertex);
        deleteVertex(vertex);
    }
    mUi->widget->update();
}
void PaintImageWidget::deleteVertex (int num)
Definition at line 299 of file paintImageWidget.cpp.
References mPaths, mPoints, mSelectedPaths, AdvancedImageWidget::mUi, and PaintImageWidget::VertexPath::vertexes.
{
    VertexPath *ownerPath = mPoints[id].ownerPath;
    do
    {
        if (ownerPath == NULL)
        {
            break;
        }
        ownerPath->vertexes.removeAll(&(mPoints[id]));
        if (!ownerPath->vertexes.isEmpty())
        {
            break;
        }
        mSelectedPaths.removeAll(ownerPath);
        for (int i = 0; i < mPaths.size(); i++)
        {
            if (&mPaths[i] == ownerPath)
            {
                mPaths.removeAt(i);
                break;
            }
        }
    } while (false);
    mPoints.removeAt(id);
    mUi->widget->update();
}
void PaintImageWidget::deselectAllPath () [inline]
Definition at line 140 of file paintImageWidget.h.
References mSelectedPaths.
Referenced by childMousePressed().
    {
        for (int i = 0; i < mSelectedPaths.size(); i++)
        {
            mSelectedPaths[i]->isSelected = false;
        }
        mSelectedPaths.clear();
    }
void PaintImageWidget::deselectAllPoints () [inline]
Definition at line 105 of file paintImageWidget.h.
References mSelectedPoints.
Referenced by childMousePressed().
    {
        for (int i = 0; i < mSelectedPoints.size(); i++)
        {
            mSelectedPoints[i]->isSelected = false;
        }
        mSelectedPoints.clear();
    }
void PaintImageWidget::drawPath (QPainter * painter, const PointPath & path)
void AdvancedImageWidget::drawResized (QPainter & painter) [protected, inherited]
Definition at line 123 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mImage, AdvancedImageWidget::mInputRect, and AdvancedImageWidget::mOutputRect.
Referenced by AdvancedImageWidget::childRepaint(), AdvancedImageWidget::saveImageToFile(), and AdvancedImageWidget::setImage().
{
    if (mImage.isNull())
    {
        painter.drawText(0,0, this->width(), this->height(), Qt::AlignHCenter | Qt::AlignVCenter, QString("NO ACTIVE IMAGE"));
        return;
    }
    // We should keep the trivial transform really trivial
    /*if (mOutputRect == mInputRect) {
        printf("Trivial transform\n");
    } else {
        qDebug() << mOutputRect << " - " << mInputRect << endl;
    }*/
    painter.drawImage(mOutputRect, *mImage, mInputRect);
}
void PaintImageWidget::editPoint (QPointF , QPointF) [signal]
void PaintImageWidget::existedPointSelected (int , QPointF) [signal]
Vertex* PaintImageWidget::findClosest (const Vector2dd & position) [inline]
Definition at line 114 of file paintImageWidget.h.
References mPoints.
Referenced by childMousePressed().
    {
        double minDist = numeric_limits<double>::max();
        Vertex *result =  NULL;
        for (int i = 0; i < mPoints.size(); i++)
        {
            double dist = (position - mPoints[i].position).l2Metric();
            if (dist < minDist)
            {
                minDist = dist;
                result = &mPoints[i];
            }
        }
        return result;
    }
void AdvancedImageWidget::fitToggled () [slot, inherited]
Definition at line 556 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi, and AdvancedImageWidget::recomputeRects().
Referenced by AdvancedImageWidget::childResized().
{
    recomputeRects();
    mUi->widget->update();
}
void AdvancedImageWidget::freezeImage () [slot, inherited]
Definition at line 218 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mContinueIcon, AdvancedImageWidget::mFreezeIcon, AdvancedImageWidget::mIsFreezed, and AdvancedImageWidget::mUi.
{
    mIsFreezed = !mIsFreezed;
    mUi->freezeButton->setIcon( mIsFreezed ? mContinueIcon : mFreezeIcon);
}
vector< vector< Vector2dd > > PaintImageWidget::getPaths ()
Definition at line 350 of file paintImageWidget.cpp.
References mPaths, and PaintImageWidget::VertexPath::vertexes.
Referenced by DistortionWidget::doLinesTransform(), and DistortionWidget::updateScore().
{
    vector<vector<Vector2dd> >straights;
    for (int i = 0; i < mPaths.size(); i++)
    {
        PaintImageWidget::VertexPath *vertexPath = &mPaths[i];
        vector<Vector2dd> path;
        for (int j = 0; j < vertexPath->vertexes.size(); j++)
        {
            path.push_back(vertexPath->vertexes[j]->position);
        }
        straights.push_back(path);
    }
    return straights;
}
QFrame * AdvancedImageWidget::getToolsFrame () [inherited]
Definition at line 652 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi.
Referenced by AdvancedImageWidget::addToolButton().
{
    return mUi->frame;
}
QWidget * AdvancedImageWidget::getWidget () [inherited]
Definition at line 647 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi.
{
    return mUi->widget;
}
Vector2dd PaintImageWidget::imageToWidgetF (const Vector2dd & p)
Definition at line 372 of file paintImageWidget.cpp.
References AdvancedImageWidget::imageToWidgetF(), Core2Qt::QPointFromVector2dd(), and Qt2Core::Vector2ddFromQPointF().
Referenced by childMousePressed(), and childRepaint().
{
    return Qt2Core::Vector2ddFromQPointF(AdvancedImageWidget::imageToWidgetF(Core2Qt::QPointFromVector2dd(p)));
}
QPointF AdvancedImageWidget::imageToWidgetF (const QPointF & p) [protected, inherited]
Definition at line 152 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mInputRect, and AdvancedImageWidget::mOutputRect.
Referenced by imageToWidgetF().
{
    if (mOutputRect.height() == 0 || mInputRect.height() == 0 ||
        mInputRect.height() == 0 || mInputRect.height() == 0)
    {
        return p;
    }
    double hAspect = (double)mInputRect.height() / mOutputRect.height();
    double wAspect = (double)mInputRect.width()  / mOutputRect.width();
    double resultX = (p.x() - mInputRect.x()) / wAspect + mOutputRect.left();
    double resultY = (p.y() - mInputRect.y()) / hAspect + mOutputRect.top();
    return QPointF(resultX, resultY);
}
void ViAreaWidget::keyPressEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 53 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyPressEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyPressEvent(event);
}
void ViAreaWidget::keyReleaseEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 59 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyReleaseEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyReleaseEvent(event);
}
void AdvancedImageWidget::loadFromQSettings (const QString & fileName, QString _root) [protected, virtual, inherited]
Reimplemented from SaveableWidget.
Definition at line 714 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mRootPath, AdvancedImageWidget::mUi, and AdvancedImageWidget::mZoomCenter.
{
    QSettings loader(fileName, QSettings::IniFormat);
    loader.beginGroup(_root + mRootPath);
    mZoomCenter.setX(loader.value("center.x", 0).toInt());
    mZoomCenter.setY(loader.value("center.y", 0).toInt());
    mUi->fitToWindowCheckBox->setChecked(loader.value("fitToWindow", false).toBool());
    mUi->aspectCheckBox     ->setChecked(loader.value("fixAspect", false).toBool());
    mUi->expSpinBox         ->setValue  (loader.value("zoom", 1.0).toDouble());
}
virtual void SaveableWidget::loadParamWidget (WidgetLoader &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 119 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::loadFromQSettings().
{}
void ViAreaWidget::mouseDoubleClickEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 35 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mouseMoveEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 16 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mousePressEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 22 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, ViAreaWidget::notifyParentMouseMove(), and ViAreaWidget::notifyParentMousePress().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
    emit notifyParentMousePress(event);
}
void ViAreaWidget::mouseReleaseEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 41 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseRelease().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseRelease(event);
}
void AdvancedImageWidget::newAreaSelected (int toolID, QRect area) [signal, inherited]
Referenced by AdvancedImageWidget::childMouseReleased().
void AdvancedImageWidget::newLineSelected (int toolID, QLine line) [signal, inherited]
Referenced by AdvancedImageWidget::childMouseReleased().
void PaintImageWidget::newPointFSelected (int , QPointF) [signal]
void AdvancedImageWidget::newPointSelected (int toolID, QPoint point) [signal, inherited]
Referenced by AdvancedImageWidget::childMouseReleased().
void PaintImageWidget::newPolygonPointSelected (int , QPointF) [signal]
void AdvancedImageWidget::notifyCenterPointChanged (QPoint point) [signal, inherited]
Referenced by AdvancedImageWidget::changeCenterPoint(), AdvancedImageWidget::childMouseMoved(), AdvancedImageWidget::childMouseReleased(), AdvancedImageWidget::childWheelEvent(), AdvancedImageWidget::recalculateZoomCenter(), and AdvancedImageWidget::zoomReset().
void ViAreaWidget::notifyKeyPressEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyPressEvent().
void ViAreaWidget::notifyKeyReleaseEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyReleaseEvent().
void ViAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), ViAreaWidget::mouseDoubleClickEvent(), ViAreaWidget::mouseMoveEvent(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::mouseReleaseEvent().
void ViAreaWidget::notifyParentResize (QResizeEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::resizeEvent().
void ViAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::wheelEvent().
void AdvancedImageWidget::notifyZoomChanged (double zoom) [signal, inherited]
Referenced by AdvancedImageWidget::zoomChanged().
void ViAreaWidget::paintEvent (QPaintEvent * event) [virtual, inherited]
Reimplemented in ImageWidget.
Definition at line 10 of file viAreaWidget.cpp.
References ViAreaWidget::askParentRepaint(), and ViAreaWidget::mForwardEvents.
{
    if (!mForwardEvents) return;
    emit askParentRepaint(event, this);
}
void AdvancedImageWidget::pointToolMoved (int toolID, QPoint point) [signal, inherited]
Referenced by AdvancedImageWidget::childMouseMoved().
void AdvancedImageWidget::recalculateZoomCenter () [protected, inherited]
Definition at line 634 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mImage, AdvancedImageWidget::mZoomCenter, and AdvancedImageWidget::notifyCenterPointChanged().
Referenced by AdvancedImageWidget::setImage().
{
    if (mImage.isNull())
    {
        mZoomCenter = QPoint(0,0);
    }
    else
    {
        mZoomCenter = QPoint(mImage->size().width(), mImage->size().height()) / 2.0;
    }
    emit notifyCenterPointChanged(mZoomCenter);
}
void AdvancedImageWidget::recomputeRects () [protected, inherited]
Definition at line 586 of file advancedImageWidget.cpp.
References AdvancedImageWidget::computeInputRect(), AdvancedImageWidget::mImage, AdvancedImageWidget::mInputRect, AdvancedImageWidget::mOutputRect, AdvancedImageWidget::mResizeCache, and AdvancedImageWidget::mUi.
Referenced by AdvancedImageWidget::changeCenterPoint(), AdvancedImageWidget::childMouseMoved(), AdvancedImageWidget::childWheelEvent(), AdvancedImageWidget::fitToggled(), AdvancedImageWidget::setImage(), AdvancedImageWidget::zoomChanged(), and AdvancedImageWidget::zoomReset().
{
    if (mImage == NULL)
    {
       return;
    }
    QRect output(mImage->rect().normalized());
    QRect input = computeInputRect();
    if (mUi->fitToWindowCheckBox->isChecked())
    {
        output = mUi->widget->rect().normalized();
        if (mUi->aspectCheckBox->isChecked())
        {
            double inputAspect = (double)input.height() / input.width();
            int outH = output.width() * inputAspect;
            if (outH > output.height())
                output.setWidth(output.height() / inputAspect);
            else
                output.setHeight(output.width() * inputAspect);
        }
    }
    if (!output.isValid())
        output = QRect(0,0,1,1);
    mOutputRect = output;
    mInputRect  = input;
    delete_safe(mResizeCache);
}
void PaintImageWidget::removeSelection (Vertex & vertex) [inline]
Definition at line 99 of file paintImageWidget.h.
References PaintImageWidget::Vertex::isSelected, and mSelectedPoints.
Referenced by deleteVertex().
    {
        mSelectedPoints.removeOne(&vertex);
        vertex.isSelected = false;
    }
void ViAreaWidget::resizeEvent (QResizeEvent * event) [virtual, inherited]
Definition at line 29 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentResize().
{
    if (!mForwardEvents) return;
    emit notifyParentResize(event);
}
void AdvancedImageWidget::saveFlowImage (QImage * image) [protected, inherited]
Definition at line 620 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mImageNumber, AdvancedImageWidget::mImageSavePath, AdvancedImageWidget::mSaveProcStarted, and AdvancedImageWidget::mUi.
Referenced by AdvancedImageWidget::setImage().
{
    if(mSaveProcStarted && image)
    {
        unsigned int pathLength = mImageSavePath.size() + 10;
        char *currentPath = new char[pathLength];
        snprintf(currentPath, pathLength, mImageSavePath.toStdString().c_str(), mImageNumber);
        image->save(currentPath);
        mImageNumber++;
        mUi->fileValuelabel->setText(currentPath);
        delete []currentPath;
    }
}
void AdvancedImageWidget::saveImageToFile () [slot, inherited]
Definition at line 287 of file advancedImageWidget.cpp.
References AdvancedImageWidget::drawResized(), AdvancedImageWidget::mImage, AdvancedImageWidget::mOutputRect, and AdvancedImageWidget::mResizeCache.
{
    QString filename = QFileDialog::getSaveFileName(
            this,
            tr("Save Image"),
            "./Image.bmp",
            tr("Image Files (*.png *.jpg *.bmp)"));
    if(mImage == NULL)
    {
        return;
    }
    if (mResizeCache == NULL)
    {
        mResizeCache = new QImage(mOutputRect.size(), QImage::Format_RGB32);
        QPainter painter(mResizeCache);
        drawResized(painter);
        painter.end();
    }
    mResizeCache->save(filename);
}
virtual void SaveableWidget::saveParamWidget (WidgetSaver &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 120 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::saveToQSettings().
{}
void AdvancedImageWidget::saveToQSettings (const QString & fileName, QString _root) [protected, virtual, inherited]
Reimplemented from SaveableWidget.
Definition at line 726 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mRootPath, AdvancedImageWidget::mUi, and AdvancedImageWidget::mZoomCenter.
{
    QSettings saver(fileName, QSettings::IniFormat);
    saver.beginGroup(_root + mRootPath);
    saver.setValue("fitToWindow", mUi->fitToWindowCheckBox->isChecked());
    saver.setValue("fixAspect"  , mUi->aspectCheckBox->isChecked());
    saver.setValue("zoom", mUi->expSpinBox->value());
    saver.setValue("center.x", mZoomCenter.x());
    saver.setValue("center.y", mZoomCenter.y());
}
void PaintImageWidget::setCurrentPoint (QPointF const & currentPoint)
void AdvancedImageWidget::setImage (QSharedPointer< QImage > _image) [inherited]
Definition at line 88 of file advancedImageWidget.cpp.
References AdvancedImageWidget::drawResized(), AdvancedImageWidget::mImage, AdvancedImageWidget::mImageSize, AdvancedImageWidget::mIsFreezed, AdvancedImageWidget::mOutputRect, AdvancedImageWidget::mResizeCache, AdvancedImageWidget::mSaveProcStarted, AdvancedImageWidget::mUi, AdvancedImageWidget::mZoomCenter, AdvancedImageWidget::recalculateZoomCenter(), AdvancedImageWidget::recomputeRects(), and AdvancedImageWidget::saveFlowImage().
Referenced by DistortionWidget::updateAdditionalData(), and TestbedMainWindow::updateViewImage().
{
    if (mIsFreezed)
        return;
    if (newImage.isNull())
        return;
    mImage = newImage;
    delete_safe(mResizeCache);
    if (mSaveProcStarted)
    {
        mResizeCache = new QImage(mOutputRect.size(), QImage::Format_RGB32);
        mResizeCache->fill(0);
        QPainter cachePainter(mResizeCache);
        drawResized(cachePainter);
        cachePainter.setPen(QColor(Qt::red));
        cachePainter.drawRect(mResizeCache->rect().adjusted(0,0,-1,-1));
        cachePainter.end();
        saveFlowImage(mResizeCache);
    }
    if ((!mImage.isNull() && mImageSize != mImage->size())
            || (mZoomCenter == QPoint(-1,-1)))
    {
        mImageSize = mImage->size();
        recalculateZoomCenter();
    }
    recomputeRects();
    mUi->widget->update();
}
void AdvancedImageWidget::setInfoString (QString info) [inline, slot, inherited]
Definition at line 66 of file advancedImageWidget.h.
References AdvancedImageWidget::mUi.
{ mUi->infoValueLabel->setText(info); }
void AdvancedImageWidget::setInfoValueLabel (QString & string) [inherited]
Definition at line 709 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi.
Referenced by AdvancedImageWidget::childMouseMoved().
{
    mUi->infoValueLabel->setText(infoString);
}
void AdvancedImageWidget::setSavingRoot (const QString & root) [inline, inherited]
Definition at line 166 of file advancedImageWidget.h.
References AdvancedImageWidget::mRootPath.
Referenced by BaseHostDialog::createAdditionalWindow().
    {
        mRootPath = root;
    }
void PaintImageWidget::setSelectedPoint (QPointF const & point, bool isSelected)
Definition at line 338 of file paintImageWidget.cpp.
{
    /* for (int i = 0; i < mPoints.count(); i ++)
    {
        if ((point - mPoints[i].first).manhattanLength() < epsilon)
        {
            mPoints[i].second = isSelected;
        }
    }*/
    update();
}
void AdvancedImageWidget::startSaveFlow () [slot, inherited]
Definition at line 311 of file advancedImageWidget.cpp.
References SaveFlowSettings::getUi(), AdvancedImageWidget::mImageSavePath, AdvancedImageWidget::mSaveDialog, AdvancedImageWidget::mSaveProcStarted, and AdvancedImageWidget::mUi.
Referenced by AdvancedImageWidget::AdvancedImageWidget().
{
    mSaveDialog->hide();
    mSaveProcStarted = true;
    mUi->saveFlowButton->setText("Stop");
    mImageSavePath = mSaveDialog->getUi()->pathEdit->text() + "/" + mSaveDialog->getUi()->fileTemplateEdit->text();
    mUi->fileNamelabel->show();
    mUi->fileValuelabel->show();
}
void AdvancedImageWidget::stopSaveFlow () [slot, inherited]
Definition at line 321 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mImageNumber, AdvancedImageWidget::mImageSavePath, AdvancedImageWidget::mSaveDialog, AdvancedImageWidget::mSaveProcStarted, and AdvancedImageWidget::mUi.
{
    if( mSaveProcStarted )
    {
        mUi->saveFlowButton->setText("Save flow");
        mSaveProcStarted = false;
        mImageSavePath = "";
        mImageNumber = 0;
        mUi->fileNamelabel->hide();
        mUi->fileValuelabel->hide();
    }
    else
    {
        mSaveDialog->show();
    }
}
void PaintImageWidget::toolButtonClicked (ToolButtonType type) [signal]
Referenced by clickOnToolButton().
void PaintImageWidget::toolButtonReleased (QWidget * button) [virtual, slot]
This could be reimplemented to add additional tools.
Reimplemented from AdvancedImageWidget.
Definition at line 91 of file paintImageWidget.cpp.
References addVertexToPath(), clickOnToolButton(), deleteVertex(), infoButton, mAddPointButton, AdvancedImageWidget::mCurrentToolClass, mDeletePointButton, mPaths, mPoints, mSelectButton, mSelectedPaths, mSelectedPoints, AdvancedImageWidget::mUi, panButton, SELECT_TOOL, selectButton, and selectZoomButton.
{
    AdvancedImageWidget::toolButtonReleased(button);
    if (button == mUi->panButton)
    {
        clickOnToolButton(button, mUi->panButton, panButton);
    }
    else if (button == mUi->selectZoomButton)
    {
        clickOnToolButton(button, mUi->selectZoomButton, selectZoomButton);
    }
    else if (button == mUi->infoButton)
    {
        clickOnToolButton(button, mUi->infoButton, infoButton);
    }
    else if (button == mSelectButton)
    {
        mCurrentToolClass = (ToolClass)SELECT_TOOL;
        mUi->widget->setCursor(Qt::ArrowCursor);
        clickOnToolButton(button, mSelectButton, selectButton);
    }
    else if (button == mAddPointButton)
    {
        int i = 0;
        for (; i < mSelectedPoints.size(); i++)
        {
            if (!mSelectedPoints[i]->isInPath()) {
                break;
            }
        }
        if (i == mSelectedPoints.size()) {
            return;
        }
        VertexPath *newPath = NULL;
        if (mSelectedPaths.isEmpty())
        {
            mPaths.append(VertexPath());
            newPath = &mPaths[mPaths.size() - 1];
        }
        else
        {
            newPath = mSelectedPaths[0];
        }
        for (int i = 0; i < mSelectedPoints.size(); i++)
        {
            if (!mSelectedPoints[i]->isInPath())
            {
                addVertexToPath(mSelectedPoints[i], newPath);
            }
        }
        mUi->widget->update();
    }
    else if (button == mDeletePointButton)
    {
        mSelectedPoints.clear();
        for (int i = 0; i < mPoints.size();)
        {
            if (mPoints[i].isSelected)
            {
                deleteVertex(i);
            }
            else
            {
                i++;
            }
        }
        mUi->widget->update();
    }
}
void PaintImageWidget::vectorDataChanged () [signal]
void ViAreaWidget::wheelEvent (QWheelEvent * event) [virtual, inherited]
Definition at line 47 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentWheelEvent().
{
    if (!mForwardEvents) return;
    emit notifyParentWheelEvent(event);
}
QPoint AdvancedImageWidget::widgetToImage (const QPoint & p) [protected, inherited]
Definition at line 169 of file advancedImageWidget.cpp.
References corecvs::fround(), and AdvancedImageWidget::widgetToImageF().
Referenced by AdvancedImageWidget::childMouseMoved(), and AdvancedImageWidget::childMouseReleased().
{
    QPointF out = widgetToImageF(p);
    return QPoint(fround(out.x()), fround(out.y()));
}
Vector2dd PaintImageWidget::widgetToImageF (const Vector2dd & p)
Definition at line 367 of file paintImageWidget.cpp.
References Core2Qt::QPointFromVector2dd(), Qt2Core::Vector2ddFromQPointF(), and AdvancedImageWidget::widgetToImageF().
Referenced by childMouseMoved(), and childMousePressed().
{
    return Qt2Core::Vector2ddFromQPointF(AdvancedImageWidget::widgetToImageF(Core2Qt::QPointFromVector2dd(p)));
}
QPointF AdvancedImageWidget::widgetToImageF (const QPointF & p) [protected, inherited]
Definition at line 141 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mInputRect, and AdvancedImageWidget::mOutputRect.
Referenced by AdvancedImageWidget::childWheelEvent(), AdvancedImageWidget::widgetToImage(), and widgetToImageF().
{
    double hAspect = (double)mInputRect.height() / mOutputRect.height();
    double wAspect = (double)mInputRect.width()  / mOutputRect.width();
    double x = (p.x() - mOutputRect.left()) * wAspect + mInputRect.x();
    double y = (p.y() - mOutputRect.top())  * hAspect + mInputRect.y();
    return QPointF(x,y);
}
void AdvancedImageWidget::zoomChanged () [slot, inherited]
Definition at line 523 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi, AdvancedImageWidget::notifyZoomChanged(), and AdvancedImageWidget::recomputeRects().
Referenced by AdvancedImageWidget::changeZoom().
{
    mUi->zoomInButton ->setEnabled(mUi->expSpinBox->value() != mUi->expSpinBox->maximum());
    mUi->zoomOutButton->setEnabled(mUi->expSpinBox->value() != mUi->expSpinBox->minimum());
    recomputeRects();
    emit notifyZoomChanged(mUi->expSpinBox->value());
    mUi->widget->update();
}
void AdvancedImageWidget::zoomIn () [slot, inherited]
Definition at line 546 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi.
Referenced by AdvancedImageWidget::childWheelEvent().
{
    mUi->expSpinBox->stepUp();
}
void AdvancedImageWidget::zoomOut () [slot, inherited]
Definition at line 551 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mUi.
Referenced by AdvancedImageWidget::childWheelEvent().
{
    mUi->expSpinBox->stepDown();
}
void AdvancedImageWidget::zoomReset () [slot, inherited]
Definition at line 508 of file advancedImageWidget.cpp.
References AdvancedImageWidget::mImage, AdvancedImageWidget::mUi, AdvancedImageWidget::mZoomCenter, AdvancedImageWidget::notifyCenterPointChanged(), and AdvancedImageWidget::recomputeRects().
{
    if (mImage == NULL) {
        mZoomCenter = QPoint(-1,-1);
    }
    else
    {
        mZoomCenter = QPoint(mImage->size().width(), mImage->size().height()) / 2.0;
    }
    mUi->expSpinBox->setValue(1.0);
    recomputeRects();
    emit notifyCenterPointChanged(mZoomCenter);
    mUi->widget->update();
}
Member Data Documentation
QToolButton* PaintImageWidget::mAddPointButton
Definition at line 172 of file paintImageWidget.h.
Referenced by PaintImageWidget(), and toolButtonReleased().
QIcon AdvancedImageWidget::mContinueIcon [protected, inherited]
Definition at line 92 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::freezeImage().
int AdvancedImageWidget::mCurrentLineButton [protected, inherited]
Definition at line 143 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childMouseReleased(), and AdvancedImageWidget::toolButtonReleased().
int AdvancedImageWidget::mCurrentPointButton [protected, inherited]
Definition at line 141 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childMouseMoved(), AdvancedImageWidget::childMouseReleased(), and AdvancedImageWidget::toolButtonReleased().
int AdvancedImageWidget::mCurrentSelectionButton [protected, inherited]
Definition at line 139 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childMouseReleased(), and AdvancedImageWidget::toolButtonReleased().
ToolClass AdvancedImageWidget::mCurrentToolClass [protected, inherited]
Definition at line 125 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::AdvancedImageWidget(), childMouseMoved(), AdvancedImageWidget::childMouseMoved(), childMousePressed(), AdvancedImageWidget::childMousePressed(), AdvancedImageWidget::childMouseReleased(), AdvancedImageWidget::childRepaint(), AdvancedImageWidget::toolButtonReleased(), and toolButtonReleased().
QToolButton* PaintImageWidget::mDeletePointButton
Definition at line 173 of file paintImageWidget.h.
Referenced by PaintImageWidget(), and toolButtonReleased().
bool PaintImageWidget::mEventFromOtherWidget [private]
Definition at line 64 of file paintImageWidget.h.
Referenced by clickOnToolButton(), and clickToolButton().
QIcon AdvancedImageWidget::mFreezeIcon [protected, inherited]
Definition at line 91 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::freezeImage().
QSharedPointer<QImage> AdvancedImageWidget::mImage [inherited]
Definition at line 28 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childMouseMoved(), AdvancedImageWidget::childMouseReleased(), AdvancedImageWidget::childRepaint(), childRepaint(), AdvancedImageWidget::computeInputRect(), AdvancedImageWidget::drawResized(), AdvancedImageWidget::recalculateZoomCenter(), AdvancedImageWidget::recomputeRects(), AdvancedImageWidget::saveImageToFile(), AdvancedImageWidget::setImage(), and AdvancedImageWidget::zoomReset().
unsigned int AdvancedImageWidget::mImageNumber [protected, inherited]
Definition at line 95 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::saveFlowImage(), and AdvancedImageWidget::stopSaveFlow().
QString AdvancedImageWidget::mImageSavePath [protected, inherited]
Definition at line 96 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::saveFlowImage(), AdvancedImageWidget::startSaveFlow(), and AdvancedImageWidget::stopSaveFlow().
QSize AdvancedImageWidget::mImageSize [protected, inherited]
Definition at line 153 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::setImage().
QRect AdvancedImageWidget::mInputRect [protected, inherited]
Definition at line 103 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::drawResized(), AdvancedImageWidget::imageToWidgetF(), AdvancedImageWidget::recomputeRects(), and AdvancedImageWidget::widgetToImageF().
bool AdvancedImageWidget::mIsFreezed [protected, inherited]
Definition at line 90 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::freezeImage(), and AdvancedImageWidget::setImage().
bool AdvancedImageWidget::mIsMousePressed [protected, inherited]
Definition at line 106 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childMouseMoved(), childMouseMoved(), AdvancedImageWidget::childMousePressed(), AdvancedImageWidget::childMouseReleased(), and AdvancedImageWidget::childRepaint().
vector<WidgetToolButton> AdvancedImageWidget::mLineButtons [protected, inherited]
Definition at line 142 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::addLineTool(), and AdvancedImageWidget::toolButtonReleased().
QRect AdvancedImageWidget::mOutputRect [protected, inherited]
Definition at line 102 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childRepaint(), AdvancedImageWidget::drawResized(), AdvancedImageWidget::imageToWidgetF(), AdvancedImageWidget::recomputeRects(), AdvancedImageWidget::saveImageToFile(), AdvancedImageWidget::setImage(), and AdvancedImageWidget::widgetToImageF().
QList<VertexPath> PaintImageWidget::mPaths
Pathes.
Definition at line 137 of file paintImageWidget.h.
Referenced by childRepaint(), clear(), deleteVertex(), getPaths(), DistortionWidget::loadPoints(), toolButtonReleased(), and DistortionWidget::updateScore().
vector<WidgetToolButton> AdvancedImageWidget::mPointButtons [protected, inherited]
Definition at line 140 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::addPointTool(), and AdvancedImageWidget::toolButtonReleased().
QList<Vertex> PaintImageWidget::mPoints
Points.
Definition at line 90 of file paintImageWidget.h.
Referenced by addVertex(), childMousePressed(), childRepaint(), clear(), deleteVertex(), findClosest(), DistortionWidget::loadPoints(), and toolButtonReleased().
QImage* AdvancedImageWidget::mResizeCache [protected, inherited]
Definition at line 110 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childRepaint(), AdvancedImageWidget::recomputeRects(), AdvancedImageWidget::saveImageToFile(), AdvancedImageWidget::setImage(), and AdvancedImageWidget::~AdvancedImageWidget().
QString AdvancedImageWidget::mRootPath [protected, inherited]
Definition at line 161 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::loadFromQSettings(), AdvancedImageWidget::saveToQSettings(), and AdvancedImageWidget::setSavingRoot().
SaveFlowSettings* AdvancedImageWidget::mSaveDialog [protected, inherited]
Definition at line 97 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::AdvancedImageWidget(), AdvancedImageWidget::startSaveFlow(), AdvancedImageWidget::stopSaveFlow(), and AdvancedImageWidget::~AdvancedImageWidget().
bool AdvancedImageWidget::mSaveProcStarted [protected, inherited]
Definition at line 94 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::saveFlowImage(), AdvancedImageWidget::setImage(), AdvancedImageWidget::startSaveFlow(), and AdvancedImageWidget::stopSaveFlow().
QToolButton* PaintImageWidget::mSelectButton
Definition at line 171 of file paintImageWidget.h.
Referenced by clickToolButton(), PaintImageWidget(), and toolButtonReleased().
QList<VertexPath *> PaintImageWidget::mSelectedPaths
Definition at line 138 of file paintImageWidget.h.
Referenced by addSelection(), clear(), deleteVertex(), deselectAllPath(), and toolButtonReleased().
QList<Vertex*> PaintImageWidget::mSelectedPoints
Definition at line 91 of file paintImageWidget.h.
Referenced by addSelection(), childMouseMoved(), clear(), currentPoint(), deselectAllPoints(), removeSelection(), and toolButtonReleased().
vector<WidgetToolButton> AdvancedImageWidget::mSelectionButtons [protected, inherited]
Definition at line 138 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::addSelectionTool(), and AdvancedImageWidget::toolButtonReleased().
QPoint AdvancedImageWidget::mSelectionEnd [protected, inherited]
Definition at line 108 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childMouseMoved(), childMouseMoved(), AdvancedImageWidget::childMousePressed(), AdvancedImageWidget::childMouseReleased(), and AdvancedImageWidget::childRepaint().
QPoint AdvancedImageWidget::mSelectionStart [protected, inherited]
Definition at line 107 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::childMousePressed(), AdvancedImageWidget::childMouseReleased(), and AdvancedImageWidget::childRepaint().
QSignalMapper AdvancedImageWidget::mToolMapper [protected, inherited]
Definition at line 145 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::addToolButton(), and AdvancedImageWidget::AdvancedImageWidget().
Ui_advancedImageWidget* AdvancedImageWidget::mUi [protected, inherited]
Definition at line 98 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::AdvancedImageWidget(), AdvancedImageWidget::changeZoom(), childMouseMoved(), AdvancedImageWidget::childMouseMoved(), AdvancedImageWidget::childMousePressed(), childMousePressed(), AdvancedImageWidget::childMouseReleased(), AdvancedImageWidget::childWheelEvent(), clickToolButton(), AdvancedImageWidget::computeInputRect(), deleteVertex(), AdvancedImageWidget::fitToggled(), AdvancedImageWidget::freezeImage(), AdvancedImageWidget::getToolsFrame(), AdvancedImageWidget::getWidget(), AdvancedImageWidget::loadFromQSettings(), AdvancedImageWidget::recomputeRects(), AdvancedImageWidget::saveFlowImage(), AdvancedImageWidget::saveToQSettings(), AdvancedImageWidget::setImage(), AdvancedImageWidget::setInfoString(), AdvancedImageWidget::setInfoValueLabel(), AdvancedImageWidget::startSaveFlow(), AdvancedImageWidget::stopSaveFlow(), AdvancedImageWidget::toolButtonReleased(), toolButtonReleased(), AdvancedImageWidget::zoomChanged(), AdvancedImageWidget::zoomIn(), AdvancedImageWidget::zoomOut(), AdvancedImageWidget::zoomReset(), and AdvancedImageWidget::~AdvancedImageWidget().
QPoint AdvancedImageWidget::mZoomCenter [protected, inherited]
Definition at line 100 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget::changeCenterPoint(), AdvancedImageWidget::childMouseMoved(), AdvancedImageWidget::childMouseReleased(), AdvancedImageWidget::childWheelEvent(), AdvancedImageWidget::computeInputRect(), AdvancedImageWidget::loadFromQSettings(), AdvancedImageWidget::recalculateZoomCenter(), AdvancedImageWidget::saveToQSettings(), AdvancedImageWidget::setImage(), and AdvancedImageWidget::zoomReset().
double PaintImageWidget::SELECTION_RADIUS = 5.0 [static, private]
Definition at line 16 of file paintImageWidget.h.
Referenced by childMousePressed().
Ui::PaintImageWidget* PaintImageWidget::ui [private]
Reimplemented from ViAreaWidget.
Definition at line 60 of file paintImageWidget.h.
Referenced by PaintImageWidget(), and ~PaintImageWidget().
The documentation for this class was generated from the following files:
utils/uis/paintImageWidget.h
utils/uis/paintImageWidget.cpp