DeepView: corecvs::SSEMath Class Reference
corecvs::SSEMath Class Reference
This class provides the base functions for SSE (and probably NEON) this creates common interface for SSE and ordinary integer types.
#include <sseMath.h>
Public Member Functions
template<>
UInt16x8 div (const UInt16x8 &val)
Unsigned operations.
template<>
UInt16x8 div (const UInt16x8 &val)
template<>
UInt16x8 div (const UInt16x8 &val)
template<>
UInt16x8 mul (const UInt16x8 &val)
template<>
UInt16x8 div (const UInt16x8 &val)
template<>
UInt16x8 div (const UInt16x8 &val)
template<>
UInt16x8 mul (const UInt16x8 &val)
Static Public Member Functions
template<int divisor>
static Int16x8 div (const Int16x8 &val)
template<int multiplier>
static Int16x8 mul (const Int16x8 &val)
template<int divisor>
static Int16x8 divU (const Int16x8 &val)
static ALIGN_STACK_SSE Int16x8 branchlessMask (const Int16x8 &val)
static ALIGN_STACK_SSE Int16x8 selector (const Int16x8 &condition, const Int16x8 &ifTrue, const Int16x8 &ifFalse)
static ALIGN_STACK_SSE Int32x4 selector (const Int32x4 &condition, const Int32x4 &ifTrue, const Int32x4 &ifFalse)
static ALIGN_STACK_SSE Int16x8 max (const Int16x8 &left, const Int16x8 &right)
static ALIGN_STACK_SSE Int16x8 min (const Int16x8 &left, const Int16x8 &right)
template<int divisor>
static Int16x8 div (const Int16x8 &val)
template<int multiplier>
static Int16x8 mul (const Int16x8 &val)
template<int divisor>
static UInt16x8 div (const UInt16x8 &val)
template<int multiplier>
static UInt16x8 mul (const UInt16x8 &val)
static ALIGN_STACK_SSE Int16x8 branchlessMask (const Int16x8 &val)
static ALIGN_STACK_SSE UInt16x8 branchlessMask (const UInt16x8 &val)
static ALIGN_STACK_SSE Int16x8 selector (const Int16x8 &condition, const Int16x8 &ifTrue, const Int16x8 &ifFalse)
static ALIGN_STACK_SSE UInt16x8 selector (const UInt16x8 &condition, const UInt16x8 &ifTrue, const UInt16x8 &ifFalse)
static ALIGN_STACK_SSE Int32x4 selector (const Int32x4 &condition, const Int32x4 &ifTrue, const Int32x4 &ifFalse)
static void blockSAD8 (PuzzleBlock &left, PuzzleBlock &right, uint16_t *result)
blockSAD8(): get UInt16x8 vector
static ALIGN_STACK_SSE Int16x8 max (const Int16x8 &left, const Int16x8 &right)
static ALIGN_STACK_SSE Int16x8 min (const Int16x8 &left, const Int16x8 &right)
static ALIGN_STACK_SSE UInt16x8 difference (const UInt16x8 &left, const UInt16x8 &right)
static ALIGN_STACK_SSE UInt16x8 difference15bit (const UInt16x8 &left, const UInt16x8 &right)
static ALIGN_STACK_SSE Int16x8 abs (const Int16x8 &value)
Detailed Description
This class provides the base functions for SSE (and probably NEON) this creates common interface for SSE and ordinary integer types.
Definition at line 16 of file sseMath.h.
Member Function Documentation
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::abs (const Int16x8 & value) [inline, static]
Definition at line 155 of file sseMath.h.
References max().
{
        return max(value, -value);
    }
static void corecvs::SSEMath::blockSAD8 (PuzzleBlock & left, PuzzleBlock & right, uint16_t * result) [inline, static]
blockSAD8(): get UInt16x8 vector
    [SAD(left,right) SAD(left+1,right) ... SAD(left+7,right) ]
where, for example, left + 5 is
             left              left + 5
         +-----------+       +-----------+
         |_0_|_1_|_2_|_3_|_4_|_5_|___|___|
         |   |   |   |       |   |   |   |
         |___|___|___|   ->  |___|___|___|
         |   |   |   |       |   |   |   |
         +-----------+       +-----------+
and
Definition at line 91 of file sseMath.h.
References corecvs::PuzzleBlock::data, difference(), corecvs::PuzzleBlock::h, corecvs::UInt16x8::save(), corecvs::PuzzleBlock::stride, and corecvs::PuzzleBlock::w.
    {
        UInt16x8 cost((uint16_t)0);
        uint16_t *dataL = NULL;
        uint16_t *dataR = NULL;
        for (int i = 0; i < left.h; i++)
        {
            dataL = left.data  + i * left.stride;
            dataR = right.data + i * right.stride;
            for (int j = 0; j < left.w; j++)
            {
                UInt16x8 valL(dataL);
                UInt16x8 valR(dataR[0]);
                UInt16x8 diff = difference(valL, valR);
                cost += diff;
                dataL++;
                dataR++;
            }
        }
        cost.save(result);
    }
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::branchlessMask (const Int16x8 & val) [inline, static]
Definition at line 28 of file sseMath.h.
    {
        return val;
    }
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::branchlessMask (const Int16x8 & val) [inline, static]
Definition at line 44 of file sseMath.h.
    {
        return val;
    }
static ALIGN_STACK_SSE UInt16x8 corecvs::SSEMath::branchlessMask (const UInt16x8 & val) [inline, static]
Definition at line 49 of file sseMath.h.
    {
        return val;
    }
static ALIGN_STACK_SSE UInt16x8 corecvs::SSEMath::difference (const UInt16x8 & left, const UInt16x8 & right) [inline, static]
Definition at line 136 of file sseMath.h.
References max(), min(), and selector().
Referenced by blockSAD8().
{
#ifdef WITH_SSE4
        UInt16x8 min_tmp = min(left, right);
        UInt16x8 max_tmp = max(left, right);
        return UInt16x8(max_tmp - min_tmp);
#else
        return selector(left > right, (left - right), (right - left));
#endif
    }
static ALIGN_STACK_SSE UInt16x8 corecvs::SSEMath::difference15bit (const UInt16x8 & left, const UInt16x8 & right) [inline, static]
Definition at line 146 of file sseMath.h.
References max(), and min().
{
        Int16x8 leftSigned  = (Int16x8)left;
        Int16x8 rightSigned = (Int16x8)right;
        Int16x8 min_tmp = min(leftSigned, rightSigned);
        Int16x8 max_tmp = max(leftSigned, rightSigned);
        return UInt16x8(max_tmp - min_tmp);
    }
Int16x8 corecvs::SSEMath::div< 16 > (const Int16x8 & val) [inline, static]
Definition at line 69 of file sseMath.h.
References corecvs::shiftArithmetic().
{
    return shiftArithmetic(val, 1);
};
template<int divisor> static Int16x8 corecvs::SSEMath::div (const Int16x8 & val) [inline, static]
template<int divisor> static UInt16x8 corecvs::SSEMath::div (const UInt16x8 & val) [inline, static]
template<> UInt16x8 corecvs::SSEMath::div (const UInt16x8 & val) [inline]
Unsigned operations.
Definition at line 164 of file sseMath.h.
{
    return val >> 1;
}
template<> UInt16x8 corecvs::SSEMath::div (const UInt16x8 & val) [inline]
Definition at line 169 of file sseMath.h.
{
    return val >> 2;
}
template<> UInt16x8 corecvs::SSEMath::div (const UInt16x8 & val) [inline]
Definition at line 174 of file sseMath.h.
{
    return val >> 4;
}
template<> UInt16x8 corecvs::SSEMath::div (const UInt16x8 & val) [inline]
Definition at line 206 of file sseMath.h.
{
    UInt16x8 a =  (val >> 1) + (val >> 2);
    a += (a >> 4) + (a >> 8) + (a >> 12);
    a >>= 2;
    UInt16x8 diff = val - mul<5>(a);
    a -= (diff > UInt16x8((uint16_t)4));
    return a;
}
template<> UInt16x8 corecvs::SSEMath::div (const UInt16x8 & val) [inline]
Definition at line 216 of file sseMath.h.
{
    return div<5>(div<2>(val));
}
Int16x8 corecvs::SSEMath::divU< 16 > (const Int16x8 & val) [inline, static]
Definition at line 54 of file sseMath.h.
{
    return  val >> 1;
};
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::max (const Int16x8 & left, const Int16x8 & right) [inline, static]
Definition at line 44 of file sseMath.h.
References corecvs::Int16x8::data.
Referenced by abs(), difference(), and difference15bit().
{
        return Int16x8(vmaxq_s16(left.data, right.data));
    }
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::max (const Int16x8 & left, const Int16x8 & right) [inline, static]
Definition at line 116 of file sseMath.h.
References corecvs::Int16x8::data.
{
        return Int16x8(_mm_max_epi16(left.data, right.data));
    }
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::min (const Int16x8 & left, const Int16x8 & right) [inline, static]
Definition at line 48 of file sseMath.h.
References corecvs::Int16x8::data.
Referenced by difference(), and difference15bit().
{
        return Int16x8(vminq_s16(left.data, right.data));
    }
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::min (const Int16x8 & left, const Int16x8 & right) [inline, static]
Definition at line 120 of file sseMath.h.
References corecvs::Int16x8::data.
{
        return Int16x8(_mm_min_epi16(left.data, right.data));
    }
Int16x8 corecvs::SSEMath::mul< 3 > (const Int16x8 & val) [inline, static]
Definition at line 86 of file sseMath.h.
{
    return (val << 2) + val;
};
template<int multiplier> static Int16x8 corecvs::SSEMath::mul (const Int16x8 & val) [inline, static]
template<int multiplier> static UInt16x8 corecvs::SSEMath::mul (const UInt16x8 & val) [inline, static]
template<> UInt16x8 corecvs::SSEMath::mul (const UInt16x8 & val) [inline]
Definition at line 201 of file sseMath.h.
{
    return (val << 2) + val;
}
template<> UInt16x8 corecvs::SSEMath::mul (const UInt16x8 & val) [inline]
Definition at line 241 of file sseMath.h.
{
    return val << 1;
}
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::selector (const Int16x8 & condition, const Int16x8 & ifTrue, const Int16x8 & ifFalse) [inline, static]
Definition at line 33 of file sseMath.h.
References corecvs::andNot().
Referenced by corecvs::DecoupleYUYV::decouple(), difference(), and corecvs::RGB24Buffer::fillWithYUYV().
    {
        return (condition & ifTrue) | (andNot(condition, ifFalse));
    }
static ALIGN_STACK_SSE Int32x4 corecvs::SSEMath::selector (const Int32x4 & condition, const Int32x4 & ifTrue, const Int32x4 & ifFalse) [inline, static]
Definition at line 38 of file sseMath.h.
References corecvs::andNot().
    {
        return (condition & ifTrue) | (andNot(condition, ifFalse));
    }
static ALIGN_STACK_SSE Int16x8 corecvs::SSEMath::selector (const Int16x8 & condition, const Int16x8 & ifTrue, const Int16x8 & ifFalse) [inline, static]
Definition at line 54 of file sseMath.h.
References corecvs::andNot().
    {
        return Int16x8((condition & ifTrue) | (andNot(condition, ifFalse)));
    }
static ALIGN_STACK_SSE UInt16x8 corecvs::SSEMath::selector (const UInt16x8 & condition, const UInt16x8 & ifTrue, const UInt16x8 & ifFalse) [inline, static]
Definition at line 59 of file sseMath.h.
References corecvs::andNot().
    {
        return UInt16x8((condition & ifTrue) | (andNot(condition, ifFalse)));
    }
static ALIGN_STACK_SSE Int32x4 corecvs::SSEMath::selector (const Int32x4 & condition, const Int32x4 & ifTrue, const Int32x4 & ifFalse) [inline, static]
Definition at line 66 of file sseMath.h.
References corecvs::andNot().
    {
        return (condition & ifTrue) | (andNot(condition, ifFalse));
    }
The documentation for this class was generated from the following files:
core/math/neon/sseMath.h
core/math/sse/sseMath.h