DeepView: RectifyParameters Class Reference
RectifyParameters Class Reference
osd parameters osd parameters
#include <rectifyParameters.h>
Public Types
enum FieldId {
MATCHINGMETHOD_ID, HESSIANTHRESHOLD_ID, OCTAVES_ID, OCTAVELAYERS_ID,
EXTENDED_ID, FILTERMINIMUMLENGTH_ID, USEKLT_ID, COMPUTEESSENTIAL_ID,
PRIORFOCAL_ID, PRIORFOCAL2_ID, BASELINELENGTH_ID, FOVANGLE_ID,
ESTIMATIONMETHOD_ID, NORMALISE_ID, RANSACITERATIONS_ID, RANSACTESTSIZE_ID,
RANSACTHRESHOLD_ID, BASELINEX_ID, BASELINEY_ID, BASELINEZ_ID,
ITERATIVEMETHOD_ID, ITERATIVEITERATIONS_ID, ITERATIVEINITIALSIGMA_ID, ITERATIVEFACTORSIGMA_ID,
MANUALX_ID, MANUALY_ID, MANUALZ_ID, MANUALPITCH_ID,
MANUALYAW_ID, MANUALROLL_ID, ZDIRX_ID, ZDIRY_ID,
ZDIRZ_ID, AUTOZ_ID, AUTOSHIFT_ID, PRESHIFT_ID,
GUESSSHIFTTHRESHOLD_ID, RECTIFY_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
MatchingMethodType::MatchingMethodType matchingMethod () const
double hessianThreshold () const
int octaves () const
int octaveLayers () const
bool extended () const
double filterMinimumLength () const
bool useKLT () const
bool computeEssential () const
double priorFocal () const
double priorFocal2 () const
double baselineLength () const
double fovAngle () const
EstimationMethodType::EstimationMethodType estimationMethod () const
bool normalise () const
int ransacIterations () const
int ransacTestSize () const
double ransacThreshold () const
double baselineX () const
double baselineY () const
double baselineZ () const
OptimizationMethodType::OptimizationMethodType iterativeMethod () const
int iterativeIterations () const
double iterativeInitialSigma () const
double iterativeFactorSigma () const
double manualX () const
double manualY () const
double manualZ () const
double manualPitch () const
double manualYaw () const
double manualRoll () const
double zdirX () const
double zdirY () const
double zdirZ () const
bool autoZ () const
bool autoShift () const
int preShift () const
int guessShiftThreshold () const
void setMatchingMethod (MatchingMethodType::MatchingMethodType matchingMethod)
void setHessianThreshold (double hessianThreshold)
void setOctaves (int octaves)
void setOctaveLayers (int octaveLayers)
void setExtended (bool extended)
void setFilterMinimumLength (double filterMinimumLength)
void setUseKLT (bool useKLT)
void setComputeEssential (bool computeEssential)
void setPriorFocal (double priorFocal)
void setPriorFocal2 (double priorFocal2)
void setBaselineLength (double baselineLength)
void setFovAngle (double fovAngle)
void setEstimationMethod (EstimationMethodType::EstimationMethodType estimationMethod)
void setNormalise (bool normalise)
void setRansacIterations (int ransacIterations)
void setRansacTestSize (int ransacTestSize)
void setRansacThreshold (double ransacThreshold)
void setBaselineX (double baselineX)
void setBaselineY (double baselineY)
void setBaselineZ (double baselineZ)
void setIterativeMethod (OptimizationMethodType::OptimizationMethodType iterativeMethod)
void setIterativeIterations (int iterativeIterations)
void setIterativeInitialSigma (double iterativeInitialSigma)
void setIterativeFactorSigma (double iterativeFactorSigma)
void setManualX (double manualX)
void setManualY (double manualY)
void setManualZ (double manualZ)
void setManualPitch (double manualPitch)
void setManualYaw (double manualYaw)
void setManualRoll (double manualRoll)
void setZdirX (double zdirX)
void setZdirY (double zdirY)
void setZdirZ (double zdirZ)
void setAutoZ (bool autoZ)
void setAutoShift (bool autoShift)
void setPreShift (int preShift)
void setGuessShiftThreshold (int guessShiftThreshold)
template<class VisitorType >
void accept (VisitorType &visitor)
RectifyParameters ()
RectifyParameters (MatchingMethodType::MatchingMethodType matchingMethod, double hessianThreshold, int octaves, int octaveLayers, bool extended, double filterMinimumLength, bool useKLT, bool computeEssential, double priorFocal, double priorFocal2, double baselineLength, double fovAngle, EstimationMethodType::EstimationMethodType estimationMethod, bool normalise, int ransacIterations, int ransacTestSize, double ransacThreshold, double baselineX, double baselineY, double baselineZ, OptimizationMethodType::OptimizationMethodType iterativeMethod, int iterativeIterations, double iterativeInitialSigma, double iterativeFactorSigma, double manualX, double manualY, double manualZ, double manualPitch, double manualYaw, double manualRoll, double zdirX, double zdirY, double zdirZ, bool autoZ, bool autoShift, int preShift, int guessShiftThreshold)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mMatchingMethod
Section with variables.
double mHessianThreshold
hessianThreshold hessianThreshold
int mOctaves
octaves octaves
int mOctaveLayers
octaveLayers octaveLayers
bool mExtended
extended extended
double mFilterMinimumLength
filterMinimumLength filterMinimumLength
bool mUseKLT
useKLT useKLT
bool mComputeEssential
computeEssential computeEssential
double mPriorFocal
priorFocal priorFocal
double mPriorFocal2
priorFocal2 priorFocal2
double mBaselineLength
baselineLength baselineLength
double mFovAngle
fovAngle fovAngle
int mEstimationMethod
estimationMethod estimationMethod
bool mNormalise
normalise normalise
int mRansacIterations
ransacIterations ransacIterations
int mRansacTestSize
ransacTestSize ransacTestSize
double mRansacThreshold
ransacThreshold ransacThreshold
double mBaselineX
baselineX baselineX
double mBaselineY
baselineY baselineY
double mBaselineZ
baselineZ baselineZ
int mIterativeMethod
iterativeMethod iterativeMethod
int mIterativeIterations
iterativeIterations iterativeIterations
double mIterativeInitialSigma
iterativeInitialSigma iterativeInitialSigma
double mIterativeFactorSigma
iterativeFactorSigma iterativeFactorSigma
double mManualX
manualX manualX
double mManualY
manualY manualY
double mManualZ
manualZ manualZ
double mManualPitch
manualPitch manualPitch
double mManualYaw
manualYaw manualYaw
double mManualRoll
manualRoll manualRoll
double mZdirX
zdirX zdirX
double mZdirY
zdirY zdirY
double mZdirZ
zdirZ zdirZ
bool mAutoZ
autoZ autoZ
bool mAutoShift
autoShift autoShift
int mPreShift
preShift preShift
int mGuessShiftThreshold
guessShiftThreshold guessShiftThreshold
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, RectifyParameters &toSave)
Detailed Description
osd parameters osd parameters
Definition at line 41 of file rectifyParameters.h.
Member Enumeration Documentation
enum RectifyParameters::FieldId
Enumerator:
MATCHINGMETHOD_ID
HESSIANTHRESHOLD_ID
OCTAVES_ID
OCTAVELAYERS_ID
EXTENDED_ID
FILTERMINIMUMLENGTH_ID
USEKLT_ID
COMPUTEESSENTIAL_ID
PRIORFOCAL_ID
PRIORFOCAL2_ID
BASELINELENGTH_ID
FOVANGLE_ID
ESTIMATIONMETHOD_ID
NORMALISE_ID
RANSACITERATIONS_ID
RANSACTESTSIZE_ID
RANSACTHRESHOLD_ID
BASELINEX_ID
BASELINEY_ID
BASELINEZ_ID
ITERATIVEMETHOD_ID
ITERATIVEITERATIONS_ID
ITERATIVEINITIALSIGMA_ID
ITERATIVEFACTORSIGMA_ID
MANUALX_ID
MANUALY_ID
MANUALZ_ID
MANUALPITCH_ID
MANUALYAW_ID
MANUALROLL_ID
ZDIRX_ID
ZDIRY_ID
ZDIRZ_ID
AUTOZ_ID
AUTOSHIFT_ID
PRESHIFT_ID
GUESSSHIFTTHRESHOLD_ID
RECTIFY_PARAMETERS_FIELD_ID_NUM
Definition at line 44 of file rectifyParameters.h.
                 {
        MATCHINGMETHOD_ID,
        HESSIANTHRESHOLD_ID,
        OCTAVES_ID,
        OCTAVELAYERS_ID,
        EXTENDED_ID,
        FILTERMINIMUMLENGTH_ID,
        USEKLT_ID,
        COMPUTEESSENTIAL_ID,
        PRIORFOCAL_ID,
        PRIORFOCAL2_ID,
        BASELINELENGTH_ID,
        FOVANGLE_ID,
        ESTIMATIONMETHOD_ID,
        NORMALISE_ID,
        RANSACITERATIONS_ID,
        RANSACTESTSIZE_ID,
        RANSACTHRESHOLD_ID,
        BASELINEX_ID,
        BASELINEY_ID,
        BASELINEZ_ID,
        ITERATIVEMETHOD_ID,
        ITERATIVEITERATIONS_ID,
        ITERATIVEINITIALSIGMA_ID,
        ITERATIVEFACTORSIGMA_ID,
        MANUALX_ID,
        MANUALY_ID,
        MANUALZ_ID,
        MANUALPITCH_ID,
        MANUALYAW_ID,
        MANUALROLL_ID,
        ZDIRX_ID,
        ZDIRY_ID,
        ZDIRZ_ID,
        AUTOZ_ID,
        AUTOSHIFT_ID,
        PRESHIFT_ID,
        GUESSSHIFTTHRESHOLD_ID,
        RECTIFY_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
RectifyParameters::RectifyParameters () [inline]
Definition at line 732 of file rectifyParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
RectifyParameters::RectifyParameters (MatchingMethodType::MatchingMethodType matchingMethod, double hessianThreshold, int octaves, int octaveLayers, bool extended, double filterMinimumLength, bool useKLT, bool computeEssential, double priorFocal, double priorFocal2, double baselineLength, double fovAngle, EstimationMethodType::EstimationMethodType estimationMethod, bool normalise, int ransacIterations, int ransacTestSize, double ransacThreshold, double baselineX, double baselineY, double baselineZ, OptimizationMethodType::OptimizationMethodType iterativeMethod, int iterativeIterations, double iterativeInitialSigma, double iterativeFactorSigma, double manualX, double manualY, double manualZ, double manualPitch, double manualYaw, double manualRoll, double zdirX, double zdirY, double zdirZ, bool autoZ, bool autoShift, int preShift, int guessShiftThreshold) [inline]
Definition at line 738 of file rectifyParameters.h.
    {
        mMatchingMethod = matchingMethod;
        mHessianThreshold = hessianThreshold;
        mOctaves = octaves;
        mOctaveLayers = octaveLayers;
        mExtended = extended;
        mFilterMinimumLength = filterMinimumLength;
        mUseKLT = useKLT;
        mComputeEssential = computeEssential;
        mPriorFocal = priorFocal;
        mPriorFocal2 = priorFocal2;
        mBaselineLength = baselineLength;
        mFovAngle = fovAngle;
        mEstimationMethod = estimationMethod;
        mNormalise = normalise;
        mRansacIterations = ransacIterations;
        mRansacTestSize = ransacTestSize;
        mRansacThreshold = ransacThreshold;
        mBaselineX = baselineX;
        mBaselineY = baselineY;
        mBaselineZ = baselineZ;
        mIterativeMethod = iterativeMethod;
        mIterativeIterations = iterativeIterations;
        mIterativeInitialSigma = iterativeInitialSigma;
        mIterativeFactorSigma = iterativeFactorSigma;
        mManualX = manualX;
        mManualY = manualY;
        mManualZ = manualZ;
        mManualPitch = manualPitch;
        mManualYaw = manualYaw;
        mManualRoll = manualRoll;
        mZdirX = zdirX;
        mZdirY = zdirY;
        mZdirZ = zdirZ;
        mAutoZ = autoZ;
        mAutoShift = autoShift;
        mPreShift = preShift;
        mGuessShiftThreshold = guessShiftThreshold;
    }
Member Function Documentation
template<class VisitorType > void RectifyParameters::accept (VisitorType & visitor) [inline]
Definition at line 691 of file rectifyParameters.h.
    {
        visitor.visit((int &)mMatchingMethod,     static_cast<const EnumField *>    (fields()[MATCHINGMETHOD_ID]));
        visitor.visit(mHessianThreshold,          static_cast<const DoubleField *>  (fields()[HESSIANTHRESHOLD_ID]));
        visitor.visit(mOctaves,                   static_cast<const IntField *>     (fields()[OCTAVES_ID]));
        visitor.visit(mOctaveLayers,              static_cast<const IntField *>     (fields()[OCTAVELAYERS_ID]));
        visitor.visit(mExtended,                  static_cast<const BoolField *>    (fields()[EXTENDED_ID]));
        visitor.visit(mFilterMinimumLength,       static_cast<const DoubleField *>  (fields()[FILTERMINIMUMLENGTH_ID]));
        visitor.visit(mUseKLT,                    static_cast<const BoolField *>    (fields()[USEKLT_ID]));
        visitor.visit(mComputeEssential,          static_cast<const BoolField *>    (fields()[COMPUTEESSENTIAL_ID]));
        visitor.visit(mPriorFocal,                static_cast<const DoubleField *>  (fields()[PRIORFOCAL_ID]));
        visitor.visit(mPriorFocal2,               static_cast<const DoubleField *>  (fields()[PRIORFOCAL2_ID]));
        visitor.visit(mBaselineLength,            static_cast<const DoubleField *>  (fields()[BASELINELENGTH_ID]));
        visitor.visit(mFovAngle,                  static_cast<const DoubleField *>  (fields()[FOVANGLE_ID]));
        visitor.visit((int &)mEstimationMethod,   static_cast<const EnumField *>    (fields()[ESTIMATIONMETHOD_ID]));
        visitor.visit(mNormalise,                 static_cast<const BoolField *>    (fields()[NORMALISE_ID]));
        visitor.visit(mRansacIterations,          static_cast<const IntField *>     (fields()[RANSACITERATIONS_ID]));
        visitor.visit(mRansacTestSize,            static_cast<const IntField *>     (fields()[RANSACTESTSIZE_ID]));
        visitor.visit(mRansacThreshold,           static_cast<const DoubleField *>  (fields()[RANSACTHRESHOLD_ID]));
        visitor.visit(mBaselineX,                 static_cast<const DoubleField *>  (fields()[BASELINEX_ID]));
        visitor.visit(mBaselineY,                 static_cast<const DoubleField *>  (fields()[BASELINEY_ID]));
        visitor.visit(mBaselineZ,                 static_cast<const DoubleField *>  (fields()[BASELINEZ_ID]));
        visitor.visit((int &)mIterativeMethod,    static_cast<const EnumField *>    (fields()[ITERATIVEMETHOD_ID]));
        visitor.visit(mIterativeIterations,       static_cast<const IntField *>     (fields()[ITERATIVEITERATIONS_ID]));
        visitor.visit(mIterativeInitialSigma,     static_cast<const DoubleField *>  (fields()[ITERATIVEINITIALSIGMA_ID]));
        visitor.visit(mIterativeFactorSigma,      static_cast<const DoubleField *>  (fields()[ITERATIVEFACTORSIGMA_ID]));
        visitor.visit(mManualX,                   static_cast<const DoubleField *>  (fields()[MANUALX_ID]));
        visitor.visit(mManualY,                   static_cast<const DoubleField *>  (fields()[MANUALY_ID]));
        visitor.visit(mManualZ,                   static_cast<const DoubleField *>  (fields()[MANUALZ_ID]));
        visitor.visit(mManualPitch,               static_cast<const DoubleField *>  (fields()[MANUALPITCH_ID]));
        visitor.visit(mManualYaw,                 static_cast<const DoubleField *>  (fields()[MANUALYAW_ID]));
        visitor.visit(mManualRoll,                static_cast<const DoubleField *>  (fields()[MANUALROLL_ID]));
        visitor.visit(mZdirX,                     static_cast<const DoubleField *>  (fields()[ZDIRX_ID]));
        visitor.visit(mZdirY,                     static_cast<const DoubleField *>  (fields()[ZDIRY_ID]));
        visitor.visit(mZdirZ,                     static_cast<const DoubleField *>  (fields()[ZDIRZ_ID]));
        visitor.visit(mAutoZ,                     static_cast<const BoolField *>    (fields()[AUTOZ_ID]));
        visitor.visit(mAutoShift,                 static_cast<const BoolField *>    (fields()[AUTOSHIFT_ID]));
        visitor.visit(mPreShift,                  static_cast<const IntField *>     (fields()[PRESHIFT_ID]));
        visitor.visit(mGuessShiftThreshold,       static_cast<const IntField *>     (fields()[GUESSSHIFTTHRESHOLD_ID]));
    }
bool RectifyParameters::autoShift () const [inline]
Definition at line 487 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mAutoShift;
    }
bool RectifyParameters::autoZ () const [inline]
Definition at line 482 of file rectifyParameters.h.
Referenced by UniversalRectifier::getZ(), and RectifyParametersControlWidget::setParameters().
    {
        return mAutoZ;
    }
double RectifyParameters::baselineLength () const [inline]
Definition at line 367 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mBaselineLength;
    }
double RectifyParameters::baselineX () const [inline]
Definition at line 402 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mBaselineX;
    }
double RectifyParameters::baselineY () const [inline]
Definition at line 407 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mBaselineY;
    }
double RectifyParameters::baselineZ () const [inline]
Definition at line 412 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mBaselineZ;
    }
static const char* corecvs::BaseReflection< RectifyParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
bool RectifyParameters::computeEssential () const [inline]
Definition at line 352 of file rectifyParameters.h.
Referenced by UniversalRectifier::ransacMethod(), UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mComputeEssential;
    }
EstimationMethodType::EstimationMethodType RectifyParameters::estimationMethod () const [inline]
Definition at line 377 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return static_cast<EstimationMethodType::EstimationMethodType>(mEstimationMethod);
    }
bool RectifyParameters::extended () const [inline]
Definition at line 337 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mExtended;
    }
static int corecvs::BaseReflection< RectifyParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< RectifyParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
double RectifyParameters::filterMinimumLength () const [inline]
Definition at line 342 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mFilterMinimumLength;
    }
double RectifyParameters::fovAngle () const [inline]
Definition at line 372 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mFovAngle;
    }
const void* RectifyParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 313 of file rectifyParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< RectifyParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
int RectifyParameters::guessShiftThreshold () const [inline]
Definition at line 497 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mGuessShiftThreshold;
    }
double RectifyParameters::hessianThreshold () const [inline]
Definition at line 322 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mHessianThreshold;
    }
double RectifyParameters::iterativeFactorSigma () const [inline]
Definition at line 432 of file rectifyParameters.h.
Referenced by UniversalRectifier::iterativeMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mIterativeFactorSigma;
    }
double RectifyParameters::iterativeInitialSigma () const [inline]
Definition at line 427 of file rectifyParameters.h.
Referenced by UniversalRectifier::iterativeMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mIterativeInitialSigma;
    }
int RectifyParameters::iterativeIterations () const [inline]
Definition at line 422 of file rectifyParameters.h.
Referenced by UniversalRectifier::iterativeMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mIterativeIterations;
    }
OptimizationMethodType::OptimizationMethodType RectifyParameters::iterativeMethod () const [inline]
Definition at line 417 of file rectifyParameters.h.
Referenced by UniversalRectifier::iterativeMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return static_cast<OptimizationMethodType::OptimizationMethodType>(mIterativeMethod);
    }
double RectifyParameters::manualPitch () const [inline]
Definition at line 452 of file rectifyParameters.h.
Referenced by UniversalRectifier::manualMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mManualPitch;
    }
double RectifyParameters::manualRoll () const [inline]
Definition at line 462 of file rectifyParameters.h.
Referenced by UniversalRectifier::manualMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mManualRoll;
    }
double RectifyParameters::manualX () const [inline]
Definition at line 437 of file rectifyParameters.h.
Referenced by UniversalRectifier::manualMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mManualX;
    }
double RectifyParameters::manualY () const [inline]
Definition at line 442 of file rectifyParameters.h.
Referenced by UniversalRectifier::manualMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mManualY;
    }
double RectifyParameters::manualYaw () const [inline]
Definition at line 457 of file rectifyParameters.h.
Referenced by UniversalRectifier::manualMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mManualYaw;
    }
double RectifyParameters::manualZ () const [inline]
Definition at line 447 of file rectifyParameters.h.
Referenced by UniversalRectifier::manualMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mManualZ;
    }
MatchingMethodType::MatchingMethodType RectifyParameters::matchingMethod () const [inline]
Definition at line 317 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return static_cast<MatchingMethodType::MatchingMethodType>(mMatchingMethod);
    }
static const char* corecvs::BaseReflection< RectifyParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< RectifyParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
bool RectifyParameters::normalise (void) const [inline]
Definition at line 382 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mNormalise;
    }
int RectifyParameters::octaveLayers () const [inline]
Definition at line 332 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mOctaveLayers;
    }
int RectifyParameters::octaves () const [inline]
Definition at line 327 of file rectifyParameters.h.
Referenced by RectifyParametersControlWidget::setParameters().
    {
        return mOctaves;
    }
int RectifyParameters::preShift () const [inline]
Definition at line 492 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mPreShift;
    }
void RectifyParameters::print () [inline]
Definition at line 824 of file rectifyParameters.h.
    {
        cout << *this;
    }
double RectifyParameters::priorFocal () const [inline]
Definition at line 357 of file rectifyParameters.h.
Referenced by UniversalRectifier::iterativeMethod(), UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mPriorFocal;
    }
double RectifyParameters::priorFocal2 () const [inline]
Definition at line 362 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mPriorFocal2;
    }
int RectifyParameters::ransacIterations () const [inline]
Definition at line 387 of file rectifyParameters.h.
Referenced by UniversalRectifier::ransacMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mRansacIterations;
    }
int RectifyParameters::ransacTestSize () const [inline]
Definition at line 392 of file rectifyParameters.h.
Referenced by UniversalRectifier::ransacMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mRansacTestSize;
    }
double RectifyParameters::ransacThreshold () const [inline]
Definition at line 397 of file rectifyParameters.h.
Referenced by UniversalRectifier::ransacMethod(), and RectifyParametersControlWidget::setParameters().
    {
        return mRansacThreshold;
    }
void RectifyParameters::setAutoShift (bool autoShift) [inline]
Definition at line 673 of file rectifyParameters.h.
    {
        mAutoShift = autoShift;
    }
void RectifyParameters::setAutoZ (bool autoZ) [inline]
Definition at line 668 of file rectifyParameters.h.
    {
        mAutoZ = autoZ;
    }
void RectifyParameters::setBaselineLength (double baselineLength) [inline]
Definition at line 553 of file rectifyParameters.h.
    {
        mBaselineLength = baselineLength;
    }
void RectifyParameters::setBaselineX (double baselineX) [inline]
Definition at line 588 of file rectifyParameters.h.
    {
        mBaselineX = baselineX;
    }
void RectifyParameters::setBaselineY (double baselineY) [inline]
Definition at line 593 of file rectifyParameters.h.
    {
        mBaselineY = baselineY;
    }
void RectifyParameters::setBaselineZ (double baselineZ) [inline]
Definition at line 598 of file rectifyParameters.h.
    {
        mBaselineZ = baselineZ;
    }
void RectifyParameters::setComputeEssential (bool computeEssential) [inline]
Definition at line 538 of file rectifyParameters.h.
    {
        mComputeEssential = computeEssential;
    }
void RectifyParameters::setEstimationMethod (EstimationMethodType::EstimationMethodType estimationMethod) [inline]
Definition at line 563 of file rectifyParameters.h.
    {
        mEstimationMethod = estimationMethod;
    }
void RectifyParameters::setExtended (bool extended) [inline]
Definition at line 523 of file rectifyParameters.h.
    {
        mExtended = extended;
    }
void RectifyParameters::setFilterMinimumLength (double filterMinimumLength) [inline]
Definition at line 528 of file rectifyParameters.h.
    {
        mFilterMinimumLength = filterMinimumLength;
    }
void RectifyParameters::setFovAngle (double fovAngle) [inline]
Definition at line 558 of file rectifyParameters.h.
    {
        mFovAngle = fovAngle;
    }
void RectifyParameters::setGuessShiftThreshold (int guessShiftThreshold) [inline]
Definition at line 683 of file rectifyParameters.h.
    {
        mGuessShiftThreshold = guessShiftThreshold;
    }
void RectifyParameters::setHessianThreshold (double hessianThreshold) [inline]
Definition at line 508 of file rectifyParameters.h.
    {
        mHessianThreshold = hessianThreshold;
    }
void RectifyParameters::setIterativeFactorSigma (double iterativeFactorSigma) [inline]
Definition at line 618 of file rectifyParameters.h.
    {
        mIterativeFactorSigma = iterativeFactorSigma;
    }
void RectifyParameters::setIterativeInitialSigma (double iterativeInitialSigma) [inline]
Definition at line 613 of file rectifyParameters.h.
    {
        mIterativeInitialSigma = iterativeInitialSigma;
    }
void RectifyParameters::setIterativeIterations (int iterativeIterations) [inline]
Definition at line 608 of file rectifyParameters.h.
    {
        mIterativeIterations = iterativeIterations;
    }
void RectifyParameters::setIterativeMethod (OptimizationMethodType::OptimizationMethodType iterativeMethod) [inline]
Definition at line 603 of file rectifyParameters.h.
    {
        mIterativeMethod = iterativeMethod;
    }
void RectifyParameters::setManualPitch (double manualPitch) [inline]
Definition at line 638 of file rectifyParameters.h.
    {
        mManualPitch = manualPitch;
    }
void RectifyParameters::setManualRoll (double manualRoll) [inline]
Definition at line 648 of file rectifyParameters.h.
    {
        mManualRoll = manualRoll;
    }
void RectifyParameters::setManualX (double manualX) [inline]
Definition at line 623 of file rectifyParameters.h.
    {
        mManualX = manualX;
    }
void RectifyParameters::setManualY (double manualY) [inline]
Definition at line 628 of file rectifyParameters.h.
    {
        mManualY = manualY;
    }
void RectifyParameters::setManualYaw (double manualYaw) [inline]
Definition at line 643 of file rectifyParameters.h.
    {
        mManualYaw = manualYaw;
    }
void RectifyParameters::setManualZ (double manualZ) [inline]
Definition at line 633 of file rectifyParameters.h.
    {
        mManualZ = manualZ;
    }
void RectifyParameters::setMatchingMethod (MatchingMethodType::MatchingMethodType matchingMethod) [inline]
Definition at line 503 of file rectifyParameters.h.
    {
        mMatchingMethod = matchingMethod;
    }
void RectifyParameters::setNormalise (bool normalise) [inline]
Definition at line 568 of file rectifyParameters.h.
    {
        mNormalise = normalise;
    }
void RectifyParameters::setOctaveLayers (int octaveLayers) [inline]
Definition at line 518 of file rectifyParameters.h.
    {
        mOctaveLayers = octaveLayers;
    }
void RectifyParameters::setOctaves (int octaves) [inline]
Definition at line 513 of file rectifyParameters.h.
    {
        mOctaves = octaves;
    }
void RectifyParameters::setPreShift (int preShift) [inline]
Definition at line 678 of file rectifyParameters.h.
    {
        mPreShift = preShift;
    }
void RectifyParameters::setPriorFocal (double priorFocal) [inline]
Definition at line 543 of file rectifyParameters.h.
    {
        mPriorFocal = priorFocal;
    }
void RectifyParameters::setPriorFocal2 (double priorFocal2) [inline]
Definition at line 548 of file rectifyParameters.h.
    {
        mPriorFocal2 = priorFocal2;
    }
void RectifyParameters::setRansacIterations (int ransacIterations) [inline]
Definition at line 573 of file rectifyParameters.h.
    {
        mRansacIterations = ransacIterations;
    }
void RectifyParameters::setRansacTestSize (int ransacTestSize) [inline]
Definition at line 578 of file rectifyParameters.h.
    {
        mRansacTestSize = ransacTestSize;
    }
void RectifyParameters::setRansacThreshold (double ransacThreshold) [inline]
Definition at line 583 of file rectifyParameters.h.
    {
        mRansacThreshold = ransacThreshold;
    }
void RectifyParameters::setUseKLT (bool useKLT) [inline]
Definition at line 533 of file rectifyParameters.h.
    {
        mUseKLT = useKLT;
    }
void RectifyParameters::setZdirX (double zdirX) [inline]
Definition at line 653 of file rectifyParameters.h.
    {
        mZdirX = zdirX;
    }
void RectifyParameters::setZdirY (double zdirY) [inline]
Definition at line 658 of file rectifyParameters.h.
    {
        mZdirY = zdirY;
    }
void RectifyParameters::setZdirZ (double zdirZ) [inline]
Definition at line 663 of file rectifyParameters.h.
    {
        mZdirZ = zdirZ;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int RectifyParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file rectifyParameters.cpp.
References AUTOSHIFT_ID, AUTOZ_ID, BASELINELENGTH_ID, BASELINEX_ID, BASELINEY_ID, BASELINEZ_ID, COMPUTEESSENTIAL_ID, ESTIMATIONMETHOD_ID, EXTENDED_ID, corecvs::BaseReflection< RectifyParameters >::fields(), FILTERMINIMUMLENGTH_ID, FOVANGLE_ID, GUESSSHIFTTHRESHOLD_ID, HESSIANTHRESHOLD_ID, ITERATIVEFACTORSIGMA_ID, ITERATIVEINITIALSIGMA_ID, ITERATIVEITERATIONS_ID, ITERATIVEMETHOD_ID, MANUALPITCH_ID, MANUALROLL_ID, MANUALX_ID, MANUALY_ID, MANUALYAW_ID, MANUALZ_ID, MATCHINGMETHOD_ID, mAutoShift, mAutoZ, mBaselineLength, mBaselineX, mBaselineY, mBaselineZ, mComputeEssential, mEstimationMethod, mExtended, mFilterMinimumLength, mFovAngle, mGuessShiftThreshold, mHessianThreshold, mIterativeFactorSigma, mIterativeInitialSigma, mIterativeIterations, mIterativeMethod, mManualPitch, mManualRoll, mManualX, mManualY, mManualYaw, mManualZ, mMatchingMethod, mNormalise, mOctaveLayers, mOctaves, mPreShift, mPriorFocal, mPriorFocal2, mRansacIterations, mRansacTestSize, mRansacThreshold, mUseKLT, mZdirX, mZdirY, mZdirZ, corecvs::BaseReflection< RectifyParameters >::naming(), NORMALISE_ID, OCTAVELAYERS_ID, OCTAVES_ID, PRESHIFT_ID, PRIORFOCAL2_ID, PRIORFOCAL_ID, RANSACITERATIONS_ID, RANSACTESTSIZE_ID, RANSACTHRESHOLD_ID, USEKLT_ID, ZDIRX_ID, ZDIRY_ID, and ZDIRZ_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Rectify Parameters",
        "osd parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          RectifyParameters::MATCHINGMETHOD_ID,
          offsetof(RectifyParameters, mMatchingMethod),
          1,
          "matchingMethod",
          "matchingMethod",
          "matchingMethod",
           NULL
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::HESSIANTHRESHOLD_ID,
          offsetof(RectifyParameters, mHessianThreshold),
          400,
          "hessianThreshold",
          "hessianThreshold",
          "hessianThreshold"
        )
    );
    fields().push_back(
        new IntField
        (
          RectifyParameters::OCTAVES_ID,
          offsetof(RectifyParameters, mOctaves),
          3,
          "octaves",
          "octaves",
          "octaves"
        )
    );
    fields().push_back(
        new IntField
        (
          RectifyParameters::OCTAVELAYERS_ID,
          offsetof(RectifyParameters, mOctaveLayers),
          4,
          "octaveLayers",
          "octaveLayers",
          "octaveLayers"
        )
    );
    fields().push_back(
        new BoolField
        (
          RectifyParameters::EXTENDED_ID,
          offsetof(RectifyParameters, mExtended),
          false,
          "extended",
          "extended",
          "extended"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::FILTERMINIMUMLENGTH_ID,
          offsetof(RectifyParameters, mFilterMinimumLength),
          3,
          "filterMinimumLength",
          "filterMinimumLength",
          "filterMinimumLength"
        )
    );
    fields().push_back(
        new BoolField
        (
          RectifyParameters::USEKLT_ID,
          offsetof(RectifyParameters, mUseKLT),
          false,
          "useKLT",
          "useKLT",
          "useKLT"
        )
    );
    fields().push_back(
        new BoolField
        (
          RectifyParameters::COMPUTEESSENTIAL_ID,
          offsetof(RectifyParameters, mComputeEssential),
          true,
          "computeEssential",
          "computeEssential",
          "computeEssential"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::PRIORFOCAL_ID,
          offsetof(RectifyParameters, mPriorFocal),
          820.427,
          "priorFocal",
          "priorFocal",
          "priorFocal"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::PRIORFOCAL2_ID,
          offsetof(RectifyParameters, mPriorFocal2),
          820.427,
          "priorFocal2",
          "priorFocal2",
          "priorFocal2"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::BASELINELENGTH_ID,
          offsetof(RectifyParameters, mBaselineLength),
          60,
          "baselineLength",
          "baselineLength",
          "baselineLength"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::FOVANGLE_ID,
          offsetof(RectifyParameters, mFovAngle),
          60,
          "fovAngle",
          "fovAngle",
          "fovAngle"
        )
    );
    fields().push_back(
        new EnumField
        (
          RectifyParameters::ESTIMATIONMETHOD_ID,
          offsetof(RectifyParameters, mEstimationMethod),
          1,
          "estimationMethod",
          "estimationMethod",
          "estimationMethod",
           NULL
        )
    );
    fields().push_back(
        new BoolField
        (
          RectifyParameters::NORMALISE_ID,
          offsetof(RectifyParameters, mNormalise),
          true,
          "normalise",
          "normalise",
          "normalise"
        )
    );
    fields().push_back(
        new IntField
        (
          RectifyParameters::RANSACITERATIONS_ID,
          offsetof(RectifyParameters, mRansacIterations),
          4000,
          "ransacIterations",
          "ransacIterations",
          "ransacIterations"
        )
    );
    fields().push_back(
        new IntField
        (
          RectifyParameters::RANSACTESTSIZE_ID,
          offsetof(RectifyParameters, mRansacTestSize),
          15,
          "ransacTestSize",
          "ransacTestSize",
          "ransacTestSize"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::RANSACTHRESHOLD_ID,
          offsetof(RectifyParameters, mRansacThreshold),
          1,
          "ransacThreshold",
          "ransacThreshold",
          "ransacThreshold"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::BASELINEX_ID,
          offsetof(RectifyParameters, mBaselineX),
          1,
          "baselineX",
          "baselineX",
          "baselineX"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::BASELINEY_ID,
          offsetof(RectifyParameters, mBaselineY),
          0,
          "baselineY",
          "baselineY",
          "baselineY"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::BASELINEZ_ID,
          offsetof(RectifyParameters, mBaselineZ),
          0,
          "baselineZ",
          "baselineZ",
          "baselineZ"
        )
    );
    fields().push_back(
        new EnumField
        (
          RectifyParameters::ITERATIVEMETHOD_ID,
          offsetof(RectifyParameters, mIterativeMethod),
          2,
          "iterativeMethod",
          "iterativeMethod",
          "iterativeMethod",
           NULL
        )
    );
    fields().push_back(
        new IntField
        (
          RectifyParameters::ITERATIVEITERATIONS_ID,
          offsetof(RectifyParameters, mIterativeIterations),
          30,
          "iterativeIterations",
          "iterativeIterations",
          "iterativeIterations"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::ITERATIVEINITIALSIGMA_ID,
          offsetof(RectifyParameters, mIterativeInitialSigma),
          30,
          "iterativeInitialSigma",
          "iterativeInitialSigma",
          "iterativeInitialSigma"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::ITERATIVEFACTORSIGMA_ID,
          offsetof(RectifyParameters, mIterativeFactorSigma),
          0.95,
          "iterativeFactorSigma",
          "iterativeFactorSigma",
          "iterativeFactorSigma"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::MANUALX_ID,
          offsetof(RectifyParameters, mManualX),
          1,
          "manualX",
          "manualX",
          "manualX"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::MANUALY_ID,
          offsetof(RectifyParameters, mManualY),
          0,
          "manualY",
          "manualY",
          "manualY"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::MANUALZ_ID,
          offsetof(RectifyParameters, mManualZ),
          0,
          "manualZ",
          "manualZ",
          "manualZ"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::MANUALPITCH_ID,
          offsetof(RectifyParameters, mManualPitch),
          0,
          "manualPitch",
          "manualPitch",
          "manualPitch"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::MANUALYAW_ID,
          offsetof(RectifyParameters, mManualYaw),
          0,
          "manualYaw",
          "manualYaw",
          "manualYaw"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::MANUALROLL_ID,
          offsetof(RectifyParameters, mManualRoll),
          0,
          "manualRoll",
          "manualRoll",
          "manualRoll"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::ZDIRX_ID,
          offsetof(RectifyParameters, mZdirX),
          1,
          "zdirX",
          "zdirX",
          "zdirX"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::ZDIRY_ID,
          offsetof(RectifyParameters, mZdirY),
          0,
          "zdirY",
          "zdirY",
          "zdirY"
        )
    );
    fields().push_back(
        new DoubleField
        (
          RectifyParameters::ZDIRZ_ID,
          offsetof(RectifyParameters, mZdirZ),
          0,
          "zdirZ",
          "zdirZ",
          "zdirZ"
        )
    );
    fields().push_back(
        new BoolField
        (
          RectifyParameters::AUTOZ_ID,
          offsetof(RectifyParameters, mAutoZ),
          true,
          "autoZ",
          "autoZ",
          "autoZ"
        )
    );
    fields().push_back(
        new BoolField
        (
          RectifyParameters::AUTOSHIFT_ID,
          offsetof(RectifyParameters, mAutoShift),
          true,
          "autoShift",
          "autoShift",
          "autoShift"
        )
    );
    fields().push_back(
        new IntField
        (
          RectifyParameters::PRESHIFT_ID,
          offsetof(RectifyParameters, mPreShift),
          0,
          "preShift",
          "preShift",
          "preShift"
        )
    );
    fields().push_back(
        new IntField
        (
          RectifyParameters::GUESSSHIFTTHRESHOLD_ID,
          offsetof(RectifyParameters, mGuessShiftThreshold),
          0,
          "guessShiftThreshold",
          "guessShiftThreshold",
          "guessShiftThreshold"
        )
    );
   return 0;
}
bool RectifyParameters::useKLT () const [inline]
Definition at line 347 of file rectifyParameters.h.
Referenced by UniversalRectifier::recalculate(), and RectifyParametersControlWidget::setParameters().
    {
        return mUseKLT;
    }
double RectifyParameters::zdirX () const [inline]
Definition at line 467 of file rectifyParameters.h.
Referenced by UniversalRectifier::getZ(), and RectifyParametersControlWidget::setParameters().
    {
        return mZdirX;
    }
double RectifyParameters::zdirY () const [inline]
Definition at line 472 of file rectifyParameters.h.
Referenced by UniversalRectifier::getZ(), and RectifyParametersControlWidget::setParameters().
    {
        return mZdirY;
    }
double RectifyParameters::zdirZ () const [inline]
Definition at line 477 of file rectifyParameters.h.
Referenced by UniversalRectifier::getZ(), and RectifyParametersControlWidget::setParameters().
    {
        return mZdirZ;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, RectifyParameters & toSave) [friend]
Definition at line 817 of file rectifyParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< RectifyParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
bool RectifyParameters::mAutoShift
autoShift autoShift
Definition at line 295 of file rectifyParameters.h.
Referenced by staticInit().
bool RectifyParameters::mAutoZ
autoZ autoZ
Definition at line 289 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mBaselineLength
baselineLength baselineLength
Definition at line 151 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mBaselineX
baselineX baselineX
Definition at line 193 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mBaselineY
baselineY baselineY
Definition at line 199 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mBaselineZ
baselineZ baselineZ
Definition at line 205 of file rectifyParameters.h.
Referenced by staticInit().
bool RectifyParameters::mComputeEssential
computeEssential computeEssential
Definition at line 133 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mEstimationMethod
estimationMethod estimationMethod
Definition at line 163 of file rectifyParameters.h.
Referenced by staticInit().
bool RectifyParameters::mExtended
extended extended
Definition at line 115 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mFilterMinimumLength
filterMinimumLength filterMinimumLength
Definition at line 121 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mFovAngle
fovAngle fovAngle
Definition at line 157 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mGuessShiftThreshold
guessShiftThreshold guessShiftThreshold
Definition at line 307 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mHessianThreshold
hessianThreshold hessianThreshold
Definition at line 97 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mIterativeFactorSigma
iterativeFactorSigma iterativeFactorSigma
Definition at line 229 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mIterativeInitialSigma
iterativeInitialSigma iterativeInitialSigma
Definition at line 223 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mIterativeIterations
iterativeIterations iterativeIterations
Definition at line 217 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mIterativeMethod
iterativeMethod iterativeMethod
Definition at line 211 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mManualPitch
manualPitch manualPitch
Definition at line 253 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mManualRoll
manualRoll manualRoll
Definition at line 265 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mManualX
manualX manualX
Definition at line 235 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mManualY
manualY manualY
Definition at line 241 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mManualYaw
manualYaw manualYaw
Definition at line 259 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mManualZ
manualZ manualZ
Definition at line 247 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mMatchingMethod
Section with variables.
matchingMethod matchingMethod
Definition at line 91 of file rectifyParameters.h.
Referenced by staticInit().
bool RectifyParameters::mNormalise
normalise normalise
Definition at line 169 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mOctaveLayers
octaveLayers octaveLayers
Definition at line 109 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mOctaves
octaves octaves
Definition at line 103 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mPreShift
preShift preShift
Definition at line 301 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mPriorFocal
priorFocal priorFocal
Definition at line 139 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mPriorFocal2
priorFocal2 priorFocal2
Definition at line 145 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mRansacIterations
ransacIterations ransacIterations
Definition at line 175 of file rectifyParameters.h.
Referenced by staticInit().
int RectifyParameters::mRansacTestSize
ransacTestSize ransacTestSize
Definition at line 181 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mRansacThreshold
ransacThreshold ransacThreshold
Definition at line 187 of file rectifyParameters.h.
Referenced by staticInit().
bool RectifyParameters::mUseKLT
useKLT useKLT
Definition at line 127 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mZdirX
zdirX zdirX
Definition at line 271 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mZdirY
zdirY zdirY
Definition at line 277 of file rectifyParameters.h.
Referenced by staticInit().
double RectifyParameters::mZdirZ
zdirZ zdirZ
Definition at line 283 of file rectifyParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< RectifyParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
utils/rectifier/rectifyParameters.h
utils/rectifier/rectifyParameters.cpp