DeepView: corecvs::AbstractMipmapPyramid< BufferType > Class Template Reference
corecvs::AbstractMipmapPyramid< BufferType > Class Template Reference
Template class that holds the pyramid of the reduced size buffers.
#include <mipmapPyramid.h>
Public Member Functions
AbstractMipmapPyramid (BufferType *input, int _levelNumber)
AbstractMipmapPyramid (BufferType *input, int _levelNumber, double factor)
Static Public Member Functions
static BufferType * downsample (BufferType *input)
static BufferType * downsample (BufferType *input, double factor)
This is designed for small factors of about 1.1-1.6.
Public Attributes
int levelNumber
vector< BufferType * > levels
Detailed Description
template<typename BufferType>
class corecvs::AbstractMipmapPyramid< BufferType >
Template class that holds the pyramid of the reduced size buffers.
For more details please see - http://en.wikipedia.org/wiki/Mipmap
Definition at line 29 of file mipmapPyramid.h.
Constructor & Destructor Documentation
template<typename BufferType> corecvs::AbstractMipmapPyramid< BufferType >::AbstractMipmapPyramid (BufferType * input, int _levelNumber) [inline]
Definition at line 35 of file mipmapPyramid.h.
References corecvs::AbstractMipmapPyramid< BufferType >::downsample(), corecvs::AbstractMipmapPyramid< BufferType >::levelNumber, and corecvs::AbstractMipmapPyramid< BufferType >::levels.
    {
        levelNumber = _levelNumber;
        levels.resize(levelNumber);
        levels[0] = new BufferType(input);
        for (int i = 1; i < _levelNumber; i++)
        {
            levels[i] = downsample(levels[i-1]);
        }
    }
template<typename BufferType> corecvs::AbstractMipmapPyramid< BufferType >::AbstractMipmapPyramid (BufferType * input, int _levelNumber, double factor) [inline]
Definition at line 46 of file mipmapPyramid.h.
References corecvs::AbstractMipmapPyramid< BufferType >::downsample(), corecvs::AbstractMipmapPyramid< BufferType >::levelNumber, and corecvs::AbstractMipmapPyramid< BufferType >::levels.
    {
        levelNumber = _levelNumber;
        levels.resize(levelNumber);
        levels[0] = new BufferType(input);
        for (int i = 1; i < _levelNumber; i++)
        {
            levels[i] = downsample(levels[i-1], factor);
        }
    }
Member Function Documentation
template<typename BufferType> static BufferType* corecvs::AbstractMipmapPyramid< BufferType >::downsample (BufferType * input) [inline, static]
Definition at line 58 of file mipmapPyramid.h.
References corecvs::Gaussian3x3int::instance, and corecvs::AbstractKernel< ElementType, IndexType >::multiplyAtPoint().
Referenced by corecvs::AbstractMipmapPyramid< BufferType >::AbstractMipmapPyramid().
    {
        BufferType* toReturn = new BufferType(input->h / 2, input->w / 2);
        for (int32_t i = 0; i < toReturn->h; i++)
        {
            for (int32_t j = 0; j < toReturn->w; j++)
            {
                toReturn->element(i,j) = Gaussian3x3int::instance->multiplyAtPoint(input, 2*i, 2*j);
            }
        }
        return toReturn;
    }
template<typename BufferType> static BufferType* corecvs::AbstractMipmapPyramid< BufferType >::downsample (BufferType * input, double factor) [inline, static]
This is designed for small factors of about 1.1-1.6.
Definition at line 76 of file mipmapPyramid.h.
    {
        BufferType* toReturn = new BufferType(input->h / factor, input->w / factor, false);
        for (int32_t i = 0; i < toReturn->h; i++)
        {
            for (int32_t j = 0; j < toReturn->w; j++)
            {
                //toReturn->element(i,j) = Gaussian3x3int::instance->multiplyAtPoint(input, (int)(factor*i), (int)(factor*j));
                toReturn->element(i,j) = input->elementBl(factor * i, factor * j);
            }
        }
        return toReturn;
    }
Member Data Documentation
template<typename BufferType> int corecvs::AbstractMipmapPyramid< BufferType >::levelNumber
Definition at line 32 of file mipmapPyramid.h.
Referenced by corecvs::AbstractMipmapPyramid< BufferType >::AbstractMipmapPyramid().
template<typename BufferType> vector<BufferType *> corecvs::AbstractMipmapPyramid< BufferType >::levels
Definition at line 33 of file mipmapPyramid.h.
Referenced by corecvs::AbstractMipmapPyramid< BufferType >::AbstractMipmapPyramid(), and corecvs::KLTGenerator< InterpolationType >::calculateHierarchicalKLTFlow().
The documentation for this class was generated from the following file:
core/buffers/mipmapPyramid.h