DeepView: HistogramDepthDialog Class Reference
HistogramDepthDialog Class Reference
#include <histogramdepthdialog.h>
Public Slots
virtual void setDepthesSlot (QSharedPointer< QMap< int, int > > depthData)
Signals
void histogramClicked (const int value)
void preZoneChanged (int zone)
void zoneStartChanged (int zone)
void zoneEndChanged (int zone)
void clickZoneEndChanged (int zone)
Public Member Functions
HistogramDepthDialog (QWidget *parent=0)
~HistogramDepthDialog ()
QMap< int, double > getDepthMap () const
void setZones (int zoneStart, int zoneEnd, int preZoneStart, int clickZoneEnd)
Protected Member Functions
void changeEvent (QEvent *e)
void redrawHistogram ()
Private Slots
virtual void histogramClickSlot (const int value)
void on_clearAllDepthesPushButton_clicked ()
void on_acceptDepthPushButton_clicked ()
void on_setPreZonePushButton_toggled (bool checked)
void on_setZoneStartPushButton_toggled (bool checked)
void on_setZoneEndPushButton_toggled (bool checked)
void on_setClickZoneEndPushButton_toggled (bool checked)
void on_nonePushButton_toggled (bool checked)
void on_zoomInPushButton_clicked ()
void on_zoomOutPushButton_clicked ()
Private Attributes
Ui::HistogramDepthDialog * mUi
QSharedPointer< QMap< int, int > > mDepthData
QMap< int, double > mDepthMap
Histogram * mCoreHistogram
Detailed Description
Definition at line 15 of file histogramdepthdialog.h.
Constructor & Destructor Documentation
HistogramDepthDialog::HistogramDepthDialog (QWidget * parent = 0)
Definition at line 12 of file histogramdepthdialog.cpp.
References clickZoneEndChanged(), histogramClickSlot(), mUi, preZoneChanged(), redrawHistogram(), zoneEndChanged(), and zoneStartChanged().
                                                          :
    QDialog(parent),
    mUi(new Ui::HistogramDepthDialog),
    mCoreHistogram(NULL)
{
    mUi->setupUi(this);
    //qDebug() << "HistogramDepthDialog::HistogramDepthDialog( _ ) called";
    redrawHistogram();
    connect(mUi->corePlot, SIGNAL(histogramBarClicked(int)), this, SLOT(histogramClickSlot(int)));
    connect(mUi->corePlot, SIGNAL(preZoneChanged(int)), this, SIGNAL(preZoneChanged(int)));
    connect(mUi->corePlot, SIGNAL(zoneStartChanged(int)), this, SIGNAL(zoneStartChanged(int)));
    connect(mUi->corePlot, SIGNAL(zoneEndChanged(int)), this, SIGNAL(zoneEndChanged(int)));
    connect(mUi->corePlot, SIGNAL(clickZoneEndChanged(int)), this, SIGNAL(clickZoneEndChanged(int)));
}
HistogramDepthDialog::~HistogramDepthDialog ()
Definition at line 76 of file histogramdepthdialog.cpp.
References mCoreHistogram, and mUi.
{
    delete_safe(mCoreHistogram);
    delete_safe(mUi);
}
Member Function Documentation
void HistogramDepthDialog::changeEvent (QEvent * e) [protected]
Definition at line 82 of file histogramdepthdialog.cpp.
References mUi.
{
    QDialog::changeEvent(e);
    switch (e->type()) {
    case QEvent::LanguageChange:
        mUi->retranslateUi(this);
        break;
    default:
        break;
    }
}
void HistogramDepthDialog::clickZoneEndChanged (int zone) [signal]
Referenced by HistogramDepthDialog().
QMap< int, double > HistogramDepthDialog::getDepthMap () const
Definition at line 109 of file histogramdepthdialog.cpp.
References mDepthMap.
{
    return mDepthMap;
}
void HistogramDepthDialog::histogramClicked (const int value) [signal]
Referenced by histogramClickSlot().
void HistogramDepthDialog::histogramClickSlot (const int value) [private, virtual, slot]
Definition at line 64 of file histogramdepthdialog.cpp.
References histogramClicked(), mDepthData, and mUi.
Referenced by HistogramDepthDialog().
{
    if (mDepthData)
    {
        mUi->label->setText("Selected depth: " + QString::number(value)
                       + ". Number of points: " + QString::number(mDepthData.data()->operator [] (value)));
        mUi->depthSpinBox->setValue(value);
        //ui->realDepthSpinBox->setValue(0);
        emit(histogramClicked(value));
    }
}
void HistogramDepthDialog::on_acceptDepthPushButton_clicked () [private, slot]
Definition at line 94 of file histogramdepthdialog.cpp.
References mDepthData, mDepthMap, and mUi.
{
    if (mDepthData.isNull())
        return;
    mDepthMap[mUi->depthSpinBox->value()] = mUi->realDepthSpinBox->value();
    mUi->learnedEntriesLabel2->setText(QString::number(mDepthMap.count()));
}
void HistogramDepthDialog::on_clearAllDepthesPushButton_clicked () [private, slot]
Definition at line 103 of file histogramdepthdialog.cpp.
References mDepthMap, and mUi.
{
    mDepthMap.clear();
    mUi->learnedEntriesLabel2->setText("0");
}
void HistogramDepthDialog::on_nonePushButton_toggled (bool checked) [private, slot]
Definition at line 145 of file histogramdepthdialog.cpp.
References mUi, and HistogramWidget::none.
{
    if (checked)
        mUi->corePlot->setZoneSettingState(HistogramWidget::none);
}
void HistogramDepthDialog::on_setClickZoneEndPushButton_toggled (bool checked) [private, slot]
Definition at line 139 of file histogramdepthdialog.cpp.
References HistogramWidget::clickEnd, and mUi.
{
    if (checked)
        mUi->corePlot->setZoneSettingState(HistogramWidget::clickEnd);
}
void HistogramDepthDialog::on_setPreZonePushButton_toggled (bool checked) [private, slot]
Definition at line 121 of file histogramdepthdialog.cpp.
References mUi, and HistogramWidget::preZone.
{
    if (checked)
        mUi->corePlot->setZoneSettingState(HistogramWidget::preZone);
}
void HistogramDepthDialog::on_setZoneEndPushButton_toggled (bool checked) [private, slot]
Definition at line 133 of file histogramdepthdialog.cpp.
References mUi, and HistogramWidget::zoneEnd.
{
    if (checked)
        mUi->corePlot->setZoneSettingState(HistogramWidget::zoneEnd);
}
void HistogramDepthDialog::on_setZoneStartPushButton_toggled (bool checked) [private, slot]
Definition at line 127 of file histogramdepthdialog.cpp.
References mUi, and HistogramWidget::zoneStart.
{
    if (checked)
        mUi->corePlot->setZoneSettingState(HistogramWidget::zoneStart);
}
void HistogramDepthDialog::on_zoomInPushButton_clicked () [private, slot]
Definition at line 151 of file histogramdepthdialog.cpp.
References mUi.
{
    mUi->corePlot->zoomIn();
}
void HistogramDepthDialog::on_zoomOutPushButton_clicked () [private, slot]
Definition at line 156 of file histogramdepthdialog.cpp.
References mUi.
{
    mUi->corePlot->zoomOut();
}
void HistogramDepthDialog::preZoneChanged (int zone) [signal]
Referenced by HistogramDepthDialog().
void HistogramDepthDialog::redrawHistogram () [protected]
Definition at line 29 of file histogramdepthdialog.cpp.
References mCoreHistogram, and mUi.
Referenced by HistogramDepthDialog(), and setDepthesSlot().
{
//    qDebug() << "HistogramDepthDialog::redrawHistogram(): " << mCoreHistogram;
    mUi->corePlot->show();
    // Use signal here to serialize
    if (mCoreHistogram != NULL)
    {
        mUi->corePlot->notifyHistogramChange(mCoreHistogram, true);
    }
}
void HistogramDepthDialog::setDepthesSlot (QSharedPointer< QMap< int, int > > depthData) [virtual, slot]
Definition at line 41 of file histogramdepthdialog.cpp.
References histogramMargin, corecvs::Histogram::max, mCoreHistogram, mDepthData, corecvs::Histogram::min, redrawHistogram(), and corecvs::Histogram::set().
{
    if (depthData.isNull() || depthData->count() == 0) {
        return;
    }
//    qDebug("HistogramDepthDialog::setDepthesSlot() called");
    mDepthData = depthData;
    QMap<int, int> &qMap = *mDepthData.data();
    Histogram *histogramToDelete = mCoreHistogram;
    int minX = (qMap.begin()    ).key();
    int maxX = (qMap.end()   - 1).key();
    mCoreHistogram = new Histogram(-histogramMargin, histogramMargin);
    for (int i = max(minX, mCoreHistogram->min); i < min(maxX, mCoreHistogram->max); i++)
    {
        mCoreHistogram->set(i, qMap[i]);
    }
    delete_safe(histogramToDelete);
    redrawHistogram();
}
void HistogramDepthDialog::setZones (int zoneStart, int zoneEnd, int preZoneStart, int clickZoneEnd)
Definition at line 114 of file histogramdepthdialog.cpp.
References mUi.
{
    if (preZoneStart > zoneStart || zoneStart > zoneEnd || zoneEnd > clickZoneEnd)
        return;
    mUi->corePlot->setZones(zoneStart, zoneEnd, preZoneStart, clickZoneEnd);
}
void HistogramDepthDialog::zoneEndChanged (int zone) [signal]
Referenced by HistogramDepthDialog().
void HistogramDepthDialog::zoneStartChanged (int zone) [signal]
Referenced by HistogramDepthDialog().
Member Data Documentation
Histogram* HistogramDepthDialog::mCoreHistogram [private]
Definition at line 44 of file histogramdepthdialog.h.
Referenced by redrawHistogram(), setDepthesSlot(), and ~HistogramDepthDialog().
QSharedPointer<QMap<int, int> > HistogramDepthDialog::mDepthData [private]
Definition at line 41 of file histogramdepthdialog.h.
Referenced by histogramClickSlot(), on_acceptDepthPushButton_clicked(), and setDepthesSlot().
QMap<int, double> HistogramDepthDialog::mDepthMap [private]
Definition at line 42 of file histogramdepthdialog.h.
Referenced by getDepthMap(), on_acceptDepthPushButton_clicked(), and on_clearAllDepthesPushButton_clicked().
Ui::HistogramDepthDialog* HistogramDepthDialog::mUi [private]
Definition at line 40 of file histogramdepthdialog.h.
Referenced by changeEvent(), histogramClickSlot(), HistogramDepthDialog(), on_acceptDepthPushButton_clicked(), on_clearAllDepthesPushButton_clicked(), on_nonePushButton_toggled(), on_setClickZoneEndPushButton_toggled(), on_setPreZonePushButton_toggled(), on_setZoneEndPushButton_toggled(), on_setZoneStartPushButton_toggled(), on_zoomInPushButton_clicked(), on_zoomOutPushButton_clicked(), redrawHistogram(), setZones(), and ~HistogramDepthDialog().
The documentation for this class was generated from the following files:
utils/uis/histogramdepthdialog.h
utils/uis/histogramdepthdialog.cpp