DeepView: InputFilterParameters Class Reference
InputFilterParameters Class Reference
Input Filter Parameters Input Filter Parameters.
#include <inputFilterParameters.h>
Public Types
enum FieldId { INPUT_TYPE_ID, INPUT_FILTER_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
InputType::InputType inputType () const
void setInputType (InputType::InputType inputType)
template<class VisitorType >
void accept (VisitorType &visitor)
InputFilterParameters ()
InputFilterParameters (InputType::InputType inputType)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mInputType
Section with variables.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, InputFilterParameters &toSave)
Detailed Description
Input Filter Parameters Input Filter Parameters.
Definition at line 39 of file inputFilterParameters.h.
Member Enumeration Documentation
enum InputFilterParameters::FieldId
Enumerator:
INPUT_TYPE_ID
INPUT_FILTER_PARAMETERS_FIELD_ID_NUM
Definition at line 42 of file inputFilterParameters.h.
                 {
        INPUT_TYPE_ID,
        INPUT_FILTER_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
InputFilterParameters::InputFilterParameters () [inline]
Definition at line 82 of file inputFilterParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
InputFilterParameters::InputFilterParameters (InputType::InputType inputType) [inline]
Definition at line 88 of file inputFilterParameters.h.
    {
        mInputType = inputType;
    }
Member Function Documentation
template<class VisitorType > void InputFilterParameters::accept (VisitorType & visitor) [inline]
Definition at line 77 of file inputFilterParameters.h.
Referenced by corecvs::InputFilter::deserialize(), and corecvs::InputFilter::serialize().
    {
        visitor.visit((int &)mInputType,          static_cast<const EnumField *>    (fields()[INPUT_TYPE_ID]));
    }
static const char* corecvs::BaseReflection< InputFilterParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< InputFilterParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< InputFilterParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* InputFilterParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 59 of file inputFilterParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< InputFilterParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
InputType::InputType InputFilterParameters::inputType () const [inline]
Definition at line 63 of file inputFilterParameters.h.
Referenced by BaseCalculationThread::executeFilterGraph(), and InputFilterParametersControlWidget::setParameters().
    {
        return static_cast<InputType::InputType>(mInputType);
    }
static const char* corecvs::BaseReflection< InputFilterParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< InputFilterParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void InputFilterParameters::print () [inline]
Definition at line 102 of file inputFilterParameters.h.
    {
        cout << *this;
    }
void InputFilterParameters::setInputType (InputType::InputType inputType) [inline]
Definition at line 69 of file inputFilterParameters.h.
    {
        mInputType = inputType;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int InputFilterParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file inputFilterParameters.cpp.
References corecvs::BaseReflection< InputFilterParameters >::fields(), INPUT_TYPE_ID, mInputType, and corecvs::BaseReflection< InputFilterParameters >::naming().
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Input Filter Parameters",
        "Input Filter Parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          InputFilterParameters::INPUT_TYPE_ID,
          offsetof(InputFilterParameters, mInputType),
          0,
          "Input Type",
          "Input Type",
          "Input Type",
           NULL
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, InputFilterParameters & toSave) [friend]
Definition at line 95 of file inputFilterParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< InputFilterParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int InputFilterParameters::mInputType
Section with variables.
Input Type Input Type
Definition at line 53 of file inputFilterParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< InputFilterParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/inputFilterParameters.h
core/xml/generated/inputFilterParameters.cpp