DeepView: V4L2BufferDescriptor Class Reference
V4L2BufferDescriptor Class Reference
Buffer descriptor type is a wrapper around the Video 4 Linux v4l2_buffer structure.
#include <V4L2.h>
Public Member Functions
V4L2BufferDescriptor ()
uint64_t usecsTimeStamp ()
Public Attributes
bool isFilled
Flag that is used to tell filled buffer from not filled.
Detailed Description
Buffer descriptor type is a wrapper around the Video 4 Linux v4l2_buffer structure.
Definition at line 41 of file V4L2.h.
Constructor & Destructor Documentation
V4L2BufferDescriptor::V4L2BufferDescriptor () [inline]
Definition at line 45 of file V4L2.h.
        {
            memset(this, 0, sizeof(V4L2BufferDescriptor));
        }
Member Function Documentation
uint64_t V4L2BufferDescriptor::usecsTimeStamp () [inline]
Definition at line 50 of file V4L2.h.
Referenced by V4L2CaptureDecoupleInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), V4L2CaptureDecoupleInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
        {
            return timestamp.tv_sec * 1000000UL + timestamp.tv_usec;
        }
Member Data Documentation
bool V4L2BufferDescriptor::isFilled
Flag that is used to tell filled buffer from not filled.
Definition at line 43 of file V4L2.h.
Referenced by V4L2CaptureInterface::decodeData(), V4L2CaptureInterface::decodeDataRGB24(), V4L2CameraDescriptor::dequeue(), V4L2CameraDescriptor::enqueue(), and V4L2CaptureDecoupleInterface::getFrame().
The documentation for this class was generated from the following file:
utils/framesources/v4l2/V4L2.h