DeepView: ParametersMapperBase Class Reference
ParametersMapperBase Class Reference
#include <parametersMapperBase.h>
Public Slots
void paramsChanged ()
Signals
void baseParametersParamsChanged (QSharedPointer< BaseParameters > params)
void presentationParametersParamsChanged (QSharedPointer< PresentationParameters > params)
Public Member Functions
ParametersMapperBase ()
void setBaseParametersControlWidget (BaseParametersControlWidget *widget)
void setPresentationParametersControlWidget (PresentationParametersControlWidget *widget)
Private Attributes
BaseParametersControlWidget * mBaseParametersControlWidget
PresentationParametersControlWidget * mPresentationParametersControlWidget
Detailed Description
Definition at line 20 of file parametersMapperBase.h.
Constructor & Destructor Documentation
ParametersMapperBase::ParametersMapperBase ()
Definition at line 11 of file parametersMapperBase.cpp.
                                           :
    mBaseParametersControlWidget(NULL)
  , mPresentationParametersControlWidget(NULL)
{
    qRegisterMetaType<QSharedPointer<BaseParameters> >("QSharedPointer<BaseParameters>");
    qRegisterMetaType<QSharedPointer<PresentationParameters> >("QSharedPointer<PresentationParameters>");
}
Member Function Documentation
void ParametersMapperBase::baseParametersParamsChanged (QSharedPointer< BaseParameters > params) [signal]
Referenced by paramsChanged().
void ParametersMapperBase::paramsChanged () [slot]
Definition at line 31 of file parametersMapperBase.cpp.
References baseParametersParamsChanged(), PresentationParametersControlWidget::createParameters(), BaseParametersControlWidget::createParameters(), mBaseParametersControlWidget, mPresentationParametersControlWidget, and presentationParametersParamsChanged().
Referenced by BaseHostDialog::createCalculator(), setBaseParametersControlWidget(), and setPresentationParametersControlWidget().
{
    if (mBaseParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperBase \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit baseParametersParamsChanged(QSharedPointer<BaseParameters>(mBaseParametersControlWidget->createParameters()));
    if (mPresentationParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperBase \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit presentationParametersParamsChanged(QSharedPointer<PresentationParameters>(mPresentationParametersControlWidget->createParameters()));
}
void ParametersMapperBase::presentationParametersParamsChanged (QSharedPointer< PresentationParameters > params) [signal]
Referenced by paramsChanged().
void ParametersMapperBase::setBaseParametersControlWidget (BaseParametersControlWidget * widget)
Definition at line 19 of file parametersMapperBase.cpp.
References mBaseParametersControlWidget, and paramsChanged().
Referenced by BaseHostDialog::createCalculator().
{
    mBaseParametersControlWidget = widget;
    QObject::connect(mBaseParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}
void ParametersMapperBase::setPresentationParametersControlWidget (PresentationParametersControlWidget * widget)
Definition at line 25 of file parametersMapperBase.cpp.
References mPresentationParametersControlWidget, and paramsChanged().
Referenced by BaseHostDialog::createCalculator().
{
    mPresentationParametersControlWidget = widget;
    QObject::connect(mPresentationParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}
Member Data Documentation
BaseParametersControlWidget* ParametersMapperBase::mBaseParametersControlWidget [private]
Definition at line 37 of file parametersMapperBase.h.
Referenced by paramsChanged(), and setBaseParametersControlWidget().
PresentationParametersControlWidget* ParametersMapperBase::mPresentationParametersControlWidget [private]
Definition at line 38 of file parametersMapperBase.h.
Referenced by paramsChanged(), and setPresentationParametersControlWidget().
The documentation for this class was generated from the following files:
applications/base/parametersMapper/parametersMapperBase.h
applications/base/parametersMapper/parametersMapperBase.cpp