DeepView: Frames Class Reference
Frames Class Reference
#include <frames.h>
Public Types
enum FrameSourceId { LEFT_FRAME, DEFAULT_FRAME = LEFT_FRAME, RIGHT_FRAME, MAX_INPUTS_NUMBER }
Public Member Functions
Frames ()
~Frames ()
void fetchNewFrames (ImageCaptureInterface *input)
G12Buffer * getCurrentFrame (FrameSourceId id)
RGB24Buffer * getCurrentRgbFrame (FrameSourceId id)
void swapFrameSources (bool shouldSwap)
Swaps the frame sources so, for example, left camera becomes right, and right camera becomes left.
uint64_t timestamp () const
int64_t desyncTime () const
uint64_t startProcessTimestamp () const
Public Attributes
G12Buffer * currentFrames [MAX_INPUTS_NUMBER]
RGB24Buffer * currentRgbFrames [MAX_INPUTS_NUMBER]
int frameCount
Private Member Functions
Frames (const Frames &)
Frames & operator= (const Frames &)
Private Attributes
bool mSwapped
uint64_t mTimestamp
int64_t mDesyncTime
uint64_t mStartProcessTimestamp
Detailed Description
Definition at line 18 of file frames.h.
Member Enumeration Documentation
enum Frames::FrameSourceId
Enumerator:
LEFT_FRAME
DEFAULT_FRAME
RIGHT_FRAME
MAX_INPUTS_NUMBER
Definition at line 21 of file frames.h.
                       {
        LEFT_FRAME,
        DEFAULT_FRAME = LEFT_FRAME,
        RIGHT_FRAME,
        MAX_INPUTS_NUMBER
    };
Constructor & Destructor Documentation
Frames::Frames ()
Definition at line 20 of file frames.cpp.
References currentFrames, currentRgbFrames, DOTRACE, frameCount, and MAX_INPUTS_NUMBER.
               :
    mSwapped(false)
  , mTimestamp(0)
  , mDesyncTime(0)
  , mStartProcessTimestamp(0)
{
    DOTRACE(("Frames::Frames() called\n"));
    for (int id = 0; id < MAX_INPUTS_NUMBER; id++)
    {
        currentFrames[id]    = NULL;
        currentRgbFrames[id] = NULL;
    }
    frameCount = 0;
    /* Remove this. BaseParametersWidget should store the state*/
    /*QSettings settings("Lanit-Tercom", "CVS");
    mSwapped = settings.value("swapCameras", false).toBool();*/
}
Frames::~Frames ()
Definition at line 41 of file frames.cpp.
References currentFrames, currentRgbFrames, and MAX_INPUTS_NUMBER.
{
    for (int id = 0; id <  MAX_INPUTS_NUMBER; id++ )
    {
        delete_safe(currentFrames[id]);
        delete_safe(currentRgbFrames[id]);
    }
}
Frames::Frames (const Frames &) [private]
Member Function Documentation
int64_t Frames::desyncTime () const [inline]
Definition at line 46 of file frames.h.
References mDesyncTime.
{ return mDesyncTime; }
void Frames::fetchNewFrames (ImageCaptureInterface * input)
Definition at line 51 of file frames.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, currentFrames, currentRgbFrames, frameCount, ImageCaptureInterface::getFrame(), ImageCaptureInterface::getFrameRGB24(), ImageCaptureInterface::isRgb, LEFT_FRAME, ImageCaptureInterface::FramePair::leftTimeStamp, MAX_INPUTS_NUMBER, mDesyncTime, mSwapped, mTimestamp, ImageCaptureInterface::FramePair::rgbBufferLeft, ImageCaptureInterface::FramePair::rgbBufferRight, RIGHT_FRAME, and ImageCaptureInterface::FramePair::rightTimeStamp.
Referenced by AbstractCalculationThread::newFrameReady().
{
 //   DOTRACE(("New frames arrived: left=0x8%X right=0x8%X\n", left, right));
    ImageCaptureInterface::FramePair pair = input->isRgb ? input->getFrameRGB24() : input->getFrame();
    if (pair.bufferLeft == NULL || pair.bufferRight == NULL)
    {
        printf("Alert: We have received one or zero frames\n");
        fflush(stdout);
    }
    for (int id = 0; id <  MAX_INPUTS_NUMBER; id++ )
    {
        delete_safe(currentFrames[id]);
        delete_safe(currentRgbFrames[id]);
    }
    currentFrames[LEFT_FRAME]  = mSwapped ? pair.bufferRight : pair.bufferLeft;
    currentFrames[RIGHT_FRAME] = mSwapped ? pair.bufferLeft  : pair.bufferRight;
    if (input->isRgb)
    {
        printf("rgb\n");
        currentRgbFrames[LEFT_FRAME]  = mSwapped ? pair.rgbBufferRight : pair.rgbBufferLeft;
        currentRgbFrames[RIGHT_FRAME] = mSwapped ? pair.rgbBufferLeft  : pair.rgbBufferRight;
    }
    else
    {
        printf("no rgb\n");
        currentRgbFrames[LEFT_FRAME]  = NULL;
        currentRgbFrames[RIGHT_FRAME]  = NULL;
    }
    mTimestamp  = (pair.leftTimeStamp / 2) + (pair.rightTimeStamp / 2);
    mDesyncTime = !mSwapped ? (pair.leftTimeStamp - pair.rightTimeStamp) : (pair.rightTimeStamp - pair.leftTimeStamp);
    frameCount++;
}
G12Buffer* Frames::getCurrentFrame (FrameSourceId id) [inline]
Definition at line 37 of file frames.h.
References currentFrames.
Referenced by BaseHostDialog::distortionEstimationFinished(), BaseCalculationThread::executeFilterGraph(), BaseCalculationThread::initData(), AbstractCalculationThread::newFrameReady(), RecorderThread::processNewData(), BaseCalculationThread::recalculateCache(), BaseHostDialog::showDistortionCorrectorDialog(), and BaseCalculationThread::transformInputFrames().
{ return currentFrames[id]; }
RGB24Buffer* Frames::getCurrentRgbFrame (FrameSourceId id) [inline]
Definition at line 38 of file frames.h.
References currentRgbFrames.
{ return currentRgbFrames[id]; }
Frames& Frames::operator= (const Frames &) [private]
uint64_t Frames::startProcessTimestamp () const [inline]
Definition at line 48 of file frames.h.
References mStartProcessTimestamp.
{ return mStartProcessTimestamp; }
void Frames::swapFrameSources (bool shouldSwap)
Swaps the frame sources so, for example, left camera becomes right, and right camera becomes left.
Useful when cameras are plugged in wrong order.
Definition at line 90 of file frames.cpp.
References mSwapped.
Referenced by BaseHostDialog::swapCameras().
{
    mSwapped = shouldSwap;
    QSettings settings("cvs-camera.conf", QSettings::IniFormat);
    settings.setValue("swapCameras", mSwapped);
}
uint64_t Frames::timestamp () const [inline]
Definition at line 44 of file frames.h.
References mTimestamp.
Referenced by AbstractCalculationThread::newFrameReady().
{ return mTimestamp; }
Member Data Documentation
G12Buffer* Frames::currentFrames[MAX_INPUTS_NUMBER]
Definition at line 28 of file frames.h.
Referenced by fetchNewFrames(), Frames(), getCurrentFrame(), and ~Frames().
RGB24Buffer* Frames::currentRgbFrames[MAX_INPUTS_NUMBER]
Definition at line 29 of file frames.h.
Referenced by fetchNewFrames(), Frames(), getCurrentRgbFrame(), and ~Frames().
int Frames::frameCount
Definition at line 30 of file frames.h.
Referenced by fetchNewFrames(), and Frames().
int64_t Frames::mDesyncTime [private]
Definition at line 53 of file frames.h.
Referenced by desyncTime(), and fetchNewFrames().
uint64_t Frames::mStartProcessTimestamp [private]
Definition at line 54 of file frames.h.
Referenced by startProcessTimestamp().
bool Frames::mSwapped [private]
Definition at line 51 of file frames.h.
Referenced by fetchNewFrames(), and swapFrameSources().
uint64_t Frames::mTimestamp [private]
Definition at line 52 of file frames.h.
Referenced by fetchNewFrames(), and timestamp().
The documentation for this class was generated from the following files:
utils/frames.h
utils/frames.cpp