DeepView: StereoCameraScene Class Reference
StereoCameraScene Class Reference
#include <mesh3DScene.h>
Public Types
enum SceneType { SCENE_3D, COORDINATE_FRAME }
Public Member Functions
StereoCameraScene (const RectificationResult &stereoPair)
virtual void prepareMesh (CloudViewDialog *)
virtual void drawMyself (CloudViewDialog *dialog)
virtual ~StereoCameraScene ()
virtual void dumpPCD (ostream &)
virtual void dumpPLY (ostream &)
virtual void setParameters (void *params)
virtual
ParametersControlWidgetBase * getContolWidget ()
virtual void replaceMesh (Mesh3D *newMesh)
virtual void setMesh (Mesh3D *newMesh)
void addAOB (Vector3dd corner1, Vector3dd corner2)
void addAOB (const AxisAlignedBoxParameters &box)
void addAOB (const AxisAlignedBox3d &box)
void addSphere (Vector3dd center, double radius, int step)
virtual void commonSetup (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void commonTierdown (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void draw (CloudViewDialog *dialog)
virtual bool isComplexObject ()
Public Attributes
Draw3dParameters mParameters
Mesh3D * owned
vector< Vector3dd > vertexes
vector< Vector3d32 > faces
vector< Vector2dd > textureCoords
QString name
Scene3D * parent
SceneType type
Matrix44 transform
bool visible
Private Attributes
RectificationResult mStereoPair
CameraScene mCamera1
CameraScene mCamera2
Detailed Description
Definition at line 117 of file mesh3DScene.h.
Member Enumeration Documentation
enum Scene3D::SceneType [inherited]
Enumerator:
SCENE_3D
COORDINATE_FRAME
Definition at line 31 of file scene3D.h.
                   {
        SCENE_3D,
        COORDINATE_FRAME
    };
Constructor & Destructor Documentation
StereoCameraScene::StereoCameraScene (const RectificationResult & stereoPair)
Definition at line 295 of file mesh3DScene.cpp.
                                                                      :
    mStereoPair(result)
{
}
virtual StereoCameraScene::~StereoCameraScene () [inline, virtual]
Definition at line 127 of file mesh3DScene.h.
{};
Member Function Documentation
void corecvs::Mesh3D::addAOB (Vector3dd corner1, Vector3dd corner2) [inherited]
Definition at line 11 of file mesh3d.cpp.
References corecvs::Mesh3D::faces, corecvs::Mesh3D::textureCoords, corecvs::Mesh3D::vertexes, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by corecvs::Mesh3D::addAOB(), and CloudViewDialog::CloudViewDialog().
{
    int vectorIndex = (int)vertexes.size();
    Vector3d32 startId(vectorIndex, vectorIndex, vectorIndex);
    vertexes.push_back(Vector3dd(c1.x(), c1.y(), c1.z()));
    vertexes.push_back(Vector3dd(c2.x(), c1.y(), c1.z()));
    vertexes.push_back(Vector3dd(c2.x(), c2.y(), c1.z()));
    vertexes.push_back(Vector3dd(c1.x(), c2.y(), c1.z()));
    vertexes.push_back(Vector3dd(c1.x(), c1.y(), c2.z()));
    vertexes.push_back(Vector3dd(c2.x(), c1.y(), c2.z()));
    vertexes.push_back(Vector3dd(c2.x(), c2.y(), c2.z()));
    vertexes.push_back(Vector3dd(c1.x(), c2.y(), c2.z()));
    faces.push_back(startId + Vector3d32(0, 1, 2));
    faces.push_back(startId + Vector3d32(0, 1, 2));
    faces.push_back(startId + Vector3d32(2, 3, 0));
    faces.push_back(startId + Vector3d32(7, 6, 5));
    faces.push_back(startId + Vector3d32(5, 4, 7));
    faces.push_back(startId + Vector3d32(0, 4, 5));
    faces.push_back(startId + Vector3d32(5, 1, 0));
    faces.push_back(startId + Vector3d32(1, 5, 6));
    faces.push_back(startId + Vector3d32(6, 2, 1));
    faces.push_back(startId + Vector3d32(2, 6, 7));
    faces.push_back(startId + Vector3d32(7, 3, 2));
    faces.push_back(startId + Vector3d32(3, 7, 4));
    faces.push_back(startId + Vector3d32(4, 0, 3));
    textureCoords.push_back(Vector2dd(0.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,1.0));
    textureCoords.push_back(Vector2dd(0.0,1.0));
    textureCoords.push_back(Vector2dd(0.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,0.0));
    textureCoords.push_back(Vector2dd(1.0,1.0));
    textureCoords.push_back(Vector2dd(0.0,1.0));
}
void corecvs::Mesh3D::addAOB (const AxisAlignedBoxParameters & box) [inherited]
Definition at line 51 of file mesh3d.cpp.
References corecvs::Mesh3D::addAOB(), AxisAlignedBoxParameters::depth(), AxisAlignedBoxParameters::height(), AxisAlignedBoxParameters::width(), AxisAlignedBoxParameters::x(), AxisAlignedBoxParameters::y(), and AxisAlignedBoxParameters::z().
{
    Vector3dd measure(box.width(), box.height(), box.depth());
    Vector3dd center (box.x()    , box.y()     , box.z    ());
    addAOB(center - measure / 2.0, center + measure / 2.0);
}
void corecvs::Mesh3D::addAOB (const AxisAlignedBox3d & box) [inherited]
Definition at line 60 of file mesh3d.cpp.
References corecvs::Mesh3D::addAOB(), corecvs::AxisAlignedBox3d::high(), and corecvs::AxisAlignedBox3d::low().
{
    addAOB(box.low(), box.high());
}
void corecvs::Mesh3D::addSphere (Vector3dd center, double radius, int step) [inherited]
Definition at line 65 of file mesh3d.cpp.
References M_PI, and corecvs::Mesh3D::vertexes.
{
    int vectorIndex = (int)vertexes.size();
    Vector3d32 startId(vectorIndex, vectorIndex, vectorIndex);
    double dphy =     M_PI / (step + 1);
    double dpsi = 2 * M_PI / (step + 1);
    for (int i = 0; i < step; i++)
    {
        for (int j = 0; j < step; j++)
        {
            double phi = dphy * i;
            double psi = dpsi * j;
            double x = radius * sin(phi) * sin(psi);
            double y = radius * sin(phi) * cos(psi);
            double z = radius * cos(phi);
            vertexes.push_back(center + Vector3dd(x,y,z));
        }
    }
}
void Scene3D::commonSetup (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 102 of file scene3D.cpp.
References corecvs::Matrix44::a(), CORE_UNUSED, Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), corecvs::RectificationResult::decomposition, Draw3dTextureGen::FORCE_TEXTURE, corecvs::RectificationResult::getCameraShift(), corecvs::CameraIntrinsics::getVFov(), Scene3D::initDecalState(), corecvs::Matrix44::inverted(), Frames::LEFT_FRAME, corecvs::RectificationResult::leftCamera, CloudViewDialog::mRectificationResult, corecvs::CameraIntrinsics::resolution, Frames::RIGHT_FRAME, corecvs::EssentialDecomposition::rotation, CloudViewDialog::texture(), Draw3dParameters::textureCorrodinates(), Draw3dParameters::textureScale(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        Matrix44 textureMatrix = Matrix44::Scale(parameters->textureScale());
        glEnable(GL_TEXTURE_GEN_S);
        glEnable(GL_TEXTURE_GEN_T);
        GLint mode = GL_OBJECT_LINEAR;
        glTexGeni (GL_S, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_S, GL_OBJECT_PLANE, &textureMatrix.a(0,0));
        glTexGeni (GL_T, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_T, GL_OBJECT_PLANE, &textureMatrix.a(1,0));
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        CameraIntrinsics *intrinsics = &(dialog->mRectificationResult->rightCamera);
        double fovR = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovR, aspect);
        glActiveTexture(GL_TEXTURE1);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::RIGHT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::RIGHT_FRAME));
            } else {
                qDebug() << "No texture for right camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE );
            initDecalState(dialog, parameters, projector);
        glActiveTexture(GL_TEXTURE0);
#else
        CORE_UNUSED(dialog);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        RectificationResult *rectification = dialog->mRectificationResult.data();
        CameraIntrinsics *intrinsics = &(rectification->leftCamera);
        double fovL = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovL, aspect);
        projector = projector * (Matrix44(rectification->decomposition.rotation) * Matrix44::Shift(rectification->getCameraShift())).inverted();
        glActiveTexture(GL_TEXTURE2);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::LEFT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::LEFT_FRAME));
            } else {
                qDebug() << "No texture for left camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL );
            initDecalState(dialog, parameters, projector);
        if (parameters->decalRightCam()) {
            qDebug() << "Both cameras. Making a merge";
            glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB, GL_INTERPOLATE);   //Interpolate RGB with RGB
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB, GL_SRC_COLOR);
            //------------------------
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_ALPHA, GL_INTERPOLATE);   //Interpolate ALPHA with ALPHA
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_ALPHA, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_ALPHA, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_ALPHA, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_ALPHA, GL_SRC_ALPHA);
            //------------------------
            float mycolor[4] = {0.5, 0.5, 0.5, 0.5};
            glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor);
        }
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::commonTierdown (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 202 of file scene3D.cpp.
References Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), Draw3dTextureGen::FORCE_TEXTURE, and Draw3dParameters::textureCorrodinates().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        glDisable(GL_TEXTURE_GEN_S);
        glDisable(GL_TEXTURE_GEN_T);
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE1);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE2);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::draw (CloudViewDialog * dialog) [virtual, inherited]
Definition at line 19 of file scene3D.cpp.
References Scene3D::drawMyself(), OpenGLTools::glMultMatrixMatrix44(), Scene3D::transform, and Scene3D::visible.
{
    if (!visible) {
//        qDebug() << name << "(" << ((void *)this) << ")" << " is invisible";
        return;
    }
//    qDebug() << name << "(" << ((void *)this) << ")" << " is drawn";
    glMatrixMode(GL_MODELVIEW);
    glPushMatrix();
      OpenGLTools::glMultMatrixMatrix44(transform);
      this->drawMyself(dialog);
    glPopMatrix();
}
void StereoCameraScene::drawMyself (CloudViewDialog * dialog) [virtual]
Reimplemented from Mesh3DScene.
Definition at line 308 of file mesh3DScene.cpp.
References corecvs::RectificationResult::decomposition, corecvs::AbstractPainter< TargetBuffer >::drawFormatVector(), CameraScene::drawMyself(), corecvs::RectificationResult::getCameraShift(), corecvs::CameraIntrinsics::getHFov(), corecvs::CameraIntrinsics::getVFov(), OpenGLTools::glMultMatrixMatrix33(), OpenGLTools::glTranslateVector3dd(), corecvs::RectificationResult::leftCamera, mCamera1, mCamera2, mStereoPair, corecvs::radToDeg(), corecvs::RectificationResult::rightCamera, corecvs::EssentialDecomposition::rotation, Draw3dCameraParameters::setColor(), Draw3dCameraParameters::setFovH(), Draw3dCameraParameters::setFovV(), and CameraScene::setParameters().
{
    glMatrixMode(GL_MODELVIEW);
    Draw3dCameraParameters camParams;
    camParams.setColor(RgbColorParameters(255,20,20));
    camParams.setFovH(radToDeg(mStereoPair.rightCamera.getHFov()));
    camParams.setFovV(radToDeg(mStereoPair.rightCamera.getVFov()));
    mCamera1.setParameters(&camParams);
    mCamera1.drawMyself(dialog);
    OpenGLTools::GLWrapper wrapper;
    GLPainter painter(&wrapper);
    glPushMatrix();
    glTranslated(-20, -30, 0);
    glScaled(0.5,0.5,0.5);
    painter.drawFormatVector(0, 0, RGBColor(255,20,20), 1, "Right");
    glPopMatrix();
    glPushMatrix();
    OpenGLTools::glTranslateVector3dd(mStereoPair.getCameraShift());
    OpenGLTools::glMultMatrixMatrix33(mStereoPair.decomposition.rotation);
    camParams.setColor(RgbColorParameters(20,20,200));
    camParams.setFovH(radToDeg(mStereoPair.leftCamera.getHFov()));
    camParams.setFovV(radToDeg(mStereoPair.leftCamera.getVFov()));
    mCamera2.setParameters(&camParams);
    mCamera2.drawMyself(dialog);
    glTranslated(-20, -30, 0);
    glScaled(0.5,0.5,0.5);
    painter.drawFormatVector(0, 0, RGBColor(20,20,200), 1, "Left");
    glPopMatrix();
}
virtual void Mesh3DScene::dumpPCD (ostream &) [inline, virtual, inherited]
Reimplemented from Scene3D.
Definition at line 32 of file mesh3DScene.h.
{}
virtual void Mesh3DScene::dumpPLY (ostream &) [inline, virtual, inherited]
Reimplemented from Scene3D.
Definition at line 33 of file mesh3DScene.h.
{}
virtual ParametersControlWidgetBase* Mesh3DScene::getContolWidget () [inline, virtual, inherited]
Reimplemented from Scene3D.
Reimplemented in CameraScene.
Definition at line 40 of file mesh3DScene.h.
References Mesh3DScene::mParameters, and Draw3dParametersControlWidget::setParameters().
    {
        Draw3dParametersControlWidget *result = new Draw3dParametersControlWidget();
        result->setParameters(mParameters);
        return result;
    };
virtual bool Scene3D::isComplexObject () [inline, virtual, inherited]
Definition at line 64 of file scene3D.h.
References Scene3D::COORDINATE_FRAME, and Scene3D::type.
    {
        return (type == COORDINATE_FRAME);
    }
void StereoCameraScene::prepareMesh (CloudViewDialog * dialog) [virtual]
Reimplemented from Mesh3DScene.
Definition at line 302 of file mesh3DScene.cpp.
References mCamera1, mCamera2, and CameraScene::prepareMesh().
{
    mCamera1.prepareMesh(dialog);
    mCamera2.prepareMesh(dialog);
}
virtual void Mesh3DScene::replaceMesh (Mesh3D * newMesh) [inline, virtual, inherited]
Definition at line 47 of file mesh3DScene.h.
References Mesh3DScene::owned.
{
        delete_safe(owned);
        owned = newMesh;
    }
virtual void Mesh3DScene::setMesh (Mesh3D * newMesh) [inline, virtual, inherited]
Definition at line 52 of file mesh3DScene.h.
References Mesh3DScene::owned.
{
        owned = newMesh;
    }
virtual void Mesh3DScene::setParameters (void * params) [inline, virtual, inherited]
Reimplemented from Scene3D.
Reimplemented in CameraScene.
Definition at line 35 of file mesh3DScene.h.
References Mesh3DScene::mParameters.
Referenced by CloudViewDialog::setNewRectificationResult().
    {
        mParameters = *static_cast<Draw3dParameters *>(params);
    };
Member Data Documentation
vector<Vector3d32> corecvs::Mesh3D::faces [inherited]
Definition at line 113 of file mesh3d.h.
Referenced by corecvs::Mesh3D::addAOB(), Mesh3DScene::drawMyself(), and PLYLoader::loadPLY().
CameraScene StereoCameraScene::mCamera1 [private]
Definition at line 119 of file mesh3DScene.h.
Referenced by drawMyself(), and prepareMesh().
CameraScene StereoCameraScene::mCamera2 [private]
Definition at line 120 of file mesh3DScene.h.
Referenced by drawMyself(), and prepareMesh().
Draw3dParameters Mesh3DScene::mParameters [inherited]
Reimplemented in CameraScene.
Definition at line 22 of file mesh3DScene.h.
Referenced by Mesh3DScene::drawMyself(), Mesh3DScene::getContolWidget(), and Mesh3DScene::setParameters().
RectificationResult StereoCameraScene::mStereoPair [private]
Definition at line 118 of file mesh3DScene.h.
Referenced by drawMyself().
QString Scene3D::name [inherited]
Definition at line 37 of file scene3D.h.
Referenced by CloudViewDialog::CloudViewDialog().
Mesh3D* Mesh3DScene::owned [inherited]
Definition at line 23 of file mesh3DScene.h.
Referenced by Mesh3DScene::replaceMesh(), and Mesh3DScene::setMesh().
Scene3D* Scene3D::parent [inherited]
Definition at line 38 of file scene3D.h.
vector<Vector2dd> corecvs::Mesh3D::textureCoords [inherited]
Definition at line 114 of file mesh3d.h.
Referenced by corecvs::Mesh3D::addAOB(), and Mesh3DScene::drawMyself().
Matrix44 Scene3D::transform [inherited]
Definition at line 41 of file scene3D.h.
Referenced by Scene3D::draw().
SceneType Scene3D::type [inherited]
Definition at line 39 of file scene3D.h.
Referenced by CoordinateFrame::CoordinateFrame(), and Scene3D::isComplexObject().
vector<Vector3dd> corecvs::Mesh3D::vertexes [inherited]
Definition at line 112 of file mesh3d.h.
Referenced by corecvs::Mesh3D::addAOB(), corecvs::Mesh3D::addSphere(), Mesh3DScene::drawMyself(), and PLYLoader::loadPLY().
bool Scene3D::visible [inherited]
Definition at line 42 of file scene3D.h.
Referenced by Scene3D::draw().
The documentation for this class was generated from the following files:
utils/3d/mesh3DScene.h
utils/3d/mesh3DScene.cpp