DeepView: corecvs::PropertyListWriterVisitor Class Reference
corecvs::PropertyListWriterVisitor Class Reference
Visitor that serializes the type hierarchy into the PropertyList - the internal human readable format for CVS core.
#include <propertyListVisitor.h>
Public Member Functions
PropertyListWriterVisitor (PropertyList *_output)
template<class Type >
void visit (Type &field, Type defaultValue, const char *fieldName)
template<typename inputType , typename reflectionType >
void visit (inputType &field, const reflectionType *fieldDescriptor)
template<>
void visit (int &intField, int defaultValue, const char *fieldName)
template<>
void visit (double &doubleField, double defaultValue, const char *fieldName)
template<>
void visit (bool &boolField, bool boolValue, const char *fieldName)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
string getCurrentPath ()
string getChildPath (string child)
void pushChild (const string child)
void popChild ()
template<>
void visit (int &intField, int, const char *fieldName)
PropertyListWriterVisitor methods that process different types.
template<>
void visit (double &doubleField, double, const char *fieldName)
template<>
void visit (bool &boolField, bool, const char *fieldName)
template<>
void visit (int &intField, const IntField *fieldDescriptor)
template<>
void visit (double &doubleField, const DoubleField *fieldDescriptor)
template<>
void visit (bool &boolField, const BoolField *fieldDescriptor)
Public Attributes
PropertyList * output
string separator
T elements
STL member.
Static Public Attributes
static string SEPARATOR_DEFAULT = "."
Detailed Description
Visitor that serializes the type hierarchy into the PropertyList - the internal human readable format for CVS core.
Definition at line 28 of file propertyListVisitor.h.
Constructor & Destructor Documentation
corecvs::PropertyListWriterVisitor::PropertyListWriterVisitor (PropertyList * _output) [inline]
Definition at line 31 of file propertyListVisitor.h.
                                                     :
        output(_output)
    {}
Member Function Documentation
string corecvs::BasePathVisitor::getChildPath (string child) [inline, inherited]
Definition at line 35 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getCurrentPath(), and corecvs::BasePathVisitor::separator.
Referenced by corecvs::BasePathVisitor::pushChild().
    {
       string newPath = getCurrentPath();
       if (!newPath.empty())
           newPath.append(separator);
       newPath.append(child);
       return newPath;
    }
string corecvs::BasePathVisitor::getCurrentPath () [inline, inherited]
Definition at line 28 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
    {
        if (empty())
            return "";
        return back();
    }
void corecvs::BasePathVisitor::popChild () [inline, inherited]
Definition at line 55 of file basePathVisitor.h.
Referenced by DefaultSetterOld::visit(), visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        pop_back();
    }
void corecvs::BasePathVisitor::pushChild (const string child) [inline, inherited]
Definition at line 50 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getChildPath().
Referenced by DefaultSetterOld::visit(), visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        push_back(getChildPath(child));
    }
template<> void corecvs::PropertyListWriterVisitor::visit (int & intField, int , const char * fieldName)
PropertyListWriterVisitor methods that process different types.
Definition at line 21 of file propertyListVisitor.cpp.
    {
        output->setIntProperty(getChildPath(fieldName), intField);
    }
template<> void corecvs::PropertyListWriterVisitor::visit (double & doubleField, double , const char * fieldName)
Definition at line 27 of file propertyListVisitor.cpp.
    {
        output->setDoubleProperty(getChildPath(fieldName), doubleField);
    }
template<> void corecvs::PropertyListWriterVisitor::visit (bool & boolField, bool , const char * fieldName)
Definition at line 33 of file propertyListVisitor.cpp.
    {
        output->setIntProperty(getChildPath(fieldName), boolField);
    }
template<class Type > void corecvs::PropertyListWriterVisitor::visit (Type & field, Type defaultValue, const char * fieldName)
Definition at line 45 of file propertyListVisitor.h.
References corecvs::BasePathVisitor::popChild(), and corecvs::BasePathVisitor::pushChild().
Referenced by BaseHostDialog::saveTransformToFile().
{
    pushChild(fieldName);
        field.accept(*this);
    popChild();
}
template<typename inputType , typename reflectionType > void corecvs::PropertyListWriterVisitor::visit (inputType & field, const reflectionType * fieldDescriptor)
Definition at line 53 of file propertyListVisitor.h.
References corecvs::BasePathVisitor::popChild(), and corecvs::BasePathVisitor::pushChild().
{
    pushChild(fieldDescriptor->name.name);
        field.accept(*this);
    popChild();
}
template<> void corecvs::PropertyListWriterVisitor::visit (int & intField, const IntField * fieldDescriptor)
Definition at line 41 of file propertyListVisitor.cpp.
    {
        output->setIntProperty(getChildPath(fieldDescriptor->getSimpleName()), intField);
    }
template<> void corecvs::PropertyListWriterVisitor::visit (double & doubleField, const DoubleField * fieldDescriptor)
Definition at line 47 of file propertyListVisitor.cpp.
    {
        output->setDoubleProperty(getChildPath(fieldDescriptor->getSimpleName()), doubleField);
    }
template<> void corecvs::PropertyListWriterVisitor::visit (bool & boolField, const BoolField * fieldDescriptor)
Definition at line 53 of file propertyListVisitor.cpp.
    {
        output->setIntProperty(getChildPath(fieldDescriptor->getSimpleName()), boolField);
    }
template<> void corecvs::PropertyListWriterVisitor::visit (int & intField, int defaultValue, const char * fieldName)
template<> void corecvs::PropertyListWriterVisitor::visit (double & doubleField, double defaultValue, const char * fieldName)
template<> void corecvs::PropertyListWriterVisitor::visit (bool & boolField, bool boolValue, const char * fieldName)
template<> void corecvs::PropertyListWriterVisitor::visit (int & field, const IntField * fieldDescriptor)
template<> void corecvs::PropertyListWriterVisitor::visit (double & field, const DoubleField * fieldDescriptor)
template<> void corecvs::PropertyListWriterVisitor::visit (bool & field, const BoolField * fieldDescriptor)
Member Data Documentation
template<typename T> T std::deque< T >::elements [inherited]
STL member.
PropertyList* corecvs::PropertyListWriterVisitor::output
Definition at line 41 of file propertyListVisitor.h.
string corecvs::BasePathVisitor::separator [inherited]
Definition at line 26 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
string corecvs::BasePathVisitor::SEPARATOR_DEFAULT = "." [static, inherited]
Definition at line 24 of file basePathVisitor.h.
The documentation for this class was generated from the following files:
core/utils/visitors/propertyListVisitor.h
core/utils/visitors/propertyListVisitor.cpp