DeepView: V4L2CaptureDecoupleInterface::SpinThread Class Reference
V4L2CaptureDecoupleInterface::SpinThread Class Reference
Public Member Functions
SpinThread (V4L2CaptureDecoupleInterface *_interface)
virtual void run (void)
Public Attributes
V4L2CaptureDecoupleInterface * interface
Detailed Description
Definition at line 51 of file V4L2CaptureDecouple.h.
Constructor & Destructor Documentation
V4L2CaptureDecoupleInterface::SpinThread::SpinThread (V4L2CaptureDecoupleInterface * _interface) [inline]
Definition at line 56 of file V4L2CaptureDecouple.h.
                                                             :
            interface(_interface)
        {}
Member Function Documentation
void V4L2CaptureDecoupleInterface::SpinThread::run (void) [virtual]
Now we have two new buffers So we do some thread protected operations. 1. Enqueue the previously used buffers 2. Replace them with the new ones
Definition at line 166 of file V4L2CaptureDecouple.cpp.
References V4L2CaptureDecoupleInterface::camera, V4L2CaptureDecoupleInterface::current, V4L2CameraDescriptor::dequeue(), V4L2CameraDescriptor::enqueue(), V4L2CaptureDecoupleInterface::frameDelay, interface, V4L2CaptureDecoupleInterface::lastFrameTime, ImageCaptureInterface::notifyAboutNewFrame(), V4L2CaptureDecoupleInterface::protectFrame, V4L2CaptureDecoupleInterface::shouldStopSpinThread, V4L2CaptureDecoupleInterface::skippedCount, V4L2CaptureDecoupleInterface::spinRunning, frame_data_t::timestamp, V4L2BufferDescriptor::usecsTimeStamp(), corecvs::PreciseTimer::usecsTo(), and corecvs::PreciseTimer::usecsToNow().
{
    while (interface->spinRunning.tryLock())
    {
        V4L2BufferDescriptor newBuffer;
        V4L2CameraDescriptor* camera = &(interface->camera);
        V4L2BufferDescriptor* current = &(interface->current);
        /* First we block till we will get a new frame */
        /*TODO: Wonder if dequeue should be static */
        /*int result =*/ camera->dequeue(newBuffer);
        /**
         *  Now we have two new buffers
         *  So we do some thread protected operations.
         *  1. Enqueue the previously used buffers
         *  2. Replace them with the new ones
         **/
        interface->protectFrame.lock();
        {
            camera->enqueue(*current);
            *current = newBuffer;
            interface->skippedCount++;
        }
        interface->protectFrame.unlock();
        /* For statistics */
        if (interface->lastFrameTime.usecsTo(PreciseTimer()) != 0)
        {
            interface->frameDelay = interface->lastFrameTime.usecsToNow();
        }
        interface->lastFrameTime = PreciseTimer::currentTime();
        frame_data_t frameData;
        frameData.timestamp = current->usecsTimeStamp();
        interface->notifyAboutNewFrame(frameData);
        interface->spinRunning.unlock();
        if (interface->shouldStopSpinThread)
        {
            break;
        }
    }
}
Member Data Documentation
V4L2CaptureDecoupleInterface* V4L2CaptureDecoupleInterface::SpinThread::interface
Definition at line 54 of file V4L2CaptureDecouple.h.
Referenced by run().
The documentation for this class was generated from the following files:
utils/framesources/v4l2/V4L2CaptureDecouple.h
utils/framesources/v4l2/V4L2CaptureDecouple.cpp