DeepView: corecvs::ParallelGetBestClassifier Class Reference
corecvs::ParallelGetBestClassifier Class Reference
Public Member Functions
ParallelGetBestClassifier (const AdaBoostInput< VJInputImage > &_inputs, VJSimpleClassifierGenerator *_gen)
void operator() (const BlockedRange< unsigned > &r) const
Private Attributes
const AdaBoostInput
< VJInputImage > & inputs
VJSimpleClassifierGenerator * gen
Detailed Description
Definition at line 26 of file vjPattern.cpp.
Constructor & Destructor Documentation
corecvs::ParallelGetBestClassifier::ParallelGetBestClassifier (const AdaBoostInput< VJInputImage > & _inputs, VJSimpleClassifierGenerator * _gen) [inline]
Definition at line 33 of file vjPattern.cpp.
                                               :
        inputs(_inputs),
        gen(_gen)
    {}
Member Function Documentation
void corecvs::ParallelGetBestClassifier::operator() (const BlockedRange< unsigned > & r) const [inline]
Now we should find the best threshold start with the one lower then the lowest result.
Calculate the epsilon of the error assuming all the results are predicted as faces
Now move threshold over the results from the list and see how epsilon changes
If we step over the real face we should be punished otherwise rewarded
Definition at line 41 of file vjPattern.cpp.
References corecvs::VJPattern::applyToPoint(), corecvs::BlockedRange< IndexType >::begin(), corecvs::VJSimpleClassifierGenerator::bestPattern, corecvs::VJSimpleClassifierGenerator::bestZ, corecvs::BlockedRange< IndexType >::end(), gen, corecvs::VJSimpleClassifierGenerator::generators, corecvs::VJSimpleClassifierGenerator::globalCount, corecvs::VJResult::inputData, inputs, corecvs::VJInputImage::integral, corecvs::VJSimpleClassifierGenerator::minEpsilonGlobal, corecvs::AdaBoostInputData< InputType >::weight, corecvs::AdaBoostInputData< InputType >::x, and corecvs::AdaBoostInputData< InputType >::y.
    {
        for(unsigned iteration = r.begin(); iteration  < r.end(); iteration++)
        {
            vector<VJResult> results;
            results.reserve(inputs.size());
            /*Choosing random VJ pattern form one of the generators*/
            VJPattern *currentPattern = gen->generators[rand() % gen->generators.size()]->pattern();
            results.clear();
            for (unsigned long i = 0; i < (unsigned long)inputs.size(); i++)
            {
                const AdaBoostInputData<VJInputImage> *data = &inputs[i];
                G12IntegralBuffer *integral = data->x.integral;
                int value = currentPattern->applyToPoint(integral,0,0);
                VJResult result = VJResult(value, data);
                results.push_back(result);
            }
            sort(results.begin(), results.end());
            /**
             *  Now we should find the best threshold start with the one lower
             *  then the lowest result.
             *
             **/
            int threshold = results[0].value - 1;
            /**
             * Calculate the epsilon of the error assuming all the
             * results are predicted as faces
             **/
            double startEpsilon = 0;
            for (unsigned i = 0; i < results.size(); i++)
            {
                if (! results[i].inputData->y)
                    startEpsilon += results[i].inputData->weight;
            }
            double minEpsilon = startEpsilon;
            double currentEpsilon = startEpsilon;
            /**
             * Now move threshold over the results from the list and
             * see how epsilon changes
             **/
            for (unsigned i = 0; i < results.size(); i++)
            {
                VJResult *result = &(results[i]);
                /**
                 * If we step over the real face we should be punished
                 * otherwise rewarded
                 **/
                if (result->inputData->y)
                    currentEpsilon += result->inputData->weight;
                else
                    currentEpsilon -= result->inputData->weight;
                if (currentEpsilon < minEpsilon)
                {
                    minEpsilon = currentEpsilon;
                    if (i < (results.size() - 1))
                    {
                        // threshold = results[i].result;
                        threshold = (results[i].value + results[i + 1].value) / 2;
                    }
                    else
                    {
                        threshold = results[i].value;
                    }
                }
            }
            /* TODO: Replace this with reduce operation */
#ifdef WITH_TBB
            spin_mutex::scoped_lock lock;
            lock.acquire(gen->VJSimpleClassifierGeneratorMutex);
            {
#endif
                if (minEpsilon < gen->minEpsilonGlobal)
                {
                    gen->minEpsilonGlobal = minEpsilon;
                    VJPattern *tmp = gen->bestPattern;
                    gen->bestPattern = currentPattern;
                    currentPattern = tmp;
                    gen->bestZ = threshold;
                }
                gen->globalCount++;
                if (gen->globalCount % 500 == 0)
                {
                    printf("Pattern attempt %d\n", gen->globalCount);
                    fflush(stdout);
                }
#ifdef WITH_TBB
            }
            lock.release();
#endif
            if (currentPattern != NULL)
                delete currentPattern;
        }
    }
Member Data Documentation
VJSimpleClassifierGenerator* corecvs::ParallelGetBestClassifier::gen [private]
Definition at line 29 of file vjPattern.cpp.
Referenced by operator()().
const AdaBoostInput<VJInputImage>& corecvs::ParallelGetBestClassifier::inputs [private]
Definition at line 28 of file vjPattern.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
core/boosting/vjPattern.cpp