DeepView: HeadSearchParametersControlWidget Class Reference
HeadSearchParametersControlWidget Class Reference
#include <headSearchParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
HeadSearchParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~HeadSearchParametersControlWidget ()
HeadSearchParameters * createParameters () const
void setParameters (const HeadSearchParameters &input)
void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_HeadSearchParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 13 of file headSearchParametersControlWidget.h.
Constructor & Destructor Documentation
HeadSearchParametersControlWidget::HeadSearchParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file headSearchParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::HeadSearchParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->thresholdDistanceSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->clusterDepthSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->clusterMinSizeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->headAreaRadiusSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->headNumberSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
HeadSearchParametersControlWidget::~HeadSearchParametersControlWidget ()
Definition at line 30 of file headSearchParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void HeadSearchParametersControlWidget::changeParameters () [inline, slot]
Definition at line 30 of file headSearchParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
HeadSearchParameters * HeadSearchParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 52 of file headSearchParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    HeadSearchParameters *result = new HeadSearchParameters(
          mUi->thresholdDistanceSpinBox->value()
        , mUi->clusterDepthSpinBox->value()
        , mUi->clusterMinSizeSpinBox->value()
        , mUi->headAreaRadiusSpinBox->value()
        , mUi->headNumberSpinBox->value()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void HeadSearchParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 36 of file headSearchParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    HeadSearchParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void HeadSearchParametersControlWidget::paramsChanged () [signal]
Referenced by HeadSearchParametersControlWidget(), and setParameters().
void HeadSearchParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 44 of file headSearchParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    HeadSearchParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void HeadSearchParametersControlWidget::setParameters (const HeadSearchParameters & input)
Definition at line 70 of file headSearchParametersControlWidget.cpp.
References HeadSearchParameters::clusterDepth(), HeadSearchParameters::clusterMinSize(), HeadSearchParameters::headAreaRadius(), HeadSearchParameters::headNumber(), mUi, paramsChanged(), and HeadSearchParameters::thresholdDistance().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->thresholdDistanceSpinBox->setValue(input.thresholdDistance());
    mUi->clusterDepthSpinBox->setValue(input.clusterDepth());
    mUi->clusterMinSizeSpinBox->setValue(input.clusterMinSize());
    mUi->headAreaRadiusSpinBox->setValue(input.headAreaRadius());
    mUi->headNumberSpinBox->setValue(input.headNumber());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void HeadSearchParametersControlWidget::setParametersVirtual (void * input)
Definition at line 83 of file headSearchParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    HeadSearchParameters *inputCasted = static_cast<HeadSearchParameters *>(input);
    setParameters(*inputCasted);
}
void HeadSearchParametersControlWidget::valueChanged () [signal]
Referenced by HeadSearchParametersControlWidget().
Member Data Documentation
bool HeadSearchParametersControlWidget::autoInit [private]
Definition at line 41 of file headSearchParametersControlWidget.h.
Ui_HeadSearchParametersControlWidget* HeadSearchParametersControlWidget::mUi [private]
Definition at line 40 of file headSearchParametersControlWidget.h.
Referenced by createParameters(), HeadSearchParametersControlWidget(), setParameters(), and ~HeadSearchParametersControlWidget().
QString HeadSearchParametersControlWidget::rootPath [private]
Definition at line 42 of file headSearchParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/corestructs/coreWidgets/headSearchParametersControlWidget.h
utils/corestructs/coreWidgets/headSearchParametersControlWidget.cpp