DeepView: SobelFilter Class Reference
SobelFilter Class Reference
#include <sobelfilter.h>
Public Slots
void parametersChangedSlot (void)
Signals
void parametersChanged (void)
Public Member Functions
SobelFilter (QWidget *parent=0)
~SobelFilter ()
virtual G12Buffer * filter (G12Buffer *input)
virtual QString getInstanceName ()
Static Public Member Functions
static QString getName ()
Private Attributes
Ui_SobelFilterClass ui
Static Private Attributes
static QString name = QString("Sobel")
Detailed Description
Definition at line 9 of file sobelfilter.h.
Constructor & Destructor Documentation
SobelFilter::SobelFilter (QWidget * parent = 0)
SobelFilter::~SobelFilter ()
Member Function Documentation
G12Buffer * SobelFilter::filter (G12Buffer * input) [virtual]
Reimplemented from BaseFilter.
Definition at line 20 of file sobelfilter.cpp.
{
    //G12Buffer *toReturn = g12BufferClone(input);
/*    if (ui.xButton->isChecked())
        return g12BufferSobelX(input);
    if (ui.yButton->isChecked())
        return g12BufferSobelY(input);
    if (ui.bothButton->isChecked())
        return g12BufferSobelMag(input, 8);*/
//    g12BufferGainOffset(toReturn, gParams.gain, gParams.offset);
    //return toReturn;
    return new G12Buffer(input);
}
virtual QString SobelFilter::getInstanceName () [inline, virtual]
Reimplemented from BaseFilter.
Definition at line 29 of file sobelfilter.h.
References name.
     {
         return name;
     };
static QString SobelFilter::getName () [inline, static]
Reimplemented from BaseFilter.
Definition at line 24 of file sobelfilter.h.
References name.
Referenced by FilterFabric::createFilterInstance(), and FilterFabric::getFilterNames().
     {
         return name;
     };
void BaseFilter::parametersChanged (void) [signal, inherited]
Referenced by BitSelector::maskChanged(), BitSelector::shiftChanged(), GainOffset::updateGainSlider(), GainOffset::updateGainText(), ScaleFilter::updateHeight(), GainOffset::updateOffsetSlider(), GainOffset::updateOffsetText(), ScaleFilter::updateWidth(), ScaleFilter::updateXScale(), ScaleFilter::updateXShift(), ScaleFilter::updateYScale(), and ScaleFilter::updateYShift().
void SobelFilter::parametersChangedSlot (void) [slot]
Definition at line 15 of file sobelfilter.cpp.
{
    emit parametersChanged();
}
Member Data Documentation
QString SobelFilter::name = QString("Sobel") [static, private]
Definition at line 13 of file sobelfilter.h.
Referenced by getInstanceName(), and getName().
Ui_SobelFilterClass SobelFilter::ui [private]
Reimplemented from BaseFilter.
Definition at line 32 of file sobelfilter.h.
The documentation for this class was generated from the following files:
utils/filters/legacy/sobelfilter.h
utils/filters/legacy/sobelfilter.cpp