DeepView: corecvs::PreciseTimerEx Class Reference
corecvs::PreciseTimerEx Class Reference
#include <preciseTimer.h>
Public Member Functions
PreciseTimerEx (uint64_t *pAccTime=NULL)
ctor: stores the current time
int64_t elapsed () const
return the elapsed time since the object exists
~PreciseTimerEx ()
dtor: accumulates the passed time into accumulator
void init ()
bool isCorrect () const
void setTime (int64_t time)
int64_t msec (int64_t time) const
int64_t msec () const
int64_t usecsTo (PreciseTimer const &end) const
int64_t usecsToNow () const
int64_t usec () const
int operator- (PreciseTimer &other)
int operator- (int &msecOther)
Static Public Member Functions
static PreciseTimer currentTime ()
Private Attributes
uint64_t * mpAccTime
Detailed Description
Definition at line 45 of file preciseTimer.h.
Constructor & Destructor Documentation
corecvs::PreciseTimerEx::PreciseTimerEx (uint64_t * pAccTime = NULL) [inline]
ctor: stores the current time
Definition at line 49 of file preciseTimer.h.
References corecvs::PreciseTimer::currentTime(), corecvs::PreciseTimer::setTime(), and corecvs::PreciseTimer::usec().
        : mpAccTime(pAccTime)                   { setTime(currentTime().usec());          }
corecvs::PreciseTimerEx::~PreciseTimerEx () [inline]
dtor: accumulates the passed time into accumulator
Definition at line 56 of file preciseTimer.h.
References elapsed(), and mpAccTime.
{ if (mpAccTime) *mpAccTime += elapsed(); }
Member Function Documentation
PreciseTimer corecvs::PreciseTimer::currentTime () [static, inherited]
Definition at line 34 of file preciseTimer.cpp.
References corecvs::PreciseTimer::setTime().
Referenced by corecvs::Clustering3D::_clusterStarting(), corecvs::Clustering3D::clusterStartRecursive(), corecvs::FilterGraph::execute(), PreciseTimerEx(), corecvs::Statistics::startInterval(), and corecvs::PreciseTimer::usecsToNow().
{
    PreciseTimer T;
#if defined(QT_CLOCK)
    QTime time = QTime::currentTime();
    T.setTime(((((int64_t)time.hour() * 60 + time.minute()) * 60 + time.second()) * 1000 + time.msec()) * 1000);
#elif defined(WINDOWS_CLOCK)
    if (!mFreq) {
        QueryPerformanceFrequency((LARGE_INTEGER*)&mFreq);
    }
    LARGE_INTEGER time;
    QueryPerformanceCounter(&time);
    T.setTime((time.QuadPart * 1000000) / mFreq);
#else
    struct timeval timeVal;
    gettimeofday(&timeVal, NULL);
    T.setTime(timeVal.tv_sec * 1000000 + timeVal.tv_usec);
#endif
    return T;
}
int64_t corecvs::PreciseTimerEx::elapsed () const [inline]
return the elapsed time since the object exists
Definition at line 53 of file preciseTimer.h.
References corecvs::PreciseTimer::usecsToNow().
Referenced by ~PreciseTimerEx().
{ return usecsToNow();                    }
void corecvs::PreciseTimer::init () [inline, inherited]
Definition at line 23 of file preciseTimer.h.
References corecvs::PreciseTimer::mTime.
Referenced by corecvs::PreciseTimer::PreciseTimer().
{ mTime = -1;                            }
bool corecvs::PreciseTimer::isCorrect () const [inline, inherited]
Definition at line 24 of file preciseTimer.h.
References corecvs::PreciseTimer::mTime.
Referenced by corecvs::PreciseTimer::usecsToNow().
{ return mTime != -1;                    }
int64_t corecvs::PreciseTimer::msec (int64_t time) const [inline, inherited]
Definition at line 27 of file preciseTimer.h.
References _roundDivUp.
{ return _roundDivUp(time, 1000);        }
int64_t corecvs::PreciseTimer::msec () const [inline, inherited]
Definition at line 32 of file preciseTimer.h.
References corecvs::PreciseTimer::msec(), and corecvs::PreciseTimer::mTime.
Referenced by corecvs::PreciseTimer::msec(), and corecvs::PreciseTimer::operator-().
{ return msec(mTime);                    }
int corecvs::PreciseTimer::operator- (PreciseTimer & other) [inline, inherited]
Definition at line 34 of file preciseTimer.h.
References corecvs::PreciseTimer::msec(), and corecvs::PreciseTimer::mTime.
{ return msec(mTime - other.mTime);      }
int corecvs::PreciseTimer::operator- (int & msecOther) [inline, inherited]
Definition at line 35 of file preciseTimer.h.
References corecvs::PreciseTimer::msec(), and corecvs::PreciseTimer::mTime.
{ return msec(mTime - msecOther * 1000); }
void corecvs::PreciseTimer::setTime (int64_t time) [inline, inherited]
Definition at line 25 of file preciseTimer.h.
References corecvs::PreciseTimer::mTime.
Referenced by corecvs::PreciseTimer::currentTime(), and PreciseTimerEx().
{ mTime = time;                          }
int64_t corecvs::PreciseTimer::usec () const [inline, inherited]
Definition at line 31 of file preciseTimer.h.
References corecvs::PreciseTimer::mTime.
Referenced by PreciseTimerEx().
{ return mTime;                          }
int64_t corecvs::PreciseTimer::usecsTo (PreciseTimer const & end) const [inline, inherited]
Definition at line 29 of file preciseTimer.h.
References corecvs::PreciseTimer::mTime.
Referenced by corecvs::Clustering3D::clusterStartRecursive(), DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), V4L2CaptureInterface::SpinThread::run(), and corecvs::PreciseTimer::usecsToNow().
{ return end.mTime - this->mTime;        }
int64_t corecvs::PreciseTimer::usecsToNow () const [inline, inherited]
Definition at line 30 of file preciseTimer.h.
References corecvs::PreciseTimer::currentTime(), corecvs::PreciseTimer::isCorrect(), and corecvs::PreciseTimer::usecsTo().
Referenced by corecvs::Clustering3D::_clusterStarting(), V4L2CaptureInterface::decodeDataRGB24(), elapsed(), corecvs::Statistics::endInterval(), corecvs::FilterGraph::execute(), BaseCalculationThread::executeFilterGraph(), V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), RecorderThread::processNewData(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), V4L2CaptureInterface::SpinThread::run(), and ContentStatistics::transition().
{ return isCorrect() ? usecsTo(currentTime()) : 0; }
Member Data Documentation
uint64_t* corecvs::PreciseTimerEx::mpAccTime [private]
Definition at line 59 of file preciseTimer.h.
Referenced by ~PreciseTimerEx().
The documentation for this class was generated from the following file:
core/utils/preciseTimer.h