DeepView: corecvs::IterativeEstimator Class Reference
corecvs::IterativeEstimator Class Reference
#include <iterativeEstimator.h>
Public Member Functions
IterativeEstimator (int _maxIterations, double _initialSigma, double _sigmaFactor, EssentialEstimator::OptimisationMethod _method=EssentialEstimator::METHOD_DEFAULT)
EssentialMatrix getEssential (const vector< Correspondance * > &samples)
virtual ~IterativeEstimator ()
Public Attributes
int maxIterations
double initialSigma
double sigmaFactor
EssentialEstimator::OptimisationMethod method
Detailed Description
Definition at line 14 of file iterativeEstimator.h.
Constructor & Destructor Documentation
corecvs::IterativeEstimator::IterativeEstimator (int _maxIterations, double _initialSigma, double _sigmaFactor, EssentialEstimator::OptimisationMethod _method = EssentialEstimator::METHOD_DEFAULT) [inline]
Definition at line 22 of file iterativeEstimator.h.
      :
        maxIterations(_maxIterations),
        initialSigma(_initialSigma),
        sigmaFactor(_sigmaFactor),
        method(_method)
    {}
corecvs::IterativeEstimator::~IterativeEstimator () [virtual]
Definition at line 96 of file iterativeEstimator.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
EssentialMatrix corecvs::IterativeEstimator::getEssential (const vector< Correspondance * > & samples)
Definition at line 16 of file iterativeEstimator.cpp.
References corecvs::EssentialMatrix::epipolarDistance(), corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_FAILER, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_PASSER, corecvs::EssentialEstimator::CostFunction7to1::getCost(), corecvs::EssentialEstimator::getEssential(), initialSigma, L_INFO_P, maxIterations, method, sigmaFactor, and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::value.
{
    EssentialMatrix model;
    int iteration;
    vector<Correspondance *> workingSamples = samples;
    EssentialEstimator::CostFunction7to1 initialCost(&samples);
    L_INFO_P("Starting iterative rectification...");
    double sigma = initialSigma;
    for (iteration = 0; iteration < maxIterations; iteration++)
    {
        EssentialEstimator estimator;
        if (workingSamples.size() < 9)
        {
            cout << "Too few inputs to continue:" << workingSamples.size() << endl;
            break;
        }
        model = estimator.getEssential(workingSamples, method);
        EssentialEstimator::CostFunction7to1 cost(&workingSamples);
        int passed = 0;
        int rejected = 0;
        vector<Correspondance *> passedSamples;
        for (unsigned i = 0; i < workingSamples.size(); i++)
        {
            Correspondance *corr = workingSamples[i];
            double value = model.epipolarDistance(*corr);
            if (value > sigma)
            {
                rejected++;
                corr->value = iteration;
            } else {
                passed++;
                passedSamples.push_back(corr);
            }
        }
        double errorPerPoint = sqrt(cost.getCost(model) / workingSamples.size());
        double errorPerPointInit = sqrt(initialCost.getCost(model) / samples.size());
#ifdef TRACE
        cout << "Iteration: " << iteration << endl;
        cout << "Error:" << cost.getCost(model) << endl;
        cout << "Sq per point:" << (cost.getCost(model) / workingSamples.size()) << endl;
        cout << "Error per point:" << errorPerPoint << endl;
        cout << " Total:" << workingSamples.size() << endl;
        cout << "   Passed  :" << passed   << endl;
        cout << "   Rejected:" << rejected << endl;
#endif
        //printf("Iteration %4d: %6d %6d %6d %lf %lf \n", iteration, passed + rejected, passed, rejected, errorPerPoint, errorPerPointInit);
        // Make real callback
        L_INFO_P("Iteration %4d: %6d %6d %6d %lf %lf"
                 , iteration, passed + rejected, passed, rejected, errorPerPoint, errorPerPointInit);
        workingSamples = passedSamples;
        sigma *= sigmaFactor;
    }
    for (unsigned i = 0; i < samples.size(); i++)
    {
        samples[i]->flags |= Correspondance::FLAG_FAILER;
    }
    for (unsigned i = 0; i < workingSamples.size(); i++)
    {
        workingSamples[i]->flags &= ~Correspondance::FLAG_FAILER;
        workingSamples[i]->flags |=  Correspondance::FLAG_PASSER;
        workingSamples[i]->value = iteration;
    }
    L_INFO_P("Iterative rectification finished");
    return model;
}
Member Data Documentation
double corecvs::IterativeEstimator::initialSigma
Definition at line 18 of file iterativeEstimator.h.
Referenced by getEssential().
int corecvs::IterativeEstimator::maxIterations
Definition at line 17 of file iterativeEstimator.h.
Referenced by getEssential().
EssentialEstimator::OptimisationMethod corecvs::IterativeEstimator::method
Definition at line 20 of file iterativeEstimator.h.
Referenced by getEssential().
double corecvs::IterativeEstimator::sigmaFactor
Definition at line 19 of file iterativeEstimator.h.
Referenced by getEssential().
The documentation for this class was generated from the following files:
core/rectification/iterativeEstimator.h
core/rectification/iterativeEstimator.cpp