DeepView: ConfigManager Class Reference
ConfigManager Class Reference
Singleton class to represent config settings.
#include <configManager.h>
Static Public Member Functions
static QString configName ()
static void setConfigName (QString const &name)
static QString camConfigName ()
static void setCamConfigName (QString const &name)
static ConfigManager * instance ()
Private Member Functions
ConfigManager ()
QString name ()
void setName (QString const &name)
QString camName ()
void setCamName (QString const &name)
Private Attributes
QString mName
QString mCamName
Static Private Attributes
static ConfigManager * mInstance = NULL
Detailed Description
Singleton class to represent config settings.
Definition at line 6 of file configManager.h.
Constructor & Destructor Documentation
ConfigManager::ConfigManager () [private]
Definition at line 33 of file configManager.cpp.
Referenced by instance().
{
}
Member Function Documentation
QString ConfigManager::camConfigName () [static]
Definition at line 15 of file configManager.cpp.
References camName(), and instance().
Referenced by BaseHostDialog::initCapture(), BaseHostDialog::loadParams(), BaseHostDialog::saveParams(), and BaseHostDialog::~BaseHostDialog().
{
    return instance()->camName();
}
QString ConfigManager::camName () [private]
Definition at line 47 of file configManager.cpp.
References mCamName.
Referenced by camConfigName().
{
    return mCamName;
}
QString ConfigManager::configName () [static]
Definition at line 5 of file configManager.cpp.
References instance(), and name().
Referenced by BaseHostDialog::deinit(), FoldableWidget::FoldableWidget(), BaseHostDialog::init(), and FoldableWidget::~FoldableWidget().
{
    return instance()->name();
}
ConfigManager * ConfigManager::instance () [static]
Definition at line 25 of file configManager.cpp.
References ConfigManager(), and mInstance.
Referenced by camConfigName(), configName(), setCamConfigName(), and setConfigName().
{
    if (mInstance == NULL)
        mInstance = new ConfigManager();
    return mInstance;
}
QString ConfigManager::name () [private]
Definition at line 37 of file configManager.cpp.
References mName.
Referenced by configName(), setCamName(), and setName().
{
    return mName;
}
void ConfigManager::setCamConfigName (QString const & name) [static]
Definition at line 20 of file configManager.cpp.
References instance(), and setCamName().
{
    instance()->setCamName(name);
}
void ConfigManager::setCamName (QString const & name) [private]
Definition at line 52 of file configManager.cpp.
References mCamName, and name().
Referenced by setCamConfigName().
{
    mCamName = name;
}
void ConfigManager::setConfigName (QString const & name) [static]
Definition at line 10 of file configManager.cpp.
References instance(), and setName().
{
    instance()->setName(name);
}
void ConfigManager::setName (QString const & name) [private]
Definition at line 42 of file configManager.cpp.
References mName, and name().
Referenced by setConfigName().
{
    mName = name;
}
Member Data Documentation
QString ConfigManager::mCamName [private]
Definition at line 29 of file configManager.h.
Referenced by camName(), and setCamName().
ConfigManager * ConfigManager::mInstance = NULL [static, private]
Definition at line 26 of file configManager.h.
Referenced by instance().
QString ConfigManager::mName [private]
Definition at line 28 of file configManager.h.
Referenced by name(), and setName().
The documentation for this class was generated from the following files:
utils/configManager.h
utils/configManager.cpp