DeepView: corecvs::TransformationCache Class Reference
corecvs::TransformationCache Class Reference
This class is caching the transformation of the buffer.
#include <transformationCache.h>
Public Member Functions
TransformationCache (Matrix33 matrix, int w, int h, Vector2d< int > inputSize)
G12Buffer * doDeformation (InterpolationType::InterpolationType type, G12Buffer *buffer)
~TransformationCache ()
Private Attributes
DirectRemapper * mRemap
DisplacementBuffer * mDisplace
FixedPointDisplace * mF8Displace
Detailed Description
This class is caching the transformation of the buffer.
Definition at line 12 of file transformationCache.h.
Constructor & Destructor Documentation
corecvs::TransformationCache::TransformationCache (Matrix33 matrix, int w, int h, Vector2d< int > inputSize)
Parameters:
matrix inverse matrix of the transformation applied
w output width of the image
h output height of the image
inputSize size of input image
Definition at line 6 of file transformationCache.cpp.
References mDisplace, mF8Displace, and mRemap.
{
    mRemap      = new DirectRemapper    (&matrix, inputSize, Vector2d<int>(w, h));
    mDisplace   = new DisplacementBuffer(&matrix, h, w);
    mF8Displace = new FixedPointDisplace( matrix, h, w);
}
corecvs::TransformationCache::~TransformationCache ()
Definition at line 41 of file transformationCache.cpp.
References mDisplace, mF8Displace, and mRemap.
{
    delete_safe(mRemap);
    delete_safe(mDisplace);
    delete_safe(mF8Displace);
}
Member Function Documentation
G12Buffer * corecvs::TransformationCache::doDeformation (InterpolationType::InterpolationType type, G12Buffer * buffer)
Definition at line 13 of file transformationCache.cpp.
References InterpolationType::BILINEAR, InterpolationType::BILINEAR_FIXED8, corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformationBl(), corecvs::G12Buffer::doReverseDeformationBlPrecomp(), corecvs::AbstractBufferParams::h, mDisplace, mF8Displace, mRemap, InterpolationType::NEAREST, corecvs::DirectRemapper::remap(), and corecvs::AbstractBufferParams::w.
Referenced by BaseCalculationThread::executeFilterGraph(), RecorderThread::processNewData(), and BaseCalculationThread::transformInputFrames().
{
    switch (type)
    {
        case InterpolationType::BILINEAR :
            return inputFrame->doReverseDeformationBl<G12Buffer, DisplacementBuffer> (
                        mDisplace,
                        mDisplace->h,
                        mDisplace->w);
            break;
        case InterpolationType::NEAREST :
            return mRemap->remap(inputFrame);
            break;
        case InterpolationType::BILINEAR_FIXED8 :
            return inputFrame->doReverseDeformationBlPrecomp(
                        mF8Displace,
                        mF8Displace->h,
                        mF8Displace->w);
            break;
        default:
            break;
    }
    return new G12Buffer(inputFrame);
}
Member Data Documentation
DisplacementBuffer* corecvs::TransformationCache::mDisplace [private]
Definition at line 28 of file transformationCache.h.
Referenced by doDeformation(), TransformationCache(), and ~TransformationCache().
FixedPointDisplace* corecvs::TransformationCache::mF8Displace [private]
Definition at line 29 of file transformationCache.h.
Referenced by doDeformation(), TransformationCache(), and ~TransformationCache().
DirectRemapper* corecvs::TransformationCache::mRemap [private]
Definition at line 27 of file transformationCache.h.
Referenced by doDeformation(), TransformationCache(), and ~TransformationCache().
The documentation for this class was generated from the following files:
core/buffers/transformationCache.h
core/buffers/transformationCache.cpp