DeepView: tinyxml2::XMLPrinter Class Reference
tinyxml2::XMLPrinter Class Reference
Printing functionality.
#include <tinyxml2.h>
Public Member Functions
XMLPrinter (std::FILE *file=0, bool compact=false)
Construct the printer.
~XMLPrinter ()
void PushHeader (bool writeBOM, bool writeDeclaration)
If streaming, write the BOM and declaration.
void OpenElement (const char *name)
If streaming, start writing an element.
void PushAttribute (const char *name, const char *value)
If streaming, add an attribute to an open element.
void PushAttribute (const char *name, int value)
void PushAttribute (const char *name, unsigned value)
void PushAttribute (const char *name, bool value)
void PushAttribute (const char *name, double value)
void CloseElement ()
If streaming, close the Element.
void PushText (const char *text, bool cdata=false)
Add a text node.
void PushText (int value)
Add a text node from an integer.
void PushText (unsigned value)
Add a text node from an unsigned.
void PushText (bool value)
Add a text node from a bool.
void PushText (float value)
Add a text node from a float.
void PushText (double value)
Add a text node from a double.
void PushComment (const char *comment)
Add a comment.
void PushDeclaration (const char *value)
void PushUnknown (const char *value)
virtual bool VisitEnter (const XMLDocument &)
Visit a document.
virtual bool VisitExit (const XMLDocument &)
Visit a document.
virtual bool VisitEnter (const XMLElement &element, const XMLAttribute *attribute)
Visit an element.
virtual bool VisitExit (const XMLElement &element)
Visit an element.
virtual bool Visit (const XMLText &text)
Visit a text node.
virtual bool Visit (const XMLComment &comment)
Visit a comment node.
virtual bool Visit (const XMLDeclaration &declaration)
Visit a declaration.
virtual bool Visit (const XMLUnknown &unknown)
Visit an unknown node.
const char * CStr () const
If in print to memory mode, return a pointer to the XML file in memory.
int CStrSize () const
If in print to memory mode, return the size of the XML file in memory.
Private Types
enum { ENTITY_RANGE = 64, BUF_SIZE = 200 }
Private Member Functions
void SealElement ()
void PrintSpace (int depth)
void PrintString (const char *, bool restrictedEntitySet)
void Print (const char *format,...)
Private Attributes
bool _elementJustOpened
bool _firstElement
std::FILE * _fp
int _depth
int _textDepth
bool _processEntities
bool _compactMode
bool _entityFlag [ENTITY_RANGE]
bool _restrictedEntityFlag [ENTITY_RANGE]
DynArray< const char *, 10 > _stack
DynArray< char, 20 > _buffer
Detailed Description
Printing functionality.
The XMLPrinter gives you more options than the XMLDocument::Print() method.
It can:
Print to memory.
Print to a file you provide.
Print XML without a XMLDocument.
Print to Memory
    XMLPrinter printer;
    doc->Print( &printer );
    SomeFunction( printer.CStr() );
Print to a File
You provide the file pointer.
    XMLPrinter printer( fp );
    doc.Print( &printer );
Print without a XMLDocument
When loading, an XML parser is very useful. However, sometimes when saving, it just gets in the way. The code is often set up for streaming, and constructing the DOM is just overhead.
The Printer supports the streaming case. The following code prints out a trivially simple XML file without ever creating an XML document.
    XMLPrinter printer( fp );
    printer.OpenElement( "foo" );
    printer.PushAttribute( "foo", "bar" );
    printer.CloseElement();
Definition at line 1805 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
ENTITY_RANGE
BUF_SIZE
Definition at line 1894 of file tinyxml2.h.
         {
        ENTITY_RANGE = 64,
        BUF_SIZE = 200
    };
Constructor & Destructor Documentation
tinyxml2::XMLPrinter::XMLPrinter (std::FILE * file = 0, bool compact = false)
Construct the printer.
If the FILE* is specified, this will print to the FILE. Else it will print to memory, and the result is available in CStr(). If 'compact' is set to true, then output is created with only required whitespace and newlines.
Definition at line 1734 of file tinyxml2.cpp.
References _buffer, _entityFlag, _restrictedEntityFlag, tinyxml2::entities, ENTITY_RANGE, tinyxml2::NUM_ENTITIES, tinyxml2::DynArray< T, INIT >::Push(), and TIXMLASSERT.
                                                 :
    _elementJustOpened( false ),
    _firstElement( true ),
    _fp( file ),
    _depth( 0 ),
    _textDepth( -1 ),
    _processEntities( true ),
    _compactMode( compact )
{
    for( int i=0; i<ENTITY_RANGE; ++i ) {
        _entityFlag[i] = false;
        _restrictedEntityFlag[i] = false;
    }
    for( int i=0; i<NUM_ENTITIES; ++i ) {
        TIXMLASSERT( entities[i].value < ENTITY_RANGE );
        if ( entities[i].value < ENTITY_RANGE ) {
            _entityFlag[ (int)entities[i].value ] = true;
        }
    }
    _restrictedEntityFlag[(int)'&'] = true;
    _restrictedEntityFlag[(int)'<'] = true;
    _restrictedEntityFlag[(int)'>'] = true; // not required, but consistency is nice
    _buffer.Push( 0 );
}
tinyxml2::XMLPrinter::~XMLPrinter () [inline]
Definition at line 1815 of file tinyxml2.h.
{}
Member Function Documentation
void tinyxml2::XMLPrinter::CloseElement ()
If streaming, close the Element.
Definition at line 1914 of file tinyxml2.cpp.
References _compactMode, _depth, _elementJustOpened, _stack, _textDepth, tinyxml2::DynArray< T, INIT >::Pop(), Print(), and PrintSpace().
Referenced by VisitExit().
{
    --_depth;
    const char* name = _stack.Pop();
    if ( _elementJustOpened ) {
        Print( "/>" );
    }
    else {
        if ( _textDepth < 0 && !_compactMode) {
            Print( "\n" );
            PrintSpace( _depth );
        }
        Print( "</%s>", name );
    }
    if ( _textDepth == _depth ) {
        _textDepth = -1;
    }
    if ( _depth == 0 && !_compactMode) {
        Print( "\n" );
    }
    _elementJustOpened = false;
}
const char* tinyxml2::XMLPrinter::CStr () const [inline]
If in print to memory mode, return a pointer to the XML file in memory.
Definition at line 1868 of file tinyxml2.h.
References _buffer, and tinyxml2::DynArray< T, INIT >::Mem().
Referenced by FilterGraphPresentation::serializeClicked().
{
        return _buffer.Mem();
    }
int tinyxml2::XMLPrinter::CStrSize () const [inline]
If in print to memory mode, return the size of the XML file in memory.
(Note the size returned includes the terminating null.)
Definition at line 1876 of file tinyxml2.h.
References _buffer, and tinyxml2::DynArray< T, INIT >::Size().
{
        return _buffer.Size();
    }
void tinyxml2::XMLPrinter::OpenElement (const char * name)
If streaming, start writing an element.
The element must be closed with CloseElement()
Definition at line 1854 of file tinyxml2.cpp.
References _compactMode, _depth, _elementJustOpened, _firstElement, _stack, _textDepth, Print(), PrintSpace(), tinyxml2::DynArray< T, INIT >::Push(), and SealElement().
Referenced by VisitEnter().
{
    if ( _elementJustOpened ) {
        SealElement();
    }
    _stack.Push( name );
    if ( _textDepth < 0 && !_firstElement && !_compactMode ) {
        Print( "\n" );
        PrintSpace( _depth );
    }
    Print( "<%s", name );
    _elementJustOpened = true;
    _firstElement = false;
    ++_depth;
}
void tinyxml2::XMLPrinter::Print (const char * format, ...) [private]
Definition at line 1760 of file tinyxml2.cpp.
References _buffer, _fp, and tinyxml2::DynArray< T, INIT >::PushArr().
Referenced by CloseElement(), OpenElement(), PrintSpace(), PrintString(), PushAttribute(), PushComment(), PushDeclaration(), PushHeader(), PushText(), PushUnknown(), and SealElement().
{
    va_list     va;
    va_start( va, format );
    if ( _fp ) {
        vfprintf( _fp, format, va );
    }
    else {
        // This seems brutally complex. Haven't figured out a better
        // way on windows.
#ifdef _MSC_VER
        int len = -1;
        int expand = 1000;
        while ( len < 0 ) {
            len = vsnprintf_s( _accumulator.Mem(), _accumulator.Capacity(), _TRUNCATE, format, va );
            if ( len < 0 ) {
                expand *= 3/2;
                _accumulator.PushArr( expand );
            }
        }
        char* p = _buffer.PushArr( len ) - 1;
        memcpy( p, _accumulator.Mem(), len+1 );
#else
        int len = vsnprintf( 0, 0, format, va );
        // Close out and re-start the va-args
        va_end( va );
        va_start( va, format );
        char* p = _buffer.PushArr( len ) - 1;
        vsnprintf( p, len+1, format, va );
#endif
    }
    va_end( va );
}
void tinyxml2::XMLPrinter::PrintSpace (int depth) [private]
Definition at line 1796 of file tinyxml2.cpp.
References Print().
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
{
    for( int i=0; i<depth; ++i ) {
        Print( "    " );
    }
}
void tinyxml2::XMLPrinter::PrintString (const char * p, bool restrictedEntitySet) [private]
Definition at line 1804 of file tinyxml2.cpp.
References _entityFlag, _processEntities, _restrictedEntityFlag, tinyxml2::entities, ENTITY_RANGE, tinyxml2::NUM_ENTITIES, and Print().
Referenced by PushAttribute(), and PushText().
{
    // Look for runs of bytes between entities to print.
    const char* q = p;
    const bool* flag = restricted ? _restrictedEntityFlag : _entityFlag;
    if ( _processEntities ) {
        while ( *q ) {
            // Remember, char is sometimes signed. (How many times has that bitten me?)
            if ( *q > 0 && *q < ENTITY_RANGE ) {
                // Check for entities. If one is found, flush
                // the stream up until the entity, write the
                // entity, and keep looking.
                if ( flag[(unsigned)(*q)] ) {
                    while ( p < q ) {
                        Print( "%c", *p );
                        ++p;
                    }
                    for( int i=0; i<NUM_ENTITIES; ++i ) {
                        if ( entities[i].value == *q ) {
                            Print( "&%s;", entities[i].pattern );
                            break;
                        }
                    }
                    ++p;
                }
            }
            ++q;
        }
    }
    // Flush the remaining string. This will be the entire
    // string if an entity wasn't found.
    if ( !_processEntities || (q-p > 0) ) {
        Print( "%s", p );
    }
}
void tinyxml2::XMLPrinter::PushAttribute (const char * name, const char * value)
If streaming, add an attribute to an open element.
Definition at line 1873 of file tinyxml2.cpp.
References _elementJustOpened, Print(), PrintString(), and TIXMLASSERT.
Referenced by PushAttribute(), and VisitEnter().
{
    TIXMLASSERT( _elementJustOpened );
    Print( " %s=\"", name );
    PrintString( value, false );
    Print( "\"" );
}
void tinyxml2::XMLPrinter::PushAttribute (const char * name, int value)
Definition at line 1882 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( v, buf, BUF_SIZE );
    PushAttribute( name, buf );
}
void tinyxml2::XMLPrinter::PushAttribute (const char * name, unsigned value)
Definition at line 1890 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( v, buf, BUF_SIZE );
    PushAttribute( name, buf );
}
void tinyxml2::XMLPrinter::PushAttribute (const char * name, bool value)
Definition at line 1898 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( v, buf, BUF_SIZE );
    PushAttribute( name, buf );
}
void tinyxml2::XMLPrinter::PushAttribute (const char * name, double value)
Definition at line 1906 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( v, buf, BUF_SIZE );
    PushAttribute( name, buf );
}
void tinyxml2::XMLPrinter::PushComment (const char * comment)
Add a comment.
Definition at line 2004 of file tinyxml2.cpp.
References _compactMode, _depth, _elementJustOpened, _firstElement, _textDepth, Print(), PrintSpace(), and SealElement().
Referenced by Visit().
{
    if ( _elementJustOpened ) {
        SealElement();
    }
    if ( _textDepth < 0 && !_firstElement && !_compactMode) {
        Print( "\n" );
        PrintSpace( _depth );
    }
    _firstElement = false;
    Print( "<!--%s-->", comment );
}
void tinyxml2::XMLPrinter::PushDeclaration (const char * value)
Definition at line 2018 of file tinyxml2.cpp.
References _compactMode, _depth, _elementJustOpened, _firstElement, _textDepth, Print(), PrintSpace(), and SealElement().
Referenced by PushHeader(), and Visit().
{
    if ( _elementJustOpened ) {
        SealElement();
    }
    if ( _textDepth < 0 && !_firstElement && !_compactMode) {
        Print( "\n" );
        PrintSpace( _depth );
    }
    _firstElement = false;
    Print( "<?%s?>", value );
}
void tinyxml2::XMLPrinter::PushHeader (bool writeBOM, bool writeDeclaration)
If streaming, write the BOM and declaration.
Definition at line 1842 of file tinyxml2.cpp.
References Print(), PushDeclaration(), TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, and TIXML_UTF_LEAD_2.
Referenced by VisitEnter().
{
    static const unsigned char bom[] = { TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, 0 };
    if ( writeBOM ) {
        Print( "%s", bom );
    }
    if ( writeDec ) {
        PushDeclaration( "xml version=\"1.0\"" );
    }
}
void tinyxml2::XMLPrinter::PushText (const char * text, bool cdata = false)
Add a text node.
Definition at line 1947 of file tinyxml2.cpp.
References _depth, _elementJustOpened, _textDepth, Print(), PrintString(), and SealElement().
Referenced by PushText(), and Visit().
{
    _textDepth = _depth-1;
    if ( _elementJustOpened ) {
        SealElement();
    }
    if ( cdata ) {
        Print( "<![CDATA[" );
        Print( "%s", text );
        Print( "]]>" );
    }
    else {
        PrintString( text, true );
    }
}
void tinyxml2::XMLPrinter::PushText (int value)
Add a text node from an integer.
Definition at line 1964 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( value, buf, BUF_SIZE );
    PushText( buf, false );
}
void tinyxml2::XMLPrinter::PushText (unsigned value)
Add a text node from an unsigned.
Definition at line 1972 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( value, buf, BUF_SIZE );
    PushText( buf, false );
}
void tinyxml2::XMLPrinter::PushText (bool value)
Add a text node from a bool.
Definition at line 1980 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( value, buf, BUF_SIZE );
    PushText( buf, false );
}
void tinyxml2::XMLPrinter::PushText (float value)
Add a text node from a float.
Definition at line 1988 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( value, buf, BUF_SIZE );
    PushText( buf, false );
}
void tinyxml2::XMLPrinter::PushText (double value)
Add a text node from a double.
Definition at line 1996 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
{
    char buf[BUF_SIZE];
    XMLUtil::ToStr( value, buf, BUF_SIZE );
    PushText( buf, false );
}
void tinyxml2::XMLPrinter::PushUnknown (const char * value)
Definition at line 2032 of file tinyxml2.cpp.
References _compactMode, _depth, _elementJustOpened, _firstElement, _textDepth, Print(), PrintSpace(), and SealElement().
Referenced by Visit().
{
    if ( _elementJustOpened ) {
        SealElement();
    }
    if ( _textDepth < 0 && !_firstElement && !_compactMode) {
        Print( "\n" );
        PrintSpace( _depth );
    }
    _firstElement = false;
    Print( "<!%s>", value );
}
void tinyxml2::XMLPrinter::SealElement () [private]
Definition at line 1940 of file tinyxml2.cpp.
References _elementJustOpened, and Print().
Referenced by OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
{
    _elementJustOpened = false;
    Print( ">" );
}
bool tinyxml2::XMLPrinter::Visit (const XMLText &) [virtual]
Visit a text node.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2074 of file tinyxml2.cpp.
References tinyxml2::XMLText::CData(), PushText(), and tinyxml2::XMLNode::Value().
{
    PushText( text.Value(), text.CData() );
    return true;
}
bool tinyxml2::XMLPrinter::Visit (const XMLComment &) [virtual]
Visit a comment node.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2081 of file tinyxml2.cpp.
References PushComment(), and tinyxml2::XMLNode::Value().
{
    PushComment( comment.Value() );
    return true;
}
bool tinyxml2::XMLPrinter::Visit (const XMLDeclaration &) [virtual]
Visit a declaration.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2087 of file tinyxml2.cpp.
References PushDeclaration(), and tinyxml2::XMLNode::Value().
{
    PushDeclaration( declaration.Value() );
    return true;
}
bool tinyxml2::XMLPrinter::Visit (const XMLUnknown &) [virtual]
Visit an unknown node.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2094 of file tinyxml2.cpp.
References PushUnknown(), and tinyxml2::XMLNode::Value().
{
    PushUnknown( unknown.Value() );
    return true;
}
bool tinyxml2::XMLPrinter::VisitEnter (const XMLDocument &) [virtual]
Visit a document.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2046 of file tinyxml2.cpp.
References _processEntities, tinyxml2::XMLDocument::HasBOM(), tinyxml2::XMLDocument::ProcessEntities(), and PushHeader().
{
    _processEntities = doc.ProcessEntities();
    if ( doc.HasBOM() ) {
        PushHeader( true, false );
    }
    return true;
}
bool tinyxml2::XMLPrinter::VisitEnter (const XMLElement & , const XMLAttribute *) [virtual]
Visit an element.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2056 of file tinyxml2.cpp.
References tinyxml2::XMLAttribute::Name(), tinyxml2::XMLElement::Name(), tinyxml2::XMLAttribute::Next(), OpenElement(), PushAttribute(), and tinyxml2::XMLAttribute::Value().
{
    OpenElement( element.Name() );
    while ( attribute ) {
        PushAttribute( attribute->Name(), attribute->Value() );
        attribute = attribute->Next();
    }
    return true;
}
virtual bool tinyxml2::XMLPrinter::VisitExit (const XMLDocument &) [inline, virtual]
Visit a document.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 1852 of file tinyxml2.h.
{
        return true;
    }
bool tinyxml2::XMLPrinter::VisitExit (const XMLElement &) [virtual]
Visit an element.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2067 of file tinyxml2.cpp.
References CloseElement().
{
    CloseElement();
    return true;
}
Member Data Documentation
DynArray< char, 20 > tinyxml2::XMLPrinter::_buffer [private]
Definition at line 1902 of file tinyxml2.h.
Referenced by CStr(), CStrSize(), Print(), and XMLPrinter().
bool tinyxml2::XMLPrinter::_compactMode [private]
Definition at line 1892 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
int tinyxml2::XMLPrinter::_depth [private]
Definition at line 1889 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
bool tinyxml2::XMLPrinter::_elementJustOpened [private]
Definition at line 1886 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushAttribute(), PushComment(), PushDeclaration(), PushText(), PushUnknown(), and SealElement().
bool tinyxml2::XMLPrinter::_entityFlag[ENTITY_RANGE] [private]
Definition at line 1898 of file tinyxml2.h.
Referenced by PrintString(), and XMLPrinter().
bool tinyxml2::XMLPrinter::_firstElement [private]
Definition at line 1887 of file tinyxml2.h.
Referenced by OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
std::FILE* tinyxml2::XMLPrinter::_fp [private]
Definition at line 1888 of file tinyxml2.h.
Referenced by Print().
bool tinyxml2::XMLPrinter::_processEntities [private]
Definition at line 1891 of file tinyxml2.h.
Referenced by PrintString(), and VisitEnter().
bool tinyxml2::XMLPrinter::_restrictedEntityFlag[ENTITY_RANGE] [private]
Definition at line 1899 of file tinyxml2.h.
Referenced by PrintString(), and XMLPrinter().
DynArray< const char*, 10 > tinyxml2::XMLPrinter::_stack [private]
Definition at line 1901 of file tinyxml2.h.
Referenced by CloseElement(), and OpenElement().
int tinyxml2::XMLPrinter::_textDepth [private]
Definition at line 1890 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
The documentation for this class was generated from the following files:
core/tinyxml/tinyxml2.h
core/tinyxml/tinyxml2.cpp