DeepView: OpenCVFilterParameters Class Reference
OpenCVFilterParameters Class Reference
OpenCV Filter Parameters OpenCV Filter Parameters.
#include <openCVFilterParameters.h>
Public Types
enum FieldId { OPENCVFILTER_ID, PARAM1_ID, PARAM2_ID, OPENCV_FILTER_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
OpenCVBinaryFilterType::OpenCVBinaryFilterType openCVFilter () const
int param1 () const
int param2 () const
void setOpenCVFilter (OpenCVBinaryFilterType::OpenCVBinaryFilterType openCVFilter)
void setParam1 (int param1)
void setParam2 (int param2)
template<class VisitorType >
void accept (VisitorType &visitor)
OpenCVFilterParameters ()
OpenCVFilterParameters (OpenCVBinaryFilterType::OpenCVBinaryFilterType openCVFilter, int param1, int param2)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mOpenCVFilter
Section with variables.
int mParam1
Param1 Param1.
int mParam2
Param2 Param2.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, OpenCVFilterParameters &toSave)
Detailed Description
OpenCV Filter Parameters OpenCV Filter Parameters.
Definition at line 39 of file openCVFilterParameters.h.
Member Enumeration Documentation
enum OpenCVFilterParameters::FieldId
Enumerator:
OPENCVFILTER_ID
PARAM1_ID
PARAM2_ID
OPENCV_FILTER_PARAMETERS_FIELD_ID_NUM
Definition at line 42 of file openCVFilterParameters.h.
                 {
        OPENCVFILTER_ID,
        PARAM1_ID,
        PARAM2_ID,
        OPENCV_FILTER_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
OpenCVFilterParameters::OpenCVFilterParameters () [inline]
Definition at line 118 of file openCVFilterParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
OpenCVFilterParameters::OpenCVFilterParameters (OpenCVBinaryFilterType::OpenCVBinaryFilterType openCVFilter, int param1, int param2) [inline]
Definition at line 124 of file openCVFilterParameters.h.
    {
        mOpenCVFilter = openCVFilter;
        mParam1 = param1;
        mParam2 = param2;
    }
Member Function Documentation
template<class VisitorType > void OpenCVFilterParameters::accept (VisitorType & visitor) [inline]
Definition at line 111 of file openCVFilterParameters.h.
    {
        visitor.visit((int &)mOpenCVFilter,       static_cast<const EnumField *>    (fields()[OPENCVFILTER_ID]));
        visitor.visit(mParam1,                    static_cast<const IntField *>     (fields()[PARAM1_ID]));
        visitor.visit(mParam2,                    static_cast<const IntField *>     (fields()[PARAM2_ID]));
    }
static const char* corecvs::BaseReflection< OpenCVFilterParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< OpenCVFilterParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< OpenCVFilterParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* OpenCVFilterParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 73 of file openCVFilterParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< OpenCVFilterParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< OpenCVFilterParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< OpenCVFilterParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
OpenCVBinaryFilterType::OpenCVBinaryFilterType OpenCVFilterParameters::openCVFilter () const [inline]
Definition at line 77 of file openCVFilterParameters.h.
Referenced by OpenCVFilterParametersControlWidget::setParameters().
    {
        return static_cast<OpenCVBinaryFilterType::OpenCVBinaryFilterType>(mOpenCVFilter);
    }
int OpenCVFilterParameters::param1 () const [inline]
Definition at line 82 of file openCVFilterParameters.h.
Referenced by OpenCVFilter::operator()(), and OpenCVFilterParametersControlWidget::setParameters().
    {
        return mParam1;
    }
int OpenCVFilterParameters::param2 () const [inline]
Definition at line 87 of file openCVFilterParameters.h.
Referenced by OpenCVFilter::operator()(), and OpenCVFilterParametersControlWidget::setParameters().
    {
        return mParam2;
    }
void OpenCVFilterParameters::print () [inline]
Definition at line 142 of file openCVFilterParameters.h.
    {
        cout << *this;
    }
void OpenCVFilterParameters::setOpenCVFilter (OpenCVBinaryFilterType::OpenCVBinaryFilterType openCVFilter) [inline]
Definition at line 93 of file openCVFilterParameters.h.
    {
        mOpenCVFilter = openCVFilter;
    }
void OpenCVFilterParameters::setParam1 (int param1) [inline]
Definition at line 98 of file openCVFilterParameters.h.
    {
        mParam1 = param1;
    }
void OpenCVFilterParameters::setParam2 (int param2) [inline]
Definition at line 103 of file openCVFilterParameters.h.
    {
        mParam2 = param2;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int OpenCVFilterParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file openCVFilterParameters.cpp.
References corecvs::BaseReflection< OpenCVFilterParameters >::fields(), mOpenCVFilter, mParam1, mParam2, corecvs::BaseReflection< OpenCVFilterParameters >::naming(), OPENCVFILTER_ID, PARAM1_ID, and PARAM2_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "OpenCV Filter Parameters",
        "OpenCV Filter Parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          OpenCVFilterParameters::OPENCVFILTER_ID,
          offsetof(OpenCVFilterParameters, mOpenCVFilter),
          0,
          "OpenCVFilter",
          "OpenCVFilter",
          "OpenCVFilter",
           NULL
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVFilterParameters::PARAM1_ID,
          offsetof(OpenCVFilterParameters, mParam1),
          50,
          "Param1",
          "Param1",
          "Param1"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVFilterParameters::PARAM2_ID,
          offsetof(OpenCVFilterParameters, mParam2),
          100,
          "Param2",
          "Param2",
          "Param2"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, OpenCVFilterParameters & toSave) [friend]
Definition at line 135 of file openCVFilterParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< OpenCVFilterParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int OpenCVFilterParameters::mOpenCVFilter
Section with variables.
OpenCVFilter OpenCVFilter
Definition at line 55 of file openCVFilterParameters.h.
Referenced by staticInit().
int OpenCVFilterParameters::mParam1
Param1 Param1.
Definition at line 61 of file openCVFilterParameters.h.
Referenced by staticInit().
int OpenCVFilterParameters::mParam2
Param2 Param2.
Definition at line 67 of file openCVFilterParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< OpenCVFilterParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/openCVFilterParameters.h
core/xml/generated/openCVFilterParameters.cpp