DeepView: RecorderDialog Class Reference
RecorderDialog Class Reference
#include <recorderDialog.h>
Public Slots
void openPathSelectDialog ()
void toggleRecording ()
void resetRecording ()
void recordingStateChanged (RecorderThread::RecordingState)
void recorderControlParametersChanged (QSharedPointer< Recorder > params)
virtual void processResult ()
void errorMessage (QString message)
void baseControlParametersChanged (QSharedPointer< BaseParameters > params)
void presentationControlParametersChanged (QSharedPointer< PresentationParameters > params)
void showStatistics ()
void showCaptureSettings ()
void showAboutDialog ()
void showInputSelectorDialog ()
void showDistortionCorrectorDialog ()
void showCameraCalculatorDialog ()
void doOpenInput ()
virtual void doLoadParams ()
virtual void doSaveParams ()
void toggleAdvanced (bool off)
Signals
void recordingTriggered ()
void recordingReset ()
void camerasParametersChanged (QSharedPointer< CamerasConfigParameters > parametersShPtr)
void pauseCalculator ()
void resumeCalculator ()
void captureStatusUpdated (bool isOn)
void singleStepStatusUpdated ()
void updatePauseCalculationAction (bool)
void emptyString ()
void filterControlParametersChanged (Frames::FrameSourceId id, QSharedPointer< FilterSelectorParameters > params)
Public Member Functions
RecorderDialog ()
~RecorderDialog ()
virtual void initParameterWidgets ()
Initialize widgets that should be in BaseHostDialog.
virtual void createCalculator ()
In this function calculator is created and connected to parameter Widgets Normally you should overload it.
virtual void connectFinishedRecalculation ()
void init (QWidget *parameterHolderWidget, QTextEdit *loggerWidget=NULL)
This method will do the following and need to be called once!
void initGraphPresentation ()
virtual void deinit ()
Call to teardown the object.
void initCapture (QString const &initString=QString(), bool isRgb=false)
virtual QList< QMenu * > additionalMenus ()
virtual QString windowTitle () const
void setAutoExit (int autoexit)
Protected Types
enum WindowType {
ownerControlledWindow, imageWindow, textWindow, oglWindow,
graphWindow
}
Protected Slots
void mouseChild (QMouseEvent *event)
virtual void camerasParamsChanged ()
virtual void play ()
Starts both capture and processing.
virtual void calculationStateChanged (AbstractCalculationThread::CalculationState state)
virtual void finishedRecalculation (AbstractOutputData *fod)
Add all events to the list, and if we are not still collecting them - process the whole list.
virtual void doLoadTransform ()
virtual void doSaveTransform ()
void stopCapture ()
void nextFrame ()
void updateWidgets ()
void setCaptureStats (CaptureStatistics stats)
Protected Member Functions
virtual CamerasConfigParameters * getAdditionalParams () const
virtual void connectFinishedRecalculation () const
virtual void initCommon ()
Initialization steps that are likely, however not mandatory to be used in specific application dialogs using BaseHostDialog as their parent class.
virtual void initCalculator ()
Calculation initialization procedures.
virtual void terminateCalculator ()
during the process of the destruction you need to make sure that the thread object is killed before deiniting all the objects that are referenced be it.
virtual void loadParams (const QString &fileName, QString root)
virtual void saveParams (const QString &fileName, QString root)
void loadTransformFromFile (QString const &filename)
void saveTransformToFile (QString const &filename)
virtual QWidget * dockWidget ()
QtStatisticsCollector * statisticsCollector ()
ViAreaWidget * createAdditionalWindow (QString const &name, WindowType type, const QIcon &icon=QIcon())
ViAreaWidget * addAdditionalWindow (QString const &name, ViAreaWidget *area, const QIcon &icon)
void cleanupEventQueue (void)
void stopCalculation ()
void deinitCamera ()
Protected Attributes
QObject * mParamsMapper
AbstractCalculationThread * mCalculator
RectificationResult mRectifierData
QSharedPointer< QImage > mImage
Ui::HostDialogStubClass mUi
bool mUseOneCaptureDevice
DistortionWidget * mDistortionWidget
CameraCalculatorWidget mCameraCalculatorWidget
bool mCameraStarted
ImageCaptureInterface * mCamera
CapSettingsDialog * mCapSettings
Frames * mFrames
StatisticsDialog mStatsDialog
BaseParametersControlWidget * mBaseControlWidget
PresentationParametersControlWidget * mPresentationControlWidget
QSharedPointer< BaseParameters > mBaseParams
QSharedPointer
< PresentationParameters > mPresentationParams
FilterGraphPresentation * mFilterGraphPresentation
QHash< QString, ViAreaWidget * > mWidgets
QMenu * mAdditionalTools
vector< SaveableWidget * > mSaveableWidgets
Widgets that delegates BaseHostDialog right to save and load them.
vector< SaveableWidget * > mSaveableCameraWidgets
Camera-dependent widgets that delegate BaseHostDialog right to save and load them.
QTimer mMemoryTimer
Timer that will fire when it's time to check the memory consumption.
MemoryUsageCalculator * mMemoryCalculator
Object that checks memory consumption.
QWidget * mDockWidget
QTextEdit * mLoggerWidget
bool mScheduledSwap
QString mInputString
int collectingEvents
Variables to handle overfill of the draw queue collectingEvents is true when we are adding the result to local queue to process, and false when we actually processing it.
vector< AbstractOutputData * > eventList
Queue that holds draw requests.
int autoExitCount
FilterPresentationsCollection * mFilterPresentationsCollection
Private Attributes
bool mIsRecording
RecorderControlWidget * mRecorderControlWidget
QSharedPointer< Recorder > mRecorderControlParams
Detailed Description
Definition at line 22 of file recorderDialog.h.
Member Enumeration Documentation
enum BaseHostDialog::WindowType [protected, inherited]
Enumerator:
ownerControlledWindow
imageWindow
textWindow
oglWindow
graphWindow
Definition at line 230 of file baseHostDialog.h.
                    {
        ownerControlledWindow,
        imageWindow,
        textWindow,
        oglWindow,
        graphWindow
    };
Constructor & Destructor Documentation
RecorderDialog::RecorderDialog ()
Definition at line 18 of file recorderDialog.cpp.
    : BaseHostDialog(),
      mIsRecording(false),
      mRecorderControlWidget(NULL)
{
//    this->resize(this->width(), this->height() - 65);
}
RecorderDialog::~RecorderDialog ()
Definition at line 27 of file recorderDialog.cpp.
References BaseHostDialog::cleanupEventQueue(), and BaseHostDialog::terminateCalculator().
{
    terminateCalculator();
    cleanupEventQueue();
}
Member Function Documentation
ViAreaWidget * BaseHostDialog::addAdditionalWindow (QString const & name, ViAreaWidget * area, const QIcon & icon) [protected, inherited]
Definition at line 701 of file baseHostDialog.cpp.
References BaseHostDialog::mAdditionalTools, and BaseHostDialog::mWidgets.
Referenced by BaseHostDialog::createAdditionalWindow().
{
    mWidgets[name] = area;
    area->setAccessibleName(name);
    area->setWindowTitle(name);
    area->setWindowIcon(icon);
    area->setGeometry(0, 0, 800, 600);
    area->hide();
    QAction *action = mAdditionalTools->addAction(icon, name);
    connect(action, SIGNAL(triggered()), area, SLOT(show()));
    connect(action, SIGNAL(triggered()), area, SLOT(raise()));
    return area;
}
QList< QMenu * > BaseHostDialog::additionalMenus () [virtual, inherited]
Definition at line 928 of file baseHostDialog.cpp.
References BaseHostDialog::mAdditionalTools.
Referenced by MainWindow::createAdditionalMenu().
{
    QList<QMenu *> menus;
    menus << mAdditionalTools;
    return menus;
}
void BaseHostDialog::baseControlParametersChanged (QSharedPointer< BaseParameters > params) [slot, inherited]
Definition at line 184 of file baseHostDialog.cpp.
References BaseHostDialog::camerasParamsChanged(), BaseHostDialog::mBaseParams, BaseHostDialog::mFrames, BaseHostDialog::mScheduledSwap, and BaseHostDialog::swapCameras().
Referenced by createCalculator(), and BaseHostDialog::createCalculator().
{
    // check if we should swap frames
    if (params.isNull()) {
        return;
    }
    if (((!mBaseParams.isNull() && params->swapCameras() != mBaseParams->swapCameras()) || mBaseParams.isNull())
    )
    {
        if (mFrames == NULL)
        {
            mScheduledSwap = true; // should schedule swap if we can't perform it now
        }
        swapCameras(params->swapCameras());
    }
    mBaseParams = params;
    camerasParamsChanged(); // FIXME: should it be here?
}
void BaseHostDialog::calculationStateChanged (AbstractCalculationThread::CalculationState state) [protected, virtual, slot, inherited]
Definition at line 632 of file baseHostDialog.cpp.
References AbstractCalculationThread::stateNames.
Referenced by BaseHostDialog::initCalculator().
{
    printf("Calculation state changed: %d (%s)\n", state, AbstractCalculationThread::stateNames[state]);
}
void BaseHostDialog::camerasParametersChanged (QSharedPointer< CamerasConfigParameters > parametersShPtr) [signal, inherited]
Referenced by BaseHostDialog::camerasParamsChanged(), and BaseHostDialog::initCalculator().
void BaseHostDialog::camerasParamsChanged () [protected, virtual, slot, inherited]
Definition at line 642 of file baseHostDialog.cpp.
References BaseHostDialog::camerasParametersChanged(), and BaseHostDialog::getAdditionalParams().
Referenced by BaseHostDialog::baseControlParametersChanged(), BaseHostDialog::distortionEstimationFinished(), BaseHostDialog::initCapture(), and BaseHostDialog::loadTransformFromFile().
{
    qDebug("BaseHostDialog::camerasParamsChanged(): called");
    QSharedPointer<CamerasConfigParameters> parametersShPtr = QSharedPointer<CamerasConfigParameters>(getAdditionalParams());
    emit camerasParametersChanged(parametersShPtr);
}
void BaseHostDialog::captureStatusUpdated (bool isOn) [signal, inherited]
Referenced by BaseHostDialog::deinitCamera(), BaseHostDialog::initCapture(), and BaseHostDialog::initCommon().
void BaseHostDialog::cleanupEventQueue (void) [protected, inherited]
Delete unprocessed results. Some can still be on the input queue...
Definition at line 564 of file baseHostDialog.cpp.
References BaseHostDialog::collectingEvents, and BaseHostDialog::eventList.
Referenced by BaseHostDialog::deinit(), and ~RecorderDialog().
{
    /**
    * Delete unprocessed results. Some can still be on the input queue...
    **/
    collectingEvents = true;
    QCoreApplication::processEvents();
    for (unsigned i = 0; i < eventList.size(); i++)
    {
        delete_safe(eventList[i]);
    }
    eventList.clear();
}
void RecorderDialog::connectFinishedRecalculation () [virtual]
Definition at line 100 of file recorderDialog.cpp.
References BaseHostDialog::finishedRecalculation(), BaseHostDialog::mCalculator, and BaseHostDialog::play().
{
    RecorderThread *calculator = dynamic_cast<RecorderThread *>(mCalculator);
    if (calculator)
    {
        connect(calculator, SIGNAL(processingFinished(AbstractOutputData *)),
                this, SLOT(finishedRecalculation(AbstractOutputData *)), Qt::QueuedConnection);
        play();
    }
}
void BaseHostDialog::connectFinishedRecalculation () const [protected, virtual, inherited]
Definition at line 487 of file baseHostDialog.cpp.
References BaseHostDialog::finishedRecalculation(), and BaseHostDialog::mCalculator.
Referenced by BaseHostDialog::initCalculator().
{
    connect(mCalculator, SIGNAL(processingFinished(AbstractOutputData *)),
            this, SLOT(finishedRecalculation(AbstractOutputData *)), Qt::QueuedConnection);
}
ViAreaWidget * BaseHostDialog::createAdditionalWindow (QString const & name, WindowType type, const QIcon & icon = QIcon()) [protected, inherited]
Definition at line 717 of file baseHostDialog.cpp.
References BaseHostDialog::addAdditionalWindow(), BaseHostDialog::graphWindow, BaseHostDialog::imageWindow, BaseHostDialog::mSaveableWidgets, BaseHostDialog::oglWindow, BaseHostDialog::ownerControlledWindow, GraphPlotDialog::setSavingRoot(), AdvancedImageWidget::setSavingRoot(), and BaseHostDialog::textWindow.
{
    ViAreaWidget *area = NULL;
    switch (type)
    {
        case ownerControlledWindow:
            area = new ViAreaWidget();
            break;
        case imageWindow:
        {
            AdvancedImageWidget *widget = new AdvancedImageWidget();
            widget->setSavingRoot(name);
            mSaveableWidgets.push_back(widget);
            area = widget;
            break;
        }
        case textWindow:
            area = new TextLabelWidget();
            break;
        case oglWindow:
            area = new CloudViewDialog();
            break;
        case graphWindow:
        default:
        {
            GraphPlotDialog *widget = new GraphPlotDialog();
            widget->setSavingRoot(name);
            mSaveableWidgets.push_back(widget);
            area = widget;
        }
        break;
    }
    return addAdditionalWindow(name, area, icon);
}
void RecorderDialog::createCalculator () [virtual]
In this function calculator is created and connected to parameter Widgets Normally you should overload it.
Reimplemented from BaseHostDialog.
Definition at line 48 of file recorderDialog.cpp.
References BaseHostDialog::baseControlParametersChanged(), errorMessage(), BaseHostDialog::mBaseControlWidget, BaseHostDialog::mCalculator, BaseHostDialog::mParamsMapper, BaseHostDialog::mPresentationControlWidget, mRecorderControlWidget, ParametersMapperRecorder::paramsChanged(), BaseHostDialog::presentationControlParametersChanged(), recorderControlParametersChanged(), recordingStateChanged(), recordingTriggered(), resetRecording(), ParametersMapperRecorder::setBaseParametersControlWidget(), ParametersMapperRecorder::setPresentationParametersControlWidget(), ParametersMapperRecorder::setRecorderControlWidget(), toggleRecording(), and RecorderControlWidget::ui().
{
    ParametersMapperRecorder *mapper = new ParametersMapperRecorder();
    mapper->setRecorderControlWidget(mRecorderControlWidget);
    mapper->setBaseParametersControlWidget(mBaseControlWidget);
    mapper->setPresentationParametersControlWidget(mPresentationControlWidget);
    connect(mapper, SIGNAL(recorderParamsChanged(QSharedPointer<Recorder>))
            , this, SLOT(recorderControlParametersChanged(QSharedPointer<Recorder>)));
  /*  connect(mapper, SIGNAL(baseParametersParamsChanged(QSharedPointer<BaseParameters>))
            , this, SLOT(baseControlParametersChanged(QSharedPointer<Base>)));*/
    mCalculator = new RecorderThread();
    connect(mapper, SIGNAL(baseParametersParamsChanged(QSharedPointer<BaseParameters>))
            , static_cast<RecorderThread*>(mCalculator)
            , SLOT(baseControlParametersChanged(QSharedPointer<BaseParameters>)));
    connect(mapper, SIGNAL(recorderParamsChanged(QSharedPointer<Recorder>))
            , static_cast<RecorderThread*>(mCalculator)
            , SLOT(recorderControlParametersChanged(QSharedPointer<Recorder>)));
    connect(mapper, SIGNAL(presentationParametersParamsChanged(QSharedPointer<PresentationParameters>))
            , static_cast<RecorderThread*>(mCalculator)
            , SLOT(presentationControlParametersChanged(QSharedPointer<PresentationParameters>)));
    mapper->paramsChanged();
    mParamsMapper = mapper;
    connect(this, SIGNAL(recordingTriggered()), mCalculator, SLOT(toggleRecording()), Qt::QueuedConnection);
    connect(mRecorderControlWidget->ui()->recRestartButton, SIGNAL(released()), mCalculator, SLOT(resetRecording()), Qt::QueuedConnection);
    connect(mRecorderControlWidget->ui()->recPauseButton, SIGNAL(released()), mCalculator, SLOT(toggleRecording()), Qt::QueuedConnection);
    connect(mCalculator, SIGNAL(recordingStateChanged(RecorderThread::RecordingState)), this,
            SLOT(recordingStateChanged(RecorderThread::RecordingState)), Qt::QueuedConnection);
    connect(mCalculator, SIGNAL(errorMessage(QString)),
            this,        SLOT  (errorMessage(QString)), Qt::BlockingQueuedConnection);
}
void BaseHostDialog::deinit () [virtual, inherited]
Call to teardown the object.
it stops all child threads and flushes the event queue
Definition at line 111 of file baseHostDialog.cpp.
References BaseHostDialog::cleanupEventQueue(), ConfigManager::configName(), BaseHostDialog::saveParams(), and BaseHostDialog::terminateCalculator().
Referenced by MainWindow::~MainWindow().
{
    /* Stop all possible events sources */
    saveParams(ConfigManager::configName(), "");
    terminateCalculator();
    /* Cleanup the queue */
    cleanupEventQueue();
}
void BaseHostDialog::deinitCamera () [protected, inherited]
Definition at line 294 of file baseHostDialog.cpp.
References BaseHostDialog::captureStatusUpdated(), BaseHostDialog::mCamera, and BaseHostDialog::mCameraStarted.
Referenced by BaseHostDialog::initCapture().
{
    delete_safe(mCamera);
    mCameraStarted = false;
    emit captureStatusUpdated(false);
}
QWidget * BaseHostDialog::dockWidget () [protected, virtual, inherited]
Definition at line 940 of file baseHostDialog.cpp.
References BaseHostDialog::mDockWidget.
Referenced by initParameterWidgets(), BaseHostDialog::initParameterWidgets(), and BaseHostDialog::toggleAdvanced().
{
    return mDockWidget;
}
void BaseHostDialog::doLoadParams () [virtual, slot, inherited]
Definition at line 759 of file baseHostDialog.cpp.
References BaseHostDialog::loadParams().
{
    QString filename = QFileDialog::getOpenFileName(
        this,
        "Choose an file name",
        ".",
        "Text (*.txt *.conf *.ini)"
        );
    loadParams(filename, "");
}
void BaseHostDialog::doLoadTransform () [protected, virtual, slot, inherited]
Definition at line 886 of file baseHostDialog.cpp.
References BaseHostDialog::loadTransformFromFile().
{
    /*Get file name*/
    QString filename = QFileDialog::getOpenFileName(
            this,
            "Choose an file name",
            ".",
            "Text (*.txt )"
            );
    loadTransformFromFile(filename);
}
void BaseHostDialog::doOpenInput () [slot, inherited]
Definition at line 210 of file baseHostDialog.cpp.
References InputSelectorWidget::getInputString(), BaseHostDialog::initCapture(), BaseHostDialog::mInputSelectorDialog, BaseHostDialog::stopCalculation(), and BaseHostDialog::stopCapture().
Referenced by BaseHostDialog::initCommon().
{
    //QMessageBox::information(this, "We will be opening the input", mInputSelectorDialog.getInputString());
    stopCapture();
    stopCalculation();
    initCapture(mInputSelectorDialog.getInputString());
}
void BaseHostDialog::doSaveParams () [virtual, slot, inherited]
Definition at line 771 of file baseHostDialog.cpp.
References BaseHostDialog::saveParams().
{
    QString filename = QFileDialog::getOpenFileName(
        this,
        "Choose an file name",
        ".",
        "Text (*.txt *.conf *.ini)"
        );
    saveParams(filename, "");
}
void BaseHostDialog::doSaveTransform () [protected, virtual, slot, inherited]
Definition at line 899 of file baseHostDialog.cpp.
References BaseHostDialog::saveTransformToFile().
{
    /*Get file name*/
    QString filename = QFileDialog::getOpenFileName(
            this,
            "Choose an file name",
            ".",
            "Text (*.txt )"
            );
    saveTransformToFile(filename);
}
void BaseHostDialog::emptyString () [signal, inherited]
Referenced by BaseHostDialog::initCapture().
void RecorderDialog::errorMessage (QString message) [slot]
Definition at line 195 of file recorderDialog.cpp.
Referenced by createCalculator().
{
    QMessageBox msgBox;
    msgBox.setText(message);
    msgBox.exec();
}
void BaseHostDialog::filterControlParametersChanged (Frames::FrameSourceId id, QSharedPointer< FilterSelectorParameters > params) [signal, inherited]
Referenced by BaseHostDialog::createCalculator().
void BaseHostDialog::finishedRecalculation (AbstractOutputData * fod) [protected, virtual, slot, inherited]
Add all events to the list, and if we are not still collecting them - process the whole list.
Definition at line 498 of file baseHostDialog.cpp.
References BaseHostDialog::autoExitCount, BaseHostDialog::collectingEvents, BaseHostDialog::eventList, BaseHostDialog::mBaseParams, BaseHostDialog::mScheduledSwap, BaseHostDialog::processResult(), and BaseHostDialog::swapCameras().
Referenced by connectFinishedRecalculation(), and BaseHostDialog::connectFinishedRecalculation().
{
    if (autoExitCount != -1)
    {
        static int stopcount = autoExitCount;
        if (stopcount <= 0)
        {
            printf("Exiting because of auto-exit option\n");
            QApplication::quit();
        }
        stopcount--;
    }
    if (mScheduledSwap && !mBaseParams.isNull())
    {
        swapCameras(mBaseParams->swapCameras());
        mScheduledSwap = false;
    }
    if (abstractOutputData != NULL)
    {
        eventList.push_back(abstractOutputData);
    }
    if (!collectingEvents)
    {
        collectingEvents = true;
        QCoreApplication::processEvents();
        collectingEvents = false;
        processResult();
        eventList.clear();
    }
}
CamerasConfigParameters * BaseHostDialog::getAdditionalParams () const [protected, virtual, inherited]
Definition at line 650 of file baseHostDialog.cpp.
References BaseHostDialog::mDistortionTransform, BaseHostDialog::mRectifierData, BaseHostDialog::mUseOneCaptureDevice, CamerasConfigParameters::OneCapDev, CamerasConfigParameters::setDistortionTransform(), CamerasConfigParameters::setInputsN(), CamerasConfigParameters::setRectifierData(), and CamerasConfigParameters::TwoCapDev.
Referenced by BaseHostDialog::camerasParamsChanged().
{
    CamerasConfigParameters  *fp = new CamerasConfigParameters ();
    fp->setInputsN(mUseOneCaptureDevice ? CamerasConfigParameters::OneCapDev : CamerasConfigParameters::TwoCapDev);
    fp->setRectifierData(mRectifierData);
    fp->setDistortionTransform(mDistortionTransform);
    return fp;
}
void BaseHostDialog::init (QWidget * parameterHolderWidget, QTextEdit * loggerWidget = NULL) [inherited]
This method will do the following and need to be called once!
Initialize common UI connect buttons etc (can be overloaded initCommon(QString)))
Initialize internal widgets (can be overloaded initParameterWidgets())
Call to initMemoryUsageCalculator
Initialize calculator (can be overloaded initCalculator())
This dialog creates all internal window structure. Some of the dependant dialogs should have ability to dock, and are brought outside of BaseHostDialog. They should be transfered in this constructor
Definition at line 76 of file baseHostDialog.cpp.
References ConfigManager::configName(), BaseHostDialog::initCalculator(), BaseHostDialog::initCommon(), BaseHostDialog::initGraphPresentation(), BaseHostDialog::initMemoryUsageCalculator(), BaseHostDialog::initParameterWidgets(), L_INFO, BaseHostDialog::loadParams(), BaseHostDialog::loadTransformFromFile(), BaseHostDialog::mDockWidget, and savePath.
Referenced by BaseHostDialog::initCapture(), and MainWindow::MainWindow().
{
    mDockWidget = parameterHolderWidget;
    L_INFO << "ViMouse started" << "\n" << "Log will go here";
    initCommon();
    initParameterWidgets();
    loadParams(ConfigManager::configName(), "");
    initMemoryUsageCalculator();
    initCalculator();
    initGraphPresentation();
    loadTransformFromFile(savePath);
}
void BaseHostDialog::initCalculator () [protected, virtual, inherited]
Calculation initialization procedures.
This function will call createCalculator. Afterwards it makes flow settings and connections and launches the calculator
Note:
The implementation provided by the base class should normally be used, unless you want to change play/pause etc control flow
Starting the thread
Definition at line 446 of file baseHostDialog.cpp.
References BaseHostDialog::calculationStateChanged(), BaseHostDialog::camerasParametersChanged(), BaseHostDialog::connectFinishedRecalculation(), BaseHostDialog::createCalculator(), AbstractCalculationThread::getFramesHolder(), BaseHostDialog::mCalculator, BaseHostDialog::mFrames, BaseHostDialog::pauseCalculator(), BaseHostDialog::resumeCalculator(), and BaseHostDialog::updatePauseCalculationAction().
Referenced by BaseHostDialog::init().
{
    createCalculator();
    mFrames = mCalculator->getFramesHolder();
  //  swapCameras(mBaseControlWidget->ui()->swapCamerasPushButton->isChecked());
    connectFinishedRecalculation();
    qRegisterMetaType<QSharedPointer<CamerasConfigParameters> >("QSharedPointer<CamerasConfigParameters>");
    connect(this, SIGNAL(camerasParametersChanged(QSharedPointer<CamerasConfigParameters>)),
            static_cast<BaseCalculationThread *>(mCalculator), SLOT(camerasParametersChanged(QSharedPointer<CamerasConfigParameters>)),
            Qt::QueuedConnection);
    //qDebug() << "BaseHostDialog:camerasParametersChanged connected" << endl;
    /* Flow controls */
    emit updatePauseCalculationAction(true);
    connect(this, SIGNAL(pauseCalculator ()), mCalculator, SLOT(pauseCalculation()));
    connect(this, SIGNAL(resumeCalculator()), mCalculator, SLOT(resumeCalculation()));
    connect(mCalculator,
        SIGNAL(calculationStateChanged(AbstractCalculationThread::CalculationState)),
        this, SLOT(calculationStateChanged(AbstractCalculationThread::CalculationState)));
    /** Starting the thread */
    mCalculator->start();
}
void BaseHostDialog::initCapture (QString const & initString = QString(), bool isRgb = false) [inherited]
Definition at line 304 of file baseHostDialog.cpp.
References BaseHostDialog::autoExitCount, ConfigManager::camConfigName(), BaseHostDialog::camerasParamsChanged(), BaseHostDialog::captureStatusUpdated(), BaseHostDialog::deinitCamera(), BaseHostDialog::emptyString(), ImageCaptureInterface::fabric(), ImageCaptureInterface::FAILURE, BaseHostDialog::init(), ImageCaptureInterface::initCapture(), CapSettingsDialog::loadFromQSettings(), BaseHostDialog::mCalculator, BaseHostDialog::mCamera, BaseHostDialog::mCapSettings, BaseHostDialog::mInputSelectorDialog, BaseHostDialog::mInputString, BaseHostDialog::mPresentationControlWidget, BaseHostDialog::mSaveableCameraWidgets, BaseHostDialog::mUseOneCaptureDevice, BaseHostDialog::setCaptureStats(), AbstractCalculationThread::setImageCaptureInterface(), InputSelectorWidget::setInputString(), BaseHostDialog::singleStepStatusUpdated(), BaseHostDialog::stopCapture(), ImageCaptureInterface::SUCCESS_1CAM, and PresentationParametersControlWidget::ui().
Referenced by BaseHostDialog::doOpenInput(), and MainWindow::MainWindow().
{
    //TODO:: if mInputString is empty, but app params not empty wizard is shown. Maybe it's bad
    if (!init.isEmpty())
    {
        mInputString = init;
    }
    if (mInputString.isEmpty())
    {
        emit emptyString();
    }
    /* Deleting previous camera*/
    deinitCamera();
    mInputSelectorDialog.setInputString(mInputString);
    mCamera = ImageCaptureInterface::fabric(mInputString.toStdString(), isRgb);
    if (mCamera == NULL)
    {
        cout << "Error initializing capture device." << endl;
        return;
    }
    ImageCaptureInterface::CapErrorCode res = mCamera->initCapture();
    if (ImageCaptureInterface::FAILURE == res)
    {
        cout << "Error: none of the capture devices started.\n" << endl;
        QMessageBox::warning(this, "Error: none of the capture devices started.","Error: none of the capture devices started.");
        return;
    }
    else if (ImageCaptureInterface::SUCCESS_1CAM == res)
    {
        cout << "Will be using only one capture device.\n" << endl;
        mUseOneCaptureDevice = true;
        mPresentationControlWidget->ui()->rightFrameButton->setEnabled(false);
    }
    else
    {
        mUseOneCaptureDevice = false;
    }
    /* Now we need to connect the camera to widgets */
    mCapSettings = new CapSettingsDialog(NULL, mCamera);
    mSaveableCameraWidgets.push_back(mCapSettings);
    mCapSettings->loadFromQSettings(ConfigManager::camConfigName(), "");
    qRegisterMetaType<CaptureStatistics>("CaptureStatistics");
    connect(mCamera, SIGNAL(newStatisticsReady(CaptureStatistics)),
            this, SLOT(setCaptureStats(CaptureStatistics)), Qt::QueuedConnection);
    connect(mCamera, SIGNAL(streamPaused()), this, SIGNAL(singleStepStatusUpdated()));
    emit captureStatusUpdated(true);
 /*   bool isPauseable = mCamera->supportPause();
    mUi.stepModeButton ->setEnabled(isPauseable);
    mUi.nextFrameButton->setEnabled(isPauseable); */
    /*  Now connect mCamera to mCalculator */
    mCalculator->setImageCaptureInterface(mCamera);
    connect(mCamera,     SIGNAL(newFrameReady(frame_data_t)),
            mCalculator, SLOT  (newFrameReady(frame_data_t)), Qt::QueuedConnection);
    camerasParamsChanged();
    if (autoExitCount == -1)
    {
        stopCapture();
    }
}
void BaseHostDialog::initCommon () [protected, virtual, inherited]
Initialization steps that are likely, however not mandatory to be used in specific application dialogs using BaseHostDialog as their parent class.
Definition at line 227 of file baseHostDialog.cpp.
References BaseHostDialog::captureStatusUpdated(), BaseHostDialog::distortionEstimationFinished(), BaseHostDialog::doOpenInput(), BaseHostDialog::mDistortionWidget, BaseHostDialog::mInputSelectorDialog, BaseHostDialog::mSaveableWidgets, and BaseHostDialog::mUi.
Referenced by BaseHostDialog::init().
{
    /* Main UI*/
    connect(&mInputSelectorDialog, SIGNAL(newInputString()), this, SLOT(doOpenInput()));
    /* Main output */
    mUi.widget->setSavingRoot("mainoutput");
    mSaveableWidgets.push_back(mUi.widget);
    /* Distortion corrector*/
    mDistortionWidget = new DistortionWidget();
    qRegisterMetaType<QSharedPointer<DisplacementBuffer> >("QSharedPointer<DisplacementBuffer>");
    connect(mDistortionWidget, SIGNAL(recalculationFinished(QSharedPointer<DisplacementBuffer>)), this, SLOT(distortionEstimationFinished()));
    /* Connect video sequence control */
    emit captureStatusUpdated(false);
}
void BaseHostDialog::initGraphPresentation () [inherited]
Definition at line 93 of file baseHostDialog.cpp.
References FilterGraphPresentation::filterGraph, FilterGraphPresentation::graphChangedSlot(), corecvs::FilterGraph::loadFromFile(), BaseHostDialog::mBaseControlWidget, BaseHostDialog::mCalculator, BaseHostDialog::mFilterGraphPresentation, BaseHostDialog::mFilterPresentationsCollection, AbstractCalculationThread::mFiltersCollection, FilterGraphPresentation::restoreFromGraph(), and BaseParametersControlWidget::ui().
Referenced by BaseHostDialog::init().
{
    mFilterPresentationsCollection = new FilterPresentationsCollection(&mCalculator->mFiltersCollection);
    mFilterGraphPresentation = new FilterGraphPresentation(mFilterPresentationsCollection);
    connect(mBaseControlWidget->ui()->filterGraphButton, SIGNAL(released()), mFilterGraphPresentation, SLOT(show()));
    connect(mFilterGraphPresentation
            , SIGNAL(graphChanged(tinyxml2::XMLDocument*))
            , mCalculator
            , SLOT(graphChanged(tinyxml2::XMLDocument*)));
    cout << "Trying to start loading Graph" << endl;
    mFilterGraphPresentation->filterGraph->loadFromFile("graph.conf");
    mFilterGraphPresentation->restoreFromGraph();
    mFilterGraphPresentation->graphChangedSlot();
}
void RecorderDialog::initParameterWidgets () [virtual]
Initialize widgets that should be in BaseHostDialog.
Reimplemented from BaseHostDialog.
Definition at line 34 of file recorderDialog.cpp.
References BaseHostDialog::dockWidget(), mRecorderControlWidget, BaseHostDialog::mSaveableWidgets, openPathSelectDialog(), toggleRecording(), RecorderControlWidget::ui(), and UI_NAME_RECORDER.
{
    BaseHostDialog::initParameterWidgets();
    mRecorderControlWidget = new RecorderControlWidget(this, true, UI_NAME_RECORDER);
    dockWidget()->layout()->addWidget(mRecorderControlWidget);
    mSaveableWidgets.push_back(mRecorderControlWidget);
    connect(mRecorderControlWidget->ui()->choosePathButton, SIGNAL(clicked()), this, SLOT(openPathSelectDialog()));
    connect(mRecorderControlWidget->ui()->recStartButton, SIGNAL(clicked()), this, SLOT(toggleRecording()));
}
void BaseHostDialog::loadParams (const QString & fileName, QString root) [protected, virtual, inherited]
Definition at line 783 of file baseHostDialog.cpp.
References ConfigManager::camConfigName(), initialCameraString, BaseHostDialog::mDockWidget, BaseHostDialog::mInputString, BaseHostDialog::mSaveableCameraWidgets, and BaseHostDialog::mSaveableWidgets.
Referenced by BaseHostDialog::doLoadParams(), and BaseHostDialog::init().
{
    QSettings settings(fileName, QSettings::IniFormat);
    QSettings cameraSettings(ConfigManager::camConfigName(), QSettings::IniFormat);
    if (!root.isEmpty())
    {
        settings.beginGroup(root);
    }
    if (mInputString.isEmpty())
    {
        mInputString = cameraSettings.value(initialCameraString, "").toString();
    }
    if (settings.value("DockWidgetHide", false).toBool())
    {
        mDockWidget->hide();
    }
    if (!root.isEmpty())
    {
        settings.endGroup();
    }
    for (unsigned i = 0; i < mSaveableWidgets.size(); i++)
    {
        mSaveableWidgets[i]->loadFromQSettings(fileName, root);
    }
    for (unsigned i = 0; i < mSaveableCameraWidgets.size(); i++)
    {
        mSaveableWidgets[i]->loadFromQSettings(ConfigManager::camConfigName(), root);
    }
}
void BaseHostDialog::loadTransformFromFile (QString const & filename) [protected, inherited]
Definition at line 855 of file baseHostDialog.cpp.
References BaseHostDialog::camerasParamsChanged(), in, corecvs::PropertyList::load(), BaseHostDialog::mRectifierData, and corecvs::PropertyListReaderVisitor::visit().
Referenced by BaseHostDialog::doLoadTransform(), and BaseHostDialog::init().
{
    fstream f;
    f.open((char *)filename.toAscii().constData(), fstream::in);
    mRectifierData = RectificationResult();
    if (f.is_open())
    {
        PropertyList list;
        list.load(f);
        PropertyListReaderVisitor readerVisitor(&list);
        RectificationResult defaultResult;
        readerVisitor.visit(mRectifierData, defaultResult, "rectification");
        f.close();
    }
    camerasParamsChanged();
}
void BaseHostDialog::mouseChild (QMouseEvent * event) [protected, slot, inherited]
Definition at line 637 of file baseHostDialog.cpp.
{
    Q_UNUSED(event)
}
void BaseHostDialog::nextFrame () [protected, slot, inherited]
Definition at line 593 of file baseHostDialog.cpp.
References BaseHostDialog::mCamera, and ImageCaptureInterface::nextFrame().
{
    if (mCamera == NULL) {
        return;
    }
    mCamera->nextFrame();
}
void RecorderDialog::openPathSelectDialog () [slot]
Definition at line 112 of file recorderDialog.cpp.
References mRecorderControlWidget, and RecorderControlWidget::ui().
Referenced by initParameterWidgets().
{
    QString dir_path = QFileDialog::getExistingDirectory( this,
                                                          "Select target directory",
                                                          QDir::homePath()
                                                          );
    if (dir_path.length() > 0)
    {
        mRecorderControlWidget->ui()->pathEdit->setText(dir_path);
    }
}
void BaseHostDialog::pauseCalculator () [signal, inherited]
Referenced by BaseHostDialog::initCalculator().
void BaseHostDialog::play () [protected, virtual, slot, inherited]
Starts both capture and processing.
Definition at line 605 of file baseHostDialog.cpp.
References AbstractCalculationThread::CALCULATION_AWAITING_DATA, AbstractCalculationThread::getCalculationState(), BaseHostDialog::mBaseParams, BaseHostDialog::mCalculator, BaseHostDialog::mCamera, BaseHostDialog::mCameraStarted, BaseHostDialog::mScheduledSwap, ImageCaptureInterface::nextFrame(), ImageCaptureInterface::startCapture(), AbstractCalculationThread::stateNames, and BaseHostDialog::swapCameras().
Referenced by connectFinishedRecalculation().
{
    qDebug() << "BaseHostDialog::Play, calc state: " << AbstractCalculationThread::stateNames[mCalculator->getCalculationState()];
    if (!mCameraStarted)
    {
        if (!mCamera)
        {
            return;
        }
        mCamera->startCapture();
        mCamera->nextFrame();  // Get a first frame from file to show something, or do nothing when capturing from cam.
        mCameraStarted = true;
    }
    if (mCalculator->getCalculationState() != AbstractCalculationThread::CALCULATION_AWAITING_DATA)
    {
        QMetaObject::invokeMethod(mCalculator, "resumeCalculation", Qt::BlockingQueuedConnection);
    }
    if (mScheduledSwap && !mBaseParams.isNull())
    {
        swapCameras(mBaseParams->swapCameras());
        mScheduledSwap = false;
    }
}
void BaseHostDialog::presentationControlParametersChanged (QSharedPointer< PresentationParameters > params) [slot, inherited]
Definition at line 205 of file baseHostDialog.cpp.
References BaseHostDialog::mPresentationParams.
Referenced by createCalculator(), and BaseHostDialog::createCalculator().
{
    mPresentationParams = params;
}
void RecorderDialog::processResult () [virtual, slot]
Reimplemented from BaseHostDialog.
Definition at line 171 of file recorderDialog.cpp.
References StatisticsDialog::addStats(), ResultImage::drawImage(), BaseHostDialog::eventList, RecorderOutputData::frameCount, ResultImage::height(), BaseHostDialog::mImage, mIsRecording, BaseOutputData::mMainImage, mRecorderControlWidget, BaseHostDialog::mStatsDialog, RecorderOutputData::stats, RecorderControlWidget::ui(), BaseHostDialog::updateWidgets(), and ResultImage::width().
{
    for (unsigned i = 0; i < eventList.size(); i++)
    {
        RecorderOutputData *fod = dynamic_cast<RecorderOutputData*>(eventList[i]);
        if (fod == NULL)
            break;
        mStatsDialog.addStats(fod->stats);
        if (mIsRecording)
            mRecorderControlWidget->ui()->frameCountLabel->setText(QString("Frame (frame pairs) written: %1").arg(fod->frameCount));
        if (i == eventList.size() - 1) {
            mImage = QSharedPointer<QImage>(new QImage(fod->mMainImage.width(), fod->mMainImage.height(),  QImage::Format_RGB32));
            fod->mMainImage.drawImage(mImage.data());
        }
        delete fod;
    }
    updateWidgets();
}
void RecorderDialog::recorderControlParametersChanged (QSharedPointer< Recorder > params) [slot]
Definition at line 92 of file recorderDialog.cpp.
References mRecorderControlParams.
Referenced by createCalculator().
{
    if (!params)
        return;
    mRecorderControlParams = params;
}
void RecorderDialog::recordingReset () [signal]
Referenced by resetRecording().
void RecorderDialog::recordingStateChanged (RecorderThread::RecordingState state) [slot]
Definition at line 135 of file recorderDialog.cpp.
References BaseHostDialog::mBaseControlWidget, mIsRecording, mRecorderControlWidget, RecorderThread::StateRecordingActive, RecorderThread::StateRecordingFailure, RecorderThread::StateRecordingPaused, RecorderThread::StateRecordingReset, and RecorderControlWidget::ui().
Referenced by createCalculator().
{
    switch (state)
    {
        case RecorderThread::StateRecordingActive:
        {
            mIsRecording = true;
            mBaseControlWidget->setEnabled(false);
            mRecorderControlWidget->ui()->recStartButton->setEnabled(false);
            mRecorderControlWidget->ui()->recPauseButton->setEnabled(true);
            mRecorderControlWidget->ui()->recRestartButton->setEnabled(true);
            mRecorderControlWidget->ui()->pathEdit->setEnabled(false);
            mRecorderControlWidget->ui()->fileTemplateEdit->setEnabled(false);
            break;
        }
        case RecorderThread::StateRecordingPaused:
        {
            break;
        }
        case RecorderThread::StateRecordingReset:
        case RecorderThread::StateRecordingFailure:
        {
            mIsRecording = false;
            mBaseControlWidget->setEnabled(true);
            mRecorderControlWidget->ui()->recStartButton->setChecked(false);
            mRecorderControlWidget->ui()->recStartButton->setEnabled(true);
            mRecorderControlWidget->ui()->recPauseButton->setChecked(false);
            mRecorderControlWidget->ui()->recPauseButton->setEnabled(false);
            mRecorderControlWidget->ui()->recRestartButton->setEnabled(false);
            mRecorderControlWidget->ui()->pathEdit->setEnabled(true);
            mRecorderControlWidget->ui()->fileTemplateEdit->setEnabled(true);
            break;
        }
    }
}
void RecorderDialog::recordingTriggered () [signal]
Referenced by createCalculator(), and toggleRecording().
void RecorderDialog::resetRecording () [slot]
Definition at line 130 of file recorderDialog.cpp.
References recordingReset().
Referenced by createCalculator().
{
    emit recordingReset();
}
void BaseHostDialog::resumeCalculator () [signal, inherited]
Referenced by BaseHostDialog::initCalculator().
void BaseHostDialog::saveParams (const QString & fileName, QString root) [protected, virtual, inherited]
Definition at line 820 of file baseHostDialog.cpp.
References ConfigManager::camConfigName(), initialCameraString, BaseHostDialog::mInputString, BaseHostDialog::mSaveableCameraWidgets, and BaseHostDialog::mSaveableWidgets.
Referenced by BaseHostDialog::deinit(), and BaseHostDialog::doSaveParams().
{
    QSettings settings(fileName, QSettings::IniFormat);
    QSettings cameraSettings(ConfigManager::camConfigName(), QSettings::IniFormat);
    if (!root.isEmpty())
    {
        cameraSettings.beginGroup(root);
    }
    cameraSettings.setValue(initialCameraString, mInputString);
    if (!root.isEmpty())
    {
        cameraSettings.endGroup();
    }
    for (unsigned i = 0; i < mSaveableWidgets.size(); i++)
    {
        mSaveableWidgets[i]->saveToQSettings(fileName, root);
    }
    for (unsigned i = 0; i < mSaveableCameraWidgets.size(); i++)
    {
        mSaveableWidgets[i]->loadFromQSettings(ConfigManager::camConfigName(), root);
    }
}
void BaseHostDialog::saveTransformToFile (QString const & filename) [protected, inherited]
Definition at line 872 of file baseHostDialog.cpp.
References BaseHostDialog::mRectifierData, corecvs::PropertyList::save(), and corecvs::PropertyListWriterVisitor::visit().
Referenced by BaseHostDialog::doSaveTransform().
{
    qDebug() << "saving to" << filename;
    fstream f;
    f.open((char *)filename.toAscii().constData(), fstream::out);
    PropertyList list;
    PropertyListWriterVisitor writerVisitor(&list);
    RectificationResult defaultResult;
    writerVisitor.visit(mRectifierData, defaultResult, "rectification");
    list.save(f);
    f.close();
}
void BaseHostDialog::setAutoExit (int autoexit) [inline, inherited]
Definition at line 117 of file baseHostDialog.h.
References BaseHostDialog::autoExitCount.
{
        this->autoExitCount = autoexit;
    }
void BaseHostDialog::setCaptureStats (CaptureStatistics stats) [protected, slot, inherited]
Definition at line 672 of file baseHostDialog.cpp.
References StatisticsDialog::addCaptureStats(), BaseHostDialog::mStatsDialog, and BaseHostDialog::mWidgets.
Referenced by BaseHostDialog::initCapture().
{
    mStatsDialog.addCaptureStats(stats);
    foreach (ViAreaWidget *widget, mWidgets)
    {
        StatisticsDialog *dialog = dynamic_cast<StatisticsDialog *>(widget);
        if (dialog != NULL) {
            dialog->addCaptureStats(stats);
        }
    }
}
void BaseHostDialog::showAboutDialog () [slot, inherited]
Definition at line 271 of file baseHostDialog.cpp.
References BaseHostDialog::mAboutDialog.
{
    mAboutDialog.show();
    mAboutDialog.raise();
}
void BaseHostDialog::showCameraCalculatorDialog () [slot, inherited]
Definition at line 253 of file baseHostDialog.cpp.
References BaseHostDialog::mCameraCalculatorWidget.
{
    mCameraCalculatorWidget.show();
    mCameraCalculatorWidget.raise();
}
void BaseHostDialog::showCaptureSettings () [slot, inherited]
Definition at line 265 of file baseHostDialog.cpp.
References BaseHostDialog::mCapSettings.
{
    mCapSettings->show();
    mCapSettings->raise();
}
void BaseHostDialog::showDistortionCorrectorDialog () [slot, inherited]
Definition at line 245 of file baseHostDialog.cpp.
References Frames::getCurrentFrame(), BaseHostDialog::mCorrectionFrame, BaseHostDialog::mDistortionWidget, BaseHostDialog::mFrames, and DistortionWidget::setBuffer().
{
    mDistortionWidget->show();
    mDistortionWidget->raise();
    //TODO::make different corrections for left and right frame
    mDistortionWidget->setBuffer(mFrames->getCurrentFrame(mCorrectionFrame));
}
void BaseHostDialog::showInputSelectorDialog () [slot, inherited]
Definition at line 277 of file baseHostDialog.cpp.
References BaseHostDialog::mInputSelectorDialog.
{
    mInputSelectorDialog.show();
    mInputSelectorDialog.raise();
}
void BaseHostDialog::showStatistics () [slot, inherited]
Definition at line 259 of file baseHostDialog.cpp.
References BaseHostDialog::mStatsDialog.
{
    mStatsDialog.show();
    mStatsDialog.raise();
}
void BaseHostDialog::singleStepStatusUpdated () [signal, inherited]
Referenced by BaseHostDialog::initCapture(), and BaseHostDialog::stopCapture().
QtStatisticsCollector * BaseHostDialog::statisticsCollector () [protected, inherited]
Definition at line 945 of file baseHostDialog.cpp.
References BaseHostDialog::mStatsDialog, and StatisticsDialog::statsAccum.
{
    return &mStatsDialog.statsAccum;
}
void BaseHostDialog::stopCalculation () [protected, inherited]
Definition at line 220 of file baseHostDialog.cpp.
References BaseHostDialog::mCalculator, and AbstractCalculationThread::setImageCaptureInterface().
Referenced by BaseHostDialog::doOpenInput().
{
    QMetaObject::invokeMethod(mCalculator, "pauseCalculation", Qt::BlockingQueuedConnection);
    mCalculator->setImageCaptureInterface(NULL);
}
void BaseHostDialog::stopCapture () [protected, slot, inherited]
Definition at line 584 of file baseHostDialog.cpp.
References BaseHostDialog::mCamera, ImageCaptureInterface::pauseCapture(), and BaseHostDialog::singleStepStatusUpdated().
Referenced by BaseHostDialog::doOpenInput(), and BaseHostDialog::initCapture().
{
    if (mCamera == NULL) {
        return;
    }
    emit singleStepStatusUpdated();
    mCamera->pauseCapture();
}
void BaseHostDialog::terminateCalculator () [protected, virtual, inherited]
during the process of the destruction you need to make sure that the thread object is killed before deiniting all the objects that are referenced be it.
The other possible solution is to use QObject::deleteLater() on the objects that are referenced by the thread.
Definition at line 477 of file baseHostDialog.cpp.
References BaseHostDialog::mCalculator.
Referenced by BaseHostDialog::deinit(), and ~RecorderDialog().
{
    if (mCalculator != NULL)
    {
        mCalculator->quit();
        mCalculator->wait();
        delete_safe (mCalculator);
    }
}
void BaseHostDialog::toggleAdvanced (bool off) [slot, inherited]
Definition at line 912 of file baseHostDialog.cpp.
References WidgetQtIterator::advancedVisibility(), and BaseHostDialog::dockWidget().
{
    WidgetQtIterator::advancedVisibility(dockWidget(), !on);
}
void RecorderDialog::toggleRecording () [slot]
Definition at line 125 of file recorderDialog.cpp.
References recordingTriggered().
Referenced by createCalculator(), and initParameterWidgets().
{
    emit recordingTriggered();
}
void BaseHostDialog::updatePauseCalculationAction (bool) [signal, inherited]
Referenced by BaseHostDialog::initCalculator().
void BaseHostDialog::updateWidgets () [protected, slot, inherited]
Definition at line 691 of file baseHostDialog.cpp.
References BaseHostDialog::mImage, BaseHostDialog::mUi, and BaseHostDialog::mWidgets.
Referenced by processResult(), and BaseHostDialog::processResult().
{
    mUi.widget->setImage(mImage);
    mUi.widget->update();
    foreach (QWidget *widget, mWidgets.values()) {
        widget->update();
    }
}
QString BaseHostDialog::windowTitle () const [virtual, inherited]
Definition at line 935 of file baseHostDialog.cpp.
Referenced by MainWindow::MainWindow().
{
    return "Base Dialog";
}
Member Data Documentation
int BaseHostDialog::autoExitCount [protected, inherited]
Definition at line 342 of file baseHostDialog.h.
Referenced by BaseHostDialog::finishedRecalculation(), BaseHostDialog::initCapture(), and BaseHostDialog::setAutoExit().
int BaseHostDialog::collectingEvents [protected, inherited]
Variables to handle overfill of the draw queue collectingEvents is true when we are adding the result to local queue to process, and false when we actually processing it.
Definition at line 330 of file baseHostDialog.h.
Referenced by BaseHostDialog::cleanupEventQueue(), and BaseHostDialog::finishedRecalculation().
vector<AbstractOutputData *> BaseHostDialog::eventList [protected, inherited]
Queue that holds draw requests.
Should better use deque here
Definition at line 335 of file baseHostDialog.h.
Referenced by BaseHostDialog::cleanupEventQueue(), BaseHostDialog::finishedRecalculation(), processResult(), and BaseHostDialog::processResult().
QMenu* BaseHostDialog::mAdditionalTools [protected, inherited]
Definition at line 279 of file baseHostDialog.h.
Referenced by BaseHostDialog::addAdditionalWindow(), BaseHostDialog::additionalMenus(), and BaseHostDialog::~BaseHostDialog().
BaseParametersControlWidget* BaseHostDialog::mBaseControlWidget [protected, inherited]
Definition at line 269 of file baseHostDialog.h.
Referenced by createCalculator(), BaseHostDialog::createCalculator(), BaseHostDialog::initGraphPresentation(), BaseHostDialog::initParameterWidgets(), and recordingStateChanged().
QSharedPointer<BaseParameters> BaseHostDialog::mBaseParams [protected, inherited]
Definition at line 272 of file baseHostDialog.h.
Referenced by BaseHostDialog::baseControlParametersChanged(), BaseHostDialog::finishedRecalculation(), and BaseHostDialog::play().
AbstractCalculationThread* BaseHostDialog::mCalculator [protected, inherited]
Definition at line 243 of file baseHostDialog.h.
Referenced by connectFinishedRecalculation(), BaseHostDialog::connectFinishedRecalculation(), createCalculator(), BaseHostDialog::createCalculator(), BaseHostDialog::initCalculator(), BaseHostDialog::initCapture(), BaseHostDialog::initGraphPresentation(), BaseHostDialog::play(), BaseHostDialog::stopCalculation(), and BaseHostDialog::terminateCalculator().
ImageCaptureInterface* BaseHostDialog::mCamera [protected, inherited]
Definition at line 262 of file baseHostDialog.h.
Referenced by BaseHostDialog::deinitCamera(), BaseHostDialog::initCapture(), BaseHostDialog::nextFrame(), BaseHostDialog::play(), BaseHostDialog::stopCapture(), and BaseHostDialog::~BaseHostDialog().
CameraCalculatorWidget BaseHostDialog::mCameraCalculatorWidget [protected, inherited]
Definition at line 258 of file baseHostDialog.h.
Referenced by BaseHostDialog::showCameraCalculatorDialog().
bool BaseHostDialog::mCameraStarted [protected, inherited]
Definition at line 261 of file baseHostDialog.h.
Referenced by BaseHostDialog::deinitCamera(), and BaseHostDialog::play().
CapSettingsDialog* BaseHostDialog::mCapSettings [protected, inherited]
Definition at line 265 of file baseHostDialog.h.
Referenced by BaseHostDialog::initCapture(), BaseHostDialog::showCaptureSettings(), and BaseHostDialog::~BaseHostDialog().
DistortionWidget* BaseHostDialog::mDistortionWidget [protected, inherited]
Definition at line 255 of file baseHostDialog.h.
Referenced by BaseHostDialog::distortionEstimationFinished(), BaseHostDialog::initCommon(), BaseHostDialog::showDistortionCorrectorDialog(), and BaseHostDialog::~BaseHostDialog().
QWidget* BaseHostDialog::mDockWidget [protected, inherited]
Definition at line 295 of file baseHostDialog.h.
Referenced by BaseHostDialog::dockWidget(), BaseHostDialog::init(), and BaseHostDialog::loadParams().
FilterGraphPresentation* BaseHostDialog::mFilterGraphPresentation [protected, inherited]
Definition at line 275 of file baseHostDialog.h.
Referenced by BaseHostDialog::createCalculator(), BaseHostDialog::initGraphPresentation(), and BaseHostDialog::~BaseHostDialog().
FilterPresentationsCollection* BaseHostDialog::mFilterPresentationsCollection [protected, inherited]
Definition at line 343 of file baseHostDialog.h.
Referenced by BaseHostDialog::initGraphPresentation().
Frames* BaseHostDialog::mFrames [protected, inherited]
Definition at line 266 of file baseHostDialog.h.
Referenced by BaseHostDialog::baseControlParametersChanged(), BaseHostDialog::distortionEstimationFinished(), BaseHostDialog::initCalculator(), BaseHostDialog::showDistortionCorrectorDialog(), and BaseHostDialog::swapCameras().
QSharedPointer<QImage> BaseHostDialog::mImage [protected, inherited]
Definition at line 248 of file baseHostDialog.h.
Referenced by processResult(), BaseHostDialog::processResult(), and BaseHostDialog::updateWidgets().
QString BaseHostDialog::mInputString [protected, inherited]
Definition at line 323 of file baseHostDialog.h.
Referenced by BaseHostDialog::initCapture(), BaseHostDialog::loadParams(), and BaseHostDialog::saveParams().
bool RecorderDialog::mIsRecording [private]
Definition at line 51 of file recorderDialog.h.
Referenced by processResult(), and recordingStateChanged().
QTextEdit* BaseHostDialog::mLoggerWidget [protected, inherited]
Definition at line 296 of file baseHostDialog.h.
MemoryUsageCalculator* BaseHostDialog::mMemoryCalculator [protected, inherited]
Object that checks memory consumption.
Definition at line 293 of file baseHostDialog.h.
Referenced by BaseHostDialog::initMemoryUsageCalculator(), and BaseHostDialog::~BaseHostDialog().
QTimer BaseHostDialog::mMemoryTimer [protected, inherited]
Timer that will fire when it's time to check the memory consumption.
Definition at line 289 of file baseHostDialog.h.
Referenced by BaseHostDialog::initMemoryUsageCalculator().
QObject* BaseHostDialog::mParamsMapper [protected, inherited]
Definition at line 242 of file baseHostDialog.h.
Referenced by createCalculator(), BaseHostDialog::createCalculator(), and BaseHostDialog::~BaseHostDialog().
PresentationParametersControlWidget* BaseHostDialog::mPresentationControlWidget [protected, inherited]
Definition at line 270 of file baseHostDialog.h.
Referenced by createCalculator(), BaseHostDialog::createCalculator(), BaseHostDialog::initCapture(), and BaseHostDialog::initParameterWidgets().
QSharedPointer<PresentationParameters> BaseHostDialog::mPresentationParams [protected, inherited]
Definition at line 273 of file baseHostDialog.h.
Referenced by BaseHostDialog::presentationControlParametersChanged().
QSharedPointer<Recorder> RecorderDialog::mRecorderControlParams [private]
Definition at line 55 of file recorderDialog.h.
Referenced by recorderControlParametersChanged().
RecorderControlWidget* RecorderDialog::mRecorderControlWidget [private]
Definition at line 53 of file recorderDialog.h.
Referenced by createCalculator(), initParameterWidgets(), openPathSelectDialog(), processResult(), and recordingStateChanged().
RectificationResult BaseHostDialog::mRectifierData [protected, inherited]
Definition at line 245 of file baseHostDialog.h.
Referenced by BaseHostDialog::getAdditionalParams(), BaseHostDialog::loadTransformFromFile(), BaseHostDialog::saveTransformToFile(), and BaseHostDialog::~BaseHostDialog().
vector<SaveableWidget *> BaseHostDialog::mSaveableCameraWidgets [protected, inherited]
Camera-dependent widgets that delegate BaseHostDialog right to save and load them.
Definition at line 284 of file baseHostDialog.h.
Referenced by BaseHostDialog::initCapture(), BaseHostDialog::loadParams(), and BaseHostDialog::saveParams().
vector<SaveableWidget *> BaseHostDialog::mSaveableWidgets [protected, inherited]
Widgets that delegates BaseHostDialog right to save and load them.
Definition at line 282 of file baseHostDialog.h.
Referenced by BaseHostDialog::createAdditionalWindow(), BaseHostDialog::initCommon(), initParameterWidgets(), BaseHostDialog::initParameterWidgets(), BaseHostDialog::loadParams(), and BaseHostDialog::saveParams().
bool BaseHostDialog::mScheduledSwap [protected, inherited]
Definition at line 299 of file baseHostDialog.h.
Referenced by BaseHostDialog::baseControlParametersChanged(), BaseHostDialog::finishedRecalculation(), and BaseHostDialog::play().
StatisticsDialog BaseHostDialog::mStatsDialog [protected, inherited]
Definition at line 267 of file baseHostDialog.h.
Referenced by processResult(), BaseHostDialog::setCaptureStats(), BaseHostDialog::showStatistics(), and BaseHostDialog::statisticsCollector().
Ui::HostDialogStubClass BaseHostDialog::mUi [protected, inherited]
Definition at line 250 of file baseHostDialog.h.
Referenced by BaseHostDialog::BaseHostDialog(), BaseHostDialog::initCommon(), and BaseHostDialog::updateWidgets().
bool BaseHostDialog::mUseOneCaptureDevice [protected, inherited]
Definition at line 252 of file baseHostDialog.h.
Referenced by BaseHostDialog::getAdditionalParams(), and BaseHostDialog::initCapture().
QHash<QString, ViAreaWidget *> BaseHostDialog::mWidgets [protected, inherited]
Definition at line 278 of file baseHostDialog.h.
Referenced by BaseHostDialog::addAdditionalWindow(), BaseHostDialog::setCaptureStats(), BaseHostDialog::updateWidgets(), and BaseHostDialog::~BaseHostDialog().
The documentation for this class was generated from the following files:
applications/recorder/recorderDialog.h
applications/recorder/recorderDialog.cpp