DeepView: corecvs::ParallelTriangulate< InputType > Class Template Reference
corecvs::ParallelTriangulate< InputType > Class Template Reference
Public Member Functions
void operator() (const BlockedRange< int > &r)
ParallelTriangulate (const Triangulator *_realThis, InputType *_input, int _density, bool _enforceRectify)
~ParallelTriangulate ()
Public Attributes
Cloud * result
Private Attributes
const Triangulator * realThis
InputType * input
int density
bool enforceRectify
Detailed Description
template<class InputType>
class corecvs::ParallelTriangulate< InputType >
Definition at line 106 of file triangulator.cpp.
Constructor & Destructor Documentation
template<class InputType> corecvs::ParallelTriangulate< InputType >::ParallelTriangulate (const Triangulator * _realThis, InputType * _input, int _density, bool _enforceRectify) [inline]
Definition at line 154 of file triangulator.cpp.
References corecvs::ParallelTriangulate< InputType >::result.
                                                                                                               :
        realThis(_realThis)
      , input(_input)
      , density(_density)
      , enforceRectify(_enforceRectify)
    {
        result = new Cloud();
        result->reserve(10000);
    }
template<class InputType> corecvs::ParallelTriangulate< InputType >::~ParallelTriangulate () [inline]
Definition at line 164 of file triangulator.cpp.
References corecvs::ParallelTriangulate< InputType >::result.
    {
        delete_safe(result);
    }
Member Function Documentation
template<class InputType> void corecvs::ParallelTriangulate< InputType >::operator() (const BlockedRange< int > & r) [inline]
Definition at line 114 of file triangulator.cpp.
References corecvs::BlockedRange< IndexType >::begin(), corecvs::BlockedRange< IndexType >::end(), corecvs::ParallelTriangulate< InputType >::enforceRectify, corecvs::ParallelTriangulate< InputType >::input, corecvs::SwarmPoint::point, corecvs::ParallelTriangulate< InputType >::realThis, corecvs::ParallelTriangulate< InputType >::result, corecvs::SwarmPoint::texCoor, corecvs::Triangulator::triangulate(), and corecvs::Vector2d< ElementType >::y().
    {
        int i, j;
        for (i = r.begin(); i < r.end(); i++)
        {
            for (j = 0; j < input->w; j++)
            {
                if (!input->isElementKnown(i, j))
                    continue;
                /* Point in right frame*/
                Vector2dd start(j,i);
                Vector2dd shift;
                shift = getInputDisparity<InputType>(input, i,j);
                if (enforceRectify)
                {
                    shift.y() = 0;
                }
                SwarmPoint cloudPoint;
                cloudPoint.point = realThis->triangulate(start, shift);
                cloudPoint.texCoor = start;
                result->push_back(cloudPoint);
            }
        }
    }
Member Data Documentation
template<class InputType> int corecvs::ParallelTriangulate< InputType >::density [private]
Definition at line 110 of file triangulator.cpp.
template<class InputType> bool corecvs::ParallelTriangulate< InputType >::enforceRectify [private]
Definition at line 111 of file triangulator.cpp.
Referenced by corecvs::ParallelTriangulate< InputType >::operator()().
template<class InputType> InputType* corecvs::ParallelTriangulate< InputType >::input [private]
Definition at line 109 of file triangulator.cpp.
Referenced by corecvs::ParallelTriangulate< InputType >::operator()().
template<class InputType> const Triangulator* corecvs::ParallelTriangulate< InputType >::realThis [private]
Definition at line 108 of file triangulator.cpp.
Referenced by corecvs::ParallelTriangulate< InputType >::operator()().
template<class InputType> Cloud* corecvs::ParallelTriangulate< InputType >::result
Definition at line 113 of file triangulator.cpp.
Referenced by corecvs::ParallelTriangulate< InputType >::operator()(), corecvs::ParallelTriangulate< InputType >::ParallelTriangulate(), corecvs::Triangulator::triangulateHelperParallel(), and corecvs::ParallelTriangulate< InputType >::~ParallelTriangulate().
The documentation for this class was generated from the following file:
core/rectification/triangulator.cpp