DeepView: RgbColorParametersControlWidget Class Reference
RgbColorParametersControlWidget Class Reference
#include <rgbColorParametersControlWidget.h>
Public Slots
void changeParameters ()
void updateIcon ()
void pickerClicked (QMouseEvent *)
void colorSelected (const QColor &color)
void repaintPicker (QPaintEvent *, QWidget *who)
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
RgbColorParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~RgbColorParametersControlWidget ()
RgbColorParameters * createParameters () const
void setParameters (const RgbColorParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
RGBColor getColor ()
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
QColorDialog mColorPicker
QColor color
Ui_RgbColorParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 13 of file rgbColorParametersControlWidget.h.
Constructor & Destructor Documentation
RgbColorParametersControlWidget::RgbColorParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file rgbColorParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::RgbColorParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->rSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->gSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->bSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
RgbColorParametersControlWidget::~RgbColorParametersControlWidget ()
Definition at line 28 of file rgbColorParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void RgbColorParametersControlWidget::changeParameters () [inline, slot]
Definition at line 39 of file rgbColorParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
void RgbColorParametersControlWidget::colorSelected (const QColor & color) [inline, slot]
Definition at line 65 of file rgbColorParametersControlWidget.h.
References mUi.
Referenced by pickerClicked().
    {
        mUi->rSpinBox->setValue(color.red());
        mUi->gSpinBox->setValue(color.green());
        mUi->bSpinBox->setValue(color.blue());
        mUi->pickerWidget->update();
    }
RgbColorParameters * RgbColorParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 50 of file rgbColorParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    RgbColorParameters *result = new RgbColorParameters(
          mUi->rSpinBox->value()
        , mUi->gSpinBox->value()
        , mUi->bSpinBox->value()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
RGBColor RgbColorParametersControlWidget::getColor () [inline]
Definition at line 30 of file rgbColorParametersControlWidget.h.
References mUi.
    {
        return RGBColor(
          mUi->rSpinBox->value()
        , mUi->gSpinBox->value()
        , mUi->bSpinBox->value());
    }
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void RgbColorParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 34 of file rgbColorParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    RgbColorParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void RgbColorParametersControlWidget::paramsChanged () [signal]
Referenced by RgbColorParametersControlWidget(), and setParameters().
void RgbColorParametersControlWidget::pickerClicked (QMouseEvent *) [inline, slot]
Definition at line 49 of file rgbColorParametersControlWidget.h.
References colorSelected(), mColorPicker, and mUi.
    {
        mColorPicker.show();
        bool signalState = mColorPicker.blockSignals(true);
        mColorPicker.setCurrentColor(QColor(
                mUi->rSpinBox->value(),
                mUi->gSpinBox->value(),
                mUi->bSpinBox->value()
        ));
        mColorPicker.blockSignals(signalState);
        connect(&mColorPicker, SIGNAL(currentColorChanged (QColor)),
                this, SLOT(colorSelected(QColor)), Qt::UniqueConnection);
    }
void RgbColorParametersControlWidget::repaintPicker (QPaintEvent * , QWidget * who) [inline, slot]
Definition at line 73 of file rgbColorParametersControlWidget.h.
References color, and mUi.
    {
        color = QColor(
            mUi->rSpinBox->value(),
            mUi->gSpinBox->value(),
            mUi->bSpinBox->value()
        );
        QPainter painter(who);
        //painter.setPen(color);
        painter.fillRect(who->rect(),color);
    }
void RgbColorParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 42 of file rgbColorParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    RgbColorParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void RgbColorParametersControlWidget::setParameters (const RgbColorParameters & input)
Definition at line 66 of file rgbColorParametersControlWidget.cpp.
References RgbColorParameters::b(), RgbColorParameters::g(), mUi, paramsChanged(), and RgbColorParameters::r().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->rSpinBox->setValue(input.r());
    mUi->gSpinBox->setValue(input.g());
    mUi->bSpinBox->setValue(input.b());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void RgbColorParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 77 of file rgbColorParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    RgbColorParameters *inputCasted = static_cast<RgbColorParameters *>(input);
    setParameters(*inputCasted);
}
void RgbColorParametersControlWidget::updateIcon () [inline, slot]
Definition at line 44 of file rgbColorParametersControlWidget.h.
    {
        //mUi->selectorPushButton->setS;
    }
void RgbColorParametersControlWidget::valueChanged () [signal]
Referenced by RgbColorParametersControlWidget().
Member Data Documentation
bool RgbColorParametersControlWidget::autoInit [private]
Definition at line 93 of file rgbColorParametersControlWidget.h.
QColor RgbColorParametersControlWidget::color [private]
Definition at line 17 of file rgbColorParametersControlWidget.h.
Referenced by repaintPicker().
QColorDialog RgbColorParametersControlWidget::mColorPicker [private]
Definition at line 16 of file rgbColorParametersControlWidget.h.
Referenced by pickerClicked().
Ui_RgbColorParametersControlWidget* RgbColorParametersControlWidget::mUi [private]
Definition at line 92 of file rgbColorParametersControlWidget.h.
Referenced by colorSelected(), createParameters(), getColor(), pickerClicked(), repaintPicker(), RgbColorParametersControlWidget(), setParameters(), and ~RgbColorParametersControlWidget().
QString RgbColorParametersControlWidget::rootPath [private]
Definition at line 94 of file rgbColorParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/corestructs/coreWidgets/rgbColorParametersControlWidget.h
utils/corestructs/coreWidgets/rgbColorParametersControlWidget.cpp