DeepView: RecorderThread Class Reference
RecorderThread Class Reference
#include <recorderThread.h>
Public Types
enum RecordingState { StateRecordingActive = 0, StateRecordingPaused, StateRecordingReset, StateRecordingFailure }
enum CalculationState {
CALCULATION_NOT_STARTED = 0, CALCULATION_AWAITING_DATA, CALCULATION_ACTIVE, CALCULATION_PAUSED,
CALCULATION_TERMINATED
}
Public Slots
void toggleRecording ()
void resetRecording ()
void recorderControlParametersChanged (QSharedPointer< Recorder > params)
void baseControlParametersChanged (QSharedPointer< BaseParameters > params)
void camerasParametersChanged (QSharedPointer< CamerasConfigParameters > parameters)
virtual void presentationControlParametersChanged (QSharedPointer< PresentationParameters > params)
virtual void filterControlParametersChanged (Frames::FrameSourceId id, QSharedPointer< FilterSelectorParameters > params)
virtual void graphChanged (tinyxml2::XMLDocument *)
Signals
void recordingStateChanged (RecorderThread::RecordingState state)
void errorMessage (QString string)
void processingFinished (AbstractOutputData *output)
void calculationStateChanged (AbstractCalculationThread::CalculationState state)
Public Member Functions
RecorderThread ()
void setLeftTransform (Matrix33 &leftTransform)
virtual void run ()
virtual void setCalculationState (CalculationState state)
virtual CalculationState getCalculationState () const
Frames * getFramesHolder ()
void setImageCaptureInterface (ImageCaptureInterface *captureInterface)
Public Attributes
FiltersCollection mFiltersCollection
Static Public Attributes
static const char * stateNames []
Protected Slots
virtual void newFrameReady (frame_data_t frameData)
New frame data is ready to be processed.
virtual void pauseCalculation ()
Pauses calculation.
virtual void resumeCalculation ()
Resumes calculation Should only be called as a asynchronous slot function.
Protected Member Functions
virtual AbstractOutputData * processNewData ()
This is the main calculation routine called when a new frame is received.
void initData (BaseOutputData *data, Statistics *stats=NULL)
void executeFilterGraph (Statistics *stats=NULL)
void transformInputFrames ()
void recalculateCache ()
As the transformation procedure uses the inverse of the transformation matrix We first apply the rectification matrix, and then the scaling and shift.
Protected Attributes
TransformationCache * mTransformationCache [Frames::MAX_INPUTS_NUMBER]
The cache of the transformation applied to the left and right image.
G12Buffer * mTransformedBuffers [Frames::MAX_INPUTS_NUMBER]
Transformed buffers.
FilterExecuter * mFilterExecuter [Frames::MAX_INPUTS_NUMBER]
RectificationResult mRectificationData
RectificationResult mPretransformedRectificationData
Matrix33 mInputPretransform
Matrix33 mInputPretransformInv
Matrix33 mFrameTransforms [Frames::MAX_INPUTS_NUMBER]
The transforms from original input image camera image to rectified image.
Matrix33 mFrameTransformsInv [Frames::MAX_INPUTS_NUMBER]
Inverse of previous to use in interpolation of the buffer.
QSharedPointer
< DisplacementBuffer > mDistortionTransform
This is a lens precorrection.
int mActiveInputsNumber
QSharedPointer< BaseParameters > mBaseParams
QSharedPointer
< PresentationParameters > mPresentationParams
bool mCacheUpdateNeeded
For a thread to start calculating it needs first frame and the input parameters.
FilterGraph * mProcessorGraph
ImageCaptureInterface * mCaptureInterface
The capture interface we fetch the frames from.
Frames mFrames
Holds the last two sets of frames acquired from the capture device(s)
uint64_t mInterframeDelay
Delay between this and previous frame.
uint64_t mLastFrameTimeStamp
CalculationState mCurrentState
Current calculation state This state can't be changed directly, but can be queried.
Private Attributes
bool mRecordingStarted
bool mIsRecording
PreciseTimer mIdleTimer
PPMLoader mSaver
uint32_t mFrameCount
QString mPath
QSharedPointer< Recorder > mRecorderParameters
Detailed Description
Definition at line 33 of file recorderThread.h.
Member Enumeration Documentation
enum AbstractCalculationThread::CalculationState [inherited]
Enumerator:
CALCULATION_NOT_STARTED
Thread is just created but still not running.
CALCULATION_AWAITING_DATA
Thread is blocked waiting for signals with frames.
CALCULATION_ACTIVE
Thread is processing the frame.
CALCULATION_PAUSED
Thread is paused, it will ignore incoming frames.
CALCULATION_TERMINATED
Thread has exited.
Definition at line 41 of file abstractCalculationThread.h.
        {
            CALCULATION_NOT_STARTED = 0, /**< Thread is just created but still not running */
            CALCULATION_AWAITING_DATA,   /**< Thread is blocked waiting for signals with frames */
            CALCULATION_ACTIVE,          /**< Thread is processing the frame */
            CALCULATION_PAUSED,          /**< Thread is paused, it will ignore incoming frames */
            CALCULATION_TERMINATED       /**< Thread has exited */
        };
enum RecorderThread::RecordingState
Enumerator:
StateRecordingActive
StateRecordingPaused
StateRecordingReset
StateRecordingFailure
Definition at line 38 of file recorderThread.h.
    {
        StateRecordingActive = 0,
        StateRecordingPaused,
        StateRecordingReset,
        StateRecordingFailure
    };
Constructor & Destructor Documentation
RecorderThread::RecorderThread ()
Definition at line 21 of file recorderThread.cpp.
References mIdleTimer.
                               :
   BaseCalculationThread()
  , mRecordingStarted(false)
  , mIsRecording(false)
  , mFrameCount(0)
  , mPath("")
  , mRecorderParameters(NULL)
{
    qRegisterMetaType<RecorderThread::RecordingState>("RecorderThread::RecordingState");
    mIdleTimer = PreciseTimer::currentTime();
}
Member Function Documentation
void RecorderThread::baseControlParametersChanged (QSharedPointer< BaseParameters > params) [virtual, slot]
Reimplemented from BaseCalculationThread.
Definition at line 176 of file recorderThread.cpp.
{
    BaseCalculationThread::baseControlParametersChanged(params);
}
void AbstractCalculationThread::calculationStateChanged (AbstractCalculationThread::CalculationState state) [signal, inherited]
Referenced by AbstractCalculationThread::newFrameReady(), AbstractCalculationThread::pauseCalculation(), and AbstractCalculationThread::resumeCalculation().
void RecorderThread::camerasParametersChanged (QSharedPointer< CamerasConfigParameters > parameters) [virtual, slot]
Reimplemented from BaseCalculationThread.
Definition at line 181 of file recorderThread.cpp.
{
    BaseCalculationThread::camerasParametersChanged(parameters);
}
void RecorderThread::errorMessage (QString string) [signal]
Referenced by processNewData().
void BaseCalculationThread::executeFilterGraph (Statistics * stats = NULL) [protected, inherited]
Definition at line 95 of file baseCalculationThread.cpp.
References corecvs::FilterGraph::clearAllData(), Frames::DEFAULT_FRAME, corecvs::TransformationCache::doDeformation(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformationBl(), corecvs::FilterGraph::execute(), Frames::getCurrentFrame(), corecvs::AbstractBufferParams::h, corecvs::FilterGraph::inputs, InputFilterParameters::inputType(), Frames::LEFT_FRAME, InputType::LEFT_FRAME, BaseCalculationThread::mBaseParams, BaseCalculationThread::mDistortionTransform, AbstractCalculationThread::mFrames, corecvs::InputFilter::mInputParameters, corecvs::OutputFilter::mOutputParameters, BaseCalculationThread::mProcessorGraph, BaseCalculationThread::mTransformationCache, BaseCalculationThread::mTransformedBuffers, corecvs::FilterGraph::outputs, OutputFilterParameters::outputType(), corecvs::Statistics::prefix, Frames::RIGHT_FRAME, InputType::RIGHT_FRAME, corecvs::Statistics::setTime(), corecvs::FilterGraph::stats, corecvs::PreciseTimer::usecsToNow(), and corecvs::AbstractBufferParams::w.
Referenced by BaseCalculationThread::initData().
{
    for (unsigned int i = 0; i < mProcessorGraph->inputs.size(); i++ )
    {
        InputFilter* input = dynamic_cast<InputFilter*>(mProcessorGraph->inputs[i]->parent);
        if (input->mInputParameters.inputType() == InputType::LEFT_FRAME) //FIXME change to Frames::LEFT_FRAME
            mProcessorGraph->inputs[i]->initPin(mFrames.getCurrentFrame(Frames::LEFT_FRAME));
        if (input->mInputParameters.inputType() == InputType::RIGHT_FRAME) //FIXME change to Frames::RIGHT_FRAME
            mProcessorGraph->inputs[i]->initPin(mFrames.getCurrentFrame(Frames::RIGHT_FRAME));
    }
    string oldPrefix;
    PreciseTimer timer = PreciseTimer::currentTime();
    if (stats != NULL)
    {
        oldPrefix = stats->prefix;
        stats->prefix += "Input Graph> ";
    }
    mProcessorGraph->stats = stats;
    mProcessorGraph->execute();
    if (stats != NULL)
    {
        stats->setTime("Total", timer.usecsToNow());
        stats->prefix = oldPrefix;
    }
    int currentOutputBlocks = Frames::DEFAULT_FRAME;
    for (unsigned int i = 0; i < mProcessorGraph->outputs.size(); i++ )
    {
        G12Buffer *outputFrame = NULL;
        OutputFilter* result = dynamic_cast<OutputFilter*>(mProcessorGraph->outputs[i]->parent);
        if (result->mOutputParameters.outputType() == OutputType::LEFT_FRAME)
        {   mProcessorGraph->outputs[i]->getPin(outputFrame);
            currentOutputBlocks = Frames::LEFT_FRAME;
        }
        else if (result->mOutputParameters.outputType() == OutputType::RIGHT_FRAME)
        {   mProcessorGraph->outputs[i]->getPin(outputFrame);
            currentOutputBlocks = Frames::RIGHT_FRAME;
        }
        if (outputFrame == NULL) {
            continue;
        }
        if (mDistortionTransform != NULL) {
            outputFrame = outputFrame->doReverseDeformationBl<G12Buffer, DisplacementBuffer>(
                mDistortionTransform.data(),
                outputFrame->h, outputFrame->w
            );
        }
        delete mTransformedBuffers[currentOutputBlocks];
        mTransformedBuffers[currentOutputBlocks] = mTransformationCache[currentOutputBlocks]->doDeformation(mBaseParams->interpolationType(), outputFrame);
    }
    mProcessorGraph->clearAllData();
    if (mTransformedBuffers[0] == NULL)
    {
//        cout<<"mTransformedBuffers[0] == NULL"<<endl;
        Frames::FrameSourceId frameId = (Frames::FrameSourceId)0;
        G12Buffer *inputFrame  = mFrames.getCurrentFrame(frameId);
        mTransformedBuffers[0] = mTransformationCache[0]->doDeformation(mBaseParams->interpolationType(), inputFrame);
    }
//    else
//        cout<<"mTransformedBuffers[0] != NULL"<<endl;
    if (mTransformedBuffers[1] == NULL)
    {
//        cout<<"mTransformedBuffers[1] == NULL"<<endl;
        Frames::FrameSourceId frameId = (Frames::FrameSourceId)1;
        G12Buffer *inputFrame  = mFrames.getCurrentFrame(frameId);
        mTransformedBuffers[1] = mTransformationCache[1]->doDeformation(mBaseParams->interpolationType(), inputFrame);
    }
//    else
//        cout<<"mTransformedBuffers[1] != NULL"<<endl;
}
void BaseCalculationThread::filterControlParametersChanged (Frames::FrameSourceId id, QSharedPointer< FilterSelectorParameters > params) [virtual, slot, inherited]
Definition at line 252 of file baseCalculationThread.cpp.
References BaseCalculationThread::mFilterExecuter.
{
    qDebug("BaseCalculationThread::filterControlParametersChanged(%d, _): Filter params received in BaseCalculationThread", id);
    /*if (id == Frames::LEFT_FRAME) {
        return;
    }*/
    params->printParams();
    delete mFilterExecuter[id];
    mFilterExecuter[id] = new FilterExecuter(*params);
}
virtual CalculationState AbstractCalculationThread::getCalculationState () const [inline, virtual, inherited]
Definition at line 95 of file abstractCalculationThread.h.
References AbstractCalculationThread::mCurrentState.
Referenced by BaseHostDialog::play().
        {
            return mCurrentState;
        }
Frames* AbstractCalculationThread::getFramesHolder () [inline, inherited]
Definition at line 100 of file abstractCalculationThread.h.
References AbstractCalculationThread::mFrames.
Referenced by BaseHostDialog::initCalculator().
        {
            return &mFrames;
        }
void BaseCalculationThread::graphChanged (tinyxml2::XMLDocument * doc) [virtual, slot, inherited]
Definition at line 244 of file baseCalculationThread.cpp.
References corecvs::FilterGraph::deserialize(), AbstractCalculationThread::mFiltersCollection, and BaseCalculationThread::mProcessorGraph.
{
//    cout << "graphChanged slot here!" << endl;
    delete_safe(mProcessorGraph);
    mProcessorGraph = new FilterGraph(&mFiltersCollection, NULL);
    mProcessorGraph->deserialize(doc);
}
void BaseCalculationThread::initData (BaseOutputData * data, Statistics * stats = NULL) [protected, inherited]
Definition at line 63 of file baseCalculationThread.cpp.
References ResultImage::addLayer(), BaseCalculationThread::executeFilterGraph(), Frames::getCurrentFrame(), Frames::LEFT_FRAME, BaseCalculationThread::mActiveInputsNumber, BaseCalculationThread::mBaseParams, AbstractCalculationThread::mFrames, BaseOutputData::mMainImage, BaseCalculationThread::mPresentationParams, BaseCalculationThread::mTransformedBuffers, AbstractCalculationThread::pauseCalculation(), BaseCalculationThread::recalculateCache(), Frames::RIGHT_FRAME, ResultImage::setHeight(), ResultImage::setWidth(), BaseCalculationThread::transformInputFrames(), and CamerasConfigParameters::TwoCapDev.
Referenced by BaseCalculationThread::processNewData().
{
    recalculateCache();
    if (mBaseParams.isNull())
        return;
    // We are missing data, so pause calculation
    if ((!mFrames.getCurrentFrame(Frames::LEFT_FRAME) ) ||
       ((!mFrames.getCurrentFrame(Frames::RIGHT_FRAME)) && (CamerasConfigParameters::TwoCapDev == mActiveInputsNumber)))
    {
        pauseCalculation();
    }
    if (mBaseParams->enableFilterGraph()) {
        executeFilterGraph(stats);
    } else {
        transformInputFrames();
    }
    calculationOutputData->mMainImage.addLayer(
            new ImageResultLayer(
                    mPresentationParams->output(),
                    mTransformedBuffers,
                    mPresentationParams->leftFrame()
            )
    );
    calculationOutputData->mMainImage.setHeight(mBaseParams->h());
    calculationOutputData->mMainImage.setWidth (mBaseParams->w());
}
void AbstractCalculationThread::newFrameReady (frame_data_t frameData) [protected, virtual, slot, inherited]
New frame data is ready to be processed.
Connect this slot to the newFrameReady signal emitted by the capture interface. In this slot we actually grab the frames and trigger the calculation.
Note:
Do not override this implementation unless you really know what you are doing.
This function processes the newFrames from the input queue. Depending on current state this function either processes of ignores input data.
If current state is CALCULATION_AWAITING_DATA the state is changed to CALCULATION_ACTIVE and the awaiting events queue is flushed by QCoreApplication::processEvents();
If current state is not CALCULATION_AWAITING_DATA all input is ignored
Here is the trick, this function can call newFrameReady recursively, but it will exit with dropped frame. No other function can change currentState, only next state is altered.
Definition at line 66 of file abstractCalculationThread.cpp.
References AbstractCalculationThread::CALCULATION_ACTIVE, AbstractCalculationThread::CALCULATION_AWAITING_DATA, AbstractCalculationThread::CALCULATION_PAUSED, AbstractCalculationThread::calculationStateChanged(), DOTRACE, Frames::fetchNewFrames(), Frames::getCurrentFrame(), Frames::MAX_INPUTS_NUMBER, AbstractCalculationThread::mCaptureInterface, AbstractCalculationThread::mCurrentState, AbstractCalculationThread::mFrames, AbstractCalculationThread::mInterframeDelay, AbstractCalculationThread::mLastFrameTimeStamp, AbstractCalculationThread::processingFinished(), AbstractCalculationThread::processNewData(), SYNC_PRINT, frame_data_t::timestamp, and Frames::timestamp().
{
//    cout << "AbstractCalculationThread::newFrameReady called..." << endl;
    //L_INFO_P("new frame notification");
    if (!mCaptureInterface)
    {
        cerr << "Image capture interface was not initialized\n";
        return;
    }
    if (mCurrentState != CALCULATION_AWAITING_DATA) {
        if (mCurrentState == CALCULATION_ACTIVE) {
            DOTRACE(("AbstractCalculationThread::dropped frame\n"));
        }
        return;
    }
    if (frameData.timestamp <= mLastFrameTimeStamp)
    {
        //cout << "Frame was received second time. Previous TS: "<< lastFrameTimeStamp << " Current TS: " << frameData.timestamp << "\n";
        return;
    }
    mCurrentState = CALCULATION_ACTIVE;
    //emit calculationStateChanged(getCalculationState());
    /**
     * Here is the trick, this function can call newFrameReady recursively,
     * but it will exit with dropped frame.
     * No other function can change currentState, only next state is altered.
     *
     **/
    QCoreApplication::processEvents();
    /* On exit from processEvents() we have flushed input queue of the thread */
    /* State can be changed already while in processEvents */
    if (mCurrentState == CALCULATION_ACTIVE)
    {
        uint64_t oldStamp   = mFrames.timestamp();
        mFrames.fetchNewFrames(mCaptureInterface);
        mInterframeDelay    = mFrames.timestamp() - oldStamp;
        mLastFrameTimeStamp = mFrames.timestamp();
/*
        cout << "AbstractCalculationThread::requesting frame..." << endl;
        if (interframeDelay == 0) {
            printf("Strange - two frames with same timestamp\n");
        }
*/
        bool ok = false;
        for (int id = 0; id <  Frames::MAX_INPUTS_NUMBER; id++) {
            ok |= (mFrames.getCurrentFrame((Frames::FrameSourceId)id) != NULL);
        }
        if (ok) /* At least one input is active */
        {
            AbstractOutputData *res = processNewData();
            if (res != NULL)
            {
                /* TODO: Possibly needs redesign. If signal is not processed there will
                be a memory leak. Use Smart pointers here */
                emit processingFinished(res);
            }
        } else {
            SYNC_PRINT(("AbstractCalculationThread::newFrameReady(): No good frames. All frames are NULL\n"));
        }
    }
    if (mCurrentState == CALCULATION_PAUSED) {
        emit calculationStateChanged(mCurrentState);
//        threadPaused.wakeAll();
    } else {
        mCurrentState = CALCULATION_AWAITING_DATA;
    }
}
void AbstractCalculationThread::pauseCalculation () [protected, virtual, slot, inherited]
Pauses calculation.
Should only be called as a asynchronous slot function
Definition at line 144 of file abstractCalculationThread.cpp.
References AbstractCalculationThread::CALCULATION_ACTIVE, AbstractCalculationThread::CALCULATION_AWAITING_DATA, AbstractCalculationThread::CALCULATION_PAUSED, AbstractCalculationThread::calculationStateChanged(), and AbstractCalculationThread::mCurrentState.
Referenced by BaseCalculationThread::initData(), and processNewData().
{
    if ((mCurrentState != CALCULATION_ACTIVE) && (mCurrentState != CALCULATION_AWAITING_DATA))
    {
        cout << "There is no calculation in progress - can't pause.\n";
        return;
    }
    if (mCurrentState == CALCULATION_AWAITING_DATA)
    {
        mCurrentState = CALCULATION_PAUSED;
        emit calculationStateChanged(mCurrentState);
//        threadPaused.wakeAll();
    }
    mCurrentState = CALCULATION_PAUSED;
}
void BaseCalculationThread::presentationControlParametersChanged (QSharedPointer< PresentationParameters > params) [virtual, slot, inherited]
Definition at line 274 of file baseCalculationThread.cpp.
References BaseCalculationThread::mPresentationParams.
{
    if (!params.isNull())
        mPresentationParams = params;
}
void AbstractCalculationThread::processingFinished (AbstractOutputData * output) [signal, inherited]
Referenced by AbstractCalculationThread::newFrameReady().
AbstractOutputData * RecorderThread::processNewData () [protected, virtual]
This is the main calculation routine called when a new frame is received.
Reimplemented from BaseCalculationThread.
Definition at line 72 of file recorderThread.cpp.
References ResultImage::addLayer(), corecvs::TransformationCache::doDeformation(), errorMessage(), RecorderOutputData::frameCount, Frames::getCurrentFrame(), Frames::LEFT_FRAME, BaseCalculationThread::mActiveInputsNumber, Frames::MAX_INPUTS_NUMBER, BaseCalculationThread::mBaseParams, mFrameCount, AbstractCalculationThread::mFrames, mIdleTimer, mIsRecording, BaseOutputData::mMainImage, mPath, BaseCalculationThread::mPresentationParams, mRecorderParameters, mSaver, BaseCalculationThread::mTransformationCache, AbstractCalculationThread::pauseCalculation(), BaseCalculationThread::recalculateCache(), recordingStateChanged(), resetRecording(), Frames::RIGHT_FRAME, corecvs::PPMLoader::save(), ResultImage::setHeight(), corecvs::Statistics::setTime(), ResultImage::setWidth(), StateRecordingFailure, RecorderOutputData::stats, CamerasConfigParameters::TwoCapDev, and corecvs::PreciseTimer::usecsToNow().
{
    Statistics stats;
#if 0
    stats.setTime(ViFlowStatisticsDescriptor::IDLE_TIME, mIdleTimer.usecsToNow());
#endif
    PreciseTimer start = PreciseTimer::currentTime();
    PreciseTimer startEl = PreciseTimer::currentTime();
    bool have_params = !(mRecorderParameters.isNull());
    bool two_frames = have_params && (CamerasConfigParameters::TwoCapDev == mActiveInputsNumber); // FIXME: additional params needed here
    // We are missing data, so pause calculation
    if ((!mFrames.getCurrentFrame(Frames::LEFT_FRAME) ) ||
       ((!mFrames.getCurrentFrame(Frames::RIGHT_FRAME)) && (CamerasConfigParameters::TwoCapDev == mActiveInputsNumber)))
    {
        emit errorMessage("Capture error.");
        pauseCalculation();
    }
    recalculateCache();
    G12Buffer *result[Frames::MAX_INPUTS_NUMBER] = {NULL, NULL};
    /*TODO: Logic here should be changed according to the host base change*/
    for (int id = 0; id < mActiveInputsNumber; id++)
    {
        G12Buffer *buf = mFrames.getCurrentFrame((Frames::FrameSourceId)id);
        result[id] = mTransformationCache[id] ? mTransformationCache[id]->doDeformation(mBaseParams->interpolationType(), buf) : buf;
        if (mIsRecording)
        {
            char currentPath[256];
            if (two_frames)
                snprintf2buf(currentPath, mPath.toStdString().c_str(), mFrameCount, id);
            else
                snprintf2buf(currentPath, mPath.toStdString().c_str(), mFrameCount);
            if (mSaver.save(currentPath, result[id]))
            {
                resetRecording();
                emit errorMessage(QString("Error writing frame to file") + currentPath);
                emit recordingStateChanged(StateRecordingFailure);
            }
        }
    }
#if 0
    stats.setTime(ViFlowStatisticsDescriptor::CORRECTON_TIME, startEl.usecsToNow());
#endif
    if (mIsRecording) {
        mFrameCount++;
    }
    RecorderOutputData* outputData = new RecorderOutputData();
    outputData->mMainImage.addLayer(
            new ImageResultLayer(
                    mPresentationParams->output(),
                    result,
                    mPresentationParams->leftFrame()
            )
    );
    outputData->mMainImage.setHeight(mBaseParams->h());
    outputData->mMainImage.setWidth (mBaseParams->w());
#if 0
    stats.setTime(ViFlowStatisticsDescriptor::TOTAL_TIME, start.usecsToNow());
#endif
    mIdleTimer = PreciseTimer::currentTime();
    for (int id = 0; id < mActiveInputsNumber; id++)
    {
        if (result[id] != mFrames.getCurrentFrame((Frames::FrameSourceId)id)) {
             delete_safe(result[id]);
        }
    }
    outputData->frameCount = this->mFrameCount;
    outputData->stats = stats;
    return outputData;
}
void BaseCalculationThread::recalculateCache () [protected, inherited]
As the transformation procedure uses the inverse of the transformation matrix We first apply the rectification matrix, and then the scaling and shift.
With inverses it is vice versa
We have a description of the math here - corecvs::StereoAligner::getAlignmentTransformation()
Let's have a look starting form camera input to rectification input image
1. CS = First we shift image by half to put it's center to [0,0] 2. MI = Second we make mirror and rotation operation 3. BH = Then we shift it back to where it was 4. SH = We make a shift of the mirrored image 5. SL = Afterwards we scale
Total transformation T1 = SL * SH * (BH * MI * CS)
as BH = CS^(-1) T1^(-1) = BH * MI * CS * SH * SL
T1 transforms from camera image to rectification input image T1^(-1) transforms from rectification input image to camera image
following the operation from corecvs::StereoAligner we have a rectification transformation for camera images - H_left and H_right.
H_left - from camera input to rectified image H_left^(-1)
Definition at line 329 of file baseCalculationThread.cpp.
References corecvs::RectificationResult::addPretransform(), RotationPresets::CLOCKWISE_180DEG, RotationPresets::CLOCKWISE_270DEG, RotationPresets::CLOCKWISE_90DEG, Frames::getCurrentFrame(), corecvs::AbstractBuffer< ElementType, IndexType >::getSize(), corecvs::AbstractBufferParams::h, corecvs::AbstractBuffer< ElementType, IndexType >::hasSameSize(), corecvs::Matrix33::inv(), Frames::LEFT_FRAME, InputType::LEFT_FRAME, corecvs::RectificationResult::leftTransform, BaseCalculationThread::mActiveInputsNumber, BaseCalculationThread::mBaseParams, BaseCalculationThread::mCacheUpdateNeeded, AbstractCalculationThread::mFrames, BaseCalculationThread::mFrameTransformsInv, BaseCalculationThread::mInputPretransform, BaseCalculationThread::mInputPretransformInv, BaseCalculationThread::mPretransformedRectificationData, BaseCalculationThread::mRectificationData, BaseCalculationThread::mTransformationCache, InputType::RIGHT_FRAME, corecvs::RectificationResult::rightTransform, and corecvs::AbstractBufferParams::w.
Referenced by BaseCalculationThread::initData(), and processNewData().
{
    G12Buffer *firstInput = mFrames.getCurrentFrame(Frames::LEFT_FRAME);
    if (!mCacheUpdateNeeded || firstInput == NULL)
        return;
    if (mBaseParams->downsample() == 0)
        mBaseParams->setDownsample(1);
    if (mBaseParams->autoH())
        mBaseParams->setH(firstInput->h / mBaseParams->downsample());
    if (mBaseParams->autoW())
        mBaseParams->setW(firstInput->w / mBaseParams->downsample());
    /* Now we know the corrected params */
    double mDownsample = mBaseParams->downsample();
    int const x = mBaseParams->x();
    int const y = mBaseParams->y();
    int const h = mBaseParams->h();
    int const w = mBaseParams->w();
    Matrix33 centerShift     = Matrix33::ShiftProj(-firstInput->w / 2.0, -firstInput->h / 2.0);
    Matrix33 centerBackShift = Matrix33::ShiftProj( firstInput->w / 2.0,  firstInput->h / 2.0);
    Matrix33 centerAction(1.0);
    switch (mBaseParams->rotation())
    {
        /* Note that clockwise rotation is against the direction common to math notation */
        case RotationPresets::CLOCKWISE_90DEG :  centerAction = Matrix33::RotationZ270(); break;
        case RotationPresets::CLOCKWISE_180DEG:  centerAction = Matrix33::RotationZ180(); break;
        case RotationPresets::CLOCKWISE_270DEG:  centerAction = Matrix33::RotationZ90();  break;
        default:                                 centerAction = Matrix33(1.0);            break;
    }
    if (mBaseParams->mirror()) {
        centerAction = Matrix33::MirrorYZ() * centerAction;
    }
    mInputPretransform    = Matrix33::Scale2(1.0 / mDownsample) * Matrix33::ShiftProj(-x, -y) * centerBackShift * centerAction * centerShift;
    mInputPretransformInv = mInputPretransform.inv();
    mPretransformedRectificationData = mRectificationData.addPretransform(mInputPretransform);
    mFrameTransformsInv[Frames::RIGHT_FRAME] = mPretransformedRectificationData.rightTransform.inv();
    mFrameTransformsInv[Frames::LEFT_FRAME]  = mPretransformedRectificationData.leftTransform .inv();
    for (int i = 0; i < mActiveInputsNumber; i++)
    {
        G12Buffer *currentBuffer = mFrames.getCurrentFrame((Frames::FrameSourceId)i);
        Q_ASSERT(currentBuffer != NULL);
        Q_ASSERT(currentBuffer->hasSameSize(firstInput));
        delete mTransformationCache[i];
        mTransformationCache[i] = new TransformationCache(mFrameTransformsInv[i], w, h, currentBuffer->getSize());
#ifdef WITH_HARDWARE
        //Matrix33 mat = Matrix33::Scale2(1.08) * Matrix33::ShiftProj(-39.5, -39.5) * Matrix33::RotateProj(6.0 / 128.0);
        try {
            mHardwareCorrectors[i] -> configure(w, h,  mFrameTransformsInv[i]);//  mat); // mFrameTransformsInv[i]);
            mHardwareCorrectors[i] -> allocReadBuffers();
        } catch (Failure fail ) {
            qDebug() << fail.getReason().c_str();
        }
#endif
    }
    mCacheUpdateNeeded = false;
}
void RecorderThread::recorderControlParametersChanged (QSharedPointer< Recorder > params) [slot]
Definition at line 167 of file recorderThread.cpp.
References mPath, and mRecorderParameters.
{
    if (!recorderParameters)
        return;
    mRecorderParameters = recorderParameters;
    mPath = QString(recorderParameters->path().c_str()) + "/" + QString(recorderParameters->fileTemplate().c_str());
}
void RecorderThread::recordingStateChanged (RecorderThread::RecordingState state) [signal]
Referenced by processNewData(), resetRecording(), and toggleRecording().
void RecorderThread::resetRecording () [slot]
Definition at line 158 of file recorderThread.cpp.
References mFrameCount, mIsRecording, mPath, mRecordingStarted, recordingStateChanged(), and StateRecordingReset.
Referenced by processNewData().
{
    mIsRecording = false;
    mRecordingStarted = false;
    mPath = "";
    mFrameCount = 0;
    emit recordingStateChanged(StateRecordingReset);
}
void AbstractCalculationThread::resumeCalculation () [protected, virtual, slot, inherited]
Resumes calculation Should only be called as a asynchronous slot function.
Definition at line 161 of file abstractCalculationThread.cpp.
References AbstractCalculationThread::CALCULATION_AWAITING_DATA, AbstractCalculationThread::CALCULATION_NOT_STARTED, AbstractCalculationThread::CALCULATION_PAUSED, AbstractCalculationThread::calculationStateChanged(), and AbstractCalculationThread::mCurrentState.
{
    if (mCurrentState == CALCULATION_NOT_STARTED)
    {
        cout << "Use start() for the first time.\n";
        return;
    }
    if (mCurrentState == CALCULATION_PAUSED)
    {
        mCurrentState = CALCULATION_AWAITING_DATA;
        emit calculationStateChanged(mCurrentState);
    }
}
void AbstractCalculationThread::run (void) [virtual, inherited]
Definition at line 51 of file abstractCalculationThread.cpp.
References AbstractCalculationThread::CALCULATION_AWAITING_DATA, AbstractCalculationThread::CALCULATION_TERMINATED, and AbstractCalculationThread::mCurrentState.
{
//    stateLock.lock();
    mCurrentState = CALCULATION_AWAITING_DATA;
//    stateLock.unlock();
    cout << "AbstractCalculationThread::run(): starting event loop.\n";
    exec();
    cout << "AbstractCalculationThread::run(): event loop terminated.\n";
//    stateLock.lock();
    mCurrentState = CALCULATION_TERMINATED;
//    stateLock.unlock();
}
virtual void AbstractCalculationThread::setCalculationState (CalculationState state) [inline, virtual, inherited]
Definition at line 90 of file abstractCalculationThread.h.
References AbstractCalculationThread::mCurrentState.
        {
            mCurrentState = state;
        }
void AbstractCalculationThread::setImageCaptureInterface (ImageCaptureInterface * captureInterface) [inline, inherited]
Definition at line 107 of file abstractCalculationThread.h.
References AbstractCalculationThread::mCaptureInterface, and AbstractCalculationThread::mLastFrameTimeStamp.
Referenced by BaseHostDialog::initCapture(), and BaseHostDialog::stopCalculation().
        {
            mCaptureInterface = captureInterface;
            mLastFrameTimeStamp = 0;
        }
void BaseCalculationThread::setLeftTransform (Matrix33 & leftTransform) [inherited]
void RecorderThread::toggleRecording () [slot]
Definition at line 33 of file recorderThread.cpp.
References mIsRecording, mRecorderParameters, mRecordingStarted, recordingStateChanged(), StateRecordingActive, and StateRecordingPaused.
{
    if (!mIsRecording)
    {
        if (mRecorderParameters.isNull())
        {
            cout << "RecorderThread: Internal error. Recording toggled but no parameters provided." << endl;
        }
        if (mRecorderParameters->path().empty())
        {
            cout << "RecorderThread: Path is empty" << endl;
        }
        if (mRecorderParameters->fileTemplate().empty())
        {
            cout << "RecorderThread: File template is empty\n";
        }
        if (!mRecordingStarted)
        {
            mRecordingStarted = true;
            printf("Recording started.\n");
        }
        else
        {
            printf("Recording resumed.\n");
        }
        mIsRecording = true;
        emit recordingStateChanged(StateRecordingActive);
    }
    else
    {
        mIsRecording = false;
        printf("Recording paused.\n");
        emit recordingStateChanged(StateRecordingPaused);
    }
}
void BaseCalculationThread::transformInputFrames () [protected, inherited]
Definition at line 176 of file baseCalculationThread.cpp.
References corecvs::TransformationCache::doDeformation(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformationBl(), corecvs::FilterExecuter::filter(), Frames::getCurrentFrame(), corecvs::AbstractBufferParams::h, InterpolationType::HARDWARE, BaseCalculationThread::mActiveInputsNumber, BaseCalculationThread::mBaseParams, BaseCalculationThread::mDistortionTransform, BaseCalculationThread::mFilterExecuter, AbstractCalculationThread::mFrames, BaseCalculationThread::mTransformationCache, BaseCalculationThread::mTransformedBuffers, and corecvs::AbstractBufferParams::w.
Referenced by BaseCalculationThread::initData().
{
    for (int i = 0; i < mActiveInputsNumber; i++)
    {
        Frames::FrameSourceId frameId = (Frames::FrameSourceId)i;
        G12Buffer *inputFrame     = mFrames.getCurrentFrame(frameId);
        G12Buffer *inputFrameOrig = inputFrame;
        if (mFilterExecuter[i] != NULL && !mFilterExecuter[i]->mFilters.empty())
        {
            G12Buffer *newInputFrame = mFilterExecuter[i]->filter(inputFrame);
            inputFrame = newInputFrame;
        }
        if (mDistortionTransform != NULL)
        {
            G12Buffer *newInputFrame = inputFrame->doReverseDeformationBl<G12Buffer, DisplacementBuffer>(
                mDistortionTransform.data(),
                inputFrame->h, inputFrame->w
            );
            if (inputFrame != inputFrameOrig)
                delete inputFrame;
            inputFrame = newInputFrame;
        }
        delete_safe (mTransformedBuffers[i]);
#ifdef WITH_HARDWARE
        if (mBaseParams->interpolationType() == InterpolationType::HARDWARE)
        {
            try {
                mTransformedBuffers[i] = new G12Buffer(inputFrame);
                mHardwareCorrectors[i] -> processABuffer(1, *(mTransformedBuffers[i]));
            } catch (Failure fail ) {
                qDebug() << fail.getReason().c_str();
            }
        } else
        {
#endif
        mTransformedBuffers[i] = mTransformationCache[i]->doDeformation(mBaseParams->interpolationType(), inputFrame);
#ifdef WITH_HARDWARE
        }
#endif
        if (inputFrame != inputFrameOrig)
        {
            delete_safe(inputFrame);
        }
    } // for (int i = 0; i < mInputsN; i++)
}
Member Data Documentation
int BaseCalculationThread::mActiveInputsNumber [protected, inherited]
Definition at line 114 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::camerasParametersChanged(), BaseCalculationThread::initData(), processNewData(), BaseCalculationThread::recalculateCache(), and BaseCalculationThread::transformInputFrames().
QSharedPointer<BaseParameters> BaseCalculationThread::mBaseParams [protected, inherited]
Definition at line 116 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::baseControlParametersChanged(), BaseCalculationThread::executeFilterGraph(), BaseCalculationThread::initData(), processNewData(), BaseCalculationThread::recalculateCache(), and BaseCalculationThread::transformInputFrames().
bool BaseCalculationThread::mCacheUpdateNeeded [protected, inherited]
For a thread to start calculating it needs first frame and the input parameters.
When we get new params, we should recalculate cached data.
Definition at line 124 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::baseControlParametersChanged(), BaseCalculationThread::camerasParametersChanged(), and BaseCalculationThread::recalculateCache().
ImageCaptureInterface* AbstractCalculationThread::mCaptureInterface [protected, inherited]
The capture interface we fetch the frames from.
Definition at line 117 of file abstractCalculationThread.h.
Referenced by AbstractCalculationThread::newFrameReady(), and AbstractCalculationThread::setImageCaptureInterface().
CalculationState AbstractCalculationThread::mCurrentState [protected, inherited]
Current calculation state This state can't be changed directly, but can be queried.
Definition at line 135 of file abstractCalculationThread.h.
Referenced by AbstractCalculationThread::getCalculationState(), AbstractCalculationThread::newFrameReady(), AbstractCalculationThread::pauseCalculation(), AbstractCalculationThread::resumeCalculation(), AbstractCalculationThread::run(), and AbstractCalculationThread::setCalculationState().
QSharedPointer<DisplacementBuffer> BaseCalculationThread::mDistortionTransform [protected, inherited]
This is a lens precorrection.
Definition at line 111 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::camerasParametersChanged(), BaseCalculationThread::executeFilterGraph(), BaseCalculationThread::transformInputFrames(), and BaseCalculationThread::~BaseCalculationThread().
FilterExecuter* BaseCalculationThread::mFilterExecuter[Frames::MAX_INPUTS_NUMBER] [protected, inherited]
Definition at line 86 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::BaseCalculationThread(), BaseCalculationThread::filterControlParametersChanged(), BaseCalculationThread::transformInputFrames(), and BaseCalculationThread::~BaseCalculationThread().
FiltersCollection AbstractCalculationThread::mFiltersCollection [inherited]
Definition at line 152 of file abstractCalculationThread.h.
Referenced by BaseCalculationThread::BaseCalculationThread(), BaseCalculationThread::graphChanged(), and BaseHostDialog::initGraphPresentation().
uint32_t RecorderThread::mFrameCount [private]
Definition at line 72 of file recorderThread.h.
Referenced by processNewData(), and resetRecording().
Frames AbstractCalculationThread::mFrames [protected, inherited]
Holds the last two sets of frames acquired from the capture device(s)
Definition at line 122 of file abstractCalculationThread.h.
Referenced by BaseCalculationThread::executeFilterGraph(), AbstractCalculationThread::getFramesHolder(), BaseCalculationThread::initData(), AbstractCalculationThread::newFrameReady(), processNewData(), BaseCalculationThread::recalculateCache(), and BaseCalculationThread::transformInputFrames().
Matrix33 BaseCalculationThread::mFrameTransforms[Frames::MAX_INPUTS_NUMBER] [protected, inherited]
The transforms from original input image camera image to rectified image.
Definition at line 102 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::BaseCalculationThread().
Matrix33 BaseCalculationThread::mFrameTransformsInv[Frames::MAX_INPUTS_NUMBER] [protected, inherited]
Inverse of previous to use in interpolation of the buffer.
Definition at line 106 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::recalculateCache().
PreciseTimer RecorderThread::mIdleTimer [private]
Definition at line 67 of file recorderThread.h.
Referenced by processNewData(), and RecorderThread().
Matrix33 BaseCalculationThread::mInputPretransform [protected, inherited]
Definition at line 95 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::recalculateCache().
Matrix33 BaseCalculationThread::mInputPretransformInv [protected, inherited]
Definition at line 97 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::recalculateCache().
uint64_t AbstractCalculationThread::mInterframeDelay [protected, inherited]
Delay between this and previous frame.
Definition at line 127 of file abstractCalculationThread.h.
Referenced by AbstractCalculationThread::newFrameReady().
bool RecorderThread::mIsRecording [private]
Definition at line 66 of file recorderThread.h.
Referenced by processNewData(), resetRecording(), and toggleRecording().
uint64_t AbstractCalculationThread::mLastFrameTimeStamp [protected, inherited]
Definition at line 129 of file abstractCalculationThread.h.
Referenced by AbstractCalculationThread::newFrameReady(), and AbstractCalculationThread::setImageCaptureInterface().
QString RecorderThread::mPath [private]
Definition at line 73 of file recorderThread.h.
Referenced by processNewData(), recorderControlParametersChanged(), and resetRecording().
QSharedPointer<PresentationParameters> BaseCalculationThread::mPresentationParams [protected, inherited]
Definition at line 117 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::initData(), BaseCalculationThread::presentationControlParametersChanged(), and processNewData().
RectificationResult BaseCalculationThread::mPretransformedRectificationData [protected, inherited]
Definition at line 92 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::recalculateCache().
FilterGraph* BaseCalculationThread::mProcessorGraph [protected, inherited]
Definition at line 125 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::BaseCalculationThread(), BaseCalculationThread::executeFilterGraph(), BaseCalculationThread::graphChanged(), and BaseCalculationThread::~BaseCalculationThread().
QSharedPointer<Recorder> RecorderThread::mRecorderParameters [private]
Definition at line 74 of file recorderThread.h.
Referenced by processNewData(), recorderControlParametersChanged(), and toggleRecording().
bool RecorderThread::mRecordingStarted [private]
Definition at line 65 of file recorderThread.h.
Referenced by resetRecording(), and toggleRecording().
RectificationResult BaseCalculationThread::mRectificationData [protected, inherited]
Definition at line 89 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::camerasParametersChanged(), and BaseCalculationThread::recalculateCache().
PPMLoader RecorderThread::mSaver [private]
Definition at line 70 of file recorderThread.h.
Referenced by processNewData().
TransformationCache* BaseCalculationThread::mTransformationCache[Frames::MAX_INPUTS_NUMBER] [protected, inherited]
The cache of the transformation applied to the left and right image.
Definition at line 66 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::BaseCalculationThread(), BaseCalculationThread::executeFilterGraph(), processNewData(), BaseCalculationThread::recalculateCache(), BaseCalculationThread::transformInputFrames(), and BaseCalculationThread::~BaseCalculationThread().
G12Buffer* BaseCalculationThread::mTransformedBuffers[Frames::MAX_INPUTS_NUMBER] [protected, inherited]
Transformed buffers.
Definition at line 75 of file baseCalculationThread.h.
Referenced by BaseCalculationThread::BaseCalculationThread(), BaseCalculationThread::executeFilterGraph(), BaseCalculationThread::initData(), BaseCalculationThread::transformInputFrames(), and BaseCalculationThread::~BaseCalculationThread().
const char * AbstractCalculationThread::stateNames [static, inherited]
Initial value:
{
    "Not started",
    "Awaiting data",
    "Active",
    "Paused",
    "Terminated"
}
Definition at line 50 of file abstractCalculationThread.h.
Referenced by BaseHostDialog::calculationStateChanged(), and BaseHostDialog::play().
The documentation for this class was generated from the following files:
applications/recorder/recorderThread.h
applications/recorder/recorderThread.cpp