DeepView: corecvs::Matrix Class Reference
corecvs::Matrix Class Reference
#include <matrix.h>
Public Types
enum InverstionAlgorithm { INVERT_LU, INVERT_SVD }
enum BufferType { NORMAL_BUFFER, VIEW_BUFFER, EMPTY_BUFFER }
typedef ElementType InternalElementType
Type of the internal data type.
typedef IndexType InternalIndexType
Public Member Functions
Matrix (int32_t h, int32_t w)
This function creates a matrix with all zero elements.
Matrix (const Matrix &that)
Matrix (const Matrix *that)
Matrix (const DiagonalMatrix &that)
Matrix (Matrix *src, int32_t x1, int32_t y1, int32_t x2, int32_t y2)
Matrix (int32_t h, int32_t w, double *data)
This function creates a matrix filling it with values form the given array line by line.
Matrix (int32_t h, int32_t w, double value)
This constructs the diagonal matrix.
Matrix (int32_t h, int32_t w, bool shouldInit)
Matrix (Matrix33 &in)
Matrix (Matrix44 &in)
double & a (int32_t y, int32_t x)
The element getter for a matrix that is used like vector (i.e has height or width of 1)
const double & a (int32_t y, int32_t x) const
Matrix * mul (const Matrix &V)
Matrix multiplication.
Matrix * transposed () const
Matrix transposition.
Matrix t () const
void transpose ()
double trace (void) const
double frobeniusNorm () const
Matrix & operator+= (const Matrix &V)
Matrix & operator-= (const Matrix &V)
Matrix & operator*= (const double v)
Multiply matrix by scalar .
Matrix & operator/= (const double v)
Divide matrix by scalar .
bool operator== (const Matrix &M) const
Check matrix for equality.
operator Matrix33 () const
void neg ()
All elements are negated .
Matrix negative () const
Matrix inv () const
This function returns an inverse of the matrix.
Matrix invSVD () const
double detSVD () const
void print ()
bool notTooFar (const Matrix *V, double epsilon=0.0) const
template<typename ResultType >
ResultType * createView (const IndexType y, const IndexType x, const IndexType h, const IndexType w)
template<typename ResultType >
ResultType * createView ()
ElementType & element (const IndexType y, const IndexType x)
The element getter.
const ElementType & element (const IndexType y, const IndexType x) const
ElementType & element (const Vector2d< IndexType > &p)
The element getter.
const ElementType & element (const Vector2d< IndexType > &p) const
bool isValidCoord (const IndexType y, const IndexType x) const
Checks if coordinate lies within the buffer area.
bool isValidCoord (const Vector2d< IndexType > &p) const
Checks if coordinate lies within the buffer area.
bool hasSameSize (const AbstractBuffer< ElementType, IndexType > *other) const
Checks if this buffer has the same size as the other.
bool hasSameSize (const IndexType &otherH, const IndexType &otherW) const
Checks if this buffer has the same size as the parameters given.
IndexType getH () const
Height getter.
IndexType getStride () const
Stride getter.
IndexType getW () const
Width getter.
Vector2d< IndexType > getSize () const
Buffer size getter.
bool isAllocated () const
Checking for successfull allocation.
size_t sizeInBytes () const
Calculate image buffer size in bytes.
void fillRectangleWith (IndexType y, IndexType x, IndexType rectH, IndexType rectW, const ElementType &value)
This function fills the rectangle inside the buffer with the value.
void fillWith (const ElementType &value)
This function fills the whole buffer with the value.
void fillWith (const AbstractBuffer &other)
This function fills the whole buffer with the values from the other buffer.
void fillWithRaw (ElementType *_data)
This function fills the whole buffer with the values from the given array.
void fillWithArgs (const ElementType value, va_list marker)
You could use this to clean the buffer.
void fillWithArgs (const ElementType value,...)
void fillLineWithArgs (IndexType line, const ElementType value,...)
void fillWithRands (ElementType valueMax, ElementType valueMin=ElementType(0))
Fills the buffer by random values within the given range.
template<typename ReturnType , typename ConvElementType , typename ConvIndexType >
void innerCycleDoConvolve (ReturnType *toReturn, AbstractKernel< ConvElementType, ConvIndexType > *kernel, int i)
template<typename ReturnType , typename ConvElementType , typename ConvIndexType >
ReturnType * doConvolve (AbstractKernel< ConvElementType, ConvIndexType > *kernel)
This function is used to convolve/cross-correlate a buffer with the kernel.
template<typename ReturnType , typename ConvElementType , typename ConvIndexType >
ReturnType * doConvolve1 (AbstractKernel< ConvElementType, ConvIndexType > *kernel)
bool isEqual (const AbstractBuffer &that) const
This method tests for equality.
bool isEqualTrace (const AbstractBuffer &that) const
template<typename operation >
void binaryOperationInPlace (const AbstractBuffer &that, const operation &oper=operation())
This method performs the "oper" operation between this and that buffers and puts result to this buffer.
template<typename operation >
void mapOperationElementwize (const operation &map)
template<typename operation >
void touchOperationElementwize (operation &map)
bool dump (ostream &s, bool binaryMode) const
bool load (istream &s, bool binaryMode)
template<typename OtherType >
OtherType * mirrorVerticalDump ()
Please check that you really don't want to invoke the copy constructor.
void mirrorVertical ()
Mirrors current buffer vertically.
template<typename OtherType >
OtherType * mirrorVertical ()
void rotate180 ()
Rotates current buffer 180 degrees.
int numElements () const
Calculate number of elements in a buffer.
Static Public Member Functions
static void svd (Matrix *A, Matrix *W, Matrix *V)
This method contains SVD implementation.
static void svd (Matrix33 *A, Vector3dd *W, Matrix33 *V)
static void svdDesc (Matrix33 *A, Vector3dd *W, Matrix33 *V)
static bool matrixSolveGaussian (Matrix *A, Matrix *B)
Solves the linear equation.
Public Attributes
ElementType * data
Sometimes underling buffer should not be deleted.
int h
int w
int stride
Static Public Attributes
static const int DATA_ALIGN_GRANULARITY = 0xF
This constant represents the default alignment of the line in the buffer.
static int bufferCount = 0
Static member that will be used to prevent and debug memory leaks.
static const IndexType STRIDE_AUTO = (IndexType)0
The height of the buffer.
static cchar TAB = '\t'
Protected Member Functions
bool_t dump (ostream &s, uint elemSize, bool_t binaryMode) const
bool_t load (istream &s, uint elemSize, bool_t binaryMode)
void setH (int _h)
void setW (int _w)
void setStride (int _s)
Static Protected Member Functions
static bool_t dump (ostream &s, int h, int w, int stride, uint elemSize, bool_t binaryMode)
static bool_t load (istream &s, int &h, int &w, int &stride, uint elemSize, bool_t binaryMode)
static bool_t write (ostream &s, int val, bool_t binaryMode)
static bool_t write (ostream &s, cchar *str, bool_t binaryMode)
static bool_t read (istream &s, int &val, bool_t binaryMode)
static bool_t read (istream &s, char *str, size_t size, bool_t binaryMode)
template<size_t size>
static bool_t read (istream &s, char(&str)[size], bool_t binaryMode)
Protected Attributes
MemoryBlockRef memoryBlock
The beginning of the allocated memory.
BufferType flags
Friends
Matrix operator* (const Matrix &A, const Matrix &B)
Matrix operator+ (const Matrix &A, const Matrix &B)
Matrix operator- (const Matrix &A, const Matrix &B)
Matrix operator*= (Matrix &M, const DiagonalMatrix &D)
Matrix operator* (const Matrix &M, const DiagonalMatrix &D)
Matrix operator* (const DiagonalMatrix &D, const Matrix &M)
Vector operator* (const Matrix &M, const Vector &V)
Vector operator* (const Vector &V, const Matrix &M)
ostream & operator<< (ostream &out, const Matrix &matrix)
ostream & operator<< (ostream &out, const AbstractBuffer &buffer)
Detailed Description
Definition at line 31 of file matrix.h.
Member Typedef Documentation
template<typename ElementType, typename IndexType = int32_t> typedef ElementType corecvs::AbstractBuffer< ElementType, IndexType >::InternalElementType [inherited]
Type of the internal data type.
Definition at line 168 of file abstractBuffer.h.
template<typename ElementType, typename IndexType = int32_t> typedef IndexType corecvs::AbstractBuffer< ElementType, IndexType >::InternalIndexType [inherited]
Definition at line 169 of file abstractBuffer.h.
Member Enumeration Documentation
template<typename ElementType, typename IndexType = int32_t> enum corecvs::AbstractBuffer::BufferType [inherited]
Enumerator:
NORMAL_BUFFER
VIEW_BUFFER
EMPTY_BUFFER
Definition at line 171 of file abstractBuffer.h.
                    {
        NORMAL_BUFFER,
        VIEW_BUFFER,
        EMPTY_BUFFER
    };
enum corecvs::Matrix::InverstionAlgorithm
Enumerator:
INVERT_LU
INVERT_SVD
Definition at line 34 of file matrix.h.
{
        INVERT_LU,
        INVERT_SVD
    };
Constructor & Destructor Documentation
corecvs::Matrix::Matrix (int32_t h, int32_t w) [inline]
This function creates a matrix with all zero elements.
Parameters:
h The height of the matrix
w The width of the matrix
Definition at line 48 of file matrix.h.
Referenced by mul(), and transposed().
: MatrixBase (h, w) {};
corecvs::Matrix::Matrix (const Matrix & that) [inline]
Definition at line 50 of file matrix.h.
: MatrixBase (that) {};
corecvs::Matrix::Matrix (const Matrix * that) [inline, explicit]
Definition at line 51 of file matrix.h.
: MatrixBase (that) {};
corecvs::Matrix::Matrix (const DiagonalMatrix & that) [explicit]
Definition at line 50 of file matrix.cpp.
References a(), corecvs::FixedArrayBase< RealType, ElementType >::at(), and corecvs::FixedArrayBase< RealType, ElementType >::size().
                                         : MatrixBase(that.size(), that.size())
{
    for (int i = 0; i < that.size(); i++)
        this->a(i,i) = that.at(i);
}
corecvs::Matrix::Matrix (Matrix * src, int32_t x1, int32_t y1, int32_t x2, int32_t y2) [inline]
Definition at line 54 of file matrix.h.
                                                                        :
        MatrixBase(src, x1, y1, x2, y2) {};
corecvs::Matrix::Matrix (int32_t h, int32_t w, double * data) [inline]
This function creates a matrix filling it with values form the given array line by line.
Parameters:
h The height of the matrix
w The width of the matrix
data The line by line raw values of the matrix
Definition at line 68 of file matrix.h.
: MatrixBase(h, w, data) {};
corecvs::Matrix::Matrix (int32_t h, int32_t w, double value)
This constructs the diagonal matrix.
Definition at line 43 of file matrix.cpp.
References corecvs::AbstractBuffer< double, int32_t >::element().
                                                 : MatrixBase(h, w, (double)(0.0))
{
    int32_t minDim = min(h,w);
    for (int32_t i = 0; i < minDim; i++)
        MatrixBase::element(i,i) = value;
}
corecvs::Matrix::Matrix (int32_t h, int32_t w, bool shouldInit) [inline]
Definition at line 100 of file matrix.h.
: MatrixBase(h, w, shouldInit) {};
corecvs::Matrix::Matrix (Matrix33 & in) [explicit]
Definition at line 18 of file matrix.cpp.
References corecvs::Matrix33::a(), and a().
                           : MatrixBase(3, 3, false)
{
    a(0,0) = in.a(0,0);
    a(0,1) = in.a(0,1);
    a(0,2) = in.a(0,2);
    a(1,0) = in.a(1,0);
    a(1,1) = in.a(1,1);
    a(1,2) = in.a(1,2);
    a(2,0) = in.a(2,0);
    a(2,1) = in.a(2,1);
    a(2,2) = in.a(2,2);
}
corecvs::Matrix::Matrix (Matrix44 & in) [explicit]
Definition at line 34 of file matrix.cpp.
References corecvs::Matrix44::a(), a(), corecvs::Matrix44::H, and corecvs::Matrix44::W.
                           : MatrixBase(4, 4, false)
{
    for (int i = 0; i < in.H; i++)
        for (int j = 0; j < in.W; j++)
        {
            a(i,j) = in.a(i,j);
        }
}
Member Function Documentation
double& corecvs::Matrix::a (int32_t y, int32_t x) [inline]
The element getter for a matrix that is used like vector (i.e has height or width of 1)
Remarks:
!!!! IT IS UNTIMATELY DICOURAGED TO USE THIS FUNCTION NOW !!!!
Parameters:
x An index of the vector element
Returns:
A matrix element Pseudonim to resemble the mathematics notation
Parameters:
x the column of the matrix
y the row of the matrix
Definition at line 132 of file matrix.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::element().
Referenced by corecvs::EllipticalApproximationUnified< Vector3dd >::addPoint(), corecvs::COOSparseMatrix::COOSparseMatrix(), detSVD(), corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), frobeniusNorm(), corecvs::HomographyReconstructor::getBestHomographyLSE(), corecvs::HomographyReconstructor::getBestHomographyLSE1(), corecvs::HomographyReconstructor::getBestHomographyLSE2(), corecvs::EllipticalApproximationUnified< Vector3dd >::getEllipseParameters(), corecvs::EssentialEstimator::getEssentialLSE(), corecvs::CamerasCalibrationFunc::getJacobian(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), inv(), invSVD(), Matrix(), matrixSolveGaussian(), corecvs::GradientDescent::minimise(), mul(), negative(), operator Matrix33(), corecvs::operator*(), corecvs::operator*=(), corecvs::operator+(), corecvs::operator-(), corecvs::operator<<(), corecvs::Matrix33::ProjectiveByPoints(), corecvs::DistortionCorrectTransform::setRadius(), svd(), t(), corecvs::COOSparseMatrix::toMatrix(), corecvs::UpperUnitaryMatrix::toMatrix(), trace(), transpose(), transposed(), and corecvs::Cholesky::udutDecompose().
    {
        return MatrixBase::element(y,x);
    };
const double& corecvs::Matrix::a (int32_t y, int32_t x) const [inline]
Definition at line 137 of file matrix.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::element().
    {
        return MatrixBase::element(y,x);
    };
template<typename ElementType, typename IndexType = int32_t> template<typename operation > void corecvs::AbstractBuffer< ElementType, IndexType >::binaryOperationInPlace (const AbstractBuffer< ElementType, IndexType > & that, const operation & oper = operation()) [inline, inherited]
This method performs the "oper" operation between this and that buffers and puts result to this buffer.
Parameters:
that - the AbstractBuffer to be processed with this to this
oper - operation to be performed
Definition at line 836 of file abstractBuffer.h.
    {
        IndexType h = min(this->h, that.h);
        IndexType w = min(this->w, that.w);
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElemRunner = &(this->element(i,0));
            const ElementType *thatElemRunner = &(that.element(i,0));
            for (IndexType j = 0; j < w; j++)
            {
                /* Writing like this just to emphasize what is actually called */
                *thisElemRunner = oper.operator()(*thisElemRunner, *thatElemRunner);
                thisElemRunner++;
                thatElemRunner++;
            }
        }
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ResultType > ResultType* corecvs::AbstractBuffer< ElementType, IndexType >::createView (const IndexType y, const IndexType x, const IndexType h, const IndexType w) [inline, inherited]
Prevent original buffer from being deleted MemoryBlock magically counts references
Definition at line 370 of file abstractBuffer.h.
    {
        // This is the only legitimate place to use default constructor
        ResultType *toReturn = new ResultType();
        toReturn->flags      = VIEW_BUFFER;
        toReturn->h          = h;
        toReturn->w          = w;
        toReturn->stride     = this->stride;
        toReturn->data       = &(this->element(y, x));
        /**
         * Prevent original buffer from being deleted
         * MemoryBlock magically counts references
         **/
        toReturn->memoryBlock = memoryBlock;
      //toReturn->_allocatedSize = 0;
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ResultType > ResultType* corecvs::AbstractBuffer< ElementType, IndexType >::createView () [inline, inherited]
Definition at line 390 of file abstractBuffer.h.
    {
        return this->createView<ResultType>(0, 0, this->h, this->w);
    }
double corecvs::Matrix::detSVD () const
Definition at line 537 of file matrix.cpp.
References a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, svd(), corecvs::AbstractBufferParams::w, and ClusteringDirectionType::X.
{
    ASSERT_TRUE(this->h == this->w, "Matrix should be square to invert.");
    int rank = this->h;
    Matrix X(this);
    Matrix result(rank, rank, 1.0);
    Matrix W(1,    rank);
    Matrix V(rank, rank);
    Matrix::svd (&X, &W, &V);
    double det = 1.0;
    for (int i = 0; i < rank ; i++)
    {
       det *= W.a(0,i);
    }
    return det;
}
template<typename ElementType, typename IndexType = int32_t> template<typename ReturnType , typename ConvElementType , typename ConvIndexType > ReturnType* corecvs::AbstractBuffer< ElementType, IndexType >::doConvolve (AbstractKernel< ConvElementType, ConvIndexType > * kernel) [inline, inherited]
This function is used to convolve/cross-correlate a buffer with the kernel.
In general convolution is
But this function does more of cross-correlation.
Definition at line 710 of file abstractBuffer.h.
    {
        IndexType i;
        ReturnType *toReturn = new ReturnType(h, w);
        parallelable_for(0, h, ParallelDoConvolve<ReturnType, ConvElementType, ConvIndexType>(toReturn, kernel, this));
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ReturnType , typename ConvElementType , typename ConvIndexType > ReturnType* corecvs::AbstractBuffer< ElementType, IndexType >::doConvolve1 (AbstractKernel< ConvElementType, ConvIndexType > * kernel) [inline, inherited]
Reimplemented in corecvs::G12Buffer.
Definition at line 755 of file abstractBuffer.h.
    {
        IndexType i,j;
        ReturnType *toReturn = new ReturnType(h, w);
        parallelable_for(kernel->centerY, h - kernel->h + kernel->centerY,
                ParallelDoConvolve1<ReturnType, ConvElementType, ConvIndexType>(toReturn, kernel, this));
        return toReturn;
    }
bool_t corecvs::AbstractBufferParams::dump (ostream & s, int h, int w, int stride, uint elemSize, bool_t binaryMode) [static, protected, inherited]
Definition at line 15 of file abstractBuffer.cpp.
References corecvs::sFormatStr, and corecvs::write_integer_bin().
{
    if (binaryMode)
    {
        write_integer_bin(s, w);
        write_integer_bin(s, stride);
        write_integer_bin(s, h);
        write_integer_bin(s, elemSize);
    }
    else
    {
        char buf[256];
        s.write(buf, snprintf2buf(buf, sFormatStr, w, stride, h, elemSize));
        s << endl;
    }
    return !s.bad();
}
bool_t corecvs::AbstractBufferParams::dump (ostream & s, uint elemSize, bool_t binaryMode) const [inline, protected, inherited]
Definition at line 152 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::dump(), corecvs::AbstractBufferParams::h, corecvs::AbstractBufferParams::stride, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::AbstractBufferParams::dump().
{ return dump(s, h, w, stride, elemSize, binaryMode); }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::dump (ostream & s, bool binaryMode) const [inline, inherited]
Definition at line 911 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::dump().
    {
        AbstractBufferParams::dump(s, sizeof(ElementType), binaryMode);
        if (binaryMode) {
            s.write((char *)data, sizeInBytes());
        }
        return !s.bad();
    }
template<typename ElementType, typename IndexType = int32_t> ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const IndexType y, const IndexType x) [inline, inherited]
The element getter.
A common practice in this project is for the y coordinate to come first
Definition at line 401 of file abstractBuffer.h.
Referenced by corecvs::Clustering3D::_clustering(), corecvs::AbstractBuffer< SegmentType * >::_init(), a(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::Buffer3d::addPoints(), corecvs::G12Buffer3d::addPoints(), corecvs::VJPattern::applyToPoint(), corecvs::AbstractBuffer< SegmentType * >::binaryOperationInPlace(), corecvs::BooleanBuffer::BooleanBuffer(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), OpenCvHelper::captureImageCopyToBuffer(), corecvs::Clustering3D::clustering(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::DecoupleYUYV::decouple(), corecvs::DerivativeBuffer::DerivativeBuffer(), corecvs::DisplacementBuffer::DisplacementBuffer(), FlowDrawer::draw(), corecvs::RGB24Buffer::drawArc(), corecvs::RGB24Buffer::drawArc1(), FlowDrawer::drawBigDotsFast(), FlowDrawer::drawDotsFast(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer2(), corecvs::RGB24Buffer::drawFlowBuffer3(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawG12Buffer(), corecvs::RGB24Buffer::drawG8Buffer(), corecvs::RGB24Buffer::drawHistogram1024x512(), corecvs::RGB24Buffer::drawIsolines(), corecvs::RGB24Buffer::drawLineSimple(), corecvs::VJSimpleClassifier::drawPattern(), corecvs::RGB24Buffer::drawPixel(), corecvs::FlowBuffer::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::AbstractContiniousBuffer< double, int >::elementBlInt(), corecvs::G12Buffer::elementBlPrecomp(), corecvs::AbstractBuffer< SegmentType * >::fillLineWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillRectangleWith(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillWithRands(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::RGB24Buffer::fillWithYUYV(), corecvs::SpatialGradient::findCornerPoints(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), corecvs::G8Buffer::FromG12Buffer(), corecvs::G12Buffer::G12Buffer(), corecvs::PPMLoader::g12BufferCreateFromPPM(), G12Image::G12Image(), corecvs::PPMLoader::g16BufferCreateFromPPM(), corecvs::FunctionArgs::getJacobian(), corecvs::EssentialEstimator::CostFunction7to1::getJacobian(), corecvs::Buffer3d::getLength(), corecvs::FlowBuffer::getMeanDifference(), corecvs::Buffer3d::getNearestPoint(), corecvs::DerivativeBuffer::gradientMagnitudeBuffer(), corecvs::Histogram::Histogram(), CloudViewDialog::initializeGLSlot(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::IntegralBuffer(), corecvs::Splain3Interpolator::interpolate(), corecvs::BilinearInterpolator::interpolate(), corecvs::PolynomInterpolator::interpolate(), corecvs::FlowBuffer::invert(), corecvs::DepthBuffer::isElementKnown(), corecvs::SixDBuffer::isElementKnown(), corecvs::FloatFlowBuffer::isElementKnown(), corecvs::Buffer3d::isElementKnown(), corecvs::FlowBuffer::isElementKnown(), corecvs::AbstractBuffer< SegmentType * >::isEqual(), corecvs::AbstractBuffer< SegmentType * >::isEqualTrace(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), QTFileLoader::load(), corecvs::BMPLoader::load(), corecvs::RAWLoader::load(), corecvs::FlowBuffer::load(), corecvs::BufferFactory::loadG16Bitmap(), corecvs::BMPLoader::loadRGB(), corecvs::FixedPointDisplace::map(), corecvs::DisplacementBuffer::map(), corecvs::AbstractBuffer< SegmentType * >::mapOperationElementwize(), TolerancePredicate::mark(), TestbedMainWindow::maskHue(), TestbedMainWindow::maskTolerance(), TestbedMainWindow::maskTolerance1(), DirectShowCaptureInterface::memberCallback(), corecvs::AbstractBuffer< SegmentType * >::mirrorVertical(), corecvs::AbstractBuffer< SegmentType * >::mirrorVerticalDump(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), corecvs::DerivativeBuffer::nonMaximalSuppression(), notTooFar(), corecvs::ThickeningBlock::operator()(), corecvs::BinarizeBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::ParallelPrepareBlurBuffers::operator()(), corecvs::SobelFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::operator()(), corecvs::DirectRemapper::ParallelRemap::operator()(), TolerancePredicate::operator()(), corecvs::operator<<(), corecvs::FloatFlowBuffer::preciseFlowCalc(), corecvs::BlurProcessor::prepareBlurBuffers(), corecvs::ErodeKernel< Algebra >::process(), corecvs::DilateKernel< Algebra >::process(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::rectangle(), corecvs::CannyFilter::recursiveEdgeProver(), TestbedMainWindow::recursiveTolerance(), QTFileLoader::RGB24BufferFromQImage(), RGB24Image::RGB24Image(), corecvs::AbstractBuffer< SegmentType * >::rotate180(), corecvs::PPMLoader::save(), corecvs::BMPLoader::save(), corecvs::PPMLoader::saveG16(), corecvs::Segmentator< TileSegmentator, TileSegment >::segment(), corecvs::TileGrid::selectWithThreshold(), corecvs::DepthBuffer::setElementUnknown(), corecvs::SixDBuffer::setElementUnknown(), corecvs::FloatFlowBuffer::setElementUnknown(), corecvs::Buffer3d::setElementUnknown(), corecvs::FlowBuffer::setElementUnknown(), corecvs::SixDBuffer::SixDBuffer(), corecvs::SpatialGradient::SpatialGradient(), corecvs::RGB24Buffer::toG12Buffer(), corecvs::AbstractBuffer< SegmentType * >::touchOperationElementwize(), corecvs::FlowBuffer::toVectorForm(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateToDB(), corecvs::BooleanBuffer::unpack(), TestbedMainWindow::updateViewImage(), corecvs::G12Buffer::verify(), and MjpegDecoderLazy::yuv422ptoG12().
    {
        return data[y * stride + x];
    }
template<typename ElementType, typename IndexType = int32_t> const ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const IndexType y, const IndexType x) const [inline, inherited]
Definition at line 406 of file abstractBuffer.h.
    {
        return data[y * stride + x];
    }
template<typename ElementType, typename IndexType = int32_t> ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const Vector2d< IndexType > & p) [inline, inherited]
The element getter.
Definition at line 414 of file abstractBuffer.h.
    {
        return element(p.y(), p.x());
    }
template<typename ElementType, typename IndexType = int32_t> const ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const Vector2d< IndexType > & p) const [inline, inherited]
Definition at line 419 of file abstractBuffer.h.
    {
        return element(p.y(), p.x());
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs (IndexType line, const ElementType value, ...) [inline, inherited]
Definition at line 602 of file abstractBuffer.h.
Referenced by corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSE(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSEUnif(), and corecvs::Matrix33::ProjectiveByPoints().
    {
       va_list marker;
       va_start(marker, value);
       this->element(line, 0) = value;
       for (IndexType j = 1; j < w; j++)
           this->element(line,j) = va_arg(marker, ElementType);
       va_end(marker);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillRectangleWith (IndexType y, IndexType x, IndexType rectH, IndexType rectW, const ElementType & value) [inline, inherited]
This function fills the rectangle inside the buffer with the value.
You could use this to clean part of the buffer
Definition at line 510 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::fillWith(), and corecvs::ThickeningBlock::operator()().
    {
        ASSERT_TRUE_P(x >= 0 && y >= 0 && x < w && y < h, ("[%d:%d] origin is not inside the buffer [%dx%d]", x, y, w, h));
        ASSERT_TRUE_P(x + rectW >= 0 && y + rectH >= 0 &&
                      x + rectW <= w && y + rectH <= h, ("[%d:%d] right lower corner is not inside the buffer [%dx%d]", x + rectW, y + rectH, w, h));
        for (IndexType i = y; i < y + rectH; i++)
        {
            ElementType *line = &(element(i, x));
            for (IndexType j = 0; j < rectW; j++)
            {
                *line++ = value;
            }
        }
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWith (const ElementType & value) [inline, inherited]
This function fills the whole buffer with the value.
You could use this to clean the buffer
Definition at line 531 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::VJSimpleClassifier::drawPattern().
    {
        /*for (IndexType i = 0; i < h; i++)
            for (IndexType j = 0; j < w; j++)
                this->element(i,j) = value; */
        fillRectangleWith(0, 0, h, w, value);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWith (const AbstractBuffer< ElementType, IndexType > & other) [inline, inherited]
This function fills the whole buffer with the values from the other buffer.
TODO: this function doesn't call the copy constructor. I believe it should.
Definition at line 563 of file abstractBuffer.h.
    {
        int copyH = CORE_MIN(this->h, other.h);
        int copyW = CORE_MIN(this->w, other.w);
        /* If buffers have same horizontal geometry use fast method*/
        if (other.stride == this->stride && other.w == this->w) {
            memcpy(this->data, other.data, sizeof(ElementType) * copyH * stride);
            return;
        }
        /* Otherwise copy line by line */
        for (int i = 0; i < copyH; i++) {
            memcpy(&this->element(i, 0), &other.element(i, 0), sizeof(ElementType) * copyW);
        }
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithArgs (const ElementType value, va_list marker) [inline, inherited]
You could use this to clean the buffer.
Note:
you should be very careful passing variables of the right type
Definition at line 585 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::fillWithArgs().
    {
        this->element(0, 0) = value;
        for (IndexType i = 0; i < h; i++)
            for (IndexType j = 0; j < w; j++)
                if (i != 0 || j != 0)
                    this->element(i,j) = va_arg(marker, ElementType);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithArgs (const ElementType value, ...) [inline, inherited]
Definition at line 594 of file abstractBuffer.h.
    {
        va_list  marker;
        va_start(marker, value);
        fillWithArgs(value, marker);
        va_end(marker);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithRands (ElementType valueMax, ElementType valueMin = ElementType(0)) [inline, inherited]
Fills the buffer by random values within the given range.
Definition at line 614 of file abstractBuffer.h.
    {
        srand(rand());
        for (IndexType i = 0; i < h; i++)
            for (IndexType j = 0; j < w; j++)
                this->element(i,j) = (ElementType)randRanged(valueMax, valueMin);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithRaw (ElementType * _data) [inline, inherited]
This function fills the whole buffer with the values from the given array.
TODO: this function doesn't call the copy constructor. I believe it should.
Definition at line 544 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::G12Buffer::operator=().
    {
       if (this->w == this->stride)
       {
           memcpy(this->data, _data, this->sizeInBytes());
           return;
       }
       size_t rawLength = sizeof(ElementType) * this->w;
       for (int i = 0; i < (int)this->h; i++)
       {
           memcpy(&this->element(i, 0), &_data[i * this->w], rawLength);
       }
    }
double corecvs::Matrix::frobeniusNorm () const
Definition at line 314 of file matrix.cpp.
References a(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::HomographyReconstructor::getBestHomographyLSE(), corecvs::HomographyReconstructor::getBestHomographyLSE1(), and corecvs::HomographyReconstructor::getBestHomographyLSE2().
{
    double norm = 0.0;
    for (int row = 0; row < h ; row++)
    {
        for (int column = 0; column < w ; column++)
        {
            double val = a(row, column);
            norm += val * val;
        }
    }
    return norm;
}
template<typename ElementType, typename IndexType = int32_t> IndexType corecvs::AbstractBuffer< ElementType, IndexType >::getH () const [inline, inherited]
Height getter.
Definition at line 459 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::G12Buffer::G12Buffer(), corecvs::G12Buffer3d::G12Buffer3d(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::IntegralBuffer(), corecvs::PolynomInterpolator::interpolate(), corecvs::FlowBuffer::load(), corecvs::AbstractBuffer< SegmentType * >::load(), and notTooFar().
    {
        return h;
    }
template<typename ElementType, typename IndexType = int32_t> Vector2d<IndexType> corecvs::AbstractBuffer< ElementType, IndexType >::getSize () const [inline, inherited]
Buffer size getter.
Definition at line 483 of file abstractBuffer.h.
Referenced by corecvs::Morphological::dilate(), corecvs::RGB24Buffer::drawIsolines(), corecvs::Morphological::erode(), TestbedMainWindow::loadImage(), corecvs::BinarizeBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::SobelFilter::operator()(), BaseCalculationThread::recalculateCache(), TestbedMainWindow::resetMask(), and corecvs::BMPLoader::save().
    {
        return Vector2d<IndexType>(w, h);
    }
template<typename ElementType, typename IndexType = int32_t> IndexType corecvs::AbstractBuffer< ElementType, IndexType >::getStride () const [inline, inherited]
Stride getter.
Definition at line 467 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::AbstractBuffer< SegmentType * >::load().
    {
        return stride;
    }
template<typename ElementType, typename IndexType = int32_t> IndexType corecvs::AbstractBuffer< ElementType, IndexType >::getW () const [inline, inherited]
Width getter.
Definition at line 475 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::G12Buffer::G12Buffer(), corecvs::G12Buffer3d::G12Buffer3d(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::IntegralBuffer(), corecvs::PolynomInterpolator::interpolate(), corecvs::G12Buffer::isValidCoordBlPrecomp(), corecvs::FlowBuffer::load(), corecvs::AbstractBuffer< SegmentType * >::load(), notTooFar(), and corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::operator()().
    {
        return w;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::hasSameSize (const AbstractBuffer< ElementType, IndexType > * other) const [inline, inherited]
Checks if this buffer has the same size as the other.
Definition at line 443 of file abstractBuffer.h.
Referenced by corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), corecvs::G12Buffer::operator=(), and BaseCalculationThread::recalculateCache().
    {
        return (this->h == other->h) && (this->w == other->w);
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::hasSameSize (const IndexType & otherH, const IndexType & otherW) const [inline, inherited]
Checks if this buffer has the same size as the parameters given.
Definition at line 451 of file abstractBuffer.h.
    {
        return (this->h == otherH) && (this->w == otherW);
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ReturnType , typename ConvElementType , typename ConvIndexType > void corecvs::AbstractBuffer< ElementType, IndexType >::innerCycleDoConvolve (ReturnType * toReturn, AbstractKernel< ConvElementType, ConvIndexType > * kernel, int i) [inline, inherited]
Definition at line 659 of file abstractBuffer.h.
    {
        for (IndexType j = 0; j < w; j++)
        {
            toReturn->element(i,j) =  kernel->template multiplyAtPoint<ElementType, IndexType>(this, i,j);
        }
    }
Matrix corecvs::Matrix::inv () const
This function returns an inverse of the matrix.
The calculation is done through LU decomposition do far
http://en.wikipedia.org/wiki/Gaussian_elimination TODO: http://en.wikipedia.org/wiki/Gauss%E2%80%93Jordan_elimination
Attention:
No check is done, if the matrix is invertible or not
Returns:
The
Definition at line 454 of file matrix.cpp.
References a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::LevenbergMarquardt::fit(), corecvs::DistortionCorrectTransform::setRadius(), and corecvs::ClassicKalman::update().
{
    unsigned i, j, k;
    double multiplier;
    ASSERT_TRUE(this->h == this->w, "Matrix should be square to invert.");
    unsigned rank = this->h;
    // Start with identity matrix
    Matrix result(rank, rank, 1.0);
    Matrix copy(this);
    for (i = 0; i < rank; ++i)
    {
        double divider = copy.a(i,i);
        if (fabs(divider) == 0)
        {
            return result;
        }
        for (j = 0; j < rank; ++j)
        {
              copy.a(i, j) /= divider;
            result.a(i, j) /= divider;
        }
        for (j = i + 1; j < rank; ++j)
        {
            multiplier = copy.a(j,i);
            if (fabs (copy.a(j,i)) > 0.0)
            {
                for (k = 0; k < rank; ++k)
                {
                      copy.a(j, k) -=   copy.a(i, k) * multiplier;
                    result.a(j, k) -= result.a(i, k) * multiplier;
                }
            }
        }
    }
    for (i = rank; i > 0; --i)
    {
        for (j = 0; j + 1 < i; ++j)
        {
            multiplier = copy.a(j,i - 1);
            for (k = 0; k < rank; k++)
            {
                 copy.a(j, k) -=   copy.a(i - 1, k) * multiplier;
               result.a(j, k) -= result.a(i - 1, k) * multiplier;
            }
        }
    }
    return result;
}
Matrix corecvs::Matrix::invSVD () const
Definition at line 512 of file matrix.cpp.
References a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, svd(), transpose(), corecvs::AbstractBufferParams::w, and ClusteringDirectionType::X.
Referenced by corecvs::HomographyReconstructor::getBestHomographyLSE1(), and corecvs::Matrix33::ProjectiveByPoints().
{
    ASSERT_TRUE(this->h == this->w, "Matrix should be square to invert.");
    int rank = this->h;
    Matrix X(this);
    Matrix result(rank, rank, 1.0);
    Matrix W(1,    rank);
    Matrix V(rank, rank);
    Matrix::svd (&X, &W, &V);
    X.transpose();
  //  cout << "Singular:" << W << endl;
    for (int i = 0; i < rank ; i++)
    {
        for (int j = 0; j < rank ; j++)
        {
            if (W.a(0,i) > 1e-5)
                X.a(i,j) /= W.a(0,i);
        }
    }
    return V * X;
}
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isAllocated () const [inline, inherited]
Checking for successfull allocation.
Definition at line 491 of file abstractBuffer.h.
    {
        return data != NULL;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isEqual (const AbstractBuffer< ElementType, IndexType > & that) const [inline, inherited]
This method tests for equality.
Definition at line 769 of file abstractBuffer.h.
Referenced by operator==().
    {
        if (that.h != this->h || that.w != this->w)
            return false;
        for (int i = 0; i < this->h; i++)
        {
            const ElementType *thisElemRunner = &(this->element(i,0));
            const ElementType *thatElemRunner = &(that.element(i,0));
            for (int j = 0; j < this->w; j++)
            {
                if (*thatElemRunner != *thisElemRunner)
                {
#ifdef ASSERTS
                  printf("Buffers have equal sizes [h=%d w=%d]\n", this->h, this->w);
                    printf("[ 0x");
                    for (size_t k = 0; k < sizeof(ElementType); k++)
                        printf("%02X ", ((uint8_t *)(void*)(thisElemRunner))[k]);
                    printf("] vs [ 0x");
                    for (size_t k = 0; k < sizeof(ElementType); k++)
                        printf("%02X ", ((uint8_t *)(void*)(thatElemRunner))[k]);
                    printf("]\nPos y=%d x=%d\n", i , j);
                    ASSERT_FAIL_P(("Buffers don't match"));
#endif
                    return false;
                }
                thatElemRunner++;
                thisElemRunner++;
            }
        }
        return true;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isEqualTrace (const AbstractBuffer< ElementType, IndexType > & that) const [inline, inherited]
Definition at line 802 of file abstractBuffer.h.
    {
        if (that.h != this->h || that.w != this->w)
            return false;
        int diffs = 0;
        for (int i = 0; i < this->h; i++)
        {
            const ElementType *thisElemRunner = &(this->element(i,0));
            const ElementType *thatElemRunner = &(that.element(i,0));
            for (int j = 0; j < this->w; j++)
            {
                if (*thatElemRunner != *thisElemRunner)
                {
                    cout << "Differ Pos y="<< i << " x=" << j << " ";
                    cout << "Fst = " <<  *thisElemRunner << " sec= " << *thatElemRunner << endl;
                    diffs++;
                }
                thatElemRunner++;
                thisElemRunner++;
            }
        }
        cout << "Totally " << diffs << " diffs" << endl;
        return diffs == 0;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord (const IndexType y, const IndexType x) const [inline, inherited]
Checks if coordinate lies within the buffer area.
Definition at line 427 of file abstractBuffer.h.
Referenced by corecvs::Buffer3d::addPoints(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::Clustering3D::clustering(), corecvs::RGB24Buffer::drawArc(), corecvs::RGB24Buffer::drawArc1(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawPixel(), corecvs::Buffer3d::getNearestPoint(), corecvs::FlowBuffer::invert(), corecvs::Buffer3d::isElementValidAndKnown(), corecvs::FlowBuffer::isElementValidAndKnown(), corecvs::AbstractBuffer< SegmentType * >::isValidCoord(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::FlowBuffer::load(), TestbedMainWindow::maskTolerance(), TestbedMainWindow::maskTolerance1(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), TestbedMainWindow::recursiveTolerance(), and TestbedMainWindow::updateViewImage().
    {
        return (x >= 0) && (x < w) && (y >= 0) && (y < h);
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord (const Vector2d< IndexType > & p) const [inline, inherited]
Checks if coordinate lies within the buffer area.
Definition at line 435 of file abstractBuffer.h.
    {
        return isValidCoord(p.y(), p.x());
    }
bool_t corecvs::AbstractBufferParams::load (istream & s, int & h, int & w, int & stride, uint elemSize, bool_t binaryMode) [static, protected, inherited]
Definition at line 33 of file abstractBuffer.cpp.
References corecvs::AbstractBufferParams::read(), corecvs::read_integer_bin(), and corecvs::sFormatStr.
Referenced by corecvs::AbstractBuffer< SegmentType * >::load().
{
    int width, stridePix, height, elSize;
    size_t pos = s.tellg();
    if (binaryMode)
    {
        read_integer_bin(s, width);
        read_integer_bin(s, stridePix);
        read_integer_bin(s, height);
        read_integer_bin(s, elSize);
    }
    else
    {
        char buf[256];
        read(s, buf, binaryMode);
        if (sscanf(buf, sFormatStr, &width, &stridePix, &height, &elSize) != 4)
            elSize = 0;
    }
    if ((uint)elSize != elemSize)
    {
        s.seekg(pos);                                       // restore pos
        return false;
    }
    h      = height;
    w      = width;
    stride = stridePix;
    return true;
}
bool_t corecvs::AbstractBufferParams::load (istream & s, uint elemSize, bool_t binaryMode) [inline, protected, inherited]
Definition at line 153 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::h, corecvs::AbstractBufferParams::load(), corecvs::AbstractBufferParams::stride, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::AbstractBufferParams::load().
{ return load(s, h, w, stride, elemSize, binaryMode); }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::load (istream & s, bool binaryMode) [inline, inherited]
Definition at line 920 of file abstractBuffer.h.
Referenced by corecvs::BufferFactory::loadG12Bitmap().
    {
        if (!AbstractBufferParams::load(s, sizeof(ElementType), binaryMode))
            return false;
        _init(getH(), getW(), getStride(), false);
        if (!binaryMode)
            return true;                                    // loading in text mode is outside
        s.read((char *)data, sizeInBytes());
        return !s.bad();
    }
template<typename ElementType, typename IndexType = int32_t> template<typename operation > void corecvs::AbstractBuffer< ElementType, IndexType >::mapOperationElementwize (const operation & map) [inline, inherited]
Definition at line 869 of file abstractBuffer.h.
Referenced by BitSelector::filter(), GainOffset::filter(), corecvs::G12Buffer::gainOffset(), corecvs::G12Buffer::intervalMap(), corecvs::BitSelectorFilter::operator()(), corecvs::GainOffsetFilter::operator()(), and corecvs::G12Buffer::shiftMask().
    {
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElementRunner = &(this->element(i,0));
            for (IndexType j = 0; j < w; j++)
            {
                *thisElementRunner = map.operator()(*thisElementRunner);
                thisElementRunner++;
            }
        }
    }
bool corecvs::Matrix::matrixSolveGaussian (Matrix * A, Matrix * B) [static]
Solves the linear equation.
This functions solves the equation
by the Gaussian method of eliminating variables.
Definition at line 367 of file matrix.cpp.
References a(), ASSERT_FALSE, corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    ASSERT_FALSE(A->h != A->w || A->w != B->h || B->w != 1, "Matrix has wrong sizes");
    int row, column, rowRunner, runner;
    int n = A->w;
    /* Walk thought the matrix from left to right */
    for (column = 0; column < n; column++)
    {
        /* Find the row absolute maximum and row number with maximum */
        int rowWithMax = -1;
        double maxInColumn = 0.0;
        for (row = column; row < n; row ++)
        {
            double absA = fabs (A->a(row,column));
            if (absA > maxInColumn)
            {
                maxInColumn = absA;
                rowWithMax = row;
            }
        }
        if (rowWithMax == -1) {
            return false;
            if (B->a(column,0) != 0)
                return false;
            for (rowRunner = 0; rowRunner < n; rowRunner++)
                if (A->a(column,rowRunner) != 0)
                    return false;
        }
        // Now we will work with the row of the same number as the column
        row = column;
        // Now put the row to the i-th position by interchange
        if (rowWithMax != row)
        {
            double tmp;
            for (rowRunner = 0; rowRunner < n; rowRunner ++)
            {
                tmp = A->a(row, rowRunner);
                A->a(row, rowRunner) = A->a(rowWithMax, rowRunner);
                A->a(rowWithMax, rowRunner) = tmp;
            }
            tmp = B->a(row,0);
            B->a(row,0) = B->a(rowWithMax,0);
            B->a(rowWithMax,0) = tmp;
        }
        // And now do the correction of all the rows
        // First divide all the row by the value of (column, row)
        double a = A->a(column, column);
        for (runner = column + 1; runner < n; runner++)
        {
            double d = A->a(runner, column);
            for (rowRunner = column; rowRunner < n; rowRunner++)
            {
                if (d != 0) {
                    A->a(runner, rowRunner) = A->a(runner, rowRunner) * a - A->a(column, rowRunner) * d;
                }
            }
            if (d != 0) {
                B->a(runner,0) = B->a(runner, 0) * a - B->a(column,0) * d;
            }
        }
    }
    for (int i = n - 1; i >= 0; i --)
    {
        for (int j = i + 1; j < n; j ++)
        {
            B->a(i, 0) -= B->a(j, 0) * A->a(i, j);
        }
        B->a(i, 0) /= A->a(i, i);
    }
    return true;
}
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::mirrorVertical () [inline, inherited]
Mirrors current buffer vertically.
Definition at line 950 of file abstractBuffer.h.
  {
      for (IndexType i = 0; i < h / 2; i++)
      {
          memcpy(&(this->element(h - 1 - i, 0)), &(this->element(i, 0)), w * sizeof(ElementType));
      }
  }
template<typename ElementType, typename IndexType = int32_t> template<typename OtherType > OtherType* corecvs::AbstractBuffer< ElementType, IndexType >::mirrorVertical () [inline, inherited]
Definition at line 978 of file abstractBuffer.h.
    {
        OtherType *toReturn = new OtherType(this->h, this->w);
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElemRunner = &(this->element(i,0));
            typename OtherType::InternalElementType *thatElemRunner = &(toReturn->element(h - 1 - i,0));
            for (IndexType j = 0; j < w; j++)
            {
                *thatElemRunner = *thisElemRunner;
                thatElemRunner++;
                thisElemRunner++;
            }
        }
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<typename OtherType > OtherType* corecvs::AbstractBuffer< ElementType, IndexType >::mirrorVerticalDump () [inline, inherited]
Please check that you really don't want to invoke the copy constructor.
Definition at line 939 of file abstractBuffer.h.
    {
        OtherType *toReturn = new OtherType(this->h, this->w);
        for (IndexType i = 0; i < h; i++)
        {
            memcpy(&(toReturn->element(h - 1 - i, 0)), &(this->element(i, 0)), w * sizeof(ElementType));
        }
        return toReturn;
    }
Matrix * corecvs::Matrix::mul (const Matrix & V)
Matrix multiplication.
Definition at line 73 of file matrix.cpp.
References a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, Matrix(), and corecvs::AbstractBufferParams::w.
{
    ASSERT_TRUE (this->w == V.h, "Matrices have wrong sizes");
    Matrix *result = new Matrix(this->h, V.w, false);
    int row, column, runner;
    for (row = 0; row < result->h ; row++)
        for (column = 0; column < result->w ; column++)
        {
            double sum = 0;
            for (runner = 0; runner < this->w; runner++)
            {
                sum += this->a(row, runner) * V.a(runner, column);
            }
            result->a(row, column) = sum;
        }
    return result;
}
void corecvs::Matrix::neg () [inline]
All elements are negated .
Definition at line 237 of file matrix.h.
    {
        using std::negate;
        this->mapOperationElementwize<negate<double> >(negate<double>());
    }
Matrix corecvs::Matrix::negative () const
Definition at line 292 of file matrix.cpp.
References a(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
   Matrix result(this->w, this->h, false);
   for (int row = 0; row < result.h ; row++)
   {
       for (int column = 0; column < result.w ; column++)
       {
           result.a(row, column) = -this->a(row, column);
       }
   }
   return result;
}
bool corecvs::Matrix::notTooFar (const Matrix * V, double epsilon = 0.0) const [inline]
Definition at line 256 of file matrix.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBuffer< ElementType, IndexType >::getH(), corecvs::AbstractBuffer< ElementType, IndexType >::getW(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
    {
        int h = getH();
        int w = getW();
        if (h != V->getH() || w != V->getW())
            return false;
        for (int i = 0; i < h; i++)
            for (int j = 0; j < w; j++)
            if (  this->element(i,j) > V->element(i,j) + epsilon ||
                  this->element(i,j) < V->element(i,j) - epsilon )
                return false;
        return true;
    }
int corecvs::AbstractBufferParams::numElements () const [inline, inherited]
Calculate number of elements in a buffer.
Definition at line 124 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::stride.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::sizeInBytes(), and corecvs::AbstractBuffer< SegmentType * >::~AbstractBuffer().
{ return h * stride; }
corecvs::Matrix::operator Matrix33 () const
Definition at line 63 of file matrix.cpp.
References a().
{
    return Matrix33 (
     a(0,0), a(0,1), a(0,2),
     a(1,0), a(1,1), a(1,2),
     a(2,0), a(2,1), a(2,2)
    );
}
Matrix& corecvs::Matrix::operator*= (const double v) [inline]
Multiply matrix by scalar .
Definition at line 201 of file matrix.h.
    {
        using std::multiplies;
        binder2nd<multiplies<double> > multiplier(multiplies<double>(), v);
        this->mapOperationElementwize<binder2nd<multiplies<double> > >(multiplier);
        return *this;
    }
Matrix& corecvs::Matrix::operator+= (const Matrix & V) [inline]
Definition at line 183 of file matrix.h.
    {
        this->binaryOperationInPlace<plus<double> >(V);
        return *this;
    }
Matrix& corecvs::Matrix::operator-= (const Matrix & V) [inline]
Definition at line 189 of file matrix.h.
    {
        this->binaryOperationInPlace<minus<double> >(V);
        return *this;
    }
Matrix& corecvs::Matrix::operator/= (const double v) [inline]
Divide matrix by scalar .
Definition at line 213 of file matrix.h.
    {
        using std::divides;
        binder2nd<divides<double> > divider(divides<double>(), v);
        this->mapOperationElementwize<binder2nd<divides<double> > >(divider);
        return *this;
    }
bool corecvs::Matrix::operator== (const Matrix & M) const [inline]
Check matrix for equality.
Definition at line 224 of file matrix.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::isEqual().
    {
        return this->isEqual(M);
    }
void corecvs::Matrix::print () [inline]
Definition at line 249 of file matrix.h.
    {
        cout << *this;
    }
bool_t corecvs::AbstractBufferParams::read (istream & s, int & val, bool_t binaryMode) [static, protected, inherited]
Definition at line 78 of file abstractBuffer.cpp.
References corecvs::read_integer_bin().
Referenced by corecvs::RGB24Buffer::fillWithYUYV(), corecvs::FlowBuffer::load(), corecvs::AbstractBufferParams::load(), and corecvs::RGB24Buffer::toG12Buffer().
{
    int value;
    size_t pos = s.tellg();
    if (binaryMode)
    {
        read_integer_bin(s, value);
    }
    else
    {
        s >> value;
    }
    if (s.bad())
    {
        s.seekg(pos);                                       // restore pos
        return false;
    }
    val = value;
    return true;
}
bool_t corecvs::AbstractBufferParams::read (istream & s, char * str, size_t size, bool_t binaryMode) [static, protected, inherited]
Definition at line 109 of file abstractBuffer.cpp.
References CORE_COUNT_OF, and CORE_UNUSED.
{
    if (str != NULL && size) {
        s.getline(str, size);                               // read one line to the output buffer
    }
    else {
        char buf[256];
        s.getline(buf, CORE_COUNT_OF(buf));                 // skip one line
    }
    CORE_UNUSED(binaryMode);
    return !s.bad();
}
template<size_t size> static bool_t corecvs::AbstractBufferParams::read (istream & s, char(&) str[size], bool_t binaryMode) [inline, static, protected, inherited]
Definition at line 150 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::read().
Referenced by corecvs::AbstractBufferParams::read().
{ return read(s, (char*)str, size, binaryMode); }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::rotate180 () [inline, inherited]
Rotates current buffer 180 degrees.
Definition at line 959 of file abstractBuffer.h.
  {
      for (IndexType i = 0; i < h / 2; i++)
      {
            ElementType *thisElemRunner = &(this->element(i, 0));
            ElementType *thatElemRunner = &(this->element(h - 1 - i, w - 1));
            for (IndexType j = 0; j < w; j++)
            {
                ElementType tmp = *thisElemRunner;
                *thisElemRunner = *thatElemRunner;
                *thatElemRunner = tmp;
                thatElemRunner--;
                thisElemRunner++;
            }
      }
  }
void corecvs::AbstractBufferParams::setH (int _h) [inline, protected, inherited]
Definition at line 137 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
{ h      = _h; }
void corecvs::AbstractBufferParams::setStride (int _s) [inline, protected, inherited]
Definition at line 139 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::stride.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
{ stride = _s; }
void corecvs::AbstractBufferParams::setW (int _w) [inline, protected, inherited]
Definition at line 138 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::w.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
{ w      = _w; }
template<typename ElementType, typename IndexType = int32_t> size_t corecvs::AbstractBuffer< ElementType, IndexType >::sizeInBytes () const [inline, inherited]
Calculate image buffer size in bytes.
Definition at line 499 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::AbstractBuffer< SegmentType * >::dump(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), and corecvs::AbstractBuffer< SegmentType * >::load().
    {
      //return _allocatedSize;
        return this->numElements() * sizeof(ElementType);
    }
void corecvs::Matrix::svd (Matrix * A, Matrix * W, Matrix * V) [static]
This method contains SVD implementation.
Remarks:
This SVD is not http://en.wikipedia.org/wiki/Snayperskaya_Vintovka_Dragunova
I have used an existing solution with unclear license. So far let it be so. In fact this solution is a reworked solution from "Numerical Recipies in C", so it it will be easy to re-implement it to make it absolutely clean.
Seems like this code is an semi-automatic translation from Fortran.
Author:
Alexander Pimenov based on code form "Numerical Recipies in C" and looking over Tina code Given a matrix A, Matrix::svd() computes its singular value decomposition, A = U W V^T. The matrix U replaces A on output. The diagonal matrix of singular values W is output as a matrix W. The matrix V (not the transpose V T) is output as V.
Definition at line 577 of file matrix.cpp.
References a(), Abs, ASSERT_FALSE, ASSERT_TRUE, corecvs::Vector2d< ElementType >::getLengthStable(), corecvs::AbstractBufferParams::h, Max, Sign, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::EssentialMatrix::assertRank2(), detSVD(), corecvs::HomographyReconstructor::getBestHomographyLSE(), corecvs::HomographyReconstructor::getBestHomographyLSE2(), corecvs::EllipticalApproximationUnified< Vector3dd >::getEllipseParameters(), corecvs::EssentialEstimator::getEssentialLSE(), invSVD(), corecvs::EssentialMatrix::nullspaces(), corecvs::EssentialMatrix::projectToEssential(), svd(), and svdDesc().
{
    ASSERT_TRUE((A != NULL && W != NULL && V != NULL), "NULL input Matrix\n");
    ASSERT_TRUE((W->h ==    1 && W->w == A->w), "Matrix W has wrong size\n" );
    ASSERT_TRUE((A->w == V->h && A->w == V->w),"Matrix V has wrong size\n");
    int n = A->w;
    int m = A->h;
    /* BUG `nm' may be used uninitialized in this function */
    int     flag, i, its, j, jj, k, l=0, nm, nm1 = n - 1, mm1 = m - 1;
    double  c, f, h, s, x, y, z;
    double  anorm = 0.0;
    double  g = 0.0;
    double scale = 0.0;
    double *rv1;
    ASSERT_FALSE((m < n), "SVDCMP: You must augment A with extra zero rows");
    ASSERT_TRUE(n > 0 , "A width should not be zero");
    rv1 = new double[n];
    /* Householder reduction to bidigonal form */
    for (i = 0; i < n; i++)
    {
        l = i + 1;
        rv1[i] = scale * g;
        g = s = scale = 0.0;
        if (i < m)
        {
            for (k = i; k < m; k++)
                scale += fabs(A->a(k,i));
            if (scale)
            {
                for (k = i; k < m; k++)
                {
                    A->a(k,i) /= scale;
                    s += A->a(k,i) * A->a(k,i);
                }
                f = A->a(i,i);
                g = -Sign(sqrt(s), f);
                h = f * g - s;
                A->a(i,i) = f - g;
                if (i != nm1)
                {
                    for (j = l; j < n; j++)
                    {
                        for (s = 0.0, k = i; k < m; k++)
                            s += A->a(k,i) * A->a(k,j);
                        f = s / h;
                        for (k = i; k < m; k++)
                            A->a(k,j) += f * A->a(k,i);
                    }
                }
                for (k = i; k < m; k++)
                    A->a(k,i) *= scale;
            }
        }
        W->a(0,i) = scale * g;
        g = s = scale = 0.0;
        if (i < m && i != nm1)
        {
            for (k = l; k < n; k++)
                scale += fabs(A->a(i,k));
            if (scale)
            {
                for (k = l; k < n; k++)
                {
                    A->a(i,k) /= scale;
                    s += A->a(i,k) * A->a(i,k);
                }
                f = A->a(i,l);
                g = -Sign(sqrt(s), f);
                h = f * g - s;
                A->a(i,l) = f - g;
                for (k = l; k < n; k++)
                    rv1[k] = A->a(i,k) / h;
                if (i != mm1)
                {
                    for (j = l; j < m; j++)
                    {
                        for (s = 0.0, k = l; k < n; k++)
                            s += A->a(j,k) * A->a(i,k);
                        for (k = l; k < n; k++)
                            A->a(j,k) += s * rv1[k];
                    }
                }
                for (k = l; k < n; k++)
                    A->a(i,k) *= scale;
            }
        }
        anorm = Max(anorm, (fabs(W->a( 0, i)) + fabs(rv1[i])));
    }
        /* Accumulation of right-hand transformations */
        for (i = n - 1; i >= 0; i--)
        {
            if (i < nm1)
            {
                if (g)
                {
                    /* double division to avoid possible underflow */
                    for (j = l; j < n; j++)
                        V->a( j, i) = (A->a( i, j) / A->a( i, l)) / g;
                    for (j = l; j < n; j++)
                    {
                        for (s = 0.0, k = l; k < n; k++)
                            s += A->a(i, k) * V->a(k, j);
                        for (k = l; k < n; k++)
                            V->a(k, j) += s * V->a(k, i);
                    }
                }
                for (j = l; j < n; j++)
                    V->a(i, j) = V->a(j, i) = 0.0;
            }
            V->a(i, i) = 1.0;
            g = rv1[i];
            l = i;
        }
        /* Accumulation of left-hand transformations */
        for (i = n - 1; i >= 0; i--)
        {
            l = i + 1;
            g = W->a(0, i);
            if (i < nm1)
                for (j = l; j < n; j++)
                    A->a(i, j) = 0.0;
            if (g)
            {
                g = 1.0 / g;
                if (i != nm1)
                {
                    for (j = l; j < n; j++)
                    {
                        for (s = 0.0, k = l; k < m; k++)
                            s += A->a(k, i) * A->a(k, j);
                        f = (s / A->a(i, i)) * g;
                        for (k = i; k < m; k++)
                            A->a(k, j) += f * A->a(k, i);
                    }
                }
                for (j = i; j < m; j++)
                    A->a(j, i) *= g;
            } else
                for (j = i; j < m; j++)
                    A->a(j, i) = 0.0;
            ++A->a(i, i);
        }
        /* diagonalization of the bidigonal form */
        for (k = n - 1; k >= 0; k--)
        {                           /* loop over singlar values */
            for (its = 0; its < 30; its++)
            {                       /* loop over allowed iterations */
                flag = 1;
                for (l = k; l >= 0; l--)
                {                   /* test for splitting */
                    nm = l - 1;     /* note that rv1[l] is always zero */
                    if (Abs(rv1[l]) + anorm == anorm)
                    {
                        flag = 0;
                        break;
                    }
                    if (fabs(W->a(0, nm)) + anorm == anorm)
                        break;
                }
                if (flag)
                {
                    c = 0.0;        /* cancellation of rv1[l], if l>1 */
                    s = 1.0;
                    for (i = l; i <= k; i++)
                    {
                        f = s * rv1[i];
                        if (Abs(f) + anorm != anorm)
{
                            g = W->a(0, i);
                            h = Vector2dd(f, g).getLengthStable();
                            W->a(0, i) = h;
                            h = 1.0 / h;
                            c = g * h;
                            s = (-f * h);
                            for (j = 0; j < m; j++)
{
                                y = A->a(j, nm);
                                z = A->a(j, i);
                                A->a( j, nm) = y * c + z * s;
                                A->a( j, i) = z * c - y * s;
                            }
                        }
                    }
                }
                z = W->a(0, k);
                if (l == k)
                {                   /* convergence */
                    if (z < 0.0)
                    {
                        W->a(0, k) = -z;
                        for (j = 0; j < n; j++)
                            V->a(j, k) = (-V->a(j, k));
                    }
                    break;
                }
                if (its == 30)
                    printf("No convergence in 30 SVDCMP iterations");
                x = W->a(0, l);           /* shift from bottom 2-by-2 minor */
                nm = k - 1;
                y = W->a(0, nm);
                g = rv1[nm];
                h = rv1[k];
                f = ((y - z) * (y + z) + (g - h) * (g + h)) / (2.0 * h * y);
                g = Vector2dd(f, 1.0).getLengthStable();
                /* next QR transformation */
                f = ((x - z) * (x + z) + h * ((y / (f + Sign(g, f))) - h)) / x;
                c = s = 1.0;
                for (j = l; j <= nm; j++)
                {
                    i = j + 1;
                    g = rv1[i];
                    y = W->a(0, i);
                    h = s * g;
                    g = c * g;
                    z = Vector2dd(f,h).getLengthStable();
                    rv1[j] = z;
                    c = f / z;
                    s = h / z;
                    f = x * c + g * s;
                    g = g * c - x * s;
                    h = y * s;
                    y = y * c;
                    for (jj = 0; jj < n; jj++)
                    {
                        x = V->a(jj, j);
                        z = V->a(jj, i);
                        V->a(jj, j) = x * c + z * s;
                        V->a(jj, i) = z * c - x * s;
                    }
                    z = Vector2dd(f,h).getLengthStable();
                    W->a(0, j) = z;       /* rotation can be arbitrary id z=0 */
                    if (z)
                    {
                        z = 1.0 / z;
                        c = f * z;
                        s = h * z;
                    }
                    f = (c * g) + (s * y);
                    x = (c * y) - (s * g);
                    for (jj = 0; jj < m; jj++)
                    {
                        y = A->a(jj, j);
                        z = A->a(jj, i);
                        A->a(jj, j) = y * c + z * s;
                        A->a(jj, i) = z * c - y * s;
                    }
                }
                rv1[l] = 0.0;
                rv1[k] = f;
                W->a(0, k) = x;
            }
        }
     delete[] rv1;
}
void corecvs::Matrix::svd (Matrix33 * A, Vector3dd * W, Matrix33 * V) [static]
Definition at line 344 of file matrix.cpp.
References a(), and svd().
{
    Matrix mA(*A);
    Matrix mW(1,3);
    Matrix mV(3,3);
    svd (&mA, &mW, &mV);
    *A = (Matrix33)mA;
    *W = Vector3dd(mW.a(0,0),mW.a(0,1),mW.a(0,2));
    *V = (Matrix33)mV;
}
void corecvs::Matrix::svdDesc (Matrix33 * A, Vector3dd * W, Matrix33 * V) [static]
Definition at line 336 of file matrix.cpp.
References corecvs::FixedVectorBase< RealType, ElementType, length >::at(), svd(), and corecvs::Matrix33::swapColumns().
Referenced by corecvs::EssentialMatrix::decompose().
{
    svd (A, W, V);
    if (W->at(0) < W->at(1)) { A->swapColumns(0,1); V->swapColumns(0,1); std::swap(W->at(0), W->at(1)); };
    if (W->at(0) < W->at(2)) { A->swapColumns(0,2); V->swapColumns(0,2); std::swap(W->at(0), W->at(2)); };
    if (W->at(1) < W->at(2)) { A->swapColumns(1,2); V->swapColumns(1,2); std::swap(W->at(1), W->at(2)); };
}
Matrix corecvs::Matrix::t () const
Definition at line 278 of file matrix.cpp.
References a(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::LevenbergMarquardt::fit(), corecvs::HomographyReconstructor::getBestHomographyLSE(), corecvs::HomographyReconstructor::getBestHomographyLSE1(), corecvs::ClassicKalman::predict(), corecvs::Matrix33::ProjectiveByPoints(), and corecvs::ClassicKalman::update().
{
    Matrix result(this->w, this->h, false);
    for (int row = 0; row < result.h ; row++)
    {
        for (int column = 0; column < result.w ; column++)
        {
            result.a(row, column) = this->a(column, row);
        }
    }
    return result;
}
template<typename ElementType, typename IndexType = int32_t> template<typename operation > void corecvs::AbstractBuffer< ElementType, IndexType >::touchOperationElementwize (operation & map) [inline, inherited]
Definition at line 883 of file abstractBuffer.h.
Referenced by corecvs::CorrespondanceList::CorrespondanceList().
    {
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElemRunner = &(this->element(i,0));
            for (IndexType j = 0; j < w; j++)
            {
                map.operator()(i, j, *thisElemRunner);
                thisElemRunner++;
            }
        }
    }
double corecvs::Matrix::trace (void) const
Definition at line 305 of file matrix.cpp.
References a(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    int minDim = h < w ? h : w;
    double sum = 0.0;
    for (int i = 0; i < minDim; i++)
        sum += a(i,i);
    return sum;
}
void corecvs::Matrix::transpose ()
Definition at line 262 of file matrix.cpp.
References a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
Referenced by invSVD().
{
    ASSERT_TRUE(this->h == this->w, "Matrix should be square to transpose.");
    for (int row = 0; row < this->h ; row++)
    {
        for (int column = row + 1; column < this->w ; column++)
        {
            double tmp;
            tmp = this->a(column, row);
            this->a(column, row) = this->a(row, column);
            this->a(row, column) = tmp;
        }
    }
}
Matrix * corecvs::Matrix::transposed () const
Matrix transposition.
Returns:
Definition at line 248 of file matrix.cpp.
References a(), corecvs::AbstractBufferParams::h, Matrix(), and corecvs::AbstractBufferParams::w.
{
    Matrix* result = new Matrix(this->w, this->h, false);
    for (int row = 0; row < result->h ; row++)
    {
        for (int column = 0; column < result->w ; column++)
        {
            result->a(column, row) = this->a(row, column);
        }
    }
    return result;
}
bool_t corecvs::AbstractBufferParams::write (ostream & s, int val, bool_t binaryMode) [static, protected, inherited]
Definition at line 65 of file abstractBuffer.cpp.
References corecvs::write_integer_bin().
Referenced by corecvs::RGB24Buffer::fillWithYUYV().
{
    if (binaryMode)
    {
        write_integer_bin(s, val);
    }
    else
    {
        s << val << ' ';
    }
    return !s.bad();
}
bool_t corecvs::AbstractBufferParams::write (ostream & s, cchar * str, bool_t binaryMode) [static, protected, inherited]
Definition at line 102 of file abstractBuffer.cpp.
References CORE_UNUSED.
{
    s << str << endl;
    CORE_UNUSED(binaryMode);
    return !s.bad();
}
Friends And Related Function Documentation
Matrix operator* (const Matrix & A, const Matrix & B) [friend]
Definition at line 94 of file matrix.cpp.
{
    ASSERT_TRUE (A.w == B.h, "Matrices have wrong sizes");
    Matrix result(A.h, B.w, false);
    int row, column, runner;
    for (row = 0; row < result.h ; row++)
        for (column = 0; column < result.w ; column++)
        {
            double sum = 0;
            for (runner = 0; runner < A.w; runner++)
            {
                sum += A.a(row, runner) * B.a(runner, column);
            }
            result.a(row, column) = sum;
        }
    return result;
}
Matrix operator* (const Matrix & M, const DiagonalMatrix & D) [friend]
Definition at line 164 of file matrix.cpp.
{
    int32_t minDim = min(M.h,M.w);
    minDim = min(minDim, D.size());
    Matrix result(minDim, minDim, false);
    for (int i = 0; i < minDim ; i++)
    {
         for (int j = 0; j < minDim ; j++)
         {
             result.a(i,j) = M.a(i,j) * D.at(i);
         }
    }
    return result;
}
Matrix operator* (const DiagonalMatrix & D, const Matrix & M) [friend]
Vector operator* (const Matrix & M, const Vector & V) [friend]
Definition at line 115 of file matrix.cpp.
{
    ASSERT_TRUE (M.w == V.size(), "Matrix and vector have wrong sizes");
    Vector result(M.h);
    int row, column;
    for (row = 0; row < M.h; row++)
    {
        double sum = 0.0;
        for (column = 0; column < M.w ; column++)
        {
            sum += V.at(column) * M.a(row, column);
        }
        result.at(row) = sum;
    }
    return result;
}
Vector operator* (const Vector & V, const Matrix & M) [friend]
Definition at line 132 of file matrix.cpp.
{
    ASSERT_TRUE (M.h == V.size(), "Matrix and vector have wrong sizes");
    Vector result(M.w);
    int row, column;
    for (column = 0; column < M.w ; column++)
    {
        double sum = 0.0;
        for (row = 0; row < M.h; row++)
        {
            sum += V.at(row) * M.a(row, column);
        }
        result.at(column) = sum;
    }
    return result;
}
Matrix operator*= (Matrix & M, const DiagonalMatrix & D) [friend]
Definition at line 150 of file matrix.cpp.
{
    int32_t minDim = min(M.h,M.w);
    minDim = min(minDim, D.size());
    for (int i = 0; i < minDim ; i++)
    {
         for (int j = 0; j < minDim ; j++)
         {
            M.a(i,j) *= D.at(i);
         }
    }
    return M;
}
Matrix operator+ (const Matrix & A, const Matrix & B) [friend]
Definition at line 196 of file matrix.cpp.
{
    ASSERT_TRUE (A.w == B.w && A.h == B.h, "Matrices have wrong sizes");
    Matrix result(A.h, A.w, false);
    for (int row = 0; row < result.h ; row++)
    {
        for (int column = 0; column < result.w ; column++)
        {
            result.a(row, column) = A.a(row, column) + B.a(row, column);
        }
    }
    return result;
}
Matrix operator- (const Matrix & A, const Matrix & B) [friend]
Definition at line 213 of file matrix.cpp.
{
    ASSERT_TRUE (A.w == B.w && A.h == B.h, "Matrices have wrong sizes");
    Matrix result(A.h, A.w, false);
    for (int row = 0; row < result.h ; row++)
    {
        for (int column = 0; column < result.w ; column++)
        {
            result.a(row, column) = A.a(row, column) - B.a(row, column);
        }
    }
    return result;
}
ostream& operator<< (ostream & out, const Matrix & matrix) [friend]
Definition at line 229 of file matrix.cpp.
{
    streamsize wasPrecision = out.precision(6);
    for (int i = 0; i < matrix.h; i++)
    {
        out << "[";
        for (int j = 0; j < matrix.w; j++)
        {
            out.width(9);
            out << matrix.a(i, j) << " ";
        }
        out << "]\n";
    }
    out.precision(wasPrecision);
    return out;
}
template<typename ElementType, typename IndexType = int32_t> ostream& operator<< (ostream & out, const AbstractBuffer< ElementType, IndexType > & buffer) [friend, inherited]
Definition at line 896 of file abstractBuffer.h.
    {
        // typedef AbstractBuffer::InternalIndexType IndexType;
        //
        for (IndexType i = 0; i < buffer.h; i++)
        {
           for (IndexType j = 0; j < buffer.w; j++)
           {
               out << buffer.element(i, j) << " ";
           }
           out << endl;
        }
        return out;
    }
Member Data Documentation
template<typename ElementType, typename IndexType = int32_t> int corecvs::AbstractBuffer< ElementType, IndexType >::bufferCount = 0 [static, inherited]
Static member that will be used to prevent and debug memory leaks.
Counter for memory profiling.
Definition at line 191 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::AbstractBuffer< SegmentType * >::~AbstractBuffer().
template<typename ElementType, typename IndexType = int32_t> ElementType* corecvs::AbstractBuffer< ElementType, IndexType >::data [inherited]
Sometimes underling buffer should not be deleted.
The properly aligned pointer to an array with data elements, memory of which is kept by the protected field "memoryBlock"
Reimplemented in corecvs::SobelHorInt, corecvs::Gaussian3x3int, corecvs::SobelVertInt, and corecvs::Gaussian3x3.
Definition at line 228 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::LevenMarq::dist(), corecvs::LevenMarq::doLevMarFit(), corecvs::AbstractBuffer< SegmentType * >::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::G12Buffer::fillWithYUYV(), corecvs::AbstractBuffer< SegmentType * >::isAllocated(), corecvs::AbstractBuffer< SegmentType * >::load(), corecvs::G12Buffer::operator=(), and corecvs::AbstractBuffer< SegmentType * >::~AbstractBuffer().
template<typename ElementType, typename IndexType = int32_t> const int corecvs::AbstractBuffer< ElementType, IndexType >::DATA_ALIGN_GRANULARITY = 0xF [static, inherited]
This constant represents the default alignment of the line in the buffer.
It is 16 bytes now to work with SSE and possibly with OPENCL.
Definition at line 185 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_getStride(), and corecvs::AbstractBuffer< SegmentType * >::_init().
template<typename ElementType, typename IndexType = int32_t> BufferType corecvs::AbstractBuffer< ElementType, IndexType >::flags [protected, inherited]
Definition at line 1006 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
int corecvs::AbstractBufferParams::h [inherited]
Definition at line 127 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::EllipticalApproximationUnified< Vector3dd >::addPoint(), corecvs::VJSimpleClassifier::applyToPoint(), corecvs::G12Buffer::binarize(), corecvs::AbstractBuffer< SegmentType * >::binaryOperationInPlace(), corecvs::BooleanBuffer::BooleanBuffer(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), corecvs::ClassicKalman::ClassicKalman(), corecvs::Clustering3D::clustering(), corecvs::COOSparseMatrix::COOSparseMatrix(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::DerivativeBuffer::DerivativeBuffer(), detSVD(), corecvs::G12Buffer::difference(), corecvs::DisplacementBuffer::DisplacementBuffer(), corecvs::AbstractBuffer< SegmentType * >::doConvolve(), corecvs::AbstractBuffer< SegmentType * >::doConvolve1(), corecvs::DistortionCorrectTransform::doCorrectionTransform(), corecvs::RadialCorrection::doCorrectionTransform(), DistortionWidget::doDefaultTransform(), corecvs::TransformationCache::doDeformation(), DistortionWidget::doInversionTransform(), DistortionWidget::doLinesTransform(), DistortionWidget::doManualTransform(), DistortionWidget::doTransformLM(), FlowDrawer::draw(), FlowDrawer::drawBigDotsFast(), FlowDrawer::drawDotsFast(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer2(), corecvs::RGB24Buffer::drawFlowBuffer3(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawG12Buffer(), corecvs::RGB24Buffer::drawG8Buffer(), corecvs::RGB24Buffer::drawIsolines(), corecvs::RGB24Buffer::drawLine(), corecvs::RGB24Buffer::drawLineSimple(), corecvs::FlowBuffer::dump(), corecvs::AbstractBufferParams::dump(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::AbstractContiniousBuffer< double, int >::elementBlInt(), BaseCalculationThread::executeFilterGraph(), corecvs::AbstractBuffer< SegmentType * >::fillRectangleWith(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillWithRands(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::RGB24Buffer::fillWithYUYV(), corecvs::G12Buffer::fillWithYUYV(), ScaleFilter::filter(), corecvs::SpatialGradient::findCornerPoints(), corecvs::LevenbergMarquardt::fit(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), frobeniusNorm(), corecvs::G8Buffer::FromG12Buffer(), corecvs::G12Buffer::G12Buffer(), G12Image::G12Image(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::getEffectiveH(), corecvs::EllipticalApproximationUnified< Vector3dd >::getEllipseParameters(), corecvs::AbstractBuffer< SegmentType * >::getH(), corecvs::FlowBuffer::getMeanDifference(), corecvs::AbstractBuffer< SegmentType * >::getSize(), corecvs::DerivativeBuffer::gradientMagnitudeBuffer(), corecvs::AbstractBuffer< SegmentType * >::hasSameSize(), corecvs::Histogram::Histogram(), PointsRectificationWidget::initCorrespondancePoints(), CloudViewDialog::initializeGLSlot(), corecvs::Splain3Interpolator::interpolate(), corecvs::BilinearInterpolator::interpolate(), inv(), corecvs::FlowBuffer::invert(), invSVD(), corecvs::AbstractBuffer< SegmentType * >::isEqual(), corecvs::AbstractBuffer< SegmentType * >::isEqualTrace(), corecvs::AbstractBuffer< SegmentType * >::isValidCoord(), corecvs::AbstractContiniousBuffer< double, int >::isValidCoordBl(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::AbstractBufferParams::load(), TestbedMainWindow::loadImage(), corecvs::AbstractBuffer< SegmentType * >::mapOperationElementwize(), TestbedMainWindow::maskHue(), matrixSolveGaussian(), DirectShowCaptureInterface::memberCallback(), corecvs::AbstractBuffer< SegmentType * >::mirrorVertical(), corecvs::AbstractBuffer< SegmentType * >::mirrorVerticalDump(), mul(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), negative(), corecvs::DerivativeBuffer::nonMaximalSuppression(), notTooFar(), corecvs::AbstractBufferParams::numElements(), corecvs::BinarizeBlock::operator()(), corecvs::ThickeningBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::SobelFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::operator*(), corecvs::operator*=(), corecvs::operator+(), corecvs::operator-(), corecvs::operator<<(), corecvs::Buffer3d::pointInBox(), corecvs::FloatFlowBuffer::preciseFlowCalc(), corecvs::BlurProcessor::prepareBlurBuffers(), corecvs::ErodeKernel< Algebra >::process(), corecvs::DilateKernel< Algebra >::process(), BaseCalculationThread::recalculateCache(), corecvs::CannyFilter::recursiveEdgeProver(), corecvs::DirectRemapper::remap(), DistortionWidget::resetParameters(), RGB24Image::RGB24Image(), corecvs::AbstractBuffer< SegmentType * >::rotate180(), corecvs::PPMLoader::save(), corecvs::BMPLoader::save(), corecvs::PPMLoader::saveG16(), corecvs::TileGrid::selectWithThreshold(), corecvs::AbstractBufferParams::setH(), DistortionWidget::showBufferChanged(), corecvs::SixDBuffer::SixDBuffer(), corecvs::SpatialGradient::SpatialGradient(), svd(), t(), corecvs::RGB24Buffer::toG12Buffer(), corecvs::AbstractBuffer< SegmentType * >::touchOperationElementwize(), corecvs::FlowBuffer::toVectorForm(), trace(), BaseCalculationThread::transformInputFrames(), transpose(), transposed(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateToDB(), corecvs::Cholesky::udutDecompose(), DistortionWidget::updateAdditionalData(), TestbedMainWindow::updateViewImage(), and corecvs::G12Buffer::verify().
template<typename ElementType, typename IndexType = int32_t> MemoryBlockRef corecvs::AbstractBuffer< ElementType, IndexType >::memoryBlock [protected, inherited]
The beginning of the allocated memory.
Definition at line 1004 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), and corecvs::AbstractBuffer< SegmentType * >::createView().
int corecvs::AbstractBufferParams::stride [inherited]
Definition at line 129 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::AbstractBufferParams::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::G12Buffer::fillWithYUYV(), corecvs::AbstractBuffer< SegmentType * >::getStride(), CloudViewDialog::initializeGLSlot(), corecvs::AbstractBufferParams::load(), corecvs::AbstractBufferParams::numElements(), and corecvs::AbstractBufferParams::setStride().
template<typename ElementType, typename IndexType = int32_t> const IndexType corecvs::AbstractBuffer< ElementType, IndexType >::STRIDE_AUTO = (IndexType)0 [static, inherited]
The height of the buffer.
Todo:
TODO: This field is public do far, but that is dangerous.
The width of the buffer The stride of the buffer
Todo:
TODO: This field is public do far, but that is dangerous.
TODO: Could happen it would be nice to have this in bytes The given stride value to have automatically chosen stride of the buffer
Definition at line 216 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
cchar corecvs::AbstractBufferParams::TAB = '\t' [static, inherited]
Definition at line 131 of file abstractBuffer.h.
Referenced by corecvs::FlowBuffer::dump().
int corecvs::AbstractBufferParams::w [inherited]
Definition at line 128 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_getStride(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::EllipticalApproximationUnified< Vector3dd >::addPoint(), corecvs::VJSimpleClassifier::applyToPoint(), corecvs::G12Buffer::binarize(), corecvs::AbstractBuffer< SegmentType * >::binaryOperationInPlace(), corecvs::BooleanBuffer::BooleanBuffer(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), corecvs::ClassicKalman::ClassicKalman(), corecvs::Clustering3D::clustering(), corecvs::COOSparseMatrix::COOSparseMatrix(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::DerivativeBuffer::DerivativeBuffer(), detSVD(), corecvs::G12Buffer::difference(), corecvs::DisplacementBuffer::DisplacementBuffer(), corecvs::AbstractBuffer< SegmentType * >::doConvolve(), corecvs::AbstractBuffer< SegmentType * >::doConvolve1(), corecvs::DistortionCorrectTransform::doCorrectionTransform(), corecvs::RadialCorrection::doCorrectionTransform(), DistortionWidget::doDefaultTransform(), corecvs::TransformationCache::doDeformation(), DistortionWidget::doInversionTransform(), DistortionWidget::doLinesTransform(), DistortionWidget::doManualTransform(), DistortionWidget::doTransformLM(), FlowDrawer::draw(), FlowDrawer::drawBigDotsFast(), FlowDrawer::drawDotsFast(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer2(), corecvs::RGB24Buffer::drawFlowBuffer3(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawG12Buffer(), corecvs::RGB24Buffer::drawG8Buffer(), corecvs::RGB24Buffer::drawIsolines(), corecvs::RGB24Buffer::drawLine(), corecvs::RGB24Buffer::drawLineSimple(), corecvs::FlowBuffer::dump(), corecvs::AbstractBufferParams::dump(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::AbstractContiniousBuffer< double, int >::elementBlInt(), BaseCalculationThread::executeFilterGraph(), corecvs::AbstractBuffer< SegmentType * >::fillLineWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillRectangleWith(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillWithRands(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::RGB24Buffer::fillWithYUYV(), corecvs::G12Buffer::fillWithYUYV(), ScaleFilter::filter(), corecvs::SpatialGradient::findCornerPoints(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), frobeniusNorm(), corecvs::G8Buffer::FromG12Buffer(), corecvs::G12Buffer::G12Buffer(), G12Image::G12Image(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::getEffectiveW(), corecvs::EllipticalApproximationUnified< Vector3dd >::getEllipseParameters(), corecvs::FlowBuffer::getMeanDifference(), corecvs::AbstractBuffer< SegmentType * >::getSize(), corecvs::ErodeKernel< Algebra >::getSizeX(), corecvs::DilateKernel< Algebra >::getSizeX(), corecvs::AbstractBuffer< SegmentType * >::getW(), corecvs::DerivativeBuffer::gradientMagnitudeBuffer(), corecvs::AbstractBuffer< SegmentType * >::hasSameSize(), corecvs::Histogram::Histogram(), PointsRectificationWidget::initCorrespondancePoints(), CloudViewDialog::initializeGLSlot(), corecvs::AbstractBuffer< SegmentType * >::innerCycleDoConvolve(), corecvs::Splain3Interpolator::interpolate(), corecvs::BilinearInterpolator::interpolate(), inv(), corecvs::FlowBuffer::invert(), invSVD(), corecvs::AbstractBuffer< SegmentType * >::isEqual(), corecvs::AbstractBuffer< SegmentType * >::isEqualTrace(), corecvs::AbstractContiniousBuffer< double, int >::isValidCoordBl(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::AbstractBufferParams::load(), TestbedMainWindow::loadImage(), corecvs::AbstractBuffer< SegmentType * >::mapOperationElementwize(), TestbedMainWindow::maskHue(), matrixSolveGaussian(), DirectShowCaptureInterface::memberCallback(), corecvs::AbstractBuffer< SegmentType * >::mirrorVertical(), corecvs::AbstractBuffer< SegmentType * >::mirrorVerticalDump(), mul(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), negative(), corecvs::DerivativeBuffer::nonMaximalSuppression(), notTooFar(), corecvs::ThickeningBlock::operator()(), corecvs::BinarizeBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::ParallelPrepareBlurBuffers::operator()(), corecvs::SobelFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::AbstractBuffer< ElementType, IndexType >::ParallelDoConvolve1< ReturnType, ConvElementType, ConvIndexType >::operator()(), corecvs::operator*(), corecvs::operator*=(), corecvs::operator+(), corecvs::operator-(), corecvs::operator<<(), corecvs::Buffer3d::pointInBox(), corecvs::FloatFlowBuffer::preciseFlowCalc(), corecvs::BlurProcessor::prepareBlurBuffers(), corecvs::ErodeKernel< Algebra >::process(), corecvs::DilateKernel< Algebra >::process(), BaseCalculationThread::recalculateCache(), corecvs::CannyFilter::recursiveEdgeProver(), corecvs::DirectRemapper::remap(), DistortionWidget::resetParameters(), RGB24Image::RGB24Image(), corecvs::AbstractBuffer< SegmentType * >::rotate180(), corecvs::PPMLoader::save(), corecvs::BMPLoader::save(), corecvs::PPMLoader::saveG16(), corecvs::TileGrid::selectWithThreshold(), corecvs::AbstractBufferParams::setW(), DistortionWidget::showBufferChanged(), corecvs::SixDBuffer::SixDBuffer(), corecvs::SpatialGradient::SpatialGradient(), svd(), t(), corecvs::RGB24Buffer::toG12Buffer(), corecvs::AbstractBuffer< SegmentType * >::touchOperationElementwize(), corecvs::FlowBuffer::toVectorForm(), trace(), BaseCalculationThread::transformInputFrames(), transpose(), transposed(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateToDB(), DistortionWidget::updateAdditionalData(), TestbedMainWindow::updateViewImage(), and corecvs::G12Buffer::verify().
The documentation for this class was generated from the following files:
core/math/matrix/matrix.h
core/math/matrix/matrix.cpp