DeepView: BitSelectorParameters Class Reference
BitSelectorParameters Class Reference
Bit Selector Parameters Bit Selector Parameters.
#include <bitSelectorParameters.h>
Public Types
enum FieldId {
SHIFT_ID, BIT_0_ID, BIT_1_ID, BIT_2_ID,
BIT_3_ID, BIT_4_ID, BIT_5_ID, BIT_6_ID,
BIT_7_ID, BIT_8_ID, BIT_9_ID, BIT_10_ID,
BIT_11_ID, BIT_12_ID, BIT_13_ID, BIT_14_ID,
BIT_15_ID, BIT_SELECTOR_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
int shift () const
bool bit0 () const
bool bit1 () const
bool bit2 () const
bool bit3 () const
bool bit4 () const
bool bit5 () const
bool bit6 () const
bool bit7 () const
bool bit8 () const
bool bit9 () const
bool bit10 () const
bool bit11 () const
bool bit12 () const
bool bit13 () const
bool bit14 () const
bool bit15 () const
void setShift (int shift)
void setBit0 (bool bit0)
void setBit1 (bool bit1)
void setBit2 (bool bit2)
void setBit3 (bool bit3)
void setBit4 (bool bit4)
void setBit5 (bool bit5)
void setBit6 (bool bit6)
void setBit7 (bool bit7)
void setBit8 (bool bit8)
void setBit9 (bool bit9)
void setBit10 (bool bit10)
void setBit11 (bool bit11)
void setBit12 (bool bit12)
void setBit13 (bool bit13)
void setBit14 (bool bit14)
void setBit15 (bool bit15)
template<class VisitorType >
void accept (VisitorType &visitor)
BitSelectorParameters ()
BitSelectorParameters (int shift, bool bit0, bool bit1, bool bit2, bool bit3, bool bit4, bool bit5, bool bit6, bool bit7, bool bit8, bool bit9, bool bit10, bool bit11, bool bit12, bool bit13, bool bit14, bool bit15)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mShift
Section with variables.
bool mBit0
bit 0 bit 0
bool mBit1
bit 1 bit 1
bool mBit2
bit 2 bit 2
bool mBit3
bit 3 bit 3
bool mBit4
bit 4 bit 4
bool mBit5
bit 5 bit 5
bool mBit6
bit 6 bit 6
bool mBit7
bit 7 bit 7
bool mBit8
bit 8 bit 8
bool mBit9
bit 9 bit 9
bool mBit10
bit 10 bit 10
bool mBit11
bit 11 bit 11
bool mBit12
bit 12 bit 12
bool mBit13
bit 13 bit 13
bool mBit14
bit 14 bit 14
bool mBit15
bit 15 bit 15
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, BitSelectorParameters &toSave)
Detailed Description
Bit Selector Parameters Bit Selector Parameters.
Definition at line 38 of file bitSelectorParameters.h.
Member Enumeration Documentation
enum BitSelectorParameters::FieldId
Enumerator:
SHIFT_ID
BIT_0_ID
BIT_1_ID
BIT_2_ID
BIT_3_ID
BIT_4_ID
BIT_5_ID
BIT_6_ID
BIT_7_ID
BIT_8_ID
BIT_9_ID
BIT_10_ID
BIT_11_ID
BIT_12_ID
BIT_13_ID
BIT_14_ID
BIT_15_ID
BIT_SELECTOR_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file bitSelectorParameters.h.
                 {
        SHIFT_ID,
        BIT_0_ID,
        BIT_1_ID,
        BIT_2_ID,
        BIT_3_ID,
        BIT_4_ID,
        BIT_5_ID,
        BIT_6_ID,
        BIT_7_ID,
        BIT_8_ID,
        BIT_9_ID,
        BIT_10_ID,
        BIT_11_ID,
        BIT_12_ID,
        BIT_13_ID,
        BIT_14_ID,
        BIT_15_ID,
        BIT_SELECTOR_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
BitSelectorParameters::BitSelectorParameters () [inline]
Definition at line 369 of file bitSelectorParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
BitSelectorParameters::BitSelectorParameters (int shift, bool bit0, bool bit1, bool bit2, bool bit3, bool bit4, bool bit5, bool bit6, bool bit7, bool bit8, bool bit9, bool bit10, bool bit11, bool bit12, bool bit13, bool bit14, bool bit15) [inline]
Definition at line 375 of file bitSelectorParameters.h.
    {
        mShift = shift;
        mBit0 = bit0;
        mBit1 = bit1;
        mBit2 = bit2;
        mBit3 = bit3;
        mBit4 = bit4;
        mBit5 = bit5;
        mBit6 = bit6;
        mBit7 = bit7;
        mBit8 = bit8;
        mBit9 = bit9;
        mBit10 = bit10;
        mBit11 = bit11;
        mBit12 = bit12;
        mBit13 = bit13;
        mBit14 = bit14;
        mBit15 = bit15;
    }
Member Function Documentation
template<class VisitorType > void BitSelectorParameters::accept (VisitorType & visitor) [inline]
Definition at line 348 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::deserialize(), and corecvs::BitSelectorFilter::serialize().
    {
        visitor.visit(mShift,                     static_cast<const IntField *>     (fields()[SHIFT_ID]));
        visitor.visit(mBit0,                      static_cast<const BoolField *>    (fields()[BIT_0_ID]));
        visitor.visit(mBit1,                      static_cast<const BoolField *>    (fields()[BIT_1_ID]));
        visitor.visit(mBit2,                      static_cast<const BoolField *>    (fields()[BIT_2_ID]));
        visitor.visit(mBit3,                      static_cast<const BoolField *>    (fields()[BIT_3_ID]));
        visitor.visit(mBit4,                      static_cast<const BoolField *>    (fields()[BIT_4_ID]));
        visitor.visit(mBit5,                      static_cast<const BoolField *>    (fields()[BIT_5_ID]));
        visitor.visit(mBit6,                      static_cast<const BoolField *>    (fields()[BIT_6_ID]));
        visitor.visit(mBit7,                      static_cast<const BoolField *>    (fields()[BIT_7_ID]));
        visitor.visit(mBit8,                      static_cast<const BoolField *>    (fields()[BIT_8_ID]));
        visitor.visit(mBit9,                      static_cast<const BoolField *>    (fields()[BIT_9_ID]));
        visitor.visit(mBit10,                     static_cast<const BoolField *>    (fields()[BIT_10_ID]));
        visitor.visit(mBit11,                     static_cast<const BoolField *>    (fields()[BIT_11_ID]));
        visitor.visit(mBit12,                     static_cast<const BoolField *>    (fields()[BIT_12_ID]));
        visitor.visit(mBit13,                     static_cast<const BoolField *>    (fields()[BIT_13_ID]));
        visitor.visit(mBit14,                     static_cast<const BoolField *>    (fields()[BIT_14_ID]));
        visitor.visit(mBit15,                     static_cast<const BoolField *>    (fields()[BIT_15_ID]));
    }
bool BitSelectorParameters::bit0 () const [inline]
Definition at line 179 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit0;
    }
bool BitSelectorParameters::bit1 () const [inline]
Definition at line 184 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit1;
    }
bool BitSelectorParameters::bit10 () const [inline]
Definition at line 229 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit10;
    }
bool BitSelectorParameters::bit11 () const [inline]
Definition at line 234 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit11;
    }
bool BitSelectorParameters::bit12 () const [inline]
Definition at line 239 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit12;
    }
bool BitSelectorParameters::bit13 () const [inline]
Definition at line 244 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit13;
    }
bool BitSelectorParameters::bit14 () const [inline]
Definition at line 249 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit14;
    }
bool BitSelectorParameters::bit15 () const [inline]
Definition at line 254 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit15;
    }
bool BitSelectorParameters::bit2 () const [inline]
Definition at line 189 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit2;
    }
bool BitSelectorParameters::bit3 () const [inline]
Definition at line 194 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit3;
    }
bool BitSelectorParameters::bit4 () const [inline]
Definition at line 199 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit4;
    }
bool BitSelectorParameters::bit5 () const [inline]
Definition at line 204 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit5;
    }
bool BitSelectorParameters::bit6 () const [inline]
Definition at line 209 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit6;
    }
bool BitSelectorParameters::bit7 () const [inline]
Definition at line 214 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit7;
    }
bool BitSelectorParameters::bit8 () const [inline]
Definition at line 219 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit8;
    }
bool BitSelectorParameters::bit9 () const [inline]
Definition at line 224 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mBit9;
    }
static const char* corecvs::BaseReflection< BitSelectorParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< BitSelectorParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< BitSelectorParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* BitSelectorParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 170 of file bitSelectorParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< BitSelectorParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< BitSelectorParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< BitSelectorParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void BitSelectorParameters::print () [inline]
Definition at line 421 of file bitSelectorParameters.h.
    {
        cout << *this;
    }
void BitSelectorParameters::setBit0 (bool bit0) [inline]
Definition at line 265 of file bitSelectorParameters.h.
    {
        mBit0 = bit0;
    }
void BitSelectorParameters::setBit1 (bool bit1) [inline]
Definition at line 270 of file bitSelectorParameters.h.
    {
        mBit1 = bit1;
    }
void BitSelectorParameters::setBit10 (bool bit10) [inline]
Definition at line 315 of file bitSelectorParameters.h.
    {
        mBit10 = bit10;
    }
void BitSelectorParameters::setBit11 (bool bit11) [inline]
Definition at line 320 of file bitSelectorParameters.h.
    {
        mBit11 = bit11;
    }
void BitSelectorParameters::setBit12 (bool bit12) [inline]
Definition at line 325 of file bitSelectorParameters.h.
    {
        mBit12 = bit12;
    }
void BitSelectorParameters::setBit13 (bool bit13) [inline]
Definition at line 330 of file bitSelectorParameters.h.
    {
        mBit13 = bit13;
    }
void BitSelectorParameters::setBit14 (bool bit14) [inline]
Definition at line 335 of file bitSelectorParameters.h.
    {
        mBit14 = bit14;
    }
void BitSelectorParameters::setBit15 (bool bit15) [inline]
Definition at line 340 of file bitSelectorParameters.h.
    {
        mBit15 = bit15;
    }
void BitSelectorParameters::setBit2 (bool bit2) [inline]
Definition at line 275 of file bitSelectorParameters.h.
    {
        mBit2 = bit2;
    }
void BitSelectorParameters::setBit3 (bool bit3) [inline]
Definition at line 280 of file bitSelectorParameters.h.
    {
        mBit3 = bit3;
    }
void BitSelectorParameters::setBit4 (bool bit4) [inline]
Definition at line 285 of file bitSelectorParameters.h.
    {
        mBit4 = bit4;
    }
void BitSelectorParameters::setBit5 (bool bit5) [inline]
Definition at line 290 of file bitSelectorParameters.h.
    {
        mBit5 = bit5;
    }
void BitSelectorParameters::setBit6 (bool bit6) [inline]
Definition at line 295 of file bitSelectorParameters.h.
    {
        mBit6 = bit6;
    }
void BitSelectorParameters::setBit7 (bool bit7) [inline]
Definition at line 300 of file bitSelectorParameters.h.
    {
        mBit7 = bit7;
    }
void BitSelectorParameters::setBit8 (bool bit8) [inline]
Definition at line 305 of file bitSelectorParameters.h.
    {
        mBit8 = bit8;
    }
void BitSelectorParameters::setBit9 (bool bit9) [inline]
Definition at line 310 of file bitSelectorParameters.h.
    {
        mBit9 = bit9;
    }
void BitSelectorParameters::setShift (int shift) [inline]
Definition at line 260 of file bitSelectorParameters.h.
    {
        mShift = shift;
    }
int BitSelectorParameters::shift () const [inline]
Definition at line 174 of file bitSelectorParameters.h.
Referenced by corecvs::BitSelectorFilter::operator()(), and BitSelectorParametersControlWidget::setParameters().
    {
        return mShift;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int BitSelectorParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file bitSelectorParameters.cpp.
References BIT_0_ID, BIT_10_ID, BIT_11_ID, BIT_12_ID, BIT_13_ID, BIT_14_ID, BIT_15_ID, BIT_1_ID, BIT_2_ID, BIT_3_ID, BIT_4_ID, BIT_5_ID, BIT_6_ID, BIT_7_ID, BIT_8_ID, BIT_9_ID, corecvs::BaseReflection< BitSelectorParameters >::fields(), mBit0, mBit1, mBit10, mBit11, mBit12, mBit13, mBit14, mBit15, mBit2, mBit3, mBit4, mBit5, mBit6, mBit7, mBit8, mBit9, mShift, corecvs::BaseReflection< BitSelectorParameters >::naming(), and SHIFT_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Bit Selector Parameters",
        "Bit Selector Parameters",
        ""
    );
    fields().push_back(
        new IntField
        (
          BitSelectorParameters::SHIFT_ID,
          offsetof(BitSelectorParameters, mShift),
          0,
          "shift",
          "shift",
          "shift"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_0_ID,
          offsetof(BitSelectorParameters, mBit0),
          true,
          "bit 0",
          "bit 0",
          "bit 0"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_1_ID,
          offsetof(BitSelectorParameters, mBit1),
          true,
          "bit 1",
          "bit 1",
          "bit 1"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_2_ID,
          offsetof(BitSelectorParameters, mBit2),
          true,
          "bit 2",
          "bit 2",
          "bit 2"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_3_ID,
          offsetof(BitSelectorParameters, mBit3),
          true,
          "bit 3",
          "bit 3",
          "bit 3"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_4_ID,
          offsetof(BitSelectorParameters, mBit4),
          true,
          "bit 4",
          "bit 4",
          "bit 4"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_5_ID,
          offsetof(BitSelectorParameters, mBit5),
          true,
          "bit 5",
          "bit 5",
          "bit 5"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_6_ID,
          offsetof(BitSelectorParameters, mBit6),
          true,
          "bit 6",
          "bit 6",
          "bit 6"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_7_ID,
          offsetof(BitSelectorParameters, mBit7),
          true,
          "bit 7",
          "bit 7",
          "bit 7"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_8_ID,
          offsetof(BitSelectorParameters, mBit8),
          true,
          "bit 8",
          "bit 8",
          "bit 8"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_9_ID,
          offsetof(BitSelectorParameters, mBit9),
          true,
          "bit 9",
          "bit 9",
          "bit 9"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_10_ID,
          offsetof(BitSelectorParameters, mBit10),
          true,
          "bit 10",
          "bit 10",
          "bit 10"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_11_ID,
          offsetof(BitSelectorParameters, mBit11),
          true,
          "bit 11",
          "bit 11",
          "bit 11"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_12_ID,
          offsetof(BitSelectorParameters, mBit12),
          true,
          "bit 12",
          "bit 12",
          "bit 12"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_13_ID,
          offsetof(BitSelectorParameters, mBit13),
          true,
          "bit 13",
          "bit 13",
          "bit 13"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_14_ID,
          offsetof(BitSelectorParameters, mBit14),
          true,
          "bit 14",
          "bit 14",
          "bit 14"
        )
    );
    fields().push_back(
        new BoolField
        (
          BitSelectorParameters::BIT_15_ID,
          offsetof(BitSelectorParameters, mBit15),
          true,
          "bit 15",
          "bit 15",
          "bit 15"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, BitSelectorParameters & toSave) [friend]
Definition at line 414 of file bitSelectorParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< BitSelectorParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
bool BitSelectorParameters::mBit0
bit 0 bit 0
Definition at line 74 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit1
bit 1 bit 1
Definition at line 80 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit10
bit 10 bit 10
Definition at line 134 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit11
bit 11 bit 11
Definition at line 140 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit12
bit 12 bit 12
Definition at line 146 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit13
bit 13 bit 13
Definition at line 152 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit14
bit 14 bit 14
Definition at line 158 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit15
bit 15 bit 15
Definition at line 164 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit2
bit 2 bit 2
Definition at line 86 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit3
bit 3 bit 3
Definition at line 92 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit4
bit 4 bit 4
Definition at line 98 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit5
bit 5 bit 5
Definition at line 104 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit6
bit 6 bit 6
Definition at line 110 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit7
bit 7 bit 7
Definition at line 116 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit8
bit 8 bit 8
Definition at line 122 of file bitSelectorParameters.h.
Referenced by staticInit().
bool BitSelectorParameters::mBit9
bit 9 bit 9
Definition at line 128 of file bitSelectorParameters.h.
Referenced by staticInit().
int BitSelectorParameters::mShift
Section with variables.
shift shift
Definition at line 68 of file bitSelectorParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< BitSelectorParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/bitSelectorParameters.h
core/xml/generated/bitSelectorParameters.cpp