DeepView: PresentationParametersControlWidget Class Reference
PresentationParametersControlWidget Class Reference
#include <presentationParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
PresentationParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~PresentationParametersControlWidget ()
PresentationParameters * createParameters () const
void setParameters (const PresentationParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Ui::PresentationParametersControlWidget * ui ()
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui::PresentationParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 13 of file presentationParametersControlWidget.h.
Constructor & Destructor Documentation
PresentationParametersControlWidget::PresentationParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file presentationParametersControlWidget.cpp.
References mUi, and paramsChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::PresentationParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->leftFrameButton, SIGNAL(clicked(bool)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->rightFrameButton, SIGNAL(clicked(bool)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->stereoComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->flowComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->outputComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->showClustersCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->showHistogramCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->autoUpdateHistogramCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->showAreaOfInterestCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->produce3DCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->produce6DCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->dump3DCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
}
PresentationParametersControlWidget::~PresentationParametersControlWidget ()
Definition at line 37 of file presentationParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void PresentationParametersControlWidget::changeParameters () [inline, slot]
Definition at line 35 of file presentationParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
PresentationParameters * PresentationParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 59 of file presentationParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), ParametersMapperBase::paramsChanged(), ParametersMapperRecorder::paramsChanged(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    PresentationParameters *result = new PresentationParameters(
          mUi->leftFrameButton->isChecked()
        , mUi->rightFrameButton->isChecked()
        , static_cast<StereoStyle::StereoStyle>(mUi->stereoComboBox->currentIndex())
        , static_cast<FlowStyle::FlowStyle>(mUi->flowComboBox->currentIndex())
        , static_cast<OutputStyle::OutputStyle>(mUi->outputComboBox->currentIndex())
        , mUi->showClustersCheckBox->isChecked()
        , mUi->showHistogramCheckBox->isChecked()
        , mUi->autoUpdateHistogramCheckBox->isChecked()
        , mUi->showAreaOfInterestCheckBox->isChecked()
        , mUi->produce3DCheckBox->isChecked()
        , mUi->produce6DCheckBox->isChecked()
        , mUi->dump3DCheckBox->isChecked()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void PresentationParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 43 of file presentationParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    PresentationParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void PresentationParametersControlWidget::paramsChanged () [signal]
Referenced by PresentationParametersControlWidget(), and setParameters().
void PresentationParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 51 of file presentationParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    PresentationParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void PresentationParametersControlWidget::setParameters (const PresentationParameters & input)
Definition at line 84 of file presentationParametersControlWidget.cpp.
References PresentationParameters::autoUpdateHistogram(), PresentationParameters::dump3D(), PresentationParameters::flow(), PresentationParameters::leftFrame(), mUi, PresentationParameters::output(), paramsChanged(), PresentationParameters::produce3D(), PresentationParameters::produce6D(), PresentationParameters::rightFrame(), PresentationParameters::showAreaOfInterest(), PresentationParameters::showClusters(), PresentationParameters::showHistogram(), and PresentationParameters::stereo().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->leftFrameButton->setChecked(input.leftFrame());
    mUi->rightFrameButton->setChecked(input.rightFrame());
    mUi->stereoComboBox->setCurrentIndex(input.stereo());
    mUi->flowComboBox->setCurrentIndex(input.flow());
    mUi->outputComboBox->setCurrentIndex(input.output());
    mUi->showClustersCheckBox->setChecked(input.showClusters());
    mUi->showHistogramCheckBox->setChecked(input.showHistogram());
    mUi->autoUpdateHistogramCheckBox->setChecked(input.autoUpdateHistogram());
    mUi->showAreaOfInterestCheckBox->setChecked(input.showAreaOfInterest());
    mUi->produce3DCheckBox->setChecked(input.produce3D());
    mUi->produce6DCheckBox->setChecked(input.produce6D());
    mUi->dump3DCheckBox->setChecked(input.dump3D());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void PresentationParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 104 of file presentationParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    PresentationParameters *inputCasted = static_cast<PresentationParameters *>(input);
    setParameters(*inputCasted);
}
Ui::PresentationParametersControlWidget* PresentationParametersControlWidget::ui () [inline]
Definition at line 29 of file presentationParametersControlWidget.h.
References mUi.
Referenced by BaseHostDialog::initCapture().
    {
        return mUi;
    }
void PresentationParametersControlWidget::valueChanged () [signal]
Member Data Documentation
bool PresentationParametersControlWidget::autoInit [private]
Definition at line 48 of file presentationParametersControlWidget.h.
Ui::PresentationParametersControlWidget* PresentationParametersControlWidget::mUi [private]
Definition at line 47 of file presentationParametersControlWidget.h.
Referenced by createParameters(), PresentationParametersControlWidget(), setParameters(), ui(), and ~PresentationParametersControlWidget().
QString PresentationParametersControlWidget::rootPath [private]
Definition at line 49 of file presentationParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
applications/base/presentationParametersControlWidget.h
applications/base/presentationParametersControlWidget.cpp