DeepView: V4L2CaptureInterface Class Reference
V4L2CaptureInterface Class Reference
#include <V4L2Capture.h>
Classes
class SpinThread
Public Types
enum DecoderType { UNCOMPRESSED, COMPRESSED_JPEG, COMPRESSED_FAST_JPEG, CODEC_NUMBER }
enum CapErrorCode { SUCCESS = 0, SUCCESS_1CAM = 1, FAILURE = 2 }
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
V4L2CaptureInterface (string _devname, bool isRgb=false)
virtual ~V4L2CaptureInterface ()
virtual int setConfigurationString (string _devname)
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual FramePair getFrameRGB24 ()
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode queryCameraParameters (CameraParameters &parameter)
Check if a specific property can be set/read and what values it can take.
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&formats)
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static void getAllCameras (int *num, int *&cameras)
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Static Public Attributes
static const char * CODEC_NAMES []
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Private Member Functions
int getParameter (int deviceHandle, int type, char const *str, CaptureParameter &param, ImageCaptureInterface::CapPropertyAccessType &accessFlags)
void setCaptureDeviceParameters (const int handle, const int prop, const int32_t val, int &res, const char *text) const
int queryCaptureDeviceParmeter (const int handle, const uint32_t propID, const char *text, ImageCaptureInterface::CapPropertyAccessType &accessFlags, v4l2_queryctrl &request) const
V4L2CameraDescriptor initCamera (string camFileHandle, int h, int w, int fpsnum=1, int fpsdenum=10)
int start (V4L2CameraDescriptor *cam)
int initBuffers (V4L2CameraDescriptor *cam)
V4L2BufferDescriptor dequeue (V4L2CameraDescriptor *cam)
void enqueue (V4L2CameraDescriptor *cam, V4L2BufferDescriptor buffer)
uint16_t * decodeMjpeg (unsigned char *buffer)
void decodeData (V4L2CameraDescriptor *camera, V4L2BufferDescriptor *buffer, G12Buffer **output)
void decodeDataRGB24 (V4L2CameraDescriptor *camera, V4L2BufferDescriptor *buffer, RGB24Buffer **output)
Private Attributes
string interfaceName
Stores the device name.
string deviceName [Frames::MAX_INPUTS_NUMBER]
V4L2CameraMode cameraMode
V4L2CameraDescriptor camera [Frames::MAX_INPUTS_NUMBER]
int formatH
int formatW
DecoderType decoder
SpinThread spin
Spin thread that blocks waiting for the frames.
QMutex protectFrame
This mutex protects both buffers from concurrent reading/writing If somebody is reading of modifying the buffer it should lock the mutex.
QMutex spinRunning
volatile bool shouldStopSpinThread
V4L2BufferDescriptor currentFrame [Frames::MAX_INPUTS_NUMBER]
PreciseTimer lastFrameTime
uint64_t frameDelay
uint64_t skippedCount
uint64_t maxDesync
Maximum de-synchronization that we will not attempt to correct.
bool mIsRgb
Static Private Attributes
static const unsigned LoopQueueBufferNumber = 8
static const unsigned LoopQueueBufferNumberMin = 5
Detailed Description
Definition at line 30 of file V4L2Capture.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapErrorCode [inherited]
Enumerator:
SUCCESS
SUCCESS_1CAM
FAILURE
Reimplemented in DirectShowCaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 72 of file imageCaptureInterface.h.
    {
        SUCCESS       = 0,
        SUCCESS_1CAM  = 1,
        FAILURE      = 2
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
enum V4L2CaptureInterface::DecoderType
Enumerator:
UNCOMPRESSED
COMPRESSED_JPEG
COMPRESSED_FAST_JPEG
CODEC_NUMBER
Definition at line 58 of file V4L2Capture.h.
                    {
        UNCOMPRESSED,
        COMPRESSED_JPEG,
        COMPRESSED_FAST_JPEG,
        CODEC_NUMBER
    };
Constructor & Destructor Documentation
V4L2CaptureInterface::V4L2CaptureInterface (string _devname, bool isRgb = false)
Definition at line 42 of file V4L2Capture.cpp.
References setConfigurationString().
    : spin(this), mIsRgb(isRgb)
{
    setConfigurationString(_devname);
}
V4L2CaptureInterface::~V4L2CaptureInterface () [virtual]
Definition at line 586 of file V4L2Capture.cpp.
References camera, Frames::MAX_INPUTS_NUMBER, shouldStopSpinThread, spinRunning, V4L2CameraDescriptor::stop(), and SYNC_PRINT.
{
   // spinRunning.lock();
    cout << "V4L2CaptureInterface::Request for killing the thread" << endl;
    shouldStopSpinThread = true;
    bool result = spinRunning.tryLock(1000);
    if (result) {
        SYNC_PRINT(("V4L2CaptureInterface::Camera thread killed\n"));
    } else {
        SYNC_PRINT(("V4L2CaptureInterface::Unable to exit Camera thread\n"));
    }
    for (int i = 0; i < Frames::MAX_INPUTS_NUMBER; i++) {
        SYNC_PRINT(("V4L2CaptureInterface::Stopping cameras\n"));
        camera[i].stop();
    }
}
Member Function Documentation
void V4L2CaptureInterface::decodeData (V4L2CameraDescriptor * camera, V4L2BufferDescriptor * buffer, G12Buffer ** output) [private]
Definition at line 334 of file V4L2Capture.cpp.
References V4L2CameraDescriptor::buffers, CODEC_NUMBER, COMPRESSED_FAST_JPEG, COMPRESSED_JPEG, MjpegDecoderLazy::decode(), decodeMjpeg(), decoder, formatH, formatW, V4L2BufferDescriptor::isFilled, V4L2UsersideBuffer::start, SYNC_PRINT, and UNCOMPRESSED.
Referenced by getFrame().
{
    if (!buffer->isFilled)
    {
        *output = new G12Buffer(formatH, formatW);
        return;
    }
    uint8_t *ptrL = (uint8_t*)(camera->buffers[buffer->index].start);
    switch(decoder)
    {
        case UNCOMPRESSED:
            *output = new G12Buffer(formatH, formatW, false);
            (*output)->fillWithYUYV((uint16_t *)ptrL);
            break;
        case COMPRESSED_JPEG:
        {
            uint16_t *ptrDecoded = decodeMjpeg(ptrL );
            *output = new G12Buffer(formatH, formatW, false);
            (*output)->fillWithYUYV(ptrDecoded);
            free(ptrDecoded);
        }
        break;
        case CODEC_NUMBER:
        case COMPRESSED_FAST_JPEG:
        {
            MjpegDecoderLazy lazyDecoder;
            *output = lazyDecoder.decode(ptrL);
            if (*output == NULL) {
                SYNC_PRINT(("V4L2CaptureInterface::decodeData(): Decoded to buffer that is NULL\n"));
            }
        }
        break;
    }
}
void V4L2CaptureInterface::decodeDataRGB24 (V4L2CameraDescriptor * camera, V4L2BufferDescriptor * buffer, RGB24Buffer ** output) [private]
Definition at line 370 of file V4L2Capture.cpp.
References V4L2CameraDescriptor::buffers, CODEC_NUMBER, COMPRESSED_FAST_JPEG, COMPRESSED_JPEG, decoder, formatH, formatW, V4L2BufferDescriptor::isFilled, V4L2UsersideBuffer::start, UNCOMPRESSED, and corecvs::PreciseTimer::usecsToNow().
Referenced by getFrameRGB24().
{
    if (!buffer->isFilled)
    {
        *output = new RGB24Buffer(formatH, formatW);
        return;
    }
    uint8_t *ptrL = (uint8_t*)(camera->buffers[buffer->index].start);
    PreciseTimer timer;
    switch(decoder)
    {
        case UNCOMPRESSED:
            *output = new RGB24Buffer(formatH, formatW);
            printf("Decoding image...");
            timer = PreciseTimer::currentTime();
#if 0
            for(int i = 0; i < formatH; i++)
            {
                uint8_t *ptrI = ptrL + formatW * 2 * i;
                RGBColor *ptrO = &((*output)->element(i,0));
                for(int j = 0; j < formatW; j+=2)
                {
                    int y1 = ptrI[0];
                    int u  = ptrI[1];
                    int y2 = ptrI[2];
                    int v  = ptrI[3];
                    ptrI += 4;
                    ptrO[j    ] = RGBColor::FromYUV(y1, u, v);
                    ptrO[j + 1] = RGBColor::FromYUV(y2, u, v);
                }
            }
#endif
            (*output)->fillWithYUYV(ptrL);
            printf("Delay: %i\n", timer.usecsToNow());
            break;
        case COMPRESSED_JPEG:
        {
            /*uint16_t *ptrDecoded = decodeMjpeg(ptrL );
            *output = new G12Buffer(formatH, formatW, false);
            (*output)->fillWithYUYV(ptrDecoded);
            free(ptrDecoded);*/
        }
        break;
        case CODEC_NUMBER:
        case COMPRESSED_FAST_JPEG:
        break;
    }
}
uint16_t * V4L2CaptureInterface::decodeMjpeg (unsigned char * buffer) [private]
Definition at line 318 of file V4L2Capture.cpp.
References MjpegDecoder::decode(), decoder, and SYNC_PRINT.
Referenced by decodeData().
{
    int width  = 800;
    int height = 600;
    unsigned char * framebuffer = 0;
    MjpegDecoder decoder;
    int result = decoder.decode(&framebuffer, data, &width, &height);
    if (result != 0)
    {
        SYNC_PRINT(("MJPEG decoder error, code %d\n", result));
    }
    return (uint16_t*)framebuffer;
}
V4L2BufferDescriptor V4L2CaptureInterface::dequeue (V4L2CameraDescriptor * cam) [private]
void V4L2CaptureInterface::enqueue (V4L2CameraDescriptor * cam, V4L2BufferDescriptor buffer) [private]
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
void V4L2CaptureInterface::getAllCameras (int * num, int *& cameras) [static]
Definition at line 540 of file V4L2Capture.cpp.
References V4L2CameraDescriptor::initCamera().
{
    vector<int> allCameras;
    const int maxUsbPortNum = 2;
    for (int i = 0; i < maxUsbPortNum; i ++)
    {
        std::stringstream ss;
        ss << i;
        string dev = "/dev/video" + ss.str();
        V4L2CameraDescriptor cameraDescriptor;
        if (cameraDescriptor.initCamera(dev, 480, 640, 1, 30, false) == 0
            || cameraDescriptor.initCamera(dev, 480, 640, 1, 30, true) == 0)
        {
            allCameras.push_back(i);
        }
    }
    *num = allCameras.size();
    cameras = new int[allCameras.size()];
    for (unsigned i = 0; i < allCameras.size(); i ++)
    {
        cameras[i] = allCameras[i];
    }
}
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::getCaptureName (QString & value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 505 of file V4L2Capture.cpp.
References camera, V4L2CameraDescriptor::getCaptureName(), and ImageCaptureInterface::SUCCESS.
{
    string name;
    if (camera[0].getCaptureName(name) != 0)
    {
        camera[1].getCaptureName(name);
    }
    value = QString(name.c_str());
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::getCaptureProperty (int id, int * value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 436 of file V4L2Capture.cpp.
References camera, V4L2CameraDescriptor::getCaptureProperty(), InputType::LEFT_FRAME, and ImageCaptureInterface::SUCCESS.
{
    camera[Frames::LEFT_FRAME].getCaptureProperty(id, value);
    //printf("Getting the values of capture properties is not supported for V4L2 yet.\n");
    return SUCCESS;
}
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::getDeviceName (int num, QString & name) [virtual]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented from ImageCaptureInterface.
Definition at line 530 of file V4L2Capture.cpp.
References deviceName, ImageCaptureInterface::FAILURE, Frames::MAX_INPUTS_NUMBER, and ImageCaptureInterface::SUCCESS.
{
    if (num  < 0 || num >= Frames::MAX_INPUTS_NUMBER)
    {
        return ImageCaptureInterface::FAILURE;
    }
    name = QString(deviceName[num].c_str());
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::getFormats (int * num, ImageCaptureInterface::CameraFormat *& formats) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 516 of file V4L2Capture.cpp.
References camera, V4L2CameraDescriptor::getCaptureFormats(), and ImageCaptureInterface::SUCCESS.
{
    if (camera[0].getCaptureFormats(num, formats) != 0)
    {
        camera[1].getCaptureFormats(num, formats);
    }
    return ImageCaptureInterface::SUCCESS;
}
V4L2CaptureInterface::FramePair V4L2CaptureInterface::getFrame () [virtual]
Main function to request frames from image interface.
Implements ImageCaptureInterface.
Definition at line 120 of file V4L2Capture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, camera, currentFrame, CaptureStatistics::DATA_SIZE, decodeData(), CaptureStatistics::DECODING_TIME, CaptureStatistics::DESYNC_TIME, frameDelay, CaptureStatistics::framesSkipped, CaptureStatistics::INTERFRAME_DELAY, Frames::LEFT_FRAME, InputType::LEFT_FRAME, ImageCaptureInterface::FramePair::leftTimeStamp, Frames::MAX_INPUTS_NUMBER, ImageCaptureInterface::newStatisticsReady(), protectFrame, ImageCaptureInterface::FramePair::rgbBufferLeft, ImageCaptureInterface::FramePair::rgbBufferRight, Frames::RIGHT_FRAME, InputType::RIGHT_FRAME, ImageCaptureInterface::FramePair::rightTimeStamp, skippedCount, start(), SYNC_PRINT, V4L2BufferDescriptor::usecsTimeStamp(), corecvs::PreciseTimer::usecsToNow(), and CaptureStatistics::values.
{
    CaptureStatistics  stats;
    PreciseTimer start = PreciseTimer::currentTime();
    FramePair result;
    protectFrame.lock();
    G12Buffer **results[Frames::MAX_INPUTS_NUMBER] = {
            &result.bufferRight,
            &result.bufferLeft
    };
    result.rgbBufferRight = NULL;
    result.rgbBufferLeft = NULL;
    for (int i=0; i < Frames::MAX_INPUTS_NUMBER; i++)
    {
        decodeData(&camera[i],  &currentFrame[i],  results[i]);
        if ((*results[i]) == NULL) {
            printf("V4L2CaptureInterface::getFrame(): Precrash condition\n");
        }
    }
    if (currentFrame[Frames::LEFT_FRAME].isFilled)
        result.leftTimeStamp  = currentFrame[Frames::LEFT_FRAME].usecsTimeStamp();
    if (currentFrame[Frames::RIGHT_FRAME].isFilled)
        result.rightTimeStamp = currentFrame[Frames::RIGHT_FRAME].usecsTimeStamp();
    if (skippedCount == 0)
    {
        SYNC_PRINT(("Warning: Requested same frames twice. Is this by design?\n"));
    }
    stats.framesSkipped = skippedCount > 0 ? skippedCount - 1 : 0;
    skippedCount = 0;
    protectFrame.unlock();
    stats.values[CaptureStatistics::DECODING_TIME] = start.usecsToNow();
    stats.values[CaptureStatistics::INTERFRAME_DELAY] = frameDelay;
    int64_t desync =  currentFrame[Frames::LEFT_FRAME].usecsTimeStamp() - currentFrame[Frames::RIGHT_FRAME].usecsTimeStamp();
    stats.values[CaptureStatistics::DESYNC_TIME] = desync > 0 ? desync : -desync;
    stats.values[CaptureStatistics::DATA_SIZE] = currentFrame[Frames::LEFT_FRAME].bytesused;
    emit newStatisticsReady(stats);
    return result;
}
V4L2CaptureInterface::FramePair V4L2CaptureInterface::getFrameRGB24 () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 172 of file V4L2Capture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, camera, currentFrame, CaptureStatistics::DATA_SIZE, decodeDataRGB24(), CaptureStatistics::DECODING_TIME, CaptureStatistics::DESYNC_TIME, frameDelay, CaptureStatistics::INTERFRAME_DELAY, Frames::LEFT_FRAME, InputType::LEFT_FRAME, ImageCaptureInterface::FramePair::leftTimeStamp, Frames::MAX_INPUTS_NUMBER, ImageCaptureInterface::newStatisticsReady(), protectFrame, ImageCaptureInterface::FramePair::rgbBufferLeft, ImageCaptureInterface::FramePair::rgbBufferRight, Frames::RIGHT_FRAME, InputType::RIGHT_FRAME, ImageCaptureInterface::FramePair::rightTimeStamp, skippedCount, start(), SYNC_PRINT, corecvs::RGB24Buffer::toG12Buffer(), and V4L2BufferDescriptor::usecsTimeStamp().
{
//    CaptureStatistics  stats;
//    PreciseTimer start = PreciseTimer::currentTime();
    protectFrame.lock();
    FramePair result;
    RGB24Buffer **results[Frames::MAX_INPUTS_NUMBER] = {
            &result.rgbBufferRight,
            &result.rgbBufferLeft
    };
    for (int i = 0; i < Frames::MAX_INPUTS_NUMBER; i++)
    {
        decodeDataRGB24(&camera[i],  &currentFrame[i],  results[i]);
        if ((*results[i]) == NULL) {
            printf("V4L2CaptureInterface::getFrameRGB24(): Precrash condition\n");
        }
    }
    result.bufferLeft  = result.rgbBufferLeft ->toG12Buffer(); // FIXME
    result.bufferRight = result.rgbBufferRight->toG12Buffer();
#if 0
    if (currentFrame[Frames::LEFT_FRAME].isFilled)
        result.leftTimeStamp  = currentFrame[Frames::LEFT_FRAME].usecsTimeStamp();
    if (currentFrame[Frames::RIGHT_FRAME].isFilled)
        result.rightTimeStamp = currentFrame[Frames::RIGHT_FRAME].usecsTimeStamp();
    if (skippedCount == 0)
    {
        SYNC_PRINT(("Warning: Requested same frames twice. Is this by design?\n"));
    }
    stats.framesSkipped = skippedCount > 0 ? skippedCount - 1 : 0;
    skippedCount = 0;
#endif
    protectFrame.unlock();
#if 0
    stats.values[CaptureStatistics::DECODING_TIME] = start.usecsToNow();
    stats.values[CaptureStatistics::INTERFRAME_DELAY] = frameDelay;
    int64_t desync =  currentFrame[Frames::LEFT_FRAME].usecsTimeStamp() - currentFrame[Frames::RIGHT_FRAME].usecsTimeStamp();
    stats.values[CaptureStatistics::DESYNC_TIME] = desync > 0 ? desync : -desync;
    stats.values[CaptureStatistics::DATA_SIZE] = currentFrame[Frames::LEFT_FRAME].bytesused;
    emit newStatisticsReady(stats);
#endif
    return result;
}
QString V4L2CaptureInterface::getInterfaceName () [virtual]
Return the interface device string.
Reimplemented from ImageCaptureInterface.
Definition at line 525 of file V4L2Capture.cpp.
References interfaceName.
{
    return QString("v4l2:") + QString(interfaceName.c_str());
}
int V4L2CaptureInterface::getParameter (int deviceHandle, int type, char const * str, CaptureParameter & param, ImageCaptureInterface::CapPropertyAccessType & accessFlags) [private]
int V4L2CaptureInterface::initBuffers (V4L2CameraDescriptor * cam) [private]
V4L2CameraDescriptor V4L2CaptureInterface::initCamera (string camFileHandle, int h, int w, int fpsnum = 1, int fpsdenum = 10) [private]
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::initCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 443 of file V4L2Capture.cpp.
References camera, cameraMode, deviceName, V4L2CameraDescriptor::formatH, formatH, V4L2CameraDescriptor::formatW, formatW, V4L2CameraMode::fpsdenum, V4L2CameraMode::fpsnum, frameDelay, V4L2CameraDescriptor::initBuffers(), V4L2CameraDescriptor::initCamera(), Frames::LEFT_FRAME, InputType::LEFT_FRAME, Frames::MAX_INPUTS_NUMBER, maxDesync, Frames::RIGHT_FRAME, InputType::RIGHT_FRAME, shouldStopSpinThread, skippedCount, and SYNC_PRINT.
{
    formatH = 0;
    formatW = 0;
    /* TODO: Check that formats are ok*/
    maxDesync = (1000000UL * cameraMode.fpsnum / cameraMode.fpsdenum) * 6 / 10;
    printf("Max allowed desync is %" PRIu64 "\n", maxDesync );
    skippedCount = 0;
    frameDelay = 0;
    shouldStopSpinThread = false;
    int result[Frames::MAX_INPUTS_NUMBER];
    for (int i = 0; i < Frames::MAX_INPUTS_NUMBER; i++) {
        result[i] = 0;
        if (!deviceName[i].empty()) {
            result[i] |= !!(camera[i].initCamera(deviceName[i], cameraMode));
            result[i] |= !!(camera[i].initBuffers());
        }
        if (formatH == 0) {
            formatH = camera[i].formatH;
            formatW = camera[i].formatW;
        } else {
            if (formatH != camera[i].formatH || formatW != camera[i].formatW)
            {
                SYNC_PRINT(( "Cameras initialized to different sizes [%dx%d] and [%dx%d]\n", formatW, formatH, camera[i].formatH, camera[i].formatW ));
            }
        }
    }
    /* If only one camera started, we assume it is the left camera */
    if ((result[Frames::LEFT_FRAME] == 0) && (result[Frames::RIGHT_FRAME] != 0))
    {
        V4L2CameraDescriptor tmp;
        tmp = camera[Frames::LEFT_FRAME];
        camera[Frames::LEFT_FRAME] = camera[Frames::RIGHT_FRAME];
        camera[Frames::RIGHT_FRAME] = tmp;
    }
    return (CapErrorCode) ((bool) result[Frames::LEFT_FRAME] + (bool) result[Frames::RIGHT_FRAME]);
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), getFrame(), getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::queryCameraParameters (CameraParameters & parameter) [virtual]
Check if a specific property can be set/read and what values it can take.
Reimplemented from ImageCaptureInterface.
Definition at line 421 of file V4L2Capture.cpp.
References camera, InputType::LEFT_FRAME, V4L2CameraDescriptor::queryCameraParameters(), and ImageCaptureInterface::SUCCESS.
{
    camera[Frames::LEFT_FRAME].queryCameraParameters(parameter);
    return SUCCESS;
}
int V4L2CaptureInterface::queryCaptureDeviceParmeter (const int handle, const uint32_t propID, const char * text, ImageCaptureInterface::CapPropertyAccessType & accessFlags, v4l2_queryctrl & request) const [private]
void V4L2CaptureInterface::setCaptureDeviceParameters (const int handle, const int prop, const int32_t val, int & res, const char * text) const [private]
Definition at line 565 of file V4L2Capture.cpp.
References SYNC_PRINT.
{
    v4l2_control request;
    if (handle)
    {
        request.id = prop;
        request.value = val;
        int result = ioctl( handle, VIDIOC_S_CTRL, &request);
        if ( result != 0 )
        {
            SYNC_PRINT(( "VIDIOC_S_CTRL for %s with value %d failed. (%s)\n", text, val, strerror(errno) ));
        }
        res |= result;
    }
    else {
        res = -1;
    }
}
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::setCaptureProperty (int id, int value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 428 of file V4L2Capture.cpp.
References camera, Frames::MAX_INPUTS_NUMBER, V4L2CameraDescriptor::setCaptureProperty(), and ImageCaptureInterface::SUCCESS.
{
    for (int i = 0; i < Frames::MAX_INPUTS_NUMBER; i++) {
        camera[i].setCaptureProperty(id, value);
    }
    return SUCCESS;
}
int V4L2CaptureInterface::setConfigurationString (string _devname) [virtual]
Definition at line 48 of file V4L2Capture.cpp.
References cameraMode, CODEC_NAMES, V4L2CameraMode::compressed, COMPRESSED_FAST_JPEG, COMPRESSED_JPEG, decoder, deviceName, V4L2CameraMode::fpsdenum, V4L2CameraMode::fpsnum, V4L2CameraMode::height, interfaceName, Frames::LEFT_FRAME, InputType::LEFT_FRAME, Frames::RIGHT_FRAME, InputType::RIGHT_FRAME, UNCOMPRESSED, and V4L2CameraMode::width.
Referenced by V4L2CaptureInterface().
{
    this->interfaceName = _devname;
    //     Group Number                   1       2 3        4 5      6       7 8       9       10     11   12     13
    QRegExp deviceStringPattern(QString("^([^,:]*)(,([^:]*))?(:(\\d*)/(\\d*))?((:mjpeg)|(:yuyv)|(:fjpeg))?(:(\\d*)x(\\d*))?$"));
    static const int Device1Group     = 1;
    static const int Device2Group     = 3;
    static const int FpsNumGroup      = 5;
    static const int FpsDenumGroup    = 6;
    static const int CompressionGroup = 7;
    static const int WidthGroup       = 12;
    static const int HeightGroup      = 13;
    printf ("Input string %s\n", _devname.c_str());
    QString qdevname(_devname.c_str());
    int result = deviceStringPattern.indexIn(qdevname);
    if (result == -1)
    {
        printf("Error in device string format:%s\n", _devname.c_str());
        exit(EXIT_FAILURE);
    }
    printf (
        "Parsed data:\n"
        "  | - Device 1=%s\n"
        "  | - Device 2=%s\n"
        "  | - FPS %s/%s\n"
        "  | - Size [%sx%s]\n"
        "  \\ - Compressing: %s\n",
        deviceStringPattern.cap(Device1Group) .toAscii().constData(),
        deviceStringPattern.cap(Device2Group) .toAscii().constData(),
        deviceStringPattern.cap(FpsNumGroup)  .toAscii().constData(),
        deviceStringPattern.cap(FpsDenumGroup).toAscii().constData(),
        deviceStringPattern.cap(WidthGroup)   .toAscii().constData(),
        deviceStringPattern.cap(HeightGroup)  .toAscii().constData(),
        deviceStringPattern.cap(CompressionGroup).toAscii().constData());
    deviceName[Frames::RIGHT_FRAME] = deviceStringPattern.cap(Device1Group).toAscii().constData();
    deviceName[Frames::LEFT_FRAME ] = deviceStringPattern.cap(Device2Group).toAscii().constData();
    bool isOk;
    cameraMode.fpsnum = deviceStringPattern.cap(FpsNumGroup).toInt(&isOk);
    if (!isOk) cameraMode.fpsnum = 1;
    cameraMode.fpsdenum = deviceStringPattern.cap(FpsDenumGroup).toInt(&isOk);
    if (!isOk) cameraMode.fpsdenum = 10;
    cameraMode.width = deviceStringPattern.cap(WidthGroup).toInt(&isOk);
    if (!isOk || cameraMode.width <= 0) cameraMode.width = 800;
    cameraMode.height = deviceStringPattern.cap(HeightGroup).toInt(&isOk);
    if (!isOk || cameraMode.height <= 0) cameraMode.height = 600;
    decoder = UNCOMPRESSED;
    if (!deviceStringPattern.cap(CompressionGroup).isEmpty())
    {
        if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":mjpeg")))
            decoder = COMPRESSED_JPEG;
        if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":fjpeg")))
            decoder = COMPRESSED_FAST_JPEG;
    }
    cameraMode.compressed = (decoder != UNCOMPRESSED);
    printf("Capture Right device: V4L2 %s\n", deviceName[Frames::RIGHT_FRAME].c_str());
    printf("Capture Left  device: V4L2 %s\n", deviceName[Frames::LEFT_FRAME ].c_str());
    printf("MJPEG compression is: %s\n", CODEC_NAMES[cameraMode.compressed]);
    return isOk ? 0 : 1;
}
int V4L2CaptureInterface::start (V4L2CameraDescriptor * cam) [private]
Referenced by getFrame(), and getFrameRGB24().
ImageCaptureInterface::CapErrorCode V4L2CaptureInterface::startCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 490 of file V4L2Capture.cpp.
References camera, Frames::LEFT_FRAME, Frames::MAX_INPUTS_NUMBER, InputType::RIGHT_FRAME, shouldStopSpinThread, spin, and V4L2CameraDescriptor::start().
{
    int res[Frames::MAX_INPUTS_NUMBER];
    /*Try to start as synchronous as possible*/
    for (int i = 0; i < Frames::MAX_INPUTS_NUMBER; i++) {
        res[i] = camera[i].start();
    }
    shouldStopSpinThread = false;
    spin.start();
    return (CapErrorCode) ((bool) res[Frames::LEFT_FRAME] + (bool) res[Frames::RIGHT_FRAME]);
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
Member Data Documentation
V4L2CameraDescriptor V4L2CaptureInterface::camera[Frames::MAX_INPUTS_NUMBER] [private]
Definition at line 110 of file V4L2Capture.h.
Referenced by getCaptureName(), getCaptureProperty(), getFormats(), getFrame(), getFrameRGB24(), initCapture(), queryCameraParameters(), V4L2CaptureInterface::SpinThread::run(), setCaptureProperty(), startCapture(), and ~V4L2CaptureInterface().
V4L2CameraMode V4L2CaptureInterface::cameraMode [private]
Definition at line 109 of file V4L2Capture.h.
Referenced by initCapture(), and setConfigurationString().
const char * V4L2CaptureInterface::CODEC_NAMES [static]
Initial value:
{
    "off",
    "mjpeg",
    "mjpeg fast decoder"
}
Definition at line 65 of file V4L2Capture.h.
Referenced by setConfigurationString(), and V4L2CaptureDecoupleInterface::V4L2CaptureDecoupleInterface().
V4L2BufferDescriptor V4L2CaptureInterface::currentFrame[Frames::MAX_INPUTS_NUMBER] [private]
Definition at line 124 of file V4L2Capture.h.
Referenced by getFrame(), getFrameRGB24(), and V4L2CaptureInterface::SpinThread::run().
DecoderType V4L2CaptureInterface::decoder [private]
Definition at line 115 of file V4L2Capture.h.
Referenced by decodeData(), decodeDataRGB24(), decodeMjpeg(), and setConfigurationString().
string V4L2CaptureInterface::deviceName[Frames::MAX_INPUTS_NUMBER] [private]
Definition at line 108 of file V4L2Capture.h.
Referenced by getDeviceName(), initCapture(), and setConfigurationString().
int V4L2CaptureInterface::formatH [private]
Definition at line 112 of file V4L2Capture.h.
Referenced by decodeData(), decodeDataRGB24(), and initCapture().
int V4L2CaptureInterface::formatW [private]
Definition at line 113 of file V4L2Capture.h.
Referenced by decodeData(), decodeDataRGB24(), and initCapture().
uint64_t V4L2CaptureInterface::frameDelay [private]
Definition at line 128 of file V4L2Capture.h.
Referenced by getFrame(), getFrameRGB24(), initCapture(), and V4L2CaptureInterface::SpinThread::run().
string V4L2CaptureInterface::interfaceName [private]
Stores the device name.
Definition at line 71 of file V4L2Capture.h.
Referenced by getInterfaceName(), and setConfigurationString().
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
PreciseTimer V4L2CaptureInterface::lastFrameTime [private]
Definition at line 127 of file V4L2Capture.h.
Referenced by V4L2CaptureInterface::SpinThread::run().
const unsigned V4L2CaptureInterface::LoopQueueBufferNumber = 8 [static, private]
Definition at line 68 of file V4L2Capture.h.
const unsigned V4L2CaptureInterface::LoopQueueBufferNumberMin = 5 [static, private]
Definition at line 69 of file V4L2Capture.h.
uint64_t V4L2CaptureInterface::maxDesync [private]
Maximum de-synchronization that we will not attempt to correct.
Definition at line 132 of file V4L2Capture.h.
Referenced by initCapture(), and V4L2CaptureInterface::SpinThread::run().
bool V4L2CaptureInterface::mIsRgb [private]
Definition at line 134 of file V4L2Capture.h.
QMutex V4L2CaptureInterface::protectFrame [private]
This mutex protects both buffers from concurrent reading/writing If somebody is reading of modifying the buffer it should lock the mutex.
Definition at line 118 of file V4L2Capture.h.
Referenced by getFrame(), getFrameRGB24(), and V4L2CaptureInterface::SpinThread::run().
volatile bool V4L2CaptureInterface::shouldStopSpinThread [private]
Definition at line 122 of file V4L2Capture.h.
Referenced by initCapture(), V4L2CaptureInterface::SpinThread::run(), startCapture(), and ~V4L2CaptureInterface().
uint64_t V4L2CaptureInterface::skippedCount [private]
Definition at line 130 of file V4L2Capture.h.
Referenced by getFrame(), getFrameRGB24(), initCapture(), and V4L2CaptureInterface::SpinThread::run().
SpinThread V4L2CaptureInterface::spin [private]
Spin thread that blocks waiting for the frames.
Definition at line 117 of file V4L2Capture.h.
Referenced by startCapture().
QMutex V4L2CaptureInterface::spinRunning [private]
Definition at line 121 of file V4L2Capture.h.
Referenced by V4L2CaptureInterface::SpinThread::run(), and ~V4L2CaptureInterface().
The documentation for this class was generated from the following files:
utils/framesources/v4l2/V4L2Capture.h
utils/framesources/v4l2/V4L2Capture.cpp