DeepView: OperationParametersControlWidget Class Reference
OperationParametersControlWidget Class Reference
#include <operationParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
OperationParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~OperationParametersControlWidget ()
OperationParameters * createParameters () const
void setParameters (const OperationParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_OperationParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 13 of file operationParametersControlWidget.h.
Constructor & Destructor Documentation
OperationParametersControlWidget::OperationParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file operationParametersControlWidget.cpp.
References mUi, and paramsChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::OperationParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->operationComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
}
OperationParametersControlWidget::~OperationParametersControlWidget ()
Definition at line 26 of file operationParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void OperationParametersControlWidget::changeParameters () [inline, slot]
Definition at line 35 of file operationParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
OperationParameters * OperationParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 48 of file operationParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    OperationParameters *result = new OperationParameters(
          static_cast<Operation::Operation>(mUi->operationComboBox->currentIndex())
    );
    return result;
}
virtual BaseReflectionStatic* OperationParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 26 of file operationParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void OperationParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 32 of file operationParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    OperationParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void OperationParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by OperationParametersControlWidget(), and setParameters().
void OperationParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 40 of file operationParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    OperationParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void OperationParametersControlWidget::setParameters (const OperationParameters & input)
Definition at line 62 of file operationParametersControlWidget.cpp.
References mUi, OperationParameters::operation(), and paramsChanged().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->operationComboBox->setCurrentIndex(input.operation());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void OperationParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 71 of file operationParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    OperationParameters *inputCasted = static_cast<OperationParameters *>(input);
    setParameters(*inputCasted);
}
void OperationParametersControlWidget::valueChanged () [signal]
Member Data Documentation
bool OperationParametersControlWidget::autoInit [private]
Definition at line 46 of file operationParametersControlWidget.h.
Ui_OperationParametersControlWidget* OperationParametersControlWidget::mUi [private]
Definition at line 45 of file operationParametersControlWidget.h.
Referenced by createParameters(), OperationParametersControlWidget(), setParameters(), and ~OperationParametersControlWidget().
QString OperationParametersControlWidget::rootPath [private]
Definition at line 47 of file operationParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/operationParametersControlWidget.h
utils/filters/ui/operationParametersControlWidget.cpp