DeepView: TreeSceneController Class Reference
TreeSceneController Class Reference
#include <treeSceneController.h>
Public Slots
void paramtersChanged ()
void transformationChanged ()
void visibilityChanged (bool state)
void clicked ()
Signals
void redrawRequest (void)
Public Member Functions
TreeSceneController (QString name, QSharedPointer< Scene3D > object, TreeSceneModel *treeModel, bool visible=true)
void generateWidget ()
void replaceScene (QSharedPointer< Scene3D > frame)
QString print (const QString &prefix=QString(""))
TreeSceneController * addChildObject (QString name, QSharedPointer< Scene3D > object, TreeSceneModel *treeModel, bool visible=true)
TreeSceneController * addChildObjectRecursive (QString name, QSharedPointer< Scene3D > object, TreeSceneModel *treeModel, bool visible=true)
template<class Visitor >
void acceptCommon (Visitor &visitor)
template<class Visitor >
void accept (Visitor &visitor)
virtual ~TreeSceneController ()
template<>
void accept (SettingsSetter &visitor)
template<>
void accept (SettingsGetter &visitor)
template<>
void accept (SettingsSetter &visitor)
template<>
void accept (SettingsGetter &visitor)
Public Attributes
TreeSceneModel * mTreeModel
Scenes(in general not in this application) could form DAG, one scene could be a child of two or more Coordinate Frames.
TreeSceneController * mParentController
vector< TreeSceneController * > mChildren
QString mName
QSharedPointer< Scene3D > mObject
Transform3DSelector * mTransform3DWidget
ParametersControlWidgetBase * mParametersWidget
Detailed Description
Definition at line 18 of file treeSceneController.h.
Constructor & Destructor Documentation
TreeSceneController::TreeSceneController (QString name, QSharedPointer< Scene3D > object, TreeSceneModel * treeModel, bool visible = true)
Definition at line 64 of file treeSceneController.cpp.
References generateWidget(), mObject, mTransform3DWidget, mTreeModel, redrawRequest(), transformationChanged(), and visibilityChanged().
Referenced by addChildObject().
  :
    mTreeModel(treeModel),
    mParentController(NULL),
    mName(name),
    mObject(object),
    mParametersWidget(NULL)
{
    if (!mObject.isNull())
    {
       // qDebug() << "Setting name object name to: " << name;
        mObject->name = name;
    }
    mTransform3DWidget = new Transform3DSelector();
    mTransform3DWidget->setWindowTitle(QString("Transform: ") + name);
    generateWidget();
    connect(mTransform3DWidget, SIGNAL(parametersChanged()), this, SLOT(transformationChanged()));
    visibilityChanged(visible);
    connect(this, SIGNAL(redrawRequest()), mTreeModel, SIGNAL(modelChanged()));
}
TreeSceneController::~TreeSceneController () [virtual]
Definition at line 239 of file treeSceneController.cpp.
References mChildren, mParametersWidget, and mTransform3DWidget.
{
    delete_safe(mTransform3DWidget);
    delete_safe(mParametersWidget);
    for (unsigned i = 0; i < mChildren.size(); i++)
    {
       delete_safe(mChildren[i]);
    }
}
Member Function Documentation
template<class Visitor > void TreeSceneController::accept (Visitor & visitor) [inline]
Definition at line 86 of file treeSceneController.h.
References acceptCommon().
Referenced by CloudViewDialog::loadParameters(), and CloudViewDialog::saveParameters().
    {
        acceptCommon(visitor);
    }
template<> void TreeSceneController::accept (SettingsSetter & visitor)
template<> void TreeSceneController::accept (SettingsGetter & visitor)
template<> void TreeSceneController::accept (SettingsSetter & visitor)
Definition at line 252 of file treeSceneController.cpp.
{
    acceptCommon(visitor);
    if (mParametersWidget != NULL)
    {
        WidgetSaver saver(&visitor);
        mParametersWidget->saveParamWidget(saver);
    }
}
template<> void TreeSceneController::accept (SettingsGetter & visitor)
Definition at line 263 of file treeSceneController.cpp.
{
    acceptCommon(visitor);
    if (mParametersWidget != NULL)
    {
        WidgetLoader loader(&visitor);
        mParametersWidget->loadParamWidget(loader);
    }
}
template<class Visitor > void TreeSceneController::acceptCommon (Visitor & visitor) [inline]
Definition at line 66 of file treeSceneController.h.
References mChildren, mName, mObject, and mTransform3DWidget.
Referenced by accept().
    {
        if (mTransform3DWidget)
        {
            visitor.visit(*mTransform3DWidget, "transformation");
        }
        if (this->mObject.isNull())
        {
            return;
        }
        visitor.visit(this->mObject->visible, true, "isVisible");
        for (unsigned i = 0; i < mChildren.size(); i++)
        {
            visitor.visit(*(mChildren[i]), mChildren[i]->mName.toAscii().data());
        }
    }
TreeSceneController * TreeSceneController::addChildObject (QString name, QSharedPointer< Scene3D > object, TreeSceneModel * treeModel, bool visible = true)
Definition at line 185 of file treeSceneController.cpp.
References CoordinateFrame::mChildren, mChildren, mObject, mParentController, and TreeSceneController().
Referenced by addChildObjectRecursive().
{
    if (!mObject->isComplexObject())
    {
        return NULL;
    }
    TreeSceneController *newController = new  TreeSceneController(name, object, treeModel, visible);
    mChildren.push_back(newController);
    newController->mParentController = this;
    QSharedPointer<CoordinateFrame> frame = mObject.staticCast<CoordinateFrame>();
    bool shouldAdd = true;
    for (unsigned i = 0; i < frame->mChildren.size(); i++ )
    {
        if (frame->mChildren[i] == newController->mObject)
            shouldAdd = false;
    }
    if (shouldAdd)
    {
        frame->mChildren.push_back(newController->mObject);
    }
    return newController;
}
TreeSceneController * TreeSceneController::addChildObjectRecursive (QString name, QSharedPointer< Scene3D > object, TreeSceneModel * treeModel, bool visible = true)
Definition at line 215 of file treeSceneController.cpp.
References addChildObject(), and addChildObjectRecursive().
Referenced by addChildObjectRecursive(), and TreeSceneModel::addObject().
{
    TreeSceneController *newController = addChildObject (name, object, treeModel, visible);
    if (newController == NULL)
    {
        return NULL;
    }
    if (object->isComplexObject())
    {
        //qDebug("Breaking complex object and adding parts\n");
        QSharedPointer<CoordinateFrame> frame = object.staticCast<CoordinateFrame>();
        for (unsigned i = 0; i < frame->mChildren.size(); i++)
        {
            //qDebug("  Adding subobject\n");
            newController->addChildObjectRecursive(frame->mChildren[i]->name, frame->mChildren[i], treeModel, visible);
        }
    }
    return newController;
}
void TreeSceneController::clicked () [slot]
Definition at line 52 of file treeSceneController.cpp.
References mParametersWidget, and mTransform3DWidget.
{
    mTransform3DWidget->show();
    mTransform3DWidget->raise();
    if (mParametersWidget != NULL)
    {
        mParametersWidget->show();
        mParametersWidget->raise();
    }
}
void TreeSceneController::generateWidget ()
Definition at line 93 of file treeSceneController.cpp.
References mName, mObject, mParametersWidget, and paramtersChanged().
Referenced by replaceScene(), and TreeSceneController().
{
    if (mObject.isNull())
    {
        return;
    }
    if (mParametersWidget != NULL)
    {
        return;
    }
    //qDebug("TreeSceneController::generateWidget() : Calling creating Control widget");
    mParametersWidget = mObject->getContolWidget();
    if (mParametersWidget == NULL)
    {
        return;
    }
    mParametersWidget->setWindowTitle(QString("Parameters for: ") + mName);
    connect(mParametersWidget,  SIGNAL(paramsChanged()),     this, SLOT(paramtersChanged()));
}
void TreeSceneController::paramtersChanged () [slot]
Definition at line 15 of file treeSceneController.cpp.
References ParametersControlWidgetBase::createParametersVirtual(), mObject, mParametersWidget, and redrawRequest().
Referenced by generateWidget(), and replaceScene().
{
    if (mObject.isNull() || mParametersWidget == NULL)
    {
        return;
    }
    BaseReflectionStatic *params = mParametersWidget->createParametersVirtual();
    if (params != NULL)
        mObject->setParameters(params);
    delete_safe(params);
    emit redrawRequest();
}
QString TreeSceneController::print (const QString & prefix = QString(""))
Definition at line 163 of file treeSceneController.cpp.
References mChildren, mName, mObject, and mParentController.
Referenced by TreeSceneModel::dropMimeData().
  {
    QString result;
    result += prefix + mName + " ";
    result += "(";
    if (!mObject.isNull())
    {
        result += mObject->name + ":" + (mObject->isComplexObject() ? "Frame" : "Object");
    } else {
        result += "null";
    }
    result += ")";
    result += "[" + (mParentController == NULL ? "null" : mParentController->mName) + "]";
    result += "\n";
    for (unsigned i = 0; i < mChildren.size(); i++)
    {
        result += mChildren[i]->print(prefix + "> ");
    }
    return result;
}
void TreeSceneController::redrawRequest (void) [signal]
Referenced by paramtersChanged(), transformationChanged(), TreeSceneController(), and visibilityChanged().
void TreeSceneController::replaceScene (QSharedPointer< Scene3D > frame)
Definition at line 118 of file treeSceneController.cpp.
References generateWidget(), CoordinateFrame::mChildren, mName, mObject, mParentController, paramtersChanged(), and transformationChanged().
Referenced by CloudViewDialog::setNewScenePointer().
{
    if (newObject.isNull())
    {
        return;
    }
    /* Rearrange mesh hierarchy according to the controller */
    if (mParentController != NULL && !mParentController->mObject.isNull())
    {
        if (!mParentController->mObject->isComplexObject())
        {
            qDebug("Seems like internal error\n");
            return;
        }
        QSharedPointer<Scene3D>        current = mObject;
        QSharedPointer<CoordinateFrame> parent = mParentController->mObject.staticCast<CoordinateFrame>();
        unsigned i = 0;
        for (; i < parent->mChildren.size(); i++)
        {
            if (parent->mChildren[i] == current)
            {
                parent->mChildren[i] = newObject;
                break;
            }
        }
        if (i >= parent->mChildren.size())
        {
            qDebug("Seems like internal error\n");
            return;
        }
    }
    newObject->visible = mObject->visible;
    mObject = newObject;
    mObject->name = mName;
    generateWidget();
    paramtersChanged();
    transformationChanged();
}
void TreeSceneController::transformationChanged () [slot]
Definition at line 30 of file treeSceneController.cpp.
References Transform3DSelector::getTransform(), mObject, mTransform3DWidget, and redrawRequest().
Referenced by replaceScene(), and TreeSceneController().
{
    if (mObject.isNull())
    {
        return;
    }
    mObject->transform = mTransform3DWidget->getTransform();
    emit redrawRequest();
}
void TreeSceneController::visibilityChanged (bool state) [slot]
Definition at line 41 of file treeSceneController.cpp.
References mObject, and redrawRequest().
Referenced by TreeSceneController().
{
    if (mObject.isNull())
    {
        return;
    }
    //qDebug () << mFrame->name << "is now:" << (state ? "visible" : "invisible");
    mObject->visible = state;
    emit redrawRequest();
}
Member Data Documentation
vector<TreeSceneController *> TreeSceneController::mChildren
Definition at line 31 of file treeSceneController.h.
Referenced by acceptCommon(), addChildObject(), TreeSceneModel::addObject(), TreeSceneModel::dropMimeData(), TreeSceneModel::index(), TreeSceneModel::parent(), print(), TreeSceneModel::rowCount(), and ~TreeSceneController().
QString TreeSceneController::mName
Definition at line 33 of file treeSceneController.h.
Referenced by acceptCommon(), TreeSceneModel::data(), TreeSceneModel::dropMimeData(), generateWidget(), print(), and replaceScene().
QSharedPointer<Scene3D> TreeSceneController::mObject
Definition at line 34 of file treeSceneController.h.
Referenced by acceptCommon(), addChildObject(), TreeSceneModel::data(), TreeSceneModel::dropMimeData(), generateWidget(), CloudViewDialog::initializeGLSlot(), paramtersChanged(), print(), CloudViewDialog::repaintGLSlot(), replaceScene(), TreeSceneModel::setData(), transformationChanged(), TreeSceneController(), and visibilityChanged().
ParametersControlWidgetBase* TreeSceneController::mParametersWidget
Definition at line 37 of file treeSceneController.h.
Referenced by clicked(), generateWidget(), paramtersChanged(), and ~TreeSceneController().
TreeSceneController* TreeSceneController::mParentController
Definition at line 30 of file treeSceneController.h.
Referenced by addChildObject(), TreeSceneModel::dropMimeData(), TreeSceneModel::parent(), print(), and replaceScene().
Transform3DSelector* TreeSceneController::mTransform3DWidget
Definition at line 36 of file treeSceneController.h.
Referenced by acceptCommon(), clicked(), transformationChanged(), TreeSceneController(), and ~TreeSceneController().
TreeSceneModel* TreeSceneController::mTreeModel
Scenes(in general not in this application) could form DAG, one scene could be a child of two or more Coordinate Frames.
However controllers form the tree hierarchy
Definition at line 28 of file treeSceneController.h.
Referenced by TreeSceneController().
The documentation for this class was generated from the following files:
utils/uis/cloudview/treeSceneController.h
utils/uis/cloudview/treeSceneController.cpp