DeepView: BaseParameters Class Reference
BaseParameters Class Reference
Base parameters Base parameters.
#include <baseParameters.h>
Public Types
enum FieldId {
ROTATION_ID, MIRROR_ID, SWAPCAMERAS_ID, FILTERLOCK_ID,
ENABLEFILTERGRAPH_ID, DOWNSAMPLE_ID, H_ID, W_ID,
AUTOH_ID, AUTOW_ID, X_ID, Y_ID,
INTERPOLATIONTYPE_ID, BASE_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
RotationPresets::RotationPresets rotation () const
bool mirror () const
bool swapCameras () const
bool filterLock () const
bool enableFilterGraph () const
double downsample () const
int h () const
int w () const
bool autoH () const
bool autoW () const
int x () const
int y () const
InterpolationType::InterpolationType interpolationType () const
void setRotation (RotationPresets::RotationPresets rotation)
void setMirror (bool mirror)
void setSwapCameras (bool swapCameras)
void setFilterLock (bool filterLock)
void setEnableFilterGraph (bool enableFilterGraph)
void setDownsample (double downsample)
void setH (int h)
void setW (int w)
void setAutoH (bool autoH)
void setAutoW (bool autoW)
void setX (int x)
void setY (int y)
void setInterpolationType (InterpolationType::InterpolationType interpolationType)
template<class VisitorType >
void accept (VisitorType &visitor)
BaseParameters ()
BaseParameters (RotationPresets::RotationPresets rotation, bool mirror, bool swapCameras, bool filterLock, bool enableFilterGraph, double downsample, int h, int w, bool autoH, bool autoW, int x, int y, InterpolationType::InterpolationType interpolationType)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mRotation
Section with variables.
bool mMirror
mirror mirror
bool mSwapCameras
swapCameras swapCameras
bool mFilterLock
filterLock filterLock
bool mEnableFilterGraph
enableFilterGraph enableFilterGraph
double mDownsample
downsample downsample
int mH
h h
int mW
w w
bool mAutoH
autoH autoH
bool mAutoW
autoW autoW
int mX
x x
int mY
y y
int mInterpolationType
InterpolationType InterpolationType.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, BaseParameters &toSave)
Detailed Description
Base parameters Base parameters.
Definition at line 40 of file baseParameters.h.
Member Enumeration Documentation
enum BaseParameters::FieldId
Enumerator:
ROTATION_ID
MIRROR_ID
SWAPCAMERAS_ID
FILTERLOCK_ID
ENABLEFILTERGRAPH_ID
DOWNSAMPLE_ID
H_ID
W_ID
AUTOH_ID
AUTOW_ID
X_ID
Y_ID
INTERPOLATIONTYPE_ID
BASE_PARAMETERS_FIELD_ID_NUM
Definition at line 43 of file baseParameters.h.
                 {
        ROTATION_ID,
        MIRROR_ID,
        SWAPCAMERAS_ID,
        FILTERLOCK_ID,
        ENABLEFILTERGRAPH_ID,
        DOWNSAMPLE_ID,
        H_ID,
        W_ID,
        AUTOH_ID,
        AUTOW_ID,
        X_ID,
        Y_ID,
        INTERPOLATIONTYPE_ID,
        BASE_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
BaseParameters::BaseParameters () [inline]
Definition at line 299 of file baseParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
BaseParameters::BaseParameters (RotationPresets::RotationPresets rotation, bool mirror, bool swapCameras, bool filterLock, bool enableFilterGraph, double downsample, int h, int w, bool autoH, bool autoW, int x, int y, InterpolationType::InterpolationType interpolationType) [inline]
Definition at line 305 of file baseParameters.h.
    {
        mRotation = rotation;
        mMirror = mirror;
        mSwapCameras = swapCameras;
        mFilterLock = filterLock;
        mEnableFilterGraph = enableFilterGraph;
        mDownsample = downsample;
        mH = h;
        mW = w;
        mAutoH = autoH;
        mAutoW = autoW;
        mX = x;
        mY = y;
        mInterpolationType = interpolationType;
    }
Member Function Documentation
template<class VisitorType > void BaseParameters::accept (VisitorType & visitor) [inline]
Definition at line 282 of file baseParameters.h.
    {
        visitor.visit((int &)mRotation,           static_cast<const EnumField *>    (fields()[ROTATION_ID]));
        visitor.visit(mMirror,                    static_cast<const BoolField *>    (fields()[MIRROR_ID]));
        visitor.visit(mSwapCameras,               static_cast<const BoolField *>    (fields()[SWAPCAMERAS_ID]));
        visitor.visit(mFilterLock,                static_cast<const BoolField *>    (fields()[FILTERLOCK_ID]));
        visitor.visit(mEnableFilterGraph,         static_cast<const BoolField *>    (fields()[ENABLEFILTERGRAPH_ID]));
        visitor.visit(mDownsample,                static_cast<const DoubleField *>  (fields()[DOWNSAMPLE_ID]));
        visitor.visit(mH,                         static_cast<const IntField *>     (fields()[H_ID]));
        visitor.visit(mW,                         static_cast<const IntField *>     (fields()[W_ID]));
        visitor.visit(mAutoH,                     static_cast<const BoolField *>    (fields()[AUTOH_ID]));
        visitor.visit(mAutoW,                     static_cast<const BoolField *>    (fields()[AUTOW_ID]));
        visitor.visit(mX,                         static_cast<const IntField *>     (fields()[X_ID]));
        visitor.visit(mY,                         static_cast<const IntField *>     (fields()[Y_ID]));
        visitor.visit((int &)mInterpolationType,  static_cast<const EnumField *>    (fields()[INTERPOLATIONTYPE_ID]));
    }
bool BaseParameters::autoH () const [inline]
Definition at line 188 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mAutoH;
    }
bool BaseParameters::autoW () const [inline]
Definition at line 193 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mAutoW;
    }
static const char* corecvs::BaseReflection< BaseParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
double BaseParameters::downsample () const [inline]
Definition at line 173 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mDownsample;
    }
bool BaseParameters::enableFilterGraph () const [inline]
Definition at line 168 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mEnableFilterGraph;
    }
static int corecvs::BaseReflection< BaseParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< BaseParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
bool BaseParameters::filterLock () const [inline]
Definition at line 163 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mFilterLock;
    }
const void* BaseParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 144 of file baseParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< BaseParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
int BaseParameters::h () const [inline]
Definition at line 178 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mH;
    }
InterpolationType::InterpolationType BaseParameters::interpolationType () const [inline]
Definition at line 208 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return static_cast<InterpolationType::InterpolationType>(mInterpolationType);
    }
bool BaseParameters::mirror () const [inline]
Definition at line 153 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mMirror;
    }
static const char* corecvs::BaseReflection< BaseParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< BaseParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void BaseParameters::print () [inline]
Definition at line 343 of file baseParameters.h.
    {
        cout << *this;
    }
RotationPresets::RotationPresets BaseParameters::rotation () const [inline]
Definition at line 148 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return static_cast<RotationPresets::RotationPresets>(mRotation);
    }
void BaseParameters::setAutoH (bool autoH) [inline]
Definition at line 254 of file baseParameters.h.
    {
        mAutoH = autoH;
    }
void BaseParameters::setAutoW (bool autoW) [inline]
Definition at line 259 of file baseParameters.h.
    {
        mAutoW = autoW;
    }
void BaseParameters::setDownsample (double downsample) [inline]
Definition at line 239 of file baseParameters.h.
    {
        mDownsample = downsample;
    }
void BaseParameters::setEnableFilterGraph (bool enableFilterGraph) [inline]
Definition at line 234 of file baseParameters.h.
    {
        mEnableFilterGraph = enableFilterGraph;
    }
void BaseParameters::setFilterLock (bool filterLock) [inline]
Definition at line 229 of file baseParameters.h.
    {
        mFilterLock = filterLock;
    }
void BaseParameters::setH (int h) [inline]
Definition at line 244 of file baseParameters.h.
    {
        mH = h;
    }
void BaseParameters::setInterpolationType (InterpolationType::InterpolationType interpolationType) [inline]
Definition at line 274 of file baseParameters.h.
    {
        mInterpolationType = interpolationType;
    }
void BaseParameters::setMirror (bool mirror) [inline]
Definition at line 219 of file baseParameters.h.
    {
        mMirror = mirror;
    }
void BaseParameters::setRotation (RotationPresets::RotationPresets rotation) [inline]
Definition at line 214 of file baseParameters.h.
    {
        mRotation = rotation;
    }
void BaseParameters::setSwapCameras (bool swapCameras) [inline]
Definition at line 224 of file baseParameters.h.
    {
        mSwapCameras = swapCameras;
    }
void BaseParameters::setW (int w) [inline]
Definition at line 249 of file baseParameters.h.
    {
        mW = w;
    }
void BaseParameters::setX (int x) [inline]
Definition at line 264 of file baseParameters.h.
    {
        mX = x;
    }
void BaseParameters::setY (int y) [inline]
Definition at line 269 of file baseParameters.h.
    {
        mY = y;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int BaseParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file baseParameters.cpp.
References AUTOH_ID, AUTOW_ID, DOWNSAMPLE_ID, ENABLEFILTERGRAPH_ID, corecvs::BaseReflection< BaseParameters >::fields(), FILTERLOCK_ID, H_ID, INTERPOLATIONTYPE_ID, mAutoH, mAutoW, mDownsample, mEnableFilterGraph, mFilterLock, mH, mInterpolationType, MIRROR_ID, mMirror, mRotation, mSwapCameras, mW, mX, mY, corecvs::BaseReflection< BaseParameters >::naming(), ROTATION_ID, SWAPCAMERAS_ID, W_ID, X_ID, and Y_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Base Parameters",
        "Base parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          BaseParameters::ROTATION_ID,
          offsetof(BaseParameters, mRotation),
          0,
          "rotation",
          "rotation",
          "rotation",
           NULL
        )
    );
    fields().push_back(
        new BoolField
        (
          BaseParameters::MIRROR_ID,
          offsetof(BaseParameters, mMirror),
          false,
          "mirror",
          "mirror",
          "mirror"
        )
    );
    fields().push_back(
        new BoolField
        (
          BaseParameters::SWAPCAMERAS_ID,
          offsetof(BaseParameters, mSwapCameras),
          false,
          "swapCameras",
          "swapCameras",
          "swapCameras"
        )
    );
    fields().push_back(
        new BoolField
        (
          BaseParameters::FILTERLOCK_ID,
          offsetof(BaseParameters, mFilterLock),
          false,
          "filterLock",
          "filterLock",
          "filterLock"
        )
    );
    fields().push_back(
        new BoolField
        (
          BaseParameters::ENABLEFILTERGRAPH_ID,
          offsetof(BaseParameters, mEnableFilterGraph),
          false,
          "enableFilterGraph",
          "enableFilterGraph",
          "enableFilterGraph"
        )
    );
    fields().push_back(
        new DoubleField
        (
          BaseParameters::DOWNSAMPLE_ID,
          offsetof(BaseParameters, mDownsample),
          1.5,
          "downsample",
          "downsample",
          "downsample"
        )
    );
    fields().push_back(
        new IntField
        (
          BaseParameters::H_ID,
          offsetof(BaseParameters, mH),
          640,
          "h",
          "h",
          "h"
        )
    );
    fields().push_back(
        new IntField
        (
          BaseParameters::W_ID,
          offsetof(BaseParameters, mW),
          480,
          "w",
          "w",
          "w"
        )
    );
    fields().push_back(
        new BoolField
        (
          BaseParameters::AUTOH_ID,
          offsetof(BaseParameters, mAutoH),
          true,
          "autoH",
          "autoH",
          "autoH"
        )
    );
    fields().push_back(
        new BoolField
        (
          BaseParameters::AUTOW_ID,
          offsetof(BaseParameters, mAutoW),
          true,
          "autoW",
          "autoW",
          "autoW"
        )
    );
    fields().push_back(
        new IntField
        (
          BaseParameters::X_ID,
          offsetof(BaseParameters, mX),
          0,
          "x",
          "x",
          "x"
        )
    );
    fields().push_back(
        new IntField
        (
          BaseParameters::Y_ID,
          offsetof(BaseParameters, mY),
          0,
          "y",
          "y",
          "y"
        )
    );
    fields().push_back(
        new EnumField
        (
          BaseParameters::INTERPOLATIONTYPE_ID,
          offsetof(BaseParameters, mInterpolationType),
          0,
          "InterpolationType",
          "InterpolationType",
          "InterpolationType",
           NULL
        )
    );
   return 0;
}
bool BaseParameters::swapCameras () const [inline]
Definition at line 158 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mSwapCameras;
    }
int BaseParameters::w () const [inline]
Definition at line 183 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mW;
    }
int BaseParameters::x () const [inline]
Definition at line 198 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mX;
    }
int BaseParameters::y () const [inline]
Definition at line 203 of file baseParameters.h.
Referenced by BaseParametersControlWidget::setParameters().
    {
        return mY;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, BaseParameters & toSave) [friend]
Definition at line 336 of file baseParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< BaseParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
bool BaseParameters::mAutoH
autoH autoH
Definition at line 114 of file baseParameters.h.
Referenced by staticInit().
bool BaseParameters::mAutoW
autoW autoW
Definition at line 120 of file baseParameters.h.
Referenced by staticInit().
double BaseParameters::mDownsample
downsample downsample
Definition at line 96 of file baseParameters.h.
Referenced by staticInit().
bool BaseParameters::mEnableFilterGraph
enableFilterGraph enableFilterGraph
Definition at line 90 of file baseParameters.h.
Referenced by staticInit().
bool BaseParameters::mFilterLock
filterLock filterLock
Definition at line 84 of file baseParameters.h.
Referenced by staticInit().
int BaseParameters::mH
h h
Definition at line 102 of file baseParameters.h.
Referenced by staticInit().
int BaseParameters::mInterpolationType
InterpolationType InterpolationType.
Definition at line 138 of file baseParameters.h.
Referenced by staticInit().
bool BaseParameters::mMirror
mirror mirror
Definition at line 72 of file baseParameters.h.
Referenced by staticInit().
int BaseParameters::mRotation
Section with variables.
rotation rotation
Definition at line 66 of file baseParameters.h.
Referenced by staticInit().
bool BaseParameters::mSwapCameras
swapCameras swapCameras
Definition at line 78 of file baseParameters.h.
Referenced by staticInit().
int BaseParameters::mW
w w
Definition at line 108 of file baseParameters.h.
Referenced by staticInit().
int BaseParameters::mX
x x
Definition at line 126 of file baseParameters.h.
Referenced by staticInit().
int BaseParameters::mY
y y
Definition at line 132 of file baseParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< BaseParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
applications/base/generatedParameters/baseParameters.h
applications/base/generatedParameters/baseParameters.cpp