DeepView: BitSelector Class Reference
BitSelector Class Reference
#include <bitselector.h>
Public Slots
void maskChanged (void)
void shiftChanged (void)
Signals
void parametersChanged (void)
Public Member Functions
BitSelector (QWidget *parent=0)
~BitSelector ()
virtual G12Buffer * filter (G12Buffer *input)
virtual QString getInstanceName ()
Static Public Member Functions
static QString getName ()
Private Attributes
Ui_BitSelectorClass ui
QCheckBox * bitBoxes [12]
uint32_t mask
int8_t shift
Static Private Attributes
static QString name = QString("Bit Selector")
Detailed Description
Definition at line 11 of file bitselector.h.
Constructor & Destructor Documentation
BitSelector::BitSelector (QWidget * parent = 0)
Definition at line 8 of file bitselector.cpp.
References bitBoxes, mask, maskChanged(), SET_BOX_ARRAY, shift, shiftChanged(), and ui.
    : BaseFilter(parent)
{
    ui.setupUi(this);
    SET_BOX_ARRAY(0);  SET_BOX_ARRAY(1);   SET_BOX_ARRAY(2);  SET_BOX_ARRAY(3);
    SET_BOX_ARRAY(4);  SET_BOX_ARRAY(5);   SET_BOX_ARRAY(6);  SET_BOX_ARRAY(7);
    SET_BOX_ARRAY(8);  SET_BOX_ARRAY(9);   SET_BOX_ARRAY(10); SET_BOX_ARRAY(11);
    mask = 0;
    for (int i = 0; i < 12; i++)
    {
        bitBoxes[i]->setChecked(true);
        mask |= (1 << i);
        connect(bitBoxes[i], SIGNAL(stateChanged(int)), this, SLOT(maskChanged()));
    }
    shift = 0;
    connect(ui.shiftBox, SIGNAL(valueChanged(int)), this, SLOT(shiftChanged()));
}
BitSelector::~BitSelector ()
Definition at line 55 of file bitselector.cpp.
{
}
Member Function Documentation
G12Buffer * BitSelector::filter (G12Buffer * input) [virtual]
Reimplemented from BaseFilter.
Definition at line 46 of file bitselector.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::mapOperationElementwize(), mask, and shift.
{
    G12Buffer *toReturn = new G12Buffer(input);
    ShiftMaskMapper smm(mask, shift);
    toReturn->mapOperationElementwize<ShiftMaskMapper>(smm);
    return toReturn;
}
virtual QString BitSelector::getInstanceName () [inline, virtual]
Reimplemented from BaseFilter.
Definition at line 32 of file bitselector.h.
     {
         return name;
     };
static QString BitSelector::getName () [inline, static]
Reimplemented from BaseFilter.
Definition at line 27 of file bitselector.h.
Referenced by FilterFabric::createFilterInstance(), and FilterFabric::getFilterNames().
     {
         return name;
     };
void BitSelector::maskChanged (void) [slot]
Definition at line 29 of file bitselector.cpp.
References bitBoxes, mask, and BaseFilter::parametersChanged().
Referenced by BitSelector().
{
    mask = 0;
    for (int i = 0; i < 12; i++)
    {
        mask |= bitBoxes[i]->isChecked() ? (1 << i) : 0;
    }
    emit parametersChanged();
}
void BaseFilter::parametersChanged (void) [signal, inherited]
Referenced by maskChanged(), shiftChanged(), GainOffset::updateGainSlider(), GainOffset::updateGainText(), ScaleFilter::updateHeight(), GainOffset::updateOffsetSlider(), GainOffset::updateOffsetText(), ScaleFilter::updateWidth(), ScaleFilter::updateXScale(), ScaleFilter::updateXShift(), ScaleFilter::updateYScale(), and ScaleFilter::updateYShift().
void BitSelector::shiftChanged (void) [slot]
Definition at line 39 of file bitselector.cpp.
References BaseFilter::parametersChanged(), shift, and ui.
Referenced by BitSelector().
{
    shift = ui.shiftBox->value();
    emit parametersChanged();
}
Member Data Documentation
QCheckBox* BitSelector::bitBoxes[12] [private]
Definition at line 38 of file bitselector.h.
Referenced by BitSelector(), and maskChanged().
uint32_t BitSelector::mask [private]
Definition at line 40 of file bitselector.h.
Referenced by BitSelector(), filter(), and maskChanged().
QString BitSelector::name = QString("Bit Selector") [static, private]
Definition at line 16 of file bitselector.h.
int8_t BitSelector::shift [private]
Definition at line 41 of file bitselector.h.
Referenced by BitSelector(), filter(), and shiftChanged().
Ui_BitSelectorClass BitSelector::ui [private]
Reimplemented from BaseFilter.
Definition at line 35 of file bitselector.h.
Referenced by BitSelector(), and shiftChanged().
The documentation for this class was generated from the following files:
utils/filters/legacy/bitselector.h
utils/filters/legacy/bitselector.cpp