DeepView: corecvs::MatrixOperationsBase< RealType, ElementType > Class Template Reference
corecvs::MatrixOperationsBase< RealType, ElementType > Class Template Reference
#include <matrixOperations.h>
Public Member Functions
RealType * realThis ()
Static cast functions.
const RealType * realThis () const
Private Member Functions
ElementType & _at (int i, int j)
Interface related functions.
const ElementType & _at (int i, int j) const
int _height () const
int _width () const
RealType _createMatrix (int h, int w) const
Detailed Description
template<typename RealType, typename ElementType>
class corecvs::MatrixOperationsBase< RealType, ElementType >
Definition at line 16 of file matrixOperations.h.
Member Function Documentation
template<typename RealType , typename ElementType > ElementType& corecvs::MatrixOperationsBase< RealType, ElementType >::_at (int i, int j) [inline, private]
Interface related functions.
Definition at line 34 of file matrixOperations.h.
References corecvs::MatrixOperationsBase< RealType, ElementType >::realThis().
{
        return realThis()->at(i, j);
    }
template<typename RealType , typename ElementType > const ElementType& corecvs::MatrixOperationsBase< RealType, ElementType >::_at (int i, int j) const [inline, private]
Definition at line 38 of file matrixOperations.h.
References corecvs::MatrixOperationsBase< RealType, ElementType >::realThis().
{
        return realThis()->at(i, j);
    }
template<typename RealType , typename ElementType > RealType corecvs::MatrixOperationsBase< RealType, ElementType >::_createMatrix (int h, int w) const [inline, private]
Definition at line 50 of file matrixOperations.h.
References corecvs::MatrixOperationsBase< RealType, ElementType >::realThis().
{
        return realThis()->createMatrix(h, w);
    }
template<typename RealType , typename ElementType > int corecvs::MatrixOperationsBase< RealType, ElementType >::_height () const [inline, private]
Definition at line 42 of file matrixOperations.h.
References corecvs::MatrixOperationsBase< RealType, ElementType >::realThis().
{
        return realThis()->height();
    }
template<typename RealType , typename ElementType > int corecvs::MatrixOperationsBase< RealType, ElementType >::_width () const [inline, private]
Definition at line 46 of file matrixOperations.h.
References corecvs::MatrixOperationsBase< RealType, ElementType >::realThis().
{
        return realThis()->width();
    }
template<typename RealType , typename ElementType > RealType* corecvs::MatrixOperationsBase< RealType, ElementType >::realThis () [inline]
Static cast functions.
Definition at line 22 of file matrixOperations.h.
Referenced by corecvs::MatrixOperationsBase< RealType, ElementType >::_at(), corecvs::MatrixOperationsBase< RealType, ElementType >::_createMatrix(), corecvs::MatrixOperationsBase< RealType, ElementType >::_height(), and corecvs::MatrixOperationsBase< RealType, ElementType >::_width().
{
        return static_cast<RealType *>(this);
    }
template<typename RealType , typename ElementType > const RealType* corecvs::MatrixOperationsBase< RealType, ElementType >::realThis () const [inline]
Definition at line 26 of file matrixOperations.h.
{
        return static_cast<const RealType *>(this);
    }
The documentation for this class was generated from the following file:
core/math/matrix/matrixOperations.h