DeepView: MakePreciseParameters Class Reference
MakePreciseParameters Class Reference
Make Precise Parameters Make Precise Parameters.
#include <makePreciseParameters.h>
Public Types
enum FieldId {
SHOULD_MAKE_PRECISE_ID, ALGORITHM_ID, INTERPOLATION_ID, KLT_ITERATIONS_ID,
KLT_RADIUS_H_ID, KLT_RADIUS_W_ID, KLT_THRESHOLD_ID, MAKE_PRECISE_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
bool shouldMakePrecise () const
MakePreciseAlgorithm::MakePreciseAlgorithm algorithm () const
PreciseInterpolationType::PreciseInterpolationType interpolation () const
int kLTIterations () const
int kLTRadiusH () const
int kLTRadiusW () const
double kLTThreshold () const
void setShouldMakePrecise (bool shouldMakePrecise)
void setAlgorithm (MakePreciseAlgorithm::MakePreciseAlgorithm algorithm)
void setInterpolation (PreciseInterpolationType::PreciseInterpolationType interpolation)
void setKLTIterations (int kLTIterations)
void setKLTRadiusH (int kLTRadiusH)
void setKLTRadiusW (int kLTRadiusW)
void setKLTThreshold (double kLTThreshold)
template<class VisitorType >
void accept (VisitorType &visitor)
MakePreciseParameters ()
MakePreciseParameters (bool shouldMakePrecise, MakePreciseAlgorithm::MakePreciseAlgorithm algorithm, PreciseInterpolationType::PreciseInterpolationType interpolation, int kLTIterations, int kLTRadiusH, int kLTRadiusW, double kLTThreshold)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
bool mShouldMakePrecise
Section with variables.
int mAlgorithm
Algorithm Algorithm.
int mInterpolation
Interpolation Interpolation.
int mKLTIterations
KLT iterations KLT iterations.
int mKLTRadiusH
KLT Radius H KLT Radius H.
int mKLTRadiusW
KLT Radius W KLT Radius W.
double mKLTThreshold
KLT Threshold KLT Threshold.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, MakePreciseParameters &toSave)
Detailed Description
Make Precise Parameters Make Precise Parameters.
Definition at line 40 of file makePreciseParameters.h.
Member Enumeration Documentation
enum MakePreciseParameters::FieldId
Enumerator:
SHOULD_MAKE_PRECISE_ID
ALGORITHM_ID
INTERPOLATION_ID
KLT_ITERATIONS_ID
KLT_RADIUS_H_ID
KLT_RADIUS_W_ID
KLT_THRESHOLD_ID
MAKE_PRECISE_PARAMETERS_FIELD_ID_NUM
Definition at line 43 of file makePreciseParameters.h.
                 {
        SHOULD_MAKE_PRECISE_ID,
        ALGORITHM_ID,
        INTERPOLATION_ID,
        KLT_ITERATIONS_ID,
        KLT_RADIUS_H_ID,
        KLT_RADIUS_W_ID,
        KLT_THRESHOLD_ID,
        MAKE_PRECISE_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
MakePreciseParameters::MakePreciseParameters () [inline]
Definition at line 191 of file makePreciseParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
MakePreciseParameters::MakePreciseParameters (bool shouldMakePrecise, MakePreciseAlgorithm::MakePreciseAlgorithm algorithm, PreciseInterpolationType::PreciseInterpolationType interpolation, int kLTIterations, int kLTRadiusH, int kLTRadiusW, double kLTThreshold) [inline]
Definition at line 197 of file makePreciseParameters.h.
    {
        mShouldMakePrecise = shouldMakePrecise;
        mAlgorithm = algorithm;
        mInterpolation = interpolation;
        mKLTIterations = kLTIterations;
        mKLTRadiusH = kLTRadiusH;
        mKLTRadiusW = kLTRadiusW;
        mKLTThreshold = kLTThreshold;
    }
Member Function Documentation
template<class VisitorType > void MakePreciseParameters::accept (VisitorType & visitor) [inline]
Definition at line 180 of file makePreciseParameters.h.
    {
        visitor.visit(mShouldMakePrecise,         static_cast<const BoolField *>    (fields()[SHOULD_MAKE_PRECISE_ID]));
        visitor.visit((int &)mAlgorithm,          static_cast<const EnumField *>    (fields()[ALGORITHM_ID]));
        visitor.visit((int &)mInterpolation,      static_cast<const EnumField *>    (fields()[INTERPOLATION_ID]));
        visitor.visit(mKLTIterations,             static_cast<const IntField *>     (fields()[KLT_ITERATIONS_ID]));
        visitor.visit(mKLTRadiusH,                static_cast<const IntField *>     (fields()[KLT_RADIUS_H_ID]));
        visitor.visit(mKLTRadiusW,                static_cast<const IntField *>     (fields()[KLT_RADIUS_W_ID]));
        visitor.visit(mKLTThreshold,              static_cast<const DoubleField *>  (fields()[KLT_THRESHOLD_ID]));
    }
MakePreciseAlgorithm::MakePreciseAlgorithm MakePreciseParameters::algorithm () const [inline]
Definition at line 111 of file makePreciseParameters.h.
Referenced by MakePreciseParametersControlWidget::setParameters().
    {
        return static_cast<MakePreciseAlgorithm::MakePreciseAlgorithm>(mAlgorithm);
    }
static const char* corecvs::BaseReflection< MakePreciseParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< MakePreciseParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< MakePreciseParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* MakePreciseParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 102 of file makePreciseParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< MakePreciseParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
PreciseInterpolationType::PreciseInterpolationType MakePreciseParameters::interpolation () const [inline]
Definition at line 116 of file makePreciseParameters.h.
Referenced by corecvs::FloatFlowBuffer::preciseFlow(), and MakePreciseParametersControlWidget::setParameters().
    {
        return static_cast<PreciseInterpolationType::PreciseInterpolationType>(mInterpolation);
    }
int MakePreciseParameters::kLTIterations () const [inline]
Definition at line 121 of file makePreciseParameters.h.
Referenced by corecvs::FloatFlowBuffer::preciseFlowCalc(), and MakePreciseParametersControlWidget::setParameters().
    {
        return mKLTIterations;
    }
int MakePreciseParameters::kLTRadiusH () const [inline]
Definition at line 126 of file makePreciseParameters.h.
Referenced by corecvs::FloatFlowBuffer::preciseFlowCalc(), and MakePreciseParametersControlWidget::setParameters().
    {
        return mKLTRadiusH;
    }
int MakePreciseParameters::kLTRadiusW () const [inline]
Definition at line 131 of file makePreciseParameters.h.
Referenced by corecvs::FloatFlowBuffer::preciseFlowCalc(), and MakePreciseParametersControlWidget::setParameters().
    {
        return mKLTRadiusW;
    }
double MakePreciseParameters::kLTThreshold () const [inline]
Definition at line 136 of file makePreciseParameters.h.
Referenced by MakePreciseParametersControlWidget::setParameters().
    {
        return mKLTThreshold;
    }
static const char* corecvs::BaseReflection< MakePreciseParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< MakePreciseParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void MakePreciseParameters::print () [inline]
Definition at line 223 of file makePreciseParameters.h.
    {
        cout << *this;
    }
void MakePreciseParameters::setAlgorithm (MakePreciseAlgorithm::MakePreciseAlgorithm algorithm) [inline]
Definition at line 147 of file makePreciseParameters.h.
    {
        mAlgorithm = algorithm;
    }
void MakePreciseParameters::setInterpolation (PreciseInterpolationType::PreciseInterpolationType interpolation) [inline]
Definition at line 152 of file makePreciseParameters.h.
    {
        mInterpolation = interpolation;
    }
void MakePreciseParameters::setKLTIterations (int kLTIterations) [inline]
Definition at line 157 of file makePreciseParameters.h.
    {
        mKLTIterations = kLTIterations;
    }
void MakePreciseParameters::setKLTRadiusH (int kLTRadiusH) [inline]
Definition at line 162 of file makePreciseParameters.h.
    {
        mKLTRadiusH = kLTRadiusH;
    }
void MakePreciseParameters::setKLTRadiusW (int kLTRadiusW) [inline]
Definition at line 167 of file makePreciseParameters.h.
    {
        mKLTRadiusW = kLTRadiusW;
    }
void MakePreciseParameters::setKLTThreshold (double kLTThreshold) [inline]
Definition at line 172 of file makePreciseParameters.h.
    {
        mKLTThreshold = kLTThreshold;
    }
void MakePreciseParameters::setShouldMakePrecise (bool shouldMakePrecise) [inline]
Definition at line 142 of file makePreciseParameters.h.
    {
        mShouldMakePrecise = shouldMakePrecise;
    }
bool MakePreciseParameters::shouldMakePrecise () const [inline]
Definition at line 106 of file makePreciseParameters.h.
Referenced by MakePreciseParametersControlWidget::setParameters().
    {
        return mShouldMakePrecise;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int MakePreciseParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file makePreciseParameters.cpp.
References ALGORITHM_ID, corecvs::BaseReflection< MakePreciseParameters >::fields(), INTERPOLATION_ID, KLT_ITERATIONS_ID, KLT_RADIUS_H_ID, KLT_RADIUS_W_ID, KLT_THRESHOLD_ID, mAlgorithm, mInterpolation, mKLTIterations, mKLTRadiusH, mKLTRadiusW, mKLTThreshold, mShouldMakePrecise, corecvs::BaseReflection< MakePreciseParameters >::naming(), and SHOULD_MAKE_PRECISE_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Make Precise Parameters",
        "Make Precise Parameters",
        ""
    );
    fields().push_back(
        new BoolField
        (
          MakePreciseParameters::SHOULD_MAKE_PRECISE_ID,
          offsetof(MakePreciseParameters, mShouldMakePrecise),
          false,
          "Should Make Precise",
          "Should Make Precise",
          "Should Make Precise"
        )
    );
    fields().push_back(
        new EnumField
        (
          MakePreciseParameters::ALGORITHM_ID,
          offsetof(MakePreciseParameters, mAlgorithm),
          0,
          "Algorithm",
          "Algorithm",
          "Algorithm",
           NULL
        )
    );
    fields().push_back(
        new EnumField
        (
          MakePreciseParameters::INTERPOLATION_ID,
          offsetof(MakePreciseParameters, mInterpolation),
          0,
          "Interpolation",
          "Interpolation",
          "Interpolation",
           NULL
        )
    );
    fields().push_back(
        new IntField
        (
          MakePreciseParameters::KLT_ITERATIONS_ID,
          offsetof(MakePreciseParameters, mKLTIterations),
          0,
          "KLT iterations",
          "KLT iterations",
          "KLT iterations"
        )
    );
    fields().push_back(
        new IntField
        (
          MakePreciseParameters::KLT_RADIUS_H_ID,
          offsetof(MakePreciseParameters, mKLTRadiusH),
          0,
          "KLT Radius H",
          "KLT Radius H",
          "KLT Radius H"
        )
    );
    fields().push_back(
        new IntField
        (
          MakePreciseParameters::KLT_RADIUS_W_ID,
          offsetof(MakePreciseParameters, mKLTRadiusW),
          0,
          "KLT Radius W",
          "KLT Radius W",
          "KLT Radius W"
        )
    );
    fields().push_back(
        new DoubleField
        (
          MakePreciseParameters::KLT_THRESHOLD_ID,
          offsetof(MakePreciseParameters, mKLTThreshold),
          0,
          "KLT Threshold",
          "KLT Threshold",
          "KLT Threshold"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, MakePreciseParameters & toSave) [friend]
Definition at line 216 of file makePreciseParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< MakePreciseParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int MakePreciseParameters::mAlgorithm
Algorithm Algorithm.
Definition at line 66 of file makePreciseParameters.h.
Referenced by staticInit().
int MakePreciseParameters::mInterpolation
Interpolation Interpolation.
Definition at line 72 of file makePreciseParameters.h.
Referenced by staticInit().
int MakePreciseParameters::mKLTIterations
KLT iterations KLT iterations.
Definition at line 78 of file makePreciseParameters.h.
Referenced by staticInit().
int MakePreciseParameters::mKLTRadiusH
KLT Radius H KLT Radius H.
Definition at line 84 of file makePreciseParameters.h.
Referenced by staticInit().
int MakePreciseParameters::mKLTRadiusW
KLT Radius W KLT Radius W.
Definition at line 90 of file makePreciseParameters.h.
Referenced by staticInit().
double MakePreciseParameters::mKLTThreshold
KLT Threshold KLT Threshold.
Definition at line 96 of file makePreciseParameters.h.
Referenced by staticInit().
bool MakePreciseParameters::mShouldMakePrecise
Section with variables.
Should Make Precise Should Make Precise
Definition at line 60 of file makePreciseParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< MakePreciseParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/makePreciseParameters.h
core/xml/generated/makePreciseParameters.cpp