DeepView: corecvs::EllipticalApproximation Class Reference
corecvs::EllipticalApproximation Class Reference
This class searches the ellipse that looks like a given blob.
#include <ellipticalApproximation.h>
Public Member Functions
int getSize () const
Get number of points for which approximation is computed.
Vector2dd getMean () const
Position of input points center.
Vector2dd getCenter () const
Vector2dd getMeanSquare () const
Vector2dd getPerAxisDeviationSquare () const
Vector2dd getPerAxisDeviation () const
double getDeviationSquare () const
double getRadius () const
double mu11 () const
this function computes
double getCenteredMixedMoment () const
double getEllipseOrientation () const
Vector2dd getEllipseAxisSquare () const
Length of the axis are in fact square roots of the eigenvalues of the covariance matrix.
Vector2dd getMainDirection () const
This function computes eigenvector corresponding to largest eigenvalue
.
Vector2dd getEllipseAxis () const
void addPoint (double x, double y)
void addPoint (const Vector2dd &point)
EllipticalApproximation ()
~EllipticalApproximation ()
Public Attributes
int count
Vector2dd sum
Vector2dd sumSquares
double mixedMoment
Detailed Description
This class searches the ellipse that looks like a given blob.
We use image moments (p,q)
Or in discrete case
moment is a total weight of the area
and are mean x and mean y
We can now define central moments
Covariance could be expressed as:
Covariance matrix is Hermitian and symmetric, so spectral theorem apply.
Definition at line 50 of file ellipticalApproximation.h.
Constructor & Destructor Documentation
corecvs::EllipticalApproximation::EllipticalApproximation () [inline]
Definition at line 231 of file ellipticalApproximation.h.
                              :
        count(0),
        sum(0.0),
        sumSquares(0.0),
        mixedMoment(0.0)
    {
    }
corecvs::EllipticalApproximation::~EllipticalApproximation ()
Definition at line 12 of file ellipticalApproximation.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
void corecvs::EllipticalApproximation::addPoint (double x, double y) [inline]
Definition at line 218 of file ellipticalApproximation.h.
Referenced by corecvs::DistPointsFunction::operator()().
    {
        addPoint(Vector2dd(x,y));
    }
void corecvs::EllipticalApproximation::addPoint (const Vector2dd & point) [inline]
Definition at line 223 of file ellipticalApproximation.h.
References count, mixedMoment, sum, and sumSquares.
    {
        count++;
        sum += point;
        sumSquares += point * point;
        mixedMoment += point.x() * point.y();
    }
Vector2dd corecvs::EllipticalApproximation::getCenter () const [inline]
Definition at line 74 of file ellipticalApproximation.h.
References getMean().
Referenced by corecvs::DistPointsFunction::operator()().
    {
        return getMean();
    }
double corecvs::EllipticalApproximation::getCenteredMixedMoment () const [inline]
Definition at line 117 of file ellipticalApproximation.h.
References mu11().
Referenced by getEllipseOrientation().
    {
        return mu11();
    }
double corecvs::EllipticalApproximation::getDeviationSquare () const [inline]
Definition at line 97 of file ellipticalApproximation.h.
References getPerAxisDeviationSquare(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by getRadius().
    {
        Vector2dd perAxisDeviationSquare = getPerAxisDeviationSquare();
        return perAxisDeviationSquare.x() + perAxisDeviationSquare.y();
    }
Vector2dd corecvs::EllipticalApproximation::getEllipseAxis () const [inline]
Definition at line 212 of file ellipticalApproximation.h.
References getEllipseAxisSquare(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        Vector2dd axisSquare = getEllipseAxisSquare();
        return Vector2dd(sqrt(axisSquare.x()), sqrt(axisSquare.y()));
    }
Vector2dd corecvs::EllipticalApproximation::getEllipseAxisSquare () const [inline]
Length of the axis are in fact square roots of the eigenvalues of the covariance matrix.
This function returns two eigenvalues of Covariance could be expressed as:
which for the 2 by 2 matrix can be directly computed as
Definition at line 162 of file ellipticalApproximation.h.
References getPerAxisDeviationSquare(), mu11(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by getEllipseAxis(), and getMainDirection().
    {
        Vector2dd perAxisDeviationSquare = getPerAxisDeviationSquare();
        double momentDiff = perAxisDeviationSquare.x() - perAxisDeviationSquare.y();
        double centeredMixedMoment = mu11();
        double b =   (perAxisDeviationSquare.x() + perAxisDeviationSquare.y()) / 2.0;
        double det = sqrt(4.0 * centeredMixedMoment * centeredMixedMoment +  momentDiff * momentDiff);
        double longAxis  = b + 0.5 * det;
        double shortAxis = b - 0.5 * det;
        return Vector2dd(longAxis, shortAxis);
    }
double corecvs::EllipticalApproximation::getEllipseOrientation () const [inline]
Definition at line 122 of file ellipticalApproximation.h.
References getCenteredMixedMoment(), getPerAxisDeviationSquare(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        Vector2dd perAxisDeviation = getPerAxisDeviationSquare();
        double momentDiff = perAxisDeviation.x() - perAxisDeviation.y();
        return 0.5 * atan2(2 * getCenteredMixedMoment(), momentDiff);
    }
Vector2dd corecvs::EllipticalApproximation::getMainDirection () const [inline]
This function computes eigenvector corresponding to largest eigenvalue
.
So are lines of the matrix are linearly dependent
So
Definition at line 200 of file ellipticalApproximation.h.
References getEllipseAxisSquare(), getPerAxisDeviationSquare(), mu11(), and corecvs::Vector2d< ElementType >::x().
Referenced by corecvs::DistPointsFunction::operator()().
    {
        Vector2dd axisSquare = getEllipseAxisSquare();
        double value = axisSquare.x();
        Vector2dd perAxisDeviationSquare = getPerAxisDeviationSquare();
        double mixed = mu11();
        return Vector2dd(mixed, value - perAxisDeviationSquare.x()).normalised();
    }
Vector2dd corecvs::EllipticalApproximation::getMean () const [inline]
Position of input points center.
Definition at line 69 of file ellipticalApproximation.h.
References count, and sum.
Referenced by getCenter(), getPerAxisDeviationSquare(), and mu11().
    {
        return sum / (double)count;
    }
Vector2dd corecvs::EllipticalApproximation::getMeanSquare () const [inline]
Definition at line 79 of file ellipticalApproximation.h.
References count, and sumSquares.
Referenced by getPerAxisDeviationSquare().
    {
        return sumSquares / (double)count;
    }
Vector2dd corecvs::EllipticalApproximation::getPerAxisDeviation () const [inline]
Definition at line 91 of file ellipticalApproximation.h.
References getPerAxisDeviationSquare(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        Vector2dd perAxisDeviationSquare = getPerAxisDeviationSquare();
        return Vector2dd(sqrt(perAxisDeviationSquare.x()), sqrt(perAxisDeviationSquare.y()));
    }
Vector2dd corecvs::EllipticalApproximation::getPerAxisDeviationSquare () const [inline]
Definition at line 84 of file ellipticalApproximation.h.
References getMean(), and getMeanSquare().
Referenced by getDeviationSquare(), getEllipseAxisSquare(), getEllipseOrientation(), getMainDirection(), and getPerAxisDeviation().
    {
        Vector2dd mean   = getMean();
        Vector2dd meanSq = getMeanSquare();
        return meanSq - (mean * mean);
    }
double corecvs::EllipticalApproximation::getRadius () const [inline]
Definition at line 103 of file ellipticalApproximation.h.
References getDeviationSquare().
    {
        return sqrt(getDeviationSquare());
    }
int corecvs::EllipticalApproximation::getSize () const [inline]
Get number of points for which approximation is computed.
Definition at line 61 of file ellipticalApproximation.h.
References count.
    {
        return count;
    }
double corecvs::EllipticalApproximation::mu11 () const [inline]
this function computes
Definition at line 111 of file ellipticalApproximation.h.
References count, getMean(), mixedMoment, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by getCenteredMixedMoment(), getEllipseAxisSquare(), and getMainDirection().
    {
        Vector2dd mean = getMean();
        return (mixedMoment / (double)count) - mean.x() * mean.y();
    }
Member Data Documentation
int corecvs::EllipticalApproximation::count
Definition at line 53 of file ellipticalApproximation.h.
Referenced by addPoint(), getMean(), getMeanSquare(), getSize(), and mu11().
double corecvs::EllipticalApproximation::mixedMoment
Definition at line 56 of file ellipticalApproximation.h.
Referenced by addPoint(), and mu11().
Vector2dd corecvs::EllipticalApproximation::sum
Definition at line 54 of file ellipticalApproximation.h.
Referenced by addPoint(), and getMean().
Vector2dd corecvs::EllipticalApproximation::sumSquares
Definition at line 55 of file ellipticalApproximation.h.
Referenced by addPoint(), and getMeanSquare().
The documentation for this class was generated from the following files:
core/geometry/ellipticalApproximation.h
core/geometry/ellipticalApproximation.cpp