DeepView: BackgroundFilterParameters Class Reference
BackgroundFilterParameters Class Reference
Background Filter Parameters Background Filter Parameters.
#include <backgroundFilterParameters.h>
Public Types
enum FieldId { THRESHOLD_ID, BACKGROUND_FILTER_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
int threshold () const
void setThreshold (int threshold)
template<class VisitorType >
void accept (VisitorType &visitor)
BackgroundFilterParameters ()
BackgroundFilterParameters (int threshold)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mThreshold
Section with variables.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, BackgroundFilterParameters &toSave)
Detailed Description
Background Filter Parameters Background Filter Parameters.
Definition at line 38 of file backgroundFilterParameters.h.
Member Enumeration Documentation
enum BackgroundFilterParameters::FieldId
Enumerator:
THRESHOLD_ID
BACKGROUND_FILTER_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file backgroundFilterParameters.h.
                 {
        THRESHOLD_ID,
        BACKGROUND_FILTER_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
BackgroundFilterParameters::BackgroundFilterParameters () [inline]
Definition at line 81 of file backgroundFilterParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
BackgroundFilterParameters::BackgroundFilterParameters (int threshold) [inline]
Definition at line 87 of file backgroundFilterParameters.h.
    {
        mThreshold = threshold;
    }
Member Function Documentation
template<class VisitorType > void BackgroundFilterParameters::accept (VisitorType & visitor) [inline]
Definition at line 76 of file backgroundFilterParameters.h.
Referenced by corecvs::BackgroundFilter::deserialize(), and corecvs::BackgroundFilter::serialize().
    {
        visitor.visit(mThreshold,                 static_cast<const IntField *>     (fields()[THRESHOLD_ID]));
    }
static const char* corecvs::BaseReflection< BackgroundFilterParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< BackgroundFilterParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< BackgroundFilterParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* BackgroundFilterParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 58 of file backgroundFilterParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< BackgroundFilterParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< BackgroundFilterParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< BackgroundFilterParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void BackgroundFilterParameters::print () [inline]
Definition at line 101 of file backgroundFilterParameters.h.
    {
        cout << *this;
    }
void BackgroundFilterParameters::setThreshold (int threshold) [inline]
Definition at line 68 of file backgroundFilterParameters.h.
    {
        mThreshold = threshold;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int BackgroundFilterParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file backgroundFilterParameters.cpp.
References corecvs::BaseReflection< BackgroundFilterParameters >::fields(), mThreshold, corecvs::BaseReflection< BackgroundFilterParameters >::naming(), and THRESHOLD_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Background Filter Parameters",
        "Background Filter Parameters",
        ""
    );
    fields().push_back(
        new IntField
        (
          BackgroundFilterParameters::THRESHOLD_ID,
          offsetof(BackgroundFilterParameters, mThreshold),
          100,
          "Threshold",
          "Threshold",
          "Threshold"
        )
    );
   return 0;
}
int BackgroundFilterParameters::threshold () const [inline]
Definition at line 62 of file backgroundFilterParameters.h.
Referenced by BackgroundFilterParametersControlWidget::setParameters().
    {
        return mThreshold;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, BackgroundFilterParameters & toSave) [friend]
Definition at line 94 of file backgroundFilterParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< BackgroundFilterParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int BackgroundFilterParameters::mThreshold
Section with variables.
Threshold Threshold
Definition at line 52 of file backgroundFilterParameters.h.
Referenced by corecvs::BackgroundFilter::operator()(), and staticInit().
Reflection corecvs::BaseReflection< BackgroundFilterParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/backgroundFilterParameters.h
core/xml/generated/backgroundFilterParameters.cpp