DeepView: corecvs::Matrix44 Class Reference
corecvs::Matrix44 Class Reference
This class is mostly for representing Projectrive Transformations in 3D.
#include <matrix44.h>
Public Types
typedef FixedVectorBase
< Matrix44, double, 16 > BaseClass
typedef double InnerElementType
typedef ReflectionHelper
< double >::Type ReflectionType
Public Member Functions
Matrix44 ()
Matrix44 (double d)
Constructs the 4 by 4 Matrix with the given diagonal element In terms of projective transform that will always be an identity matrix.
Matrix44 (const FixedVector< double, 16 > &data)
Matrix44 (double _a00, double _a01, double _a02, double _a03, double _a10, double _a11, double _a12, double _a13, double _a20, double _a21, double _a22, double _a23, double _a30, double _a31, double _a32, double _a33)
Matrix44 (const Matrix33 &_m, const Vector3dd &_shift=Vector3dd(0, 0, 0))
Constructs the matrix form linear part presented by Matrix33 and affine shift presented by Vector3dd.
double & a (int i, int j)
Geting Matrix element functions block.
const double & a (int i, int j) const
void transpose ()
Transposing the matrix.
Matrix44 transposed () const
Returning transposed matrix.
Matrix44 inverted () const
Terribly ineffective.
double det () const
double frobeniusNorm () const
Frobenius Norm
.
~Matrix44 ()
int size () const
double & operator[] (int n)
const double & operator[] (int n) const
double & at (int n)
const double & at (int n) const
Matrix44 createVector (int) const
Matrix44 * realThis ()
Static cast functions.
const Matrix44 * realThis () const
bool operator== (const Matrix44 &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const Matrix44 &that) const
Inequality operator.
bool notTooFar (const Matrix44 &that, const double &epsilon=double(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const Matrix44 &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const Matrix44 &V)
VectorOperationsBase & operator*= (const double &c)
VectorOperationsBase & operator/= (const double &c)
Matrix44 operator- () const
Negative operator.
double sumAllElements () const
Sum of the elements of the vector.
double mulAllElements () const
Product of all elements of the vector.
double sumAllElementsSq () const
Sum of the squares of element of the vector.
double l2Metric () const
Euclidean distance.
double operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
Matrix44 normalised () const
Return a normalized copy of vector.
Matrix44 cloneVector () const
Return copy of vector.
double l1Metric () const
Sum of the absolute values of element of the vector.
double lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
double minimum () const
double maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
void accept (VisitorType &visitor)
Static Public Member Functions
static Matrix44 ProjectParallelToZ ()
Constructs the 4 by 4 Matrix that projects to the plane Z == 1 If you are simulating camera you better use Intrinsic Parameters and reduction from projective coordinates to 2D.
static Matrix44 Shift (double x, double y, double z)
Constructs the matrix form affine shift.
static Matrix44 Shift (const Vector3dd &v)
static Matrix44 Scale (const double &d)
static Matrix44 Frustum (double fovY, double aspect, double zNear=1.0, double zFar=1000.0)
Public Attributes
double element [length]
Static Public Attributes
static const int H = 4
static const int W = H
static const int ELEM_NUM = H*W
static const int LENGTH
Friends
Matrix44 operator* (const Matrix44 &M1, const Matrix44 &M2)
Could use Strassen - http://en.wikipedia.org/wiki/Strassen_algorithm but stability is more valuable now.
Matrix44 operator*= (Matrix44 &M1, const Matrix44 &M2)
Matrix44 operator* (const Matrix44 &M1, const Matrix33 &M2)
This is in fact used only for 3D matrix convenience.
Matrix44 operator* (const Matrix33 &M1, const Matrix44 &M2)
Matrix44 operator*= (Matrix44 &M1, const Matrix33 &M2)
Vector3dd operator* (const Matrix44 &M1, const Vector3dd &v)
FixedVector< double, 4 > operator* (const Matrix44 &m, const FixedVector< double, 4 > &v)
ostream & operator<< (ostream &out, const Matrix44 &matrix)
istream & operator>> (istream &in, Matrix44 &matrix)
Matrix44 operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
Matrix44 operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
Matrix44 operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
Matrix44 operator* (const double &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
Matrix44 operator* (const VectorOperationsBase &V, const double &c)
Matrix44 operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
Matrix44 operator/ (const VectorOperationsBase &V, const double &c)
Operator * does the component-specific multiplication by constant
.
double operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
This class is mostly for representing Projectrive Transformations in 3D.
Definition at line 30 of file matrix44.h.
Member Typedef Documentation
typedef FixedVectorBase<Matrix44, double, 16> corecvs::Matrix44::BaseClass
Reimplemented from corecvs::FixedVectorBase< Matrix44, double, 16 >.
Definition at line 33 of file matrix44.h.
typedef double corecvs::FixedVectorBase< Matrix44 , double , length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<double >::Type corecvs::VectorOperationsBase< Matrix44 , double >::ReflectionType [inherited]
Definition at line 561 of file vectorOperations.h.
Constructor & Destructor Documentation
corecvs::Matrix44::Matrix44 ()
Definition at line 13 of file matrix44.cpp.
Referenced by Frustum(), inverted(), and transposed().
{
}
corecvs::Matrix44::Matrix44 (double d) [inline, explicit]
Constructs the 4 by 4 Matrix with the given diagonal element In terms of projective transform that will always be an identity matrix.
Definition at line 55 of file matrix44.h.
References a(), and H.
                                : BaseClass(0.0)
    {
        for (int i = 0; i < H; i++)
            a(i,i) = d;
    }
corecvs::Matrix44::Matrix44 (const FixedVector< double, 16 > & data) [inline]
Definition at line 61 of file matrix44.h.
                                                  : BaseClass(data)
    { }
corecvs::Matrix44::Matrix44 (double _a00, double _a01, double _a02, double _a03, double _a10, double _a11, double _a12, double _a13, double _a20, double _a21, double _a22, double _a23, double _a30, double _a31, double _a32, double _a33) [inline]
Definition at line 154 of file matrix44.h.
References a().
{
    a(0,0) = _a00;   a(0,1) = _a01;   a(0,2) = _a02;   a(0,3) = _a03;
    a(1,0) = _a10;   a(1,1) = _a11;   a(1,2) = _a12;   a(1,3) = _a13;
    a(2,0) = _a20;   a(2,1) = _a21;   a(2,2) = _a22;   a(2,3) = _a23;
    a(3,0) = _a30;   a(3,1) = _a31;   a(3,2) = _a32;   a(3,3) = _a33;
}
corecvs::Matrix44::Matrix44 (const Matrix33 & _matrix, const Vector3dd & _shift = Vector3dd(0,0,0)) [inline]
Constructs the matrix form linear part presented by Matrix33 and affine shift presented by Vector3dd.
Definition at line 183 of file matrix44.h.
References a(), corecvs::Matrix33::a(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
    a(0,0)  = _matrix.a(0,0);
    a(0,1)  = _matrix.a(0,1);
    a(0,2)  = _matrix.a(0,2);
    a(0,3)  = _shift.x();
    a(1,0)  = _matrix.a(1,0);
    a(1,1)  = _matrix.a(1,1);
    a(1,2)  = _matrix.a(1,2);
    a(1,3)  = _shift.y();
    a(2,0)  = _matrix.a(2,0);
    a(2,1)  = _matrix.a(2,1);
    a(2,2)  = _matrix.a(2,2);
    a(2,3)  = _shift.z();
    a(3,0)  = 0;
    a(3,1)  = 0;
    a(3,2)  = 0;
    a(3,3)  = 1;
}
corecvs::Matrix44::~Matrix44 ()
Definition at line 251 of file matrix44.cpp.
{
}
Member Function Documentation
double & corecvs::Matrix44::a (int i, int j) [inline]
Geting Matrix element functions block.
Definition at line 208 of file matrix44.h.
References W.
Referenced by Scene3D::commonSetup(), det(), corecvs::FCostFunction::function(), corecvs::FCostFunction::functionPro(), Scene3D::initDecalState(), inverted(), corecvs::Matrix::Matrix(), Matrix44(), corecvs::operator*(), Scale(), transpose(), and transposed().
{
   return (*this)[i * W + j];
}
const double & corecvs::Matrix44::a (int i, int j) const [inline]
Definition at line 213 of file matrix44.h.
References W.
{
   return (*this)[i * W + j];
}
void corecvs::VectorOperationsBase< Matrix44 , double >::accept (VisitorType & visitor) [inline, inherited]
Definition at line 578 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            const ReflectionType fieldDescriptor(i, defaultValue, name);
            visitor.visit(_at(i), &fieldDescriptor);
        }
    }
void corecvs::VectorOperationsBase< Matrix44 , double >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
double & corecvs::FixedVectorBase< Matrix44 , double , length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
    {
        return element[n];
    }
const double & corecvs::FixedVectorBase< Matrix44 , double , length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
Matrix44 corecvs::VectorOperationsBase< Matrix44 , double >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
Matrix44 corecvs::FixedVectorBase< Matrix44 , double , length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
double corecvs::Matrix44::det () const
Definition at line 240 of file matrix44.cpp.
References a().
Referenced by inverted().
{
   double det =
       a(0,3)*a(1,2)*a(2,1)*a(3,0) - a(0,2)*a(1,3)*a(2,1)*a(3,0) - a(0,3)*a(1,1)*a(2,2)*a(3,0) + a(0,1)*a(1,3)*a(2,2)*a(3,0)+
       a(0,2)*a(1,1)*a(2,3)*a(3,0) - a(0,1)*a(1,2)*a(2,3)*a(3,0) - a(0,3)*a(1,2)*a(2,0)*a(3,1) + a(0,2)*a(1,3)*a(2,0)*a(3,1)+
       a(0,3)*a(1,0)*a(2,2)*a(3,1) - a(0,0)*a(1,3)*a(2,2)*a(3,1) - a(0,2)*a(1,0)*a(2,3)*a(3,1) + a(0,0)*a(1,2)*a(2,3)*a(3,1)+
       a(0,3)*a(1,1)*a(2,0)*a(3,2) - a(0,1)*a(1,3)*a(2,0)*a(3,2) - a(0,3)*a(1,0)*a(2,1)*a(3,2) + a(0,0)*a(1,3)*a(2,1)*a(3,2)+
       a(0,1)*a(1,0)*a(2,3)*a(3,2) - a(0,0)*a(1,1)*a(2,3)*a(3,2) - a(0,2)*a(1,1)*a(2,0)*a(3,3) + a(0,1)*a(1,2)*a(2,0)*a(3,3)+
       a(0,2)*a(1,0)*a(2,1)*a(3,3) - a(0,0)*a(1,2)*a(2,1)*a(3,3) - a(0,1)*a(1,0)*a(2,2)*a(3,3) + a(0,0)*a(1,1)*a(2,2)*a(3,3);
   return det;
}
double corecvs::Matrix44::frobeniusNorm () const
Frobenius Norm
.
Definition at line 180 of file matrix44.cpp.
References corecvs::VectorOperationsBase< Matrix44, double >::sumAllElementsSq().
{
    return sqrt(sumAllElementsSq());
}
Matrix44 corecvs::Matrix44::Frustum (double fovY, double aspect, double zNear = 1.0, double zFar = 1000.0) [static]
Definition at line 79 of file matrix44.cpp.
References Matrix44().
{
    double f = 1.0 / tan(fovY / 2);
    double zDepth = zNear - zFar;
    return Matrix44 (
         f / aspect, 0 ,             0           ,            0            ,
         0         ,-f ,             0           ,            0            ,
         0         , 0 , -(zFar + zNear) / zDepth, 2 *zFar * zNear / zDepth,
         0         , 0 ,             1           ,            0
    );
}
Matrix44 corecvs::Matrix44::inverted () const
Terribly ineffective.
Definition at line 214 of file matrix44.cpp.
References a(), det(), and Matrix44().
Referenced by Scene3D::commonSetup(), corecvs::RectificationResult::getRectifiedProjectionLeft(), Scene3D::initDecalState(), and CloudViewDialog::resetCameraPos().
{
    Matrix44 toReturn = Matrix44 (
        a(1,2)*a(2,3)*a(3,1) - a(1,3)*a(2,2)*a(3,1) + a(1,3)*a(2,1)*a(3,2) - a(1,1)*a(2,3)*a(3,2) - a(1,2)*a(2,1)*a(3,3) + a(1,1)*a(2,2)*a(3,3),
        a(0,3)*a(2,2)*a(3,1) - a(0,2)*a(2,3)*a(3,1) - a(0,3)*a(2,1)*a(3,2) + a(0,1)*a(2,3)*a(3,2) + a(0,2)*a(2,1)*a(3,3) - a(0,1)*a(2,2)*a(3,3),
        a(0,2)*a(1,3)*a(3,1) - a(0,3)*a(1,2)*a(3,1) + a(0,3)*a(1,1)*a(3,2) - a(0,1)*a(1,3)*a(3,2) - a(0,2)*a(1,1)*a(3,3) + a(0,1)*a(1,2)*a(3,3),
        a(0,3)*a(1,2)*a(2,1) - a(0,2)*a(1,3)*a(2,1) - a(0,3)*a(1,1)*a(2,2) + a(0,1)*a(1,3)*a(2,2) + a(0,2)*a(1,1)*a(2,3) - a(0,1)*a(1,2)*a(2,3),
        a(1,3)*a(2,2)*a(3,0) - a(1,2)*a(2,3)*a(3,0) - a(1,3)*a(2,0)*a(3,2) + a(1,0)*a(2,3)*a(3,2) + a(1,2)*a(2,0)*a(3,3) - a(1,0)*a(2,2)*a(3,3),
        a(0,2)*a(2,3)*a(3,0) - a(0,3)*a(2,2)*a(3,0) + a(0,3)*a(2,0)*a(3,2) - a(0,0)*a(2,3)*a(3,2) - a(0,2)*a(2,0)*a(3,3) + a(0,0)*a(2,2)*a(3,3),
        a(0,3)*a(1,2)*a(3,0) - a(0,2)*a(1,3)*a(3,0) - a(0,3)*a(1,0)*a(3,2) + a(0,0)*a(1,3)*a(3,2) + a(0,2)*a(1,0)*a(3,3) - a(0,0)*a(1,2)*a(3,3),
        a(0,2)*a(1,3)*a(2,0) - a(0,3)*a(1,2)*a(2,0) + a(0,3)*a(1,0)*a(2,2) - a(0,0)*a(1,3)*a(2,2) - a(0,2)*a(1,0)*a(2,3) + a(0,0)*a(1,2)*a(2,3),
        a(1,1)*a(2,3)*a(3,0) - a(1,3)*a(2,1)*a(3,0) + a(1,3)*a(2,0)*a(3,1) - a(1,0)*a(2,3)*a(3,1) - a(1,1)*a(2,0)*a(3,3) + a(1,0)*a(2,1)*a(3,3),
        a(0,3)*a(2,1)*a(3,0) - a(0,1)*a(2,3)*a(3,0) - a(0,3)*a(2,0)*a(3,1) + a(0,0)*a(2,3)*a(3,1) + a(0,1)*a(2,0)*a(3,3) - a(0,0)*a(2,1)*a(3,3),
        a(0,1)*a(1,3)*a(3,0) - a(0,3)*a(1,1)*a(3,0) + a(0,3)*a(1,0)*a(3,1) - a(0,0)*a(1,3)*a(3,1) - a(0,1)*a(1,0)*a(3,3) + a(0,0)*a(1,1)*a(3,3),
        a(0,3)*a(1,1)*a(2,0) - a(0,1)*a(1,3)*a(2,0) - a(0,3)*a(1,0)*a(2,1) + a(0,0)*a(1,3)*a(2,1) + a(0,1)*a(1,0)*a(2,3) - a(0,0)*a(1,1)*a(2,3),
        a(1,2)*a(2,1)*a(3,0) - a(1,1)*a(2,2)*a(3,0) - a(1,2)*a(2,0)*a(3,1) + a(1,0)*a(2,2)*a(3,1) + a(1,1)*a(2,0)*a(3,2) - a(1,0)*a(2,1)*a(3,2),
        a(0,1)*a(2,2)*a(3,0) - a(0,2)*a(2,1)*a(3,0) + a(0,2)*a(2,0)*a(3,1) - a(0,0)*a(2,2)*a(3,1) - a(0,1)*a(2,0)*a(3,2) + a(0,0)*a(2,1)*a(3,2),
        a(0,2)*a(1,1)*a(3,0) - a(0,1)*a(1,2)*a(3,0) - a(0,2)*a(1,0)*a(3,1) + a(0,0)*a(1,2)*a(3,1) + a(0,1)*a(1,0)*a(3,2) - a(0,0)*a(1,1)*a(3,2),
        a(0,1)*a(1,2)*a(2,0) - a(0,2)*a(1,1)*a(2,0) + a(0,2)*a(1,0)*a(2,1) - a(0,0)*a(1,2)*a(2,1) - a(0,1)*a(1,0)*a(2,2) + a(0,0)*a(1,1)*a(2,2)
   );
   toReturn /= det();
   return toReturn;
}
bool corecvs::VectorOperationsBase< Matrix44 , double >::isInHypercube (const VectorOperationsBase< Matrix44, double > & low, const VectorOperationsBase< Matrix44, double > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
void corecvs::VectorOperationsBase< Matrix44 , double >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Definition at line 407 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
Matrix44 corecvs::VectorOperationsBase< Matrix44 , double >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Definition at line 420 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
bool corecvs::VectorOperationsBase< Matrix44 , double >::notTooFar (const Matrix44 & that, const double & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< Matrix44 , double >::operator!= (const Matrix44 & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix44 , double >::operator*= (const double & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix44 , double >::operator+= (const Matrix44 & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
Matrix44 corecvs::VectorOperationsBase< Matrix44 , double >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix44 , double >::operator-= (const Matrix44 & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix44 , double >::operator/= (const double & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< Matrix44 , double >::operator== (const Matrix44 & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
double & corecvs::FixedVectorBase< Matrix44 , double , length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
const double & corecvs::FixedVectorBase< Matrix44 , double , length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
void corecvs::VectorOperationsBase< Matrix44 , double >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< Matrix44 , double >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
Matrix44 corecvs::Matrix44::ProjectParallelToZ () [static]
Constructs the 4 by 4 Matrix that projects to the plane Z == 1 If you are simulating camera you better use Intrinsic Parameters and reduction from projective coordinates to 2D.
Definition at line 32 of file matrix44.cpp.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
{
   Matrix44 M;
   double *y = M.element;
   (*y++) =  1.0;  (*y++) =  0.0;  (*y++) =  0.0; (*y++) =  0.0;
   (*y++) =  0.0;  (*y++) =  1.0;  (*y++) =  0.0; (*y++) =  0.0;
   (*y++) =  0.0;  (*y++) =  0.0;  (*y++) =  1.0; (*y++) =  0.0;
   (*y++) =  0.0;  (*y++) =  0.0;  (*y++) =  1.0; (*y)   =  0.0;
   return M;
}
Matrix44 * corecvs::VectorOperationsBase< Matrix44 , double >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const Matrix44 * corecvs::VectorOperationsBase< Matrix44 , double >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
Matrix44 corecvs::Matrix44::Scale (const double & d) [static]
Definition at line 72 of file matrix44.cpp.
References a().
{
    Matrix44 result(d);
    result.a(3,3) = 1.0;
    return result;
}
Matrix44 corecvs::Matrix44::Shift (double x, double y, double z) [static]
Constructs the matrix form affine shift.
Definition at line 56 of file matrix44.cpp.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
Referenced by corecvs::RectificationResult::getRectifiedProjectionLeft(), and Shift().
{
    Matrix44 M;
    double *e = M.element;
    (*e++) =  1.0;  (*e++) =  0.0;  (*e++) =  0.0; (*e++) =  x;
    (*e++) =  0.0;  (*e++) =  1.0;  (*e++) =  0.0; (*e++) =  y;
    (*e++) =  0.0;  (*e++) =  0.0;  (*e++) =  1.0; (*e++) =  z;
    (*e++) =  0.0;  (*e++) =  0.0;  (*e++) =  0.0; (*e)   =  1.0;
    return M;
}
Matrix44 corecvs::Matrix44::Shift (const Vector3dd & v) [static]
Definition at line 67 of file matrix44.cpp.
References Shift(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
    return Shift(v.x(), v.y(), v.z());
}
int corecvs::FixedVectorBase< Matrix44 , double , length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
double corecvs::VectorOperationsBase< Matrix44 , double >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
Referenced by frobeniusNorm().
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
void corecvs::Matrix44::transpose ()
Transposing the matrix.
Definition at line 146 of file matrix44.cpp.
References a().
{
   double tmp;
   tmp = a(1,0); a(1,0) = a(0,1); a(0,1) = tmp;
   tmp = a(2,0); a(2,0) = a(0,2); a(0,2) = tmp;
   tmp = a(2,1); a(2,1) = a(1,2); a(1,2) = tmp;
   tmp = a(3,0); a(3,0) = a(0,3); a(0,3) = tmp;
   tmp = a(3,1); a(3,1) = a(1,3); a(1,3) = tmp;
   tmp = a(3,2); a(3,2) = a(2,3); a(2,3) = tmp;
}
Matrix44 corecvs::Matrix44::transposed () const
Returning transposed matrix.
Definition at line 162 of file matrix44.cpp.
References a(), and Matrix44().
Referenced by corecvs::FCostFunction::getBMatrix(), corecvs::FCostFunction::getMMatrix(), OpenGLTools::glMultMatrixMatrix44(), and Scene3D::initDecalState().
{
   return Matrix44(
       a(0,0), a(1,0), a(2,0), a(3,0),
       a(0,1), a(1,1), a(2,1), a(3,1),
       a(0,2), a(1,2), a(2,2), a(3,2),
       a(0,3), a(1,3), a(2,3), a(3,3)
   );
}
Friends And Related Function Documentation
double operator& (const VectorOperationsBase< Matrix44, double > & V1, const VectorOperationsBase< Matrix44, double > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
Matrix44 operator* (const Matrix44 & M1, const Matrix44 & M2) [friend]
Could use Strassen - http://en.wikipedia.org/wiki/Strassen_algorithm but stability is more valuable now.
49 multiplications instead of 64
Definition at line 98 of file matrix44.cpp.
{
    Matrix44 result;
    int row, column, runner;
    for (row = 0; row < Matrix44::H ; row++)
    {
        for (column = 0; column < Matrix44::W ; column++)
        {
            double sum = 0;
            for (runner = 0; runner < Matrix44::H ; runner++)
            {
                sum += M1.a(row, runner) * M2.a(runner, column);
            }
            result.a(row, column) = sum;
        }
    }
    return result;
}
Matrix44 operator* (const Matrix44 & M1, const Matrix33 & M2) [friend]
This is in fact used only for 3D matrix convenience.
Definition at line 121 of file matrix44.cpp.
{
    return M1 * Matrix44(M2);
}
Matrix44 operator* (const Matrix33 & M1, const Matrix44 & M2) [friend]
Definition at line 126 of file matrix44.cpp.
{
    return Matrix44(M1) * M2;
}
Vector3dd operator* (const Matrix44 & M1, const Vector3dd & v) [friend]
Definition at line 195 of file matrix44.cpp.
{
    FixedVector<double, 4> v4;
    v4[0] = v.x();
    v4[1] = v.y();
    v4[2] = v.z();
    v4[3] = 1.0;
    FixedVector<double, 4> r = m * v4;
    return Vector3dd(r[0],r[1],r[2]) / r[3];
}
FixedVector<double, 4> operator* (const Matrix44 & m, const FixedVector< double, 4 > & v) [friend]
Definition at line 185 of file matrix44.cpp.
{
    FixedVector<double, 4> toReturn;
    toReturn[0] = v[0] * m.a(0,0) + v[1] * m.a(0,1) + v[2] * m.a(0,2) + m.a(0,3) * v[3];
    toReturn[1] = v[0] * m.a(1,0) + v[1] * m.a(1,1) + v[2] * m.a(1,2) + m.a(1,3) * v[3];
    toReturn[2] = v[0] * m.a(2,0) + v[1] * m.a(2,1) + v[2] * m.a(2,2) + m.a(2,3) * v[3];
    toReturn[3] = v[0] * m.a(3,0) + v[1] * m.a(3,1) + v[2] * m.a(3,2) + m.a(3,3) * v[3];
    return toReturn;
}
Matrix44 operator* (const VectorOperationsBase< Matrix44, double > & V1, const VectorOperationsBase< Matrix44, double > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
Matrix44 operator* (const double & c, const VectorOperationsBase< Matrix44, double > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
Matrix44 operator* (const VectorOperationsBase< Matrix44, double > & V, const double & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
Matrix44 operator*= (Matrix44 & M1, const Matrix44 & M2) [friend]
Definition at line 131 of file matrix44.cpp.
{
    M1 = M1 * M2;
    return M1;
}
Matrix44 operator*= (Matrix44 & M1, const Matrix33 & M2) [friend]
Definition at line 137 of file matrix44.cpp.
{
    M1 = M1 * M2;
    return M1;
}
Matrix44 operator+ (const VectorOperationsBase< Matrix44, double > & V1, const VectorOperationsBase< Matrix44, double > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
Matrix44 operator- (const VectorOperationsBase< Matrix44, double > & V1, const VectorOperationsBase< Matrix44, double > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
Matrix44 operator/ (const VectorOperationsBase< Matrix44, double > & V1, const VectorOperationsBase< Matrix44, double > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
Matrix44 operator/ (const VectorOperationsBase< Matrix44, double > & V, const double & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const Matrix44 & matrix) [friend]
Definition at line 108 of file matrix44.h.
    {
        streamsize wasPrecision = out.precision(6);
        for (int i = 0; i < matrix.H; i++)
        {
            out << "[";
            for (int j = 0; j < matrix.W; j++)
            {
                out << (j == 0 ? "" : " ");
                out.width(6);
                out << matrix.a(i,j);
            }
            out << "]\n";
        }
        out.precision(wasPrecision);
        return out;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< Matrix44, double > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, Matrix44 & matrix) [friend]
Definition at line 126 of file matrix44.h.
       {
           for (int i = 0; i < matrix.H; i++)
           {
               for (int j = 0; j < matrix.W; j++)
               {
                   while (true)
                   {
                       in >> matrix.a(i,j);
                       // cout << "Read:" << i << "," << j << " " << matrix.a(i,j) << endl;
                       if (in.good())
                           break;
                       if (in.eof())
                           return in;
                       /* Not a number clean the error and advance*/
                       in.clear();
                       // cout << "Skipped:" << ((char)in.peek()) << endl;
                       in.ignore();
                   }
               }
           }
           return in;
       }
istream& operator>> (istream & in, VectorOperationsBase< Matrix44, double > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
Member Data Documentation
const int corecvs::Matrix44::ELEM_NUM = H*W [static]
Definition at line 37 of file matrix44.h.
double corecvs::FixedVectorBase< Matrix44 , double , length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
const int corecvs::Matrix44::H = 4 [static]
Definition at line 35 of file matrix44.h.
Referenced by corecvs::Matrix::Matrix(), Matrix44(), and corecvs::operator*().
const int corecvs::FixedVectorBase< Matrix44 , double , length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
const int corecvs::Matrix44::W = H [static]
Definition at line 36 of file matrix44.h.
Referenced by a(), corecvs::Matrix::Matrix(), and corecvs::operator*().
The documentation for this class was generated from the following files:
core/math/matrix/matrix44.h
core/math/matrix/matrix44.cpp