DeepView: Draw3dParametersControlWidget Class Reference
Draw3dParametersControlWidget Class Reference
#include <draw3dParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
Draw3dParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~Draw3dParametersControlWidget ()
Draw3dParameters * createParameters () const
void setParameters (const Draw3dParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_Draw3dParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file draw3dParametersControlWidget.h.
Constructor & Destructor Documentation
Draw3dParametersControlWidget::Draw3dParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 17 of file draw3dParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::Draw3dParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->styleComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->colorControlWidget, SIGNAL(paramsChanged()), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->secondaryColorControlWidget, SIGNAL(paramsChanged()), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->textureCorrodinatesComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->textureAlphaSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->textureScaleSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalMatrixTypeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalLeftCamCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalLeftAlphaSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalRightCamCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->decalRightAlphaSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
Draw3dParametersControlWidget::~Draw3dParametersControlWidget ()
Definition at line 38 of file draw3dParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void Draw3dParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file draw3dParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
Draw3dParameters * Draw3dParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 60 of file draw3dParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    RgbColorParameters *tmp1 = NULL;
    RgbColorParameters *tmp2 = NULL;
    Draw3dParameters *result = new Draw3dParameters(
          static_cast<Draw3dStyle::Draw3dStyle>(mUi->styleComboBox->currentIndex())
        , * (tmp1 = mUi->colorControlWidget->createParameters())
        , * (tmp2 = mUi->secondaryColorControlWidget->createParameters())
        , static_cast<Draw3dTextureGen::Draw3dTextureGen>(mUi->textureCorrodinatesComboBox->currentIndex())
        , mUi->textureAlphaSpinBox->value()
        , mUi->textureScaleSpinBox->value()
        , mUi->decalMatrixTypeSpinBox->value()
        , mUi->decalLeftCamCheckBox->isChecked()
        , mUi->decalLeftAlphaSpinBox->value()
        , mUi->decalRightCamCheckBox->isChecked()
        , mUi->decalRightAlphaSpinBox->value()
    );
    delete tmp1;
    delete tmp2;
    return result;
}
virtual BaseReflectionStatic* Draw3dParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from ParametersControlWidgetBase.
Definition at line 25 of file draw3dParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void Draw3dParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 44 of file draw3dParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    Draw3dParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void Draw3dParametersControlWidget::paramsChanged () [signal]
Referenced by Draw3dParametersControlWidget(), and setParameters().
void Draw3dParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 52 of file draw3dParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    Draw3dParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void Draw3dParametersControlWidget::setParameters (const Draw3dParameters & input)
Definition at line 88 of file draw3dParametersControlWidget.cpp.
References Draw3dParameters::color(), Draw3dParameters::decalLeftAlpha(), Draw3dParameters::decalLeftCam(), Draw3dParameters::decalMatrixType(), Draw3dParameters::decalRightAlpha(), Draw3dParameters::decalRightCam(), mUi, paramsChanged(), Draw3dParameters::secondaryColor(), Draw3dParameters::style(), Draw3dParameters::textureAlpha(), Draw3dParameters::textureCorrodinates(), and Draw3dParameters::textureScale().
Referenced by CoordinateFrame::getContolWidget(), Mesh3DScene::getContolWidget(), loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->styleComboBox->setCurrentIndex(input.style());
    mUi->colorControlWidget->setParameters(input.color());
    mUi->secondaryColorControlWidget->setParameters(input.secondaryColor());
    mUi->textureCorrodinatesComboBox->setCurrentIndex(input.textureCorrodinates());
    mUi->textureAlphaSpinBox->setValue(input.textureAlpha());
    mUi->textureScaleSpinBox->setValue(input.textureScale());
    mUi->decalMatrixTypeSpinBox->setValue(input.decalMatrixType());
    mUi->decalLeftCamCheckBox->setChecked(input.decalLeftCam());
    mUi->decalLeftAlphaSpinBox->setValue(input.decalLeftAlpha());
    mUi->decalRightCamCheckBox->setChecked(input.decalRightCam());
    mUi->decalRightAlphaSpinBox->setValue(input.decalRightAlpha());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void Draw3dParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 107 of file draw3dParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    Draw3dParameters *inputCasted = static_cast<Draw3dParameters *>(input);
    setParameters(*inputCasted);
}
void Draw3dParametersControlWidget::valueChanged () [signal]
Referenced by Draw3dParametersControlWidget().
Member Data Documentation
bool Draw3dParametersControlWidget::autoInit [private]
Definition at line 45 of file draw3dParametersControlWidget.h.
Ui_Draw3dParametersControlWidget* Draw3dParametersControlWidget::mUi [private]
Definition at line 44 of file draw3dParametersControlWidget.h.
Referenced by createParameters(), Draw3dParametersControlWidget(), setParameters(), and ~Draw3dParametersControlWidget().
QString Draw3dParametersControlWidget::rootPath [private]
Definition at line 46 of file draw3dParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/3d/draw3dParametersControlWidget.h
utils/3d/generated/draw3dParametersControlWidget.cpp