DeepView: corecvs::BufferFactory Class Reference
corecvs::BufferFactory Class Reference
Singleton for buffer loading.
#include <bufferFactory.h>
Public Member Functions
bool registerLoader (BufferLoader< G12Buffer > *loader)
Public function to add own buffer loader, i.e.
virtual G12Buffer * loadG12Bitmap (string name)
Main function to get a 12-bits buffer from the file with the given path name.
virtual G12Buffer * loadG16Bitmap (string name)
Main function to get a 16-bits buffer from the file with the given path name.
Static Public Member Functions
static BufferFactory * getInstance ()
Public function to get the only one instance of this object.
Private Member Functions
BufferFactory ()
virtual ~BufferFactory ()
Private Attributes
vector< BufferLoader
< G12Buffer > * > mLoaders
List of loaders - the supported formats.
Static Private Attributes
static CountedPtr< BufferFactory > sThis
Friends
class CountedPtr< BufferFactory >
Detailed Description
Singleton for buffer loading.
Definition at line 25 of file bufferFactory.h.
Constructor & Destructor Documentation
corecvs::BufferFactory::BufferFactory () [inline, private]
Definition at line 52 of file bufferFactory.h.
{}
corecvs::BufferFactory::~BufferFactory () [private, virtual]
Definition at line 104 of file bufferFactory.cpp.
References mLoaders.
{
    // delete all registered loaders
    vector<BufferLoader<G12Buffer> *>::iterator it;
    for (it = mLoaders.begin(); it != mLoaders.end(); it++)
    {
        delete_safe (*it);
    }
    mLoaders.clear();
    //printf("BufferFactory has been destroyed.\n");
}
Member Function Documentation
BufferFactory * corecvs::BufferFactory::getInstance () [static]
Public function to get the only one instance of this object.
It will be automatically destroyed on shut down.
Definition at line 19 of file bufferFactory.cpp.
References ASSERT_TRUE, CountedPtr< T >::get(), mLoaders, registerLoader(), and sThis.
{
    ASSERT_TRUE(sThis.get() != NULL, "Out of memory!");
    if (sThis.get()->mLoaders.size() == 0)
    {
        sThis.get()->registerLoader(new PPMLoader());
        sThis.get()->registerLoader(new RAWLoader());
        sThis.get()->registerLoader(new BMPLoader());
    }
    return sThis.get();
}
G12Buffer * corecvs::BufferFactory::loadG12Bitmap (string name) [virtual]
Main function to get a 12-bits buffer from the file with the given path name.
Definition at line 32 of file bufferFactory.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::load(), and mLoaders.
{
    vector<BufferLoader<G12Buffer> *>::iterator it;
    for (it = mLoaders.begin(); it != mLoaders.end(); it++)
    {
        if (!((*it)->acceptsFile(name)))
            continue;
        G12Buffer *result = (*it)->load(name);
        if (result != NULL)
            return result;
    }
    return NULL;
}
G12Buffer * corecvs::BufferFactory::loadG16Bitmap (string name) [virtual]
Main function to get a 16-bits buffer from the file with the given path name.
Definition at line 48 of file bufferFactory.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), and corecvs::PPMLoader::g16BufferCreateFromPPM().
{
    if (name.rfind(".pgm") != string::npos)
    {
        return PPMLoader().g16BufferCreateFromPPM(name);
    }
    G12Buffer *result = NULL;
    FILE *In = NULL;
    uint32_t h = 0;
    uint32_t w = 0;
    uint16_t d = 0;
    int read = 0;
    In = fopen(name.c_str(), "rb");
    if (In == NULL)
    {
        goto exit;
    }
    read = fread(&h, sizeof(uint32_t), 1, In);
    if (read != 1) {
        goto exit;
    }
    read = fread(&w, sizeof(uint32_t), 1, In);
    if (read != 1)
    {
        goto exit;
    }
    if (h > 2000 || w > 2000)
    {
        goto exit;
    }
    result = new G12Buffer(h,w);
    for (uint32_t i = 0; i < h; ++i) {
        for (uint32_t j = 0; j < w; ++j) {
            read = fread(&d, sizeof(uint16_t), 1, In);
            if (read != 1)
            {
                goto exit;
            }
            result->element(i,j) = d;
        }
    }
exit:
    if (In != NULL)
    {
        fclose(In);
    }
    return result;
}
bool corecvs::BufferFactory::registerLoader (BufferLoader< G12Buffer > * loader) [inline]
Public function to add own buffer loader, i.e.
QtFileLoader
Definition at line 35 of file bufferFactory.h.
References mLoaders.
Referenced by getInstance().
    {
        mLoaders.push_back(loader);
        return true;
    }
Friends And Related Function Documentation
friend class CountedPtr< BufferFactory > [friend]
Definition at line 51 of file bufferFactory.h.
Member Data Documentation
vector<BufferLoader<G12Buffer> *> corecvs::BufferFactory::mLoaders [private]
List of loaders - the supported formats.
Definition at line 60 of file bufferFactory.h.
Referenced by getInstance(), loadG12Bitmap(), registerLoader(), and ~BufferFactory().
CountedPtr< BufferFactory > corecvs::BufferFactory::sThis [static, private]
Definition at line 55 of file bufferFactory.h.
Referenced by getInstance().
The documentation for this class was generated from the following files:
core/buffers/bufferFactory.h
core/buffers/bufferFactory.cpp