DeepView: corecvs::EssentialMatrix Class Reference
corecvs::EssentialMatrix Class Reference
Both essential and fundamental matrices hold the following property:
#include <essentialMatrix.h>
Public Types
typedef FixedVectorBase
< Matrix33, double, 9 > BaseClass
typedef double InnerElementType
typedef ReflectionHelper
< double >::Type ReflectionType
Public Member Functions
EssentialMatrix ()
EssentialMatrix (const Matrix33 &other)
double epipolarDistance (const Vector2dd &right, const Vector2dd &left) const
The inliers calculation is as follows:
.
double epipolarDistance (const Correspondance &data) const
Matrix33 criteriaMatrix () const
double quality () const
void decompose (Matrix33 &R, Vector3dd &t)
Calculating decomposition of essential matrix E in form
.
void decompose (Matrix33 &R, Matrix33 &R1, Vector3dd &t)
void decompose (Matrix33 rot[4], Vector3dd trans[4])
void decompose (EssentialDecomposition decomposition[4])
void nullspaces (Vector3dd *leftNullspace, Vector3dd *rightNullspace)
Calculating vectors for left and right nullspaces of the 3 by 3 matrix of rank 2.
void assertRank2 ()
This function approximates the input matrix with rank 2 matrix to remove the noise form Fundamental Matrix.
void projectToEssential ()
void invert ()
Invertion of the matrix inplace.
Matrix33 inv ()
This function returns an inverse of the matrix.
double trace () const
Computing the trace of the matrix.
double det ()
Computing determinant of the matrix.
double & a (int i, int j)
Geting Matrix element functions block.
const double & a (int i, int j) const
void transpose ()
Transposing the matrix.
void swapRows (int r1, int r2)
void swapColumns (int r1, int r2)
Matrix33 transposed () const
Returning transposed matrix.
void neg ()
Vector3dd aV (int i) const
Get the i-th row vector.
Vector3dd aW (int i) const
Get the i-th column vector.
Vector3dd diagonal () const
Get the diagonal vector.
double frobeniusNorm () const
VectorOperationsBase & operator*= (const double &c)
Vector3dd mulBy2dRight (const Vector2dd &V) const
We expect that * 1.0 will be optimized out.
Vector3dd mulBy2dLeft (const Vector2dd &V) const
void print () const
void serialise (ostream &out) const
int size () const
double & operator[] (int n)
const double & operator[] (int n) const
double & at (int n)
const double & at (int n) const
Matrix33 createVector (int) const
Matrix33 * realThis ()
Static cast functions.
const Matrix33 * realThis () const
bool operator== (const Matrix33 &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const Matrix33 &that) const
Inequality operator.
bool notTooFar (const Matrix33 &that, const double &epsilon=double(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const Matrix33 &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const Matrix33 &V)
VectorOperationsBase & operator/= (const double &c)
Matrix33 operator- () const
Negative operator.
double sumAllElements () const
Sum of the elements of the vector.
double mulAllElements () const
Product of all elements of the vector.
double sumAllElementsSq () const
Sum of the squares of element of the vector.
double l2Metric () const
Euclidean distance.
double operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
Matrix33 normalised () const
Return a normalized copy of vector.
Matrix33 cloneVector () const
Return copy of vector.
double l1Metric () const
Sum of the absolute values of element of the vector.
double lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void println () const
double minimum () const
double maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
void accept (VisitorType &visitor)
Static Public Member Functions
static EssentialMatrix compose (const Matrix33 &R, const Vector3dd &t)
Returns the essential matrix based on the rotation and the shift of the camera
.
static Matrix33 RotationX (double angle)
Creates a 3D rotation matrix over the Y axis by the angle alpha.
static Matrix33 RotationY (double angle)
Creates a 3D rotation matrix over the Y axis by the angle alpha.
static Matrix33 RotationZ (double angle)
Creates a 2D projective transform for the rotation by the angle alpha or a 3d rotation transform.
static Matrix33 RotationZ90 ()
static Matrix33 RotationZ180 ()
static Matrix33 RotationZ270 ()
static Matrix33 RotateProj (double angle)
static Matrix33 Rotate (const Vector3dd &v, double angle)
static Matrix33 MirrorXY ()
static Matrix33 MirrorYZ ()
static Matrix33 MirrorXZ ()
static Matrix33 Scale3 (const Vector3dd &v)
static Matrix33 Scale3 (double v)
static Matrix33 Scale2 (double x, double y)
This function returns a matrix with only 2 scale components.
static Matrix33 Scale2 (const Vector2dd &v)
static Matrix33 Scale2 (double v)
static Matrix33 ScaleProj (double v)
static Matrix33 ShiftProj (double x, double y)
This function returns a matrix with only shift components.
static Matrix33 ShiftProj (const Vector2dd &v)
static Matrix33 Projective (double x, double y)
This function returns a matrix with only the projective components.
static Matrix33 Projective (const Vector2dd &v)
static Matrix33 CrossProductRight (const Vector3dd &vector)
Produce matrix that is equal to vector product with the given vector on the right.
static Matrix33 CrossProductLeft (const Vector3dd &vector)
Produce matrix that is equal to vector product with the given vector to the left.
static Matrix33 VectorByVector (const Vector3dd &a, const Vector3dd &b)
This function returns a matrix constucted as a product of two vectors .
static Matrix33 FromRows (const Vector3dd &a, const Vector3dd &b, const Vector3dd &c)
Synonym to Matrix33(const Vector3dd& _V1,const Vector3dd& _V2,const Vector3dd& _V3)
static Matrix33 FromColumns (const Vector3dd &a, const Vector3dd &b, const Vector3dd &c)
Matrix construction via 3 columns.
static Matrix33 ProjectiveByPoints (Vector2dd points[4], Vector2dd images[4])
Calculate the Matrix that transform given points to given images This is done almost the same way as in rectification Rectificator::getFundamantalRansac() using the SVD.
static Matrix33 ProjectiveByPoints (int pointNumber, Vector2dd points[], Vector2dd images[])
Get the best transformation for a set of points.
Public Attributes
double element [length]
Static Public Attributes
static const int H = 3
static const int W = H
static const int ELEM_NUM = H*W
static const int LENGTH
Friends
Matrix33 operator* (const Matrix33 &M1, const Matrix33 &M2)
Negating the matrix - all elements are replaced with their negative values.
Vector3dd operator* (const Matrix33 &matrix, const Vector3dd &V)
Vector by Matrix left multiplication .
Vector3dd operator* (const Vector3dd &V, const Matrix33 &matrix)
Vector by Matrix right multiplication .
Vector2dd operator* (const Matrix33 &matrix, const Vector2dd &V)
Apply projective transformation to 2D vector
.
Vector2dd operator* (const Vector2dd &V, const Matrix33 &matrix)
Apply projective transformation to 2D vector (vector is form the right)
.
Matrix33 operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
Matrix33 operator* (const double &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
Matrix33 operator* (const VectorOperationsBase &V, const double &c)
Matrix33 operator*= (Matrix33 &M1, const Matrix33 &M2)
ostream & operator<< (ostream &out, const Matrix33 &matrix)
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, Matrix33 &matrix)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Matrix33 operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
Matrix33 operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
Matrix33 operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
Matrix33 operator/ (const VectorOperationsBase &V, const double &c)
Operator * does the component-specific multiplication by constant
.
double operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
Detailed Description
Both essential and fundamental matrices hold the following property:
             [ a_11   a_12  a_13 ]  [ x']    [ 0 ]
 [x, y ,1]   [ a_21   a_22  a_23 ]  [ y'] =  [ 0 ]
             [ a_31   a_32  a_33 ]  [ 1 ]    [ 0 ]
In case of Fundamental matrix is a point in the image captured by uncalibrated camera. In case of Essential Matrix is a point captured by normalized camera
Definition at line 216 of file essentialMatrix.h.
Member Typedef Documentation
typedef FixedVectorBase<Matrix33, double, 9> corecvs::Matrix33::BaseClass [inherited]
Reimplemented from corecvs::FixedVectorBase< Matrix33, double, 9 >.
Definition at line 51 of file matrix33.h.
typedef double corecvs::FixedVectorBase< Matrix33 , double , length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<double >::Type corecvs::VectorOperationsBase< Matrix33 , double >::ReflectionType [inherited]
Definition at line 561 of file vectorOperations.h.
Constructor & Destructor Documentation
corecvs::EssentialMatrix::EssentialMatrix () [inline]
Definition at line 219 of file essentialMatrix.h.
: Matrix33(Matrix33::CrossProductLeft(Vector3dd(1.0,0.0,0.0))) {};
corecvs::EssentialMatrix::EssentialMatrix (const Matrix33 & other) [inline]
Definition at line 220 of file essentialMatrix.h.
: Matrix33(other) {};
Member Function Documentation
double & corecvs::Matrix33::a (int i, int j) [inline, inherited]
Geting Matrix element functions block.
Definition at line 246 of file matrix33.h.
References corecvs::Matrix33::W.
Referenced by assertRank2(), corecvs::Matrix33::aV(), corecvs::Matrix33::aW(), decompose(), corecvs::Matrix33::det(), corecvs::Matrix33::diagonal(), corecvs::GenericQuaternion< ElementType >::FromMatrix(), corecvs::StereoAligner::getAlignmentTransformation(), corecvs::EssentialEstimator::getEssentialLSE(), corecvs::Matrix33::inv(), corecvs::Matrix::Matrix(), corecvs::Matrix33::Matrix33(), corecvs::Matrix44::Matrix44(), corecvs::operator*(), projectToEssential(), corecvs::Matrix33::swapColumns(), corecvs::Matrix33::swapRows(), corecvs::Matrix33::trace(), corecvs::Matrix33::transpose(), and corecvs::Matrix33::transposed().
{
   return (*this)[i * W + j];
}
const double & corecvs::Matrix33::a (int i, int j) const [inline, inherited]
Definition at line 251 of file matrix33.h.
References corecvs::Matrix33::W.
{
   return (*this)[i * W + j];
}
void corecvs::VectorOperationsBase< Matrix33 , double >::accept (VisitorType & visitor) [inline, inherited]
Definition at line 578 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            const ReflectionType fieldDescriptor(i, defaultValue, name);
            visitor.visit(_at(i), &fieldDescriptor);
        }
    }
void corecvs::VectorOperationsBase< Matrix33 , double >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
void corecvs::EssentialMatrix::assertRank2 () [inline]
This function approximates the input matrix with rank 2 matrix to remove the noise form Fundamental Matrix.
The algorithm is - decompose the F matrix with SVD. Take the smallest singular value and replace it with 0
Definition at line 521 of file essentialMatrix.h.
References corecvs::Matrix33::a(), corecvs::FixedVectorBase< Matrix33, double, 9 >::LENGTH, corecvs::VectorOperationsBase< RealType, ElementType >::print(), corecvs::Matrix::svd(), corecvs::Matrix33::transpose(), and corecvs::Matrix33::W.
Referenced by corecvs::ModelFundamental8Point::ModelFundamental8Point().
    {
        Vector3dd W;
        Matrix33  V;
        Matrix::svd(this, &W, &V);
    #ifdef TRACE
            printf("The singular values:\n");
            W.print();
            printf("\n");
    #endif
        // Leave out the last singular number. To assert that rank is 2
        int mini = -1;
        double minval = numeric_limits<double>::max();
        // is it needed here?
//        unsigned max = -1;
        double maxval = numeric_limits<double>::min();
        for (int i = 0; i < Vector3dd::LENGTH; i ++)
        {
            double w = W[i];
            if (w <= minval)
            {
                mini = i;
                minval = w;
            }
            if (w >= maxval)
            {
//                max = i;
                maxval = w;
            }
        }
        Matrix33 Wbig(0.0);
        for (int i = 0; i < Vector3dd::LENGTH; i++)
        {
            if (i != mini)
                Wbig.a(i, i) = (W[i] / maxval);
        }
        V.transpose();
        *this = *this * Wbig * V;
    }
double & corecvs::FixedVectorBase< Matrix33 , double , length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
    {
        return element[n];
    }
const double & corecvs::FixedVectorBase< Matrix33 , double , length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
Vector3dd corecvs::Matrix33::aV (int i) const [inherited]
Get the i-th row vector.
Definition at line 200 of file matrix33.cpp.
References corecvs::Matrix33::a().
{
    return Vector3dd (a(i,0), a(i,1), a(i,2));
}
Vector3dd corecvs::Matrix33::aW (int i) const [inherited]
Get the i-th column vector.
Definition at line 209 of file matrix33.cpp.
References corecvs::Matrix33::a().
Referenced by nullspaces().
{
    return Vector3dd (a(0,i), a(1,i), a(2,i));
}
Matrix33 corecvs::VectorOperationsBase< Matrix33 , double >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
static EssentialMatrix corecvs::EssentialMatrix::compose (const Matrix33 & R, const Vector3dd & t) [inline, static]
Returns the essential matrix based on the rotation and the shift of the camera
.
Definition at line 297 of file essentialMatrix.h.
References corecvs::Matrix33::CrossProductLeft().
Referenced by corecvs::EssentialEstimator::CostFunctionBase::getEssential().
    {
        return Matrix33::CrossProductLeft(t) * R;
    }
Matrix33 corecvs::FixedVectorBase< Matrix33 , double , length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
Matrix33 corecvs::EssentialMatrix::criteriaMatrix () const [inline]
Definition at line 274 of file essentialMatrix.h.
References corecvs::Matrix33::trace(), and corecvs::Matrix33::transposed().
Referenced by quality().
    {
        Matrix33 &E = *(Matrix33 *)this;
        Matrix33 ET = E.transposed();
        Matrix33 EET = E * ET;
        return (2 * EET * E) - E * EET.trace();
    }
Matrix33 corecvs::Matrix33::CrossProductLeft (const Vector3dd & vector) [static, inherited]
Produce matrix that is equal to vector product with the given vector to the left.
Definition at line 504 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by compose(), and corecvs::Matrix33::CrossProductRight().
{
    return Matrix33(
               0.0, -vector.z(),  vector.y(),
        vector.z(),         0.0, -vector.x(),
       -vector.y(),  vector.x(),         0.0
       );
}
Matrix33 corecvs::Matrix33::CrossProductRight (const Vector3dd & vector) [static, inherited]
Produce matrix that is equal to vector product with the given vector on the right.
Definition at line 491 of file matrix33.cpp.
References corecvs::Matrix33::CrossProductLeft().
{
    return Matrix33::CrossProductLeft(-vector);
}
void corecvs::EssentialMatrix::decompose (Matrix33 & R, Vector3dd & t) [inline]
Calculating decomposition of essential matrix E in form
.
where is the left cross product of vector in matrix form:
and . R is rotation matrix. We use SVD decomposition to compute and R from E: An SVD of E gives
where U and V are orthogonal matrices and is a diagonal matrix with
The diagonal entries of are the singular values of E which, according to the internal constraints of the essential matrix, must consist of two identical and one zero value. Define
with and make the following:
For more information you can see http://en.wikipedia.org/wiki/Essential_matrix But there decomposition not the same, as we have.
Definition at line 341 of file essentialMatrix.h.
References corecvs::Matrix33::a(), corecvs::Matrix33::Scale3(), corecvs::Matrix::svdDesc(), corecvs::Matrix33::transposed(), and corecvs::Matrix33::W.
Referenced by decompose(), and UniversalRectifier::decomposeEssential().
    {
        Matrix33 W(
                0.0, -1.0, 0.0,
                1.0,  0.0, 0.0,
                0.0,  0.0, 1.0
        );
        Matrix33 WT(W.transposed());
        Matrix33  U = *this;
        Vector3dd vS;
        Matrix33  V;
        Matrix::svdDesc(&U, &vS, &V);
        Matrix33 S = Matrix33::Scale3(vS);
        Matrix33 VT = V.transposed();
        Matrix33 UT = U.transposed();
        R = U * WT * VT;
        Matrix33 T = U * S * W * UT;
    #ifdef TRACE
        cout << "WS:" << endl << vS << endl;
        cout << "====================================" << endl;
        cout << "V :" << V << endl;
        cout << "VT:" << VT << endl;
        cout << "WS:" << W * S << endl;
        cout << "====================================" << endl;
        cout << "T :" << T << endl;
        cout << "ER:" << R * T << endl;
    #endif
        t = Vector3dd(
                T.a(2,1) - T.a(1,2),
                T.a(0,2) - T.a(2,0),
                T.a(1,0) - T.a(0,1)) / 2.0;
    }
void corecvs::EssentialMatrix::decompose (Matrix33 & R, Matrix33 & R1, Vector3dd & t) [inline]
Definition at line 379 of file essentialMatrix.h.
References corecvs::Matrix33::a(), corecvs::Matrix33::det(), corecvs::Matrix33::Scale3(), corecvs::Matrix::svdDesc(), corecvs::Matrix33::transposed(), and corecvs::Matrix33::W.
    {
        Matrix33 W(
                0.0, -1.0, 0.0,
                1.0,  0.0, 0.0,
                0.0,  0.0, 1.0
        );
        Matrix33 WT(W.transposed());
        Matrix33  U = *this;
        Vector3dd vS;
        Matrix33  V;
        Matrix::svdDesc(&U, &vS, &V);
        Matrix33 S = Matrix33::Scale3(vS);
        Matrix33 VT = V.transposed();
        Matrix33 UT = U.transposed();
                 R  = U * WT * VT;
                 R1 = U * W  * VT;
        Matrix33 T  = U * S * W * UT;
    #ifdef TRACE
        cout << "U :" << U.det() << endl << U << endl;
        cout << "WS:" << endl << vS << endl;
        cout << "V :" << V.det() << endl << V << endl;
        cout << "====================================" << endl;
        cout << "VT:" << VT << endl;
        cout << "WS:" << W * S << endl;
        cout << "====================================" << endl;
        cout << "T :" << T << endl;
        cout << "ER:" << R * T << endl;
    #endif
        t = Vector3dd(
                T.a(2,1) - T.a(1,2),
                T.a(0,2) - T.a(2,0),
                T.a(1,0) - T.a(0,1)) / 2.0;
    }
void corecvs::EssentialMatrix::decompose (Matrix33 rot[4], Vector3dd trans[4]) [inline]
Definition at line 419 of file essentialMatrix.h.
References corecvs::Matrix33::a(), corecvs::Matrix33::det(), corecvs::Matrix33::Scale3(), corecvs::Matrix::svdDesc(), corecvs::Matrix33::transposed(), and corecvs::Matrix33::W.
    {
        Matrix33 W(
                0.0, -1.0, 0.0,
                1.0,  0.0, 0.0,
                0.0,  0.0, 1.0
        );
        Matrix33 WT(W.transposed());
        Matrix33  U = *this;
        Vector3dd vS;
        Matrix33  V;
        Matrix::svdDesc(&U, &vS, &V);
        if (U.det() < 0) U = - U;
        if (V.det() < 0) V = - V;
        Matrix33 S = Matrix33::Scale3(vS);
        Matrix33 VT = V.transposed();
        Matrix33 UT = U.transposed();
        Matrix33  R  = U * WT * VT;
        Matrix33  R1 = U * W  * VT;
        Matrix33  T  = U * S * W * UT;
        Vector3dd t = Vector3dd(
                T.a(2,1) - T.a(1,2),
                T.a(0,2) - T.a(2,0),
                T.a(1,0) - T.a(0,1)) / 2.0;
        rot[0] = R;  trans[0] =  t;
        rot[1] = R;  trans[1] = -t;
        rot[2] = R1; trans[2] =  t;
        rot[3] = R1; trans[3] = -t;
    }
void corecvs::EssentialMatrix::decompose (EssentialDecomposition decomposition[4]) [inline]
Definition at line 455 of file essentialMatrix.h.
References decompose().
    {
        Matrix33 rot[4];
        Vector3dd trans[4];
        decompose(rot, trans);
        for (int i = 0; i < 4; i++)
        {
            decomposition[i] = EssentialDecomposition(rot[i], trans[i]);
        }
    }
double corecvs::Matrix33::det () [inherited]
Computing determinant of the matrix.
Definition at line 71 of file matrix33.cpp.
References corecvs::Matrix33::a().
Referenced by decompose(), corecvs::StereoAligner::getAlignmentTransformation(), and corecvs::Matrix33::inv().
{
 return    a(0,0) * (a(1,1) * a(2,2) - a(1,2) * a(2,1))
         - a(0,1) * (a(1,0) * a(2,2) - a(1,2) * a(2,0))
         + a(0,2) * (a(1,0) * a(2,1) - a(1,1) * a(2,0));
}
Vector3dd corecvs::Matrix33::diagonal () const [inherited]
Get the diagonal vector.
Definition at line 217 of file matrix33.cpp.
References corecvs::Matrix33::a().
{
    return Vector3dd (a(0,0), a(1,1), a(2,2));
}
double corecvs::EssentialMatrix::epipolarDistance (const Vector2dd & right, const Vector2dd & left) const [inline]
The inliers calculation is as follows:
.
Where (x,y) are the coordinates in "right" frame and (x' y') are form the "left" frame
We first get the epipolar line for a "right" input point. This line will be in "left" frame
Thus we have an equation of the line
Here is the equation of the line - . And now we want to know how far is the real right point from the predicted by the current model -
Definition at line 259 of file essentialMatrix.h.
References corecvs::Line2d::distanceTo(), and corecvs::Matrix33::mulBy2dLeft().
Referenced by epipolarDistance(), corecvs::Model8Point::fits(), corecvs::EssentialEstimator::CostFunction7to1::getCost(), corecvs::IterativeEstimator::getEssential(), corecvs::EssentialEstimator::CostFunction7to1::getJacobian(), and corecvs::EssentialEstimator::CostFunction7toN::operator()().
     {
         Vector3dd line = this->mulBy2dLeft(right);
         Line2d epiline(line);
         return epiline.distanceTo(left);
     }
double corecvs::EssentialMatrix::epipolarDistance (const Correspondance & data) const [inline]
Definition at line 266 of file essentialMatrix.h.
References corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, epipolarDistance(), and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start.
     {
         return epipolarDistance(data.start, data.end);
     }
double corecvs::Matrix33::frobeniusNorm () const [inherited]
Definition at line 136 of file matrix33.cpp.
References corecvs::VectorOperationsBase< Matrix33, double >::sumAllElementsSq().
Referenced by quality().
{
    return sqrt(sumAllElementsSq());
}
Matrix33 corecvs::Matrix33::FromColumns (const Vector3dd & W1, const Vector3dd & W2, const Vector3dd & W3) [inline, static, inherited]
Matrix construction via 3 columns.
Parameters:
W1 first column
W2 second column
W3 third column
Definition at line 307 of file matrix33.h.
References corecvs::Matrix33::Matrix33(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by corecvs::EssentialDecomposition::getScaler().
{
    return Matrix33(
            W1.x(), W2.x(), W3.x(),
            W1.y(), W2.y(), W3.y(),
            W1.z(), W2.z(), W3.z()
    );
}
Matrix33 corecvs::Matrix33::FromRows (const Vector3dd & a, const Vector3dd & b, const Vector3dd & c) [inline, static, inherited]
Synonym to Matrix33(const Vector3dd& _V1,const Vector3dd& _V2,const Vector3dd& _V3)
Definition at line 284 of file matrix33.h.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33(_V1, _V2, _V3);
}
Matrix33 corecvs::Matrix33::inv () [inherited]
This function returns an inverse of the matrix.
The calculation is done straight forward using the following formular property
Attention:
No check is done, if the matrix is invertable or not
Returns:
The
Definition at line 40 of file matrix33.cpp.
References corecvs::Matrix33::a(), corecvs::Matrix33::det(), and corecvs::Matrix33::Matrix33().
Referenced by corecvs::EssentialDecomposition::getScaler(), corecvs::Matrix33::invert(), corecvs::HomographyReconstructor::noramlisePoints(), BaseCalculationThread::recalculateCache(), and corecvs::Triangulator::Triangulator().
{
    Matrix33 toReturn;
    /* Will hold the minors determinant with the changing sign*/
    double ma =   a(1,1) * a(2,2) - a(1,2) * a(2,1);
    double mb = - a(1,0) * a(2,2) + a(1,2) * a(2,0);
    double mc =   a(1,0) * a(2,1) - a(1,1) * a(2,0);
    double det =   a(0,0) * ma
                 + a(0,1) * mb
                 + a(0,2) * mc;
    return Matrix33(
        ma / det,
        (a(0,2) * a(2,1) - a(0,1) * a(2,2) ) / det,
        (a(0,1) * a(1,2) - a(0,2) * a(1,1) ) / det,
        mb / det,
        (a(0,0) * a(2,2) - a(0,2) * a(2,0) ) / det,
        (a(0,2) * a(1,0) - a(0,0) * a(1,2) ) / det,
        mc / det,
        (a(0,1) * a(2,0) - a(0,0) * a(2,1) ) / det,
        (a(0,0) * a(1,1) - a(0,1) * a(1,0) ) / det
    );
}
void corecvs::Matrix33::invert () [inherited]
Invertion of the matrix inplace.
Definition at line 21 of file matrix33.cpp.
References corecvs::Matrix33::inv().
{
    *this = this->inv();
}
bool corecvs::VectorOperationsBase< Matrix33 , double >::isInHypercube (const VectorOperationsBase< Matrix33, double > & low, const VectorOperationsBase< Matrix33, double > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
Matrix33 corecvs::Matrix33::MirrorXY () [static, inherited]
Definition at line 377 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33 (
        1,  0,  0,
        0,  1,  0,
        0,  0, -1
    );
}
Matrix33 corecvs::Matrix33::MirrorXZ () [static, inherited]
Definition at line 395 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33 (
        1,  0,  0,
        0, -1,  0,
        0,  0,  1
    );
}
Matrix33 corecvs::Matrix33::MirrorYZ () [static, inherited]
Definition at line 386 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33 (
       -1,  0,  0,
        0,  1,  0,
        0,  0,  1
    );
}
double corecvs::VectorOperationsBase< Matrix33 , double >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
Vector3dd corecvs::Matrix33::mulBy2dLeft (const Vector2dd & V) const [inline, inherited]
Definition at line 420 of file matrix33.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by epipolarDistance(), and corecvs::operator*().
{
    return Vector3dd(V.x(), V.y(), 1.0) * (*this);
}
Vector3dd corecvs::Matrix33::mulBy2dRight (const Vector2dd & V) const [inline, inherited]
We expect that * 1.0 will be optimized out.
Definition at line 415 of file matrix33.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::operator*().
{
    return (*this) * Vector3dd(V.x(), V.y(), 1.0);
}
void corecvs::Matrix33::neg () [inherited]
void corecvs::VectorOperationsBase< Matrix33 , double >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Definition at line 407 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
Matrix33 corecvs::VectorOperationsBase< Matrix33 , double >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Definition at line 420 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
bool corecvs::VectorOperationsBase< Matrix33 , double >::notTooFar (const Matrix33 & that, const double & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
void corecvs::EssentialMatrix::nullspaces (Vector3dd * leftNullspace, Vector3dd * rightNullspace) [inline]
Calculating vectors for left and right nullspaces of the 3 by 3 matrix of rank 2.
We use this function to find both epipoles for a given fundamental matrix.
Parameters:
[out] leftNullspace of the matrix (it correspond to first image)
[out] rightNullspace of the matrix (it correspond to second image)
Definition at line 494 of file essentialMatrix.h.
References corecvs::Matrix33::aW(), corecvs::FixedVectorBase< Matrix33, double, 9 >::LENGTH, corecvs::Matrix::svd(), and corecvs::Matrix33::W.
Referenced by corecvs::StereoAligner::getAlignmentTransformation(), corecvs::StereoAligner::getBestZ(), and UniversalRectifier::recalculate().
    {
        Matrix33  A(*this);
        Vector3dd W(0.0);
        Matrix33  V(0.0);
        Matrix::svd(&A, &W, &V);
        double mind = numeric_limits<double>::max();
        int mini = -1;
        for (int i = 0; i < Vector3dd::LENGTH; i++)
        {
            if (W[i] < mind)
            {
                mind = W[i];
                mini = i;
            }
        }
        *leftNullspace  = A.aW(mini);
        *rightNullspace = V.aW(mini);
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< Matrix33 , double >::operator!= (const Matrix33 & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix33 , double >::operator*= (const double & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix33 , double >::operator+= (const Matrix33 & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
Matrix33 corecvs::VectorOperationsBase< Matrix33 , double >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix33 , double >::operator-= (const Matrix33 & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< Matrix33 , double >::operator/= (const double & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< Matrix33 , double >::operator== (const Matrix33 & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
double & corecvs::FixedVectorBase< Matrix33 , double , length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
const double & corecvs::FixedVectorBase< Matrix33 , double , length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
void corecvs::Matrix33::print () const [inline, inherited]
Reimplemented from corecvs::VectorOperationsBase< Matrix33, double >.
Definition at line 174 of file matrix33.h.
Referenced by corecvs::StereoAligner::getAlignmentTransformation(), UniversalRectifier::iterativeMethod(), UniversalRectifier::manualMethod(), and UniversalRectifier::recalculate().
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< Matrix33 , double >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
Matrix33 corecvs::Matrix33::Projective (double px, double py) [static, inherited]
This function returns a matrix with only the projective components.
Definition at line 455 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
Referenced by corecvs::StereoAligner::getAlignmentTransformation(), corecvs::HomographyReconstructor::CostFunctionWize::matrixFromState(), and corecvs::Matrix33::Projective().
{
    return Matrix33 (
        1,   0,  0,
        0,   1,  0,
        px, py,  1
    );
}
static Matrix33 corecvs::Matrix33::Projective (const Vector2dd & v) [inline, static, inherited]
Definition at line 160 of file matrix33.h.
References corecvs::Matrix33::Projective(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        return Projective(v.x(), v.y());
    }
Matrix33 corecvs::Matrix33::ProjectiveByPoints (Vector2dd points[4], Vector2dd images[4]) [static, inherited]
Calculate the Matrix that transform given points to given images This is done almost the same way as in rectification Rectificator::getFundamantalRansac() using the SVD.
Matrix is searched in form
Definition at line 573 of file matrix33.cpp.
References corecvs::Matrix::a(), corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs(), corecvs::Matrix::invSVD(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::Matrix33::ProjectiveByPoints().
{
    Matrix M(8,8);
    Matrix B(8,1);
    /*TODO: Remove common code in this and the other reconstruction function */
    for (int i = 0; i < 4; i++)
    {
        Vector2dd point = points[i];
        Vector2dd image = images[i];
        M.fillLineWithArgs(i,
             point.x(), point.y(), (double)1.0, (double)0.0, (double)0.0, (double)0.0, -point.x() * image.x(), -point.y() * image.x());
        M.fillLineWithArgs(i + 4,
             (double)0.0, (double)0.0, (double)0.0, point.x(), point.y(), (double)1.0, -point.x() * image.y(), -point.y() * image.y());
        B.a(i,0) = image.x();
        B.a(i+4,0) = image.y();
    }
    Matrix result = M.invSVD() * B;
    Matrix33 toReturn(
            result.a(0,0), result.a(1,0), result.a(2,0),
            result.a(3,0), result.a(4,0), result.a(5,0),
            result.a(6,0), result.a(7,0), 1.0
    );
    return toReturn;
}
Matrix33 corecvs::Matrix33::ProjectiveByPoints (int pointNumber, Vector2dd points[], Vector2dd images[]) [static, inherited]
Get the best transformation for a set of points.
This functions uses Liner Least Squares Method - http://en.wikipedia.org/wiki/Linear_least_squares_%28mathematics%29
Definition at line 610 of file matrix33.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs(), corecvs::Matrix::invSVD(), corecvs::Matrix33::ProjectiveByPoints(), corecvs::Matrix::t(), ClusteringDirectionType::X, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    ASSERT_TRUE(pointNumber >= 4, "Too few points to create transform");
    if (pointNumber == 4)
        return ProjectiveByPoints(points, images);
    Matrix X(pointNumber * 2,8);
    Matrix B(pointNumber * 2,1);
    for (int i = 0; i < pointNumber; i++)
    {
        Vector2dd point = points[i];
        Vector2dd image = images[i];
        X.fillLineWithArgs(i,
             point.x(), point.y(), (double)1.0, (double)0.0, (double)0.0, (double)0.0, -point.x() * image.x(), -point.y() * image.x());
        X.fillLineWithArgs(i + 4,
             (double)0.0, (double)0.0, (double)0.0, point.x(), point.y(), (double)1.0, -point.x() * image.y(), -point.y() * image.y());
        B.a(i,0) = image.x();
        B.a(i+4,0) = image.y();
    }
    Matrix XTX = X.t() * X;
    Matrix XTB = X.t() * B;
    Matrix result = XTX.invSVD() * XTB;
    Matrix33 toReturn(
              result.a(0,0), result.a(1,0), result.a(2,0),
              result.a(3,0), result.a(4,0), result.a(5,0),
              result.a(6,0), result.a(7,0), 1.0
    );
    return toReturn;
}
void corecvs::EssentialMatrix::projectToEssential () [inline]
Definition at line 570 of file essentialMatrix.h.
References corecvs::Matrix33::a(), corecvs::VectorOperationsBase< RealType, ElementType >::print(), corecvs::Matrix::svd(), corecvs::Matrix33::transpose(), and corecvs::Matrix33::W.
Referenced by corecvs::ModelEssential8Point::ModelEssential8Point().
    {
        Vector3dd W;
        Matrix33  V;
        Matrix::svd(this, &W, &V);
#ifdef TRACE
        printf("The singular values:\n");
        W.print();
        printf("\n");
#endif
        // Leave out the last singular number. To assert that rank is 2
        unsigned mini = 0;
        double minval = numeric_limits<double>::max();
        for (unsigned i = 0; i < 3; i ++)
        {
            if (W[i] <= minval)
            {
                mini = i;
                minval = W[i];
            }
        }
        Matrix33 Wbig(0.0);
        double sum = 0.0;
        for (unsigned i = 0; i < 3; i++)
        {
            if (i != mini)
                sum += W[i];
        }
        for (unsigned i = 0; i < 3; i++)
        {
            if (i != mini)
                Wbig.a(i, i) = 1.0;//sum / 2.0;
        }
        V.transpose();
        *this = *this * Wbig * V;
    }
double corecvs::EssentialMatrix::quality () const [inline]
Definition at line 285 of file essentialMatrix.h.
References criteriaMatrix(), and corecvs::Matrix33::frobeniusNorm().
    {
        return (criteriaMatrix().frobeniusNorm());
    }
Matrix33 * corecvs::VectorOperationsBase< Matrix33 , double >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const Matrix33 * corecvs::VectorOperationsBase< Matrix33 , double >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
static Matrix33 corecvs::Matrix33::Rotate (const Vector3dd & v, double angle) [static, inherited]
static Matrix33 corecvs::Matrix33::RotateProj (double angle) [inline, static, inherited]
Definition at line 115 of file matrix33.h.
References corecvs::Matrix33::RotationZ().
    {
        return RotationZ(angle);
    }
Matrix33 corecvs::Matrix33::RotationX (double alpha) [static, inherited]
Creates a 3D rotation matrix over the Y axis by the angle alpha.
Parameters:
alpha angle to rotate by
Returns:
the rotation matrix
Definition at line 239 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
Referenced by corecvs::FCostFunction::RotationMatrix(), and corecvs::CameraAngles::toMatrix().
{
  double  sinA = sin(alpha);
  double  cosA = cos(alpha);
  return Matrix33 (
      1,    0,     0,
      0, cosA, -sinA,
      0, sinA,  cosA
  );
}
Matrix33 corecvs::Matrix33::RotationY (double alpha) [static, inherited]
Creates a 3D rotation matrix over the Y axis by the angle alpha.
Parameters:
alpha angle to rotate by
Returns:
the rotation matrix
Definition at line 264 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
Referenced by corecvs::FCostFunction::RotationMatrix(), and corecvs::CameraAngles::toMatrix().
{
  double  sinA = sin(alpha);
  double  cosA = cos(alpha);
  return Matrix33 (
      cosA,  0,  sinA,
         0,  1,     0,
     -sinA,  0,  cosA
  );
}
Matrix33 corecvs::Matrix33::RotationZ (double alpha) [static, inherited]
Creates a 2D projective transform for the rotation by the angle alpha or a 3d rotation transform.
Parameters:
alpha angle to rotate by
Returns:
the rotation matrix
Definition at line 291 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
Referenced by corecvs::HomographyReconstructor::CostFunctionWize::matrixFromState(), corecvs::Matrix33::RotateProj(), corecvs::FCostFunction::RotationMatrix(), and corecvs::CameraAngles::toMatrix().
{
  double  sinA = sin(alpha);
  double  cosA = cos(alpha);
  return Matrix33 (
      cosA, -sinA,  0,
      sinA,  cosA,  0,
         0,     0,  1
  );
}
Matrix33 corecvs::Matrix33::RotationZ180 () [static, inherited]
Definition at line 311 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33 (
       -1,  0,  0,
        0, -1,  0,
        0,  0,  1
    );
}
Matrix33 corecvs::Matrix33::RotationZ270 () [static, inherited]
Definition at line 320 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33 (
        0,  1,  0,
       -1,  0,  0,
        0,  0,  1
    );
}
Matrix33 corecvs::Matrix33::RotationZ90 () [static, inherited]
Definition at line 302 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33 (
        0, -1,  0,
        1,  0,  0,
        0,  0,  1
    );
}
Matrix33 corecvs::Matrix33::Scale2 (double x, double y) [static, inherited]
This function returns a matrix with only 2 scale components.
Returns:
The scale matrix
Definition at line 431 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
Referenced by corecvs::StereoAligner::getAlignmentTransformation(), corecvs::HomographyReconstructor::CostFunctionWize::matrixFromState(), corecvs::Matrix33::Scale2(), and corecvs::Matrix33::ScaleProj().
{
    return Matrix33 (
        x,   0,   0,
        0,   y,   0,
        0,   0,   1
    );
}
static Matrix33 corecvs::Matrix33::Scale2 (const Vector2dd & v) [inline, static, inherited]
Definition at line 136 of file matrix33.h.
References corecvs::Matrix33::Scale2(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        return Scale2(v.x(), v.y());
    }
static Matrix33 corecvs::Matrix33::Scale2 (double v) [inline, static, inherited]
Definition at line 141 of file matrix33.h.
References corecvs::Matrix33::Scale2().
    {
        return Scale2(v,v);
    }
static Matrix33 corecvs::Matrix33::Scale3 (const Vector3dd & v) [static, inherited]
Referenced by decompose().
Matrix33 corecvs::Matrix33::Scale3 (double v) [static, inherited]
Definition at line 440 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
{
    return Matrix33 (v);
}
static Matrix33 corecvs::Matrix33::ScaleProj (double v) [inline, static, inherited]
Definition at line 146 of file matrix33.h.
References corecvs::Matrix33::Scale2().
Referenced by corecvs::CorrespondanceList::getNormalizingTransform(), and corecvs::HomographyReconstructor::noramlisePoints().
    {
        return Scale2(v);
    }
void corecvs::Matrix33::serialise (ostream & out) const [inline, inherited]
Definition at line 179 of file matrix33.h.
    {
        streamsize oldPrec = out.precision(numeric_limits<double>::digits10 + 3);
        out << *this;
        out.precision(oldPrec);
    }
Matrix33 corecvs::Matrix33::ShiftProj (double x, double y) [static, inherited]
This function returns a matrix with only shift components.
Definition at line 474 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33().
Referenced by corecvs::StereoAligner::getLateralCorrection(), corecvs::StereoAligner::getLateralCorrectionFixPoint(), corecvs::CorrespondanceList::getNormalizingTransform(), corecvs::HomographyReconstructor::CostFunctionWize::matrixFromState(), corecvs::HomographyReconstructor::noramlisePoints(), and corecvs::Matrix33::ShiftProj().
{
   return Matrix33 (
        1,   0,   x,
        0,   1,   y,
        0,   0,   1
   );
}
static Matrix33 corecvs::Matrix33::ShiftProj (const Vector2dd & v) [inline, static, inherited]
Definition at line 154 of file matrix33.h.
References corecvs::Matrix33::ShiftProj(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        return ShiftProj(v.x(), v.y());
    }
int corecvs::FixedVectorBase< Matrix33 , double , length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
double corecvs::VectorOperationsBase< Matrix33 , double >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
Referenced by corecvs::Matrix33::frobeniusNorm().
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
void corecvs::Matrix33::swapColumns (int r1, int r2) [inherited]
Definition at line 109 of file matrix33.cpp.
References corecvs::Matrix33::a(), and corecvs::Matrix33::H.
Referenced by corecvs::Matrix::svdDesc().
{
    double tmp;
    for (int i = 0; i < H; i++)
    {
        tmp = a(i, r1);
        a(i, r1) = a(i, r2);
        a(i, r2) = tmp;
    }
}
void corecvs::Matrix33::swapRows (int r1, int r2) [inherited]
Definition at line 98 of file matrix33.cpp.
References corecvs::Matrix33::a(), and corecvs::Matrix33::W.
{
    double tmp;
    for (int j = 0; j < W; j++)
    {
        tmp = a(r1, j);
        a(r1, j) = a(r2, j);
        a(r2, j) = tmp;
    }
}
double corecvs::Matrix33::trace (void) const [inherited]
Computing the trace of the matrix.
The sum of diagonal elements
Definition at line 82 of file matrix33.cpp.
References corecvs::Matrix33::a().
Referenced by criteriaMatrix().
{
    return a(0,0) + a(1,1) + a(2,2);
}
void corecvs::Matrix33::transpose () [inherited]
Transposing the matrix.
Definition at line 90 of file matrix33.cpp.
References corecvs::Matrix33::a().
Referenced by assertRank2(), and projectToEssential().
{
   double tmp;
   tmp = a(1,0); a(1,0) = a(0,1); a(0,1) = tmp;
   tmp = a(2,0); a(2,0) = a(0,2); a(0,2) = tmp;
   tmp = a(2,1); a(2,1) = a(1,2); a(1,2) = tmp;
}
Matrix33 corecvs::Matrix33::transposed () const [inherited]
Returning transposed matrix.
Definition at line 124 of file matrix33.cpp.
References corecvs::Matrix33::a(), and corecvs::Matrix33::Matrix33().
Referenced by criteriaMatrix(), decompose(), corecvs::StereoAligner::getAlignmentTransformation(), and UniversalRectifier::recalculate().
{
   return Matrix33(
       a(0,0), a(1,0), a(2,0),
       a(0,1), a(1,1), a(2,1),
       a(0,2), a(1,2), a(2,2)
   );
}
Matrix33 corecvs::Matrix33::VectorByVector (const Vector3dd & a, const Vector3dd & b) [static, inherited]
This function returns a matrix constucted as a product of two vectors .
Definition at line 525 of file matrix33.cpp.
References corecvs::Matrix33::Matrix33(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by corecvs::StereoAligner::getDistortion().
{
   return Matrix33(
        b.x() * a.x(), b.y() * a.x(), b.z() * a.x(),
        b.x() * a.y(), b.y() * a.y(), b.z() * a.y(),
        b.x() * a.z(), b.y() * a.z(), b.z() * a.z()
   );
}
Friends And Related Function Documentation
double operator& (const VectorOperationsBase< Matrix33, double > & V1, const VectorOperationsBase< Matrix33, double > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
Matrix33 operator* (const Matrix33 & M1, const Matrix33 & M2) [friend, inherited]
Negating the matrix - all elements are replaced with their negative values.
Matrix multiplication ACCURATE version is slower 1.5 - 2 times
Definition at line 157 of file matrix33.cpp.
{
   Matrix33 M;
#ifdef ACCURATE
   double sum;
   for (int i = 0;i < 3; i++)
     for (int j = 0;j <3; j++)
     {
       sum = 0;
       for (int k = 0; k < 3; k++)
         sum+= M1.x[i*3 + k] * M2.x[k*3 + j];
       M.x[i * 3 + j] = sum;
     }
#else
   return Matrix33(
           m1.a(0,0) * m2.a(0,0) + m1.a(0,1) * m2.a(1,0) + m1.a(0,2) * m2.a(2,0),
           m1.a(0,0) * m2.a(0,1) + m1.a(0,1) * m2.a(1,1) + m1.a(0,2) * m2.a(2,1),
           m1.a(0,0) * m2.a(0,2) + m1.a(0,1) * m2.a(1,2) + m1.a(0,2) * m2.a(2,2),
           m1.a(1,0) * m2.a(0,0) + m1.a(1,1) * m2.a(1,0) + m1.a(1,2) * m2.a(2,0),
           m1.a(1,0) * m2.a(0,1) + m1.a(1,1) * m2.a(1,1) + m1.a(1,2) * m2.a(2,1),
           m1.a(1,0) * m2.a(0,2) + m1.a(1,1) * m2.a(1,2) + m1.a(1,2) * m2.a(2,2),
           m1.a(2,0) * m2.a(0,0) + m1.a(2,1) * m2.a(1,0) + m1.a(2,2) * m2.a(2,0),
           m1.a(2,0) * m2.a(0,1) + m1.a(2,1) * m2.a(1,1) + m1.a(2,2) * m2.a(2,1),
           m1.a(2,0) * m2.a(0,2) + m1.a(2,1) * m2.a(1,2) + m1.a(2,2) * m2.a(2,2)
   );
#endif
}
Vector3dd operator* (const Matrix33 & matrix, const Vector3dd & V) [friend, inherited]
Vector by Matrix left multiplication .
Note:
ACCURATE version is slower with debug on
Parameters:
matrix input matrix
V input V
Definition at line 379 of file matrix33.h.
{
  double a,b,c;
  a = matrix.a(0,0) * V.x() +  matrix.a(0,1) * V.y() + matrix.a(0,2) * V.z();
  b = matrix.a(1,0) * V.x() +  matrix.a(1,1) * V.y() + matrix.a(1,2) * V.z();
  c = matrix.a(2,0) * V.x() +  matrix.a(2,1) * V.y() + matrix.a(2,2) * V.z();
  return Vector3dd(a,b,c);
}
Vector3dd operator* (const Vector3dd & V, const Matrix33 & matrix) [friend, inherited]
Vector by Matrix right multiplication .
Note:
ACCURATE version is slower with debug on
Parameters:
V input vector
matrix input matrix
Definition at line 402 of file matrix33.h.
{
  double a,b,c;
  a = matrix.a(0,0) * V.x() + matrix.a(1,0) * V.y() + matrix.a(2,0) * V.z();
  b = matrix.a(0,1) * V.x() + matrix.a(1,1) * V.y() + matrix.a(2,1) * V.z();
  c = matrix.a(0,2) * V.x() + matrix.a(1,2) * V.y() + matrix.a(2,2) * V.z();
  return Vector3dd(a,b,c);
}
Vector2dd operator* (const Matrix33 & matrix, const Vector2dd & V) [friend, inherited]
Apply projective transformation to 2D vector
.
Parameters:
matrix input matrix
V input V
Returns:
Definition at line 445 of file matrix33.h.
{
    return (Vector2dd) matrix.mulBy2dRight(V);
}
Vector2dd operator* (const Vector2dd & V, const Matrix33 & matrix) [friend, inherited]
Apply projective transformation to 2D vector (vector is form the right)
.
Parameters:
matrix input matrix
V input V
Returns:
Definition at line 465 of file matrix33.h.
{
    return (Vector2dd) matrix.mulBy2dLeft(V);
}
Matrix33 operator* (const VectorOperationsBase< Matrix33, double > & V1, const VectorOperationsBase< Matrix33, double > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
Matrix33 operator* (const double & c, const VectorOperationsBase< Matrix33, double > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
Matrix33 operator* (const VectorOperationsBase< Matrix33, double > & V, const double & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
Matrix33 operator*= (Matrix33 & M1, const Matrix33 & M2) [friend, inherited]
Definition at line 191 of file matrix33.cpp.
{
    M1 = M1 * M2;
    return M1;
}
Matrix33 operator+ (const VectorOperationsBase< Matrix33, double > & V1, const VectorOperationsBase< Matrix33, double > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
Matrix33 operator- (const VectorOperationsBase< Matrix33, double > & V1, const VectorOperationsBase< Matrix33, double > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
Matrix33 operator/ (const VectorOperationsBase< Matrix33, double > & V1, const VectorOperationsBase< Matrix33, double > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
Matrix33 operator/ (const VectorOperationsBase< Matrix33, double > & V, const double & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const Matrix33 & matrix) [friend, inherited]
Definition at line 186 of file matrix33.h.
    {
        //streamsize wasPrecision = out.precision(6);
        for (int i = 0; i < matrix.H; i++)
        {
            out << "[";
            for (int j = 0; j < matrix.W; j++)
            {
                out << (j == 0 ? "" : " ");
                //out.width(6);
                out << matrix.a(i,j);
            }
            out << "]\n";
        }
        //out.precision(wasPrecision);
        return out;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< Matrix33, double > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, Matrix33 & matrix) [friend, inherited]
Definition at line 205 of file matrix33.h.
    {
        for (int i = 0; i < matrix.H; i++)
        {
            for (int j = 0; j < matrix.W; j++)
            {
                while (true)
                {
                    in >> matrix.a(i,j);
                    // cout << "Read:" << i << "," << j << " " << matrix.a(i,j) << endl;
                    if (in.good())
                        break;
                    if (in.eof())
                        return in;
                    /* Not a number clean the error and advance*/
                    in.clear();
                    // cout << "Skipped:" << ((char)in.peek()) << endl;
                    in.ignore();
                }
            }
        }
        return in;
    }
istream& operator>> (istream & in, VectorOperationsBase< Matrix33, double > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
Member Data Documentation
const int corecvs::Matrix33::ELEM_NUM = H*W [static, inherited]
Definition at line 55 of file matrix33.h.
double corecvs::FixedVectorBase< Matrix33 , double , length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
const int corecvs::Matrix33::H = 3 [static, inherited]
Definition at line 53 of file matrix33.h.
Referenced by corecvs::Matrix33::swapColumns().
const int corecvs::FixedVectorBase< Matrix33 , double , length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
Referenced by assertRank2(), and nullspaces().
const int corecvs::Matrix33::W = H [static, inherited]
Definition at line 54 of file matrix33.h.
Referenced by corecvs::Matrix33::a(), assertRank2(), decompose(), nullspaces(), projectToEssential(), and corecvs::Matrix33::swapRows().
The documentation for this class was generated from the following file:
core/rectification/essentialMatrix.h