DeepView: corecvs::ParallelPrepareBlurBuffers Class Reference
corecvs::ParallelPrepareBlurBuffers Class Reference
Public Member Functions
ParallelPrepareBlurBuffers (G12IntegralBuffer *_integral, G12Buffer *_blur, unsigned _dy, unsigned _dx)
void operator() (const BlockedRange< int > &r) const
Private Attributes
G12IntegralBuffer * integral
G12Buffer * blur
unsigned dy
unsigned dx
Detailed Description
Definition at line 22 of file blurProcessor.cpp.
Constructor & Destructor Documentation
corecvs::ParallelPrepareBlurBuffers::ParallelPrepareBlurBuffers (G12IntegralBuffer * _integral, G12Buffer * _blur, unsigned _dy, unsigned _dx) [inline]
Definition at line 30 of file blurProcessor.cpp.
                          :
       integral(_integral), blur(_blur), dy(_dy), dx(_dx)
       {}
Member Function Documentation
void corecvs::ParallelPrepareBlurBuffers::operator() (const BlockedRange< int > & r) const [inline]
Definition at line 39 of file blurProcessor.cpp.
References corecvs::BlockedRange< IndexType >::begin(), blur, corecvs::BlurProcessor::BLUR_RADIUS, dx, dy, corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::BlockedRange< IndexType >::end(), integral, corecvs::IntegralBuffer< ElementType, BaseElementType, IndexType >::rectangle(), and corecvs::AbstractBufferParams::w.
    {
        for( int i = r.begin(); i < r.end(); i ++ )
        {
            G12Buffer::InternalElementType* outoffset = &(blur->element(i, 0));
            for (int j = 0; j < blur->w; j ++)
            {
                int y = i * 2 + dy;
                int x = j * 2 + dx;
                unsigned tmp = integral->rectangle(x, y, x + BlurProcessor::BLUR_RADIUS * 2, y + BlurProcessor::BLUR_RADIUS * 2);
                *outoffset = (uint16_t)(tmp / 25);
                outoffset++;
            }
        }
    }
Member Data Documentation
G12Buffer* corecvs::ParallelPrepareBlurBuffers::blur [private]
Definition at line 25 of file blurProcessor.cpp.
Referenced by operator()().
unsigned corecvs::ParallelPrepareBlurBuffers::dx [private]
Definition at line 27 of file blurProcessor.cpp.
Referenced by operator()().
unsigned corecvs::ParallelPrepareBlurBuffers::dy [private]
Definition at line 26 of file blurProcessor.cpp.
Referenced by operator()().
G12IntegralBuffer* corecvs::ParallelPrepareBlurBuffers::integral [private]
Definition at line 24 of file blurProcessor.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
core/buffers/kernels/blurProcessor.cpp