DeepView: CloudViewDialog Class Reference
CloudViewDialog Class Reference
#include <cloudViewDialog.h>
Public Types
enum SceneId {
MAIN_SCENE, ADDITIONAL_SCENE, CAMERA_PAIR, FIRST_USER_SCENE,
GAPER_ZONE = FIRST_USER_SCENE, CONTROL_ZONE, DETECTED_PERSON, DISP_CONTROL_ZONE,
DISP_PREDICTED_CONTROL_ZONE, CLUSTER_ZONE, CLUSTER_SWARM, HEAD_SEARCH_ZONE,
SCENE_NUMBER
}
enum SubScene { SUBSCENE_PLANE, SUBSCENE_GRID, SUBSCENE_CAMERA, SUBSCENE_USER }
enum CameraType {
ORTHO_TOP, ORTHO_LEFT, ORTHO_FRONT, PINHOLE_AT_0,
RIGHT_CAMERA, LEFT_CAMERA, FACE_CAMERA
}
Public Slots
void downRotate ()
void upRotate ()
void leftRotate ()
void rightRotate ()
void resetCameraPos ()
void resetCamera ()
void resetCameraSlot ()
void zoomIn ()
void zoomOut ()
void childMoveEvent (QMouseEvent *event)
void childPressEvent (QMouseEvent *event)
void childReleaseEvent (QMouseEvent *event)
void childWheelEvent (QWheelEvent *event)
void childKeyPressEvent (QKeyEvent *event)
void childKeyReleaseEvent (QKeyEvent *event)
void keyPressEvent (QKeyEvent *event)
void keyReleaseEvent (QKeyEvent *event)
void initializeGLSlot ()
void repaintGLSlot ()
void resizeGLSlot (int width, int height)
void updateCameraMatrix ()
void updateHelperObjects ()
void savePointsPCD ()
void savePointsPLY ()
void loadMesh ()
void addCoordinateFrame ()
void saveParameters ()
void loadParameters ()
Signals
void askParentRepaint (QPaintEvent *event, QWidget *who)
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (QResizeEvent *event)
void notifyKeyPressEvent (QKeyEvent *event)
void notifyKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
CloudViewDialog (QWidget *parent=0)
~CloudViewDialog ()
GLuint texture (int cameraId)
void setNewScenePointer (QSharedPointer< Scene3D > scene, int sceneId=MAIN_SCENE)
void setNewRectificationResult (QSharedPointer< RectificationResult > rectificationResult)
void setNewCameraImage (QSharedPointer< QImage > texture, int cameraId=Frames::RIGHT_FRAME)
virtual void paintEvent (QPaintEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void resizeEvent (QResizeEvent *event)
Public Attributes
Ui_CloudViewDialogClass mUi
QSharedPointer< Scene3D > mScenes [SCENE_NUMBER]
TreeSceneController * mSceneControllers [SCENE_NUMBER]
QSharedPointer
< RectificationResult > mRectificationResult
QSharedPointer< QImage > mCameraImage [Frames::MAX_INPUTS_NUMBER]
Matrix44 mCamera
double mCameraZoom
GLuint mFancyTexture
Static Public Attributes
static const double ROTATE_STEP = 0.05
static const double ZOOM_DIVISION = 1000.0
static const double SHIFT_STEP = 10.0
static const double START_X = 0
static const double START_Y = 0
static const double START_Z = 1 * Grid3DScene::GRID_SIZE * Grid3DScene::GRID_STEP
Protected Member Functions
TreeSceneController * addSubObject (QString name, QSharedPointer< Scene3D > scene, bool visible=true)
void setZoom (double value)
void zoom (int delta)
Protected Attributes
int mIsTracking
QPoint mTrack
TreeSceneModel mTreeModel
Private Attributes
GLuint mCameraTexture [Frames::MAX_INPUTS_NUMBER]
Detailed Description
Definition at line 28 of file cloudViewDialog.h.
Member Enumeration Documentation
enum CloudViewDialog::CameraType
Enumerator:
ORTHO_TOP
ORTHO_LEFT
ORTHO_FRONT
PINHOLE_AT_0
RIGHT_CAMERA
LEFT_CAMERA
FACE_CAMERA
Definition at line 131 of file cloudViewDialog.h.
                    {
        ORTHO_TOP,
        ORTHO_LEFT,
        ORTHO_FRONT,
        PINHOLE_AT_0,
        RIGHT_CAMERA,
        LEFT_CAMERA,
        FACE_CAMERA
    };
enum CloudViewDialog::SceneId
Enumerator:
MAIN_SCENE
ADDITIONAL_SCENE
CAMERA_PAIR
FIRST_USER_SCENE
GAPER_ZONE
CONTROL_ZONE
DETECTED_PERSON
DISP_CONTROL_ZONE
DISP_PREDICTED_CONTROL_ZONE
CLUSTER_ZONE
CLUSTER_SWARM
HEAD_SEARCH_ZONE
SCENE_NUMBER
Definition at line 93 of file cloudViewDialog.h.
                {
        MAIN_SCENE,
        ADDITIONAL_SCENE,
        CAMERA_PAIR,
        FIRST_USER_SCENE,
        GAPER_ZONE = FIRST_USER_SCENE,
        CONTROL_ZONE,
        DETECTED_PERSON,
        DISP_CONTROL_ZONE,
        DISP_PREDICTED_CONTROL_ZONE,
        CLUSTER_ZONE,
        CLUSTER_SWARM,
        HEAD_SEARCH_ZONE,
        /* Should be the last one*/
        SCENE_NUMBER
    };
enum CloudViewDialog::SubScene
Enumerator:
SUBSCENE_PLANE
SUBSCENE_GRID
SUBSCENE_CAMERA
SUBSCENE_USER
Definition at line 124 of file cloudViewDialog.h.
                  {
        SUBSCENE_PLANE,
        SUBSCENE_GRID,
        SUBSCENE_CAMERA,
        SUBSCENE_USER
    };
Constructor & Destructor Documentation
CloudViewDialog::CloudViewDialog (QWidget * parent = 0)
Definition at line 31 of file cloudViewDialog.cpp.
References corecvs::Mesh3D::addAOB(), addCoordinateFrame(), addSubObject(), ViAreaWidget::askParentRepaint(), childKeyPressEvent(), childKeyReleaseEvent(), childMoveEvent(), childPressEvent(), childReleaseEvent(), childWheelEvent(), downRotate(), TreeSceneModel::FLAG_COLUMN, in, initializeGLSlot(), leftRotate(), loadMesh(), PLYLoader::loadPLY(), Frames::MAX_INPUTS_NUMBER, mCameraTexture, mFancyTexture, mSceneControllers, mTreeModel, mUi, Scene3D::name, TreeSceneModel::NAME_COLUMN, ViAreaWidget::notifyParentMouseMove(), ViAreaWidget::notifyParentMousePress(), ViAreaWidget::notifyParentMouseRelease(), ViAreaWidget::notifyParentResize(), ViAreaWidget::notifyParentWheelEvent(), TreeSceneModel::PARAMETER_COLUMN, repaintGLSlot(), resetCameraSlot(), resizeGLSlot(), rightRotate(), SCENE_NUMBER, START_Z, updateCameraMatrix(), upRotate(), zoomIn(), and zoomOut().
                                                :
      ViAreaWidget(parent)
    , mCameraZoom(1.0)
    , mIsTracking(false)
{
    mFancyTexture = -1;
    for (int i = 0; i < Frames::MAX_INPUTS_NUMBER; i++)
    {
        mCameraTexture[i] = -1;
    }
    for (int i = 0; i < SCENE_NUMBER;i++)
    {
        mSceneControllers[i] = NULL;
    }
    /* Now lets work with UI a bit */
    mUi.setupUi(this);
    qDebug("Creating CloudViewDialog for working with OpenGL(%d.%d)",
            mUi.widget->format().majorVersion(),
            mUi.widget->format().minorVersion());
    connect(mUi.downButton,   SIGNAL(pressed()), this, SLOT(downRotate  ()));
    connect(mUi.upButton,     SIGNAL(pressed()), this, SLOT(upRotate    ()));
    connect(mUi.leftButton,   SIGNAL(pressed()), this, SLOT(leftRotate  ()));
    connect(mUi.rightButton,  SIGNAL(pressed()), this, SLOT(rightRotate ()));
    connect(mUi.centerButton, SIGNAL(pressed()), this, SLOT(resetCameraSlot ()));
    connect(mUi.zoomInButton, SIGNAL(pressed()), this, SLOT(zoomIn      ()));
    connect(mUi.zoomOutButton,SIGNAL(pressed()), this, SLOT(zoomOut     ()));
    connect(mUi.cameraTypeBox,SIGNAL(currentIndexChanged(int)),           this, SLOT(updateCameraMatrix()));
    connect(mUi.widget, SIGNAL(askParentInitialize()),                    this, SLOT(initializeGLSlot()));
    connect(mUi.widget, SIGNAL(askParentRepaint()),                       this, SLOT(repaintGLSlot()));
    connect(mUi.widget, SIGNAL(notifyParentResize(int, int)),             this, SLOT(resizeGLSlot(int, int)));
    connect(mUi.widget, SIGNAL(notifyParentMouseMove(QMouseEvent *)),     this, SLOT(childMoveEvent(QMouseEvent *)));
    connect(mUi.widget, SIGNAL(notifyParentMousePress(QMouseEvent *)),    this, SLOT(childPressEvent(QMouseEvent *)));
    connect(mUi.widget, SIGNAL(notifyParentMouseRelease(QMouseEvent *)),  this, SLOT(childReleaseEvent(QMouseEvent *)));
    connect(mUi.widget, SIGNAL(notifyParentKeyPressEvent(QKeyEvent *)),   this, SLOT(childKeyPressEvent(QKeyEvent *)));
    connect(mUi.widget, SIGNAL(notifyParentKeyReleaseEvent(QKeyEvent *)), this, SLOT(childKeyReleaseEvent(QKeyEvent *)));
    connect(mUi.widget, SIGNAL(notifyParentWheelEvent(QWheelEvent *)),    this, SLOT(childWheelEvent(QWheelEvent *)));
    mUi.frustumFarBox->setValue(fabs(START_Z * 3.0));
    /* Prepare table of visible objects*/
    mUi.treeView->setModel(&mTreeModel);
    mUi.treeView->setDragEnabled(true);
    mUi.treeView->setAcceptDrops(true);
    mUi.treeView->setDropIndicatorShown(true);
    mUi.treeView->setColumnWidth(TreeSceneModel::NAME_COLUMN,200);
    mUi.treeView->setColumnWidth(TreeSceneModel::FLAG_COLUMN,30);
    mUi.treeView->setColumnWidth(TreeSceneModel::PARAMETER_COLUMN,20);
    connect(mUi.treeView, SIGNAL(clicked(const QModelIndex &)), &mTreeModel, SLOT(clicked(const QModelIndex &)));
    connect(&mTreeModel, SIGNAL(modelChanged()), mUi.widget, SLOT(update()));
    connect(mUi.loadMeshPushButton, SIGNAL(released()), this, SLOT(loadMesh()));
    connect(mUi.addFramePushButton, SIGNAL(released()), this, SLOT(addCoordinateFrame()));
    addSubObject("grid"  , QSharedPointer<Scene3D>(new Grid3DScene()));
    addSubObject("plane" , QSharedPointer<Scene3D>(new Plane3DScene()));
    QSharedPointer<CoordinateFrame> worldFrame = QSharedPointer<CoordinateFrame>(new CoordinateFrame());
/*    QSharedPointer<Scene3D> grid  = QSharedPointer<Scene3D>(new Grid3DScene());
    QSharedPointer<Scene3D> plane = QSharedPointer<Scene3D>(new Plane3DScene());
    grid->name  = "Grid";
    plane->name = "Plane";
    worldFrame->mChildren.push_back(grid);
    worldFrame->mChildren.push_back(plane);*/
    QSharedPointer<Scene3D> camera = QSharedPointer<Scene3D>(new CameraScene());
    camera->name = "camera";
    worldFrame->mChildren.push_back(camera);
    Mesh3DScene *mesh = new Mesh3DScene();
    PLYLoader loader;
    ifstream file("data/box.ply", ios::in);
    if (!file.fail() && loader.loadPLY(file, *mesh) != 0)
    {
        qDebug() << "CloudViewDialog::Unable to load mesh";
    } else {
        mesh->name = "box-ply";
    //    addSubObject("box-ply", QSharedPointer<Scene3D>(mesh));
    }
    file.close();
    worldFrame->mChildren.push_back(QSharedPointer<Scene3D>(mesh));
    Mesh3DScene *box = new Mesh3DScene();
    box->addAOB(Vector3dd(0.0,0.0,0.0), Vector3dd(1.0,1.0,1.0));
    box->name = "box-mesh";
    //addSubObject("box-mesh", QSharedPointer<Scene3D>(box));
    worldFrame->mChildren.push_back(QSharedPointer<Scene3D>(box));
    addSubObject("World Frame", worldFrame);
}
CloudViewDialog::~CloudViewDialog ()
Definition at line 148 of file cloudViewDialog.cpp.
{
}
Member Function Documentation
void CloudViewDialog::addCoordinateFrame () [slot]
Definition at line 761 of file cloudViewDialog.cpp.
References addSubObject().
Referenced by CloudViewDialog().
{
    QSharedPointer<CoordinateFrame> newFrame = QSharedPointer<CoordinateFrame>(new CoordinateFrame());
    addSubObject("New Frame", newFrame);
}
TreeSceneController * CloudViewDialog::addSubObject (QString name, QSharedPointer< Scene3D > scene, bool visible = true) [protected]
Definition at line 140 of file cloudViewDialog.cpp.
References TreeSceneModel::addObject(), and mTreeModel.
Referenced by addCoordinateFrame(), CloudViewDialog(), loadMesh(), and setNewScenePointer().
{
    qDebug() << "Adding object" << name;
    return mTreeModel.addObject(name, scene, visible);
}
void ViAreaWidget::askParentRepaint (QPaintEvent * event, QWidget * who) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::paintEvent().
void CloudViewDialog::childKeyPressEvent (QKeyEvent * event) [slot]
Definition at line 457 of file cloudViewDialog.cpp.
References mCamera, mUi, and SHIFT_STEP.
Referenced by CloudViewDialog().
{
    Vector3dd shift(0.0, 0.0, 0.0);
    Matrix33 rotate(1.0);
    switch (event->key())
    {
        case Qt::Key_W:
                shift = Vector3dd(0, 0,  -SHIFT_STEP);
            break;
        case Qt::Key_A:
                rotate = Matrix33::RotationY(0.1);
            break;
        case Qt::Key_S:
                shift = Vector3dd(0, 0, SHIFT_STEP);
            break;
        case Qt::Key_D:
                rotate = Matrix33::RotationY(-0.1);
            break;
        case Qt::Key_R:
                rotate = Matrix33::RotationZ(-0.1);
            break;
        case Qt::Key_T:
                rotate = Matrix33::RotationZ(0.1);
            break;
        case Qt::Key_Up:
                shift = Vector3dd(0, SHIFT_STEP, 0);
            break;
        case Qt::Key_Left:
                shift = Vector3dd(SHIFT_STEP, 0, 0);
            break;
        case Qt::Key_Down:
                shift = Vector3dd(0, -SHIFT_STEP, 0);
            break;
        case Qt::Key_Right:
                shift = Vector3dd(-SHIFT_STEP, 0, 0);
            break;
    }
    mCamera = Matrix44(rotate, shift) * mCamera;
    mUi.widget->updateGL();
    //cout << "childKeyPressEvent" << endl;
}
void CloudViewDialog::childKeyReleaseEvent (QKeyEvent * event) [slot]
Definition at line 503 of file cloudViewDialog.cpp.
Referenced by CloudViewDialog().
{}
void CloudViewDialog::childMoveEvent (QMouseEvent * event) [slot]
Definition at line 394 of file cloudViewDialog.cpp.
References LEFT_CAMERA, mCamera, mCameraZoom, mTrack, mUi, ORTHO_FRONT, ORTHO_LEFT, ORTHO_TOP, PINHOLE_AT_0, and RIGHT_CAMERA.
Referenced by CloudViewDialog().
{
    uint32_t buttons = event->buttons();
    if (buttons & Qt::LeftButton)
    {
        double xs = (event->x() - mTrack.x()) / 500.0;
        double ys = (event->y() - mTrack.y()) / 500.0;
        mCamera = Matrix33::RotationY( xs) * mCamera;
        mCamera = Matrix33::RotationX(-ys) * mCamera;
    }
    if (buttons & Qt::MidButton)
    {
        double xs = (event->x() - mTrack.x()) /*/ 10.0*/;
        double ys = (event->y() - mTrack.y()) /*/ 10.0*/;
        Vector3dd shift(xs, ys, 0);
        switch (mUi.cameraTypeBox->currentIndex())
        {
            case ORTHO_TOP:
            case ORTHO_LEFT:
            case ORTHO_FRONT:
               shift *= (1.0 / mCameraZoom);
               break;
            default:
            case PINHOLE_AT_0:
            case LEFT_CAMERA:
            case RIGHT_CAMERA:
               break;
        }
        mCamera = Matrix44(Matrix33(1.0), shift) * mCamera;
    }
    if (buttons & Qt::RightButton)
    {
        double xs = (event->x() - mTrack.x()) / 10.0;
        // double ys = (event->y() - track.y()) / 10.0;
        mCamera = Matrix44(Matrix33(1.0), Vector3dd(0, 0, xs)) * mCamera;
    }
    /*xRot += (event->x() - track.x()) * 3.0;
    yRot += (event->y() - track.y()) * 3.0;*/
    mTrack = event->pos();
    mUi.widget->updateGL();
}
void CloudViewDialog::childPressEvent (QMouseEvent * event) [slot]
Definition at line 446 of file cloudViewDialog.cpp.
References mIsTracking, and mTrack.
Referenced by CloudViewDialog().
{
    mIsTracking = 1;
    mTrack = event->pos();
}
void CloudViewDialog::childReleaseEvent (QMouseEvent * event) [slot]
Definition at line 452 of file cloudViewDialog.cpp.
References mIsTracking.
Referenced by CloudViewDialog().
{
    mIsTracking = 0;
}
void CloudViewDialog::childWheelEvent (QWheelEvent * event) [slot]
Definition at line 199 of file cloudViewDialog.cpp.
References zoom().
Referenced by CloudViewDialog().
{
    double delta = event->delta();
    zoom(delta);
}
void CloudViewDialog::downRotate () [slot]
Definition at line 152 of file cloudViewDialog.cpp.
References mCamera, mUi, and ROTATE_STEP.
Referenced by CloudViewDialog().
{
    mCamera *= Matrix33::RotationX(-ROTATE_STEP);
    mUi.widget->updateGL();
}
void CloudViewDialog::initializeGLSlot () [slot]
Definition at line 512 of file cloudViewDialog.cpp.
References drawCircle(), corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBufferParams::h, mFancyTexture, TreeSceneController::mObject, TreeSceneModel::mTopItem, mTreeModel, mUi, resetCameraPos(), corecvs::AbstractBufferParams::stride, and corecvs::AbstractBufferParams::w.
Referenced by CloudViewDialog().
{
    qDebug() << "GL Init called" << endl;
    resetCameraPos();
    mUi.widget->qglClearColor(Qt::black);
    glShadeModel(GL_FLAT);
    glEnable(GL_DEPTH_TEST);
    glDisable(GL_CULL_FACE);
    glEnable(GL_TEXTURE_2D);
    /*Prepare a fancy texture*/
    glGenTextures( 1, &mFancyTexture );
    glBindTexture( GL_TEXTURE_2D, mFancyTexture );
    const int imageWidth  = 128;
    const int imageHeight = 128;
    RGB24Buffer textureBuffer(imageHeight, imageWidth, RGBColor::Blue());
    for (int i = 1; i < 8; i++)
    {
        for (int j = 1; j < 8; j++)
        {
            AbstractPainter<RGB24Buffer>(&textureBuffer).drawCircle(i * 16, j * 16, 5, RGBColor::Yellow());
        }
    }
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    /* TODO: Move this to GLTools */
    GLint oldStride;
    glGetIntegerv(GL_UNPACK_ROW_LENGTH, &oldStride);
    glPixelStorei(GL_UNPACK_ROW_LENGTH, textureBuffer.stride);
    glTexImage2D (GL_TEXTURE_2D, 0, GL_RGB, textureBuffer.w, textureBuffer.h, 0, GL_RGBA, GL_UNSIGNED_BYTE, &(textureBuffer.element(0,0)));
    glPixelStorei(GL_UNPACK_ROW_LENGTH, oldStride);
    glDisable(GL_TEXTURE_2D);
    if (mTreeModel.mTopItem != NULL &&
        !mTreeModel.mTopItem->mObject.isNull())
    {
        mTreeModel.mTopItem->mObject->prepareMesh(this);
    }
}
void CloudViewDialog::keyPressEvent (QKeyEvent * event) [virtual, slot]
Reimplemented from ViAreaWidget.
Definition at line 506 of file cloudViewDialog.cpp.
{}
void CloudViewDialog::keyReleaseEvent (QKeyEvent * event) [virtual, slot]
Reimplemented from ViAreaWidget.
Definition at line 509 of file cloudViewDialog.cpp.
{}
void CloudViewDialog::leftRotate () [slot]
Definition at line 164 of file cloudViewDialog.cpp.
References mCamera, mUi, and ROTATE_STEP.
Referenced by CloudViewDialog().
{
    mCamera *= Matrix33::RotationY( ROTATE_STEP);
    mUi.widget->updateGL();
}
void CloudViewDialog::loadMesh () [slot]
Definition at line 733 of file cloudViewDialog.cpp.
References addSubObject(), in, and PLYLoader::loadPLY().
Referenced by CloudViewDialog().
{
    QString fileName = QFileDialog::getOpenFileName(
      this,
      tr("Load 3D Model"),
      ".",
      tr("3D Model (*.ply)"));
    Mesh3DScene *mesh = new Mesh3DScene();
    ifstream file;
    file.open(fileName.toAscii().data(), ios::in);
    if (file.fail())
    {
        qDebug() << "Can't open property list file" << endl;
        return;
    }
    PLYLoader loader;
    if (loader.loadPLY(file, *mesh) != 0)
    {
       qDebug() << "CloudViewDialog::Unable to load mesh";
       file.close();
       return;
    }
    QFileInfo fileInfo(fileName);
    addSubObject(fileInfo.baseName(), QSharedPointer<Scene3D>(mesh));
}
void CloudViewDialog::loadParameters () [slot]
Definition at line 785 of file cloudViewDialog.cpp.
References TreeSceneController::accept(), TreeSceneModel::mTopItem, and mTreeModel.
{
    qDebug() << "Loading cloudview state";
    SettingsGetter visitor("cloud.ini", "root");
    mTreeModel.mTopItem->accept(visitor);
    /*for (unsigned i = 0; i < mControllers.size(); i++)
    {
        if (mControllers[i] == NULL)
            continue;
        visitor.settings()->beginGroup(QString("Sub-object%1").arg(i));
            mControllers[i]->accept(visitor);
        visitor.settings()->endGroup();
    }*/
//    QSettings settings("cloud.ini", QSettings::IniFormat);
}
void ViAreaWidget::mouseDoubleClickEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 35 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mouseMoveEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 16 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mousePressEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 22 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, ViAreaWidget::notifyParentMouseMove(), and ViAreaWidget::notifyParentMousePress().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
    emit notifyParentMousePress(event);
}
void ViAreaWidget::mouseReleaseEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 41 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseRelease().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseRelease(event);
}
void ViAreaWidget::notifyKeyPressEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyPressEvent().
void ViAreaWidget::notifyKeyReleaseEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyReleaseEvent().
void ViAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog(), ViAreaWidget::mouseDoubleClickEvent(), ViAreaWidget::mouseMoveEvent(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::mouseReleaseEvent().
void ViAreaWidget::notifyParentResize (QResizeEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog(), and ViAreaWidget::resizeEvent().
void ViAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog(), and ViAreaWidget::wheelEvent().
void ViAreaWidget::paintEvent (QPaintEvent * event) [virtual, inherited]
Reimplemented in ImageWidget.
Definition at line 10 of file viAreaWidget.cpp.
References ViAreaWidget::askParentRepaint(), and ViAreaWidget::mForwardEvents.
{
    if (!mForwardEvents) return;
    emit askParentRepaint(event, this);
}
void CloudViewDialog::repaintGLSlot () [slot]
Definition at line 561 of file cloudViewDialog.cpp.
References FACE_CAMERA, OpenGLTools::glMultMatrixMatrix44(), mCamera, TreeSceneController::mObject, TreeSceneModel::mTopItem, mTreeModel, mUi, resetCamera(), and resetCameraPos().
Referenced by CloudViewDialog().
{
    if (mUi.cameraTypeBox->currentIndex() == FACE_CAMERA)
    {
        resetCamera();
        resetCameraPos();
    }
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
    OpenGLTools::glMultMatrixMatrix44(mCamera);
//    qDebug("=== Starting draw === ");
    if (mTreeModel.mTopItem != NULL &&
        !mTreeModel.mTopItem->mObject.isNull())
    {
        mTreeModel.mTopItem->mObject->draw(this);
    }
//    qDebug("=== Ending draw === ");
    //OpenGLTools::drawOrts(10.0, 1.0);
    glDisable(GL_TEXTURE_2D);
}
void CloudViewDialog::resetCamera () [slot]
Definition at line 263 of file cloudViewDialog.cpp.
References DETECTED_PERSON, FACE_CAMERA, OpenGLTools::glMultMatrixMatrix44(), OpenGLTools::gluPerspective(), OpenGLTools::gluPerspectivePosZ(), LEFT_CAMERA, mCameraZoom, mRectificationResult, mScenes, mUi, ORTHO_FRONT, ORTHO_LEFT, ORTHO_TOP, PINHOLE_AT_0, corecvs::radToDeg(), RIGHT_CAMERA, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by repaintGLSlot(), resetCameraSlot(), resizeGLSlot(), and zoom().
{
    float farPlane = mUi.frustumFarBox->value();
    int width  = mUi.widget->width();
    int height = mUi.widget->height();
    double aspect = (double)width / (double)height;
    glViewport(0, 0, width, height);
    glMatrixMode(GL_PROJECTION);
    switch(mUi.cameraTypeBox->currentIndex())
    {
        case ORTHO_TOP:
        case ORTHO_FRONT:
        case ORTHO_LEFT:
            glLoadIdentity();
            glOrtho(-width / 2.0, width / 2.0, height / 2.0, -height / 2.0, farPlane, -farPlane);
            glScaled(mCameraZoom, mCameraZoom, mCameraZoom);
         //   glRotated(90, 1.0, 0.0, 0.0);
            break;
        case PINHOLE_AT_0:
        default:
        {
            glLoadIdentity();
            OpenGLTools::gluPerspectivePosZ(60.0f, aspect, 1.0f, farPlane);
            break;
        }
        case LEFT_CAMERA:
        {
            glLoadIdentity();
            double fov = mRectificationResult->leftCamera.getVFov();
            OpenGLTools::gluPerspectivePosZ(radToDeg(fov), aspect, 1.0f, farPlane);
            break;
        }
        case RIGHT_CAMERA:
        {
            glLoadIdentity();
            double fov = mRectificationResult->rightCamera.getVFov();
            OpenGLTools::gluPerspectivePosZ(radToDeg(fov), aspect, 1.0f, farPlane);
            break;
        }
        case FACE_CAMERA:
        {
#if GOOPEN
            glLoadIdentity();
            FaceMesh *faceMesh = static_cast<FaceMesh *>(mScenes[DETECTED_PERSON].data());
            if (faceMesh == NULL)
            {
                OpenGLTools::gluPerspective(60.0f, aspect, 1.0f, farPlane);
                break;
            }
            //printf("Setting a projection Matrix to face\n");
            Vector3dd cameraPos = faceMesh->mPerson.object.position3D;
            printf("Camera is at %lf %lf %lf\n", cameraPos.x(), cameraPos.y(), cameraPos.z());
            Vector3dd windowP  = Vector3dd(-35, 220, 0);
            Vector3dd windowX  = Vector3dd(510,   0, 0);
            Vector3dd windowY  = Vector3dd(  0, 320, 0);
            Vector3dd windowP1 = windowP + windowX + windowY;
           /* Plane3d plane = Plane3d::FromPointAndVectors(windowP, windowX, windowY);
            Vector3dd projected = plane.projectPointTo(cameraPos);
            Vector3dd dir = projected - cameraPos;*/
            double invDist = 1.0 / cameraPos.z();
            double zNear = 0.9;
            double zFar  = 2000.0;
            double zDepth = zNear - zFar;
            double zToZ = ((zFar + zNear)  / zDepth) * invDist;
            double wToZ = (2 *zFar * zNear / zDepth) * invDist;
            Matrix44 matrix (
                   1.0, 0.0 ,      0.0,  0.0,
                   0.0, 1.0 ,      0.0,  0.0,
                   0.0, 0.0 ,     zToZ, wToZ,
                   0.0, 0.0 , -invDist, 0.0
               );
            cout << "Matrix projective part:" << endl;
            cout << matrix << endl;
            /*Projecting window top corner*/
            Vector3dd relativeP = windowP  - cameraPos;
            Vector3dd zeroProj = matrix * relativeP;
            cout << "Corner 1 is:" << endl;
            cout << "  3D       "  << relativeP << endl;
            cout << "  Projected"  << zeroProj << endl;
            Vector3dd intProj  = matrix * (windowP1 - cameraPos);
            cout << "Corner 2 is:" <<  intProj << endl;
            double dx = intProj.x() - zeroProj.x();
            double dy = intProj.y() - zeroProj.y();
            printf("Size is %lf %lf\n", dx, dy);
            matrix =
                Matrix44(Matrix33::Scale3(Vector3dd(-2.0 / dx, -2.0 / dy, 1.0))) *
                Matrix44::Shift(-zeroProj.x(), -zeroProj.y(), 0) *
                matrix;
            Vector3dd testIn  = ((windowP1 + windowP) / 2.0) - cameraPos;
            Vector3dd testOut = matrix * testIn;
            cout << "Test input :" << testIn  << endl;
            cout << "Test result:" << testOut << endl;
            cout << "Final Matrix:" << endl;
            cout << matrix << endl;
            OpenGLTools::glMultMatrixMatrix44(matrix);
            glViewport(0, 0, width, height);
            break;
#endif
        }
    }
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
}
void CloudViewDialog::resetCameraPos () [slot]
Definition at line 207 of file cloudViewDialog.cpp.
References corecvs::degToRad(), DETECTED_PERSON, FACE_CAMERA, corecvs::Matrix44::inverted(), LEFT_CAMERA, mCamera, mRectificationResult, mScenes, mUi, ORTHO_FRONT, ORTHO_LEFT, ORTHO_TOP, PINHOLE_AT_0, RIGHT_CAMERA, setZoom(), START_X, START_Y, and START_Z.
Referenced by initializeGLSlot(), repaintGLSlot(), and resetCameraSlot().
{
    switch(mUi.cameraTypeBox->currentIndex())
    {
        case ORTHO_TOP:
            mCamera = Matrix44(Matrix33::RotationX(degToRad(90)), Vector3dd(0.0,0.0,0.0));
            break;
        case ORTHO_LEFT:
            mCamera = Matrix44(Matrix33::RotationY(degToRad(-90)), Vector3dd(0.0,0.0,0.0));
            break;
        case ORTHO_FRONT:
            mCamera = Matrix44(Matrix33(1.0), Vector3dd(0.0,0.0,0.0));
            break;
        default:
        case PINHOLE_AT_0:
            mCamera = Matrix44(Matrix33(1.0), Vector3dd( START_X, START_Y, START_Z));
            break;
        case LEFT_CAMERA:
            mCamera = Matrix44(mRectificationResult->decomposition.rotation) * Matrix44::Shift(mRectificationResult->getCameraShift());
            mCamera = mCamera.inverted();
            break;
        case RIGHT_CAMERA:
            mCamera = Matrix44(Matrix33(1.0), Vector3dd(0.0,0.0,0.0));
            break;
        case FACE_CAMERA:
        {
#if GOOPEN
            mCamera = Matrix44(Matrix33(1.0), Vector3dd(0.0,0.0,0.0));
            FaceMesh *faceMesh = static_cast<FaceMesh *>(mScenes[DETECTED_PERSON].data());
            if (faceMesh == NULL) {
                break;
            }
            printf("Setting a projection Matrix to face\n");
            Vector3dd cameraPos = faceMesh->mPerson.object.position3D;
            /* Move to zero */
            Matrix44 shiftCamToZero = Matrix44::Shift(-cameraPos);
            Matrix44 projector = shiftCamToZero;
            mCamera = Matrix44(Matrix33(1.0), -cameraPos);
#endif
        }
            break;
    }
    setZoom(1.0);
}
void CloudViewDialog::resetCameraSlot () [slot]
Definition at line 255 of file cloudViewDialog.cpp.
References mUi, resetCamera(), and resetCameraPos().
Referenced by CloudViewDialog().
{
    resetCameraPos();
    resetCamera();
    qDebug() << "Resetting camera";
    mUi.widget->updateGL();
}
void ViAreaWidget::resizeEvent (QResizeEvent * event) [virtual, inherited]
Definition at line 29 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentResize().
{
    if (!mForwardEvents) return;
    emit notifyParentResize(event);
}
void CloudViewDialog::resizeGLSlot (int width, int height) [slot]
Definition at line 598 of file cloudViewDialog.cpp.
References resetCamera().
Referenced by CloudViewDialog(), and updateCameraMatrix().
{
    resetCamera();
}
void CloudViewDialog::rightRotate () [slot]
Definition at line 170 of file cloudViewDialog.cpp.
References mCamera, mUi, and ROTATE_STEP.
Referenced by CloudViewDialog().
{
    mCamera *= Matrix33::RotationY(-ROTATE_STEP);
    mUi.widget->updateGL();
}
void CloudViewDialog::saveParameters () [slot]
Definition at line 768 of file cloudViewDialog.cpp.
References TreeSceneController::accept(), TreeSceneModel::mTopItem, and mTreeModel.
{
    qDebug() << "Saving cloudview state";
    SettingsSetter visitor("cloud.ini", "root");
    mTreeModel.mTopItem->accept(visitor);
  /*  for (unsigned i = 0; i < mControllers.size(); i++)
    {
        if (mControllers[i] == NULL)
            continue;
        visitor.settings()->beginGroup(QString("Sub-object%1").arg(i));
            mControllers[i]->accept(visitor);
        visitor.settings()->endGroup();
    }*/
}
void CloudViewDialog::savePointsPCD () [slot]
Definition at line 691 of file cloudViewDialog.cpp.
References MAIN_SCENE, and mScenes.
{
    static int count = 0;
    qDebug("Dump slot called...\n");
    if (mScenes[MAIN_SCENE].isNull())
    {
        return;
    }
    char name[100];
    snprintf2buf(name, "exported%d.pcd", count);
    count++;
    qDebug("Dumping current scene to <%s>...", name);
    fstream file(name, fstream::out);
    mScenes[MAIN_SCENE]->dumpPCD(file);
    file.close();
    qDebug("done\n");
}
void CloudViewDialog::savePointsPLY () [slot]
Definition at line 712 of file cloudViewDialog.cpp.
References MAIN_SCENE, and mScenes.
{
    static int count = 0;
    qDebug("Dump slot called...\n");
    if (mScenes[MAIN_SCENE].isNull())
    {
        return;
    }
    char name[100];
    snprintf2buf(name, "exported%d.ply", count);
    count++;
    qDebug("Dumping current scene to <%s>...", name);
    fstream file(name, fstream::out);
    mScenes[MAIN_SCENE]->dumpPLY(file);
    file.close();
    qDebug("done\n");
}
void CloudViewDialog::setNewCameraImage (QSharedPointer< QImage > texture, int cameraId = Frames::RIGHT_FRAME)
Definition at line 661 of file cloudViewDialog.cpp.
References mCameraImage, mCameraTexture, mUi, and texture().
{
    if (texture.isNull()) {
        return;
    }
    //SYNC_PRINT(("void CloudViewDialog::setNewCameraImage () called\n"));
    if (mCameraTexture[cameraId] != (unsigned)-1)
    {
        //SYNC_PRINT(("Deleting old texture\n"));
        mUi.widget->deleteTexture(mCameraTexture[cameraId]);
        mCameraTexture[cameraId] = -1;
    }
    mCameraImage[cameraId] = texture;
    //mCameraTexture[cameraId] = mUi.widget->bindTexture(*texture.data(), GL_TEXTURE_2D, GL_RGBA);
    mUi.widget->update();
}
void CloudViewDialog::setNewRectificationResult (QSharedPointer< RectificationResult > rectificationResult)
Definition at line 643 of file cloudViewDialog.cpp.
References CAMERA_PAIR, mRectificationResult, mUi, setNewScenePointer(), and Mesh3DScene::setParameters().
{
    if (rectificationResult.isNull())
    {
        return;
    }
    mRectificationResult = rectificationResult;
    StereoCameraScene *cameraModels = new StereoCameraScene(*(mRectificationResult.data()));
    Draw3dCameraParameters parameters;
    cameraModels->setParameters(&parameters);
    setNewScenePointer(QSharedPointer<Scene3D>(cameraModels), CAMERA_PAIR);
    mUi.widget->update();
}
void CloudViewDialog::setNewScenePointer (QSharedPointer< Scene3D > scene, int sceneId = MAIN_SCENE)
Definition at line 603 of file cloudViewDialog.cpp.
References ADDITIONAL_SCENE, addSubObject(), CAMERA_PAIR, CLUSTER_SWARM, CLUSTER_ZONE, CONTROL_ZONE, DETECTED_PERSON, DISP_CONTROL_ZONE, DISP_PREDICTED_CONTROL_ZONE, GAPER_ZONE, HEAD_SEARCH_ZONE, MAIN_SCENE, mSceneControllers, mScenes, mUi, and TreeSceneController::replaceScene().
Referenced by setNewRectificationResult().
{
/*    if (newScene.isNull()) {
        return;
    }*/
    if (mUi.pauseButton->isChecked())
    {
        return;
    }
    bool isFirst = (mSceneControllers[sceneId] == NULL);
    if (isFirst && !newScene.isNull())
    {
        const char *name = "internal";
        switch (sceneId) {
        case MAIN_SCENE                 : name = "3d Main";          break;
        case ADDITIONAL_SCENE           : name = "3d Additional";    break;
        case CAMERA_PAIR                : name = "Camera Pair";      break;
        case GAPER_ZONE                 : name = "Gaper zone";       break;
        case CONTROL_ZONE               : name = "Control zone";     break;
        case DETECTED_PERSON            : name = "Detected person";  break;
        case DISP_CONTROL_ZONE          : name = "Control Zone";     break;
        case DISP_PREDICTED_CONTROL_ZONE: name = "Predicted Zone";   break;
        case CLUSTER_ZONE               : name = "Cluster zone";     break;
        case CLUSTER_SWARM              : name = "Cluster swarm";    break;
        case HEAD_SEARCH_ZONE           : name = "Head search zone"; break;
        default:
            break;
        };
        mSceneControllers[sceneId] = addSubObject(name, newScene, true);
    }
    mSceneControllers[sceneId]->replaceScene(newScene);
    mScenes[sceneId] = newScene;
    mUi.widget->update();
}
void CloudViewDialog::setZoom (double value) [protected]
Definition at line 176 of file cloudViewDialog.cpp.
References mCameraZoom, and mUi.
Referenced by resetCameraPos(), and zoom().
{
    mCameraZoom = value;
    mUi.zoomLabel->setText(QString("x %1").arg(mCameraZoom));
}
GLuint CloudViewDialog::texture (int cameraId)
Definition at line 681 of file cloudViewDialog.cpp.
References mCameraImage, mCameraTexture, and mUi.
Referenced by Scene3D::commonSetup(), and setNewCameraImage().
{
    if (mCameraTexture[cameraId] == (GLuint)-1 && !mCameraImage[cameraId].isNull())
    {
            mCameraTexture[cameraId] = mUi.widget->bindTexture(*mCameraImage[cameraId].data(), GL_TEXTURE_2D, GL_RGBA);
    }
    return mCameraTexture[cameraId];
}
void CloudViewDialog::updateCameraMatrix () [slot]
Definition at line 588 of file cloudViewDialog.cpp.
References mUi, and resizeGLSlot().
Referenced by CloudViewDialog().
{
    resizeGLSlot(mUi.widget->width(), mUi.widget->height());
}
void CloudViewDialog::updateHelperObjects () [slot]
Definition at line 593 of file cloudViewDialog.cpp.
References mUi.
{
    mUi.widget->update();
}
void CloudViewDialog::upRotate () [slot]
Definition at line 158 of file cloudViewDialog.cpp.
References mCamera, mUi, and ROTATE_STEP.
Referenced by CloudViewDialog().
{
    mCamera *= Matrix33::RotationX( ROTATE_STEP);
    mUi.widget->updateGL();
}
void ViAreaWidget::wheelEvent (QWheelEvent * event) [virtual, inherited]
Definition at line 47 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentWheelEvent().
{
    if (!mForwardEvents) return;
    emit notifyParentWheelEvent(event);
}
void CloudViewDialog::zoom (int delta) [protected]
Definition at line 182 of file cloudViewDialog.cpp.
References mCameraZoom, mUi, resetCamera(), setZoom(), and ZOOM_DIVISION.
Referenced by childWheelEvent(), zoomIn(), and zoomOut().
{
    setZoom(mCameraZoom * exp(delta / CloudViewDialog::ZOOM_DIVISION));
    resetCamera();
    mUi.widget->updateGL();
}
void CloudViewDialog::zoomIn () [slot]
Definition at line 189 of file cloudViewDialog.cpp.
References zoom().
Referenced by CloudViewDialog().
{
    zoom(+1);
}
void CloudViewDialog::zoomOut () [slot]
Definition at line 194 of file cloudViewDialog.cpp.
References zoom().
Referenced by CloudViewDialog().
{
    zoom(-1);
}
Member Data Documentation
Matrix44 CloudViewDialog::mCamera
Definition at line 121 of file cloudViewDialog.h.
Referenced by childKeyPressEvent(), childMoveEvent(), downRotate(), Scene3DMouse::drawMyself(), Scene3D::initDecalState(), leftRotate(), repaintGLSlot(), resetCameraPos(), rightRotate(), and upRotate().
QSharedPointer<QImage> CloudViewDialog::mCameraImage[Frames::MAX_INPUTS_NUMBER]
Definition at line 113 of file cloudViewDialog.h.
Referenced by setNewCameraImage(), and texture().
GLuint CloudViewDialog::mCameraTexture[Frames::MAX_INPUTS_NUMBER] [private]
Definition at line 151 of file cloudViewDialog.h.
Referenced by CloudViewDialog(), setNewCameraImage(), and texture().
double CloudViewDialog::mCameraZoom
Definition at line 122 of file cloudViewDialog.h.
Referenced by childMoveEvent(), Scene3DMouse::drawMyself(), resetCamera(), setZoom(), and zoom().
GLuint CloudViewDialog::mFancyTexture
Definition at line 149 of file cloudViewDialog.h.
Referenced by CloudViewDialog(), Mesh3DScene::drawMyself(), and initializeGLSlot().
int CloudViewDialog::mIsTracking [protected]
Definition at line 142 of file cloudViewDialog.h.
Referenced by childPressEvent(), and childReleaseEvent().
QSharedPointer<RectificationResult> CloudViewDialog::mRectificationResult
Definition at line 112 of file cloudViewDialog.h.
Referenced by Scene3D::commonSetup(), resetCamera(), resetCameraPos(), and setNewRectificationResult().
TreeSceneController* CloudViewDialog::mSceneControllers[SCENE_NUMBER]
Definition at line 111 of file cloudViewDialog.h.
Referenced by CloudViewDialog(), and setNewScenePointer().
QSharedPointer<Scene3D> CloudViewDialog::mScenes[SCENE_NUMBER]
Definition at line 110 of file cloudViewDialog.h.
Referenced by resetCamera(), resetCameraPos(), savePointsPCD(), savePointsPLY(), and setNewScenePointer().
QPoint CloudViewDialog::mTrack [protected]
Definition at line 143 of file cloudViewDialog.h.
Referenced by childMoveEvent(), and childPressEvent().
TreeSceneModel CloudViewDialog::mTreeModel [protected]
Definition at line 145 of file cloudViewDialog.h.
Referenced by addSubObject(), CloudViewDialog(), initializeGLSlot(), loadParameters(), repaintGLSlot(), and saveParameters().
Ui_CloudViewDialogClass CloudViewDialog::mUi
Definition at line 91 of file cloudViewDialog.h.
Referenced by childKeyPressEvent(), childMoveEvent(), CloudViewDialog(), downRotate(), initializeGLSlot(), leftRotate(), repaintGLSlot(), resetCamera(), resetCameraPos(), resetCameraSlot(), rightRotate(), setNewCameraImage(), setNewRectificationResult(), setNewScenePointer(), setZoom(), texture(), updateCameraMatrix(), updateHelperObjects(), upRotate(), and zoom().
const double CloudViewDialog::ROTATE_STEP = 0.05 [static]
Definition at line 33 of file cloudViewDialog.h.
Referenced by downRotate(), leftRotate(), rightRotate(), and upRotate().
const double CloudViewDialog::SHIFT_STEP = 10.0 [static]
Definition at line 35 of file cloudViewDialog.h.
Referenced by childKeyPressEvent().
const double CloudViewDialog::START_X = 0 [static]
Definition at line 38 of file cloudViewDialog.h.
Referenced by resetCameraPos().
const double CloudViewDialog::START_Y = 0 [static]
Definition at line 39 of file cloudViewDialog.h.
Referenced by resetCameraPos().
const double CloudViewDialog::START_Z = 1 * Grid3DScene::GRID_SIZE * Grid3DScene::GRID_STEP [static]
Definition at line 40 of file cloudViewDialog.h.
Referenced by CloudViewDialog(), and resetCameraPos().
const double CloudViewDialog::ZOOM_DIVISION = 1000.0 [static]
Definition at line 34 of file cloudViewDialog.h.
Referenced by zoom().
The documentation for this class was generated from the following files:
utils/uis/cloudview/cloudViewDialog.h
utils/uis/cloudview/cloudViewDialog.cpp