DeepView: corecvs::EssentialEstimator Class Reference
corecvs::EssentialEstimator Class Reference
#include <essentialEstimator.h>
Classes
class CostFunction7to1
Normalized cost function try to trick the optimization algorithms by re-normalising the direction and the rotation quaternion every time it is used.
class CostFunction7toN
Function that returned.
class CostFunctionBase
This is a class that describe the translation form state in form of the array of doubles into an Essential matrix.
class NormalizeFunction
Function that normalizes the current state.
Public Types
enum OptimisationMethod {
METHOD_SVD_LSE, METHOD_GRAD_DESC, METHOD_MARQ_LEV, METHOD_CLASSIC_KALMAN,
METHOD_ITERATIVE_KALMAN, METHOD_GRAD_DESC_RM, METHOD_LAST, METHOD_DEFAULT = METHOD_MARQ_LEV
}
Public Member Functions
EssentialMatrix getEssential (const vector< Correspondance * > &samples, OptimisationMethod method=METHOD_DEFAULT)
EssentialMatrix getEssentialLSE (const vector< Correspondance * > &samples)
Both essential and fundamental matrices can be searched with 8 point algorithm.
EssentialMatrix getEssentialLM (const vector< Correspondance * > &samples)
EssentialMatrix getEssentialGrad (const vector< Correspondance * > &samples)
EssentialMatrix getEssentialGradToRm (const vector< Correspondance * > &samples)
EssentialMatrix getEssentialSimpleKalman (const vector< Correspondance * > &samples)
EssentialEstimator ()
virtual ~EssentialEstimator ()
Detailed Description
Definition at line 18 of file essentialEstimator.h.
Member Enumeration Documentation
enum corecvs::EssentialEstimator::OptimisationMethod
Enumerator:
METHOD_SVD_LSE
METHOD_GRAD_DESC
METHOD_MARQ_LEV
METHOD_CLASSIC_KALMAN
METHOD_ITERATIVE_KALMAN
METHOD_GRAD_DESC_RM
METHOD_LAST
METHOD_DEFAULT
Definition at line 22 of file essentialEstimator.h.
{
        METHOD_SVD_LSE,
        METHOD_GRAD_DESC,
        METHOD_MARQ_LEV,
        METHOD_CLASSIC_KALMAN,
        METHOD_ITERATIVE_KALMAN,
        METHOD_GRAD_DESC_RM,
        METHOD_LAST,
        METHOD_DEFAULT = METHOD_MARQ_LEV
    };
Constructor & Destructor Documentation
corecvs::EssentialEstimator::EssentialEstimator ()
Definition at line 22 of file essentialEstimator.cpp.
{
}
corecvs::EssentialEstimator::~EssentialEstimator () [virtual]
Definition at line 582 of file essentialEstimator.cpp.
{
}
Member Function Documentation
EssentialMatrix corecvs::EssentialEstimator::getEssential (const vector< Correspondance * > & samples, OptimisationMethod method = METHOD_DEFAULT)
Definition at line 377 of file essentialEstimator.cpp.
References getEssentialGrad(), getEssentialLM(), getEssentialLSE(), getEssentialSimpleKalman(), METHOD_CLASSIC_KALMAN, METHOD_GRAD_DESC, METHOD_GRAD_DESC_RM, METHOD_ITERATIVE_KALMAN, METHOD_MARQ_LEV, and METHOD_SVD_LSE.
Referenced by corecvs::IterativeEstimator::getEssential(), corecvs::EssentialEstimator::CostFunction7to1::getJacobian(), corecvs::Model8Point::Model8Point(), corecvs::EssentialEstimator::CostFunction7to1::operator()(), and corecvs::EssentialEstimator::CostFunction7toN::operator()().
{
    switch (method)
    {
        case METHOD_SVD_LSE:
            return getEssentialLSE(samples);
        case METHOD_GRAD_DESC:
            return getEssentialGrad(samples);
        case METHOD_MARQ_LEV:
            return getEssentialLM(samples);
        case METHOD_CLASSIC_KALMAN:
            return getEssentialSimpleKalman(samples);
        case METHOD_ITERATIVE_KALMAN:
//            return getEssentialKalman(samples);
        case METHOD_GRAD_DESC_RM:
//            return getEssentialGradToRm(samples);
        default:
            return getEssentialLM(samples);
    }
    return EssentialMatrix();
}
EssentialMatrix corecvs::EssentialEstimator::getEssentialGrad (const vector< Correspondance * > & samples)
Definition at line 168 of file essentialEstimator.cpp.
References corecvs::GradientDescent::f, corecvs::EssentialEstimator::CostFunctionBase::getEssential(), corecvs::GradientDescent::lambda, corecvs::GradientDescent::maxIterations, corecvs::GradientDescent::minimise(), corecvs::GradientDescent::normalisation, corecvs::EssentialEstimator::CostFunctionBase::packState(), corecvs::GenericQuaternion< ElementType >::RotationIdentity(), and corecvs::EssentialEstimator::CostFunctionBase::VECTOR_SIZE.
Referenced by getEssential().
{
    CostFunction7to1 costFunction(&samples);
    NormalizeFunction normalise;
    GradientDescent GDfit;
    GDfit.f = &costFunction;
    GDfit.normalisation = &normalise;
    GDfit.maxIterations = 10000000;
    GDfit.lambda = 0.003;
    vector<double> input(CostFunctionBase::VECTOR_SIZE);
    Quaternion rotation    = Quaternion::RotationIdentity();
    Vector3dd  translation = Vector3dd(-1.0, 0.0, 0.0);
    CostFunctionBase::packState(&input[0], rotation, translation);
    vector<double> optInput = GDfit.minimise(input);
    return CostFunctionBase::getEssential(&optInput[0]);
}
EssentialMatrix corecvs::EssentialEstimator::getEssentialGradToRm (const vector< Correspondance * > & samples)
Definition at line 188 of file essentialEstimator.cpp.
References corecvs::GradientDescentRnToRm::f, corecvs::GradientDescentRnToRm::fit(), corecvs::EssentialEstimator::CostFunctionBase::getEssential(), corecvs::GradientDescentRnToRm::lambda, corecvs::GradientDescentRnToRm::maxIterations, corecvs::GradientDescentRnToRm::normalisation, corecvs::EssentialEstimator::CostFunctionBase::packState(), corecvs::GenericQuaternion< ElementType >::RotationIdentity(), and corecvs::EssentialEstimator::CostFunctionBase::VECTOR_SIZE.
{
    CostFunction7toN costFunction(&samples);
    NormalizeFunction normalise;
    GradientDescentRnToRm GDfit;
    GDfit.f = &costFunction;
    GDfit.normalisation = &normalise;
    GDfit.maxIterations = 1000000;
    GDfit.lambda = 0.003;
    vector<double> input(CostFunctionBase::VECTOR_SIZE);
    Quaternion rotation    = Quaternion::RotationIdentity();
    Vector3dd  translation = Vector3dd(-1.0, 0.0, 0.0);
    CostFunctionBase::packState(&input[0], rotation, translation);
    vector<double> output(samples.size());
    /* This is an overkill*/
    for (unsigned i = 0; i < output.size(); i++)
        output[i] = 0.0;
    vector<double> optInput = GDfit.fit(input, output);
    return CostFunctionBase::getEssential(&optInput[0]);
}
EssentialMatrix corecvs::EssentialEstimator::getEssentialLM (const vector< Correspondance * > & samples)
Definition at line 131 of file essentialEstimator.cpp.
References corecvs::LevenbergMarquardt::f, corecvs::LevenbergMarquardt::fit(), corecvs::EssentialEstimator::CostFunctionBase::getEssential(), corecvs::LevenbergMarquardt::lambdaFactor, corecvs::LevenbergMarquardt::maxIterations, corecvs::LevenbergMarquardt::normalisation, corecvs::EssentialEstimator::CostFunctionBase::packState(), corecvs::GenericQuaternion< ElementType >::RotationIdentity(), corecvs::LevenbergMarquardt::startLambda, and corecvs::EssentialEstimator::CostFunctionBase::VECTOR_SIZE.
Referenced by getEssential().
{
    CostFunction7toN costFunction(&samples);
    NormalizeFunction normalise;
    LevenbergMarquardt LMfit;
    LMfit.f = &costFunction;
    LMfit.normalisation = &normalise;
    LMfit.maxIterations = 100000;
    LMfit.startLambda = 10;
    LMfit.lambdaFactor = 20.0;
    vector<double> input(CostFunctionBase::VECTOR_SIZE);
    /* Left camera is in the negative direction of right camera */
    Quaternion rotation    = Quaternion::RotationIdentity();
    Vector3dd  translation = Vector3dd(-1.0, 0.0, 0.0);
    CostFunctionBase::packState(&input[0], rotation, translation);
    vector<double> output(samples.size());
    for (unsigned i = 0; i < samples.size(); i++)
        output[i] = 0.0;
    vector<double> optInput = LMfit.fit(input, output);
    PrinterVisitor visitor;
   /* cout << "Axis" << endl;
    CostFunctionBase::getRotationAxis(&optInput[0]).accept(visitor);
    cout << "Angle:" << endl;
    cout << radToDeg(CostFunctionBase::getRotationAngle(&optInput[0]))  << "deg" << endl;
    cout << "Baseline:" << endl;
    CostFunctionBase::getTranslation(&optInput[0]).accept(visitor);
*/
    return CostFunctionBase::getEssential(&optInput[0]);
}
EssentialMatrix corecvs::EssentialEstimator::getEssentialLSE (const vector< Correspondance * > & samples)
Both essential and fundamental matrices can be searched with 8 point algorithm.
             [ a_11   a_12  a_13 ]  [ x']    [ 0 ]
 [x, y ,1]   [ a_21   a_22  a_23 ]  [ y'] =  [ 0 ]
             [ a_31   a_32  a_33 ]  [ 1 ]    [ 0 ]
We reconstruct the model by LSE estimation.
Todo:
TODO Here the transform should be done to increase the precision. The choice should be centered to 0 and scaled to average of sqrt(2)
Definition at line 70 of file essentialEstimator.cpp.
References corecvs::Matrix33::a(), corecvs::Matrix::a(), corecvs::Matrix::svd(), ClusteringDirectionType::X, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by getEssential().
{
    Matrix X((int)samples.size(), 9);
    Matrix W(1,9);
    Matrix V(9,9);
    Matrix33 F(0.0);
    for (unsigned i = 0; i < samples.size(); i++)
    {
        Vector2dd first  = samples[i]->start;
        Vector2dd second = samples[i]->end;
        X.fillLineWithArgs(i,
        first.x() * second.x(), first.x() * second.y(), first.x(),
        first.y() * second.x(), first.y() * second.y(), first.y(),
        second.x(), second.y(),  1.0);
    }
#ifdef DEEP_TRACE
        X.print();
        cout << endl;
        fflush(stdout);
#endif
    /** \todo TODO Here the transform should be done to increase the precision.
     * The choice should be centered to 0 and scaled to average of sqrt(2) */
    Matrix::svd(&X, &W, &V);
#ifdef DEEP_TRACE
    printf("The singular values:\n");
    W.print();
    printf("\n");
#endif
    int min = -1;
    double minval = std::numeric_limits<double>::max();
    for (unsigned i = 0; i < 9; i ++)
    {
        if (W.a(0, i) <= minval)
        {
            min = i;
            minval = W.a(0, i);
        }
    }
    F = Matrix33(
        V.a(0,min), V.a(1,min), V.a(2,min),
        V.a(3,min), V.a(4,min), V.a(5,min),
        V.a(6,min), V.a(7,min), V.a(8,min)
    );
    if (F.a(2,1) < 0) {
        F = -F;
    }
    return EssentialMatrix(F);
}
EssentialMatrix corecvs::EssentialEstimator::getEssentialSimpleKalman (const vector< Correspondance * > & samples)
Definition at line 212 of file essentialEstimator.cpp.
References corecvs::EssentialEstimator::CostFunctionBase::getEssential(), corecvs::EssentialEstimator::CostFunctionBase::packState(), corecvs::ClassicKalman::predict(), corecvs::GenericQuaternion< ElementType >::RotationIdentity(), corecvs::ClassicKalman::update(), corecvs::EssentialEstimator::CostFunctionBase::VECTOR_SIZE, corecvs::ClassicKalman::x, corecvs::ClassicKalman::xPredicted, and corecvs::ClassicKalman::z.
Referenced by getEssential().
{
    IdentityFunction F(CostFunctionBase::VECTOR_SIZE);
    CostFunction7to1 H(&samples);
    NormalizeFunction N;
    // We know almost nothing about the essential matrix
    Matrix P(CostFunctionBase::VECTOR_SIZE, CostFunctionBase::VECTOR_SIZE, 500.0);
    // Our model evolution is precise
    Matrix Q(CostFunctionBase::VECTOR_SIZE, CostFunctionBase::VECTOR_SIZE, 0.0);
    // Our measurement is precise up to 2px.
    Matrix R(1,1, 2.0);
    Vector input(CostFunctionBase::VECTOR_SIZE);
    Quaternion rotation    = Quaternion::RotationIdentity();
    Vector3dd  translation = Vector3dd(-1.0, 0.0, 0.0);
    CostFunctionBase::packState(&input[0], rotation, translation);
    ClassicKalman kalmanFilter(
        &F,
        &H,
        Q,
        R,
        P,
        input);
    Vector normalised(CostFunctionBase::VECTOR_SIZE);
    static int maxIterations = 2500000;
    cout << "================== Starting Simple Kalman optimisation ================== " << endl;
    cout << "[" << flush;
    for (int step = 0; step < maxIterations; step++)
    {
        if ((step % ((maxIterations / 100) + 1) == 0))
        {
            cout << "#" << flush;
        }
        double measurement = 0.0;
        kalmanFilter.predict();
        N(kalmanFilter.xPredicted, normalised);
        kalmanFilter.xPredicted = normalised;
        kalmanFilter.z[0] = measurement;
        kalmanFilter.update();
    }
    cout << "]" << endl;
    return CostFunctionBase::getEssential(&kalmanFilter.x[0]);
}
The documentation for this class was generated from the following files:
core/rectification/essentialEstimator.h
core/rectification/essentialEstimator.cpp