DeepView: CannyParametersControlWidget Class Reference
CannyParametersControlWidget Class Reference
#include <cannyParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
CannyParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~CannyParametersControlWidget ()
CannyParameters * createParameters () const
void setParameters (const CannyParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_CannyParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file cannyParametersControlWidget.h.
Constructor & Destructor Documentation
CannyParametersControlWidget::CannyParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file cannyParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::CannyParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->shouldEdgeDetectCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->minimumThresholdSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->maximumThresholdSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
CannyParametersControlWidget::~CannyParametersControlWidget ()
Definition at line 28 of file cannyParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void CannyParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file cannyParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
CannyParameters * CannyParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 50 of file cannyParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    CannyParameters *result = new CannyParameters(
          mUi->shouldEdgeDetectCheckBox->isChecked()
        , mUi->minimumThresholdSpinBox->value()
        , mUi->maximumThresholdSpinBox->value()
    );
    return result;
}
virtual BaseReflectionStatic* CannyParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 25 of file cannyParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void CannyParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 34 of file cannyParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    CannyParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void CannyParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by CannyParametersControlWidget(), and setParameters().
void CannyParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 42 of file cannyParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    CannyParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void CannyParametersControlWidget::setParameters (const CannyParameters & input)
Definition at line 66 of file cannyParametersControlWidget.cpp.
References CannyParameters::maximumThreshold(), CannyParameters::minimumThreshold(), mUi, paramsChanged(), and CannyParameters::shouldEdgeDetect().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->shouldEdgeDetectCheckBox->setChecked(input.shouldEdgeDetect());
    mUi->minimumThresholdSpinBox->setValue(input.minimumThreshold());
    mUi->maximumThresholdSpinBox->setValue(input.maximumThreshold());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void CannyParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 77 of file cannyParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    CannyParameters *inputCasted = static_cast<CannyParameters *>(input);
    setParameters(*inputCasted);
}
void CannyParametersControlWidget::valueChanged () [signal]
Referenced by CannyParametersControlWidget().
Member Data Documentation
bool CannyParametersControlWidget::autoInit [private]
Definition at line 45 of file cannyParametersControlWidget.h.
Ui_CannyParametersControlWidget* CannyParametersControlWidget::mUi [private]
Definition at line 44 of file cannyParametersControlWidget.h.
Referenced by CannyParametersControlWidget(), createParameters(), setParameters(), and ~CannyParametersControlWidget().
QString CannyParametersControlWidget::rootPath [private]
Definition at line 46 of file cannyParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/cannyParametersControlWidget.h
utils/filters/ui/cannyParametersControlWidget.cpp