DeepView: WidgetQtIterator Class Reference
WidgetQtIterator Class Reference
#include <widgetQtIterator.h>
Static Public Member Functions
static bool isAdvanced (QObject *object)
static QString print (QWidget *widget, QString prefix)
static void advancedVisibility (QWidget *widget, bool off)
Detailed Description
Definition at line 18 of file widgetQtIterator.h.
Member Function Documentation
static void WidgetQtIterator::advancedVisibility (QWidget * widget, bool off) [inline, static]
Definition at line 102 of file widgetQtIterator.h.
References isAdvanced().
Referenced by BaseHostDialog::toggleAdvanced().
    {
        if (isAdvanced(widget))
            widget->setVisible(!off);
        bool isLeaf = widget->inherits("QLabel")
                || widget->inherits("QComboBox")
                || widget->inherits("QCheckBox")
                || widget->inherits("QSpinBox")
                || widget->inherits("QDoubleSpinBox");
        QObjectList children = widget->children();
        if (!children.isEmpty() && !isLeaf )
        {
            foreach(QObject* object, children)
            {
                if (!object->isWidgetType())
                    continue;
                advancedVisibility(static_cast<QWidget *>(object), off);
            }
        }
    }
static bool WidgetQtIterator::isAdvanced (QObject * object) [inline, static]
Definition at line 22 of file widgetQtIterator.h.
Referenced by advancedVisibility(), and print().
    {
        QVariant prop = object->property("tags");
        if (!prop.isNull())
        {
            QString string = prop.toString();
//            qDebug() << "tags: " << string;
            if (string.contains("advanced"))
                return true;
        }
        return false;
    }
static QString WidgetQtIterator::print (QWidget * widget, QString prefix) [inline, static]
Definition at line 35 of file widgetQtIterator.h.
References isAdvanced().
    {
        QString output;
        const char *name = widget->metaObject()->className();
        output += prefix + name + " " + (isAdvanced(widget) ? "advanced" : "ordinary");
        output += "\n";
        bool isLeaf = false;
        if (widget->inherits("QLabel"))
        {
            QLabel *label = static_cast<QLabel *>(widget);
            output += prefix + "   Label:" + label->text() + "\n";
            isLeaf = true;
        }
        if (widget->inherits("QComboBox"))
        {
            QComboBox *box = static_cast<QComboBox *>(widget);
            output += prefix + "   QComboBox:" + box->itemText(0) + "\n";
            isLeaf = true;
        }
        if (widget->inherits("QCheckBox"))
        {
            QCheckBox *box = static_cast<QCheckBox *>(widget);
            output += prefix + "   QCheckBox:" + box->text() + " " + (box->isChecked() ? "true" : "false") + "\n";
            isLeaf = true;
        }
        if (widget->inherits("QSpinBox"))
        {
            QSpinBox *box = static_cast<QSpinBox *>(widget);
            output += prefix + "   QSpinBox:" + QString::number(box->value()) + "\n";
            isLeaf = true;
        }
        if (widget->inherits("QDoubleSpinBox"))
        {
            QDoubleSpinBox *box = static_cast<QDoubleSpinBox *>(widget);
            output += prefix + "   QDoubleSpinBox:" + QString::number(box->value()) + "\n";
            isLeaf = true;
        }
        if (widget->inherits("QGroupBox"))
        {
            //QGroupBox *group = static_cast<QGroupBox *>(widget);
            output += prefix + "   QGroupBox:" + "\n";
        }
        QObjectList children = widget->children();
        if (!children.isEmpty() && !isLeaf )
        {
            output += prefix + "Children:\n";
            int num = 0;
            foreach(QObject* object, children)
            {
                if (!object->isWidgetType())
                    continue;
                num++;
                output += prefix + " " + QString::number(num) + " [" + QString::number(children.size()) + "]\n";
                output += print(static_cast<QWidget *>(object), prefix + "--->");
            }
        }
        return output;
    }
The documentation for this class was generated from the following file:
utils/serializer/widgetQtIterator.h