DeepView: corecvs::DirectRemapper Class Reference
corecvs::DirectRemapper Class Reference
TODO: rewrite this based on AbstractBuffer This class caches the image transformation.
#include <displacementBuffer.h>
Classes
class ParallelRemap
Public Member Functions
DirectRemapper (Matrix33 *proj, Vector2d< int > inputSize, Vector2d< int > outputSize)
DirectRemapper (Matrix33 *proj, int inputH, int inputW, int outputH, int outputW)
void _init (Matrix33 *proj, int inputH, int inputW, int outputH, int outputW)
G12Buffer * remap (G12Buffer *input)
~DirectRemapper ()
Public Attributes
int mInputH
int mInputW
int mOutputH
int mOutputW
Vector2d32 * mOffsets
Detailed Description
TODO: rewrite this based on AbstractBuffer This class caches the image transformation.
for each output pixel we store its position at the input one.
This class design under development
Definition at line 127 of file displacementBuffer.h.
Constructor & Destructor Documentation
corecvs::DirectRemapper::DirectRemapper (Matrix33 * proj, Vector2d< int > inputSize, Vector2d< int > outputSize) [inline]
Definition at line 138 of file displacementBuffer.h.
References _init(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        _init (proj, inputSize.y(), inputSize.x(), outputSize.y(), outputSize.x());
    }
corecvs::DirectRemapper::DirectRemapper (Matrix33 * proj, int inputH, int inputW, int outputH, int outputW) [inline]
Definition at line 143 of file displacementBuffer.h.
References _init().
    {
        _init (proj, inputH, inputW, outputH, outputW);
    }
corecvs::DirectRemapper::~DirectRemapper () [inline]
Definition at line 211 of file displacementBuffer.h.
References mOffsets.
    {
        deletearr_safe(mOffsets);
    }
Member Function Documentation
void corecvs::DirectRemapper::_init (Matrix33 * proj, int inputH, int inputW, int outputH, int outputW) [inline]
Definition at line 148 of file displacementBuffer.h.
References DOTRACE, corecvs::fround(), mInputH, mInputW, mOffsets, mOutputH, mOutputW, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by DirectRemapper().
    {
        mInputH  = inputH;
        mInputW  = inputW;
        mOutputH = outputH;
        mOutputW = outputW;
        DOTRACE(("DirectRemapper: h= %d, w= %d\n", mOutputH, mOutputW));
        mOffsets = new Vector2d32[mOutputH * mOutputW];
        int i,j;
        for (i = 0; i < mOutputH; i++)
        {
            for (j = 0; j < mOutputW; j++)
            {
                Vector3dd data = (*proj) * Vector3dd(j,i,1);
                data = data / data.z();
                int oldX = fround(data.x());
                int oldY = fround(data.y());
                if (oldY < 0 || oldY >= mInputH || oldX < 0 || oldX >= mInputW)
                    mOffsets[i * mOutputW + j] = Vector2d32(0, 0);
                else
                    mOffsets[i * mOutputW + j] = Vector2d32(oldX, oldY);
            }
        }
        mOutputW = outputW;
    }
G12Buffer* corecvs::DirectRemapper::remap (G12Buffer * input) [inline]
Definition at line 203 of file displacementBuffer.h.
References ASSERT_TRUE, corecvs::AbstractBufferParams::h, mInputH, mInputW, mOutputH, mOutputW, corecvs::parallelable_for(), and corecvs::AbstractBufferParams::w.
Referenced by corecvs::TransformationCache::doDeformation().
    {
        ASSERT_TRUE(input->h == mInputH && input->w == mInputW, "Wrong size...");
        G12Buffer *result = new G12Buffer(mOutputH, mOutputW);
        parallelable_for(0, mOutputH, ParallelRemap(result, input, this));
        return result;
    }
Member Data Documentation
int corecvs::DirectRemapper::mInputH
Definition at line 131 of file displacementBuffer.h.
Referenced by _init(), and remap().
int corecvs::DirectRemapper::mInputW
Definition at line 132 of file displacementBuffer.h.
Referenced by _init(), and remap().
Vector2d32* corecvs::DirectRemapper::mOffsets
Definition at line 136 of file displacementBuffer.h.
Referenced by _init(), corecvs::DirectRemapper::ParallelRemap::operator()(), and ~DirectRemapper().
int corecvs::DirectRemapper::mOutputH
Definition at line 133 of file displacementBuffer.h.
Referenced by _init(), and remap().
int corecvs::DirectRemapper::mOutputW
Definition at line 134 of file displacementBuffer.h.
Referenced by _init(), corecvs::DirectRemapper::ParallelRemap::operator()(), and remap().
The documentation for this class was generated from the following file:
core/buffers/displacementBuffer.h