DeepView: V4L2CaptureDecoupleInterface Class Reference
V4L2CaptureDecoupleInterface Class Reference
#include <V4L2CaptureDecouple.h>
Classes
class SpinThread
Public Types
enum CapErrorCode { SUCCESS = 0, SUCCESS_1CAM = 1, FAILURE = 2 }
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
V4L2CaptureDecoupleInterface (string _devname)
virtual ~V4L2CaptureDecoupleInterface ()
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode queryCameraParameters (CameraParameters &parameter)
Check if a specific property can be set/read and what values it can take.
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual FramePair getFrameRGB24 ()
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&)
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Static Public Attributes
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Private Member Functions
int getParameter (int deviceHandle, int type, char const *str, CaptureParameter &param, ImageCaptureInterface::CapPropertyAccessType &accessFlags)
void setCaptureDeviceParameters (const int handle, const int prop, const int32_t val, int &res, const char *text) const
int queryCaptureDeviceParmeter (const int handle, const uint32_t propID, const char *text, ImageCaptureInterface::CapPropertyAccessType &accessFlags, v4l2_queryctrl &request) const
V4L2CameraDescriptor initCamera (string camFileHandle, int h, int w, int fpsnum=1, int fpsdenum=10)
int start (V4L2CameraDescriptor *cam)
int initBuffers (V4L2CameraDescriptor *cam)
V4L2BufferDescriptor dequeue (V4L2CameraDescriptor *cam)
void enqueue (V4L2CameraDescriptor *cam, V4L2BufferDescriptor buffer)
uint16_t * decodeMjpeg (unsigned char *buffer)
void decodeData (V4L2CameraDescriptor *camera, V4L2BufferDescriptor *buffer, G12Buffer **output)
Private Attributes
string devname
Stores the device name.
string deviceName
V4L2CameraMode cameraMode
V4L2CameraDescriptor camera
V4L2CaptureInterface::DecoderType decoder
DecoupleYUYV::ImageCouplingType coupling
unsigned formatH
unsigned formatW
SpinThread spin
Spin thread that blocks waiting for the frames.
QMutex protectFrame
This mutex protects both buffers from concurent reading/writind If somebody is reading of modifying the buffer it should lok the mutex.
QMutex spinRunning
volatile bool shouldStopSpinThread
V4L2BufferDescriptor current
PreciseTimer lastFrameTime
uint64_t frameDelay
uint64_t skippedCount
Static Private Attributes
static const unsigned LoopQueueBufferNumber = 8
static const unsigned LoopQueueBufferNumberMin = 5
Detailed Description
Definition at line 26 of file V4L2CaptureDecouple.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapErrorCode [inherited]
Enumerator:
SUCCESS
SUCCESS_1CAM
FAILURE
Reimplemented in DirectShowCaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 72 of file imageCaptureInterface.h.
    {
        SUCCESS       = 0,
        SUCCESS_1CAM  = 1,
        FAILURE      = 2
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
Constructor & Destructor Documentation
V4L2CaptureDecoupleInterface::V4L2CaptureDecoupleInterface (string _devname)
Definition at line 13 of file V4L2CaptureDecouple.cpp.
References OutputStyle::ANAGLYPH_RC, cameraMode, V4L2CaptureInterface::CODEC_NAMES, V4L2CameraMode::compressed, V4L2CaptureInterface::COMPRESSED_FAST_JPEG, V4L2CaptureInterface::COMPRESSED_JPEG, coupling, decoder, deviceName, devname, V4L2CameraMode::fpsdenum, V4L2CameraMode::fpsnum, V4L2CameraMode::height, OutputStyle::SIDEBYSIDE_STEREO, V4L2CaptureInterface::UNCOMPRESSED, and V4L2CameraMode::width.
    : spin(this)
{
    this->devname = _devname;
    //     Group Number                   1       2 3      4       56        7       8         9 10     11     1213    14
    QRegExp deviceStringPattern(QString("^([^,:]*)(:(\\d*)/(\\d*))?((:mjpeg)|(:yuyv)|(:fjpeg))?(:(\\d*)x(\\d*))?((:rc)|(:rc2)|(:sbs)|(:rcf))?$"));
    static const int DeviceGroup     = 1;
    static const int FpsNumGroup      = 3;
    static const int FpsDenumGroup    = 4;
    static const int CompressionGroup = 5;
    static const int WidthGroup       = 10;
    static const int HeightGroup      = 11;
    static const int CouplingGroup    = 12;
    printf ("Input string %s\n", _devname.c_str());
    QString qdevname(_devname.c_str());
    int result = deviceStringPattern.indexIn(qdevname);
    if (result == -1)
    {
        printf("Error in device string format:%s\n", _devname.c_str());
        exit(EXIT_FAILURE);
    }
    printf (
        "Parsed data:\n"
        "  | - Device =%s\n"
        "  | - FPS %s/%s\n"
        "  | - Size [%sx%s]\n"
        "  | - Compressing: %s\n"
        "  \\ - Coupling: <%s>\n",
        deviceStringPattern.cap(DeviceGroup).toAscii().constData(),
        deviceStringPattern.cap(FpsNumGroup).toAscii().constData(),
        deviceStringPattern.cap(FpsDenumGroup).toAscii().constData(),
        deviceStringPattern.cap(WidthGroup).toAscii().constData(),
        deviceStringPattern.cap(HeightGroup).toAscii().constData(),
        deviceStringPattern.cap(CompressionGroup).toAscii().constData(),
        deviceStringPattern.cap(CouplingGroup).toAscii().constData()
    );
    deviceName =  deviceStringPattern.cap(DeviceGroup).toAscii().constData();
    bool err;
    cameraMode.fpsnum = deviceStringPattern.cap(FpsNumGroup).toInt(&err);
    if (!err) cameraMode.fpsnum = 1;
    cameraMode.fpsdenum = deviceStringPattern.cap(FpsDenumGroup).toInt(&err);
    if (!err) cameraMode.fpsdenum = 10;
    cameraMode.width = deviceStringPattern.cap(WidthGroup).toInt(&err);
    if (!err || cameraMode.width <= 0) cameraMode.width = 800;
    cameraMode.height = deviceStringPattern.cap(HeightGroup).toInt(&err);
    if (!err || cameraMode.height <= 0) cameraMode.height = 600;
    decoder = V4L2CaptureInterface::UNCOMPRESSED;
    if (!deviceStringPattern.cap(CompressionGroup).isEmpty())
    {
        if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":mjpeg")))
            decoder = V4L2CaptureInterface::COMPRESSED_JPEG;
        if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":fjpeg")))
            decoder = V4L2CaptureInterface::COMPRESSED_FAST_JPEG;
    }
    cameraMode.compressed = (decoder != V4L2CaptureInterface::UNCOMPRESSED);
    coupling = DecoupleYUYV::ANAGLYPH_RC;
    if (!deviceStringPattern.cap(CouplingGroup).compare(QString(":sbs"))) {
        coupling = DecoupleYUYV::SIDEBYSIDE_STEREO;
    }
    if (!deviceStringPattern.cap(CouplingGroup).compare(QString(":rc2"))) {
        coupling = DecoupleYUYV::ANAGLYPH_RC_X2;
    }
    if (!deviceStringPattern.cap(CouplingGroup).compare(QString(":rcf"))) {
        coupling = DecoupleYUYV::ANAGLYPH_RC_FAST;
    }
    printf("Capture device: V4L2 %s\n", deviceName.c_str());
    printf("MJPEG compression is: %s\n", V4L2CaptureInterface::CODEC_NAMES[decoder]);
    printf("Coupling is: %d\n", coupling);
}
V4L2CaptureDecoupleInterface::~V4L2CaptureDecoupleInterface () [virtual]
Definition at line 236 of file V4L2CaptureDecouple.cpp.
References camera, shouldStopSpinThread, spinRunning, V4L2CameraDescriptor::stop(), and SYNC_PRINT.
{
   // spinRunning.lock();
    cout << "V4L2CaptureDecoupleInterface::Request for killing the thread" << endl;
    shouldStopSpinThread = true;
    bool result = spinRunning.tryLock(1000);
    if (result)
        printf("V4L2CaptureDecoupleInterface::Camera thread killed\n");
    else
        printf("V4L2CaptureDecoupleInterface::Unable to exit Camera thread\n");
    SYNC_PRINT(("V4L2CaptureDecoupleInterface::Stopping cameras\n"));
    camera.stop();
}
Member Function Documentation
void V4L2CaptureDecoupleInterface::decodeData (V4L2CameraDescriptor * camera, V4L2BufferDescriptor * buffer, G12Buffer ** output) [private]
uint16_t* V4L2CaptureDecoupleInterface::decodeMjpeg (unsigned char * buffer) [private]
V4L2BufferDescriptor V4L2CaptureDecoupleInterface::dequeue (V4L2CameraDescriptor * cam) [private]
void V4L2CaptureDecoupleInterface::enqueue (V4L2CameraDescriptor * cam, V4L2BufferDescriptor buffer) [private]
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureName (QString & value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 171 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
V4L2CaptureDecoupleInterface::CapErrorCode V4L2CaptureDecoupleInterface::getCaptureProperty (int id, int * value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 219 of file V4L2CaptureDecouple.cpp.
References camera, V4L2CameraDescriptor::getCaptureProperty(), and ImageCaptureInterface::SUCCESS.
{
    camera.getCaptureProperty(id, value);
    return SUCCESS;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getDeviceName (int num, QString & name) [virtual, inherited]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented in DirectShowCaptureInterface, and V4L2CaptureInterface.
Definition at line 186 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getFormats (int * num, CameraFormat *&) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 176 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
V4L2CaptureDecoupleInterface::FramePair V4L2CaptureDecoupleInterface::getFrame () [virtual]
Main function to request frames from image interface.
Implements ImageCaptureInterface.
Definition at line 98 of file V4L2CaptureDecouple.cpp.
References V4L2CameraDescriptor::buffers, camera, coupling, current, CaptureStatistics::DATA_SIZE, CaptureStatistics::DECODING_TIME, CaptureStatistics::DESYNC_TIME, formatH, formatW, frameDelay, CaptureStatistics::framesSkipped, CaptureStatistics::INTERFRAME_DELAY, V4L2BufferDescriptor::isFilled, ImageCaptureInterface::FramePair::leftTimeStamp, ImageCaptureInterface::newStatisticsReady(), protectFrame, ImageCaptureInterface::FramePair::rightTimeStamp, skippedCount, V4L2UsersideBuffer::start, start(), SYNC_PRINT, V4L2BufferDescriptor::usecsTimeStamp(), corecvs::PreciseTimer::usecsToNow(), and CaptureStatistics::values.
{
    CaptureStatistics  stats;
    PreciseTimer start = PreciseTimer::currentTime();
    FramePair result( NULL, NULL);
    protectFrame.lock();
        uint8_t *ptr = (uint8_t*)(camera.buffers[current.index].start);
        DecoupleYUYV::decouple(formatH, formatW, ptr, coupling, result);
        if (current.isFilled) {
            result.leftTimeStamp  = current.usecsTimeStamp();
            result.rightTimeStamp = current.usecsTimeStamp();
        }
        if (skippedCount == 0) {
            SYNC_PRINT(("Warning: Requested same frames twice. Is this by design?\n"));
        }
        stats.framesSkipped = skippedCount > 0 ? skippedCount - 1 : 0;
        skippedCount = 0;
    protectFrame.unlock();
    stats.values[CaptureStatistics::DECODING_TIME] = start.usecsToNow();
    stats.values[CaptureStatistics::INTERFRAME_DELAY] = frameDelay;
    stats.values[CaptureStatistics::DESYNC_TIME] = 0;
    stats.values[CaptureStatistics::DATA_SIZE] = current.bytesused;
    emit newStatisticsReady(stats);
    return result;
}
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual, inherited]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
QString V4L2CaptureDecoupleInterface::getInterfaceName () [virtual]
Return the interface device string.
Reimplemented from ImageCaptureInterface.
Definition at line 231 of file V4L2CaptureDecouple.cpp.
References devname.
{
    return QString("v4l2d:") + QString(devname.c_str());
}
int V4L2CaptureDecoupleInterface::getParameter (int deviceHandle, int type, char const * str, CaptureParameter & param, ImageCaptureInterface::CapPropertyAccessType & accessFlags) [private]
int V4L2CaptureDecoupleInterface::initBuffers (V4L2CameraDescriptor * cam) [private]
V4L2CameraDescriptor V4L2CaptureDecoupleInterface::initCamera (string camFileHandle, int h, int w, int fpsnum = 1, int fpsdenum = 10) [private]
ImageCaptureInterface::CapErrorCode V4L2CaptureDecoupleInterface::initCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 135 of file V4L2CaptureDecouple.cpp.
References camera, cameraMode, deviceName, ImageCaptureInterface::FAILURE, formatH, V4L2CameraDescriptor::formatH, formatW, V4L2CameraDescriptor::formatW, frameDelay, V4L2CameraDescriptor::initBuffers(), V4L2CameraDescriptor::initCamera(), LoopQueueBufferNumber, LoopQueueBufferNumberMin, shouldStopSpinThread, skippedCount, and ImageCaptureInterface::SUCCESS.
{
    camera.initCamera(deviceName, cameraMode);
    formatH = camera.formatH;
    formatW = camera.formatW;
    skippedCount = 0;
    frameDelay = 0;
    shouldStopSpinThread = false;
    int res = camera.initBuffers(LoopQueueBufferNumber, LoopQueueBufferNumberMin);
    return (res == 0) ? SUCCESS : FAILURE;
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
V4L2CaptureDecoupleInterface::CapErrorCode V4L2CaptureDecoupleInterface::queryCameraParameters (CameraParameters & parameter) [virtual]
Check if a specific property can be set/read and what values it can take.
Reimplemented from ImageCaptureInterface.
Definition at line 225 of file V4L2CaptureDecouple.cpp.
References camera, V4L2CameraDescriptor::queryCameraParameters(), and ImageCaptureInterface::SUCCESS.
{
    camera.queryCameraParameters(parameter);
    return SUCCESS;
}
int V4L2CaptureDecoupleInterface::queryCaptureDeviceParmeter (const int handle, const uint32_t propID, const char * text, ImageCaptureInterface::CapPropertyAccessType & accessFlags, v4l2_queryctrl & request) const [private]
void V4L2CaptureDecoupleInterface::setCaptureDeviceParameters (const int handle, const int prop, const int32_t val, int & res, const char * text) const [private]
V4L2CaptureDecoupleInterface::CapErrorCode V4L2CaptureDecoupleInterface::setCaptureProperty (int id, int value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 213 of file V4L2CaptureDecouple.cpp.
References camera, V4L2CameraDescriptor::setCaptureProperty(), and ImageCaptureInterface::SUCCESS.
Referenced by startCapture().
{
    camera.setCaptureProperty(id, value);
    return SUCCESS;
}
int V4L2CaptureDecoupleInterface::start (V4L2CameraDescriptor * cam) [private]
Referenced by getFrame().
ImageCaptureInterface::CapErrorCode V4L2CaptureDecoupleInterface::startCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 151 of file V4L2CaptureDecouple.cpp.
References camera, ImageCaptureInterface::FAILURE, CameraParameters::SATURATION, setCaptureProperty(), shouldStopSpinThread, spin, V4L2CameraDescriptor::start(), and ImageCaptureInterface::SUCCESS.
{
    int res = camera.start();
    setCaptureProperty(CameraParameters::SATURATION, 0);
    shouldStopSpinThread = false;
    spin.start();
    return (res == 0) ? SUCCESS : FAILURE;
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
Member Data Documentation
V4L2CameraDescriptor V4L2CaptureDecoupleInterface::camera [private]
Definition at line 84 of file V4L2CaptureDecouple.h.
Referenced by getCaptureProperty(), getFrame(), initCapture(), queryCameraParameters(), V4L2CaptureDecoupleInterface::SpinThread::run(), setCaptureProperty(), startCapture(), and ~V4L2CaptureDecoupleInterface().
V4L2CameraMode V4L2CaptureDecoupleInterface::cameraMode [private]
Definition at line 83 of file V4L2CaptureDecouple.h.
Referenced by initCapture(), and V4L2CaptureDecoupleInterface().
DecoupleYUYV::ImageCouplingType V4L2CaptureDecoupleInterface::coupling [private]
Definition at line 87 of file V4L2CaptureDecouple.h.
Referenced by getFrame(), and V4L2CaptureDecoupleInterface().
V4L2BufferDescriptor V4L2CaptureDecoupleInterface::current [private]
Definition at line 99 of file V4L2CaptureDecouple.h.
Referenced by getFrame(), and V4L2CaptureDecoupleInterface::SpinThread::run().
V4L2CaptureInterface::DecoderType V4L2CaptureDecoupleInterface::decoder [private]
Definition at line 86 of file V4L2CaptureDecouple.h.
Referenced by V4L2CaptureDecoupleInterface().
string V4L2CaptureDecoupleInterface::deviceName [private]
Definition at line 82 of file V4L2CaptureDecouple.h.
Referenced by initCapture(), and V4L2CaptureDecoupleInterface().
string V4L2CaptureDecoupleInterface::devname [private]
Stores the device name.
Definition at line 48 of file V4L2CaptureDecouple.h.
Referenced by getInterfaceName(), and V4L2CaptureDecoupleInterface().
unsigned V4L2CaptureDecoupleInterface::formatH [private]
Definition at line 89 of file V4L2CaptureDecouple.h.
Referenced by getFrame(), and initCapture().
unsigned V4L2CaptureDecoupleInterface::formatW [private]
Definition at line 90 of file V4L2CaptureDecouple.h.
Referenced by getFrame(), and initCapture().
uint64_t V4L2CaptureDecoupleInterface::frameDelay [private]
Definition at line 103 of file V4L2CaptureDecouple.h.
Referenced by getFrame(), initCapture(), and V4L2CaptureDecoupleInterface::SpinThread::run().
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
PreciseTimer V4L2CaptureDecoupleInterface::lastFrameTime [private]
Definition at line 102 of file V4L2CaptureDecouple.h.
Referenced by V4L2CaptureDecoupleInterface::SpinThread::run().
const unsigned V4L2CaptureDecoupleInterface::LoopQueueBufferNumber = 8 [static, private]
Definition at line 45 of file V4L2CaptureDecouple.h.
Referenced by initCapture().
const unsigned V4L2CaptureDecoupleInterface::LoopQueueBufferNumberMin = 5 [static, private]
Definition at line 46 of file V4L2CaptureDecouple.h.
Referenced by initCapture().
QMutex V4L2CaptureDecoupleInterface::protectFrame [private]
This mutex protects both buffers from concurent reading/writind If somebody is reading of modifying the buffer it should lok the mutex.
Definition at line 93 of file V4L2CaptureDecouple.h.
Referenced by getFrame(), and V4L2CaptureDecoupleInterface::SpinThread::run().
volatile bool V4L2CaptureDecoupleInterface::shouldStopSpinThread [private]
Definition at line 97 of file V4L2CaptureDecouple.h.
Referenced by initCapture(), V4L2CaptureDecoupleInterface::SpinThread::run(), startCapture(), and ~V4L2CaptureDecoupleInterface().
uint64_t V4L2CaptureDecoupleInterface::skippedCount [private]
Definition at line 105 of file V4L2CaptureDecouple.h.
Referenced by getFrame(), initCapture(), and V4L2CaptureDecoupleInterface::SpinThread::run().
SpinThread V4L2CaptureDecoupleInterface::spin [private]
Spin thread that blocks waiting for the frames.
Definition at line 92 of file V4L2CaptureDecouple.h.
Referenced by startCapture().
QMutex V4L2CaptureDecoupleInterface::spinRunning [private]
Definition at line 96 of file V4L2CaptureDecouple.h.
Referenced by V4L2CaptureDecoupleInterface::SpinThread::run(), and ~V4L2CaptureDecoupleInterface().
The documentation for this class was generated from the following files:
utils/framesources/v4l2/V4L2CaptureDecouple.h
utils/framesources/v4l2/V4L2CaptureDecouple.cpp