DeepView: corecvs::PropertyListReaderVisitor Class Reference
corecvs::PropertyListReaderVisitor Class Reference
Visitor that de-serializes the type hierarchy from the PropertyList - the internal human readable format for CVS core.
#include <propertyListVisitor.h>
Public Member Functions
PropertyListReaderVisitor (PropertyList *_input, bool _ignoreUnknown=false)
template<class Type >
void visit (Type &field, Type defaultValue, const char *fieldName)
template<typename inputType , typename reflectionType >
void visit (inputType &field, const reflectionType *fieldDescriptor)
template<>
void visit (int &intField, int defaultValue, const char *fieldName)
template<>
void visit (double &doubleField, double defaultValue, const char *fieldName)
template<>
void visit (bool &boolField, bool boolValue, const char *fieldName)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
string getCurrentPath ()
string getChildPath (string child)
void pushChild (const string child)
void popChild ()
template<>
void visit (int &intField, int defaultValue, const char *fieldName)
PropertyListReaderVisitor methods that process different types.
template<>
void visit (double &doubleField, double defaultValue, const char *fieldName)
template<>
void visit (bool &boolField, bool defaultValue, const char *fieldName)
template<>
void visit (int &intField, const IntField *fieldDescriptor)
template<>
void visit (double &doubleField, const DoubleField *fieldDescriptor)
template<>
void visit (bool &boolField, const BoolField *fieldDescriptor)
Public Attributes
PropertyList * input
bool ignoreUnknown
string separator
T elements
STL member.
Static Public Attributes
static string SEPARATOR_DEFAULT = "."
Detailed Description
Visitor that de-serializes the type hierarchy from the PropertyList - the internal human readable format for CVS core.
Definition at line 86 of file propertyListVisitor.h.
Constructor & Destructor Documentation
corecvs::PropertyListReaderVisitor::PropertyListReaderVisitor (PropertyList * _input, bool _ignoreUnknown = false) [inline]
Definition at line 92 of file propertyListVisitor.h.
                                                                                 :
        input(_input),
        ignoreUnknown(_ignoreUnknown)
    {}
Member Function Documentation
string corecvs::BasePathVisitor::getChildPath (string child) [inline, inherited]
Definition at line 35 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getCurrentPath(), and corecvs::BasePathVisitor::separator.
Referenced by corecvs::BasePathVisitor::pushChild().
    {
       string newPath = getCurrentPath();
       if (!newPath.empty())
           newPath.append(separator);
       newPath.append(child);
       return newPath;
    }
string corecvs::BasePathVisitor::getCurrentPath () [inline, inherited]
Definition at line 28 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
    {
        if (empty())
            return "";
        return back();
    }
void corecvs::BasePathVisitor::popChild () [inline, inherited]
Definition at line 55 of file basePathVisitor.h.
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and visit().
    {
        pop_back();
    }
void corecvs::BasePathVisitor::pushChild (const string child) [inline, inherited]
Definition at line 50 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getChildPath().
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and visit().
    {
        push_back(getChildPath(child));
    }
template<> void corecvs::PropertyListReaderVisitor::visit (int & intField, int defaultValue, const char * fieldName)
PropertyListReaderVisitor methods that process different types.
Definition at line 68 of file propertyListVisitor.cpp.
    {
        intField = input->getIntProperty(getChildPath(fieldName), defaultValue);
    }
template<> void corecvs::PropertyListReaderVisitor::visit (double & doubleField, double defaultValue, const char * fieldName)
Definition at line 74 of file propertyListVisitor.cpp.
    {
        doubleField = input->getDoubleProperty(getChildPath(fieldName), defaultValue);
    }
template<> void corecvs::PropertyListReaderVisitor::visit (bool & boolField, bool defaultValue, const char * fieldName)
Definition at line 80 of file propertyListVisitor.cpp.
    {
        boolField = input->getIntProperty(getChildPath(fieldName), defaultValue);
    }
template<> void corecvs::PropertyListReaderVisitor::visit (int & intField, const IntField * fieldDescriptor)
Definition at line 88 of file propertyListVisitor.cpp.
    {
        intField = input->getIntProperty(getChildPath(fieldDescriptor->getSimpleName()), fieldDescriptor->defaultValue);
    }
template<> void corecvs::PropertyListReaderVisitor::visit (double & doubleField, const DoubleField * fieldDescriptor)
Definition at line 94 of file propertyListVisitor.cpp.
    {
        doubleField = input->getDoubleProperty(getChildPath(fieldDescriptor->getSimpleName()), fieldDescriptor->defaultValue);
    }
template<class Type > void corecvs::PropertyListReaderVisitor::visit (Type & field, Type defaultValue, const char * fieldName)
Definition at line 107 of file propertyListVisitor.h.
References corecvs::BasePathVisitor::popChild(), and corecvs::BasePathVisitor::pushChild().
Referenced by BaseHostDialog::loadTransformFromFile().
{
    pushChild(fieldName);
        field.accept(*this);
    popChild();
}
template<> void corecvs::PropertyListReaderVisitor::visit (bool & boolField, const BoolField * fieldDescriptor)
Definition at line 100 of file propertyListVisitor.cpp.
    {
        boolField = input->getIntProperty(getChildPath(fieldDescriptor->getSimpleName()), fieldDescriptor->defaultValue);
    }
template<typename inputType , typename reflectionType > void corecvs::PropertyListReaderVisitor::visit (inputType & field, const reflectionType * fieldDescriptor)
Definition at line 115 of file propertyListVisitor.h.
References corecvs::BasePathVisitor::popChild(), and corecvs::BasePathVisitor::pushChild().
{
    pushChild(fieldDescriptor->name.name);
        field.accept(*this);
    popChild();
}
template<> void corecvs::PropertyListReaderVisitor::visit (int & intField, int defaultValue, const char * fieldName)
template<> void corecvs::PropertyListReaderVisitor::visit (double & doubleField, double defaultValue, const char * fieldName)
template<> void corecvs::PropertyListReaderVisitor::visit (bool & boolField, bool boolValue, const char * fieldName)
template<> void corecvs::PropertyListReaderVisitor::visit (int & field, const IntField * fieldDescriptor)
template<> void corecvs::PropertyListReaderVisitor::visit (double & field, const DoubleField * fieldDescriptor)
template<> void corecvs::PropertyListReaderVisitor::visit (bool & field, const BoolField * fieldDescriptor)
Member Data Documentation
template<typename T> T std::deque< T >::elements [inherited]
STL member.
bool corecvs::PropertyListReaderVisitor::ignoreUnknown
Definition at line 90 of file propertyListVisitor.h.
PropertyList* corecvs::PropertyListReaderVisitor::input
Definition at line 89 of file propertyListVisitor.h.
string corecvs::BasePathVisitor::separator [inherited]
Definition at line 26 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
string corecvs::BasePathVisitor::SEPARATOR_DEFAULT = "." [static, inherited]
Definition at line 24 of file basePathVisitor.h.
The documentation for this class was generated from the following files:
core/utils/visitors/propertyListVisitor.h
core/utils/visitors/propertyListVisitor.cpp