DeepView: ThickeningParameters Class Reference
ThickeningParameters Class Reference
Thickening Parameters Thickening Parameters.
#include <thickeningParameters.h>
Public Types
enum FieldId { POWER_ID, THICKENING_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
int power () const
void setPower (int power)
template<class VisitorType >
void accept (VisitorType &visitor)
ThickeningParameters ()
ThickeningParameters (int power)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mPower
Section with variables.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, ThickeningParameters &toSave)
Detailed Description
Thickening Parameters Thickening Parameters.
Definition at line 38 of file thickeningParameters.h.
Member Enumeration Documentation
enum ThickeningParameters::FieldId
Enumerator:
POWER_ID
THICKENING_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file thickeningParameters.h.
                 {
        POWER_ID,
        THICKENING_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
ThickeningParameters::ThickeningParameters () [inline]
Definition at line 81 of file thickeningParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
ThickeningParameters::ThickeningParameters (int power) [inline]
Definition at line 87 of file thickeningParameters.h.
    {
        mPower = power;
    }
Member Function Documentation
template<class VisitorType > void ThickeningParameters::accept (VisitorType & visitor) [inline]
Definition at line 76 of file thickeningParameters.h.
Referenced by corecvs::ThickeningBlock::deserialize(), and corecvs::ThickeningBlock::serialize().
    {
        visitor.visit(mPower,                     static_cast<const IntField *>     (fields()[POWER_ID]));
    }
static const char* corecvs::BaseReflection< ThickeningParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< ThickeningParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< ThickeningParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* ThickeningParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 58 of file thickeningParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< ThickeningParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< ThickeningParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< ThickeningParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
int ThickeningParameters::power () const [inline]
Definition at line 62 of file thickeningParameters.h.
Referenced by corecvs::ThickeningBlock::operator()(), and ThickeningParametersControlWidget::setParameters().
    {
        return mPower;
    }
void ThickeningParameters::print () [inline]
Definition at line 101 of file thickeningParameters.h.
    {
        cout << *this;
    }
void ThickeningParameters::setPower (int power) [inline]
Definition at line 68 of file thickeningParameters.h.
    {
        mPower = power;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int ThickeningParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file thickeningParameters.cpp.
References corecvs::BaseReflection< ThickeningParameters >::fields(), mPower, corecvs::BaseReflection< ThickeningParameters >::naming(), and POWER_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Thickening Parameters",
        "Thickening Parameters",
        ""
    );
    fields().push_back(
        new IntField
        (
          ThickeningParameters::POWER_ID,
          offsetof(ThickeningParameters, mPower),
          5000,
          "Power",
          "Power",
          "Power"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, ThickeningParameters & toSave) [friend]
Definition at line 94 of file thickeningParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< ThickeningParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int ThickeningParameters::mPower
Section with variables.
Power Power
Definition at line 52 of file thickeningParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< ThickeningParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/thickeningParameters.h
core/xml/generated/thickeningParameters.cpp