DeepView: Draw3dParameters Class Reference
Draw3dParameters Class Reference
draw 3d Parameters draw 3d Parameters
#include <draw3dParameters.h>
Public Types
enum FieldId {
STYLE_ID, COLOR_ID, SECONDARY_COLOR_ID, TEXTURE_CORRODINATES_ID,
TEXTURE_ALPHA_ID, TEXTURE_SCALE_ID, DECAL_MATRIX_TYPE_ID, DECAL_LEFT_CAM_ID,
DECAL_LEFT_ALPHA_ID, DECAL_RIGHT_CAM_ID, DECAL_RIGHT_ALPHA_ID, DRAW_3D_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
Draw3dStyle::Draw3dStyle style () const
RgbColorParameters color () const
RgbColorParameters secondaryColor () const
Draw3dTextureGen::Draw3dTextureGen textureCorrodinates () const
int textureAlpha () const
double textureScale () const
int decalMatrixType () const
bool decalLeftCam () const
int decalLeftAlpha () const
bool decalRightCam () const
int decalRightAlpha () const
void setStyle (Draw3dStyle::Draw3dStyle style)
void setColor (RgbColorParameters const &color)
void setSecondaryColor (RgbColorParameters const &secondaryColor)
void setTextureCorrodinates (Draw3dTextureGen::Draw3dTextureGen textureCorrodinates)
void setTextureAlpha (int textureAlpha)
void setTextureScale (double textureScale)
void setDecalMatrixType (int decalMatrixType)
void setDecalLeftCam (bool decalLeftCam)
void setDecalLeftAlpha (int decalLeftAlpha)
void setDecalRightCam (bool decalRightCam)
void setDecalRightAlpha (int decalRightAlpha)
template<class VisitorType >
void accept (VisitorType &visitor)
Draw3dParameters ()
Draw3dParameters (Draw3dStyle::Draw3dStyle style, RgbColorParameters color, RgbColorParameters secondaryColor, Draw3dTextureGen::Draw3dTextureGen textureCorrodinates, int textureAlpha, double textureScale, int decalMatrixType, bool decalLeftCam, int decalLeftAlpha, bool decalRightCam, int decalRightAlpha)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mStyle
Section with variables.
RgbColorParameters mColor
Color Color.
RgbColorParameters mSecondaryColor
Secondary Color Secondary Color.
int mTextureCorrodinates
Texture Corrodinates Texture Corrodinates.
int mTextureAlpha
Texture Alpha Texture Alpha.
double mTextureScale
Texture Scale Texture Scale.
int mDecalMatrixType
Decal Matrix Type Decal Matrix Type.
bool mDecalLeftCam
Decal Left Cam Decal Left Cam.
int mDecalLeftAlpha
Decal Left Alpha Decal Left Alpha.
bool mDecalRightCam
Decal Right Cam Decal Right Cam.
int mDecalRightAlpha
Decal Right Alpha Decal Right Alpha.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, Draw3dParameters &toSave)
Detailed Description
draw 3d Parameters draw 3d Parameters
Definition at line 41 of file draw3dParameters.h.
Member Enumeration Documentation
enum Draw3dParameters::FieldId
Enumerator:
STYLE_ID
COLOR_ID
SECONDARY_COLOR_ID
TEXTURE_CORRODINATES_ID
TEXTURE_ALPHA_ID
TEXTURE_SCALE_ID
DECAL_MATRIX_TYPE_ID
DECAL_LEFT_CAM_ID
DECAL_LEFT_ALPHA_ID
DECAL_RIGHT_CAM_ID
DECAL_RIGHT_ALPHA_ID
DRAW_3D_PARAMETERS_FIELD_ID_NUM
Definition at line 44 of file draw3dParameters.h.
                 {
        STYLE_ID,
        COLOR_ID,
        SECONDARY_COLOR_ID,
        TEXTURE_CORRODINATES_ID,
        TEXTURE_ALPHA_ID,
        TEXTURE_SCALE_ID,
        DECAL_MATRIX_TYPE_ID,
        DECAL_LEFT_CAM_ID,
        DECAL_LEFT_ALPHA_ID,
        DECAL_RIGHT_CAM_ID,
        DECAL_RIGHT_ALPHA_ID,
        DRAW_3D_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
Draw3dParameters::Draw3dParameters () [inline]
Definition at line 264 of file draw3dParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
Draw3dParameters::Draw3dParameters (Draw3dStyle::Draw3dStyle style, RgbColorParameters color, RgbColorParameters secondaryColor, Draw3dTextureGen::Draw3dTextureGen textureCorrodinates, int textureAlpha, double textureScale, int decalMatrixType, bool decalLeftCam, int decalLeftAlpha, bool decalRightCam, int decalRightAlpha) [inline]
Definition at line 270 of file draw3dParameters.h.
    {
        mStyle = style;
        mColor = color;
        mSecondaryColor = secondaryColor;
        mTextureCorrodinates = textureCorrodinates;
        mTextureAlpha = textureAlpha;
        mTextureScale = textureScale;
        mDecalMatrixType = decalMatrixType;
        mDecalLeftCam = decalLeftCam;
        mDecalLeftAlpha = decalLeftAlpha;
        mDecalRightCam = decalRightCam;
        mDecalRightAlpha = decalRightAlpha;
    }
Member Function Documentation
template<class VisitorType > void Draw3dParameters::accept (VisitorType & visitor) [inline]
Definition at line 249 of file draw3dParameters.h.
    {
        visitor.visit((int &)mStyle,              static_cast<const EnumField *>    (fields()[STYLE_ID]));
        visitor.visit(mColor,                     static_cast<const CompositeField *>(fields()[COLOR_ID]));
        visitor.visit(mSecondaryColor,            static_cast<const CompositeField *>(fields()[SECONDARY_COLOR_ID]));
        visitor.visit((int &)mTextureCorrodinates, static_cast<const EnumField *>    (fields()[TEXTURE_CORRODINATES_ID]));
        visitor.visit(mTextureAlpha,              static_cast<const IntField *>     (fields()[TEXTURE_ALPHA_ID]));
        visitor.visit(mTextureScale,              static_cast<const DoubleField *>  (fields()[TEXTURE_SCALE_ID]));
        visitor.visit(mDecalMatrixType,           static_cast<const IntField *>     (fields()[DECAL_MATRIX_TYPE_ID]));
        visitor.visit(mDecalLeftCam,              static_cast<const BoolField *>    (fields()[DECAL_LEFT_CAM_ID]));
        visitor.visit(mDecalLeftAlpha,            static_cast<const IntField *>     (fields()[DECAL_LEFT_ALPHA_ID]));
        visitor.visit(mDecalRightCam,             static_cast<const BoolField *>    (fields()[DECAL_RIGHT_CAM_ID]));
        visitor.visit(mDecalRightAlpha,           static_cast<const IntField *>     (fields()[DECAL_RIGHT_ALPHA_ID]));
    }
RgbColorParameters Draw3dParameters::color () const [inline]
Definition at line 140 of file draw3dParameters.h.
Referenced by Mesh3DScene::drawMyself(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mColor;
    }
static const char* corecvs::BaseReflection< Draw3dParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
int Draw3dParameters::decalLeftAlpha () const [inline]
Definition at line 175 of file draw3dParameters.h.
Referenced by Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mDecalLeftAlpha;
    }
bool Draw3dParameters::decalLeftCam () const [inline]
Definition at line 170 of file draw3dParameters.h.
Referenced by Scene3D::commonSetup(), Scene3D::commonTierdown(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mDecalLeftCam;
    }
int Draw3dParameters::decalMatrixType () const [inline]
Definition at line 165 of file draw3dParameters.h.
Referenced by Scene3D::initDecalState(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mDecalMatrixType;
    }
int Draw3dParameters::decalRightAlpha () const [inline]
Definition at line 185 of file draw3dParameters.h.
Referenced by Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mDecalRightAlpha;
    }
bool Draw3dParameters::decalRightCam () const [inline]
Definition at line 180 of file draw3dParameters.h.
Referenced by Scene3D::commonSetup(), Scene3D::commonTierdown(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mDecalRightCam;
    }
static int corecvs::BaseReflection< Draw3dParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< Draw3dParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* Draw3dParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 131 of file draw3dParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< Draw3dParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< Draw3dParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< Draw3dParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void Draw3dParameters::print () [inline]
Definition at line 304 of file draw3dParameters.h.
    {
        cout << *this;
    }
RgbColorParameters Draw3dParameters::secondaryColor () const [inline]
Definition at line 145 of file draw3dParameters.h.
Referenced by Mesh3DScene::drawMyself(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mSecondaryColor;
    }
void Draw3dParameters::setColor (RgbColorParameters const & color) [inline]
Definition at line 196 of file draw3dParameters.h.
    {
        mColor = color;
    }
void Draw3dParameters::setDecalLeftAlpha (int decalLeftAlpha) [inline]
Definition at line 231 of file draw3dParameters.h.
    {
        mDecalLeftAlpha = decalLeftAlpha;
    }
void Draw3dParameters::setDecalLeftCam (bool decalLeftCam) [inline]
Definition at line 226 of file draw3dParameters.h.
    {
        mDecalLeftCam = decalLeftCam;
    }
void Draw3dParameters::setDecalMatrixType (int decalMatrixType) [inline]
Definition at line 221 of file draw3dParameters.h.
    {
        mDecalMatrixType = decalMatrixType;
    }
void Draw3dParameters::setDecalRightAlpha (int decalRightAlpha) [inline]
Definition at line 241 of file draw3dParameters.h.
    {
        mDecalRightAlpha = decalRightAlpha;
    }
void Draw3dParameters::setDecalRightCam (bool decalRightCam) [inline]
Definition at line 236 of file draw3dParameters.h.
    {
        mDecalRightCam = decalRightCam;
    }
void Draw3dParameters::setSecondaryColor (RgbColorParameters const & secondaryColor) [inline]
Definition at line 201 of file draw3dParameters.h.
    {
        mSecondaryColor = secondaryColor;
    }
void Draw3dParameters::setStyle (Draw3dStyle::Draw3dStyle style) [inline]
Definition at line 191 of file draw3dParameters.h.
    {
        mStyle = style;
    }
void Draw3dParameters::setTextureAlpha (int textureAlpha) [inline]
Definition at line 211 of file draw3dParameters.h.
    {
        mTextureAlpha = textureAlpha;
    }
void Draw3dParameters::setTextureCorrodinates (Draw3dTextureGen::Draw3dTextureGen textureCorrodinates) [inline]
Definition at line 206 of file draw3dParameters.h.
    {
        mTextureCorrodinates = textureCorrodinates;
    }
void Draw3dParameters::setTextureScale (double textureScale) [inline]
Definition at line 216 of file draw3dParameters.h.
    {
        mTextureScale = textureScale;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int Draw3dParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file draw3dParameters.cpp.
References COLOR_ID, DECAL_LEFT_ALPHA_ID, DECAL_LEFT_CAM_ID, DECAL_MATRIX_TYPE_ID, DECAL_RIGHT_ALPHA_ID, DECAL_RIGHT_CAM_ID, corecvs::BaseReflection< Draw3dParameters >::fields(), mColor, mDecalLeftAlpha, mDecalLeftCam, mDecalMatrixType, mDecalRightAlpha, mDecalRightCam, mSecondaryColor, mStyle, mTextureAlpha, mTextureCorrodinates, mTextureScale, corecvs::BaseReflection< Draw3dParameters >::naming(), SECONDARY_COLOR_ID, STYLE_ID, TEXTURE_ALPHA_ID, TEXTURE_CORRODINATES_ID, and TEXTURE_SCALE_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "draw 3d Parameters",
        "draw 3d Parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          Draw3dParameters::STYLE_ID,
          offsetof(Draw3dParameters, mStyle),
          0,
          "style",
          "style",
          "style",
           NULL
        )
    );
    fields().push_back(
        new CompositeField
        (
          Draw3dParameters::COLOR_ID,
          offsetof(Draw3dParameters, mColor),
          "Color",
          "RgbColorParameters",
          "Color",
          "Color",
           NULL
        )
    );
    fields().push_back(
        new CompositeField
        (
          Draw3dParameters::SECONDARY_COLOR_ID,
          offsetof(Draw3dParameters, mSecondaryColor),
          "Secondary Color",
          "RgbColorParameters",
          "Secondary Color",
          "Secondary Color",
           NULL
        )
    );
    fields().push_back(
        new EnumField
        (
          Draw3dParameters::TEXTURE_CORRODINATES_ID,
          offsetof(Draw3dParameters, mTextureCorrodinates),
          0,
          "Texture Corrodinates",
          "Texture Corrodinates",
          "Texture Corrodinates",
           NULL
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dParameters::TEXTURE_ALPHA_ID,
          offsetof(Draw3dParameters, mTextureAlpha),
          255,
          "Texture Alpha",
          "Texture Alpha",
          "Texture Alpha"
        )
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dParameters::TEXTURE_SCALE_ID,
          offsetof(Draw3dParameters, mTextureScale),
          1,
          "Texture Scale",
          "Texture Scale",
          "Texture Scale"
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dParameters::DECAL_MATRIX_TYPE_ID,
          offsetof(Draw3dParameters, mDecalMatrixType),
          11,
          "Decal Matrix Type",
          "Decal Matrix Type",
          "Decal Matrix Type"
        )
    );
    fields().push_back(
        new BoolField
        (
          Draw3dParameters::DECAL_LEFT_CAM_ID,
          offsetof(Draw3dParameters, mDecalLeftCam),
          false,
          "Decal Left Cam",
          "Decal Left Cam",
          "Decal Left Cam"
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dParameters::DECAL_LEFT_ALPHA_ID,
          offsetof(Draw3dParameters, mDecalLeftAlpha),
          255,
          "Decal Left Alpha",
          "Decal Left Alpha",
          "Decal Left Alpha"
        )
    );
    fields().push_back(
        new BoolField
        (
          Draw3dParameters::DECAL_RIGHT_CAM_ID,
          offsetof(Draw3dParameters, mDecalRightCam),
          false,
          "Decal Right Cam",
          "Decal Right Cam",
          "Decal Right Cam"
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dParameters::DECAL_RIGHT_ALPHA_ID,
          offsetof(Draw3dParameters, mDecalRightAlpha),
          255,
          "Decal Right Alpha",
          "Decal Right Alpha",
          "Decal Right Alpha"
        )
    );
   return 0;
}
Draw3dStyle::Draw3dStyle Draw3dParameters::style () const [inline]
Definition at line 135 of file draw3dParameters.h.
Referenced by CoordinateFrame::drawMyself(), Mesh3DScene::drawMyself(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return static_cast<Draw3dStyle::Draw3dStyle>(mStyle);
    }
int Draw3dParameters::textureAlpha () const [inline]
Definition at line 155 of file draw3dParameters.h.
Referenced by Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mTextureAlpha;
    }
Draw3dTextureGen::Draw3dTextureGen Draw3dParameters::textureCorrodinates () const [inline]
Definition at line 150 of file draw3dParameters.h.
Referenced by Scene3D::commonSetup(), Scene3D::commonTierdown(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return static_cast<Draw3dTextureGen::Draw3dTextureGen>(mTextureCorrodinates);
    }
double Draw3dParameters::textureScale () const [inline]
Definition at line 160 of file draw3dParameters.h.
Referenced by Scene3D::commonSetup(), Draw3dCameraParameters::setBaseParameters(), and Draw3dParametersControlWidget::setParameters().
    {
        return mTextureScale;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, Draw3dParameters & toSave) [friend]
Definition at line 297 of file draw3dParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< Draw3dParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
RgbColorParameters Draw3dParameters::mColor
Color Color.
Definition at line 71 of file draw3dParameters.h.
Referenced by staticInit().
int Draw3dParameters::mDecalLeftAlpha
Decal Left Alpha Decal Left Alpha.
Definition at line 113 of file draw3dParameters.h.
Referenced by staticInit().
bool Draw3dParameters::mDecalLeftCam
Decal Left Cam Decal Left Cam.
Definition at line 107 of file draw3dParameters.h.
Referenced by staticInit().
int Draw3dParameters::mDecalMatrixType
Decal Matrix Type Decal Matrix Type.
Definition at line 101 of file draw3dParameters.h.
Referenced by staticInit().
int Draw3dParameters::mDecalRightAlpha
Decal Right Alpha Decal Right Alpha.
Definition at line 125 of file draw3dParameters.h.
Referenced by staticInit().
bool Draw3dParameters::mDecalRightCam
Decal Right Cam Decal Right Cam.
Definition at line 119 of file draw3dParameters.h.
Referenced by staticInit().
RgbColorParameters Draw3dParameters::mSecondaryColor
Secondary Color Secondary Color.
Definition at line 77 of file draw3dParameters.h.
Referenced by staticInit().
int Draw3dParameters::mStyle
Section with variables.
style style
Definition at line 65 of file draw3dParameters.h.
Referenced by staticInit().
int Draw3dParameters::mTextureAlpha
Texture Alpha Texture Alpha.
Definition at line 89 of file draw3dParameters.h.
Referenced by staticInit().
int Draw3dParameters::mTextureCorrodinates
Texture Corrodinates Texture Corrodinates.
Definition at line 83 of file draw3dParameters.h.
Referenced by staticInit().
double Draw3dParameters::mTextureScale
Texture Scale Texture Scale.
Definition at line 95 of file draw3dParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< Draw3dParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
utils/3d/generated/draw3dParameters.h
utils/3d/generated/draw3dParameters.cpp