DeepView: FilterParametersControlWidgetBase Class Reference
FilterParametersControlWidgetBase Class Reference
#include <filterParametersControlWidgetBase.h>
Signals
void paramsChanged ()
Public Member Functions
FilterParametersControlWidgetBase (QWidget *parent)
virtual void setParametersVirtual (void *)
virtual BaseReflectionStatic * createParametersVirtual () const
Detailed Description
Definition at line 19 of file filterParametersControlWidgetBase.h.
Constructor & Destructor Documentation
FilterParametersControlWidgetBase::FilterParametersControlWidgetBase (QWidget * parent) [inline]
Definition at line 24 of file filterParametersControlWidgetBase.h.
: QWidget(parent) {}
Member Function Documentation
virtual BaseReflectionStatic* FilterParametersControlWidgetBase::createParametersVirtual () const [inline, virtual]
Reimplemented in OperationParametersControlWidget, CannyParametersControlWidget, InputFilterParametersControlWidget, OpenCVFilterParametersControlWidget, OutputFilterParametersControlWidget, SobelParametersControlWidget, BackgroundFilterParametersControlWidget, MaskingParametersControlWidget, ThickeningParametersControlWidget, BinarizeParametersControlWidget, BitSelectorParametersControlWidget, and GainOffsetParametersControlWidget.
Definition at line 27 of file filterParametersControlWidgetBase.h.
Referenced by FilterSelector::getParameters(), and FilterBlockPresentation::parametersChanged().
    {
        return NULL;
    }
void FilterParametersControlWidgetBase::paramsChanged () [signal]
Reimplemented in OperationParametersControlWidget, BitSelectorParametersControlWidget, CannyParametersControlWidget, GainOffsetParametersControlWidget, InputFilterParametersControlWidget, OpenCVFilterParametersControlWidget, OutputFilterParametersControlWidget, SobelParametersControlWidget, BackgroundFilterParametersControlWidget, BinarizeParametersControlWidget, MaskingParametersControlWidget, and ThickeningParametersControlWidget.
virtual void FilterParametersControlWidgetBase::setParametersVirtual (void *) [inline, virtual]
Reimplemented in BinarizeParametersControlWidget, BitSelectorParametersControlWidget, GainOffsetParametersControlWidget, OperationParametersControlWidget, CannyParametersControlWidget, InputFilterParametersControlWidget, OpenCVFilterParametersControlWidget, OutputFilterParametersControlWidget, SobelParametersControlWidget, BackgroundFilterParametersControlWidget, MaskingParametersControlWidget, and ThickeningParametersControlWidget.
Definition at line 25 of file filterParametersControlWidgetBase.h.
Referenced by FilterGraphPresentation::restoreFromGraph().
{}
The documentation for this class was generated from the following file:
utils/filters/filterParametersControlWidgetBase.h