DeepView: WidgetSaver Class Reference
WidgetSaver Class Reference
#include <parametersControlWidgetBase.h>
Public Member Functions
WidgetSaver ()
WidgetSaver (SettingsSetter *qtSettigns)
WidgetSaver (XmlSetter *xmlSetter)
template<class ParametersClass >
void saveParameters (ParametersClass &paramsClass, QString name)
Private Attributes
SettingsSetter * mQtSettings
XmlSetter * mXmlSetter
Detailed Description
Definition at line 25 of file parametersControlWidgetBase.h.
Constructor & Destructor Documentation
WidgetSaver::WidgetSaver () [inline]
Definition at line 30 of file parametersControlWidgetBase.h.
                  :
        mQtSettings(NULL),
        mXmlSetter(NULL)
    {}
WidgetSaver::WidgetSaver (SettingsSetter * qtSettigns) [inline]
Definition at line 35 of file parametersControlWidgetBase.h.
                                            :
        mQtSettings(qtSettigns),
        mXmlSetter(NULL)
    {}
WidgetSaver::WidgetSaver (XmlSetter * xmlSetter) [inline]
Definition at line 40 of file parametersControlWidgetBase.h.
                                      :
        mQtSettings(NULL),
        mXmlSetter(xmlSetter)
    {}
Member Function Documentation
template<class ParametersClass > void WidgetSaver::saveParameters (ParametersClass & paramsClass, QString name) [inline]
Definition at line 46 of file parametersControlWidgetBase.h.
References mQtSettings, mXmlSetter, and SettingsSetter::settings().
Referenced by MakePreciseParametersControlWidget::saveParamWidget(), GraphPlotParametersControlWidget::saveParamWidget(), AxisAlignedBoxParametersControlWidget::saveParamWidget(), OpenCVBMParametersControlWidget::saveParamWidget(), OpenCVSGMParametersControlWidget::saveParamWidget(), PresentationParametersControlWidget::saveParamWidget(), HeadSearchParametersControlWidget::saveParamWidget(), BaseParametersControlWidget::saveParamWidget(), RecorderControlWidget::saveParamWidget(), RgbColorParametersControlWidget::saveParamWidget(), BinarizeParametersControlWidget::saveParamWidget(), MaskingParametersControlWidget::saveParamWidget(), ThickeningParametersControlWidget::saveParamWidget(), GainOffsetParametersControlWidget::saveParamWidget(), BackgroundFilterParametersControlWidget::saveParamWidget(), BitSelectorParametersControlWidget::saveParamWidget(), OutputFilterParametersControlWidget::saveParamWidget(), OpenCVFilterParametersControlWidget::saveParamWidget(), CannyParametersControlWidget::saveParamWidget(), InputFilterParametersControlWidget::saveParamWidget(), Draw3dCameraParametersControlWidget::saveParamWidget(), Draw3dViMouseParametersControlWidget::saveParamWidget(), Draw3dParametersControlWidget::saveParamWidget(), SobelParametersControlWidget::saveParamWidget(), OperationParametersControlWidget::saveParamWidget(), and RectifyParametersControlWidget::saveParamWidget().
    {
        if (mQtSettings) {
            qDebug() << "Saving widget: " << name;
            mQtSettings->settings()->beginGroup(name);
                paramsClass.accept(*mQtSettings);
            mQtSettings->settings()->endGroup();
            return;
        }
        if (mXmlSetter) {
            paramsClass.accept(*mXmlSetter);
            return;
        }
    }
Member Data Documentation
SettingsSetter* WidgetSaver::mQtSettings [private]
Definition at line 26 of file parametersControlWidgetBase.h.
Referenced by saveParameters().
XmlSetter* WidgetSaver::mXmlSetter [private]
Definition at line 27 of file parametersControlWidgetBase.h.
Referenced by saveParameters().
The documentation for this class was generated from the following file:
utils/corestructs/parametersControlWidgetBase.h