DeepView: SaveFlowSettings Class Reference
SaveFlowSettings Class Reference
#include <saveFlowSettings.h>
Public Slots
void openPathSelectDialog ()
Public Member Functions
SaveFlowSettings ()
~SaveFlowSettings ()
Ui_SaveFlowSettings * getUi ()
Protected Attributes
Ui_SaveFlowSettings * mUi
Detailed Description
Definition at line 16 of file saveFlowSettings.h.
Constructor & Destructor Documentation
SaveFlowSettings::SaveFlowSettings ()
Definition at line 4 of file saveFlowSettings.cpp.
References mUi, and openPathSelectDialog().
                                  :
    mUi(new Ui::SaveFlowSettings)
{
    mUi->setupUi(this);
    connect(mUi->choosePathButton, SIGNAL(clicked()), this, SLOT(openPathSelectDialog()));
}
SaveFlowSettings::~SaveFlowSettings ()
Definition at line 11 of file saveFlowSettings.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
Ui_SaveFlowSettings * SaveFlowSettings::getUi ()
Definition at line 17 of file saveFlowSettings.cpp.
References mUi.
Referenced by AdvancedImageWidget::AdvancedImageWidget(), and AdvancedImageWidget::startSaveFlow().
{
    return mUi;
}
void SaveFlowSettings::openPathSelectDialog () [slot]
Definition at line 22 of file saveFlowSettings.cpp.
References mUi.
Referenced by SaveFlowSettings().
{
    QString dir_path = QFileDialog::getExistingDirectory( this,
                                                          "Select target directory",
                                                          "."
                                                          );
    if (dir_path.length() > 0)
    {
        mUi->pathEdit->setText(dir_path);
    }
}
Member Data Documentation
Ui_SaveFlowSettings* SaveFlowSettings::mUi [protected]
Definition at line 34 of file saveFlowSettings.h.
Referenced by getUi(), openPathSelectDialog(), SaveFlowSettings(), and ~SaveFlowSettings().
The documentation for this class was generated from the following files:
utils/corestructs/saveFlowSettings.h
utils/corestructs/saveFlowSettings.cpp