DeepView: tinyxml2::XMLDeclaration Class Reference
tinyxml2::XMLDeclaration Class Reference
In correct XML the declaration is the first entry in the file.
#include <tinyxml2.h>
Public Member Functions
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual const XMLDeclaration * ToDeclaration () const
virtual bool Accept (XMLVisitor *visitor) const
Accept a hierarchical visit of the nodes in the TinyXML DOM.
char * ParseDeep (char *, StrPair *endTag)
virtual XMLNode * ShallowClone (XMLDocument *document) const
Make a copy of this node, but not its children.
virtual bool ShallowEqual (const XMLNode *compare) const
Test if 2 nodes are the same, but don't test children.
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual const XMLText * ToText () const
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual const XMLComment * ToComment () const
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual const XMLDocument * ToDocument () const
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
The meaning of 'value' changes for the specific type.
void SetValue (const char *val, bool staticMem=false)
Set the Value of an XML node.
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
Get the first child element, or optionally the first child element with the specified name.
XMLElement * FirstChildElement (const char *value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
Get the last child element or optionally the last child element with the specified name.
XMLElement * LastChildElement (const char *value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an opitionally supplied name.
XMLElement * PreviousSiblingElement (const char *value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an opitionally supplied name.
XMLElement * NextSiblingElement (const char *value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
Add a child node as the last (right) child.
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
Add a child node as the first (left) child.
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
Add a node after the specified child node.
void DeleteChildren ()
Delete all the children of this node.
void DeleteChild (XMLNode *node)
Delete a child of this node.
Protected Member Functions
XMLDeclaration (XMLDocument *doc)
virtual ~XMLDeclaration ()
XMLDeclaration (const XMLDeclaration &)
XMLDeclaration & operator= (const XMLDeclaration &)
Protected Attributes
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
Friends
class XMLDocument
Detailed Description
In correct XML the declaration is the first entry in the file.
        <?xml version="1.0" standalone="yes"?>
TinyXML2 will happily read or write files without a declaration, however.
The text of the declaration isn't interpreted. It is parsed and written as a string.
Definition at line 884 of file tinyxml2.h.
Constructor & Destructor Documentation
tinyxml2::XMLDeclaration::XMLDeclaration (XMLDocument * doc) [protected]
Definition at line 955 of file tinyxml2.cpp.
                                                 : XMLNode( doc )
{
}
tinyxml2::XMLDeclaration::~XMLDeclaration () [protected, virtual]
Definition at line 960 of file tinyxml2.cpp.
{
    //printf( "~XMLDeclaration\n" );
}
tinyxml2::XMLDeclaration::XMLDeclaration (const XMLDeclaration &) [protected]
Member Function Documentation
bool tinyxml2::XMLDeclaration::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
        TiXmlPrinter printer;
        tinyxmlDoc.Accept( &printer );
        const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Definition at line 995 of file tinyxml2.cpp.
References tinyxml2::XMLVisitor::Visit().
{
    return visitor->Visit( *this );
}
void tinyxml2::XMLNode::DeleteChild (XMLNode * node) [inherited]
Delete a child of this node.
Definition at line 646 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_parent, DELETE_NODE, and TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::DeleteNode().
{
    TIXMLASSERT( node->_parent == this );
    DELETE_NODE( node );
}
void tinyxml2::XMLNode::DeleteChildren () [inherited]
Delete all the children of this node.
Definition at line 614 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_lastChild, DELETE_NODE, and tinyxml2::XMLNode::Unlink().
Referenced by tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::Parse(), tinyxml2::XMLDocument::~XMLDocument(), and tinyxml2::XMLNode::~XMLNode().
{
    while( _firstChild ) {
        XMLNode* node = _firstChild;
        Unlink( node );
        DELETE_NODE( node );
    }
    _firstChild = _lastChild = 0;
}
const XMLNode* tinyxml2::XMLNode::FirstChild () const [inline, inherited]
Get the first child node, or null if none exists.
Definition at line 633 of file tinyxml2.h.
References tinyxml2::XMLNode::_firstChild.
Referenced by tinyxml2::XMLElement::Accept(), corecvs::FilterGraph::deserialize(), corecvs::FilterBlock::deserialize(), corecvs::FilterBlock::deserializePins(), corecvs::FiltersCollection::FiltersCollection(), tinyxml2::XMLHandle::FirstChild(), tinyxml2::XMLConstHandle::FirstChild(), corecvs::FiltersCollection::getContainedBlocks(), tinyxml2::XMLElement::GetText(), corecvs::CompoundFilter::loadGraph(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), and tinyxml2::XMLElement::QueryUnsignedText().
{
        return _firstChild;
    }
XMLNode* tinyxml2::XMLNode::FirstChild () [inline, inherited]
Definition at line 637 of file tinyxml2.h.
References tinyxml2::XMLNode::_firstChild.
{
        return _firstChild;
    }
const XMLElement * tinyxml2::XMLNode::FirstChildElement (const char * value = 0) const [inherited]
Get the first child element, or optionally the first child element with the specified name.
Definition at line 725 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_next, tinyxml2::XMLElement::Name(), tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLHandle::FirstChildElement(), tinyxml2::XMLConstHandle::FirstChildElement(), tinyxml2::XMLDocument::RootElement(), and corecvs::DeserializerVisitor::visit().
{
    for( XMLNode* node=_firstChild; node; node=node->_next ) {
        XMLElement* element = node->ToElement();
        if ( element ) {
            if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                return element;
            }
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::FirstChildElement (const char * value = 0) [inline, inherited]
Definition at line 646 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->FirstChildElement( value ));
    }
const XMLDocument* tinyxml2::XMLNode::GetDocument () const [inline, inherited]
Get the XMLDocument that owns this XMLNode.
Definition at line 548 of file tinyxml2.h.
References tinyxml2::XMLNode::_document.
Referenced by corecvs::BinarizeBlock::serialize(), corecvs::ThickeningBlock::serialize(), corecvs::MaskFilterBlock::serialize(), corecvs::BackgroundFilter::serialize(), corecvs::BitSelectorFilter::serialize(), corecvs::SobelFilter::serialize(), corecvs::GainOffsetFilter::serialize(), corecvs::CannyFilter::serialize(), corecvs::InputFilter::serialize(), corecvs::Pin::serialize(), corecvs::OutputFilter::serialize(), corecvs::FilterBlock::serialize(), corecvs::OperationFilter::serialize(), and corecvs::SerializerVisitor::visit().
{
        return _document;
    }
XMLDocument* tinyxml2::XMLNode::GetDocument () [inline, inherited]
Get the XMLDocument that owns this XMLNode.
Definition at line 552 of file tinyxml2.h.
References tinyxml2::XMLNode::_document.
{
        return _document;
    }
XMLNode * tinyxml2::XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis) [inherited]
Add a node after the specified child node.
Definition at line 702 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_next, tinyxml2::XMLNode::_parent, tinyxml2::XMLNode::_prev, tinyxml2::XMLNode::InsertEndChild(), tinyxml2::MemPool::SetTracked(), and TIXMLASSERT.
{
    TIXMLASSERT( afterThis->_parent == this );
    if ( afterThis->_parent != this ) {
        return 0;
    }
    if ( afterThis->_next == 0 ) {
        // The last node or the only node.
        return InsertEndChild( addThis );
    }
    addThis->_prev = afterThis;
    addThis->_next = afterThis->_next;
    afterThis->_next->_prev = addThis;
    afterThis->_next = addThis;
    addThis->_parent = this;
    addThis->_memPool->SetTracked();
    return addThis;
}
XMLNode * tinyxml2::XMLNode::InsertEndChild (XMLNode * addThis) [inherited]
Add a child node as the last (right) child.
Definition at line 653 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_lastChild, tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_next, tinyxml2::XMLNode::_parent, tinyxml2::XMLNode::_prev, tinyxml2::MemPool::SetTracked(), and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::LinkEndChild(), tinyxml2::XMLNode::ParseDeep(), corecvs::FiltersCollection::saveCompoundFilters(), corecvs::ThickeningBlock::serialize(), corecvs::BinarizeBlock::serialize(), corecvs::MaskFilterBlock::serialize(), corecvs::BackgroundFilter::serialize(), corecvs::SobelFilter::serialize(), corecvs::BitSelectorFilter::serialize(), corecvs::GainOffsetFilter::serialize(), corecvs::CannyFilter::serialize(), corecvs::InputFilter::serialize(), corecvs::Pin::serialize(), corecvs::OutputFilter::serialize(), corecvs::FilterBlock::serialize(), and corecvs::OperationFilter::serialize().
{
    if ( _lastChild ) {
        TIXMLASSERT( _firstChild );
        TIXMLASSERT( _lastChild->_next == 0 );
        _lastChild->_next = addThis;
        addThis->_prev = _lastChild;
        _lastChild = addThis;
        addThis->_next = 0;
    }
    else {
        TIXMLASSERT( _firstChild == 0 );
        _firstChild = _lastChild = addThis;
        addThis->_prev = 0;
        addThis->_next = 0;
    }
    addThis->_parent = this;
    addThis->_memPool->SetTracked();
    return addThis;
}
XMLNode * tinyxml2::XMLNode::InsertFirstChild (XMLNode * addThis) [inherited]
Add a child node as the first (left) child.
Definition at line 677 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_lastChild, tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_next, tinyxml2::XMLNode::_parent, tinyxml2::XMLNode::_prev, tinyxml2::MemPool::SetTracked(), and TIXMLASSERT.
{
    if ( _firstChild ) {
        TIXMLASSERT( _lastChild );
        TIXMLASSERT( _firstChild->_prev == 0 );
        _firstChild->_prev = addThis;
        addThis->_next = _firstChild;
        _firstChild = addThis;
        addThis->_prev = 0;
    }
    else {
        TIXMLASSERT( _lastChild == 0 );
        _firstChild = _lastChild = addThis;
        addThis->_prev = 0;
        addThis->_next = 0;
    }
    addThis->_parent = this;
    addThis->_memPool->SetTracked();
    return addThis;
}
const XMLNode* tinyxml2::XMLNode::LastChild () const [inline, inherited]
Get the last child node, or null if none exists.
Definition at line 651 of file tinyxml2.h.
References tinyxml2::XMLNode::_lastChild.
Referenced by corecvs::BinarizeBlock::deserialize(), corecvs::ThickeningBlock::deserialize(), corecvs::MaskFilterBlock::deserialize(), corecvs::BackgroundFilter::deserialize(), corecvs::SobelFilter::deserialize(), corecvs::GainOffsetFilter::deserialize(), corecvs::BitSelectorFilter::deserialize(), corecvs::CannyFilter::deserialize(), corecvs::InputFilter::deserialize(), corecvs::OutputFilter::deserialize(), corecvs::OperationFilter::deserialize(), tinyxml2::XMLNode::LastChild(), tinyxml2::XMLHandle::LastChild(), and tinyxml2::XMLConstHandle::LastChild().
{
        return _lastChild;
    }
XMLNode* tinyxml2::XMLNode::LastChild () [inline, inherited]
Definition at line 655 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChild().
{
        return const_cast<XMLNode*>(const_cast<const XMLNode*>(this)->LastChild() );
    }
const XMLElement * tinyxml2::XMLNode::LastChildElement (const char * value = 0) const [inherited]
Get the last child element or optionally the last child element with the specified name.
Definition at line 739 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_lastChild, tinyxml2::XMLNode::_prev, tinyxml2::XMLElement::Name(), tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLHandle::LastChildElement(), and tinyxml2::XMLConstHandle::LastChildElement().
{
    for( XMLNode* node=_lastChild; node; node=node->_prev ) {
        XMLElement* element = node->ToElement();
        if ( element ) {
            if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                return element;
            }
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::LastChildElement (const char * value = 0) [inline, inherited]
Definition at line 664 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChildElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->LastChildElement(value) );
    }
XMLNode* tinyxml2::XMLNode::LinkEndChild (XMLNode * addThis) [inline, inherited]
Definition at line 705 of file tinyxml2.h.
References tinyxml2::XMLNode::InsertEndChild().
{
        return InsertEndChild( addThis );
    }
const XMLNode* tinyxml2::XMLNode::NextSibling () const [inline, inherited]
Get the next (right) sibling node of this node.
Definition at line 685 of file tinyxml2.h.
References tinyxml2::XMLNode::_next.
Referenced by tinyxml2::XMLElement::Accept(), tinyxml2::XMLDocument::Accept(), corecvs::FilterGraph::deserialize(), corecvs::FilterBlock::deserialize(), corecvs::FilterBlock::deserializePins(), corecvs::FiltersCollection::FiltersCollection(), corecvs::FiltersCollection::getContainedBlocks(), tinyxml2::XMLHandle::NextSibling(), and tinyxml2::XMLConstHandle::NextSibling().
{
        return _next;
    }
XMLNode* tinyxml2::XMLNode::NextSibling () [inline, inherited]
Definition at line 689 of file tinyxml2.h.
References tinyxml2::XMLNode::_next.
{
        return _next;
    }
const XMLElement * tinyxml2::XMLNode::NextSiblingElement (const char * value = 0) const [inherited]
Get the next (right) sibling element of this node, with an opitionally supplied name.
Definition at line 753 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_next, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::NextSiblingElement(), tinyxml2::XMLHandle::NextSiblingElement(), and tinyxml2::XMLConstHandle::NextSiblingElement().
{
    for( XMLNode* element=this->_next; element; element = element->_next ) {
        if (    element->ToElement()
                && (!value || XMLUtil::StringEqual( value, element->Value() ))) {
            return element->ToElement();
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::NextSiblingElement (const char * value = 0) [inline, inherited]
Definition at line 696 of file tinyxml2.h.
References tinyxml2::XMLNode::NextSiblingElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->NextSiblingElement( value ) );
    }
bool tinyxml2::XMLNode::NoChildren () const [inline, inherited]
Returns true if this node has no children.
Definition at line 628 of file tinyxml2.h.
References tinyxml2::XMLNode::_firstChild.
{
        return !_firstChild;
    }
XMLDeclaration& tinyxml2::XMLDeclaration::operator= (const XMLDeclaration &) [protected]
const XMLNode* tinyxml2::XMLNode::Parent () const [inline, inherited]
Get the parent of this node on the DOM.
Definition at line 619 of file tinyxml2.h.
References tinyxml2::XMLNode::_parent.
{
        return _parent;
    }
XMLNode* tinyxml2::XMLNode::Parent () [inline, inherited]
Definition at line 623 of file tinyxml2.h.
References tinyxml2::XMLNode::_parent.
{
        return _parent;
    }
char * tinyxml2::XMLDeclaration::ParseDeep (char * p, StrPair * endTag) [virtual]
Reimplemented from tinyxml2::XMLNode.
Definition at line 966 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLNode::_value, tinyxml2::StrPair::NEEDS_NEWLINE_NORMALIZATION, tinyxml2::StrPair::ParseText(), tinyxml2::XMLDocument::SetError(), and tinyxml2::XML_ERROR_PARSING_DECLARATION.
{
    // Declaration parses as text.
    const char* start = p;
    p = _value.ParseText( p, "?>", StrPair::NEEDS_NEWLINE_NORMALIZATION );
    if ( p == 0 ) {
        _document->SetError( XML_ERROR_PARSING_DECLARATION, start, 0 );
    }
    return p;
}
const XMLNode* tinyxml2::XMLNode::PreviousSibling () const [inline, inherited]
Get the previous (left) sibling node of this node.
Definition at line 669 of file tinyxml2.h.
References tinyxml2::XMLNode::_prev.
Referenced by tinyxml2::XMLHandle::PreviousSibling(), and tinyxml2::XMLConstHandle::PreviousSibling().
{
        return _prev;
    }
XMLNode* tinyxml2::XMLNode::PreviousSibling () [inline, inherited]
Definition at line 673 of file tinyxml2.h.
References tinyxml2::XMLNode::_prev.
{
        return _prev;
    }
const XMLElement * tinyxml2::XMLNode::PreviousSiblingElement (const char * value = 0) const [inherited]
Get the previous (left) sibling element of this node, with an opitionally supplied name.
Definition at line 765 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_prev, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::PreviousSiblingElement(), tinyxml2::XMLHandle::PreviousSiblingElement(), and tinyxml2::XMLConstHandle::PreviousSiblingElement().
{
    for( XMLNode* element=_prev; element; element = element->_prev ) {
        if (    element->ToElement()
                && (!value || XMLUtil::StringEqual( value, element->Value() ))) {
            return element->ToElement();
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::PreviousSiblingElement (const char * value = 0) [inline, inherited]
Definition at line 680 of file tinyxml2.h.
References tinyxml2::XMLNode::PreviousSiblingElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->PreviousSiblingElement( value ) );
    }
void tinyxml2::XMLNode::SetValue (const char * val, bool staticMem = false) [inherited]
Set the Value of an XML node.
See also:
Value()
Definition at line 603 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_value, tinyxml2::StrPair::SetInternedStr(), and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLDocument::NewUnknown(), and tinyxml2::XMLElement::SetName().
{
    if ( staticMem ) {
        _value.SetInternedStr( str );
    }
    else {
        _value.SetStr( str );
    }
}
XMLNode * tinyxml2::XMLDeclaration::ShallowClone (XMLDocument * document) const [virtual]
Make a copy of this node, but not its children.
You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
Definition at line 978 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLDocument::NewDeclaration(), and tinyxml2::XMLNode::Value().
{
    if ( !doc ) {
        doc = _document;
    }
    XMLDeclaration* dec = doc->NewDeclaration( Value() );   // fixme: this will always allocate memory. Intern?
    return dec;
}
bool tinyxml2::XMLDeclaration::ShallowEqual (const XMLNode * compare) const [virtual]
Test if 2 nodes are the same, but don't test children.
The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
Definition at line 988 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLNode::ToDeclaration(), and tinyxml2::XMLNode::Value().
{
    return ( compare->ToDeclaration() && XMLUtil::StringEqual( compare->ToDeclaration()->Value(), Value() ));
}
virtual XMLComment* tinyxml2::XMLNode::ToComment () [inline, virtual, inherited]
Safely cast to a Comment, or null.
Reimplemented in tinyxml2::XMLComment.
Definition at line 565 of file tinyxml2.h.
Referenced by tinyxml2::XMLComment::ShallowEqual().
{
        return 0;
    }
virtual const XMLComment* tinyxml2::XMLNode::ToComment () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLComment.
Definition at line 587 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLDeclaration* tinyxml2::XMLDeclaration::ToDeclaration () [inline, virtual]
Safely cast to a Declaration, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 888 of file tinyxml2.h.
{
        return this;
    }
virtual const XMLDeclaration* tinyxml2::XMLDeclaration::ToDeclaration () const [inline, virtual]
Reimplemented from tinyxml2::XMLNode.
Definition at line 891 of file tinyxml2.h.
{
        return this;
    }
virtual XMLDocument* tinyxml2::XMLNode::ToDocument () [inline, virtual, inherited]
Safely cast to a Document, or null.
Reimplemented in tinyxml2::XMLDocument.
Definition at line 569 of file tinyxml2.h.
{
        return 0;
    }
virtual const XMLDocument* tinyxml2::XMLNode::ToDocument () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLDocument.
Definition at line 590 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLElement* tinyxml2::XMLNode::ToElement () [inline, virtual, inherited]
Safely cast to an Element, or null.
Reimplemented in tinyxml2::XMLElement.
Definition at line 557 of file tinyxml2.h.
Referenced by corecvs::BinarizeBlock::deserialize(), corecvs::ThickeningBlock::deserialize(), corecvs::MaskFilterBlock::deserialize(), corecvs::BackgroundFilter::deserialize(), corecvs::SobelFilter::deserialize(), corecvs::GainOffsetFilter::deserialize(), corecvs::BitSelectorFilter::deserialize(), corecvs::CannyFilter::deserialize(), corecvs::InputFilter::deserialize(), corecvs::OutputFilter::deserialize(), corecvs::Pin::deserialize(), corecvs::FilterGraph::deserialize(), corecvs::FilterBlock::deserialize(), corecvs::OperationFilter::deserialize(), corecvs::FilterBlock::deserializePins(), corecvs::FiltersCollection::FiltersCollection(), corecvs::FiltersCollection::getContainedBlocks(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::ShallowEqual(), tinyxml2::XMLHandle::ToElement(), and tinyxml2::XMLConstHandle::ToElement().
{
        return 0;
    }
virtual const XMLElement* tinyxml2::XMLNode::ToElement () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLElement.
Definition at line 581 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLText* tinyxml2::XMLNode::ToText () [inline, virtual, inherited]
Safely cast to Text, or null.
Reimplemented in tinyxml2::XMLText.
Definition at line 561 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLHandle::ToText(), and tinyxml2::XMLConstHandle::ToText().
{
        return 0;
    }
virtual const XMLText* tinyxml2::XMLNode::ToText () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLText.
Definition at line 584 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLUnknown* tinyxml2::XMLNode::ToUnknown () [inline, virtual, inherited]
Safely cast to an Unknown, or null.
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 577 of file tinyxml2.h.
Referenced by tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLHandle::ToUnknown(), and tinyxml2::XMLConstHandle::ToUnknown().
{
        return 0;
    }
virtual const XMLUnknown* tinyxml2::XMLNode::ToUnknown () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 596 of file tinyxml2.h.
{
        return 0;
    }
const char* tinyxml2::XMLNode::Value () const [inline, inherited]
The meaning of 'value' changes for the specific type.
        Document:    empty
        Element:    name of the element
        Comment:    the comment text
        Unknown:    the tag contents
        Text:        the text string
Definition at line 609 of file tinyxml2.h.
References tinyxml2::XMLNode::_value, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::Visit().
{
        return _value.GetStr();
    }
Friends And Related Function Documentation
friend class XMLDocument [friend]
Reimplemented from tinyxml2::XMLNode.
Definition at line 886 of file tinyxml2.h.
Member Data Documentation
XMLDocument* tinyxml2::XMLNode::_document [protected, inherited]
Definition at line 779 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), and tinyxml2::XMLDocument::XMLDocument().
XMLNode* tinyxml2::XMLNode::_firstChild [protected, inherited]
Definition at line 783 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NoChildren(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::_lastChild [protected, inherited]
Definition at line 784 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChild(), tinyxml2::XMLNode::LastChildElement(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::_next [protected, inherited]
Definition at line 787 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NextSibling(), tinyxml2::XMLNode::NextSiblingElement(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::_parent [protected, inherited]
Definition at line 780 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChild(), tinyxml2::XMLDocument::DeleteNode(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::Parent(), tinyxml2::XMLNode::Unlink(), and tinyxml2::XMLNode::~XMLNode().
XMLNode* tinyxml2::XMLNode::_prev [protected, inherited]
Definition at line 786 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::PreviousSibling(), tinyxml2::XMLNode::PreviousSiblingElement(), and tinyxml2::XMLNode::Unlink().
StrPair tinyxml2::XMLNode::_value [mutable, protected, inherited]
Definition at line 781 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLElement::ParseDeep(), tinyxml2::XMLNode::SetValue(), and tinyxml2::XMLNode::Value().
The documentation for this class was generated from the following files:
core/tinyxml/tinyxml2.h
core/tinyxml/tinyxml2.cpp