DeepView: corecvs::BaseReflection< RealThis > Class Template Reference
corecvs::BaseReflection< RealThis > Class Template Reference
This is a common parent for a reflection enabled class basically it just transforms dynamic Reflection class into static field.
#include <reflection.h>
Public Member Functions
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
template<>
Reflection reflection
template<>
int dummy
Static Public Member Functions
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Static Public Attributes
static Reflection reflection
static int dummy
Detailed Description
template<typename RealThis>
class corecvs::BaseReflection< RealThis >
This is a common parent for a reflection enabled class basically it just transforms dynamic Reflection class into static field.
Definition at line 646 of file reflection.h.
Member Function Documentation
template<typename RealThis> static const char* corecvs::BaseReflection< RealThis >::commentById (int fieldId) [inline, static]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
template<> int corecvs::BaseReflection< AxisAlignedBoxParameters >::dummy ()
Definition at line 24 of file axisAlignedBoxParameters.cpp.
template<> int corecvs::BaseReflection< CannyParameters >::dummy ()
Definition at line 24 of file cannyParameters.cpp.
template<> int corecvs::BaseReflection< OutputFilterParameters >::dummy ()
Definition at line 24 of file outputFilterParameters.cpp.
template<> int corecvs::BaseReflection< RgbColorParameters >::dummy ()
Definition at line 24 of file rgbColorParameters.cpp.
template<> int corecvs::BaseReflection< GainOffsetParameters >::dummy ()
Definition at line 24 of file gainOffsetParameters.cpp.
template<> int corecvs::BaseReflection< SobelParameters >::dummy ()
Definition at line 24 of file sobelParameters.cpp.
template<> int corecvs::BaseReflection< ThickeningParameters >::dummy ()
Definition at line 24 of file thickeningParameters.cpp.
template<> int corecvs::BaseReflection< BackgroundFilterParameters >::dummy ()
Definition at line 24 of file backgroundFilterParameters.cpp.
template<> int corecvs::BaseReflection< HeadSearchParameters >::dummy ()
Definition at line 24 of file headSearchParameters.cpp.
template<> int corecvs::BaseReflection< Draw3dCameraParameters >::dummy ()
Definition at line 24 of file draw3dCameraParameters.cpp.
template<> int corecvs::BaseReflection< Draw3dParameters >::dummy ()
Definition at line 24 of file draw3dParameters.cpp.
template<> int corecvs::BaseReflection< InputFilterParameters >::dummy ()
Definition at line 24 of file inputFilterParameters.cpp.
template<> int corecvs::BaseReflection< Draw3dViMouseParameters >::dummy ()
Definition at line 24 of file draw3dViMouseParameters.cpp.
template<> int corecvs::BaseReflection< OpenCVBMParameters >::dummy ()
Definition at line 24 of file openCVBMParameters.cpp.
template<> int corecvs::BaseReflection< BinarizeParameters >::dummy ()
Definition at line 24 of file binarizeParameters.cpp.
template<> int corecvs::BaseReflection< MakePreciseParameters >::dummy ()
Definition at line 24 of file makePreciseParameters.cpp.
template<> int corecvs::BaseReflection< OpenCVSGMParameters >::dummy ()
Definition at line 24 of file openCVSGMParameters.cpp.
template<> int corecvs::BaseReflection< RectifyParameters >::dummy ()
Definition at line 24 of file rectifyParameters.cpp.
template<> int corecvs::BaseReflection< MaskingParameters >::dummy ()
Definition at line 24 of file maskingParameters.cpp.
template<> int corecvs::BaseReflection< GraphPlotParameters >::dummy ()
Definition at line 24 of file graphPlotParameters.cpp.
template<> int corecvs::BaseReflection< BaseParameters >::dummy ()
Definition at line 24 of file baseParameters.cpp.
template<> int corecvs::BaseReflection< BitSelectorParameters >::dummy ()
Definition at line 24 of file bitSelectorParameters.cpp.
template<> int corecvs::BaseReflection< OpenCVFilterParameters >::dummy ()
Definition at line 24 of file openCVFilterParameters.cpp.
template<> int corecvs::BaseReflection< PresentationParameters >::dummy ()
Definition at line 24 of file presentationParameters.cpp.
template<> int corecvs::BaseReflection< Recorder >::dummy ()
Definition at line 24 of file recorder.cpp.
template<> int corecvs::BaseReflection< OperationParameters >::dummy ()
Definition at line 24 of file operationParameters.cpp.
template<typename RealThis> static int corecvs::BaseReflection< RealThis >::fieldNumber () [inline, static]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
template<typename RealThis> static vector<const BaseField *>& corecvs::BaseReflection< RealThis >::fields () [inline, static]
Definition at line 659 of file reflection.h.
Referenced by corecvs::BaseReflection< GainOffsetParameters >::commentById(), corecvs::BaseReflection< GainOffsetParameters >::fieldNumber(), and corecvs::BaseReflection< GainOffsetParameters >::nameById().
    {
        return getReflection()->fields;
    }
template<typename RealThis> static Reflection* corecvs::BaseReflection< RealThis >::getReflection () [inline, static]
Definition at line 654 of file reflection.h.
Referenced by corecvs::BaseReflection< GainOffsetParameters >::fields(), and corecvs::BaseReflection< GainOffsetParameters >::naming().
    {
        return &(RealThis::reflection);
    }
template<typename RealThis> static const char* corecvs::BaseReflection< RealThis >::nameById (int fieldId) [inline, static]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
template<typename RealThis> static ReflectionNaming& corecvs::BaseReflection< RealThis >::naming () [inline, static]
Definition at line 664 of file reflection.h.
    {
        return getReflection()->name;
    }
template<> Reflection corecvs::BaseReflection< Draw3dParameters >::reflection ()
Definition at line 22 of file draw3dParameters.cpp.
template<> Reflection corecvs::BaseReflection< InputFilterParameters >::reflection ()
Definition at line 22 of file inputFilterParameters.cpp.
template<> Reflection corecvs::BaseReflection< BinarizeParameters >::reflection ()
Definition at line 22 of file binarizeParameters.cpp.
template<> Reflection corecvs::BaseReflection< Draw3dViMouseParameters >::reflection ()
Definition at line 22 of file draw3dViMouseParameters.cpp.
template<> Reflection corecvs::BaseReflection< OpenCVSGMParameters >::reflection ()
Definition at line 22 of file openCVSGMParameters.cpp.
template<> Reflection corecvs::BaseReflection< RectifyParameters >::reflection ()
Definition at line 22 of file rectifyParameters.cpp.
template<> Reflection corecvs::BaseReflection< GraphPlotParameters >::reflection ()
Definition at line 22 of file graphPlotParameters.cpp.
template<> Reflection corecvs::BaseReflection< MaskingParameters >::reflection ()
Definition at line 22 of file maskingParameters.cpp.
template<> Reflection corecvs::BaseReflection< PresentationParameters >::reflection ()
Definition at line 22 of file presentationParameters.cpp.
template<> Reflection corecvs::BaseReflection< AxisAlignedBoxParameters >::reflection ()
Definition at line 22 of file axisAlignedBoxParameters.cpp.
Referenced by corecvs::BaseReflection< GainOffsetParameters >::getReflection().
template<> Reflection corecvs::BaseReflection< OperationParameters >::reflection ()
Definition at line 22 of file operationParameters.cpp.
template<> Reflection corecvs::BaseReflection< BaseParameters >::reflection ()
Definition at line 22 of file baseParameters.cpp.
template<> Reflection corecvs::BaseReflection< SobelParameters >::reflection ()
Definition at line 22 of file sobelParameters.cpp.
template<> Reflection corecvs::BaseReflection< BackgroundFilterParameters >::reflection ()
Definition at line 22 of file backgroundFilterParameters.cpp.
template<> Reflection corecvs::BaseReflection< BitSelectorParameters >::reflection ()
Definition at line 22 of file bitSelectorParameters.cpp.
template<> Reflection corecvs::BaseReflection< Draw3dCameraParameters >::reflection ()
Definition at line 22 of file draw3dCameraParameters.cpp.
template<> Reflection corecvs::BaseReflection< CannyParameters >::reflection ()
Definition at line 22 of file cannyParameters.cpp.
template<> Reflection corecvs::BaseReflection< MakePreciseParameters >::reflection ()
Definition at line 22 of file makePreciseParameters.cpp.
template<> Reflection corecvs::BaseReflection< OpenCVFilterParameters >::reflection ()
Definition at line 22 of file openCVFilterParameters.cpp.
template<> Reflection corecvs::BaseReflection< OpenCVBMParameters >::reflection ()
Definition at line 22 of file openCVBMParameters.cpp.
template<> Reflection corecvs::BaseReflection< GainOffsetParameters >::reflection ()
Definition at line 22 of file gainOffsetParameters.cpp.
template<> Reflection corecvs::BaseReflection< RgbColorParameters >::reflection ()
Definition at line 22 of file rgbColorParameters.cpp.
template<> Reflection corecvs::BaseReflection< ThickeningParameters >::reflection ()
Definition at line 22 of file thickeningParameters.cpp.
template<> Reflection corecvs::BaseReflection< OutputFilterParameters >::reflection ()
Definition at line 22 of file outputFilterParameters.cpp.
template<> Reflection corecvs::BaseReflection< Recorder >::reflection ()
Definition at line 22 of file recorder.cpp.
template<> Reflection corecvs::BaseReflection< HeadSearchParameters >::reflection ()
Definition at line 22 of file headSearchParameters.cpp.
Member Data Documentation
template<typename RealThis> int corecvs::BaseReflection< RealThis >::dummy [static]
Definition at line 650 of file reflection.h.
template<typename RealThis> Reflection corecvs::BaseReflection< RealThis >::reflection [static]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following file:
core/reflection/reflection.h