DeepView: corecvs::FilterGraph Class Reference
corecvs::FilterGraph Class Reference
#include <filterGraph.h>
Classes
class NamePredicate
Public Member Functions
FilterGraph (FiltersCollection *_collection, FilterGraph *_parent)
~FilterGraph ()
void clear ()
FilterBlock * addBlock (FilterBlock *block)
void removeBlock (FilterBlock *block)
bool connect (Pin *startPin, Pin *endPin)
void removeConnections (Pin *pin)
FilterBlock * blockByName (const char *name)
void deserialize (const char *)
void deserialize (XMLDocument *)
XMLDocument * serialize ()
void serialize (XMLPrinter *)
FilterGraph * ultimateParent ()
void renewCompoundFilters (int typeId, FilterBlock *blockToIgnore)
bool topologicSort ()
void execute ()
void clearAllData ()
void print ()
void saveToFile (const char *filename)
void loadFromFile (const char *filename)
Static Public Member Functions
static void breakConnection (Pin *startPin, Pin *endPin)
Public Attributes
vector< FilterBlock * > blocks
int blockCounter
vector< Pin * > inputs
vector< Pin * > outputs
FiltersCollection * collection
FilterGraph * parent
Statistics * stats
Detailed Description
Definition at line 20 of file filterGraph.h.
Constructor & Destructor Documentation
corecvs::FilterGraph::FilterGraph (FiltersCollection * _collection, FilterGraph * _parent) [inline]
Definition at line 33 of file filterGraph.h.
                                                                      :
        blockCounter(0)
      , collection(_collection)
      , parent(_parent)
      , stats(NULL)
    {}
corecvs::FilterGraph::~FilterGraph ()
Definition at line 8 of file filterGraph.cpp.
{
    vector<FilterBlock*>::iterator itBlocks;
    for (itBlocks = blocks.begin(); itBlocks != blocks.end(); ++itBlocks)
        delete_safe(*itBlocks);
    blocks.clear();
    inputs.clear();
    outputs.clear();
} // ~FilterGraph
Member Function Documentation
FilterBlock * corecvs::FilterGraph::addBlock (FilterBlock * block)
Definition at line 34 of file filterGraph.cpp.
References corecvs::FilterBlock::COMPOUND_FILTER, corecvs::FilterBlock::INPUT_FILTER, corecvs::FilterBlock::inputPins, corecvs::FilterBlock::OUTPUT_FILTER, corecvs::FilterBlock::outputPins, corecvs::FilterBlock::parent, and corecvs::FilterBlock::sort.
Referenced by FilterGraphPresentation::addFilter().
{
    blocks.push_back(block);
    block->parent = this;
    switch (block->sort)
    {
case FilterBlock::INPUT_FILTER:
        inputs.push_back(block->inputPins[0]);
        break;
case FilterBlock::OUTPUT_FILTER:
        outputs.push_back(block->outputPins[0]);
        break;
case FilterBlock::COMPOUND_FILTER:
        dynamic_cast<CompoundFilter*>(block)->graph->parent = this;
        break;
default:
        break;
    } // switch
    return block;
} // addBlock
FilterBlock* corecvs::FilterGraph::blockByName (const char * name) [inline]
Definition at line 61 of file filterGraph.h.
References blocks.
Referenced by corecvs::Pin::deserialize().
    {
        vector<FilterBlock *>::iterator block = std::find_if(blocks.begin(), blocks.end(), NamePredicate(name));
        if (block == blocks.end()) {
            return NULL;
        }
        return *block;
    }
void corecvs::FilterGraph::breakConnection (Pin * startPin, Pin * endPin) [static]
Definition at line 87 of file filterGraph.cpp.
References corecvs::Pin::takeFrom.
Referenced by FilterGraphPresentation::deleteItem(), and DiagramScene::mouseReleaseEvent().
{
    if (endPin == NULL || startPin == NULL)  return;
    endPin->takeFrom = NULL;
}
void corecvs::FilterGraph::clear ()
Definition at line 18 of file filterGraph.cpp.
Referenced by corecvs::CompoundFilter::loadGraph().
{
    vector<FilterBlock*>::iterator itBlocks;
    for (itBlocks = blocks.begin(); itBlocks != blocks.end(); ++itBlocks)
        delete_safe(*itBlocks);
    blocks.clear();
    inputs.clear();
    outputs.clear();
} // clear()
void corecvs::FilterGraph::clearAllData ()
Definition at line 163 of file filterGraph.cpp.
References corecvs::FilterBlock::INPUT_FILTER.
Referenced by corecvs::CompoundFilter::clear(), and BaseCalculationThread::executeFilterGraph().
{
    for (unsigned int i = 0; i < blocks.size(); i++)
       if (blocks[i]->sort != FilterBlock::INPUT_FILTER)  blocks[i]->clear();
}
bool corecvs::FilterGraph::connect (Pin * startPin, Pin * endPin)
Definition at line 77 of file filterGraph.cpp.
References corecvs::Pin::INPUT_PIN, corecvs::Pin::OUTPUT_PIN, corecvs::Pin::takeFrom, and corecvs::Pin::type.
Referenced by DiagramScene::mouseReleaseEvent().
{
    if (endPin == NULL || startPin == NULL)  return false;
    if (endPin->takeFrom)  return false;
    if (startPin->type == Pin::OUTPUT_PIN && endPin->type == Pin::INPUT_PIN)
         endPin->takeFrom = startPin;
    else return false;
    return true;
}
void corecvs::FilterGraph::deserialize (const char * xml)
Definition at line 237 of file filterGraph.cpp.
References tinyxml2::XMLDocument::Error(), and tinyxml2::XMLDocument::Parse().
Referenced by BaseCalculationThread::graphChanged(), and FilterGraphPresentation::serializeClicked().
{
    XMLDocument* doc = new XMLDocument();
    XMLError errorId = doc->Parse(xml);
    if (doc->Error())
    {   cout << "Parsing Error: " << errorId << endl;
        delete doc;
        return;
    }
    deserialize(doc);
    delete doc;
}
void corecvs::FilterGraph::deserialize (XMLDocument * doc)
Definition at line 250 of file filterGraph.cpp.
References tinyxml2::XMLElement::Attribute(), corecvs::FilterBlock::deserialize(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLElement::IntAttribute(), tinyxml2::XMLNode::NextSibling(), and tinyxml2::XMLNode::ToElement().
{
    XMLNode* p = doc->FirstChild();
    while (p)
    {   FilterBlock* filter = collection->getBlockFromName(p->ToElement()->Attribute("type"),
                                                           p->ToElement()->IntAttribute("id"));
        addBlock(filter);
        filter->deserialize(p);
        p = p->NextSibling();
    }
} // deserialize
void corecvs::FilterGraph::execute ()
Definition at line 141 of file filterGraph.cpp.
References corecvs::FilterBlock::clear(), corecvs::PreciseTimer::currentTime(), corecvs::FilterBlock::getFullName(), corecvs::FilterBlock::inputPins, corecvs::FilterBlock::PROCESSING_FILTER, and corecvs::PreciseTimer::usecsToNow().
Referenced by BaseCalculationThread::executeFilterGraph().
{
    /* Ok, we expect graph to be topologically sorted*/
    for (unsigned int i = 0; i < blocks.size(); i++)
    {
        FilterBlock *block = blocks[i];
        for (unsigned int j = 0; j < block->inputPins.size(); j++)
        {
            block->inputPins[j]->setPin(block->inputPins[j]->takeFrom);
        }
        PreciseTimer blockExecutionTime = PreciseTimer::currentTime();
        block->operator ()();
        if (stats != NULL) {
            stats->setTime(block->getFullName(), blockExecutionTime.usecsToNow());
        }
    } // for
    for (unsigned int i = 0; i < blocks.size(); i++)
        if (blocks[i]->sort == FilterBlock::PROCESSING_FILTER)  blocks[i]->clear();
} // execute
void corecvs::FilterGraph::loadFromFile (const char * filename)
Definition at line 204 of file filterGraph.cpp.
References tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XML_SUCCESS.
Referenced by corecvs::CompoundFilter::CompoundFilter(), BaseHostDialog::initGraphPresentation(), and corecvs::CompoundFilter::loadGraph().
{
//        FILE *file = fopen("graph.conf", "r");
//        if (NULL == file)  return;
//        XMLDocument doc;
//        XMLError err = doc.LoadFile(file);
//        if (err != XML_SUCCESS)  return;
//        deserialize(&doc);
//        fclose(file);
    XMLDocument doc;
    XMLError err = doc.LoadFile(filename);
    if (err != XML_SUCCESS)  return;
    deserialize(&doc);
}
void corecvs::FilterGraph::print ()
Definition at line 169 of file filterGraph.cpp.
{
    printf("Quantity of blocks: %d\n", (int)blocks.size());
    vector<FilterBlock *>::iterator itBlocks;
    for (itBlocks = blocks.begin(); itBlocks != blocks.end(); ++itBlocks)
    {
        printf("%s\n", (*itBlocks)->getInstanceName());
        for (unsigned int j = 0; j < (*itBlocks)->inputPins.size(); j++)
            if ((*itBlocks)->inputPins[j]->takeFrom != NULL)
                printf("%s:%s -> %s:%s\n",
                       (*itBlocks)->inputPins[j]->takeFrom->parent->getInstanceName(),
                       (*itBlocks)->inputPins[j]->takeFrom->instanceName,
                       (*itBlocks)->getInstanceName(),
                       (*itBlocks)->inputPins[j]->instanceName);
    }
} // print
void corecvs::FilterGraph::removeBlock (FilterBlock * block)
Definition at line 57 of file filterGraph.cpp.
References corecvs::FilterBlock::inputPins, and corecvs::FilterBlock::outputPins.
Referenced by FilterGraphPresentation::deleteItem().
{
    vector<FilterBlock*>::iterator blocksIterator = std::find(blocks.begin(), blocks.end(), block);
    if (blocksIterator != blocks.end())  blocks.erase(blocksIterator);
    for (unsigned int i = 0; i < block->inputPins.size(); i++)
    {   vector<Pin*>::iterator pinsIterator = std::find(inputs.begin(), inputs.end(), block->inputPins[i]);
        if (pinsIterator != inputs.end())  inputs.erase(pinsIterator);
    }
    for (unsigned int i = 0; i < block->outputPins.size(); i++)
    {   vector<Pin*>::iterator pinsIterator = std::find(outputs.begin(), outputs.end(), block->outputPins[i]);
        if (pinsIterator != outputs.end())  outputs.erase(pinsIterator);
        removeConnections(block->outputPins[i]);
        if (block->outputPins[i]->parent != block)
            dynamic_cast<CompoundFilter*>(block->outputPins[i]->parent)->parent->removeConnections(block->outputPins[i]);
    }
} // removeBlock
void corecvs::FilterGraph::removeConnections (Pin * pin)
Definition at line 93 of file filterGraph.cpp.
{
    for (unsigned int i = 0; i < blocks.size(); i++)
       for (unsigned int j = 0; j < blocks[i]->inputPins.size(); j++)
          if (blocks[i]->inputPins[j]->takeFrom == pin)
              blocks[i]->inputPins[j]->takeFrom = NULL;
}
void corecvs::FilterGraph::renewCompoundFilters (int typeId, FilterBlock * blockToIgnore)
Definition at line 269 of file filterGraph.cpp.
References corecvs::CompoundFilter::graph, corecvs::CompoundFilter::loadGraph(), renewCompoundFilters(), and corecvs::CompoundFilter::typeId.
Referenced by FilterGraphPresentation::addFilter(), FilterGraphPresentation::closeEvent(), FilterGraphPresentation::deleteItem(), and renewCompoundFilters().
{
    for (unsigned int i = 0; i < blocks.size(); i++)
    {   CompoundFilter* b = dynamic_cast<CompoundFilter*>(blocks[i]);
        if (b == NULL || b == blockToIgnore)  continue;
        if (b->typeId == _typeid)
             b->loadGraph();
        else b->graph->renewCompoundFilters(_typeid, blockToIgnore);
    }
}
void corecvs::FilterGraph::saveToFile (const char * filename)
Definition at line 186 of file filterGraph.cpp.
Referenced by FilterGraphPresentation::saveAsClicked(), and FilterGraphPresentation::saveGraphToFile().
{
    FILE *file = fopen(filename, "w");
    XMLPrinter* printer = new XMLPrinter(file);
    serialize(printer);
    fclose(file);
    delete printer;
}
XMLDocument * corecvs::FilterGraph::serialize ()
Definition at line 227 of file filterGraph.cpp.
Referenced by FilterGraphPresentation::graphChangedSlot(), and FilterGraphPresentation::serializeClicked().
{
    XMLDocument* doc = new XMLDocument();
    topologicSort();
    for (unsigned int i = 0; i < blocks.size(); i++)
       blocks[i]->serialize(doc);
    return doc;
}
void corecvs::FilterGraph::serialize (XMLPrinter * stream)
Definition at line 220 of file filterGraph.cpp.
References tinyxml2::XMLDocument::Print().
{
    XMLDocument* doc = serialize();
    doc->Print(stream);
    delete doc;
}
bool corecvs::FilterGraph::topologicSort ()
Definition at line 102 of file filterGraph.cpp.
Referenced by FilterGraphPresentation::drawGraph().
{
    /* Count inputs to blocks */
    for (unsigned int i = 0; i < blocks.size(); i++)
    {  blocks[i]->inLinks = 0;
       for (unsigned int j = 0; j < blocks[i]->inputPins.size(); j++)
          if ( blocks[i]->inputPins[j]->takeFrom != NULL &&
               !blocks[i]->isOuterPin(blocks[i]->inputPins[j]) )
             blocks[i]->inLinks++;
    }
    vector<FilterBlock*> result;
    while(true)
    {   /* Find Blocks with no links */
        vector<FilterBlock *>::iterator itBlocks;
        for (itBlocks = blocks.begin(); itBlocks != blocks.end(); ++itBlocks)
            if ((*itBlocks)->inLinks == 0)  break;
        if (itBlocks == blocks.end()) /* No objects found */
            return false;
        result.push_back(*itBlocks);
        /* Count inputs to blocks */
        for (unsigned int i = 0; i < blocks.size(); i++)
           for (unsigned int j = 0; j < blocks[i]->inputPins.size(); j++)
               if (blocks[i]->inputPins[j]->takeFrom != NULL &&
                   blocks[i]->inputPins[j]->takeFrom->parent == *itBlocks)
               {
                   blocks[i]->inLinks--;
               }
        blocks.erase(itBlocks);
        if (blocks.size() == 0)  break;
    } // while(true)
    blocks = result;
    return true;
} // topologicSort
FilterGraph * corecvs::FilterGraph::ultimateParent ()
Definition at line 262 of file filterGraph.cpp.
References parent.
Referenced by FilterGraphPresentation::addFilter(), FilterGraphPresentation::closeEvent(), and FilterGraphPresentation::deleteItem().
{
    FilterGraph* p = this;
    while (p->parent)  p = p->parent;
    return p;
}
Member Data Documentation
int corecvs::FilterGraph::blockCounter
Definition at line 24 of file filterGraph.h.
vector<FilterBlock*> corecvs::FilterGraph::blocks
Definition at line 23 of file filterGraph.h.
Referenced by blockByName(), FilterGraphPresentation::drawGraph(), FilterPinPresentation::FilterPinPresentation(), corecvs::CompoundFilter::loadGraph(), and FilterGraphPresentation::restoreFromGraph().
FiltersCollection* corecvs::FilterGraph::collection
Definition at line 27 of file filterGraph.h.
Referenced by corecvs::CompoundFilter::loadGraph().
vector<Pin*> corecvs::FilterGraph::inputs
Definition at line 25 of file filterGraph.h.
Referenced by BaseCalculationThread::executeFilterGraph(), and corecvs::CompoundFilter::stealPinsFromGraph().
vector<Pin*> corecvs::FilterGraph::outputs
Definition at line 26 of file filterGraph.h.
Referenced by BaseCalculationThread::executeFilterGraph(), and corecvs::CompoundFilter::stealPinsFromGraph().
FilterGraph* corecvs::FilterGraph::parent
Definition at line 28 of file filterGraph.h.
Referenced by ultimateParent().
Statistics* corecvs::FilterGraph::stats
Definition at line 31 of file filterGraph.h.
Referenced by BaseCalculationThread::executeFilterGraph().
The documentation for this class was generated from the following files:
core/filters/blocks/filterGraph.h
core/filters/blocks/filterGraph.cpp