DeepView: corecvs::ModelFundamental8Point Class Reference
corecvs::ModelFundamental8Point Class Reference
Public Member Functions
ModelFundamental8Point ()
ModelFundamental8Point (const vector< Correspondance * > &samples)
bool fits (const Correspondance &data, double fitTreshold)
Public Attributes
EssentialMatrix model
Detailed Description
Definition at line 46 of file ransacEstimator.cpp.
Constructor & Destructor Documentation
corecvs::ModelFundamental8Point::ModelFundamental8Point () [inline]
Definition at line 49 of file ransacEstimator.cpp.
: Model8Point() {};
corecvs::ModelFundamental8Point::ModelFundamental8Point (const vector< Correspondance * > & samples) [inline]
Definition at line 50 of file ransacEstimator.cpp.
References corecvs::EssentialMatrix::assertRank2(), and corecvs::Model8Point::model.
                                                                    :
                Model8Point(samples)
    {
        model.assertRank2();
    };
Member Function Documentation
bool corecvs::Model8Point::fits (const Correspondance & data, double fitTreshold) [inline, inherited]
Definition at line 40 of file ransacEstimator.cpp.
References corecvs::EssentialMatrix::epipolarDistance(), and corecvs::Model8Point::model.
Referenced by corecvs::RansacEstimator::getEssentialRansac(), and corecvs::RansacEstimator::getFundamentalRansac().
    {
        return (model.epipolarDistance(data) < fitTreshold);
    }
Member Data Documentation
EssentialMatrix corecvs::Model8Point::model [inherited]
Definition at line 25 of file ransacEstimator.cpp.
Referenced by corecvs::Model8Point::fits(), corecvs::RansacEstimator::getEssentialRansac(), corecvs::RansacEstimator::getFundamentalRansac(), corecvs::Model8Point::Model8Point(), corecvs::ModelEssential8Point::ModelEssential8Point(), and ModelFundamental8Point().
The documentation for this class was generated from the following file:
core/rectification/ransacEstimator.cpp