DeepView: PointsRectificationWidget Class Reference
PointsRectificationWidget Class Reference
#include <pointsRectificationWidget.h>
Signals
void readyCorrespondancePoints (CorrespondanceList *correspondancePoints, G12Buffer *leftBuffer, G12Buffer *rightBuffer)
Public Member Functions
PointsRectificationWidget (QWidget *parent=0)
~PointsRectificationWidget ()
void setImage (G12Buffer *buffer, Frames::FrameSourceId id)
void addPointPair (QPointF const &leftPoint, QPointF const &rightPoint)
Private Slots
void deletePairs ()
void addPair ()
void editPointLeftImage (QPointF const &prevPoint, QPointF const &newPoint)
void editPointRightImage (QPointF const &prevPoint, QPointF const &newPoint)
void selectionChanged (QItemSelection const &selected, QItemSelection const &deselected)
void initCorrespondancePoints ()
void updateRightZoom (double zoom)
void updateLeftZoom (double zoom)
void updateRightCenter (QPoint center)
void updateLeftCenter (QPoint center)
Private Member Functions
void initModel ()
void setNewPointsCoord (QPointF const &prevPoint, QPointF const &newPoint, bool isLeftImage)
Static Private Member Functions
static bool isNextRow (QModelIndex const &index1, QModelIndex const &index2)
Private Attributes
Ui::PointsRectificationWidget * mUi
QStandardItemModel * mPointModel
CorrespondanceList * mCorrespondancePoints
G12Buffer * mLeftBuffer
G12Buffer * mRightBuffer
Detailed Description
Definition at line 14 of file pointsRectificationWidget.h.
Constructor & Destructor Documentation
PointsRectificationWidget::PointsRectificationWidget (QWidget * parent = 0) [explicit]
Definition at line 6 of file pointsRectificationWidget.cpp.
References addPair(), deletePairs(), editPointLeftImage(), editPointRightImage(), initCorrespondancePoints(), initModel(), mUi, updateLeftCenter(), updateLeftZoom(), updateRightCenter(), and updateRightZoom().
                                                                    :
      QWidget(parent)
    , mUi(new Ui::PointsRectificationWidget)
    , mCorrespondancePoints(NULL)
    , mLeftBuffer(NULL)
    , mRightBuffer(NULL)
{
    mUi->setupUi(this);
    initModel();
    connect(mUi->deleteButton , SIGNAL(released()), this, SLOT(deletePairs()));
    connect(mUi->addButton    , SIGNAL(released()), this, SLOT(addPair()));
    connect(mUi->rectifyButton, SIGNAL(released()), this, SLOT(initCorrespondancePoints()));
    connect(mUi->leftWidget, SIGNAL(editPoint(QPointF,QPointF)), this, SLOT(editPointLeftImage(QPointF,QPointF)));
    connect(mUi->rightWidget, SIGNAL(editPoint(QPointF,QPointF)), this, SLOT(editPointRightImage(QPointF,QPointF)));
    connect(mUi->leftWidget , SIGNAL(notifyCenterPointChanged(QPoint)), this, SLOT(updateRightCenter(QPoint)));
    connect(mUi->rightWidget, SIGNAL(notifyCenterPointChanged(QPoint)), this, SLOT(updateLeftCenter (QPoint)));
    connect(mUi->leftWidget , SIGNAL(notifyZoomChanged(double)), this, SLOT(updateRightZoom(double)));
    connect(mUi->rightWidget, SIGNAL(notifyZoomChanged(double)), this, SLOT(updateLeftZoom (double)));
    connect(mUi->rightWidget, SIGNAL(toolButtonClicked(ToolButtonType)), mUi->leftWidget, SLOT(clickToolButton(ToolButtonType)));
    connect(mUi->leftWidget, SIGNAL(toolButtonClicked(ToolButtonType)), mUi->rightWidget, SLOT(clickToolButton(ToolButtonType)));
}
PointsRectificationWidget::~PointsRectificationWidget ()
Definition at line 100 of file pointsRectificationWidget.cpp.
References mCorrespondancePoints, mLeftBuffer, mPointModel, mRightBuffer, and mUi.
{
    delete_safe(mUi);
    delete_safe(mPointModel);
    delete_safe(mCorrespondancePoints);
    delete_safe(mLeftBuffer);
    delete_safe(mRightBuffer);
}
Member Function Documentation
void PointsRectificationWidget::addPair () [private, slot]
Definition at line 178 of file pointsRectificationWidget.cpp.
References addPointPair(), and mUi.
Referenced by PointsRectificationWidget().
{
    QPointF leftPoint  = mUi->leftWidget->currentPoint();
    QPointF rightPoint = mUi->rightWidget->currentPoint();
    addPointPair(leftPoint, rightPoint);
}
void PointsRectificationWidget::addPointPair (QPointF const & leftPoint, QPointF const & rightPoint)
Definition at line 131 of file pointsRectificationWidget.cpp.
References mPointModel, mUi, and Qt2Core::Vector2ddFromQPointF().
Referenced by addPair().
{
    QList<QStandardItem *> items;
    items << new QStandardItem(QString::number(leftPoint.x()))  << new QStandardItem(QString::number(leftPoint.y()))
          << new QStandardItem(QString::number(rightPoint.x())) << new QStandardItem(QString::number(rightPoint.y()));
    foreach (QStandardItem *item, items)
    {
        item->setEditable(false);
    }
    mPointModel->appendRow(items);
    mUi->leftWidget ->addVertex(Qt2Core::Vector2ddFromQPointF(leftPoint ));
    mUi->rightWidget->addVertex(Qt2Core::Vector2ddFromQPointF(rightPoint));
}
void PointsRectificationWidget::deletePairs () [private, slot]
Definition at line 145 of file pointsRectificationWidget.cpp.
References mPointModel, mUi, and Qt2Core::Vector2ddFromQPointF().
Referenced by PointsRectificationWidget().
{
    QModelIndexList selectedIndices = mUi->pointsMatchingTableView->selectionModel()->selectedIndexes();
    QMap<int, QModelIndex> toDelete;
    foreach (QModelIndex const &index, selectedIndices)
    {
        if (toDelete.contains(index.row()))
            continue;
        toDelete[index.row()] = index;
    }
    for (int i = toDelete.values().size() - 1; i >= 0; i--)
    {
        int selectedRow = toDelete.keys().at(i);
        QPointF leftPoint(mPointModel->item(selectedRow, 0)->text().toDouble(),
                          mPointModel->item(selectedRow, 1)->text().toDouble());
        QPointF rightPoint(mPointModel->item(selectedRow, 2)->text().toDouble(),
                           mPointModel->item(selectedRow, 3)->text().toDouble());
        mUi->leftWidget->deleteVertex(Qt2Core::Vector2ddFromQPointF(leftPoint));
        mUi->rightWidget->deleteVertex(Qt2Core::Vector2ddFromQPointF(rightPoint));
        mPointModel->removeRow(selectedRow);
    }
}
void PointsRectificationWidget::editPointLeftImage (QPointF const & prevPoint, QPointF const & newPoint) [private, slot]
Definition at line 33 of file pointsRectificationWidget.cpp.
References setNewPointsCoord().
Referenced by PointsRectificationWidget().
{
    setNewPointsCoord(prevPoint, newPoint, true);
}
void PointsRectificationWidget::editPointRightImage (QPointF const & prevPoint, QPointF const & newPoint) [private, slot]
Definition at line 38 of file pointsRectificationWidget.cpp.
References setNewPointsCoord().
Referenced by PointsRectificationWidget().
{
    setNewPointsCoord(prevPoint, newPoint, false);
}
void PointsRectificationWidget::initCorrespondancePoints () [private, slot]
Definition at line 185 of file pointsRectificationWidget.cpp.
References corecvs::CorrespondanceList::h, corecvs::AbstractBufferParams::h, mCorrespondancePoints, mLeftBuffer, mPointModel, mRightBuffer, readyCorrespondancePoints(), corecvs::CorrespondanceList::w, and corecvs::AbstractBufferParams::w.
Referenced by PointsRectificationWidget().
{
    delete mCorrespondancePoints;
    mCorrespondancePoints = new CorrespondanceList();
    for (int i = 0; i < mPointModel->rowCount(); i ++)
    {
        Vector2dd left (mPointModel->item(i, 0)->text().toDouble(), mPointModel->item(i,1)->text().toDouble());
        Vector2dd right(mPointModel->item(i, 2)->text().toDouble(), mPointModel->item(i, 3)->text().toDouble());
        mCorrespondancePoints->push_back(Correspondance(left, right));
    }
    mCorrespondancePoints->h = mLeftBuffer->h;
    mCorrespondancePoints->w = mLeftBuffer->w;
    emit readyCorrespondancePoints(mCorrespondancePoints, mLeftBuffer, mRightBuffer);
}
void PointsRectificationWidget::initModel () [private]
Definition at line 60 of file pointsRectificationWidget.cpp.
References mPointModel, mUi, and selectionChanged().
Referenced by PointsRectificationWidget().
{
    mPointModel = new QStandardItemModel();
    QStringList headers;
    headers << "Left point x" << "Left point y" << "Right point x" << "Right point y";
    mPointModel->setHorizontalHeaderLabels(headers);
    mUi->pointsMatchingTableView->setModel(mPointModel);
    connect(mUi->pointsMatchingTableView->selectionModel(),
            SIGNAL(selectionChanged(QItemSelection,QItemSelection)),
            this,
            SLOT  (selectionChanged(QItemSelection,QItemSelection)));
}
bool PointsRectificationWidget::isNextRow (QModelIndex const & index1, QModelIndex const & index2) [static, private]
Definition at line 173 of file pointsRectificationWidget.cpp.
{
    return index1.row() > index2.row();
}
void PointsRectificationWidget::readyCorrespondancePoints (CorrespondanceList * correspondancePoints, G12Buffer * leftBuffer, G12Buffer * rightBuffer) [signal]
Referenced by initCorrespondancePoints().
void PointsRectificationWidget::selectionChanged (QItemSelection const & selected, QItemSelection const & deselected) [private, slot]
Definition at line 73 of file pointsRectificationWidget.cpp.
References mPointModel, and mUi.
Referenced by initModel().
{
    foreach (QModelIndex const &index, selected.indexes())
    {
        //FIXME:: check all collumns?
        if (index.column() == 0)
        {
            int row = index.row();
            QPointF leftPoint(mPointModel->item(row, 0)->text().toDouble(), mPointModel->item(row, 1)->text().toDouble());
            QPointF rightPoint(mPointModel->item(row, 2)->text().toDouble(), mPointModel->item(row, 3)->text().toDouble());
            mUi->leftWidget ->setSelectedPoint(leftPoint, true);
            mUi->rightWidget->setSelectedPoint(rightPoint, true);
        }
    }
    foreach (QModelIndex const &index, deselected.indexes())
    {
        if (index.column() == 0)
        {
            int row = index.row();
            QPointF leftPoint(mPointModel->item(row, 0)->text().toDouble(), mPointModel->item(row, 1)->text().toDouble());
            QPointF rightPoint(mPointModel->item(row, 2)->text().toDouble(), mPointModel->item(row, 3)->text().toDouble());
            mUi->leftWidget->setSelectedPoint(leftPoint, false);
            mUi->rightWidget->setSelectedPoint(rightPoint, false);
        }
    }
}
void PointsRectificationWidget::setImage (G12Buffer * buffer, Frames::FrameSourceId id)
Definition at line 109 of file pointsRectificationWidget.cpp.
References Frames::LEFT_FRAME, mLeftBuffer, mRightBuffer, mUi, and Frames::RIGHT_FRAME.
{
    if (buffer == NULL) {
        return;
    }
    switch (id)
    {
    case Frames::LEFT_FRAME :
        delete mLeftBuffer;
        mLeftBuffer = new G12Buffer(buffer);
        mUi->leftWidget->setImage(QSharedPointer<QImage>(new G12Image(buffer)));
        break;
    case Frames::RIGHT_FRAME :
        delete mRightBuffer;
        mRightBuffer = new G12Buffer(buffer);
        mUi->rightWidget->setImage(QSharedPointer<QImage>(new G12Image(buffer)));
        break;
    default:
        break;
    }
}
void PointsRectificationWidget::setNewPointsCoord (QPointF const & prevPoint, QPointF const & newPoint, bool isLeftImage) [private]
Definition at line 43 of file pointsRectificationWidget.cpp.
References mPointModel.
Referenced by editPointLeftImage(), and editPointRightImage().
{
    int xColumn = isLeftImage ? 0 : 2;
    int yColumn = isLeftImage ? 1 : 3;
    for (int i = 0; i < mPointModel->rowCount(); i ++)
    {
        if (fabs(mPointModel->item(i, xColumn)->text().toDouble() - prevPoint.x()) < 0.001 &&
            fabs(mPointModel->item(i, yColumn)->text().toDouble() - prevPoint.y()) < 0.001)
        {
            QStandardItem *itemX = new QStandardItem(QString::number(newPoint.x()));
            QStandardItem *itemY = new QStandardItem(QString::number(newPoint.y()));
            mPointModel->setItem(i, xColumn, itemX);
            mPointModel->setItem(i, yColumn, itemY);
        }
    }
}
void PointsRectificationWidget::updateLeftCenter (QPoint center) [private, slot]
Definition at line 230 of file pointsRectificationWidget.cpp.
References mUi.
Referenced by PointsRectificationWidget().
{
    if (!mUi->lockButton->isChecked())
        return;
    mUi->leftWidget->blockSignals(true);
    mUi->leftWidget->changeCenterPoint(center);
    mUi->leftWidget->blockSignals(false);
}
void PointsRectificationWidget::updateLeftZoom (double zoom) [private, slot]
Definition at line 212 of file pointsRectificationWidget.cpp.
References mUi.
Referenced by PointsRectificationWidget().
{
    if (!mUi->lockButton->isChecked())
        return;
    mUi->leftWidget->blockSignals(true);
    mUi->leftWidget->changeZoom(zoom);
    mUi->leftWidget->blockSignals(false);
}
void PointsRectificationWidget::updateRightCenter (QPoint center) [private, slot]
Definition at line 221 of file pointsRectificationWidget.cpp.
References mUi.
Referenced by PointsRectificationWidget().
{
    if (!mUi->lockButton->isChecked())
        return;
    mUi->rightWidget->blockSignals(true);
    mUi->rightWidget->changeCenterPoint(center);
    mUi->rightWidget->blockSignals(false);
}
void PointsRectificationWidget::updateRightZoom (double zoom) [private, slot]
Definition at line 203 of file pointsRectificationWidget.cpp.
References mUi.
Referenced by PointsRectificationWidget().
{
    if (!mUi->lockButton->isChecked())
        return;
    mUi->rightWidget->blockSignals(true);
    mUi->rightWidget->changeZoom(zoom);
    mUi->rightWidget->blockSignals(false);
}
Member Data Documentation
CorrespondanceList* PointsRectificationWidget::mCorrespondancePoints [private]
Definition at line 30 of file pointsRectificationWidget.h.
Referenced by initCorrespondancePoints(), and ~PointsRectificationWidget().
G12Buffer* PointsRectificationWidget::mLeftBuffer [private]
Definition at line 31 of file pointsRectificationWidget.h.
Referenced by initCorrespondancePoints(), setImage(), and ~PointsRectificationWidget().
QStandardItemModel* PointsRectificationWidget::mPointModel [private]
Definition at line 26 of file pointsRectificationWidget.h.
Referenced by addPointPair(), deletePairs(), initCorrespondancePoints(), initModel(), selectionChanged(), setNewPointsCoord(), and ~PointsRectificationWidget().
G12Buffer* PointsRectificationWidget::mRightBuffer [private]
Definition at line 32 of file pointsRectificationWidget.h.
Referenced by initCorrespondancePoints(), setImage(), and ~PointsRectificationWidget().
Ui::PointsRectificationWidget* PointsRectificationWidget::mUi [private]
Definition at line 25 of file pointsRectificationWidget.h.
Referenced by addPair(), addPointPair(), deletePairs(), initModel(), PointsRectificationWidget(), selectionChanged(), setImage(), updateLeftCenter(), updateLeftZoom(), updateRightCenter(), updateRightZoom(), and ~PointsRectificationWidget().
The documentation for this class was generated from the following files:
utils/uis/pointsRectificationWidget.h
utils/uis/pointsRectificationWidget.cpp