DeepView: AbstractCalculationThread Class Reference
AbstractCalculationThread Class Reference
#include <abstractCalculationThread.h>
Public Types
enum CalculationState {
CALCULATION_NOT_STARTED = 0, CALCULATION_AWAITING_DATA, CALCULATION_ACTIVE, CALCULATION_PAUSED,
CALCULATION_TERMINATED
}
Signals
void processingFinished (AbstractOutputData *output)
void calculationStateChanged (AbstractCalculationThread::CalculationState state)
Public Member Functions
AbstractCalculationThread ()
virtual ~AbstractCalculationThread ()
virtual void run ()
virtual void setCalculationState (CalculationState state)
virtual CalculationState getCalculationState () const
Frames * getFramesHolder ()
void setImageCaptureInterface (ImageCaptureInterface *captureInterface)
Public Attributes
FiltersCollection mFiltersCollection
Static Public Attributes
static const char * stateNames []
Protected Slots
virtual void newFrameReady (frame_data_t frameData)
New frame data is ready to be processed.
virtual void pauseCalculation ()
Pauses calculation.
virtual void resumeCalculation ()
Resumes calculation Should only be called as a asynchronous slot function.
Protected Member Functions
virtual AbstractOutputData * processNewData ()=0
This is the main calculation routine called when a new frame is received.
Protected Attributes
ImageCaptureInterface * mCaptureInterface
The capture interface we fetch the frames from.
Frames mFrames
Holds the last two sets of frames acquired from the capture device(s)
uint64_t mInterframeDelay
Delay between this and previous frame.
uint64_t mLastFrameTimeStamp
CalculationState mCurrentState
Current calculation state This state can't be changed directly, but can be queried.
Detailed Description
Definition at line 36 of file abstractCalculationThread.h.
Member Enumeration Documentation
enum AbstractCalculationThread::CalculationState
Enumerator:
CALCULATION_NOT_STARTED
Thread is just created but still not running.
CALCULATION_AWAITING_DATA
Thread is blocked waiting for signals with frames.
CALCULATION_ACTIVE
Thread is processing the frame.
CALCULATION_PAUSED
Thread is paused, it will ignore incoming frames.
CALCULATION_TERMINATED
Thread has exited.
Definition at line 41 of file abstractCalculationThread.h.
        {
            CALCULATION_NOT_STARTED = 0, /**< Thread is just created but still not running */
            CALCULATION_AWAITING_DATA,   /**< Thread is blocked waiting for signals with frames */
            CALCULATION_ACTIVE,          /**< Thread is processing the frame */
            CALCULATION_PAUSED,          /**< Thread is paused, it will ignore incoming frames */
            CALCULATION_TERMINATED       /**< Thread has exited */
        };
Constructor & Destructor Documentation
AbstractCalculationThread::AbstractCalculationThread ()
Definition at line 35 of file abstractCalculationThread.cpp.
                                                     :
    mCaptureInterface(NULL)
  , mInterframeDelay(0)
  , mLastFrameTimeStamp(0)
  , mCurrentState(CALCULATION_NOT_STARTED)
{
    qRegisterMetaType<AbstractCalculationThread::CalculationState>("AbstractCalculationThread::CalculationState");
    // TODO: this is a workaround to fix the problem of AbstractCalculationThread slots
    //       being processed in a wrong thread context.
    //       AbstractCalculationThread should not inherit from QThread but rather be
    //       created in the context of a new thread.
    moveToThread(this);
}
virtual AbstractCalculationThread::~AbstractCalculationThread () [inline, virtual]
Definition at line 86 of file abstractCalculationThread.h.
{}
Member Function Documentation
void AbstractCalculationThread::calculationStateChanged (AbstractCalculationThread::CalculationState state) [signal]
Referenced by newFrameReady(), pauseCalculation(), and resumeCalculation().
virtual CalculationState AbstractCalculationThread::getCalculationState () const [inline, virtual]
Definition at line 95 of file abstractCalculationThread.h.
References mCurrentState.
Referenced by BaseHostDialog::play().
        {
            return mCurrentState;
        }
Frames* AbstractCalculationThread::getFramesHolder () [inline]
Definition at line 100 of file abstractCalculationThread.h.
References mFrames.
Referenced by BaseHostDialog::initCalculator().
        {
            return &mFrames;
        }
void AbstractCalculationThread::newFrameReady (frame_data_t frameData) [protected, virtual, slot]
New frame data is ready to be processed.
Connect this slot to the newFrameReady signal emitted by the capture interface. In this slot we actually grab the frames and trigger the calculation.
Note:
Do not override this implementation unless you really know what you are doing.
This function processes the newFrames from the input queue. Depending on current state this function either processes of ignores input data.
If current state is CALCULATION_AWAITING_DATA the state is changed to CALCULATION_ACTIVE and the awaiting events queue is flushed by QCoreApplication::processEvents();
If current state is not CALCULATION_AWAITING_DATA all input is ignored
Here is the trick, this function can call newFrameReady recursively, but it will exit with dropped frame. No other function can change currentState, only next state is altered.
Definition at line 66 of file abstractCalculationThread.cpp.
References CALCULATION_ACTIVE, CALCULATION_AWAITING_DATA, CALCULATION_PAUSED, calculationStateChanged(), DOTRACE, Frames::fetchNewFrames(), Frames::getCurrentFrame(), Frames::MAX_INPUTS_NUMBER, mCaptureInterface, mCurrentState, mFrames, mInterframeDelay, mLastFrameTimeStamp, processingFinished(), processNewData(), SYNC_PRINT, frame_data_t::timestamp, and Frames::timestamp().
{
//    cout << "AbstractCalculationThread::newFrameReady called..." << endl;
    //L_INFO_P("new frame notification");
    if (!mCaptureInterface)
    {
        cerr << "Image capture interface was not initialized\n";
        return;
    }
    if (mCurrentState != CALCULATION_AWAITING_DATA) {
        if (mCurrentState == CALCULATION_ACTIVE) {
            DOTRACE(("AbstractCalculationThread::dropped frame\n"));
        }
        return;
    }
    if (frameData.timestamp <= mLastFrameTimeStamp)
    {
        //cout << "Frame was received second time. Previous TS: "<< lastFrameTimeStamp << " Current TS: " << frameData.timestamp << "\n";
        return;
    }
    mCurrentState = CALCULATION_ACTIVE;
    //emit calculationStateChanged(getCalculationState());
    /**
     * Here is the trick, this function can call newFrameReady recursively,
     * but it will exit with dropped frame.
     * No other function can change currentState, only next state is altered.
     *
     **/
    QCoreApplication::processEvents();
    /* On exit from processEvents() we have flushed input queue of the thread */
    /* State can be changed already while in processEvents */
    if (mCurrentState == CALCULATION_ACTIVE)
    {
        uint64_t oldStamp   = mFrames.timestamp();
        mFrames.fetchNewFrames(mCaptureInterface);
        mInterframeDelay    = mFrames.timestamp() - oldStamp;
        mLastFrameTimeStamp = mFrames.timestamp();
/*
        cout << "AbstractCalculationThread::requesting frame..." << endl;
        if (interframeDelay == 0) {
            printf("Strange - two frames with same timestamp\n");
        }
*/
        bool ok = false;
        for (int id = 0; id <  Frames::MAX_INPUTS_NUMBER; id++) {
            ok |= (mFrames.getCurrentFrame((Frames::FrameSourceId)id) != NULL);
        }
        if (ok) /* At least one input is active */
        {
            AbstractOutputData *res = processNewData();
            if (res != NULL)
            {
                /* TODO: Possibly needs redesign. If signal is not processed there will
                be a memory leak. Use Smart pointers here */
                emit processingFinished(res);
            }
        } else {
            SYNC_PRINT(("AbstractCalculationThread::newFrameReady(): No good frames. All frames are NULL\n"));
        }
    }
    if (mCurrentState == CALCULATION_PAUSED) {
        emit calculationStateChanged(mCurrentState);
//        threadPaused.wakeAll();
    } else {
        mCurrentState = CALCULATION_AWAITING_DATA;
    }
}
void AbstractCalculationThread::pauseCalculation () [protected, virtual, slot]
Pauses calculation.
Should only be called as a asynchronous slot function
Definition at line 144 of file abstractCalculationThread.cpp.
References CALCULATION_ACTIVE, CALCULATION_AWAITING_DATA, CALCULATION_PAUSED, calculationStateChanged(), and mCurrentState.
Referenced by BaseCalculationThread::initData(), and RecorderThread::processNewData().
{
    if ((mCurrentState != CALCULATION_ACTIVE) && (mCurrentState != CALCULATION_AWAITING_DATA))
    {
        cout << "There is no calculation in progress - can't pause.\n";
        return;
    }
    if (mCurrentState == CALCULATION_AWAITING_DATA)
    {
        mCurrentState = CALCULATION_PAUSED;
        emit calculationStateChanged(mCurrentState);
//        threadPaused.wakeAll();
    }
    mCurrentState = CALCULATION_PAUSED;
}
void AbstractCalculationThread::processingFinished (AbstractOutputData * output) [signal]
Referenced by newFrameReady().
virtual AbstractOutputData* AbstractCalculationThread::processNewData () [protected, pure virtual]
This is the main calculation routine called when a new frame is received.
Implemented in BaseCalculationThread, and RecorderThread.
Referenced by newFrameReady().
void AbstractCalculationThread::resumeCalculation () [protected, virtual, slot]
Resumes calculation Should only be called as a asynchronous slot function.
Definition at line 161 of file abstractCalculationThread.cpp.
References CALCULATION_AWAITING_DATA, CALCULATION_NOT_STARTED, CALCULATION_PAUSED, calculationStateChanged(), and mCurrentState.
{
    if (mCurrentState == CALCULATION_NOT_STARTED)
    {
        cout << "Use start() for the first time.\n";
        return;
    }
    if (mCurrentState == CALCULATION_PAUSED)
    {
        mCurrentState = CALCULATION_AWAITING_DATA;
        emit calculationStateChanged(mCurrentState);
    }
}
void AbstractCalculationThread::run (void) [virtual]
Definition at line 51 of file abstractCalculationThread.cpp.
References CALCULATION_AWAITING_DATA, CALCULATION_TERMINATED, and mCurrentState.
{
//    stateLock.lock();
    mCurrentState = CALCULATION_AWAITING_DATA;
//    stateLock.unlock();
    cout << "AbstractCalculationThread::run(): starting event loop.\n";
    exec();
    cout << "AbstractCalculationThread::run(): event loop terminated.\n";
//    stateLock.lock();
    mCurrentState = CALCULATION_TERMINATED;
//    stateLock.unlock();
}
virtual void AbstractCalculationThread::setCalculationState (CalculationState state) [inline, virtual]
Definition at line 90 of file abstractCalculationThread.h.
References mCurrentState.
        {
            mCurrentState = state;
        }
void AbstractCalculationThread::setImageCaptureInterface (ImageCaptureInterface * captureInterface) [inline]
Definition at line 107 of file abstractCalculationThread.h.
References mCaptureInterface, and mLastFrameTimeStamp.
Referenced by BaseHostDialog::initCapture(), and BaseHostDialog::stopCalculation().
        {
            mCaptureInterface = captureInterface;
            mLastFrameTimeStamp = 0;
        }
Member Data Documentation
ImageCaptureInterface* AbstractCalculationThread::mCaptureInterface [protected]
The capture interface we fetch the frames from.
Definition at line 117 of file abstractCalculationThread.h.
Referenced by newFrameReady(), and setImageCaptureInterface().
CalculationState AbstractCalculationThread::mCurrentState [protected]
Current calculation state This state can't be changed directly, but can be queried.
Definition at line 135 of file abstractCalculationThread.h.
Referenced by getCalculationState(), newFrameReady(), pauseCalculation(), resumeCalculation(), run(), and setCalculationState().
FiltersCollection AbstractCalculationThread::mFiltersCollection
Definition at line 152 of file abstractCalculationThread.h.
Referenced by BaseCalculationThread::BaseCalculationThread(), BaseCalculationThread::graphChanged(), and BaseHostDialog::initGraphPresentation().
Frames AbstractCalculationThread::mFrames [protected]
Holds the last two sets of frames acquired from the capture device(s)
Definition at line 122 of file abstractCalculationThread.h.
Referenced by BaseCalculationThread::executeFilterGraph(), getFramesHolder(), BaseCalculationThread::initData(), newFrameReady(), RecorderThread::processNewData(), BaseCalculationThread::recalculateCache(), and BaseCalculationThread::transformInputFrames().
uint64_t AbstractCalculationThread::mInterframeDelay [protected]
Delay between this and previous frame.
Definition at line 127 of file abstractCalculationThread.h.
Referenced by newFrameReady().
uint64_t AbstractCalculationThread::mLastFrameTimeStamp [protected]
Definition at line 129 of file abstractCalculationThread.h.
Referenced by newFrameReady(), and setImageCaptureInterface().
const char * AbstractCalculationThread::stateNames [static]
Initial value:
{
    "Not started",
    "Awaiting data",
    "Active",
    "Paused",
    "Terminated"
}
Definition at line 50 of file abstractCalculationThread.h.
Referenced by BaseHostDialog::calculationStateChanged(), and BaseHostDialog::play().
The documentation for this class was generated from the following files:
applications/base/abstractCalculationThread.h
applications/base/abstractCalculationThread.cpp