DeepView: Draw3dViMouseParameters Class Reference
Draw3dViMouseParameters Class Reference
draw 3d ViMouse Parameters draw 3d ViMouse Parameters
#include <draw3dViMouseParameters.h>
Public Types
enum FieldId {
REDDIST_ID, BLUEDIST_ID, FLOWZOOM_ID, POINT_COLOR_TYPE_ID,
FLOW_COLOR_TYPE_ID, DRAW_3D_VIMOUSE_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
double redDist () const
double blueDist () const
double flowZoom () const
ViMouse3dStereoStyle::ViMouse3dStereoStyle pointColorType () const
ViMouse3dFlowStyle::ViMouse3dFlowStyle flowColorType () const
void setRedDist (double redDist)
void setBlueDist (double blueDist)
void setFlowZoom (double flowZoom)
void setPointColorType (ViMouse3dStereoStyle::ViMouse3dStereoStyle pointColorType)
void setFlowColorType (ViMouse3dFlowStyle::ViMouse3dFlowStyle flowColorType)
template<class VisitorType >
void accept (VisitorType &visitor)
Draw3dViMouseParameters ()
Draw3dViMouseParameters (double redDist, double blueDist, double flowZoom, ViMouse3dStereoStyle::ViMouse3dStereoStyle pointColorType, ViMouse3dFlowStyle::ViMouse3dFlowStyle flowColorType)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
double mRedDist
Section with variables.
double mBlueDist
blueDist blueDist
double mFlowZoom
flowZoom flowZoom
int mPointColorType
Point Color Type Point Color Type.
int mFlowColorType
Flow Color Type Flow Color Type.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, Draw3dViMouseParameters &toSave)
Detailed Description
draw 3d ViMouse Parameters draw 3d ViMouse Parameters
Definition at line 40 of file draw3dViMouseParameters.h.
Member Enumeration Documentation
enum Draw3dViMouseParameters::FieldId
Enumerator:
REDDIST_ID
BLUEDIST_ID
FLOWZOOM_ID
POINT_COLOR_TYPE_ID
FLOW_COLOR_TYPE_ID
DRAW_3D_VIMOUSE_PARAMETERS_FIELD_ID_NUM
Definition at line 43 of file draw3dViMouseParameters.h.
                 {
        REDDIST_ID,
        BLUEDIST_ID,
        FLOWZOOM_ID,
        POINT_COLOR_TYPE_ID,
        FLOW_COLOR_TYPE_ID,
        DRAW_3D_VIMOUSE_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
Draw3dViMouseParameters::Draw3dViMouseParameters () [inline]
Definition at line 155 of file draw3dViMouseParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
Draw3dViMouseParameters::Draw3dViMouseParameters (double redDist, double blueDist, double flowZoom, ViMouse3dStereoStyle::ViMouse3dStereoStyle pointColorType, ViMouse3dFlowStyle::ViMouse3dFlowStyle flowColorType) [inline]
Definition at line 161 of file draw3dViMouseParameters.h.
    {
        mRedDist = redDist;
        mBlueDist = blueDist;
        mFlowZoom = flowZoom;
        mPointColorType = pointColorType;
        mFlowColorType = flowColorType;
    }
Member Function Documentation
template<class VisitorType > void Draw3dViMouseParameters::accept (VisitorType & visitor) [inline]
Definition at line 146 of file draw3dViMouseParameters.h.
    {
        visitor.visit(mRedDist,                   static_cast<const DoubleField *>  (fields()[REDDIST_ID]));
        visitor.visit(mBlueDist,                  static_cast<const DoubleField *>  (fields()[BLUEDIST_ID]));
        visitor.visit(mFlowZoom,                  static_cast<const DoubleField *>  (fields()[FLOWZOOM_ID]));
        visitor.visit((int &)mPointColorType,     static_cast<const EnumField *>    (fields()[POINT_COLOR_TYPE_ID]));
        visitor.visit((int &)mFlowColorType,      static_cast<const EnumField *>    (fields()[FLOW_COLOR_TYPE_ID]));
    }
double Draw3dViMouseParameters::blueDist () const [inline]
Definition at line 97 of file draw3dViMouseParameters.h.
Referenced by Scene3DMouse::drawMyself(), and Draw3dViMouseParametersControlWidget::setParameters().
    {
        return mBlueDist;
    }
static const char* corecvs::BaseReflection< Draw3dViMouseParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< Draw3dViMouseParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< Draw3dViMouseParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
ViMouse3dFlowStyle::ViMouse3dFlowStyle Draw3dViMouseParameters::flowColorType () const [inline]
Definition at line 112 of file draw3dViMouseParameters.h.
Referenced by Scene3DMouse::drawMyself(), and Draw3dViMouseParametersControlWidget::setParameters().
    {
        return static_cast<ViMouse3dFlowStyle::ViMouse3dFlowStyle>(mFlowColorType);
    }
double Draw3dViMouseParameters::flowZoom () const [inline]
Definition at line 102 of file draw3dViMouseParameters.h.
Referenced by Scene3DMouse::drawMyself(), and Draw3dViMouseParametersControlWidget::setParameters().
    {
        return mFlowZoom;
    }
const void* Draw3dViMouseParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 88 of file draw3dViMouseParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< Draw3dViMouseParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< Draw3dViMouseParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< Draw3dViMouseParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
ViMouse3dStereoStyle::ViMouse3dStereoStyle Draw3dViMouseParameters::pointColorType () const [inline]
Definition at line 107 of file draw3dViMouseParameters.h.
Referenced by Scene3DMouse::drawMyself(), and Draw3dViMouseParametersControlWidget::setParameters().
    {
        return static_cast<ViMouse3dStereoStyle::ViMouse3dStereoStyle>(mPointColorType);
    }
void Draw3dViMouseParameters::print () [inline]
Definition at line 183 of file draw3dViMouseParameters.h.
    {
        cout << *this;
    }
double Draw3dViMouseParameters::redDist () const [inline]
Definition at line 92 of file draw3dViMouseParameters.h.
Referenced by Scene3DMouse::drawMyself(), and Draw3dViMouseParametersControlWidget::setParameters().
    {
        return mRedDist;
    }
void Draw3dViMouseParameters::setBlueDist (double blueDist) [inline]
Definition at line 123 of file draw3dViMouseParameters.h.
    {
        mBlueDist = blueDist;
    }
void Draw3dViMouseParameters::setFlowColorType (ViMouse3dFlowStyle::ViMouse3dFlowStyle flowColorType) [inline]
Definition at line 138 of file draw3dViMouseParameters.h.
    {
        mFlowColorType = flowColorType;
    }
void Draw3dViMouseParameters::setFlowZoom (double flowZoom) [inline]
Definition at line 128 of file draw3dViMouseParameters.h.
    {
        mFlowZoom = flowZoom;
    }
void Draw3dViMouseParameters::setPointColorType (ViMouse3dStereoStyle::ViMouse3dStereoStyle pointColorType) [inline]
Definition at line 133 of file draw3dViMouseParameters.h.
    {
        mPointColorType = pointColorType;
    }
void Draw3dViMouseParameters::setRedDist (double redDist) [inline]
Definition at line 118 of file draw3dViMouseParameters.h.
    {
        mRedDist = redDist;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int Draw3dViMouseParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file draw3dViMouseParameters.cpp.
References BLUEDIST_ID, corecvs::BaseReflection< Draw3dViMouseParameters >::fields(), FLOW_COLOR_TYPE_ID, FLOWZOOM_ID, mBlueDist, mFlowColorType, mFlowZoom, mPointColorType, mRedDist, corecvs::BaseReflection< Draw3dViMouseParameters >::naming(), POINT_COLOR_TYPE_ID, and REDDIST_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "draw 3d ViMouse Parameters",
        "draw 3d ViMouse Parameters",
        ""
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dViMouseParameters::REDDIST_ID,
          offsetof(Draw3dViMouseParameters, mRedDist),
          0,
          "redDist",
          "redDist",
          "redDist"
        )
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dViMouseParameters::BLUEDIST_ID,
          offsetof(Draw3dViMouseParameters, mBlueDist),
          1000,
          "blueDist",
          "blueDist",
          "blueDist"
        )
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dViMouseParameters::FLOWZOOM_ID,
          offsetof(Draw3dViMouseParameters, mFlowZoom),
          1,
          "flowZoom",
          "flowZoom",
          "flowZoom"
        )
    );
    fields().push_back(
        new EnumField
        (
          Draw3dViMouseParameters::POINT_COLOR_TYPE_ID,
          offsetof(Draw3dViMouseParameters, mPointColorType),
          0,
          "Point Color Type",
          "Point Color Type",
          "Point Color Type",
           NULL
        )
    );
    fields().push_back(
        new EnumField
        (
          Draw3dViMouseParameters::FLOW_COLOR_TYPE_ID,
          offsetof(Draw3dViMouseParameters, mFlowColorType),
          0,
          "Flow Color Type",
          "Flow Color Type",
          "Flow Color Type",
           NULL
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, Draw3dViMouseParameters & toSave) [friend]
Definition at line 176 of file draw3dViMouseParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< Draw3dViMouseParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
double Draw3dViMouseParameters::mBlueDist
blueDist blueDist
Definition at line 64 of file draw3dViMouseParameters.h.
Referenced by staticInit().
int Draw3dViMouseParameters::mFlowColorType
Flow Color Type Flow Color Type.
Definition at line 82 of file draw3dViMouseParameters.h.
Referenced by staticInit().
double Draw3dViMouseParameters::mFlowZoom
flowZoom flowZoom
Definition at line 70 of file draw3dViMouseParameters.h.
Referenced by staticInit().
int Draw3dViMouseParameters::mPointColorType
Point Color Type Point Color Type.
Definition at line 76 of file draw3dViMouseParameters.h.
Referenced by staticInit().
double Draw3dViMouseParameters::mRedDist
Section with variables.
redDist redDist
Definition at line 58 of file draw3dViMouseParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< Draw3dViMouseParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
utils/3d/generated/draw3dViMouseParameters.h
utils/3d/generated/draw3dViMouseParameters.cpp