DeepView: OpenCVBMParameters Class Reference
OpenCVBMParameters Class Reference
OpenCV BM Parameters Class OpenCV BM Parameters Class.
#include <openCVBMParameters.h>
Public Types
enum FieldId {
BLOCK_SIZE_ID, DISPARITY_SEARCH_ID, PREFILTERCAP_ID, MINDISPARITY_ID,
TEXTURETHRESHOLD_ID, UNIQUENESSRATIO_ID, SPECKLEWINDOWSIZE_ID, SPECKLERANGE_ID,
DISP12MAXDIFF_ID, OPENCV_BM_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
int blockSize () const
int disparitySearch () const
int preFilterCap () const
int minDisparity () const
int textureThreshold () const
int uniquenessRatio () const
int speckleWindowSize () const
int speckleRange () const
int disp12MaxDiff () const
void setBlockSize (int blockSize)
void setDisparitySearch (int disparitySearch)
void setPreFilterCap (int preFilterCap)
void setMinDisparity (int minDisparity)
void setTextureThreshold (int textureThreshold)
void setUniquenessRatio (int uniquenessRatio)
void setSpeckleWindowSize (int speckleWindowSize)
void setSpeckleRange (int speckleRange)
void setDisp12MaxDiff (int disp12MaxDiff)
template<class VisitorType >
void accept (VisitorType &visitor)
OpenCVBMParameters ()
OpenCVBMParameters (int blockSize, int disparitySearch, int preFilterCap, int minDisparity, int textureThreshold, int uniquenessRatio, int speckleWindowSize, int speckleRange, int disp12MaxDiff)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mBlockSize
Section with variables.
int mDisparitySearch
Disparity search Disparity search.
int mPreFilterCap
preFilterCap preFilterCap
int mMinDisparity
minDisparity minDisparity
int mTextureThreshold
textureThreshold textureThreshold
int mUniquenessRatio
uniquenessRatio uniquenessRatio
int mSpeckleWindowSize
speckleWindowSize speckleWindowSize
int mSpeckleRange
speckleRange speckleRange
int mDisp12MaxDiff
disp12MaxDiff disp12MaxDiff
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, OpenCVBMParameters &toSave)
Detailed Description
OpenCV BM Parameters Class OpenCV BM Parameters Class.
Definition at line 38 of file openCVBMParameters.h.
Member Enumeration Documentation
enum OpenCVBMParameters::FieldId
Enumerator:
BLOCK_SIZE_ID
DISPARITY_SEARCH_ID
PREFILTERCAP_ID
MINDISPARITY_ID
TEXTURETHRESHOLD_ID
UNIQUENESSRATIO_ID
SPECKLEWINDOWSIZE_ID
SPECKLERANGE_ID
DISP12MAXDIFF_ID
OPENCV_BM_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file openCVBMParameters.h.
                 {
        BLOCK_SIZE_ID,
        DISPARITY_SEARCH_ID,
        PREFILTERCAP_ID,
        MINDISPARITY_ID,
        TEXTURETHRESHOLD_ID,
        UNIQUENESSRATIO_ID,
        SPECKLEWINDOWSIZE_ID,
        SPECKLERANGE_ID,
        DISP12MAXDIFF_ID,
        OPENCV_BM_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
OpenCVBMParameters::OpenCVBMParameters () [inline]
Definition at line 225 of file openCVBMParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
OpenCVBMParameters::OpenCVBMParameters (int blockSize, int disparitySearch, int preFilterCap, int minDisparity, int textureThreshold, int uniquenessRatio, int speckleWindowSize, int speckleRange, int disp12MaxDiff) [inline]
Definition at line 231 of file openCVBMParameters.h.
    {
        mBlockSize = blockSize;
        mDisparitySearch = disparitySearch;
        mPreFilterCap = preFilterCap;
        mMinDisparity = minDisparity;
        mTextureThreshold = textureThreshold;
        mUniquenessRatio = uniquenessRatio;
        mSpeckleWindowSize = speckleWindowSize;
        mSpeckleRange = speckleRange;
        mDisp12MaxDiff = disp12MaxDiff;
    }
Member Function Documentation
template<class VisitorType > void OpenCVBMParameters::accept (VisitorType & visitor) [inline]
Definition at line 212 of file openCVBMParameters.h.
    {
        visitor.visit(mBlockSize,                 static_cast<const IntField *>     (fields()[BLOCK_SIZE_ID]));
        visitor.visit(mDisparitySearch,           static_cast<const IntField *>     (fields()[DISPARITY_SEARCH_ID]));
        visitor.visit(mPreFilterCap,              static_cast<const IntField *>     (fields()[PREFILTERCAP_ID]));
        visitor.visit(mMinDisparity,              static_cast<const IntField *>     (fields()[MINDISPARITY_ID]));
        visitor.visit(mTextureThreshold,          static_cast<const IntField *>     (fields()[TEXTURETHRESHOLD_ID]));
        visitor.visit(mUniquenessRatio,           static_cast<const IntField *>     (fields()[UNIQUENESSRATIO_ID]));
        visitor.visit(mSpeckleWindowSize,         static_cast<const IntField *>     (fields()[SPECKLEWINDOWSIZE_ID]));
        visitor.visit(mSpeckleRange,              static_cast<const IntField *>     (fields()[SPECKLERANGE_ID]));
        visitor.visit(mDisp12MaxDiff,             static_cast<const IntField *>     (fields()[DISP12MAXDIFF_ID]));
    }
int OpenCVBMParameters::blockSize () const [inline]
Definition at line 118 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mBlockSize;
    }
static const char* corecvs::BaseReflection< OpenCVBMParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
int OpenCVBMParameters::disp12MaxDiff () const [inline]
Definition at line 158 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mDisp12MaxDiff;
    }
int OpenCVBMParameters::disparitySearch () const [inline]
Definition at line 123 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mDisparitySearch;
    }
static int corecvs::BaseReflection< OpenCVBMParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< OpenCVBMParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* OpenCVBMParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 114 of file openCVBMParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< OpenCVBMParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
int OpenCVBMParameters::minDisparity () const [inline]
Definition at line 133 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mMinDisparity;
    }
static const char* corecvs::BaseReflection< OpenCVBMParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< OpenCVBMParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
int OpenCVBMParameters::preFilterCap () const [inline]
Definition at line 128 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mPreFilterCap;
    }
void OpenCVBMParameters::print () [inline]
Definition at line 261 of file openCVBMParameters.h.
    {
        cout << *this;
    }
void OpenCVBMParameters::setBlockSize (int blockSize) [inline]
Definition at line 164 of file openCVBMParameters.h.
    {
        mBlockSize = blockSize;
    }
void OpenCVBMParameters::setDisp12MaxDiff (int disp12MaxDiff) [inline]
Definition at line 204 of file openCVBMParameters.h.
    {
        mDisp12MaxDiff = disp12MaxDiff;
    }
void OpenCVBMParameters::setDisparitySearch (int disparitySearch) [inline]
Definition at line 169 of file openCVBMParameters.h.
    {
        mDisparitySearch = disparitySearch;
    }
void OpenCVBMParameters::setMinDisparity (int minDisparity) [inline]
Definition at line 179 of file openCVBMParameters.h.
    {
        mMinDisparity = minDisparity;
    }
void OpenCVBMParameters::setPreFilterCap (int preFilterCap) [inline]
Definition at line 174 of file openCVBMParameters.h.
    {
        mPreFilterCap = preFilterCap;
    }
void OpenCVBMParameters::setSpeckleRange (int speckleRange) [inline]
Definition at line 199 of file openCVBMParameters.h.
    {
        mSpeckleRange = speckleRange;
    }
void OpenCVBMParameters::setSpeckleWindowSize (int speckleWindowSize) [inline]
Definition at line 194 of file openCVBMParameters.h.
    {
        mSpeckleWindowSize = speckleWindowSize;
    }
void OpenCVBMParameters::setTextureThreshold (int textureThreshold) [inline]
Definition at line 184 of file openCVBMParameters.h.
    {
        mTextureThreshold = textureThreshold;
    }
void OpenCVBMParameters::setUniquenessRatio (int uniquenessRatio) [inline]
Definition at line 189 of file openCVBMParameters.h.
    {
        mUniquenessRatio = uniquenessRatio;
    }
int OpenCVBMParameters::speckleRange () const [inline]
Definition at line 153 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mSpeckleRange;
    }
int OpenCVBMParameters::speckleWindowSize () const [inline]
Definition at line 148 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mSpeckleWindowSize;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int OpenCVBMParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file openCVBMParameters.cpp.
References BLOCK_SIZE_ID, DISP12MAXDIFF_ID, DISPARITY_SEARCH_ID, corecvs::BaseReflection< OpenCVBMParameters >::fields(), mBlockSize, mDisp12MaxDiff, mDisparitySearch, MINDISPARITY_ID, mMinDisparity, mPreFilterCap, mSpeckleRange, mSpeckleWindowSize, mTextureThreshold, mUniquenessRatio, corecvs::BaseReflection< OpenCVBMParameters >::naming(), PREFILTERCAP_ID, SPECKLERANGE_ID, SPECKLEWINDOWSIZE_ID, TEXTURETHRESHOLD_ID, and UNIQUENESSRATIO_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "OpenCV BM Parameters",
        "OpenCV BM Parameters Class",
        ""
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::BLOCK_SIZE_ID,
          offsetof(OpenCVBMParameters, mBlockSize),
          21,
          "Block Size",
          "Block Size",
          "Block Size"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::DISPARITY_SEARCH_ID,
          offsetof(OpenCVBMParameters, mDisparitySearch),
          0,
          "Disparity search",
          "Disparity search",
          "Disparity search"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::PREFILTERCAP_ID,
          offsetof(OpenCVBMParameters, mPreFilterCap),
          31,
          "preFilterCap",
          "preFilterCap",
          "preFilterCap"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::MINDISPARITY_ID,
          offsetof(OpenCVBMParameters, mMinDisparity),
          1,
          "minDisparity",
          "minDisparity",
          "minDisparity"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::TEXTURETHRESHOLD_ID,
          offsetof(OpenCVBMParameters, mTextureThreshold),
          10,
          "textureThreshold",
          "textureThreshold",
          "textureThreshold"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::UNIQUENESSRATIO_ID,
          offsetof(OpenCVBMParameters, mUniquenessRatio),
          15,
          "uniquenessRatio",
          "uniquenessRatio",
          "uniquenessRatio"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::SPECKLEWINDOWSIZE_ID,
          offsetof(OpenCVBMParameters, mSpeckleWindowSize),
          100,
          "speckleWindowSize",
          "speckleWindowSize",
          "speckleWindowSize"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::SPECKLERANGE_ID,
          offsetof(OpenCVBMParameters, mSpeckleRange),
          32,
          "speckleRange",
          "speckleRange",
          "speckleRange"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVBMParameters::DISP12MAXDIFF_ID,
          offsetof(OpenCVBMParameters, mDisp12MaxDiff),
          1,
          "disp12MaxDiff",
          "disp12MaxDiff",
          "disp12MaxDiff"
        )
    );
   return 0;
}
int OpenCVBMParameters::textureThreshold () const [inline]
Definition at line 138 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mTextureThreshold;
    }
int OpenCVBMParameters::uniquenessRatio () const [inline]
Definition at line 143 of file openCVBMParameters.h.
Referenced by OpenCVBMParametersControlWidget::setParameters().
    {
        return mUniquenessRatio;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, OpenCVBMParameters & toSave) [friend]
Definition at line 254 of file openCVBMParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< OpenCVBMParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int OpenCVBMParameters::mBlockSize
Section with variables.
Block Size Block Size
Definition at line 60 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mDisp12MaxDiff
disp12MaxDiff disp12MaxDiff
Definition at line 108 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mDisparitySearch
Disparity search Disparity search.
Definition at line 66 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mMinDisparity
minDisparity minDisparity
Definition at line 78 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mPreFilterCap
preFilterCap preFilterCap
Definition at line 72 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mSpeckleRange
speckleRange speckleRange
Definition at line 102 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mSpeckleWindowSize
speckleWindowSize speckleWindowSize
Definition at line 96 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mTextureThreshold
textureThreshold textureThreshold
Definition at line 84 of file openCVBMParameters.h.
Referenced by staticInit().
int OpenCVBMParameters::mUniquenessRatio
uniquenessRatio uniquenessRatio
Definition at line 90 of file openCVBMParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< OpenCVBMParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
utils/corestructs/libWidgets/openCVBMParameters.h
utils/corestructs/libWidgets/openCVBMParameters.cpp