DeepView: ScaleFilter Class Reference
ScaleFilter Class Reference
#include <scalefilter.h>
Public Slots
void updateXScale (double value)
void updateYScale (double value)
void updateHeight (int val)
void updateWidth (int val)
void updateXShift (int val)
void updateYShift (int val)
Signals
void parametersChanged (void)
Public Member Functions
virtual QString getInstanceName ()
virtual G12Buffer * filter (G12Buffer *input)
ScaleFilter (QWidget *parent=0)
~ScaleFilter ()
Static Public Member Functions
static QString getName ()
Private Attributes
Ui_ScaleFilterClass ui
Static Private Attributes
static QString name = QString("Scale")
Detailed Description
Definition at line 10 of file scalefilter.h.
Constructor & Destructor Documentation
ScaleFilter::ScaleFilter (QWidget * parent = 0)
Definition at line 10 of file scalefilter.cpp.
References ui, updateHeight(), updateWidth(), updateXScale(), updateXShift(), updateYScale(), and updateYShift().
    : BaseFilter(parent)
{
    ui.setupUi(this);
    connect(ui.heightBox, SIGNAL(valueChanged(int)), this, SLOT(updateHeight(int)));
    connect(ui.widthBox,  SIGNAL(valueChanged(int)), this, SLOT(updateWidth(int)));
    connect(ui.scaleXBox, SIGNAL(valueChanged(double)), this, SLOT(updateXScale(double)));
    connect(ui.scaleYBox, SIGNAL(valueChanged(double)), this, SLOT(updateYScale(double)));
    connect(ui.shiftXBox, SIGNAL(valueChanged(int)), this, SLOT(updateXShift(int)));
    connect(ui.shiftXBox, SIGNAL(valueChanged(int)), this, SLOT(updateYShift(int)));
}
ScaleFilter::~ScaleFilter ()
Definition at line 75 of file scalefilter.cpp.
{
}
Member Function Documentation
G12Buffer * ScaleFilter::filter (G12Buffer * input) [virtual]
Reimplemented from BaseFilter.
Definition at line 58 of file scalefilter.cpp.
References corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformationBl(), corecvs::AbstractBufferParams::h, ui, and corecvs::AbstractBufferParams::w.
{
    Matrix33 matrix;
    matrix =
        Matrix33::ShiftProj( ui.shiftXBox->value(), ui.shiftYBox->value()) *
        Matrix33::Scale2(1.0 / ui.scaleXBox->value(), 1.0 / ui.scaleYBox->value());
    ProjectiveTransform transform(matrix);
    int h = ui.heightBox->value();
    int w = ui.widthBox->value();
    if (h == -1) h = input->h * ui.scaleYBox->value();
    if (w == -1) w = input->w * ui.scaleXBox->value();
    G12Buffer *changed = input->doReverseDeformationBl<G12Buffer, ProjectiveTransform> (&transform, h, w);
    return changed;
}
virtual QString ScaleFilter::getInstanceName () [inline, virtual]
Reimplemented from BaseFilter.
Definition at line 32 of file scalefilter.h.
    {
        return name;
    };
static QString ScaleFilter::getName () [inline, static]
Reimplemented from BaseFilter.
Definition at line 27 of file scalefilter.h.
Referenced by FilterFabric::createFilterInstance(), and FilterFabric::getFilterNames().
     {
         return name;
     };
void BaseFilter::parametersChanged (void) [signal, inherited]
Referenced by BitSelector::maskChanged(), BitSelector::shiftChanged(), GainOffset::updateGainSlider(), GainOffset::updateGainText(), updateHeight(), GainOffset::updateOffsetSlider(), GainOffset::updateOffsetText(), updateWidth(), updateXScale(), updateXShift(), updateYScale(), and updateYShift().
void ScaleFilter::updateHeight (int val) [slot]
Definition at line 36 of file scalefilter.cpp.
References BaseFilter::parametersChanged().
Referenced by ScaleFilter().
{
    emit parametersChanged();
}
void ScaleFilter::updateWidth (int val) [slot]
Definition at line 41 of file scalefilter.cpp.
References BaseFilter::parametersChanged().
Referenced by ScaleFilter().
{
    emit parametersChanged();
}
void ScaleFilter::updateXScale (double value) [slot]
Definition at line 26 of file scalefilter.cpp.
References BaseFilter::parametersChanged().
Referenced by ScaleFilter().
{
    emit parametersChanged();
}
void ScaleFilter::updateXShift (int val) [slot]
Definition at line 46 of file scalefilter.cpp.
References BaseFilter::parametersChanged().
Referenced by ScaleFilter().
{
    emit parametersChanged();
}
void ScaleFilter::updateYScale (double value) [slot]
Definition at line 31 of file scalefilter.cpp.
References BaseFilter::parametersChanged().
Referenced by ScaleFilter().
{
    emit parametersChanged();
}
void ScaleFilter::updateYShift (int val) [slot]
Definition at line 51 of file scalefilter.cpp.
References BaseFilter::parametersChanged().
Referenced by ScaleFilter().
{
    emit parametersChanged();
}
Member Data Documentation
QString ScaleFilter::name = QString("Scale") [static, private]
Definition at line 14 of file scalefilter.h.
Ui_ScaleFilterClass ScaleFilter::ui [private]
Reimplemented from BaseFilter.
Definition at line 43 of file scalefilter.h.
Referenced by filter(), and ScaleFilter().
The documentation for this class was generated from the following files:
utils/filters/legacy/scalefilter.h
utils/filters/legacy/scalefilter.cpp