DeepView: HeadSearchParameters Class Reference
HeadSearchParameters Class Reference
Head Search Parameters Head Search Parameters.
#include <headSearchParameters.h>
Public Types
enum FieldId {
THRESHOLD_DISTANCE_ID, CLUSTER_DEPTH_ID, CLUSTER_MIN_SIZE_ID, HEAD_AREA_RADIUS_ID,
HEAD_NUMBER_ID, HEAD_SEARCH_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
double thresholdDistance () const
double clusterDepth () const
int clusterMinSize () const
double headAreaRadius () const
int headNumber () const
void setThresholdDistance (double thresholdDistance)
void setClusterDepth (double clusterDepth)
void setClusterMinSize (int clusterMinSize)
void setHeadAreaRadius (double headAreaRadius)
void setHeadNumber (int headNumber)
template<class VisitorType >
void accept (VisitorType &visitor)
HeadSearchParameters ()
HeadSearchParameters (double thresholdDistance, double clusterDepth, int clusterMinSize, double headAreaRadius, int headNumber)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
double mThresholdDistance
Section with variables.
double mClusterDepth
Cluster depth Cluster depth in mm.
int mClusterMinSize
Cluster min size Cluster min size.
double mHeadAreaRadius
Head area radius Head area in mm.
int mHeadNumber
Head Number Expected number of heads.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, HeadSearchParameters &toSave)
Detailed Description
Head Search Parameters Head Search Parameters.
Definition at line 38 of file headSearchParameters.h.
Member Enumeration Documentation
enum HeadSearchParameters::FieldId
Enumerator:
THRESHOLD_DISTANCE_ID
CLUSTER_DEPTH_ID
CLUSTER_MIN_SIZE_ID
HEAD_AREA_RADIUS_ID
HEAD_NUMBER_ID
HEAD_SEARCH_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file headSearchParameters.h.
                 {
        THRESHOLD_DISTANCE_ID,
        CLUSTER_DEPTH_ID,
        CLUSTER_MIN_SIZE_ID,
        HEAD_AREA_RADIUS_ID,
        HEAD_NUMBER_ID,
        HEAD_SEARCH_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
HeadSearchParameters::HeadSearchParameters () [inline]
Definition at line 153 of file headSearchParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
HeadSearchParameters::HeadSearchParameters (double thresholdDistance, double clusterDepth, int clusterMinSize, double headAreaRadius, int headNumber) [inline]
Definition at line 159 of file headSearchParameters.h.
    {
        mThresholdDistance = thresholdDistance;
        mClusterDepth = clusterDepth;
        mClusterMinSize = clusterMinSize;
        mHeadAreaRadius = headAreaRadius;
        mHeadNumber = headNumber;
    }
Member Function Documentation
template<class VisitorType > void HeadSearchParameters::accept (VisitorType & visitor) [inline]
Definition at line 144 of file headSearchParameters.h.
    {
        visitor.visit(mThresholdDistance,         static_cast<const DoubleField *>  (fields()[THRESHOLD_DISTANCE_ID]));
        visitor.visit(mClusterDepth,              static_cast<const DoubleField *>  (fields()[CLUSTER_DEPTH_ID]));
        visitor.visit(mClusterMinSize,            static_cast<const IntField *>     (fields()[CLUSTER_MIN_SIZE_ID]));
        visitor.visit(mHeadAreaRadius,            static_cast<const DoubleField *>  (fields()[HEAD_AREA_RADIUS_ID]));
        visitor.visit(mHeadNumber,                static_cast<const IntField *>     (fields()[HEAD_NUMBER_ID]));
    }
double HeadSearchParameters::clusterDepth () const [inline]
Definition at line 95 of file headSearchParameters.h.
Referenced by HeadSearchParametersControlWidget::setParameters().
    {
        return mClusterDepth;
    }
int HeadSearchParameters::clusterMinSize () const [inline]
Definition at line 100 of file headSearchParameters.h.
Referenced by HeadSearchParametersControlWidget::setParameters().
    {
        return mClusterMinSize;
    }
static const char* corecvs::BaseReflection< HeadSearchParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< HeadSearchParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< HeadSearchParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* HeadSearchParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 86 of file headSearchParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< HeadSearchParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
double HeadSearchParameters::headAreaRadius () const [inline]
Definition at line 105 of file headSearchParameters.h.
Referenced by HeadSearchParametersControlWidget::setParameters().
    {
        return mHeadAreaRadius;
    }
int HeadSearchParameters::headNumber () const [inline]
Definition at line 110 of file headSearchParameters.h.
Referenced by HeadSearchParametersControlWidget::setParameters().
    {
        return mHeadNumber;
    }
static const char* corecvs::BaseReflection< HeadSearchParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< HeadSearchParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void HeadSearchParameters::print () [inline]
Definition at line 181 of file headSearchParameters.h.
    {
        cout << *this;
    }
void HeadSearchParameters::setClusterDepth (double clusterDepth) [inline]
Definition at line 121 of file headSearchParameters.h.
    {
        mClusterDepth = clusterDepth;
    }
void HeadSearchParameters::setClusterMinSize (int clusterMinSize) [inline]
Definition at line 126 of file headSearchParameters.h.
    {
        mClusterMinSize = clusterMinSize;
    }
void HeadSearchParameters::setHeadAreaRadius (double headAreaRadius) [inline]
Definition at line 131 of file headSearchParameters.h.
    {
        mHeadAreaRadius = headAreaRadius;
    }
void HeadSearchParameters::setHeadNumber (int headNumber) [inline]
Definition at line 136 of file headSearchParameters.h.
    {
        mHeadNumber = headNumber;
    }
void HeadSearchParameters::setThresholdDistance (double thresholdDistance) [inline]
Definition at line 116 of file headSearchParameters.h.
    {
        mThresholdDistance = thresholdDistance;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int HeadSearchParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file headSearchParameters.cpp.
References CLUSTER_DEPTH_ID, CLUSTER_MIN_SIZE_ID, corecvs::BaseReflection< HeadSearchParameters >::fields(), HEAD_AREA_RADIUS_ID, HEAD_NUMBER_ID, mClusterDepth, mClusterMinSize, mHeadAreaRadius, mHeadNumber, mThresholdDistance, corecvs::BaseReflection< HeadSearchParameters >::naming(), and THRESHOLD_DISTANCE_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Head Search Parameters",
        "Head Search Parameters",
        ""
    );
    fields().push_back(
        new DoubleField
        (
          HeadSearchParameters::THRESHOLD_DISTANCE_ID,
          offsetof(HeadSearchParameters, mThresholdDistance),
          100,
          "Threshold Distance",
          "Threshold Distance",
          "Threshold Distance in mm"
        )
    );
    fields().push_back(
        new DoubleField
        (
          HeadSearchParameters::CLUSTER_DEPTH_ID,
          offsetof(HeadSearchParameters, mClusterDepth),
          100,
          "Cluster depth",
          "Cluster depth",
          "Cluster depth in mm"
        )
    );
    fields().push_back(
        new IntField
        (
          HeadSearchParameters::CLUSTER_MIN_SIZE_ID,
          offsetof(HeadSearchParameters, mClusterMinSize),
          100,
          "Cluster min size",
          "Cluster min size",
          "Cluster min size"
        )
    );
    fields().push_back(
        new DoubleField
        (
          HeadSearchParameters::HEAD_AREA_RADIUS_ID,
          offsetof(HeadSearchParameters, mHeadAreaRadius),
          100,
          "Head area radius",
          "Head area radius",
          "Head area in mm"
        )
    );
    fields().push_back(
        new IntField
        (
          HeadSearchParameters::HEAD_NUMBER_ID,
          offsetof(HeadSearchParameters, mHeadNumber),
          1,
          "Head Number",
          "Head Number",
          "Expected number of heads"
        )
    );
   return 0;
}
double HeadSearchParameters::thresholdDistance () const [inline]
Definition at line 90 of file headSearchParameters.h.
Referenced by HeadSearchParametersControlWidget::setParameters().
    {
        return mThresholdDistance;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, HeadSearchParameters & toSave) [friend]
Definition at line 174 of file headSearchParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< HeadSearchParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
double HeadSearchParameters::mClusterDepth
Cluster depth Cluster depth in mm.
Definition at line 62 of file headSearchParameters.h.
Referenced by staticInit().
int HeadSearchParameters::mClusterMinSize
Cluster min size Cluster min size.
Definition at line 68 of file headSearchParameters.h.
Referenced by staticInit().
double HeadSearchParameters::mHeadAreaRadius
Head area radius Head area in mm.
Definition at line 74 of file headSearchParameters.h.
Referenced by staticInit().
int HeadSearchParameters::mHeadNumber
Head Number Expected number of heads.
Definition at line 80 of file headSearchParameters.h.
Referenced by staticInit().
double HeadSearchParameters::mThresholdDistance
Section with variables.
Threshold Distance Threshold Distance in mm
Definition at line 56 of file headSearchParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< HeadSearchParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/headSearchParameters.h
core/xml/generated/headSearchParameters.cpp