DeepView: corecvs::Statistics Class Reference
corecvs::Statistics Class Reference
#include <calculationStats.h>
Public Member Functions
void startInterval ()
void endInterval (const string &str)
void resetInterval (const string &str)
void setTime (const string &str, uint64_t delay)
void setValue (const string &str, uint64_t value)
Public Attributes
map< string, SingleStat > values
string prefix
PreciseTimer helperTimer
Detailed Description
Definition at line 95 of file calculationStats.h.
Member Function Documentation
void corecvs::Statistics::endInterval (const string & str) [inline]
Definition at line 108 of file calculationStats.h.
References helperTimer, prefix, corecvs::PreciseTimer::usecsToNow(), and values.
Referenced by resetInterval().
    {
        values[prefix + str] = SingleStat(helperTimer.usecsToNow());
    }
void corecvs::Statistics::resetInterval (const string & str) [inline]
Definition at line 113 of file calculationStats.h.
References endInterval(), and startInterval().
    {
        endInterval(str);
        startInterval();
    }
void corecvs::Statistics::setTime (const string & str, uint64_t delay) [inline]
Definition at line 119 of file calculationStats.h.
References prefix, and values.
Referenced by corecvs::Clustering3D::_clusterStarting(), BaseCalculationThread::executeFilterGraph(), and RecorderThread::processNewData().
    {
        values[prefix + str] = SingleStat(delay);
    }
void corecvs::Statistics::setValue (const string & str, uint64_t value) [inline]
Definition at line 124 of file calculationStats.h.
References prefix, corecvs::SingleStat::UNSIGNED, and values.
    {
        values[prefix + str] = SingleStat(value, SingleStat::UNSIGNED);
    }
void corecvs::Statistics::startInterval () [inline]
Definition at line 103 of file calculationStats.h.
References corecvs::PreciseTimer::currentTime(), and helperTimer.
Referenced by resetInterval().
    {
        helperTimer = PreciseTimer::currentTime();
    }
Member Data Documentation
PreciseTimer corecvs::Statistics::helperTimer
Definition at line 101 of file calculationStats.h.
Referenced by endInterval(), and startInterval().
string corecvs::Statistics::prefix
Definition at line 100 of file calculationStats.h.
Referenced by endInterval(), BaseCalculationThread::executeFilterGraph(), setTime(), and setValue().
map<string, SingleStat> corecvs::Statistics::values
Definition at line 99 of file calculationStats.h.
Referenced by corecvs::BaseTimeStatisticsCollector::addStatistics(), endInterval(), setTime(), and setValue().
The documentation for this class was generated from the following file:
core/stats/calculationStats.h