DeepView: DirectShowCameraDescriptor Class Reference
DirectShowCameraDescriptor Class Reference
#include <directShow.h>
Public Types
enum { UNCOMPRESSED_YUV = 0, UNCOMPRESSED_RGB = 1, COMPRESSED_JPEG = 2, COMPRESSED_FAST_JPEG = 3 }
Public Member Functions
DirectShowCameraDescriptor ()
int queryCameraParameters (CameraParameters &parameters)
int setCaptureProperty (int id, int value)
int getCaptureProperty (int id, int *value)
Public Attributes
DSCapDeviceId deviceHandle
int size
uint64_t decodeTime
uint64_t timestamp
bool gotBuffer
G12Buffer * buffer
uint8_t * rawBuffer
int height
int width
Static Public Attributes
static const char * codec_names []
Static Private Member Functions
static void setFromCameraParam (CaptureParameter &param, CameraParameter &camParam)
Detailed Description
Definition at line 13 of file directShow.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
UNCOMPRESSED_YUV
UNCOMPRESSED_RGB
COMPRESSED_JPEG
COMPRESSED_FAST_JPEG
Definition at line 30 of file directShow.h.
         {
       UNCOMPRESSED_YUV = 0,
       UNCOMPRESSED_RGB = 1,
       COMPRESSED_JPEG = 2,
       COMPRESSED_FAST_JPEG = 3
    };
Constructor & Destructor Documentation
DirectShowCameraDescriptor::DirectShowCameraDescriptor () [inline]
Definition at line 38 of file directShow.h.
                                 :
        deviceHandle(-1),
        size(0),
        decodeTime(0),
        timestamp(0),
        gotBuffer(false),
        buffer(NULL),
        rawBuffer(NULL),
        height(0),
        width(0)
    {}
Member Function Documentation
int DirectShowCameraDescriptor::getCaptureProperty (int id, int * value)
Definition at line 216 of file directShow.cpp.
References CameraParameters::AUTO_FOCUS, CameraParameters::BACKLIGHT_COMPENSATION, CameraParameters::CONTRAST, deviceHandle, CameraParameters::EXPOSURE, CameraParameters::EXPOSURE_AUTO, CameraParameters::FOCUS, CameraParameters::GAIN, CameraParameters::HUE, CameraParameters::IRIS, CameraParameters::SATURATION, CameraParameters::SHARPNESS, and CameraParameters::WHITE_BALANCE.
Referenced by DirectShowCaptureDecoupleInterface::getCaptureProperty(), and DirectShowCaptureInterface::getCaptureProperty().
{
    switch (id)
    {
        case CameraParameters::EXPOSURE_AUTO:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Exposure, &param);
            *value = param.isAuto;
            break;
        }
        case CameraParameters::EXPOSURE:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Exposure, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::IRIS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Iris, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::FOCUS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Focus, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::AUTO_FOCUS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Focus, &param);
            *value = param.isAuto;
            break;
        }
        /* AMP */
        case CameraParameters::CONTRAST:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Contrast, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::HUE:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Hue, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::SATURATION:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Saturation, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::SHARPNESS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Sharpness, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::WHITE_BALANCE:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_WhiteBalance, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::BACKLIGHT_COMPENSATION:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_BacklightCompensation, &param);
            *value = param.value;
            break;
        }
        case CameraParameters::GAIN:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Gain, &param);
            *value = param.value;
            break;
        }
        default:
        {
            printf("Set request for unknown parameter (%d)\n", id);
            return 1;
        }
    }
    return 0;
}
int DirectShowCameraDescriptor::queryCameraParameters (CameraParameters & parameters)
Definition at line 24 of file directShow.cpp.
References CameraParameters::AUTO_FOCUS, CameraParameters::BACKLIGHT_COMPENSATION, CameraParameters::BRIGHTNESS, CameraParameters::CONTRAST, deviceHandle, CameraParameters::EXPOSURE, CameraParameters::EXPOSURE_AUTO, CameraParameters::FOCUS, CameraParameters::GAIN, CameraParameters::HUE, CameraParameters::IRIS, CameraParameters::mCameraControls, CaptureParameter::pushMenuItem(), CameraParameters::SATURATION, CaptureParameter::setActive(), CaptureParameter::setDefaultValue(), setFromCameraParam(), CaptureParameter::setIsMenu(), CaptureParameter::setMaximum(), CaptureParameter::setMinimum(), CaptureParameter::setStep(), CameraParameters::SHARPNESS, and CameraParameters::WHITE_BALANCE.
Referenced by DirectShowCaptureDecoupleInterface::queryCameraParameters(), and DirectShowCaptureInterface::queryCameraParameters().
{
    CameraParameter paramsFromCamera;
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Exposure, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::EXPOSURE], paramsFromCamera);
    CaptureParameter &expAuto = parameters.mCameraControls[CameraParameters::EXPOSURE_AUTO];
    expAuto = CaptureParameter();
    expAuto.setActive(true);
    expAuto.setIsMenu(0);
    expAuto.setMinimum(0);
    expAuto.setMaximum(1);
    expAuto.setStep(1);
    expAuto.setDefaultValue(0);
    expAuto.pushMenuItem(QString("OFF"), 0);
    expAuto.pushMenuItem(QString("ON") , 1);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Iris, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::IRIS], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Focus, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::FOCUS], paramsFromCamera);
    CaptureParameter &focusAuto = parameters.mCameraControls[CameraParameters::AUTO_FOCUS];
    focusAuto = CaptureParameter();
    focusAuto.setActive(true);
    focusAuto.setIsMenu(0);
    focusAuto.setMinimum(0);
    focusAuto.setMaximum(1);
    focusAuto.setStep(1);
    focusAuto.setDefaultValue(0);
    focusAuto.pushMenuItem(QString("OFF"), 0);
    focusAuto.pushMenuItem(QString("ON") , 1);
    /*Amp contols*/
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Brightness, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::BRIGHTNESS], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Contrast, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::CONTRAST], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Hue, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::HUE], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Saturation, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::SATURATION], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Sharpness, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::SHARPNESS], paramsFromCamera);
//    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_ColorEnable, &paramsFromCamera);
//    setFromCameraParam(parameters.mCameraControls[CameraParameters::COL], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_WhiteBalance, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::WHITE_BALANCE], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_BacklightCompensation, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::BACKLIGHT_COMPENSATION], paramsFromCamera);
    DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Gain, &paramsFromCamera);
    setFromCameraParam(parameters.mCameraControls[CameraParameters::GAIN], paramsFromCamera);
    return 0;
}
int DirectShowCameraDescriptor::setCaptureProperty (int id, int value)
Definition at line 91 of file directShow.cpp.
References CameraParameters::AUTO_FOCUS, CameraParameters::BACKLIGHT_COMPENSATION, CameraParameters::CONTRAST, deviceHandle, CameraParameters::EXPOSURE, CameraParameters::EXPOSURE_AUTO, CameraParameters::FOCUS, CameraParameters::GAIN, CameraParameters::HUE, CameraParameters::IRIS, CameraParameters::SATURATION, CameraParameters::SHARPNESS, and CameraParameters::WHITE_BALANCE.
Referenced by DirectShowCaptureDecoupleInterface::setCaptureProperty(), and DirectShowCaptureInterface::setCaptureProperty().
{
    switch (id)
    {
        case CameraParameters::EXPOSURE_AUTO:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Exposure, &param);
            param.isAuto = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_Control_Exposure, &param);
            break;
        }
        case CameraParameters::EXPOSURE:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Exposure, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_Control_Exposure, &param);
            break;
        }
        case CameraParameters::IRIS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Iris, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_Control_Iris, &param);
            break;
        }
        case CameraParameters::FOCUS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Focus, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_Control_Focus, &param);
            break;
        }
        case CameraParameters::AUTO_FOCUS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_Control_Focus, &param);
            param.isAuto = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_Control_Focus, &param);
            break;
        }
        /* AMP */
        case CameraParameters::CONTRAST:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Contrast, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_AMP_Contrast, &param);
            break;
        }
        case CameraParameters::HUE:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Hue, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_AMP_Hue, &param);
            break;
        }
        case CameraParameters::SATURATION:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Saturation, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_AMP_Saturation, &param);
            break;
        }
        case CameraParameters::SHARPNESS:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Sharpness, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_AMP_Sharpness, &param);
            break;
        }
        case CameraParameters::WHITE_BALANCE:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_WhiteBalance, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_AMP_WhiteBalance, &param);
            break;
        }
        case CameraParameters::BACKLIGHT_COMPENSATION:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_BacklightCompensation, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_AMP_BacklightCompensation, &param);
            break;
        }
        case CameraParameters::GAIN:
        {
            CameraParameter param;
            DirectShowCapDll_getCameraProp(deviceHandle, CAPDLL_AMP_Gain, &param);
            param.value = value;
            DirectShowCapDll_setCameraProp(deviceHandle, CAPDLL_AMP_Gain, &param);
            break;
        }
        default:
            {
                printf("Set request for unknown parameter (%d)\n", id);
                return 1;
            }
    }
    return 0;
}
void DirectShowCameraDescriptor::setFromCameraParam (CaptureParameter & param, CameraParameter & camParam) [static, private]
Definition at line 12 of file directShow.cpp.
References CaptureParameter::setActive(), CaptureParameter::setDefaultValue(), CaptureParameter::setMaximum(), CaptureParameter::setMinimum(), and CaptureParameter::setStep().
Referenced by queryCameraParameters().
{
    param = CaptureParameter();
    param.setActive      (true);
    param.setMaximum     (camParam.maxValue);
    param.setMinimum     (camParam.minValue);
    param.setStep        (camParam.step);
    param.setDefaultValue(camParam.defaultValue);
}
Member Data Documentation
G12Buffer* DirectShowCameraDescriptor::buffer
Definition at line 24 of file directShow.h.
Referenced by DirectShowCaptureInterface::memberCallback().
const char * DirectShowCameraDescriptor::codec_names [static]
Initial value:
{
        "yuv",
        "rgb",
        "mjpeg",
        "mjpeg fast decoder"
}
Definition at line 17 of file directShow.h.
Referenced by DirectShowCaptureDecoupleInterface::DirectShowCaptureDecoupleInterface().
uint64_t DirectShowCameraDescriptor::decodeTime
Definition at line 21 of file directShow.h.
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
DSCapDeviceId DirectShowCameraDescriptor::deviceHandle
Definition at line 19 of file directShow.h.
Referenced by DirectShowCaptureDecoupleInterface::DirectShowCaptureDecoupleInterface(), DirectShowCaptureInterface::DirectShowCaptureInterface(), getCaptureProperty(), DirectShowCaptureInterface::isCorrectDeviceHandle(), queryCameraParameters(), and setCaptureProperty().
bool DirectShowCameraDescriptor::gotBuffer
Definition at line 23 of file directShow.h.
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
int DirectShowCameraDescriptor::height
Definition at line 26 of file directShow.h.
uint8_t* DirectShowCameraDescriptor::rawBuffer
Definition at line 25 of file directShow.h.
Referenced by DirectShowCaptureDecoupleInterface::getFrame(), and DirectShowCaptureDecoupleInterface::memberCallback().
int DirectShowCameraDescriptor::size
Definition at line 20 of file directShow.h.
uint64_t DirectShowCameraDescriptor::timestamp
Definition at line 22 of file directShow.h.
Referenced by DirectShowCaptureDecoupleInterface::getFrame(), DirectShowCaptureInterface::getFrame(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
int DirectShowCameraDescriptor::width
Definition at line 27 of file directShow.h.
The documentation for this class was generated from the following files:
utils/framesources/directShow/directShow.h
utils/framesources/directShow/directShow.cpp