DeepView: ParametersMapperRecorder Class Reference
ParametersMapperRecorder Class Reference
#include <parametersMapperRecorder.h>
Public Slots
void paramsChanged ()
Signals
void baseParametersParamsChanged (QSharedPointer< BaseParameters > params)
void recorderParamsChanged (QSharedPointer< Recorder > params)
void presentationParametersParamsChanged (QSharedPointer< PresentationParameters > params)
Public Member Functions
ParametersMapperRecorder ()
void setBaseParametersControlWidget (BaseParametersControlWidget *widget)
void setRecorderControlWidget (RecorderControlWidget *widget)
void setPresentationParametersControlWidget (PresentationParametersControlWidget *widget)
Private Attributes
BaseParametersControlWidget * mBaseParametersControlWidget
RecorderControlWidget * mRecorderControlWidget
PresentationParametersControlWidget * mPresentationParametersControlWidget
Detailed Description
Definition at line 21 of file parametersMapperRecorder.h.
Constructor & Destructor Documentation
ParametersMapperRecorder::ParametersMapperRecorder ()
Definition at line 11 of file parametersMapperRecorder.cpp.
                                                   :
    mBaseParametersControlWidget(NULL)
  , mRecorderControlWidget(NULL)
  , mPresentationParametersControlWidget(NULL)
{
    qRegisterMetaType<QSharedPointer<BaseParameters> >("QSharedPointer<BaseParameters>");
    qRegisterMetaType<QSharedPointer<Recorder> >("QSharedPointer<Recorder>");
    qRegisterMetaType<QSharedPointer<PresentationParameters> >("QSharedPointer<PresentationParameters>");
}
Member Function Documentation
void ParametersMapperRecorder::baseParametersParamsChanged (QSharedPointer< BaseParameters > params) [signal]
Referenced by paramsChanged().
void ParametersMapperRecorder::paramsChanged () [slot]
Definition at line 39 of file parametersMapperRecorder.cpp.
References baseParametersParamsChanged(), PresentationParametersControlWidget::createParameters(), BaseParametersControlWidget::createParameters(), RecorderControlWidget::createParameters(), mBaseParametersControlWidget, mPresentationParametersControlWidget, mRecorderControlWidget, presentationParametersParamsChanged(), and recorderParamsChanged().
Referenced by RecorderDialog::createCalculator(), setBaseParametersControlWidget(), setPresentationParametersControlWidget(), and setRecorderControlWidget().
{
    if (mBaseParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperRecorder \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit baseParametersParamsChanged(QSharedPointer<BaseParameters>(mBaseParametersControlWidget->createParameters()));
    if (mRecorderControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperRecorder \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit recorderParamsChanged(QSharedPointer<Recorder>(mRecorderControlWidget->createParameters()));
    if (mPresentationParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperRecorder \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit presentationParametersParamsChanged(QSharedPointer<PresentationParameters>(mPresentationParametersControlWidget->createParameters()));
}
void ParametersMapperRecorder::presentationParametersParamsChanged (QSharedPointer< PresentationParameters > params) [signal]
Referenced by paramsChanged().
void ParametersMapperRecorder::recorderParamsChanged (QSharedPointer< Recorder > params) [signal]
Referenced by paramsChanged().
void ParametersMapperRecorder::setBaseParametersControlWidget (BaseParametersControlWidget * widget)
Definition at line 21 of file parametersMapperRecorder.cpp.
References mBaseParametersControlWidget, and paramsChanged().
Referenced by RecorderDialog::createCalculator().
{
    mBaseParametersControlWidget = widget;
    QObject::connect(mBaseParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}
void ParametersMapperRecorder::setPresentationParametersControlWidget (PresentationParametersControlWidget * widget)
Definition at line 33 of file parametersMapperRecorder.cpp.
References mPresentationParametersControlWidget, and paramsChanged().
Referenced by RecorderDialog::createCalculator().
{
    mPresentationParametersControlWidget = widget;
    QObject::connect(mPresentationParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}
void ParametersMapperRecorder::setRecorderControlWidget (RecorderControlWidget * widget)
Definition at line 27 of file parametersMapperRecorder.cpp.
References mRecorderControlWidget, and paramsChanged().
Referenced by RecorderDialog::createCalculator().
{
    mRecorderControlWidget = widget;
    QObject::connect(mRecorderControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}
Member Data Documentation
BaseParametersControlWidget* ParametersMapperRecorder::mBaseParametersControlWidget [private]
Definition at line 40 of file parametersMapperRecorder.h.
Referenced by paramsChanged(), and setBaseParametersControlWidget().
PresentationParametersControlWidget* ParametersMapperRecorder::mPresentationParametersControlWidget [private]
Definition at line 42 of file parametersMapperRecorder.h.
Referenced by paramsChanged(), and setPresentationParametersControlWidget().
RecorderControlWidget* ParametersMapperRecorder::mRecorderControlWidget [private]
Definition at line 41 of file parametersMapperRecorder.h.
Referenced by paramsChanged(), and setRecorderControlWidget().
The documentation for this class was generated from the following files:
applications/recorder/parametersMapper/parametersMapperRecorder.h
applications/recorder/parametersMapper/parametersMapperRecorder.cpp