DeepView: OpenCVSGMParametersControlWidget Class Reference
OpenCVSGMParametersControlWidget Class Reference
#include <openCVSGMParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
OpenCVSGMParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~OpenCVSGMParametersControlWidget ()
OpenCVSGMParameters * createParameters () const
void setParameters (const OpenCVSGMParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_OpenCVSGMParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file openCVSGMParametersControlWidget.h.
Constructor & Destructor Documentation
OpenCVSGMParametersControlWidget::OpenCVSGMParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file openCVSGMParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::OpenCVSGMParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->preFilterCapSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->sADWindowSizeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->p1MultiplierSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->p2MultiplierSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->minDisparitySpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->uniquenessRatioSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->speckleWindowSizeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->speckleRangeSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->disp12MaxDiffSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fullDPCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
}
OpenCVSGMParametersControlWidget::~OpenCVSGMParametersControlWidget ()
Definition at line 35 of file openCVSGMParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void OpenCVSGMParametersControlWidget::changeParameters () [inline, slot]
Definition at line 29 of file openCVSGMParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
OpenCVSGMParameters * OpenCVSGMParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 57 of file openCVSGMParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    OpenCVSGMParameters *result = new OpenCVSGMParameters(
          mUi->preFilterCapSpinBox->value()
        , mUi->sADWindowSizeSpinBox->value()
        , mUi->p1MultiplierSpinBox->value()
        , mUi->p2MultiplierSpinBox->value()
        , mUi->minDisparitySpinBox->value()
        , mUi->uniquenessRatioSpinBox->value()
        , mUi->speckleWindowSizeSpinBox->value()
        , mUi->speckleRangeSpinBox->value()
        , mUi->disp12MaxDiffSpinBox->value()
        , mUi->fullDPCheckBox->isChecked()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void OpenCVSGMParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 41 of file openCVSGMParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    OpenCVSGMParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void OpenCVSGMParametersControlWidget::paramsChanged () [signal]
Referenced by OpenCVSGMParametersControlWidget(), and setParameters().
void OpenCVSGMParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 49 of file openCVSGMParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    OpenCVSGMParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void OpenCVSGMParametersControlWidget::setParameters (const OpenCVSGMParameters & input)
Definition at line 80 of file openCVSGMParametersControlWidget.cpp.
References OpenCVSGMParameters::disp12MaxDiff(), OpenCVSGMParameters::fullDP(), OpenCVSGMParameters::minDisparity(), mUi, OpenCVSGMParameters::p1Multiplier(), OpenCVSGMParameters::p2Multiplier(), paramsChanged(), OpenCVSGMParameters::preFilterCap(), OpenCVSGMParameters::sADWindowSize(), OpenCVSGMParameters::speckleRange(), OpenCVSGMParameters::speckleWindowSize(), and OpenCVSGMParameters::uniquenessRatio().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->preFilterCapSpinBox->setValue(input.preFilterCap());
    mUi->sADWindowSizeSpinBox->setValue(input.sADWindowSize());
    mUi->p1MultiplierSpinBox->setValue(input.p1Multiplier());
    mUi->p2MultiplierSpinBox->setValue(input.p2Multiplier());
    mUi->minDisparitySpinBox->setValue(input.minDisparity());
    mUi->uniquenessRatioSpinBox->setValue(input.uniquenessRatio());
    mUi->speckleWindowSizeSpinBox->setValue(input.speckleWindowSize());
    mUi->speckleRangeSpinBox->setValue(input.speckleRange());
    mUi->disp12MaxDiffSpinBox->setValue(input.disp12MaxDiff());
    mUi->fullDPCheckBox->setChecked(input.fullDP());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void OpenCVSGMParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 98 of file openCVSGMParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    OpenCVSGMParameters *inputCasted = static_cast<OpenCVSGMParameters *>(input);
    setParameters(*inputCasted);
}
void OpenCVSGMParametersControlWidget::valueChanged () [signal]
Referenced by OpenCVSGMParametersControlWidget().
Member Data Documentation
bool OpenCVSGMParametersControlWidget::autoInit [private]
Definition at line 40 of file openCVSGMParametersControlWidget.h.
Ui_OpenCVSGMParametersControlWidget* OpenCVSGMParametersControlWidget::mUi [private]
Definition at line 39 of file openCVSGMParametersControlWidget.h.
Referenced by createParameters(), OpenCVSGMParametersControlWidget(), setParameters(), and ~OpenCVSGMParametersControlWidget().
QString OpenCVSGMParametersControlWidget::rootPath [private]
Definition at line 41 of file openCVSGMParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/corestructs/libWidgets/openCVSGMParametersControlWidget.h
utils/corestructs/libWidgets/openCVSGMParametersControlWidget.cpp