DeepView: corecvs::DisparityBuffer Class Reference
corecvs::DisparityBuffer Class Reference
#include <disparityBuffer.h>
Public Types
typedef AbstractBuffer
< ElementType, IndexType > BaseClass
enum BufferType { NORMAL_BUFFER, VIEW_BUFFER, EMPTY_BUFFER }
typedef ElementType InternalElementType
Type of the internal data type.
typedef IndexType InternalIndexType
Public Member Functions
DisparityBuffer (int32_t h, int32_t w)
DisparityBuffer (DisparityBuffer &that)
DisparityBuffer (DisparityBuffer *that)
DisparityBuffer (DisparityBuffer *src, int32_t x1, int32_t y1, int32_t x2, int32_t y2)
DisparityBuffer (uint32_t h, uint32_t w, bool shouldClear)
DisparityBuffer (uint32_t h, uint32_t w, DisparityElement *data)
ElementType elementBl (const Vector2dd &p)
ElementType elementBl (double y, double x)
The element getter with spline interpolation.
ElementType elementBlFast (const Vector2dd &p)
ElementType elementBlFast (double y, double x)
Alternative version (faster)
ElementType elementBlInt (double y, double x)
The element getter with bilinear filtration This version is using integer multiplication.
bool isValidCoordBl (double y, double x) const
Checks if coordinate lies within the buffer area.
bool isValidCoordBl (const Vector2dd &p) const
Checks if coordinate lies within the buffer area.
template<class ReturnType , class DeformMapType >
ReturnType * doReverseDeformationBl (const DeformMapType *map, IndexType newH, IndexType newW)
This function template is responsible for applying reverse transformation to the abstract buffer.
template<class ReturnType , class DeformMapType >
ReturnType * doReverseDeformation (DeformMapType &map, IndexType newH, IndexType newW)
template<typename ResultType >
ResultType * createView (const IndexType y, const IndexType x, const IndexType h, const IndexType w)
template<typename ResultType >
ResultType * createView ()
ElementType & element (const IndexType y, const IndexType x)
The element getter.
const ElementType & element (const IndexType y, const IndexType x) const
ElementType & element (const Vector2d< IndexType > &p)
The element getter.
const ElementType & element (const Vector2d< IndexType > &p) const
bool isValidCoord (const IndexType y, const IndexType x) const
Checks if coordinate lies within the buffer area.
bool isValidCoord (const Vector2d< IndexType > &p) const
Checks if coordinate lies within the buffer area.
bool hasSameSize (const AbstractBuffer< ElementType, IndexType > *other) const
Checks if this buffer has the same size as the other.
bool hasSameSize (const IndexType &otherH, const IndexType &otherW) const
Checks if this buffer has the same size as the parameters given.
IndexType getH () const
Height getter.
IndexType getStride () const
Stride getter.
IndexType getW () const
Width getter.
Vector2d< IndexType > getSize () const
Buffer size getter.
bool isAllocated () const
Checking for successfull allocation.
size_t sizeInBytes () const
Calculate image buffer size in bytes.
void fillRectangleWith (IndexType y, IndexType x, IndexType rectH, IndexType rectW, const ElementType &value)
This function fills the rectangle inside the buffer with the value.
void fillWith (const ElementType &value)
This function fills the whole buffer with the value.
void fillWith (const AbstractBuffer &other)
This function fills the whole buffer with the values from the other buffer.
void fillWithRaw (ElementType *_data)
This function fills the whole buffer with the values from the given array.
void fillWithArgs (const ElementType value, va_list marker)
You could use this to clean the buffer.
void fillWithArgs (const ElementType value,...)
void fillLineWithArgs (IndexType line, const ElementType value,...)
void fillWithRands (ElementType valueMax, ElementType valueMin=ElementType(0))
Fills the buffer by random values within the given range.
template<typename ReturnType , typename ConvElementType , typename ConvIndexType >
void innerCycleDoConvolve (ReturnType *toReturn, AbstractKernel< ConvElementType, ConvIndexType > *kernel, int i)
template<typename ReturnType , typename ConvElementType , typename ConvIndexType >
ReturnType * doConvolve (AbstractKernel< ConvElementType, ConvIndexType > *kernel)
This function is used to convolve/cross-correlate a buffer with the kernel.
template<typename ReturnType , typename ConvElementType , typename ConvIndexType >
ReturnType * doConvolve1 (AbstractKernel< ConvElementType, ConvIndexType > *kernel)
bool isEqual (const AbstractBuffer &that) const
This method tests for equality.
bool isEqualTrace (const AbstractBuffer &that) const
template<typename operation >
void binaryOperationInPlace (const AbstractBuffer &that, const operation &oper=operation())
This method performs the "oper" operation between this and that buffers and puts result to this buffer.
template<typename operation >
void mapOperationElementwize (const operation &map)
template<typename operation >
void touchOperationElementwize (operation &map)
bool dump (ostream &s, bool binaryMode) const
bool load (istream &s, bool binaryMode)
template<typename OtherType >
OtherType * mirrorVerticalDump ()
Please check that you really don't want to invoke the copy constructor.
void mirrorVertical ()
Mirrors current buffer vertically.
template<typename OtherType >
OtherType * mirrorVertical ()
void rotate180 ()
Rotates current buffer 180 degrees.
int numElements () const
Calculate number of elements in a buffer.
Public Attributes
int32_t maxValue
ElementType * data
Sometimes underling buffer should not be deleted.
int h
int w
int stride
Static Public Attributes
static const int16_t DISPARITY_UNKNOWN = INT16_MAX
static const int DATA_ALIGN_GRANULARITY = 0xF
This constant represents the default alignment of the line in the buffer.
static int bufferCount = 0
Static member that will be used to prevent and debug memory leaks.
static const IndexType STRIDE_AUTO = (IndexType)0
The height of the buffer.
static cchar TAB = '\t'
Protected Member Functions
bool_t dump (ostream &s, uint elemSize, bool_t binaryMode) const
bool_t load (istream &s, uint elemSize, bool_t binaryMode)
void setH (int _h)
void setW (int _w)
void setStride (int _s)
Static Protected Member Functions
static bool_t dump (ostream &s, int h, int w, int stride, uint elemSize, bool_t binaryMode)
static bool_t load (istream &s, int &h, int &w, int &stride, uint elemSize, bool_t binaryMode)
static bool_t write (ostream &s, int val, bool_t binaryMode)
static bool_t write (ostream &s, cchar *str, bool_t binaryMode)
static bool_t read (istream &s, int &val, bool_t binaryMode)
static bool_t read (istream &s, char *str, size_t size, bool_t binaryMode)
template<size_t size>
static bool_t read (istream &s, char(&str)[size], bool_t binaryMode)
Protected Attributes
MemoryBlockRef memoryBlock
The beginning of the allocated memory.
BufferType flags
Friends
ostream & operator<< (ostream &out, const AbstractBuffer &buffer)
Detailed Description
Definition at line 22 of file disparityBuffer.h.
Member Typedef Documentation
template<typename ElementType, typename IndexType = int32_t> typedef AbstractBuffer<ElementType, IndexType> corecvs::AbstractContiniousBuffer< ElementType, IndexType >::BaseClass [inherited]
Definition at line 32 of file abstractContiniousBuffer.h.
template<typename ElementType, typename IndexType = int32_t> typedef ElementType corecvs::AbstractBuffer< ElementType, IndexType >::InternalElementType [inherited]
Type of the internal data type.
Definition at line 168 of file abstractBuffer.h.
template<typename ElementType, typename IndexType = int32_t> typedef IndexType corecvs::AbstractBuffer< ElementType, IndexType >::InternalIndexType [inherited]
Definition at line 169 of file abstractBuffer.h.
Member Enumeration Documentation
template<typename ElementType, typename IndexType = int32_t> enum corecvs::AbstractBuffer::BufferType [inherited]
Enumerator:
NORMAL_BUFFER
VIEW_BUFFER
EMPTY_BUFFER
Definition at line 171 of file abstractBuffer.h.
                    {
        NORMAL_BUFFER,
        VIEW_BUFFER,
        EMPTY_BUFFER
    };
Constructor & Destructor Documentation
corecvs::DisparityBuffer::DisparityBuffer (int32_t h, int32_t w) [inline]
Definition at line 29 of file disparityBuffer.h.
                                          :
        DisparityBufferBase(h, w, (DisparityElement)DisparityBuffer::DISPARITY_UNKNOWN) {}
corecvs::DisparityBuffer::DisparityBuffer (DisparityBuffer & that) [inline]
Definition at line 32 of file disparityBuffer.h.
: DisparityBufferBase (that) {}
corecvs::DisparityBuffer::DisparityBuffer (DisparityBuffer * that) [inline]
Definition at line 33 of file disparityBuffer.h.
: DisparityBufferBase (that) {}
corecvs::DisparityBuffer::DisparityBuffer (DisparityBuffer * src, int32_t x1, int32_t y1, int32_t x2, int32_t y2) [inline]
Definition at line 35 of file disparityBuffer.h.
                                                                                          :
        DisparityBufferBase(src, x1, y1, x2, y2) {}
corecvs::DisparityBuffer::DisparityBuffer (uint32_t h, uint32_t w, bool shouldClear) [inline]
Definition at line 38 of file disparityBuffer.h.
                                                              :
        DisparityBufferBase(h, w, shouldClear) {}
corecvs::DisparityBuffer::DisparityBuffer (uint32_t h, uint32_t w, DisparityElement * data) [inline]
Definition at line 41 of file disparityBuffer.h.
                                                                    :
        DisparityBufferBase(h, w, data) {}
Member Function Documentation
template<typename ElementType, typename IndexType = int32_t> template<typename operation > void corecvs::AbstractBuffer< ElementType, IndexType >::binaryOperationInPlace (const AbstractBuffer< ElementType, IndexType > & that, const operation & oper = operation()) [inline, inherited]
This method performs the "oper" operation between this and that buffers and puts result to this buffer.
Parameters:
that - the AbstractBuffer to be processed with this to this
oper - operation to be performed
Definition at line 836 of file abstractBuffer.h.
    {
        IndexType h = min(this->h, that.h);
        IndexType w = min(this->w, that.w);
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElemRunner = &(this->element(i,0));
            const ElementType *thatElemRunner = &(that.element(i,0));
            for (IndexType j = 0; j < w; j++)
            {
                /* Writing like this just to emphasize what is actually called */
                *thisElemRunner = oper.operator()(*thisElemRunner, *thatElemRunner);
                thisElemRunner++;
                thatElemRunner++;
            }
        }
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ResultType > ResultType* corecvs::AbstractBuffer< ElementType, IndexType >::createView (const IndexType y, const IndexType x, const IndexType h, const IndexType w) [inline, inherited]
Prevent original buffer from being deleted MemoryBlock magically counts references
Definition at line 370 of file abstractBuffer.h.
    {
        // This is the only legitimate place to use default constructor
        ResultType *toReturn = new ResultType();
        toReturn->flags      = VIEW_BUFFER;
        toReturn->h          = h;
        toReturn->w          = w;
        toReturn->stride     = this->stride;
        toReturn->data       = &(this->element(y, x));
        /**
         * Prevent original buffer from being deleted
         * MemoryBlock magically counts references
         **/
        toReturn->memoryBlock = memoryBlock;
      //toReturn->_allocatedSize = 0;
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ResultType > ResultType* corecvs::AbstractBuffer< ElementType, IndexType >::createView () [inline, inherited]
Definition at line 390 of file abstractBuffer.h.
    {
        return this->createView<ResultType>(0, 0, this->h, this->w);
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ReturnType , typename ConvElementType , typename ConvIndexType > ReturnType* corecvs::AbstractBuffer< ElementType, IndexType >::doConvolve (AbstractKernel< ConvElementType, ConvIndexType > * kernel) [inline, inherited]
This function is used to convolve/cross-correlate a buffer with the kernel.
In general convolution is
But this function does more of cross-correlation.
Definition at line 710 of file abstractBuffer.h.
    {
        IndexType i;
        ReturnType *toReturn = new ReturnType(h, w);
        parallelable_for(0, h, ParallelDoConvolve<ReturnType, ConvElementType, ConvIndexType>(toReturn, kernel, this));
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ReturnType , typename ConvElementType , typename ConvIndexType > ReturnType* corecvs::AbstractBuffer< ElementType, IndexType >::doConvolve1 (AbstractKernel< ConvElementType, ConvIndexType > * kernel) [inline, inherited]
Reimplemented in corecvs::G12Buffer.
Definition at line 755 of file abstractBuffer.h.
    {
        IndexType i,j;
        ReturnType *toReturn = new ReturnType(h, w);
        parallelable_for(kernel->centerY, h - kernel->h + kernel->centerY,
                ParallelDoConvolve1<ReturnType, ConvElementType, ConvIndexType>(toReturn, kernel, this));
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<class ReturnType , class DeformMapType > ReturnType* corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformation (DeformMapType & map, IndexType newH, IndexType newW) [inline, inherited]
Definition at line 385 of file abstractContiniousBuffer.h.
    {
        IndexType i,j;
        ReturnType *toReturn = new ReturnType(newH, newW);
        DOTRACE(("Starting integer transform to %d %d...\n", newW - 1, newH - 1));
        parallelable_for((IndexType)0, (IndexType)(newH-1), ParallelDoReverseDeformation<ReturnType, DeformMapType>(toReturn, map, this));
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<class ReturnType , class DeformMapType > ReturnType* corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformationBl (const DeformMapType * map, IndexType newH, IndexType newW) [inline, inherited]
This function template is responsible for applying reverse transformation to the abstract buffer.
Parameters:
map The map to apply
newH Output Buffer Height
newW Output Buffer Width
Definition at line 342 of file abstractContiniousBuffer.h.
Referenced by corecvs::DistortionCorrectTransform::doCorrectionTransform(), corecvs::RadialCorrection::doCorrectionTransform(), corecvs::TransformationCache::doDeformation(), BaseCalculationThread::executeFilterGraph(), ScaleFilter::filter(), DistortionWidget::showBufferChanged(), and BaseCalculationThread::transformInputFrames().
    {
        ReturnType *toReturn = new ReturnType(newH, newW);
        DOTRACE(("Starting transform to %d %d...\n", newW - 1, newH - 1));
        parallelable_for((IndexType)0,(IndexType)(newH-1), ParallelDoReverseDeformationBl<ReturnType, DeformMapType>(toReturn, map, this));
        return toReturn;
    }
bool_t corecvs::AbstractBufferParams::dump (ostream & s, int h, int w, int stride, uint elemSize, bool_t binaryMode) [static, protected, inherited]
Definition at line 15 of file abstractBuffer.cpp.
References corecvs::sFormatStr, and corecvs::write_integer_bin().
{
    if (binaryMode)
    {
        write_integer_bin(s, w);
        write_integer_bin(s, stride);
        write_integer_bin(s, h);
        write_integer_bin(s, elemSize);
    }
    else
    {
        char buf[256];
        s.write(buf, snprintf2buf(buf, sFormatStr, w, stride, h, elemSize));
        s << endl;
    }
    return !s.bad();
}
bool_t corecvs::AbstractBufferParams::dump (ostream & s, uint elemSize, bool_t binaryMode) const [inline, protected, inherited]
Definition at line 152 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::dump(), corecvs::AbstractBufferParams::h, corecvs::AbstractBufferParams::stride, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::AbstractBufferParams::dump().
{ return dump(s, h, w, stride, elemSize, binaryMode); }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::dump (ostream & s, bool binaryMode) const [inline, inherited]
Definition at line 911 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::dump().
    {
        AbstractBufferParams::dump(s, sizeof(ElementType), binaryMode);
        if (binaryMode) {
            s.write((char *)data, sizeInBytes());
        }
        return !s.bad();
    }
template<typename ElementType, typename IndexType = int32_t> ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const IndexType y, const IndexType x) [inline, inherited]
The element getter.
A common practice in this project is for the y coordinate to come first
Definition at line 401 of file abstractBuffer.h.
Referenced by corecvs::Clustering3D::_clustering(), corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::Matrix::a(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::Buffer3d::addPoints(), corecvs::G12Buffer3d::addPoints(), corecvs::VJPattern::applyToPoint(), corecvs::AbstractBuffer< SegmentType * >::binaryOperationInPlace(), corecvs::BooleanBuffer::BooleanBuffer(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), OpenCvHelper::captureImageCopyToBuffer(), corecvs::Clustering3D::clustering(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::DecoupleYUYV::decouple(), corecvs::DerivativeBuffer::DerivativeBuffer(), corecvs::DisplacementBuffer::DisplacementBuffer(), FlowDrawer::draw(), corecvs::RGB24Buffer::drawArc(), corecvs::RGB24Buffer::drawArc1(), FlowDrawer::drawBigDotsFast(), FlowDrawer::drawDotsFast(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer2(), corecvs::RGB24Buffer::drawFlowBuffer3(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawG12Buffer(), corecvs::RGB24Buffer::drawG8Buffer(), corecvs::RGB24Buffer::drawHistogram1024x512(), corecvs::RGB24Buffer::drawIsolines(), corecvs::RGB24Buffer::drawLineSimple(), corecvs::VJSimpleClassifier::drawPattern(), corecvs::RGB24Buffer::drawPixel(), corecvs::FlowBuffer::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::AbstractContiniousBuffer< double, int >::elementBlInt(), corecvs::G12Buffer::elementBlPrecomp(), corecvs::AbstractBuffer< SegmentType * >::fillLineWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillRectangleWith(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillWithRands(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::RGB24Buffer::fillWithYUYV(), corecvs::SpatialGradient::findCornerPoints(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), corecvs::G8Buffer::FromG12Buffer(), corecvs::G12Buffer::G12Buffer(), corecvs::PPMLoader::g12BufferCreateFromPPM(), G12Image::G12Image(), corecvs::PPMLoader::g16BufferCreateFromPPM(), corecvs::FunctionArgs::getJacobian(), corecvs::EssentialEstimator::CostFunction7to1::getJacobian(), corecvs::Buffer3d::getLength(), corecvs::FlowBuffer::getMeanDifference(), corecvs::Buffer3d::getNearestPoint(), corecvs::DerivativeBuffer::gradientMagnitudeBuffer(), corecvs::Histogram::Histogram(), CloudViewDialog::initializeGLSlot(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::IntegralBuffer(), corecvs::Splain3Interpolator::interpolate(), corecvs::BilinearInterpolator::interpolate(), corecvs::PolynomInterpolator::interpolate(), corecvs::FlowBuffer::invert(), corecvs::DepthBuffer::isElementKnown(), corecvs::SixDBuffer::isElementKnown(), corecvs::FloatFlowBuffer::isElementKnown(), corecvs::Buffer3d::isElementKnown(), corecvs::FlowBuffer::isElementKnown(), corecvs::AbstractBuffer< SegmentType * >::isEqual(), corecvs::AbstractBuffer< SegmentType * >::isEqualTrace(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), QTFileLoader::load(), corecvs::BMPLoader::load(), corecvs::RAWLoader::load(), corecvs::FlowBuffer::load(), corecvs::BufferFactory::loadG16Bitmap(), corecvs::BMPLoader::loadRGB(), corecvs::FixedPointDisplace::map(), corecvs::DisplacementBuffer::map(), corecvs::AbstractBuffer< SegmentType * >::mapOperationElementwize(), TolerancePredicate::mark(), TestbedMainWindow::maskHue(), TestbedMainWindow::maskTolerance(), TestbedMainWindow::maskTolerance1(), DirectShowCaptureInterface::memberCallback(), corecvs::AbstractBuffer< SegmentType * >::mirrorVertical(), corecvs::AbstractBuffer< SegmentType * >::mirrorVerticalDump(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), corecvs::DerivativeBuffer::nonMaximalSuppression(), corecvs::Matrix::notTooFar(), corecvs::ThickeningBlock::operator()(), corecvs::BinarizeBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::ParallelPrepareBlurBuffers::operator()(), corecvs::SobelFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::operator()(), corecvs::DirectRemapper::ParallelRemap::operator()(), TolerancePredicate::operator()(), corecvs::operator<<(), corecvs::FloatFlowBuffer::preciseFlowCalc(), corecvs::BlurProcessor::prepareBlurBuffers(), corecvs::ErodeKernel< Algebra >::process(), corecvs::DilateKernel< Algebra >::process(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::rectangle(), corecvs::CannyFilter::recursiveEdgeProver(), TestbedMainWindow::recursiveTolerance(), QTFileLoader::RGB24BufferFromQImage(), RGB24Image::RGB24Image(), corecvs::AbstractBuffer< SegmentType * >::rotate180(), corecvs::PPMLoader::save(), corecvs::BMPLoader::save(), corecvs::PPMLoader::saveG16(), corecvs::Segmentator< TileSegmentator, TileSegment >::segment(), corecvs::TileGrid::selectWithThreshold(), corecvs::DepthBuffer::setElementUnknown(), corecvs::SixDBuffer::setElementUnknown(), corecvs::FloatFlowBuffer::setElementUnknown(), corecvs::Buffer3d::setElementUnknown(), corecvs::FlowBuffer::setElementUnknown(), corecvs::SixDBuffer::SixDBuffer(), corecvs::SpatialGradient::SpatialGradient(), corecvs::RGB24Buffer::toG12Buffer(), corecvs::AbstractBuffer< SegmentType * >::touchOperationElementwize(), corecvs::FlowBuffer::toVectorForm(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateToDB(), corecvs::BooleanBuffer::unpack(), TestbedMainWindow::updateViewImage(), corecvs::G12Buffer::verify(), and MjpegDecoderLazy::yuv422ptoG12().
    {
        return data[y * stride + x];
    }
template<typename ElementType, typename IndexType = int32_t> const ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const IndexType y, const IndexType x) const [inline, inherited]
Definition at line 406 of file abstractBuffer.h.
    {
        return data[y * stride + x];
    }
template<typename ElementType, typename IndexType = int32_t> ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const Vector2d< IndexType > & p) [inline, inherited]
The element getter.
Definition at line 414 of file abstractBuffer.h.
    {
        return element(p.y(), p.x());
    }
template<typename ElementType, typename IndexType = int32_t> const ElementType& corecvs::AbstractBuffer< ElementType, IndexType >::element (const Vector2d< IndexType > & p) const [inline, inherited]
Definition at line 419 of file abstractBuffer.h.
    {
        return element(p.y(), p.x());
    }
template<typename ElementType, typename IndexType = int32_t> ElementType corecvs::AbstractContiniousBuffer< ElementType, IndexType >::elementBl (const Vector2dd & p) [inline, inherited]
Definition at line 65 of file abstractContiniousBuffer.h.
Referenced by corecvs::AbstractContiniousBuffer< double, int >::elementBl().
    {
        return elementBl(p.y(), p.x());
    }
template<typename ElementType, typename IndexType = int32_t> ElementType corecvs::AbstractContiniousBuffer< ElementType, IndexType >::elementBl (double y, double x) [inline, inherited]
The element getter with spline interpolation.
The element getter with bilinear filtration
Definition at line 168 of file abstractContiniousBuffer.h.
    {
        /* floor() is needed here because of values (-1..0] which will be
         * rounded to 0 and cause error */
        IndexType i = (IndexType)floor(y);
        IndexType j = (IndexType)floor(x);
        ASSERT_TRUE_P(this->isValidCoordBl(y,x),
                ("Invalid coordinate in AbstractContiniousBuffer::elementBl(double y=%lf, double x=%lf) buffer sizes is [%dx%d]",
                   y, x, this->w, this->h));
        ElementType a = this->element(i    ,j    );
        ElementType b = this->element(i    ,j + 1);
        ElementType c = this->element(i + 1,j    );
        ElementType d = this->element(i + 1,j + 1);
        double k1 = x - j;
        double k2 = y - i;
        ElementType result =
             (a * (1 - k1) + k1 * b) * (1 - k2) +
             (c * (1 - k1) + k1 * d) *      k2;
        return result;
    }
template<typename ElementType, typename IndexType = int32_t> ElementType corecvs::AbstractContiniousBuffer< ElementType, IndexType >::elementBlFast (const Vector2dd & p) [inline, inherited]
Definition at line 70 of file abstractContiniousBuffer.h.
Referenced by corecvs::AbstractContiniousBuffer< double, int >::elementBlFast().
    {
        return elementBlFast(p.y(), p.x());
    }
template<typename ElementType, typename IndexType = int32_t> ElementType corecvs::AbstractContiniousBuffer< ElementType, IndexType >::elementBlFast (double y, double x) [inline, inherited]
Alternative version (faster)
http://en.wikipedia.org/wiki/Bilinear_interpolation
GEDB
Could not be used for uint buffers
Definition at line 241 of file abstractContiniousBuffer.h.
    {
        /* floor() is needed here because of values (-1..0] which will be
         * rounded to 0 and cause error */
        IndexType i = floor(y);
        IndexType j = floor(x);
        ASSERT_TRUE_P(this->isValidCoordBl(y,x),
                ("Invalid coordinate in AbstractContiniousBuffer::elementBl(double y=%lf, double x=%lf) buffer sizes is [%dx%d]",
                   y, x, this->w, this->h));
        ElementType &a = this->element(i    ,j    );
        ElementType &b = this->element(i    ,j + 1);
        ElementType &c = this->element(i + 1,j    );
        ElementType &d = this->element(i + 1,j + 1);
        double k1 = x - j;
        double k2 = y - i;
        ElementType b1 = a;
        ElementType b2 = b - a;
        ElementType b3 = c - a;
        ElementType b4 = d - b2 - c;
        ElementType result = b1 + b2 * k1 + b3 * k2 + b4 * k1 * k2;
        return result;
    }
template<typename ElementType, typename IndexType = int32_t> ElementType corecvs::AbstractContiniousBuffer< ElementType, IndexType >::elementBlInt (double y, double x) [inline, inherited]
The element getter with bilinear filtration This version is using integer multiplication.
Definition at line 198 of file abstractContiniousBuffer.h.
    {
        /* floor() is needed here because of values (-1..0] which will be
         * rounded to 0 and cause error */
        IndexType i = floor(y);
        IndexType j = floor(x);
        ASSERT_TRUE_P(this->isValidCoordBl(y,x),
                ("Invalid coordinate in AbstractContiniousBuffer::elementBl(double y=%lf, double x=%lf) buffer sizes is [%dx%d]",
                   y, x, this->w, this->h));
        ElementType a = this->element(i    ,j    );
        ElementType b = this->element(i    ,j + 1);
        ElementType c = this->element(i + 1,j    );
        ElementType d = this->element(i + 1,j + 1);
        double k1 = (x - j);
        double k2 = (y - i);
        double k3 = 1.0 - k1;
        double k4 = 1.0 - k2;
        int f1 = k3 * k4 * 256.0;
        int f2 = k1 * k4 * 256.0;
        int f3 = k3 * k2 * 256.0;
        int f4 = k1 * k2 * 256.0;
        ElementType result =
             (a * f1 + f2 * b) +
             (c * f3 + f4 * d);
        return result / 256;
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs (IndexType line, const ElementType value, ...) [inline, inherited]
Definition at line 602 of file abstractBuffer.h.
Referenced by corecvs::HomographyReconstructor::addPoint2LineConstraintLSE(), corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSE(), corecvs::HomographyReconstructor::addPoint2PointConstraintLSEUnif(), and corecvs::Matrix33::ProjectiveByPoints().
    {
       va_list marker;
       va_start(marker, value);
       this->element(line, 0) = value;
       for (IndexType j = 1; j < w; j++)
           this->element(line,j) = va_arg(marker, ElementType);
       va_end(marker);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillRectangleWith (IndexType y, IndexType x, IndexType rectH, IndexType rectW, const ElementType & value) [inline, inherited]
This function fills the rectangle inside the buffer with the value.
You could use this to clean part of the buffer
Definition at line 510 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::fillWith(), and corecvs::ThickeningBlock::operator()().
    {
        ASSERT_TRUE_P(x >= 0 && y >= 0 && x < w && y < h, ("[%d:%d] origin is not inside the buffer [%dx%d]", x, y, w, h));
        ASSERT_TRUE_P(x + rectW >= 0 && y + rectH >= 0 &&
                      x + rectW <= w && y + rectH <= h, ("[%d:%d] right lower corner is not inside the buffer [%dx%d]", x + rectW, y + rectH, w, h));
        for (IndexType i = y; i < y + rectH; i++)
        {
            ElementType *line = &(element(i, x));
            for (IndexType j = 0; j < rectW; j++)
            {
                *line++ = value;
            }
        }
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWith (const ElementType & value) [inline, inherited]
This function fills the whole buffer with the value.
You could use this to clean the buffer
Definition at line 531 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::VJSimpleClassifier::drawPattern().
    {
        /*for (IndexType i = 0; i < h; i++)
            for (IndexType j = 0; j < w; j++)
                this->element(i,j) = value; */
        fillRectangleWith(0, 0, h, w, value);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWith (const AbstractBuffer< ElementType, IndexType > & other) [inline, inherited]
This function fills the whole buffer with the values from the other buffer.
TODO: this function doesn't call the copy constructor. I believe it should.
Definition at line 563 of file abstractBuffer.h.
    {
        int copyH = CORE_MIN(this->h, other.h);
        int copyW = CORE_MIN(this->w, other.w);
        /* If buffers have same horizontal geometry use fast method*/
        if (other.stride == this->stride && other.w == this->w) {
            memcpy(this->data, other.data, sizeof(ElementType) * copyH * stride);
            return;
        }
        /* Otherwise copy line by line */
        for (int i = 0; i < copyH; i++) {
            memcpy(&this->element(i, 0), &other.element(i, 0), sizeof(ElementType) * copyW);
        }
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithArgs (const ElementType value, va_list marker) [inline, inherited]
You could use this to clean the buffer.
Note:
you should be very careful passing variables of the right type
Definition at line 585 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::fillWithArgs().
    {
        this->element(0, 0) = value;
        for (IndexType i = 0; i < h; i++)
            for (IndexType j = 0; j < w; j++)
                if (i != 0 || j != 0)
                    this->element(i,j) = va_arg(marker, ElementType);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithArgs (const ElementType value, ...) [inline, inherited]
Definition at line 594 of file abstractBuffer.h.
    {
        va_list  marker;
        va_start(marker, value);
        fillWithArgs(value, marker);
        va_end(marker);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithRands (ElementType valueMax, ElementType valueMin = ElementType(0)) [inline, inherited]
Fills the buffer by random values within the given range.
Definition at line 614 of file abstractBuffer.h.
    {
        srand(rand());
        for (IndexType i = 0; i < h; i++)
            for (IndexType j = 0; j < w; j++)
                this->element(i,j) = (ElementType)randRanged(valueMax, valueMin);
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::fillWithRaw (ElementType * _data) [inline, inherited]
This function fills the whole buffer with the values from the given array.
TODO: this function doesn't call the copy constructor. I believe it should.
Definition at line 544 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::G12Buffer::operator=().
    {
       if (this->w == this->stride)
       {
           memcpy(this->data, _data, this->sizeInBytes());
           return;
       }
       size_t rawLength = sizeof(ElementType) * this->w;
       for (int i = 0; i < (int)this->h; i++)
       {
           memcpy(&this->element(i, 0), &_data[i * this->w], rawLength);
       }
    }
template<typename ElementType, typename IndexType = int32_t> IndexType corecvs::AbstractBuffer< ElementType, IndexType >::getH () const [inline, inherited]
Height getter.
Definition at line 459 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::G12Buffer::G12Buffer(), corecvs::G12Buffer3d::G12Buffer3d(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::IntegralBuffer(), corecvs::PolynomInterpolator::interpolate(), corecvs::FlowBuffer::load(), corecvs::AbstractBuffer< SegmentType * >::load(), and corecvs::Matrix::notTooFar().
    {
        return h;
    }
template<typename ElementType, typename IndexType = int32_t> Vector2d<IndexType> corecvs::AbstractBuffer< ElementType, IndexType >::getSize () const [inline, inherited]
Buffer size getter.
Definition at line 483 of file abstractBuffer.h.
Referenced by corecvs::Morphological::dilate(), corecvs::RGB24Buffer::drawIsolines(), corecvs::Morphological::erode(), TestbedMainWindow::loadImage(), corecvs::BinarizeBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::SobelFilter::operator()(), BaseCalculationThread::recalculateCache(), TestbedMainWindow::resetMask(), and corecvs::BMPLoader::save().
    {
        return Vector2d<IndexType>(w, h);
    }
template<typename ElementType, typename IndexType = int32_t> IndexType corecvs::AbstractBuffer< ElementType, IndexType >::getStride () const [inline, inherited]
Stride getter.
Definition at line 467 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::AbstractBuffer< SegmentType * >::load().
    {
        return stride;
    }
template<typename ElementType, typename IndexType = int32_t> IndexType corecvs::AbstractBuffer< ElementType, IndexType >::getW () const [inline, inherited]
Width getter.
Definition at line 475 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::G12Buffer::G12Buffer(), corecvs::G12Buffer3d::G12Buffer3d(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::IntegralBuffer(), corecvs::PolynomInterpolator::interpolate(), corecvs::G12Buffer::isValidCoordBlPrecomp(), corecvs::FlowBuffer::load(), corecvs::AbstractBuffer< SegmentType * >::load(), corecvs::Matrix::notTooFar(), and corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::operator()().
    {
        return w;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::hasSameSize (const AbstractBuffer< ElementType, IndexType > * other) const [inline, inherited]
Checks if this buffer has the same size as the other.
Definition at line 443 of file abstractBuffer.h.
Referenced by corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), corecvs::G12Buffer::operator=(), and BaseCalculationThread::recalculateCache().
    {
        return (this->h == other->h) && (this->w == other->w);
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::hasSameSize (const IndexType & otherH, const IndexType & otherW) const [inline, inherited]
Checks if this buffer has the same size as the parameters given.
Definition at line 451 of file abstractBuffer.h.
    {
        return (this->h == otherH) && (this->w == otherW);
    }
template<typename ElementType, typename IndexType = int32_t> template<typename ReturnType , typename ConvElementType , typename ConvIndexType > void corecvs::AbstractBuffer< ElementType, IndexType >::innerCycleDoConvolve (ReturnType * toReturn, AbstractKernel< ConvElementType, ConvIndexType > * kernel, int i) [inline, inherited]
Definition at line 659 of file abstractBuffer.h.
    {
        for (IndexType j = 0; j < w; j++)
        {
            toReturn->element(i,j) =  kernel->template multiplyAtPoint<ElementType, IndexType>(this, i,j);
        }
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isAllocated () const [inline, inherited]
Checking for successfull allocation.
Definition at line 491 of file abstractBuffer.h.
    {
        return data != NULL;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isEqual (const AbstractBuffer< ElementType, IndexType > & that) const [inline, inherited]
This method tests for equality.
Definition at line 769 of file abstractBuffer.h.
Referenced by corecvs::Matrix::operator==().
    {
        if (that.h != this->h || that.w != this->w)
            return false;
        for (int i = 0; i < this->h; i++)
        {
            const ElementType *thisElemRunner = &(this->element(i,0));
            const ElementType *thatElemRunner = &(that.element(i,0));
            for (int j = 0; j < this->w; j++)
            {
                if (*thatElemRunner != *thisElemRunner)
                {
#ifdef ASSERTS
                  printf("Buffers have equal sizes [h=%d w=%d]\n", this->h, this->w);
                    printf("[ 0x");
                    for (size_t k = 0; k < sizeof(ElementType); k++)
                        printf("%02X ", ((uint8_t *)(void*)(thisElemRunner))[k]);
                    printf("] vs [ 0x");
                    for (size_t k = 0; k < sizeof(ElementType); k++)
                        printf("%02X ", ((uint8_t *)(void*)(thatElemRunner))[k]);
                    printf("]\nPos y=%d x=%d\n", i , j);
                    ASSERT_FAIL_P(("Buffers don't match"));
#endif
                    return false;
                }
                thatElemRunner++;
                thisElemRunner++;
            }
        }
        return true;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isEqualTrace (const AbstractBuffer< ElementType, IndexType > & that) const [inline, inherited]
Definition at line 802 of file abstractBuffer.h.
    {
        if (that.h != this->h || that.w != this->w)
            return false;
        int diffs = 0;
        for (int i = 0; i < this->h; i++)
        {
            const ElementType *thisElemRunner = &(this->element(i,0));
            const ElementType *thatElemRunner = &(that.element(i,0));
            for (int j = 0; j < this->w; j++)
            {
                if (*thatElemRunner != *thisElemRunner)
                {
                    cout << "Differ Pos y="<< i << " x=" << j << " ";
                    cout << "Fst = " <<  *thisElemRunner << " sec= " << *thatElemRunner << endl;
                    diffs++;
                }
                thatElemRunner++;
                thisElemRunner++;
            }
        }
        cout << "Totally " << diffs << " diffs" << endl;
        return diffs == 0;
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord (const IndexType y, const IndexType x) const [inline, inherited]
Checks if coordinate lies within the buffer area.
Definition at line 427 of file abstractBuffer.h.
Referenced by corecvs::Buffer3d::addPoints(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::Clustering3D::clustering(), corecvs::RGB24Buffer::drawArc(), corecvs::RGB24Buffer::drawArc1(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawPixel(), corecvs::Buffer3d::getNearestPoint(), corecvs::FlowBuffer::invert(), corecvs::Buffer3d::isElementValidAndKnown(), corecvs::FlowBuffer::isElementValidAndKnown(), corecvs::AbstractBuffer< SegmentType * >::isValidCoord(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::FlowBuffer::load(), TestbedMainWindow::maskTolerance(), TestbedMainWindow::maskTolerance1(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), TestbedMainWindow::recursiveTolerance(), and TestbedMainWindow::updateViewImage().
    {
        return (x >= 0) && (x < w) && (y >= 0) && (y < h);
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::isValidCoord (const Vector2d< IndexType > & p) const [inline, inherited]
Checks if coordinate lies within the buffer area.
Definition at line 435 of file abstractBuffer.h.
    {
        return isValidCoord(p.y(), p.x());
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractContiniousBuffer< ElementType, IndexType >::isValidCoordBl (double y, double x) const [inline, inherited]
Checks if coordinate lies within the buffer area.
Parameters:
y The y coordinate of the point to check
x The x coordinate of the point to check
Definition at line 276 of file abstractContiniousBuffer.h.
Referenced by corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::AbstractContiniousBuffer< double, int >::elementBlInt(), corecvs::Splain3Interpolator::interpolate(), corecvs::BilinearInterpolator::interpolate(), corecvs::PolynomInterpolator::interpolate(), corecvs::AbstractContiniousBuffer< double, int >::isValidCoordBl(), and corecvs::KLTGenerator< InterpolationType >::kltIteration().
    {
        /*return (floor(x) >= 0) && (ceil(x) < this->w) &&
                 (floor(y) >= 0) && (ceil(y) < this->h);*/
        return (floor(x) >= 0) && (floor(x) + 1.0 < this->w) &&
               (floor(y) >= 0) && (floor(y) + 1.0 < this->h);
    }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractContiniousBuffer< ElementType, IndexType >::isValidCoordBl (const Vector2dd & p) const [inline, inherited]
Checks if coordinate lies within the buffer area.
Definition at line 287 of file abstractContiniousBuffer.h.
    {
        return isValidCoordBl(p.y(), p.x());
    }
bool_t corecvs::AbstractBufferParams::load (istream & s, int & h, int & w, int & stride, uint elemSize, bool_t binaryMode) [static, protected, inherited]
Definition at line 33 of file abstractBuffer.cpp.
References corecvs::AbstractBufferParams::read(), corecvs::read_integer_bin(), and corecvs::sFormatStr.
Referenced by corecvs::AbstractBuffer< SegmentType * >::load().
{
    int width, stridePix, height, elSize;
    size_t pos = s.tellg();
    if (binaryMode)
    {
        read_integer_bin(s, width);
        read_integer_bin(s, stridePix);
        read_integer_bin(s, height);
        read_integer_bin(s, elSize);
    }
    else
    {
        char buf[256];
        read(s, buf, binaryMode);
        if (sscanf(buf, sFormatStr, &width, &stridePix, &height, &elSize) != 4)
            elSize = 0;
    }
    if ((uint)elSize != elemSize)
    {
        s.seekg(pos);                                       // restore pos
        return false;
    }
    h      = height;
    w      = width;
    stride = stridePix;
    return true;
}
bool_t corecvs::AbstractBufferParams::load (istream & s, uint elemSize, bool_t binaryMode) [inline, protected, inherited]
Definition at line 153 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::h, corecvs::AbstractBufferParams::load(), corecvs::AbstractBufferParams::stride, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::AbstractBufferParams::load().
{ return load(s, h, w, stride, elemSize, binaryMode); }
template<typename ElementType, typename IndexType = int32_t> bool corecvs::AbstractBuffer< ElementType, IndexType >::load (istream & s, bool binaryMode) [inline, inherited]
Definition at line 920 of file abstractBuffer.h.
Referenced by corecvs::BufferFactory::loadG12Bitmap().
    {
        if (!AbstractBufferParams::load(s, sizeof(ElementType), binaryMode))
            return false;
        _init(getH(), getW(), getStride(), false);
        if (!binaryMode)
            return true;                                    // loading in text mode is outside
        s.read((char *)data, sizeInBytes());
        return !s.bad();
    }
template<typename ElementType, typename IndexType = int32_t> template<typename operation > void corecvs::AbstractBuffer< ElementType, IndexType >::mapOperationElementwize (const operation & map) [inline, inherited]
Definition at line 869 of file abstractBuffer.h.
Referenced by BitSelector::filter(), GainOffset::filter(), corecvs::G12Buffer::gainOffset(), corecvs::G12Buffer::intervalMap(), corecvs::BitSelectorFilter::operator()(), corecvs::GainOffsetFilter::operator()(), and corecvs::G12Buffer::shiftMask().
    {
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElementRunner = &(this->element(i,0));
            for (IndexType j = 0; j < w; j++)
            {
                *thisElementRunner = map.operator()(*thisElementRunner);
                thisElementRunner++;
            }
        }
    }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::mirrorVertical () [inline, inherited]
Mirrors current buffer vertically.
Definition at line 950 of file abstractBuffer.h.
  {
      for (IndexType i = 0; i < h / 2; i++)
      {
          memcpy(&(this->element(h - 1 - i, 0)), &(this->element(i, 0)), w * sizeof(ElementType));
      }
  }
template<typename ElementType, typename IndexType = int32_t> template<typename OtherType > OtherType* corecvs::AbstractBuffer< ElementType, IndexType >::mirrorVertical () [inline, inherited]
Definition at line 978 of file abstractBuffer.h.
    {
        OtherType *toReturn = new OtherType(this->h, this->w);
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElemRunner = &(this->element(i,0));
            typename OtherType::InternalElementType *thatElemRunner = &(toReturn->element(h - 1 - i,0));
            for (IndexType j = 0; j < w; j++)
            {
                *thatElemRunner = *thisElemRunner;
                thatElemRunner++;
                thisElemRunner++;
            }
        }
        return toReturn;
    }
template<typename ElementType, typename IndexType = int32_t> template<typename OtherType > OtherType* corecvs::AbstractBuffer< ElementType, IndexType >::mirrorVerticalDump () [inline, inherited]
Please check that you really don't want to invoke the copy constructor.
Definition at line 939 of file abstractBuffer.h.
    {
        OtherType *toReturn = new OtherType(this->h, this->w);
        for (IndexType i = 0; i < h; i++)
        {
            memcpy(&(toReturn->element(h - 1 - i, 0)), &(this->element(i, 0)), w * sizeof(ElementType));
        }
        return toReturn;
    }
int corecvs::AbstractBufferParams::numElements () const [inline, inherited]
Calculate number of elements in a buffer.
Definition at line 124 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::stride.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::sizeInBytes(), and corecvs::AbstractBuffer< SegmentType * >::~AbstractBuffer().
{ return h * stride; }
bool_t corecvs::AbstractBufferParams::read (istream & s, int & val, bool_t binaryMode) [static, protected, inherited]
Definition at line 78 of file abstractBuffer.cpp.
References corecvs::read_integer_bin().
Referenced by corecvs::RGB24Buffer::fillWithYUYV(), corecvs::FlowBuffer::load(), corecvs::AbstractBufferParams::load(), and corecvs::RGB24Buffer::toG12Buffer().
{
    int value;
    size_t pos = s.tellg();
    if (binaryMode)
    {
        read_integer_bin(s, value);
    }
    else
    {
        s >> value;
    }
    if (s.bad())
    {
        s.seekg(pos);                                       // restore pos
        return false;
    }
    val = value;
    return true;
}
bool_t corecvs::AbstractBufferParams::read (istream & s, char * str, size_t size, bool_t binaryMode) [static, protected, inherited]
Definition at line 109 of file abstractBuffer.cpp.
References CORE_COUNT_OF, and CORE_UNUSED.
{
    if (str != NULL && size) {
        s.getline(str, size);                               // read one line to the output buffer
    }
    else {
        char buf[256];
        s.getline(buf, CORE_COUNT_OF(buf));                 // skip one line
    }
    CORE_UNUSED(binaryMode);
    return !s.bad();
}
template<size_t size> static bool_t corecvs::AbstractBufferParams::read (istream & s, char(&) str[size], bool_t binaryMode) [inline, static, protected, inherited]
Definition at line 150 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::read().
Referenced by corecvs::AbstractBufferParams::read().
{ return read(s, (char*)str, size, binaryMode); }
template<typename ElementType, typename IndexType = int32_t> void corecvs::AbstractBuffer< ElementType, IndexType >::rotate180 () [inline, inherited]
Rotates current buffer 180 degrees.
Definition at line 959 of file abstractBuffer.h.
  {
      for (IndexType i = 0; i < h / 2; i++)
      {
            ElementType *thisElemRunner = &(this->element(i, 0));
            ElementType *thatElemRunner = &(this->element(h - 1 - i, w - 1));
            for (IndexType j = 0; j < w; j++)
            {
                ElementType tmp = *thisElemRunner;
                *thisElemRunner = *thatElemRunner;
                *thatElemRunner = tmp;
                thatElemRunner--;
                thisElemRunner++;
            }
      }
  }
void corecvs::AbstractBufferParams::setH (int _h) [inline, protected, inherited]
Definition at line 137 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
{ h      = _h; }
void corecvs::AbstractBufferParams::setStride (int _s) [inline, protected, inherited]
Definition at line 139 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::stride.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
{ stride = _s; }
void corecvs::AbstractBufferParams::setW (int _w) [inline, protected, inherited]
Definition at line 138 of file abstractBuffer.h.
References corecvs::AbstractBufferParams::w.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
{ w      = _w; }
template<typename ElementType, typename IndexType = int32_t> size_t corecvs::AbstractBuffer< ElementType, IndexType >::sizeInBytes () const [inline, inherited]
Calculate image buffer size in bytes.
Definition at line 499 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::AbstractBuffer< SegmentType * >::dump(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), and corecvs::AbstractBuffer< SegmentType * >::load().
    {
      //return _allocatedSize;
        return this->numElements() * sizeof(ElementType);
    }
template<typename ElementType, typename IndexType = int32_t> template<typename operation > void corecvs::AbstractBuffer< ElementType, IndexType >::touchOperationElementwize (operation & map) [inline, inherited]
Definition at line 883 of file abstractBuffer.h.
Referenced by corecvs::CorrespondanceList::CorrespondanceList().
    {
        for (IndexType i = 0; i < h; i++)
        {
            ElementType *thisElemRunner = &(this->element(i,0));
            for (IndexType j = 0; j < w; j++)
            {
                map.operator()(i, j, *thisElemRunner);
                thisElemRunner++;
            }
        }
    }
bool_t corecvs::AbstractBufferParams::write (ostream & s, int val, bool_t binaryMode) [static, protected, inherited]
Definition at line 65 of file abstractBuffer.cpp.
References corecvs::write_integer_bin().
Referenced by corecvs::RGB24Buffer::fillWithYUYV().
{
    if (binaryMode)
    {
        write_integer_bin(s, val);
    }
    else
    {
        s << val << ' ';
    }
    return !s.bad();
}
bool_t corecvs::AbstractBufferParams::write (ostream & s, cchar * str, bool_t binaryMode) [static, protected, inherited]
Definition at line 102 of file abstractBuffer.cpp.
References CORE_UNUSED.
{
    s << str << endl;
    CORE_UNUSED(binaryMode);
    return !s.bad();
}
Friends And Related Function Documentation
template<typename ElementType, typename IndexType = int32_t> ostream& operator<< (ostream & out, const AbstractBuffer< ElementType, IndexType > & buffer) [friend, inherited]
Definition at line 896 of file abstractBuffer.h.
    {
        // typedef AbstractBuffer::InternalIndexType IndexType;
        //
        for (IndexType i = 0; i < buffer.h; i++)
        {
           for (IndexType j = 0; j < buffer.w; j++)
           {
               out << buffer.element(i, j) << " ";
           }
           out << endl;
        }
        return out;
    }
Member Data Documentation
template<typename ElementType, typename IndexType = int32_t> int corecvs::AbstractBuffer< ElementType, IndexType >::bufferCount = 0 [static, inherited]
Static member that will be used to prevent and debug memory leaks.
Counter for memory profiling.
Definition at line 191 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), and corecvs::AbstractBuffer< SegmentType * >::~AbstractBuffer().
template<typename ElementType, typename IndexType = int32_t> ElementType* corecvs::AbstractBuffer< ElementType, IndexType >::data [inherited]
Sometimes underling buffer should not be deleted.
The properly aligned pointer to an array with data elements, memory of which is kept by the protected field "memoryBlock"
Reimplemented in corecvs::SobelHorInt, corecvs::Gaussian3x3int, corecvs::SobelVertInt, and corecvs::Gaussian3x3.
Definition at line 228 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::LevenMarq::dist(), corecvs::LevenMarq::doLevMarFit(), corecvs::AbstractBuffer< SegmentType * >::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::G12Buffer::fillWithYUYV(), corecvs::AbstractBuffer< SegmentType * >::isAllocated(), corecvs::AbstractBuffer< SegmentType * >::load(), corecvs::G12Buffer::operator=(), and corecvs::AbstractBuffer< SegmentType * >::~AbstractBuffer().
template<typename ElementType, typename IndexType = int32_t> const int corecvs::AbstractBuffer< ElementType, IndexType >::DATA_ALIGN_GRANULARITY = 0xF [static, inherited]
This constant represents the default alignment of the line in the buffer.
It is 16 bytes now to work with SSE and possibly with OPENCL.
Definition at line 185 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_getStride(), and corecvs::AbstractBuffer< SegmentType * >::_init().
const int16_t corecvs::DisparityBuffer::DISPARITY_UNKNOWN = INT16_MAX [static]
Definition at line 25 of file disparityBuffer.h.
template<typename ElementType, typename IndexType = int32_t> BufferType corecvs::AbstractBuffer< ElementType, IndexType >::flags [protected, inherited]
Definition at line 1006 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
int corecvs::AbstractBufferParams::h [inherited]
Definition at line 127 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::EllipticalApproximationUnified< Vector3dd >::addPoint(), corecvs::VJSimpleClassifier::applyToPoint(), corecvs::G12Buffer::binarize(), corecvs::AbstractBuffer< SegmentType * >::binaryOperationInPlace(), corecvs::BooleanBuffer::BooleanBuffer(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), corecvs::ClassicKalman::ClassicKalman(), corecvs::Clustering3D::clustering(), corecvs::COOSparseMatrix::COOSparseMatrix(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::DerivativeBuffer::DerivativeBuffer(), corecvs::Matrix::detSVD(), corecvs::G12Buffer::difference(), corecvs::DisplacementBuffer::DisplacementBuffer(), corecvs::AbstractBuffer< SegmentType * >::doConvolve(), corecvs::AbstractBuffer< SegmentType * >::doConvolve1(), corecvs::DistortionCorrectTransform::doCorrectionTransform(), corecvs::RadialCorrection::doCorrectionTransform(), DistortionWidget::doDefaultTransform(), corecvs::TransformationCache::doDeformation(), DistortionWidget::doInversionTransform(), DistortionWidget::doLinesTransform(), DistortionWidget::doManualTransform(), DistortionWidget::doTransformLM(), FlowDrawer::draw(), FlowDrawer::drawBigDotsFast(), FlowDrawer::drawDotsFast(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer2(), corecvs::RGB24Buffer::drawFlowBuffer3(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawG12Buffer(), corecvs::RGB24Buffer::drawG8Buffer(), corecvs::RGB24Buffer::drawIsolines(), corecvs::RGB24Buffer::drawLine(), corecvs::RGB24Buffer::drawLineSimple(), corecvs::FlowBuffer::dump(), corecvs::AbstractBufferParams::dump(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::AbstractContiniousBuffer< double, int >::elementBlInt(), BaseCalculationThread::executeFilterGraph(), corecvs::AbstractBuffer< SegmentType * >::fillRectangleWith(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillWithRands(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::RGB24Buffer::fillWithYUYV(), corecvs::G12Buffer::fillWithYUYV(), ScaleFilter::filter(), corecvs::SpatialGradient::findCornerPoints(), corecvs::LevenbergMarquardt::fit(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), corecvs::Matrix::frobeniusNorm(), corecvs::G8Buffer::FromG12Buffer(), corecvs::G12Buffer::G12Buffer(), G12Image::G12Image(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::getEffectiveH(), corecvs::EllipticalApproximationUnified< Vector3dd >::getEllipseParameters(), corecvs::AbstractBuffer< SegmentType * >::getH(), corecvs::FlowBuffer::getMeanDifference(), corecvs::AbstractBuffer< SegmentType * >::getSize(), corecvs::DerivativeBuffer::gradientMagnitudeBuffer(), corecvs::AbstractBuffer< SegmentType * >::hasSameSize(), corecvs::Histogram::Histogram(), PointsRectificationWidget::initCorrespondancePoints(), CloudViewDialog::initializeGLSlot(), corecvs::Splain3Interpolator::interpolate(), corecvs::BilinearInterpolator::interpolate(), corecvs::Matrix::inv(), corecvs::FlowBuffer::invert(), corecvs::Matrix::invSVD(), corecvs::AbstractBuffer< SegmentType * >::isEqual(), corecvs::AbstractBuffer< SegmentType * >::isEqualTrace(), corecvs::AbstractBuffer< SegmentType * >::isValidCoord(), corecvs::AbstractContiniousBuffer< double, int >::isValidCoordBl(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::AbstractBufferParams::load(), TestbedMainWindow::loadImage(), corecvs::AbstractBuffer< SegmentType * >::mapOperationElementwize(), TestbedMainWindow::maskHue(), corecvs::Matrix::matrixSolveGaussian(), DirectShowCaptureInterface::memberCallback(), corecvs::AbstractBuffer< SegmentType * >::mirrorVertical(), corecvs::AbstractBuffer< SegmentType * >::mirrorVerticalDump(), corecvs::Matrix::mul(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), corecvs::Matrix::negative(), corecvs::DerivativeBuffer::nonMaximalSuppression(), corecvs::Matrix::notTooFar(), corecvs::AbstractBufferParams::numElements(), corecvs::BinarizeBlock::operator()(), corecvs::ThickeningBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::SobelFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::operator*(), corecvs::operator*=(), corecvs::operator+(), corecvs::operator-(), corecvs::operator<<(), corecvs::Buffer3d::pointInBox(), corecvs::FloatFlowBuffer::preciseFlowCalc(), corecvs::BlurProcessor::prepareBlurBuffers(), corecvs::ErodeKernel< Algebra >::process(), corecvs::DilateKernel< Algebra >::process(), BaseCalculationThread::recalculateCache(), corecvs::CannyFilter::recursiveEdgeProver(), corecvs::DirectRemapper::remap(), DistortionWidget::resetParameters(), RGB24Image::RGB24Image(), corecvs::AbstractBuffer< SegmentType * >::rotate180(), corecvs::PPMLoader::save(), corecvs::BMPLoader::save(), corecvs::PPMLoader::saveG16(), corecvs::TileGrid::selectWithThreshold(), corecvs::AbstractBufferParams::setH(), DistortionWidget::showBufferChanged(), corecvs::SixDBuffer::SixDBuffer(), corecvs::SpatialGradient::SpatialGradient(), corecvs::Matrix::svd(), corecvs::Matrix::t(), corecvs::RGB24Buffer::toG12Buffer(), corecvs::AbstractBuffer< SegmentType * >::touchOperationElementwize(), corecvs::FlowBuffer::toVectorForm(), corecvs::Matrix::trace(), BaseCalculationThread::transformInputFrames(), corecvs::Matrix::transpose(), corecvs::Matrix::transposed(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateToDB(), corecvs::Cholesky::udutDecompose(), DistortionWidget::updateAdditionalData(), TestbedMainWindow::updateViewImage(), and corecvs::G12Buffer::verify().
int32_t corecvs::DisparityBuffer::maxValue
Definition at line 27 of file disparityBuffer.h.
template<typename ElementType, typename IndexType = int32_t> MemoryBlockRef corecvs::AbstractBuffer< ElementType, IndexType >::memoryBlock [protected, inherited]
The beginning of the allocated memory.
Definition at line 1004 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init(), and corecvs::AbstractBuffer< SegmentType * >::createView().
int corecvs::AbstractBufferParams::stride [inherited]
Definition at line 129 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::AbstractBufferParams::dump(), corecvs::AbstractBuffer< SegmentType * >::element(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::G12Buffer::fillWithYUYV(), corecvs::AbstractBuffer< SegmentType * >::getStride(), CloudViewDialog::initializeGLSlot(), corecvs::AbstractBufferParams::load(), corecvs::AbstractBufferParams::numElements(), and corecvs::AbstractBufferParams::setStride().
template<typename ElementType, typename IndexType = int32_t> const IndexType corecvs::AbstractBuffer< ElementType, IndexType >::STRIDE_AUTO = (IndexType)0 [static, inherited]
The height of the buffer.
Todo:
TODO: This field is public do far, but that is dangerous.
The width of the buffer The stride of the buffer
Todo:
TODO: This field is public do far, but that is dangerous.
TODO: Could happen it would be nice to have this in bytes The given stride value to have automatically chosen stride of the buffer
Definition at line 216 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_init().
cchar corecvs::AbstractBufferParams::TAB = '\t' [static, inherited]
Definition at line 131 of file abstractBuffer.h.
Referenced by corecvs::FlowBuffer::dump().
int corecvs::AbstractBufferParams::w [inherited]
Definition at line 128 of file abstractBuffer.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::_getStride(), corecvs::AbstractBuffer< SegmentType * >::AbstractBuffer(), corecvs::EllipticalApproximationUnified< Vector3dd >::addPoint(), corecvs::VJSimpleClassifier::applyToPoint(), corecvs::G12Buffer::binarize(), corecvs::AbstractBuffer< SegmentType * >::binaryOperationInPlace(), corecvs::BooleanBuffer::BooleanBuffer(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), corecvs::ClassicKalman::ClassicKalman(), corecvs::Clustering3D::clustering(), corecvs::COOSparseMatrix::COOSparseMatrix(), corecvs::AbstractBuffer< SegmentType * >::createView(), corecvs::DerivativeBuffer::DerivativeBuffer(), corecvs::Matrix::detSVD(), corecvs::G12Buffer::difference(), corecvs::DisplacementBuffer::DisplacementBuffer(), corecvs::AbstractBuffer< SegmentType * >::doConvolve(), corecvs::AbstractBuffer< SegmentType * >::doConvolve1(), corecvs::DistortionCorrectTransform::doCorrectionTransform(), corecvs::RadialCorrection::doCorrectionTransform(), DistortionWidget::doDefaultTransform(), corecvs::TransformationCache::doDeformation(), DistortionWidget::doInversionTransform(), DistortionWidget::doLinesTransform(), DistortionWidget::doManualTransform(), DistortionWidget::doTransformLM(), FlowDrawer::draw(), FlowDrawer::drawBigDotsFast(), FlowDrawer::drawDotsFast(), corecvs::RGB24Buffer::drawFlowBuffer(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer2(), corecvs::RGB24Buffer::drawFlowBuffer3(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawG12Buffer(), corecvs::RGB24Buffer::drawG8Buffer(), corecvs::RGB24Buffer::drawIsolines(), corecvs::RGB24Buffer::drawLine(), corecvs::RGB24Buffer::drawLineSimple(), corecvs::FlowBuffer::dump(), corecvs::AbstractBufferParams::dump(), corecvs::AbstractContiniousBuffer< double, int >::elementBl(), corecvs::AbstractContiniousBuffer< double, int >::elementBlFast(), corecvs::AbstractContiniousBuffer< double, int >::elementBlInt(), BaseCalculationThread::executeFilterGraph(), corecvs::AbstractBuffer< SegmentType * >::fillLineWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillRectangleWith(), corecvs::AbstractBuffer< SegmentType * >::fillWith(), corecvs::AbstractBuffer< SegmentType * >::fillWithArgs(), corecvs::AbstractBuffer< SegmentType * >::fillWithRands(), corecvs::AbstractBuffer< SegmentType * >::fillWithRaw(), corecvs::RGB24Buffer::fillWithYUYV(), corecvs::G12Buffer::fillWithYUYV(), ScaleFilter::filter(), corecvs::SpatialGradient::findCornerPoints(), corecvs::FixedPointDisplace::FixedPointDisplace(), corecvs::FloatFlowBuffer::FloatFlowBuffer(), corecvs::Matrix::frobeniusNorm(), corecvs::G8Buffer::FromG12Buffer(), corecvs::G12Buffer::G12Buffer(), G12Image::G12Image(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::getEffectiveW(), corecvs::EllipticalApproximationUnified< Vector3dd >::getEllipseParameters(), corecvs::FlowBuffer::getMeanDifference(), corecvs::AbstractBuffer< SegmentType * >::getSize(), corecvs::ErodeKernel< Algebra >::getSizeX(), corecvs::DilateKernel< Algebra >::getSizeX(), corecvs::AbstractBuffer< SegmentType * >::getW(), corecvs::DerivativeBuffer::gradientMagnitudeBuffer(), corecvs::AbstractBuffer< SegmentType * >::hasSameSize(), corecvs::Histogram::Histogram(), PointsRectificationWidget::initCorrespondancePoints(), CloudViewDialog::initializeGLSlot(), corecvs::AbstractBuffer< SegmentType * >::innerCycleDoConvolve(), corecvs::Splain3Interpolator::interpolate(), corecvs::BilinearInterpolator::interpolate(), corecvs::Matrix::inv(), corecvs::FlowBuffer::invert(), corecvs::Matrix::invSVD(), corecvs::AbstractBuffer< SegmentType * >::isEqual(), corecvs::AbstractBuffer< SegmentType * >::isEqualTrace(), corecvs::AbstractContiniousBuffer< double, int >::isValidCoordBl(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::AbstractBufferParams::load(), TestbedMainWindow::loadImage(), corecvs::AbstractBuffer< SegmentType * >::mapOperationElementwize(), TestbedMainWindow::maskHue(), corecvs::Matrix::matrixSolveGaussian(), DirectShowCaptureInterface::memberCallback(), corecvs::AbstractBuffer< SegmentType * >::mirrorVertical(), corecvs::AbstractBuffer< SegmentType * >::mirrorVerticalDump(), corecvs::Matrix::mul(), corecvs::AbstractKernel< int32_t, uint32_t >::multiplyAtPoint(), corecvs::Matrix::negative(), corecvs::DerivativeBuffer::nonMaximalSuppression(), corecvs::Matrix::notTooFar(), corecvs::ThickeningBlock::operator()(), corecvs::BinarizeBlock::operator()(), corecvs::MaskFilterBlock::operator()(), corecvs::BackgroundFilter::operator()(), corecvs::ParallelPrepareBlurBuffers::operator()(), corecvs::SobelFilter::operator()(), corecvs::CannyFilter::operator()(), corecvs::AbstractBuffer< ElementType, IndexType >::ParallelDoConvolve1< ReturnType, ConvElementType, ConvIndexType >::operator()(), corecvs::operator*(), corecvs::operator*=(), corecvs::operator+(), corecvs::operator-(), corecvs::operator<<(), corecvs::Buffer3d::pointInBox(), corecvs::FloatFlowBuffer::preciseFlowCalc(), corecvs::BlurProcessor::prepareBlurBuffers(), corecvs::ErodeKernel< Algebra >::process(), corecvs::DilateKernel< Algebra >::process(), BaseCalculationThread::recalculateCache(), corecvs::CannyFilter::recursiveEdgeProver(), corecvs::DirectRemapper::remap(), DistortionWidget::resetParameters(), RGB24Image::RGB24Image(), corecvs::AbstractBuffer< SegmentType * >::rotate180(), corecvs::PPMLoader::save(), corecvs::BMPLoader::save(), corecvs::PPMLoader::saveG16(), corecvs::TileGrid::selectWithThreshold(), corecvs::AbstractBufferParams::setW(), DistortionWidget::showBufferChanged(), corecvs::SixDBuffer::SixDBuffer(), corecvs::SpatialGradient::SpatialGradient(), corecvs::Matrix::svd(), corecvs::Matrix::t(), corecvs::RGB24Buffer::toG12Buffer(), corecvs::AbstractBuffer< SegmentType * >::touchOperationElementwize(), corecvs::FlowBuffer::toVectorForm(), corecvs::Matrix::trace(), BaseCalculationThread::transformInputFrames(), corecvs::Matrix::transpose(), corecvs::Matrix::transposed(), corecvs::Triangulator::triangulate(), corecvs::Triangulator::triangulateToDB(), DistortionWidget::updateAdditionalData(), TestbedMainWindow::updateViewImage(), and corecvs::G12Buffer::verify().
The documentation for this class was generated from the following file:
core/buffers/disparityBuffer.h