DeepView: corecvs::VJPattern Class Reference
corecvs::VJPattern Class Reference
Viola-Jones generic Haar wavelet.
#include <vjPattern.h>
Public Member Functions
VJPattern ()
virtual ~VJPattern ()
int applyToPoint (G12IntegralBuffer *buffer, int y, int x)
void addPoint (const PatternCorner &corner)
void addRectangle (int x1, int y1, int x2, int y2, int multipiler)
void print ()
VJPattern * scale (double scale)
Public Attributes
vector< PatternCorner > points
Friends
ostream & operator<< (ostream &out, VJPattern &toSave)
istream & operator>> (istream &in, VJPattern &toLoad)
Detailed Description
Viola-Jones generic Haar wavelet.
Definition at line 72 of file vjPattern.h.
Constructor & Destructor Documentation
corecvs::VJPattern::VJPattern ()
Definition at line 17 of file vjPattern.cpp.
{
}
corecvs::VJPattern::~VJPattern () [virtual]
Definition at line 21 of file vjPattern.cpp.
{
}
Member Function Documentation
void corecvs::VJPattern::addPoint (const PatternCorner & corner) [inline]
Definition at line 90 of file vjPattern.h.
References corecvs::PatternCorner::multiplier, and corecvs::PatternCorner::point.
    {
        vector<PatternCorner>::iterator it;
        for (it = points.begin(); it != points.end(); it++)
        {
            if ((*it).point == corner.point)
            {
                (*it).multiplier += corner.multiplier;
                return;
            }
        }
        points.push_back(corner);
    }
void corecvs::VJPattern::addRectangle (int x1, int y1, int x2, int y2, int multipiler) [inline]
Definition at line 105 of file vjPattern.h.
Referenced by corecvs::HorizontalPattern2::pattern(), corecvs::HorizontalPattern3::pattern(), corecvs::VerticalPattern2::pattern(), corecvs::VerticalPattern3::pattern(), and corecvs::SquarePattern2::pattern().
    {
        int tmp;
        if (x1 > x2) {tmp = x1; x1 = x2; x2 = tmp;};
        if (y1 > y2) {tmp = y1; y1 = y2; y2 = tmp;};
        addPoint(PatternCorner(x2, y2,  multipiler));
        addPoint(PatternCorner(x1, y1,  multipiler));
        addPoint(PatternCorner(x2, y1, -multipiler));
        addPoint(PatternCorner(x1, y2, -multipiler));
    }
int corecvs::VJPattern::applyToPoint (G12IntegralBuffer * buffer, int y, int x) [inline]
Definition at line 79 of file vjPattern.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::PatternCorner::multiplier, and corecvs::PatternCorner::point.
Referenced by corecvs::ParallelGetBestClassifier::operator()().
    {
        int sum = 0;
        for (unsigned i = 0; i < points.size(); i++)
        {
            PatternCorner *pc = &(points[i]);
            sum += pc->multiplier * buffer->element(pc->point + Vector2d32(x,y));
        }
        return sum;
    }
void corecvs::VJPattern::print () [inline]
Definition at line 129 of file vjPattern.h.
    {
        cout << this;
    }
VJPattern* corecvs::VJPattern::scale (double scale) [inline]
TODO: A correction should be applied.
Definition at line 150 of file vjPattern.h.
References corecvs::fround(), corecvs::PatternCorner::multiplier, corecvs::PatternCorner::point, points, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::VJSimpleClassifier::scale().
    {
        VJPattern *toReturn = new VJPattern();
        /**
         * TODO: A correction should be applied.
         **/
        for (unsigned i = 0; i < points.size(); i++)
        {
            PatternCorner *oldCorner = &(points.at(i));
            int x = fround(oldCorner->point.x() * scale);
            int y = fround(oldCorner->point.y() * scale);
            PatternCorner corner(Vector2d32(x,y), oldCorner->multiplier);
            toReturn->points.push_back(corner);
        }
        return toReturn;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, VJPattern & toSave) [friend]
Definition at line 117 of file vjPattern.h.
    {
        //const vector<PatternCorner>::iterator it;
        out << toSave.points.size() << "\n";
        for (unsigned i = 0; i <= toSave.points.size(); i++)
        {
            PatternCorner *corner = &(toSave.points[i]);
            out << corner->point.x() << " "<< corner->point.y() << "  " << corner->multiplier << "\n";
        }
        return out;
    }
istream& operator>> (istream & in, VJPattern & toLoad) [friend]
Definition at line 134 of file vjPattern.h.
    {
        toLoad.points.clear();
        unsigned int size;
        in >> size;
        for (unsigned i = 0; i < size; i++)
        {
            int x;
            int y;
            int mul;
            in >> x >> y >> mul;
            toLoad.addPoint(PatternCorner(x,y,mul));
        }
        return in;
    }
Member Data Documentation
vector<PatternCorner> corecvs::VJPattern::points
Definition at line 75 of file vjPattern.h.
Referenced by scale().
The documentation for this class was generated from the following files:
core/boosting/vjPattern.h
core/boosting/vjPattern.cpp