DeepView: corecvs::GenericQuaternion< ElementType > Class Template Reference
corecvs::GenericQuaternion< ElementType > Class Template Reference
#include <quaternion.h>
Public Types
typedef ElementType InnerElementType
typedef ReflectionHelper
< ElementType >::Type ReflectionType
Public Member Functions
GenericQuaternion (const GenericQuaternion &Q)
GenericQuaternion (const ElementType &_x, const ElementType &_y, const ElementType &_z, const ElementType &_t)
GenericQuaternion (const BaseClass &V)
GenericQuaternion (const ElementType &x)
GenericQuaternion ()
ElementType & x ()
ElementType & y ()
ElementType & z ()
ElementType & t ()
VectorType v () const
const ElementType & x () const
const ElementType & y () const
const ElementType & z () const
const ElementType & t () const
GenericQuaternion conjugated () const
GenericQuaternion (const VectorType &axis, const ElementType &alpha)
TODO: Add -.
Matrix33 toMatrix () const
This function is a reworked function form somewhere in Internet.
double getAngle () const
NB - this function expects normalized quaternion as input.
VectorType getAxis () const
GenericQuaternion (const VectorType &vec)
const VectorType operator* (const VectorType &input) const
TODO: Speed this up by removing dead code TODO: better do this in common friend style.
int size () const
ElementType & operator[] (int n)
const ElementType & operator[] (int n) const
ElementType & at (int n)
const ElementType & at (int n) const
GenericQuaternion< ElementType > createVector (int) const
GenericQuaternion< ElementType > * realThis ()
Static cast functions.
const GenericQuaternion
< ElementType > * realThis () const
bool operator== (const GenericQuaternion< ElementType > &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const GenericQuaternion< ElementType > &that) const
Inequality operator.
bool notTooFar (const GenericQuaternion< ElementType > &that, const ElementType &epsilon=ElementType(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const GenericQuaternion< ElementType > &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const GenericQuaternion< ElementType > &V)
VectorOperationsBase & operator*= (const ElementType &c)
VectorOperationsBase & operator/= (const ElementType &c)
GenericQuaternion< ElementType > operator- () const
Negative operator.
ElementType sumAllElements () const
Sum of the elements of the vector.
ElementType mulAllElements () const
Product of all elements of the vector.
ElementType sumAllElementsSq () const
Sum of the squares of element of the vector.
ElementType l2Metric () const
Euclidean distance.
ElementType operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
GenericQuaternion< ElementType > normalised () const
Return a normalized copy of vector.
GenericQuaternion< ElementType > cloneVector () const
Return copy of vector.
ElementType l1Metric () const
Sum of the absolute values of element of the vector.
ElementType lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
ElementType minimum () const
ElementType maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
void accept (VisitorType &visitor)
Static Public Member Functions
static GenericQuaternion RotationX (ElementType alpha)
static GenericQuaternion RotationY (ElementType alpha)
static GenericQuaternion RotationZ (ElementType alpha)
static GenericQuaternion Rotation (const VectorType &axis, const ElementType &alpha)
static GenericQuaternion RotationIdentity ()
static GenericQuaternion FromMatrix (const Matrix33 &R)
Public Attributes
ElementType element [length]
Static Public Attributes
static const int LENGTH
Private Types
typedef FixedVectorBase
< GenericQuaternion
< ElementType >, ElementType, 4 > BaseClass
typedef Vector3d< ElementType > VectorType
Friends
GenericQuaternion operator^ (const GenericQuaternion &Q1, const GenericQuaternion &Q2)
Hamilton Product.
GenericQuaternion operator^ (const GenericQuaternion &Q, const VectorType &V)
GenericQuaternion operator^ (const VectorType &V, const GenericQuaternion &Q)
GenericQuaternion hamilton1 (const GenericQuaternion &Q1, const GenericQuaternion &Q2)
Other version of Hamilton product.
GenericQuaternion< ElementType > operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
GenericQuaternion< ElementType > operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
GenericQuaternion< ElementType > operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
GenericQuaternion< ElementType > operator* (const ElementType &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
GenericQuaternion< ElementType > operator* (const VectorOperationsBase &V, const ElementType &c)
GenericQuaternion< ElementType > operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
GenericQuaternion< ElementType > operator/ (const VectorOperationsBase &V, const ElementType &c)
Operator * does the component-specific multiplication by constant
.
ElementType operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
template<typename ElementType>
class corecvs::GenericQuaternion< ElementType >
Definition at line 20 of file quaternion.h.
Member Typedef Documentation
template<typename ElementType > typedef FixedVectorBase<GenericQuaternion<ElementType>, ElementType, 4> corecvs::GenericQuaternion< ElementType >::BaseClass [private]
Reimplemented from corecvs::FixedVectorBase< GenericQuaternion< ElementType >, ElementType, 4 >.
Definition at line 23 of file quaternion.h.
typedef ElementType corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<ElementType>::Type corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::ReflectionType [inherited]
Definition at line 561 of file vectorOperations.h.
template<typename ElementType > typedef Vector3d<ElementType> corecvs::GenericQuaternion< ElementType >::VectorType [private]
Definition at line 24 of file quaternion.h.
Constructor & Destructor Documentation
template<typename ElementType > corecvs::GenericQuaternion< ElementType >::GenericQuaternion (const GenericQuaternion< ElementType > & Q) [inline]
Definition at line 28 of file quaternion.h.
                                                         : BaseClass(Q)
    {
    }
template<typename ElementType > corecvs::GenericQuaternion< ElementType >::GenericQuaternion (const ElementType & _x, const ElementType & _y, const ElementType & _z, const ElementType & _t) [inline]
Definition at line 32 of file quaternion.h.
    {
        (*this)[0] = _x;
        (*this)[1] = _y;
        (*this)[2] = _z;
        (*this)[3] = _t;
    }
template<typename ElementType > corecvs::GenericQuaternion< ElementType >::GenericQuaternion (const BaseClass & V) [inline, explicit]
Definition at line 41 of file quaternion.h.
: BaseClass(V) {};
template<typename ElementType > corecvs::GenericQuaternion< ElementType >::GenericQuaternion (const ElementType & x) [inline, explicit]
Definition at line 42 of file quaternion.h.
: BaseClass(x) {};
template<typename ElementType > corecvs::GenericQuaternion< ElementType >::GenericQuaternion () [inline]
Definition at line 43 of file quaternion.h.
Referenced by corecvs::GenericQuaternion< ElementType >::conjugated(), corecvs::GenericQuaternion< ElementType >::FromMatrix(), corecvs::GenericQuaternion< ElementType >::Rotation(), corecvs::GenericQuaternion< ElementType >::RotationIdentity(), corecvs::GenericQuaternion< ElementType >::RotationX(), corecvs::GenericQuaternion< ElementType >::RotationY(), and corecvs::GenericQuaternion< ElementType >::RotationZ().
: BaseClass() {};
template<typename ElementType > corecvs::GenericQuaternion< ElementType >::GenericQuaternion (const VectorType & axis, const ElementType & alpha) [inline]
TODO: Add -.
* Reciprocal * 4x4 Matrix * Interpolation
Definition at line 186 of file quaternion.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::normalised(), corecvs::GenericQuaternion< ElementType >::t(), corecvs::GenericQuaternion< ElementType >::x(), corecvs::Vector3d< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), corecvs::Vector3d< ElementType >::y(), corecvs::GenericQuaternion< ElementType >::z(), and corecvs::Vector3d< ElementType >::z().
    {
        Vector3dd naxis = axis.normalised();
        double sina2 = sin(alpha * 0.5);
        double cosa2 = cos(alpha * 0.5);
        x() = naxis.x() * sina2;
        y() = naxis.y() * sina2;
        z() = naxis.z() * sina2;
        t() = cosa2;
    }
template<typename ElementType > corecvs::GenericQuaternion< ElementType >::GenericQuaternion (const VectorType & vec) [inline, explicit]
Definition at line 231 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::t(), corecvs::GenericQuaternion< ElementType >::x(), corecvs::Vector3d< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), corecvs::Vector3d< ElementType >::y(), corecvs::GenericQuaternion< ElementType >::z(), and corecvs::Vector3d< ElementType >::z().
    {
        x() = vec.x();
        y() = vec.y();
        z() = vec.z();
        t() = 0;
    };
Member Function Documentation
void corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::accept (VisitorType & visitor) [inline, inherited]
Definition at line 578 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            const ReflectionType fieldDescriptor(i, defaultValue, name);
            visitor.visit(_at(i), &fieldDescriptor);
        }
    }
void corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
ElementType& corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
GenericQuaternion< ElementType > corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
template<typename ElementType > GenericQuaternion corecvs::GenericQuaternion< ElementType >::conjugated () const [inline]
Definition at line 172 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::GenericQuaternion< ElementType >::t(), corecvs::GenericQuaternion< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), and corecvs::GenericQuaternion< ElementType >::z().
Referenced by corecvs::GenericQuaternion< ElementType >::operator*().
    {
        return GenericQuaternion(-this->x(), -this->y(), -this->z(), this->t());
    }
GenericQuaternion< ElementType > corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
template<typename ElementType > static GenericQuaternion corecvs::GenericQuaternion< ElementType >::FromMatrix (const Matrix33 & R) [inline, static]
Definition at line 281 of file quaternion.h.
References corecvs::Matrix33::a(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::GenericQuaternion< ElementType >::t(), corecvs::GenericQuaternion< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), and corecvs::GenericQuaternion< ElementType >::z().
    {
        double a = R.a(0,0);
        double b = R.a(1,1);
        double c = R.a(2,2);
        double trace = a + b + c;
        if (trace > 0)
        {
            double r = sqrt(trace + 1.0);
            double i2r = 1 / (2.0 * r);
            double t = r / 2.0;
            double x = ( R.a(2,1) - R.a(1,2)) * i2r;
            double y = ( R.a(0,2) - R.a(2,0)) * i2r;
            double z = ( R.a(1,0) - R.a(0,1)) * i2r;
            return GenericQuaternion(x,y,z,t);
        }
        if (a > b && a > c)
        {
            double r = sqrt(1 + a - b - c);
            double t = (R.a(2,1) - R.a(1,2)) / (2.0 * r);
            double x = r / 2.0;
            double y = (R.a(0,1) + R.a(1,0)) / (2.0 * r);
            double z = (R.a(0,2) + R.a(2,0)) / (2.0 * r);
            return GenericQuaternion(x,y,z,t);
        } else
        if (b > c)
        {
            double r = sqrt(1 + b - a - c);
            double t = (R.a(0,2) - R.a(2,0)) / (2.0 * r);
            double x = (R.a(0,1) + R.a(1,0)) / (2.0 * r);
            double y = r / 2.0;
            double z = (R.a(1,2) + R.a(2,1)) / (2.0 * r);
            return GenericQuaternion(x,y,z,t);
        } else
        {
            double r = sqrt(1 + c - a - c);
            double t = (R.a(1,0) - R.a(0,1)) / (2.0 * r);
            double x = (R.a(0,2) + R.a(2,0)) / (2.0 * r);
            double y = (R.a(1,2) + R.a(2,1)) / (2.0 * r);
            double z = r / 2.0;
            return GenericQuaternion(x,y,z,t);
        }
    }
template<typename ElementType > double corecvs::GenericQuaternion< ElementType >::getAngle () const [inline]
NB - this function expects normalized quaternion as input.
Definition at line 222 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::t().
{
        return 2 * acos(t());
    }
template<typename ElementType > VectorType corecvs::GenericQuaternion< ElementType >::getAxis () const [inline]
Definition at line 226 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::t(), and corecvs::GenericQuaternion< ElementType >::v().
{
        double sina2 = sqrt(1.0 - (t() * t()));
        return (v() / sina2);
    }
bool corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::isInHypercube (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & low, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
void corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Definition at line 407 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
GenericQuaternion< ElementType > corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Definition at line 420 of file vectorOperations.h.
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
bool corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::notTooFar (const GenericQuaternion< ElementType > & that, const ElementType & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
Referenced by corecvs::GenericQuaternion< ElementType >::toMatrix().
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator!= (const GenericQuaternion< ElementType > & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
template<typename ElementType > const VectorType corecvs::GenericQuaternion< ElementType >::operator* (const VectorType & input) const [inline]
TODO: Speed this up by removing dead code TODO: better do this in common friend style.
Definition at line 244 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::conjugated(), and corecvs::GenericQuaternion< ElementType >::v().
    {
        GenericQuaternion tmp = ((*this) ^ input) ^ this->conjugated();
        return tmp.v();
    }
VectorOperationsBase& corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator*= (const ElementType & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator+= (const GenericQuaternion< ElementType > & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
GenericQuaternion< ElementType > corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator-= (const GenericQuaternion< ElementType > & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator/= (const ElementType & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::operator== (const GenericQuaternion< ElementType > & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
ElementType& corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
const ElementType& corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
void corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
    {
        print();
        cout << "\n";
    }
GenericQuaternion< ElementType > * corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const GenericQuaternion< ElementType > * corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
template<typename ElementType > static GenericQuaternion corecvs::GenericQuaternion< ElementType >::Rotation (const VectorType & axis, const ElementType & alpha) [inline, static]
Definition at line 271 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::GenericQuaternion().
    {
        return GenericQuaternion(axis, alpha);
    }
template<typename ElementType > static GenericQuaternion corecvs::GenericQuaternion< ElementType >::RotationIdentity () [inline, static]
Definition at line 276 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::GenericQuaternion().
Referenced by corecvs::EssentialEstimator::getEssentialGrad(), corecvs::EssentialEstimator::getEssentialGradToRm(), corecvs::EssentialEstimator::getEssentialLM(), and corecvs::EssentialEstimator::getEssentialSimpleKalman().
    {
        return GenericQuaternion(0.0, 0.0, 0.0, 1.0);
    }
template<typename ElementType > static GenericQuaternion corecvs::GenericQuaternion< ElementType >::RotationX (ElementType alpha) [inline, static]
Definition at line 250 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::GenericQuaternion().
    {
        ElementType sina2 = sin(alpha * 0.5);
        ElementType cosa2 = cos(alpha * 0.5);
        return GenericQuaternion(sina2, 0.0, 0.0, cosa2);
    }
template<typename ElementType > static GenericQuaternion corecvs::GenericQuaternion< ElementType >::RotationY (ElementType alpha) [inline, static]
Definition at line 257 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::GenericQuaternion().
    {
        ElementType sina2 = sin(alpha * 0.5);
        ElementType cosa2 = cos(alpha * 0.5);
        return GenericQuaternion(0.0, sina2, 0.0, cosa2);
    }
template<typename ElementType > static GenericQuaternion corecvs::GenericQuaternion< ElementType >::RotationZ (ElementType alpha) [inline, static]
Definition at line 264 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::GenericQuaternion().
    {
        ElementType sina2 = sin(alpha * 0.5);
        ElementType cosa2 = cos(alpha * 0.5);
        return GenericQuaternion(0.0, 0.0, sina2, cosa2);
    }
int corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
ElementType corecvs::VectorOperationsBase< GenericQuaternion< ElementType > , ElementType >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
template<typename ElementType > ElementType& corecvs::GenericQuaternion< ElementType >::t () [inline]
Definition at line 60 of file quaternion.h.
Referenced by corecvs::GenericQuaternion< ElementType >::conjugated(), corecvs::GenericQuaternion< ElementType >::FromMatrix(), corecvs::CameraAngles::FromQuaternion(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::GenericQuaternion< ElementType >::getAngle(), corecvs::GenericQuaternion< ElementType >::getAxis(), corecvs::EssentialEstimator::CostFunctionBase::packState(), and corecvs::GenericQuaternion< ElementType >::toMatrix().
    {
        return (*this)[3];
    };
template<typename ElementType > const ElementType& corecvs::GenericQuaternion< ElementType >::t () const [inline]
Definition at line 86 of file quaternion.h.
    {
        return (*this)[3];
    };
template<typename ElementType > Matrix33 corecvs::GenericQuaternion< ElementType >::toMatrix () const [inline]
This function is a reworked function form somewhere in Internet.
License is unclear
Definition at line 202 of file quaternion.h.
References corecvs::VectorOperationsBase< GenericQuaternion< ElementType >, ElementType >::operator!(), corecvs::GenericQuaternion< ElementType >::t(), corecvs::GenericQuaternion< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), and corecvs::GenericQuaternion< ElementType >::z().
{
        double wx, wy, wz, xx, yy, yz, xy, xz, zz, x2, y2, z2;
        double s  = 2.0f / this->operator !();
        x2 = x() * s;
        y2 = y() * s;
        z2 = z() * s;
        xx = x() * x2;   xy = x() * y2;   xz = x() * z2;
        yy = y() * y2;   yz = y() * z2;   zz = z() * z2;
        wx = t() * x2;   wy = t() * y2;   wz = t() * z2;
        return Matrix33 (
        1.0f - (yy + zz),          xy - wz,           xz + wy,
                 xy + wz, 1.0f - (xx + zz),           yz - wx,
                 xz - wy,          yz + wx,  1.0f - (xx + yy)
        );
    }
template<typename ElementType > VectorType corecvs::GenericQuaternion< ElementType >::v () const [inline]
Definition at line 65 of file quaternion.h.
References corecvs::GenericQuaternion< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), and corecvs::GenericQuaternion< ElementType >::z().
Referenced by corecvs::GenericQuaternion< ElementType >::getAxis(), and corecvs::GenericQuaternion< ElementType >::operator*().
    {
        return VectorType(x(), y(), z());
    }
template<typename ElementType > ElementType& corecvs::GenericQuaternion< ElementType >::x () [inline]
Definition at line 45 of file quaternion.h.
Referenced by corecvs::GenericQuaternion< ElementType >::conjugated(), corecvs::GenericQuaternion< ElementType >::FromMatrix(), corecvs::CameraAngles::FromQuaternion(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::EssentialEstimator::CostFunctionBase::packState(), corecvs::GenericQuaternion< ElementType >::toMatrix(), and corecvs::GenericQuaternion< ElementType >::v().
    {
        return (*this)[0];
    };
template<typename ElementType > const ElementType& corecvs::GenericQuaternion< ElementType >::x () const [inline]
Definition at line 71 of file quaternion.h.
    {
        return (*this)[0];
    };
template<typename ElementType > ElementType& corecvs::GenericQuaternion< ElementType >::y () [inline]
Definition at line 50 of file quaternion.h.
Referenced by corecvs::GenericQuaternion< ElementType >::conjugated(), corecvs::GenericQuaternion< ElementType >::FromMatrix(), corecvs::CameraAngles::FromQuaternion(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::EssentialEstimator::CostFunctionBase::packState(), corecvs::GenericQuaternion< ElementType >::toMatrix(), and corecvs::GenericQuaternion< ElementType >::v().
    {
        return (*this)[1];
    };
template<typename ElementType > const ElementType& corecvs::GenericQuaternion< ElementType >::y () const [inline]
Definition at line 76 of file quaternion.h.
    {
        return (*this)[1];
    };
template<typename ElementType > ElementType& corecvs::GenericQuaternion< ElementType >::z () [inline]
Definition at line 55 of file quaternion.h.
Referenced by corecvs::GenericQuaternion< ElementType >::conjugated(), corecvs::GenericQuaternion< ElementType >::FromMatrix(), corecvs::CameraAngles::FromQuaternion(), corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::EssentialEstimator::CostFunctionBase::packState(), corecvs::GenericQuaternion< ElementType >::toMatrix(), and corecvs::GenericQuaternion< ElementType >::v().
    {
        return (*this)[2];
    };
template<typename ElementType > const ElementType& corecvs::GenericQuaternion< ElementType >::z () const [inline]
Definition at line 81 of file quaternion.h.
    {
        return (*this)[2];
    };
Friends And Related Function Documentation
template<typename ElementType > GenericQuaternion hamilton1 (const GenericQuaternion< ElementType > & Q1, const GenericQuaternion< ElementType > & Q2) [friend]
Other version of Hamilton product.
This could be faster in case addition is faster then multiplication This is not true for x86 Core i7. Totally: 9 multiplications 1 multiplication by const 27 add/sub
37 overall
Definition at line 154 of file quaternion.h.
    {
        ElementType tt = (Q1.z() + Q1.x()) * (Q2.x() + Q2.y());
        ElementType yy = (Q1.t() - Q1.y()) * (Q2.t() + Q2.z());
        ElementType zz = (Q1.t() + Q1.y()) * (Q2.t() - Q2.z());
        ElementType xx = tt + yy + zz;
        ElementType qq = 0.5 * (xx + (Q1.z() - Q1.x()) * (Q2.x() - Q2.y()));
        ElementType t = qq - tt + (Q1.z() - Q1.y()) * (Q2.y() - Q2.z());
        ElementType x = qq - xx + (Q1.x() + Q1.t()) * (Q2.x() + Q2.t());
        ElementType y = qq - yy + (Q1.t() - Q1.x()) * (Q2.y() + Q2.z());
        ElementType z = qq - zz + (Q1.z() + Q1.y()) * (Q2.t() - Q2.x());
        return GenericQuaternion(x, y, z, t);
    }
ElementType operator& (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V1, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
GenericQuaternion< ElementType > operator* (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V1, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
GenericQuaternion< ElementType > operator* (const ElementType & c, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
GenericQuaternion< ElementType > operator* (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
GenericQuaternion< ElementType > operator+ (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V1, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
GenericQuaternion< ElementType > operator- (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V1, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
GenericQuaternion< ElementType > operator/ (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V1, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
GenericQuaternion< ElementType > operator/ (const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & V, const ElementType & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, VectorOperationsBase< GenericQuaternion< ElementType >, ElementType > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
template<typename ElementType > GenericQuaternion operator^ (const GenericQuaternion< ElementType > & Q1, const GenericQuaternion< ElementType > & Q2) [friend]
Hamilton Product.
Totally: 16 multiplications 12 add/subtract
28 overall
Definition at line 110 of file quaternion.h.
    {
        ElementType x, y, z, t;
        t = Q1.t() * Q2.t() - Q1.x() * Q2.x() - Q1.y() * Q2.y() - Q1.z() * Q2.z();
        x = Q1.t() * Q2.x() + Q1.x() * Q2.t() + Q1.y() * Q2.z() - Q1.z() * Q2.y();
        y = Q1.t() * Q2.y() - Q1.x() * Q2.z() + Q1.y() * Q2.t() + Q1.z() * Q2.x();
        z = Q1.t() * Q2.z() + Q1.x() * Q2.y() - Q1.y() * Q2.x() + Q1.z() * Q2.t();
        return GenericQuaternion(x, y, z, t);
    }
template<typename ElementType > GenericQuaternion operator^ (const GenericQuaternion< ElementType > & Q, const VectorType & V) [friend]
Definition at line 121 of file quaternion.h.
    {
        ElementType x, y, z, t;
        t =               - Q.x() * V.x() - Q.y() * V.y() - Q.z() * V.z();
        x = Q.t() * V.x()                 + Q.y() * V.z() - Q.z() * V.y();
        y = Q.t() * V.y() - Q.x() * V.z()                 + Q.z() * V.x();
        z = Q.t() * V.z() + Q.x() * V.y() - Q.y() * V.x()                ;
        return GenericQuaternion(x, y, z, t);
    }
template<typename ElementType > GenericQuaternion operator^ (const VectorType & V, const GenericQuaternion< ElementType > & Q) [friend]
Definition at line 131 of file quaternion.h.
    {
        ElementType x, y, z, t;
        y =  - V.x() * Q.x() - V.y() * Q.y() - V.z() * Q.z();
        x =  + V.x() * Q.t() + V.y() * Q.z() - V.z() * Q.y();
        y =  - V.x() * Q.z() + V.y() * Q.t() + V.z() * Q.x();
        z =  + V.x() * Q.y() - V.y() * Q.x() + V.z() * Q.t();
        return GenericQuaternion(x, y, z, t);
    }
Member Data Documentation
ElementType corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
const int corecvs::FixedVectorBase< GenericQuaternion< ElementType > , ElementType, length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
The documentation for this class was generated from the following file:
core/math/quaternion.h