DeepView: V4L2CaptureInterface::SpinThread Class Reference
V4L2CaptureInterface::SpinThread Class Reference
Public Member Functions
SpinThread (V4L2CaptureInterface *_interface)
virtual void run (void)
Public Attributes
V4L2CaptureInterface * interface
Detailed Description
Definition at line 74 of file V4L2Capture.h.
Constructor & Destructor Documentation
V4L2CaptureInterface::SpinThread::SpinThread (V4L2CaptureInterface * _interface) [inline]
Definition at line 79 of file V4L2Capture.h.
                                                     :
            interface(_interface)
        {}
Member Function Documentation
void V4L2CaptureInterface::SpinThread::run (void) [virtual]
Now we have two new buffers So we do some thread protected operations. 1. Enqueue the previously used buffers 2. Replace them with the new ones
Definition at line 229 of file V4L2Capture.cpp.
References V4L2CaptureInterface::camera, V4L2CaptureInterface::currentFrame, V4L2CameraDescriptor::dequeue(), V4L2CameraDescriptor::deviceHandle, V4L2CameraDescriptor::enqueue(), V4L2CaptureInterface::frameDelay, interface, V4L2CameraDescriptor::INVALID_HANDLE, V4L2CaptureInterface::lastFrameTime, InputType::LEFT_FRAME, V4L2CaptureInterface::maxDesync, ImageCaptureInterface::notifyAboutNewFrame(), V4L2CaptureInterface::protectFrame, InputType::RIGHT_FRAME, V4L2CaptureInterface::shouldStopSpinThread, V4L2CaptureInterface::skippedCount, V4L2CaptureInterface::spinRunning, frame_data_t::timestamp, V4L2BufferDescriptor::usecsTimeStamp(), corecvs::PreciseTimer::usecsTo(), and corecvs::PreciseTimer::usecsToNow().
{
    while (interface->spinRunning.tryLock())
    {
        V4L2BufferDescriptor newBufferLeft;
        V4L2BufferDescriptor newBufferRight;
        V4L2CameraDescriptor* left  = &(interface->camera[Frames::LEFT_FRAME ]);
        V4L2CameraDescriptor* right = &(interface->camera[Frames::RIGHT_FRAME]);
        V4L2BufferDescriptor* currentLeft  = &(interface->currentFrame[Frames::LEFT_FRAME ]);
        V4L2BufferDescriptor* currentRight = &(interface->currentFrame[Frames::RIGHT_FRAME]);
        /* First we block till we will get a new frame */
        /*TODO: Wonder if dequeue should be static */
        left->dequeue(newBufferLeft);
        /* If we have only one camera, we assume this is the left camera */
        if (right->deviceHandle != V4L2CameraDescriptor::INVALID_HANDLE) {
            right->dequeue(newBufferRight);
        }
        uint64_t leftStamp = newBufferLeft.usecsTimeStamp();
        if (right->deviceHandle != V4L2CameraDescriptor::INVALID_HANDLE)
        {
            uint64_t rightStamp = newBufferRight.usecsTimeStamp();
            /*Reducing desync only  one frame at a time*/
            if (leftStamp > rightStamp && leftStamp - rightStamp > interface->maxDesync)
            {
                right->enqueue(newBufferRight);
                right->dequeue(newBufferRight);
                rightStamp = newBufferRight.usecsTimeStamp();
            }
            if (rightStamp > leftStamp && rightStamp - leftStamp > interface->maxDesync)
            {
                left->enqueue(newBufferLeft);
                left->dequeue(newBufferLeft);
                leftStamp = newBufferLeft.usecsTimeStamp();
            }
        }
        /**
         *  Now we have two new buffers
         *  So we do some thread protected operations.
         *  1. Enqueue the previously used buffers
         *  2. Replace them with the new ones
         **/
        interface->protectFrame.lock();
        {
            if (left->deviceHandle != -1)
            {
                left->enqueue(*currentLeft);
                *currentLeft = newBufferLeft;
            }
            if (right->deviceHandle != -1)
            {
                right->enqueue(*currentRight);
                *currentRight = newBufferRight;
            }
            interface->skippedCount++;
        }
        interface->protectFrame.unlock();
        /* For statistics */
        if (interface->lastFrameTime.usecsTo(PreciseTimer()) != 0)
        {
            interface->frameDelay = interface->lastFrameTime.usecsToNow();
        }
        interface->lastFrameTime = PreciseTimer::currentTime();
//        cout << "Frame notification" << endl;
        frame_data_t frameData;
        frameData.timestamp = (currentLeft->usecsTimeStamp() / 2) + (currentRight->usecsTimeStamp() / 2);;
        interface->notifyAboutNewFrame(frameData);
        interface->spinRunning.unlock();
        if (interface->shouldStopSpinThread)
        {
            break;
        }
    }
}
Member Data Documentation
V4L2CaptureInterface* V4L2CaptureInterface::SpinThread::interface
Definition at line 77 of file V4L2Capture.h.
Referenced by run().
The documentation for this class was generated from the following files:
utils/framesources/v4l2/V4L2Capture.h
utils/framesources/v4l2/V4L2Capture.cpp