DeepView: StatisticsDialog Class Reference
StatisticsDialog Class Reference
#include <statisticsDialog.h>
Public Slots
void addCaptureStats (CaptureStatistics capture)
void addStats (Statistics &flow)
void reset ()
Signals
void askParentRepaint (QPaintEvent *event, QWidget *who)
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (QResizeEvent *event)
void notifyKeyPressEvent (QKeyEvent *event)
void notifyKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
StatisticsDialog (QWidget *parent=0)
~StatisticsDialog ()
void redrawCaptureStats ()
void redrawStats ()
QString printMs (uint64_t ms)
virtual void paintEvent (QPaintEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
Public Attributes
QtStatisticsCollector statsAccum
Private Attributes
Ui_StatisticsDialogClass ui
CaptureStatistics captureAccum
CaptureStatistics captureCurrent
int statsAdded
int captureAdded
Detailed Description
Definition at line 13 of file statisticsDialog.h.
Constructor & Destructor Documentation
StatisticsDialog::StatisticsDialog (QWidget * parent = 0)
Definition at line 3 of file statisticsDialog.cpp.
References redrawCaptureStats(), redrawStats(), and ui.
    : ViAreaWidget(parent),
      statsAdded(0),
      captureAdded(0)
{
    ui.setupUi(this);
    redrawCaptureStats();
    redrawStats();
}
StatisticsDialog::~StatisticsDialog ()
Definition at line 101 of file statisticsDialog.cpp.
{
}
Member Function Documentation
void StatisticsDialog::addCaptureStats (CaptureStatistics capture) [slot]
Definition at line 25 of file statisticsDialog.cpp.
References captureAccum, captureAdded, captureCurrent, and redrawCaptureStats().
Referenced by BaseHostDialog::setCaptureStats().
{
    captureCurrent = capture;
    captureAccum += capture;
    captureAdded++;
    redrawCaptureStats();
}
void StatisticsDialog::addStats (Statistics & flow) [slot]
Definition at line 19 of file statisticsDialog.cpp.
References corecvs::BaseTimeStatisticsCollector::addStatistics(), redrawStats(), and statsAccum.
Referenced by RecorderDialog::processResult().
{
    statsAccum.addStatistics(newStats);
    redrawStats();
}
void ViAreaWidget::askParentRepaint (QPaintEvent * event, QWidget * who) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::paintEvent().
void ViAreaWidget::keyPressEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 53 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyPressEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyPressEvent(event);
}
void ViAreaWidget::keyReleaseEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 59 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyReleaseEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyReleaseEvent(event);
}
void ViAreaWidget::mouseDoubleClickEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 35 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mouseMoveEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 16 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mousePressEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 22 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, ViAreaWidget::notifyParentMouseMove(), and ViAreaWidget::notifyParentMousePress().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
    emit notifyParentMousePress(event);
}
void ViAreaWidget::mouseReleaseEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 41 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseRelease().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseRelease(event);
}
void ViAreaWidget::notifyKeyPressEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyPressEvent().
void ViAreaWidget::notifyKeyReleaseEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyReleaseEvent().
void ViAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), ViAreaWidget::mouseDoubleClickEvent(), ViAreaWidget::mouseMoveEvent(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::mouseReleaseEvent().
void ViAreaWidget::notifyParentResize (QResizeEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::resizeEvent().
void ViAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::wheelEvent().
void ViAreaWidget::paintEvent (QPaintEvent * event) [virtual, inherited]
Reimplemented in ImageWidget.
Definition at line 10 of file viAreaWidget.cpp.
References ViAreaWidget::askParentRepaint(), and ViAreaWidget::mForwardEvents.
{
    if (!mForwardEvents) return;
    emit askParentRepaint(event, this);
}
QString StatisticsDialog::printMs (uint64_t ms)
Definition at line 14 of file statisticsDialog.cpp.
{
    return QString("%1 | %2 us").arg(ms / 1000).arg(ms % 1000, 3, 10, QChar('0'));
}
void StatisticsDialog::redrawCaptureStats ()
Definition at line 34 of file statisticsDialog.cpp.
References captureAccum, captureAdded, captureCurrent, CaptureStatistics::DATA_SIZE, CaptureStatistics::framesSkipped, CaptureStatistics::INTERFRAME_DELAY, CaptureStatistics::MAX_TIME_ID, CaptureStatistics::names, CaptureStatistics::temperature, CaptureStatistics::triggerSkipped, ui, and CaptureStatistics::values.
Referenced by addCaptureStats(), reset(), and StatisticsDialog().
{
    QString stats;
    for (int i = 0; i < CaptureStatistics::MAX_TIME_ID; i++)
    {
        double meanValue = 0.0;
        if (captureAdded != 0 )
        {
            meanValue = captureAccum.values[i] / captureAdded;
        }
        stats += QString("%1 : %2 us : %3 ms : %4 us \n")
                .arg(CaptureStatistics::names[i], -20)
                .arg(captureCurrent.values[i], 7)
                .arg((captureCurrent.values[i] + 500) / 1000, 7)
                .arg(meanValue , 7);
    }
    stats += QString("%1 : %2 Kb\n")
            .arg(CaptureStatistics::names[CaptureStatistics::DATA_SIZE], -20)
            .arg(captureCurrent.values[CaptureStatistics::DATA_SIZE] / 1024, 7);
    uint64_t interframe = 0.0;
    if (captureAdded != 0) {
        interframe = captureAccum.values[CaptureStatistics::INTERFRAME_DELAY] / captureAdded;
    }
    if (interframe != 0)
    {
        double fps = 1000000.0 / interframe;
        stats += QString("Stereo FPS : %1\n").arg(fps);//.arg(1000000.0 / interframe, 5, 'f', 1);
    }
    double meanSkipped = 0.0;
    if (captureAdded != 0 )
    {
        meanSkipped = (double)captureAccum.framesSkipped / captureAdded;
    }
    stats += QString("Frames skipped : %1%\n")
            .arg(meanSkipped * 100.0, 0, 'f', 2);
    stats += QString("Triggers skipped : %1%\n").arg(captureAccum.triggerSkipped);
    stats += QString("Temperature : %1C   %2C \n").arg(captureAccum.temperature[0], 0, 'f', 2).arg(captureAccum.temperature[1], 0, 'f', 2);
    ui.captureStats->setText(stats);
}
void StatisticsDialog::redrawStats ()
Definition at line 83 of file statisticsDialog.cpp.
References QtStatisticsCollector::printForQT(), statsAccum, and ui.
Referenced by addStats(), reset(), and StatisticsDialog().
{
    QString stats = statsAccum.printForQT();
    ui.flowStats->setText(stats);
}
void StatisticsDialog::reset (void) [slot]
Definition at line 89 of file statisticsDialog.cpp.
References captureAccum, captureAdded, captureCurrent, redrawCaptureStats(), redrawStats(), corecvs::BaseTimeStatisticsCollector::reset(), statsAccum, and statsAdded.
{
    cout << "Resetting statistics" << endl;
    statsAccum.reset();
    statsAdded = 0;
    captureAccum = CaptureStatistics();
    captureCurrent = CaptureStatistics();
    captureAdded = 0;
    redrawCaptureStats();
    redrawStats();
}
void ViAreaWidget::resizeEvent (QResizeEvent * event) [virtual, inherited]
Definition at line 29 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentResize().
{
    if (!mForwardEvents) return;
    emit notifyParentResize(event);
}
void ViAreaWidget::wheelEvent (QWheelEvent * event) [virtual, inherited]
Definition at line 47 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentWheelEvent().
{
    if (!mForwardEvents) return;
    emit notifyParentWheelEvent(event);
}
Member Data Documentation
CaptureStatistics StatisticsDialog::captureAccum [private]
Definition at line 34 of file statisticsDialog.h.
Referenced by addCaptureStats(), redrawCaptureStats(), and reset().
int StatisticsDialog::captureAdded [private]
Definition at line 38 of file statisticsDialog.h.
Referenced by addCaptureStats(), redrawCaptureStats(), and reset().
CaptureStatistics StatisticsDialog::captureCurrent [private]
Definition at line 35 of file statisticsDialog.h.
Referenced by addCaptureStats(), redrawCaptureStats(), and reset().
QtStatisticsCollector StatisticsDialog::statsAccum
Definition at line 31 of file statisticsDialog.h.
Referenced by addStats(), redrawStats(), reset(), and BaseHostDialog::statisticsCollector().
int StatisticsDialog::statsAdded [private]
Definition at line 37 of file statisticsDialog.h.
Referenced by reset().
Ui_StatisticsDialogClass StatisticsDialog::ui [private]
Reimplemented from ViAreaWidget.
Definition at line 33 of file statisticsDialog.h.
Referenced by redrawCaptureStats(), redrawStats(), and StatisticsDialog().
The documentation for this class was generated from the following files:
applications/base/statistics/statisticsDialog.h
applications/base/statistics/statisticsDialog.cpp