DeepView: MemoryUsageCalculator Class Reference
MemoryUsageCalculator Class Reference
Class that gets memory usage info from OS and checks if it is within allowed range or not.
#include <memoryUsageCalculator.h>
Public Slots
void getMemoryUsage ()
Recalculate memory usage.
Signals
void memoryOverflow ()
Is thrown if memory usage hits the limit.
Protected Member Functions
virtual void getMemoryUsageImpl ()=0
Platform-specific implementation.
Protected Attributes
double mVirtualSize
double mResidentSize
Detailed Description
Class that gets memory usage info from OS and checks if it is within allowed range or not.
Definition at line 8 of file memoryUsageCalculator.h.
Member Function Documentation
void MemoryUsageCalculator::getMemoryUsage () [slot]
Recalculate memory usage.
Definition at line 4 of file memoryUsageCalculator.cpp.
References getMemoryUsageImpl(), memoryOverflow(), mResidentSize, and upperMemoryUsageLimit.
{
    getMemoryUsageImpl();
    if (mResidentSize > upperMemoryUsageLimit)
    {
        qDebug() << "We are using " << mResidentSize << "Mb with is bigger then high limit of " << upperMemoryUsageLimit << "Mb";
        emit memoryOverflow();
    }
}
virtual void MemoryUsageCalculator::getMemoryUsageImpl () [protected, pure virtual]
Platform-specific implementation.
Implemented in LinuxMemoryUsageCalculator, MacMemoryUsageCalculator, and WindowsMemoryUsageCalculator.
Referenced by getMemoryUsage().
void MemoryUsageCalculator::memoryOverflow () [signal]
Is thrown if memory usage hits the limit.
Referenced by getMemoryUsage().
Member Data Documentation
double MemoryUsageCalculator::mResidentSize [protected]
Definition at line 25 of file memoryUsageCalculator.h.
Referenced by getMemoryUsage(), WindowsMemoryUsageCalculator::getMemoryUsageImpl(), MacMemoryUsageCalculator::getMemoryUsageImpl(), and LinuxMemoryUsageCalculator::getMemoryUsageImpl().
double MemoryUsageCalculator::mVirtualSize [protected]
Definition at line 24 of file memoryUsageCalculator.h.
Referenced by MacMemoryUsageCalculator::getMemoryUsageImpl(), WindowsMemoryUsageCalculator::getMemoryUsageImpl(), and LinuxMemoryUsageCalculator::getMemoryUsageImpl().
The documentation for this class was generated from the following files:
applications/base/memoryUsageCalculator/memoryUsageCalculator.h
applications/base/memoryUsageCalculator/memoryUsageCalculator.cpp