DeepView: tinyxml2::XMLConstHandle Class Reference
tinyxml2::XMLConstHandle Class Reference
A variant of the XMLHandle class for working with const XMLNodes and Documents.
#include <tinyxml2.h>
Public Member Functions
XMLConstHandle (const XMLNode *node)
XMLConstHandle (const XMLNode &node)
XMLConstHandle (const XMLConstHandle &ref)
XMLConstHandle & operator= (const XMLConstHandle &ref)
const XMLConstHandle FirstChild () const
const XMLConstHandle FirstChildElement (const char *value=0) const
const XMLConstHandle LastChild () const
const XMLConstHandle LastChildElement (const char *_value=0) const
const XMLConstHandle PreviousSibling () const
const XMLConstHandle PreviousSiblingElement (const char *_value=0) const
const XMLConstHandle NextSibling () const
const XMLConstHandle NextSiblingElement (const char *_value=0) const
const XMLNode * ToNode () const
const XMLElement * ToElement () const
const XMLText * ToText () const
const XMLUnknown * ToUnknown () const
const XMLDeclaration * ToDeclaration () const
Private Attributes
const XMLNode * _node
Detailed Description
A variant of the XMLHandle class for working with const XMLNodes and Documents.
It is the same in all regards, except for the 'const' qualifiers. See XMLHandle for API.
Definition at line 1698 of file tinyxml2.h.
Constructor & Destructor Documentation
tinyxml2::XMLConstHandle::XMLConstHandle (const XMLNode * node) [inline]
Definition at line 1701 of file tinyxml2.h.
References _node.
Referenced by FirstChild(), FirstChildElement(), LastChild(), LastChildElement(), NextSibling(), NextSiblingElement(), PreviousSibling(), and PreviousSiblingElement().
{
        _node = node;
    }
tinyxml2::XMLConstHandle::XMLConstHandle (const XMLNode & node) [inline]
Definition at line 1704 of file tinyxml2.h.
References _node.
{
        _node = &node;
    }
tinyxml2::XMLConstHandle::XMLConstHandle (const XMLConstHandle & ref) [inline]
Definition at line 1707 of file tinyxml2.h.
References _node.
{
        _node = ref._node;
    }
Member Function Documentation
const XMLConstHandle tinyxml2::XMLConstHandle::FirstChild () const [inline]
Definition at line 1716 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::FirstChild(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->FirstChild() : 0 );
    }
const XMLConstHandle tinyxml2::XMLConstHandle::FirstChildElement (const char * value = 0) const [inline]
Definition at line 1719 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::FirstChildElement(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->FirstChildElement( value ) : 0 );
    }
const XMLConstHandle tinyxml2::XMLConstHandle::LastChild () const [inline]
Definition at line 1722 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::LastChild(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->LastChild() : 0 );
    }
const XMLConstHandle tinyxml2::XMLConstHandle::LastChildElement (const char * _value = 0) const [inline]
Definition at line 1725 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::LastChildElement(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->LastChildElement( _value ) : 0 );
    }
const XMLConstHandle tinyxml2::XMLConstHandle::NextSibling () const [inline]
Definition at line 1734 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::NextSibling(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->NextSibling() : 0 );
    }
const XMLConstHandle tinyxml2::XMLConstHandle::NextSiblingElement (const char * _value = 0) const [inline]
Definition at line 1737 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::NextSiblingElement(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->NextSiblingElement( _value ) : 0 );
    }
XMLConstHandle& tinyxml2::XMLConstHandle::operator= (const XMLConstHandle & ref) [inline]
Definition at line 1711 of file tinyxml2.h.
References _node.
{
        _node = ref._node;
        return *this;
    }
const XMLConstHandle tinyxml2::XMLConstHandle::PreviousSibling () const [inline]
Definition at line 1728 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::PreviousSibling(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->PreviousSibling() : 0 );
    }
const XMLConstHandle tinyxml2::XMLConstHandle::PreviousSiblingElement (const char * _value = 0) const [inline]
Definition at line 1731 of file tinyxml2.h.
References _node, tinyxml2::XMLNode::PreviousSiblingElement(), and XMLConstHandle().
{
        return XMLConstHandle( _node ? _node->PreviousSiblingElement( _value ) : 0 );
    }
const XMLDeclaration* tinyxml2::XMLConstHandle::ToDeclaration () const [inline]
Definition at line 1754 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToDeclaration().
{
        return ( ( _node && _node->ToDeclaration() ) ? _node->ToDeclaration() : 0 );
    }
const XMLElement* tinyxml2::XMLConstHandle::ToElement () const [inline]
Definition at line 1745 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToElement().
{
        return ( ( _node && _node->ToElement() ) ? _node->ToElement() : 0 );
    }
const XMLNode* tinyxml2::XMLConstHandle::ToNode () const [inline]
Definition at line 1742 of file tinyxml2.h.
References _node.
{
        return _node;
    }
const XMLText* tinyxml2::XMLConstHandle::ToText () const [inline]
Definition at line 1748 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToText().
{
        return ( ( _node && _node->ToText() ) ? _node->ToText() : 0 );
    }
const XMLUnknown* tinyxml2::XMLConstHandle::ToUnknown () const [inline]
Definition at line 1751 of file tinyxml2.h.
References _node, and tinyxml2::XMLNode::ToUnknown().
{
        return ( ( _node && _node->ToUnknown() ) ? _node->ToUnknown() : 0 );
    }
Member Data Documentation
const XMLNode* tinyxml2::XMLConstHandle::_node [private]
Definition at line 1759 of file tinyxml2.h.
Referenced by FirstChild(), FirstChildElement(), LastChild(), LastChildElement(), NextSibling(), NextSiblingElement(), operator=(), PreviousSibling(), PreviousSiblingElement(), ToDeclaration(), ToElement(), ToNode(), ToText(), ToUnknown(), and XMLConstHandle().
The documentation for this class was generated from the following file:
core/tinyxml/tinyxml2.h