DeepView: AxisAlignedBoxParameters Class Reference
AxisAlignedBoxParameters Class Reference
Axis Aligned Box Parameters Axis Aligned Box Parameters.
#include <axisAlignedBoxParameters.h>
Public Types
enum FieldId {
X_ID, Y_ID, Z_ID, WIDTH_ID,
HEIGHT_ID, DEPTH_ID, AXIS_ALIGNED_BOX_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
double x () const
double y () const
double z () const
double width () const
double height () const
double depth () const
void setX (double x)
void setY (double y)
void setZ (double z)
void setWidth (double width)
void setHeight (double height)
void setDepth (double depth)
template<class VisitorType >
void accept (VisitorType &visitor)
AxisAlignedBoxParameters ()
AxisAlignedBoxParameters (double x, double y, double z, double width, double height, double depth)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
double mX
Section with variables.
double mY
Y Y.
double mZ
Z Z.
double mWidth
width width
double mHeight
height height
double mDepth
depth depth
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, AxisAlignedBoxParameters &toSave)
Detailed Description
Axis Aligned Box Parameters Axis Aligned Box Parameters.
Definition at line 38 of file axisAlignedBoxParameters.h.
Member Enumeration Documentation
enum AxisAlignedBoxParameters::FieldId
Enumerator:
X_ID
Y_ID
Z_ID
WIDTH_ID
HEIGHT_ID
DEPTH_ID
AXIS_ALIGNED_BOX_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file axisAlignedBoxParameters.h.
                 {
        X_ID,
        Y_ID,
        Z_ID,
        WIDTH_ID,
        HEIGHT_ID,
        DEPTH_ID,
        AXIS_ALIGNED_BOX_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
AxisAlignedBoxParameters::AxisAlignedBoxParameters () [inline]
Definition at line 171 of file axisAlignedBoxParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
AxisAlignedBoxParameters::AxisAlignedBoxParameters (double x, double y, double z, double width, double height, double depth) [inline]
Definition at line 177 of file axisAlignedBoxParameters.h.
    {
        mX = x;
        mY = y;
        mZ = z;
        mWidth = width;
        mHeight = height;
        mDepth = depth;
    }
Member Function Documentation
template<class VisitorType > void AxisAlignedBoxParameters::accept (VisitorType & visitor) [inline]
Definition at line 161 of file axisAlignedBoxParameters.h.
    {
        visitor.visit(mX,                         static_cast<const DoubleField *>  (fields()[X_ID]));
        visitor.visit(mY,                         static_cast<const DoubleField *>  (fields()[Y_ID]));
        visitor.visit(mZ,                         static_cast<const DoubleField *>  (fields()[Z_ID]));
        visitor.visit(mWidth,                     static_cast<const DoubleField *>  (fields()[WIDTH_ID]));
        visitor.visit(mHeight,                    static_cast<const DoubleField *>  (fields()[HEIGHT_ID]));
        visitor.visit(mDepth,                     static_cast<const DoubleField *>  (fields()[DEPTH_ID]));
    }
static const char* corecvs::BaseReflection< AxisAlignedBoxParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
double AxisAlignedBoxParameters::depth () const [inline]
Definition at line 122 of file axisAlignedBoxParameters.h.
Referenced by corecvs::Mesh3D::addAOB(), corecvs::AxisAlignedBox3d::AxisAlignedBox3d(), and AxisAlignedBoxParametersControlWidget::setParameters().
    {
        return mDepth;
    }
static int corecvs::BaseReflection< AxisAlignedBoxParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< AxisAlignedBoxParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* AxisAlignedBoxParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 93 of file axisAlignedBoxParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< AxisAlignedBoxParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
double AxisAlignedBoxParameters::height () const [inline]
Definition at line 117 of file axisAlignedBoxParameters.h.
Referenced by corecvs::Mesh3D::addAOB(), corecvs::AxisAlignedBox3d::AxisAlignedBox3d(), and AxisAlignedBoxParametersControlWidget::setParameters().
    {
        return mHeight;
    }
static const char* corecvs::BaseReflection< AxisAlignedBoxParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< AxisAlignedBoxParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void AxisAlignedBoxParameters::print () [inline]
Definition at line 201 of file axisAlignedBoxParameters.h.
    {
        cout << *this;
    }
void AxisAlignedBoxParameters::setDepth (double depth) [inline]
Definition at line 153 of file axisAlignedBoxParameters.h.
    {
        mDepth = depth;
    }
void AxisAlignedBoxParameters::setHeight (double height) [inline]
Definition at line 148 of file axisAlignedBoxParameters.h.
    {
        mHeight = height;
    }
void AxisAlignedBoxParameters::setWidth (double width) [inline]
Definition at line 143 of file axisAlignedBoxParameters.h.
    {
        mWidth = width;
    }
void AxisAlignedBoxParameters::setX (double x) [inline]
Definition at line 128 of file axisAlignedBoxParameters.h.
    {
        mX = x;
    }
void AxisAlignedBoxParameters::setY (double y) [inline]
Definition at line 133 of file axisAlignedBoxParameters.h.
    {
        mY = y;
    }
void AxisAlignedBoxParameters::setZ (double z) [inline]
Definition at line 138 of file axisAlignedBoxParameters.h.
    {
        mZ = z;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int AxisAlignedBoxParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file axisAlignedBoxParameters.cpp.
References DEPTH_ID, corecvs::BaseReflection< AxisAlignedBoxParameters >::fields(), HEIGHT_ID, mDepth, mHeight, mWidth, mX, mY, mZ, corecvs::BaseReflection< AxisAlignedBoxParameters >::naming(), WIDTH_ID, X_ID, Y_ID, and Z_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Axis Aligned Box Parameters",
        "Axis Aligned Box Parameters",
        ""
    );
    fields().push_back(
        new DoubleField
        (
          AxisAlignedBoxParameters::X_ID,
          offsetof(AxisAlignedBoxParameters, mX),
          0,
          "X",
          "X",
          "X"
        )
    );
    fields().push_back(
        new DoubleField
        (
          AxisAlignedBoxParameters::Y_ID,
          offsetof(AxisAlignedBoxParameters, mY),
          0,
          "Y",
          "Y",
          "Y"
        )
    );
    fields().push_back(
        new DoubleField
        (
          AxisAlignedBoxParameters::Z_ID,
          offsetof(AxisAlignedBoxParameters, mZ),
          3000,
          "Z",
          "Z",
          "Z"
        )
    );
    fields().push_back(
        new DoubleField
        (
          AxisAlignedBoxParameters::WIDTH_ID,
          offsetof(AxisAlignedBoxParameters, mWidth),
          1000,
          "width",
          "width",
          "width"
        )
    );
    fields().push_back(
        new DoubleField
        (
          AxisAlignedBoxParameters::HEIGHT_ID,
          offsetof(AxisAlignedBoxParameters, mHeight),
          1000,
          "height",
          "height",
          "height"
        )
    );
    fields().push_back(
        new DoubleField
        (
          AxisAlignedBoxParameters::DEPTH_ID,
          offsetof(AxisAlignedBoxParameters, mDepth),
          1000,
          "depth",
          "depth",
          "depth"
        )
    );
   return 0;
}
double AxisAlignedBoxParameters::width () const [inline]
Definition at line 112 of file axisAlignedBoxParameters.h.
Referenced by corecvs::Mesh3D::addAOB(), corecvs::AxisAlignedBox3d::AxisAlignedBox3d(), and AxisAlignedBoxParametersControlWidget::setParameters().
    {
        return mWidth;
    }
double AxisAlignedBoxParameters::x () const [inline]
Definition at line 97 of file axisAlignedBoxParameters.h.
Referenced by corecvs::Mesh3D::addAOB(), corecvs::AxisAlignedBox3d::AxisAlignedBox3d(), and AxisAlignedBoxParametersControlWidget::setParameters().
    {
        return mX;
    }
double AxisAlignedBoxParameters::y () const [inline]
Definition at line 102 of file axisAlignedBoxParameters.h.
Referenced by corecvs::Mesh3D::addAOB(), corecvs::AxisAlignedBox3d::AxisAlignedBox3d(), and AxisAlignedBoxParametersControlWidget::setParameters().
    {
        return mY;
    }
double AxisAlignedBoxParameters::z () const [inline]
Definition at line 107 of file axisAlignedBoxParameters.h.
Referenced by corecvs::Mesh3D::addAOB(), corecvs::AxisAlignedBox3d::AxisAlignedBox3d(), and AxisAlignedBoxParametersControlWidget::setParameters().
    {
        return mZ;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, AxisAlignedBoxParameters & toSave) [friend]
Definition at line 194 of file axisAlignedBoxParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< AxisAlignedBoxParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
double AxisAlignedBoxParameters::mDepth
depth depth
Definition at line 87 of file axisAlignedBoxParameters.h.
Referenced by staticInit().
double AxisAlignedBoxParameters::mHeight
height height
Definition at line 81 of file axisAlignedBoxParameters.h.
Referenced by staticInit().
double AxisAlignedBoxParameters::mWidth
width width
Definition at line 75 of file axisAlignedBoxParameters.h.
Referenced by staticInit().
double AxisAlignedBoxParameters::mX
Section with variables.
X X
Definition at line 57 of file axisAlignedBoxParameters.h.
Referenced by staticInit().
double AxisAlignedBoxParameters::mY
Y Y.
Definition at line 63 of file axisAlignedBoxParameters.h.
Referenced by staticInit().
double AxisAlignedBoxParameters::mZ
Z Z.
Definition at line 69 of file axisAlignedBoxParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< AxisAlignedBoxParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/axisAlignedBoxParameters.h
core/xml/generated/axisAlignedBoxParameters.cpp