DeepView: corecvs::BasePathVisitor Class Reference
corecvs::BasePathVisitor Class Reference
Base class for visitors that iterate over the hierarchy of types.
#include <basePathVisitor.h>
Public Member Functions
string getCurrentPath ()
string getChildPath (string child)
BasePathVisitor (string _separator=SEPARATOR_DEFAULT)
void pushChild (const string child)
void popChild ()
Public Attributes
string separator
T elements
STL member.
Static Public Attributes
static string SEPARATOR_DEFAULT = "."
Detailed Description
Base class for visitors that iterate over the hierarchy of types.
Definition at line 21 of file basePathVisitor.h.
Constructor & Destructor Documentation
corecvs::BasePathVisitor::BasePathVisitor (string _separator = SEPARATOR_DEFAULT) [inline]
Definition at line 45 of file basePathVisitor.h.
                                                             :
        separator(_separator)
    {
    }
Member Function Documentation
string corecvs::BasePathVisitor::getChildPath (string child) [inline]
Definition at line 35 of file basePathVisitor.h.
References getCurrentPath(), and separator.
Referenced by pushChild().
    {
       string newPath = getCurrentPath();
       if (!newPath.empty())
           newPath.append(separator);
       newPath.append(child);
       return newPath;
    }
string corecvs::BasePathVisitor::getCurrentPath () [inline]
Definition at line 28 of file basePathVisitor.h.
Referenced by getChildPath().
    {
        if (empty())
            return "";
        return back();
    }
void corecvs::BasePathVisitor::popChild () [inline]
Definition at line 55 of file basePathVisitor.h.
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        pop_back();
    }
void corecvs::BasePathVisitor::pushChild (const string child) [inline]
Definition at line 50 of file basePathVisitor.h.
References getChildPath().
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        push_back(getChildPath(child));
    }
Member Data Documentation
template<typename T> T std::deque< T >::elements [inherited]
STL member.
string corecvs::BasePathVisitor::separator
Definition at line 26 of file basePathVisitor.h.
Referenced by getChildPath().
string corecvs::BasePathVisitor::SEPARATOR_DEFAULT = "." [static]
Definition at line 24 of file basePathVisitor.h.
The documentation for this class was generated from the following files:
core/utils/visitors/basePathVisitor.h
core/utils/visitors/basePathVisitor.cpp