DeepView: corecvs::BlockedRange< IndexType > Class Template Reference
corecvs::BlockedRange< IndexType > Class Template Reference
#include <tbbWrapper.h>
Public Types
typedef std::size_t size_type
Public Member Functions
BlockedRange (IndexType begin, IndexType end, size_type grainsize=1)
IndexType end () const
IndexType begin () const
size_type size () const
bool empty () const
bool is_divisible () const
Static Public Member Functions
static IndexType do_split (BlockedRange &r)
Please not the design here -.
Private Attributes
IndexType myBegin
IndexType myEnd
size_type myGrainsize
Detailed Description
template<typename IndexType>
class corecvs::BlockedRange< IndexType >
Definition at line 27 of file tbbWrapper.h.
Member Typedef Documentation
template<typename IndexType> typedef std::size_t corecvs::BlockedRange< IndexType >::size_type
Definition at line 29 of file tbbWrapper.h.
Constructor & Destructor Documentation
template<typename IndexType> corecvs::BlockedRange< IndexType >::BlockedRange (IndexType begin, IndexType end, size_type grainsize = 1) [inline]
Definition at line 31 of file tbbWrapper.h.
                                                                          :
        myBegin(begin),
        myEnd(end),
        myGrainsize(grainsize)
    {
    }
Member Function Documentation
template<typename IndexType> IndexType corecvs::BlockedRange< IndexType >::begin () const [inline]
Definition at line 43 of file tbbWrapper.h.
Referenced by corecvs::ParallelPrepareBlurBuffers::operator()(), corecvs::ParallelGetBestClassifier::operator()(), corecvs::PunchedBufferOperations< ThisTypeName, ElementType >::ParallelDensityCounter::operator()(), corecvs::BufferProcessor< InputBuffer, OutputBuffer, GenericKernelType, GAlgebraType >::ParallelProcess< shouldAlign >::operator()(), corecvs::BufferConverter< ReaderType, WriterType, GenericKernelType, GAlgebraType >::ParallelConverter::operator()(), corecvs::ParallelTriangulate< InputType >::operator()(), corecvs::IntegralBuffer< ElementType, BaseElementType, IndexType >::ParallelRectangularBlur< ReturnType >::operator()(), corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::operator()(), corecvs::BufferConverter< ReaderType, WriterType, GenericKernelType, GAlgebraType >::ParallelProcessAlign::operator()(), corecvs::DirectRemapper::ParallelRemap::operator()(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformationBl< ReturnType, DeformMapType >::operator()(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator()(), corecvs::AbstractBuffer< ElementType, IndexType >::ParallelDoConvolve< ReturnType, ConvElementType, ConvIndexType >::operator()(), and corecvs::AbstractBuffer< ElementType, IndexType >::ParallelDoConvolve1< ReturnType, ConvElementType, ConvIndexType >::operator()().
    {
        return myBegin;
    }
template<typename IndexType> static IndexType corecvs::BlockedRange< IndexType >::do_split (BlockedRange< IndexType > & r) [inline, static]
Please not the design here -.
During the split the input range r is transformed into the first part of the split, and the newly constructed object becomes the second part.
Attention:
For a newly created part to finish at the appropriate place we need to _first_ initialize the myEnd , and then myBegin.
TBB blocked_range<Type> version does it by defining end before begin. I don't think one should give up semantics for precisely following C++ guidelines of using initialization list.
Definition at line 87 of file tbbWrapper.h.
References ASSERT_TRUE, corecvs::BlockedRange< IndexType >::is_divisible(), corecvs::BlockedRange< IndexType >::myBegin, and corecvs::BlockedRange< IndexType >::myEnd.
{
        ASSERT_TRUE(r.is_divisible(), "TBB Wrapper internal error\n");
        IndexType middle = r.myBegin + (r.myEnd - r.myBegin) / 2u;
        r.myEnd = middle;
        return middle;
    }
template<typename IndexType> bool corecvs::BlockedRange< IndexType >::empty () const [inline]
Definition at line 53 of file tbbWrapper.h.
    {
        return !(myBegin < myEnd);
    }
template<typename IndexType> IndexType corecvs::BlockedRange< IndexType >::end () const [inline]
Definition at line 38 of file tbbWrapper.h.
Referenced by corecvs::ParallelPrepareBlurBuffers::operator()(), corecvs::ParallelGetBestClassifier::operator()(), corecvs::PunchedBufferOperations< ThisTypeName, ElementType >::ParallelDensityCounter::operator()(), corecvs::BufferProcessor< InputBuffer, OutputBuffer, GenericKernelType, GAlgebraType >::ParallelProcess< shouldAlign >::operator()(), corecvs::BufferConverter< ReaderType, WriterType, GenericKernelType, GAlgebraType >::ParallelConverter::operator()(), corecvs::ParallelTriangulate< InputType >::operator()(), corecvs::IntegralBuffer< ElementType, BaseElementType, IndexType >::ParallelRectangularBlur< ReturnType >::operator()(), corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::operator()(), corecvs::BufferConverter< ReaderType, WriterType, GenericKernelType, GAlgebraType >::ParallelProcessAlign::operator()(), corecvs::DirectRemapper::ParallelRemap::operator()(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformationBl< ReturnType, DeformMapType >::operator()(), corecvs::AbstractContiniousBuffer< ElementType, IndexType >::ParallelDoReverseDeformation< ReturnType, DeformMapType >::operator()(), corecvs::AbstractBuffer< ElementType, IndexType >::ParallelDoConvolve< ReturnType, ConvElementType, ConvIndexType >::operator()(), and corecvs::AbstractBuffer< ElementType, IndexType >::ParallelDoConvolve1< ReturnType, ConvElementType, ConvIndexType >::operator()().
    {
        return myEnd;
    }
template<typename IndexType> bool corecvs::BlockedRange< IndexType >::is_divisible () const [inline]
Definition at line 58 of file tbbWrapper.h.
Referenced by corecvs::BlockedRange< IndexType >::do_split().
    {
        return myGrainsize < size();
    }
template<typename IndexType> size_type corecvs::BlockedRange< IndexType >::size () const [inline]
Definition at line 48 of file tbbWrapper.h.
    {
        return size_type(myEnd - myBegin);
    }
Member Data Documentation
template<typename IndexType> IndexType corecvs::BlockedRange< IndexType >::myBegin [private]
Definition at line 95 of file tbbWrapper.h.
Referenced by corecvs::BlockedRange< IndexType >::do_split().
template<typename IndexType> IndexType corecvs::BlockedRange< IndexType >::myEnd [private]
Definition at line 96 of file tbbWrapper.h.
Referenced by corecvs::BlockedRange< IndexType >::do_split().
template<typename IndexType> size_type corecvs::BlockedRange< IndexType >::myGrainsize [private]
Definition at line 97 of file tbbWrapper.h.
The documentation for this class was generated from the following file:
core/tbbwrapper/tbbWrapper.h