DeepView: UEyeCaptureInterface Class Reference
UEyeCaptureInterface Class Reference
#include <uEyeCapture.h>
Classes
class SpinThread
Public Types
enum CapErrorCode { SUCCESS = 0, SUCCESS_1CAM = 1, FAILURE = 2 }
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
UEyeCaptureInterface (string _devname)
virtual ~UEyeCaptureInterface ()
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode queryCameraParameters (CameraParameters &parameter)
Check if a specific property can be set/read and what values it can take.
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual FramePair getFrameRGB24 ()
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&)
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static int ueyeTrace (int)
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Static Public Attributes
static const double EXPOSURE_SCALER = 10.0
static const double FPS_SCALER = 100.0
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Private Types
enum SyncType {
NO_SYNC, SOFT_SYNC, HARD_SYNC, FRAME_HARD_SYNC,
EXT_SYNC
}
Private Member Functions
void decodeData (UEyeCameraDescriptor *camera, BufferDescriptorType *buffer, G12Buffer **output)
Private Attributes
string devname
Stores the device name.
SyncType sync
UEyeCameraDescriptor leftCamera
UEyeCameraDescriptor rightCamera
BufferDescriptorType * currentLeft
BufferDescriptorType * currentRight
SpinThread spin
Spin thread that blocks waiting for the frames.
QMutex protectFrame
This mutex protects both buffers from concurrent reading/writind If somebody is reading of modifying the buffer it should look the mutex.
QMutex spinRunning
volatile bool shouldStopSpinThread
PreciseTimer lastFrameTime
uint64_t frameDelay
uint64_t skippedCount
uint64_t triggerSkippedCount
uint64_t maxDesync
Maximum de-synchronization that we will not attempt to correct.
Detailed Description
Definition at line 29 of file uEyeCapture.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapErrorCode [inherited]
Enumerator:
SUCCESS
SUCCESS_1CAM
FAILURE
Reimplemented in DirectShowCaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 72 of file imageCaptureInterface.h.
    {
        SUCCESS       = 0,
        SUCCESS_1CAM  = 1,
        FAILURE      = 2
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
enum UEyeCaptureInterface::SyncType [private]
Enumerator:
NO_SYNC
SOFT_SYNC
HARD_SYNC
FRAME_HARD_SYNC
EXT_SYNC
Definition at line 72 of file uEyeCapture.h.
                  {
        NO_SYNC,
        SOFT_SYNC,
        HARD_SYNC,
        FRAME_HARD_SYNC,
        EXT_SYNC
    };
Constructor & Destructor Documentation
UEyeCaptureInterface::UEyeCaptureInterface (string _devname)
Definition at line 52 of file uEyeCapture.cpp.
References devname, EXT_SYNC, FRAME_HARD_SYNC, frameDelay, HARD_SYNC, UEyeCameraDescriptor::init(), leftCamera, NO_SYNC, rightCamera, skippedCount, SOFT_SYNC, sync, and triggerSkippedCount.
                                                          :
    sync(NO_SYNC),
    currentLeft(NULL),
    currentRight(NULL),
    spin(this)
{
    printf("#################################################   \n");
    printf("Hi, Stranger. I will help you with the uEye cameras.\n");
    printf("Remember, everything is in the eye of the beholder. \n");
    printf("#################################################   \n");
    int camNum = 0;
    is_GetNumberOfCameras (&camNum);
    printf("Currently there are %d cameras in the system:\n", camNum);
    UEYE_CAMERA_LIST *camList = (UEYE_CAMERA_LIST *)malloc(sizeof(ULONG) + camNum * sizeof(UEYE_CAMERA_INFO));
    camList->dwCount = camNum;
    is_GetCameraList(camList);
    printf("%2s %16s %5s %5s %5s %6s %16s\n",
            "N", "Model" ,"camId", "devId" ,"sensId", "inuse?", "Serial");
    for (int i = 0; i < camNum; i++)
    {
        printf("% 2d %16s % 5u % 5u %5u %6s %16s\n",
            i,
            camList->uci[i].Model,
            camList->uci[i].dwCameraID,
            camList->uci[i].dwDeviceID,
            camList->uci[i].dwSensorID,
            camList->uci[i].dwInUse != 0 ? "used" : "free",
            camList->uci[i].SerNo);
    }
    free(camList);
    this->devname = _devname;
    //     Group Number                   1       2 3        4 5          6 7             8 910   11     12 13     14 15                 16 17
    QRegExp deviceStringPattern(QString("^([^,:]*)(,([^:]*))?(:(\\d*)mhz)?(:([0-9.]*)fps)?(:((10)|(8))b)?(:x(\\d*))?(:(sync|hsync|fsync|esync))?(:(global))?$"));
    static const int Device1Group       = 1;
    static const int Device2Group       = 3;
    static const int PixelClockGroup    = 5;
    static const int FpsGroup           = 7;
    static const int BitsGroup          = 9;
    static const int BinningGroup       = 13;
    static const int SyncGroup          = 15;
    static const int GlobalShutterGroup = 17;
    //static const int WidthGroup       = 12;
    //static const int HeightGroup      = 13;
    printf ("Input string %s\n", _devname.c_str());
    QString qdevname(_devname.c_str());
    int result = deviceStringPattern.indexIn(qdevname);
    if (result == -1)
    {
        printf("Error in device string format:%s\n", _devname.c_str());
        exit(EXIT_FAILURE);
    }
    printf (
        "Parsed data:\n"
        "  | - Device 1=%s\n"
        "  | - Device 2=%s\n"
        "  | - Pixelclock %s Mhz, FPS %s\n"
        "  | - BPP:%s with bining %s\n"
        "  | - Sync:%s\n"
        "  \\ - GlobalShutter:%s\n",
        deviceStringPattern.cap(Device1Group).toAscii().constData(),
        deviceStringPattern.cap(Device2Group).toAscii().constData(),
        deviceStringPattern.cap(PixelClockGroup).toAscii().constData(),
        deviceStringPattern.cap(FpsGroup).toAscii().constData(),
        deviceStringPattern.cap(BitsGroup).toAscii().constData(),
        deviceStringPattern.cap(BinningGroup).toAscii().constData(),
        deviceStringPattern.cap(SyncGroup).toAscii().constData(),
        deviceStringPattern.cap(GlobalShutterGroup).toAscii().constData()
    );
    string leftName  = deviceStringPattern.cap(Device1Group).toAscii().constData();
    string rightName = deviceStringPattern.cap(Device2Group).toAscii().constData();
    bool err;
    int leftID =  deviceStringPattern.cap(Device1Group).toInt(&err);
    if (!err) {
        printf("Wrong left device ID (%s)\n", leftName.c_str());
    }
    int rightID =  deviceStringPattern.cap(Device2Group).toInt(&err);
    if (!err) {
        printf("Wrong right device ID (%s)\n", rightName.c_str());
    }
    int pixelClock = deviceStringPattern.cap(PixelClockGroup).toInt(&err);
    if (!err) pixelClock = 85;
    double fps = deviceStringPattern.cap(FpsGroup).toDouble(&err);
    if (!err) fps = 50.0;
/*    int width = deviceStringPattern.cap(WidthGroup).toInt(&err);
    if (!err || width <= 0) width = 800;
    int height = deviceStringPattern.cap(HeightGroup).toInt(&err);
    if (!err || height <= 0) height = 600;*/
    int binning = 1;
    binning = deviceStringPattern.cap(BinningGroup).toInt(&err);
    if (!err) binning = 1;
    sync = NO_SYNC;
    if (!deviceStringPattern.cap(SyncGroup).compare(QString("sync")))
        sync = SOFT_SYNC;
    if (!deviceStringPattern.cap(SyncGroup).compare(QString("hsync")))
        sync = HARD_SYNC;
    if (!deviceStringPattern.cap(SyncGroup).compare(QString("fsync")))
        sync = FRAME_HARD_SYNC;
    if (!deviceStringPattern.cap(SyncGroup).compare(QString("esync")))
        sync = EXT_SYNC;
    bool  globalShutter = false;
    if (!deviceStringPattern.cap(GlobalShutterGroup).compare(QString("global")))
        globalShutter = true;
    printf("Shutter is:%s\n", globalShutter ? "global" : "rolling");
    printf("Capture Left  device: GigE DeviceID = %d\n", leftID);
    printf("Capture Right device: GigE DeviceID = %d\n", rightID);
    leftCamera.init(leftID, (binning == 2), globalShutter, pixelClock, fps);
    rightCamera.init(rightID, (binning == 2), globalShutter, pixelClock, fps);
    skippedCount = 0;
    triggerSkippedCount = 0;
    frameDelay = 0;
}
UEyeCaptureInterface::~UEyeCaptureInterface () [virtual]
Definition at line 237 of file uEyeCapture.cpp.
References UEyeCameraDescriptor::deAllocImages(), leftCamera, UEyeCameraDescriptor::mCamera, rightCamera, shouldStopSpinThread, and spinRunning.
{
    cout << "Request for killing the thread" << endl;
    shouldStopSpinThread = true;
    bool result = spinRunning.tryLock(1000);
    is_DisableEvent(leftCamera.mCamera, IS_SET_EVENT_FRAME);
    is_DisableEvent(rightCamera.mCamera, IS_SET_EVENT_FRAME);
#ifdef Q_OS_WIN
    is_ExitEvent (leftCamera .mCamera, IS_SET_EVENT_FRAME);
    is_ExitEvent (rightCamera.mCamera, IS_SET_EVENT_FRAME);
    CloseHandle(leftCamera .mWinEvent);
    CloseHandle(rightCamera.mWinEvent);
#endif
    if (result)
        printf("Camera thread killed\n");
    else
        printf("Unable to exit Camera thread\n");
    printf("Deleting image buffers\n");
    leftCamera.deAllocImages();
    rightCamera.deAllocImages();
    printf("uEye: Closing camera...");
    is_ExitCamera(leftCamera.mCamera);
    is_ExitCamera(rightCamera.mCamera);
    printf("done\n");
}
Member Function Documentation
void UEyeCaptureInterface::decodeData (UEyeCameraDescriptor * camera, BufferDescriptorType * buffer, G12Buffer ** output) [private]
Definition at line 508 of file uEyeCapture.cpp.
References BufferDescriptorType::buffer, UEyeCameraDescriptor::bufferProps, sBufferProps::height, and sBufferProps::width.
Referenced by getFrame().
{
#if 0
    if (!buffer->isFilled)
    {
        *output = new G12Buffer(formatH, formatW);
        return;
    }
#endif
    *output = new G12Buffer(camera->bufferProps.height, camera->bufferProps.width, false);
    for (int i = 0; i < camera->bufferProps.height; i++)
    {
        uint16_t *lineIn  = ((uint16_t *)buffer->buffer) + camera->bufferProps.width * i;
        uint16_t *lineOut = &((*output)->element(i,0));
        for (int j = 0; j < camera->bufferProps.width; j++)
        {
            uint16_t value = *lineIn;
            //printf("%u\n", value);
            //value = (j % 256) | (i % 1024);
            //value >>= 4;
            *lineOut = value;
            lineOut++;
            lineIn++;
        }
    }
}
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureName (QString & value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 171 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode UEyeCaptureInterface::getCaptureProperty (int id, int * value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 699 of file uEyeCapture.cpp.
References CameraParameters::EXPOSURE, EXPOSURE_SCALER, ImageCaptureInterface::FAILURE, CameraParameters::FPS, FPS_SCALER, leftCamera, CameraParameters::MASTER_FLASH_DELAY, CameraParameters::MASTER_FLASH_DURATION, UEyeCameraDescriptor::mCamera, rightCamera, CameraParameters::SLAVE_TRIGGER_DELAY, ImageCaptureInterface::SUCCESS, and ueyeTrace().
{
 //   printf("Getting the values of capture properties is not supported for uEye interface yet.\n");
    switch (id)
    {
       case (CameraParameters::EXPOSURE):
       {
           double ms = 0.0;
           ueyeTrace(is_Exposure (leftCamera.mCamera , IS_EXPOSURE_CMD_GET_EXPOSURE, (void*)&ms, sizeof(double)));
           *value = ms * EXPOSURE_SCALER;
           return SUCCESS;
       }
       case (CameraParameters::FPS):
       {
           double newFps;
           ueyeTrace(is_SetFrameRate (leftCamera.mCamera , IS_GET_FRAMERATE, &newFps));
           *value = newFps * FPS_SCALER;
           return SUCCESS;
       }
       case (CameraParameters::MASTER_FLASH_DELAY):
       {
           IO_FLASH_PARAMS flashParams;
           flashParams.s32Delay    = 0;
           flashParams.u32Duration = 0;
           ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_GET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
           *value = flashParams.s32Delay;
           return SUCCESS;
       }
       case (CameraParameters::MASTER_FLASH_DURATION):
       {
           IO_FLASH_PARAMS flashParams;
           flashParams.s32Delay    = 0;
           flashParams.u32Duration = 0;
           ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_GET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
           *value = flashParams.u32Duration;
           return SUCCESS;
       }
       case (CameraParameters::SLAVE_TRIGGER_DELAY):
       {
           *value = is_SetTriggerDelay (rightCamera.mCamera, IS_GET_TRIGGER_DELAY);
           return SUCCESS;
       }
       default:
       {
           printf("Set request for unknown parameter (%d)\n", id);
           return ImageCaptureInterface::FAILURE;
       }
    }
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getDeviceName (int num, QString & name) [virtual, inherited]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented in DirectShowCaptureInterface, and V4L2CaptureInterface.
Definition at line 186 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getFormats (int * num, CameraFormat *&) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 176 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
UEyeCaptureInterface::FramePair UEyeCaptureInterface::getFrame () [virtual]
Main function to request frames from image interface.
Implements ImageCaptureInterface.
Definition at line 194 of file uEyeCapture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, currentLeft, currentRight, decodeData(), CaptureStatistics::DECODING_TIME, CaptureStatistics::DESYNC_TIME, frameDelay, CaptureStatistics::framesSkipped, UEyeCameraDescriptor::getTemperature(), CaptureStatistics::INTERFRAME_DELAY, CaptureStatistics::INTERNAL_DESYNC_TIME, BufferDescriptorType::internalTimestamp, leftCamera, ImageCaptureInterface::FramePair::leftTimeStamp, ImageCaptureInterface::newStatisticsReady(), protectFrame, rightCamera, ImageCaptureInterface::FramePair::rightTimeStamp, skippedCount, CaptureStatistics::temperature, CaptureStatistics::triggerSkipped, triggerSkippedCount, BufferDescriptorType::usecsTimeStamp(), corecvs::PreciseTimer::usecsToNow(), and CaptureStatistics::values.
{
    CaptureStatistics  stats;
    PreciseTimer start = PreciseTimer::currentTime();
    FramePair result( NULL, NULL);
//    printf("Called getFrame\n");
    protectFrame.lock();
        decodeData(&leftCamera , currentLeft,  &(result.bufferLeft));
        decodeData(&rightCamera, currentRight, &(result.bufferRight));
        result.leftTimeStamp  = currentLeft->usecsTimeStamp();
        result.rightTimeStamp = currentRight->usecsTimeStamp();
        stats.framesSkipped = skippedCount > 0 ? skippedCount - 1 : 0;
        skippedCount = 0;
        stats.triggerSkipped = triggerSkippedCount;
        triggerSkippedCount = 0;
        int64_t internalDesync =  currentLeft->internalTimestamp - currentRight->internalTimestamp;
    protectFrame.unlock();
    stats.values[CaptureStatistics::DECODING_TIME] = start.usecsToNow();
    stats.values[CaptureStatistics::INTERFRAME_DELAY] = frameDelay;
    int64_t desync =  result.leftTimeStamp - result.rightTimeStamp;
    stats.values[CaptureStatistics::DESYNC_TIME] = desync > 0 ? desync : -desync;
    stats.values[CaptureStatistics::INTERNAL_DESYNC_TIME] = internalDesync > 0 ? internalDesync : -internalDesync;
    /* Get temperature data */
    stats.temperature[0] = leftCamera.getTemperature();
    stats.temperature[1] = rightCamera.getTemperature();
    //stats.values[CaptureStatistics::DATA_SIZE] = currentLeft.bytesused;
    emit newStatisticsReady(stats);
//    printf("Finished getFrame\n");
    return result;
}
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual, inherited]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
QString ImageCaptureInterface::getInterfaceName () [virtual, inherited]
Return the interface device string.
Reimplemented in V4L2CaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 181 of file imageCaptureInterface.cpp.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
{
    return "";
}
ImageCaptureInterface::CapErrorCode UEyeCaptureInterface::initCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 538 of file uEyeCapture.cpp.
References UEyeCameraDescriptor::initBuffer(), leftCamera, and rightCamera.
{
    int resR = leftCamera .initBuffer();
    int resL = rightCamera.initBuffer();
#if 0
    /* If only one camera started, we assume it is the left camera */
    if (resL && !resR)
    {
        UEyeCameraDescriptor tmp;
        tmp = leftCamera;
        left = rightCamera;
        right = tmp;
    }
#endif
    return (CapErrorCode) ((bool) resL + (bool) resR);
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode UEyeCaptureInterface::queryCameraParameters (CameraParameters & parameter) [virtual]
Check if a specific property can be set/read and what values it can take.
Reimplemented from ImageCaptureInterface.
Definition at line 562 of file uEyeCapture.cpp.
References CameraParameters::EXPOSURE, CameraParameters::EXPOSURE_AUTO, EXPOSURE_SCALER, CameraParameters::FPS, FPS_SCALER, leftCamera, CameraParameters::MASTER_FLASH_DELAY, CameraParameters::MASTER_FLASH_DURATION, UEyeCameraDescriptor::mCamera, CameraParameters::mCameraControls, CaptureParameter::pushMenuItem(), rightCamera, CaptureParameter::setActive(), CaptureParameter::setDefaultValue(), CaptureParameter::setIsMenu(), CaptureParameter::setMaximum(), CaptureParameter::setMinimum(), CaptureParameter::setStep(), CameraParameters::SLAVE_TRIGGER_DELAY, ImageCaptureInterface::SUCCESS, and ueyeTrace().
{
    /* Exposure */
    double defaultExp;
    double minExp;
    double maxExp;
    double stepExp;
    ueyeTrace(is_Exposure (leftCamera.mCamera , IS_EXPOSURE_CMD_GET_EXPOSURE_DEFAULT, (void*)&defaultExp, sizeof(double)));
    ueyeTrace(is_Exposure (leftCamera.mCamera , IS_EXPOSURE_CMD_GET_EXPOSURE_RANGE_MIN, (void*)&minExp,   sizeof(double)));
    ueyeTrace(is_Exposure (leftCamera.mCamera , IS_EXPOSURE_CMD_GET_EXPOSURE_RANGE_MAX, (void*)&maxExp,   sizeof(double)));
    ueyeTrace(is_Exposure (leftCamera.mCamera , IS_EXPOSURE_CMD_GET_EXPOSURE_RANGE_INC, (void*)&stepExp,  sizeof(double)));
    CaptureParameter *param = &(params.mCameraControls[CameraParameters::EXPOSURE]);
    param->setActive(true);
    param->setDefaultValue(defaultExp * EXPOSURE_SCALER);
    param->setMinimum     (minExp     * EXPOSURE_SCALER);
    param->setMaximum     (maxExp     * EXPOSURE_SCALER);
    param->setStep        (stepExp    * EXPOSURE_SCALER);
    /* Exposure auto*/
    param = &(params.mCameraControls[CameraParameters::EXPOSURE_AUTO]);
    *param = CaptureParameter();
    param->setActive(true);
    param->setDefaultValue(0);
    param->setMinimum(0);
    param->setMaximum(1);
    param->setStep(1);
    param->setIsMenu(true);
    param->pushMenuItem(QString("False"), 0);
    param->pushMenuItem(QString("True") , 1);
    /* Gain */
    /* Frame rate */
    param = &(params.mCameraControls[CameraParameters::FPS]);
    param->setActive(true);
    param->setDefaultValue(25 * FPS_SCALER);
    param->setMinimum     (0  * FPS_SCALER);
    param->setMaximum     (50 * FPS_SCALER);
    param->setStep        (1);
    param = &(params.mCameraControls[CameraParameters::MASTER_FLASH_DELAY]);
    param->setActive      (true);
    param->setDefaultValue(0);
    param->setMinimum     (-500000);
    param->setMaximum     (500000);
    param->setStep        (1);
    param = &(params.mCameraControls[CameraParameters::MASTER_FLASH_DURATION]);
    param->setActive      (true);
    param->setDefaultValue(0);
    param->setMinimum     (0);
    param->setMaximum     (500000);
    param->setStep        (1);
    param = &(params.mCameraControls[CameraParameters::SLAVE_TRIGGER_DELAY]);
    param->setActive      (true);
    param->setDefaultValue(0);
    param->setMinimum     (is_SetTriggerDelay (rightCamera.mCamera, IS_GET_MIN_TRIGGER_DELAY));
    param->setMaximum     (is_SetTriggerDelay (rightCamera.mCamera, IS_GET_MAX_TRIGGER_DELAY));
    param->setStep        (is_SetTriggerDelay (rightCamera.mCamera, IS_GET_TRIGGER_DELAY_GRANULARITY));
    return ImageCaptureInterface::SUCCESS;
}
UEyeCaptureInterface::CapErrorCode UEyeCaptureInterface::setCaptureProperty (int id, int value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 633 of file uEyeCapture.cpp.
References CameraParameters::EXPOSURE, CameraParameters::EXPOSURE_AUTO, EXPOSURE_SCALER, ImageCaptureInterface::FAILURE, CameraParameters::FPS, FPS_SCALER, leftCamera, CameraParameters::MASTER_FLASH_DELAY, CameraParameters::MASTER_FLASH_DURATION, UEyeCameraDescriptor::mCamera, rightCamera, CameraParameters::SLAVE_TRIGGER_DELAY, ImageCaptureInterface::SUCCESS, and ueyeTrace().
{
    int retL = 0;
    int retR = 0;
    switch (id)
    {
        case (CameraParameters::EXPOSURE):
        {
            double ms = 0.0;
            ms = (double)value / EXPOSURE_SCALER;
            ueyeTrace(is_Exposure (leftCamera.mCamera , IS_EXPOSURE_CMD_SET_EXPOSURE, (void*)&ms, sizeof(double)));
            ms = (double)value / EXPOSURE_SCALER;
            ueyeTrace(is_Exposure (rightCamera.mCamera, IS_EXPOSURE_CMD_SET_EXPOSURE, (void*)&ms, sizeof(double)));
            return SUCCESS;
        }
        case (CameraParameters::FPS):
        {
            double fps = (double)value / FPS_SCALER;
            double newFps;
            ueyeTrace(is_SetFrameRate (leftCamera.mCamera , fps, &newFps));
            ueyeTrace(is_SetFrameRate (rightCamera.mCamera, fps, &newFps));
            return SUCCESS;
        }
        case (CameraParameters::MASTER_FLASH_DELAY):
        {
            IO_FLASH_PARAMS flashParams;
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 0;
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_GET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            flashParams.s32Delay = value;
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            return SUCCESS;
        }
        case (CameraParameters::MASTER_FLASH_DURATION):
        {
            IO_FLASH_PARAMS flashParams;
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 0;
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_GET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            flashParams.u32Duration = value;
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            return SUCCESS;
        }
        case (CameraParameters::SLAVE_TRIGGER_DELAY):
        {
            is_SetTriggerDelay (rightCamera.mCamera, value);
            return SUCCESS;
        }
        case (CameraParameters::EXPOSURE_AUTO) :
        {
            double enable = value;
            ueyeTrace(is_SetAutoParameter(leftCamera.mCamera, IS_SET_ENABLE_AUTO_SHUTTER, &enable, 0));
            return SUCCESS;
        }
        default:
        {
            printf("Set request for unknown parameter (%d)\n", id);
            return ImageCaptureInterface::FAILURE;
        }
    }
    return (ImageCaptureInterface::CapErrorCode) ((bool) retL + (bool) retR);
}
ImageCaptureInterface::CapErrorCode UEyeCaptureInterface::startCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 271 of file uEyeCapture.cpp.
References EXT_SYNC, FRAME_HARD_SYNC, HARD_SYNC, leftCamera, UEyeCameraDescriptor::mCamera, NO_SYNC, rightCamera, shouldStopSpinThread, SOFT_SYNC, spin, ImageCaptureInterface::SUCCESS, sync, and ueyeTrace().
{
    qDebug("Start capture");
    printf("Enabling events...\n");
#ifdef Q_OS_WIN
    leftCamera.mWinEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
    is_InitEvent(leftCamera.mCamera, leftCamera.mWinEvent, IS_SET_EVENT_FRAME);
    rightCamera.mWinEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
    is_InitEvent(rightCamera.mCamera, rightCamera.mWinEvent, IS_SET_EVENT_FRAME);
#endif
    is_EnableEvent(leftCamera.mCamera, IS_SET_EVENT_FRAME);
    is_EnableEvent(rightCamera.mCamera, IS_SET_EVENT_FRAME);
    switch (sync)
    {
        case NO_SYNC:
            is_CaptureVideo (leftCamera.mCamera, IS_DONT_WAIT);
            is_CaptureVideo (rightCamera.mCamera, IS_DONT_WAIT);
            break;
        case SOFT_SYNC:
            is_SetExternalTrigger (leftCamera.mCamera , IS_SET_TRIGGER_SOFTWARE);
            is_SetExternalTrigger (rightCamera.mCamera, IS_SET_TRIGGER_SOFTWARE);
            break;
        case HARD_SYNC:
        {
            /* Should make a check that connection exist */
            /*Left camera will generate flash*/
            UINT nMode = IO_FLASH_MODE_FREERUN_HI_ACTIVE;
            printf("Setting left flash IO_FLASH_MODE_FREERUN_HI_ACTIVE...\n");
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_MODE, (void*)&nMode, sizeof(nMode)));
            /* Switching on leftCamera flash that will become right camera trigger */
            printf("Setting left flash duration and delay...\n");
            IO_FLASH_PARAMS flashParams;
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 5000;  // in us
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            /*right camera will generate flash also (for debug)*/
            nMode = IO_FLASH_MODE_FREERUN_HI_ACTIVE;
            printf("Setting right flash IO_FLASH_MODE_FREERUN_HI_ACTIVE...\n");
            ueyeTrace(is_IO(rightCamera.mCamera, IS_IO_CMD_FLASH_SET_MODE, (void*)&nMode, sizeof(nMode)));
            /* Switching on leftCamera flash that will become right camera trigger */
            printf("Setting right flash duration and delay...\n");
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 5000;
            ueyeTrace(is_IO(rightCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            /* Right camera is trigger based */
            ueyeTrace(is_SetExternalTrigger (rightCamera.mCamera, IS_SET_TRIGGER_LO_HI));
            //ueyeTrace(is_SetExternalTrigger (rightCamera.mCamera, IS_SET_TRIGGER_HI_LO));
            printf("Launching both cameras run...\n");
            /* Left camera is in free run mode */
            ueyeTrace(is_CaptureVideo (leftCamera.mCamera, IS_DONT_WAIT));
            /* Same for the right camera */
            ueyeTrace(is_CaptureVideo (rightCamera.mCamera, IS_DONT_WAIT));
            break;
        }
        case FRAME_HARD_SYNC:
        {
            /* TODO: Should make a check that connection exist */
            /* Both cams are now trigger based*/
            ueyeTrace(is_SetExternalTrigger (leftCamera.mCamera, IS_SET_TRIGGER_OFF));
            /*Left camera will generate flash*/
            UINT nMode = IO_FLASH_MODE_FREERUN_HI_ACTIVE;
            printf("Setting left flash IO_FLASH_MODE_TRIGGER_HI_ACTIVE...\n");
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_MODE, (void*)&nMode, sizeof(nMode)));
            /* Switching on leftCamera flash that will become right camera trigger */
            printf("Setting left flash duration and delay...\n");
            IO_FLASH_PARAMS flashParams;
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 5000;
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            printf("Setting right camera to TRIGGER MODE...\n");
            ueyeTrace(is_SetExternalTrigger (rightCamera.mCamera, IS_SET_TRIGGER_LO_HI   ));
            /*right camera will generate flash also (for debug)*/
            nMode = IO_FLASH_MODE_TRIGGER_HI_ACTIVE;
            printf("Setting right flash IO_FLASH_MODE_TRIGGER_HI_ACTIVE...\n");
            ueyeTrace(is_IO(rightCamera.mCamera, IS_IO_CMD_FLASH_SET_MODE, (void*)&nMode, sizeof(nMode)));
            /* Switching on leftCamera flash that will become right camera trigger */
            printf("Setting right flash duration and delay...\n");
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 5000;
            ueyeTrace(is_IO(rightCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            break;
        }
        case EXT_SYNC:
        {
            printf("Running on external syncro...\n");
            /* Setting triggers for both cams*/
            printf("Setting left camera to TRIGGER MODE...\n");
            ueyeTrace(is_SetExternalTrigger (leftCamera.mCamera, IS_SET_TRIGGER_LO_HI));
            printf("Setting right camera to TRIGGER MODE...\n");
            ueyeTrace(is_SetExternalTrigger (rightCamera.mCamera,IS_SET_TRIGGER_LO_HI));
            /*Left camera will generate flash*/
            UINT nMode = IO_FLASH_MODE_TRIGGER_HI_ACTIVE;
            printf("Setting left flash IO_FLASH_MODE_TRIGGER_HI_ACTIVE...\n");
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_MODE, (void*)&nMode, sizeof(nMode)));
            /* Switching on leftCamera flash that will become right camera trigger */
            printf("Setting left flash duration and delay...\n");
            IO_FLASH_PARAMS flashParams;
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 5000;
            ueyeTrace(is_IO(leftCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            /*right camera will generate flash also (for debug)*/
            nMode = IO_FLASH_MODE_TRIGGER_HI_ACTIVE;
            printf("Setting right flash IO_FLASH_MODE_TRIGGER_HI_ACTIVE...\n");
            ueyeTrace(is_IO(rightCamera.mCamera, IS_IO_CMD_FLASH_SET_MODE, (void*)&nMode, sizeof(nMode)));
            /* Switching on leftCamera flash that will become right camera trigger */
            printf("Setting right flash duration and delay...\n");
            flashParams.s32Delay    = 0;
            flashParams.u32Duration = 5000;
            ueyeTrace(is_IO(rightCamera.mCamera, IS_IO_CMD_FLASH_SET_PARAMS, (void*)&flashParams, sizeof(flashParams)));
            /* Left camera is repeated run mode */
            ueyeTrace(is_CaptureVideo (leftCamera.mCamera, IS_DONT_WAIT));
            /* Same for the right camera */
            ueyeTrace(is_CaptureVideo (rightCamera.mCamera, IS_DONT_WAIT));
            break;
        }
    }
    shouldStopSpinThread = false;
    spin.start();
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
int UEyeCaptureInterface::ueyeTrace (int result) [static]
Definition at line 37 of file uEyeCapture.cpp.
Referenced by getCaptureProperty(), queryCameraParameters(), UEyeCaptureInterface::SpinThread::run(), setCaptureProperty(), and startCapture().
{
    if (result != IS_SUCCESS)
    {
        char * str = 0;
        is_GetError(1,&result,&str);
        printf("   UEYE: Function failed with error code %d. Error string: %s\n", result, str);
    }
    return result;
}
Member Data Documentation
BufferDescriptorType* UEyeCaptureInterface::currentLeft [private]
Definition at line 87 of file uEyeCapture.h.
Referenced by getFrame(), and UEyeCaptureInterface::SpinThread::run().
BufferDescriptorType* UEyeCaptureInterface::currentRight [private]
Definition at line 88 of file uEyeCapture.h.
Referenced by getFrame(), and UEyeCaptureInterface::SpinThread::run().
string UEyeCaptureInterface::devname [private]
Stores the device name.
Definition at line 70 of file uEyeCapture.h.
Referenced by UEyeCaptureInterface().
const double UEyeCaptureInterface::EXPOSURE_SCALER = 10.0 [static]
Definition at line 52 of file uEyeCapture.h.
Referenced by getCaptureProperty(), queryCameraParameters(), and setCaptureProperty().
const double UEyeCaptureInterface::FPS_SCALER = 100.0 [static]
Definition at line 53 of file uEyeCapture.h.
Referenced by getCaptureProperty(), queryCameraParameters(), and setCaptureProperty().
uint64_t UEyeCaptureInterface::frameDelay [private]
Definition at line 100 of file uEyeCapture.h.
Referenced by getFrame(), UEyeCaptureInterface::SpinThread::run(), and UEyeCaptureInterface().
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
PreciseTimer UEyeCaptureInterface::lastFrameTime [private]
Definition at line 99 of file uEyeCapture.h.
Referenced by UEyeCaptureInterface::SpinThread::run().
UEyeCameraDescriptor UEyeCaptureInterface::leftCamera [private]
Definition at line 84 of file uEyeCapture.h.
Referenced by getCaptureProperty(), getFrame(), initCapture(), queryCameraParameters(), UEyeCaptureInterface::SpinThread::run(), setCaptureProperty(), startCapture(), UEyeCaptureInterface(), and ~UEyeCaptureInterface().
uint64_t UEyeCaptureInterface::maxDesync [private]
Maximum de-synchronization that we will not attempt to correct.
Definition at line 105 of file uEyeCapture.h.
QMutex UEyeCaptureInterface::protectFrame [private]
This mutex protects both buffers from concurrent reading/writind If somebody is reading of modifying the buffer it should look the mutex.
Definition at line 92 of file uEyeCapture.h.
Referenced by getFrame(), and UEyeCaptureInterface::SpinThread::run().
UEyeCameraDescriptor UEyeCaptureInterface::rightCamera [private]
Definition at line 85 of file uEyeCapture.h.
Referenced by getCaptureProperty(), getFrame(), initCapture(), queryCameraParameters(), UEyeCaptureInterface::SpinThread::run(), setCaptureProperty(), startCapture(), UEyeCaptureInterface(), and ~UEyeCaptureInterface().
volatile bool UEyeCaptureInterface::shouldStopSpinThread [private]
Definition at line 96 of file uEyeCapture.h.
Referenced by UEyeCaptureInterface::SpinThread::run(), startCapture(), and ~UEyeCaptureInterface().
uint64_t UEyeCaptureInterface::skippedCount [private]
Definition at line 102 of file uEyeCapture.h.
Referenced by getFrame(), UEyeCaptureInterface::SpinThread::run(), and UEyeCaptureInterface().
SpinThread UEyeCaptureInterface::spin [private]
Spin thread that blocks waiting for the frames.
Definition at line 91 of file uEyeCapture.h.
Referenced by startCapture().
QMutex UEyeCaptureInterface::spinRunning [private]
Definition at line 95 of file uEyeCapture.h.
Referenced by UEyeCaptureInterface::SpinThread::run(), and ~UEyeCaptureInterface().
SyncType UEyeCaptureInterface::sync [private]
Definition at line 80 of file uEyeCapture.h.
Referenced by UEyeCaptureInterface::SpinThread::run(), startCapture(), and UEyeCaptureInterface().
uint64_t UEyeCaptureInterface::triggerSkippedCount [private]
Definition at line 103 of file uEyeCapture.h.
Referenced by getFrame(), UEyeCaptureInterface::SpinThread::run(), and UEyeCaptureInterface().
The documentation for this class was generated from the following files:
utils/framesources/uEyeCapture.h
utils/framesources/uEyeCapture.cpp