DeepView: InputSelectorWidget Class Reference
InputSelectorWidget Class Reference
#include <inputSelectorWidget.h>
Signals
void newInputString ()
Public Member Functions
InputSelectorWidget (QWidget *parent=0)
~InputSelectorWidget ()
QString getInputString ()
void setInputString (const QString &str)
Private Attributes
Ui::InputSelectorWidgetClass ui
Detailed Description
Definition at line 7 of file inputSelectorWidget.h.
Constructor & Destructor Documentation
InputSelectorWidget::InputSelectorWidget (QWidget * parent = 0)
Definition at line 3 of file inputSelectorWidget.cpp.
References newInputString(), and ui.
    : QWidget(parent)
{
    ui.setupUi(this);
    connect(ui.okPushButton, SIGNAL(pressed()), this, SIGNAL(newInputString()));
}
InputSelectorWidget::~InputSelectorWidget ()
Definition at line 21 of file inputSelectorWidget.cpp.
{
}
Member Function Documentation
QString InputSelectorWidget::getInputString ()
Definition at line 10 of file inputSelectorWidget.cpp.
References ui.
Referenced by BaseHostDialog::doOpenInput().
{
    return ui.inputLineEdit->text();
}
void InputSelectorWidget::newInputString () [signal]
Referenced by InputSelectorWidget().
void InputSelectorWidget::setInputString (const QString & str)
Definition at line 15 of file inputSelectorWidget.cpp.
References ui.
Referenced by BaseHostDialog::initCapture().
{
    ui.inputLineEdit->setText(str);
}
Member Data Documentation
Ui::InputSelectorWidgetClass InputSelectorWidget::ui [private]
Definition at line 22 of file inputSelectorWidget.h.
Referenced by getInputString(), InputSelectorWidget(), and setInputString().
The documentation for this class was generated from the following files:
utils/widgets/inputSelectorWidget.h
utils/widgets/inputSelectorWidget.cpp