DeepView: tinyxml2::XMLDocument Class Reference
tinyxml2::XMLDocument Class Reference
A Document binds together all the functionality.
#include <tinyxml2.h>
Public Member Functions
XMLDocument (bool processEntities=true, Whitespace=PRESERVE_WHITESPACE)
constructor
~XMLDocument ()
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual const XMLDocument * ToDocument () const
XMLError Parse (const char *xml, size_t nBytes=(size_t)(-1))
Parse an XML file from a character string.
XMLError LoadFile (const char *filename)
Load an XML file from disk.
XMLError LoadFile (std::FILE *)
Load an XML file from disk.
XMLError SaveFile (const char *filename, bool compact=false)
Save the XML file to disk.
XMLError SaveFile (std::FILE *fp, bool compact=false)
Save the XML file to disk.
bool ProcessEntities () const
Whitespace WhitespaceMode () const
bool HasBOM () const
Returns true if this document has a leading Byte Order Mark of UTF8.
void SetBOM (bool useBOM)
Sets whether to write the BOM when writing the file.
XMLElement * RootElement ()
Return the root element of DOM.
const XMLElement * RootElement () const
void Print (XMLPrinter *streamer=0)
Print the Document.
virtual bool Accept (XMLVisitor *visitor) const
Accept a hierarchical visit of the nodes in the TinyXML DOM.
XMLElement * NewElement (const char *name)
Create a new Element associated with this Document.
XMLComment * NewComment (const char *comment)
Create a new Comment associated with this Document.
XMLText * NewText (const char *text)
Create a new Text associated with this Document.
XMLDeclaration * NewDeclaration (const char *text=0)
Create a new Declaration associated with this Document.
XMLUnknown * NewUnknown (const char *text)
Create a new Unknown associated with this Document.
void DeleteNode (XMLNode *node)
Delete a node associated with this document.
void SetError (XMLError error, const char *str1, const char *str2)
bool Error () const
Return true if there was an error parsing the document.
XMLError ErrorID () const
Return the errorID.
const char * GetErrorStr1 () const
Return a possibly helpful diagnostic location or string.
const char * GetErrorStr2 () const
Return a possibly helpful secondary diagnostic location or string.
void PrintError () const
If there is an error, print it to stdout.
char * Identify (char *p, XMLNode **node)
virtual XMLNode * ShallowClone (XMLDocument *) const
Make a copy of this node, but not its children.
virtual bool ShallowEqual (const XMLNode *) const
Test if 2 nodes are the same, but don't test children.
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual const XMLText * ToText () const
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual const XMLComment * ToComment () const
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual const XMLDeclaration * ToDeclaration () const
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
The meaning of 'value' changes for the specific type.
void SetValue (const char *val, bool staticMem=false)
Set the Value of an XML node.
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
Get the first child element, or optionally the first child element with the specified name.
XMLElement * FirstChildElement (const char *value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
Get the last child element or optionally the last child element with the specified name.
XMLElement * LastChildElement (const char *value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an opitionally supplied name.
XMLElement * PreviousSiblingElement (const char *value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an opitionally supplied name.
XMLElement * NextSiblingElement (const char *value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
Add a child node as the last (right) child.
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
Add a child node as the first (left) child.
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
Add a node after the specified child node.
void DeleteChildren ()
Delete all the children of this node.
void DeleteChild (XMLNode *node)
Delete a child of this node.
virtual char * ParseDeep (char *, StrPair *)
Protected Attributes
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
Private Member Functions
XMLDocument (const XMLDocument &)
void operator= (const XMLDocument &)
void InitDocument ()
Private Attributes
bool _writeBOM
bool _processEntities
XMLError _errorID
Whitespace _whitespace
const char * _errorStr1
const char * _errorStr2
char * _charBuffer
MemPoolT< sizeof(XMLElement) > _elementPool
MemPoolT< sizeof(XMLAttribute) > _attributePool
MemPoolT< sizeof(XMLText) > _textPool
MemPoolT< sizeof(XMLComment) > _commentPool
Friends
class XMLElement
Detailed Description
A Document binds together all the functionality.
It can be saved, loaded, and printed to the screen. All Nodes are connected and allocated to a Document. If the Document is deleted, all its Nodes are also deleted.
Definition at line 1358 of file tinyxml2.h.
Constructor & Destructor Documentation
tinyxml2::XMLDocument::XMLDocument (bool processEntities = true, Whitespace whitespace = PRESERVE_WHITESPACE)
constructor
Definition at line 1491 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document.
                                                                      :
    XMLNode( 0 ),
    _writeBOM( false ),
    _processEntities( processEntities ),
    _errorID( XML_NO_ERROR ),
    _whitespace( whitespace ),
    _errorStr1( 0 ),
    _errorStr2( 0 ),
    _charBuffer( 0 )
{
    _document = this;   // avoid warning about 'this' in initializer list
}
tinyxml2::XMLDocument::~XMLDocument ()
Definition at line 1505 of file tinyxml2.cpp.
References _attributePool, _charBuffer, _commentPool, _elementPool, _textPool, tinyxml2::MemPoolT< SIZE >::CurrentAllocs(), tinyxml2::XMLNode::DeleteChildren(), Error(), TIXMLASSERT, and tinyxml2::MemPoolT< SIZE >::Untracked().
{
    DeleteChildren();
    delete [] _charBuffer;
#if 0
    textPool.Trace( "text" );
    elementPool.Trace( "element" );
    commentPool.Trace( "comment" );
    attributePool.Trace( "attribute" );
#endif
#ifdef DEBUG
    if ( Error() == false ) {
        TIXMLASSERT( _elementPool.CurrentAllocs()   == _elementPool.Untracked() );
        TIXMLASSERT( _attributePool.CurrentAllocs() == _attributePool.Untracked() );
        TIXMLASSERT( _textPool.CurrentAllocs()      == _textPool.Untracked() );
        TIXMLASSERT( _commentPool.CurrentAllocs()   == _commentPool.Untracked() );
    }
#endif
}
tinyxml2::XMLDocument::XMLDocument (const XMLDocument &) [private]
Member Function Documentation
bool tinyxml2::XMLDocument::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
        TiXmlPrinter printer;
        tinyxmlDoc.Accept( &printer );
        const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Definition at line 570 of file tinyxml2.cpp.
References tinyxml2::XMLNode::NextSibling(), tinyxml2::XMLVisitor::VisitEnter(), and tinyxml2::XMLVisitor::VisitExit().
Referenced by Print().
{
    if ( visitor->VisitEnter( *this ) ) {
        for ( const XMLNode* node=FirstChild(); node; node=node->NextSibling() ) {
            if ( !node->Accept( visitor ) ) {
                break;
            }
        }
    }
    return visitor->VisitExit( *this );
}
void tinyxml2::XMLNode::DeleteChild (XMLNode * node) [inherited]
Delete a child of this node.
Definition at line 646 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_parent, DELETE_NODE, and TIXMLASSERT.
Referenced by DeleteNode().
{
    TIXMLASSERT( node->_parent == this );
    DELETE_NODE( node );
}
void tinyxml2::XMLNode::DeleteChildren () [inherited]
Delete all the children of this node.
Definition at line 614 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_lastChild, DELETE_NODE, and tinyxml2::XMLNode::Unlink().
Referenced by LoadFile(), Parse(), ~XMLDocument(), and tinyxml2::XMLNode::~XMLNode().
{
    while( _firstChild ) {
        XMLNode* node = _firstChild;
        Unlink( node );
        DELETE_NODE( node );
    }
    _firstChild = _lastChild = 0;
}
void tinyxml2::XMLDocument::DeleteNode (XMLNode * node) [inline]
Delete a node associated with this document.
It will be unlinked from the DOM.
Definition at line 1504 of file tinyxml2.h.
References tinyxml2::XMLNode::_parent, and tinyxml2::XMLNode::DeleteChild().
{
        node->_parent->DeleteChild( node );
    }
bool tinyxml2::XMLDocument::Error () const [inline]
Return true if there was an error parsing the document.
Definition at line 1511 of file tinyxml2.h.
References _errorID, and tinyxml2::XML_NO_ERROR.
Referenced by corecvs::FilterGraph::deserialize(), corecvs::FiltersCollection::getContainedBlocks(), tinyxml2::XMLNode::ParseDeep(), and ~XMLDocument().
                       {
        return _errorID != XML_NO_ERROR;
    }
XMLError tinyxml2::XMLDocument::ErrorID () const [inline]
Return the errorID.
Definition at line 1515 of file tinyxml2.h.
References _errorID.
{
        return _errorID;
    }
const XMLNode* tinyxml2::XMLNode::FirstChild () const [inline, inherited]
Get the first child node, or null if none exists.
Definition at line 633 of file tinyxml2.h.
References tinyxml2::XMLNode::_firstChild.
Referenced by tinyxml2::XMLElement::Accept(), corecvs::FilterGraph::deserialize(), corecvs::FilterBlock::deserialize(), corecvs::FilterBlock::deserializePins(), corecvs::FiltersCollection::FiltersCollection(), tinyxml2::XMLHandle::FirstChild(), tinyxml2::XMLConstHandle::FirstChild(), corecvs::FiltersCollection::getContainedBlocks(), tinyxml2::XMLElement::GetText(), corecvs::CompoundFilter::loadGraph(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), and tinyxml2::XMLElement::QueryUnsignedText().
{
        return _firstChild;
    }
XMLNode* tinyxml2::XMLNode::FirstChild () [inline, inherited]
Definition at line 637 of file tinyxml2.h.
References tinyxml2::XMLNode::_firstChild.
{
        return _firstChild;
    }
const XMLElement * tinyxml2::XMLNode::FirstChildElement (const char * value = 0) const [inherited]
Get the first child element, or optionally the first child element with the specified name.
Definition at line 725 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_next, tinyxml2::XMLElement::Name(), tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLHandle::FirstChildElement(), tinyxml2::XMLConstHandle::FirstChildElement(), RootElement(), and corecvs::DeserializerVisitor::visit().
{
    for( XMLNode* node=_firstChild; node; node=node->_next ) {
        XMLElement* element = node->ToElement();
        if ( element ) {
            if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                return element;
            }
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::FirstChildElement (const char * value = 0) [inline, inherited]
Definition at line 646 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->FirstChildElement( value ));
    }
const XMLDocument* tinyxml2::XMLNode::GetDocument () const [inline, inherited]
Get the XMLDocument that owns this XMLNode.
Definition at line 548 of file tinyxml2.h.
References tinyxml2::XMLNode::_document.
Referenced by corecvs::BinarizeBlock::serialize(), corecvs::ThickeningBlock::serialize(), corecvs::MaskFilterBlock::serialize(), corecvs::BackgroundFilter::serialize(), corecvs::BitSelectorFilter::serialize(), corecvs::SobelFilter::serialize(), corecvs::GainOffsetFilter::serialize(), corecvs::CannyFilter::serialize(), corecvs::InputFilter::serialize(), corecvs::Pin::serialize(), corecvs::OutputFilter::serialize(), corecvs::FilterBlock::serialize(), corecvs::OperationFilter::serialize(), and corecvs::SerializerVisitor::visit().
{
        return _document;
    }
XMLDocument* tinyxml2::XMLNode::GetDocument () [inline, inherited]
Get the XMLDocument that owns this XMLNode.
Definition at line 552 of file tinyxml2.h.
References tinyxml2::XMLNode::_document.
{
        return _document;
    }
const char* tinyxml2::XMLDocument::GetErrorStr1 () const [inline]
Return a possibly helpful diagnostic location or string.
Definition at line 1519 of file tinyxml2.h.
References _errorStr1.
{
        return _errorStr1;
    }
const char* tinyxml2::XMLDocument::GetErrorStr2 () const [inline]
Return a possibly helpful secondary diagnostic location or string.
Definition at line 1523 of file tinyxml2.h.
References _errorStr2.
{
        return _errorStr2;
    }
bool tinyxml2::XMLDocument::HasBOM () const [inline]
Returns true if this document has a leading Byte Order Mark of UTF8.
Definition at line 1427 of file tinyxml2.h.
References _writeBOM.
Referenced by tinyxml2::XMLPrinter::VisitEnter().
{
        return _writeBOM;
    }
char * tinyxml2::XMLDocument::Identify (char * p, XMLNode ** node)
Definition at line 495 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_memPool, tinyxml2::XMLText::SetCData(), and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::ParseDeep().
{
    XMLNode* returnNode = 0;
    char* start = p;
    p = XMLUtil::SkipWhiteSpace( p );
    if( !p || !*p ) {
        return p;
    }
    // What is this thing?
    // - Elements start with a letter or underscore, but xml is reserved.
    // - Comments: <!--
    // - Decleration: <?
    // - Everthing else is unknown to tinyxml.
    //
    static const char* xmlHeader        = { "<?" };
    static const char* commentHeader    = { "<!--" };
    static const char* dtdHeader        = { "<!" };
    static const char* cdataHeader      = { "<![CDATA[" };
    static const char* elementHeader    = { "<" };  // and a header for everything else; check last.
    static const int xmlHeaderLen       = 2;
    static const int commentHeaderLen   = 4;
    static const int dtdHeaderLen       = 2;
    static const int cdataHeaderLen     = 9;
    static const int elementHeaderLen   = 1;
#if defined(_MSC_VER)
#pragma warning (push)
#pragma warning (disable : 4127)
#endif
    TIXMLASSERT( sizeof( XMLComment ) == sizeof( XMLUnknown ) );        // use same memory pool
    TIXMLASSERT( sizeof( XMLComment ) == sizeof( XMLDeclaration ) );    // use same memory pool
#if defined(_MSC_VER)
#pragma warning (pop)
#endif
    if ( XMLUtil::StringEqual( p, xmlHeader, xmlHeaderLen ) ) {
        returnNode = new (_commentPool.Alloc()) XMLDeclaration( this );
        returnNode->_memPool = &_commentPool;
        p += xmlHeaderLen;
    }
    else if ( XMLUtil::StringEqual( p, commentHeader, commentHeaderLen ) ) {
        returnNode = new (_commentPool.Alloc()) XMLComment( this );
        returnNode->_memPool = &_commentPool;
        p += commentHeaderLen;
    }
    else if ( XMLUtil::StringEqual( p, cdataHeader, cdataHeaderLen ) ) {
        XMLText* text = new (_textPool.Alloc()) XMLText( this );
        returnNode = text;
        returnNode->_memPool = &_textPool;
        p += cdataHeaderLen;
        text->SetCData( true );
    }
    else if ( XMLUtil::StringEqual( p, dtdHeader, dtdHeaderLen ) ) {
        returnNode = new (_commentPool.Alloc()) XMLUnknown( this );
        returnNode->_memPool = &_commentPool;
        p += dtdHeaderLen;
    }
    else if ( XMLUtil::StringEqual( p, elementHeader, elementHeaderLen ) ) {
        returnNode = new (_elementPool.Alloc()) XMLElement( this );
        returnNode->_memPool = &_elementPool;
        p += elementHeaderLen;
    }
    else {
        returnNode = new (_textPool.Alloc()) XMLText( this );
        returnNode->_memPool = &_textPool;
        p = start;  // Back it up, all the text counts.
    }
    *node = returnNode;
    return p;
}
void tinyxml2::XMLDocument::InitDocument () [private]
Definition at line 1528 of file tinyxml2.cpp.
References _charBuffer, _errorID, _errorStr1, _errorStr2, and tinyxml2::XML_NO_ERROR.
Referenced by LoadFile(), and Parse().
{
    _errorID = XML_NO_ERROR;
    _errorStr1 = 0;
    _errorStr2 = 0;
    delete [] _charBuffer;
    _charBuffer = 0;
}
XMLNode * tinyxml2::XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis) [inherited]
Add a node after the specified child node.
Definition at line 702 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_next, tinyxml2::XMLNode::_parent, tinyxml2::XMLNode::_prev, tinyxml2::XMLNode::InsertEndChild(), tinyxml2::MemPool::SetTracked(), and TIXMLASSERT.
{
    TIXMLASSERT( afterThis->_parent == this );
    if ( afterThis->_parent != this ) {
        return 0;
    }
    if ( afterThis->_next == 0 ) {
        // The last node or the only node.
        return InsertEndChild( addThis );
    }
    addThis->_prev = afterThis;
    addThis->_next = afterThis->_next;
    afterThis->_next->_prev = addThis;
    afterThis->_next = addThis;
    addThis->_parent = this;
    addThis->_memPool->SetTracked();
    return addThis;
}
XMLNode * tinyxml2::XMLNode::InsertEndChild (XMLNode * addThis) [inherited]
Add a child node as the last (right) child.
Definition at line 653 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_lastChild, tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_next, tinyxml2::XMLNode::_parent, tinyxml2::XMLNode::_prev, tinyxml2::MemPool::SetTracked(), and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::LinkEndChild(), tinyxml2::XMLNode::ParseDeep(), corecvs::FiltersCollection::saveCompoundFilters(), corecvs::ThickeningBlock::serialize(), corecvs::BinarizeBlock::serialize(), corecvs::MaskFilterBlock::serialize(), corecvs::SobelFilter::serialize(), corecvs::BitSelectorFilter::serialize(), corecvs::GainOffsetFilter::serialize(), corecvs::BackgroundFilter::serialize(), corecvs::CannyFilter::serialize(), corecvs::InputFilter::serialize(), corecvs::Pin::serialize(), corecvs::OutputFilter::serialize(), corecvs::FilterBlock::serialize(), and corecvs::OperationFilter::serialize().
{
    if ( _lastChild ) {
        TIXMLASSERT( _firstChild );
        TIXMLASSERT( _lastChild->_next == 0 );
        _lastChild->_next = addThis;
        addThis->_prev = _lastChild;
        _lastChild = addThis;
        addThis->_next = 0;
    }
    else {
        TIXMLASSERT( _firstChild == 0 );
        _firstChild = _lastChild = addThis;
        addThis->_prev = 0;
        addThis->_next = 0;
    }
    addThis->_parent = this;
    addThis->_memPool->SetTracked();
    return addThis;
}
XMLNode * tinyxml2::XMLNode::InsertFirstChild (XMLNode * addThis) [inherited]
Add a child node as the first (left) child.
Definition at line 677 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_firstChild, tinyxml2::XMLNode::_lastChild, tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_next, tinyxml2::XMLNode::_parent, tinyxml2::XMLNode::_prev, tinyxml2::MemPool::SetTracked(), and TIXMLASSERT.
{
    if ( _firstChild ) {
        TIXMLASSERT( _lastChild );
        TIXMLASSERT( _firstChild->_prev == 0 );
        _firstChild->_prev = addThis;
        addThis->_next = _firstChild;
        _firstChild = addThis;
        addThis->_prev = 0;
    }
    else {
        TIXMLASSERT( _lastChild == 0 );
        _firstChild = _lastChild = addThis;
        addThis->_prev = 0;
        addThis->_next = 0;
    }
    addThis->_parent = this;
    addThis->_memPool->SetTracked();
    return addThis;
}
const XMLNode* tinyxml2::XMLNode::LastChild () const [inline, inherited]
Get the last child node, or null if none exists.
Definition at line 651 of file tinyxml2.h.
References tinyxml2::XMLNode::_lastChild.
Referenced by corecvs::BinarizeBlock::deserialize(), corecvs::ThickeningBlock::deserialize(), corecvs::MaskFilterBlock::deserialize(), corecvs::BackgroundFilter::deserialize(), corecvs::SobelFilter::deserialize(), corecvs::GainOffsetFilter::deserialize(), corecvs::BitSelectorFilter::deserialize(), corecvs::CannyFilter::deserialize(), corecvs::InputFilter::deserialize(), corecvs::OutputFilter::deserialize(), corecvs::OperationFilter::deserialize(), tinyxml2::XMLNode::LastChild(), tinyxml2::XMLHandle::LastChild(), and tinyxml2::XMLConstHandle::LastChild().
{
        return _lastChild;
    }
XMLNode* tinyxml2::XMLNode::LastChild () [inline, inherited]
Definition at line 655 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChild().
{
        return const_cast<XMLNode*>(const_cast<const XMLNode*>(this)->LastChild() );
    }
const XMLElement * tinyxml2::XMLNode::LastChildElement (const char * value = 0) const [inherited]
Get the last child element or optionally the last child element with the specified name.
Definition at line 739 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_lastChild, tinyxml2::XMLNode::_prev, tinyxml2::XMLElement::Name(), tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLHandle::LastChildElement(), and tinyxml2::XMLConstHandle::LastChildElement().
{
    for( XMLNode* node=_lastChild; node; node=node->_prev ) {
        XMLElement* element = node->ToElement();
        if ( element ) {
            if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                return element;
            }
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::LastChildElement (const char * value = 0) [inline, inherited]
Definition at line 664 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChildElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->LastChildElement(value) );
    }
XMLNode* tinyxml2::XMLNode::LinkEndChild (XMLNode * addThis) [inline, inherited]
Definition at line 705 of file tinyxml2.h.
References tinyxml2::XMLNode::InsertEndChild().
{
        return InsertEndChild( addThis );
    }
XMLError tinyxml2::XMLDocument::LoadFile (const char * filename)
Load an XML file from disk.
Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1584 of file tinyxml2.cpp.
References _charBuffer, _errorID, _writeBOM, tinyxml2::XMLNode::DeleteChildren(), InitDocument(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLUtil::ReadBOM(), SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), tinyxml2::XML_ERROR_EMPTY_DOCUMENT, tinyxml2::XML_ERROR_FILE_NOT_FOUND, and tinyxml2::XML_ERROR_FILE_READ_ERROR.
Referenced by corecvs::FiltersCollection::addFilterType(), corecvs::FiltersCollection::FiltersCollection(), and corecvs::FilterGraph::loadFromFile().
{
    DeleteChildren();
    InitDocument();
    FILE* fp = 0;
#if defined(_MSC_VER) && (_MSC_VER >= 1400)
    errno_t err = fopen_s(&fp, filename, "rb" );
    if ( !fp || err) {
#else
    fp = fopen( filename, "rb" );
    if ( !fp) {
#endif
        SetError( XML_ERROR_FILE_NOT_FOUND, filename, 0 );
        return _errorID;
    }
    LoadFile( fp );
    fclose( fp );
    return _errorID;
}
XMLError tinyxml2::XMLDocument::LoadFile (std::FILE *)
Load an XML file from disk.
You are responsible for providing and closing the FILE*.
Returns XML_NO_ERROR (0) on success, or an errorID.
XMLComment * tinyxml2::XMLDocument::NewComment (const char * comment)
Create a new Comment associated with this Document.
The memory for the Comment is managed by the Document.
Definition at line 1548 of file tinyxml2.cpp.
References _commentPool, tinyxml2::MemPoolT< SIZE >::Alloc(), and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLComment::ShallowClone().
{
    XMLComment* comment = new (_commentPool.Alloc()) XMLComment( this );
    comment->_memPool = &_commentPool;
    comment->SetValue( str );
    return comment;
}
XMLDeclaration * tinyxml2::XMLDocument::NewDeclaration (const char * text = 0)
Create a new Declaration associated with this Document.
The memory for the object is managed by the Document.
If the 'text' param is null, the standard declaration is used.:
            <?xml version="1.0" encoding="UTF-8"?>
Definition at line 1566 of file tinyxml2.cpp.
References _commentPool, tinyxml2::MemPoolT< SIZE >::Alloc(), and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLDeclaration::ShallowClone().
{
    XMLDeclaration* dec = new (_commentPool.Alloc()) XMLDeclaration( this );
    dec->_memPool = &_commentPool;
    dec->SetValue( str ? str : "xml version=\"1.0\" encoding=\"UTF-8\"" );
    return dec;
}
XMLElement * tinyxml2::XMLDocument::NewElement (const char * name)
Create a new Element associated with this Document.
The memory for the Element is managed by the Document.
Definition at line 1539 of file tinyxml2.cpp.
References _elementPool, tinyxml2::MemPoolT< SIZE >::Alloc(), tinyxml2::XMLElement::SetName(), and XMLElement.
Referenced by corecvs::FiltersCollection::saveCompoundFilters(), corecvs::BinarizeBlock::serialize(), corecvs::ThickeningBlock::serialize(), corecvs::MaskFilterBlock::serialize(), corecvs::GainOffsetFilter::serialize(), corecvs::BackgroundFilter::serialize(), corecvs::SobelFilter::serialize(), corecvs::BitSelectorFilter::serialize(), corecvs::CannyFilter::serialize(), corecvs::InputFilter::serialize(), corecvs::OutputFilter::serialize(), corecvs::Pin::serialize(), corecvs::FilterBlock::serialize(), corecvs::OperationFilter::serialize(), tinyxml2::XMLElement::ShallowClone(), and corecvs::SerializerVisitor::visit().
{
    XMLElement* ele = new (_elementPool.Alloc()) XMLElement( this );
    ele->_memPool = &_elementPool;
    ele->SetName( name );
    return ele;
}
XMLText * tinyxml2::XMLDocument::NewText (const char * text)
Create a new Text associated with this Document.
The memory for the Text is managed by the Document.
Definition at line 1557 of file tinyxml2.cpp.
References _textPool, tinyxml2::MemPoolT< SIZE >::Alloc(), and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLText::ShallowClone().
{
    XMLText* text = new (_textPool.Alloc()) XMLText( this );
    text->_memPool = &_textPool;
    text->SetValue( str );
    return text;
}
XMLUnknown * tinyxml2::XMLDocument::NewUnknown (const char * text)
Create a new Unknown associated with this Document.
The memory for the object is managed by the Document.
Definition at line 1575 of file tinyxml2.cpp.
References _commentPool, tinyxml2::MemPoolT< SIZE >::Alloc(), and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLUnknown::ShallowClone().
{
    XMLUnknown* unk = new (_commentPool.Alloc()) XMLUnknown( this );
    unk->_memPool = &_commentPool;
    unk->SetValue( str );
    return unk;
}
const XMLNode* tinyxml2::XMLNode::NextSibling () const [inline, inherited]
Get the next (right) sibling node of this node.
Definition at line 685 of file tinyxml2.h.
References tinyxml2::XMLNode::_next.
Referenced by tinyxml2::XMLElement::Accept(), Accept(), corecvs::FilterGraph::deserialize(), corecvs::FilterBlock::deserialize(), corecvs::FilterBlock::deserializePins(), corecvs::FiltersCollection::FiltersCollection(), corecvs::FiltersCollection::getContainedBlocks(), tinyxml2::XMLHandle::NextSibling(), and tinyxml2::XMLConstHandle::NextSibling().
{
        return _next;
    }
XMLNode* tinyxml2::XMLNode::NextSibling () [inline, inherited]
Definition at line 689 of file tinyxml2.h.
References tinyxml2::XMLNode::_next.
{
        return _next;
    }
const XMLElement * tinyxml2::XMLNode::NextSiblingElement (const char * value = 0) const [inherited]
Get the next (right) sibling element of this node, with an opitionally supplied name.
Definition at line 753 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_next, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::NextSiblingElement(), tinyxml2::XMLHandle::NextSiblingElement(), and tinyxml2::XMLConstHandle::NextSiblingElement().
{
    for( XMLNode* element=this->_next; element; element = element->_next ) {
        if (    element->ToElement()
                && (!value || XMLUtil::StringEqual( value, element->Value() ))) {
            return element->ToElement();
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::NextSiblingElement (const char * value = 0) [inline, inherited]
Definition at line 696 of file tinyxml2.h.
References tinyxml2::XMLNode::NextSiblingElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->NextSiblingElement( value ) );
    }
bool tinyxml2::XMLNode::NoChildren () const [inline, inherited]
Returns true if this node has no children.
Definition at line 628 of file tinyxml2.h.
References tinyxml2::XMLNode::_firstChild.
{
        return !_firstChild;
    }
void tinyxml2::XMLDocument::operator= (const XMLDocument &) [private]
const XMLNode* tinyxml2::XMLNode::Parent () const [inline, inherited]
Get the parent of this node on the DOM.
Definition at line 619 of file tinyxml2.h.
References tinyxml2::XMLNode::_parent.
{
        return _parent;
    }
XMLNode* tinyxml2::XMLNode::Parent () [inline, inherited]
Definition at line 623 of file tinyxml2.h.
References tinyxml2::XMLNode::_parent.
{
        return _parent;
    }
XMLError tinyxml2::XMLDocument::Parse (const char * xml, size_t nBytes = (size_t)(-1))
Parse an XML file from a character string.
Returns XML_NO_ERROR (0) on success, or an errorID.
You may optionally pass in the 'nBytes', which is the number of bytes which will be parsed. If not specified, TinyXML will assume 'xml' points to a null terminated string.
Definition at line 1668 of file tinyxml2.cpp.
References _charBuffer, _errorID, _writeBOM, tinyxml2::XMLNode::DeleteChildren(), InitDocument(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLUtil::ReadBOM(), SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), and tinyxml2::XML_ERROR_EMPTY_DOCUMENT.
Referenced by corecvs::FilterGraph::deserialize(), and corecvs::FiltersCollection::getContainedBlocks().
{
    DeleteChildren();
    InitDocument();
    if ( !p || !*p ) {
        SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
        return _errorID;
    }
    if ( len == (size_t)(-1) ) {
        len = strlen( p );
    }
    _charBuffer = new char[ len+1 ];
    memcpy( _charBuffer, p, len );
    _charBuffer[len] = 0;
    p = XMLUtil::SkipWhiteSpace( p );
    p = XMLUtil::ReadBOM( p, &_writeBOM );
    if ( !p || !*p ) {
        SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
        return _errorID;
    }
    ParseDeep( _charBuffer, 0 );
    return _errorID;
}
char * tinyxml2::XMLNode::ParseDeep (char * p, StrPair * parentEnd) [virtual, inherited]
Reimplemented in tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
Definition at line 777 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_value, tinyxml2::XMLElement::CLOSING, tinyxml2::XMLElement::ClosingType(), DELETE_NODE, tinyxml2::StrPair::Empty(), Error(), tinyxml2::StrPair::GetStr(), Identify(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLElement::OPEN, tinyxml2::XMLNode::ParseDeep(), SetError(), tinyxml2::MemPool::SetTracked(), tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLNode::ToElement(), tinyxml2::XMLNode::Value(), tinyxml2::XML_ERROR_MISMATCHED_ELEMENT, and tinyxml2::XML_ERROR_PARSING.
Referenced by LoadFile(), Parse(), and tinyxml2::XMLNode::ParseDeep().
{
    // This is a recursive method, but thinking about it "at the current level"
    // it is a pretty simple flat list:
    //      <foo/>
    //      <!-- comment -->
    //
    // With a special case:
    //      <foo>
    //      </foo>
    //      <!-- comment -->
    //
    // Where the closing element (/foo) *must* be the next thing after the opening
    // element, and the names must match. BUT the tricky bit is that the closing
    // element will be read by the child.
    //
    // 'endTag' is the end tag for this node, it is returned by a call to a child.
    // 'parentEnd' is the end tag for the parent, which is filled in and returned.
    while( p && *p ) {
        XMLNode* node = 0;
        p = _document->Identify( p, &node );
        if ( p == 0 || node == 0 ) {
            break;
        }
        StrPair endTag;
        p = node->ParseDeep( p, &endTag );
        if ( !p ) {
            DELETE_NODE( node );
            node = 0;
            if ( !_document->Error() ) {
                _document->SetError( XML_ERROR_PARSING, 0, 0 );
            }
            break;
        }
        // We read the end tag. Return it to the parent.
        if ( node->ToElement() && node->ToElement()->ClosingType() == XMLElement::CLOSING ) {
            if ( parentEnd ) {
                *parentEnd = static_cast<XMLElement*>(node)->_value;
            }
            node->_memPool->SetTracked();   // created and then immediately deleted.
            DELETE_NODE( node );
            return p;
        }
        // Handle an end tag returned to this level.
        // And handle a bunch of annoying errors.
        XMLElement* ele = node->ToElement();
        if ( ele ) {
            if ( endTag.Empty() && ele->ClosingType() == XMLElement::OPEN ) {
                _document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                p = 0;
            }
            else if ( !endTag.Empty() && ele->ClosingType() != XMLElement::OPEN ) {
                _document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                p = 0;
            }
            else if ( !endTag.Empty() ) {
                if ( !XMLUtil::StringEqual( endTag.GetStr(), node->Value() )) {
                    _document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                    p = 0;
                }
            }
        }
        if ( p == 0 ) {
            DELETE_NODE( node );
            node = 0;
        }
        if ( node ) {
            this->InsertEndChild( node );
        }
    }
    return 0;
}
const XMLNode* tinyxml2::XMLNode::PreviousSibling () const [inline, inherited]
Get the previous (left) sibling node of this node.
Definition at line 669 of file tinyxml2.h.
References tinyxml2::XMLNode::_prev.
Referenced by tinyxml2::XMLHandle::PreviousSibling(), and tinyxml2::XMLConstHandle::PreviousSibling().
{
        return _prev;
    }
XMLNode* tinyxml2::XMLNode::PreviousSibling () [inline, inherited]
Definition at line 673 of file tinyxml2.h.
References tinyxml2::XMLNode::_prev.
{
        return _prev;
    }
const XMLElement * tinyxml2::XMLNode::PreviousSiblingElement (const char * value = 0) const [inherited]
Get the previous (left) sibling element of this node, with an opitionally supplied name.
Definition at line 765 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_prev, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLNode::PreviousSiblingElement(), tinyxml2::XMLHandle::PreviousSiblingElement(), and tinyxml2::XMLConstHandle::PreviousSiblingElement().
{
    for( XMLNode* element=_prev; element; element = element->_prev ) {
        if (    element->ToElement()
                && (!value || XMLUtil::StringEqual( value, element->Value() ))) {
            return element->ToElement();
        }
    }
    return 0;
}
XMLElement* tinyxml2::XMLNode::PreviousSiblingElement (const char * value = 0) [inline, inherited]
Definition at line 680 of file tinyxml2.h.
References tinyxml2::XMLNode::PreviousSiblingElement().
{
        return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->PreviousSiblingElement( value ) );
    }
void tinyxml2::XMLDocument::Print (XMLPrinter * streamer = 0)
Print the Document.
If the Printer is not provided, it will print to stdout. If you provide Printer, this can print to a file:
        XMLPrinter printer( fp );
        doc.Print( &printer );
Or you can use a printer to print to memory:
        XMLPrinter printer;
        doc->Print( &printer );
        // printer.CStr() has a const char* to the XML
Definition at line 1696 of file tinyxml2.cpp.
References Accept().
Referenced by SaveFile(), and corecvs::FilterGraph::serialize().
{
    XMLPrinter stdStreamer( stdout );
    if ( !streamer ) {
        streamer = &stdStreamer;
    }
    Accept( streamer );
}
void tinyxml2::XMLDocument::PrintError () const
If there is an error, print it to stdout.
Definition at line 1714 of file tinyxml2.cpp.
References _errorID, _errorStr1, _errorStr2, and TIXML_SNPRINTF.
{
    if ( _errorID ) {
        static const int LEN = 20;
        char buf1[LEN] = { 0 };
        char buf2[LEN] = { 0 };
        if ( _errorStr1 ) {
            TIXML_SNPRINTF( buf1, LEN, "%s", _errorStr1 );
        }
        if ( _errorStr2 ) {
            TIXML_SNPRINTF( buf2, LEN, "%s", _errorStr2 );
        }
        printf( "XMLDocument error id=%d str1=%s str2=%s\n",
                _errorID, buf1, buf2 );
    }
}
bool tinyxml2::XMLDocument::ProcessEntities () const [inline]
Definition at line 1417 of file tinyxml2.h.
References _processEntities.
Referenced by tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLText::ParseDeep(), and tinyxml2::XMLPrinter::VisitEnter().
{
        return _processEntities;
    }
XMLElement* tinyxml2::XMLDocument::RootElement () [inline]
Return the root element of DOM.
Equivalent to FirstChildElement(). To get the first node, use FirstChild().
Definition at line 1439 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
{
        return FirstChildElement();
    }
const XMLElement* tinyxml2::XMLDocument::RootElement () const [inline]
Definition at line 1442 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
{
        return FirstChildElement();
    }
XMLError tinyxml2::XMLDocument::SaveFile (const char * filename, bool compact = false)
Save the XML file to disk.
Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1641 of file tinyxml2.cpp.
References _errorID, Print(), SetError(), and tinyxml2::XML_ERROR_FILE_COULD_NOT_BE_OPENED.
Referenced by corecvs::FiltersCollection::saveCompoundFilters().
{
    FILE* fp = 0;
#if defined(_MSC_VER) && (_MSC_VER >= 1400)
    errno_t err = fopen_s(&fp, filename, "w" );
    if ( !fp || err) {
#else
    fp = fopen( filename, "w" );
    if ( !fp) {
#endif
        SetError( XML_ERROR_FILE_COULD_NOT_BE_OPENED, filename, 0 );
        return _errorID;
    }
    SaveFile(fp, compact);
    fclose( fp );
    return _errorID;
}
XMLError tinyxml2::XMLDocument::SaveFile (std::FILE * fp, bool compact = false)
Save the XML file to disk.
You are responsible for providing and closing the FILE*.
Returns XML_NO_ERROR (0) on success, or an errorID.
void tinyxml2::XMLDocument::SetBOM (bool useBOM) [inline]
Sets whether to write the BOM when writing the file.
Definition at line 1432 of file tinyxml2.h.
References _writeBOM.
{
        _writeBOM = useBOM;
    }
void tinyxml2::XMLDocument::SetError (XMLError error, const char * str1, const char * str2)
Definition at line 1706 of file tinyxml2.cpp.
References _errorID, _errorStr1, and _errorStr2.
Referenced by LoadFile(), Parse(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), and SaveFile().
{
    _errorID = error;
    _errorStr1 = str1;
    _errorStr2 = str2;
}
void tinyxml2::XMLNode::SetValue (const char * val, bool staticMem = false) [inherited]
Set the Value of an XML node.
See also:
Value()
Definition at line 603 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_value, tinyxml2::StrPair::SetInternedStr(), and tinyxml2::StrPair::SetStr().
Referenced by NewComment(), NewDeclaration(), NewText(), NewUnknown(), and tinyxml2::XMLElement::SetName().
{
    if ( staticMem ) {
        _value.SetInternedStr( str );
    }
    else {
        _value.SetStr( str );
    }
}
virtual XMLNode* tinyxml2::XMLDocument::ShallowClone (XMLDocument * document) const [inline, virtual]
Make a copy of this node, but not its children.
You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
Definition at line 1532 of file tinyxml2.h.
{
        return 0;
    }
virtual bool tinyxml2::XMLDocument::ShallowEqual (const XMLNode * compare) const [inline, virtual]
Test if 2 nodes are the same, but don't test children.
The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
Definition at line 1535 of file tinyxml2.h.
{
        return false;
    }
virtual XMLComment* tinyxml2::XMLNode::ToComment () [inline, virtual, inherited]
Safely cast to a Comment, or null.
Reimplemented in tinyxml2::XMLComment.
Definition at line 565 of file tinyxml2.h.
Referenced by tinyxml2::XMLComment::ShallowEqual().
{
        return 0;
    }
virtual const XMLComment* tinyxml2::XMLNode::ToComment () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLComment.
Definition at line 587 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () [inline, virtual, inherited]
Safely cast to a Declaration, or null.
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 573 of file tinyxml2.h.
Referenced by tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLHandle::ToDeclaration(), and tinyxml2::XMLConstHandle::ToDeclaration().
{
        return 0;
    }
virtual const XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 593 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLDocument* tinyxml2::XMLDocument::ToDocument () [inline, virtual]
Safely cast to a Document, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 1366 of file tinyxml2.h.
{
        return this;
    }
virtual const XMLDocument* tinyxml2::XMLDocument::ToDocument () const [inline, virtual]
Reimplemented from tinyxml2::XMLNode.
Definition at line 1369 of file tinyxml2.h.
{
        return this;
    }
virtual XMLElement* tinyxml2::XMLNode::ToElement () [inline, virtual, inherited]
Safely cast to an Element, or null.
Reimplemented in tinyxml2::XMLElement.
Definition at line 557 of file tinyxml2.h.
Referenced by corecvs::BinarizeBlock::deserialize(), corecvs::ThickeningBlock::deserialize(), corecvs::MaskFilterBlock::deserialize(), corecvs::BackgroundFilter::deserialize(), corecvs::SobelFilter::deserialize(), corecvs::GainOffsetFilter::deserialize(), corecvs::BitSelectorFilter::deserialize(), corecvs::CannyFilter::deserialize(), corecvs::InputFilter::deserialize(), corecvs::OutputFilter::deserialize(), corecvs::Pin::deserialize(), corecvs::FilterGraph::deserialize(), corecvs::FilterBlock::deserialize(), corecvs::OperationFilter::deserialize(), corecvs::FilterBlock::deserializePins(), corecvs::FiltersCollection::FiltersCollection(), corecvs::FiltersCollection::getContainedBlocks(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::ShallowEqual(), tinyxml2::XMLHandle::ToElement(), and tinyxml2::XMLConstHandle::ToElement().
{
        return 0;
    }
virtual const XMLElement* tinyxml2::XMLNode::ToElement () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLElement.
Definition at line 581 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLText* tinyxml2::XMLNode::ToText () [inline, virtual, inherited]
Safely cast to Text, or null.
Reimplemented in tinyxml2::XMLText.
Definition at line 561 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLHandle::ToText(), and tinyxml2::XMLConstHandle::ToText().
{
        return 0;
    }
virtual const XMLText* tinyxml2::XMLNode::ToText () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLText.
Definition at line 584 of file tinyxml2.h.
{
        return 0;
    }
virtual XMLUnknown* tinyxml2::XMLNode::ToUnknown () [inline, virtual, inherited]
Safely cast to an Unknown, or null.
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 577 of file tinyxml2.h.
Referenced by tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLHandle::ToUnknown(), and tinyxml2::XMLConstHandle::ToUnknown().
{
        return 0;
    }
virtual const XMLUnknown* tinyxml2::XMLNode::ToUnknown () const [inline, virtual, inherited]
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 596 of file tinyxml2.h.
{
        return 0;
    }
const char* tinyxml2::XMLNode::Value () const [inline, inherited]
The meaning of 'value' changes for the specific type.
        Document:    empty
        Element:    name of the element
        Comment:    the comment text
        Unknown:    the tag contents
        Text:        the text string
Definition at line 609 of file tinyxml2.h.
References tinyxml2::XMLNode::_value, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::Visit().
{
        return _value.GetStr();
    }
Whitespace tinyxml2::XMLDocument::WhitespaceMode () const [inline]
Definition at line 1420 of file tinyxml2.h.
References _whitespace.
Referenced by tinyxml2::XMLText::ParseDeep().
{
        return _whitespace;
    }
Friends And Related Function Documentation
friend class XMLElement [friend]
Reimplemented from tinyxml2::XMLNode.
Definition at line 1360 of file tinyxml2.h.
Referenced by NewElement().
Member Data Documentation
MemPoolT< sizeof(XMLAttribute) > tinyxml2::XMLDocument::_attributePool [private]
Definition at line 1553 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLElement::ParseAttributes(), and ~XMLDocument().
char* tinyxml2::XMLDocument::_charBuffer [private]
Definition at line 1550 of file tinyxml2.h.
Referenced by InitDocument(), LoadFile(), Parse(), and ~XMLDocument().
MemPoolT< sizeof(XMLComment) > tinyxml2::XMLDocument::_commentPool [private]
Definition at line 1555 of file tinyxml2.h.
Referenced by NewComment(), NewDeclaration(), NewUnknown(), and ~XMLDocument().
XMLDocument* tinyxml2::XMLNode::_document [protected, inherited]
Definition at line 779 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), and XMLDocument().
MemPoolT< sizeof(XMLElement) > tinyxml2::XMLDocument::_elementPool [private]
Definition at line 1552 of file tinyxml2.h.
Referenced by NewElement(), and ~XMLDocument().
XMLError tinyxml2::XMLDocument::_errorID [private]
Definition at line 1546 of file tinyxml2.h.
Referenced by Error(), ErrorID(), InitDocument(), LoadFile(), Parse(), PrintError(), SaveFile(), and SetError().
const char* tinyxml2::XMLDocument::_errorStr1 [private]
Definition at line 1548 of file tinyxml2.h.
Referenced by GetErrorStr1(), InitDocument(), PrintError(), and SetError().
const char* tinyxml2::XMLDocument::_errorStr2 [private]
Definition at line 1549 of file tinyxml2.h.
Referenced by GetErrorStr2(), InitDocument(), PrintError(), and SetError().
XMLNode* tinyxml2::XMLNode::_firstChild [protected, inherited]
Definition at line 783 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NoChildren(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::_lastChild [protected, inherited]
Definition at line 784 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChild(), tinyxml2::XMLNode::LastChildElement(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::_next [protected, inherited]
Definition at line 787 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NextSibling(), tinyxml2::XMLNode::NextSiblingElement(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::_parent [protected, inherited]
Definition at line 780 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChild(), DeleteNode(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::Parent(), tinyxml2::XMLNode::Unlink(), and tinyxml2::XMLNode::~XMLNode().
XMLNode* tinyxml2::XMLNode::_prev [protected, inherited]
Definition at line 786 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::PreviousSibling(), tinyxml2::XMLNode::PreviousSiblingElement(), and tinyxml2::XMLNode::Unlink().
bool tinyxml2::XMLDocument::_processEntities [private]
Definition at line 1545 of file tinyxml2.h.
Referenced by ProcessEntities().
MemPoolT< sizeof(XMLText) > tinyxml2::XMLDocument::_textPool [private]
Definition at line 1554 of file tinyxml2.h.
Referenced by NewText(), and ~XMLDocument().
StrPair tinyxml2::XMLNode::_value [mutable, protected, inherited]
Definition at line 781 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLElement::ParseDeep(), tinyxml2::XMLNode::SetValue(), and tinyxml2::XMLNode::Value().
Whitespace tinyxml2::XMLDocument::_whitespace [private]
Definition at line 1547 of file tinyxml2.h.
Referenced by WhitespaceMode().
bool tinyxml2::XMLDocument::_writeBOM [private]
Definition at line 1544 of file tinyxml2.h.
Referenced by HasBOM(), LoadFile(), Parse(), and SetBOM().
The documentation for this class was generated from the following files:
core/tinyxml/tinyxml2.h
core/tinyxml/tinyxml2.cpp