DeepView: corecvs::EssentialEstimator::CostFunction7to1 Class Reference
corecvs::EssentialEstimator::CostFunction7to1 Class Reference
Normalized cost function try to trick the optimization algorithms by re-normalising the direction and the rotation quaternion every time it is used.
#include <essentialEstimator.h>
Public Types
enum InputVector2Model {
ROTATION_Q_X = 0, ROTATION_Q_Y, ROTATION_Q_Z, ROTATION_Q_T,
TRANSLATION_X, TRANSLATION_Y, TRANSLATION_Z, VECTOR_SIZE
}
Public Member Functions
CostFunction7to1 (const vector< Correspondance * > *_samples)
double getCost (const EssentialMatrix &matrix) const
virtual void operator() (const double in[], double out[])
Operator that computes funсtion.
virtual Matrix getJacobian (const double in[], double delta=1e-7)
This function computes Jacobian
.
virtual void operator() (const Vector &in, Vector &out)
virtual Matrix getJacobian (const Vector &in, double delta=1e-7)
Static Public Member Functions
static Quaternion getRotationQ (const double in[])
static Matrix33 getRotationM (const double in[])
static Vector3dd getTranslation (const double in[])
static EssentialMatrix getEssential (const double in[])
static double getRotationAngle (const double in[])
static Vector3dd getRotationAxis (const double in[])
static void packState (double out[], const Quaternion &q, const Vector3dd &t)
Public Attributes
const vector< Correspondance * > * samples
int inputs
int outputs
Detailed Description
Normalized cost function try to trick the optimization algorithms by re-normalising the direction and the rotation quaternion every time it is used.
Definition at line 74 of file essentialEstimator.h.
Member Enumeration Documentation
enum corecvs::EssentialEstimator::CostFunctionBase::InputVector2Model [inherited]
Enumerator:
ROTATION_Q_X
ROTATION_Q_Y
ROTATION_Q_Z
ROTATION_Q_T
TRANSLATION_X
TRANSLATION_Y
TRANSLATION_Z
VECTOR_SIZE
Definition at line 42 of file essentialEstimator.h.
{
            ROTATION_Q_X = 0,
            ROTATION_Q_Y,
            ROTATION_Q_Z,
            ROTATION_Q_T,
            TRANSLATION_X,
            TRANSLATION_Y,
            TRANSLATION_Z,
            VECTOR_SIZE
        };
Constructor & Destructor Documentation
corecvs::EssentialEstimator::CostFunction7to1::CostFunction7to1 (const vector< Correspondance * > * _samples) [inline]
Definition at line 78 of file essentialEstimator.h.
                                                                   :
               CostFunctionBase(1),
               samples(_samples)
        {};
Member Function Documentation
double corecvs::EssentialEstimator::CostFunction7to1::getCost (const EssentialMatrix & matrix) const
Definition at line 446 of file essentialEstimator.cpp.
References corecvs::EssentialMatrix::epipolarDistance().
Referenced by corecvs::IterativeEstimator::getEssential(), and UniversalRectifier::recalculate().
{
    double cost = 0.0;
    for (unsigned i = 0; i < samples->size(); i++)
    {
        double fitness = matrix.epipolarDistance(*(samples->at(i)));
        cost += fitness * fitness;
    }
    return cost;
}
EssentialMatrix corecvs::EssentialEstimator::CostFunctionBase::getEssential (const double in[]) [static, inherited]
Definition at line 430 of file essentialEstimator.cpp.
References corecvs::EssentialMatrix::compose().
Referenced by corecvs::EssentialEstimator::getEssentialGrad(), corecvs::EssentialEstimator::getEssentialGradToRm(), corecvs::EssentialEstimator::getEssentialLM(), and corecvs::EssentialEstimator::getEssentialSimpleKalman().
{
    return EssentialMatrix::compose(getRotationM(in), getTranslation(in));
}
Matrix corecvs::EssentialEstimator::CostFunction7to1::getJacobian (const double in[], double delta = 1e-7) [virtual]
This function computes Jacobian
.
TODO: Bring differencing out and use following information http://en.wikipedia.org/wiki/Numerical_differentiation#Practical_considerations_using_floating_point_arithmetic
Reimplemented from corecvs::FunctionArgs.
Definition at line 465 of file essentialEstimator.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::EssentialMatrix::epipolarDistance(), and corecvs::EssentialEstimator::getEssential().
{
    Matrix result(outputs, inputs);
    // is it needed here?
//    EssentialMatrix m = getEssential(in);
    vector<double> xc(inputs);
    EssentialMatrix m_minus(Matrix33(1.0));
    EssentialMatrix m_plus (Matrix33(1.0));
    for (int i = 0; i < inputs; i++)
    {
       xc[i] = in[i];
    }
    for (int i = 0; i < inputs; i++)
    {
       xc[i] = in[i] - delta;
       m_minus = getEssential(&xc[0]);
       xc[i] = in[i] + delta;
       m_plus  = getEssential(&xc[0]);
       xc[i] = in[i];
       double sum_plus  = 0.0;
       double sum_minus = 0.0;
       for (unsigned j = 0; j < samples->size(); j++)
       {
           Correspondance *corr = samples->at(j);
           double value_plus  = m_plus .epipolarDistance(*corr);
           double value_minus = m_minus.epipolarDistance(*corr);
           sum_plus  += value_plus  * value_plus ;
           sum_minus += value_minus * value_minus;
       }
       result.element(0,i) = (sum_plus - sum_minus) / (2.0 * delta);
/*
       double d = 0.0;
       for (unsigned j = 0; j < samples->size(); j++)
       {
           Correspondance *corr = samples->at(j);
           double value_plus  = m_plus .epipolarDistance(*corr);
           double value_minus = m_minus.epipolarDistance(*corr);
           double value       = m.      epipolarDistance(*corr);
           double dvalue = value * (value_plus - value_minus) / delta;
           d += dvalue;
       }
       result.element(0,i) = d;
*/
/*
       double d = 0.0;
       for (unsigned j = 0; j < samples->size(); j++)
       {
           Correspondance *corr = samples->at(j);
           double value_plus  = m_plus .epipolarDistance(*corr);
           double value_minus = m_minus.epipolarDistance(*corr);
           double value       = m.      epipolarDistance(*corr);
           d += value * (value_plus - value_minus);
       }
       result.element(0,i) = d / delta;
*/
/*       double d = 0.0;
       double sum_plus  = 0.0;
       double sum_minus = 0.0;
       for (unsigned j = 0; j < samples->size(); j++)
       {
           Correspondance *corr = samples->at(j);
           double value_plus  = m_plus .epipolarDistance(*corr);
           double value_minus = m_minus.epipolarDistance(*corr);
           double value       = m.      epipolarDistance(*corr);
           sum_plus  += value * value_plus ;
           sum_minus += value * value_minus;
       }
       result.element(0,i) = (sum_plus - sum_minus) / delta;*/
    }
//    Matrix result1 = FunctionArgs::getJacobian(in);
//    cout << result  << endl;
//    cout << result1 << endl;
    return result;
}
virtual Matrix corecvs::FunctionArgs::getJacobian (const Vector & in, double delta = 1e-7) [inline, virtual, inherited]
Definition at line 96 of file function.h.
References corecvs::FixedArrayBase< RealType, ElementType >::element, and corecvs::FunctionArgs::getJacobian().
    {
        return getJacobian(in.element, delta);
    }
double corecvs::EssentialEstimator::CostFunctionBase::getRotationAngle (const double in[]) [static, inherited]
Definition at line 420 of file essentialEstimator.cpp.
{
    return getRotationQ(in).getAngle();
}
Vector3dd corecvs::EssentialEstimator::CostFunctionBase::getRotationAxis (const double in[]) [static, inherited]
Definition at line 425 of file essentialEstimator.cpp.
{
    return getRotationQ(in).getAxis();
}
Matrix33 corecvs::EssentialEstimator::CostFunctionBase::getRotationM (const double in[]) [static, inherited]
Definition at line 415 of file essentialEstimator.cpp.
{
    return getRotationQ(in).toMatrix();
}
Quaternion corecvs::EssentialEstimator::CostFunctionBase::getRotationQ (const double in[]) [static, inherited]
Definition at line 405 of file essentialEstimator.cpp.
References corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_T, corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_X, corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_Y, and corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_Z.
Referenced by corecvs::EssentialEstimator::NormalizeFunction::operator()().
{
    return Quaternion(in[ROTATION_Q_X], in[ROTATION_Q_Y], in[ROTATION_Q_Z], in[ROTATION_Q_T]).normalised();
}
Vector3dd corecvs::EssentialEstimator::CostFunctionBase::getTranslation (const double in[]) [static, inherited]
Definition at line 410 of file essentialEstimator.cpp.
References corecvs::VectorOperationsBase< RealType, ElementType >::normalised().
Referenced by corecvs::EssentialEstimator::NormalizeFunction::operator()().
{
    return Vector3dd(in[TRANSLATION_X], in[TRANSLATION_Y], in[TRANSLATION_Z]).normalised();
}
virtual void corecvs::FunctionArgs::operator() (const Vector & in, Vector & out) [inline, virtual, inherited]
Definition at line 46 of file function.h.
References corecvs::FixedArrayBase< RealType, ElementType >::element, and corecvs::FunctionArgs::operator()().
    {
        return operator()(in.element, out.element);
    }
void corecvs::EssentialEstimator::CostFunction7to1::operator() (const double in[], double out[]) [virtual]
Operator that computes funсtion.
Implements corecvs::FunctionArgs.
Definition at line 457 of file essentialEstimator.cpp.
References corecvs::EssentialEstimator::getEssential().
{
    EssentialMatrix m = getEssential(in);
    out[0] = getCost(m);
}
void corecvs::EssentialEstimator::CostFunctionBase::packState (double out[], const Quaternion & q, const Vector3dd & t) [static, inherited]
Definition at line 435 of file essentialEstimator.cpp.
References corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_T, corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_X, corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_Y, corecvs::EssentialEstimator::CostFunctionBase::ROTATION_Q_Z, corecvs::GenericQuaternion< ElementType >::t(), corecvs::EssentialEstimator::CostFunctionBase::TRANSLATION_X, corecvs::EssentialEstimator::CostFunctionBase::TRANSLATION_Y, corecvs::EssentialEstimator::CostFunctionBase::TRANSLATION_Z, corecvs::GenericQuaternion< ElementType >::x(), corecvs::Vector3d< ElementType >::x(), corecvs::GenericQuaternion< ElementType >::y(), corecvs::Vector3d< ElementType >::y(), corecvs::GenericQuaternion< ElementType >::z(), and corecvs::Vector3d< ElementType >::z().
Referenced by corecvs::EssentialEstimator::getEssentialGrad(), corecvs::EssentialEstimator::getEssentialGradToRm(), corecvs::EssentialEstimator::getEssentialLM(), corecvs::EssentialEstimator::getEssentialSimpleKalman(), and corecvs::EssentialEstimator::NormalizeFunction::operator()().
{
    out[CostFunctionBase::ROTATION_Q_X]  = q.x();
    out[CostFunctionBase::ROTATION_Q_Y]  = q.y();
    out[CostFunctionBase::ROTATION_Q_Z]  = q.z();
    out[CostFunctionBase::ROTATION_Q_T]  = q.t();
    out[CostFunctionBase::TRANSLATION_X] = t.x();
    out[CostFunctionBase::TRANSLATION_Y] = t.y();
    out[CostFunctionBase::TRANSLATION_Z] = t.z();
}
Member Data Documentation
int corecvs::FunctionArgs::inputs [inherited]
Definition at line 32 of file function.h.
Referenced by corecvs::ClassicKalman::ClassicKalman(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawIsolines(), corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::CamerasCalibrationFunc::getJacobian(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::FunctionArgs::getJacobian(), corecvs::IdentityFunction::getJacobian(), corecvs::LengthFunction::LengthFunction(), corecvs::GradientDescent::minimise(), corecvs::IdentityFunction::operator()(), and corecvs::ScalerFunction::ScalerFunction().
int corecvs::FunctionArgs::outputs [inherited]
Definition at line 33 of file function.h.
Referenced by corecvs::ClassicKalman::ClassicKalman(), corecvs::RGB24Buffer::drawFunction(), corecvs::RGB24Buffer::drawIsolines(), corecvs::GradientDescent::fit(), corecvs::LevenbergMarquardt::fit(), corecvs::GradientDescentRnToRm::fit(), corecvs::CamerasCalibrationFunc::getJacobian(), corecvs::CurvatureFunc::getJacobian(), corecvs::StraightFunc::getJacobian(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::RadialFunc::getJacobian(), corecvs::FunctionArgs::getJacobian(), corecvs::IdentityFunction::getJacobian(), corecvs::LengthFunction::LengthFunction(), corecvs::GradientDescent::minimise(), corecvs::ScalerFunction::operator()(), corecvs::LengthFunction::operator()(), and corecvs::ScalerFunction::ScalerFunction().
const vector<Correspondance *>* corecvs::EssentialEstimator::CostFunction7to1::samples
Definition at line 76 of file essentialEstimator.h.
The documentation for this class was generated from the following files:
core/rectification/essentialEstimator.h
core/rectification/essentialEstimator.cpp