DeepView: DirectShowCaptureInterface Class Reference
DirectShowCaptureInterface Class Reference
#include <directShowCapture.h>
Public Types
typedef
ImageCaptureInterface::CapErrorCode CapErrorCode
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
void memberCallback (DSCapDeviceId dev, FrameData data)
DirectShowCaptureInterface (string _devname)
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual CapErrorCode queryCameraParameters (CameraParameters &parameters)
Check if a specific property can be set/read and what values it can take.
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&format)
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual ~DirectShowCaptureInterface ()
virtual FramePair getFrameRGB24 ()
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static void callback (void *thiz, DSCapDeviceId dev, FrameData data)
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Public Attributes
int compressed
QMutex protectFrame
string devname
Stores the device name.
DirectShowCameraDescriptor cameras [2]
PreciseTimer lastFrameTime
int skippedCount
int isRunning
unsigned int delay
Static Public Attributes
static const char * codec_names []
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Private Member Functions
bool isCorrectDeviceHandle (int cameraNum)
Detailed Description
Definition at line 25 of file directShowCapture.h.
Member Typedef Documentation
typedef ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::CapErrorCode
Reimplemented from ImageCaptureInterface.
Definition at line 28 of file directShowCapture.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
Constructor & Destructor Documentation
DirectShowCaptureInterface::DirectShowCaptureInterface (string _devname)
Definition at line 27 of file directShowCapture.cpp.
References callback(), cameras, codec_names, compressed, DirectShowCameraDescriptor::COMPRESSED_FAST_JPEG, DirectShowCameraDescriptor::COMPRESSED_JPEG, DirectShowCameraDescriptor::deviceHandle, devname, isCorrectDeviceHandle(), isRunning, skippedCount, DirectShowCameraDescriptor::UNCOMPRESSED_RGB, and DirectShowCameraDescriptor::UNCOMPRESSED_YUV.
{
    this->devname = _devname;
    //     Group Number                   1       2 3        4 5      6       7 8       9       10     11        1213     14
    QRegExp deviceStringPattern(QString("^([^,:]*)(,([^:]*))?(:(\\d*)/(\\d*))?((:mjpeg)|(:yuyv)|(:rgb)|(:fjpeg))?(:(\\d*)x(\\d*))?$"));
    static const int Device1Group     = 1;
    static const int Device2Group     = 3;
    static const int FpsNumGroup      = 5;
    static const int FpsDenumGroup    = 6;
    static const int CompressionGroup = 7;
    static const int WidthGroup       = 13;
    static const int HeightGroup      = 14;
    printf ("Input string %s\n", _devname.c_str());
    QString qdevname(_devname.c_str());
    int result = deviceStringPattern.indexIn(qdevname);
    if (result == -1)
    {
        printf("Error in device string format:%s\n", _devname.c_str());
        return;
    }
    printf (
    "Parsed data:\n"
    "  | - Device 1=%s\n"
    "  | - Device 2=%s\n"
    "  | - FPS %s/%s\n"
    "  | - Size [%sx%s]\n"
    "  \\ - Compressing: %s\n",
    deviceStringPattern.cap(Device1Group).toAscii().constData(),
    deviceStringPattern.cap(Device2Group).toAscii().constData(),
    deviceStringPattern.cap(FpsNumGroup).toAscii().constData(),
    deviceStringPattern.cap(FpsDenumGroup).toAscii().constData(),
    deviceStringPattern.cap(WidthGroup).toAscii().constData(),
    deviceStringPattern.cap(HeightGroup).toAscii().constData(),
    deviceStringPattern.cap(CompressionGroup).toAscii().constData());
    int leftName =  deviceStringPattern.cap(Device1Group).isEmpty() ? -1 : deviceStringPattern.cap(Device1Group).toInt();
    int rightName = deviceStringPattern.cap(Device2Group).isEmpty() ? -1 : deviceStringPattern.cap(Device2Group).toInt();
    bool err;
    int fpsnum = deviceStringPattern.cap(FpsNumGroup).toInt(&err);
    if (!err) fpsnum = 1;
    int fpsdenum = deviceStringPattern.cap(FpsDenumGroup).toInt(&err);
    if (!err) fpsdenum = 10;
    int width = deviceStringPattern.cap(WidthGroup).toInt(&err);
    if (!err || width <= 0) width = 800;
    int height = deviceStringPattern.cap(HeightGroup).toInt(&err);
    if (!err || height <= 0) height = 600;
    compressed = DirectShowCameraDescriptor::UNCOMPRESSED_YUV;
    int formatId = CAP_YUV;
    if (!deviceStringPattern.cap(CompressionGroup).isEmpty())
    {
       if        (!deviceStringPattern.cap(CompressionGroup).compare(QString(":rgb"))) {
           compressed = DirectShowCameraDescriptor::UNCOMPRESSED_RGB;
           formatId = CAP_RGB;
       } else if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":mjpeg"))) {
           compressed = DirectShowCameraDescriptor::COMPRESSED_JPEG;
           formatId = CAP_MJPEG;
       } else if (!deviceStringPattern.cap(CompressionGroup).compare(QString(":fjpeg"))) {
           compressed = DirectShowCameraDescriptor::COMPRESSED_FAST_JPEG;
           formatId = CAP_MJPEG;
       }
    }
    printf("Capture Left device: DShow  %d\n", leftName);
    printf("Capture Right device: DShow %d\n", rightName);
    printf("Format is: %s\n", codec_names[compressed]);
    /* TODO: Make cycle here */
    cameras[0].deviceHandle = leftName >= 0 ? DirectShowCapDll_initCapture(leftName) : -1;
    cameras[1].deviceHandle = rightName >= 0 ? DirectShowCapDll_initCapture(rightName) : -1;
    CaptureTypeFormat format1 = {formatId, height, width, (int)((double)fpsdenum / fpsnum) }; // FixMe: probably round should be here?
    CaptureTypeFormat format2 = {formatId, height, width, (int)((double)fpsdenum / fpsnum) }; // FixMe:
    if (isCorrectDeviceHandle(0))
    {
        DirectShowCapDll_setFormat(cameras[0].deviceHandle, &format1);
        DirectShowCapDll_setFrameCallback(cameras[0].deviceHandle, this, DirectShowCaptureInterface::callback);
    }
    if (isCorrectDeviceHandle(1))
    {
        DirectShowCapDll_setFormat(cameras[1].deviceHandle, &format2);
        DirectShowCapDll_setFrameCallback(cameras[1].deviceHandle, this, DirectShowCaptureInterface::callback);
    }
    printf("Real Formats:\n");
    DirectShowCapDll_printSimpleFormat(&format1); printf("\n");
    DirectShowCapDll_printSimpleFormat(&format2); printf("\n");
    skippedCount = 0;
    isRunning = false;
}
DirectShowCaptureInterface::~DirectShowCaptureInterface () [virtual]
Definition at line 257 of file directShowCapture.cpp.
References cameras, isCorrectDeviceHandle(), and isRunning.
{
    if (!isRunning)
        return;
        /*
            Callback is set safe and synchroniously,
            so after the call of the callback reset, we will never again
            recive a frame. So it will be safe to destroy the object
        */
    if (isCorrectDeviceHandle(0))
    {
        DirectShowCapDll_setFrameCallback(cameras[0].deviceHandle, NULL, NULL);
        DirectShowCapDll_stop(cameras[0].deviceHandle);
    }
    if (isCorrectDeviceHandle(1))
    {
        DirectShowCapDll_setFrameCallback(cameras[1].deviceHandle, NULL, NULL);
        DirectShowCapDll_stop(cameras[1].deviceHandle);
    }
    isRunning = false;
}
Member Function Documentation
void DirectShowCaptureInterface::callback (void * thiz, DSCapDeviceId dev, FrameData data) [static]
Definition at line 126 of file directShowCapture.cpp.
References memberCallback().
Referenced by DirectShowCaptureInterface().
{
    //printf("Received new frame in a callback\n");
    DirectShowCaptureInterface *pInterface = (DirectShowCaptureInterface *)thiz;
    pInterface->memberCallback(dev, data);
}
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::getCaptureName (QString & value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 312 of file directShowCapture.cpp.
References cameras, ImageCaptureInterface::FAILURE, isCorrectDeviceHandle(), and ImageCaptureInterface::SUCCESS.
{
    if (!isCorrectDeviceHandle(0))
        return ImageCaptureInterface::FAILURE;
    char *name = NULL;
    DirectShowCapDll_deviceName(cameras[0].deviceHandle, &name);
    value = "";
    int k = 0;
    while (name[k] != '\0')
    {
        value += name[k];
        k += 2;
    }
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::getCaptureProperty (int id, int * value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 303 of file directShowCapture.cpp.
References cameras, DirectShowCameraDescriptor::getCaptureProperty(), isCorrectDeviceHandle(), and ImageCaptureInterface::SUCCESS.
{
    if (isCorrectDeviceHandle(0))
    {
        cameras[0].getCaptureProperty(id, value);
    }
    return ImageCaptureInterface::SUCCESS;
}
DirectShowCaptureInterface::CapErrorCode DirectShowCaptureInterface::getDeviceName (int num, QString & name) [virtual]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented from ImageCaptureInterface.
Definition at line 352 of file directShowCapture.cpp.
References devname, ImageCaptureInterface::FAILURE, and ImageCaptureInterface::SUCCESS.
{
    if (num < 0 || num >= 2)
    {
        return ImageCaptureInterface::FAILURE;
    }
    //     Group Number                   1       2 3        4 5      6       7 8       9       10     11        1213     14
    QRegExp deviceStringPattern(QString("^([^,:]*)(,([^:]*))?(:(\\d*)/(\\d*))?((:mjpeg)|(:yuyv)|(:rgb)|(:fjpeg))?(:(\\d*)x(\\d*))?$"));
    static const int Device1Group     = 1;
    static const int Device2Group     = 3;
    QString qdevname(devname.c_str());
    int result = deviceStringPattern.indexIn(qdevname);
    if (result == -1)
    {
        printf("Error in device string format:%s\n", devname.c_str());
        return ImageCaptureInterface::FAILURE;
    }
    if (num == 0)
    {
        name = deviceStringPattern.cap(Device1Group);
    }
    else
    {
        name = deviceStringPattern.cap(Device2Group);
    }
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::getFormats (int * num, CameraFormat *& format) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 328 of file directShowCapture.cpp.
References cameras, ImageCaptureInterface::FAILURE, ImageCaptureInterface::CameraFormat::fps, ImageCaptureInterface::CameraFormat::height, isCorrectDeviceHandle(), ImageCaptureInterface::SUCCESS, and ImageCaptureInterface::CameraFormat::width.
{
    if (!isCorrectDeviceHandle(0))
        return ImageCaptureInterface::FAILURE;
    DirectShowCapDll_getFormatNumber(cameras[0].deviceHandle, num);
    int number = *num;
    CaptureTypeFormat* captureTypeFormats = new CaptureTypeFormat[number];
    delete format;
    format = new CameraFormat[number];
    DirectShowCapDll_getFormats(cameras[0].deviceHandle, number, captureTypeFormats);
    for (int i = 0; i < number; i ++)
    {
        format[i].fps    = captureTypeFormats[i].fps;
        format[i].width  = captureTypeFormats[i].width;
        format[i].height = captureTypeFormats[i].height;
    }
    delete[] captureTypeFormats;
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::FramePair DirectShowCaptureInterface::getFrame () [virtual]
Main function to request frames from image interface.
Implements ImageCaptureInterface.
Definition at line 219 of file directShowCapture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, cameras, ImageCaptureInterface::FramePair::leftTimeStamp, protectFrame, ImageCaptureInterface::FramePair::rightTimeStamp, and DirectShowCameraDescriptor::timestamp.
{
    protectFrame.lock();
    FramePair result(NULL, NULL);
    if (cameras[0].buffer != NULL)
    {
        result.bufferLeft = new G12Buffer(cameras[0].buffer);
    }
    if (cameras[1].buffer != NULL)
    {
        result.bufferRight = new G12Buffer(cameras[1].buffer);
    }
    result.leftTimeStamp = cameras[0].timestamp;
    result.rightTimeStamp = cameras[1].timestamp;
    protectFrame.unlock();
    return result;
}
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual, inherited]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
QString ImageCaptureInterface::getInterfaceName () [virtual, inherited]
Return the interface device string.
Reimplemented in V4L2CaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 181 of file imageCaptureInterface.cpp.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
{
    return "";
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::initCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 237 of file directShowCapture.cpp.
References ImageCaptureInterface::SUCCESS.
{
    return ImageCaptureInterface::SUCCESS;
}
bool DirectShowCaptureInterface::isCorrectDeviceHandle (int cameraNum) [private]
Definition at line 380 of file directShowCapture.cpp.
References cameras, and DirectShowCameraDescriptor::deviceHandle.
Referenced by DirectShowCaptureInterface(), getCaptureName(), getCaptureProperty(), getFormats(), queryCameraParameters(), setCaptureProperty(), startCapture(), and ~DirectShowCaptureInterface().
{
    return cameras[cameraNum].deviceHandle >= 0;
}
ALIGN_STACK_SSE void DirectShowCaptureInterface::memberCallback (DSCapDeviceId dev, FrameData data)
Definition at line 133 of file directShowCapture.cpp.
References DirectShowCameraDescriptor::buffer, cameras, MjpegDecoderLazy::decode(), DirectShowCameraDescriptor::decodeTime, CaptureStatistics::DECODING_TIME, CaptureStatistics::DESYNC_TIME, corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::G12Buffer::fillWithYUYV(), DirectShowCameraDescriptor::gotBuffer, corecvs::AbstractBufferParams::h, CaptureStatistics::INTERFRAME_DELAY, lastFrameTime, ImageCaptureInterface::newFrameReady(), ImageCaptureInterface::newImageReady(), ImageCaptureInterface::newStatisticsReady(), protectFrame, skippedCount, frame_data_t::timestamp, DirectShowCameraDescriptor::timestamp, corecvs::PreciseTimer::usecsTo(), corecvs::PreciseTimer::usecsToNow(), CaptureStatistics::values, and corecvs::AbstractBufferParams::w.
Referenced by callback().
{
    //SYNC_PRINT(("Received new frame in a member %d\n", dev));
    protectFrame.lock();
    DirectShowCameraDescriptor *camera = NULL;
    if      (cameras[0].deviceHandle == dev)
        camera = &cameras[0];
    else if (cameras[1].deviceHandle == dev)
        camera = &cameras[1];
    else
        goto exit;
    {
        PreciseTimer timer = PreciseTimer::currentTime();
        camera->gotBuffer = true;
        camera->timestamp = (data.timestamp + 5) / 10;
        delete camera->buffer;
        if (data.format.type == CAP_YUV)
        {
            camera->buffer = new G12Buffer(data.format.height, data.format.width, false);
            camera->buffer->fillWithYUYV((uint16_t *)data.data);
        }
        else if (data.format.type == CAP_MJPEG)
        {
            MjpegDecoderLazy lazyDecoder;
            camera->buffer = lazyDecoder.decode((unsigned char *)data.data);
        }
        else if (data.format.type == CAP_RGB)
        {
            // Take this somewhere else
            camera->buffer = new G12Buffer(data.format.height, data.format.width, false);
            int w = camera->buffer->w;
            int h = camera->buffer->h;
            for (int i = 0; i < h; i++)
            {
                uint8_t  *rgbData = ((uint8_t *)data.data) + 3 * (h - i - 1) * w;
                uint16_t *greyData = &(camera->buffer->element(i,0));
                for (int j = 0; j < w; j++)
                {
                    uint16_t r = rgbData[0];
                    uint16_t g = rgbData[1];
                    uint16_t b = rgbData[2];
                    *greyData = (11 * r + 16 * g + 5 * b) >> 1;
                    rgbData +=3;
                    greyData+=1;
                }
            }
        } else {
            camera->buffer = new G12Buffer(data.format.height, data.format.width, false);
        }
        camera->decodeTime = timer.usecsToNow();
        /* If both frames are in place */
        if (cameras[0].gotBuffer && cameras[1].gotBuffer)
        {
            cameras[0].gotBuffer = false;
            cameras[1].gotBuffer = false;
            CaptureStatistics stats;
            int64_t desync =  cameras[0].timestamp - cameras[1].timestamp;
            stats.values[CaptureStatistics::DESYNC_TIME] = desync > 0 ? desync : -desync;
            stats.values[CaptureStatistics::DECODING_TIME] = cameras[0].decodeTime + cameras[1].decodeTime;
            if (lastFrameTime.usecsTo(PreciseTimer()) != 0)
            {
                stats.values[CaptureStatistics::INTERFRAME_DELAY] = lastFrameTime.usecsToNow();
            }
            lastFrameTime = PreciseTimer::currentTime();
            frame_data_t frameData;
            frameData.timestamp = cameras[0].timestamp / 2 + cameras[1].timestamp / 2;
            newFrameReady(frameData);
            newStatisticsReady(stats);
        } else {
            emit newImageReady();
            skippedCount++;
        }
    }
exit:
    protectFrame.unlock();
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::queryCameraParameters (CameraParameters & parameter) [virtual]
Check if a specific property can be set/read and what values it can take.
Reimplemented from ImageCaptureInterface.
Definition at line 281 of file directShowCapture.cpp.
References cameras, isCorrectDeviceHandle(), DirectShowCameraDescriptor::queryCameraParameters(), and ImageCaptureInterface::SUCCESS.
{
    if (isCorrectDeviceHandle(0))
    {
        cameras[0].queryCameraParameters(parameters);
    }
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::setCaptureProperty (int id, int value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 290 of file directShowCapture.cpp.
References cameras, isCorrectDeviceHandle(), DirectShowCameraDescriptor::setCaptureProperty(), and ImageCaptureInterface::SUCCESS.
{
    if (isCorrectDeviceHandle(0))
    {
        cameras[0].setCaptureProperty(id, value);
    }
    if (isCorrectDeviceHandle(1))
    {
        cameras[1].setCaptureProperty(id, value);
    }
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode DirectShowCaptureInterface::startCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 242 of file directShowCapture.cpp.
References cameras, isCorrectDeviceHandle(), isRunning, and ImageCaptureInterface::SUCCESS.
{
    isRunning = true;
    if (isCorrectDeviceHandle(0))
    {
        DirectShowCapDll_start(cameras[0].deviceHandle);
    }
    if (isCorrectDeviceHandle(1))
    {
        DirectShowCapDll_start(cameras[1].deviceHandle);
    }
    //spin.start();
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
Member Data Documentation
DirectShowCameraDescriptor DirectShowCaptureInterface::cameras[2]
Definition at line 36 of file directShowCapture.h.
Referenced by DirectShowCaptureInterface(), getCaptureName(), getCaptureProperty(), getFormats(), getFrame(), isCorrectDeviceHandle(), memberCallback(), queryCameraParameters(), setCaptureProperty(), startCapture(), and ~DirectShowCaptureInterface().
const char * DirectShowCaptureInterface::codec_names [static]
Initial value:
{
        "yuv",
        "rgb",
        "mjpeg",
        "mjpeg fast decoder"
}
Definition at line 30 of file directShowCapture.h.
Referenced by DirectShowCaptureInterface().
int DirectShowCaptureInterface::compressed
Definition at line 31 of file directShowCapture.h.
Referenced by DirectShowCaptureInterface().
unsigned int DirectShowCaptureInterface::delay
Definition at line 48 of file directShowCapture.h.
string DirectShowCaptureInterface::devname
Stores the device name.
Definition at line 35 of file directShowCapture.h.
Referenced by DirectShowCaptureInterface(), and getDeviceName().
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
int DirectShowCaptureInterface::isRunning
Definition at line 41 of file directShowCapture.h.
Referenced by DirectShowCaptureInterface(), startCapture(), and ~DirectShowCaptureInterface().
PreciseTimer DirectShowCaptureInterface::lastFrameTime
Definition at line 39 of file directShowCapture.h.
Referenced by memberCallback().
QMutex DirectShowCaptureInterface::protectFrame
Definition at line 34 of file directShowCapture.h.
Referenced by getFrame(), and memberCallback().
int DirectShowCaptureInterface::skippedCount
Definition at line 40 of file directShowCapture.h.
Referenced by DirectShowCaptureInterface(), and memberCallback().
The documentation for this class was generated from the following files:
utils/framesources/directShow/directShowCapture.h
utils/framesources/directShow/directShowCapture.cpp