DeepView: corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp Class Reference
corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp Class Reference
#include <g12Buffer.h>
Public Member Functions
ParallelDoReverseDeformationBlPrecomp (G12Buffer *_toReturn, const FixedPointDisplace *_map, G12Buffer *_buf)
void operator() (const BlockedRange< G12Buffer::InternalIndexType > &r) const
Private Attributes
G12Buffer * toReturn
const FixedPointDisplace * map
G12Buffer * buf
Detailed Description
Definition at line 128 of file g12Buffer.h.
Constructor & Destructor Documentation
corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::ParallelDoReverseDeformationBlPrecomp (G12Buffer * _toReturn, const FixedPointDisplace * _map, G12Buffer * _buf) [inline]
Definition at line 135 of file g12Buffer.h.
              :
        toReturn(_toReturn), map(_map), buf(_buf)
        {}
Member Function Documentation
void corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::operator() (const BlockedRange< G12Buffer::InternalIndexType > & r) const [inline]
Definition at line 143 of file g12Buffer.h.
References corecvs::BlockedRange< IndexType >::begin(), buf, corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::G12Buffer::elementBlPrecomp(), corecvs::BlockedRange< IndexType >::end(), corecvs::AbstractBuffer< ElementType, IndexType >::getW(), corecvs::G12Buffer::isValidCoordBlPrecomp(), corecvs::FixedPointDisplace::map(), map, and toReturn.
        {
            G12Buffer::InternalIndexType j;
            G12Buffer::InternalIndexType newW = toReturn->getW();
            for (G12Buffer::InternalIndexType i = r.begin(); i < r.end(); i++)
            {
                for (j = 0; j < newW - 1; j++)
                {
                    BilinearMapPoint p = map->map(i,j);
                    if (buf->isValidCoordBlPrecomp(p))
                        toReturn->element(i,j) = buf->elementBlPrecomp(p);
                    else
                        toReturn->element(i,j) = 0x0;
                }
            }
        }
Member Data Documentation
G12Buffer* corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::buf [private]
Definition at line 132 of file g12Buffer.h.
Referenced by operator()().
const FixedPointDisplace* corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::map [private]
Definition at line 131 of file g12Buffer.h.
Referenced by operator()().
G12Buffer* corecvs::G12Buffer::ParallelDoReverseDeformationBlPrecomp::toReturn [private]
Definition at line 130 of file g12Buffer.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
core/buffers/g12Buffer.h