DeepView: GraphPlotParameters Class Reference
GraphPlotParameters Class Reference
Graph Plot Parameters Graph Plot Parameters.
#include <graphPlotParameters.h>
Public Types
enum FieldId {
GRAPHSTYLE_ID, WIDTH_ID, CENTERAT_ID, XGRID_ID,
YGRID_ID, XSCALE_ID, YSCALE_ID, CONTRAST_ID,
SELECTGRAPH_ID, FIX_TIME_VALUE_ID, FIX_GRID_VALUE_ID, GRAPH_PLOT_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
GraphStyle::GraphStyle graphStyle () const
int width () const
double centerAt () const
bool xGrid () const
bool yGrid () const
double xScale () const
double yScale () const
double contrast () const
bool selectGraph () const
bool fixTimeValue () const
bool fixGridValue () const
void setGraphStyle (GraphStyle::GraphStyle graphStyle)
void setWidth (int width)
void setCenterAt (double centerAt)
void setXGrid (bool xGrid)
void setYGrid (bool yGrid)
void setXScale (double xScale)
void setYScale (double yScale)
void setContrast (double contrast)
void setSelectGraph (bool selectGraph)
void setFixTimeValue (bool fixTimeValue)
void setFixGridValue (bool fixGridValue)
template<class VisitorType >
void accept (VisitorType &visitor)
GraphPlotParameters ()
GraphPlotParameters (GraphStyle::GraphStyle graphStyle, int width, double centerAt, bool xGrid, bool yGrid, double xScale, double yScale, double contrast, bool selectGraph, bool fixTimeValue, bool fixGridValue)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mGraphStyle
Section with variables.
int mWidth
width width
double mCenterAt
centerAt centerAt
bool mXGrid
xGrid xGrid
bool mYGrid
yGrid yGrid
double mXScale
xScale xScale
double mYScale
yScale yScale
double mContrast
contrast contrast
bool mSelectGraph
selectGraph selectGraph
bool mFixTimeValue
Fix Time value Fix Time value.
bool mFixGridValue
Fix Grid value Fix Grid value.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, GraphPlotParameters &toSave)
Detailed Description
Graph Plot Parameters Graph Plot Parameters.
Definition at line 39 of file graphPlotParameters.h.
Member Enumeration Documentation
enum GraphPlotParameters::FieldId
Enumerator:
GRAPHSTYLE_ID
WIDTH_ID
CENTERAT_ID
XGRID_ID
YGRID_ID
XSCALE_ID
YSCALE_ID
CONTRAST_ID
SELECTGRAPH_ID
FIX_TIME_VALUE_ID
FIX_GRID_VALUE_ID
GRAPH_PLOT_PARAMETERS_FIELD_ID_NUM
Definition at line 42 of file graphPlotParameters.h.
                 {
        GRAPHSTYLE_ID,
        WIDTH_ID,
        CENTERAT_ID,
        XGRID_ID,
        YGRID_ID,
        XSCALE_ID,
        YSCALE_ID,
        CONTRAST_ID,
        SELECTGRAPH_ID,
        FIX_TIME_VALUE_ID,
        FIX_GRID_VALUE_ID,
        GRAPH_PLOT_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
GraphPlotParameters::GraphPlotParameters () [inline]
Definition at line 262 of file graphPlotParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
GraphPlotParameters::GraphPlotParameters (GraphStyle::GraphStyle graphStyle, int width, double centerAt, bool xGrid, bool yGrid, double xScale, double yScale, double contrast, bool selectGraph, bool fixTimeValue, bool fixGridValue) [inline]
Definition at line 268 of file graphPlotParameters.h.
    {
        mGraphStyle = graphStyle;
        mWidth = width;
        mCenterAt = centerAt;
        mXGrid = xGrid;
        mYGrid = yGrid;
        mXScale = xScale;
        mYScale = yScale;
        mContrast = contrast;
        mSelectGraph = selectGraph;
        mFixTimeValue = fixTimeValue;
        mFixGridValue = fixGridValue;
    }
Member Function Documentation
template<class VisitorType > void GraphPlotParameters::accept (VisitorType & visitor) [inline]
Definition at line 247 of file graphPlotParameters.h.
    {
        visitor.visit((int &)mGraphStyle,         static_cast<const EnumField *>    (fields()[GRAPHSTYLE_ID]));
        visitor.visit(mWidth,                     static_cast<const IntField *>     (fields()[WIDTH_ID]));
        visitor.visit(mCenterAt,                  static_cast<const DoubleField *>  (fields()[CENTERAT_ID]));
        visitor.visit(mXGrid,                     static_cast<const BoolField *>    (fields()[XGRID_ID]));
        visitor.visit(mYGrid,                     static_cast<const BoolField *>    (fields()[YGRID_ID]));
        visitor.visit(mXScale,                    static_cast<const DoubleField *>  (fields()[XSCALE_ID]));
        visitor.visit(mYScale,                    static_cast<const DoubleField *>  (fields()[YSCALE_ID]));
        visitor.visit(mContrast,                  static_cast<const DoubleField *>  (fields()[CONTRAST_ID]));
        visitor.visit(mSelectGraph,               static_cast<const BoolField *>    (fields()[SELECTGRAPH_ID]));
        visitor.visit(mFixTimeValue,              static_cast<const BoolField *>    (fields()[FIX_TIME_VALUE_ID]));
        visitor.visit(mFixGridValue,              static_cast<const BoolField *>    (fields()[FIX_GRID_VALUE_ID]));
    }
double GraphPlotParameters::centerAt () const [inline]
Definition at line 143 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mCenterAt;
    }
static const char* corecvs::BaseReflection< GraphPlotParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
double GraphPlotParameters::contrast () const [inline]
Definition at line 168 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mContrast;
    }
static int corecvs::BaseReflection< GraphPlotParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< GraphPlotParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
bool GraphPlotParameters::fixGridValue () const [inline]
Definition at line 183 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mFixGridValue;
    }
bool GraphPlotParameters::fixTimeValue () const [inline]
Definition at line 178 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mFixTimeValue;
    }
const void* GraphPlotParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 129 of file graphPlotParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< GraphPlotParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
GraphStyle::GraphStyle GraphPlotParameters::graphStyle () const [inline]
Definition at line 133 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return static_cast<GraphStyle::GraphStyle>(mGraphStyle);
    }
static const char* corecvs::BaseReflection< GraphPlotParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< GraphPlotParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void GraphPlotParameters::print () [inline]
Definition at line 302 of file graphPlotParameters.h.
    {
        cout << *this;
    }
bool GraphPlotParameters::selectGraph () const [inline]
Definition at line 173 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mSelectGraph;
    }
void GraphPlotParameters::setCenterAt (double centerAt) [inline]
Definition at line 199 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mCenterAt = centerAt;
    }
void GraphPlotParameters::setContrast (double contrast) [inline]
Definition at line 224 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mContrast = contrast;
    }
void GraphPlotParameters::setFixGridValue (bool fixGridValue) [inline]
Definition at line 239 of file graphPlotParameters.h.
    {
        mFixGridValue = fixGridValue;
    }
void GraphPlotParameters::setFixTimeValue (bool fixTimeValue) [inline]
Definition at line 234 of file graphPlotParameters.h.
    {
        mFixTimeValue = fixTimeValue;
    }
void GraphPlotParameters::setGraphStyle (GraphStyle::GraphStyle graphStyle) [inline]
Definition at line 189 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mGraphStyle = graphStyle;
    }
void GraphPlotParameters::setSelectGraph (bool selectGraph) [inline]
Definition at line 229 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mSelectGraph = selectGraph;
    }
void GraphPlotParameters::setWidth (int width) [inline]
Definition at line 194 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mWidth = width;
    }
void GraphPlotParameters::setXGrid (bool xGrid) [inline]
Definition at line 204 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mXGrid = xGrid;
    }
void GraphPlotParameters::setXScale (double xScale) [inline]
Definition at line 214 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mXScale = xScale;
    }
void GraphPlotParameters::setYGrid (bool yGrid) [inline]
Definition at line 209 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mYGrid = yGrid;
    }
void GraphPlotParameters::setYScale (double yScale) [inline]
Definition at line 219 of file graphPlotParameters.h.
Referenced by GraphPlotDialog::resetSettings().
    {
        mYScale = yScale;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int GraphPlotParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file graphPlotParameters.cpp.
References CENTERAT_ID, CONTRAST_ID, corecvs::BaseReflection< GraphPlotParameters >::fields(), FIX_GRID_VALUE_ID, FIX_TIME_VALUE_ID, GRAPHSTYLE_ID, mCenterAt, mContrast, mFixGridValue, mFixTimeValue, mGraphStyle, mSelectGraph, mWidth, mXGrid, mXScale, mYGrid, mYScale, corecvs::BaseReflection< GraphPlotParameters >::naming(), SELECTGRAPH_ID, WIDTH_ID, XGRID_ID, XSCALE_ID, YGRID_ID, and YSCALE_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Graph Plot Parameters",
        "Graph Plot Parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          GraphPlotParameters::GRAPHSTYLE_ID,
          offsetof(GraphPlotParameters, mGraphStyle),
          0,
          "graphStyle",
          "graphStyle",
          "graphStyle",
           NULL
        )
    );
    fields().push_back(
        new IntField
        (
          GraphPlotParameters::WIDTH_ID,
          offsetof(GraphPlotParameters, mWidth),
          1,
          "width",
          "width",
          "width"
        )
    );
    fields().push_back(
        new DoubleField
        (
          GraphPlotParameters::CENTERAT_ID,
          offsetof(GraphPlotParameters, mCenterAt),
          0,
          "centerAt",
          "centerAt",
          "centerAt"
        )
    );
    fields().push_back(
        new BoolField
        (
          GraphPlotParameters::XGRID_ID,
          offsetof(GraphPlotParameters, mXGrid),
          false,
          "xGrid",
          "xGrid",
          "xGrid"
        )
    );
    fields().push_back(
        new BoolField
        (
          GraphPlotParameters::YGRID_ID,
          offsetof(GraphPlotParameters, mYGrid),
          false,
          "yGrid",
          "yGrid",
          "yGrid"
        )
    );
    fields().push_back(
        new DoubleField
        (
          GraphPlotParameters::XSCALE_ID,
          offsetof(GraphPlotParameters, mXScale),
          1,
          "xScale",
          "xScale",
          "xScale"
        )
    );
    fields().push_back(
        new DoubleField
        (
          GraphPlotParameters::YSCALE_ID,
          offsetof(GraphPlotParameters, mYScale),
          1,
          "yScale",
          "yScale",
          "yScale"
        )
    );
    fields().push_back(
        new DoubleField
        (
          GraphPlotParameters::CONTRAST_ID,
          offsetof(GraphPlotParameters, mContrast),
          50,
          "contrast",
          "contrast",
          "contrast"
        )
    );
    fields().push_back(
        new BoolField
        (
          GraphPlotParameters::SELECTGRAPH_ID,
          offsetof(GraphPlotParameters, mSelectGraph),
          false,
          "selectGraph",
          "selectGraph",
          "selectGraph"
        )
    );
    fields().push_back(
        new BoolField
        (
          GraphPlotParameters::FIX_TIME_VALUE_ID,
          offsetof(GraphPlotParameters, mFixTimeValue),
          false,
          "Fix Time value",
          "Fix Time value",
          "Fix Time value"
        )
    );
    fields().push_back(
        new BoolField
        (
          GraphPlotParameters::FIX_GRID_VALUE_ID,
          offsetof(GraphPlotParameters, mFixGridValue),
          true,
          "Fix Grid value",
          "Fix Grid value",
          "Fix Grid value"
        )
    );
   return 0;
}
int GraphPlotParameters::width () const [inline]
Definition at line 138 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mWidth;
    }
bool GraphPlotParameters::xGrid () const [inline]
Definition at line 148 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mXGrid;
    }
double GraphPlotParameters::xScale () const [inline]
Definition at line 158 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mXScale;
    }
bool GraphPlotParameters::yGrid () const [inline]
Definition at line 153 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mYGrid;
    }
double GraphPlotParameters::yScale () const [inline]
Definition at line 163 of file graphPlotParameters.h.
Referenced by GraphPlotParametersControlWidget::setParameters().
    {
        return mYScale;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, GraphPlotParameters & toSave) [friend]
Definition at line 295 of file graphPlotParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< GraphPlotParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
double GraphPlotParameters::mCenterAt
centerAt centerAt
Definition at line 75 of file graphPlotParameters.h.
Referenced by staticInit().
double GraphPlotParameters::mContrast
contrast contrast
Definition at line 105 of file graphPlotParameters.h.
Referenced by staticInit().
bool GraphPlotParameters::mFixGridValue
Fix Grid value Fix Grid value.
Definition at line 123 of file graphPlotParameters.h.
Referenced by staticInit().
bool GraphPlotParameters::mFixTimeValue
Fix Time value Fix Time value.
Definition at line 117 of file graphPlotParameters.h.
Referenced by staticInit().
int GraphPlotParameters::mGraphStyle
Section with variables.
graphStyle graphStyle
Definition at line 63 of file graphPlotParameters.h.
Referenced by staticInit().
bool GraphPlotParameters::mSelectGraph
selectGraph selectGraph
Definition at line 111 of file graphPlotParameters.h.
Referenced by staticInit().
int GraphPlotParameters::mWidth
width width
Definition at line 69 of file graphPlotParameters.h.
Referenced by staticInit().
bool GraphPlotParameters::mXGrid
xGrid xGrid
Definition at line 81 of file graphPlotParameters.h.
Referenced by staticInit().
double GraphPlotParameters::mXScale
xScale xScale
Definition at line 93 of file graphPlotParameters.h.
Referenced by staticInit().
bool GraphPlotParameters::mYGrid
yGrid yGrid
Definition at line 87 of file graphPlotParameters.h.
Referenced by staticInit().
double GraphPlotParameters::mYScale
yScale yScale
Definition at line 99 of file graphPlotParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< GraphPlotParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
utils/widgets/generated/graphPlotParameters.h
utils/widgets/generated/graphPlotParameters.cpp