DeepView: AbstractFlowColorer Class Reference
AbstractFlowColorer Class Reference
#include <abstractFlowColorer.h>
Public Member Functions
AbstractFlowColorer (const DrawColoring _style=drawHeatColoring)
virtual QColor getColor (Vector2d16 &point)=0
virtual uint32_t getPacked (Vector2d16 &point)=0
virtual bool shouldDrawEllipses (int disp)=0
virtual QColor ellipsesColor ()=0
Static Public Member Functions
static int hsvCacheInit ()
static uint32_t packRGB (unsigned r, unsigned g, unsigned b)
Public Attributes
DrawColoring style
Static Public Attributes
static QColor * hsvColorCache
static uint32_t * hsvPackedCache
static int dummy = AbstractFlowColorer::hsvCacheInit()
Detailed Description
Definition at line 16 of file abstractFlowColorer.h.
Constructor & Destructor Documentation
AbstractFlowColorer::AbstractFlowColorer (const DrawColoring _style = drawHeatColoring) [inline]
Definition at line 26 of file abstractFlowColorer.h.
                                                                      :
        style(_style ) {};
Member Function Documentation
virtual QColor AbstractFlowColorer::ellipsesColor () [pure virtual]
Implemented in StereoColorer, and FlowColorer.
Referenced by FlowDrawer::draw().
virtual QColor AbstractFlowColorer::getColor (Vector2d16 & point) [pure virtual]
Implemented in StereoColorer, and FlowColorer.
Referenced by FlowDrawer::draw().
virtual uint32_t AbstractFlowColorer::getPacked (Vector2d16 & point) [pure virtual]
Implemented in StereoColorer, and FlowColorer.
Referenced by FlowDrawer::drawBigDotsFast(), and FlowDrawer::drawDotsFast().
int AbstractFlowColorer::hsvCacheInit () [static]
Definition at line 17 of file abstractFlowColorer.cpp.
References hsvColorCache, hsvPackedCache, and packRGB().
{
    hsvColorCache  = new QColor[256];
    hsvPackedCache = new uint32_t[256];
    for (unsigned i = 0; i < 256; i++)
    {
        QColor color;
        color.setHsv(i, 255, 255, 255);
        uint32_t r = color.red();
        uint32_t g = color.green();
        uint32_t b = color.blue();
        hsvColorCache [i] = color;
        hsvPackedCache[i] = packRGB(r,g,b);
    }
    return 0;
}
static uint32_t AbstractFlowColorer::packRGB (unsigned r, unsigned g, unsigned b) [inline, static]
Definition at line 29 of file abstractFlowColorer.h.
Referenced by FlowColorer::getPacked(), StereoColorer::getPacked(), and hsvCacheInit().
    {
        return (0xFF << 24) | (r << 16) | (g << 8) | (b);
    }
virtual bool AbstractFlowColorer::shouldDrawEllipses (int disp) [pure virtual]
Implemented in StereoColorer, and FlowColorer.
Referenced by FlowDrawer::draw().
Member Data Documentation
int AbstractFlowColorer::dummy = AbstractFlowColorer::hsvCacheInit() [static]
Definition at line 21 of file abstractFlowColorer.h.
QColor * AbstractFlowColorer::hsvColorCache [static]
Definition at line 19 of file abstractFlowColorer.h.
Referenced by FlowColorer::getColor(), StereoColorer::getColor(), and hsvCacheInit().
uint32_t * AbstractFlowColorer::hsvPackedCache [static]
Definition at line 20 of file abstractFlowColorer.h.
Referenced by FlowColorer::getPacked(), StereoColorer::getPacked(), and hsvCacheInit().
DrawColoring AbstractFlowColorer::style
Definition at line 24 of file abstractFlowColorer.h.
Referenced by FlowColorer::getColor(), and FlowColorer::getPacked().
The documentation for this class was generated from the following files:
utils/flowcolorers/abstractFlowColorer.h
utils/flowcolorers/abstractFlowColorer.cpp