DeepView: OperationParameters Class Reference
OperationParameters Class Reference
Operation Parameters Operation Parameters.
#include <operationParameters.h>
Public Types
enum FieldId { OPERATION_ID, OPERATION_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
Operation::Operation operation () const
void setOperation (Operation::Operation operation)
template<class VisitorType >
void accept (VisitorType &visitor)
OperationParameters ()
OperationParameters (Operation::Operation operation)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mOperation
Section with variables.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, OperationParameters &toSave)
Detailed Description
Operation Parameters Operation Parameters.
Definition at line 39 of file operationParameters.h.
Member Enumeration Documentation
enum OperationParameters::FieldId
Enumerator:
OPERATION_ID
OPERATION_PARAMETERS_FIELD_ID_NUM
Definition at line 42 of file operationParameters.h.
                 {
        OPERATION_ID,
        OPERATION_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
OperationParameters::OperationParameters () [inline]
Definition at line 82 of file operationParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
OperationParameters::OperationParameters (Operation::Operation operation) [inline]
Definition at line 88 of file operationParameters.h.
    {
        mOperation = operation;
    }
Member Function Documentation
template<class VisitorType > void OperationParameters::accept (VisitorType & visitor) [inline]
Definition at line 77 of file operationParameters.h.
Referenced by corecvs::OperationFilter::deserialize(), and corecvs::OperationFilter::serialize().
    {
        visitor.visit((int &)mOperation,          static_cast<const EnumField *>    (fields()[OPERATION_ID]));
    }
static const char* corecvs::BaseReflection< OperationParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< OperationParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< OperationParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* OperationParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 59 of file operationParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< OperationParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< OperationParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< OperationParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
Operation::Operation OperationParameters::operation () const [inline]
Definition at line 63 of file operationParameters.h.
Referenced by OperationParametersControlWidget::setParameters().
    {
        return static_cast<Operation::Operation>(mOperation);
    }
void OperationParameters::print () [inline]
Definition at line 102 of file operationParameters.h.
    {
        cout << *this;
    }
void OperationParameters::setOperation (Operation::Operation operation) [inline]
Definition at line 69 of file operationParameters.h.
    {
        mOperation = operation;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int OperationParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file operationParameters.cpp.
References corecvs::BaseReflection< OperationParameters >::fields(), mOperation, corecvs::BaseReflection< OperationParameters >::naming(), and OPERATION_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Operation Parameters",
        "Operation Parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          OperationParameters::OPERATION_ID,
          offsetof(OperationParameters, mOperation),
          0,
          "operation",
          "operation",
          "operation",
           NULL
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, OperationParameters & toSave) [friend]
Definition at line 95 of file operationParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< OperationParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int OperationParameters::mOperation
Section with variables.
operation operation
Definition at line 53 of file operationParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< OperationParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/operationParameters.h
core/xml/generated/operationParameters.cpp