DeepView: XmlGetter Class Reference
XmlGetter Class Reference
#include <xmlGetter.h>
Public Member Functions
XmlGetter (QString const &fileName)
template<class Type >
void visit (Type &field, Type defaultValue, const char *fieldName)
template<typename inputType , typename reflectionType >
void visit (inputType &field, const reflectionType *fieldDescriptor)
template<>
void visit (bool &boolField, bool defaultValue, const char *fieldName)
template<>
void visit (double &doubleField, double defaultValue, const char *fieldName)
template<>
void visit (float &floatField, float defaultValue, const char *fieldName)
template<>
void visit (int &intField, int defaultValue, const char *fieldName)
template<>
void visit (int &, const IntField *)
template<>
void visit (double &, const DoubleField *)
template<>
void visit (float &, const FloatField *)
template<>
void visit (bool &, const BoolField *)
template<>
void visit (void *&, const PointerField *)
template<>
void visit (int &, const EnumField *)
template<>
void visit (int &intField, int defaultValue, const char *)
template<>
void visit (double &doubleField, double defaultValue, const char *)
template<>
void visit (float &floatField, float defaultValue, const char *)
template<>
void visit (bool &boolField, bool defaultValue, const char *)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (float &field, const FloatField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
template<>
void visit (void *&field, const PointerField *fieldDescriptor)
template<>
void visit (int &field, const EnumField *fieldDescriptor)
string getCurrentPath ()
string getChildPath (string child)
void pushChild (const string child)
void popChild ()
Public Attributes
string separator
T elements
STL member.
Static Public Attributes
static string SEPARATOR_DEFAULT = "."
Private Attributes
QString mFileName
QDomElement mDocumentElement
Detailed Description
Definition at line 19 of file xmlGetter.h.
Constructor & Destructor Documentation
XmlGetter::XmlGetter (QString const & fileName)
Definition at line 7 of file xmlGetter.cpp.
References mDocumentElement, and mFileName.
{
    mFileName = fileName;
    QFile file(mFileName);
    if (!file.open(QFile::ReadWrite))
        return;
    QDomDocument doc("document");
    doc.setContent(&file);
    mDocumentElement = doc.documentElement();
    file.close();
}
Member Function Documentation
string corecvs::BasePathVisitor::getChildPath (string child) [inline, inherited]
Definition at line 35 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getCurrentPath(), and corecvs::BasePathVisitor::separator.
Referenced by corecvs::BasePathVisitor::pushChild().
    {
       string newPath = getCurrentPath();
       if (!newPath.empty())
           newPath.append(separator);
       newPath.append(child);
       return newPath;
    }
string corecvs::BasePathVisitor::getCurrentPath () [inline, inherited]
Definition at line 28 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
    {
        if (empty())
            return "";
        return back();
    }
void corecvs::BasePathVisitor::popChild () [inline, inherited]
Definition at line 55 of file basePathVisitor.h.
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        pop_back();
    }
void corecvs::BasePathVisitor::pushChild (const string child) [inline, inherited]
Definition at line 50 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getChildPath().
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        push_back(getChildPath(child));
    }
template<> void XmlGetter::visit (bool & boolField, bool defaultValue, const char * fieldName)
Definition at line 20 of file xmlGetter.cpp.
{
    QDomElement element = mDocumentElement.toDocument().elementById(fieldName);
    if (element.isNull())
        boolField = defaultValue;
    else
        boolField = element.attribute("value", defaultValue ? "true" : "false") == "true";
}
template<class Type > void XmlGetter::visit (Type & field, Type defaultValue, const char * fieldName) [inline]
Definition at line 24 of file xmlGetter.h.
    {
        pushChild(fieldName);
            field.accept(*this);
        popChild();
    }
template<> void XmlGetter::visit (double & doubleField, double defaultValue, const char * fieldName)
Definition at line 30 of file xmlGetter.cpp.
{
    QDomElement element = mDocumentElement.toDocument().elementById(fieldName);
    if (element.isNull())
        doubleField = defaultValue;
    else
        doubleField = element.attribute("value", QString::number(defaultValue)).toDouble();
}
template<typename inputType , typename reflectionType > void XmlGetter::visit (inputType & field, const reflectionType * fieldDescriptor) [inline]
Definition at line 32 of file xmlGetter.h.
    {
        pushChild(fieldDescriptor->getSimpleName());
           field.accept(*this);
        popChild();
    }
template<> void XmlGetter::visit (float & floatField, float defaultValue, const char * fieldName)
Definition at line 40 of file xmlGetter.cpp.
{
    QDomElement element = mDocumentElement.toDocument().elementById(fieldName);
    if (element.isNull())
        floatField = defaultValue;
    else
        floatField = element.attribute("value", QString::number(defaultValue)).toFloat();
}
template<> void XmlGetter::visit (int & intField, int defaultValue, const char *)
template<> void XmlGetter::visit (double & doubleField, double defaultValue, const char *)
template<> void XmlGetter::visit (int & intField, int defaultValue, const char * fieldName)
Definition at line 50 of file xmlGetter.cpp.
{
    QDomElement element = mDocumentElement.toDocument().elementById(fieldName);
    if (element.isNull())
        intField = defaultValue;
    else
        intField = element.attribute("value", QString::number(defaultValue)).toDouble();
}
template<> void XmlGetter::visit (float & floatField, float defaultValue, const char *)
template<> void XmlGetter::visit (bool & boolField, bool defaultValue, const char *)
template<> void XmlGetter::visit (int & field, const IntField * fieldDescriptor)
template<> void XmlGetter::visit (double & field, const DoubleField * fieldDescriptor)
template<> void XmlGetter::visit (int & , const IntField *)
Definition at line 62 of file xmlGetter.cpp.
{
    qDebug() << "XmlGetter::visit<int, IntField>(int &field, const IntField *fieldDescriptor) NOT YET SUPPORTED";
}
template<> void XmlGetter::visit (float & field, const FloatField * fieldDescriptor)
template<> void XmlGetter::visit (bool & field, const BoolField * fieldDescriptor)
template<> void XmlGetter::visit (double & , const DoubleField *)
Definition at line 68 of file xmlGetter.cpp.
{
    qDebug() << "XmlGetter::visit<int, DoubleField>(double &field, const DoubleField *fieldDescriptor) NOT YET SUPPORTED";
}
template<> void XmlGetter::visit (void *& field, const PointerField * fieldDescriptor)
template<> void XmlGetter::visit (float & , const FloatField *)
Definition at line 74 of file xmlGetter.cpp.
{
    qDebug() << "XmlGetter::visit<int, FloatField>(float &field, const FloatField *fieldDescriptor) NOT YET SUPPORTED";
}
template<> void XmlGetter::visit (int & field, const EnumField * fieldDescriptor)
template<> void XmlGetter::visit (bool & , const BoolField *)
Definition at line 80 of file xmlGetter.cpp.
{
    qDebug() << "XmlGetter::visit<int, BoolField>(bool &field, const BoolField *fieldDescriptor) NOT YET SUPPORTED";
}
template<> void XmlGetter::visit (void *& , const PointerField *)
Definition at line 92 of file xmlGetter.cpp.
{
    qDebug() << "XmlGetter::visit<int, PointerField>(void * &field, const PointerField * /*fieldDescriptor*/) NOT YET SUPPORTED";
}
template<> void XmlGetter::visit (int & , const EnumField *)
Definition at line 98 of file xmlGetter.cpp.
{
    qDebug() << "XmlGetter::visit<int, EnumField>(int &field, const EnumField *fieldDescriptor) NOT YET SUPPORTED";
}
Member Data Documentation
template<typename T> T std::deque< T >::elements [inherited]
STL member.
QDomElement XmlGetter::mDocumentElement [private]
Definition at line 41 of file xmlGetter.h.
Referenced by XmlGetter().
QString XmlGetter::mFileName [private]
Definition at line 40 of file xmlGetter.h.
Referenced by XmlGetter().
string corecvs::BasePathVisitor::separator [inherited]
Definition at line 26 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
string corecvs::BasePathVisitor::SEPARATOR_DEFAULT = "." [static, inherited]
Definition at line 24 of file basePathVisitor.h.
The documentation for this class was generated from the following files:
utils/visitors/xmlGetter.h
utils/visitors/xmlGetter.cpp