DeepView: SobelParameters Class Reference
SobelParameters Class Reference
Sobel Parameters Sobel Parameters.
#include <sobelParameters.h>
Public Types
enum FieldId { MIXING_TYPE_ID, HORIZONTAL_ID, VERTICAL_ID, SOBEL_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
SobelMixingType::SobelMixingType mixingType () const
bool horizontal () const
bool vertical () const
void setMixingType (SobelMixingType::SobelMixingType mixingType)
void setHorizontal (bool horizontal)
void setVertical (bool vertical)
template<class VisitorType >
void accept (VisitorType &visitor)
SobelParameters ()
SobelParameters (SobelMixingType::SobelMixingType mixingType, bool horizontal, bool vertical)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mMixingType
Section with variables.
bool mHorizontal
Horizontal Horizontal.
bool mVertical
Vertical Vertical.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, SobelParameters &toSave)
Detailed Description
Sobel Parameters Sobel Parameters.
Definition at line 39 of file sobelParameters.h.
Member Enumeration Documentation
enum SobelParameters::FieldId
Enumerator:
MIXING_TYPE_ID
HORIZONTAL_ID
VERTICAL_ID
SOBEL_PARAMETERS_FIELD_ID_NUM
Definition at line 42 of file sobelParameters.h.
                 {
        MIXING_TYPE_ID,
        HORIZONTAL_ID,
        VERTICAL_ID,
        SOBEL_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
SobelParameters::SobelParameters () [inline]
Definition at line 118 of file sobelParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
SobelParameters::SobelParameters (SobelMixingType::SobelMixingType mixingType, bool horizontal, bool vertical) [inline]
Definition at line 124 of file sobelParameters.h.
    {
        mMixingType = mixingType;
        mHorizontal = horizontal;
        mVertical = vertical;
    }
Member Function Documentation
template<class VisitorType > void SobelParameters::accept (VisitorType & visitor) [inline]
Definition at line 111 of file sobelParameters.h.
Referenced by corecvs::SobelFilter::deserialize(), and corecvs::SobelFilter::serialize().
    {
        visitor.visit((int &)mMixingType,         static_cast<const EnumField *>    (fields()[MIXING_TYPE_ID]));
        visitor.visit(mHorizontal,                static_cast<const BoolField *>    (fields()[HORIZONTAL_ID]));
        visitor.visit(mVertical,                  static_cast<const BoolField *>    (fields()[VERTICAL_ID]));
    }
static const char* corecvs::BaseReflection< SobelParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< SobelParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< SobelParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
const void* SobelParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 73 of file sobelParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< SobelParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
bool SobelParameters::horizontal () const [inline]
Definition at line 82 of file sobelParameters.h.
Referenced by corecvs::SobelFilter::operator()(), and SobelParametersControlWidget::setParameters().
    {
        return mHorizontal;
    }
SobelMixingType::SobelMixingType SobelParameters::mixingType () const [inline]
Definition at line 77 of file sobelParameters.h.
Referenced by SobelParametersControlWidget::setParameters().
    {
        return static_cast<SobelMixingType::SobelMixingType>(mMixingType);
    }
static const char* corecvs::BaseReflection< SobelParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< SobelParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void SobelParameters::print () [inline]
Definition at line 142 of file sobelParameters.h.
    {
        cout << *this;
    }
void SobelParameters::setHorizontal (bool horizontal) [inline]
Definition at line 98 of file sobelParameters.h.
    {
        mHorizontal = horizontal;
    }
void SobelParameters::setMixingType (SobelMixingType::SobelMixingType mixingType) [inline]
Definition at line 93 of file sobelParameters.h.
    {
        mMixingType = mixingType;
    }
void SobelParameters::setVertical (bool vertical) [inline]
Definition at line 103 of file sobelParameters.h.
    {
        mVertical = vertical;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int SobelParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file sobelParameters.cpp.
References corecvs::BaseReflection< SobelParameters >::fields(), HORIZONTAL_ID, mHorizontal, MIXING_TYPE_ID, mMixingType, mVertical, corecvs::BaseReflection< SobelParameters >::naming(), and VERTICAL_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Sobel Parameters",
        "Sobel Parameters",
        ""
    );
    fields().push_back(
        new EnumField
        (
          SobelParameters::MIXING_TYPE_ID,
          offsetof(SobelParameters, mMixingType),
          0,
          "Mixing Type",
          "Mixing Type",
          "Mixing Type",
           NULL
        )
    );
    fields().push_back(
        new BoolField
        (
          SobelParameters::HORIZONTAL_ID,
          offsetof(SobelParameters, mHorizontal),
          false,
          "Horizontal",
          "Horizontal",
          "Horizontal"
        )
    );
    fields().push_back(
        new BoolField
        (
          SobelParameters::VERTICAL_ID,
          offsetof(SobelParameters, mVertical),
          false,
          "Vertical",
          "Vertical",
          "Vertical"
        )
    );
   return 0;
}
bool SobelParameters::vertical () const [inline]
Definition at line 87 of file sobelParameters.h.
Referenced by corecvs::SobelFilter::operator()(), and SobelParametersControlWidget::setParameters().
    {
        return mVertical;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, SobelParameters & toSave) [friend]
Definition at line 135 of file sobelParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< SobelParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
bool SobelParameters::mHorizontal
Horizontal Horizontal.
Definition at line 61 of file sobelParameters.h.
Referenced by staticInit().
int SobelParameters::mMixingType
Section with variables.
Mixing Type Mixing Type
Definition at line 55 of file sobelParameters.h.
Referenced by corecvs::SobelFilter::operator()(), and staticInit().
bool SobelParameters::mVertical
Vertical Vertical.
Definition at line 67 of file sobelParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< SobelParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/sobelParameters.h
core/xml/generated/sobelParameters.cpp