DeepView: corecvs::BaseTimeStatisticsCollector Class Reference
corecvs::BaseTimeStatisticsCollector Class Reference
#include <calculationStats.h>
Classes
class AdvancedPrinter
class OrderFilter
class SimplePrinter
class StringFilter
class WikiPrinter
Public Types
typedef map< string, UnitedStat > StatsMap
Public Member Functions
BaseTimeStatisticsCollector ()
virtual void reset ()
virtual void addSingleStat (string name, const SingleStat &stat)
virtual void addStatistics (Statistics &stats)
virtual int maximumCaptionLength () const
template<class StreamType >
void printStats (StreamType &stream) const
virtual void printSimple ()
virtual void printAdvanced ()
virtual void printWiki ()
Public Attributes
StatsMap sumValues
vector< OrderFilter * > mOrderFilters
Detailed Description
Definition at line 131 of file calculationStats.h.
Member Typedef Documentation
typedef map<string, UnitedStat> corecvs::BaseTimeStatisticsCollector::StatsMap
Definition at line 134 of file calculationStats.h.
Constructor & Destructor Documentation
corecvs::BaseTimeStatisticsCollector::BaseTimeStatisticsCollector () [inline]
Definition at line 168 of file calculationStats.h.
    {
    }
Member Function Documentation
virtual void corecvs::BaseTimeStatisticsCollector::addSingleStat (string name, const SingleStat & stat) [inline, virtual]
Definition at line 178 of file calculationStats.h.
References corecvs::UnitedStat::addValue(), and sumValues.
Referenced by addStatistics(), and ContentStatistics::transition().
    {
        UnitedStat unitedStat;
        //typename map<string, UnitedStat>::iterator uit;
        map<string, UnitedStat>::iterator uit;
        uit = sumValues.find(name);
        if (uit != sumValues.end())
        {
           unitedStat = uit->second;
        }
        unitedStat.addValue(stat);
        sumValues[name] = unitedStat;
    }
virtual void corecvs::BaseTimeStatisticsCollector::addStatistics (Statistics & stats) [inline, virtual]
Definition at line 194 of file calculationStats.h.
References addSingleStat(), and corecvs::Statistics::values.
Referenced by StatisticsDialog::addStats().
    {
        /* New style */
        map<string, SingleStat>::iterator it;
        for (it = stats.values.begin(); it != stats.values.end(); ++it )
        {
            string name = it->first;
            SingleStat stat = it->second;
            addSingleStat(name, stat);
        }
    }
virtual int corecvs::BaseTimeStatisticsCollector::maximumCaptionLength () const [inline, virtual]
Definition at line 206 of file calculationStats.h.
References sumValues.
Referenced by printStats().
    {
        //typename StatsMap::const_iterator uit;
        StatsMap::const_iterator uit;
        int maxCaptionLen = 0;
        for (uit = this->sumValues.begin(); uit != this->sumValues.end(); ++uit )
        {
            int len = (int)uit->first.length();
            if (len > maxCaptionLen)
            {
                maxCaptionLen = len;
            }
        }
        return maxCaptionLen;
    }
virtual void corecvs::BaseTimeStatisticsCollector::printAdvanced () [inline, virtual]
Definition at line 325 of file calculationStats.h.
References printStats().
    {
        printf("=============================================================\n");
        AdvancedPrinter printer;
        printStats(printer);
        printf("=============================================================\n");
    }
virtual void corecvs::BaseTimeStatisticsCollector::printSimple () [inline, virtual]
Definition at line 294 of file calculationStats.h.
References printStats().
    {
        printf("=============================================================\n");
        SimplePrinter printer;
        printStats(printer);
        printf("=============================================================\n");
    }
template<class StreamType > void corecvs::BaseTimeStatisticsCollector::printStats (StreamType & stream) const [inline]
Definition at line 224 of file calculationStats.h.
References corecvs::BaseTimeStatisticsCollector::OrderFilter::filter(), maximumCaptionLength(), mOrderFilters, and sumValues.
Referenced by printAdvanced(), printSimple(), and printWiki().
    {
        typename StatsMap::const_iterator uit;
        /* Get caption width */
        int maxCaptionLen = maximumCaptionLength();
        /* Flags */
        int size = this->sumValues.size();
        bool *isPrinted = new bool[size];
        for (int i = 0; i < size; i++)
        {
            isPrinted[i] = false;
        }
        int printCount = 0;
        /* First show all filters */
        //printf("Totaly we have %d filters\n", mOrderFilters.size());
        for (unsigned i = 0; i < mOrderFilters.size(); i++)
        {
            OrderFilter *filter = mOrderFilters[i];
            int j = 0;
            for (uit = this->sumValues.begin(); uit != this->sumValues.end(); ++uit, j++ )
            {
                if (isPrinted[j])
                {
                    continue;
                }
                if (filter->filter(uit->first))
                {
                    isPrinted[j] = true;
                    stream.printUnitedStat(uit->first, maxCaptionLen, uit->second, printCount);
                    printCount++;
                }
            }
        }
        int j = 0;
        for (uit = this->sumValues.begin(); uit != this->sumValues.end(); ++uit, j++ )
        {
            if (isPrinted[j])
            {
                continue;
            }
            stream.printUnitedStat(uit->first, maxCaptionLen, uit->second, printCount);
            printCount++;
        }
        deletearr_safe(isPrinted);
    }
virtual void corecvs::BaseTimeStatisticsCollector::printWiki () [inline, virtual]
Definition at line 342 of file calculationStats.h.
References printStats().
    {
        printf("|");
/*        for (unsigned i = 0; i < Statistics::SIZE; i++)
        {
            printf("%s|", Statistics::getNames()[i]);
        }*/
        printf("\n");
        printf("====================Paste this to  wiki======================\n");
        const char *withsse = "";
#ifdef WITH_SSE
        withsse = "!y.png!";
#endif
        const char *withtbb = "";
#ifdef WITH_TBB
        withtbb = "!y.png!";
#endif
        const char *osId = "!l.png!";
#ifdef Q_OS_WIN
        osId = "!w.png!";
#endif
#ifdef Q_OS_MAC
        osId = "!a.png!"
#endif
        const char *is64bit = "!3.png!";
#ifdef __x86_64
    is64bit = "!6.png!";
#endif
        const char *compiler = "unkn";
#if defined (__GNUC__) && defined (__GNUC_MINOR__)
#define GCC_XSTR(value) GCC_STR(value)
#define GCC_STR(value) #value
        compiler = "g" GCC_XSTR(__GNUC__) "." GCC_XSTR(__GNUC_MINOR__);
#undef GCC_STR
#undef GCC_XSTR
#elif defined (__clang__)
        compiler = "clan";
#elif defined (_MSC_VER)
        compiler = "msvc";
#elif defined (__MINGW32__)
        compiler = "mgw";
#elif defined (__INTEL_COMPILER)
        compiler = "icc";
#endif
               //       OS  bits comp tbb  sse
        printf("|%-15s|%-7s|%-7s|%-4s|%-7s|%-7s|", " ", osId, is64bit, compiler, withtbb, withsse);
        WikiPrinter printer;
        printStats(printer);
        printf("\n");
        printf("=============================================================\n");
    }
virtual void corecvs::BaseTimeStatisticsCollector::reset (void) [inline, virtual]
Definition at line 173 of file calculationStats.h.
References sumValues.
Referenced by StatisticsDialog::reset().
    {
        sumValues.clear();
    }
Member Data Documentation
vector<OrderFilter *> corecvs::BaseTimeStatisticsCollector::mOrderFilters
Definition at line 166 of file calculationStats.h.
Referenced by printStats().
StatsMap corecvs::BaseTimeStatisticsCollector::sumValues
Definition at line 136 of file calculationStats.h.
Referenced by addSingleStat(), maximumCaptionLength(), printStats(), and reset().
The documentation for this class was generated from the following file:
core/stats/calculationStats.h