DeepView: ThickeningParametersControlWidget Class Reference
ThickeningParametersControlWidget Class Reference
#include <thickeningParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
ThickeningParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~ThickeningParametersControlWidget ()
ThickeningParameters * createParameters () const
void setParameters (const ThickeningParameters &input)
void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_ThickeningParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 11 of file thickeningParametersControlWidget.h.
Constructor & Destructor Documentation
ThickeningParametersControlWidget::ThickeningParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file thickeningParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::ThickeningParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->powerSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
ThickeningParametersControlWidget::~ThickeningParametersControlWidget ()
Definition at line 26 of file thickeningParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void ThickeningParametersControlWidget::changeParameters () [inline, slot]
Definition at line 32 of file thickeningParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
ThickeningParameters * ThickeningParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 48 of file thickeningParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    ThickeningParameters *result = new ThickeningParameters(
          mUi->powerSpinBox->value()
    );
    return result;
}
virtual BaseReflectionStatic* ThickeningParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 23 of file thickeningParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void ThickeningParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 32 of file thickeningParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    ThickeningParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void ThickeningParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by setParameters(), and ThickeningParametersControlWidget().
void ThickeningParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 40 of file thickeningParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    ThickeningParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void ThickeningParametersControlWidget::setParameters (const ThickeningParameters & input)
Definition at line 62 of file thickeningParametersControlWidget.cpp.
References mUi, paramsChanged(), and ThickeningParameters::power().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->powerSpinBox->setValue(input.power());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void ThickeningParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 71 of file thickeningParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    ThickeningParameters *inputCasted = static_cast<ThickeningParameters *>(input);
    setParameters(*inputCasted);
}
void ThickeningParametersControlWidget::valueChanged () [signal]
Referenced by ThickeningParametersControlWidget().
Member Data Documentation
bool ThickeningParametersControlWidget::autoInit [private]
Definition at line 43 of file thickeningParametersControlWidget.h.
Ui_ThickeningParametersControlWidget* ThickeningParametersControlWidget::mUi [private]
Definition at line 42 of file thickeningParametersControlWidget.h.
Referenced by createParameters(), setParameters(), ThickeningParametersControlWidget(), and ~ThickeningParametersControlWidget().
QString ThickeningParametersControlWidget::rootPath [private]
Definition at line 44 of file thickeningParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/thickeningParametersControlWidget.h
utils/filters/ui/thickeningParametersControlWidget.cpp