DeepView: corecvs::FCostFunction Class Reference
corecvs::FCostFunction Class Reference
#include <FCostFunction.h>
Public Types
enum CameraId {
FIRST_CAMERA_NUMBER = 0, FRONT_VIEW_CAMERA = FIRST_CAMERA_NUMBER, REAR_VIEW_CAMERA, LEFT_SIDE_VIEW_CAMERA,
RIGHT_SIDE_VIEW_CAMERA, CAMERA_NUMBER
}
enum CostFunctionType { FU = 0, FV, AUTO }
Public Member Functions
FCostFunction ()
virtual ~FCostFunction ()
Static Public Member Functions
static Matrix44 RotationMatrix (double i_yaw, double i_pitch, double i_roll)
Rotation matrix in details:
static Matrix44 NominalMatrix (CameraId cameraId)
Transformation form camera system to car system depending on camera.
static Matrix44 InvNominalMatrix (CameraId cameraId)
static Matrix44 getMMatrix (CameraId cameraId, const ShiftRotateTransformation &cameraExtrinsics)
static Matrix44 getDMatrix (CameraId cameraId, const CameraIntrinsics &cameraIntrinsics, const ShiftRotateTransformation &cameraExtrinsics)
static Matrix44 getInvDMatrix (CameraId cameraId, const CameraIntrinsics &cameraIntrinsics, const ShiftRotateTransformation &cameraExtrinsics)
static Matrix44 getBMatrix (CameraId cameraId, const CameraIntrinsics &cameraIntrinsics, const ShiftRotateTransformation &cameraExtrinsics, const ShiftRotateTransformation &carEvolution)
static Matrix44 GetMatrixForTransform (const ShiftRotateTransformation &transform)
Helper function that transforms Euler angels into Matrix presentation Sould be merged into ShiftRotateTransformation class.
static double function (const FloatFlowVector &flow, const Matrix44 &B)
static double functionPro (const FloatFlowVector &flow, const Matrix44 &B, double *distancePtr, CostFunctionType *typePtr)
static double function (const FloatFlowVector &flow, CameraId cameraId, const CameraIntrinsics &cameraIntrinsics, const ShiftRotateTransformation &cameraExtrinsics, const ShiftRotateTransformation &carEvolution)
static double functionPro (const FloatFlowVector &flow, CameraId cameraId, const CameraIntrinsics &cameraIntrinsics, const ShiftRotateTransformation &cameraExtrinsics, const ShiftRotateTransformation &carEvolution, double *distancePtr, CostFunctionType *typePtr)
Detailed Description
Definition at line 17 of file FCostFunction.h.
Member Enumeration Documentation
enum corecvs::FCostFunction::CameraId
Enumerator:
FIRST_CAMERA_NUMBER
FRONT_VIEW_CAMERA
REAR_VIEW_CAMERA
LEFT_SIDE_VIEW_CAMERA
RIGHT_SIDE_VIEW_CAMERA
CAMERA_NUMBER
Definition at line 21 of file FCostFunction.h.
              {
    FIRST_CAMERA_NUMBER = 0,
    FRONT_VIEW_CAMERA = FIRST_CAMERA_NUMBER,
    REAR_VIEW_CAMERA,
    LEFT_SIDE_VIEW_CAMERA,
    RIGHT_SIDE_VIEW_CAMERA,
    CAMERA_NUMBER
};
enum corecvs::FCostFunction::CostFunctionType
Enumerator:
FU
FV
AUTO
Definition at line 30 of file FCostFunction.h.
                      {
    FU = 0,
    FV,
    AUTO
};
Constructor & Destructor Documentation
corecvs::FCostFunction::FCostFunction ()
Definition at line 226 of file FCostFunction.cpp.
{
}
corecvs::FCostFunction::~FCostFunction () [virtual]
Definition at line 590 of file FCostFunction.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
double corecvs::FCostFunction::function (const FloatFlowVector & flow, const Matrix44 & B) [static]
Definition at line 412 of file FCostFunction.cpp.
References corecvs::Matrix44::a(), corecvs::FloatFlowVector::end, corecvs::FloatFlowVector::start, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
 {
   double Tu, Tv, Tw;
   double d0, d1;
   /* Prepare Flow */
   double u0 = flow.start.x();
   double v0 = flow.start.y();
   double u1 = flow.end.x();
   double v1 = flow.end.y();
   Tu = B.a(0,0) * u0 + B.a(0,1) * v0 + B.a(0,2);
   Tv = B.a(1,0) * u0 + B.a(1,1) * v0 + B.a(1,2);
   Tw = B.a(2,0) * u0 + B.a(2,1) * v0 + B.a(2,2);
#ifdef OLDSTYLE
     if (fabs(v1 - v0) > fabs(u1 - u0)) // Flow is more vertical then horizontal
     {
       double denum = (Tw * v1 - Tv);
       if (denum == 0.0)
           return 0.0;
       d0 = - (B.a(2,3) * v1 - B.a(1,3)) / denum;
       if (d0 == 0.0)
           d0 = 1.0;
       d1 = d0 * Tw + B.a(2,3);
       if (d1 == 0.0)
           d1 = 1.0;
       return  u1 - (1.0 / d1) * (Tu * d0 + B.a(0,3));
     } else
     {
       double denum = (Tw * u1 - Tu);
       if (denum == 0.0)
           return 0.0;
       d0 = -(B.a(2,3) * u1 - B.a(0,3)) / denum;
       if (d0 == 0.0)
          d0 = 1.0;
       d1 = d0 * Tw + B.a(2,3);
       if (d1 == 0.0)
          d1 = 1.0;
       return  v1 - (1.0 / d1) * (Tv * d0 + B.a(1,3));
     }
#else
    double ru1,  rv1;
    double rTu,  rTv;
    double rb13, rb03;
    if (fabs(v1 - v0) < fabs(u1 - u0)) // Flow is more vertical then horizontal
    {
        rv1 = v1; rTv = Tv; rb13 = B.a(1,3);
        ru1 = u1; rTu = Tu; rb03 = B.a(0,3);
    } else {
        rv1 = u1; rTv = Tu; rb13 = B.a(0,3);
        ru1 = v1; rTu = Tv; rb03 = B.a(1,3);
    }
    double denum = (Tw * ru1 - rTu);
    if (denum == 0.0)
        return 0.0;
    d0 = - (B.a(2,3) * ru1 - rb03) / denum;
    if (d0 == 0.0)
     d0 = 1.0;
    d1 = d0 * Tw + B.a(2,3);
    if (d1 == 0.0)
     d1 = 1.0;
    return  rv1 - (1.0 / d1) * (rTv * d0 + rb13);
#endif
 }
double corecvs::FCostFunction::function (const FloatFlowVector & flow, CameraId cameraId, const CameraIntrinsics & cameraIntrinsics, const ShiftRotateTransformation & cameraExtrinsics, const ShiftRotateTransformation & carEvolution) [static]
Definition at line 564 of file FCostFunction.cpp.
References getBMatrix().
 {
     Matrix44 B = getBMatrix(cameraId, cameraIntrinsics, cameraExtrinsics, carEvolution);
     return function(flow, B);
 }
double corecvs::FCostFunction::functionPro (const FloatFlowVector & flow, const Matrix44 & B, double * distancePtr, CostFunctionType * typePtr) [static]
Definition at line 499 of file FCostFunction.cpp.
References corecvs::Matrix44::a(), AUTO, corecvs::FloatFlowVector::end, FU, FV, corecvs::FloatFlowVector::start, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by functionPro().
  {
    double Tu, Tv, Tw;
    double d0, d1;
    /* Prepare Flow */
    double u0 = flow.start.x();
    double v0 = flow.start.y();
    double u1 = flow.end.x();
    double v1 = flow.end.y();
    Tu = B.a(0,0) * u0 + B.a(0,1) * v0 + B.a(0,2);
    Tv = B.a(1,0) * u0 + B.a(1,1) * v0 + B.a(1,2);
    Tw = B.a(2,0) * u0 + B.a(2,1) * v0 + B.a(2,2);
     double ru1,  rv1;
     double rTu,  rTv;
     double rb13, rb03;
     CostFunctionType type;
     if (typePtr == NULL || *typePtr == AUTO)
         type = (fabs(v1 - v0) > fabs(u1 - u0)) ? FV : FU;
     else
         type = *typePtr;
     if (type == FU) // Flow is more vertical then horizontal
     {
         rv1 = v1; rTv = Tv; rb13 = B.a(1,3);
         ru1 = u1; rTu = Tu; rb03 = B.a(0,3);
     } else {
         rv1 = u1; rTv = Tu; rb13 = B.a(0,3);
         ru1 = v1; rTu = Tv; rb03 = B.a(1,3);
     }
     double denum = (Tw * ru1 - rTu);
     if (denum == 0.0)
         return 0.0;
     d0 = -(B.a(2,3) * ru1 - rb03) / denum;
     if (d0 == 0.0)
      d0 = 1.0;
     d1 = d0 * Tw + B.a(2,3);
     if (d1 == 0.0)
      d1 = 1.0;
     double f = rv1 - (1.0 / d1) * (rTv * d0 + rb13);
     if (typePtr)
         *typePtr = type;
     if (distancePtr)
         *distancePtr = d1;
     return  f;
  }
double corecvs::FCostFunction::functionPro (const FloatFlowVector & flow, CameraId cameraId, const CameraIntrinsics & cameraIntrinsics, const ShiftRotateTransformation & cameraExtrinsics, const ShiftRotateTransformation & carEvolution, double * distancePtr, CostFunctionType * typePtr) [static]
Definition at line 576 of file FCostFunction.cpp.
References functionPro(), and getBMatrix().
{
     Matrix44 B = getBMatrix(cameraId, cameraIntrinsics, cameraExtrinsics, carEvolution);
     return functionPro(flow, B, distancePtr, typePtr);
}
Matrix44 corecvs::FCostFunction::getBMatrix (CameraId cameraId, const CameraIntrinsics & cameraIntrinsics, const ShiftRotateTransformation & cameraExtrinsics, const ShiftRotateTransformation & carEvolution) [static]
Definition at line 382 of file FCostFunction.cpp.
References corecvs::EulerAngles::alpha, corecvs::EulerAngles::beta, corecvs::EulerAngles::gamma, corecvs::CameraIntrinsics::getInvKMatrix(), corecvs::CameraIntrinsics::getKMatrix(), GetMatrixForTransform(), NominalMatrix(), corecvs::ShiftRotateTransformation::rotation, RotationMatrix(), corecvs::ShiftRotateTransformation::translation, and corecvs::Matrix44::transposed().
Referenced by function(), and functionPro().
 {
     Matrix44 REulerCamera = RotationMatrix(
           cameraExtrinsics.rotation.gamma,
           cameraExtrinsics.rotation.beta,
           cameraExtrinsics.rotation.alpha);
     Matrix44 NominalCamera = NominalMatrix(cameraId);
     Matrix44 invTCamera = Matrix44( Matrix33(1.0), -cameraExtrinsics.translation);
     Matrix44 TCamera    = Matrix44( Matrix33(1.0),  cameraExtrinsics.translation);
    /*Car Evolution*/
    Matrix44  A = GetMatrixForTransform(carEvolution);
    Matrix44  K    = cameraIntrinsics.getKMatrix();
    Matrix44  invK = cameraIntrinsics.getInvKMatrix();
    return K * REulerCamera.transposed() * NominalCamera.transposed() * invTCamera  *
           A *
           TCamera * NominalCamera * REulerCamera * invK;
 }
Matrix44 corecvs::FCostFunction::getDMatrix (CameraId cameraId, const CameraIntrinsics & cameraIntrinsics, const ShiftRotateTransformation & cameraExtrinsics) [static]
Definition at line 371 of file FCostFunction.cpp.
References corecvs::CameraIntrinsics::getKMatrix(), and getMMatrix().
Referenced by corecvs::FlowSimuator::simulateFlow().
 {
     Matrix44 M = FCostFunction::getMMatrix(cameraId, cameraExtrinsics);
     Matrix44 K = cameraIntrinsics.getKMatrix();
     return K * M;
 }
Matrix44 corecvs::FCostFunction::getInvDMatrix (CameraId cameraId, const CameraIntrinsics & cameraIntrinsics, const ShiftRotateTransformation & cameraExtrinsics) [static]
Definition at line 352 of file FCostFunction.cpp.
References corecvs::EulerAngles::alpha, corecvs::EulerAngles::beta, corecvs::EulerAngles::gamma, corecvs::CameraIntrinsics::getInvKMatrix(), NominalMatrix(), corecvs::ShiftRotateTransformation::rotation, RotationMatrix(), and corecvs::ShiftRotateTransformation::translation.
 {
   Matrix44 RCamera = RotationMatrix(
         cameraExtrinsics.rotation.gamma,
         cameraExtrinsics.rotation.beta,
         cameraExtrinsics.rotation.alpha);
   Matrix44 NominalCamera = NominalMatrix(cameraId);
   Matrix44 TCamera = Matrix44( Matrix33(1.0), cameraExtrinsics.translation);
   Matrix44 InvK = cameraIntrinsics.getInvKMatrix();
   return TCamera * NominalCamera * RCamera * InvK;
 }
Matrix44 corecvs::FCostFunction::GetMatrixForTransform (const ShiftRotateTransformation & transform) [static]
Helper function that transforms Euler angels into Matrix presentation Sould be merged into ShiftRotateTransformation class.
Definition at line 321 of file FCostFunction.cpp.
References corecvs::EulerAngles::alpha, corecvs::EulerAngles::beta, corecvs::EulerAngles::gamma, corecvs::ShiftRotateTransformation::rotation, RotationMatrix(), and corecvs::ShiftRotateTransformation::translation.
Referenced by getBMatrix(), and corecvs::FlowSimuator::simulateFlow().
{
    Matrix44 REulerCar = RotationMatrix(
            transform.rotation.gamma,
            transform.rotation.beta,
            transform.rotation.alpha);
    Matrix44 TCar = Matrix44( Matrix33(1.0), transform.translation);
    return REulerCar * TCar;
}
Matrix44 corecvs::FCostFunction::getMMatrix (CameraId cameraId, const ShiftRotateTransformation & cameraExtrinsics) [static]
Definition at line 336 of file FCostFunction.cpp.
References corecvs::EulerAngles::alpha, corecvs::EulerAngles::beta, corecvs::EulerAngles::gamma, NominalMatrix(), corecvs::ShiftRotateTransformation::rotation, RotationMatrix(), corecvs::ShiftRotateTransformation::translation, and corecvs::Matrix44::transposed().
Referenced by getDMatrix().
 {
   Matrix44 invREulerCamera = RotationMatrix(
         cameraExtrinsics.rotation.gamma,
         cameraExtrinsics.rotation.beta,
         cameraExtrinsics.rotation.alpha).transposed();
   Matrix44 invNominalCamera = NominalMatrix(cameraId).transposed();
   Matrix44 invT = Matrix44( Matrix33(1.0), -cameraExtrinsics.translation);
   return invREulerCamera * invNominalCamera * invT;
 }
static Matrix44 corecvs::FCostFunction::InvNominalMatrix (CameraId cameraId) [static]
Matrix44 corecvs::FCostFunction::NominalMatrix (CameraId cameraId) [static]
Transformation form camera system to car system depending on camera.
Definition at line 270 of file FCostFunction.cpp.
References FRONT_VIEW_CAMERA, LEFT_SIDE_VIEW_CAMERA, REAR_VIEW_CAMERA, and RIGHT_SIDE_VIEW_CAMERA.
Referenced by getBMatrix(), getInvDMatrix(), and getMMatrix().
 {
    switch (cameraId)
    {
    /*Front*/
      case FRONT_VIEW_CAMERA:
         return Matrix44(
              0.0, 0.0,-1.0, 0.0,
              1.0, 0.0, 0.0, 0.0,
              0.0,-1.0, 0.0, 0.0,
              0.0, 0.0, 0.0, 1.0
         );
         break;
    /*Rear*/
      case REAR_VIEW_CAMERA:
          return Matrix44(
             0.0, 0.0, 1.0, 0.0,
            -1.0, 0.0, 0.0, 0.0,
             0.0,-1.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 1.0
         );
         break;
     /*Left*/
      case LEFT_SIDE_VIEW_CAMERA:
         return Matrix44(
            -1.0, 0.0, 0.0, 0.0,
             0.0, 0.0,-1.0, 0.0,
             0.0,-1.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 1.0
         );
         break;
     /*Right*/
      case RIGHT_SIDE_VIEW_CAMERA:
         return Matrix44(
             1.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 1.0, 0.0,
             0.0,-1.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 1.0
         );
         break;
      default:
         break;
    }
    return Matrix44(1.0);
 }
Matrix44 corecvs::FCostFunction::RotationMatrix (double i_yaw, double i_pitch, double i_roll) [static]
Rotation matrix in details:
The axis goes as follows:
-car forward movement
-goes right from car
-orthogonal, goes into the ground
Example of the rotation matrix:
See more in the file describtion
Definition at line 252 of file FCostFunction.cpp.
References corecvs::Matrix33::RotationX(), corecvs::Matrix33::RotationY(), and corecvs::Matrix33::RotationZ().
Referenced by getBMatrix(), getInvDMatrix(), GetMatrixForTransform(), and getMMatrix().
 {
     /*TODO: Check and explain the order */
     /* Ra matrix initialization */
     Matrix33 Ra = Matrix33::RotationZ(i_yaw);
     Matrix33 Rb = Matrix33::RotationY(i_pitch);
     Matrix33 Rc = Matrix33::RotationX(i_roll);
     return Matrix44(Ra*Rb*Rc);
 }
The documentation for this class was generated from the following files:
core/automotive/FCostFunction.h
core/automotive/FCostFunction.cpp