DeepView: Draw3dCameraParameters Class Reference
Draw3dCameraParameters Class Reference
draw 3d Camera Parameters draw 3d Camera Parameters
#include <draw3dCameraParameters.h>
Public Types
enum FieldId {
FOVH_ID, FOVV_ID, NEARPLANE_ID, FARPLANE_ID,
STYLE_ID, COLOR_ID, SECONDARY_COLOR_ID, TEXTURE_CORRODINATES_ID,
TEXTURE_ALPHA_ID, TEXTURE_SCALE_ID, DECAL_MATRIX_TYPE_ID, DECAL_LEFT_CAM_ID,
DECAL_LEFT_ALPHA_ID, DECAL_RIGHT_CAM_ID, DECAL_RIGHT_ALPHA_ID, DRAW_3D_CAMERA_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
double fovH () const
double fovV () const
double nearPlane () const
double farPlane () const
Draw3dStyle::Draw3dStyle style () const
RgbColorParameters color () const
RgbColorParameters secondaryColor () const
Draw3dTextureGen::Draw3dTextureGen textureCorrodinates () const
int textureAlpha () const
double textureScale () const
int decalMatrixType () const
bool decalLeftCam () const
int decalLeftAlpha () const
bool decalRightCam () const
int decalRightAlpha () const
void setFovH (double fovH)
void setFovV (double fovV)
void setNearPlane (double nearPlane)
void setFarPlane (double farPlane)
void setStyle (Draw3dStyle::Draw3dStyle style)
void setColor (RgbColorParameters const &color)
void setSecondaryColor (RgbColorParameters const &secondaryColor)
void setTextureCorrodinates (Draw3dTextureGen::Draw3dTextureGen textureCorrodinates)
void setTextureAlpha (int textureAlpha)
void setTextureScale (double textureScale)
void setDecalMatrixType (int decalMatrixType)
void setDecalLeftCam (bool decalLeftCam)
void setDecalLeftAlpha (int decalLeftAlpha)
void setDecalRightCam (bool decalRightCam)
void setDecalRightAlpha (int decalRightAlpha)
Draw3dParameters baseParameters () const
Base Parameters Base Parameters.
void setBaseParameters (Draw3dParameters const &baseParameters)
template<class VisitorType >
void accept (VisitorType &visitor)
Draw3dCameraParameters ()
Draw3dCameraParameters (double fovH, double fovV, double nearPlane, double farPlane, Draw3dStyle::Draw3dStyle style, RgbColorParameters color, RgbColorParameters secondaryColor, Draw3dTextureGen::Draw3dTextureGen textureCorrodinates, int textureAlpha, double textureScale, int decalMatrixType, bool decalLeftCam, int decalLeftAlpha, bool decalRightCam, int decalRightAlpha)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
double mFovH
Section with variables.
double mFovV
fovV fovV
double mNearPlane
nearPlane nearPlane
double mFarPlane
farPlane farPlane
int mStyle
style style
RgbColorParameters mColor
Color Color.
RgbColorParameters mSecondaryColor
Secondary Color Secondary Color.
int mTextureCorrodinates
Texture Corrodinates Texture Corrodinates.
int mTextureAlpha
Texture Alpha Texture Alpha.
double mTextureScale
Texture Scale Texture Scale.
int mDecalMatrixType
Decal Matrix Type Decal Matrix Type.
bool mDecalLeftCam
Decal Left Cam Decal Left Cam.
int mDecalLeftAlpha
Decal Left Alpha Decal Left Alpha.
bool mDecalRightCam
Decal Right Cam Decal Right Cam.
int mDecalRightAlpha
Decal Right Alpha Decal Right Alpha.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, Draw3dCameraParameters &toSave)
Detailed Description
draw 3d Camera Parameters draw 3d Camera Parameters
Definition at line 42 of file draw3dCameraParameters.h.
Member Enumeration Documentation
enum Draw3dCameraParameters::FieldId
Enumerator:
FOVH_ID
FOVV_ID
NEARPLANE_ID
FARPLANE_ID
STYLE_ID
COLOR_ID
SECONDARY_COLOR_ID
TEXTURE_CORRODINATES_ID
TEXTURE_ALPHA_ID
TEXTURE_SCALE_ID
DECAL_MATRIX_TYPE_ID
DECAL_LEFT_CAM_ID
DECAL_LEFT_ALPHA_ID
DECAL_RIGHT_CAM_ID
DECAL_RIGHT_ALPHA_ID
DRAW_3D_CAMERA_PARAMETERS_FIELD_ID_NUM
Definition at line 45 of file draw3dCameraParameters.h.
                 {
        FOVH_ID,
        FOVV_ID,
        NEARPLANE_ID,
        FARPLANE_ID,
        STYLE_ID,
        COLOR_ID,
        SECONDARY_COLOR_ID,
        TEXTURE_CORRODINATES_ID,
        TEXTURE_ALPHA_ID,
        TEXTURE_SCALE_ID,
        DECAL_MATRIX_TYPE_ID,
        DECAL_LEFT_CAM_ID,
        DECAL_LEFT_ALPHA_ID,
        DECAL_RIGHT_CAM_ID,
        DECAL_RIGHT_ALPHA_ID,
        DRAW_3D_CAMERA_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
Draw3dCameraParameters::Draw3dCameraParameters () [inline]
Definition at line 373 of file draw3dCameraParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
Draw3dCameraParameters::Draw3dCameraParameters (double fovH, double fovV, double nearPlane, double farPlane, Draw3dStyle::Draw3dStyle style, RgbColorParameters color, RgbColorParameters secondaryColor, Draw3dTextureGen::Draw3dTextureGen textureCorrodinates, int textureAlpha, double textureScale, int decalMatrixType, bool decalLeftCam, int decalLeftAlpha, bool decalRightCam, int decalRightAlpha) [inline]
Definition at line 379 of file draw3dCameraParameters.h.
    {
        mFovH = fovH;
        mFovV = fovV;
        mNearPlane = nearPlane;
        mFarPlane = farPlane;
        mStyle = style;
        mColor = color;
        mSecondaryColor = secondaryColor;
        mTextureCorrodinates = textureCorrodinates;
        mTextureAlpha = textureAlpha;
        mTextureScale = textureScale;
        mDecalMatrixType = decalMatrixType;
        mDecalLeftCam = decalLeftCam;
        mDecalLeftAlpha = decalLeftAlpha;
        mDecalRightCam = decalRightCam;
        mDecalRightAlpha = decalRightAlpha;
    }
Member Function Documentation
template<class VisitorType > void Draw3dCameraParameters::accept (VisitorType & visitor) [inline]
Definition at line 354 of file draw3dCameraParameters.h.
    {
        visitor.visit(mFovH,                      static_cast<const DoubleField *>  (fields()[FOVH_ID]));
        visitor.visit(mFovV,                      static_cast<const DoubleField *>  (fields()[FOVV_ID]));
        visitor.visit(mNearPlane,                 static_cast<const DoubleField *>  (fields()[NEARPLANE_ID]));
        visitor.visit(mFarPlane,                  static_cast<const DoubleField *>  (fields()[FARPLANE_ID]));
        visitor.visit((int &)mStyle,              static_cast<const EnumField *>    (fields()[STYLE_ID]));
        visitor.visit(mColor,                     static_cast<const CompositeField *>(fields()[COLOR_ID]));
        visitor.visit(mSecondaryColor,            static_cast<const CompositeField *>(fields()[SECONDARY_COLOR_ID]));
        visitor.visit((int &)mTextureCorrodinates, static_cast<const EnumField *>    (fields()[TEXTURE_CORRODINATES_ID]));
        visitor.visit(mTextureAlpha,              static_cast<const IntField *>     (fields()[TEXTURE_ALPHA_ID]));
        visitor.visit(mTextureScale,              static_cast<const DoubleField *>  (fields()[TEXTURE_SCALE_ID]));
        visitor.visit(mDecalMatrixType,           static_cast<const IntField *>     (fields()[DECAL_MATRIX_TYPE_ID]));
        visitor.visit(mDecalLeftCam,              static_cast<const BoolField *>    (fields()[DECAL_LEFT_CAM_ID]));
        visitor.visit(mDecalLeftAlpha,            static_cast<const IntField *>     (fields()[DECAL_LEFT_ALPHA_ID]));
        visitor.visit(mDecalRightCam,             static_cast<const BoolField *>    (fields()[DECAL_RIGHT_CAM_ID]));
        visitor.visit(mDecalRightAlpha,           static_cast<const IntField *>     (fields()[DECAL_RIGHT_ALPHA_ID]));
    }
Draw3dParameters Draw3dCameraParameters::baseParameters () const [inline]
Base Parameters Base Parameters.
Definition at line 320 of file draw3dCameraParameters.h.
    {
        return Draw3dParameters(
             style()
           , color()
           , secondaryColor()
           , textureCorrodinates()
           , textureAlpha()
           , textureScale()
           , decalMatrixType()
           , decalLeftCam()
           , decalLeftAlpha()
           , decalRightCam()
           , decalRightAlpha()
        );
    }
RgbColorParameters Draw3dCameraParameters::color () const [inline]
Definition at line 189 of file draw3dCameraParameters.h.
Referenced by CameraScene::drawMyself(), and Draw3dCameraParametersControlWidget::setParameters().
    {
        return mColor;
    }
static const char* corecvs::BaseReflection< Draw3dCameraParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
int Draw3dCameraParameters::decalLeftAlpha () const [inline]
Definition at line 224 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mDecalLeftAlpha;
    }
bool Draw3dCameraParameters::decalLeftCam () const [inline]
Definition at line 219 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mDecalLeftCam;
    }
int Draw3dCameraParameters::decalMatrixType () const [inline]
Definition at line 214 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mDecalMatrixType;
    }
int Draw3dCameraParameters::decalRightAlpha () const [inline]
Definition at line 234 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mDecalRightAlpha;
    }
bool Draw3dCameraParameters::decalRightCam () const [inline]
Definition at line 229 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mDecalRightCam;
    }
double Draw3dCameraParameters::farPlane () const [inline]
Definition at line 179 of file draw3dCameraParameters.h.
Referenced by CameraScene::drawMyself(), and Draw3dCameraParametersControlWidget::setParameters().
    {
        return mFarPlane;
    }
static int corecvs::BaseReflection< Draw3dCameraParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< Draw3dCameraParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
double Draw3dCameraParameters::fovH () const [inline]
Definition at line 164 of file draw3dCameraParameters.h.
Referenced by CameraScene::drawMyself(), and Draw3dCameraParametersControlWidget::setParameters().
    {
        return mFovH;
    }
double Draw3dCameraParameters::fovV () const [inline]
Definition at line 169 of file draw3dCameraParameters.h.
Referenced by CameraScene::drawMyself(), and Draw3dCameraParametersControlWidget::setParameters().
    {
        return mFovV;
    }
const void* Draw3dCameraParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 160 of file draw3dCameraParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< Draw3dCameraParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< Draw3dCameraParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< Draw3dCameraParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
double Draw3dCameraParameters::nearPlane () const [inline]
Definition at line 174 of file draw3dCameraParameters.h.
Referenced by CameraScene::drawMyself(), and Draw3dCameraParametersControlWidget::setParameters().
    {
        return mNearPlane;
    }
void Draw3dCameraParameters::print () [inline]
Definition at line 421 of file draw3dCameraParameters.h.
    {
        cout << *this;
    }
RgbColorParameters Draw3dCameraParameters::secondaryColor () const [inline]
Definition at line 194 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mSecondaryColor;
    }
void Draw3dCameraParameters::setBaseParameters (Draw3dParameters const & baseParameters) [inline]
Definition at line 337 of file draw3dCameraParameters.h.
References Draw3dParameters::color(), Draw3dParameters::decalLeftAlpha(), Draw3dParameters::decalLeftCam(), Draw3dParameters::decalMatrixType(), Draw3dParameters::decalRightAlpha(), Draw3dParameters::decalRightCam(), Draw3dParameters::secondaryColor(), Draw3dParameters::style(), Draw3dParameters::textureAlpha(), Draw3dParameters::textureCorrodinates(), and Draw3dParameters::textureScale().
    {
        mStyle         = baseParameters.style();
        mColor         = baseParameters.color();
        mSecondaryColor = baseParameters.secondaryColor();
        mTextureCorrodinates = baseParameters.textureCorrodinates();
        mTextureAlpha  = baseParameters.textureAlpha();
        mTextureScale  = baseParameters.textureScale();
        mDecalMatrixType = baseParameters.decalMatrixType();
        mDecalLeftCam  = baseParameters.decalLeftCam();
        mDecalLeftAlpha = baseParameters.decalLeftAlpha();
        mDecalRightCam = baseParameters.decalRightCam();
        mDecalRightAlpha = baseParameters.decalRightAlpha();
    }
void Draw3dCameraParameters::setColor (RgbColorParameters const & color) [inline]
Definition at line 265 of file draw3dCameraParameters.h.
Referenced by StereoCameraScene::drawMyself().
    {
        mColor = color;
    }
void Draw3dCameraParameters::setDecalLeftAlpha (int decalLeftAlpha) [inline]
Definition at line 300 of file draw3dCameraParameters.h.
    {
        mDecalLeftAlpha = decalLeftAlpha;
    }
void Draw3dCameraParameters::setDecalLeftCam (bool decalLeftCam) [inline]
Definition at line 295 of file draw3dCameraParameters.h.
    {
        mDecalLeftCam = decalLeftCam;
    }
void Draw3dCameraParameters::setDecalMatrixType (int decalMatrixType) [inline]
Definition at line 290 of file draw3dCameraParameters.h.
    {
        mDecalMatrixType = decalMatrixType;
    }
void Draw3dCameraParameters::setDecalRightAlpha (int decalRightAlpha) [inline]
Definition at line 310 of file draw3dCameraParameters.h.
    {
        mDecalRightAlpha = decalRightAlpha;
    }
void Draw3dCameraParameters::setDecalRightCam (bool decalRightCam) [inline]
Definition at line 305 of file draw3dCameraParameters.h.
    {
        mDecalRightCam = decalRightCam;
    }
void Draw3dCameraParameters::setFarPlane (double farPlane) [inline]
Definition at line 255 of file draw3dCameraParameters.h.
    {
        mFarPlane = farPlane;
    }
void Draw3dCameraParameters::setFovH (double fovH) [inline]
Definition at line 240 of file draw3dCameraParameters.h.
Referenced by StereoCameraScene::drawMyself().
    {
        mFovH = fovH;
    }
void Draw3dCameraParameters::setFovV (double fovV) [inline]
Definition at line 245 of file draw3dCameraParameters.h.
Referenced by StereoCameraScene::drawMyself().
    {
        mFovV = fovV;
    }
void Draw3dCameraParameters::setNearPlane (double nearPlane) [inline]
Definition at line 250 of file draw3dCameraParameters.h.
    {
        mNearPlane = nearPlane;
    }
void Draw3dCameraParameters::setSecondaryColor (RgbColorParameters const & secondaryColor) [inline]
Definition at line 270 of file draw3dCameraParameters.h.
    {
        mSecondaryColor = secondaryColor;
    }
void Draw3dCameraParameters::setStyle (Draw3dStyle::Draw3dStyle style) [inline]
Definition at line 260 of file draw3dCameraParameters.h.
    {
        mStyle = style;
    }
void Draw3dCameraParameters::setTextureAlpha (int textureAlpha) [inline]
Definition at line 280 of file draw3dCameraParameters.h.
    {
        mTextureAlpha = textureAlpha;
    }
void Draw3dCameraParameters::setTextureCorrodinates (Draw3dTextureGen::Draw3dTextureGen textureCorrodinates) [inline]
Definition at line 275 of file draw3dCameraParameters.h.
    {
        mTextureCorrodinates = textureCorrodinates;
    }
void Draw3dCameraParameters::setTextureScale (double textureScale) [inline]
Definition at line 285 of file draw3dCameraParameters.h.
    {
        mTextureScale = textureScale;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int Draw3dCameraParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file draw3dCameraParameters.cpp.
References COLOR_ID, DECAL_LEFT_ALPHA_ID, DECAL_LEFT_CAM_ID, DECAL_MATRIX_TYPE_ID, DECAL_RIGHT_ALPHA_ID, DECAL_RIGHT_CAM_ID, FARPLANE_ID, corecvs::BaseReflection< Draw3dCameraParameters >::fields(), FOVH_ID, FOVV_ID, mColor, mDecalLeftAlpha, mDecalLeftCam, mDecalMatrixType, mDecalRightAlpha, mDecalRightCam, mFarPlane, mFovH, mFovV, mNearPlane, mSecondaryColor, mStyle, mTextureAlpha, mTextureCorrodinates, mTextureScale, corecvs::BaseReflection< Draw3dCameraParameters >::naming(), NEARPLANE_ID, SECONDARY_COLOR_ID, STYLE_ID, TEXTURE_ALPHA_ID, TEXTURE_CORRODINATES_ID, and TEXTURE_SCALE_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "draw 3d Camera Parameters",
        "draw 3d Camera Parameters",
        ""
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dCameraParameters::FOVH_ID,
          offsetof(Draw3dCameraParameters, mFovH),
          90,
          "fovH",
          "fovH",
          "fovH"
        )
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dCameraParameters::FOVV_ID,
          offsetof(Draw3dCameraParameters, mFovV),
          60,
          "fovV",
          "fovV",
          "fovV"
        )
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dCameraParameters::NEARPLANE_ID,
          offsetof(Draw3dCameraParameters, mNearPlane),
          10,
          "nearPlane",
          "nearPlane",
          "nearPlane"
        )
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dCameraParameters::FARPLANE_ID,
          offsetof(Draw3dCameraParameters, mFarPlane),
          100,
          "farPlane",
          "farPlane",
          "farPlane"
        )
    );
    fields().push_back(
        new EnumField
        (
          Draw3dCameraParameters::STYLE_ID,
          offsetof(Draw3dCameraParameters, mStyle),
          0,
          "style",
          "style",
          "style",
           NULL
        )
    );
    fields().push_back(
        new CompositeField
        (
          Draw3dCameraParameters::COLOR_ID,
          offsetof(Draw3dCameraParameters, mColor),
          "Color",
          "RgbColorParameters",
          "Color",
          "Color",
           NULL
        )
    );
    fields().push_back(
        new CompositeField
        (
          Draw3dCameraParameters::SECONDARY_COLOR_ID,
          offsetof(Draw3dCameraParameters, mSecondaryColor),
          "Secondary Color",
          "RgbColorParameters",
          "Secondary Color",
          "Secondary Color",
           NULL
        )
    );
    fields().push_back(
        new EnumField
        (
          Draw3dCameraParameters::TEXTURE_CORRODINATES_ID,
          offsetof(Draw3dCameraParameters, mTextureCorrodinates),
          0,
          "Texture Corrodinates",
          "Texture Corrodinates",
          "Texture Corrodinates",
           NULL
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dCameraParameters::TEXTURE_ALPHA_ID,
          offsetof(Draw3dCameraParameters, mTextureAlpha),
          255,
          "Texture Alpha",
          "Texture Alpha",
          "Texture Alpha"
        )
    );
    fields().push_back(
        new DoubleField
        (
          Draw3dCameraParameters::TEXTURE_SCALE_ID,
          offsetof(Draw3dCameraParameters, mTextureScale),
          1,
          "Texture Scale",
          "Texture Scale",
          "Texture Scale"
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dCameraParameters::DECAL_MATRIX_TYPE_ID,
          offsetof(Draw3dCameraParameters, mDecalMatrixType),
          11,
          "Decal Matrix Type",
          "Decal Matrix Type",
          "Decal Matrix Type"
        )
    );
    fields().push_back(
        new BoolField
        (
          Draw3dCameraParameters::DECAL_LEFT_CAM_ID,
          offsetof(Draw3dCameraParameters, mDecalLeftCam),
          false,
          "Decal Left Cam",
          "Decal Left Cam",
          "Decal Left Cam"
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dCameraParameters::DECAL_LEFT_ALPHA_ID,
          offsetof(Draw3dCameraParameters, mDecalLeftAlpha),
          255,
          "Decal Left Alpha",
          "Decal Left Alpha",
          "Decal Left Alpha"
        )
    );
    fields().push_back(
        new BoolField
        (
          Draw3dCameraParameters::DECAL_RIGHT_CAM_ID,
          offsetof(Draw3dCameraParameters, mDecalRightCam),
          false,
          "Decal Right Cam",
          "Decal Right Cam",
          "Decal Right Cam"
        )
    );
    fields().push_back(
        new IntField
        (
          Draw3dCameraParameters::DECAL_RIGHT_ALPHA_ID,
          offsetof(Draw3dCameraParameters, mDecalRightAlpha),
          255,
          "Decal Right Alpha",
          "Decal Right Alpha",
          "Decal Right Alpha"
        )
    );
   return 0;
}
Draw3dStyle::Draw3dStyle Draw3dCameraParameters::style () const [inline]
Definition at line 184 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return static_cast<Draw3dStyle::Draw3dStyle>(mStyle);
    }
int Draw3dCameraParameters::textureAlpha () const [inline]
Definition at line 204 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mTextureAlpha;
    }
Draw3dTextureGen::Draw3dTextureGen Draw3dCameraParameters::textureCorrodinates () const [inline]
Definition at line 199 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return static_cast<Draw3dTextureGen::Draw3dTextureGen>(mTextureCorrodinates);
    }
double Draw3dCameraParameters::textureScale () const [inline]
Definition at line 209 of file draw3dCameraParameters.h.
Referenced by Draw3dCameraParametersControlWidget::setParameters().
    {
        return mTextureScale;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, Draw3dCameraParameters & toSave) [friend]
Definition at line 414 of file draw3dCameraParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< Draw3dCameraParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
RgbColorParameters Draw3dCameraParameters::mColor
Color Color.
Definition at line 100 of file draw3dCameraParameters.h.
Referenced by staticInit().
int Draw3dCameraParameters::mDecalLeftAlpha
Decal Left Alpha Decal Left Alpha.
Definition at line 142 of file draw3dCameraParameters.h.
Referenced by staticInit().
bool Draw3dCameraParameters::mDecalLeftCam
Decal Left Cam Decal Left Cam.
Definition at line 136 of file draw3dCameraParameters.h.
Referenced by staticInit().
int Draw3dCameraParameters::mDecalMatrixType
Decal Matrix Type Decal Matrix Type.
Definition at line 130 of file draw3dCameraParameters.h.
Referenced by staticInit().
int Draw3dCameraParameters::mDecalRightAlpha
Decal Right Alpha Decal Right Alpha.
Definition at line 154 of file draw3dCameraParameters.h.
Referenced by staticInit().
bool Draw3dCameraParameters::mDecalRightCam
Decal Right Cam Decal Right Cam.
Definition at line 148 of file draw3dCameraParameters.h.
Referenced by staticInit().
double Draw3dCameraParameters::mFarPlane
farPlane farPlane
Definition at line 88 of file draw3dCameraParameters.h.
Referenced by staticInit().
double Draw3dCameraParameters::mFovH
Section with variables.
fovH fovH
Definition at line 70 of file draw3dCameraParameters.h.
Referenced by staticInit().
double Draw3dCameraParameters::mFovV
fovV fovV
Definition at line 76 of file draw3dCameraParameters.h.
Referenced by staticInit().
double Draw3dCameraParameters::mNearPlane
nearPlane nearPlane
Definition at line 82 of file draw3dCameraParameters.h.
Referenced by staticInit().
RgbColorParameters Draw3dCameraParameters::mSecondaryColor
Secondary Color Secondary Color.
Definition at line 106 of file draw3dCameraParameters.h.
Referenced by staticInit().
int Draw3dCameraParameters::mStyle
style style
Definition at line 94 of file draw3dCameraParameters.h.
Referenced by staticInit().
int Draw3dCameraParameters::mTextureAlpha
Texture Alpha Texture Alpha.
Definition at line 118 of file draw3dCameraParameters.h.
Referenced by staticInit().
int Draw3dCameraParameters::mTextureCorrodinates
Texture Corrodinates Texture Corrodinates.
Definition at line 112 of file draw3dCameraParameters.h.
Referenced by staticInit().
double Draw3dCameraParameters::mTextureScale
Texture Scale Texture Scale.
Definition at line 124 of file draw3dCameraParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< Draw3dCameraParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
utils/3d/generated/draw3dCameraParameters.h
utils/3d/generated/draw3dCameraParameters.cpp