DeepView: corecvs::InputPin Class Reference
corecvs::InputPin Class Reference
#include <pins.h>
Public Types
enum PinType { INPUT_PIN, OUTPUT_PIN }
Public Member Functions
InputPin (FilterBlock *_parent, const char *name="none")
virtual ~InputPin ()
void breakConnection ()
virtual bool setPin (OutputPin *, bool=false)
virtual XMLNode * serialize (XMLNode *doc, bool outerPin)
virtual void deserialize (XMLNode *)
int getInstanceId () const
virtual void setInstanceId (int)
virtual void clear ()
virtual const char * getTypeName () const
virtual bool isEmpty ()
virtual bool setPin (Pin *, bool=false)
virtual bool getPin (G12Buffer *&, bool=false)
virtual bool getPin (char *&, bool=false)
virtual void initPin (G12Buffer *)
Public Attributes
OutputPin * takeFrom
char * instanceName
PinType type
FilterBlock * parent
int instanceId
Detailed Description
Definition at line 184 of file pins.h.
Member Enumeration Documentation
enum corecvs::Pin::PinType [inherited]
Enumerator:
INPUT_PIN
OUTPUT_PIN
Definition at line 23 of file pins.h.
                {
        INPUT_PIN,
        OUTPUT_PIN
   };
Constructor & Destructor Documentation
corecvs::InputPin::InputPin (FilterBlock * _parent, const char * name = "none") [inline]
Definition at line 187 of file pins.h.
                                                              :
        Pin(_parent, INPUT_PIN, name),
        takeFrom(NULL)
   {}
virtual corecvs::InputPin::~InputPin () [virtual]
Member Function Documentation
void corecvs::InputPin::breakConnection () [inline]
Reimplemented from corecvs::Pin.
Definition at line 194 of file pins.h.
{ takeFrom = NULL; }
virtual void corecvs::Pin::clear () [inline, virtual, inherited]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 41 of file pins.h.
Referenced by corecvs::Pin::~Pin().
{}
virtual void corecvs::InputPin::deserialize (XMLNode *) [virtual]
Reimplemented from corecvs::Pin.
int corecvs::Pin::getInstanceId () const [inline, inherited]
Definition at line 38 of file pins.h.
Referenced by corecvs::FilterBlock::IdPredicate::operator()().
{ return instanceId; }
virtual bool corecvs::Pin::getPin (G12Buffer *& , bool = false) [inline, virtual, inherited]
Reimplemented in corecvs::OutputPin, and corecvs::G12Pin.
Definition at line 54 of file pins.h.
Referenced by corecvs::G12Pin::setPin(), corecvs::TxtPin::setPin(), and corecvs::ExtraTxtPin< TypeOfPin >::setPin().
   {   std::cerr << "error G12\n";
       return false;
   }
virtual bool corecvs::Pin::getPin (char *& , bool = false) [inline, virtual, inherited]
Reimplemented in corecvs::OutputPin, and corecvs::TxtPin.
Definition at line 58 of file pins.h.
   {   std::cerr << "error Txt\n";
       return false;
   }
virtual const char* corecvs::Pin::getTypeName () const [inline, virtual, inherited]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 47 of file pins.h.
Referenced by corecvs::Pin::serialize().
{ return "none"; }
virtual void corecvs::Pin::initPin (G12Buffer *) [inline, virtual, inherited]
Reimplemented in corecvs::G12Pin.
Definition at line 64 of file pins.h.
{ std::cerr << "error G12 initPin"; }
virtual bool corecvs::Pin::isEmpty () [inline, virtual, inherited]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 49 of file pins.h.
{ return false; }
virtual XMLNode* corecvs::InputPin::serialize (XMLNode * doc, bool outerPin) [virtual]
Reimplemented from corecvs::Pin.
virtual void corecvs::Pin::setInstanceId (int) [inline, virtual, inherited]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 39 of file pins.h.
Referenced by corecvs::Pin::deserialize().
{}
virtual bool corecvs::Pin::setPin (Pin * , bool = false) [inline, virtual, inherited]
Reimplemented in corecvs::TxtPin, and corecvs::G12Pin.
Definition at line 50 of file pins.h.
Referenced by DiagramScene::mouseReleaseEvent().
   {   std::cerr << "error Abstract\n";
       return false;
   }
virtual bool corecvs::InputPin::setPin (OutputPin * , bool = false) [inline, virtual]
Definition at line 196 of file pins.h.
   {   std::cerr << "error Abstract\n";
       return false;
   }
Member Data Documentation
int corecvs::Pin::instanceId [inherited]
Definition at line 72 of file pins.h.
Referenced by corecvs::Pin::serialize().
char* corecvs::Pin::instanceName [inherited]
Definition at line 69 of file pins.h.
Referenced by corecvs::Pin::deserialize(), FilterPinPresentation::FilterPinPresentation(), FilterGraphPresentation::nameChanged(), corecvs::FilterBlock::NamePredicate::operator()(), corecvs::Pin::serialize(), and corecvs::Pin::~Pin().
FilterBlock* corecvs::Pin::parent [inherited]
Definition at line 71 of file pins.h.
Referenced by corecvs::CompoundFilter::addPin(), corecvs::Pin::deserialize(), FilterPinPresentation::FilterPinPresentation(), and corecvs::Pin::serialize().
OutputPin* corecvs::InputPin::takeFrom
Reimplemented from corecvs::Pin.
Definition at line 204 of file pins.h.
PinType corecvs::Pin::type [inherited]
Definition at line 70 of file pins.h.
Referenced by corecvs::FilterGraph::connect(), FilterPinPresentation::drawPinName(), and corecvs::FilterBlock::isOuterPin().
The documentation for this class was generated from the following file:
core/filters/blocks/pins.h