DeepView: corecvs::StereoAligner Class Reference
corecvs::StereoAligner Class Reference
#include <stereoAligner.h>
Public Member Functions
StereoAligner ()
Static Public Member Functions
static void getAlignmentTransformation (const Matrix33 &F, Matrix33 *leftTransform, Matrix33 *rightTransform, Vector3dd z=Vector3dd(0.0, 1.0, 0.0))
This function implements the simple rectification.
static void getLateralCorrection (Matrix33 *leftTransform, Matrix33 *rightTransform, CorrespondanceList *list, unsigned threshold=0)
static void getLateralCorrectionFixPoint (Matrix33 *leftTransform, Matrix33 *rightb, Vector2dd fixedPoint)
static Vector3dd getBestZ (const Matrix33 &F, const Vector2dd &rect, unsigned granularity=512, double *leftDistortions=NULL, double *rightDistortions=NULL)
static double getDistortion (Vector3dd projective, const Vector2dd &rect)
Detailed Description
Definition at line 38 of file stereoAligner.h.
Constructor & Destructor Documentation
corecvs::StereoAligner::StereoAligner () [inline]
Definition at line 42 of file stereoAligner.h.
{}
Member Function Documentation
void corecvs::StereoAligner::getAlignmentTransformation (const Matrix33 & F, Matrix33 * firstTransform, Matrix33 * secondTransform, Vector3dd z = Vector3dd(0.0,1.0,0.0)) [static]
This function implements the simple rectification.
It is not optimal in any sense. This rectification is universal for both essential and fundamental matrix. In essential case it could be done simpler.
We actually want to transform and to and to satisfy the following condition:
This will be done, by presenting
The main idea is selecting two connected directions in both cameras This function does the following decomposition
Let be the left nullspace of , and the second one. Left nullspace vector is the direction to the second optical center in the first coordinate system.
Quite obviously the common rectified plane should be parallel to this line. So we need one more constraint to define this plane and the ability to calculate this direction in both First and Second coordinate systems.
Let's choose arbitary vector z (most probably it would be close to Y direction) And have a look at following vectors
and are the normal vectors to the same plane but in first and second coordinate system respectively. And this plane will be paralle to in first coordinate system and to in the second. Let's prove this step by step.
1. is ortogonal both to and - obvious 2. Consider the point in space ortogonal to . It can be decomposed by and
The rotational part can be reduced to :
If one wants to apply the transformations to input images. F is a transform computed for first pair of images. The following formulas could be used:
This could be presented as:
Finally align transformations and there inverses are
Parameters:
[in] F input fundamental or essential matrix
[out] leftTransform output left transform
[out] rightTransform output right transform
[in] z free vector
Todo:
TODO In fact this vector should be guessed
Definition at line 212 of file stereoAligner.cpp.
References corecvs::Matrix33::a(), ASSERT_TRUE, corecvs::Matrix33::det(), corecvs::VectorOperationsBase< RealType, ElementType >::notTooFar(), corecvs::EssentialMatrix::nullspaces(), corecvs::Matrix33::print(), corecvs::VectorOperationsBase< RealType, ElementType >::print(), corecvs::VectorOperationsBase< RealType, ElementType >::println(), corecvs::Matrix33::Projective(), corecvs::Matrix33::Scale2(), corecvs::Matrix33::transposed(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    Vector3dd E1;
    Vector3dd E2;
    EssentialMatrix(F).nullspaces(&E1, &E2);
#ifdef TRACE
    printf("Fundamental Matrix:\n");
    F.print();
    printf("\n");
    printf("Epipoles:\n");
    E1.print();
    printf("\n");
    E2.print();
    printf("\n");
    printf("Z Direction:\n");
    z.println();
#endif
    /// \todo TODO In fact this vector should be guessed
    //vector3Dd z = {-0.75,0.75,0};
    //vector3Dd z = {0.75,-0.75,0};
    //Vector3dd z1 = Vector3dd(1.,0.,0.);
    Vector3dd w1 = z ^ E1;
    Vector3dd w2 = z * F;
#ifdef TRACE
    printf("Projective correctives:\n");
    w1.print();
    printf("\n");
    w2.print();
    printf("\n");
#endif
    Vector2dd w1_2d = (Vector2dd) w1;
    Vector2dd w2_2d = (Vector2dd) w2;
#ifdef TRACE
    printf("Normalized correctives:\n");
    w1_2d.println();
    w2_2d.println();
    printf("Checks:\n");
    printf("Dot product for 1st corrector: %lg (should be zero)\n",
            E1 & Vector3dd(w1_2d.x(), w1_2d.y(), 1.0));
    printf("Dot product for 2nd corrector: %lg\n",
            E2 & Vector3dd(w2_2d.x(), w2_2d.y(), 1.0));
#endif
    Matrix33 projectivePartFirst  = Matrix33::Projective(w1_2d);
    Matrix33 projectivePartSecond = Matrix33::Projective(w2_2d);
    double wc = 0;
    double a, b;
    a = w2_2d.y() * F.a(2,2) - F.a(1,2);
    b = F.a(0,2) - w2_2d.x() * F.a(2,2);
    Matrix33 rotationalPartFirst(
         a,  b,  0,
        -b,  a,  wc,
         0,  0,  1 );
    a = F.a(2,1) - w1_2d.y() * F.a(2,2);
    b = w1_2d.x() * F.a(2,2) - F.a(2,0);
    Matrix33 rotationalPartSecond(
         a,  b,  0,
        -b,  a,  F.a(2,2) + wc,
         0,  0,  1 );
    if (a < 0)
    {   rotationalPartFirst = -rotationalPartFirst;
        rotationalPartFirst.a(2,2) = 1.0;
        rotationalPartSecond = -rotationalPartSecond;
        rotationalPartSecond.a(2,2) = 1.0;
        printf("Rotative negation done\n");
    }
#ifdef TRACE
    printf("Rotator1:\n");
    rotationalPartFirst.print();
    printf("Rotator2:\n");
    rotationalPartSecond.print();
    printf("Projector1:\n");
    projectivePartSecond.print();
    printf("Projector2:\n");
    projectivePartFirst.print();
#endif
    Matrix33 first  =  rotationalPartFirst  * projectivePartFirst;
    Matrix33 second =  rotationalPartSecond * projectivePartSecond;
//#ifdef ASSERTS
    Matrix33 Ix(
             0,  0,  0,
             0,  0, -1,
             0,  1,  0 );
    Matrix33 Fprim = first.transposed() * Ix * second;
    printf("Recollect\n");
    Fprim.print();
    printf("\n");
    printf("Old Matrix was\n");
    F.print();
    printf("\n");
    ASSERT_TRUE(Fprim.notTooFar(F, 1e-5), "Matrix reconstruction failed");
//#endif // ASSERTS
    double det1 = rotationalPartFirst .det();
    double det2 = rotationalPartSecond.det();
    printf("rotationalPartLeft .det() %lg\n", det1);
    printf("rotationalPartRight.det() %lg\n", det2);
    double scaleFactor = det1 > det2 ? det1 : det2;
    scaleFactor = sqrt(scaleFactor);
    printf("Scale factor %lg\n", scaleFactor);
    Matrix33 scale =  Matrix33::Scale2(1.0 / scaleFactor, 1.0 / scaleFactor);
    *firstTransform  = scale * first;
    *secondTransform = scale * second;
#ifdef TRACE
    printf("Final L %lg:\n", detL);
    leftTransform->print();
    printf("Final R %lg:\n", detR);
    rightTransform->print();
#endif
}
Vector3dd corecvs::StereoAligner::getBestZ (const Matrix33 & F, const Vector2dd & rect, unsigned granularity = 512, double * leftDistortions = NULL, double * rightDistortions = NULL) [static]
Definition at line 353 of file stereoAligner.cpp.
References ASSERT_TRUE, getDistortion(), M_PI, corecvs::Vector3d< ElementType >::normalizeProjective(), and corecvs::EssentialMatrix::nullspaces().
{
    Vector3dd E1;
    Vector3dd E2;
    EssentialMatrix(F).nullspaces(&E2, &E1);
    double minsum = numeric_limits<double>::max();
    double minalpha  = 0;
    for (unsigned i = 0; i < granularity; i++)
    {
        double alpha = i / (double)granularity * (M_PI * 2.0);
        Vector3dd z = Vector3dd(cos(alpha), sin(alpha), 0.0);
        Vector3dd w1 = z ^ E1;
        Vector3dd w2 = F * z;
        w1 = w1.normalizeProjective();
        w2 = w2.normalizeProjective();
        double distLeft = getDistortion(w1, rect);
        double distRight = getDistortion(w2, rect);
        if (leftDistortions != NULL)
            leftDistortions[i] = distLeft;
        if (rightDistortions != NULL)
            rightDistortions[i] = distRight;
        ASSERT_TRUE(distLeft > 0 && distRight > 0, "Internal error");
        if (distLeft + distRight <  minsum)
        {
            minsum = distLeft + distRight;
            minalpha = alpha;
        }
    }
    return Vector3dd(cos(minalpha), sin(minalpha), 0.0);
}
double corecvs::StereoAligner::getDistortion (Vector3dd projective, const Vector2dd & rect) [static]
Definition at line 489 of file stereoAligner.cpp.
References corecvs::Matrix33::VectorByVector(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by getBestZ().
{
    double h = rect.y();
    double w = rect.x();
    Matrix33 PPt = w * h * (1 / 12.0) *
        Matrix33(
            w * w - 1,      0.0,  0.0,
                  0.0, h * h -1,  0.0,
                  0.0,      0.0,  0.0
        );
    Vector3dd center = Vector3dd( w * 0.5, h * 0.5, 1.0);
    Matrix33 ppc = Matrix33::VectorByVector(center, center);
    double distortion =
            ((projective * PPt) & projective) /
            ((projective * ppc) & projective);
    return distortion;
}
void corecvs::StereoAligner::getLateralCorrection (Matrix33 * leftTransform, Matrix33 * rightTransform, CorrespondanceList * list, unsigned threshold = 0) [static]
Definition at line 425 of file stereoAligner.cpp.
References ASSERT_TRUE, corecvs::Matrix33::ShiftProj(), and corecvs::Vector2d< ElementType >::x().
{
    ASSERT_TRUE(list->size() != 0, "Input list should not ne empty");
    double min = numeric_limits<double>::max();
    double max = numeric_limits<double>::min();
    vector<double> sortedLaterals;
    sortedLaterals.reserve(list->size());
//    double totalMisrectify = 0;
    for (unsigned i = 0; i < list->size(); i++)
    {
        Vector2dd left  = (*leftTransform) * list->at(i).start;
        Vector2dd right = (*rightTransform) * list->at(i).end;
//        totalMisrectify += fabs(left.y() - right.y());
        double diff = left.x() - right.x();
        if (diff < min) {
            diff = min;
        }
        if (diff > max) {
            diff = max;
        }
        sortedLaterals.push_back(diff);
    }
    sort(sortedLaterals.begin(), sortedLaterals.end());
    double shift;
    if (threshold > sortedLaterals.size())
        shift = max;
    else
        shift = sortedLaterals[sortedLaterals.size() - 1 - threshold];
    (*leftTransform)  = Matrix33::ShiftProj( shift / 2.0, 0.0) * (*leftTransform);
    (*rightTransform) = Matrix33::ShiftProj(-shift / 2.0, 0.0) * (*rightTransform);
 //   DOTRACE(("Total misrectify is %lf", totalMisrectify));
}
void corecvs::StereoAligner::getLateralCorrectionFixPoint (Matrix33 * leftTransform, Matrix33 * rightb, Vector2dd fixedPoint) [static]
Definition at line 471 of file stereoAligner.cpp.
References corecvs::Matrix33::ShiftProj().
{
    Vector2dd fixedPointShift = (*leftTransform) * fixedPoint;
    Matrix33 backShift = Matrix33::ShiftProj(fixedPoint - fixedPointShift);
    *leftTransform = backShift * (*leftTransform);
    *rightTransform = backShift * (*rightTransform);
}
The documentation for this class was generated from the following files:
core/rectification/stereoAligner.h
core/rectification/stereoAligner.cpp