DeepView: OpenCvHelper Class Reference
OpenCvHelper Class Reference
#include <openCvHelper.h>
Static Public Member Functions
static bool captureImageCopyToBuffer (cv::VideoCapture &capture, G12Buffer *buf)
static bool captureImageCopyToBuffer (CvCapture *capHandle, G12Buffer *buf)
Static Private Member Functions
static bool captureImageCopyToBuffer (IplImage *image, G12Buffer *buf)
Detailed Description
Definition at line 11 of file openCvHelper.h.
Member Function Documentation
bool OpenCvHelper::captureImageCopyToBuffer (cv::VideoCapture & capture, G12Buffer * buf) [static]
Definition at line 3 of file openCvHelper.cpp.
Referenced by captureImageCopyToBuffer(), OpenCvFileCapture::SpinThread::grabFramePair(), and OpenCVCaptureInterface::SpinThread::run().
{
    cv::Mat image;
    if (!capture.grab())
        return false;
    capture.retrieve(image);
    IplImage frame = image;
    return captureImageCopyToBuffer(&frame, buf);
}
bool OpenCvHelper::captureImageCopyToBuffer (CvCapture * capHandle, G12Buffer * buf) [static]
Definition at line 15 of file openCvHelper.cpp.
References captureImageCopyToBuffer().
{
    IplImage* frame = cvQueryFrame(capHandle);
    return captureImageCopyToBuffer(frame, buf);
}
bool OpenCvHelper::captureImageCopyToBuffer (IplImage * image, G12Buffer * buf) [static, private]
Definition at line 21 of file openCvHelper.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element().
{
    if (!buf)
        throw "No buffer allocated for a frame";
    const uchar *imageData = (const uchar *)frame->imageData;
    /*
     * Note here that OpenCV image is stored so that each lined is 32-bits aligned thus
     * explaining the necessity to "skip" the few last bytes of each line of OpenCV image buffer.
     */
    int widthStep = frame->widthStep;
    int height = frame->height;
    int width = frame->width;
    if ((frame->depth != IPL_DEPTH_8U) || (frame->nChannels != 3))
    {
        printf("Unsupported IplImage format: depth=%d, channels = %d\n", frame->depth, frame->nChannels);
        exit(EXIT_FAILURE);
    }
    for (int i = 0; i < height; i++)
    {
        for (int j = 0; j < width; j++)
        {
            buf->element(i, j) =  (11 * imageData[0] + 16 * imageData[1] + 5 * imageData[2]) >> 1;
            imageData += 3;
        }
        imageData += widthStep - 3 * width;
    }
    return true;
}
The documentation for this class was generated from the following files:
utils/framesources/openCvHelper.h
utils/framesources/openCvHelper.cpp