DeepView: RecorderControlWidget Class Reference
RecorderControlWidget Class Reference
#include <recorderControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
RecorderControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~RecorderControlWidget ()
Recorder * createParameters () const
void setParameters (const Recorder &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Ui::RecorderControlWidget * ui ()
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui::RecorderControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 13 of file recorderControlWidget.h.
Constructor & Destructor Documentation
RecorderControlWidget::RecorderControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file recorderControlWidget.cpp.
References mUi, and paramsChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::RecorderControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->pathEdit, SIGNAL(textChanged(QString)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fileTemplateEdit, SIGNAL(textChanged(QString)), this, SIGNAL(paramsChanged()));
}
RecorderControlWidget::~RecorderControlWidget ()
Definition at line 27 of file recorderControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void RecorderControlWidget::changeParameters () [inline, slot]
Definition at line 35 of file recorderControlWidget.h.
    {
        // emit paramsChanged();
    }
Recorder * RecorderControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 49 of file recorderControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), ParametersMapperRecorder::paramsChanged(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    Recorder *result = new Recorder(
          mUi->pathEdit->text().toStdString()
        , mUi->fileTemplateEdit->text().toStdString()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void RecorderControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 33 of file recorderControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    Recorder *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void RecorderControlWidget::paramsChanged () [signal]
Referenced by RecorderControlWidget(), and setParameters().
void RecorderControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 41 of file recorderControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    Recorder *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void RecorderControlWidget::setParameters (const Recorder & input)
Definition at line 64 of file recorderControlWidget.cpp.
References Recorder::fileTemplate(), mUi, paramsChanged(), and Recorder::path().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->pathEdit->setText(input.path().c_str());
    mUi->fileTemplateEdit->setText(input.fileTemplate().c_str());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void RecorderControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 74 of file recorderControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    Recorder *inputCasted = static_cast<Recorder *>(input);
    setParameters(*inputCasted);
}
Ui::RecorderControlWidget* RecorderControlWidget::ui () [inline]
Definition at line 29 of file recorderControlWidget.h.
References mUi.
Referenced by RecorderDialog::createCalculator(), RecorderDialog::initParameterWidgets(), RecorderDialog::openPathSelectDialog(), RecorderDialog::processResult(), and RecorderDialog::recordingStateChanged().
    {
        return mUi;
    }
void RecorderControlWidget::valueChanged () [signal]
Member Data Documentation
bool RecorderControlWidget::autoInit [private]
Definition at line 46 of file recorderControlWidget.h.
Ui::RecorderControlWidget* RecorderControlWidget::mUi [private]
Definition at line 45 of file recorderControlWidget.h.
Referenced by createParameters(), RecorderControlWidget(), setParameters(), ui(), and ~RecorderControlWidget().
QString RecorderControlWidget::rootPath [private]
Definition at line 47 of file recorderControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
applications/recorder/recorderControlWidget.h
applications/recorder/recorderControlWidget.cpp