DeepView: ImageWidget Class Reference
ImageWidget Class Reference
#include <g12Image.h>
Signals
void askParentRepaint (QPaintEvent *event, QWidget *who)
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (QResizeEvent *event)
void notifyKeyPressEvent (QKeyEvent *event)
void notifyKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
ImageWidget ()
void setImage (QImage *_image)
virtual void paintEvent (QPaintEvent *)
~ImageWidget ()
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
Public Attributes
QImage * image
Detailed Description
Definition at line 38 of file g12Image.h.
Constructor & Destructor Documentation
ImageWidget::ImageWidget () [inline]
Definition at line 42 of file g12Image.h.
: image(NULL) {};
ImageWidget::~ImageWidget () [inline]
Definition at line 47 of file g12Image.h.
{};
Member Function Documentation
void ViAreaWidget::askParentRepaint (QPaintEvent * event, QWidget * who) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::paintEvent().
void ViAreaWidget::keyPressEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 53 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyPressEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyPressEvent(event);
}
void ViAreaWidget::keyReleaseEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 59 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyReleaseEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyReleaseEvent(event);
}
void ViAreaWidget::mouseDoubleClickEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 35 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mouseMoveEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 16 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mousePressEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 22 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, ViAreaWidget::notifyParentMouseMove(), and ViAreaWidget::notifyParentMousePress().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
    emit notifyParentMousePress(event);
}
void ViAreaWidget::mouseReleaseEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 41 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseRelease().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseRelease(event);
}
void ViAreaWidget::notifyKeyPressEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyPressEvent().
void ViAreaWidget::notifyKeyReleaseEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyReleaseEvent().
void ViAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), ViAreaWidget::mouseDoubleClickEvent(), ViAreaWidget::mouseMoveEvent(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::mouseReleaseEvent().
void ViAreaWidget::notifyParentResize (QResizeEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::resizeEvent().
void ViAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget::AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::wheelEvent().
void ImageWidget::paintEvent (QPaintEvent * event) [virtual]
Reimplemented from ViAreaWidget.
Definition at line 121 of file g12Image.cpp.
References image.
{
    QPainter p(this);
    if (image != NULL)
        p.drawImage(QPoint(0,0), *image);
    ViAreaWidget::paintEvent(event);
}
void ViAreaWidget::resizeEvent (QResizeEvent * event) [virtual, inherited]
Definition at line 29 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentResize().
{
    if (!mForwardEvents) return;
    emit notifyParentResize(event);
}
void ImageWidget::setImage (QImage * _image)
Definition at line 111 of file g12Image.cpp.
References image.
{
    QImage *oldImage = image;
    image = newImage;
    delete oldImage;
    this->resize(image->size());
    this->update();
}
void ViAreaWidget::wheelEvent (QWheelEvent * event) [virtual, inherited]
Definition at line 47 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentWheelEvent().
{
    if (!mForwardEvents) return;
    emit notifyParentWheelEvent(event);
}
Member Data Documentation
QImage* ImageWidget::image
Definition at line 40 of file g12Image.h.
Referenced by paintEvent(), and setImage().
The documentation for this class was generated from the following files:
utils/corestructs/g12Image.h
utils/corestructs/g12Image.cpp