DeepView: corecvs::AbstractPainter< TargetBuffer > Class Template Reference
corecvs::AbstractPainter< TargetBuffer > Class Template Reference
#include <abstractPainter.h>
Classes
class EqualPredicate
struct Segment
Public Types
typedef
TargetBuffer::InternalElementType ElementType
Public Member Functions
AbstractPainter (TargetBuffer *target)
void drawChar (uint16_t x, uint16_t y, uint8_t theChar, ElementType color, int scale=2)
This function draws the char with the hardcoded font Not all chars are supported.
void drawFormat (uint16_t x, uint16_t y, ElementType color, int scale, const char *format,...)
int drawGlyph (int16_t dx, int16_t dy, uint8_t theChar, ElementType color, int scale)
void drawFormatVector (int16_t x, int16_t y, ElementType color, int scale, const char *format,...)
void drawCircle (int x, int y, int rad, ElementType color)
template<class Predicate >
void floodFill (int startX, int startY, Predicate &predicate)
virtual ~AbstractPainter ()
Private Attributes
TargetBuffer * mTarget
Detailed Description
template<class TargetBuffer>
class corecvs::AbstractPainter< TargetBuffer >
Definition at line 20 of file abstractPainter.h.
Member Typedef Documentation
template<class TargetBuffer > typedef TargetBuffer::InternalElementType corecvs::AbstractPainter< TargetBuffer >::ElementType
Definition at line 24 of file abstractPainter.h.
Constructor & Destructor Documentation
template<class TargetBuffer > corecvs::AbstractPainter< TargetBuffer >::AbstractPainter (TargetBuffer * target) [inline]
Definition at line 26 of file abstractPainter.h.
                                          :
        mTarget(target)
    {}
template<class TargetBuffer > virtual corecvs::AbstractPainter< TargetBuffer >::~AbstractPainter () [inline, virtual]
Definition at line 305 of file abstractPainter.h.
{}
Member Function Documentation
template<class TargetBuffer > void corecvs::AbstractPainter< TargetBuffer >::drawChar (uint16_t x, uint16_t y, uint8_t theChar, ElementType color, int scale = 2) [inline]
This function draws the char with the hardcoded font Not all chars are supported.
Note: this method must be implemented right here, otherwise msvc couldn't understand correctly usage of "ElementType".
Definition at line 36 of file abstractPainter.h.
References corecvs::HardcodeFont::alpha_glyphs, corecvs::HardcodeFont::GLYPH_HEIGHT, corecvs::HardcodeFont::GLYPH_WIDTH, corecvs::AbstractPainter< TargetBuffer >::mTarget, corecvs::HardcodeFont::num_glyphs, and corecvs::HardcodeFont::symbols_glyphs.
Referenced by corecvs::AbstractPainter< TargetBuffer >::drawFormat().
    {
        uint8_t *char_ptr = NULL;
        if (theChar == ' ')
            return;
        if (theChar >='0' && theChar <= '9')
            char_ptr = HardcodeFont::num_glyphs + HardcodeFont::GLYPH_HEIGHT * (theChar - '0');
        if (theChar >='a' && theChar <= 'z')
            char_ptr = HardcodeFont::alpha_glyphs + HardcodeFont::GLYPH_HEIGHT * (theChar - 'a');
        if (theChar >='A' && theChar <= 'Z')
            char_ptr = HardcodeFont::alpha_glyphs + HardcodeFont::GLYPH_HEIGHT * (theChar - 'A');
        if (theChar == '-')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 0;
        if (theChar == '%')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 1;
        if (theChar == '.')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 2;
        if (theChar == ':')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 3;
        if (theChar == '!')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 4;
        if (theChar == '?')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 5;
        if (theChar == '$')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 6;
        if (theChar == '\"')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 7;
        if (theChar == '\'')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 8;
        if (theChar == '_')
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 9;
        if (char_ptr == NULL)
            char_ptr = HardcodeFont::symbols_glyphs + HardcodeFont::GLYPH_HEIGHT * 10;
        for (int i = 0; i < HardcodeFont::GLYPH_HEIGHT; i++)
        {
            for (int j = 0; j < HardcodeFont::GLYPH_WIDTH; j++)
            {
                if (char_ptr[i] & (1 << (HardcodeFont::GLYPH_WIDTH - j - 1)))
                {
                    int rx = x + scale * j;
                    int ry = y + scale * i;
                    for (int dy = 0; dy < scale; dy++)
                    {
                        for (int dx = 0; dx < scale; dx++)
{
                            if (mTarget->isValidCoord(ry + dy, rx + dx))
                                mTarget->element(ry + dy, rx + dx) = color;
                        }
                    }
                }
            }
        }
    }
template<class TargetBuffer > void corecvs::AbstractPainter< TargetBuffer >::drawCircle (int x, int y, int rad, ElementType color) [inline]
Definition at line 157 of file abstractPainter.h.
References corecvs::AbstractPainter< TargetBuffer >::mTarget.
    {
        int radsq = rad * rad;
        for (int dy = -rad; dy <= 0; dy++)
        {
            int dx = (int)sqrt((float)(radsq - (dy - 0.5) * (dy - 0.5)));
            for (int j= x - dx; j <= x + dx; j++)
            {
                if (mTarget->isValidCoord(y - dy, j))
                    mTarget->element(y - dy, j) = color;
                if (mTarget->isValidCoord(y + dy, j))
                    mTarget->element(y + dy, j) = color;
            }
        }
    }
template<class TargetBuffer > void corecvs::AbstractPainter< TargetBuffer >::drawFormat (uint16_t x, uint16_t y, ElementType color, int scale, const char * format, ...) [inline]
Definition at line 95 of file abstractPainter.h.
References CORE_COUNT_OF, and corecvs::AbstractPainter< TargetBuffer >::drawChar().
    {
        char str[1024];
        va_list marker;
        va_start(marker, format);
        vsnprintf(str, CORE_COUNT_OF(str), format, marker);
        int i = 0;
        while (str[i] != 0)
        {
            drawChar(x + i * 6 * scale, y, str[i], color, scale);
            i++;
        }
        va_end(marker);
    }
template<class TargetBuffer > void corecvs::AbstractPainter< TargetBuffer >::drawFormatVector (int16_t x, int16_t y, ElementType color, int scale, const char * format, ...) [inline]
Definition at line 141 of file abstractPainter.h.
References CORE_COUNT_OF, and corecvs::AbstractPainter< TargetBuffer >::drawGlyph().
Referenced by StereoCameraScene::drawMyself().
    {
        char str[1024];
        va_list marker;
        va_start(marker, format);
        vsnprintf(str, CORE_COUNT_OF(str), format, marker);
        int i = 0;
        int dx = 0;
        while (str[i] != 0)
        {
            dx += drawGlyph(x + dx, y, str[i++], color, scale);
        }
        va_end(marker);
    }
template<class TargetBuffer > int corecvs::AbstractPainter< TargetBuffer >::drawGlyph (int16_t dx, int16_t dy, uint8_t theChar, ElementType color, int scale) [inline]
Definition at line 111 of file abstractPainter.h.
References corecvs::HersheyVectorFont::Glyph::data, corecvs::HersheyVectorFont::data, corecvs::HersheyVectorFont::Glyph::len, corecvs::AbstractPainter< TargetBuffer >::mTarget, and corecvs::HersheyVectorFont::Glyph::width.
Referenced by corecvs::AbstractPainter< TargetBuffer >::drawFormatVector().
    {
        int id = 0;
        if (theChar >= ' ' || theChar <= '~')
        {
            id = theChar - ' ';
        }
        HersheyVectorFont::Glyph *glyph = &HersheyVectorFont::data[id];
        int oldx = -1;
        int oldy = -1;
        //printf("(%d)\n", glyph->len);
        for (int i = 0; i < glyph->len; i++)
        {
            int x = glyph->data[i * 2];
            int y = glyph->data[i * 2 + 1];
          //printf("[%d %d][%d %d]\n", x,y, oldx, oldy);
            if (x != -1 && y != -1 && oldx != -1 && oldy != -1)
            {
                mTarget->drawLine(dx + oldx * scale, dy - oldy * scale, dx + x * scale, dy - y * scale, color);
            }
            oldx = x;
            oldy = y;
        }
        return glyph->width * scale;
    }
template<class TargetBuffer > template<class Predicate > void corecvs::AbstractPainter< TargetBuffer >::floodFill (int startX, int startY, Predicate & predicate) [inline]
Definition at line 220 of file abstractPainter.h.
References corecvs::AbstractPainter< TargetBuffer >::mTarget, corecvs::AbstractPainter< TargetBuffer >::Segment::x1, corecvs::AbstractPainter< TargetBuffer >::Segment::x2, and corecvs::AbstractPainter< TargetBuffer >::Segment::y.
    {
        std::vector<Segment> queue;
        /* Put the first segment*/
        if (!predicate(mTarget, startX, startY)) {
            return;
        }
//        printf("Pushing top %d [%d -> %d]\n", startY, startX, startX);
        queue.push_back(Segment(startX, startX, startY));
        while (!queue.empty()) {
            Segment state = queue.back();
            queue.pop_back();
            int x1 = state.x1;
            int x2 = state.x2;
            int y  = state.y;
            if (y < 0 || y > mTarget->h - 1) {
                continue;
            }
            while((x1 > 0) && predicate(mTarget, x1 - 1, y))
            {
                x1--;
            }
            while((x2 < mTarget->w - 1) && predicate(mTarget, x2 + 1, y) )
            {
                x2++;
            }
            //printf("Filling %d to %d\n", x1, x2);
            bool topAdd = false;    /* we store the fact that top scanline is already added */
            Segment top;
            top.y = y - 1;
            bool bottomAdd = false;    /* we store the fact that top scanline is already added */
            Segment bottom;
            bottom.y = y + 1;
            /* Fill line */
            for (int run = x1; run <= x2; run ++)
            {
                bool topFill    = false;
                bool bottomFill = false;
                if (y > 0) {
                    topFill = predicate(mTarget, run, y - 1);
                    if (!topAdd && topFill) {
                        topAdd = true;
                        top.x1 = run;
                    }
                    if (topAdd && (!topFill || run == x2)) {
                        topAdd = false;
                        top.x2 = run - 1;
//                        printf("Pushing top %d [%d -> %d]\n", top.y, top.x1, top.x2);
                        queue.push_back(top);
                    }
                }
                if (y < mTarget->h - 1 )
                {
                    bottomFill = predicate(mTarget, run, y + 1);
                    if (!bottomAdd && bottomFill) {
                        bottomAdd = true;
                        bottom.x1 = run;
                    }
                    if (bottomAdd && (!bottomFill || run == x2)) {
                        bottomAdd = false;
                        bottom.x2 = run - 1;
//                        printf("Pushing bottom %d [%d -> %d]\n", bottom.y, bottom.x1, bottom.x2);
                        queue.push_back(bottom);
                    }
                }
                predicate.mark(mTarget, run, y);
            }
        }
    }
Member Data Documentation
template<class TargetBuffer > TargetBuffer* corecvs::AbstractPainter< TargetBuffer >::mTarget [private]
Definition at line 22 of file abstractPainter.h.
Referenced by corecvs::AbstractPainter< TargetBuffer >::drawChar(), corecvs::AbstractPainter< TargetBuffer >::drawCircle(), corecvs::AbstractPainter< TargetBuffer >::drawGlyph(), and corecvs::AbstractPainter< TargetBuffer >::floodFill().
The documentation for this class was generated from the following file:
core/buffers/rgb24/abstractPainter.h