DeepView: corecvs::LevenMarq Class Reference
corecvs::LevenMarq Class Reference
#include <levenmarq.h>
Static Public Member Functions
static vector< Vector2dd > doLevMarFit (vector< Vector2dd > const &distortionVector)
Levenberg–Marquardt fillting:
static vector< Vector2dd > doLevMarFit (vector< Vector2dd > const &distortionVector)
Static Private Member Functions
static Matrix * createMatrix (vector< Vector2dd > const &curve, double k, double b)
static double dist (Matrix *m)
static vector< Vector2dd > inverseCurve (vector< Vector2dd > const &curve)
static Matrix * createMatrix (vector< Vector2dd > const &curve, double k, double b)
static double dist (Matrix *m)
static vector< Vector2dd > inverseCurve (vector< Vector2dd > const &curve)
Detailed Description
Definition at line 8 of file levenmarq.h.
Member Function Documentation
Matrix * corecvs::LevenMarq::createMatrix (vector< Vector2dd > const & curve, double k, double b) [static, private]
Definition at line 105 of file levenmarq.cpp.
References ELEM, and matrixCreate().
Referenced by doLevMarFit().
{
    Matrix *D = matrixCreate(curve.size(), 1);
    for (unsigned i = 0; i < curve.size(); i++)
    {
        double pntDist = curve.at(i).y() - (k * curve.at(i).x() + b);
        ELEM(D, i, 0) = pntDist;
    }
    return D;
}
static Matrix* corecvs::LevenMarq::createMatrix (vector< Vector2dd > const & curve, double k, double b) [static, private]
double corecvs::LevenMarq::dist (Matrix * m) [static, private]
Definition at line 116 of file levenmarq.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::data.
Referenced by doLevMarFit().
{
    double norm = 0;
    for (int i = 0; i < m->m; i++)
    {
        norm += pow(m->data[i], 2);
    }
    return norm;
}
static double corecvs::LevenMarq::dist (Matrix * m) [static, private]
vector< Vector2dd > corecvs::LevenMarq::doLevMarFit (vector< Vector2dd > const & distVector) [static]
Levenberg–Marquardt fillting:
http://en.wikipedia.org/wiki/Levenberg%E2%80%93Marquardt_algorithm
Definition at line 23 of file levenmarq.cpp.
References createMatrix(), corecvs::AbstractBuffer< ElementType, IndexType >::data, corecvs::dimention, dist(), ELEM, inverseCurve(), corecvs::iterations, corecvs::lambda_factor, matrixCopy(), matrixCreate(), matrixMultiply(), matrixSolveGaussian(), matrixTranspose(), and corecvs::minXDif.
{
    vector<Vector2dd> distortionVector = distVector;
    int num = distortionVector.size();
    Matrix *D = matrixCreate(num, 1);
    Matrix * J = matrixCreate(num, dimention);
    Matrix *JT = matrixCreate(dimention, num);
    Matrix *A = matrixCreate(dimention, dimention);
    Matrix *Asolve = matrixCreate(dimention, dimention);
    Matrix *B = matrixCreate(dimention, 1);
    Matrix *Bsolve = matrixCreate(dimention, 1);
    vector<Vector2dd> correctVector;
    double lambda = 0.01;
    bool wasInverse = false;
    if (fabs(distortionVector.at(0).x() - distortionVector.back().x()) < minXDif)
    {
        distortionVector = inverseCurve(distVector);
        wasInverse = true;
    }
    double k = (distortionVector.at(0).y() - distortionVector.back().y()) / (distortionVector.at(0).x() - distortionVector.back().x());
    double b = distortionVector. at(0).y() - k * distortionVector.at(0).x();
    D = createMatrix(distortionVector, k, b);
    double norm = dist(D);
    for (int g = 0; g < iterations; g++)
    {
        // Fill the matrices
        for (int i = 0; i < num; i++)
        {
            ELEM(J, i, 0) = distortionVector.at(i).x();
            ELEM(J, i, 1) = 1;
        }
        // Now form the equation
        // (trans(J) * J) * delta = trans(J) * (y - f(x))
        matrixTranspose(J, JT);
        matrixMultiply(JT, J, A);
        //printf("D size is %lf\n", norm);
        matrixMultiply(JT, D, B);
        bool f = false;
        while (lambda < 1e12 && !f)
        {
            matrixCopy(A, Asolve);
            matrixCopy(B, Bsolve);
            for (int j = 0; j < dimention; j++)
            {
                Asolve->data[j * dimention + j] *= (1.0 + lambda );
            }
            matrixSolveGaussian(Asolve, Bsolve);
            double k0 = k + Bsolve->data[0];
            double b0 = b + Bsolve->data[1];
            D = createMatrix(distortionVector, k0, b0);
            double norm1 = dist(D);
            if (norm1 < norm) // If the currnet solution is better
            {
                //printf("Current solution is better");
                lambda /= lambda_factor;
                norm = norm1;
                k = k0;
                b = b0;
                f = true;
            }
            else
                lambda *= lambda_factor;//"Current solution is worse. Try new lambda\n");
        }
    }
    for (int i = 0; i < num; i++)
    {
        double x = distortionVector.at(i).x();
        Vector2dd pnt(x, k * x + b);
        correctVector.push_back(pnt);
    }
    if (wasInverse)
    {
        return inverseCurve(correctVector);
    }
    return correctVector;
}
static vector<Vector2dd> corecvs::LevenMarq::doLevMarFit (vector< Vector2dd > const & distortionVector) [static]
vector< Vector2dd > corecvs::LevenMarq::inverseCurve (vector< Vector2dd > const & curve) [static, private]
Definition at line 126 of file levenmarq.cpp.
Referenced by doLevMarFit().
{
    vector<Vector2dd> inversedCurve;
    for (unsigned i = 0; i < curve.size(); i++)
    {
        Vector2dd pnt(curve.at(i).y(), curve.at(i).x());
        inversedCurve.push_back(pnt);
    }
    return inversedCurve;
}
static vector<Vector2dd> corecvs::LevenMarq::inverseCurve (vector< Vector2dd > const & curve) [static, private]
The documentation for this class was generated from the following files:
core/clegacy/math/levenmarq.h
core/clegacy/math/levenmarq.cpp