DeepView: WidgetLoader Class Reference
WidgetLoader Class Reference
#include <parametersControlWidgetBase.h>
Public Member Functions
WidgetLoader ()
WidgetLoader (SettingsGetter *qtSettigns)
WidgetLoader (XmlGetter *xmlSetter)
template<class ParametersClass >
void loadParameters (ParametersClass &paramsClass, QString name)
Private Attributes
SettingsGetter * mQtSettings
XmlGetter * mXmlGetter
Detailed Description
Definition at line 63 of file parametersControlWidgetBase.h.
Constructor & Destructor Documentation
WidgetLoader::WidgetLoader () [inline]
Definition at line 68 of file parametersControlWidgetBase.h.
                   :
        mQtSettings(NULL),
        mXmlGetter(NULL)
    {}
WidgetLoader::WidgetLoader (SettingsGetter * qtSettigns) [inline]
Definition at line 73 of file parametersControlWidgetBase.h.
                                             :
        mQtSettings(qtSettigns),
        mXmlGetter(NULL)
    {}
WidgetLoader::WidgetLoader (XmlGetter * xmlSetter) [inline]
Definition at line 78 of file parametersControlWidgetBase.h.
                                       :
        mQtSettings(NULL),
        mXmlGetter(xmlSetter)
    {}
Member Function Documentation
template<class ParametersClass > void WidgetLoader::loadParameters (ParametersClass & paramsClass, QString name) [inline]
Definition at line 84 of file parametersControlWidgetBase.h.
References mQtSettings, mXmlGetter, and SettingsGetter::settings().
Referenced by MakePreciseParametersControlWidget::loadParamWidget(), GraphPlotParametersControlWidget::loadParamWidget(), AxisAlignedBoxParametersControlWidget::loadParamWidget(), OpenCVBMParametersControlWidget::loadParamWidget(), OpenCVSGMParametersControlWidget::loadParamWidget(), PresentationParametersControlWidget::loadParamWidget(), HeadSearchParametersControlWidget::loadParamWidget(), BaseParametersControlWidget::loadParamWidget(), RecorderControlWidget::loadParamWidget(), RgbColorParametersControlWidget::loadParamWidget(), BinarizeParametersControlWidget::loadParamWidget(), MaskingParametersControlWidget::loadParamWidget(), ThickeningParametersControlWidget::loadParamWidget(), GainOffsetParametersControlWidget::loadParamWidget(), BackgroundFilterParametersControlWidget::loadParamWidget(), BitSelectorParametersControlWidget::loadParamWidget(), OutputFilterParametersControlWidget::loadParamWidget(), OpenCVFilterParametersControlWidget::loadParamWidget(), CannyParametersControlWidget::loadParamWidget(), InputFilterParametersControlWidget::loadParamWidget(), Draw3dCameraParametersControlWidget::loadParamWidget(), Draw3dViMouseParametersControlWidget::loadParamWidget(), Draw3dParametersControlWidget::loadParamWidget(), SobelParametersControlWidget::loadParamWidget(), OperationParametersControlWidget::loadParamWidget(), and RectifyParametersControlWidget::loadParamWidget().
    {
        if (mQtSettings) {
            mQtSettings->settings()->beginGroup(name);
                paramsClass.accept(*mQtSettings);
            mQtSettings->settings()->endGroup();
            return;
        }
        if (mXmlGetter) {
            paramsClass.accept(*mXmlGetter);
            return;
        }
    }
Member Data Documentation
SettingsGetter* WidgetLoader::mQtSettings [private]
Definition at line 64 of file parametersControlWidgetBase.h.
Referenced by loadParameters().
XmlGetter* WidgetLoader::mXmlGetter [private]
Definition at line 65 of file parametersControlWidgetBase.h.
Referenced by loadParameters().
The documentation for this class was generated from the following file:
utils/corestructs/parametersControlWidgetBase.h