DeepView: DiagramItem Class Reference
DiagramItem Class Reference
[0]
#include <diagramitem.h>
Public Types
enum { Type = UserType + 15 }
Public Member Functions
DiagramItem (QGraphicsItem *parent=0, QGraphicsScene *scene=0)
void finishInit ()
void removeArrow (Arrow *arrow)
void removeArrows ()
QPolygonF polygon () const
void addArrow (Arrow *arrow)
int type () const
virtual void foo ()
~DiagramItem ()
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Protected Attributes
QPolygonF myPolygon
Private Attributes
QList< Arrow * > arrows
Detailed Description
[0]
Definition at line 52 of file diagramitem.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 55 of file diagramitem.h.
{ Type = UserType + 15 };
Constructor & Destructor Documentation
DiagramItem::DiagramItem (QGraphicsItem * parent = 0, QGraphicsScene * scene = 0) [inline]
Definition at line 57 of file diagramitem.h.
                                           :
        QGraphicsPolygonItem(parent, scene)
    {}
DiagramItem::~DiagramItem ()
Definition at line 68 of file diagramitem.cpp.
References removeArrows().
{
    removeArrows();
}
Member Function Documentation
void DiagramItem::addArrow (Arrow * arrow)
Definition at line 73 of file diagramitem.cpp.
References arrows.
Referenced by DiagramScene::addArrow().
{
    arrows.append(arrow);
}
void DiagramItem::finishInit ()
Definition at line 47 of file diagramitem.cpp.
References myPolygon.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), and FilterPinPresentation::FilterPinPresentation().
{
    setPolygon(myPolygon);
    setFlag(QGraphicsItem::ItemSendsGeometryChanges, true);
}
virtual void DiagramItem::foo () [inline, virtual]
Definition at line 70 of file diagramitem.h.
{}
QVariant DiagramItem::itemChange (GraphicsItemChange change, const QVariant & value) [protected]
Definition at line 78 of file diagramitem.cpp.
References arrows, and Arrow::updatePosition().
{
    if (change == QGraphicsItem::ItemPositionChange)
        foreach (Arrow *arrow, arrows)
            arrow->updatePosition();
    return value;
}
QPolygonF DiagramItem::polygon () const [inline]
Definition at line 66 of file diagramitem.h.
Referenced by FilterBlockPresentation::drawInputPins(), FilterBlockPresentation::drawOutputPins(), and Arrow::paint().
        { return myPolygon; }
void DiagramItem::removeArrow (Arrow * arrow)
Definition at line 53 of file diagramitem.cpp.
References arrows.
Referenced by FilterGraphPresentation::deleteItem(), and removeArrows().
{
    int index = arrows.indexOf(arrow);
    if (index != -1)  arrows.removeAt(index);
}
void DiagramItem::removeArrows ()
Definition at line 59 of file diagramitem.cpp.
References arrows, Arrow::endItem(), removeArrow(), and Arrow::startItem().
Referenced by FilterGraphPresentation::deleteItem(), and ~DiagramItem().
{
    foreach (Arrow *arrow, arrows)
    {   arrow->startItem()->removeArrow(arrow);
        arrow->endItem()->removeArrow(arrow);
        delete_safe(arrow);
    }
}
int DiagramItem::type () const [inline]
Definition at line 69 of file diagramitem.h.
{ return Type;}
Member Data Documentation
QList<Arrow *> DiagramItem::arrows [private]
Definition at line 79 of file diagramitem.h.
Referenced by addArrow(), itemChange(), removeArrow(), and removeArrows().
QPolygonF DiagramItem::myPolygon [protected]
Definition at line 76 of file diagramitem.h.
Referenced by FilterBlockPresentation::FilterBlockPresentation(), FilterPinPresentation::FilterPinPresentation(), and finishInit().
The documentation for this class was generated from the following files:
utils/filters/graph/diagramitem.h
utils/filters/graph/diagramitem.cpp