DeepView: StereoColorer Class Reference
StereoColorer Class Reference
#include <stereoColorer.h>
Public Member Functions
StereoColorer (int preDisp, int minDisp, int maxDisp, int clickDisp)
virtual QColor getColor (Vector2d16 &point)
virtual uint32_t getPacked (Vector2d16 &point)
bool shouldDrawEllipses (int disp)
QColor ellipsesColor ()
Static Public Member Functions
static int hsvCacheInit ()
static uint32_t packRGB (unsigned r, unsigned g, unsigned b)
Public Attributes
DrawColoring style
Static Public Attributes
static QColor * hsvColorCache
static uint32_t * hsvPackedCache
static int dummy = AbstractFlowColorer::hsvCacheInit()
Private Attributes
int mPreDisp
int mMinDisp
int mMaxDisp
int mClickDisp
Detailed Description
Definition at line 5 of file stereoColorer.h.
Constructor & Destructor Documentation
StereoColorer::StereoColorer (int preDisp, int minDisp, int maxDisp, int clickDisp)
Definition at line 4 of file stereoColorer.cpp.
    : AbstractFlowColorer(),
      mPreDisp(preDisp),
      mMinDisp(minDisp),
      mMaxDisp(maxDisp),
      mClickDisp(clickDisp)
{
}
Member Function Documentation
QColor StereoColorer::ellipsesColor () [virtual]
Implements AbstractFlowColorer.
Definition at line 82 of file stereoColorer.cpp.
{
    return QColor(255, 0, 0);
}
QColor StereoColorer::getColor (Vector2d16 & point) [virtual]
Implements AbstractFlowColorer.
Definition at line 25 of file stereoColorer.cpp.
References AbstractFlowColorer::hsvColorCache, mMaxDisp, mMinDisp, mPreDisp, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    int disp = static_cast<int>(point.x());
    if ((point.y() > 20) || (point.y() < -20)) {
        return  QColor(0, 0, 0);
    }
    if (disp < mPreDisp) {
        return QColor(0, 128, 0);
    }
    if (disp < mMinDisp) {
        return QColor(248, 168, 255);
    }
    if (disp > mMaxDisp ) {
        return QColor(128, 0, 0);
    }
    int hue = (disp - mMinDisp) * 255;
    int diff = mMaxDisp - mMinDisp;
    hue = hue / ((diff > 0) ? diff : 1);
    if (hue > 255) hue = 255;
    if (hue < 0) hue = 0;
    return hsvColorCache[hue];
}
uint32_t StereoColorer::getPacked (Vector2d16 & point) [virtual]
Implements AbstractFlowColorer.
Definition at line 51 of file stereoColorer.cpp.
References AbstractFlowColorer::hsvPackedCache, mMaxDisp, mMinDisp, mPreDisp, AbstractFlowColorer::packRGB(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    int disp = static_cast<int>(point.x());
    if ((point.y() > 20) || (point.y() < -20)) {
        return packRGB(0x00,0x00,0x00);
    }
    if (disp < mPreDisp) {
        return packRGB(0x00,0x7F,0x00);
    }
    if (disp < mMinDisp) {
        return packRGB(248, 168, 255);
    }
    if (disp > mMaxDisp ) {
        return packRGB(0x7F,0x00,0x00);
    }
    int hue = (disp - mMinDisp) * 255;
    int diff = mMaxDisp - mMinDisp;
    hue = hue / ((diff > 0) ? diff : 1);
    if (hue > 255) hue = 255;
    if (hue < 0) hue = 0;
    return hsvPackedCache[hue];
}
int AbstractFlowColorer::hsvCacheInit () [static, inherited]
Definition at line 17 of file abstractFlowColorer.cpp.
References AbstractFlowColorer::hsvColorCache, AbstractFlowColorer::hsvPackedCache, and AbstractFlowColorer::packRGB().
{
    hsvColorCache  = new QColor[256];
    hsvPackedCache = new uint32_t[256];
    for (unsigned i = 0; i < 256; i++)
    {
        QColor color;
        color.setHsv(i, 255, 255, 255);
        uint32_t r = color.red();
        uint32_t g = color.green();
        uint32_t b = color.blue();
        hsvColorCache [i] = color;
        hsvPackedCache[i] = packRGB(r,g,b);
    }
    return 0;
}
static uint32_t AbstractFlowColorer::packRGB (unsigned r, unsigned g, unsigned b) [inline, static, inherited]
Definition at line 29 of file abstractFlowColorer.h.
Referenced by FlowColorer::getPacked(), getPacked(), and AbstractFlowColorer::hsvCacheInit().
    {
        return (0xFF << 24) | (r << 16) | (g << 8) | (b);
    }
bool StereoColorer::shouldDrawEllipses (int disp) [virtual]
Implements AbstractFlowColorer.
Definition at line 77 of file stereoColorer.cpp.
References mClickDisp, and mMaxDisp.
{
    return (disp > mMaxDisp && disp < mClickDisp);
}
Member Data Documentation
int AbstractFlowColorer::dummy = AbstractFlowColorer::hsvCacheInit() [static, inherited]
Definition at line 21 of file abstractFlowColorer.h.
QColor * AbstractFlowColorer::hsvColorCache [static, inherited]
Definition at line 19 of file abstractFlowColorer.h.
Referenced by FlowColorer::getColor(), getColor(), and AbstractFlowColorer::hsvCacheInit().
uint32_t * AbstractFlowColorer::hsvPackedCache [static, inherited]
Definition at line 20 of file abstractFlowColorer.h.
Referenced by FlowColorer::getPacked(), getPacked(), and AbstractFlowColorer::hsvCacheInit().
int StereoColorer::mClickDisp [private]
Definition at line 23 of file stereoColorer.h.
Referenced by shouldDrawEllipses().
int StereoColorer::mMaxDisp [private]
Definition at line 22 of file stereoColorer.h.
Referenced by getColor(), getPacked(), and shouldDrawEllipses().
int StereoColorer::mMinDisp [private]
Definition at line 21 of file stereoColorer.h.
Referenced by getColor(), and getPacked().
int StereoColorer::mPreDisp [private]
Definition at line 20 of file stereoColorer.h.
Referenced by getColor(), and getPacked().
DrawColoring AbstractFlowColorer::style [inherited]
Definition at line 24 of file abstractFlowColorer.h.
Referenced by FlowColorer::getColor(), and FlowColorer::getPacked().
The documentation for this class was generated from the following files:
utils/flowcolorers/stereoColorer.h
utils/flowcolorers/stereoColorer.cpp