DeepView: MjpegDecoderLazy::HuffmanParser Class Reference
MjpegDecoderLazy::HuffmanParser Class Reference
#include <mjpegDecoderLazy.h>
Public Member Functions
HuffmanParser (uint8_t *_datap)
HuffmanParser ()
int getValue (HuffmanTable *tbl)
int getBits (int number)
int readMarker ()
Public Attributes
uint8_t * datap
pointer to the data in stream
uint32_t bits
currently processed bits
int left
number of bits left to process untill we will need to pop more form stream
int marker
flag if marker was found
Private Member Functions
int fillbits ()
Detailed Description
Definition at line 64 of file mjpegDecoderLazy.h.
Constructor & Destructor Documentation
MjpegDecoderLazy::HuffmanParser::HuffmanParser (uint8_t * _datap) [inline]
Definition at line 72 of file mjpegDecoderLazy.h.
: datap(_datap), bits(0), left(0), marker(0) {}
MjpegDecoderLazy::HuffmanParser::HuffmanParser () [inline]
Definition at line 73 of file mjpegDecoderLazy.h.
{}
Member Function Documentation
int MjpegDecoderLazy::HuffmanParser::fillbits () [inline, private]
Definition at line 335 of file mjpegDecoderLazy.cpp.
References bits, datap, left, and marker.
{
   if (marker)
   {
       return left;
   }
   /* while the buffer is not yet filled */
   while (left <= 24) {
       /*get new byte*/
       uint8_t b = *datap++;
       uint8_t m;
       /* Check if it is a marker */
       if (b == 0xff) {
           if ((m = *datap++) != 0) {
               //printf("Marker %d\n", marker);
               marker = m;
               break;
           }
       }
       bits |= (b << (24 - left));
       left += 8;
   }
    return left;
}
int MjpegDecoderLazy::HuffmanParser::getBits (int number) [inline]
Definition at line 382 of file mjpegDecoderLazy.cpp.
References fillbits().
Referenced by MjpegDecoderLazy::decode_mcus().
{
    fillbits();
    if (number == 0)
        return 0;
    uint32_t value = bits >> (32 - number);
    bits <<= number;
    left -=  number;
#ifdef _TRACE
    printf("Addbits  : ");
    for (int tst = 0; tst < number; tst++)
    {
        printf("%s ", (value << tst) & (1 << (number - 1)) ? "1" : "0");
    }
#endif
    if (!(value & (1 << (number - 1)))) {
        value += (-1 << number) + 1;
    }
#ifdef _TRACE
    printf(" to %d\n", value);
#endif
    return value;
}
int MjpegDecoderLazy::HuffmanParser::getValue (HuffmanTable * tbl) [inline]
Definition at line 361 of file mjpegDecoderLazy.cpp.
References fillbits(), MjpegDecoderLazy::HuffmanTableEntry::length, MjpegDecoderLazy::HuffmanTable::table, and MjpegDecoderLazy::HuffmanTableEntry::value.
Referenced by MjpegDecoderLazy::decode_mcus().
{
    fillbits();
    uint16_t code = bits >> 16;
    uint8_t value  = tbl->table[code].value;
    uint8_t length = tbl->table[code].length;
#ifdef _TRACE
    printf("%8x : ", tbl->table);
    for (int tst = 0; tst < length; tst++)
    {
       printf("%s ", (code << tst) & 0x8000 ? "1" : "0");
    }
    printf(" -> %d\n", value);
#endif
    left -= length;
    bits <<= length;
    return value;
}
int MjpegDecoderLazy::HuffmanParser::readMarker () [inline]
Definition at line 408 of file mjpegDecoderLazy.cpp.
References fillbits().
Referenced by MjpegDecoderLazy::dec_checkmarker(), and MjpegDecoderLazy::decode().
{
    fillbits();
    int toReturn = marker;
    marker = 0;
    left = 0;
    bits = 0;
    fillbits();
    return toReturn;
}
Member Data Documentation
uint32_t MjpegDecoderLazy::HuffmanParser::bits
currently processed bits
Definition at line 68 of file mjpegDecoderLazy.h.
Referenced by fillbits().
uint8_t* MjpegDecoderLazy::HuffmanParser::datap
pointer to the data in stream
Definition at line 67 of file mjpegDecoderLazy.h.
Referenced by fillbits().
int MjpegDecoderLazy::HuffmanParser::left
number of bits left to process untill we will need to pop more form stream
Definition at line 69 of file mjpegDecoderLazy.h.
Referenced by fillbits().
int MjpegDecoderLazy::HuffmanParser::marker
flag if marker was found
Definition at line 70 of file mjpegDecoderLazy.h.
Referenced by fillbits().
The documentation for this class was generated from the following files:
utils/framesources/decoders/mjpegDecoderLazy.h
utils/framesources/decoders/mjpegDecoderLazy.cpp