DeepView: corecvs::FixedPoint24p8 Class Reference
corecvs::FixedPoint24p8 Class Reference
#include <fixedPoint24p8.h>
Public Member Functions
FixedPoint24p8 ()
FixedPoint24p8 (const uint32_t &_data)
FixedPoint24p8 (const double &value)
FixedPoint24p8 (const float &value)
FixedPoint24p8 operator+ (const FixedPoint24p8 &arg1, const FixedPoint24p8 &arg2)
FixedPoint24p8 operator- (const FixedPoint24p8 &arg1, const FixedPoint24p8 &arg2)
FixedPoint24p8 operator* (const FixedPoint24p8 &arg1, const FixedPoint24p8 &arg2)
FixedPoint24p8 mulFast (const FixedPoint24p8 &arg1, const FixedPoint24p8 &arg2)
FixedPoint24p8 fromUInt (uint32_t value)
Public Attributes
uint32_t data
Static Public Attributes
static const unsigned SHIFT_BITS = 8
static const unsigned FIXED_SCALE = 256
Detailed Description
Definition at line 18 of file fixedPoint24p8.h.
Constructor & Destructor Documentation
corecvs::FixedPoint24p8::FixedPoint24p8 ()
Definition at line 14 of file fixedPoint24p8.cpp.
Referenced by operator+(), and operator-().
{
}
corecvs::FixedPoint24p8::FixedPoint24p8 (const uint32_t & _data) [inline, explicit]
Definition at line 28 of file fixedPoint24p8.h.
References data.
    {
        data = _data;
    }
corecvs::FixedPoint24p8::FixedPoint24p8 (const double & value) [inline, explicit]
Definition at line 33 of file fixedPoint24p8.h.
References data, FIXED_SCALE, and corecvs::fround().
    {
        data = fround(value * FIXED_SCALE);
    }
corecvs::FixedPoint24p8::FixedPoint24p8 (const float & value) [inline, explicit]
Definition at line 38 of file fixedPoint24p8.h.
References data, FIXED_SCALE, and corecvs::fround().
    {
        data = fround(value * FIXED_SCALE);
    }
Member Function Documentation
FixedPoint24p8 corecvs::FixedPoint24p8::fromUInt (uint32_t value) [inline]
Definition at line 64 of file fixedPoint24p8.h.
References SHIFT_BITS.
    {
        return value << SHIFT_BITS;
    }
FixedPoint24p8 corecvs::FixedPoint24p8::mulFast (const FixedPoint24p8 & arg1, const FixedPoint24p8 & arg2) [inline]
Definition at line 59 of file fixedPoint24p8.h.
References data, and SHIFT_BITS.
    {
        return (arg1.data * arg2.data) >> SHIFT_BITS;
    }
FixedPoint24p8 corecvs::FixedPoint24p8::operator* (const FixedPoint24p8 & arg1, const FixedPoint24p8 & arg2) [inline]
Definition at line 53 of file fixedPoint24p8.h.
References data, and SHIFT_BITS.
    {
        uint64_t result = arg1.data * arg2.data;
        return result >> SHIFT_BITS;
    }
FixedPoint24p8 corecvs::FixedPoint24p8::operator+ (const FixedPoint24p8 & arg1, const FixedPoint24p8 & arg2) [inline]
Definition at line 43 of file fixedPoint24p8.h.
References data, and FixedPoint24p8().
    {
        return FixedPoint24p8(arg1.data + arg2.data);
    }
FixedPoint24p8 corecvs::FixedPoint24p8::operator- (const FixedPoint24p8 & arg1, const FixedPoint24p8 & arg2) [inline]
Definition at line 48 of file fixedPoint24p8.h.
References data, and FixedPoint24p8().
    {
        return FixedPoint24p8(arg1.data - arg2.data);
    }
Member Data Documentation
uint32_t corecvs::FixedPoint24p8::data
Definition at line 24 of file fixedPoint24p8.h.
Referenced by FixedPoint24p8(), mulFast(), operator*(), operator+(), and operator-().
const unsigned corecvs::FixedPoint24p8::FIXED_SCALE = 256 [static]
Definition at line 22 of file fixedPoint24p8.h.
Referenced by FixedPoint24p8().
const unsigned corecvs::FixedPoint24p8::SHIFT_BITS = 8 [static]
Definition at line 21 of file fixedPoint24p8.h.
Referenced by fromUInt(), mulFast(), and operator*().
The documentation for this class was generated from the following files:
core/math/fixed/fixedPoint24p8.h
core/math/fixed/fixedPoint24p8.cpp