DeepView: BaseParametersControlWidget Class Reference
BaseParametersControlWidget Class Reference
#include <baseParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
BaseParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~BaseParametersControlWidget ()
BaseParameters * createParameters () const
void setParameters (const BaseParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Ui::BaseParametersControlWidget * ui ()
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui::BaseParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 13 of file baseParametersControlWidget.h.
Constructor & Destructor Documentation
BaseParametersControlWidget::BaseParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file baseParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::BaseParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->rotationComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->mirrorCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->swapCamerasButton, SIGNAL(clicked(bool)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->filterLockButton, SIGNAL(clicked(bool)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->enableFilterGraphCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->downsampleSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->hSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->wSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->autoHCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->autoWCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->xSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->ySpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->interpolationTypeComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
}
BaseParametersControlWidget::~BaseParametersControlWidget ()
Definition at line 38 of file baseParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void BaseParametersControlWidget::changeParameters () [inline, slot]
Definition at line 35 of file baseParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
BaseParameters * BaseParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 60 of file baseParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), ParametersMapperBase::paramsChanged(), ParametersMapperRecorder::paramsChanged(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    BaseParameters *result = new BaseParameters(
          static_cast<RotationPresets::RotationPresets>(mUi->rotationComboBox->currentIndex())
        , mUi->mirrorCheckBox->isChecked()
        , mUi->swapCamerasButton->isChecked()
        , mUi->filterLockButton->isChecked()
        , mUi->enableFilterGraphCheckBox->isChecked()
        , mUi->downsampleSpinBox->value()
        , mUi->hSpinBox->value()
        , mUi->wSpinBox->value()
        , mUi->autoHCheckBox->isChecked()
        , mUi->autoWCheckBox->isChecked()
        , mUi->xSpinBox->value()
        , mUi->ySpinBox->value()
        , static_cast<InterpolationType::InterpolationType>(mUi->interpolationTypeComboBox->currentIndex())
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void BaseParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 44 of file baseParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    BaseParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void BaseParametersControlWidget::paramsChanged () [signal]
Referenced by BaseParametersControlWidget(), and setParameters().
void BaseParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 52 of file baseParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    BaseParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void BaseParametersControlWidget::setParameters (const BaseParameters & input)
Definition at line 86 of file baseParametersControlWidget.cpp.
References BaseParameters::autoH(), BaseParameters::autoW(), BaseParameters::downsample(), BaseParameters::enableFilterGraph(), BaseParameters::filterLock(), BaseParameters::h(), BaseParameters::interpolationType(), BaseParameters::mirror(), mUi, paramsChanged(), BaseParameters::rotation(), BaseParameters::swapCameras(), BaseParameters::w(), BaseParameters::x(), and BaseParameters::y().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->rotationComboBox->setCurrentIndex(input.rotation());
    mUi->mirrorCheckBox->setChecked(input.mirror());
    mUi->swapCamerasButton->setChecked(input.swapCameras());
    mUi->filterLockButton->setChecked(input.filterLock());
    mUi->enableFilterGraphCheckBox->setChecked(input.enableFilterGraph());
    mUi->downsampleSpinBox->setValue(input.downsample());
    mUi->hSpinBox->setValue(input.h());
    mUi->wSpinBox->setValue(input.w());
    mUi->autoHCheckBox->setChecked(input.autoH());
    mUi->autoWCheckBox->setChecked(input.autoW());
    mUi->xSpinBox->setValue(input.x());
    mUi->ySpinBox->setValue(input.y());
    mUi->interpolationTypeComboBox->setCurrentIndex(input.interpolationType());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void BaseParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 107 of file baseParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    BaseParameters *inputCasted = static_cast<BaseParameters *>(input);
    setParameters(*inputCasted);
}
Ui::BaseParametersControlWidget* BaseParametersControlWidget::ui () [inline]
Definition at line 29 of file baseParametersControlWidget.h.
References mUi.
Referenced by BaseHostDialog::initGraphPresentation(), and BaseHostDialog::initParameterWidgets().
    {
        return mUi;
    }
void BaseParametersControlWidget::valueChanged () [signal]
Referenced by BaseParametersControlWidget().
Member Data Documentation
bool BaseParametersControlWidget::autoInit [private]
Definition at line 48 of file baseParametersControlWidget.h.
Ui::BaseParametersControlWidget* BaseParametersControlWidget::mUi [private]
Definition at line 47 of file baseParametersControlWidget.h.
Referenced by BaseParametersControlWidget(), createParameters(), setParameters(), ui(), and ~BaseParametersControlWidget().
QString BaseParametersControlWidget::rootPath [private]
Definition at line 49 of file baseParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
applications/base/baseParametersControlWidget.h
applications/base/baseParametersControlWidget.cpp