DeepView: AdvancedImageWidget Class Reference
AdvancedImageWidget Class Reference
#include <advancedImageWidget.h>
Classes
struct WidgetToolButton
Tool bars.
Public Slots
virtual void childRepaint (QPaintEvent *event, QWidget *who)
void freezeImage ()
virtual void toolButtonReleased (QWidget *button)
This could be reimplemented to add additional tools.
void saveImageToFile ()
void startSaveFlow ()
void stopSaveFlow ()
virtual void childMouseMoved (QMouseEvent *)
virtual void childMousePressed (QMouseEvent *)
virtual void childMouseReleased (QMouseEvent *)
virtual void childWheelEvent (QWheelEvent *)
virtual void childResized (QResizeEvent *)
void zoomIn ()
void zoomOut ()
void zoomReset ()
void zoomChanged ()
void fitToggled ()
void setInfoString (QString info)
bool addSelectionTool (int toolID, QString name, QIcon icon)
bool addLineTool (int toolID, QString name, QIcon icon)
bool addPointTool (int toolID, QString name, QIcon icon)
void changeZoom (double zoom)
void changeCenterPoint (QPoint point)
Signals
void newAreaSelected (int toolID, QRect area)
void newPointSelected (int toolID, QPoint point)
void newLineSelected (int toolID, QLine line)
void pointToolMoved (int toolID, QPoint point)
void notifyZoomChanged (double zoom)
void notifyCenterPointChanged (QPoint point)
void askParentRepaint (QPaintEvent *event, QWidget *who)
void notifyParentMouseMove (QMouseEvent *event)
void notifyParentMousePress (QMouseEvent *event)
void notifyParentMouseRelease (QMouseEvent *event)
void notifyParentWheelEvent (QWheelEvent *event)
void notifyParentResize (QResizeEvent *event)
void notifyKeyPressEvent (QKeyEvent *event)
void notifyKeyReleaseEvent (QKeyEvent *event)
Public Member Functions
AdvancedImageWidget (QWidget *parent=0, bool showHeader=true)
void setImage (QSharedPointer< QImage > _image)
QWidget * getWidget ()
QFrame * getToolsFrame ()
void setInfoValueLabel (QString &string)
~AdvancedImageWidget ()
void setSavingRoot (const QString &root)
virtual void paintEvent (QPaintEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void loadParamWidget (WidgetLoader &)
virtual void saveParamWidget (WidgetSaver &)
Public Attributes
QSharedPointer< QImage > mImage
Protected Types
enum ToolClass {
NO_TOOL, ZOOM_SELECT_TOOL, PAN_TOOL, INFO_TOOL,
RECT_SELECTION_TOOLS, LINE_SELECTION_TOOLS, POINT_SELECTION_TOOLS, TOOL_CLASS_LAST
}
Protected Member Functions
void drawResized (QPainter &painter)
QToolButton * addToolButton (QString name, QIcon icon, bool checkable=true)
QPointF widgetToImageF (const QPointF &p)
QPointF imageToWidgetF (const QPointF &p)
QPoint widgetToImage (const QPoint &p)
QRect computeInputRect ()
void recomputeRects ()
void saveFlowImage (QImage *image)
void recalculateZoomCenter ()
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Protected Attributes
bool mIsFreezed
QIcon mFreezeIcon
QIcon mContinueIcon
bool mSaveProcStarted
unsigned int mImageNumber
QString mImageSavePath
SaveFlowSettings * mSaveDialog
Ui_advancedImageWidget * mUi
QPoint mZoomCenter
QRect mOutputRect
QRect mInputRect
bool mIsMousePressed
QPoint mSelectionStart
QPoint mSelectionEnd
QImage * mResizeCache
ToolClass mCurrentToolClass
vector< WidgetToolButton > mSelectionButtons
int mCurrentSelectionButton
vector< WidgetToolButton > mPointButtons
int mCurrentPointButton
vector< WidgetToolButton > mLineButtons
int mCurrentLineButton
QSignalMapper mToolMapper
QSize mImageSize
QString mRootPath
Detailed Description
Definition at line 23 of file advancedImageWidget.h.
Member Enumeration Documentation
enum AdvancedImageWidget::ToolClass [protected]
Enumerator:
NO_TOOL
ZOOM_SELECT_TOOL
PAN_TOOL
INFO_TOOL
RECT_SELECTION_TOOLS
LINE_SELECTION_TOOLS
POINT_SELECTION_TOOLS
TOOL_CLASS_LAST
Definition at line 112 of file advancedImageWidget.h.
                   {
        NO_TOOL,
        ZOOM_SELECT_TOOL,
        PAN_TOOL,
        INFO_TOOL,
        RECT_SELECTION_TOOLS,
        LINE_SELECTION_TOOLS,
        POINT_SELECTION_TOOLS,
        TOOL_CLASS_LAST
    };
Constructor & Destructor Documentation
AdvancedImageWidget::AdvancedImageWidget (QWidget * parent = 0, bool showHeader = true)
Definition at line 21 of file advancedImageWidget.cpp.
References ViAreaWidget::askParentRepaint(), childMouseMoved(), childMousePressed(), childMouseReleased(), childRepaint(), childResized(), childWheelEvent(), SaveFlowSettings::getUi(), mCurrentToolClass, mSaveDialog, mToolMapper, mUi, NO_TOOL, ViAreaWidget::notifyParentMouseMove(), ViAreaWidget::notifyParentMousePress(), ViAreaWidget::notifyParentMouseRelease(), ViAreaWidget::notifyParentResize(), ViAreaWidget::notifyParentWheelEvent(), startSaveFlow(), and toolButtonReleased().
                                                                        :
    ViAreaWidget(parent, false)
  , mImage(NULL)
  , mIsFreezed(false)
    /* Icons */
  , mFreezeIcon  (QString::fromUtf8(":/new/prefix1/pause.png"))
  , mContinueIcon(QString::fromUtf8(":/new/prefix1/play.png" ))
  , mSaveProcStarted(false)
  , mImageNumber(0)
  , mImageSavePath("")
  , mSaveDialog(NULL)
  , mUi(new Ui::advancedImageWidget)
  , mZoomCenter(-1,-1)
  , mIsMousePressed(false)
  , mResizeCache(NULL)
  , mCurrentToolClass(NO_TOOL)
  , mCurrentSelectionButton(0)
  , mCurrentPointButton(0)
  , mCurrentLineButton(0)
  , mImageSize(QSize())
{
    mUi->setupUi(this);
    mSaveDialog = new SaveFlowSettings();
    mSaveDialog->setAccessibleName("Save flow setting");
    mSaveDialog->setWindowTitle("Save flow setting");
    mSaveDialog->setGeometry(0, 0, 400, 400);
    mUi->fileNamelabel ->hide();
    mUi->fileValuelabel->hide();
    if (!showHeader)
    {
        mUi->frame_2->hide();
        mUi->widget_2->hide();
    }
    //mUi->widget->setCursor(Qt::OpenHandCursor);
    connect(mUi->widget, SIGNAL(askParentRepaint(QPaintEvent*,QWidget*)), this, SLOT(childRepaint(QPaintEvent*,QWidget*)));
    connect(mSaveDialog->getUi()->pushButton,SIGNAL(released()), this, SLOT(startSaveFlow()) );
    connect(mUi->widget, SIGNAL(notifyParentWheelEvent(QWheelEvent *)),   this, SLOT(childWheelEvent   (QWheelEvent *)));
    connect(mUi->widget, SIGNAL(notifyParentMouseMove(QMouseEvent *)),    this, SLOT(childMouseMoved   (QMouseEvent *)));
    connect(mUi->widget, SIGNAL(notifyParentMousePress(QMouseEvent *)),   this, SLOT(childMousePressed (QMouseEvent *)));
    connect(mUi->widget, SIGNAL(notifyParentMouseRelease(QMouseEvent *)), this, SLOT(childMouseReleased(QMouseEvent *)));
    connect(mUi->widget, SIGNAL(notifyParentResize(QResizeEvent *)),      this, SLOT(childResized      (QResizeEvent *)));
    connect(mUi->infoButton,       SIGNAL(released()), &mToolMapper, SLOT(map()));
    mToolMapper.setMapping(mUi->infoButton, mUi->infoButton);
    connect(mUi->panButton,        SIGNAL(released()), &mToolMapper, SLOT(map()));
    mToolMapper.setMapping(mUi->panButton, mUi->panButton);
    connect(mUi->selectZoomButton, SIGNAL(released()), &mToolMapper, SLOT(map()));
    mToolMapper.setMapping(mUi->selectZoomButton, mUi->selectZoomButton);
    connect(&mToolMapper, SIGNAL(mapped(QWidget *)), this, SLOT(toolButtonReleased(QWidget *)));
    mCurrentToolClass = NO_TOOL;
}
AdvancedImageWidget::~AdvancedImageWidget ()
Definition at line 81 of file advancedImageWidget.cpp.
References mResizeCache, mSaveDialog, and mUi.
{
    delete_safe(mUi);
    delete_safe(mSaveDialog);
    delete_safe(mResizeCache);
}
Member Function Documentation
bool AdvancedImageWidget::addLineTool (int toolID, QString name, QIcon icon) [slot]
Definition at line 689 of file advancedImageWidget.cpp.
References addToolButton(), and mLineButtons.
{
//    qDebug("AdvancedImageWidget::addLineTool(%d, _ , _)", toolID);
    QToolButton *toolButton = addToolButton(name, icon);
    WidgetToolButton toolRef(toolID, toolButton);
    mLineButtons.push_back(toolRef);
    return true;
}
bool AdvancedImageWidget::addPointTool (int toolID, QString name, QIcon icon) [slot]
Definition at line 699 of file advancedImageWidget.cpp.
References addToolButton(), and mPointButtons.
Referenced by TestbedMainWindow::TestbedMainWindow().
{
//    qDebug("AdvancedImageWidget::addPointTool(%d, _ , _)", toolID);
    QToolButton *toolButton = addToolButton(name, icon);
    WidgetToolButton toolRef(toolID, toolButton);
    mPointButtons.push_back(toolRef);
    return true;
}
bool AdvancedImageWidget::addSelectionTool (int toolID, QString name, QIcon icon) [slot]
Definition at line 679 of file advancedImageWidget.cpp.
References addToolButton(), and mSelectionButtons.
{
//    qDebug("AdvancedImageWidget::addSelectionTool(%d, _ , _)", toolID);
    QToolButton *toolButton = addToolButton(name, icon);
    WidgetToolButton toolRef(toolID, toolButton);
    mSelectionButtons.push_back(toolRef);
    return true;
}
QToolButton * AdvancedImageWidget::addToolButton (QString name, QIcon icon, bool checkable = true) [protected]
Definition at line 657 of file advancedImageWidget.cpp.
References getToolsFrame(), and mToolMapper.
Referenced by addLineTool(), addPointTool(), addSelectionTool(), and PaintImageWidget::PaintImageWidget().
{
    QFrame* holder = getToolsFrame();
    QToolButton *toolButton = new QToolButton();
    toolButton->setIcon(icon);
    toolButton->setText(name);
    toolButton->setToolTip(name);
    toolButton->setIconSize(QSize(24,24));
    if (checkable)
    {
        toolButton->setAutoExclusive(true);
        toolButton->setCheckable(true);
        toolButton->setAutoRaise(true);
    }
    holder->layout()->addWidget(toolButton);
    connect(toolButton, SIGNAL(released()),&mToolMapper, SLOT(map()));
    mToolMapper.setMapping(toolButton, toolButton);
    //connect(toolButton, SIGNAL(released()), this, SLOT(toolButtonReleased()));
    return toolButton;
}
void ViAreaWidget::askParentRepaint (QPaintEvent * event, QWidget * who) [signal, inherited]
Referenced by AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::paintEvent().
void AdvancedImageWidget::changeCenterPoint (QPoint point) [slot]
Definition at line 538 of file advancedImageWidget.cpp.
References mZoomCenter, notifyCenterPointChanged(), and recomputeRects().
{
    mZoomCenter = point;
    recomputeRects();
    emit notifyCenterPointChanged(mZoomCenter);
}
void AdvancedImageWidget::changeZoom (double zoom) [slot]
Definition at line 532 of file advancedImageWidget.cpp.
References mUi, and zoomChanged().
{
    mUi->expSpinBox->setValue(zoom);
    zoomChanged();
}
void AdvancedImageWidget::childMouseMoved (QMouseEvent * event) [virtual, slot]
Reimplemented in PaintImageWidget.
Definition at line 452 of file advancedImageWidget.cpp.
References info, INFO_TOOL, mCurrentPointButton, mCurrentToolClass, mImage, mIsMousePressed, mSelectionEnd, mUi, mZoomCenter, notifyCenterPointChanged(), PAN_TOOL, POINT_SELECTION_TOOLS, pointToolMoved(), recomputeRects(), setInfoValueLabel(), and widgetToImage().
Referenced by AdvancedImageWidget().
{
    if (mImage.isNull())
        return;
    QPoint imagePoint = widgetToImage(event->pos());
    if ((mCurrentToolClass == INFO_TOOL) && mImage->valid(imagePoint))
    {
        QColor color = mImage->pixel(imagePoint);
        QString info = QString("[%1 x %2] of [%3 x %4] (%5 %6 %7)")
                .arg(imagePoint.x())
                .arg(imagePoint.y())
                .arg(mImage->width())
                .arg(mImage->height())
                .arg(color.red())
                .arg(color.green())
                .arg(color.blue());
        setInfoValueLabel(info);
    }
    /* Pan */
    if (!mIsMousePressed)
        return;
    QPoint shift = (widgetToImage(mSelectionEnd) - imagePoint);
    mSelectionEnd = event->pos();
    if (mCurrentToolClass == PAN_TOOL)
    {
        mZoomCenter += shift;
        if (mZoomCenter.x() < mImage->rect().left())   mZoomCenter.setX(mImage->rect().left()  );
        if (mZoomCenter.x() > mImage->rect().right())  mZoomCenter.setX(mImage->rect().right() );
        if (mZoomCenter.y() < mImage->rect().top())    mZoomCenter.setY(mImage->rect().top()   );
        if (mZoomCenter.y() > mImage->rect().bottom()) mZoomCenter.setY(mImage->rect().bottom());
        recomputeRects();
        emit notifyCenterPointChanged(mZoomCenter);
    }
    if (mCurrentToolClass == POINT_SELECTION_TOOLS)
    {
        emit pointToolMoved(mCurrentPointButton, widgetToImage(mSelectionEnd));
    }
    /*if (mCurrentToolClass == LINE_SELECTION_TOOLS)
    {
        QLine line(widgetToImage(mSelectionStart), widgetToImage(mSelectionEnd));
        emit newLineSelected(mCurrentSelectionButton, line);
    }*/
    /* Draw tooling instruments */
    mUi->widget->update();
}
void AdvancedImageWidget::childMousePressed (QMouseEvent * event) [virtual, slot]
Reimplemented in PaintImageWidget.
Definition at line 369 of file advancedImageWidget.cpp.
References mCurrentToolClass, mIsMousePressed, mSelectionEnd, mSelectionStart, mUi, and PAN_TOOL.
Referenced by AdvancedImageWidget().
{
/*    if (!mIsMousePressed && mCurrentToolClass == LINE_SELECTION_TOOLS){
        mLineSelectionMode = true;
    }*/
    mIsMousePressed = true;
    mSelectionStart = event->pos();
    mSelectionEnd   = event->pos();
    if (mCurrentToolClass == PAN_TOOL)
    {
        mUi->widget->setCursor(Qt::ClosedHandCursor);
    }
    mUi->widget->update();
}
void AdvancedImageWidget::childMouseReleased (QMouseEvent * event) [virtual, slot]
Reimplemented in PaintImageWidget.
Definition at line 386 of file advancedImageWidget.cpp.
References LINE_SELECTION_TOOLS, mCurrentLineButton, mCurrentPointButton, mCurrentSelectionButton, mCurrentToolClass, mImage, mIsMousePressed, mSelectionEnd, mSelectionStart, mUi, mZoomCenter, newAreaSelected(), newLineSelected(), newPointSelected(), notifyCenterPointChanged(), PAN_TOOL, POINT_SELECTION_TOOLS, RECT_SELECTION_TOOLS, widgetToImage(), and ZOOM_SELECT_TOOL.
Referenced by AdvancedImageWidget().
{
    mIsMousePressed = false;
    mSelectionEnd = event->pos();
    if (mCurrentToolClass == PAN_TOOL)
    {
        mUi->widget->setCursor(Qt::OpenHandCursor);
    }
    /*All other tools depend on image*/
    if (mImage.isNull())
    {
        return;
    }
    if (mCurrentToolClass == ZOOM_SELECT_TOOL)
    {
        QRect selection(widgetToImage(mSelectionStart), widgetToImage(mSelectionEnd));
        mZoomCenter = selection.center();
        emit notifyCenterPointChanged(mZoomCenter);
        QSize outSize = selection.normalized().size();
        if (outSize.isNull())
        {
            outSize = QSize(1,1);
        }
        QSize inSize = mImage->size();
        if (inSize.isNull())
        {
            inSize = QSize(1,1);
        }
        double verticalAspect   = (double)outSize.height() / inSize.height();
        double horizontalAspect = (double)outSize.width()  / inSize.width();
        double aspect = std::min(verticalAspect, horizontalAspect);
        aspect = std::min(aspect, 1.0);
        aspect = 1.0 / aspect;
        aspect = std::max(aspect, (double)mUi->expSpinBox->minimum());
        aspect = std::min(aspect, (double)mUi->expSpinBox->maximum());
        mUi->expSpinBox->setValue((int)aspect);
    }
    if (mCurrentToolClass == RECT_SELECTION_TOOLS)
    {
        QRect selection(widgetToImage(mSelectionStart), widgetToImage(mSelectionEnd));
        qDebug("AdvancedImageWidget::mouseReleased: Emitting newAreaSelected(%d, _)", mCurrentSelectionButton);
        emit newAreaSelected(mCurrentSelectionButton, selection);
    }
    if (mCurrentToolClass == LINE_SELECTION_TOOLS)
    {
        QLine line(widgetToImage(mSelectionStart), widgetToImage(mSelectionEnd));
        emit newLineSelected(mCurrentLineButton, line);
    }
    if (mCurrentToolClass == POINT_SELECTION_TOOLS)
    {
        emit newPointSelected(mCurrentPointButton, widgetToImage(mSelectionEnd));
    }
    mUi->widget->update();
}
void AdvancedImageWidget::childRepaint (QPaintEvent * event, QWidget * who) [virtual, slot]
Reimplemented in PaintImageWidget.
Definition at line 176 of file advancedImageWidget.cpp.
References drawResized(), LINE_SELECTION_TOOLS, mCurrentToolClass, mImage, mIsMousePressed, mOutputRect, mResizeCache, mSelectionEnd, mSelectionStart, RECT_SELECTION_TOOLS, and ZOOM_SELECT_TOOL.
Referenced by AdvancedImageWidget().
{
    if (mImage == NULL)
        return;
    QPainter p(childWidget);
    if (mResizeCache != NULL)
    {
        p.drawImage(mOutputRect.topLeft(), *mResizeCache);
    }
    else
    {
        drawResized(p);
    }
    if (mIsMousePressed && (mCurrentToolClass == ZOOM_SELECT_TOOL))
    {
      p.setPen(Qt::DashLine);
      p.drawRect(QRect(mSelectionStart, mSelectionEnd));
    }
    if (mIsMousePressed && (mCurrentToolClass == RECT_SELECTION_TOOLS))
    {
      QPen pen;
      pen.setColor(Qt::red);
      pen.setStyle(Qt::DashDotLine);
      p.setPen(pen);
      p.drawRect(QRect(mSelectionStart, mSelectionEnd));
    }
    if (mIsMousePressed && (mCurrentToolClass == LINE_SELECTION_TOOLS))
    {
      QPen pen;
      pen.setColor(Qt::red);
      pen.setStyle(Qt::DashDotLine);
      p.setPen(pen);
      p.drawLine(QLine(mSelectionStart, mSelectionEnd));
      //p.drawText(mSelectionEnd, QString::number(mDistance));
    }
} // childRepaint
void AdvancedImageWidget::childResized (QResizeEvent *) [virtual, slot]
Definition at line 562 of file advancedImageWidget.cpp.
References fitToggled().
Referenced by AdvancedImageWidget().
{
   fitToggled();
   // printf("Child resize called to %d %d\n", event->size().width(), event->size().height());
}
void AdvancedImageWidget::childWheelEvent (QWheelEvent * event) [virtual, slot]
Definition at line 339 of file advancedImageWidget.cpp.
References corecvs::fround(), mUi, mZoomCenter, notifyCenterPointChanged(), recomputeRects(), widgetToImageF(), zoomIn(), and zoomOut().
Referenced by AdvancedImageWidget().
{
   // qDebug("AdvancedImageWidget::childWheelEvent() delta=%d\n", event->delta());
    QPointF scrollWidgetPoint = event->pos();
    QPointF scrollImagePoint = widgetToImageF(scrollWidgetPoint);
    if (event->delta() > 0)
    {
        for (int i = 0; i < event->delta() / 60; i++) {
            zoomIn();
        }
    }
    if (event->delta() < 0)
    {
        for (int i = 0; i < -event->delta() / 60; i++) {
            zoomOut();
        }
    }
    QPointF newScrollImagePoint = widgetToImageF(scrollWidgetPoint);
    QPointF shift = newScrollImagePoint - scrollImagePoint;
    mZoomCenter -= QPoint(fround(shift.x()), fround(shift.y()));
    recomputeRects();
    emit notifyCenterPointChanged(mZoomCenter);
    mUi->widget->update();
}
QRect AdvancedImageWidget::computeInputRect () [protected]
Definition at line 568 of file advancedImageWidget.cpp.
References mImage, mUi, and mZoomCenter.
Referenced by recomputeRects().
{
    if (mImage == NULL)
    {
        return QRect();
    }
    double zoomFactor = mUi->expSpinBox->value();
    QSize size = mImage->rect().normalized().size() / zoomFactor;
    if (size.isNull())
    {
        size = QSize(1,1);
    }
    QPoint topLeft = mZoomCenter - QPoint(size.width(), size.height()) / 2.0;
    return QRect (topLeft, size);
}
void AdvancedImageWidget::drawResized (QPainter & painter) [protected]
Definition at line 123 of file advancedImageWidget.cpp.
References mImage, mInputRect, and mOutputRect.
Referenced by childRepaint(), saveImageToFile(), and setImage().
{
    if (mImage.isNull())
    {
        painter.drawText(0,0, this->width(), this->height(), Qt::AlignHCenter | Qt::AlignVCenter, QString("NO ACTIVE IMAGE"));
        return;
    }
    // We should keep the trivial transform really trivial
    /*if (mOutputRect == mInputRect) {
        printf("Trivial transform\n");
    } else {
        qDebug() << mOutputRect << " - " << mInputRect << endl;
    }*/
    painter.drawImage(mOutputRect, *mImage, mInputRect);
}
void AdvancedImageWidget::fitToggled () [slot]
Definition at line 556 of file advancedImageWidget.cpp.
References mUi, and recomputeRects().
Referenced by childResized().
{
    recomputeRects();
    mUi->widget->update();
}
void AdvancedImageWidget::freezeImage () [slot]
Definition at line 218 of file advancedImageWidget.cpp.
References mContinueIcon, mFreezeIcon, mIsFreezed, and mUi.
{
    mIsFreezed = !mIsFreezed;
    mUi->freezeButton->setIcon( mIsFreezed ? mContinueIcon : mFreezeIcon);
}
QFrame * AdvancedImageWidget::getToolsFrame ()
Definition at line 652 of file advancedImageWidget.cpp.
References mUi.
Referenced by addToolButton().
{
    return mUi->frame;
}
QWidget * AdvancedImageWidget::getWidget ()
Definition at line 647 of file advancedImageWidget.cpp.
References mUi.
{
    return mUi->widget;
}
QPointF AdvancedImageWidget::imageToWidgetF (const QPointF & p) [protected]
Definition at line 152 of file advancedImageWidget.cpp.
References mInputRect, and mOutputRect.
Referenced by PaintImageWidget::imageToWidgetF().
{
    if (mOutputRect.height() == 0 || mInputRect.height() == 0 ||
        mInputRect.height() == 0 || mInputRect.height() == 0)
    {
        return p;
    }
    double hAspect = (double)mInputRect.height() / mOutputRect.height();
    double wAspect = (double)mInputRect.width()  / mOutputRect.width();
    double resultX = (p.x() - mInputRect.x()) / wAspect + mOutputRect.left();
    double resultY = (p.y() - mInputRect.y()) / hAspect + mOutputRect.top();
    return QPointF(resultX, resultY);
}
void ViAreaWidget::keyPressEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 53 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyPressEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyPressEvent(event);
}
void ViAreaWidget::keyReleaseEvent (QKeyEvent * event) [virtual, inherited]
Reimplemented in CloudViewDialog.
Definition at line 59 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyKeyReleaseEvent().
{
    if (!mForwardEvents) return;
    emit notifyKeyReleaseEvent(event);
}
void AdvancedImageWidget::loadFromQSettings (const QString & fileName, QString _root) [protected, virtual]
Reimplemented from SaveableWidget.
Definition at line 714 of file advancedImageWidget.cpp.
References mRootPath, mUi, and mZoomCenter.
{
    QSettings loader(fileName, QSettings::IniFormat);
    loader.beginGroup(_root + mRootPath);
    mZoomCenter.setX(loader.value("center.x", 0).toInt());
    mZoomCenter.setY(loader.value("center.y", 0).toInt());
    mUi->fitToWindowCheckBox->setChecked(loader.value("fitToWindow", false).toBool());
    mUi->aspectCheckBox     ->setChecked(loader.value("fixAspect", false).toBool());
    mUi->expSpinBox         ->setValue  (loader.value("zoom", 1.0).toDouble());
}
virtual void SaveableWidget::loadParamWidget (WidgetLoader &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 119 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::loadFromQSettings().
{}
void ViAreaWidget::mouseDoubleClickEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 35 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mouseMoveEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 16 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseMove().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
}
void ViAreaWidget::mousePressEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 22 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, ViAreaWidget::notifyParentMouseMove(), and ViAreaWidget::notifyParentMousePress().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseMove(event);
    emit notifyParentMousePress(event);
}
void ViAreaWidget::mouseReleaseEvent (QMouseEvent * event) [virtual, inherited]
Definition at line 41 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentMouseRelease().
{
    if (!mForwardEvents) return;
    emit notifyParentMouseRelease(event);
}
void AdvancedImageWidget::newAreaSelected (int toolID, QRect area) [signal]
Referenced by childMouseReleased().
void AdvancedImageWidget::newLineSelected (int toolID, QLine line) [signal]
Referenced by childMouseReleased().
void AdvancedImageWidget::newPointSelected (int toolID, QPoint point) [signal]
Referenced by childMouseReleased().
void AdvancedImageWidget::notifyCenterPointChanged (QPoint point) [signal]
Referenced by changeCenterPoint(), childMouseMoved(), childMouseReleased(), childWheelEvent(), recalculateZoomCenter(), and zoomReset().
void ViAreaWidget::notifyKeyPressEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyPressEvent().
void ViAreaWidget::notifyKeyReleaseEvent (QKeyEvent * event) [signal, inherited]
Referenced by ViAreaWidget::keyReleaseEvent().
void ViAreaWidget::notifyParentMouseMove (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), ViAreaWidget::mouseDoubleClickEvent(), ViAreaWidget::mouseMoveEvent(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMousePress (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::mousePressEvent().
void ViAreaWidget::notifyParentMouseRelease (QMouseEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), GraphPlotDialog::GraphPlotDialog(), and ViAreaWidget::mouseReleaseEvent().
void ViAreaWidget::notifyParentResize (QResizeEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::resizeEvent().
void ViAreaWidget::notifyParentWheelEvent (QWheelEvent * event) [signal, inherited]
Referenced by AdvancedImageWidget(), CloudViewDialog::CloudViewDialog(), and ViAreaWidget::wheelEvent().
void AdvancedImageWidget::notifyZoomChanged (double zoom) [signal]
Referenced by zoomChanged().
void ViAreaWidget::paintEvent (QPaintEvent * event) [virtual, inherited]
Reimplemented in ImageWidget.
Definition at line 10 of file viAreaWidget.cpp.
References ViAreaWidget::askParentRepaint(), and ViAreaWidget::mForwardEvents.
{
    if (!mForwardEvents) return;
    emit askParentRepaint(event, this);
}
void AdvancedImageWidget::pointToolMoved (int toolID, QPoint point) [signal]
Referenced by childMouseMoved().
void AdvancedImageWidget::recalculateZoomCenter () [protected]
Definition at line 634 of file advancedImageWidget.cpp.
References mImage, mZoomCenter, and notifyCenterPointChanged().
Referenced by setImage().
{
    if (mImage.isNull())
    {
        mZoomCenter = QPoint(0,0);
    }
    else
    {
        mZoomCenter = QPoint(mImage->size().width(), mImage->size().height()) / 2.0;
    }
    emit notifyCenterPointChanged(mZoomCenter);
}
void AdvancedImageWidget::recomputeRects () [protected]
Definition at line 586 of file advancedImageWidget.cpp.
References computeInputRect(), mImage, mInputRect, mOutputRect, mResizeCache, and mUi.
Referenced by changeCenterPoint(), childMouseMoved(), childWheelEvent(), fitToggled(), setImage(), zoomChanged(), and zoomReset().
{
    if (mImage == NULL)
    {
       return;
    }
    QRect output(mImage->rect().normalized());
    QRect input = computeInputRect();
    if (mUi->fitToWindowCheckBox->isChecked())
    {
        output = mUi->widget->rect().normalized();
        if (mUi->aspectCheckBox->isChecked())
        {
            double inputAspect = (double)input.height() / input.width();
            int outH = output.width() * inputAspect;
            if (outH > output.height())
                output.setWidth(output.height() / inputAspect);
            else
                output.setHeight(output.width() * inputAspect);
        }
    }
    if (!output.isValid())
        output = QRect(0,0,1,1);
    mOutputRect = output;
    mInputRect  = input;
    delete_safe(mResizeCache);
}
void ViAreaWidget::resizeEvent (QResizeEvent * event) [virtual, inherited]
Definition at line 29 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentResize().
{
    if (!mForwardEvents) return;
    emit notifyParentResize(event);
}
void AdvancedImageWidget::saveFlowImage (QImage * image) [protected]
Definition at line 620 of file advancedImageWidget.cpp.
References mImageNumber, mImageSavePath, mSaveProcStarted, and mUi.
Referenced by setImage().
{
    if(mSaveProcStarted && image)
    {
        unsigned int pathLength = mImageSavePath.size() + 10;
        char *currentPath = new char[pathLength];
        snprintf(currentPath, pathLength, mImageSavePath.toStdString().c_str(), mImageNumber);
        image->save(currentPath);
        mImageNumber++;
        mUi->fileValuelabel->setText(currentPath);
        delete []currentPath;
    }
}
void AdvancedImageWidget::saveImageToFile () [slot]
Definition at line 287 of file advancedImageWidget.cpp.
References drawResized(), mImage, mOutputRect, and mResizeCache.
{
    QString filename = QFileDialog::getSaveFileName(
            this,
            tr("Save Image"),
            "./Image.bmp",
            tr("Image Files (*.png *.jpg *.bmp)"));
    if(mImage == NULL)
    {
        return;
    }
    if (mResizeCache == NULL)
    {
        mResizeCache = new QImage(mOutputRect.size(), QImage::Format_RGB32);
        QPainter painter(mResizeCache);
        drawResized(painter);
        painter.end();
    }
    mResizeCache->save(filename);
}
virtual void SaveableWidget::saveParamWidget (WidgetSaver &) [inline, virtual, inherited]
Reimplemented in RectifyParametersControlWidget, Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, Draw3dViMouseParametersControlWidget, RgbColorParametersControlWidget, HeadSearchParametersControlWidget, BaseParametersControlWidget, PresentationParametersControlWidget, RecorderControlWidget, AxisAlignedBoxParametersControlWidget, OpenCVBMParametersControlWidget, OpenCVSGMParametersControlWidget, MakePreciseParametersControlWidget, and GraphPlotParametersControlWidget.
Definition at line 120 of file parametersControlWidgetBase.h.
Referenced by SaveableWidget::saveToQSettings().
{}
void AdvancedImageWidget::saveToQSettings (const QString & fileName, QString _root) [protected, virtual]
Reimplemented from SaveableWidget.
Definition at line 726 of file advancedImageWidget.cpp.
References mRootPath, mUi, and mZoomCenter.
{
    QSettings saver(fileName, QSettings::IniFormat);
    saver.beginGroup(_root + mRootPath);
    saver.setValue("fitToWindow", mUi->fitToWindowCheckBox->isChecked());
    saver.setValue("fixAspect"  , mUi->aspectCheckBox->isChecked());
    saver.setValue("zoom", mUi->expSpinBox->value());
    saver.setValue("center.x", mZoomCenter.x());
    saver.setValue("center.y", mZoomCenter.y());
}
void AdvancedImageWidget::setImage (QSharedPointer< QImage > _image)
Definition at line 88 of file advancedImageWidget.cpp.
References drawResized(), mImage, mImageSize, mIsFreezed, mOutputRect, mResizeCache, mSaveProcStarted, mUi, mZoomCenter, recalculateZoomCenter(), recomputeRects(), and saveFlowImage().
Referenced by DistortionWidget::updateAdditionalData(), and TestbedMainWindow::updateViewImage().
{
    if (mIsFreezed)
        return;
    if (newImage.isNull())
        return;
    mImage = newImage;
    delete_safe(mResizeCache);
    if (mSaveProcStarted)
    {
        mResizeCache = new QImage(mOutputRect.size(), QImage::Format_RGB32);
        mResizeCache->fill(0);
        QPainter cachePainter(mResizeCache);
        drawResized(cachePainter);
        cachePainter.setPen(QColor(Qt::red));
        cachePainter.drawRect(mResizeCache->rect().adjusted(0,0,-1,-1));
        cachePainter.end();
        saveFlowImage(mResizeCache);
    }
    if ((!mImage.isNull() && mImageSize != mImage->size())
            || (mZoomCenter == QPoint(-1,-1)))
    {
        mImageSize = mImage->size();
        recalculateZoomCenter();
    }
    recomputeRects();
    mUi->widget->update();
}
void AdvancedImageWidget::setInfoString (QString info) [inline, slot]
Definition at line 66 of file advancedImageWidget.h.
References mUi.
{ mUi->infoValueLabel->setText(info); }
void AdvancedImageWidget::setInfoValueLabel (QString & string)
Definition at line 709 of file advancedImageWidget.cpp.
References mUi.
Referenced by childMouseMoved().
{
    mUi->infoValueLabel->setText(infoString);
}
void AdvancedImageWidget::setSavingRoot (const QString & root) [inline]
Definition at line 166 of file advancedImageWidget.h.
References mRootPath.
Referenced by BaseHostDialog::createAdditionalWindow().
    {
        mRootPath = root;
    }
void AdvancedImageWidget::startSaveFlow () [slot]
Definition at line 311 of file advancedImageWidget.cpp.
References SaveFlowSettings::getUi(), mImageSavePath, mSaveDialog, mSaveProcStarted, and mUi.
Referenced by AdvancedImageWidget().
{
    mSaveDialog->hide();
    mSaveProcStarted = true;
    mUi->saveFlowButton->setText("Stop");
    mImageSavePath = mSaveDialog->getUi()->pathEdit->text() + "/" + mSaveDialog->getUi()->fileTemplateEdit->text();
    mUi->fileNamelabel->show();
    mUi->fileValuelabel->show();
}
void AdvancedImageWidget::stopSaveFlow () [slot]
Definition at line 321 of file advancedImageWidget.cpp.
References mImageNumber, mImageSavePath, mSaveDialog, mSaveProcStarted, and mUi.
{
    if( mSaveProcStarted )
    {
        mUi->saveFlowButton->setText("Save flow");
        mSaveProcStarted = false;
        mImageSavePath = "";
        mImageNumber = 0;
        mUi->fileNamelabel->hide();
        mUi->fileValuelabel->hide();
    }
    else
    {
        mSaveDialog->show();
    }
}
void AdvancedImageWidget::toolButtonReleased (QWidget * button) [virtual, slot]
This could be reimplemented to add additional tools.
Reimplemented in PaintImageWidget.
Definition at line 224 of file advancedImageWidget.cpp.
References INFO_TOOL, LINE_SELECTION_TOOLS, mCurrentLineButton, mCurrentPointButton, mCurrentSelectionButton, mCurrentToolClass, mLineButtons, mPointButtons, mSelectionButtons, mUi, PAN_TOOL, POINT_SELECTION_TOOLS, RECT_SELECTION_TOOLS, and ZOOM_SELECT_TOOL.
Referenced by AdvancedImageWidget().
{
    if (mUi->panButton->isChecked())
    {
        mCurrentToolClass = PAN_TOOL;
        mUi->widget->setCursor(Qt::OpenHandCursor);
        return;
    }
    if (mUi->selectZoomButton->isChecked())
    {
        mCurrentToolClass = ZOOM_SELECT_TOOL;
        mUi->widget->setCursor(Qt::ArrowCursor);
        return;
    }
    if (mUi->infoButton->isChecked()) {
        mCurrentToolClass = INFO_TOOL;
        mUi->widget->setCursor(Qt::CrossCursor);
        return;
    }
    mUi->widget->setMouseTracking(mCurrentToolClass == INFO_TOOL);
    for (int i = 0; i < (int)mSelectionButtons.size(); i++)
    {
        QToolButton *button = mSelectionButtons.at(i).button;
        if (!button->isChecked())
            continue;
        mUi->widget->setCursor(Qt::ArrowCursor);
        mCurrentSelectionButton = mSelectionButtons.at(i).id;
        mCurrentToolClass = RECT_SELECTION_TOOLS;
        return;
    }
    for (int i = 0; i < (int)mPointButtons.size(); i++)
    {
        QToolButton *button = mPointButtons.at(i).button;
        if (!button->isChecked())
          continue;
        mCurrentToolClass = POINT_SELECTION_TOOLS;
        mUi->widget->setCursor(Qt::CrossCursor);
        mCurrentPointButton = mPointButtons.at(i).id;
        return;
    }
    for (int i = 0; i < (int)mLineButtons.size(); i++)
    {
       QToolButton *button = mLineButtons.at(i).button;
       if (!button->isChecked())
           continue;
       mCurrentToolClass = LINE_SELECTION_TOOLS;
       mUi->widget->setCursor(Qt::CrossCursor);
       mCurrentLineButton = mLineButtons.at(i).id;
       return;
    }
    //printf("tools [%c%c%c%c]\n", isInSelectArea ? 'X' : 'O', isInPan ? 'X' : 'O', isInSelectZoom ? 'X' : 'O', isInInfo ? 'X' : 'O');
}
void ViAreaWidget::wheelEvent (QWheelEvent * event) [virtual, inherited]
Definition at line 47 of file viAreaWidget.cpp.
References ViAreaWidget::mForwardEvents, and ViAreaWidget::notifyParentWheelEvent().
{
    if (!mForwardEvents) return;
    emit notifyParentWheelEvent(event);
}
QPoint AdvancedImageWidget::widgetToImage (const QPoint & p) [protected]
Definition at line 169 of file advancedImageWidget.cpp.
References corecvs::fround(), and widgetToImageF().
Referenced by childMouseMoved(), and childMouseReleased().
{
    QPointF out = widgetToImageF(p);
    return QPoint(fround(out.x()), fround(out.y()));
}
QPointF AdvancedImageWidget::widgetToImageF (const QPointF & p) [protected]
Definition at line 141 of file advancedImageWidget.cpp.
References mInputRect, and mOutputRect.
Referenced by childWheelEvent(), widgetToImage(), and PaintImageWidget::widgetToImageF().
{
    double hAspect = (double)mInputRect.height() / mOutputRect.height();
    double wAspect = (double)mInputRect.width()  / mOutputRect.width();
    double x = (p.x() - mOutputRect.left()) * wAspect + mInputRect.x();
    double y = (p.y() - mOutputRect.top())  * hAspect + mInputRect.y();
    return QPointF(x,y);
}
void AdvancedImageWidget::zoomChanged () [slot]
Definition at line 523 of file advancedImageWidget.cpp.
References mUi, notifyZoomChanged(), and recomputeRects().
Referenced by changeZoom().
{
    mUi->zoomInButton ->setEnabled(mUi->expSpinBox->value() != mUi->expSpinBox->maximum());
    mUi->zoomOutButton->setEnabled(mUi->expSpinBox->value() != mUi->expSpinBox->minimum());
    recomputeRects();
    emit notifyZoomChanged(mUi->expSpinBox->value());
    mUi->widget->update();
}
void AdvancedImageWidget::zoomIn () [slot]
Definition at line 546 of file advancedImageWidget.cpp.
References mUi.
Referenced by childWheelEvent().
{
    mUi->expSpinBox->stepUp();
}
void AdvancedImageWidget::zoomOut () [slot]
Definition at line 551 of file advancedImageWidget.cpp.
References mUi.
Referenced by childWheelEvent().
{
    mUi->expSpinBox->stepDown();
}
void AdvancedImageWidget::zoomReset () [slot]
Definition at line 508 of file advancedImageWidget.cpp.
References mImage, mUi, mZoomCenter, notifyCenterPointChanged(), and recomputeRects().
{
    if (mImage == NULL) {
        mZoomCenter = QPoint(-1,-1);
    }
    else
    {
        mZoomCenter = QPoint(mImage->size().width(), mImage->size().height()) / 2.0;
    }
    mUi->expSpinBox->setValue(1.0);
    recomputeRects();
    emit notifyCenterPointChanged(mZoomCenter);
    mUi->widget->update();
}
Member Data Documentation
QIcon AdvancedImageWidget::mContinueIcon [protected]
Definition at line 92 of file advancedImageWidget.h.
Referenced by freezeImage().
int AdvancedImageWidget::mCurrentLineButton [protected]
Definition at line 143 of file advancedImageWidget.h.
Referenced by childMouseReleased(), and toolButtonReleased().
int AdvancedImageWidget::mCurrentPointButton [protected]
Definition at line 141 of file advancedImageWidget.h.
Referenced by childMouseMoved(), childMouseReleased(), and toolButtonReleased().
int AdvancedImageWidget::mCurrentSelectionButton [protected]
Definition at line 139 of file advancedImageWidget.h.
Referenced by childMouseReleased(), and toolButtonReleased().
ToolClass AdvancedImageWidget::mCurrentToolClass [protected]
Definition at line 125 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget(), PaintImageWidget::childMouseMoved(), childMouseMoved(), PaintImageWidget::childMousePressed(), childMousePressed(), childMouseReleased(), childRepaint(), toolButtonReleased(), and PaintImageWidget::toolButtonReleased().
QIcon AdvancedImageWidget::mFreezeIcon [protected]
Definition at line 91 of file advancedImageWidget.h.
Referenced by freezeImage().
QSharedPointer<QImage> AdvancedImageWidget::mImage
Definition at line 28 of file advancedImageWidget.h.
Referenced by childMouseMoved(), childMouseReleased(), childRepaint(), PaintImageWidget::childRepaint(), computeInputRect(), drawResized(), recalculateZoomCenter(), recomputeRects(), saveImageToFile(), setImage(), and zoomReset().
unsigned int AdvancedImageWidget::mImageNumber [protected]
Definition at line 95 of file advancedImageWidget.h.
Referenced by saveFlowImage(), and stopSaveFlow().
QString AdvancedImageWidget::mImageSavePath [protected]
Definition at line 96 of file advancedImageWidget.h.
Referenced by saveFlowImage(), startSaveFlow(), and stopSaveFlow().
QSize AdvancedImageWidget::mImageSize [protected]
Definition at line 153 of file advancedImageWidget.h.
Referenced by setImage().
QRect AdvancedImageWidget::mInputRect [protected]
Definition at line 103 of file advancedImageWidget.h.
Referenced by drawResized(), imageToWidgetF(), recomputeRects(), and widgetToImageF().
bool AdvancedImageWidget::mIsFreezed [protected]
Definition at line 90 of file advancedImageWidget.h.
Referenced by freezeImage(), and setImage().
bool AdvancedImageWidget::mIsMousePressed [protected]
Definition at line 106 of file advancedImageWidget.h.
Referenced by childMouseMoved(), PaintImageWidget::childMouseMoved(), childMousePressed(), childMouseReleased(), and childRepaint().
vector<WidgetToolButton> AdvancedImageWidget::mLineButtons [protected]
Definition at line 142 of file advancedImageWidget.h.
Referenced by addLineTool(), and toolButtonReleased().
QRect AdvancedImageWidget::mOutputRect [protected]
Definition at line 102 of file advancedImageWidget.h.
Referenced by childRepaint(), drawResized(), imageToWidgetF(), recomputeRects(), saveImageToFile(), setImage(), and widgetToImageF().
vector<WidgetToolButton> AdvancedImageWidget::mPointButtons [protected]
Definition at line 140 of file advancedImageWidget.h.
Referenced by addPointTool(), and toolButtonReleased().
QImage* AdvancedImageWidget::mResizeCache [protected]
Definition at line 110 of file advancedImageWidget.h.
Referenced by childRepaint(), recomputeRects(), saveImageToFile(), setImage(), and ~AdvancedImageWidget().
QString AdvancedImageWidget::mRootPath [protected]
Definition at line 161 of file advancedImageWidget.h.
Referenced by loadFromQSettings(), saveToQSettings(), and setSavingRoot().
SaveFlowSettings* AdvancedImageWidget::mSaveDialog [protected]
Definition at line 97 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget(), startSaveFlow(), stopSaveFlow(), and ~AdvancedImageWidget().
bool AdvancedImageWidget::mSaveProcStarted [protected]
Definition at line 94 of file advancedImageWidget.h.
Referenced by saveFlowImage(), setImage(), startSaveFlow(), and stopSaveFlow().
vector<WidgetToolButton> AdvancedImageWidget::mSelectionButtons [protected]
Definition at line 138 of file advancedImageWidget.h.
Referenced by addSelectionTool(), and toolButtonReleased().
QPoint AdvancedImageWidget::mSelectionEnd [protected]
Definition at line 108 of file advancedImageWidget.h.
Referenced by childMouseMoved(), PaintImageWidget::childMouseMoved(), childMousePressed(), childMouseReleased(), and childRepaint().
QPoint AdvancedImageWidget::mSelectionStart [protected]
Definition at line 107 of file advancedImageWidget.h.
Referenced by childMousePressed(), childMouseReleased(), and childRepaint().
QSignalMapper AdvancedImageWidget::mToolMapper [protected]
Definition at line 145 of file advancedImageWidget.h.
Referenced by addToolButton(), and AdvancedImageWidget().
Ui_advancedImageWidget* AdvancedImageWidget::mUi [protected]
Definition at line 98 of file advancedImageWidget.h.
Referenced by AdvancedImageWidget(), changeZoom(), childMouseMoved(), PaintImageWidget::childMouseMoved(), childMousePressed(), PaintImageWidget::childMousePressed(), childMouseReleased(), childWheelEvent(), PaintImageWidget::clickToolButton(), computeInputRect(), PaintImageWidget::deleteVertex(), fitToggled(), freezeImage(), getToolsFrame(), getWidget(), loadFromQSettings(), recomputeRects(), saveFlowImage(), saveToQSettings(), setImage(), setInfoString(), setInfoValueLabel(), startSaveFlow(), stopSaveFlow(), toolButtonReleased(), PaintImageWidget::toolButtonReleased(), zoomChanged(), zoomIn(), zoomOut(), zoomReset(), and ~AdvancedImageWidget().
QPoint AdvancedImageWidget::mZoomCenter [protected]
Definition at line 100 of file advancedImageWidget.h.
Referenced by changeCenterPoint(), childMouseMoved(), childMouseReleased(), childWheelEvent(), computeInputRect(), loadFromQSettings(), recalculateZoomCenter(), saveToQSettings(), setImage(), and zoomReset().
The documentation for this class was generated from the following files:
utils/uis/advancedImageWidget.h
utils/uis/advancedImageWidget.cpp