DeepView: corecvs::HomographyReconstructor Class Reference
corecvs::HomographyReconstructor Class Reference
#include <homographyReconstructor.h>
Classes
class CostFunction
class CostFunctionWize
Public Member Functions
HomographyReconstructor ()
void addPoint2PointConstraint (const Vector2dd &from, const Vector2dd &to)
void addPoint2LineConstraint (const Vector2dd &from, const Line2d &line)
void addPoint2SegmentConstraint (const Vector2dd &from, const Segment2d &line)
void reset (void)
bool hasEnoughtConstraints ()
double getCostFunction (Matrix33 &input)
This function computes the classical Euklidian cost.
Matrix33 getBestHomography (int method)
Matrix33 getBestHomographyLSE (void)
Matrix33 getBestHomographyLSE1 (void)
Actual computation.
Matrix33 getBestHomographyLSE2 (void)
Matrix33 getBestHomographyClassicKalman (void)
This block is devoted to Kalman reconstruction.
Matrix33 getBestHomographyFastKalman (void)
Matrix33 getBestHomographyLM (Matrix33 guess=Matrix33(1.0))
This block is devoted to LM reconstruction.
void noramlisePoints (Matrix33 &transformLeft, Matrix33 &transformRight)
TODO: This function doubles the code form rectificator.cpp.
virtual ~HomographyReconstructor ()
Public Attributes
vector< Correspondance > p2p
vector< CorrespondancePointLine > p2l
vector
< CorrespondancePointSegment > p2s
Private Member Functions
void addPoint2PointConstraintLSE (Matrix &A, Matrix &B, int num, const Vector2dd &from, const Vector2dd &to)
This block is devoted to LSE optimization.
void addPoint2LineConstraintLSE (Matrix &A, Matrix &B, int num, const Vector2dd &from, const Line2d &line)
Matrix is searched in form.
void addPoint2LineConstraintLSEUnif (Matrix &A, int num, const Vector2dd &from, const Line2d &line)
void addPoint2PointConstraintLSEUnif (Matrix &A, int num, const Vector2dd &from, const Vector2dd &to)
Friends
ostream & operator<< (ostream &out, const HomographyReconstructor &reconstructor)
Detailed Description
Definition at line 28 of file homographyReconstructor.h.
Constructor & Destructor Documentation
corecvs::HomographyReconstructor::HomographyReconstructor ()
Definition at line 19 of file homographyReconstructor.cpp.
{
}
corecvs::HomographyReconstructor::~HomographyReconstructor () [virtual]
Definition at line 73 of file homographyReconstructor.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
void corecvs::HomographyReconstructor::addPoint2LineConstraint (const Vector2dd & from, const Line2d & line)
Definition at line 28 of file homographyReconstructor.cpp.
References p2l.
{
    p2l.push_back(CorrespondancePointLine(from, line));
}
void corecvs::HomographyReconstructor::addPoint2LineConstraintLSE (Matrix & A, Matrix & B, int num, const Vector2dd & from, const Line2d & line) [private]
Matrix is searched in form.
We have a point and a line
The matrix will transform the point to the
So we have minimize
We will rewrite it as:
Definition at line 284 of file homographyReconstructor.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs(), corecvs::Line2d::normalised(), corecvs::Vector2d< ElementType >::x(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector2d< ElementType >::y(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by getBestHomographyLSE(), and getBestHomographyLSE1().
{
    Line2d l = line.normalised();
    double lx =  l.x();
    double ly =  l.y();
    double lz =  l.z();
    double fx = from.x();
    double fy = from.y();
    A.fillLineWithArgs(num,
            lx * fx, lx * fy, lx,
            ly * fx, ly * fy, ly,
            lz * fx, lz * fy);
    B.fillLineWithArgs(num, -lz);
}
void corecvs::HomographyReconstructor::addPoint2LineConstraintLSEUnif (Matrix & A, int num, const Vector2dd & from, const Line2d & line) [private]
Definition at line 305 of file homographyReconstructor.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs(), corecvs::Line2d::normalised(), corecvs::Vector2d< ElementType >::x(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector2d< ElementType >::y(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by getBestHomographyLSE2().
{
    Line2d l = line.normalised();
    double lx =  l.x();
    double ly =  l.y();
    double lz =  l.z();
    double fx = from.x();
    double fy = from.y();
    A.fillLineWithArgs(num,
            lx * fx, lx * fy, lx,
            ly * fx, ly * fy, ly,
            lz * fx, lz * fy, lz);
}
void corecvs::HomographyReconstructor::addPoint2PointConstraint (const Vector2dd & from, const Vector2dd & to)
Definition at line 23 of file homographyReconstructor.cpp.
References p2p.
{
    p2p.push_back(Correspondance(from,to));
}
void corecvs::HomographyReconstructor::addPoint2PointConstraintLSE (Matrix & A, Matrix & B, int num, const Vector2dd & from, const Vector2dd & to) [private]
This block is devoted to LSE optimization.
Calculate the Matrix that transform given points to given images This is done almost the same way as in rectification Rectificator::getFundamantalRansac() using the SVD
Matrix is searched in form
Definition at line 202 of file homographyReconstructor.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by getBestHomographyLSE(), and getBestHomographyLSE1().
{
   double fx = from.x();
   double fy = from.y();
   double tx =   to.x();
   double ty =   to.y();
   A.fillLineWithArgs(num    , fx,  fy, 1.0, 0.0, 0.0, 0.0, -fx * tx, -fy * tx);
   B.fillLineWithArgs(num    , tx);
   A.fillLineWithArgs(num + 1, 0.0, 0.0, 0.0,  fx,  fy, 1.0, -fx * ty, -fy * ty);
   B.fillLineWithArgs(num + 1, ty);
}
void corecvs::HomographyReconstructor::addPoint2PointConstraintLSEUnif (Matrix & A, int num, const Vector2dd & from, const Vector2dd & to) [private]
Definition at line 220 of file homographyReconstructor.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::fillLineWithArgs(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by getBestHomographyLSE2().
{
   double fx = from.x();
   double fy = from.y();
   double tx =   to.x();
   double ty =   to.y();
   A.fillLineWithArgs(num    ,  fx,  fy, 1.0, 0.0, 0.0, 0.0, -fx * tx, -fy * tx, -tx);
   A.fillLineWithArgs(num + 1, 0.0, 0.0, 0.0,  fx,  fy, 1.0, -fx * ty, -fy * ty, -ty);
}
void corecvs::HomographyReconstructor::addPoint2SegmentConstraint (const Vector2dd & from, const Segment2d & line)
Definition at line 33 of file homographyReconstructor.cpp.
References p2s.
{
    p2s.push_back(CorrespondancePointSegment(from, seg));
}
Matrix33 corecvs::HomographyReconstructor::getBestHomography (int method)
Matrix33 corecvs::HomographyReconstructor::getBestHomographyClassicKalman (void)
This block is devoted to Kalman reconstruction.
Definition at line 542 of file homographyReconstructor.cpp.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element, corecvs::ClassicKalman::predict(), corecvs::ClassicKalman::update(), corecvs::ClassicKalman::x, and corecvs::ClassicKalman::z.
{
    CostFunction F(this);
    IdentityFunction H(1);
    // We know almost nothing about the homography matrix
    Matrix P(8,8, 1000.0);
    // Our model evolution is precise
    Matrix Q(8,8, 0.0);
    // Our measurement is precise up to 2px.
    Matrix R(1,1, 2.0 * 8.0);
    Matrix33 ident(1.0);
    Vector x(8, ident.element);
    ClassicKalman kalmanFilter(
        &F,
        &H,
        Q,
        R,
        P,
        x);
    for (int step = 0; step < 250; step++)
    {
        double measurement = 0.0;
        kalmanFilter.predict();
        kalmanFilter.z[0] = measurement;
        kalmanFilter.update();
    }
    return Matrix33(
            kalmanFilter.x[0], kalmanFilter.x[1], kalmanFilter.x[2],
            kalmanFilter.x[3], kalmanFilter.x[4], kalmanFilter.x[5],
            kalmanFilter.x[6], kalmanFilter.x[7], 1.0
    );
}
Matrix33 corecvs::HomographyReconstructor::getBestHomographyFastKalman (void)
Matrix33 corecvs::HomographyReconstructor::getBestHomographyLM (Matrix33 guess = Matrix33(1.0))
This block is devoted to LM reconstruction.
Definition at line 586 of file homographyReconstructor.cpp.
References corecvs::LevenbergMarquardt::f, corecvs::LevenbergMarquardt::fit(), and corecvs::LevenbergMarquardt::maxIterations.
{
    CostFunction F(this);
    LevenbergMarquardt LMfit;
    LMfit.f = &F;
    LMfit.maxIterations = 25;
    vector<double> input(8);
    input[0] = 1.0; input[1] = 0.0; input[2] = 0.0;
    input[3] = 0.0; input[4] = 1.0; input[5] = 0.0;
    input[6] = 0.0; input[7] = 0.0;
    vector<double> output(1);
    output[0] = 0.0;
    vector<double> optInput = LMfit.fit(input, output);
    return Matrix33(
            optInput[0], optInput[1], optInput[2],
            optInput[3], optInput[4], optInput[5],
            optInput[6], optInput[7], 1.0
       );
}
Matrix33 corecvs::HomographyReconstructor::getBestHomographyLSE (void)
Definition at line 365 of file homographyReconstructor.cpp.
References corecvs::Matrix::a(), addPoint2LineConstraintLSE(), addPoint2PointConstraintLSE(), corecvs::Matrix::frobeniusNorm(), p2l, p2p, corecvs::Matrix::svd(), and corecvs::Matrix::t().
{
    int problemSize = (int)(p2l.size() + p2p.size() * 2);
    Matrix mX(problemSize ,8);
    Matrix mB(problemSize ,1);
    int lineNum = 0;
    for (unsigned i = 0; i < p2p.size(); i++)
    {
        addPoint2PointConstraintLSE(mX, mB, lineNum, p2p[i].start, p2p[i].end);
        lineNum += 2;
    }
    for (unsigned i = 0; i < p2l.size(); i++)
    {
        addPoint2LineConstraintLSE(mX, mB, lineNum, p2l[i].start, p2l[i].end);
        lineNum += 1;
    }
    cout << "X" << endl << mX << endl;
    cout << "B" << endl << mB << endl;
    Matrix U(mX);
    Matrix W(1, 8);
    Matrix VT(8, 8);
    Matrix::svd (&U, &W, &VT);
    Matrix UT = U.t();
    Matrix UtB = UT * mB;
    Matrix UtB8(8,1);
    for (int i = 0; i < 8; i++)
    {
       // if (W.a(0,i) > 1e-6)
            UtB8.a(i,0) = UtB.a(i,0) / W.a(0,i);
       // else
       //     UtB8.a(i,0) = 0.0;
    }
    Matrix result = VT * UtB8;
    Matrix test = mX * result - mB;
    cout << "Residual:" << test.frobeniusNorm() << endl;
    Matrix33 toReturn(
        result.a(0,0), result.a(1,0), result.a(2,0),
        result.a(3,0), result.a(4,0), result.a(5,0),
        result.a(6,0), result.a(7,0), 1.0
    );
    return toReturn;
}
Matrix33 corecvs::HomographyReconstructor::getBestHomographyLSE1 (void)
Actual computation.
Definition at line 327 of file homographyReconstructor.cpp.
References corecvs::Matrix::a(), addPoint2LineConstraintLSE(), addPoint2PointConstraintLSE(), corecvs::Matrix::frobeniusNorm(), corecvs::Matrix::invSVD(), p2l, p2p, and corecvs::Matrix::t().
{
    int problemSize = (int)(p2l.size() + p2p.size() * 2);
    Matrix mX(problemSize, 8);
    Matrix mB(problemSize, 1);
    int lineNum = 0;
    for (unsigned i = 0; i < p2p.size(); i++)
    {
        addPoint2PointConstraintLSE(mX, mB, lineNum, p2p[i].start, p2p[i].end);
        lineNum += 2;
    }
    for (unsigned i = 0; i < p2l.size(); i++)
    {
        addPoint2LineConstraintLSE(mX, mB, lineNum, p2l[i].start, p2l[i].end);
        lineNum += 1;
    }
    cout << "X" << endl << mX << endl;
    cout << "B" << endl << mB << endl;
    Matrix mXTX = mX.t() * mX;
    Matrix mXTB = mX.t() * mB;
    Matrix result = mXTX.invSVD() * mXTB;
    Matrix test = mX * result - mB;
    cout << "Residual:" << test.frobeniusNorm() << endl;
    Matrix33 toReturn(
        result.a(0,0), result.a(1,0), result.a(2,0),
        result.a(3,0), result.a(4,0), result.a(5,0),
        result.a(6,0), result.a(7,0), 1.0
    );
    return toReturn;
}
Matrix33 corecvs::HomographyReconstructor::getBestHomographyLSE2 (void)
Definition at line 418 of file homographyReconstructor.cpp.
References corecvs::Matrix::a(), addPoint2LineConstraintLSEUnif(), addPoint2PointConstraintLSEUnif(), corecvs::Matrix::frobeniusNorm(), p2l, p2p, and corecvs::Matrix::svd().
{
    int problemSize = (int)(p2l.size() + p2p.size() * 2);
    Matrix mX(problemSize ,9);
    int lineNum = 0;
    for (unsigned i = 0; i < p2p.size(); i++)
    {
        addPoint2PointConstraintLSEUnif(mX, lineNum, p2p[i].start, p2p[i].end);
        lineNum += 2;
    }
    for (unsigned i = 0; i < p2l.size(); i++)
    {
        addPoint2LineConstraintLSEUnif(mX, lineNum, p2l[i].start, p2l[i].end);
        lineNum += 1;
    }
    cout << "X" << endl << mX << endl;
    Matrix U(mX);
    Matrix W(1, 9);
    Matrix VT(9, 9);
    Matrix::svd(&U, &W, &VT);
    cout << "Singualar Values" << endl << W << endl;
    int minId = -1;
    double minval = std::numeric_limits<double>::max();
    for (unsigned i = 0; i < 9; i ++)
    {
       if (W.a(0, i) <= minval)
       {
           minId = i;
           minval = W.a(0, i);
       }
    }
    Matrix33 toReturn(
        VT.a(0,minId), VT.a(1,minId), VT.a(2,minId),
        VT.a(3,minId), VT.a(4,minId), VT.a(5,minId),
        VT.a(6,minId), VT.a(7,minId), VT.a(8,minId)
    );
    toReturn /= VT.a(8,minId);
    Matrix result(9, 1, toReturn.element);
    Matrix test = mX * result;
    cout << "Result" << endl << test << endl;
    cout << "Residual:" << test.frobeniusNorm() << endl;
    return toReturn;
}
double corecvs::HomographyReconstructor::getCostFunction (Matrix33 & input)
This function computes the classical Euklidian cost.
Definition at line 477 of file homographyReconstructor.cpp.
References p2l, and p2p.
Referenced by corecvs::HomographyReconstructor::CostFunction::operator()().
{
    double cost = 0.0;
    for (unsigned i = 0; i < p2p.size(); i++)
    {
        Vector2dd point = (H * p2p[i].start);
        cost += (point - p2p[i].end).sumAllElementsSq();
    }
    for (unsigned i = 0; i < p2l.size(); i++)
    {
        Vector2dd point = H * p2l[i].start;
        double distanceSq = p2l[i].end.sqDistanceTo(point);
        cost += distanceSq;
    }
    return cost;
}
bool corecvs::HomographyReconstructor::hasEnoughtConstraints ()
Definition at line 38 of file homographyReconstructor.cpp.
References p2l, p2p, and p2s.
{
    size_t constraintSize  = p2l.size() + p2s.size() + p2p.size() * 2;
    return (constraintSize >= 8);
}
void corecvs::HomographyReconstructor::noramlisePoints (Matrix33 & transformLeft, Matrix33 & transformRight)
TODO: This function doubles the code form rectificator.cpp.
Definition at line 82 of file homographyReconstructor.cpp.
References corecvs::Matrix33::inv(), p2l, p2p, p2s, corecvs::Matrix33::ScaleProj(), corecvs::Matrix33::ShiftProj(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    Vector2dd lmean(0.0);
    Vector2dd lmeansq(0.0);
    Vector2dd rmean(0.0);
    Vector2dd rmeansq(0.0);
    int lcount = 0;
    int rcount = 0;
    for (unsigned  i = 0; i < p2p.size(); i++)
    {
        lmean += p2p[i].start;
        lmeansq += (p2p[i].start) * (p2p[i].start);
        rmean += p2p[i].end;
        rmeansq += (p2p[i].end) * (p2p[i].end);
        lcount++;
        rcount++;
    }
    for (unsigned  i = 0; i < p2l.size(); i++)
    {
        lmean += p2l[i].start;
        lmeansq += (p2l[i].start) * (p2l[i].start);
        lcount++;
    }
    for (unsigned  i = 0; i < p2s.size(); i++)
    {
        lmean += p2s[i].start;
        lmeansq += (p2s[i].start) * (p2s[i].start);
        lcount++;
        Vector2dd segCenter = p2s[i].end.getCenter();
        rmean += segCenter;
        rmeansq += segCenter * segCenter;
        rcount++;
    }
    lmean /= lcount;
    lmeansq  /= lcount;
    rmean  /= rcount;
    rmeansq  /= rcount;
    Vector2dd lsqmean = lmean * lmean;
    Vector2dd rsqmean = rmean * rmean;
    double lscaler = sqrt (lmeansq.x() - lsqmean.x()  + lmeansq.y() - lsqmean.y());
    double rscaler = sqrt (rmeansq.x() - rsqmean.x()  + rmeansq.y() - rsqmean.y());
    transformLeft     = Matrix33::ScaleProj(sqrt(2.0) / lscaler) * Matrix33::ShiftProj(-lmean);
    transformRight    = Matrix33::ScaleProj(sqrt(2.0) / rscaler) * Matrix33::ShiftProj(-rmean);
    //Matrix33 transformRightInv = Matrix33::ShiftProj(rmean) * Matrix33::ScaleProj(rscaler / sqrt(2.0));
    for (unsigned  i = 0; i < p2p.size(); i++)
    {
       p2p[i].start = transformLeft  * p2p[i].start;
       p2p[i].end   = transformRight * p2p[i].end;
    }
    for (unsigned  i = 0; i < p2l.size(); i++)
    {
       p2l[i].start = transformLeft  * p2l[i].start;
       Vector3dd line = p2l[i].end;
       line = line * transformRight.inv();
       p2l[i].end = Line2d(line[0], line[1], line[2]);
       p2l[i].end.normalise();
    }
    for (unsigned  i = 0; i < p2s.size(); i++)
    {
        p2s[i].start = transformLeft  * p2s[i].start;
        p2s[i].end.a = transformRight * p2s[i].end.a;
        p2s[i].end.b = transformRight * p2s[i].end.b;
    }
}
void corecvs::HomographyReconstructor::reset (void)
Definition at line 46 of file homographyReconstructor.cpp.
References p2l, p2p, and p2s.
{
   p2p.clear();
   p2l.clear();
   p2s.clear();
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, const HomographyReconstructor & reconstructor) [friend]
Definition at line 53 of file homographyReconstructor.cpp.
{
    streamsize wasPrecision = out.precision(6);
    out << "// Points2Points " << endl;
    out << reconstructor.p2p.size() << endl;
    for (unsigned i = 0; i < reconstructor.p2p.size(); i++)
    {
        out << reconstructor.p2p[i].start << " " << reconstructor.p2p[i].end  << endl;
    }
    out << "// Points2Line " << endl;
    out << reconstructor.p2l.size() << endl;
    for (unsigned i = 0; i < reconstructor.p2l.size(); i++)
    {
        out << reconstructor.p2l[i].start << " " << reconstructor.p2l[i].end  << endl;
    }
    out.precision(wasPrecision);
    return out;
}
Member Data Documentation
vector<CorrespondancePointLine> corecvs::HomographyReconstructor::p2l
Definition at line 32 of file homographyReconstructor.h.
Referenced by addPoint2LineConstraint(), getBestHomographyLSE(), getBestHomographyLSE1(), getBestHomographyLSE2(), getCostFunction(), hasEnoughtConstraints(), noramlisePoints(), corecvs::operator<<(), and reset().
vector<Correspondance> corecvs::HomographyReconstructor::p2p
Definition at line 31 of file homographyReconstructor.h.
Referenced by addPoint2PointConstraint(), getBestHomographyLSE(), getBestHomographyLSE1(), getBestHomographyLSE2(), getCostFunction(), hasEnoughtConstraints(), noramlisePoints(), corecvs::operator<<(), and reset().
vector<CorrespondancePointSegment> corecvs::HomographyReconstructor::p2s
Definition at line 33 of file homographyReconstructor.h.
Referenced by addPoint2SegmentConstraint(), hasEnoughtConstraints(), noramlisePoints(), and reset().
The documentation for this class was generated from the following files:
core/math/matrix/homographyReconstructor.h
core/math/matrix/homographyReconstructor.cpp