DeepView: corecvs::Element6D Class Reference
corecvs::Element6D Class Reference
This class holds fully or partially reconstructed 6D point at disparity level.
#include <element6D.h>
Public Member Functions
Element6D ()
Element6D (Vector2d16 const &flowValue, int32_t const dispValue, int32_t const dispPrevValue)
bool hasFlow () const
bool hasDisp () const
bool hasPrevDisp () const
bool is5D () const
bool is6D () const
Public Attributes
Vector2dd floatFlow
Vector2d16 flow
int32_t disp
int32_t dispPrev
Static Public Attributes
static const int CFLOW_UNKNOWN_X = INT16_MAX
Constants that denote unknown values.
static const int CFLOW_UNKNOWN_Y = INT16_MAX
Detailed Description
This class holds fully or partially reconstructed 6D point at disparity level.
Definition at line 19 of file element6D.h.
Constructor & Destructor Documentation
corecvs::Element6D::Element6D () [inline]
Definition at line 23 of file element6D.h.
        : flow(Element6D::CFLOW_UNKNOWN_X, Element6D::CFLOW_UNKNOWN_Y)
        , disp(Element6D::CFLOW_UNKNOWN_X)
        , dispPrev(Element6D::CFLOW_UNKNOWN_X)
    {
    }
corecvs::Element6D::Element6D (Vector2d16 const & flowValue, int32_t const dispValue, int32_t const dispPrevValue) [inline]
Definition at line 30 of file element6D.h.
        : flow(flowValue)
        , disp(dispValue)
        , dispPrev(dispPrevValue)
    {
    }
Member Function Documentation
bool corecvs::Element6D::hasDisp () const [inline]
Definition at line 52 of file element6D.h.
References CFLOW_UNKNOWN_X, and disp.
Referenced by is5D(), and corecvs::Triangulator::triangulate().
    {
        return (disp  != (int) Element6D::CFLOW_UNKNOWN_X);
    }
bool corecvs::Element6D::hasFlow () const [inline]
Definition at line 45 of file element6D.h.
References CFLOW_UNKNOWN_X, CFLOW_UNKNOWN_Y, flow, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by is5D(), and corecvs::Triangulator::triangulate().
    {
        return
            (flow.x() != (int) Element6D::CFLOW_UNKNOWN_X) &&
            (flow.y() != (int) Element6D::CFLOW_UNKNOWN_Y);
    }
bool corecvs::Element6D::hasPrevDisp () const [inline]
Definition at line 57 of file element6D.h.
References CFLOW_UNKNOWN_X, and dispPrev.
Referenced by is6D(), and corecvs::Triangulator::triangulate().
    {
        return (dispPrev  != (int) Element6D::CFLOW_UNKNOWN_X);
    }
bool corecvs::Element6D::is5D () const [inline]
Definition at line 62 of file element6D.h.
References hasDisp(), and hasFlow().
Referenced by is6D().
    {
        return hasFlow() && hasDisp();
    }
bool corecvs::Element6D::is6D () const [inline]
Definition at line 67 of file element6D.h.
References hasPrevDisp(), and is5D().
    {
        return is5D() && hasPrevDisp();
    }
Member Data Documentation
const int corecvs::Element6D::CFLOW_UNKNOWN_X = INT16_MAX [static]
Constants that denote unknown values.
Definition at line 41 of file element6D.h.
Referenced by hasDisp(), hasFlow(), and hasPrevDisp().
const int corecvs::Element6D::CFLOW_UNKNOWN_Y = INT16_MAX [static]
Definition at line 42 of file element6D.h.
Referenced by hasFlow().
int32_t corecvs::Element6D::disp
Definition at line 75 of file element6D.h.
Referenced by hasDisp(), corecvs::SixDBuffer::SixDBuffer(), and corecvs::Triangulator::triangulate().
int32_t corecvs::Element6D::dispPrev
Definition at line 76 of file element6D.h.
Referenced by hasPrevDisp(), corecvs::SixDBuffer::SixDBuffer(), and corecvs::Triangulator::triangulate().
Vector2dd corecvs::Element6D::floatFlow
Definition at line 73 of file element6D.h.
Referenced by corecvs::SixDBuffer::SixDBuffer().
Vector2d16 corecvs::Element6D::flow
Definition at line 74 of file element6D.h.
Referenced by hasFlow(), corecvs::SixDBuffer::SixDBuffer(), and corecvs::Triangulator::triangulate().
The documentation for this class was generated from the following file:
core/buffers/flow/element6D.h