DeepView: corecvs::ImagerControl Class Reference
corecvs::ImagerControl Class Reference
#include <imagerControl.h>
Public Member Functions
void setPersentile (double _persentile)
void setCurrentState (ImagerState &state)
void input (ContolInput &input)
ImagerState reaction ()
Static Public Member Functions
static double getMultipierForDb (double db)
Static Protected Member Functions
static unsigned transformToAbsolute ()
Protected Attributes
ImagerState currentState
ImagerState nextState
double persentile
int lastchange
Static Protected Attributes
static double gainScaleDb []
static double gainAbsolute []
static unsigned gainLevelNumber = ImagerControl::transformToAbsolute()
Detailed Description
Definition at line 28 of file imagerControl.h.
Member Function Documentation
double corecvs::ImagerControl::getMultipierForDb (double db) [static]
Definition at line 64 of file imagerControl.cpp.
Referenced by transformToAbsolute().
{
    return pow(10, 0.1 * db);
}
void corecvs::ImagerControl::input (ContolInput & input)
Definition at line 79 of file imagerControl.cpp.
References currentState, corecvs::ImagerState::gain, gainAbsolute, corecvs::Histogram::getHigherPersentile(), corecvs::Histogram::getOverExpo(), corecvs::Histogram::getUnderExpo(), corecvs::ContolInput::histPtr, nextState, persentile, and TRACE_CONTROL.
{
    nextState = currentState;
    int gain = currentState.gain;
    double overexpo  = input.histPtr->getOverExpo();
    double underexpo = input.histPtr->getUnderExpo();
    TRACE_CONTROL("CONTROL: Current gain is %u\n", gain);
    TRACE_CONTROL("CONTROL: Over expo %2.2lf\n", overexpo * 100.0 );
    TRACE_CONTROL("CONTROL: Under expo %2.2lf\n", underexpo * 100.0 );
    if (overexpo > persentile)
    {
        nextState.gain = gain;
        TRACE_CONTROL("CONTROL: Decided to increase gain %d+1\n", gain);
        return;
    }
    if (gain == 0)
    {
        return;
    }
    /* Now we should check if we should not reduce the gain */
    int highPersentle = input.histPtr->getHigherPersentile(persentile);
    TRACE_CONTROL("CONTROL: The level of high percentile %u of %u\n", highPersentle, 0xFFF);
    // TODO: ASAP get rid of the constant should somehow reuse the
    double ratio = (double)(0xFFF - highPersentle) / 0xFFF;
    double predictedRatio = 1.0;
    do {
        gain--;
        predictedRatio =  gainAbsolute[gain] / gainAbsolute[currentState.gain];
        TRACE_CONTROL("CONTROL: Decided to decrease gain %d-1\n", gain);
    } while (predictedRatio > ratio && gain > 0);
    nextState.gain = gain;
}
ImagerState corecvs::ImagerControl::reaction ()
Definition at line 119 of file imagerControl.cpp.
References currentState, and nextState.
{
    currentState = nextState;
    return nextState;
}
void corecvs::ImagerControl::setCurrentState (ImagerState & state) [inline]
Definition at line 49 of file imagerControl.h.
References currentState.
    {
        this->currentState = state;
    }
void corecvs::ImagerControl::setPersentile (double _persentile) [inline]
Definition at line 44 of file imagerControl.h.
References persentile.
    {
        this->persentile = _persentile;
    }
unsigned corecvs::ImagerControl::transformToAbsolute () [static, protected]
Definition at line 69 of file imagerControl.cpp.
References GAIN_LEVEL_NUMBER, gainAbsolute, gainScaleDb, and getMultipierForDb().
{
    for (unsigned i = 0; i < GAIN_LEVEL_NUMBER; i++)
    {
        gainAbsolute[i] = getMultipierForDb(ImagerControl::gainScaleDb[i]);
    }
    return GAIN_LEVEL_NUMBER;
}
Member Data Documentation
ImagerState corecvs::ImagerControl::currentState [protected]
Definition at line 37 of file imagerControl.h.
Referenced by input(), reaction(), and setCurrentState().
double corecvs::ImagerControl::gainAbsolute [static, protected]
Definition at line 32 of file imagerControl.h.
Referenced by input(), and transformToAbsolute().
unsigned corecvs::ImagerControl::gainLevelNumber = ImagerControl::transformToAbsolute() [static, protected]
Definition at line 34 of file imagerControl.h.
double corecvs::ImagerControl::gainScaleDb [static, protected]
Definition at line 31 of file imagerControl.h.
Referenced by transformToAbsolute().
int corecvs::ImagerControl::lastchange [protected]
Definition at line 40 of file imagerControl.h.
ImagerState corecvs::ImagerControl::nextState [protected]
Definition at line 38 of file imagerControl.h.
Referenced by input(), and reaction().
double corecvs::ImagerControl::persentile [protected]
Definition at line 39 of file imagerControl.h.
Referenced by input(), and setPersentile().
The documentation for this class was generated from the following files:
core/cammodel/imagerControl.h
core/cammodel/imagerControl.cpp