DeepView: TolerancePredicate Class Reference
TolerancePredicate Class Reference
Public Member Functions
TolerancePredicate (G8Buffer *mask, RGBColor startColor, int tolerance)
bool operator() (RGB24Buffer *buffer, int x, int y)
void mark (RGB24Buffer *buffer, int x, int y)
Private Attributes
G8Buffer * mMask
RGBColor mStartColor
int mTolerance
Detailed Description
Definition at line 187 of file testbedMainWindow.cpp.
Constructor & Destructor Documentation
TolerancePredicate::TolerancePredicate (G8Buffer * mask, RGBColor startColor, int tolerance) [inline]
Definition at line 193 of file testbedMainWindow.cpp.
                                                                           :
        mMask(mask), mStartColor(startColor), mTolerance(tolerance) {};
Member Function Documentation
void TolerancePredicate::mark (RGB24Buffer * buffer, int x, int y) [inline]
Definition at line 211 of file testbedMainWindow.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), and mMask.
{
         mMask->element(y,x) = 255;
     }
bool TolerancePredicate::operator() (RGB24Buffer * buffer, int x, int y) [inline]
Definition at line 196 of file testbedMainWindow.cpp.
References corecvs::RGBColor::b(), corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::RGBColor::g(), mMask, mStartColor, mTolerance, and corecvs::RGBColor::r().
{
        if (mMask->element(y,x) == 255)
            return false;
        RGBColor currentColor = buffer->element(y,x);
        int r = (int)currentColor.r() - (int)mStartColor.r();
        int g = (int)currentColor.g() - (int)mStartColor.g();
        int b = (int)currentColor.b() - (int)mStartColor.b();
        int sum = abs(r) + abs(g) + abs(b);
        if (sum > mTolerance)
           return false;
        return true;
     }
Member Data Documentation
G8Buffer* TolerancePredicate::mMask [private]
Definition at line 189 of file testbedMainWindow.cpp.
Referenced by mark(), and operator()().
RGBColor TolerancePredicate::mStartColor [private]
Definition at line 190 of file testbedMainWindow.cpp.
Referenced by operator()().
int TolerancePredicate::mTolerance [private]
Definition at line 191 of file testbedMainWindow.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
applications/testbed/testbedMainWindow.cpp