DeepView: ParameterEditorWidget Class Reference
ParameterEditorWidget Class Reference
#include <parameterEditorWidget.h>
Public Member Functions
ParameterEditorWidget (QWidget *parent=NULL)
virtual ~ParameterEditorWidget ()
virtual double minimum (void)=0
virtual double maximum (void)=0
virtual double value (void)=0
virtual void setValue (double value)=0
virtual void setAutoSupported (bool value)=0
virtual void stepUp ()=0
virtual void stepDown ()=0
virtual void setName (QString name)=0
Detailed Description
Definition at line 14 of file parameterEditorWidget.h.
Constructor & Destructor Documentation
ParameterEditorWidget::ParameterEditorWidget (QWidget * parent = NULL)
Definition at line 10 of file parameterEditorWidget.cpp.
                                                            :
    QWidget(parent)
{
    // TODO Auto-generated constructor stub
}
ParameterEditorWidget::~ParameterEditorWidget () [virtual]
Definition at line 17 of file parameterEditorWidget.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
virtual double ParameterEditorWidget::maximum (void) [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
virtual double ParameterEditorWidget::minimum (void) [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
virtual void ParameterEditorWidget::setAutoSupported (bool value) [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
Referenced by CapSettingsDialog::refreshDialog().
virtual void ParameterEditorWidget::setName (QString name) [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
Referenced by CapSettingsDialog::refreshDialog().
virtual void ParameterEditorWidget::setValue (double value) [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::refreshDialog().
virtual void ParameterEditorWidget::stepDown () [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
virtual void ParameterEditorWidget::stepUp () [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
virtual double ParameterEditorWidget::value (void) [pure virtual]
Implemented in ParameterSelector, and ParameterSlider.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
The documentation for this class was generated from the following files:
utils/widgets/parameterEditorWidget.h
utils/widgets/parameterEditorWidget.cpp