DeepView: OpenCVSGMParameters Class Reference
OpenCVSGMParameters Class Reference
OpenCV SGM Parameters Class OpenCV SGM Parameters Class.
#include <openCVSGMParameters.h>
Public Types
enum FieldId {
PRE_FILTER_CAP_ID, SAD_WINDOW_SIZE_ID, P1_MULTIPLIER_ID, P2_MULTIPLIER_ID,
MIN_DISPARITY_ID, UNIQUENESS_RATIO_ID, SPECKLE_WINDOW_SIZE_ID, SPECKLE_RANGE_ID,
DISP_12_MAX_DIFF_ID, FULL_DP_ID, OPENCV_SGM_PARAMETERS_FIELD_ID_NUM
}
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
int preFilterCap () const
int sADWindowSize () const
int p1Multiplier () const
int p2Multiplier () const
int minDisparity () const
int uniquenessRatio () const
int speckleWindowSize () const
int speckleRange () const
int disp12MaxDiff () const
bool fullDP () const
void setPreFilterCap (int preFilterCap)
void setSADWindowSize (int sADWindowSize)
void setP1Multiplier (int p1Multiplier)
void setP2Multiplier (int p2Multiplier)
void setMinDisparity (int minDisparity)
void setUniquenessRatio (int uniquenessRatio)
void setSpeckleWindowSize (int speckleWindowSize)
void setSpeckleRange (int speckleRange)
void setDisp12MaxDiff (int disp12MaxDiff)
void setFullDP (bool fullDP)
template<class VisitorType >
void accept (VisitorType &visitor)
OpenCVSGMParameters ()
OpenCVSGMParameters (int preFilterCap, int sADWindowSize, int p1Multiplier, int p2Multiplier, int minDisparity, int uniquenessRatio, int speckleWindowSize, int speckleRange, int disp12MaxDiff, bool fullDP)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mPreFilterCap
Section with variables.
int mSADWindowSize
SAD Window Size SAD Window Size.
int mP1Multiplier
P1 multiplier P1 multiplier.
int mP2Multiplier
P2 multiplier P2 multiplier.
int mMinDisparity
Min Disparity Min Disparity.
int mUniquenessRatio
Uniqueness Ratio Uniqueness Ratio.
int mSpeckleWindowSize
Speckle Window Size Speckle Window Size.
int mSpeckleRange
Speckle Range Speckle Range.
int mDisp12MaxDiff
Disp 12 Max Diff Disp 12 Max Diff.
bool mFullDP
Full DP Full DP.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, OpenCVSGMParameters &toSave)
Detailed Description
OpenCV SGM Parameters Class OpenCV SGM Parameters Class.
Definition at line 38 of file openCVSGMParameters.h.
Member Enumeration Documentation
enum OpenCVSGMParameters::FieldId
Enumerator:
PRE_FILTER_CAP_ID
SAD_WINDOW_SIZE_ID
P1_MULTIPLIER_ID
P2_MULTIPLIER_ID
MIN_DISPARITY_ID
UNIQUENESS_RATIO_ID
SPECKLE_WINDOW_SIZE_ID
SPECKLE_RANGE_ID
DISP_12_MAX_DIFF_ID
FULL_DP_ID
OPENCV_SGM_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file openCVSGMParameters.h.
                 {
        PRE_FILTER_CAP_ID,
        SAD_WINDOW_SIZE_ID,
        P1_MULTIPLIER_ID,
        P2_MULTIPLIER_ID,
        MIN_DISPARITY_ID,
        UNIQUENESS_RATIO_ID,
        SPECKLE_WINDOW_SIZE_ID,
        SPECKLE_RANGE_ID,
        DISP_12_MAX_DIFF_ID,
        FULL_DP_ID,
        OPENCV_SGM_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
OpenCVSGMParameters::OpenCVSGMParameters () [inline]
Definition at line 243 of file openCVSGMParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
OpenCVSGMParameters::OpenCVSGMParameters (int preFilterCap, int sADWindowSize, int p1Multiplier, int p2Multiplier, int minDisparity, int uniquenessRatio, int speckleWindowSize, int speckleRange, int disp12MaxDiff, bool fullDP) [inline]
Definition at line 249 of file openCVSGMParameters.h.
    {
        mPreFilterCap = preFilterCap;
        mSADWindowSize = sADWindowSize;
        mP1Multiplier = p1Multiplier;
        mP2Multiplier = p2Multiplier;
        mMinDisparity = minDisparity;
        mUniquenessRatio = uniquenessRatio;
        mSpeckleWindowSize = speckleWindowSize;
        mSpeckleRange = speckleRange;
        mDisp12MaxDiff = disp12MaxDiff;
        mFullDP = fullDP;
    }
Member Function Documentation
template<class VisitorType > void OpenCVSGMParameters::accept (VisitorType & visitor) [inline]
Definition at line 229 of file openCVSGMParameters.h.
    {
        visitor.visit(mPreFilterCap,              static_cast<const IntField *>     (fields()[PRE_FILTER_CAP_ID]));
        visitor.visit(mSADWindowSize,             static_cast<const IntField *>     (fields()[SAD_WINDOW_SIZE_ID]));
        visitor.visit(mP1Multiplier,              static_cast<const IntField *>     (fields()[P1_MULTIPLIER_ID]));
        visitor.visit(mP2Multiplier,              static_cast<const IntField *>     (fields()[P2_MULTIPLIER_ID]));
        visitor.visit(mMinDisparity,              static_cast<const IntField *>     (fields()[MIN_DISPARITY_ID]));
        visitor.visit(mUniquenessRatio,           static_cast<const IntField *>     (fields()[UNIQUENESS_RATIO_ID]));
        visitor.visit(mSpeckleWindowSize,         static_cast<const IntField *>     (fields()[SPECKLE_WINDOW_SIZE_ID]));
        visitor.visit(mSpeckleRange,              static_cast<const IntField *>     (fields()[SPECKLE_RANGE_ID]));
        visitor.visit(mDisp12MaxDiff,             static_cast<const IntField *>     (fields()[DISP_12_MAX_DIFF_ID]));
        visitor.visit(mFullDP,                    static_cast<const BoolField *>    (fields()[FULL_DP_ID]));
    }
static const char* corecvs::BaseReflection< OpenCVSGMParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
int OpenCVSGMParameters::disp12MaxDiff () const [inline]
Definition at line 165 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mDisp12MaxDiff;
    }
static int corecvs::BaseReflection< OpenCVSGMParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< OpenCVSGMParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
bool OpenCVSGMParameters::fullDP () const [inline]
Definition at line 170 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mFullDP;
    }
const void* OpenCVSGMParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 121 of file openCVSGMParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< OpenCVSGMParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
int OpenCVSGMParameters::minDisparity () const [inline]
Definition at line 145 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mMinDisparity;
    }
static const char* corecvs::BaseReflection< OpenCVSGMParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< OpenCVSGMParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
int OpenCVSGMParameters::p1Multiplier () const [inline]
Definition at line 135 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mP1Multiplier;
    }
int OpenCVSGMParameters::p2Multiplier () const [inline]
Definition at line 140 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mP2Multiplier;
    }
int OpenCVSGMParameters::preFilterCap () const [inline]
Definition at line 125 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mPreFilterCap;
    }
void OpenCVSGMParameters::print () [inline]
Definition at line 281 of file openCVSGMParameters.h.
    {
        cout << *this;
    }
int OpenCVSGMParameters::sADWindowSize () const [inline]
Definition at line 130 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mSADWindowSize;
    }
void OpenCVSGMParameters::setDisp12MaxDiff (int disp12MaxDiff) [inline]
Definition at line 216 of file openCVSGMParameters.h.
    {
        mDisp12MaxDiff = disp12MaxDiff;
    }
void OpenCVSGMParameters::setFullDP (bool fullDP) [inline]
Definition at line 221 of file openCVSGMParameters.h.
    {
        mFullDP = fullDP;
    }
void OpenCVSGMParameters::setMinDisparity (int minDisparity) [inline]
Definition at line 196 of file openCVSGMParameters.h.
    {
        mMinDisparity = minDisparity;
    }
void OpenCVSGMParameters::setP1Multiplier (int p1Multiplier) [inline]
Definition at line 186 of file openCVSGMParameters.h.
    {
        mP1Multiplier = p1Multiplier;
    }
void OpenCVSGMParameters::setP2Multiplier (int p2Multiplier) [inline]
Definition at line 191 of file openCVSGMParameters.h.
    {
        mP2Multiplier = p2Multiplier;
    }
void OpenCVSGMParameters::setPreFilterCap (int preFilterCap) [inline]
Definition at line 176 of file openCVSGMParameters.h.
    {
        mPreFilterCap = preFilterCap;
    }
void OpenCVSGMParameters::setSADWindowSize (int sADWindowSize) [inline]
Definition at line 181 of file openCVSGMParameters.h.
    {
        mSADWindowSize = sADWindowSize;
    }
void OpenCVSGMParameters::setSpeckleRange (int speckleRange) [inline]
Definition at line 211 of file openCVSGMParameters.h.
    {
        mSpeckleRange = speckleRange;
    }
void OpenCVSGMParameters::setSpeckleWindowSize (int speckleWindowSize) [inline]
Definition at line 206 of file openCVSGMParameters.h.
    {
        mSpeckleWindowSize = speckleWindowSize;
    }
void OpenCVSGMParameters::setUniquenessRatio (int uniquenessRatio) [inline]
Definition at line 201 of file openCVSGMParameters.h.
    {
        mUniquenessRatio = uniquenessRatio;
    }
int OpenCVSGMParameters::speckleRange () const [inline]
Definition at line 160 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mSpeckleRange;
    }
int OpenCVSGMParameters::speckleWindowSize () const [inline]
Definition at line 155 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mSpeckleWindowSize;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int OpenCVSGMParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file openCVSGMParameters.cpp.
References DISP_12_MAX_DIFF_ID, corecvs::BaseReflection< OpenCVSGMParameters >::fields(), FULL_DP_ID, mDisp12MaxDiff, mFullDP, MIN_DISPARITY_ID, mMinDisparity, mP1Multiplier, mP2Multiplier, mPreFilterCap, mSADWindowSize, mSpeckleRange, mSpeckleWindowSize, mUniquenessRatio, corecvs::BaseReflection< OpenCVSGMParameters >::naming(), P1_MULTIPLIER_ID, P2_MULTIPLIER_ID, PRE_FILTER_CAP_ID, SAD_WINDOW_SIZE_ID, SPECKLE_RANGE_ID, SPECKLE_WINDOW_SIZE_ID, and UNIQUENESS_RATIO_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "OpenCV SGM Parameters",
        "OpenCV SGM Parameters Class",
        ""
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::PRE_FILTER_CAP_ID,
          offsetof(OpenCVSGMParameters, mPreFilterCap),
          10,
          "Pre Filter Cap",
          "Pre Filter Cap",
          "Pre Filter Cap"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::SAD_WINDOW_SIZE_ID,
          offsetof(OpenCVSGMParameters, mSADWindowSize),
          5,
          "SAD Window Size",
          "SAD Window Size",
          "SAD Window Size"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::P1_MULTIPLIER_ID,
          offsetof(OpenCVSGMParameters, mP1Multiplier),
          8,
          "P1 multiplier",
          "P1 multiplier",
          "P1 multiplier"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::P2_MULTIPLIER_ID,
          offsetof(OpenCVSGMParameters, mP2Multiplier),
          32,
          "P2 multiplier",
          "P2 multiplier",
          "P2 multiplier"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::MIN_DISPARITY_ID,
          offsetof(OpenCVSGMParameters, mMinDisparity),
          0,
          "Min Disparity",
          "Min Disparity",
          "Min Disparity"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::UNIQUENESS_RATIO_ID,
          offsetof(OpenCVSGMParameters, mUniquenessRatio),
          15,
          "Uniqueness Ratio",
          "Uniqueness Ratio",
          "Uniqueness Ratio"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::SPECKLE_WINDOW_SIZE_ID,
          offsetof(OpenCVSGMParameters, mSpeckleWindowSize),
          50,
          "Speckle Window Size",
          "Speckle Window Size",
          "Speckle Window Size"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::SPECKLE_RANGE_ID,
          offsetof(OpenCVSGMParameters, mSpeckleRange),
          16,
          "Speckle Range",
          "Speckle Range",
          "Speckle Range"
        )
    );
    fields().push_back(
        new IntField
        (
          OpenCVSGMParameters::DISP_12_MAX_DIFF_ID,
          offsetof(OpenCVSGMParameters, mDisp12MaxDiff),
          -1,
          "Disp 12 Max Diff",
          "Disp 12 Max Diff",
          "Disp 12 Max Diff"
        )
    );
    fields().push_back(
        new BoolField
        (
          OpenCVSGMParameters::FULL_DP_ID,
          offsetof(OpenCVSGMParameters, mFullDP),
          true,
          "Full DP",
          "Full DP",
          "Full DP"
        )
    );
   return 0;
}
int OpenCVSGMParameters::uniquenessRatio () const [inline]
Definition at line 150 of file openCVSGMParameters.h.
Referenced by OpenCVSGMParametersControlWidget::setParameters().
    {
        return mUniquenessRatio;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, OpenCVSGMParameters & toSave) [friend]
Definition at line 274 of file openCVSGMParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< OpenCVSGMParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int OpenCVSGMParameters::mDisp12MaxDiff
Disp 12 Max Diff Disp 12 Max Diff.
Definition at line 109 of file openCVSGMParameters.h.
Referenced by staticInit().
bool OpenCVSGMParameters::mFullDP
Full DP Full DP.
Definition at line 115 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mMinDisparity
Min Disparity Min Disparity.
Definition at line 85 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mP1Multiplier
P1 multiplier P1 multiplier.
Definition at line 73 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mP2Multiplier
P2 multiplier P2 multiplier.
Definition at line 79 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mPreFilterCap
Section with variables.
Pre Filter Cap Pre Filter Cap
Definition at line 61 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mSADWindowSize
SAD Window Size SAD Window Size.
Definition at line 67 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mSpeckleRange
Speckle Range Speckle Range.
Definition at line 103 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mSpeckleWindowSize
Speckle Window Size Speckle Window Size.
Definition at line 97 of file openCVSGMParameters.h.
Referenced by staticInit().
int OpenCVSGMParameters::mUniquenessRatio
Uniqueness Ratio Uniqueness Ratio.
Definition at line 91 of file openCVSGMParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< OpenCVSGMParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
utils/corestructs/libWidgets/openCVSGMParameters.h
utils/corestructs/libWidgets/openCVSGMParameters.cpp