DeepView: Scene3DMouse Class Reference
Scene3DMouse Class Reference
#include <scene3DMouse.h>
Public Types
enum SceneType { SCENE_3D, COORDINATE_FRAME }
Public Member Functions
virtual void drawMyself (CloudViewDialog *dialog)
virtual void dumpPCD (ostream &out)
Format description http://pointclouds.org/documentation/tutorials/pcd_file_format.php.
virtual void dumpPLY (ostream &out)
Format description http://local.wasp.uwa.edu.au/~pbourke/dataformats/ply/.
virtual
ParametersControlWidgetBase * getContolWidget ()
virtual void setParameters (void *params)
Scene3DMouse ()
virtual ~Scene3DMouse ()
virtual void commonSetup (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void commonTierdown (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void draw (CloudViewDialog *dialog)
virtual void prepareMesh (CloudViewDialog *dialog)
virtual bool isComplexObject ()
Public Attributes
Draw3dViMouseParameters mParameters
Cloud * cloud
QString name
Scene3D * parent
SceneType type
Matrix44 transform
bool visible
Detailed Description
Definition at line 19 of file scene3DMouse.h.
Member Enumeration Documentation
enum Scene3D::SceneType [inherited]
Enumerator:
SCENE_3D
COORDINATE_FRAME
Definition at line 31 of file scene3D.h.
                   {
        SCENE_3D,
        COORDINATE_FRAME
    };
Constructor & Destructor Documentation
Scene3DMouse::Scene3DMouse ()
Definition at line 17 of file scene3DMouse.cpp.
                           :
    cloud(NULL)
{}
Scene3DMouse::~Scene3DMouse () [virtual]
Definition at line 237 of file scene3DMouse.cpp.
References cloud.
{
    delete_safe(cloud);
}
Member Function Documentation
void Scene3D::commonSetup (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 102 of file scene3D.cpp.
References corecvs::Matrix44::a(), CORE_UNUSED, Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), corecvs::RectificationResult::decomposition, Draw3dTextureGen::FORCE_TEXTURE, corecvs::RectificationResult::getCameraShift(), corecvs::CameraIntrinsics::getVFov(), Scene3D::initDecalState(), corecvs::Matrix44::inverted(), Frames::LEFT_FRAME, corecvs::RectificationResult::leftCamera, CloudViewDialog::mRectificationResult, corecvs::CameraIntrinsics::resolution, Frames::RIGHT_FRAME, corecvs::EssentialDecomposition::rotation, CloudViewDialog::texture(), Draw3dParameters::textureCorrodinates(), Draw3dParameters::textureScale(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        Matrix44 textureMatrix = Matrix44::Scale(parameters->textureScale());
        glEnable(GL_TEXTURE_GEN_S);
        glEnable(GL_TEXTURE_GEN_T);
        GLint mode = GL_OBJECT_LINEAR;
        glTexGeni (GL_S, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_S, GL_OBJECT_PLANE, &textureMatrix.a(0,0));
        glTexGeni (GL_T, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_T, GL_OBJECT_PLANE, &textureMatrix.a(1,0));
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        CameraIntrinsics *intrinsics = &(dialog->mRectificationResult->rightCamera);
        double fovR = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovR, aspect);
        glActiveTexture(GL_TEXTURE1);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::RIGHT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::RIGHT_FRAME));
            } else {
                qDebug() << "No texture for right camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE );
            initDecalState(dialog, parameters, projector);
        glActiveTexture(GL_TEXTURE0);
#else
        CORE_UNUSED(dialog);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        RectificationResult *rectification = dialog->mRectificationResult.data();
        CameraIntrinsics *intrinsics = &(rectification->leftCamera);
        double fovL = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovL, aspect);
        projector = projector * (Matrix44(rectification->decomposition.rotation) * Matrix44::Shift(rectification->getCameraShift())).inverted();
        glActiveTexture(GL_TEXTURE2);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::LEFT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::LEFT_FRAME));
            } else {
                qDebug() << "No texture for left camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL );
            initDecalState(dialog, parameters, projector);
        if (parameters->decalRightCam()) {
            qDebug() << "Both cameras. Making a merge";
            glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB, GL_INTERPOLATE);   //Interpolate RGB with RGB
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB, GL_SRC_COLOR);
            //------------------------
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_ALPHA, GL_INTERPOLATE);   //Interpolate ALPHA with ALPHA
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_ALPHA, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_ALPHA, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_ALPHA, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_ALPHA, GL_SRC_ALPHA);
            //------------------------
            float mycolor[4] = {0.5, 0.5, 0.5, 0.5};
            glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor);
        }
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::commonTierdown (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 202 of file scene3D.cpp.
References Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), Draw3dTextureGen::FORCE_TEXTURE, and Draw3dParameters::textureCorrodinates().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        glDisable(GL_TEXTURE_GEN_S);
        glDisable(GL_TEXTURE_GEN_T);
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE1);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE2);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::draw (CloudViewDialog * dialog) [virtual, inherited]
Definition at line 19 of file scene3D.cpp.
References Scene3D::drawMyself(), OpenGLTools::glMultMatrixMatrix44(), Scene3D::transform, and Scene3D::visible.
{
    if (!visible) {
//        qDebug() << name << "(" << ((void *)this) << ")" << " is invisible";
        return;
    }
//    qDebug() << name << "(" << ((void *)this) << ")" << " is drawn";
    glMatrixMode(GL_MODELVIEW);
    glPushMatrix();
      OpenGLTools::glMultMatrixMatrix44(transform);
      this->drawMyself(dialog);
    glPopMatrix();
}
void Scene3DMouse::drawMyself (CloudViewDialog * dialog) [virtual]
Reimplemented from Scene3D.
Definition at line 21 of file scene3DMouse.cpp.
References Draw3dViMouseParameters::blueDist(), ViMouse3dStereoStyle::BY_CLUSTER, ViMouse3dFlowStyle::BY_FLAG, ViMouse3dStereoStyle::BY_FLAG, cloud, corecvs::SwarmPoint::cluster, corecvs::SwarmPoint::color, ViMouse3dStereoStyle::DISTANCE, corecvs::SwarmPoint::flag, Draw3dViMouseParameters::flowColorType(), Draw3dViMouseParameters::flowZoom(), OpenGLTools::glColorRGB(), OpenGLTools::glVertexVector3dd(), ViMouse3dStereoStyle::GREY_VALUE, ViMouse3dFlowStyle::HEAT, corecvs::VectorOperationsBase< RealType, ElementType >::l1Metric(), corecvs::lerpLimit(), CloudViewDialog::mCamera, CloudViewDialog::mCameraZoom, mParameters, ViMouse3dStereoStyle::NONE, corecvs::SwarmPoint::point, Draw3dViMouseParameters::pointColorType(), Draw3dViMouseParameters::redDist(), corecvs::SwarmPoint::speed, ViMouse3dFlowStyle::WHITE, corecvs::Vector3d< ElementType >::y(), ViMouse3dStereoStyle::Y_COORDINATE, corecvs::Vector3d< ElementType >::z(), and ViMouse3dStereoStyle::Z_COORDINATE.
{
    Scene3D::drawMyself(dialog);
    if (cloud == NULL) {
        return;
    }
    double redDist  = mParameters.redDist();
    double blueDist = mParameters.blueDist();
    double flowZoom = mParameters.flowZoom();
    int pointColorType = mParameters.pointColorType();
    int flowColorType  = mParameters.flowColorType();
    double    zoom  = dialog->mCameraZoom;
    Matrix44  camera = dialog->mCamera;
    if (pointColorType != ViMouse3dStereoStyle::NONE)
    {
        glBegin(GL_POINTS);
        glColor4f(1.0, 1.0, 1.0, 1.0);
        for (unsigned i = 0; i < cloud->size(); i++)
        {
            SwarmPoint p = cloud->operator[](i);
            Vector3dd point = p.point;
            switch (pointColorType)
            {
            case ViMouse3dStereoStyle::GREY_VALUE:
                OpenGLTools::glColorRGB(p.color);
                break;
            case ViMouse3dStereoStyle::Z_COORDINATE:
                OpenGLTools::glColorRGB(RGBColor::rainbow1(
                    lerpLimit(1.0, 0.0, p.point.z(), redDist, blueDist)
                ));
                break;
            case ViMouse3dStereoStyle::Y_COORDINATE:
                OpenGLTools::glColorRGB(RGBColor::rainbow1(
                    lerpLimit(1.0, 0.0, p.point.y(), redDist, blueDist)
                ));
                break;
            case ViMouse3dStereoStyle::BY_FLAG:
                if        (p.flag == SwarmPoint::IS_3D) {
                    OpenGLTools::glColorRGB(p.color);
                } else if (p.flag == SwarmPoint::IS_6D) {
                    glColor4f(0.0f, 1.0f, 0.0f, 1.0f);
                } else {
                    glColor4f(1.0f, 0.0f, 0.0f, 1.0f);
                }
                break;
            case ViMouse3dStereoStyle::BY_CLUSTER:
                {
                   RGBColor color(71123 * p.cluster);
                   OpenGLTools::glColorRGB(color);
                }
                break;
            default:
            case ViMouse3dStereoStyle::DISTANCE:
                Vector3dd projected = (Matrix44::Scale(zoom) * camera * point);
                OpenGLTools::glColorRGB(RGBColor::rainbow1(
                    lerpLimit(1.0, 0.0, projected.z(), redDist, blueDist)
                ));
                break;
            }
            OpenGLTools::glVertexVector3dd(point);
        }
        glEnd();
    }
    if (flowColorType == ViMouse3dFlowStyle::WHITE || flowColorType == ViMouse3dFlowStyle::HEAT)
    {
        /* Draw Flow */
        glBegin(GL_LINES);
        glLineWidth(1.0);
        if (flowColorType == ViMouse3dFlowStyle::WHITE) {
            glColor4f(1.0, 1.0, 1.0, 1.0);
        }
        for (unsigned i = 0; i < cloud->size(); i++)
        {
            SwarmPoint p  = cloud->operator[](i);
            Vector3dd point = p.point;
            Vector3dd flow  = p.speed;
            Vector3dd point1 = point - flow * flowZoom + Vector3dd(0.00001);
            if (flowColorType == ViMouse3dFlowStyle::HEAT)
            {
                OpenGLTools::glColorRGB(
                    RGBColor::rainbow1(lerpLimit(0.0, 1.0, flow.l1Metric(), 15.0, 100.0))
                );
            }
            OpenGLTools::glVertexVector3dd(point);
            OpenGLTools::glVertexVector3dd(point1);
        }
        glEnd();
    }
    if (flowColorType == ViMouse3dFlowStyle::BY_FLAG)
    {
        glBegin(GL_LINES);
        glLineWidth(1.0);
            for (unsigned i = 0; i < cloud->size(); i++)
            {
                SwarmPoint &p  = cloud->operator[](i);
                if (p.flag != 1 && p.flag != 2)
                    continue;
                if      (p.flag == SwarmPoint::IS_6D)
                     glColor4f(0.0f, 1.0f, 0.0f, 1.0f);
                else if (p.flag == SwarmPoint::USER_1)
                     glColor4f(1.0f, 0.0f, 0.0f, 1.0f);
                Vector3dd point = p.point;
                Vector3dd flow  = p.speed;
                Vector3dd point1 = point - flow * flowZoom + Vector3dd(0.00001);
                OpenGLTools::glVertexVector3dd(point);
                OpenGLTools::glVertexVector3dd(point1);
            }
        glEnd();
    }
}
void Scene3DMouse::dumpPCD (ostream & out) [virtual]
Format description http://pointclouds.org/documentation/tutorials/pcd_file_format.php.
Reimplemented from Scene3D.
Definition at line 154 of file scene3DMouse.cpp.
References cloud, corecvs::SwarmPoint::color, corecvs::RGBColor::color(), corecvs::SwarmPoint::point, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
   /* VERSION .7
    FIELDS x y z rgb
    SIZE 4 4 4 4
    TYPE F F F F
    COUNT 1 1 1 1
    WIDTH 213
    HEIGHT 1
    VIEWPOINT 0 0 0 1 0 0 0
    POINTS 213
    DATA ascii
    0.93773 0.33763 0 4.2108e+06*/
    out << "# .PCD v.7 - Point Cloud Data file format\n";
    out << "VERSION .7\n";
    out << "FIELDS x y z rgb\n";
    out << "SIZE  4 4 4 4\n";
    out << "TYPE  F F F U\n";
    out << "COUNT 1 1 1 1\n";
    out << "WIDTH " << cloud->size() << "\n";
    out << "HEIGHT 1\n";
    out << "VIEWPOINT 0 0 0 1 0 0 0\n";
    out << "POINTS " << cloud->size() << "\n";
    out << "DATA ascii\n";
    for (unsigned i = 0; i < cloud->size(); i++)
    {
       SwarmPoint &p  = cloud->operator[](i);
       out << (p.point.x() / 1000.0)  << " " << (p.point.y() / 1000.0) << " " << (p.point.z() / 1000.0) << " "
           << p.color.color() <<  endl;
    }
}
void Scene3DMouse::dumpPLY (ostream & out) [virtual]
Format description http://local.wasp.uwa.edu.au/~pbourke/dataformats/ply/.
Reimplemented from Scene3D.
Definition at line 194 of file scene3DMouse.cpp.
References corecvs::RGBColor::b(), cloud, corecvs::SwarmPoint::color, corecvs::RGBColor::g(), corecvs::SwarmPoint::point, corecvs::RGBColor::r(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
    out << "ply" << endl;
    out << "format ascii 1.0" << endl;
    out << "comment made by ViMouse software" << endl;
    out << "comment This file is a saved stereo-reconstruction" << endl;
    out << "element vertex " << cloud->size() << endl;
    out << "property float x" << endl;
    out << "property float y" << endl;
    out << "property float z" << endl;
    out << "property uchar red" << endl;
    out << "property uchar green" << endl;
    out << "property uchar blue" << endl;
    out << "end_header" << endl;
    for (unsigned i = 0; i < cloud->size(); i++)
    {
        SwarmPoint &p  = cloud->operator[](i);
        double x = p.point.x() / 100.0;
        double y = p.point.y() / 100.0;
        double z = p.point.z() / 100.0;
        double limit = 1000;
        if (x < -limit) x = -limit;
        if (y < -limit) y = -limit;
        if (z < -limit) z = -limit;
        if (x > limit) x = limit;
        if (y > limit) y = limit;
        if (z > limit) z = limit;
       out << x << " "
           << y << " "
           << z << " "
           << (unsigned)(p.color.r()) << " "
           << (unsigned)(p.color.g()) << " "
           << (unsigned)(p.color.b()) << endl;
    }
}
virtual ParametersControlWidgetBase* Scene3DMouse::getContolWidget () [inline, virtual]
Reimplemented from Scene3D.
Definition at line 30 of file scene3DMouse.h.
References mParameters, and Draw3dViMouseParametersControlWidget::setParameters().
    {
        Draw3dViMouseParametersControlWidget *result = new Draw3dViMouseParametersControlWidget();
        result->setParameters(mParameters);
        return result;
    };
virtual bool Scene3D::isComplexObject () [inline, virtual, inherited]
Definition at line 64 of file scene3D.h.
References Scene3D::COORDINATE_FRAME, and Scene3D::type.
    {
        return (type == COORDINATE_FRAME);
    }
void Scene3D::prepareMesh (CloudViewDialog * dialog) [virtual, inherited]
Reimplemented in StereoCameraScene, CameraScene, Plane3DScene, Grid3DScene, Mesh3DScene, and CoordinateFrame.
Definition at line 235 of file scene3D.cpp.
{
}
virtual void Scene3DMouse::setParameters (void * params) [inline, virtual]
Reimplemented from Scene3D.
Definition at line 37 of file scene3DMouse.h.
References mParameters.
    {
        mParameters = *static_cast<Draw3dViMouseParameters *>(params);
    };
Member Data Documentation
Cloud* Scene3DMouse::cloud
Definition at line 40 of file scene3DMouse.h.
Referenced by drawMyself(), dumpPCD(), dumpPLY(), and ~Scene3DMouse().
Draw3dViMouseParameters Scene3DMouse::mParameters
Definition at line 22 of file scene3DMouse.h.
Referenced by drawMyself(), getContolWidget(), and setParameters().
QString Scene3D::name [inherited]
Definition at line 37 of file scene3D.h.
Referenced by CloudViewDialog::CloudViewDialog().
Scene3D* Scene3D::parent [inherited]
Definition at line 38 of file scene3D.h.
Matrix44 Scene3D::transform [inherited]
Definition at line 41 of file scene3D.h.
Referenced by Scene3D::draw().
SceneType Scene3D::type [inherited]
Definition at line 39 of file scene3D.h.
Referenced by CoordinateFrame::CoordinateFrame(), and Scene3D::isComplexObject().
bool Scene3D::visible [inherited]
Definition at line 42 of file scene3D.h.
Referenced by Scene3D::draw().
The documentation for this class was generated from the following files:
applications/base/scene3DMouse.h
applications/base/scene3DMouse.cpp