DeepView: corecvs::EssentialDecomposition Class Reference
corecvs::EssentialDecomposition Class Reference
This class stores the relative position of first and second camera.
#include <essentialMatrix.h>
Public Member Functions
EssentialDecomposition ()
EssentialDecomposition (const Matrix33 &_rotation, const Vector3dd &_direction)
void getScaler (const Vector3dd &right, const Vector3dd &left, double &s1, double &s2, double &err) const
Triangulation taking as input left and right 2D projective vectors of the pixel in left () and right () cameras and returning lengths of 3D-vectors of the pixel for left and right cameras.
void getDistance (const Vector3dd &right, const Vector3dd &left, double &d1, double &d2, double &err) const
Triangulation taking as input left and right 2D projective vectors of the pixel in left () and right () cameras and returning lengths of 3D-vectors of the pixel for left and right cameras.
void getScaler (const Vector2dd &right2d, const Vector2dd &left2d, double &s1, double &s2, double &err) const
Shortcut for Vector2dd of getScaler()
void getDistance (const Vector2dd &right2d, const Vector2dd &left2d, double &d1, double &d2, double &err) const
Shortcut for Vector2dd of getDistance()
void getScaler (const Correspondance &corr, double &s1, double &s2, double &err) const
Shortcut for Correspondance of getScaler()
void getDistance (const Correspondance &corr, double &d1, double &d2, double &err) const
Shortcut for Correspondance of getDistance()
template<class VisitorType >
void accept (VisitorType &visitor)
Public Attributes
Matrix33 rotation
Vector3dd direction
Friends
ostream & operator<< (ostream &out, const EssentialDecomposition &edecomp)
Detailed Description
This class stores the relative position of first and second camera.
It basically consist of the 2 operations - rotation and shift.
Definition at line 28 of file essentialMatrix.h.
Constructor & Destructor Documentation
corecvs::EssentialDecomposition::EssentialDecomposition () [inline]
Definition at line 37 of file essentialMatrix.h.
                             :
        rotation(1.0),
        direction(1.0, 0.0, 0.0)
    {
    }
corecvs::EssentialDecomposition::EssentialDecomposition (const Matrix33 & _rotation, const Vector3dd & _direction) [inline]
Definition at line 43 of file essentialMatrix.h.
                                                                                   :
        rotation(_rotation),
        direction(_direction.normalised())
    {}
Member Function Documentation
template<class VisitorType > void corecvs::EssentialDecomposition::accept (VisitorType & visitor) [inline]
Definition at line 174 of file essentialMatrix.h.
References direction, and rotation.
    {
        visitor.visit(rotation,  Matrix33 (1.0),         "rotation");
        visitor.visit(direction, Vector3dd(1.0,0.0,0.0), "direction");
    }
void corecvs::EssentialDecomposition::getDistance (const Vector3dd & right, const Vector3dd & left, double & d1, double & d2, double & err) const [inline]
Triangulation taking as input left and right 2D projective vectors of the pixel in left () and right () cameras and returning lengths of 3D-vectors of the pixel for left and right cameras.
If the camera translation vector is and 3D-vectors are and then
Considering triangle made by vectors , and and making use of the sine law we obtain
Parameters:
left [in] Vector to the point in left CAMERA frame
right [in] Vector to the point in right CAMERA frame
d1 [out] Distance to intersection point in LEFT CAMERA frame
d2 [out] Distance to intersection point in RIGHT CAMERA frame
err [out] Scaler that shows a residual error
Definition at line 113 of file essentialMatrix.h.
References direction, corecvs::VectorOperationsBase< RealType, ElementType >::normalised(), and rotation.
Referenced by getDistance(), and corecvs::Triangulator::triangulate().
    {
        Vector3dd n1 = right.normalised();
        Vector3dd n2 = rotation * left.normalised();
        double t = (n1 ^ n2).l2Metric();
        d1 = (n2 ^ direction).l2Metric() / t;
        d2 = (n1 ^ direction).l2Metric() / t;
        err = direction & (n1 ^ n2).normalised();
    }
void corecvs::EssentialDecomposition::getDistance (const Vector2dd & right2d, const Vector2dd & left2d, double & d1, double & d2, double & err) const [inline]
Shortcut for Vector2dd of getDistance()
Definition at line 143 of file essentialMatrix.h.
References getDistance().
    {
        Vector3dd right = Vector3dd(right2d, 1.0);
        Vector3dd left  = Vector3dd(left2d , 1.0);
        getDistance(right, left, d1, d2, err);
    }
void corecvs::EssentialDecomposition::getDistance (const Correspondance & corr, double & d1, double & d2, double & err) const [inline]
Shortcut for Correspondance of getDistance()
Definition at line 166 of file essentialMatrix.h.
References getDistance(), and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start.
    {
        Vector3dd right = Vector3dd(corr.start.x(), corr.start.y(), 1.0);
        Vector3dd left  = Vector3dd(corr.  end.x(), corr.  end.y(), 1.0);
        getDistance(right, left, d1, d2, err);
    }
void corecvs::EssentialDecomposition::getScaler (const Vector3dd & right, const Vector3dd & left, double & s1, double & s2, double & err) const [inline]
Triangulation taking as input left and right 2D projective vectors of the pixel in left () and right () cameras and returning lengths of 3D-vectors of the pixel for left and right cameras.
If the camera translation vector is and 3D-vectors are and then
or
If the equation is not perfect then we have general decomposition of the vector in non-orthogonal basis
Making matrix out of columns , , we obtain non-homogeneous linear system in , , .
Parameters:
left [in] Vector to the point in left CAMERA frame
right [in] Vector to the point in right CAMERA frame
s1 [out] Scaler that will transform left vector to intersection point in LEFT CAMERA frame
s2 [out] Scaler that will transform left vector to intersection point in RIGHT CAMERA frame
err [out] Scaler that shows a residual error
Definition at line 76 of file essentialMatrix.h.
References direction, corecvs::Matrix33::FromColumns(), corecvs::Matrix33::inv(), rotation, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by UniversalRectifier::decomposeEssential(), corecvs::Triangulator::getDepth(), getScaler(), UniversalRectifier::recalculate(), and corecvs::Triangulator::triangulate().
    {
        Vector3dd n1 = right;
        Vector3dd n2 = rotation * left;
        Matrix33 m = Matrix33::FromColumns(n1, -n2, n1 ^ n2);
        Vector3dd scaler = m.inv() * direction;
        s1  = scaler.x();
        s2  = scaler.y();
        err = scaler.z();
    }
void corecvs::EssentialDecomposition::getScaler (const Vector2dd & right2d, const Vector2dd & left2d, double & s1, double & s2, double & err) const [inline]
Shortcut for Vector2dd of getScaler()
Definition at line 130 of file essentialMatrix.h.
References getScaler().
    {
        Vector3dd right = Vector3dd(right2d, 1.0);
        Vector3dd left  = Vector3dd(left2d , 1.0);
        getScaler(right, left, s1, s2, err);
    }
void corecvs::EssentialDecomposition::getScaler (const Correspondance & corr, double & s1, double & s2, double & err) const [inline]
Shortcut for Correspondance of getScaler()
Definition at line 156 of file essentialMatrix.h.
References corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, getScaler(), and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start.
    {
        Vector3dd right = Vector3dd(corr.start.x(), corr.start.y(), 1.0);
        Vector3dd left  = Vector3dd(corr.end  .x(), corr.end  .y(), 1.0);
        getScaler(right, left, s1, s2, err);
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, const EssentialDecomposition & edecomp) [friend]
Definition at line 180 of file essentialMatrix.h.
    {
        Quaternion q = Quaternion::FromMatrix(edecomp.rotation);
        out << "This matrix is rotating " << radToDeg(q.getAngle()) << "deg around axis: ";
        out << q.getAxis() << endl;
        out << "And then shifting by vector:" << endl;
        out << edecomp.direction << endl;
        return out;
    }
Member Data Documentation
Vector3dd corecvs::EssentialDecomposition::direction
Definition at line 35 of file essentialMatrix.h.
Referenced by accept(), corecvs::RectificationResult::getCameraShift(), getDistance(), corecvs::RectificationResult::getRectifiedProjectionLeft(), and getScaler().
Matrix33 corecvs::EssentialDecomposition::rotation
Definition at line 32 of file essentialMatrix.h.
Referenced by accept(), Scene3D::commonSetup(), StereoCameraScene::drawMyself(), getDistance(), corecvs::RectificationResult::getRectifiedProjectionLeft(), and getScaler().
The documentation for this class was generated from the following file:
core/rectification/essentialMatrix.h