DeepView: OpenCvFileCapture Class Reference
OpenCvFileCapture Class Reference
Capture video stream from avi file using OpenCV library.
#include <openCvFileCapture.h>
Classes
class SpinThread
Public Types
enum CapErrorCode { SUCCESS = 0, SUCCESS_1CAM = 1, FAILURE = 2 }
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
OpenCvFileCapture (QString const &params)
Capture video stream from avi file using OpenCV library.
virtual
ImageCaptureInterface::CapErrorCode startCapture ()
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode initCapture ()
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
QMutex & spinThreadRunMutex ()
QMutex & protectFrameMutex ()
void notifyAboutStreamPaused ()
void increaseTimeStamp ()
string getImageFileName (uint imageNumber, uint channelNumber=0)
Aux function to get an image file name, which path name is given by additional parameters.
void increaseImageFileCounter ()
void resetImageFileCounter ()
virtual FramePair getFrameRGB24 ()
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&)
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode queryCameraParameters (CameraParameters &parameter)
Check if a specific property can be set/read and what values it can take.
Static Public Member Functions
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Public Attributes
bool shouldStopSpinThread
uint64_t mTimeStamp
Static Public Attributes
static string sPgmImageFileFmt = "image%04u_c%d.pgm"
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Protected Attributes
uint64_t mDelay
Delay to sleep before querying for a new frame in milliseconds.
FramePair mCurrent
AbstractFileCaptureSpinThread * mSpin
QMutex mProtectFrame
protectFrame protects changes of mCount and mCurrentCount
bool mShouldSkipUnclaimed
QMutex mSpinThreadRun
controls the spin thread.
string mPathFmt
bool mVerbose
unsigned mCount
Static Protected Attributes
static cint capDefaultDelay = 35
Private Attributes
cv::VideoCapture mCapture
Friends
class AbstractFileCaptureSpinThread
Detailed Description
Capture video stream from avi file using OpenCV library.
Definition at line 10 of file openCvFileCapture.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapErrorCode [inherited]
Enumerator:
SUCCESS
SUCCESS_1CAM
FAILURE
Reimplemented in DirectShowCaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 72 of file imageCaptureInterface.h.
    {
        SUCCESS       = 0,
        SUCCESS_1CAM  = 1,
        FAILURE      = 2
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
Constructor & Destructor Documentation
OpenCvFileCapture::OpenCvFileCapture (QString const & params)
Capture video stream from avi file using OpenCV library.
Definition at line 11 of file openCvFileCapture.cpp.
References mCapture, AbstractFileCapture::mCurrent, AbstractFileCapture::mDelay, ImageFileCaptureInterface::mPathFmt, and AbstractFileCapture::mSpin.
    : AbstractFileCapture(params)
{
    mCapture.open(mPathFmt);
    if (!mCapture.isOpened())
    {
        printf("failed to open file");
        exit(EXIT_FAILURE);  // TODO: do not use exit() here.
    }
    mSpin = new SpinThread(this, mDelay, mCurrent, mCapture, mPathFmt);
}
Member Function Documentation
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureName (QString & value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 171 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureProperty (int id, int * value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, DirectShowCaptureDecoupleInterface, V4L2CaptureInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 166 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by CapSettingsDialog::refreshDialog().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getDeviceName (int num, QString & name) [virtual, inherited]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented in DirectShowCaptureInterface, and V4L2CaptureInterface.
Definition at line 186 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getFormats (int * num, CameraFormat *&) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 176 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::FramePair OpenCvFileCapture::getFrame () [virtual]
Main function to request frames from image interface.
Implements AbstractFileCapture.
Definition at line 25 of file openCvFileCapture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, ImageCaptureInterface::FramePair::leftTimeStamp, AbstractFileCapture::mCurrent, AbstractFileCapture::mProtectFrame, and ImageCaptureInterface::FramePair::rightTimeStamp.
{
    mProtectFrame.lock();
        FramePair result(NULL, NULL);
        result.bufferLeft     = new G12Buffer(mCurrent.bufferLeft);
        result.bufferRight    = new G12Buffer(mCurrent.bufferRight);
        result.leftTimeStamp  = mCurrent.leftTimeStamp;
        result.rightTimeStamp = mCurrent.rightTimeStamp;
    mProtectFrame.unlock();
    return result;
}
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual, inherited]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
string ImageFileCaptureInterface::getImageFileName (uint imageNumber, uint channelNumber = 0) [inherited]
Aux function to get an image file name, which path name is given by additional parameters.
Parameters:
imageNumber - image file number in a series (since 1-st)
channelNumber - image file channel number in a series (usual 0 or 1)
We're to check correctness of the current directory, but we need a path to "data" folder with image files.
"../" - Bin directory curDir "../../" - OpenCL project curDir "../../../" - MSVC sets curDir to the project dir (= "hostSoft")
Note:
But from another side it's dangerously to scan up to 3 levels by trying to find a requested file.
especially if there's a special folder structure with different series... Therefore for Unix it's applied only for one parent as we run from the bin directory,
but usually use images by path like this: "data/pair".
Definition at line 28 of file imageFileCaptureInterface.cpp.
References ImageFileCaptureInterface::mPathFmt, ImageFileCaptureInterface::mPathPrefix, and ImageFileCaptureInterface::sPgmImageFileFmt.
Referenced by FileCaptureInterface::getFrame(), FilePreciseCapture::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
{
    // TODO: How to replace this with C++ construct? I.e. MFC's CString has a method Format() for this, but std::string doesn't. :(
    char pathName[256];
    if (mPathFmt.find("%0.0s") != string::npos)             // format comes from GUI with constant pair for debugging
    {
        snprintf2buf(pathName, mPathFmt.c_str(), "", channelNumber);// str + int (the way to disable pair switching over series)
    }
    else if (mPathFmt.find("%") != string::npos)            // format comes from GUI with series processing
    {
        // TODO: it would be good here to check that format expects exactly 2 integers
        snprintf2buf(pathName, mPathFmt.c_str(), imageNumber, channelNumber); // expects 2 ints
    }
    else if (!mPathFmt.empty())                             // format comes as a ready path, only from some tests
    {
        // one exclusion is possible here: when ctor got a direct path to the file!
        QFileInfo fi(mPathFmt.c_str());
        if (fi.isFile() && fi.exists()) {
            return mPathFmt;                                // return immediately the initial path as it's not a format
        }
        // mPathFmt has a real folder path
        if (mPathFmt[mPathFmt.length() - 1] != '/') {       // append slash at the end if absent
            mPathFmt += '/';
        }
        mPathFmt += sPgmImageFileFmt;                       // add default format to the pathFmt
        return getImageFileName(imageNumber, channelNumber);
    }
    if (imageNumber == 1 && mPathPrefix.empty() && !QFile::exists(pathName))
    {
        /**
         * We're to check correctness of the current directory, but we need a path to "data" folder with image files.
         *
         *       "../"  - Bin directory curDir
         *    "../../"  - OpenCL project curDir
         * "../../../"  - MSVC sets curDir to the project dir (= "hostSoft")
         *
         * \note  But from another side it's dangerously to scan up to 3 levels by trying to find a requested file.\n
         *        especially if there's a special folder structure with different series...
         *        Therefore for Unix it's applied only for one parent as we run from the bin directory, \n
         *        but usually use images by path like this: "data/pair".
         */
        string path(pathName);
        string prefix;
#ifdef WIN32
        cuint numRecursiveFoldersToCheck = 3;
#else
        cuint numRecursiveFoldersToCheck = 1;               // one check for parent dir is ok or also dangerously?
#endif
        for (unsigned k = 0; k < numRecursiveFoldersToCheck; k++)
        {
            path  .insert(0, "../");
            prefix.insert(0, "../");                        // try at folder one step up
            if (QFile::exists(path.c_str()))
            {
                mPathPrefix.assign(prefix);
                break;
            }
        }
    }
    return mPathPrefix + pathName;
}
QString ImageCaptureInterface::getInterfaceName () [virtual, inherited]
Return the interface device string.
Reimplemented in V4L2CaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 181 of file imageCaptureInterface.cpp.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
{
    return "";
}
void ImageFileCaptureInterface::increaseImageFileCounter () [inline, inherited]
Definition at line 25 of file imageFileCaptureInterface.h.
Referenced by FileCaptureInterface::getFrame(), FilePreciseCapture::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
{ mCount++;   }
void AbstractFileCapture::increaseTimeStamp () [inherited]
Definition at line 135 of file abstractFileCapture.cpp.
References AbstractFileCapture::mDelay, and AbstractFileCapture::mTimeStamp.
{
    mTimeStamp += mDelay * 1000;
}
ImageCaptureInterface::CapErrorCode AbstractFileCapture::initCapture () [virtual, inherited]
Reimplemented from ImageCaptureInterface.
Definition at line 87 of file abstractFileCapture.cpp.
References ImageCaptureInterface::SUCCESS.
{
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode AbstractFileCapture::nextFrame () [virtual, inherited]
Reimplemented from ImageCaptureInterface.
Definition at line 104 of file abstractFileCapture.cpp.
References AbstractFileCapture::mSpin, AbstractFileCaptureSpinThread::nextFrame(), and ImageCaptureInterface::SUCCESS.
{
    mSpin->nextFrame();
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
void AbstractFileCapture::notifyAboutStreamPaused () [inherited]
Definition at line 125 of file abstractFileCapture.cpp.
References ImageCaptureInterface::streamPaused().
Referenced by AbstractFileCaptureSpinThread::pause().
{
    emit streamPaused();
}
ImageCaptureInterface::CapErrorCode AbstractFileCapture::pauseCapture () [virtual, inherited]
Reimplemented from ImageCaptureInterface.
Definition at line 98 of file abstractFileCapture.cpp.
References AbstractFileCapture::mSpin, ImageCaptureInterface::SUCCESS, and AbstractFileCaptureSpinThread::togglePause().
{
    mSpin->togglePause();
    return ImageCaptureInterface::SUCCESS;
}
QMutex & AbstractFileCapture::protectFrameMutex () [inherited]
Definition at line 115 of file abstractFileCapture.cpp.
References AbstractFileCapture::mProtectFrame.
Referenced by AbstractFileCaptureSpinThread::run().
{
    return mProtectFrame;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::queryCameraParameters (CameraParameters & parameter) [virtual, inherited]
Check if a specific property can be set/read and what values it can take.
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, DirectShowCaptureDecoupleInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 211 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::SUCCESS.
Referenced by CapSettingsDialog::refreshDialog().
{
    Q_UNUSED(parameter)
    return ImageCaptureInterface::SUCCESS;
}
void ImageFileCaptureInterface::resetImageFileCounter () [inline, inherited]
Definition at line 26 of file imageFileCaptureInterface.h.
Referenced by FileCaptureInterface::getFrame(), FilePreciseCapture::FileSpinThread::grabFramePair(), and ImageFileCaptureInterface::ImageFileCaptureInterface().
{ mCount = 1; }
ImageCaptureInterface::CapErrorCode AbstractFileCapture::setCaptureProperty (int id, int value) [virtual, inherited]
Reimplemented from ImageCaptureInterface.
Definition at line 79 of file abstractFileCapture.cpp.
References ImageCaptureInterface::FAILURE.
{
    Q_UNUSED(id);
    Q_UNUSED(value);
    return ImageCaptureInterface::FAILURE;
}
QMutex & AbstractFileCapture::spinThreadRunMutex () [inherited]
Definition at line 110 of file abstractFileCapture.cpp.
References AbstractFileCapture::mSpinThreadRun.
Referenced by AbstractFileCaptureSpinThread::run().
{
    return mSpinThreadRun;
}
ImageCaptureInterface::CapErrorCode OpenCvFileCapture::startCapture () [virtual]
Reimplemented from AbstractFileCapture.
Definition at line 37 of file openCvFileCapture.cpp.
References AbstractFileCapture::mSpin, and ImageCaptureInterface::SUCCESS.
{
    mSpin->start();
//  return ImageCaptureInterface::CapSuccess1Cam;
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool AbstractFileCapture::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented from ImageCaptureInterface.
Definition at line 130 of file abstractFileCapture.cpp.
{
    return true;
}
Friends And Related Function Documentation
friend class AbstractFileCaptureSpinThread [friend, inherited]
Definition at line 40 of file abstractFileCapture.h.
Member Data Documentation
cint AbstractFileCapture::capDefaultDelay = 35 [static, protected, inherited]
Definition at line 33 of file abstractFileCapture.h.
Referenced by AbstractFileCapture::AbstractFileCapture().
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
cv::VideoCapture OpenCvFileCapture::mCapture [private]
Definition at line 38 of file openCvFileCapture.h.
Referenced by OpenCvFileCapture::SpinThread::grabFramePair(), and OpenCvFileCapture().
unsigned ImageFileCaptureInterface::mCount [protected, inherited]
Definition at line 31 of file imageFileCaptureInterface.h.
Referenced by FileCaptureInterface::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
FramePair AbstractFileCapture::mCurrent [protected, inherited]
Definition at line 37 of file abstractFileCapture.h.
Referenced by AbstractFileCapture::AbstractFileCapture(), FilePreciseCapture::FilePreciseCapture(), getFrame(), and OpenCvFileCapture().
uint64_t AbstractFileCapture::mDelay [protected, inherited]
Delay to sleep before querying for a new frame in milliseconds.
Definition at line 36 of file abstractFileCapture.h.
Referenced by AbstractFileCapture::AbstractFileCapture(), FilePreciseCapture::FilePreciseCapture(), FilePreciseCapture::FileSpinThread::grabFramePair(), AbstractFileCapture::increaseTimeStamp(), and OpenCvFileCapture().
string ImageFileCaptureInterface::mPathFmt [protected, inherited]
Definition at line 29 of file imageFileCaptureInterface.h.
Referenced by AbstractFileCapture::AbstractFileCapture(), FileCaptureInterface::FileCaptureInterface(), FilePreciseCapture::FilePreciseCapture(), ImageFileCaptureInterface::getImageFileName(), ImageFileCaptureInterface::ImageFileCaptureInterface(), and OpenCvFileCapture().
QMutex AbstractFileCapture::mProtectFrame [protected, inherited]
protectFrame protects changes of mCount and mCurrentCount
Definition at line 44 of file abstractFileCapture.h.
Referenced by getFrame(), FilePreciseCapture::getFrame(), and AbstractFileCapture::protectFrameMutex().
bool AbstractFileCapture::mShouldSkipUnclaimed [protected, inherited]
Definition at line 46 of file abstractFileCapture.h.
Referenced by AbstractFileCapture::AbstractFileCapture(), FilePreciseCapture::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
AbstractFileCaptureSpinThread* AbstractFileCapture::mSpin [protected, inherited]
Definition at line 41 of file abstractFileCapture.h.
Referenced by FilePreciseCapture::FilePreciseCapture(), AbstractFileCapture::nextFrame(), OpenCvFileCapture(), AbstractFileCapture::pauseCapture(), startCapture(), AbstractFileCapture::startCapture(), and AbstractFileCapture::~AbstractFileCapture().
QMutex AbstractFileCapture::mSpinThreadRun [protected, inherited]
controls the spin thread.
if locked spin thread will exit ASAP
Definition at line 48 of file abstractFileCapture.h.
Referenced by AbstractFileCapture::spinThreadRunMutex(), and AbstractFileCapture::~AbstractFileCapture().
uint64_t AbstractFileCapture::mTimeStamp [inherited]
Definition at line 52 of file abstractFileCapture.h.
Referenced by FilePreciseCapture::getFrame(), FilePreciseCapture::FileSpinThread::grabFramePair(), AbstractFileCapture::increaseTimeStamp(), and AbstractFileCaptureSpinThread::run().
bool ImageFileCaptureInterface::mVerbose [protected, inherited]
Definition at line 30 of file imageFileCaptureInterface.h.
Referenced by FilePreciseCapture::FilePreciseCapture(), FileCaptureInterface::getFrame(), FilePreciseCapture::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
bool AbstractFileCapture::shouldStopSpinThread [inherited]
Definition at line 51 of file abstractFileCapture.h.
Referenced by AbstractFileCaptureSpinThread::run(), and AbstractFileCapture::~AbstractFileCapture().
string ImageFileCaptureInterface::sPgmImageFileFmt = "image%04u_c%d.pgm" [static, inherited]
Definition at line 23 of file imageFileCaptureInterface.h.
Referenced by ImageFileCaptureInterface::getImageFileName().
The documentation for this class was generated from the following files:
utils/framesources/openCvFileCapture.h
utils/framesources/openCvFileCapture.cpp