DeepView: OpenCVFilterParametersControlWidget Class Reference
OpenCVFilterParametersControlWidget Class Reference
#include <openCVFilterParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
OpenCVFilterParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~OpenCVFilterParametersControlWidget ()
OpenCVFilterParameters * createParameters () const
void setParameters (const OpenCVFilterParameters &input)
virtual void setParametersVirtual (void *input)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
Private Attributes
Ui_OpenCVFilterParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file openCVFilterParametersControlWidget.h.
Constructor & Destructor Documentation
OpenCVFilterParametersControlWidget::OpenCVFilterParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file openCVFilterParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::OpenCVFilterParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->openCVFilterComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->param1SpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->param2SpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}
OpenCVFilterParametersControlWidget::~OpenCVFilterParametersControlWidget ()
Definition at line 28 of file openCVFilterParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void OpenCVFilterParametersControlWidget::changeParameters () [inline, slot]
Definition at line 34 of file openCVFilterParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
OpenCVFilterParameters * OpenCVFilterParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 50 of file openCVFilterParametersControlWidget.cpp.
References mUi.
Referenced by createParametersVirtual(), loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    OpenCVFilterParameters *result = new OpenCVFilterParameters(
          static_cast<OpenCVBinaryFilterType::OpenCVBinaryFilterType>(mUi->openCVFilterComboBox->currentIndex())
        , mUi->param1SpinBox->value()
        , mUi->param2SpinBox->value()
    );
    return result;
}
virtual BaseReflectionStatic* OpenCVFilterParametersControlWidget::createParametersVirtual () const [inline, virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 25 of file openCVFilterParametersControlWidget.h.
References createParameters().
    {
        return createParameters();
    }
void OpenCVFilterParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Definition at line 34 of file openCVFilterParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    OpenCVFilterParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void OpenCVFilterParametersControlWidget::paramsChanged () [signal]
Reimplemented from FilterParametersControlWidgetBase.
Referenced by OpenCVFilterParametersControlWidget(), and setParameters().
void OpenCVFilterParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Definition at line 42 of file openCVFilterParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    OpenCVFilterParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
void OpenCVFilterParametersControlWidget::setParameters (const OpenCVFilterParameters & input)
Definition at line 66 of file openCVFilterParametersControlWidget.cpp.
References mUi, OpenCVFilterParameters::openCVFilter(), OpenCVFilterParameters::param1(), OpenCVFilterParameters::param2(), and paramsChanged().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->openCVFilterComboBox->setCurrentIndex(input.openCVFilter());
    mUi->param1SpinBox->setValue(input.param1());
    mUi->param2SpinBox->setValue(input.param2());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void OpenCVFilterParametersControlWidget::setParametersVirtual (void * input) [virtual]
Reimplemented from FilterParametersControlWidgetBase.
Definition at line 77 of file openCVFilterParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    OpenCVFilterParameters *inputCasted = static_cast<OpenCVFilterParameters *>(input);
    setParameters(*inputCasted);
}
void OpenCVFilterParametersControlWidget::valueChanged () [signal]
Referenced by OpenCVFilterParametersControlWidget().
Member Data Documentation
bool OpenCVFilterParametersControlWidget::autoInit [private]
Definition at line 45 of file openCVFilterParametersControlWidget.h.
Ui_OpenCVFilterParametersControlWidget* OpenCVFilterParametersControlWidget::mUi [private]
Definition at line 44 of file openCVFilterParametersControlWidget.h.
Referenced by createParameters(), OpenCVFilterParametersControlWidget(), setParameters(), and ~OpenCVFilterParametersControlWidget().
QString OpenCVFilterParametersControlWidget::rootPath [private]
Definition at line 46 of file openCVFilterParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/filters/ui/openCVFilterParametersControlWidget.h
utils/filters/ui/openCVFilterParametersControlWidget.cpp