DeepView: OpenCVCaptureInterface Class Reference
OpenCVCaptureInterface Class Reference
#include <openCVCapture.h>
Classes
class SpinThread
Public Types
enum CapErrorCode { SUCCESS = 0, SUCCESS_1CAM = 1, FAILURE = 2 }
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
OpenCVCaptureInterface (string _devname, unsigned int mode)
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual ~OpenCVCaptureInterface ()
virtual FramePair getFrameRGB24 ()
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&)
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode queryCameraParameters (CameraParameters &parameter)
Check if a specific property can be set/read and what values it can take.
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Public Attributes
SpinThread spin
FramePair current
QMutex protectFrame
unsigned int delay
Delay to sleep before querying OpenCV for a new frame in milliseconds.
CvCapture * captureLeft
CvCapture * captureRight
Static Public Attributes
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Detailed Description
Definition at line 33 of file openCVCapture.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapErrorCode [inherited]
Enumerator:
SUCCESS
SUCCESS_1CAM
FAILURE
Reimplemented in DirectShowCaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 72 of file imageCaptureInterface.h.
    {
        SUCCESS       = 0,
        SUCCESS_1CAM  = 1,
        FAILURE      = 2
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
Constructor & Destructor Documentation
OpenCVCaptureInterface::OpenCVCaptureInterface (string _devname, unsigned int mode)
Definition at line 17 of file openCVCapture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, CAP_ANY, CAP_DEFAULT_DELAY, CAP_DS, CAP_VFW, captureLeft, captureRight, current, delay, and SYNC_PRINT.
                                                                                  : spin(this)
{
    unsigned int domain = 0;
    if      (mode == CAP_ANY)
    {
        domain = CV_CAP_ANY;
        printf("OpenCVCapture: using ANY. Input: %s\n", _devname.c_str());
        fflush(stdout);
    }
    else if (mode == CAP_VFW)
    {
        domain = CV_CAP_VFW;
        printf("OpenCVCapture: using VFW. Input: %s\n", _devname.c_str());
        fflush(stdout);
    }
    else if (mode == CAP_DS)
    {
        domain = CV_CAP_DSHOW;
        printf("OpenCVCapture: using DirectShow. Input: %s\n", _devname.c_str());
        fflush(stdout);
    }
    QRegExp devStringPattern(QString("^(\\d*)(,(\\d*))?(,(\\d*)ms)?$"));
    static const int DEVICE_1_GROUP  = 1;
    static const int DEVICE_2_GROUP  = 3;
    static const int DELAY_GROUP     = 5;
    QString qdevname = QString::fromStdString(_devname);
    int result = devStringPattern.indexIn(qdevname);
    if (result == -1)
    {
        printf("Error in device string format <%s>\n", _devname.c_str());
        fflush(stdout);
        exit(EXIT_FAILURE);
    }
    bool err;
    int left_index  = devStringPattern.cap(DEVICE_1_GROUP).toInt(&err);
    int right_index = devStringPattern.cap(DEVICE_2_GROUP).toInt(&err);
    captureLeft  = 0;
    captureRight = 0;
    int id1 = left_index  + domain;
    int id2 = right_index + domain;
    SYNC_PRINT(("Calling first  cvCaptureFromCAM(%d)\n", id1));
    captureLeft = cvCaptureFromCAM(id1);
    SYNC_PRINT(("Calling second cvCaptureFromCAM(%d)\n", id1));
    captureRight = cvCaptureFromCAM(id2);
    if (!captureLeft && !captureRight)
    {
        printf("Both cameras failed to initialize");
        fflush(stdout);
        exit(EXIT_FAILURE);
    }
    // We assume that if there is only one camera active, it is the left camera
    if (!captureLeft && captureRight)
    {
        captureLeft  = captureRight;
        captureRight = 0;
    }
    delay = devStringPattern.cap(DELAY_GROUP).toInt(&err);
    if (!err)
        delay = CAP_DEFAULT_DELAY;
    current.bufferLeft  = new G12Buffer(800, 600, false);
    current.bufferRight = new G12Buffer(800, 600, false);
}
OpenCVCaptureInterface::~OpenCVCaptureInterface () [virtual]
Definition at line 219 of file openCVCapture.cpp.
References captureLeft, captureRight, spin, and OpenCVCaptureInterface::SpinThread::stop().
{
    spin.stop();
    spin.wait();
    cvReleaseCapture(&captureLeft);
    if (captureRight)
        cvReleaseCapture(&captureRight);
}
Member Function Documentation
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureName (QString & value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 171 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureProperty (int id, int * value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, DirectShowCaptureDecoupleInterface, V4L2CaptureInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 166 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by CapSettingsDialog::refreshDialog().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getDeviceName (int num, QString & name) [virtual, inherited]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented in DirectShowCaptureInterface, and V4L2CaptureInterface.
Definition at line 186 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getFormats (int * num, CameraFormat *&) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 176 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
OpenCVCaptureInterface::FramePair OpenCVCaptureInterface::getFrame () [virtual]
Main function to request frames from image interface.
Implements ImageCaptureInterface.
Definition at line 143 of file openCVCapture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, current, ImageCaptureInterface::FramePair::leftTimeStamp, protectFrame, and ImageCaptureInterface::FramePair::rightTimeStamp.
{
    protectFrame.lock();
        FramePair result;
        result.bufferLeft     = new G12Buffer(current.bufferLeft);
        result.bufferRight    = new G12Buffer(current.bufferRight);
        result.leftTimeStamp  = current.leftTimeStamp;
        result.rightTimeStamp = current.rightTimeStamp;
    protectFrame.unlock();
    return result;
}
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual, inherited]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
QString ImageCaptureInterface::getInterfaceName () [virtual, inherited]
Return the interface device string.
Reimplemented in V4L2CaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 181 of file imageCaptureInterface.cpp.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
{
    return "";
}
ImageCaptureInterface::CapErrorCode OpenCVCaptureInterface::initCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 190 of file openCVCapture.cpp.
References ImageCaptureInterface::SUCCESS.
{
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::queryCameraParameters (CameraParameters & parameter) [virtual, inherited]
Check if a specific property can be set/read and what values it can take.
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, DirectShowCaptureDecoupleInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 211 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::SUCCESS.
Referenced by CapSettingsDialog::refreshDialog().
{
    Q_UNUSED(parameter)
    return ImageCaptureInterface::SUCCESS;
}
ImageCaptureInterface::CapErrorCode OpenCVCaptureInterface::setCaptureProperty (int id, int value) [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 155 of file openCVCapture.cpp.
References CORE_UNUSED, and ImageCaptureInterface::FAILURE.
{
    CORE_UNUSED(id);
    CORE_UNUSED(value);
    /*
    int retL = -1;
    int retR = -1;
    switch (propID)
    {
    case (ImageCaptureInterface::CAP_PROP_WIDTH):
        {
            if (captureLeft)
                retL = cvSetCaptureProperty(captureLeft, CV_CAP_PROP_FRAME_WIDTH, propValue);
            if (captureRight)
                retR = cvSetCaptureProperty(captureRight, CV_CAP_PROP_FRAME_WIDTH, propValue);
            break;
        }
    case (ImageCaptureInterface::CAP_PROP_HEIGHT):
        {
            if (captureLeft)
                retL = cvSetCaptureProperty(captureLeft, CV_CAP_PROP_FRAME_HEIGHT, propValue);
            if (captureRight)
                retR = cvSetCaptureProperty(captureRight, CV_CAP_PROP_FRAME_HEIGHT, propValue);
            break;
        }
    default:
        return ImageCaptureInterface::CAP_FAILURE;
    }
    return (ImageCaptureInterface::CapErrorCode) ((bool) retL + (bool) retR);
    */
    return ImageCaptureInterface::FAILURE;
}
ImageCaptureInterface::CapErrorCode OpenCVCaptureInterface::startCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 195 of file openCVCapture.cpp.
References captureLeft, captureRight, and spin.
{
    int retL = -1;
    int retR = -1;
    if (captureLeft)
    {
        retL = !cvSetCaptureProperty(captureLeft, CV_CAP_PROP_FRAME_WIDTH, 800);
        // retL |= cvSetCaptureProperty(captureLeft, CV_CAP_PROP_FRAME_HEIGHT, 600);
    }
    if (captureRight)
    {
        retR = !cvSetCaptureProperty(captureRight, CV_CAP_PROP_FRAME_WIDTH, 800);
        //retR |= cvSetCaptureProperty(captureRight, CV_CAP_PROP_FRAME_HEIGHT, 600);
    }
    qDebug("Setting 800x600: retL == %d, retR == %d\n", retL, retR);
    spin.start();
    return (ImageCaptureInterface::CapErrorCode) ((bool) retL + (bool) retR);
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
Member Data Documentation
CvCapture* OpenCVCaptureInterface::captureLeft
Definition at line 65 of file openCVCapture.h.
Referenced by OpenCVCaptureInterface(), OpenCVCaptureInterface::SpinThread::run(), startCapture(), and ~OpenCVCaptureInterface().
CvCapture * OpenCVCaptureInterface::captureRight
Definition at line 65 of file openCVCapture.h.
Referenced by OpenCVCaptureInterface(), OpenCVCaptureInterface::SpinThread::run(), startCapture(), and ~OpenCVCaptureInterface().
FramePair OpenCVCaptureInterface::current
Definition at line 55 of file openCVCapture.h.
Referenced by getFrame(), OpenCVCaptureInterface(), and OpenCVCaptureInterface::SpinThread::run().
unsigned int OpenCVCaptureInterface::delay
Delay to sleep before querying OpenCV for a new frame in milliseconds.
Definition at line 63 of file openCVCapture.h.
Referenced by OpenCVCaptureInterface(), and OpenCVCaptureInterface::SpinThread::run().
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
QMutex OpenCVCaptureInterface::protectFrame
Definition at line 56 of file openCVCapture.h.
Referenced by getFrame(), and OpenCVCaptureInterface::SpinThread::run().
SpinThread OpenCVCaptureInterface::spin
Definition at line 54 of file openCVCapture.h.
Referenced by startCapture(), and ~OpenCVCaptureInterface().
The documentation for this class was generated from the following files:
utils/framesources/openCVCapture.h
utils/framesources/openCVCapture.cpp