DeepView: corecvs::AxisAlignedBox3d Class Reference
corecvs::AxisAlignedBox3d Class Reference
#include <mesh3d.h>
Public Member Functions
AxisAlignedBox3d ()
AxisAlignedBox3d (const Vector3dd &low, const Vector3dd &high)
AxisAlignedBox3d (const AxisAlignedBoxParameters &params)
void _initByLowHigh (const Vector3dd &low, const Vector3dd &high)
void _initByCenter (const Vector3dd &center, const Vector3dd &measure)
bool contains (const Vector3dd &vector) const
const Vector3dd & low () const
const Vector3dd & high () const
double width () const
double height () const
double depth () const
Vector3dd getCenter ()
void getPoints (Vector3dd points[8])
Static Public Member Functions
static AxisAlignedBox3d ByCenter (const Vector3dd &center, const Vector3dd &measure)
Private Attributes
Vector3dd mLow
Vector3dd mHigh
Detailed Description
Definition at line 15 of file mesh3d.h.
Constructor & Destructor Documentation
corecvs::AxisAlignedBox3d::AxisAlignedBox3d () [inline]
Definition at line 21 of file mesh3d.h.
References _initByLowHigh().
    {
        _initByLowHigh(Vector3dd(0.0), Vector3dd(0.0));
    }
corecvs::AxisAlignedBox3d::AxisAlignedBox3d (const Vector3dd & low, const Vector3dd & high) [inline]
Definition at line 26 of file mesh3d.h.
References _initByLowHigh().
    {
        _initByLowHigh(low, high);
    }
corecvs::AxisAlignedBox3d::AxisAlignedBox3d (const AxisAlignedBoxParameters & params) [inline]
Definition at line 31 of file mesh3d.h.
References _initByCenter(), AxisAlignedBoxParameters::depth(), AxisAlignedBoxParameters::height(), AxisAlignedBoxParameters::width(), AxisAlignedBoxParameters::x(), AxisAlignedBoxParameters::y(), and AxisAlignedBoxParameters::z().
    {
        Vector3dd measure(params.width(), params.height(), params.depth());
        Vector3dd center (params.x()    , params.y()     , params.z    ());
        _initByCenter(center, measure);
    }
Member Function Documentation
void corecvs::AxisAlignedBox3d::_initByCenter (const Vector3dd & center, const Vector3dd & measure) [inline]
Definition at line 52 of file mesh3d.h.
References _initByLowHigh().
Referenced by AxisAlignedBox3d(), and ByCenter().
    {
        _initByLowHigh((center - measure / 2.0), (center + measure / 2.0));
    }
void corecvs::AxisAlignedBox3d::_initByLowHigh (const Vector3dd & low, const Vector3dd & high) [inline]
Definition at line 39 of file mesh3d.h.
References mHigh, mLow, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
Referenced by _initByCenter(), and AxisAlignedBox3d().
    {
        /* TODO: Move this to vector opetions and use cycle */
        mLow .x() = std::min(low.x(), high.x());
        mHigh.x() = std::max(low.x(), high.x());
        mLow .y() = std::min(low.y(), high.y());
        mHigh.y() = std::max(low.y(), high.y());
        mLow .z() = std::min(low.z(), high.z());
        mHigh.z() = std::max(low.z(), high.z());
    }
static AxisAlignedBox3d corecvs::AxisAlignedBox3d::ByCenter (const Vector3dd & center, const Vector3dd & measure) [inline, static]
Definition at line 57 of file mesh3d.h.
References _initByCenter().
    {
        AxisAlignedBox3d box;
        box._initByCenter(center, measure);
        return box;
    }
bool corecvs::AxisAlignedBox3d::contains (const Vector3dd & vector) const [inline]
Definition at line 64 of file mesh3d.h.
References corecvs::Vector3d< ElementType >::isInCube(), mHigh, and mLow.
Referenced by corecvs::Cloud::filterByAABB(), and corecvs::Buffer3d::pointInBox().
    {
        return vector.isInCube(mLow, mHigh);
    }
double corecvs::AxisAlignedBox3d::depth () const [inline]
Definition at line 85 of file mesh3d.h.
References mHigh, mLow, and corecvs::Vector3d< ElementType >::z().
{
        return mHigh.z() - mLow.z();
    }
Vector3dd corecvs::AxisAlignedBox3d::getCenter () [inline]
Definition at line 89 of file mesh3d.h.
References mHigh, and mLow.
    {
        return ((mLow + mHigh) / 2.0);
    }
void corecvs::AxisAlignedBox3d::getPoints (Vector3dd points[8]) [inline]
Definition at line 94 of file mesh3d.h.
References mHigh, mLow, corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
    {
        points[0] = Vector3dd(mLow .x() , mLow .y(), mLow.z());
        points[1] = Vector3dd(mHigh.x() , mLow .y(), mLow.z());
        points[2] = Vector3dd(mHigh.x() , mHigh.y(), mLow.z());
        points[3] = Vector3dd(mLow .x() , mHigh.y(), mLow.z());
        points[4] = Vector3dd(mLow .x() , mLow .y(), mHigh.z());
        points[5] = Vector3dd(mHigh.x() , mLow .y(), mHigh.z());
        points[6] = Vector3dd(mHigh.x() , mHigh.y(), mHigh.z());
        points[7] = Vector3dd(mLow .x() , mHigh.y(), mHigh.z());
    }
double corecvs::AxisAlignedBox3d::height () const [inline]
Definition at line 81 of file mesh3d.h.
References mHigh, mLow, and corecvs::Vector3d< ElementType >::y().
{
        return mHigh.y() - mLow.y();
    }
const Vector3dd& corecvs::AxisAlignedBox3d::high () const [inline]
Definition at line 73 of file mesh3d.h.
References mHigh.
Referenced by corecvs::Mesh3D::addAOB().
{
        return mHigh;
    }
const Vector3dd& corecvs::AxisAlignedBox3d::low () const [inline]
Definition at line 69 of file mesh3d.h.
References mLow.
Referenced by corecvs::Mesh3D::addAOB().
{
        return mLow;
    }
double corecvs::AxisAlignedBox3d::width () const [inline]
Definition at line 77 of file mesh3d.h.
References mHigh, mLow, and corecvs::Vector3d< ElementType >::x().
{
        return mHigh.x() - mLow.x();
    }
Member Data Documentation
Vector3dd corecvs::AxisAlignedBox3d::mHigh [private]
Definition at line 18 of file mesh3d.h.
Referenced by _initByLowHigh(), contains(), depth(), getCenter(), getPoints(), height(), high(), and width().
Vector3dd corecvs::AxisAlignedBox3d::mLow [private]
Definition at line 17 of file mesh3d.h.
Referenced by _initByLowHigh(), contains(), depth(), getCenter(), getPoints(), height(), low(), and width().
The documentation for this class was generated from the following file:
core/geometry/mesh3d.h