DeepView: corecvs::ObjectRef< Type > Class Template Reference
corecvs::ObjectRef< Type > Class Template Reference
This class is an smart pointer to the memory block.
#include <memoryBlock.h>
Public Member Functions
ObjectRef ()
ObjectRef (bool shouldAllocate)
ObjectBlock< Type > * allocate (size_t size=sizeof(Type), size_t alignMask=0)
In the worst case we will have to add align mask twice.
void * getBlockStart ()
Type * get ()
void * getAlignedStart (size_t alignMask)
int addRef ()
int freeRef ()
ObjectRef & operator= (const ObjectRef &other)
ObjectRef (const ObjectRef &other)
~ObjectRef ()
Public Attributes
ObjectBlock< Type > * block
Detailed Description
template<typename Type>
class corecvs::ObjectRef< Type >
This class is an smart pointer to the memory block.
It counts references to the block (counter is stored in a block itself)
This class can be used for two purposes. 1. Allocate a piece of memory with automatic reference count 2. Allocate an object with automatic reference count
Definition at line 63 of file memoryBlock.h.
Constructor & Destructor Documentation
template<typename Type> corecvs::ObjectRef< Type >::ObjectRef () [inline]
Definition at line 68 of file memoryBlock.h.
                : block(NULL)
    {
        DOTRACE(("Calling default constructor for ObjectRef<> at %p. Block at %p\n", (void *)this, (void *)block));
    }
template<typename Type> corecvs::ObjectRef< Type >::ObjectRef (bool shouldAllocate) [inline, explicit]
Definition at line 74 of file memoryBlock.h.
                                            : block(NULL)
    {
        DOTRACE(("Calling specific constructor for ObjectRef<> at %p. Block at %p\n", (void *)this, (void *)block ));
        if (shouldAllocate)
        {
            allocate();
        }
    }
template<typename Type> corecvs::ObjectRef< Type >::ObjectRef (const ObjectRef< Type > & other) [inline]
Definition at line 189 of file memoryBlock.h.
                                       : block( NULL )
    {
        operator =(other);
    }
template<typename Type> corecvs::ObjectRef< Type >::~ObjectRef () [inline]
Definition at line 195 of file memoryBlock.h.
    {
        freeRef();
    }
Member Function Documentation
template<typename Type> int corecvs::ObjectRef< Type >::addRef () [inline]
Definition at line 143 of file memoryBlock.h.
Referenced by corecvs::ObjectRef< MessageInternal >::allocate(), and corecvs::ObjectRef< MessageInternal >::operator=().
    {
        if (this->block == NULL)
        {
            return 0;
        }
        atomic_inc_and_fetch(&(block->refCount()));
        DOTRACE(("Reference for block %p Increment to %d\n", (void *)block, block->refCount()));
        return block->refCount();
    }
template<typename Type> ObjectBlock<Type>* corecvs::ObjectRef< Type >::allocate (size_t size = sizeof(Type), size_t alignMask = 0) [inline]
In the worst case we will have to add align mask twice.
Say we want to allocate 10 bytes with 4 byte alignment.
|---X XXXX XXXX X---|
Definition at line 92 of file memoryBlock.h.
Referenced by corecvs::FixedArrayBase< DiagonalMatrix, double >::_init(), corecvs::VoxelBufferBase< RealType, ElementType >::_init(), corecvs::AbstractBuffer< SegmentType * >::_init(), Log::MessageScoped::MessageScoped(), and corecvs::ObjectRef< MessageInternal >::ObjectRef().
    {
        if (this->block != NULL)
        {
            freeRef();
        }
        size_t totalSize = size + 2 * alignMask + sizeof(ObjectBlock<Type>) - sizeof(Type);
        void *rawBlock = new uint8_t[totalSize];
        if (rawBlock != NULL)
        {
            this->block = new(rawBlock) ObjectBlock<Type>();
            addRef();
        } /* Otherwise NULL will remain and we will return it */
        DOTRACE(("Calling allocate for MemoryBlockRef:\n"
                 "   Position is %p\n"
                 "   Raw position %p\n"
                 "   Size is %d\n"
                 "   Allocated size is %d\n"
                 "   Data start is %p\n"
                 "   Align start is %p\n",
                this->block,
                (void *)rawBlock,
                (int)size,
                (int)totalSize,
                getBlockStart(),
                getAlignedStart(alignMask)));
        return this->block;
    }
template<typename Type> int corecvs::ObjectRef< Type >::freeRef () [inline]
Definition at line 154 of file memoryBlock.h.
Referenced by corecvs::ObjectRef< MessageInternal >::allocate(), corecvs::ObjectRef< MessageInternal >::operator=(), and corecvs::ObjectRef< MessageInternal >::~ObjectRef().
    {
        if (this->block == NULL)
        {
            return 0;
        }
        ASSERT_FALSE_P(block->refCount() == 0, ("Block referenced by %p overfreed\n", (void *)this));
        DOTRACE(("Reference for block %p Decrement to %d\n", (void *)block, block->refCount() - 1));
        atomic_int new_count = atomic_dec_and_fetch(&(block->refCount()));
        if (new_count == 0)
        {
            block->~ObjectBlock<Type>();
            DOTRACE(("Deleting block %p\n", (void *)this->block));
            uint8_t *rawBlock = (uint8_t *)(void *)(this->block);
            delete[] rawBlock;
            this->block = NULL;
            return 0;
        }
        return block->refCount();
    }
template<typename Type> Type* corecvs::ObjectRef< Type >::get () [inline]
Definition at line 129 of file memoryBlock.h.
Referenced by LoggerWidget::doDrain(), StdStreamLogDrain::drain(), Log::MessageScoped::MessageScoped(), Log::MessageScoped::operator<<(), operator<<(), and Log::MessageScoped::~MessageScoped().
    {
        return &(block->data);
    }
template<typename Type> void* corecvs::ObjectRef< Type >::getAlignedStart (size_t alignMask) [inline]
Definition at line 135 of file memoryBlock.h.
Referenced by corecvs::FixedArrayBase< DiagonalMatrix, double >::_init(), corecvs::VoxelBufferBase< RealType, ElementType >::_init(), corecvs::AbstractBuffer< SegmentType * >::_init(), and corecvs::ObjectRef< MessageInternal >::allocate().
    {
        uintptr_t unalignedBlock = (uintptr_t)getBlockStart();
        uintptr_t   alignedBlock = (((unalignedBlock - 1) | alignMask) + 1);
        return (void *) alignedBlock;
    }
template<typename Type> void* corecvs::ObjectRef< Type >::getBlockStart () [inline]
Definition at line 124 of file memoryBlock.h.
Referenced by corecvs::ObjectRef< MessageInternal >::allocate(), and corecvs::ObjectRef< MessageInternal >::getAlignedStart().
    {
        return (void *)&(block->data);
    }
template<typename Type> ObjectRef& corecvs::ObjectRef< Type >::operator= (const ObjectRef< Type > & other) [inline]
Definition at line 177 of file memoryBlock.h.
Referenced by corecvs::ObjectRef< MessageInternal >::ObjectRef().
    {
        DOTRACE(("Assigning reference with block %p to reference with block %p\n", (void *)other.block, (void *)block));
        if (this->block != NULL)
        {
            freeRef();
        }
        this->block = other.block;
        addRef();
        return *this;
    }
Member Data Documentation
template<typename Type> ObjectBlock<Type>* corecvs::ObjectRef< Type >::block
Definition at line 66 of file memoryBlock.h.
Referenced by corecvs::ObjectRef< MessageInternal >::addRef(), corecvs::ObjectRef< MessageInternal >::allocate(), corecvs::ObjectRef< MessageInternal >::freeRef(), corecvs::ObjectRef< MessageInternal >::get(), corecvs::ObjectRef< MessageInternal >::getBlockStart(), corecvs::ObjectRef< MessageInternal >::ObjectRef(), and corecvs::ObjectRef< MessageInternal >::operator=().
The documentation for this class was generated from the following file:
core/buffers/memory/memoryBlock.h