DeepView: CoordinateFrame Class Reference
CoordinateFrame Class Reference
#include <coordinateFrame.h>
Public Types
enum SceneType { SCENE_3D, COORDINATE_FRAME }
Public Member Functions
CoordinateFrame ()
virtual ~CoordinateFrame ()
virtual void prepareMesh (CloudViewDialog *dialog)
virtual void drawMyself (CloudViewDialog *dialog)
virtual void dumpPCD (ostream &out)
virtual void dumpPLY (ostream &out)
virtual void setParameters (void *params)
virtual
ParametersControlWidgetBase * getContolWidget ()
virtual void commonSetup (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void commonTierdown (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void draw (CloudViewDialog *dialog)
virtual bool isComplexObject ()
Public Attributes
vector< QSharedPointer< Scene3D > > mChildren
Draw3dParameters mParameters
QString name
Scene3D * parent
SceneType type
Matrix44 transform
bool visible
Detailed Description
Definition at line 14 of file coordinateFrame.h.
Member Enumeration Documentation
enum Scene3D::SceneType [inherited]
Enumerator:
SCENE_3D
COORDINATE_FRAME
Definition at line 31 of file scene3D.h.
                   {
        SCENE_3D,
        COORDINATE_FRAME
    };
Constructor & Destructor Documentation
CoordinateFrame::CoordinateFrame ()
Definition at line 10 of file coordinateFrame.cpp.
References Scene3D::COORDINATE_FRAME, and Scene3D::type.
{
    type = Scene3D::COORDINATE_FRAME;
}
CoordinateFrame::~CoordinateFrame () [virtual]
Definition at line 15 of file coordinateFrame.cpp.
{
}
Member Function Documentation
void Scene3D::commonSetup (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 102 of file scene3D.cpp.
References corecvs::Matrix44::a(), CORE_UNUSED, Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), corecvs::RectificationResult::decomposition, Draw3dTextureGen::FORCE_TEXTURE, corecvs::RectificationResult::getCameraShift(), corecvs::CameraIntrinsics::getVFov(), Scene3D::initDecalState(), corecvs::Matrix44::inverted(), Frames::LEFT_FRAME, corecvs::RectificationResult::leftCamera, CloudViewDialog::mRectificationResult, corecvs::CameraIntrinsics::resolution, Frames::RIGHT_FRAME, corecvs::EssentialDecomposition::rotation, CloudViewDialog::texture(), Draw3dParameters::textureCorrodinates(), Draw3dParameters::textureScale(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        Matrix44 textureMatrix = Matrix44::Scale(parameters->textureScale());
        glEnable(GL_TEXTURE_GEN_S);
        glEnable(GL_TEXTURE_GEN_T);
        GLint mode = GL_OBJECT_LINEAR;
        glTexGeni (GL_S, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_S, GL_OBJECT_PLANE, &textureMatrix.a(0,0));
        glTexGeni (GL_T, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_T, GL_OBJECT_PLANE, &textureMatrix.a(1,0));
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        CameraIntrinsics *intrinsics = &(dialog->mRectificationResult->rightCamera);
        double fovR = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovR, aspect);
        glActiveTexture(GL_TEXTURE1);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::RIGHT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::RIGHT_FRAME));
            } else {
                qDebug() << "No texture for right camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE );
            initDecalState(dialog, parameters, projector);
        glActiveTexture(GL_TEXTURE0);
#else
        CORE_UNUSED(dialog);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        RectificationResult *rectification = dialog->mRectificationResult.data();
        CameraIntrinsics *intrinsics = &(rectification->leftCamera);
        double fovL = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovL, aspect);
        projector = projector * (Matrix44(rectification->decomposition.rotation) * Matrix44::Shift(rectification->getCameraShift())).inverted();
        glActiveTexture(GL_TEXTURE2);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::LEFT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::LEFT_FRAME));
            } else {
                qDebug() << "No texture for left camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL );
            initDecalState(dialog, parameters, projector);
        if (parameters->decalRightCam()) {
            qDebug() << "Both cameras. Making a merge";
            glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB, GL_INTERPOLATE);   //Interpolate RGB with RGB
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB, GL_SRC_COLOR);
            //------------------------
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_ALPHA, GL_INTERPOLATE);   //Interpolate ALPHA with ALPHA
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_ALPHA, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_ALPHA, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_ALPHA, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_ALPHA, GL_SRC_ALPHA);
            //------------------------
            float mycolor[4] = {0.5, 0.5, 0.5, 0.5};
            glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor);
        }
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::commonTierdown (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 202 of file scene3D.cpp.
References Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), Draw3dTextureGen::FORCE_TEXTURE, and Draw3dParameters::textureCorrodinates().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        glDisable(GL_TEXTURE_GEN_S);
        glDisable(GL_TEXTURE_GEN_T);
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE1);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE2);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::draw (CloudViewDialog * dialog) [virtual, inherited]
Definition at line 19 of file scene3D.cpp.
References Scene3D::drawMyself(), OpenGLTools::glMultMatrixMatrix44(), Scene3D::transform, and Scene3D::visible.
{
    if (!visible) {
//        qDebug() << name << "(" << ((void *)this) << ")" << " is invisible";
        return;
    }
//    qDebug() << name << "(" << ((void *)this) << ")" << " is drawn";
    glMatrixMode(GL_MODELVIEW);
    glPushMatrix();
      OpenGLTools::glMultMatrixMatrix44(transform);
      this->drawMyself(dialog);
    glPopMatrix();
}
void CoordinateFrame::drawMyself (CloudViewDialog * dialog) [virtual]
Reimplemented from Scene3D.
Definition at line 28 of file coordinateFrame.cpp.
References OpenGLTools::drawOrts(), mChildren, mParameters, Draw3dStyle::POINTS, and Draw3dParameters::style().
{
    //qDebug("Drawing coordinate frame");
    if (mParameters.style() != Draw3dStyle::POINTS) {
        OpenGLTools::drawOrts(10.0, 1.0);
    }
    for (unsigned i = 0; i < mChildren.size(); i++)
    {
            mChildren[i]->draw(dialog);
    }
}
void CoordinateFrame::dumpPCD (ostream & out) [virtual]
Reimplemented from Scene3D.
Definition at line 43 of file coordinateFrame.cpp.
{
}
void CoordinateFrame::dumpPLY (ostream & out) [virtual]
Reimplemented from Scene3D.
Definition at line 47 of file coordinateFrame.cpp.
{
}
virtual ParametersControlWidgetBase* CoordinateFrame::getContolWidget () [inline, virtual]
Reimplemented from Scene3D.
Definition at line 35 of file coordinateFrame.h.
References mParameters, and Draw3dParametersControlWidget::setParameters().
    {
        Draw3dParametersControlWidget *result = new Draw3dParametersControlWidget();
        result->setParameters(mParameters);
        return result;
    };
virtual bool Scene3D::isComplexObject () [inline, virtual, inherited]
Definition at line 64 of file scene3D.h.
References Scene3D::COORDINATE_FRAME, and Scene3D::type.
    {
        return (type == COORDINATE_FRAME);
    }
void CoordinateFrame::prepareMesh (CloudViewDialog * dialog) [virtual]
Reimplemented from Scene3D.
Definition at line 19 of file coordinateFrame.cpp.
References mChildren.
{
    for (unsigned i = 0; i < mChildren.size(); i++)
    {
          mChildren[i]->prepareMesh(dialog);
    }
}
virtual void CoordinateFrame::setParameters (void * params) [inline, virtual]
Reimplemented from Scene3D.
Definition at line 30 of file coordinateFrame.h.
References mParameters.
    {
        mParameters = *static_cast<Draw3dParameters *>(params);
    };
Member Data Documentation
vector<QSharedPointer<Scene3D> > CoordinateFrame::mChildren
Definition at line 17 of file coordinateFrame.h.
Referenced by TreeSceneController::addChildObject(), drawMyself(), prepareMesh(), and TreeSceneController::replaceScene().
Draw3dParameters CoordinateFrame::mParameters
Definition at line 18 of file coordinateFrame.h.
Referenced by drawMyself(), getContolWidget(), and setParameters().
QString Scene3D::name [inherited]
Definition at line 37 of file scene3D.h.
Referenced by CloudViewDialog::CloudViewDialog().
Scene3D* Scene3D::parent [inherited]
Definition at line 38 of file scene3D.h.
Matrix44 Scene3D::transform [inherited]
Definition at line 41 of file scene3D.h.
Referenced by Scene3D::draw().
SceneType Scene3D::type [inherited]
Definition at line 39 of file scene3D.h.
Referenced by CoordinateFrame(), and Scene3D::isComplexObject().
bool Scene3D::visible [inherited]
Definition at line 42 of file scene3D.h.
Referenced by Scene3D::draw().
The documentation for this class was generated from the following files:
utils/3d/coordinateFrame.h
utils/3d/coordinateFrame.cpp