DeepView: QTFileLoader Class Reference
QTFileLoader Class Reference
#include <qtFileLoader.h>
Public Member Functions
QTFileLoader ()
virtual ~QTFileLoader ()
virtual bool acceptsFile (string name)
virtual G12Buffer * load (string name)
Static Public Member Functions
static int registerMyself ()
static RGB24Buffer * RGB24BufferFromQImage (QImage *image)
Static Private Attributes
static int DUMMY = 1
This is a form of dirty hack to be sure that int QT builds loading QT images will always work without any change of code.
Detailed Description
Definition at line 22 of file qtFileLoader.h.
Constructor & Destructor Documentation
QTFileLoader::QTFileLoader ()
Definition at line 18 of file qtFileLoader.cpp.
{
    // TODO Auto-generated constructor stub
}
QTFileLoader::~QTFileLoader () [virtual]
Definition at line 24 of file qtFileLoader.cpp.
{
    // TODO Auto-generated destructor stub
}
Member Function Documentation
bool QTFileLoader::acceptsFile (string name) [virtual]
Implements corecvs::BufferLoader< G12Buffer >.
Definition at line 58 of file qtFileLoader.cpp.
{
    return true;
}
G12Buffer * QTFileLoader::load (string name) [virtual]
TODO: Make this faster using .bits() method. So far don't want to mess with possible image formats
Implements corecvs::BufferLoader< G12Buffer >.
Definition at line 29 of file qtFileLoader.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element().
{
    QString qtName = QString::fromStdString(name);
    QImage image(qtName);
    if (image.isNull())
        return NULL;
    G12Buffer *result = new G12Buffer(image.height(), image.width(), false);
    /**
     * TODO: Make this faster using .bits() method.
     * So far don't want to mess with possible image formats
     *
     */
    for (int i = 0; i < image.height(); i++)
    {
        for (int j = 0; j < image.width(); j++)
        {
            QRgb pixel = image.pixel(j,i);
            // Do conversion without qGray to possibly save 9-th bit
            uint16_t gray = (11 * qRed(pixel) + 16 * qGreen(pixel) + 5 * qBlue(pixel)) >> 1;
            result->element(i,j) = gray;
        }
    }
    return result;
}
static int QTFileLoader::registerMyself () [inline, static]
Definition at line 31 of file qtFileLoader.h.
Referenced by main().
    {
        BufferFactory::getInstance()->registerLoader(new QTFileLoader());   // TODO: memory leak: this loader is never destroyed!!!
        return 0;
    }
RGB24Buffer * QTFileLoader::RGB24BufferFromQImage (QImage * image) [static]
TODO: Make this faster using .bits() method. So far don't want to mess with possible image formats
Definition at line 64 of file qtFileLoader.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element().
Referenced by TestbedMainWindow::loadImage().
{
    if (image == NULL)
        return NULL;
    RGB24Buffer *result = new RGB24Buffer(image->height(), image->width(), false);
    /**
     * TODO: Make this faster using .bits() method.
     * So far don't want to mess with possible image formats
     *
     */
    for (int i = 0; i < image->height(); i++)
    {
        for (int j = 0; j < image->width(); j++)
        {
            QRgb pixel = image->pixel(j,i);
            result->element(i,j) = RGBColor(qRed(pixel), qGreen(pixel), qBlue(pixel));
        }
    }
    return result;
}
Member Data Documentation
int QTFileLoader::DUMMY = 1 [static, private]
This is a form of dirty hack to be sure that int QT builds loading QT images will always work without any change of code.
Definition at line 25 of file qtFileLoader.h.
The documentation for this class was generated from the following files:
utils/fileformats/qtFileLoader.h
utils/fileformats/qtFileLoader.cpp