DeepView: Scene3D Class Reference
Scene3D Class Reference
Part of the hierarchically displayable scene.
#include <scene3D.h>
Public Types
enum SceneType { SCENE_3D, COORDINATE_FRAME }
Public Member Functions
virtual void commonSetup (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void commonTierdown (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void draw (CloudViewDialog *dialog)
virtual void prepareMesh (CloudViewDialog *dialog)
virtual void drawMyself (CloudViewDialog *dialog)
virtual void dumpPCD (ostream &out)
virtual void dumpPLY (ostream &out)
virtual void setParameters (void *)
virtual
ParametersControlWidgetBase * getContolWidget ()
virtual bool isComplexObject ()
Scene3D ()
virtual ~Scene3D ()
Public Attributes
QString name
Scene3D * parent
SceneType type
Matrix44 transform
bool visible
Private Member Functions
void initDecalState (CloudViewDialog *dialog, const Draw3dParameters *parameters, Matrix44 &projector)
Detailed Description
Part of the hierarchically displayable scene.
Definition at line 25 of file scene3D.h.
Member Enumeration Documentation
enum Scene3D::SceneType
Enumerator:
SCENE_3D
COORDINATE_FRAME
Definition at line 31 of file scene3D.h.
                   {
        SCENE_3D,
        COORDINATE_FRAME
    };
Constructor & Destructor Documentation
Scene3D::Scene3D () [inline]
Definition at line 69 of file scene3D.h.
              :
        parent(NULL),
        type(SCENE_3D),
        transform(1.0),
        visible(true)
    {}
Scene3D::~Scene3D () [virtual]
Definition at line 15 of file scene3D.cpp.
{
}
Member Function Documentation
void Scene3D::commonSetup (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual]
Definition at line 102 of file scene3D.cpp.
References corecvs::Matrix44::a(), CORE_UNUSED, Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), corecvs::RectificationResult::decomposition, Draw3dTextureGen::FORCE_TEXTURE, corecvs::RectificationResult::getCameraShift(), corecvs::CameraIntrinsics::getVFov(), initDecalState(), corecvs::Matrix44::inverted(), Frames::LEFT_FRAME, corecvs::RectificationResult::leftCamera, CloudViewDialog::mRectificationResult, corecvs::CameraIntrinsics::resolution, Frames::RIGHT_FRAME, corecvs::EssentialDecomposition::rotation, CloudViewDialog::texture(), Draw3dParameters::textureCorrodinates(), Draw3dParameters::textureScale(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        Matrix44 textureMatrix = Matrix44::Scale(parameters->textureScale());
        glEnable(GL_TEXTURE_GEN_S);
        glEnable(GL_TEXTURE_GEN_T);
        GLint mode = GL_OBJECT_LINEAR;
        glTexGeni (GL_S, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_S, GL_OBJECT_PLANE, &textureMatrix.a(0,0));
        glTexGeni (GL_T, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_T, GL_OBJECT_PLANE, &textureMatrix.a(1,0));
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        CameraIntrinsics *intrinsics = &(dialog->mRectificationResult->rightCamera);
        double fovR = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovR, aspect);
        glActiveTexture(GL_TEXTURE1);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::RIGHT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::RIGHT_FRAME));
            } else {
                qDebug() << "No texture for right camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE );
            initDecalState(dialog, parameters, projector);
        glActiveTexture(GL_TEXTURE0);
#else
        CORE_UNUSED(dialog);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        RectificationResult *rectification = dialog->mRectificationResult.data();
        CameraIntrinsics *intrinsics = &(rectification->leftCamera);
        double fovL = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovL, aspect);
        projector = projector * (Matrix44(rectification->decomposition.rotation) * Matrix44::Shift(rectification->getCameraShift())).inverted();
        glActiveTexture(GL_TEXTURE2);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::LEFT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::LEFT_FRAME));
            } else {
                qDebug() << "No texture for left camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL );
            initDecalState(dialog, parameters, projector);
        if (parameters->decalRightCam()) {
            qDebug() << "Both cameras. Making a merge";
            glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB, GL_INTERPOLATE);   //Interpolate RGB with RGB
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB, GL_SRC_COLOR);
            //------------------------
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_ALPHA, GL_INTERPOLATE);   //Interpolate ALPHA with ALPHA
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_ALPHA, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_ALPHA, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_ALPHA, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_ALPHA, GL_SRC_ALPHA);
            //------------------------
            float mycolor[4] = {0.5, 0.5, 0.5, 0.5};
            glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor);
        }
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::commonTierdown (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual]
Definition at line 202 of file scene3D.cpp.
References Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), Draw3dTextureGen::FORCE_TEXTURE, and Draw3dParameters::textureCorrodinates().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        glDisable(GL_TEXTURE_GEN_S);
        glDisable(GL_TEXTURE_GEN_T);
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE1);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE2);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::draw (CloudViewDialog * dialog) [virtual]
Definition at line 19 of file scene3D.cpp.
References drawMyself(), OpenGLTools::glMultMatrixMatrix44(), transform, and visible.
{
    if (!visible) {
//        qDebug() << name << "(" << ((void *)this) << ")" << " is invisible";
        return;
    }
//    qDebug() << name << "(" << ((void *)this) << ")" << " is drawn";
    glMatrixMode(GL_MODELVIEW);
    glPushMatrix();
      OpenGLTools::glMultMatrixMatrix44(transform);
      this->drawMyself(dialog);
    glPopMatrix();
}
void Scene3D::drawMyself (CloudViewDialog * dialog) [virtual]
Reimplemented in StereoCameraScene, CameraScene, Plane3DScene, Grid3DScene, Mesh3DScene, Scene3DMouse, and CoordinateFrame.
Definition at line 241 of file scene3D.cpp.
Referenced by draw().
{
    //qDebug() << "Calling Scene3D::Scene3D::drawMyself() for" << name;
}
void Scene3D::dumpPCD (ostream & out) [virtual]
Reimplemented in Mesh3DScene, Scene3DMouse, and CoordinateFrame.
Definition at line 246 of file scene3D.cpp.
{
}
void Scene3D::dumpPLY (ostream & out) [virtual]
Reimplemented in Mesh3DScene, Scene3DMouse, and CoordinateFrame.
Definition at line 251 of file scene3D.cpp.
{
}
virtual ParametersControlWidgetBase* Scene3D::getContolWidget () [inline, virtual]
Reimplemented in CameraScene, Mesh3DScene, CoordinateFrame, and Scene3DMouse.
Definition at line 58 of file scene3D.h.
    {
//        qDebug("Scene3D::getContolWidget() : Called");
        return NULL;
    };
void Scene3D::initDecalState (CloudViewDialog * dialog, const Draw3dParameters * parameters, Matrix44 & projector) [private]
Definition at line 35 of file scene3D.cpp.
References corecvs::Matrix44::a(), Draw3dParameters::decalMatrixType(), corecvs::Matrix44::inverted(), CloudViewDialog::mCamera, and corecvs::Matrix44::transposed().
Referenced by commonSetup().
{
    glEnable(GL_TEXTURE_GEN_S);
    glEnable(GL_TEXTURE_GEN_T);
    glEnable(GL_TEXTURE_GEN_R);
    glEnable(GL_TEXTURE_GEN_Q);
    qDebug() << "Decal Matrix type " << parameters->decalMatrixType();
    bool eyeLinear =  (parameters->decalMatrixType() % 10) < 5;
    GLint decalMode = eyeLinear ? GL_EYE_LINEAR : GL_OBJECT_LINEAR;
    GLint planeMode = eyeLinear ? GL_EYE_PLANE  : GL_OBJECT_PLANE;
    glTexGeni (GL_S, GL_TEXTURE_GEN_MODE, decalMode);
    glTexGeni (GL_T, GL_TEXTURE_GEN_MODE, decalMode);
    glTexGeni (GL_R, GL_TEXTURE_GEN_MODE, decalMode);
    glTexGeni (GL_Q, GL_TEXTURE_GEN_MODE, decalMode);
    Matrix44 bias = Matrix44(Matrix33::Scale3(0.5), Vector3dd(0.5, 0.5, 0.5));
    /*double zNear = 0.5;
    double zFar  = 100.0;
    double fovyRad = degToRad(45);
    double f = 1.0 / tan(fovyRad / 2);
    double zDepth = zNear - zFar;
    Matrix44 matrixProj (
        f / 1.0   , 0 ,             0          ,            0            ,
        0         ,-f ,             0          ,            0            ,
        0         , 0 , -(zFar + zNear) / zDepth, 2 *zFar * zNear / zDepth,
        0         , 0 ,             1          ,            0
    );*/
    Matrix44 texGen(1.0);
    switch( parameters->decalMatrixType() % 5)
    {
        case 0: texGen = Matrix44(1.0);                           break;
        case 1: texGen = dialog->mCamera.inverted();              break;
        case 2: texGen = dialog->mCamera;                         break;
        case 3: texGen = dialog->mCamera.inverted().transposed(); break;
        case 4: texGen = dialog->mCamera.transposed();            break;
    }
    if (parameters->decalMatrixType() > 10)
    {
        texGen = bias * projector * texGen;
    }
    cout << texGen << endl;
    if (eyeLinear) {
        glMatrixMode(GL_MODELVIEW);
        glPushMatrix();
        glLoadIdentity();
    }
    glTexGendv(GL_S, planeMode, &texGen.a(0,0));
    glTexGendv(GL_T, planeMode, &texGen.a(1,0));
    glTexGendv(GL_R, planeMode, &texGen.a(2,0));
    glTexGendv(GL_Q, planeMode, &texGen.a(3,0));
    if (eyeLinear) {
        glPopMatrix();
    }
}
virtual bool Scene3D::isComplexObject () [inline, virtual]
Definition at line 64 of file scene3D.h.
References COORDINATE_FRAME, and type.
    {
        return (type == COORDINATE_FRAME);
    }
void Scene3D::prepareMesh (CloudViewDialog * dialog) [virtual]
Reimplemented in StereoCameraScene, CameraScene, Plane3DScene, Grid3DScene, Mesh3DScene, and CoordinateFrame.
Definition at line 235 of file scene3D.cpp.
{
}
virtual void Scene3D::setParameters (void *) [inline, virtual]
Reimplemented in CameraScene, Scene3DMouse, Mesh3DScene, and CoordinateFrame.
Definition at line 55 of file scene3D.h.
{};
Member Data Documentation
QString Scene3D::name
Definition at line 37 of file scene3D.h.
Referenced by CloudViewDialog::CloudViewDialog().
Scene3D* Scene3D::parent
Definition at line 38 of file scene3D.h.
Matrix44 Scene3D::transform
Definition at line 41 of file scene3D.h.
Referenced by draw().
SceneType Scene3D::type
Definition at line 39 of file scene3D.h.
Referenced by CoordinateFrame::CoordinateFrame(), and isComplexObject().
bool Scene3D::visible
Definition at line 42 of file scene3D.h.
Referenced by draw().
The documentation for this class was generated from the following files:
utils/3d/scene3D.h
utils/3d/scene3D.cpp