DeepView: FilterFabric Class Reference
FilterFabric Class Reference
#include <basefilter.h>
Static Public Member Functions
static BaseFilter * createFilterInstance (QString name)
static QVector< QString > getFilterNames ()
Detailed Description
Definition at line 40 of file basefilter.h.
Member Function Documentation
BaseFilter * FilterFabric::createFilterInstance (QString name) [static]
Definition at line 25 of file basefilter.cpp.
References SobelFilter::getName(), ScaleFilter::getName(), BitSelector::getName(), and GainOffset::getName().
{
//    if (name == QString(BaseFilter::getName()))
//        return new BaseFilter();
    if (name == QString(GainOffset::getName()))
        return new GainOffset();
    if (name == QString(BitSelector::getName()))
        return new BitSelector();
    if (name == QString(SobelFilter::getName()))
        return new SobelFilter();
    if (name == QString(ScaleFilter::getName()))
        return new ScaleFilter();
    return NULL;
}
QVector< QString > FilterFabric::getFilterNames () [static]
Definition at line 40 of file basefilter.cpp.
References SobelFilter::getName(), ScaleFilter::getName(), BitSelector::getName(), and GainOffset::getName().
{
    QVector<QString> list;
//    list.append(BaseFilter::getName());
    list.append(GainOffset::getName());
    list.append(BitSelector::getName());
    list.append(SobelFilter::getName());
    list.append(ScaleFilter::getName());
    return list;
}
The documentation for this class was generated from the following files:
utils/filters/legacy/basefilter.h
utils/filters/legacy/basefilter.cpp