DeepView: HistogramDialog Class Reference
HistogramDialog Class Reference
#include <histogramdialog.h>
Public Slots
void notifyBufferChangeSlot (G12Buffer *buf)
void notifyHistogramChangeSlot (Histogram *buf)
void doUpdate (void)
Public Member Functions
HistogramDialog (QWidget *parent=0)
~HistogramDialog ()
Public Attributes
bool isInternal
Histogram * histogram
Private Attributes
Ui_HistogramDialogClass ui
Detailed Description
Definition at line 11 of file histogramdialog.h.
Constructor & Destructor Documentation
HistogramDialog::HistogramDialog (QWidget * parent = 0)
Definition at line 3 of file histogramdialog.cpp.
References doUpdate(), histogram, isInternal, and ui.
    : QDialog(parent)
{
    ui.setupUi(this);
//    connect(this,SIGNAL(notifyBufferChange(G12Buffer *)), ui.widget, SLOT(notifyBufferChange(G12Buffer *)));
    connect(ui.marginBox, SIGNAL(stateChanged(int)), this, SLOT(doUpdate()));
    isInternal = false;
    histogram = NULL;
}
HistogramDialog::~HistogramDialog ()
Definition at line 55 of file histogramdialog.cpp.
{
}
Member Function Documentation
void HistogramDialog::doUpdate (void) [slot]
Definition at line 43 of file histogramdialog.cpp.
References histogram, and ui.
Referenced by HistogramDialog(), notifyBufferChangeSlot(), and notifyHistogramChangeSlot().
{
    ui.widget->notifyHistogramChange(histogram, ui.marginBox->isChecked());
    if (histogram != NULL)
    {
        ui.maxLabel->setText(QString("%1").arg(histogram->getMaximum()));
        ui.statistics->setText(QString("L-%1 (%2%) H-%3(%4%)").
                arg(histogram->getUnderExpo()).arg(histogram->getUnderExpoRel() * 100.0).
                arg(histogram->getOverExpo()).arg(histogram->getOverExpoRel() * 100.0));
    }
}
void HistogramDialog::notifyBufferChangeSlot (G12Buffer * buf) [slot]
Definition at line 13 of file histogramdialog.cpp.
References doUpdate(), histogram, and isInternal.
{
    if (isInternal && histogram != NULL)
    {
        delete histogram;
    }
    histogram = NULL;
    if (buffer != NULL)
    {
        isInternal = true;
        histogram = new Histogram(buffer);
    }
    doUpdate();
}
void HistogramDialog::notifyHistogramChangeSlot (Histogram * buf) [slot]
Definition at line 30 of file histogramdialog.cpp.
References doUpdate(), histogram, and isInternal.
{
    if (isInternal && histogram != NULL)
    {
        delete histogram;
    }
    histogram = _histogram;
    isInternal = false;
    doUpdate();
}
Member Data Documentation
Histogram* HistogramDialog::histogram
Definition at line 29 of file histogramdialog.h.
Referenced by doUpdate(), HistogramDialog(), notifyBufferChangeSlot(), and notifyHistogramChangeSlot().
bool HistogramDialog::isInternal
Definition at line 28 of file histogramdialog.h.
Referenced by HistogramDialog(), notifyBufferChangeSlot(), and notifyHistogramChangeSlot().
Ui_HistogramDialogClass HistogramDialog::ui [private]
Definition at line 32 of file histogramdialog.h.
Referenced by doUpdate(), and HistogramDialog().
The documentation for this class was generated from the following files:
utils/corestructs/histogramdialog.h
utils/corestructs/histogramdialog.cpp