DeepView: corecvs::VJSimpleClassifier Class Reference
corecvs::VJSimpleClassifier Class Reference
#include <vjPattern.h>
Public Types
typedef VJInputImage InputType
Public Member Functions
VJSimpleClassifier ()
VJSimpleClassifier (VJPattern *pattern, int _thersthod, int _leftMargin, int _topMargin, int _bottonMargin, int _rightMargin)
bool classify (const VJInputImage &input)
bool applyToPoint (G12IntegralBuffer *buffer, int y, int x)
void print ()
RGB24Buffer * drawPattern ()
VJSimpleClassifier * scale (double scale)
bool classify (const VJInputImage &) const
Public Attributes
VJPattern * pattern
int thershold
int leftMargin
int topMargin
int bottomMargin
int rightMargin
Friends
ostream & operator<< (ostream &out, VJSimpleClassifier &toSave)
istream & operator>> (istream &in, VJSimpleClassifier &toLoad)
Detailed Description
Definition at line 169 of file vjPattern.h.
Member Typedef Documentation
typedef VJInputImage corecvs::Classifier< VJInputImage >::InputType [inherited]
Definition at line 137 of file adaBoost.h.
Constructor & Destructor Documentation
corecvs::VJSimpleClassifier::VJSimpleClassifier () [inline]
Definition at line 179 of file vjPattern.h.
    {
        memset(this, 0 , sizeof (VJSimpleClassifier));
    }
corecvs::VJSimpleClassifier::VJSimpleClassifier (VJPattern * pattern, int _thersthod, int _leftMargin, int _topMargin, int _bottonMargin, int _rightMargin) [inline]
Definition at line 185 of file vjPattern.h.
                                   :
            pattern(pattern),
            thershold(_thersthod),
            leftMargin(_leftMargin),
            topMargin(_topMargin),
            bottomMargin(_bottonMargin),
            rightMargin(_rightMargin)
    {
    }
Member Function Documentation
bool corecvs::VJSimpleClassifier::applyToPoint (G12IntegralBuffer * buffer, int y, int x) [inline]
In fact in this case should return something more intelligent
Definition at line 207 of file vjPattern.h.
References corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
Referenced by corecvs::VJAdaBoostedClassifier::applyToPoint().
    {
        if (y < topMargin  || y > buffer->h - bottomMargin ||
            x < leftMargin || x > buffer->w - rightMargin)
        {
            /** In fact in this case should return something more intelligent*/
                return false;
        }
        int result = pattern->applyToPoint(buffer, y, x);
        if (result > thershold)
            return true;
        return false;
    }
bool corecvs::Classifier< VJInputImage >::classify (const VJInputImage &) const [inline, inherited]
Definition at line 139 of file adaBoost.h.
    {
        return false;
    };
bool corecvs::VJSimpleClassifier::classify (const VJInputImage & input) [inline]
Definition at line 202 of file vjPattern.h.
References corecvs::VJInputImage::integral.
Referenced by corecvs::AdaBoostedClassifier< VJSimpleClassifier >::classify().
    {
        return applyToPoint(input.integral, 0, 0);
    }
RGB24Buffer* corecvs::VJSimpleClassifier::drawPattern () [inline]
Definition at line 246 of file vjPattern.h.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBuffer< ElementType, IndexType >::fillWith(), corecvs::PatternCorner::multiplier, corecvs::PatternCorner::point, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        int h = bottomMargin - topMargin;
        int w = rightMargin - leftMargin;
        G12Buffer *canvas = new G12Buffer(h, w, false);
        canvas->fillWith(G12Buffer::BUFFER_MAX_VALUE >> 2);
        for (unsigned l = 0; l < pattern->points.size(); l++)
        {
            PatternCorner *point = &(pattern->points.at(l));
            for (int i = 0; i < point->point.y() + topMargin; i++)
            {
                for (int j = 0; j < point->point.x() + leftMargin; j++)
                {
                    canvas->element(i,j) += point->multiplier * 256 * 2;
                }
            }
        }
        return new RGB24Buffer(canvas);
    }
void corecvs::VJSimpleClassifier::print () [inline]
Definition at line 230 of file vjPattern.h.
    {
        cout << this;
    }
VJSimpleClassifier* corecvs::VJSimpleClassifier::scale (double scale) [inline]
Definition at line 270 of file vjPattern.h.
References bottomMargin, corecvs::fround(), leftMargin, pattern, rightMargin, corecvs::VJPattern::scale(), thershold, and topMargin.
    {
        VJSimpleClassifier *toReturn = new VJSimpleClassifier();
        toReturn->thershold    = fround(thershold * scale * scale);
        toReturn->leftMargin   = fround(leftMargin * scale);
        toReturn->topMargin    = fround(leftMargin * scale);
        toReturn->bottomMargin = fround(leftMargin * scale);
        toReturn->rightMargin  = fround(leftMargin * scale);
        toReturn->pattern = pattern->scale(scale);
        return toReturn;
    }
Friends And Related Function Documentation
ostream& operator<< (ostream & out, VJSimpleClassifier & toSave) [friend]
Definition at line 221 of file vjPattern.h.
    {
        out << toSave.leftMargin << " " << toSave.topMargin << " ";
        out << toSave.rightMargin << " " << toSave.bottomMargin << "\n";
        out << toSave.thershold << "\n";
        out << toSave.pattern << "\n";
        return out;
    }
istream& operator>> (istream & in, VJSimpleClassifier & toLoad) [friend]
Definition at line 236 of file vjPattern.h.
    {
        in >> toLoad.leftMargin >> toLoad.topMargin;
        in >> toLoad.rightMargin >> toLoad.bottomMargin;
        in >> toLoad.thershold;
        toLoad.pattern = new VJPattern();
        in >> (*toLoad.pattern);
        return in;
    }
Member Data Documentation
int corecvs::VJSimpleClassifier::bottomMargin
Definition at line 176 of file vjPattern.h.
Referenced by scale().
int corecvs::VJSimpleClassifier::leftMargin
Definition at line 174 of file vjPattern.h.
Referenced by scale().
VJPattern* corecvs::VJSimpleClassifier::pattern
Definition at line 172 of file vjPattern.h.
Referenced by scale().
int corecvs::VJSimpleClassifier::rightMargin
Definition at line 177 of file vjPattern.h.
Referenced by scale().
int corecvs::VJSimpleClassifier::thershold
Definition at line 173 of file vjPattern.h.
Referenced by scale().
int corecvs::VJSimpleClassifier::topMargin
Definition at line 175 of file vjPattern.h.
Referenced by scale().
The documentation for this class was generated from the following file:
core/boosting/vjPattern.h