DeepView: MakePreciseParametersControlWidget Class Reference
MakePreciseParametersControlWidget Class Reference
#include <makePreciseParametersControlWidget.h>
Public Slots
void changeParameters ()
Signals
void valueChanged ()
void paramsChanged ()
Public Member Functions
MakePreciseParametersControlWidget (QWidget *parent=0, bool autoInit=false, QString rootPath=QString())
~MakePreciseParametersControlWidget ()
MakePreciseParameters * createParameters () const
void setParameters (const MakePreciseParameters &input)
virtual void setParametersVirtual (void *input)
virtual void loadParamWidget (WidgetLoader &loader)
virtual void saveParamWidget (WidgetSaver &saver)
virtual BaseReflectionStatic * createParametersVirtual () const
virtual void loadFromQSettings (const QString &fileName, QString _root)
virtual void saveToQSettings (const QString &fileName, QString _root)
Private Attributes
Ui_MakePreciseParametersControlWidget * mUi
bool autoInit
QString rootPath
Detailed Description
Definition at line 12 of file makePreciseParametersControlWidget.h.
Constructor & Destructor Documentation
MakePreciseParametersControlWidget::MakePreciseParametersControlWidget (QWidget * parent = 0, bool autoInit = false, QString rootPath = QString()) [explicit]
Definition at line 15 of file makePreciseParametersControlWidget.cpp.
References mUi, paramsChanged(), and valueChanged().
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::MakePreciseParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);
    QObject::connect(mUi->shouldMakePreciseCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->algorithmComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->interpolationComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->kLTIterationsSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->kLTRadiusHSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->kLTRadiusWSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->kLTThresholdSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
}
MakePreciseParametersControlWidget::~MakePreciseParametersControlWidget ()
Definition at line 32 of file makePreciseParametersControlWidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void MakePreciseParametersControlWidget::changeParameters () [inline, slot]
Definition at line 28 of file makePreciseParametersControlWidget.h.
    {
        // emit paramsChanged();
    }
MakePreciseParameters * MakePreciseParametersControlWidget::createParameters () const
We should think of returning parameters by value or saving them in a preallocated place
Definition at line 54 of file makePreciseParametersControlWidget.cpp.
References mUi.
Referenced by loadParamWidget(), and saveParamWidget().
{
    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/
    MakePreciseParameters *result = new MakePreciseParameters(
          mUi->shouldMakePreciseCheckBox->isChecked()
        , static_cast<MakePreciseAlgorithm::MakePreciseAlgorithm>(mUi->algorithmComboBox->currentIndex())
        , static_cast<PreciseInterpolationType::PreciseInterpolationType>(mUi->interpolationComboBox->currentIndex())
        , mUi->kLTIterationsSpinBox->value()
        , mUi->kLTRadiusHSpinBox->value()
        , mUi->kLTRadiusWSpinBox->value()
        , mUi->kLTThresholdSpinBox->value()
    );
    return result;
}
BaseReflectionStatic * ParametersControlWidgetBase::createParametersVirtual () const [virtual, inherited]
Reimplemented in Draw3dCameraParametersControlWidget, Draw3dParametersControlWidget, and Draw3dViMouseParametersControlWidget.
Definition at line 3 of file parametersControlWidgetBase.cpp.
Referenced by TreeSceneController::paramtersChanged().
{
    return NULL;
}
virtual void SaveableWidget::loadFromQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 104 of file parametersControlWidgetBase.h.
References SaveableWidget::loadParamWidget().
    {
        SettingsGetter visitor(fileName, _root);
        WidgetLoader loader(&visitor);
        loadParamWidget(loader);
    }
void MakePreciseParametersControlWidget::loadParamWidget (WidgetLoader & loader) [virtual]
Reimplemented from SaveableWidget.
Definition at line 38 of file makePreciseParametersControlWidget.cpp.
References createParameters(), WidgetLoader::loadParameters(), rootPath, and setParameters().
{
    MakePreciseParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}
void MakePreciseParametersControlWidget::paramsChanged () [signal]
Referenced by MakePreciseParametersControlWidget(), and setParameters().
void MakePreciseParametersControlWidget::saveParamWidget (WidgetSaver & saver) [virtual]
Reimplemented from SaveableWidget.
Definition at line 46 of file makePreciseParametersControlWidget.cpp.
References createParameters(), rootPath, and WidgetSaver::saveParameters().
{
    MakePreciseParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}
virtual void SaveableWidget::saveToQSettings (const QString & fileName, QString _root) [inline, virtual, inherited]
Reimplemented in AdvancedImageWidget, and GraphPlotDialog.
Definition at line 111 of file parametersControlWidgetBase.h.
References SaveableWidget::saveParamWidget().
    {
        // qDebug() << "SaveableWidget::saveToQSettings: " << _root << " to file" << fileName;
        SettingsSetter visitor(fileName, _root);
        WidgetSaver saver(&visitor);
        saveParamWidget(saver);
    }
void MakePreciseParametersControlWidget::setParameters (const MakePreciseParameters & input)
Definition at line 74 of file makePreciseParametersControlWidget.cpp.
References MakePreciseParameters::algorithm(), MakePreciseParameters::interpolation(), MakePreciseParameters::kLTIterations(), MakePreciseParameters::kLTRadiusH(), MakePreciseParameters::kLTRadiusW(), MakePreciseParameters::kLTThreshold(), mUi, paramsChanged(), and MakePreciseParameters::shouldMakePrecise().
Referenced by loadParamWidget(), and setParametersVirtual().
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->shouldMakePreciseCheckBox->setChecked(input.shouldMakePrecise());
    mUi->algorithmComboBox->setCurrentIndex(input.algorithm());
    mUi->interpolationComboBox->setCurrentIndex(input.interpolation());
    mUi->kLTIterationsSpinBox->setValue(input.kLTIterations());
    mUi->kLTRadiusHSpinBox->setValue(input.kLTRadiusH());
    mUi->kLTRadiusWSpinBox->setValue(input.kLTRadiusW());
    mUi->kLTThresholdSpinBox->setValue(input.kLTThreshold());
    blockSignals(wasBlocked);
    emit paramsChanged();
}
void MakePreciseParametersControlWidget::setParametersVirtual (void * input) [virtual]
Definition at line 89 of file makePreciseParametersControlWidget.cpp.
References setParameters().
{
    // Modify widget parameters from outside
    MakePreciseParameters *inputCasted = static_cast<MakePreciseParameters *>(input);
    setParameters(*inputCasted);
}
void MakePreciseParametersControlWidget::valueChanged () [signal]
Referenced by MakePreciseParametersControlWidget().
Member Data Documentation
bool MakePreciseParametersControlWidget::autoInit [private]
Definition at line 39 of file makePreciseParametersControlWidget.h.
Ui_MakePreciseParametersControlWidget* MakePreciseParametersControlWidget::mUi [private]
Definition at line 38 of file makePreciseParametersControlWidget.h.
Referenced by createParameters(), MakePreciseParametersControlWidget(), setParameters(), and ~MakePreciseParametersControlWidget().
QString MakePreciseParametersControlWidget::rootPath [private]
Definition at line 40 of file makePreciseParametersControlWidget.h.
Referenced by loadParamWidget(), and saveParamWidget().
The documentation for this class was generated from the following files:
utils/corestructs/coreWidgets/makePreciseParametersControlWidget.h
utils/corestructs/coreWidgets/makePreciseParametersControlWidget.cpp