DeepView: OpenCVCaptureInterface::SpinThread Class Reference
OpenCVCaptureInterface::SpinThread Class Reference
Public Member Functions
SpinThread (OpenCVCaptureInterface *interface)
virtual void run (void)
void stop ()
Private Attributes
OpenCVCaptureInterface * mInterface
bool mStopping
Detailed Description
Definition at line 38 of file openCVCapture.h.
Constructor & Destructor Documentation
OpenCVCaptureInterface::SpinThread::SpinThread (OpenCVCaptureInterface * interface) [inline]
Definition at line 41 of file openCVCapture.h.
            : mInterface(interface), mStopping(false)
        {
        }
Member Function Documentation
void OpenCVCaptureInterface::SpinThread::run (void) [virtual]
Definition at line 92 of file openCVCapture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, OpenCvHelper::captureImageCopyToBuffer(), OpenCVCaptureInterface::captureLeft, OpenCVCaptureInterface::captureRight, OpenCVCaptureInterface::current, OpenCVCaptureInterface::delay, ImageCaptureInterface::FramePair::leftTimeStamp, mInterface, mStopping, ImageCaptureInterface::notifyAboutNewFrame(), OpenCVCaptureInterface::protectFrame, ImageCaptureInterface::FramePair::rightTimeStamp, and frame_data_t::timestamp.
{
    // We must capture a frame before getting properties.
    cvQueryFrame(mInterface->captureLeft);
    while (!mStopping)
    {
        uint width  = cvGetCaptureProperty(mInterface->captureLeft, CV_CAP_PROP_FRAME_WIDTH);
        uint height = cvGetCaptureProperty(mInterface->captureLeft, CV_CAP_PROP_FRAME_HEIGHT);
        OpenCVCaptureInterface::FramePair *pair = &(mInterface->current);
        mInterface->protectFrame.lock();
            delete pair->bufferLeft;
            delete pair->bufferRight;
            pair->bufferLeft  = new G12Buffer(height, width, false);
            pair->bufferRight = new G12Buffer(height, width, false);
            // OpenCV does not set timestamps for the frames
            pair->leftTimeStamp  = 0;
            pair->rightTimeStamp = 0;
            if (mInterface->captureLeft)
            {
                OpenCvHelper::captureImageCopyToBuffer(mInterface->captureLeft, pair->bufferLeft);
            }
            if (mInterface->captureRight)
            {
                OpenCvHelper::captureImageCopyToBuffer(mInterface->captureRight, pair->bufferRight);
            }
        mInterface->protectFrame.unlock();
        frame_data_t frameData;
        frameData.timestamp = (pair->leftTimeStamp / 2) + (pair->rightTimeStamp / 2);
        mInterface->notifyAboutNewFrame(frameData);
        /*
         * If we don't sleep here we'll find ourselves flooding the application with false new
         * frame notifications
         */
        if (mInterface->delay)
            msleep(mInterface->delay);
    }
}
void OpenCVCaptureInterface::SpinThread::stop ()
Definition at line 138 of file openCVCapture.cpp.
Referenced by OpenCVCaptureInterface::~OpenCVCaptureInterface().
{
    mStopping = true;
}
Member Data Documentation
OpenCVCaptureInterface* OpenCVCaptureInterface::SpinThread::mInterface [private]
Definition at line 49 of file openCVCapture.h.
Referenced by run().
bool OpenCVCaptureInterface::SpinThread::mStopping [private]
Definition at line 50 of file openCVCapture.h.
Referenced by run().
The documentation for this class was generated from the following files:
utils/framesources/openCVCapture.h
utils/framesources/openCVCapture.cpp