DeepView: SerializedWidget Class Reference
SerializedWidget Class Reference
#include <serializedWidget.h>
Public Slots
void deserialize ()
Public Member Functions
SerializedWidget (QWidget *parent=0)
~SerializedWidget ()
Private Attributes
QTimer * mTimer
Detailed Description
Definition at line 9 of file serializedWidget.h.
Constructor & Destructor Documentation
SerializedWidget::SerializedWidget (QWidget * parent = 0)
Definition at line 3 of file serializedWidget.cpp.
References deserialize(), and mTimer.
                                                  : QWidget(parent)
{
    mTimer = new QTimer(this);
    QObject::connect(mTimer, SIGNAL(timeout()), this, SLOT(deserialize()));
    mTimer->start(500);
}
SerializedWidget::~SerializedWidget ()
Definition at line 10 of file serializedWidget.cpp.
References Serializer::serialize().
{
    qDebug() << "serialized";
    Serializer::serialize(* this);
}
Member Function Documentation
void SerializedWidget::deserialize () [inline, slot]
Definition at line 14 of file serializedWidget.h.
References mTimer.
Referenced by SerializedWidget().
    {
        if (objectName().isEmpty())
            return;
        Serializer::deserialize(this);
        mTimer->stop();
    }
Member Data Documentation
QTimer* SerializedWidget::mTimer [private]
Definition at line 28 of file serializedWidget.h.
Referenced by deserialize(), and SerializedWidget().
The documentation for this class was generated from the following files:
utils/serializer/serializedWidget.h
utils/serializer/serializedWidget.cpp