DeepView: RgbColorParameters Class Reference
RgbColorParameters Class Reference
rgb Color Parameters rgb Color Parameters
#include <rgbColorParameters.h>
Public Types
enum FieldId { R_ID, G_ID, B_ID, RGB_COLOR_PARAMETERS_FIELD_ID_NUM }
Public Member Functions
const void * getPtrById (int fieldId) const
Section with getters.
int r () const
int g () const
int b () const
void setR (int r)
void setG (int g)
void setB (int b)
template<class VisitorType >
void accept (VisitorType &visitor)
RgbColorParameters ()
RgbColorParameters (int r, int g, int b)
void print ()
Static Public Member Functions
static int staticInit ()
Static fields init function, this is used for "dynamic" field initialization.
static Reflection * getReflection ()
static vector< const BaseField * > & fields ()
static ReflectionNaming & naming ()
static int fieldNumber ()
static const char * nameById (int fieldId)
static const char * commentById (int fieldId)
Public Attributes
int mR
Section with variables.
int mG
G G.
int mB
B B.
Static Public Attributes
static Reflection reflection
static int dummy
Friends
ostream & operator<< (ostream &out, RgbColorParameters &toSave)
Detailed Description
rgb Color Parameters rgb Color Parameters
Definition at line 38 of file rgbColorParameters.h.
Member Enumeration Documentation
enum RgbColorParameters::FieldId
Enumerator:
R_ID
G_ID
B_ID
RGB_COLOR_PARAMETERS_FIELD_ID_NUM
Definition at line 41 of file rgbColorParameters.h.
                 {
        R_ID,
        G_ID,
        B_ID,
        RGB_COLOR_PARAMETERS_FIELD_ID_NUM
    };
Constructor & Destructor Documentation
RgbColorParameters::RgbColorParameters () [inline]
Definition at line 117 of file rgbColorParameters.h.
    {
        DefaultSetter setter;
        accept(setter);
    }
RgbColorParameters::RgbColorParameters (int r, int g, int b) [inline]
Definition at line 123 of file rgbColorParameters.h.
    {
        mR = r;
        mG = g;
        mB = b;
    }
Member Function Documentation
template<class VisitorType > void RgbColorParameters::accept (VisitorType & visitor) [inline]
Definition at line 110 of file rgbColorParameters.h.
    {
        visitor.visit(mR,                         static_cast<const IntField *>     (fields()[R_ID]));
        visitor.visit(mG,                         static_cast<const IntField *>     (fields()[G_ID]));
        visitor.visit(mB,                         static_cast<const IntField *>     (fields()[B_ID]));
    }
int RgbColorParameters::b () const [inline]
Definition at line 86 of file rgbColorParameters.h.
Referenced by Mesh3DScene::drawMyself(), CameraScene::drawMyself(), and RgbColorParametersControlWidget::setParameters().
    {
        return mB;
    }
static const char* corecvs::BaseReflection< RgbColorParameters >::commentById (int fieldId) [inline, static, inherited]
Definition at line 679 of file reflection.h.
    {
        return fields()[fieldId]->name.comment;
    }
static int corecvs::BaseReflection< RgbColorParameters >::fieldNumber () [inline, static, inherited]
Definition at line 669 of file reflection.h.
    {
        return fields().size();
    }
static vector<const BaseField *>& corecvs::BaseReflection< RgbColorParameters >::fields () [inline, static, inherited]
Definition at line 659 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->fields;
    }
int RgbColorParameters::g () const [inline]
Definition at line 81 of file rgbColorParameters.h.
Referenced by Mesh3DScene::drawMyself(), CameraScene::drawMyself(), and RgbColorParametersControlWidget::setParameters().
    {
        return mG;
    }
const void* RgbColorParameters::getPtrById (int fieldId) const [inline]
Section with getters.
Definition at line 72 of file rgbColorParameters.h.
    {
        return (const unsigned char *)(this) + fields()[fieldId]->offset;
    }
static Reflection* corecvs::BaseReflection< RgbColorParameters >::getReflection () [inline, static, inherited]
Definition at line 654 of file reflection.h.
    {
        return &(RealThis::reflection);
    }
static const char* corecvs::BaseReflection< RgbColorParameters >::nameById (int fieldId) [inline, static, inherited]
Definition at line 674 of file reflection.h.
    {
        return fields()[fieldId]->name.name;
    }
static ReflectionNaming& corecvs::BaseReflection< RgbColorParameters >::naming () [inline, static, inherited]
Definition at line 664 of file reflection.h.
Referenced by staticInit().
    {
        return getReflection()->name;
    }
void RgbColorParameters::print () [inline]
Definition at line 141 of file rgbColorParameters.h.
    {
        cout << *this;
    }
int RgbColorParameters::r () const [inline]
Definition at line 76 of file rgbColorParameters.h.
Referenced by Mesh3DScene::drawMyself(), CameraScene::drawMyself(), and RgbColorParametersControlWidget::setParameters().
    {
        return mR;
    }
void RgbColorParameters::setB (int b) [inline]
Definition at line 102 of file rgbColorParameters.h.
    {
        mB = b;
    }
void RgbColorParameters::setG (int g) [inline]
Definition at line 97 of file rgbColorParameters.h.
    {
        mG = g;
    }
void RgbColorParameters::setR (int r) [inline]
Definition at line 92 of file rgbColorParameters.h.
    {
        mR = r;
    }
SUPPRESS_OFFSET_WARNING_BEGIN int RgbColorParameters::staticInit () [static]
Static fields init function, this is used for "dynamic" field initialization.
Definition at line 29 of file rgbColorParameters.cpp.
References B_ID, corecvs::BaseReflection< RgbColorParameters >::fields(), G_ID, mB, mG, mR, corecvs::BaseReflection< RgbColorParameters >::naming(), and R_ID.
{
    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "rgb Color Parameters",
        "rgb Color Parameters",
        ""
    );
    fields().push_back(
        new IntField
        (
          RgbColorParameters::R_ID,
          offsetof(RgbColorParameters, mR),
          128,
          "R",
          "R",
          "R"
        )
    );
    fields().push_back(
        new IntField
        (
          RgbColorParameters::G_ID,
          offsetof(RgbColorParameters, mG),
          128,
          "G",
          "G",
          "G"
        )
    );
    fields().push_back(
        new IntField
        (
          RgbColorParameters::B_ID,
          offsetof(RgbColorParameters, mB),
          128,
          "B",
          "B",
          "B"
        )
    );
   return 0;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, RgbColorParameters & toSave) [friend]
Definition at line 134 of file rgbColorParameters.h.
    {
        PrinterVisitor printer(out);
        toSave.accept<PrinterVisitor>(printer);
        return out;
    }
Member Data Documentation
int corecvs::BaseReflection< RgbColorParameters >::dummy [static, inherited]
Definition at line 650 of file reflection.h.
int RgbColorParameters::mB
B B.
Definition at line 66 of file rgbColorParameters.h.
Referenced by staticInit().
int RgbColorParameters::mG
G G.
Definition at line 60 of file rgbColorParameters.h.
Referenced by staticInit().
int RgbColorParameters::mR
Section with variables.
R R
Definition at line 54 of file rgbColorParameters.h.
Referenced by staticInit().
Reflection corecvs::BaseReflection< RgbColorParameters >::reflection [static, inherited]
Definition at line 649 of file reflection.h.
The documentation for this class was generated from the following files:
core/xml/generated/rgbColorParameters.h
core/xml/generated/rgbColorParameters.cpp