DeepView: MjpegDecoderLazy Class Reference
MjpegDecoderLazy Class Reference
#include <mjpegDecoderLazy.h>
Classes
class ComponentData
class HuffmanParser
class HuffmanTable
class HuffmanTableEntry
class JpegDecdata
class Jpginfo
class ScanData
Huffman decode table.
class StreamParser
Public Member Functions
MjpegDecoderLazy ()
G12Buffer * decode (unsigned char *buf)
Static Public Attributes
static const unsigned DECBITS = 10
static const int MAXCOMP = 4
static const int M_SOI = 0xd8
static const int M_APP0 = 0xe0
static const int M_DQT = 0xdb
static const int M_SOF0 = 0xc0
static const int M_DHT = 0xc4
static const int M_DRI = 0xdd
static const int M_SOS = 0xda
static const int M_RST0 = 0xd0
static const int M_EOI = 0xd9
static const int M_COM = 0xfe
static const int M_EOF = 0x80
static const int ERR_NO_SOI = 1
static const int ERR_NOT_8BIT = 2
static const int ERR_HEIGHT_MISMATCH = 3
static const int ERR_WIDTH_MISMATCH = 4
static const int ERR_BAD_WIDTH_OR_HEIGHT = 5
static const int ERR_TOO_MANY_COMPPS = 6
static const int ERR_ILLEGAL_HV = 7
static const int ERR_QUANT_TABLE_SELECTOR = 8
static const int ERR_NOT_YCBCR_221111 = 9
static const int ERR_UNKNOWN_CID_IN_SCAN = 10
static const int ERR_NOT_SEQUENTIAL_DCT = 11
static const int ERR_WRONG_MARKER = 12
static const int ERR_NO_EOI = 13
static const int ERR_BAD_TABLES = 14
static const int ERR_DEPTH_MISMATCH = 15
static const int JPG_HUFFMAN_TABLE_LENGTH = 0x1A0
static uint8_t JPEGHuffmanTable []
static uint8_t CoefZigZag []
static uint8_t CoefZigZag2 []
static int aaidct []
Private Member Functions
int huffman_init ()
void dec_makehuff (HuffmanTable *hu, unsigned *hufflen, unsigned char *huffvals)
Construct the huffman lookup tables form the length and values.
int readtables (int till, int *isDHT)
void idctqtab (uint8_t *qin, int *qout)
int dec_readmarker (void)
int dec_checkmarker (void)
void decode_mcus (int *dct, int n, ScanData *sc)
This functions decodes JPEG Minimum Coded Unit form huffman compressed stream.
void idct (int *in, int *out, int *quant, long off)
void yuv422ptoG12 (int *out, G12Buffer *pic, int x, int y)
Private Attributes
StreamParser parser
HuffmanParser hparser
Jpginfo info
HuffmanTable dhuff [4]
ComponentData * comps
ScanData * scans
uint8_t quants [4][64]
Detailed Description
Definition at line 19 of file mjpegDecoderLazy.h.
Constructor & Destructor Documentation
MjpegDecoderLazy::MjpegDecoderLazy ()
Definition at line 117 of file mjpegDecoderLazy.cpp.
                                   :
    comps(NULL),
    scans(NULL)
{
}
Member Function Documentation
int MjpegDecoderLazy::dec_checkmarker (void) [private]
Definition at line 419 of file mjpegDecoderLazy.cpp.
References MjpegDecoderLazy::Jpginfo::dri, hparser, info, MjpegDecoderLazy::Jpginfo::nm, MjpegDecoderLazy::Jpginfo::ns, MjpegDecoderLazy::HuffmanParser::readMarker(), MjpegDecoderLazy::Jpginfo::rm, and scans.
Referenced by decode().
{
    int i;
    int marker = hparser.readMarker();
    if (marker != info.rm)
        return -1;
    info.nm = info.dri;
    info.rm = (info.rm + 1) & ~(0x8);
    for (i = 0; i < info.ns; i++)
        scans[i].dc = 0;
    return 0;
}
void MjpegDecoderLazy::dec_makehuff (HuffmanTable * hu, unsigned * hufflen, unsigned char * huffvals) [private]
Construct the huffman lookup tables form the length and values.
hufflen will hold 16 entries that hold the number of the codes coded to particular length
huffvals - will hold the array of the values sorted lexicographically by the code
Definition at line 271 of file mjpegDecoderLazy.cpp.
References _DOTRACE, MjpegDecoderLazy::HuffmanTableEntry::length, MjpegDecoderLazy::HuffmanTable::table, and MjpegDecoderLazy::HuffmanTableEntry::value.
Referenced by huffman_init(), and readtables().
{
    _DOTRACE(("Creating Huffman lookup table %x\n", hu->table));
    memset(hu->table, 0, (1 << 16) * sizeof(HuffmanTableEntry));
    unsigned code = 0;
#ifdef _TRACE
    printf("Raw length:\n");
    for (unsigned i = 1; i < 16; i++, code <<= 1)
    {
        printf("%d ", hufflen[i]);
    }
    printf("\n");
#endif
    int count = 0;
    for (unsigned i = 1; i <= 16; i++, code <<= 1) {  /* sizes */
        /* Go through the codes of particular length */
        for (unsigned j = 0; j < hufflen[i-1]; j++) {
            unsigned char currentValue = *huffvals++;
            uint32_t c = code << (16 - i);
            unsigned d;
            /*TODO: make a cycle simpler */
            for (d = 0; d < (unsigned)(1 << (16 - i)); d++) {
                hu->table[c | d].length = i;
                hu->table[c | d].value  = currentValue;
                count++;
            }
#ifdef _TRACE
            printf("%4d -> ", currentValue);
            for (int tst = 0; tst < i; tst++)
            {
                printf("%s ", (c << tst) & 0x8000 ? "1" : "0");
            }
            printf("\n");
#endif
            code++;
        }
    }
#ifdef DEEP_TRACE
    printf("Totally filled %d lines\n", code);
    printf("Table dump\n");
    for (unsigned i = 0; i < (1 << 16); i++)
    {
        unsigned c = i;
        unsigned length = hu->table[i].length;
        for (int tst = 0; tst < 16; tst++)
        {
            printf("%s%s", (c << tst) & 0x8000 ? "1" : "0", length == (tst + 1)? "|" : " ");
        }
        printf("  %d %d %d\n", i, hu->table[i].value, hu->table[i].length);
    }
    printf("\n");
#endif
}
int MjpegDecoderLazy::dec_readmarker (void) [private]
G12Buffer * MjpegDecoderLazy::decode (unsigned char * buf)
Definition at line 689 of file mjpegDecoderLazy.cpp.
References _DOTRACE, MjpegDecoderLazy::ComponentData::cid, MjpegDecoderLazy::ScanData::cid, comps, MjpegDecoderLazy::StreamParser::datap, MjpegDecoderLazy::JpegDecdata::dcts, dec_checkmarker(), decode_mcus(), dhuff, MjpegDecoderLazy::JpegDecdata::dquant, MjpegDecoderLazy::Jpginfo::dri, ERR_BAD_TABLES, ERR_BAD_WIDTH_OR_HEIGHT, ERR_ILLEGAL_HV, ERR_NO_EOI, ERR_NO_SOI, ERR_NOT_8BIT, ERR_NOT_YCBCR_221111, ERR_QUANT_TABLE_SELECTOR, ERR_TOO_MANY_COMPPS, ERR_UNKNOWN_CID_IN_SCAN, ERR_WRONG_MARKER, MjpegDecoderLazy::StreamParser::getbyte(), MjpegDecoderLazy::StreamParser::getword(), hparser, MjpegDecoderLazy::ScanData::huac, MjpegDecoderLazy::ScanData::hudc, huffman_init(), MjpegDecoderLazy::ComponentData::hv, MjpegDecoderLazy::ScanData::hv, idct(), idctqtab(), IFIX, info, M_EOI, M_RST0, M_SOF0, M_SOI, M_SOS, MAXCOMP, MjpegDecoderLazy::Jpginfo::nc, MjpegDecoderLazy::ScanData::next, MjpegDecoderLazy::Jpginfo::nm, MjpegDecoderLazy::Jpginfo::ns, MjpegDecoderLazy::JpegDecdata::out, parser, quants, MjpegDecoderLazy::HuffmanParser::readMarker(), readtables(), MjpegDecoderLazy::Jpginfo::rm, scans, MjpegDecoderLazy::ComponentData::tq, MjpegDecoderLazy::ScanData::tq, and yuv422ptoG12().
Referenced by V4L2CaptureInterface::decodeData(), and DirectShowCaptureInterface::memberCallback().
{
    JpegDecdata *decdata;
     int i, j, m, tac, tdc;
     int intwidth;
     int intheight;
     int mcusx, mcusy, mx, my;
     int ypitch ,xpitch,bpp,pitch,x,y;
     int mb;
/*     int max[6];*/
     G12Buffer *toReturn = NULL;
//     ftopict convert;
     int err = 0;
     int isInitHuffman = 0;
     decdata = new JpegDecdata();
     memset(&info, 0, sizeof(Jpginfo));
     {
         if (!decdata) {
             err = -1; goto error;
         }
         if (buf == NULL) {
             err = -1; goto error;
         }
         parser = StreamParser(buf);
         if (parser.getbyte() != 0xff) {
             err = ERR_NO_SOI; goto error;
         }
         if (parser.getbyte() != M_SOI) {
             err = ERR_NO_SOI; goto error;
         }
         if (readtables(M_SOF0, &isInitHuffman)) {
             err = ERR_BAD_TABLES; goto error;
         }
         parser.getword();
         i = parser.getbyte();
         if (i != 8) {
             err = ERR_NOT_8BIT; goto error;
         }
         intheight = parser.getword();
         intwidth = parser.getword();
         if ((intheight & 7) || (intwidth & 7)) {
             err = ERR_BAD_WIDTH_OR_HEIGHT; goto error;
         }
         _DOTRACE(("File metrics are [%dx%d]\n",intwidth, intheight));
         info.nc = parser.getbyte();
         if (info.nc > MAXCOMP) {
             err = ERR_TOO_MANY_COMPPS; goto error;
         }
         _DOTRACE(("File has %d components\n", info.nc));
         comps = new ComponentData[info.nc];
         scans = new ScanData[info.nc];
         for (i = 0; i < info.nc; i++) {
             int h, v;
             comps[i].cid = parser.getbyte();
             comps[i].hv =  parser.getbyte();
             v = comps[i].hv & 0xF;
             h = comps[i].hv >> 4;
             comps[i].tq = parser.getbyte();
             if (h > 3 || v > 3) {
                 err = ERR_ILLEGAL_HV; goto error;
             }
             if (comps[i].tq > 3) {
                 err = ERR_QUANT_TABLE_SELECTOR; goto error;
             }
         }
         if (readtables(M_SOS,&isInitHuffman)) {
             err = ERR_BAD_TABLES; goto error;
         }
         parser.getword();
         info.ns = parser.getbyte();
         if (info.ns == 0){
             _DOTRACE(("info ns %d/n",info.ns));
             err = ERR_NOT_YCBCR_221111;  goto error;
         }
         for (i = 0; i < info.ns; i++) {
             scans[i].cid = parser.getbyte();
             tdc = parser.getbyte();
             tac = tdc & 15;
             tdc >>= 4;
             if (tdc > 1 || tac > 1) {
                 err = ERR_QUANT_TABLE_SELECTOR;
                 goto error;
             }
             for (j = 0; j < info.nc; j++)
                 if (comps[j].cid == scans[i].cid)
                     break;
             if (j == info.nc) {
                 err = ERR_UNKNOWN_CID_IN_SCAN;
                 goto error;
             }
             scans[i].hv = comps[j].hv;
             scans[i].tq = comps[j].tq;
             scans[i].hudc = dhuff + tdc;
             scans[i].huac = dhuff + 2 + tac;
         }
         i = parser.getbyte();
         j = parser.getbyte();
         m = parser.getbyte();
         if (i != 0 || j != 63 || m != 0) {
             _DOTRACE(("hmm FW error,not seq DCT ??\n"));
         }
         // printf("ext huffman table %d \n",isInitHuffman);
         if(!isInitHuffman) {
             if(huffman_init() < 0) {
                 //return -ERR_BAD_TABLES;
                 return NULL;
             }
         }
         toReturn = new G12Buffer(intheight, intwidth, false);
         int width = intwidth;
         int height = intheight;
         if (scans[0].hv != 0x21)
         {
             _DOTRACE(("Formats other then 422 are temporary unsupported\n"));
             return NULL;
             //return -1;
         }
         _DOTRACE(("Format is 422\n"));
         mb=4;
         mcusx = width >> 4;
         mcusy = height >> 3;
         bpp=2;
         xpitch = 16 * bpp;
         pitch = width * bpp; // YUYV out
         ypitch = 8 * pitch;
         idctqtab(quants[scans[0].tq], decdata->dquant[0]);
         idctqtab(quants[scans[1].tq], decdata->dquant[1]);
         idctqtab(quants[scans[2].tq], decdata->dquant[2]);
         hparser = HuffmanParser(parser.datap);
         info.nm = info.dri + 1;
         info.rm = M_RST0;
         for (i = 0; i < info.ns; i++)
            scans[i].dc = 0;
         scans[0].next = 2;
         scans[1].next = 1;
         scans[2].next = 0; /* 4xx encoding */
         for (my = 0, y = 0; my < mcusy; my++,y+=ypitch)
         {
             for (mx = 0, x = 0; mx < mcusx; mx++,x+=xpitch)
             {
                 if (info.dri && !--info.nm)
                     if (dec_checkmarker()) {
                     err = ERR_WRONG_MARKER;
                     goto error;
                 }
                 decode_mcus(decdata->dcts, mb, scans);
                 idct(decdata->dcts      , decdata->out      , decdata->dquant[0], IFIX(128.5));
                 idct(decdata->dcts + 64 , decdata->out + 64 , decdata->dquant[0], IFIX(128.5));
/*               idct(decdata->dcts + 128, decdata->out + 256, decdata->dquant[1], IFIX(0.5)  , max[4]);
                 idct(decdata->dcts + 192, decdata->out + 320, decdata->dquant[2], IFIX(0.5)  , max[5]);
*/
                 yuv422ptoG12(decdata->out, toReturn, my * 8, mx * 16);
             }
         }
         m = hparser.readMarker();
         if (m != M_EOI) {
             err = ERR_NO_EOI; goto error;
         }
         err = 0;
         /*delete[] comps;
         delete[] scans;
         delete decdata;
         return toReturn;*/
     }
error:
    if (err != 0)
    {
        printf("FJPEG decoder: error code: %d\n", err);
        if (1)
        {
            FILE *out = fopen("precrash.mjpeg", "wb");
            fwrite(buf, 320 * 200 * 2, 1, out);
            fclose(out);
        }
        if ( err != ERR_NO_EOI)
        {
            if (toReturn)
            {
                delete toReturn;
                toReturn = NULL;
            }
        }
    }
    delete[] comps;
    delete[] scans;
    delete decdata;
    return toReturn;
}
void MjpegDecoderLazy::decode_mcus (int * dct, int n, ScanData * sc) [private]
This functions decodes JPEG Minimum Coded Unit form huffman compressed stream.
Definition at line 441 of file mjpegDecoderLazy.cpp.
References _DOTRACE, MjpegDecoderLazy::ScanData::dc, MjpegDecoderLazy::HuffmanParser::getBits(), MjpegDecoderLazy::HuffmanParser::getValue(), hparser, MjpegDecoderLazy::ScanData::huac, MjpegDecoderLazy::ScanData::hudc, and MjpegDecoderLazy::ScanData::next.
Referenced by decode().
{
    int t;
    memset(dct, 0, n * 64 * sizeof(*dct));
    while (n-- > 0) {
        int *dctend = dct + 64;
        int dcBits = hparser.getValue(sc->hudc);
        int dcValue = hparser.getBits(dcBits);
        sc->dc += dcValue;
        _DOTRACE(("DC %d\n", dcValue));
        *dct++ = sc->dc;
        while (dct < dctend) {
            t = hparser.getValue(sc->huac);
            unsigned r = t >> 4;
            unsigned s = t & 0xF;
            if (r == 0 && s == 0)
            {
                dct = dctend;
                _DOTRACE(("block Ended\n"));
                break;
            }
            dct += r;
            int acValue = hparser.getBits(s);
            *dct++ = acValue;
            _DOTRACE(("YAC %d skipped %d\n", acValue, r));
        }
#ifdef _TRACE
        printf("Raw block\n");
          for (unsigned j = 0; j < 8; j++) {
              for (unsigned k = 0; k < 8; k++) {
                  printf("%4d ",((unsigned *)(dct - 64))[j * 8 + k]);
              }
              printf("\n");
          }
#endif
        if (n == sc->next)
            sc++;
    }
}
int MjpegDecoderLazy::huffman_init () [private]
Definition at line 126 of file mjpegDecoderLazy.cpp.
References _DOTRACE, dec_makehuff(), dhuff, ERR_BAD_TABLES, JPEGHuffmanTable, and JPG_HUFFMAN_TABLE_LENGTH.
Referenced by decode().
{
    int tc, th, tt;
    const unsigned char *ptr= JPEGHuffmanTable ;
    int i, l;
    unsigned j;
    l = JPG_HUFFMAN_TABLE_LENGTH ;
    while (l > 0) {
        unsigned hufflen[16], k;
        unsigned char huffvals[256];
        tc = *ptr++;
        th = tc & 15;
        tc >>= 4;
        tt = tc * 2 + th;
        if (tc > 1 || th > 1)
            return -ERR_BAD_TABLES;
        for (i = 0; i < 16; i++)
            hufflen[i] = *ptr++;
        l -= 1 + 16;
        k = 0;
        for (i = 0; i < 16; i++) {
            for (j = 0; j < hufflen[i]; j++)
                huffvals[k++] = *ptr++;
            l -= hufflen[i];
        }
        _DOTRACE(("Creating predefined huffman lookup table:"));
        dec_makehuff(dhuff + tt, hufflen, huffvals);
    }
    return 0;
}
void MjpegDecoderLazy::idct (int * in, int * out, int * quant, long off) [private]
Definition at line 496 of file mjpegDecoderLazy.cpp.
References C22, CoefZigZag2, IC4, IMULT, ITOINT, and S22.
Referenced by decode().
{
     long t0, t1, t2, t3, t4, t5, t6, t7;
     long tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6;
     long tmp[64], *tmpp;
    /*
     int32_t t0, t1, t2, t3, t4, t5, t6, t7; // t ;
     int32_t tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6;
     int32_t tmp[64], *tmpp;
    */
     int i, j, te;
     unsigned char *zig2p;
     t0 = off;
/*     if (max == 1) {
         t0 += in[0] * quant[0];
         for (i = 0; i < 64; i++)
             out[i] = ITOINT(t0);
         return;
     }*/
     zig2p = CoefZigZag2;
     tmpp = tmp;
     for (i = 0; i < 8; i++) {
         j = *zig2p++;
         t0 += in[j] * (long) quant[j];
         j = *zig2p++;
         t5 = in[j] * (long) quant[j];
         j = *zig2p++;
         t2 = in[j] * (long) quant[j];
         j = *zig2p++;
         t7 = in[j] * (long) quant[j];
         j = *zig2p++;
         t1 = in[j] * (long) quant[j];
         j = *zig2p++;
         t4 = in[j] * (long) quant[j];
         j = *zig2p++;
         t3 = in[j] * (long) quant[j];
         j = *zig2p++;
         t6 = in[j] * (long) quant[j];
         if ((t1 | t2 | t3 | t4 | t5 | t6 | t7) == 0) {
             tmpp[0 * 8] = t0;
             tmpp[1 * 8] = t0;
             tmpp[2 * 8] = t0;
             tmpp[3 * 8] = t0;
             tmpp[4 * 8] = t0;
             tmpp[5 * 8] = t0;
             tmpp[6 * 8] = t0;
             tmpp[7 * 8] = t0;
             tmpp++;
             t0 = 0;
             continue;
         }
         //IDCT;
         tmp0 = t0 + t1;
         t1 = t0 - t1;
         tmp2 = t2 - t3;
         t3 = t2 + t3;
         tmp2 = IMULT(tmp2, IC4) - t3;
         tmp3 = tmp0 + t3;
         t3 = tmp0 - t3;
         tmp1 = t1 + tmp2;
         tmp2 = t1 - tmp2;
         tmp4 = t4 - t7;
         t7 = t4 + t7;
         tmp5 = t5 + t6;
         t6 = t5 - t6;
         tmp6 = tmp5 - t7;
         t7 = tmp5 + t7;
         tmp5 = IMULT(tmp6, IC4);
         tmp6 = IMULT((tmp4 + t6), S22);
         tmp4 = IMULT(tmp4, (C22 - S22)) + tmp6;
         t6 = IMULT(t6, (C22 + S22)) - tmp6;
         t6 = t6 - t7;
         t5 = tmp5 - t6;
         t4 = tmp4 - t5;
         tmpp[0 * 8] = tmp3 + t7;    //t0;
         tmpp[1 * 8] = tmp1 + t6;    //t1;
         tmpp[2 * 8] = tmp2 + t5;    //t2;
         tmpp[3 * 8] = t3 + t4;  //t3;
         tmpp[4 * 8] = t3 - t4;  //t4;
         tmpp[5 * 8] = tmp2 - t5;    //t5;
         tmpp[6 * 8] = tmp1 - t6;    //t6;
         tmpp[7 * 8] = tmp3 - t7;    //t7;
         tmpp++;
         t0 = 0;
     }
     for (i = 0, j = 0; i < 8; i++) {
         t0 = tmp[j + 0];
         t1 = tmp[j + 1];
         t2 = tmp[j + 2];
         t3 = tmp[j + 3];
         t4 = tmp[j + 4];
         t5 = tmp[j + 5];
         t6 = tmp[j + 6];
         t7 = tmp[j + 7];
         if ((t1 | t2 | t3 | t4 | t5 | t6 | t7) == 0) {
             te = ITOINT(t0);
             out[j + 0] = te;
             out[j + 1] = te;
             out[j + 2] = te;
             out[j + 3] = te;
             out[j + 4] = te;
             out[j + 5] = te;
             out[j + 6] = te;
             out[j + 7] = te;
             j += 8;
             continue;
         }
         //IDCT;
         tmp0 = t0 + t1;
         t1 = t0 - t1;
         tmp2 = t2 - t3;
         t3 = t2 + t3;
         tmp2 = IMULT(tmp2, IC4) - t3;
         tmp3 = tmp0 + t3;
         t3 = tmp0 - t3;
         tmp1 = t1 + tmp2;
         tmp2 = t1 - tmp2;
         tmp4 = t4 - t7;
         t7 = t4 + t7;
         tmp5 = t5 + t6;
         t6 = t5 - t6;
         tmp6 = tmp5 - t7;
         t7 = tmp5 + t7;
         tmp5 = IMULT(tmp6, IC4);
         tmp6 = IMULT((tmp4 + t6), S22);
         tmp4 = IMULT(tmp4, (C22 - S22)) + tmp6;
         t6 = IMULT(t6, (C22 + S22)) - tmp6;
         t6 = t6 - t7;
         t5 = tmp5 - t6;
         t4 = tmp4 - t5;
         out[j + 0] = ITOINT(tmp3 + t7);
         out[j + 1] = ITOINT(tmp1 + t6);
         out[j + 2] = ITOINT(tmp2 + t5);
         out[j + 3] = ITOINT(t3 + t4);
         out[j + 4] = ITOINT(t3 - t4);
         out[j + 5] = ITOINT(tmp2 - t5);
         out[j + 6] = ITOINT(tmp1 - t6);
         out[j + 7] = ITOINT(tmp3 - t7);
         j += 8;
     }
}
void MjpegDecoderLazy::idctqtab (uint8_t * qin, int * qout) [private]
Definition at line 246 of file mjpegDecoderLazy.cpp.
References aaidct, and CoefZigZag.
Referenced by decode().
{
    int i, j;
    const uint8_t *offset = CoefZigZag;
    for (i = 0; i < 8; i++)
    {
        for (j = 0; j < 8; j++)
        {
            qout[*offset] = qin[*offset] * ((aaidct[i] * aaidct[j]) >> 11);
            offset++;
        }
    }
}
int MjpegDecoderLazy::readtables (int till, int * isDHT) [private]
Definition at line 158 of file mjpegDecoderLazy.cpp.
References _DOTRACE, dec_makehuff(), dhuff, MjpegDecoderLazy::Jpginfo::dri, MjpegDecoderLazy::StreamParser::getbyte(), MjpegDecoderLazy::StreamParser::getword(), info, M_DHT, M_DQT, M_DRI, parser, and quants.
Referenced by decode().
{
    int m, l, i, lq, pq, tq;
    unsigned j;
    int tc, th, tt;
    for (;;) {
        if (parser.getbyte() != 0xff) {
            return -1;
        }
        nextbyte:
        if ((m = parser.getbyte()) == till)
            break;
        switch (m) {
        case 0xc2:
            return 0;
        case M_DQT:
            //printf("find DQT \n");
            lq = parser.getword();
            while (lq > 2) {
                pq = parser.getbyte();
                tq = pq & 0xF;
                if (tq > 3)
                {
                    return -1;
                }
                pq >>= 4;
                if (pq != 0)
                {
                    return -1;
                }
                for (i = 0; i < 64; i++)
                    quants[tq][i] = parser.getbyte();
                lq -= 64 + 1;
            }
            break;
    case M_DHT:
            //printf("find DHT \n");
            l = parser.getword();
            while (l > 2) {
                unsigned hufflen[16], k;
                unsigned char huffvals[256];
                tc = parser.getbyte();
                th = tc & 15;
                tc >>= 4;
                tt = tc * 2 + th;
                if (tc > 1 || th > 1)
                {
                    return -1;
                }
                for (i = 0; i < 16; i++)
                    hufflen[i] = parser.getbyte();
                l -= 1 + 16;
                k = 0;
                for (i = 0; i < 16; i++) {
                    for (j = 0; j < hufflen[i]; j++)
                        huffvals[k++] = parser.getbyte();
                    l -= hufflen[i];
                }
                dec_makehuff(dhuff + tt, hufflen, huffvals);
            }
            *isDHT= 1;
            break;
    case M_DRI:
            _DOTRACE(("find DRI \n"));
            l = parser.getword();
            info.dri = parser.getword();
            break;
    case 0xff:
            goto nextbyte;
            break;
    default:
            l = parser.getword();
            while (l-- > 2)
                parser.getbyte();
            break;
        }
    }
    return 0;
}
void MjpegDecoderLazy::yuv422ptoG12 (int * out, G12Buffer * pic, int x, int y) [private]
Definition at line 653 of file mjpegDecoderLazy.cpp.
References CLIP, and corecvs::AbstractBuffer< ElementType, IndexType >::element().
Referenced by decode().
{
    int j, k;
#ifdef _TRACE
    printf("Macroblock\n");
    printf("Y\n");
    for (j = 0; j < 8; j++) {
        for (k = 0; k < 8; k++) {
            printf("%4d ",((unsigned *)out)[j * 8 + k]);
        }
        printf("\n");
    }
    for (j = 0; j < 8; j++) {
        for (k = 0; k < 8; k++) {
            printf("%4d ",((unsigned *)out)[j * 8 + k + 64]);
        }
        printf("\n");
    }
    printf("\n");
#endif
    for (j = 0; j < 8; j++) {
        for (k = 0; k < 8; k++) {
            int value;
            value = out[j * 8 + k];
            pic->element(y + j, x + k) = CLIP(value) << 4;
            value = out[j * 8 + k + 64];
            pic->element(y + j, x + k + 8) = CLIP(value) << 4;
        }
    }
}
Member Data Documentation
int MjpegDecoderLazy::aaidct [static]
Initial value:
 {
    IFIX(0.3535533906), IFIX(0.4903926402),
    IFIX(0.4619397663), IFIX(0.4157348062),
    IFIX(0.3535533906), IFIX(0.2777851165),
    IFIX(0.1913417162), IFIX(0.0975451610)
}
Definition at line 168 of file mjpegDecoderLazy.h.
Referenced by idctqtab().
unsigned char MjpegDecoderLazy::CoefZigZag [static]
Initial value:
 {
    0,   1,  5,  6, 14, 15, 27, 28,
    2,   4,  7, 13, 16, 26, 29, 42,
    3,   8, 12, 17, 25, 30, 41, 43,
    9,  11, 18, 24, 31, 40, 44, 53,
    10, 19, 23, 32, 39, 45, 52, 54,
    20, 22, 33, 38, 46, 51, 55, 60,
    21, 34, 37, 47, 50, 56, 59, 61,
    35, 36, 48, 49, 57, 58, 62, 63
}
Definition at line 166 of file mjpegDecoderLazy.h.
Referenced by idctqtab().
unsigned char MjpegDecoderLazy::CoefZigZag2 [static]
Initial value:
 {
     0,  2,  3,  9, 10, 20, 21, 35,
    14, 16, 25, 31, 39, 46, 50, 57,
     5,  7, 12, 18, 23, 33, 37, 48,
    27, 29, 41, 44, 52, 55, 59, 62,
    15, 26, 30, 40, 45, 51, 56, 58,
     1,  4,  8, 11, 19, 22, 34, 36,
    28, 42, 43, 53, 54, 60, 61, 63,
     6, 13, 17, 24, 32, 38, 47, 49
}
Definition at line 167 of file mjpegDecoderLazy.h.
Referenced by idct().
ComponentData* MjpegDecoderLazy::comps [private]
Definition at line 195 of file mjpegDecoderLazy.h.
Referenced by decode().
const unsigned MjpegDecoderLazy::DECBITS = 10 [static]
Definition at line 23 of file mjpegDecoderLazy.h.
HuffmanTable MjpegDecoderLazy::dhuff[4] [private]
Definition at line 194 of file mjpegDecoderLazy.h.
Referenced by decode(), huffman_init(), and readtables().
const int MjpegDecoderLazy::ERR_BAD_TABLES = 14 [static]
Definition at line 160 of file mjpegDecoderLazy.h.
Referenced by decode(), and huffman_init().
const int MjpegDecoderLazy::ERR_BAD_WIDTH_OR_HEIGHT = 5 [static]
Definition at line 151 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_DEPTH_MISMATCH = 15 [static]
Definition at line 161 of file mjpegDecoderLazy.h.
const int MjpegDecoderLazy::ERR_HEIGHT_MISMATCH = 3 [static]
Definition at line 149 of file mjpegDecoderLazy.h.
const int MjpegDecoderLazy::ERR_ILLEGAL_HV = 7 [static]
Definition at line 153 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_NO_EOI = 13 [static]
Definition at line 159 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_NO_SOI = 1 [static]
Definition at line 147 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_NOT_8BIT = 2 [static]
Definition at line 148 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_NOT_SEQUENTIAL_DCT = 11 [static]
Definition at line 157 of file mjpegDecoderLazy.h.
const int MjpegDecoderLazy::ERR_NOT_YCBCR_221111 = 9 [static]
Definition at line 155 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_QUANT_TABLE_SELECTOR = 8 [static]
Definition at line 154 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_TOO_MANY_COMPPS = 6 [static]
Definition at line 152 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_UNKNOWN_CID_IN_SCAN = 10 [static]
Definition at line 156 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::ERR_WIDTH_MISMATCH = 4 [static]
Definition at line 150 of file mjpegDecoderLazy.h.
const int MjpegDecoderLazy::ERR_WRONG_MARKER = 12 [static]
Definition at line 158 of file mjpegDecoderLazy.h.
Referenced by decode().
HuffmanParser MjpegDecoderLazy::hparser [private]
Definition at line 191 of file mjpegDecoderLazy.h.
Referenced by dec_checkmarker(), decode(), and decode_mcus().
Jpginfo MjpegDecoderLazy::info [private]
Definition at line 193 of file mjpegDecoderLazy.h.
Referenced by dec_checkmarker(), decode(), and readtables().
uint8_t MjpegDecoderLazy::JPEGHuffmanTable [static]
Definition at line 165 of file mjpegDecoderLazy.h.
Referenced by huffman_init().
const int MjpegDecoderLazy::JPG_HUFFMAN_TABLE_LENGTH = 0x1A0 [static]
Definition at line 163 of file mjpegDecoderLazy.h.
Referenced by huffman_init().
const int MjpegDecoderLazy::M_APP0 = 0xe0 [static]
Definition at line 134 of file mjpegDecoderLazy.h.
const int MjpegDecoderLazy::M_COM = 0xfe [static]
Definition at line 142 of file mjpegDecoderLazy.h.
const int MjpegDecoderLazy::M_DHT = 0xc4 [static]
Definition at line 137 of file mjpegDecoderLazy.h.
Referenced by readtables().
const int MjpegDecoderLazy::M_DQT = 0xdb [static]
Definition at line 135 of file mjpegDecoderLazy.h.
Referenced by readtables().
const int MjpegDecoderLazy::M_DRI = 0xdd [static]
Definition at line 138 of file mjpegDecoderLazy.h.
Referenced by readtables().
const int MjpegDecoderLazy::M_EOF = 0x80 [static]
Definition at line 143 of file mjpegDecoderLazy.h.
const int MjpegDecoderLazy::M_EOI = 0xd9 [static]
Definition at line 141 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::M_RST0 = 0xd0 [static]
Definition at line 140 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::M_SOF0 = 0xc0 [static]
Definition at line 136 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::M_SOI = 0xd8 [static]
Definition at line 133 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::M_SOS = 0xda [static]
Definition at line 139 of file mjpegDecoderLazy.h.
Referenced by decode().
const int MjpegDecoderLazy::MAXCOMP = 4 [static]
Definition at line 24 of file mjpegDecoderLazy.h.
Referenced by decode().
StreamParser MjpegDecoderLazy::parser [private]
Definition at line 190 of file mjpegDecoderLazy.h.
Referenced by decode(), and readtables().
uint8_t MjpegDecoderLazy::quants[4][64] [private]
Definition at line 198 of file mjpegDecoderLazy.h.
Referenced by decode(), and readtables().
ScanData* MjpegDecoderLazy::scans [private]
Definition at line 196 of file mjpegDecoderLazy.h.
Referenced by dec_checkmarker(), and decode().
The documentation for this class was generated from the following files:
utils/framesources/decoders/mjpegDecoderLazy.h
utils/framesources/decoders/mjpegDecoderLazy.cpp