DeepView: FileCaptureInterface Class Reference
FileCaptureInterface Class Reference
This class implements the capture from a list of files.
#include <fileCapture.h>
Public Types
enum CapErrorCode { SUCCESS = 0, SUCCESS_1CAM = 1, FAILURE = 2 }
enum CapCameraId { CAMERA_LEFT = 0x01, CAMERA_RIGHT = 0x10, CAMERA_BOTH = 0x11 }
enum CapPropertyAccessType { ACCESS_NONE = 0x00, ACCESS_READ = 0x01, ACCESS_WRITE = 0x10, ACCESS_READWRITE = 0x11 }
Used to pass capture parameters in set/get requests.
Signals
void newFrameReady (frame_data_t frameData)
void newImageReady ()
void newStatisticsReady (CaptureStatistics stats)
void streamPaused ()
Public Member Functions
FileCaptureInterface (string pathFmt, bool isVerbose=true)
virtual FramePair getFrame ()
Main function to request frames from image interface.
virtual CapErrorCode initCapture ()
virtual CapErrorCode startCapture ()
virtual ~FileCaptureInterface ()
string getImageFileName (uint imageNumber, uint channelNumber=0)
Aux function to get an image file name, which path name is given by additional parameters.
void increaseImageFileCounter ()
void resetImageFileCounter ()
virtual FramePair getFrameRGB24 ()
virtual CapErrorCode setCaptureProperty (int id, int value)
virtual CapErrorCode getCaptureProperty (int id, int *value)
virtual CapErrorCode getCaptureName (QString &value)
virtual CapErrorCode getFormats (int *num, CameraFormat *&)
virtual QString getInterfaceName ()
Return the interface device string.
virtual CapErrorCode getDeviceName (int num, QString &name)
Return some id of one of the stereo-/multi- camera sub-device.
virtual CapErrorCode queryCameraParameters (CameraParameters &parameter)
Check if a specific property can be set/read and what values it can take.
virtual CapErrorCode pauseCapture ()
virtual CapErrorCode nextFrame ()
virtual bool supportPause ()
Check if particular image capturer support pausing.
Static Public Member Functions
static ImageCaptureInterface * fabric (string input, bool isRgb=false)
Fabric to create particular implementation of the capturer.
Static Public Attributes
static string sPgmImageFileFmt = "image%04u_c%d.pgm"
static bool isRgb = false
Protected Member Functions
virtual void notifyAboutNewFrame (frame_data_t frameData)
Internal function to trigger frame notify signal.
Protected Attributes
string mPathFmt
bool mVerbose
unsigned mCount
Detailed Description
This class implements the capture from a list of files.
It sends newFrameReady signal immediately. More precise camera simulation is done in FilePreciseCaptureInterface class
Definition at line 21 of file fileCapture.h.
Member Enumeration Documentation
enum ImageCaptureInterface::CapCameraId [inherited]
Enumerator:
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_BOTH
Definition at line 79 of file imageCaptureInterface.h.
    {
        CAMERA_LEFT   = 0x01,
        CAMERA_RIGHT  = 0x10,
        CAMERA_BOTH   = 0x11
    };
enum ImageCaptureInterface::CapErrorCode [inherited]
Enumerator:
SUCCESS
SUCCESS_1CAM
FAILURE
Reimplemented in DirectShowCaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 72 of file imageCaptureInterface.h.
    {
        SUCCESS       = 0,
        SUCCESS_1CAM  = 1,
        FAILURE      = 2
    };
enum ImageCaptureInterface::CapPropertyAccessType [inherited]
Used to pass capture parameters in set/get requests.
Enumerator:
ACCESS_NONE
ACCESS_READ
ACCESS_WRITE
ACCESS_READWRITE
Definition at line 108 of file imageCaptureInterface.h.
    {
        ACCESS_NONE         = 0x00,
        ACCESS_READ         = 0x01,
        ACCESS_WRITE        = 0x10,
        ACCESS_READWRITE    = 0x11
    };
Constructor & Destructor Documentation
FileCaptureInterface::FileCaptureInterface (string pathFmt, bool isVerbose = true)
Definition at line 21 of file fileCapture.cpp.
References ImageFileCaptureInterface::mPathFmt.
    : ImageFileCaptureInterface(&pathFmt, isVerbose)
{
    cout << "Starting capture form file with pattern:" << mPathFmt << "\n";
}
FileCaptureInterface::~FileCaptureInterface () [virtual]
Definition at line 76 of file fileCapture.cpp.
{
}
Member Function Documentation
ImageCaptureInterface * ImageCaptureInterface::fabric (string input, bool isRgb = false) [static, inherited]
Fabric to create particular implementation of the capturer.
Definition at line 53 of file imageCaptureInterface.cpp.
References CAP_ANY, CAP_DS, CAP_VFW, and ImageCaptureInterface::isRgb.
Referenced by BaseHostDialog::initCapture().
{
    isRgb = isRGB;
    string file("file:");
    if (input.substr(0, file.size()).compare(file) == 0)
    {
        string tmp = input.substr(file.size());
        return new FileCaptureInterface(tmp);
    }
    string prec("prec:");
    if (input.substr(0, prec.size()).compare(prec) == 0)
    {
        string tmp = input.substr(prec.size());
        return new FilePreciseCapture(QString(tmp.c_str()), false);
    }
#ifdef Q_OS_LINUX
    string v4l2("v4l2:");
    if (input.substr(0, v4l2.size()).compare(v4l2) == 0)
    {
        string tmp = input.substr(v4l2.size());
        return new V4L2CaptureInterface(tmp, isRgb);
    }
    string v4l2d("v4l2d:");
    if (input.substr(0, v4l2d.size()).compare(v4l2d) == 0)
    {
        string tmp = input.substr(v4l2d.size());
        return new V4L2CaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_UEYE
    string ueye("ueye:");
    if (input.substr(0, ueye.size()).compare(ueye) == 0)
    {
        string tmp = input.substr(ueye.size());
        return new UEyeCaptureInterface(tmp);
    }
#endif
#ifdef WITH_DIRECTSHOW
    string dshow("dshow:");
    if (input.substr(0, dshow.size()).compare(dshow) == 0)
    {
        string tmp = input.substr(dshow.size());
        return new DirectShowCaptureInterface(tmp);
    }
    string dshowd("dshowd:");
    if (input.substr(0, dshowd.size()).compare(dshowd) == 0)
    {
        string tmp = input.substr(dshowd.size());
        return new DirectShowCaptureDecoupleInterface(tmp);
    }
#endif
#ifdef WITH_OPENCV
    string any("any:");
    if (input.substr(0, any.size()).compare(any) == 0)
    {
        string tmp = input.substr(any.size());
        return new OpenCVCaptureInterface(tmp, CAP_ANY);
    }
    string vfw("vfw:");
    if (input.substr(0, vfw.size()).compare(vfw) == 0)
    {
        string tmp = input.substr(vfw.size());
        return new OpenCVCaptureInterface(tmp, CAP_VFW);
    }
    string ds("ds:");
    if (input.substr(0, ds.size()).compare(ds) == 0)
    {
        string tmp = input.substr(ds.size());
        return new OpenCVCaptureInterface(tmp, CAP_DS);
    }
    string opencv_file("opencv_file:");
    if (input.substr(0, opencv_file.size()).compare(opencv_file) == 0)
    {
        string tmp = input.substr(opencv_file.size());
        return new OpenCvFileCapture(QString(tmp.c_str()));
    }
#endif
    return NULL;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureName (QString & value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 171 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getCaptureProperty (int id, int * value) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, DirectShowCaptureDecoupleInterface, V4L2CaptureInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 166 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by CapSettingsDialog::refreshDialog().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getDeviceName (int num, QString & name) [virtual, inherited]
Return some id of one of the stereo-/multi- camera sub-device.
Reimplemented in DirectShowCaptureInterface, and V4L2CaptureInterface.
Definition at line 186 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::getFormats (int * num, CameraFormat *&) [virtual, inherited]
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, and DirectShowCaptureDecoupleInterface.
Definition at line 176 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
{
    return FAILURE;
}
FileCaptureInterface::FramePair FileCaptureInterface::getFrame () [virtual]
Main function to request frames from image interface.
Implements ImageCaptureInterface.
Definition at line 27 of file fileCapture.cpp.
References ImageCaptureInterface::FramePair::bufferLeft, ImageCaptureInterface::FramePair::bufferRight, ImageFileCaptureInterface::getImageFileName(), ImageFileCaptureInterface::increaseImageFileCounter(), ImageFileCaptureInterface::mCount, ImageFileCaptureInterface::mVerbose, and ImageFileCaptureInterface::resetImageFileCounter().
{
    FramePair result;
    string name0 = getImageFileName(mCount, 0);
    string name1 = getImageFileName(mCount, 1);
    if (mVerbose) {
        printf("Grabbing frame from file: %s\n", name0.c_str());
    }
    result.bufferLeft = BufferFactory::getInstance()->loadG12Bitmap(name0);
    if (result.bufferLeft)
    {
        if (mVerbose) {
            printf("Grabbing frame from file: %s\n", name1.c_str());
        }
        result.bufferRight = BufferFactory::getInstance()->loadG12Bitmap(name1);
    }
    if (!result.bufferLeft || !result.bufferRight)
    {
        delete result.bufferLeft;
        delete result.bufferRight;
        if (mVerbose) {
            printf("File not found, resetting to first image in the sequence.\n");
        }
        resetImageFileCounter();
        return getFrame();
    }
    increaseImageFileCounter();
    return result;
}
virtual FramePair ImageCaptureInterface::getFrameRGB24 () [inline, virtual, inherited]
Reimplemented in V4L2CaptureInterface.
Definition at line 166 of file imageCaptureInterface.h.
Referenced by Frames::fetchNewFrames().
    {
        return getFrame();
    }
string ImageFileCaptureInterface::getImageFileName (uint imageNumber, uint channelNumber = 0) [inherited]
Aux function to get an image file name, which path name is given by additional parameters.
Parameters:
imageNumber - image file number in a series (since 1-st)
channelNumber - image file channel number in a series (usual 0 or 1)
We're to check correctness of the current directory, but we need a path to "data" folder with image files.
"../" - Bin directory curDir "../../" - OpenCL project curDir "../../../" - MSVC sets curDir to the project dir (= "hostSoft")
Note:
But from another side it's dangerously to scan up to 3 levels by trying to find a requested file.
especially if there's a special folder structure with different series... Therefore for Unix it's applied only for one parent as we run from the bin directory,
but usually use images by path like this: "data/pair".
Definition at line 28 of file imageFileCaptureInterface.cpp.
References ImageFileCaptureInterface::mPathFmt, ImageFileCaptureInterface::mPathPrefix, and ImageFileCaptureInterface::sPgmImageFileFmt.
Referenced by getFrame(), FilePreciseCapture::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
{
    // TODO: How to replace this with C++ construct? I.e. MFC's CString has a method Format() for this, but std::string doesn't. :(
    char pathName[256];
    if (mPathFmt.find("%0.0s") != string::npos)             // format comes from GUI with constant pair for debugging
    {
        snprintf2buf(pathName, mPathFmt.c_str(), "", channelNumber);// str + int (the way to disable pair switching over series)
    }
    else if (mPathFmt.find("%") != string::npos)            // format comes from GUI with series processing
    {
        // TODO: it would be good here to check that format expects exactly 2 integers
        snprintf2buf(pathName, mPathFmt.c_str(), imageNumber, channelNumber); // expects 2 ints
    }
    else if (!mPathFmt.empty())                             // format comes as a ready path, only from some tests
    {
        // one exclusion is possible here: when ctor got a direct path to the file!
        QFileInfo fi(mPathFmt.c_str());
        if (fi.isFile() && fi.exists()) {
            return mPathFmt;                                // return immediately the initial path as it's not a format
        }
        // mPathFmt has a real folder path
        if (mPathFmt[mPathFmt.length() - 1] != '/') {       // append slash at the end if absent
            mPathFmt += '/';
        }
        mPathFmt += sPgmImageFileFmt;                       // add default format to the pathFmt
        return getImageFileName(imageNumber, channelNumber);
    }
    if (imageNumber == 1 && mPathPrefix.empty() && !QFile::exists(pathName))
    {
        /**
         * We're to check correctness of the current directory, but we need a path to "data" folder with image files.
         *
         *       "../"  - Bin directory curDir
         *    "../../"  - OpenCL project curDir
         * "../../../"  - MSVC sets curDir to the project dir (= "hostSoft")
         *
         * \note  But from another side it's dangerously to scan up to 3 levels by trying to find a requested file.\n
         *        especially if there's a special folder structure with different series...
         *        Therefore for Unix it's applied only for one parent as we run from the bin directory, \n
         *        but usually use images by path like this: "data/pair".
         */
        string path(pathName);
        string prefix;
#ifdef WIN32
        cuint numRecursiveFoldersToCheck = 3;
#else
        cuint numRecursiveFoldersToCheck = 1;               // one check for parent dir is ok or also dangerously?
#endif
        for (unsigned k = 0; k < numRecursiveFoldersToCheck; k++)
        {
            path  .insert(0, "../");
            prefix.insert(0, "../");                        // try at folder one step up
            if (QFile::exists(path.c_str()))
            {
                mPathPrefix.assign(prefix);
                break;
            }
        }
    }
    return mPathPrefix + pathName;
}
QString ImageCaptureInterface::getInterfaceName () [virtual, inherited]
Return the interface device string.
Reimplemented in V4L2CaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 181 of file imageCaptureInterface.cpp.
Referenced by CapSettingsDialog::loadFromQSettings(), and CapSettingsDialog::saveToQSettings().
{
    return "";
}
void ImageFileCaptureInterface::increaseImageFileCounter () [inline, inherited]
Definition at line 25 of file imageFileCaptureInterface.h.
Referenced by getFrame(), FilePreciseCapture::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
{ mCount++;   }
ImageCaptureInterface::CapErrorCode FileCaptureInterface::initCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 66 of file fileCapture.cpp.
References ImageCaptureInterface::SUCCESS.
{
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::newFrameReady (frame_data_t frameData) [signal, inherited]
Referenced by DirectShowCaptureDecoupleInterface::memberCallback(), DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newImageReady () [signal, inherited]
Referenced by DirectShowCaptureInterface::memberCallback(), and ImageCaptureInterface::notifyAboutNewFrame().
void ImageCaptureInterface::newStatisticsReady (CaptureStatistics stats) [signal, inherited]
Referenced by V4L2CaptureDecoupleInterface::getFrame(), UEyeCaptureInterface::getFrame(), V4L2CaptureInterface::getFrame(), V4L2CaptureInterface::getFrameRGB24(), DirectShowCaptureDecoupleInterface::memberCallback(), and DirectShowCaptureInterface::memberCallback().
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::nextFrame () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 206 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::nextFrame(), and BaseHostDialog::play().
{
    return FAILURE;
}
void ImageCaptureInterface::notifyAboutNewFrame (frame_data_t frameData) [protected, virtual, inherited]
Internal function to trigger frame notify signal.
Definition at line 145 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::newFrameReady(), and ImageCaptureInterface::newImageReady().
Referenced by AbstractFileCaptureSpinThread::run(), OpenCVCaptureInterface::SpinThread::run(), V4L2CaptureDecoupleInterface::SpinThread::run(), UEyeCaptureInterface::SpinThread::run(), and V4L2CaptureInterface::SpinThread::run().
{
    emit newFrameReady(frameData);
    emit newImageReady();
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::pauseCapture () [virtual, inherited]
Reimplemented in AbstractFileCapture.
Definition at line 201 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by BaseHostDialog::stopCapture().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::queryCameraParameters (CameraParameters & parameter) [virtual, inherited]
Check if a specific property can be set/read and what values it can take.
Reimplemented in DirectShowCaptureInterface, V4L2CaptureInterface, DirectShowCaptureDecoupleInterface, UEyeCaptureInterface, and V4L2CaptureDecoupleInterface.
Definition at line 211 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::SUCCESS.
Referenced by CapSettingsDialog::refreshDialog().
{
    Q_UNUSED(parameter)
    return ImageCaptureInterface::SUCCESS;
}
void ImageFileCaptureInterface::resetImageFileCounter () [inline, inherited]
Definition at line 26 of file imageFileCaptureInterface.h.
Referenced by getFrame(), FilePreciseCapture::FileSpinThread::grabFramePair(), and ImageFileCaptureInterface::ImageFileCaptureInterface().
{ mCount = 1; }
ImageCaptureInterface::CapErrorCode ImageCaptureInterface::setCaptureProperty (int id, int value) [virtual, inherited]
Reimplemented in OpenCVCaptureInterface, DirectShowCaptureInterface, DirectShowCaptureDecoupleInterface, V4L2CaptureInterface, UEyeCaptureInterface, V4L2CaptureDecoupleInterface, and AbstractFileCapture.
Definition at line 161 of file imageCaptureInterface.cpp.
References ImageCaptureInterface::FAILURE.
Referenced by CapSettingsDialog::parameterChanged(), and CapSettingsDialog::resetPressed().
{
    return FAILURE;
}
ImageCaptureInterface::CapErrorCode FileCaptureInterface::startCapture () [virtual]
Reimplemented from ImageCaptureInterface.
Definition at line 71 of file fileCapture.cpp.
References ImageCaptureInterface::SUCCESS.
{
    return ImageCaptureInterface::SUCCESS;
}
void ImageCaptureInterface::streamPaused () [signal, inherited]
Referenced by AbstractFileCapture::notifyAboutStreamPaused().
bool ImageCaptureInterface::supportPause () [virtual, inherited]
Check if particular image capturer support pausing.
This function can be called before starting or even initing the capture
Reimplemented in AbstractFileCapture.
Definition at line 217 of file imageCaptureInterface.cpp.
{
    return false;
}
Member Data Documentation
bool ImageCaptureInterface::isRgb = false [static, inherited]
Definition at line 139 of file imageCaptureInterface.h.
Referenced by ImageCaptureInterface::fabric(), and Frames::fetchNewFrames().
unsigned ImageFileCaptureInterface::mCount [protected, inherited]
Definition at line 31 of file imageFileCaptureInterface.h.
Referenced by getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
string ImageFileCaptureInterface::mPathFmt [protected, inherited]
Definition at line 29 of file imageFileCaptureInterface.h.
Referenced by AbstractFileCapture::AbstractFileCapture(), FileCaptureInterface(), FilePreciseCapture::FilePreciseCapture(), ImageFileCaptureInterface::getImageFileName(), ImageFileCaptureInterface::ImageFileCaptureInterface(), and OpenCvFileCapture::OpenCvFileCapture().
bool ImageFileCaptureInterface::mVerbose [protected, inherited]
Definition at line 30 of file imageFileCaptureInterface.h.
Referenced by FilePreciseCapture::FilePreciseCapture(), getFrame(), FilePreciseCapture::getFrame(), and FilePreciseCapture::FileSpinThread::grabFramePair().
string ImageFileCaptureInterface::sPgmImageFileFmt = "image%04u_c%d.pgm" [static, inherited]
Definition at line 23 of file imageFileCaptureInterface.h.
Referenced by ImageFileCaptureInterface::getImageFileName().
The documentation for this class was generated from the following files:
utils/framesources/fileCapture.h
utils/framesources/fileCapture.cpp