DeepView: Plane3DScene Class Reference
Plane3DScene Class Reference
#include <mesh3DScene.h>
Public Types
enum SceneType { SCENE_3D, COORDINATE_FRAME }
Public Member Functions
Plane3DScene ()
virtual void prepareMesh (CloudViewDialog *dialog)
virtual void drawMyself (CloudViewDialog *dialog)
virtual void commonSetup (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void commonTierdown (CloudViewDialog *dialog, const Draw3dParameters *parameters)
virtual void draw (CloudViewDialog *dialog)
virtual void dumpPCD (ostream &out)
virtual void dumpPLY (ostream &out)
virtual void setParameters (void *)
virtual
ParametersControlWidgetBase * getContolWidget ()
virtual bool isComplexObject ()
Public Attributes
QString name
Scene3D * parent
SceneType type
Matrix44 transform
bool visible
Private Attributes
GLuint mPlaneListId
Detailed Description
Definition at line 78 of file mesh3DScene.h.
Member Enumeration Documentation
enum Scene3D::SceneType [inherited]
Enumerator:
SCENE_3D
COORDINATE_FRAME
Definition at line 31 of file scene3D.h.
                   {
        SCENE_3D,
        COORDINATE_FRAME
    };
Constructor & Destructor Documentation
Plane3DScene::Plane3DScene () [inline]
Definition at line 82 of file mesh3DScene.h.
                   :
        mPlaneListId(0)
    {}
Member Function Documentation
void Scene3D::commonSetup (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 102 of file scene3D.cpp.
References corecvs::Matrix44::a(), CORE_UNUSED, Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), corecvs::RectificationResult::decomposition, Draw3dTextureGen::FORCE_TEXTURE, corecvs::RectificationResult::getCameraShift(), corecvs::CameraIntrinsics::getVFov(), Scene3D::initDecalState(), corecvs::Matrix44::inverted(), Frames::LEFT_FRAME, corecvs::RectificationResult::leftCamera, CloudViewDialog::mRectificationResult, corecvs::CameraIntrinsics::resolution, Frames::RIGHT_FRAME, corecvs::EssentialDecomposition::rotation, CloudViewDialog::texture(), Draw3dParameters::textureCorrodinates(), Draw3dParameters::textureScale(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        Matrix44 textureMatrix = Matrix44::Scale(parameters->textureScale());
        glEnable(GL_TEXTURE_GEN_S);
        glEnable(GL_TEXTURE_GEN_T);
        GLint mode = GL_OBJECT_LINEAR;
        glTexGeni (GL_S, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_S, GL_OBJECT_PLANE, &textureMatrix.a(0,0));
        glTexGeni (GL_T, GL_TEXTURE_GEN_MODE, mode);
        glTexGendv(GL_T, GL_OBJECT_PLANE, &textureMatrix.a(1,0));
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        CameraIntrinsics *intrinsics = &(dialog->mRectificationResult->rightCamera);
        double fovR = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovR, aspect);
        glActiveTexture(GL_TEXTURE1);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::RIGHT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::RIGHT_FRAME));
            } else {
                qDebug() << "No texture for right camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE );
            initDecalState(dialog, parameters, projector);
        glActiveTexture(GL_TEXTURE0);
#else
        CORE_UNUSED(dialog);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        RectificationResult *rectification = dialog->mRectificationResult.data();
        CameraIntrinsics *intrinsics = &(rectification->leftCamera);
        double fovL = intrinsics->getVFov();
        double aspect = intrinsics->resolution.x() / intrinsics->resolution.y();
        Matrix44 projector = Matrix44::Frustum(fovL, aspect);
        projector = projector * (Matrix44(rectification->decomposition.rotation) * Matrix44::Shift(rectification->getCameraShift())).inverted();
        glActiveTexture(GL_TEXTURE2);
            glEnable(GL_TEXTURE_2D);
            if (dialog->texture(Frames::LEFT_FRAME) != (GLuint)-1) {
                glBindTexture(GL_TEXTURE_2D, dialog->texture(Frames::LEFT_FRAME));
            } else {
                qDebug() << "No texture for left camera";
            }
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T    , GL_REPEAT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
            glTexEnvf ( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL );
            initDecalState(dialog, parameters, projector);
        if (parameters->decalRightCam()) {
            qDebug() << "Both cameras. Making a merge";
            glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB, GL_INTERPOLATE);   //Interpolate RGB with RGB
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_RGB, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_RGB, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_RGB, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB, GL_SRC_COLOR);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB, GL_SRC_COLOR);
            //------------------------
            glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_ALPHA, GL_INTERPOLATE);   //Interpolate ALPHA with ALPHA
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE0_ALPHA, GL_PREVIOUS);
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE1_ALPHA, GL_TEXTURE);
            //GL_CONSTANT refers to the call we make with glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor)
            glTexEnvi(GL_TEXTURE_ENV, GL_SOURCE2_ALPHA, GL_CONSTANT);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_ALPHA, GL_SRC_ALPHA);
            glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_ALPHA, GL_SRC_ALPHA);
            //------------------------
            float mycolor[4] = {0.5, 0.5, 0.5, 0.5};
            glTexEnvfv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_COLOR, mycolor);
        }
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::commonTierdown (CloudViewDialog * dialog, const Draw3dParameters * parameters) [virtual, inherited]
Definition at line 202 of file scene3D.cpp.
References Draw3dParameters::decalLeftCam(), Draw3dParameters::decalRightCam(), Draw3dTextureGen::FORCE_TEXTURE, and Draw3dParameters::textureCorrodinates().
Referenced by Mesh3DScene::drawMyself().
{
    if (parameters->textureCorrodinates() == Draw3dTextureGen::FORCE_TEXTURE) {
        glDisable(GL_TEXTURE_GEN_S);
        glDisable(GL_TEXTURE_GEN_T);
    }
    if (parameters->decalRightCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE1);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
    if (parameters->decalLeftCam()) {
#ifdef WITH_OPENGLEXT
        glActiveTexture(GL_TEXTURE2);
            glDisable(GL_TEXTURE_GEN_S);
            glDisable(GL_TEXTURE_GEN_T);
            glDisable(GL_TEXTURE_GEN_R);
            glDisable(GL_TEXTURE_GEN_Q);
            glDisable(GL_TEXTURE_2D);
        glActiveTexture(GL_TEXTURE0);
#endif
    }
}
void Scene3D::draw (CloudViewDialog * dialog) [virtual, inherited]
Definition at line 19 of file scene3D.cpp.
References Scene3D::drawMyself(), OpenGLTools::glMultMatrixMatrix44(), Scene3D::transform, and Scene3D::visible.
{
    if (!visible) {
//        qDebug() << name << "(" << ((void *)this) << ")" << " is invisible";
        return;
    }
//    qDebug() << name << "(" << ((void *)this) << ")" << " is drawn";
    glMatrixMode(GL_MODELVIEW);
    glPushMatrix();
      OpenGLTools::glMultMatrixMatrix44(transform);
      this->drawMyself(dialog);
    glPopMatrix();
}
void Plane3DScene::drawMyself (CloudViewDialog * dialog) [virtual]
Reimplemented from Scene3D.
Definition at line 207 of file mesh3DScene.cpp.
References mPlaneListId.
{
    //qDebug() << "Calling Plane3DScene::drawMyself() for" << name;
    if (mPlaneListId == 0)
    {
        qDebug("Grid3DScene was not initialized");
    }
    glDisable(GL_TEXTURE_2D);
    glCallList(mPlaneListId);
   // glEnable(GL_TEXTURE_2D);
}
void Scene3D::dumpPCD (ostream & out) [virtual, inherited]
Reimplemented in Mesh3DScene, Scene3DMouse, and CoordinateFrame.
Definition at line 246 of file scene3D.cpp.
{
}
void Scene3D::dumpPLY (ostream & out) [virtual, inherited]
Reimplemented in Mesh3DScene, Scene3DMouse, and CoordinateFrame.
Definition at line 251 of file scene3D.cpp.
{
}
virtual ParametersControlWidgetBase* Scene3D::getContolWidget () [inline, virtual, inherited]
Reimplemented in CameraScene, Mesh3DScene, CoordinateFrame, and Scene3DMouse.
Definition at line 58 of file scene3D.h.
    {
//        qDebug("Scene3D::getContolWidget() : Called");
        return NULL;
    };
virtual bool Scene3D::isComplexObject () [inline, virtual, inherited]
Definition at line 64 of file scene3D.h.
References Scene3D::COORDINATE_FRAME, and Scene3D::type.
    {
        return (type == COORDINATE_FRAME);
    }
void Plane3DScene::prepareMesh (CloudViewDialog * dialog) [virtual]
Reimplemented from Scene3D.
Definition at line 148 of file mesh3DScene.cpp.
References mPlaneListId.
{
    //qDebug() << "Calling Plane3DScene::prepareMesh() for" << name;
    mPlaneListId = glGenLists(1);
    if (mPlaneListId == 0) {
        qDebug("Plane3DScene failed to create display list");
        return;
    }
    glNewList(mPlaneListId,GL_COMPILE);
    glBegin(GL_LINES);
    glColor3ub(0,255,255);
    const double STEP = 10;
    const int    PLANE_SIZE = 50;
    for (int i = 0; i <= 2 * PLANE_SIZE; i++)
    {
        double x =  PLANE_SIZE * STEP;
        double z =  i * STEP;
        if        (i % 10 == 0) {
            glColor3ub( 128,128,0);
        } else if (i % 2 == 0) {
            glColor3ub( 0,128,128);
        } else {
            glColor3ub( 0, 64, 64);
        }
        glVertex3d(-x, 0, z);
        glVertex3d( x, 0, z);
    }
    for (int j = -PLANE_SIZE; j <= PLANE_SIZE; j++)
    {
        double x = j * STEP;
        double z = 2 * PLANE_SIZE * STEP;
        if        (j % 10 == 0) {
            glColor3ub( 128,128,0);
        } else if (j % 2 == 0) {
            glColor3ub( 0,128,128);
        } else {
            glColor3ub( 0, 64, 64);
        }
        glVertex3d(x, 0, 0);
        glVertex3d(x, 0, z);
    }
    glEnd();
    glDisable(GL_LINE_STIPPLE);
    glEndList();
}
virtual void Scene3D::setParameters (void *) [inline, virtual, inherited]
Reimplemented in CameraScene, Scene3DMouse, Mesh3DScene, and CoordinateFrame.
Definition at line 55 of file scene3D.h.
{};
Member Data Documentation
GLuint Plane3DScene::mPlaneListId [private]
Definition at line 79 of file mesh3DScene.h.
Referenced by drawMyself(), and prepareMesh().
QString Scene3D::name [inherited]
Definition at line 37 of file scene3D.h.
Referenced by CloudViewDialog::CloudViewDialog().
Scene3D* Scene3D::parent [inherited]
Definition at line 38 of file scene3D.h.
Matrix44 Scene3D::transform [inherited]
Definition at line 41 of file scene3D.h.
Referenced by Scene3D::draw().
SceneType Scene3D::type [inherited]
Definition at line 39 of file scene3D.h.
Referenced by CoordinateFrame::CoordinateFrame(), and Scene3D::isComplexObject().
bool Scene3D::visible [inherited]
Definition at line 42 of file scene3D.h.
Referenced by Scene3D::draw().
The documentation for this class was generated from the following files:
utils/3d/mesh3DScene.h
utils/3d/mesh3DScene.cpp