DeepView: corecvs::RGBColor Class Reference
corecvs::RGBColor Class Reference
I use inheritance because no new data members will be added.
#include <rgbColor.h>
Public Types
enum FieldId { FIELD_R = 0, FIELD_G = 1, FIELD_B = 2, FIELD_A = 3 }
typedef VectorOperationsBase
< RGBColor, uint8_t > BaseClass
typedef uint8_t InnerElementType
typedef ReflectionHelper
< uint8_t >::Type ReflectionType
Public Member Functions
RGBColor (uint32_t color)
RGBColor (const Vector3d32 &other)
RGBColor (uint8_t _r, uint8_t _g, uint8_t _b)
RGBColor ()
uint8_t & r ()
uint8_t & g ()
uint8_t & b ()
uint8_t & a ()
uint32_t & color ()
const uint8_t & r () const
const uint8_t & g () const
const uint8_t & b () const
uint32_t & color () const
uint8_t brightness () const
uint8_t luma () const
uint16_t luma12 () const
int16_t y () const
int16_t cb () const
int16_t cr () const
uint8_t value () const
uint8_t chroma () const
uint8_t saturation () const
uint16_t hue () const
template<class VisitorType >
void accept (VisitorType &visitor)
int size () const
uint8_t & operator[] (int n)
const uint8_t & operator[] (int n) const
uint8_t & at (int n)
const uint8_t & at (int n) const
RGBColor createVector (int) const
RGBColor * realThis ()
Static cast functions.
const RGBColor * realThis () const
bool operator== (const RGBColor &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const RGBColor &that) const
Inequality operator.
bool notTooFar (const RGBColor &that, const uint8_t &epsilon=uint8_t(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const RGBColor &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const RGBColor &V)
VectorOperationsBase & operator*= (const uint8_t &c)
VectorOperationsBase & operator/= (const uint8_t &c)
RGBColor operator- () const
Negative operator.
uint8_t sumAllElements () const
Sum of the elements of the vector.
uint8_t mulAllElements () const
Product of all elements of the vector.
uint8_t sumAllElementsSq () const
Sum of the squares of element of the vector.
uint8_t l2Metric () const
Euclidean distance.
uint8_t operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
RGBColor normalised () const
Return a normalized copy of vector.
RGBColor cloneVector () const
Return copy of vector.
uint8_t l1Metric () const
Sum of the absolute values of element of the vector.
uint8_t lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
uint8_t minimum () const
uint8_t maximum () const
Please don't use this for double so far.
void accept1 (VisitorType &visitor)
Static Public Member Functions
static RGBColor gray (uint8_t gray)
static RGBColor gray12 (uint16_t gray)
static RGBColor FromYUV (uint8_t y, uint8_t u, uint8_t v)
C = Y - 16 D = U - 128 E = V - 128 Using the previous coefficients and noting that clamp() denotes clamping a value to the range of 0 to 255, the following formulae provide the conversion from YUV to RGB (NTSC version): R = clamp((298 C + 409 E + 128) >> 8) G = clamp((298 C - 100 D - 208 E + 128) >> 8) B = clamp((298 C + 516 D + 128) >> 8)
static RGBColor Black ()
static RGBColor Red ()
static RGBColor Orange ()
static RGBColor Yellow ()
static RGBColor Green ()
static RGBColor Cyan ()
static RGBColor Blue ()
static RGBColor Indigo ()
static RGBColor Violet ()
static RGBColor lerpColor (const RGBColor &first, const RGBColor &second, double alpha)
static RGBColor rainbow (double x)
Helper method that allows to represent the double value in interval 0..1 With a real rainbow color coding.
static RGBColor rainbow1 (double x)
Helper method that allows to represent the double value in interval 0..1 With a color coding.
static Reflection staticInit ()
Public Attributes
uint8_t element [length]
Static Public Attributes
static Reflection reflect
static const int LENGTH
Friends
RGBColor operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
RGBColor operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
RGBColor operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
RGBColor operator* (const uint8_t &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
RGBColor operator* (const VectorOperationsBase &V, const uint8_t &c)
RGBColor operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
RGBColor operator/ (const VectorOperationsBase &V, const uint8_t &c)
Operator * does the component-specific multiplication by constant
.
uint8_t operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
I use inheritance because no new data members will be added.
Definition at line 20 of file rgbColor.h.
Member Typedef Documentation
typedef VectorOperationsBase<RGBColor , uint8_t > corecvs::FixedVectorBase< RGBColor , uint8_t , length >::BaseClass [inherited]
Definition at line 38 of file fixedVector.h.
typedef uint8_t corecvs::FixedVectorBase< RGBColor , uint8_t , length >::InnerElementType [inherited]
Definition at line 39 of file fixedVector.h.
typedef ReflectionHelper<uint8_t >::Type corecvs::VectorOperationsBase< RGBColor , uint8_t >::ReflectionType [inherited]
Definition at line 561 of file vectorOperations.h.
Member Enumeration Documentation
enum corecvs::RGBColor::FieldId
Enumerator:
FIELD_R
FIELD_G
FIELD_B
FIELD_A
Definition at line 23 of file rgbColor.h.
                 {
        FIELD_R = 0,
        FIELD_G = 1,
        FIELD_B = 2,
        FIELD_A = 3
    };
Constructor & Destructor Documentation
corecvs::RGBColor::RGBColor (uint32_t color) [inline, explicit]
Definition at line 33 of file rgbColor.h.
References a(), b(), g(), and r().
    {
        r() = color & 0xFF;
        g() = (color >> 8) & 0xFF;
        b() = (color >> 16) & 0xFF;
        a() = 0;
    }
corecvs::RGBColor::RGBColor (const Vector3d32 & other) [inline, explicit]
Definition at line 41 of file rgbColor.h.
References a(), b(), g(), and r().
    {
        r() = other[0];
        g() = other[1];
        b() = other[2];
        a() = 0;
    }
corecvs::RGBColor::RGBColor (uint8_t _r, uint8_t _g, uint8_t _b) [inline]
Definition at line 49 of file rgbColor.h.
References a(), b(), g(), and r().
    {
        this->r() = _r;
        this->g() = _g;
        this->b() = _b;
        this->a() = 0;
    }
corecvs::RGBColor::RGBColor () [inline]
Definition at line 57 of file rgbColor.h.
Referenced by Black(), Blue(), Cyan(), FromYUV(), gray(), gray12(), Green(), Indigo(), lerpColor(), Orange(), rainbow1(), Red(), Violet(), and Yellow().
    {
    }
Member Function Documentation
uint8_t& corecvs::RGBColor::a () [inline]
Definition at line 76 of file rgbColor.h.
Referenced by accept(), and RGBColor().
    {
        return (*this)[3];
    }
template<class VisitorType > void corecvs::RGBColor::accept (VisitorType & visitor) [inline]
Reimplemented from corecvs::VectorOperationsBase< RGBColor, uint8_t >.
Definition at line 380 of file rgbColor.h.
References a(), b(), FIELD_A, FIELD_B, FIELD_G, FIELD_R, corecvs::Reflection::fields, g(), r(), and reflect.
    {
        visitor.visit(r(), static_cast<const IntField *>(reflect.fields[FIELD_R]));
        visitor.visit(g(), static_cast<const IntField *>(reflect.fields[FIELD_G]));
        visitor.visit(b(), static_cast<const IntField *>(reflect.fields[FIELD_B]));
        visitor.visit(a(), static_cast<const IntField *>(reflect.fields[FIELD_A]));
    }
void corecvs::VectorOperationsBase< RGBColor , uint8_t >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
uint8_t & corecvs::FixedVectorBase< RGBColor , uint8_t , length >::at (int n) [inline, inherited]
Definition at line 108 of file fixedVector.h.
    {
        return element[n];
    }
const uint8_t & corecvs::FixedVectorBase< RGBColor , uint8_t , length >::at (int n) const [inline, inherited]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
uint8_t& corecvs::RGBColor::b () [inline]
Definition at line 71 of file rgbColor.h.
Referenced by accept(), brightness(), cb(), PaintImageWidget::childRepaint(), chroma(), cr(), Scene3DMouse::dumpPLY(), FromYUV(), OpenGLTools::glColorRGB(), hue(), lerpColor(), luma(), luma12(), TolerancePredicate::operator()(), TestbedMainWindow::recursiveTolerance(), RGBColor(), saturation(), corecvs::BMPLoader::save(), TestbedMainWindow::updateViewImage(), value(), and y().
    {
        return (*this)[0];
    }
const uint8_t& corecvs::RGBColor::b () const [inline]
Definition at line 97 of file rgbColor.h.
    {
        return (*this)[0];
    }
static RGBColor corecvs::RGBColor::Black () [inline, static]
Definition at line 274 of file rgbColor.h.
References RGBColor().
    {
        return RGBColor(0, 0, 0);
    }
static RGBColor corecvs::RGBColor::Blue () [inline, static]
Definition at line 304 of file rgbColor.h.
References RGBColor().
Referenced by rainbow().
    {
        return RGBColor(0, 0, 255);
    }
uint8_t corecvs::RGBColor::brightness () const [inline]
TODO: Should I add ~1.5 = 2 to the sum? because 0, 1, 1 -> 1 255,255,254 -> 255;
Definition at line 108 of file rgbColor.h.
References b(), g(), and r().
    {
        /**
         * TODO: Should I add ~1.5 = 2 to the sum?
         * because
         *     0,  1,  1 -> 1
         *   255,255,254 -> 255;
         *
         * */
        return ((uint16_t)r() + (uint16_t)g() + (uint16_t)b()) / 3;
    }
int16_t corecvs::RGBColor::cb () const [inline]
Definition at line 139 of file rgbColor.h.
References b(), g(), and r().
    {
        return (int)(-0.16874 * r() - 0.33126 * g() + 0.50000 * b());
    }
uint8_t corecvs::RGBColor::chroma () const [inline]
Definition at line 169 of file rgbColor.h.
References b(), g(), and r().
    {
        uint8_t m;
        uint8_t M;
        if (r() > g())
        {
          m = g();
          M = r();
        } else {
          M = g();
          m = r();
        }
        if (m > b()) m = b();
        if (M < b()) M = b();
        return M - m;
    }
RGBColor corecvs::VectorOperationsBase< RGBColor , uint8_t >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), corecvs::VectorOperationsBase< RealType, ElementType >::_createVector(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
uint32_t& corecvs::RGBColor::color () [inline]
Definition at line 81 of file rgbColor.h.
Referenced by Scene3DMouse::dumpPCD().
    {
        return (*(uint32_t *)this);
    }
uint32_t& corecvs::RGBColor::color () const [inline]
Definition at line 102 of file rgbColor.h.
    {
       return (*(uint32_t *)this);
    }
int16_t corecvs::RGBColor::cr () const [inline]
Definition at line 144 of file rgbColor.h.
References b(), g(), and r().
    {
        return (int)( 0.50000 * r() - 0.41869 * g() - 0.08131 * b());
    }
RGBColor corecvs::FixedVectorBase< RGBColor , uint8_t , length >::createVector (int) const [inline, inherited]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
static RGBColor corecvs::RGBColor::Cyan () [inline, static]
Definition at line 299 of file rgbColor.h.
References RGBColor().
    {
        return RGBColor(0, 255, 255);
    }
static RGBColor corecvs::RGBColor::FromYUV (uint8_t y, uint8_t u, uint8_t v) [inline, static]
C = Y - 16 D = U - 128 E = V - 128 Using the previous coefficients and noting that clamp() denotes clamping a value to the range of 0 to 255, the following formulae provide the conversion from YUV to RGB (NTSC version): R = clamp((298 C + 409 E + 128) >> 8) G = clamp((298 C - 100 D - 208 E + 128) >> 8) B = clamp((298 C + 516 D + 128) >> 8)
Definition at line 261 of file rgbColor.h.
References b(), g(), r(), and RGBColor().
    {
        int c = y - 16;
        int d = u - 128;
        int e = v - 128;
        int r =  ((298 * c           + 409 * e + 128) >> 8);
        int g =  ((298 * c - 100 * d - 208 * e + 128) >> 8);
        int b =  ((298 * c + 516 * d           + 128) >> 8);
        return RGBColor(r,g,b);
    }
uint8_t& corecvs::RGBColor::g () [inline]
Definition at line 66 of file rgbColor.h.
Referenced by accept(), brightness(), cb(), PaintImageWidget::childRepaint(), chroma(), cr(), Scene3DMouse::dumpPLY(), FromYUV(), OpenGLTools::glColorRGB(), hue(), lerpColor(), luma(), luma12(), TolerancePredicate::operator()(), TestbedMainWindow::recursiveTolerance(), RGBColor(), saturation(), corecvs::BMPLoader::save(), TestbedMainWindow::updateViewImage(), value(), and y().
    {
        return (*this)[1];
    }
const uint8_t& corecvs::RGBColor::g () const [inline]
Definition at line 92 of file rgbColor.h.
    {
        return (*this)[1];
    }
static RGBColor corecvs::RGBColor::gray (uint8_t gray) [inline, static]
Definition at line 242 of file rgbColor.h.
References RGBColor().
Referenced by corecvs::RGB24Buffer::drawIsolines().
    {
        return RGBColor(gray, gray, gray);
    }
static RGBColor corecvs::RGBColor::gray12 (uint16_t gray) [inline, static]
Definition at line 247 of file rgbColor.h.
References RGBColor().
    {
        return RGBColor(gray >> 4, gray >> 4, gray >> 4);
    }
static RGBColor corecvs::RGBColor::Green () [inline, static]
Definition at line 294 of file rgbColor.h.
References RGBColor().
Referenced by rainbow().
    {
        return RGBColor(0, 255, 0);
    }
uint16_t corecvs::RGBColor::hue () const [inline]
Definition at line 206 of file rgbColor.h.
References b(), g(), and r().
    {
        uint8_t m;
        uint8_t M;
        int16_t hue;
        if (r() > g())
        {
            m = g();
            M = r();
        } else {
            M = g();
            m = r();
        }
        if (m > b()) m = b();
        if (M < b()) M = b();
        uint8_t c = M - m;
        if (c == 0) return 0;
        if (M == r())
        {
            hue = (g() - b()) * 60 / c;
            if (hue < 0) hue += 360;
            return hue;
        }
        if (M == g())
        {
            hue = (b() - r()) * 60 / c + 120;
            return hue;
        }
        /* M == b() */
        hue = (r() - g()) * 60 / c + 240;
        return hue;
    }
static RGBColor corecvs::RGBColor::Indigo () [inline, static]
Definition at line 309 of file rgbColor.h.
References RGBColor().
Referenced by rainbow().
    {
        return RGBColor(111, 0, 255);
    }
bool corecvs::VectorOperationsBase< RGBColor , uint8_t >::isInHypercube (const VectorOperationsBase< RGBColor, uint8_t > & low, const VectorOperationsBase< RGBColor, uint8_t > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElementsSq().
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
static RGBColor corecvs::RGBColor::lerpColor (const RGBColor & first, const RGBColor & second, double alpha) [inline, static]
Definition at line 319 of file rgbColor.h.
References b(), g(), r(), and RGBColor().
Referenced by rainbow().
    {
        uint8_t r = (uint8_t)lerp<double>(first.r(), second.r(),alpha);
        uint8_t g = (uint8_t)lerp<double>(first.g(), second.g(),alpha);
        uint8_t b = (uint8_t)lerp<double>(first.b(), second.b(),alpha);
        return RGBColor(r, g, b);
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
uint8_t corecvs::RGBColor::luma () const [inline]
Definition at line 121 of file rgbColor.h.
References b(), g(), and r().
    {
        return (11 * r() + 16 * g() + 5 * b()) >> 4;
    }
uint16_t corecvs::RGBColor::luma12 () const [inline]
Definition at line 127 of file rgbColor.h.
References b(), g(), and r().
Referenced by corecvs::BMPLoader::load().
    {
        return (5 * (int)r() + 8 * (int)g() + 2 * (int)b());
        //return (11 * r() + 16 * g() + 5 * b()) >> 1;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::maximum (void) const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), corecvs::VectorOperationsBase< RealType, ElementType >::_size(), and corecvs::VectorOperationsBase< RealType, ElementType >::maximum().
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::minimum (void) const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), corecvs::VectorOperationsBase< RealType, ElementType >::_size(), and corecvs::VectorOperationsBase< RealType, ElementType >::minimum().
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
void corecvs::VectorOperationsBase< RGBColor , uint8_t >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Definition at line 407 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric(), and corecvs::VectorOperationsBase< RealType, ElementType >::operator/=().
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
RGBColor corecvs::VectorOperationsBase< RGBColor , uint8_t >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Definition at line 420 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::cloneVector(), and corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric().
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
bool corecvs::VectorOperationsBase< RGBColor , uint8_t >::notTooFar (const RGBColor & that, const uint8_t & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric().
    {
        return l2Metric();
    };
bool corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator!= (const RGBColor & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::operator==().
    {
        return !(operator ==(that));
    }
VectorOperationsBase& corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator*= (const uint8_t & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator+= (const RGBColor & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
RGBColor corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), corecvs::VectorOperationsBase< RealType, ElementType >::_createVector(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator-= (const RGBColor & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
VectorOperationsBase& corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator/= (const uint8_t & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
bool corecvs::VectorOperationsBase< RGBColor , uint8_t >::operator== (const RGBColor & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
uint8_t & corecvs::FixedVectorBase< RGBColor , uint8_t , length >::operator[] (int n) [inline, inherited]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
const uint8_t & corecvs::FixedVectorBase< RGBColor , uint8_t , length >::operator[] (int n) const [inline, inherited]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
static RGBColor corecvs::RGBColor::Orange () [inline, static]
Definition at line 284 of file rgbColor.h.
References RGBColor().
Referenced by rainbow().
    {
        return RGBColor(255, 127, 0);
    }
void corecvs::VectorOperationsBase< RGBColor , uint8_t >::print () const [inline, inherited]
Definition at line 525 of file vectorOperations.h.
    {
        cout << *this;
    }
void corecvs::VectorOperationsBase< RGBColor , uint8_t >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::print().
    {
        print();
        cout << "\n";
    }
uint8_t& corecvs::RGBColor::r () [inline]
Definition at line 61 of file rgbColor.h.
Referenced by accept(), brightness(), cb(), PaintImageWidget::childRepaint(), chroma(), cr(), Scene3DMouse::dumpPLY(), FromYUV(), OpenGLTools::glColorRGB(), hue(), lerpColor(), luma(), luma12(), TolerancePredicate::operator()(), TestbedMainWindow::recursiveTolerance(), RGBColor(), saturation(), corecvs::BMPLoader::save(), TestbedMainWindow::updateViewImage(), value(), and y().
    {
        return (*this)[2];
    }
const uint8_t& corecvs::RGBColor::r () const [inline]
Definition at line 87 of file rgbColor.h.
    {
        return (*this)[2];
    }
RGBColor corecvs::RGBColor::rainbow (double x) [static]
Helper method that allows to represent the double value in interval 0..1 With a real rainbow color coding.
0.0 Red (web color) (Hex: #FF0000) (RGB: 255, 0, 0)
1/6 Orange (color wheel Orange) (Hex: #FF7F00) (RGB: 255, 127, 0)
2/6 Yellow (web color) (Hex: #FFFF00) (RGB: 255, 255, 0)
3/6 Green (X11) (Electric Green) (HTML/CSS Lime) (Color wheel green) (Hex: #00FF00) (RGB: 0, 255, 0)
4/6 Blue (web color) (Hex: #0000FF) (RGB: 0, 0, 255)
5/6 Indigo (Electric Indigo) (Hex: #6600FF) (RGB: 111, 0, 255)
1.0 Violet (Electric Violet) (Hex: #8B00FF) (RGB: 143, 0, 255)
Definition at line 20 of file rgbColor.cpp.
References Blue(), Green(), Indigo(), lerpColor(), Orange(), Red(), Violet(), and Yellow().
Referenced by corecvs::RGB24Buffer::drawFunction().
{
    x *= 6;
    if (x < 0.0) x = 0.0;
    if (x > 6.0) x = 6.0;
    switch ((int)x)
    {
        case 0:
            return lerpColor(   Red(), Orange(), x);
        case 1:
            return lerpColor(Orange(), Yellow(), x - 1);
        case 2:
            return lerpColor(Yellow(),  Green(), x - 2);
        case 3:
            return lerpColor( Green(),   Blue(), x - 3);
        case 4:
            return lerpColor(  Blue(), Indigo(), x - 4);
        case 5:
        default:
            return lerpColor(Indigo(), Violet(), x - 5);
    }
}
static RGBColor corecvs::RGBColor::rainbow1 (double x) [inline, static]
Helper method that allows to represent the double value in interval 0..1 With a color coding.
0.0 blue
0.5 green
1.0 red
Definition at line 352 of file rgbColor.h.
References corecvs::fround(), and RGBColor().
Referenced by corecvs::RGB24Buffer::drawCorrespondanceList(), corecvs::RGB24Buffer::drawFlowBuffer1(), corecvs::RGB24Buffer::drawFlowBuffer2(), and corecvs::RGB24Buffer::drawFlowBuffer3().
    {
        x *= 2;
        if (x < 0.0) x = 0.0;
        if (x > 2.0) x = 2.0;
        if (x < 1.0)
        {
            return RGBColor(0, fround(x * 255) , fround((1.0 - x) * 255));
        }
        x -= 1.0;
        return RGBColor(fround(x * 255) , fround((1.0 - x) * 255), 0 );
    }
RGBColor * corecvs::VectorOperationsBase< RGBColor , uint8_t >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
{
        return static_cast<RealType *>(this);
    }
const RGBColor * corecvs::VectorOperationsBase< RGBColor , uint8_t >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
static RGBColor corecvs::RGBColor::Red () [inline, static]
Definition at line 279 of file rgbColor.h.
References RGBColor().
Referenced by rainbow().
    {
        return RGBColor(255, 0, 0);
    }
uint8_t corecvs::RGBColor::saturation () const [inline]
Definition at line 187 of file rgbColor.h.
References b(), g(), and r().
    {
        uint8_t m;
        uint8_t M;
        if (r() > g())
        {
          m = g();
          M = r();
        } else {
          M = g();
          m = r();
        }
        if (m > b()) m = b();
        if (M < b()) M = b();
        return M == 0 ? 0 : (M - m) * 255 / M;
    }
int corecvs::FixedVectorBase< RGBColor , uint8_t , length >::size () const [inline, inherited]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
static Reflection corecvs::RGBColor::staticInit () [inline, static]
Definition at line 369 of file rgbColor.h.
References FIELD_A, FIELD_B, FIELD_G, FIELD_R, and corecvs::Reflection::fields.
    {
        Reflection reflection;
        reflection.fields.push_back( new IntField(FIELD_R, 0, "r") );
        reflection.fields.push_back( new IntField(FIELD_G, 0, "g") );
        reflection.fields.push_back( new IntField(FIELD_B, 0, "b") );
        reflection.fields.push_back( new IntField(FIELD_A, 0, "a") );
        return reflection;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
uint8_t corecvs::VectorOperationsBase< RGBColor , uint8_t >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
References corecvs::VectorOperationsBase< RealType, ElementType >::_at(), and corecvs::VectorOperationsBase< RealType, ElementType >::_size().
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
uint8_t corecvs::RGBColor::value () const [inline]
Definition at line 151 of file rgbColor.h.
References b(), g(), and r().
    {
       uint8_t m;
       uint8_t M;
       if (r() > g())
       {
         m = g();
         M = r();
       } else {
         M = g();
         m = r();
       }
       if (m > b()) m = b();
       if (M < b()) M = b();
       return M;
    }
static RGBColor corecvs::RGBColor::Violet () [inline, static]
Definition at line 314 of file rgbColor.h.
References RGBColor().
Referenced by rainbow().
    {
        return RGBColor(143, 0, 255);
    }
int16_t corecvs::RGBColor::y () const [inline]
Definition at line 134 of file rgbColor.h.
References b(), g(), and r().
    {
        return (int)( 0.299   * r() + 0.587   * g() + 0.114   * b());
    }
static RGBColor corecvs::RGBColor::Yellow () [inline, static]
Definition at line 289 of file rgbColor.h.
References RGBColor().
Referenced by rainbow().
    {
        return RGBColor(255, 255, 0);
    }
Friends And Related Function Documentation
uint8_t operator& (const VectorOperationsBase< RGBColor, uint8_t > & V1, const VectorOperationsBase< RGBColor, uint8_t > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
RGBColor operator* (const VectorOperationsBase< RGBColor, uint8_t > & V1, const VectorOperationsBase< RGBColor, uint8_t > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
RGBColor operator* (const uint8_t & c, const VectorOperationsBase< RGBColor, uint8_t > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
RGBColor operator* (const VectorOperationsBase< RGBColor, uint8_t > & V, const uint8_t & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
RGBColor operator+ (const VectorOperationsBase< RGBColor, uint8_t > & V1, const VectorOperationsBase< RGBColor, uint8_t > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
RGBColor operator- (const VectorOperationsBase< RGBColor, uint8_t > & V1, const VectorOperationsBase< RGBColor, uint8_t > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
RGBColor operator/ (const VectorOperationsBase< RGBColor, uint8_t > & V1, const VectorOperationsBase< RGBColor, uint8_t > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
RGBColor operator/ (const VectorOperationsBase< RGBColor, uint8_t > & V, const uint8_t & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
ostream& operator<< (ostream & out, const VectorOperationsBase< RGBColor, uint8_t > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
istream& operator>> (istream & in, VectorOperationsBase< RGBColor, uint8_t > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
Member Data Documentation
uint8_t corecvs::FixedVectorBase< RGBColor , uint8_t , length >::element[length] [inherited]
Definition at line 42 of file fixedVector.h.
const int corecvs::FixedVectorBase< RGBColor , uint8_t , length >::LENGTH [static, inherited]
Definition at line 37 of file fixedVector.h.
Reflection corecvs::RGBColor::reflect [static]
Definition at line 367 of file rgbColor.h.
Referenced by accept().
The documentation for this class was generated from the following files:
core/buffers/rgb24/rgbColor.h
core/buffers/rgb24/rgbColor.cpp