DeepView: AbstractFileCaptureSpinThread Class Reference
AbstractFileCaptureSpinThread Class Reference
#include <abstractFileCaptureSpinThread.h>
Public Member Functions
AbstractFileCaptureSpinThread (AbstractFileCapture *pInterface, int delay, ImageCaptureInterface::FramePair &framePair)
virtual ~AbstractFileCaptureSpinThread ()
virtual void run ()
void togglePause ()
void nextFrame ()
virtual bool grabFramePair ()=0
Protected Member Functions
void pause ()
Protected Attributes
ImageCaptureInterface::FramePair & mFramePair
AbstractFileCapture * mInterface
Private Attributes
bool mPaused
bool mNextFrameNeeded
int mDelay
Detailed Description
Definition at line 9 of file abstractFileCaptureSpinThread.h.
Constructor & Destructor Documentation
AbstractFileCaptureSpinThread::AbstractFileCaptureSpinThread (AbstractFileCapture * pInterface, int delay, ImageCaptureInterface::FramePair & framePair)
Definition at line 4 of file abstractFileCaptureSpinThread.cpp.
    : mFramePair(framePair)
    , mInterface(pInterface)
    , mPaused(false)
    , mNextFrameNeeded(false)
    , mDelay(delay)
{
}
virtual AbstractFileCaptureSpinThread::~AbstractFileCaptureSpinThread () [inline, virtual]
Definition at line 13 of file abstractFileCaptureSpinThread.h.
{}
Member Function Documentation
virtual bool AbstractFileCaptureSpinThread::grabFramePair () [pure virtual]
Implemented in FilePreciseCapture::FileSpinThread, and OpenCvFileCapture::SpinThread.
Referenced by run().
void AbstractFileCaptureSpinThread::nextFrame ()
Definition at line 63 of file abstractFileCaptureSpinThread.cpp.
References mNextFrameNeeded.
Referenced by AbstractFileCapture::nextFrame().
{
    mNextFrameNeeded = true;
}
void AbstractFileCaptureSpinThread::pause () [protected]
Definition at line 68 of file abstractFileCaptureSpinThread.cpp.
References mInterface, mPaused, and AbstractFileCapture::notifyAboutStreamPaused().
{
    mPaused = true;
    mInterface->notifyAboutStreamPaused();
}
void AbstractFileCaptureSpinThread::run () [virtual]
Definition at line 17 of file abstractFileCaptureSpinThread.cpp.
References grabFramePair(), mDelay, mInterface, mNextFrameNeeded, mPaused, AbstractFileCapture::mTimeStamp, ImageCaptureInterface::notifyAboutNewFrame(), AbstractFileCapture::protectFrameMutex(), AbstractFileCapture::shouldStopSpinThread, AbstractFileCapture::spinThreadRunMutex(), and frame_data_t::timestamp.
{
    if (!grabFramePair())  // We must get a frame before querying for properties
    {
        printf("No frames.\n");
        return;
    }
    frame_data_t frameData;
    frameData.timestamp = mInterface->mTimeStamp;
    mInterface->notifyAboutNewFrame(frameData);
    while (mInterface->spinThreadRunMutex().tryLock())
    {
        if (mDelay != 0)
            msleep(mDelay);
        if (!mPaused || mNextFrameNeeded)
        {
            mNextFrameNeeded = false;
            mInterface->protectFrameMutex().lock();
                if (!grabFramePair()) {
                    printf("No more frames.\n");
                }
                else {
                    frame_data_t frameData;
                    frameData.timestamp = mInterface->mTimeStamp;
                    mInterface->notifyAboutNewFrame(frameData);
                }
            mInterface->protectFrameMutex().unlock();
        }
        mInterface->spinThreadRunMutex().unlock();
        if (mInterface->shouldStopSpinThread) {
            break;
        }
    }
}
void AbstractFileCaptureSpinThread::togglePause ()
Definition at line 58 of file abstractFileCaptureSpinThread.cpp.
References mPaused.
Referenced by AbstractFileCapture::pauseCapture().
{
    mPaused = !mPaused;
}
Member Data Documentation
int AbstractFileCaptureSpinThread::mDelay [private]
Definition at line 30 of file abstractFileCaptureSpinThread.h.
Referenced by run().
ImageCaptureInterface::FramePair& AbstractFileCaptureSpinThread::mFramePair [protected]
Definition at line 22 of file abstractFileCaptureSpinThread.h.
AbstractFileCapture* AbstractFileCaptureSpinThread::mInterface [protected]
Definition at line 23 of file abstractFileCaptureSpinThread.h.
Referenced by pause(), and run().
bool AbstractFileCaptureSpinThread::mNextFrameNeeded [private]
Definition at line 29 of file abstractFileCaptureSpinThread.h.
Referenced by nextFrame(), and run().
bool AbstractFileCaptureSpinThread::mPaused [private]
Definition at line 28 of file abstractFileCaptureSpinThread.h.
Referenced by pause(), run(), and togglePause().
The documentation for this class was generated from the following files:
utils/framesources/abstractFileCaptureSpinThread.h
utils/framesources/abstractFileCaptureSpinThread.cpp