DeepView: corecvs::Cholesky Class Reference
corecvs::Cholesky Class Reference
Class that implements Cholesky decomposition.
#include <cholesky.h>
Public Member Functions
Cholesky ()
virtual ~Cholesky ()
Static Public Member Functions
static void udutDecompose (Matrix *A, Matrix **Uresult, DiagonalMatrix **Dresult)
Cholesky UDUT decomposition.
static void udutDecompose (Matrix *A, UpperUnitaryMatrix **Uresult, DiagonalMatrix **Dresult)
Detailed Description
Class that implements Cholesky decomposition.
For details see Cholesky::udutDecompose()
Definition at line 22 of file cholesky.h.
Constructor & Destructor Documentation
corecvs::Cholesky::Cholesky ()
Definition at line 12 of file cholesky.cpp.
{
}
corecvs::Cholesky::~Cholesky () [virtual]
Definition at line 16 of file cholesky.cpp.
{
}
Member Function Documentation
void corecvs::Cholesky::udutDecompose (Matrix * A, Matrix ** Uresult, DiagonalMatrix ** Dresult) [static]
Cholesky UDUT decomposition.
This decomposition is based on the recurrent relations that become obvious from the example below
so the recurrent relations are:
Starting form the last column
And for other columns
Definition at line 71 of file cholesky.cpp.
References corecvs::DiagonalMatrix::a(), corecvs::Matrix::a(), and corecvs::AbstractBufferParams::h.
Referenced by corecvs::UDUTDecomposed::UDUTDecomposed().
{
    int n = A->h;
    Matrix *u         = new Matrix(n, n);
    DiagonalMatrix *d = new DiagonalMatrix(n);
    /* Starting with last row */
    int j = n - 1;
    d->a(j) = A->a(j,j);
    u->a(j,j) = 1.0;
    for (int i = 0; i < j; i ++)
    {
        u->a(i, j) = A->a(i, j) / d->a(j);
    }
    /* Recurrent continuation for columns */
    for (j = n - 2; j >= 0; j-- )
    {
        double sum = 0.0;
        for (int k = j + 1; k < n; k++)
        {
            double ujk = u->a(j,k);
            sum += d->a(k) * ujk * ujk;
        }
        d->a(j) = A->a(j,j) - sum;
        for (int i = 0; i < j; i++)
        {
            double sum = 0;
            for (int k = j + 1; k < n; k++)
            {
                double ujk = u->a(j,k);
                double uik = u->a(i,k);
                sum += d->a(k) * ujk * uik;
            }
            u->a(i,j) = (A->a(i,j) - sum ) / d->a(j);
        }
        u->a(j,j) = 1.0;
        for (int i = j + 1; i < n; i++ )
            u->a(i,j) = 0.0;
    }
    if (Uresult != NULL) {
        *Uresult = u;
    } else {
        delete u;
    }
    if (Dresult != NULL) {
        *Dresult = d;
    } else {
        delete d;
    }
}
void corecvs::Cholesky::udutDecompose (Matrix * A, UpperUnitaryMatrix ** Uresult, DiagonalMatrix ** Dresult) [static]
Definition at line 130 of file cholesky.cpp.
References corecvs::DiagonalMatrix::a(), corecvs::UpperUnitaryMatrix::a(), corecvs::Matrix::a(), corecvs::AbstractBufferParams::h, and corecvs::UpperUnitaryMatrix::u().
{
    int n = A->h;
    UpperUnitaryMatrix *u  = new UpperUnitaryMatrix(n, false);
    DiagonalMatrix *d = new DiagonalMatrix(n);
    /* Starting with last row */
    int j = n - 1;
    d->a(j) = A->a(j,j);
    for (int i = 0; i < j; i ++)
    {
        u->u(i, j) = A->a(i, j) / d->a(j);
    }
    /* Recurrent continuation for columns */
    for (j = n - 2; j >= 0; j-- )
    {
        double sum = 0.0;
        for (int k = j+1; k < n; k++)
        {
            double ujk = u->a(j,k);
            sum += d->a(k) * ujk * ujk;
        }
        d->a(j) = A->a(j,j) - sum;
        for (int i = 0; i < j; i++)
        {
            double sum = 0;
            for (int k = j + 1; k < n; k++)
            {
                double ujk = u->a(j,k);
                double uik = u->a(i,k);
                sum += d->a(k) * ujk * uik;
            }
            u->u(i,j) = (A->a(i,j) - sum ) / d->a(j);
        }
    }
    if (Uresult != NULL)
        *Uresult = u;
    if (Dresult != NULL)
        *Dresult = d;
}
The documentation for this class was generated from the following files:
core/kalman/cholesky.h
core/kalman/cholesky.cpp