DeepView: corecvs::FixedVectorBase< RealType, ElementType, length > Class Template Reference
corecvs::FixedVectorBase< RealType, ElementType, length > Class Template Reference
This class is a template for a vector of the fixed length.
#include <fixedVector.h>
Public Types
typedef VectorOperationsBase
< RealType, ElementType > BaseClass
typedef ElementType InnerElementType
typedef ReflectionHelper
< ElementType >::Type ReflectionType
Public Member Functions
template<typename OtherRealType >
FixedVectorBase (const FixedVectorBase< OtherRealType, typename OtherRealType::InnerElementType, length > &V)
This functions creates the object from the other fixed vector.
template<typename OtherRealType >
FixedVectorBase (const FixedVectorBase< OtherRealType, typename OtherRealType::InnerElementType, length-1 > &V, const typename OtherRealType::InnerElementType &lastElement)
This functions creates the fixed vector object from the other fixed vector of smaller size, adding an element at the end.
FixedVectorBase (const ElementType &x)
Copy constructor.
FixedVectorBase (const ElementType *x)
Constructor from raw data.
FixedVectorBase ()
int size () const
ElementType & operator[] (int n)
const ElementType & operator[] (int n) const
ElementType & at (int n)
const ElementType & at (int n) const
RealType createVector (int) const
RealType * realThis ()
Static cast functions.
const RealType * realThis () const
bool operator== (const RealType &that) const
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
bool operator!= (const RealType &that) const
Inequality operator.
bool notTooFar (const RealType &that, const ElementType &epsilon=ElementType(0)) const
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
VectorOperationsBase & operator+= (const RealType &V)
Add-to-this operator Performs addition on element by element basis.
VectorOperationsBase & operator-= (const RealType &V)
VectorOperationsBase & operator*= (const ElementType &c)
VectorOperationsBase & operator/= (const ElementType &c)
RealType operator- () const
Negative operator.
ElementType sumAllElements () const
Sum of the elements of the vector.
ElementType mulAllElements () const
Product of all elements of the vector.
ElementType sumAllElementsSq () const
Sum of the squares of element of the vector.
ElementType l2Metric () const
Euclidean distance.
ElementType operator! () const
Another alias for Euclidean distance.
void normalise ()
Normalize a vector length to 1 without changing the direction.
RealType normalised () const
Return a normalized copy of vector.
RealType cloneVector () const
Return copy of vector.
ElementType l1Metric () const
Sum of the absolute values of element of the vector.
ElementType lInfMetric () const
Value of the maximum absolute value.
bool isInHypercube (const VectorOperationsBase &low, const VectorOperationsBase &high) const
Check if current vector is inside the n dimensional cube
.
void print () const
void println () const
ElementType minimum () const
ElementType maximum () const
Please don't use this for double so far.
template<class VisitorType >
void accept1 (VisitorType &visitor)
template<class VisitorType >
void accept (VisitorType &visitor)
Public Attributes
ElementType element [length]
Static Public Attributes
static const int LENGTH = length
Friends
RealType operator+ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator + does the component-specific addition.
RealType operator- (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator - does the component-specific subtraction
.
RealType operator* (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator * does the component-specific multiplication
.
RealType operator* (const ElementType &c, const VectorOperationsBase &V)
Operator * does the component-specific multiplication by constant
.
RealType operator* (const VectorOperationsBase &V, const ElementType &c)
RealType operator/ (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
Operator / does the component-specific division
.
RealType operator/ (const VectorOperationsBase &V, const ElementType &c)
Operator * does the component-specific multiplication by constant
.
ElementType operator& (const VectorOperationsBase &V1, const VectorOperationsBase &V2)
The dot product of two vectors.
ostream & operator<< (ostream &out, const VectorOperationsBase &vector)
istream & operator>> (istream &in, VectorOperationsBase &vector)
Detailed Description
template<typename RealType, typename ElementType, int length>
class corecvs::FixedVectorBase< RealType, ElementType, length >
This class is a template for a vector of the fixed length.
This template could be parameterized by different types and vector lengths.
In the code below we pray for static loop unrolling and good optimization. Thus there will be no performance loss.
Definition at line 33 of file fixedVector.h.
Member Typedef Documentation
template<typename RealType, typename ElementType, int length> typedef VectorOperationsBase<RealType, ElementType> corecvs::FixedVectorBase< RealType, ElementType, length >::BaseClass
Reimplemented in corecvs::FixedVector< ElementType, length >, corecvs::FixedVector< double, 4 >, corecvs::FixedVector< uint64_t, MAX_ID >, corecvs::Matrix33, Triangulation::Point, corecvs::Matrix44, corecvs::Vector2d< ElementType >, corecvs::Vector2d< int16_t >, corecvs::Vector2d< double >, corecvs::Vector2d< int32_t >, corecvs::Vector2d< Int32x4 >, corecvs::Vector3d< ElementType >, corecvs::Vector3d< double >, and corecvs::GenericQuaternion< ElementType >.
Definition at line 38 of file fixedVector.h.
template<typename RealType, typename ElementType, int length> typedef ElementType corecvs::FixedVectorBase< RealType, ElementType, length >::InnerElementType
Definition at line 39 of file fixedVector.h.
template<typename RealType, typename ElementType> typedef ReflectionHelper<ElementType>::Type corecvs::VectorOperationsBase< RealType, ElementType >::ReflectionType [inherited]
Reimplemented in corecvs::Vector2d< ElementType >, corecvs::Vector2d< int16_t >, corecvs::Vector2d< double >, corecvs::Vector2d< int32_t >, and corecvs::Vector2d< Int32x4 >.
Definition at line 561 of file vectorOperations.h.
Constructor & Destructor Documentation
template<typename RealType, typename ElementType, int length> template<typename OtherRealType > corecvs::FixedVectorBase< RealType, ElementType, length >::FixedVectorBase (const FixedVectorBase< OtherRealType, typename OtherRealType::InnerElementType, length > & V) [inline]
This functions creates the object from the other fixed vector.
Definition at line 51 of file fixedVector.h.
    {
        for (int i = 0; i < length; i++)
            this->element[i] = (ElementType)V.element[i];
    }
template<typename RealType, typename ElementType, int length> template<typename OtherRealType > corecvs::FixedVectorBase< RealType, ElementType, length >::FixedVectorBase (const FixedVectorBase< OtherRealType, typename OtherRealType::InnerElementType, length-1 > & V, const typename OtherRealType::InnerElementType & lastElement) [inline]
This functions creates the fixed vector object from the other fixed vector of smaller size, adding an element at the end.
Definition at line 62 of file fixedVector.h.
    {
        for (int i = 0; i < length - 1; i++)
            this->element[i] = (ElementType)V.element[i];
        this->element[length - 1] = lastElement;
    }
template<typename RealType, typename ElementType, int length> corecvs::FixedVectorBase< RealType, ElementType, length >::FixedVectorBase (const ElementType & x) [inline, explicit]
Copy constructor.
Acts the same way as assignment constructor
Definition at line 76 of file fixedVector.h.
    {
        BaseClass::operator =(x);
    }
template<typename RealType, typename ElementType, int length> corecvs::FixedVectorBase< RealType, ElementType, length >::FixedVectorBase (const ElementType * x) [inline, explicit]
Constructor from raw data.
Definition at line 84 of file fixedVector.h.
    {
        for (int i = 0; i < length; i++)
            this->element[i] = x[i];
    }
template<typename RealType, typename ElementType, int length> corecvs::FixedVectorBase< RealType, ElementType, length >::FixedVectorBase () [inline]
Definition at line 91 of file fixedVector.h.
{}
Member Function Documentation
template<typename RealType, typename ElementType> template<class VisitorType > void corecvs::VectorOperationsBase< RealType, ElementType >::accept (VisitorType & visitor) [inline, inherited]
Reimplemented in corecvs::RGBColor, corecvs::Vector2d< ElementType >, corecvs::Vector2d< int16_t >, corecvs::Vector2d< double >, corecvs::Vector2d< int32_t >, corecvs::Vector2d< Int32x4 >, corecvs::Vector3d< ElementType >, and corecvs::Vector3d< double >.
Definition at line 578 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            const ReflectionType fieldDescriptor(i, defaultValue, name);
            visitor.visit(_at(i), &fieldDescriptor);
        }
    }
template<typename RealType, typename ElementType> template<class VisitorType > void corecvs::VectorOperationsBase< RealType, ElementType >::accept1 (VisitorType & visitor) [inline, inherited]
Definition at line 565 of file vectorOperations.h.
    {
        ElementType defaultValue(0);
        char name[50];
        for (int i = 0; i < _size() ; i++)
        {
            snprintf2buf(name, "a[%d]", i);
            visitor.visit(_at(i), defaultValue, name);
        }
    }
template<typename RealType, typename ElementType, int length> ElementType& corecvs::FixedVectorBase< RealType, ElementType, length >::at (int n) [inline]
Definition at line 108 of file fixedVector.h.
Referenced by corecvs::Matrix::svdDesc().
    {
        return element[n];
    }
template<typename RealType, typename ElementType, int length> const ElementType& corecvs::FixedVectorBase< RealType, ElementType, length >::at (int n) const [inline]
Definition at line 113 of file fixedVector.h.
    {
        return element[n];
    }
template<typename RealType, typename ElementType> RealType corecvs::VectorOperationsBase< RealType, ElementType >::cloneVector () const [inline, inherited]
Return copy of vector.
Definition at line 433 of file vectorOperations.h.
Referenced by corecvs::VectorOperationsBase< RGBColor, uint8_t >::normalised().
    {
        RealType result = this->_createVector(this->_size());
        for (int i = 0; i < this->_size(); i++)
            result.at(i) = this->_at(i);
        return result;
    }
template<typename RealType, typename ElementType, int length> RealType corecvs::FixedVectorBase< RealType, ElementType, length >::createVector (int) const [inline]
Definition at line 118 of file fixedVector.h.
{
        return RealType();
    }
template<typename RealType, typename ElementType> bool corecvs::VectorOperationsBase< RealType, ElementType >::isInHypercube (const VectorOperationsBase< RealType, ElementType > & low, const VectorOperationsBase< RealType, ElementType > & high) const [inline, inherited]
Check if current vector is inside the n dimensional cube
.
NB - both low and high limits are included.
Definition at line 498 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) <  low._at(i)) return false;
            if (_at(i) > high._at(i)) return false;
        }
        return true;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::l1Metric () const [inline, inherited]
Sum of the absolute values of element of the vector.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 448 of file vectorOperations.h.
Referenced by FlowDrawer::draw(), and Scene3DMouse::drawMyself().
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
            result += (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
        return result;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric () const [inline, inherited]
Euclidean distance.
Definition at line 383 of file vectorOperations.h.
Referenced by corecvs::Plane3d::deviationTo(), corecvs::Ray3d::distanceTo(), corecvs::Line2d::distanceTo(), corecvs::Plane3d::distanceTo(), DistortionWidget::doLinesTransform(), corecvs::LevenbergMarquardt::fit(), corecvs::AngleFunction::getJacobian(), corecvs::AnglePointsFunction::getJacobian(), corecvs::DistPointsFunction::getJacobian(), corecvs::LensCorrectionParametres::LensCorrectionParametres(), corecvs::Line2d::normalise(), corecvs::VectorOperationsBase< RGBColor, uint8_t >::normalise(), corecvs::VectorOperationsBase< RGBColor, uint8_t >::normalised(), corecvs::VectorOperationsBase< RGBColor, uint8_t >::operator!(), corecvs::AngleFunction::operator()(), corecvs::DistortionCorrectTransform::setZ(), and DistortionWidget::updateAdditionalData().
    {
        /* TODO ASAP: Correct this to select appropriate sqrt */
        return (ElementType)sqrt((double)this->sumAllElementsSq());
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::lInfMetric () const [inline, inherited]
Value of the maximum absolute value.
More info: http://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions
Definition at line 463 of file vectorOperations.h.
    {
        ElementType result = 0;
        for (int i = 0; i < _size(); i++)
        {
            ElementType abs = (_at(i) > ElementType(0)) ? _at(i) : -_at(i);
            if (abs > result)
                result = abs;
        }
        return result;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::maximum () const [inline, inherited]
Please don't use this for double so far.
Definition at line 549 of file vectorOperations.h.
Referenced by corecvs::VectorOperationsBase< RGBColor, uint8_t >::maximum().
    {
        ElementType maximum = numeric_limits<ElementType>::min();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) > maximum)
                maximum = _at(i);
        }
        return maximum;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::minimum () const [inline, inherited]
Definition at line 537 of file vectorOperations.h.
Referenced by corecvs::VectorOperationsBase< RGBColor, uint8_t >::minimum().
    {
        ElementType minimum = numeric_limits<ElementType>::max();
        for (int i = 0; i < _size(); i++)
        {
            if (_at(i) < minimum)
                minimum = _at(i);
        }
        return minimum;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::mulAllElements () const [inline, inherited]
Product of all elements of the vector.
Definition at line 355 of file vectorOperations.h.
    {
        ElementType result(1.0);
        for (int i = 0; i < _size(); i++)
            result *= _at(i);
        return result;
    }
template<typename RealType, typename ElementType> void corecvs::VectorOperationsBase< RealType, ElementType >::normalise (void) [inline, inherited]
Normalize a vector length to 1 without changing the direction.
Reimplemented in corecvs::Plane3d, and corecvs::Line2d.
Definition at line 407 of file vectorOperations.h.
Referenced by UniversalRectifier::manualMethod(), and corecvs::EssentialEstimator::NormalizeFunction::operator()().
    {
        ElementType length = this->l2Metric();
        if (length != 0)
            this->operator /=(length);
    }
template<typename RealType, typename ElementType> RealType corecvs::VectorOperationsBase< RealType, ElementType >::normalised (void) const [inline, inherited]
Return a normalized copy of vector.
Reimplemented in corecvs::Plane3d, and corecvs::Line2d.
Definition at line 420 of file vectorOperations.h.
Referenced by corecvs::GenericQuaternion< ElementType >::GenericQuaternion(), corecvs::EssentialDecomposition::getDistance(), corecvs::EssentialEstimator::CostFunctionBase::getTranslation(), and corecvs::Triangulator::triangulate().
    {
        ElementType length = this->l2Metric();
        if (length != ElementType(0))
            return (*this / length);
        else {
            return this->cloneVector();
        }
    }
template<typename RealType, typename ElementType> bool corecvs::VectorOperationsBase< RealType, ElementType >::notTooFar (const RealType & that, const ElementType & epsilon = ElementType(0)) const [inline, inherited]
Equal with epsilon Doesn't have much sense in case of integers but with doubles - quite useful.
Definition at line 149 of file vectorOperations.h.
Referenced by corecvs::StereoAligner::getAlignmentTransformation().
    {
        if (_size() != that.size())
           return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) > that.at(i) + epsilon ||
                _at(i) < that.at(i) - epsilon )
                return false;
        return true;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::operator! () const [inline, inherited]
Another alias for Euclidean distance.
Definition at line 395 of file vectorOperations.h.
    {
        return l2Metric();
    };
template<typename RealType, typename ElementType> bool corecvs::VectorOperationsBase< RealType, ElementType >::operator!= (const RealType & that) const [inline, inherited]
Inequality operator.
Doesn't have much sense in case of doubles but with integers - quite useful
Definition at line 140 of file vectorOperations.h.
    {
        return !(operator ==(that));
    }
template<typename RealType, typename ElementType> VectorOperationsBase& corecvs::VectorOperationsBase< RealType, ElementType >::operator*= (const ElementType & c) [inline, inherited]
Definition at line 189 of file vectorOperations.h.
    {
        for (int i = 0; i < _size(); i++)
            _at(i) *= c;
        return *this;
    }
template<typename RealType, typename ElementType> VectorOperationsBase& corecvs::VectorOperationsBase< RealType, ElementType >::operator+= (const RealType & V) [inline, inherited]
Add-to-this operator Performs addition on element by element basis.
Parameters:
V Reference to the vector to add
Returns:
Reference to current vector
Definition at line 171 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) += V.at(i);
        return *this;
    }
template<typename RealType, typename ElementType> RealType corecvs::VectorOperationsBase< RealType, ElementType >::operator- () const [inline, inherited]
Negative operator.
Definition at line 481 of file vectorOperations.h.
    {
        RealType result = _createVector(_size());
        for (int i = 0; i < _size(); i++)
            result.at(i) = -_at(i);
        return result;
    }
template<typename RealType, typename ElementType> VectorOperationsBase& corecvs::VectorOperationsBase< RealType, ElementType >::operator-= (const RealType & V) [inline, inherited]
Definition at line 180 of file vectorOperations.h.
    {
        int length = _size() < V.size() ? _size() : V.size();
        for (int i = 0; i < length; i++)
            _at(i) -= V.at(i);
        return *this;
    }
template<typename RealType, typename ElementType> VectorOperationsBase& corecvs::VectorOperationsBase< RealType, ElementType >::operator/= (const ElementType & c) [inline, inherited]
Definition at line 196 of file vectorOperations.h.
Referenced by corecvs::VectorOperationsBase< RGBColor, uint8_t >::normalise().
    {
        for (int i = 0; i < _size(); i++)
            _at(i) /= c;
        return *this;
    }
template<typename RealType, typename ElementType> bool corecvs::VectorOperationsBase< RealType, ElementType >::operator== (const RealType & that) const [inline, inherited]
Equality operator Doesn't have much sense in case of doubles but with integers - quite useful.
Definition at line 123 of file vectorOperations.h.
Referenced by corecvs::VectorOperationsBase< RGBColor, uint8_t >::operator!=().
    {
        if (_size() != that.size())
            return false;
        for (int i = 0; i < _size(); i++)
            if (_at(i) != that.at(i))
                return false;
        return true;
    }
template<typename RealType, typename ElementType, int length> ElementType& corecvs::FixedVectorBase< RealType, ElementType, length >::operator[] (int n) [inline]
Definition at line 98 of file fixedVector.h.
    {
        return element[n];
    }
template<typename RealType, typename ElementType, int length> const ElementType& corecvs::FixedVectorBase< RealType, ElementType, length >::operator[] (int n) const [inline]
Definition at line 103 of file fixedVector.h.
    {
        return element[n];
    }
template<typename RealType, typename ElementType> void corecvs::VectorOperationsBase< RealType, ElementType >::print () const [inline, inherited]
Reimplemented in corecvs::Matrix33.
Definition at line 525 of file vectorOperations.h.
Referenced by corecvs::EssentialMatrix::assertRank2(), corecvs::StereoAligner::getAlignmentTransformation(), corecvs::VectorOperationsBase< RGBColor, uint8_t >::println(), and corecvs::EssentialMatrix::projectToEssential().
    {
        cout << *this;
    }
template<typename RealType, typename ElementType> void corecvs::VectorOperationsBase< RealType, ElementType >::println () const [inline, inherited]
Definition at line 531 of file vectorOperations.h.
Referenced by corecvs::StereoAligner::getAlignmentTransformation(), and UniversalRectifier::getZ().
    {
        print();
        cout << "\n";
    }
template<typename RealType, typename ElementType> RealType* corecvs::VectorOperationsBase< RealType, ElementType >::realThis () [inline, inherited]
Static cast functions.
Definition at line 56 of file vectorOperations.h.
Referenced by corecvs::VectorOperationsBase< RGBColor, uint8_t >::_at(), corecvs::VectorOperationsBase< RGBColor, uint8_t >::_createVector(), corecvs::VectorOperationsBase< RGBColor, uint8_t >::_size(), and corecvs::VectorOperationsBase< RGBColor, uint8_t >::operator=().
{
        return static_cast<RealType *>(this);
    }
template<typename RealType, typename ElementType> const RealType* corecvs::VectorOperationsBase< RealType, ElementType >::realThis () const [inline, inherited]
Definition at line 60 of file vectorOperations.h.
{
        return static_cast<const RealType *>(this);
    }
template<typename RealType, typename ElementType, int length> int corecvs::FixedVectorBase< RealType, ElementType, length >::size () const [inline]
Definition at line 93 of file fixedVector.h.
    {
        return length;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElements () const [inline, inherited]
Sum of the elements of the vector.
Definition at line 341 of file vectorOperations.h.
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i);
        return result;
    }
template<typename RealType, typename ElementType> ElementType corecvs::VectorOperationsBase< RealType, ElementType >::sumAllElementsSq () const [inline, inherited]
Sum of the squares of element of the vector.
Definition at line 369 of file vectorOperations.h.
Referenced by corecvs::LevenbergMarquardt::fit(), corecvs::Plane3d::intersectWith(), corecvs::VectorOperationsBase< RGBColor, uint8_t >::l2Metric(), corecvs::SphericalCorrection< RadiusCorrectionLUT >::map(), corecvs::Plane3d::projectPointTo(), corecvs::Line2d::sqDistanceTo(), and corecvs::Plane3d::sqDistanceTo().
    {
        ElementType result(0);
        for (int i = 0; i < _size(); i++)
            result += _at(i) * _at(i);
        return result;
    }
Friends And Related Function Documentation
template<typename RealType, typename ElementType> ElementType operator& (const VectorOperationsBase< RealType, ElementType > & V1, const VectorOperationsBase< RealType, ElementType > & V2) [friend, inherited]
The dot product of two vectors.
Parameters:
V1
V2
Definition at line 325 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        ElementType result(0);
        for (int i = 0; i < length; i++)
            result += V1._at(i) * V2._at(i);
        return result;
    }
template<typename RealType, typename ElementType> RealType operator* (const VectorOperationsBase< RealType, ElementType > & V1, const VectorOperationsBase< RealType, ElementType > & V2) [friend, inherited]
Operator * does the component-specific multiplication
.
Parameters:
V1
V2
Definition at line 246 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) * V2._at(i);
        return result;
    }
template<typename RealType, typename ElementType> RealType operator* (const ElementType & c, const VectorOperationsBase< RealType, ElementType > & V) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
TODO: Could be nice to have operator *non-commutative
Parameters:
c
V
Definition at line 282 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) * c;
        return result;
    }
template<typename RealType, typename ElementType> RealType operator* (const VectorOperationsBase< RealType, ElementType > & V, const ElementType & c) [friend, inherited]
Definition at line 291 of file vectorOperations.h.
    {
        return operator *(c, V);
    }
template<typename RealType, typename ElementType> RealType operator+ (const VectorOperationsBase< RealType, ElementType > & V1, const VectorOperationsBase< RealType, ElementType > & V2) [friend, inherited]
Operator + does the component-specific addition.
Parameters:
V1
V2
Definition at line 212 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) + V2._at(i);
        return result;
    }
template<typename RealType, typename ElementType> RealType operator- (const VectorOperationsBase< RealType, ElementType > & V1, const VectorOperationsBase< RealType, ElementType > & V2) [friend, inherited]
Operator - does the component-specific subtraction
.
Parameters:
V1
V2
Definition at line 229 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) - V2._at(i);
        return result;
    }
template<typename RealType, typename ElementType> RealType operator/ (const VectorOperationsBase< RealType, ElementType > & V1, const VectorOperationsBase< RealType, ElementType > & V2) [friend, inherited]
Operator / does the component-specific division
.
Parameters:
V1
V2
Definition at line 263 of file vectorOperations.h.
    {
        int length = V1._size() < V2._size() ? V1._size() : V2._size();
        RealType result = V1._createVector(length);
        for (int i = 0; i < length; i++)
            result.at(i) = V1._at(i) / V2._at(i);
        return result;
    }
template<typename RealType, typename ElementType> RealType operator/ (const VectorOperationsBase< RealType, ElementType > & V, const ElementType & c) [friend, inherited]
Operator * does the component-specific multiplication by constant
.
Parameters:
c
V
Definition at line 304 of file vectorOperations.h.
    {
        RealType result = V._createVector(V._size());
        for (int i = 0; i < V._size(); i++)
            result.at(i) = V._at(i) / c;
        return result;
    }
template<typename RealType, typename ElementType> ostream& operator<< (ostream & out, const VectorOperationsBase< RealType, ElementType > & vector) [friend, inherited]
Definition at line 509 of file vectorOperations.h.
    {
        out << "[";
        for (int i = 0; i < vector._size(); i++)
           out << (i == 0 ? "" : ", ") << vector._at(i);
        out << "]";
        return out;
    }
template<typename RealType, typename ElementType> istream& operator>> (istream & in, VectorOperationsBase< RealType, ElementType > & vector) [friend, inherited]
Definition at line 518 of file vectorOperations.h.
    {
        for (int i = 0; i < vector._size(); i++)
            in >> vector._at(i);
        return in;
    }
Member Data Documentation
template<typename RealType, typename ElementType, int length> ElementType corecvs::FixedVectorBase< RealType, ElementType, length >::element[length]
Definition at line 42 of file fixedVector.h.
Referenced by corecvs::FixedVectorBase< Vector3d< ElementType >, ElementType, 3 >::at(), corecvs::FixedVectorBase< Vector3d< ElementType >, ElementType, 3 >::FixedVectorBase(), corecvs::HomographyReconstructor::getBestHomographyClassicKalman(), corecvs::getInputDisparity(), corecvs::getInputDisparity< DisparityBuffer >(), corecvs::getInputDisparity< FloatFlowBuffer >(), OpenGLTools::glMultMatrixMatrix44(), corecvs::Int16x8::Int16x8(), corecvs::Int8x16::Int8x16(), corecvs::IntBase8x16< Int8x16 >::IntBase8x16(), corecvs::FixedVectorBase< Vector3d< ElementType >, ElementType, 3 >::operator[](), corecvs::Matrix44::ProjectParallelToZ(), MatrixWidget::setProjectiveTransform(), corecvs::Matrix44::Shift(), and corecvs::UInt8x16::UInt8x16().
template<typename RealType, typename ElementType, int length> const int corecvs::FixedVectorBase< RealType, ElementType, length >::LENGTH = length [static]
Definition at line 37 of file fixedVector.h.
The documentation for this class was generated from the following file:
core/math/vector/fixedVector.h