DeepView: corecvs::Morphological Class Reference
corecvs::Morphological Class Reference
This class holds morpological transformations
.
#include <morphological.h>
Static Public Member Functions
static G12Buffer * erode (G12Buffer *input, G12Buffer *element, int centerX, int centerY)
static G12Buffer * dilate (G12Buffer *input, G12Buffer *element, int centerX, int centerY)
static G8Buffer * erode (G8Buffer *input, G12Buffer *element, int centerX, int centerY)
static G8Buffer * dilate (G8Buffer *input, G12Buffer *element, int centerX, int centerY)
Detailed Description
This class holds morpological transformations
.
Erosion
Dilation
Opening
Closing
Definition at line 55 of file morphological.h.
Member Function Documentation
G12Buffer * corecvs::Morphological::dilate (G12Buffer * input, G12Buffer * element, int centerX, int centerY) [static]
Definition at line 59 of file morphological.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::getSize().
{
    G12Buffer *result = new G12Buffer(input->getSize());
    DilateKernel<DummyAlgebra> dilater(element, centerY, centerX);
    process<DilateKernel>(&input, &result, dilater);
    return result;
}
G8Buffer * corecvs::Morphological::dilate (G8Buffer * input, G12Buffer * element, int centerX, int centerY) [static]
Definition at line 76 of file morphological.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::getSize().
{
    G8Buffer *result = new G8Buffer(input->getSize());
    DilateKernel<DummyAlgebra> dilater(element, centerY, centerX);
    process8<DilateKernel>(&input, &result, dilater);
    return result;
}
G12Buffer * corecvs::Morphological::erode (G12Buffer * input, G12Buffer * element, int centerX, int centerY) [static]
Definition at line 50 of file morphological.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::getSize().
{
    G12Buffer *result = new G12Buffer(input->getSize());
    ErodeKernel<DummyAlgebra> erroder(element, centerY, centerX);
    process<ErodeKernel>(&input, &result, erroder);
    return result;
}
G8Buffer * corecvs::Morphological::erode (G8Buffer * input, G12Buffer * element, int centerX, int centerY) [static]
Definition at line 67 of file morphological.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::getSize().
{
    G8Buffer *result = new G8Buffer(input->getSize());
    ErodeKernel<DummyAlgebra> erroder(element, centerY, centerX);
    process8<ErodeKernel>(&input, &result, erroder);
    return result;
}
The documentation for this class was generated from the following files:
core/buffers/morphological/morphological.h
core/buffers/morphological/morphological.cpp