DeepView: corecvs::CorrespondanceList Class Reference
corecvs::CorrespondanceList Class Reference
#include <correspondanceList.h>
Public Member Functions
CorrespondanceList ()
CorrespondanceList (const CorrespondanceList &list)
CorrespondanceList (FlowBuffer *input, bool swap=false)
CorrespondanceList (FloatFlowBuffer *input)
virtual ~CorrespondanceList ()
void getNormalizingTransform (Matrix33 &transformRight, Matrix33 &transformLeft, double *scale)
void transform (const ProjectiveTransform &transformRight, const ProjectiveTransform &transformLeft)
CorrespondanceList * makePreciseCopy (G12Buffer *first, G12Buffer *second)
void makePrecise (G12Buffer *first, G12Buffer *second)
void resetFlags (void)
Vector2dd getSize () const
Vector2dd getMeanDifference ()
Public Attributes
int h
int w
T elements
STL member.
Detailed Description
Definition at line 69 of file correspondanceList.h.
Constructor & Destructor Documentation
corecvs::CorrespondanceList::CorrespondanceList ()
Definition at line 15 of file correspondanceList.cpp.
Referenced by makePreciseCopy().
{
}
corecvs::CorrespondanceList::CorrespondanceList (const CorrespondanceList & list)
Definition at line 19 of file correspondanceList.cpp.
                                                                     : vector<Correspondance>(list), h(list.h), w(list.w)
{
}
corecvs::CorrespondanceList::CorrespondanceList (FlowBuffer * input, bool swap = false)
Definition at line 111 of file correspondanceList.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::touchOperationElementwize().
                                                                   :
            h(input->h),
            w(input->w)
{
    if (swap)
    {
        CFlowBufferToucherOperator<true> toucher(this);
        input->touchOperationElementwize(toucher);
    } else {
        CFlowBufferToucherOperator<false> toucher(this);
        input->touchOperationElementwize(toucher);
    }
}
corecvs::CorrespondanceList::CorrespondanceList (FloatFlowBuffer * input)
Definition at line 125 of file correspondanceList.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::touchOperationElementwize().
                                                             :
            h(input->h),
            w(input->w)
{
    CFlowBufferToucherOperator<> toucher(this);
    input->touchOperationElementwize(toucher);
}
corecvs::CorrespondanceList::~CorrespondanceList () [virtual]
Definition at line 23 of file correspondanceList.cpp.
{
}
Member Function Documentation
Vector2dd corecvs::CorrespondanceList::getMeanDifference () [inline]
Definition at line 104 of file correspondanceList.h.
References corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start.
Referenced by UniversalRectifier::recalculate().
    {
      Vector2dd mean (0.0);
      for (unsigned i = 0; i < size(); i++)
      {
        Correspondance *corr = &(at(i));
        mean += (corr->end - corr->start);
      }
      return (size() != 0) ? mean / size() : Vector2dd(0.0);
    }
void corecvs::CorrespondanceList::getNormalizingTransform (Matrix33 & transformRight, Matrix33 & transformLeft, double * scale)
Definition at line 60 of file correspondanceList.cpp.
References corecvs::Matrix33::ScaleProj(), corecvs::Matrix33::ShiftProj(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by UniversalRectifier::recalculate().
{
    Vector2dd rightMean(0.0);
    Vector2dd rightMeanSq(0.0);
    Vector2dd leftMean(0.0);
    Vector2dd leftMeanSq(0.0);
    for (unsigned  i = 0; i < this->size(); i++)
    {
        rightMean   += (*this)[i].start;
        rightMeanSq += ((*this)[i].start) * ((*this)[i].start);
        leftMean   += (*this)[i].end;
        leftMeanSq += ((*this)[i].end) * ((*this)[i].end);
    }
    int count = (this->size() == 0) ? 1 : (int)this->size();
    rightMean   /= count;
    rightMeanSq /= count;
    leftMean    /= count;
    leftMeanSq  /= count;
    Vector2dd rightSqMean = rightMean * rightMean;
    Vector2dd leftSqMean  = leftMean * leftMean;
    double rightScaler = sqrt (rightMeanSq.x() - rightSqMean.x()  + rightMeanSq.y() - rightSqMean.y());
    double leftScaler  = sqrt (leftMeanSq.x()  - leftSqMean.x()   + leftMeanSq.y()  - leftSqMean.y());
    if (rightScaler < 1e-15) rightScaler = 1.0;
    if (leftScaler < 1e-15) leftScaler = 1.0;
    transformRight = Matrix33::ScaleProj(sqrt(2.0) / rightScaler) * Matrix33::ShiftProj(-rightMean);
    transformLeft  = Matrix33::ScaleProj(sqrt(2.0) / leftScaler ) * Matrix33::ShiftProj(-leftMean);
    if (scale != NULL )
        *scale = sqrt(2.0f) / ((rightScaler + leftScaler) * 2.0) ;
}
Vector2dd corecvs::CorrespondanceList::getSize () const [inline]
Definition at line 99 of file correspondanceList.h.
References h, and w.
Referenced by UniversalRectifier::getZ(), and UniversalRectifier::recalculate().
    {
        return Vector2dd(w, h);
    }
void corecvs::CorrespondanceList::makePrecise (G12Buffer * first, G12Buffer * second)
Definition at line 173 of file correspondanceList.cpp.
References corecvs::KLTCalculationContext::first, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::FLAG_FILTERED_KLT, corecvs::PrimitiveCorrespondance< FirstType, SecondType >::flags, corecvs::KLTCalculationContext::gradient, corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::KLTCalculationContext::second, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by UniversalRectifier::recalculate().
{
    SpatialGradient *sg = new SpatialGradient(first);
    SpatialGradientIntegralBuffer *gradient = new SpatialGradientIntegralBuffer(sg);
    delete sg;
    KLTCalculationContext context;
    context.first = first;
    context.second = second;
    context.gradient = gradient;
    KLTGenerator<BilinearInterpolator> kltGenerator;
    for (unsigned i = 0; i < this->size(); i++)
    {
        // TODO: Be careful with this.
        Vector2dd start = Vector2dd(at(i).start.x(),at(i).start.y());
        Vector2dd guess = at(i).end - at(i).start;
        bool status = kltGenerator.kltIterationSubpixel(context, start, &guess, 2);
        if (status)
        {
            Correspondance corr(
                    Vector2dd(start.x(),start.y()),
                    Vector2dd(start.x() + guess.x(),start.y() + guess.y())
                    );
            int oldFlags = at(i).flags;
            at(i) = corr;
            at(i).flags = oldFlags;
        } else {
            at(i).flags |= Correspondance::FLAG_FILTERED_KLT;
        }
    }
    delete gradient;
}
CorrespondanceList * corecvs::CorrespondanceList::makePreciseCopy (G12Buffer * first, G12Buffer * second)
Definition at line 133 of file correspondanceList.cpp.
References CorrespondanceList(), corecvs::KLTCalculationContext::first, corecvs::fround(), corecvs::KLTCalculationContext::gradient, h, corecvs::KLTGenerator< InterpolationType >::kltIterationSubpixel(), corecvs::KLTCalculationContext::second, w, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    SpatialGradient *sg = new SpatialGradient(first);
    SpatialGradientIntegralBuffer *gradient = new SpatialGradientIntegralBuffer(sg);
    delete sg;
    KLTCalculationContext context;
    context.first = first;
    context.second = second;
    context.gradient = gradient;
    KLTGenerator<BilinearInterpolator> kltGenerator;
    CorrespondanceList *toReturn = new CorrespondanceList();
    toReturn->h = this->h;
    toReturn->w = this->w;
    for (unsigned i = 0; i < this->size(); i++)
    {
        // TODO: Be careful with this.
        Vector2dd start = Vector2dd(
                    fround(at(i).start.x()),
                    fround(at(i).start.y())
                  );
        Vector2dd guess = at(i).end - at(i).start;
        bool status = kltGenerator.kltIterationSubpixel(context, start, &guess, 2);
        if (status)
        {
            Correspondance corr(
                    Vector2dd(start.x(),start.y()),
                    Vector2dd(start.x() + guess.x(),start.y() + guess.y())
                    );
            toReturn->push_back(corr);
        }
    }
    delete gradient;
    return toReturn;
}
void corecvs::CorrespondanceList::resetFlags (void) [inline]
Definition at line 90 of file correspondanceList.h.
Referenced by UniversalRectifier::recalculate().
    {
        iterator it;
        for (it = begin(); it != end(); ++it)
        {
            (*it).clearFlags();
        }
    }
void corecvs::CorrespondanceList::transform (const ProjectiveTransform & transformRight, const ProjectiveTransform & transformLeft)
Definition at line 100 of file correspondanceList.cpp.
References corecvs::PrimitiveCorrespondance< FirstType, SecondType >::end, and corecvs::PrimitiveCorrespondance< FirstType, SecondType >::start.
Referenced by UniversalRectifier::recalculate().
{
    for (unsigned i = 0; i < this->size(); i++)
    {
        Correspondance *corr = &((*this)[i]);
        corr->start = transformRight (corr->start);
        corr->end   = transformLeft  (corr->end);
    }
}
Member Data Documentation
template<typename T> T std::vector< T >::elements [inherited]
STL member.
int corecvs::CorrespondanceList::h
Definition at line 72 of file correspondanceList.h.
Referenced by getSize(), PointsRectificationWidget::initCorrespondancePoints(), makePreciseCopy(), and UniversalRectifier::recalculate().
int corecvs::CorrespondanceList::w
Definition at line 73 of file correspondanceList.h.
Referenced by getSize(), PointsRectificationWidget::initCorrespondancePoints(), makePreciseCopy(), and UniversalRectifier::recalculate().
The documentation for this class was generated from the following files:
core/rectification/correspondanceList.h
core/rectification/correspondanceList.cpp