DeepView: Triangulation::Edge Class Reference
Triangulation::Edge Class Reference
#include <triangulation.h>
Public Member Functions
Edge (const Point &_org, const Point &_dest)
Edge (void)
Edge & rot (void)
Having the edge rotated 90deg around the center.
Edge & flip (void)
Point point (const double) const
int intersect (const Edge &, double &) const
double cosAngle (const Edge &e2)
int classify (const Point &p2) const
bool operator== (const Edge &e1) const
Public Attributes
Point org
Point dest
Friends
ostream & operator<< (ostream &out, const Edge &edge)
Detailed Description
Definition at line 174 of file triangulation.h.
Constructor & Destructor Documentation
Triangulation::Edge::Edge (const Point & _org, const Point & _dest) [inline]
Definition at line 180 of file triangulation.h.
                                                :
            org(_org), dest(_dest)
    {
    }
Triangulation::Edge::Edge (void) [inline]
Definition at line 184 of file triangulation.h.
               :
            org(Point(0, 0)), dest(Point(0, 0))
    {
    }
Member Function Documentation
int Triangulation::Edge::classify (const Point & p2) const [inline]
Definition at line 194 of file triangulation.h.
References Triangulation::classify().
Referenced by intersect(), Triangulation::isInsideTriangle(), and Triangulation::mate().
    {
        return Triangulation::classify(dest, org, p2);
    }
double Triangulation::Edge::cosAngle (const Edge & e2) [inline]
Definition at line 94 of file triangulation.cpp.
References corecvs::Vector2d< ElementType >::cosineTo(), dest, and org.
Referenced by Triangulation::vertexHullFromTriangulation().
{
    Point p0 = dest - org;
    Point p1 = e2.dest - e2.org;
    return p0.cosineTo(p1);
}
Edge & Triangulation::Edge::flip (void) [inline]
Definition at line 33 of file triangulation.cpp.
References dest, and org.
Referenced by Triangulation::updateFrontier().
{
  Point tmp = org;
    org = dest;
    dest = tmp;
    return *this;
}
int Triangulation::Edge::intersect (const Edge & e, double & t) const
Definition at line 70 of file triangulation.cpp.
References classify(), Triangulation::COLLINEAR, dest, Triangulation::doubleEqual(), Triangulation::LEFT, org, Triangulation::PARALLEL, Triangulation::RIGHT, and Triangulation::SKEW.
Referenced by Triangulation::mate().
{
    Point c = e.org;
    Point d = e.dest;
    Vector2dd n = ((Vector2dd)(d - c)).rightNormal();
    double denom = n & (dest - org);
    if (/*denom == 0*/ doubleEqual(denom, 0.0))
    {
        int aclass = e.classify(org);
        if ((aclass == LEFT) || (aclass == RIGHT))
            return PARALLEL;
        else
            return COLLINEAR;
    }
    double num = n & (org - c);
    t = -num / denom;
    return SKEW;
}
bool Triangulation::Edge::operator== (const Edge & e1) const [inline]
Definition at line 205 of file triangulation.h.
References dest, and org.
    {
        if (org == e1.org && dest == e1.dest)
            return true;
        return false;
    }
Point Triangulation::Edge::point (const double t) const [inline]
Definition at line 41 of file triangulation.cpp.
References dest, and org.
{
    return Point(org + t * (dest - org));
}
Edge & Triangulation::Edge::rot (void)
Having the edge rotated 90deg around the center.
Definition at line 50 of file triangulation.cpp.
References dest, org, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Triangulation::mate().
{
    Point m = 0.5 * (org + dest);
    Point v = dest - org;
    Point n(v.y(), -v.x());
    dest = m - 0.5 * n;
    org = m + 0.5 * n;
    return *this;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & out, const Edge & edge) [friend]
Definition at line 199 of file triangulation.h.
    {
        out << "{" << edge.org << "=>" << edge.dest << "}";
        return out;
    }
Member Data Documentation
Point Triangulation::Edge::dest
Definition at line 178 of file triangulation.h.
Referenced by cosAngle(), flip(), intersect(), Triangulation::mate(), Triangulation::EdgeCmp::operator()(), operator==(), point(), rot(), Triangulation::triangulate(), and Triangulation::vertexHullFromTriangulation().
Point Triangulation::Edge::org
Definition at line 177 of file triangulation.h.
Referenced by cosAngle(), flip(), intersect(), Triangulation::EdgeCmp::operator()(), operator==(), point(), rot(), Triangulation::triangulate(), and Triangulation::vertexHullFromTriangulation().
The documentation for this class was generated from the following files:
core/geometry/triangulation.h
core/geometry/triangulation.cpp