DeepView: HistogramWidget Class Reference
HistogramWidget Class Reference
#include <histogramwidget.h>
Public Types
enum ZoneSettingState {
none, preZone, zoneStart, zoneEnd,
clickEnd
}
Public Slots
void notifyHistogramChange (Histogram *histogram, bool useMargin)
void zoomIn ()
void zoomOut ()
Signals
void histogramBarClicked (int bar)
void preZoneChanged (int zone)
void zoneStartChanged (int zone)
void zoneEndChanged (int zone)
void clickZoneEndChanged (int zone)
Public Member Functions
HistogramWidget (QWidget *parent=0)
~HistogramWidget ()
void setZoneSettingState (ZoneSettingState state)
void setZones (int zoneStart, int zoneEnd, int preZoneStart, int clickZoneEnd)
Private Member Functions
void drawGrid (QPainter &painter, int scaleX, int scaleY)
bool getBarByX (int x, int *bar)
virtual void paintEvent (QPaintEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void wheelEvent (QWheelEvent *event)
void setZone (int zoneBorder)
void recalculateFrame ()
double toAbsolute (double const &x) const
double toRelative (double const &x) const
Private Attributes
int mSelectedH
Ui::HistogramWidgetClass * mUi
bool mUseMargin
Histogram * mHistogram
double mZoneStart
double mZoneEnd
double mPreZoneStart
double mClickZoneEnd
ZoneSettingState mZoneSettingState
bool mSettingZone
double mZoomFactor
double mFrameLeftBorder
QPointF mPrevMousePos
Detailed Description
Definition at line 13 of file histogramwidget.h.
Member Enumeration Documentation
enum HistogramWidget::ZoneSettingState
Enumerator:
none
preZone
zoneStart
zoneEnd
clickEnd
Definition at line 23 of file histogramwidget.h.
{
        none
        , preZone
        , zoneStart
        , zoneEnd
        , clickEnd
    };
Constructor & Destructor Documentation
HistogramWidget::HistogramWidget (QWidget * parent = 0)
Definition at line 14 of file histogramwidget.cpp.
References mUi.
    : QWidget(parent)
    , mUi(new Ui::HistogramWidgetClass)
    , mUseMargin(false)
    , mHistogram(NULL)
    , mZoneStart(std::numeric_limits<int>::min())
    , mZoneEnd(std::numeric_limits<int>::min())
    , mPreZoneStart(std::numeric_limits<int>::min())
    , mClickZoneEnd(std::numeric_limits<int>::min())
    , mZoneSettingState(none)
    , mSettingZone(false)
    , mZoomFactor(1.0)
    , mFrameLeftBorder(0.0)
{
    mUi->setupUi(this);
}
HistogramWidget::~HistogramWidget ()
Definition at line 31 of file histogramwidget.cpp.
References mUi.
{
    delete mUi;
}
Member Function Documentation
void HistogramWidget::clickZoneEndChanged (int zone) [signal]
Referenced by mousePressEvent(), and setZone().
void HistogramWidget::drawGrid (QPainter & painter, int scaleX, int scaleY) [private]
Definition at line 154 of file histogramwidget.cpp.
References gridDensity, initialGridStep, corecvs::Histogram::max, mHistogram, corecvs::Histogram::min, mZoomFactor, and toRelative().
Referenced by paintEvent().
{
    Q_UNUSED(scaleX);
    int const h = size().height();
    double dy = static_cast<double>(h) / scaleY;
    while (dy < 10)
        dy *= 10;
    double x = mHistogram->min;
    double y = 0;
    double gridStep = initialGridStep;
    while (width() / mZoomFactor / gridStep < gridDensity)
        gridStep /= 2;
    QPen pen(Qt::DotLine);
    for (int j = 0; x < mHistogram->max; x += gridStep, j++)
    {
        pen.setColor(j % 5 ? Qt::gray : Qt::black);
        painter.setPen(pen);
        painter.drawLine(toRelative(x), 0, toRelative(x), h);
    }
    for (int i = 0; y < h; y += dy, i++)
    {
        pen.setColor(i % 5 ? Qt::gray : Qt::black);
        painter.setPen(pen);
        double const start = qMax(0.0, toRelative(mHistogram->min));
        double const end = qMin(static_cast<double>(size().width()), toRelative(mHistogram->max));
        painter.drawLine(start, y, end, y);
    }
}
bool HistogramWidget::getBarByX (int x, int * bar) [private]
Definition at line 223 of file histogramwidget.cpp.
References corecvs::Histogram::max, and mHistogram.
Referenced by mousePressEvent(), paintEvent(), and setZone().
{
    if (mHistogram == NULL || x < mHistogram->min || x >= mHistogram->max)
        return false;
    *bar = x;
    return true;
}
void HistogramWidget::histogramBarClicked (int bar) [signal]
Referenced by mousePressEvent().
void HistogramWidget::mouseMoveEvent (QMouseEvent * event) [private, virtual]
Definition at line 265 of file histogramwidget.cpp.
References corecvs::Histogram::max, mFrameLeftBorder, mHistogram, mPrevMousePos, mSelectedH, mSettingZone, mZoomFactor, setZone(), and toAbsolute().
{
    int const x = event->x();
    if (x > 0 && x < size().width())
    {
        mSelectedH = x;
        if (mSettingZone)
            setZone(toAbsolute(x));
#if QT_VERSION >= 0x040700
        if (event->buttons() & (Qt::MiddleButton | Qt::RightButton))
#else
            if (event->buttons() & (Qt::MidButton | Qt::RightButton))
#endif
            {
            if (mPrevMousePos != QPointF())
            {
                double const delta = (event->posF().x() - mPrevMousePos.x()) / mZoomFactor;
                if (!(mFrameLeftBorder < mHistogram->min && delta > 0)
                    && !(mFrameLeftBorder + toAbsolute(width()) > mHistogram->max && delta < 0))
                    {
                    mFrameLeftBorder -= delta;
                }
            }
            mPrevMousePos = event->posF();
        }
        update();
    }
}
void HistogramWidget::mousePressEvent (QMouseEvent * event) [private, virtual]
Definition at line 232 of file histogramwidget.cpp.
References clickZoneEndChanged(), getBarByX(), histogramBarClicked(), corecvs::Histogram::max, mClickZoneEnd, mHistogram, mPreZoneStart, mSettingZone, mZoneEnd, mZoneStart, preZoneChanged(), setZone(), toAbsolute(), zoneEndChanged(), and zoneStartChanged().
{
    if (event->buttons() & Qt::RightButton & Qt::LeftButton)
    {
        if (mHistogram)
        {
            mPreZoneStart = mHistogram->max;
            mZoneStart = mHistogram->max;
            mZoneEnd = mHistogram->max;
            mClickZoneEnd = mHistogram->max;
            emit preZoneChanged(mHistogram->max);
            emit zoneStartChanged(mHistogram->max);
            emit zoneEndChanged(mHistogram->max);
            emit clickZoneEndChanged(mHistogram->max);
        }
        update();
        return;
    }
    if (event->button() == Qt::LeftButton) {
        int const x = floor(toAbsolute(event->x()));
        mSettingZone = true;
        setZone(x);
        int bar = 0;
        if (getBarByX(x, &bar)) {
            emit histogramBarClicked(bar);
        } else {
            printf("Bar out of range %d\n", bar);
        }
    }
}
void HistogramWidget::mouseReleaseEvent (QMouseEvent * event) [private, virtual]
Definition at line 298 of file histogramwidget.cpp.
References mPrevMousePos, and mSettingZone.
{
    Q_UNUSED(event)
    mSettingZone = false;
    mPrevMousePos = QPointF();
}
void HistogramWidget::notifyHistogramChange (Histogram * histogram, bool useMargin) [slot]
Definition at line 190 of file histogramwidget.cpp.
References mHistogram, mSelectedH, mUseMargin, and recalculateFrame().
{
    mSelectedH = 0;
    bool needRecalculateFrame = (mHistogram == NULL);
    mHistogram = histogram;
    mUseMargin = useMargin;
    if (needRecalculateFrame && mHistogram != NULL) {
        recalculateFrame();
    }
    update();
}
void HistogramWidget::paintEvent (QPaintEvent * event) [private, virtual]
Definition at line 36 of file histogramwidget.cpp.
References corecvs::Histogram::data, drawGrid(), getBarByX(), corecvs::Histogram::getData(), corecvs::Histogram::getMaximum(), corecvs::Histogram::max, mClickZoneEnd, mHistogram, corecvs::Histogram::min, mPreZoneStart, mSelectedH, mUseMargin, mZoneEnd, mZoneStart, mZoomFactor, toAbsolute(), toRelative(), zoneEnd, and zoneStart.
{
    QPainter painter(this);
    painter.setPen(Qt::black);
    int h = size().height();
    if (mHistogram == NULL)
    {
        painter.drawText(0, 0, size().width(), size().height(), Qt::AlignHCenter | Qt::AlignVCenter, QString("NO Histogram"));
        return;
    }
    if (h == 0)
        h = 1;
    uint32_t globalMax = 0;
    unsigned const start = mUseMargin ? 0 : 1;
    unsigned const end   = (unsigned)mHistogram->data.size() - start - 1;
    unsigned x = start;
    globalMax = mHistogram->getMaximum(mUseMargin);
    double scaleY = static_cast<double>(h) / (globalMax + 1);
    drawGrid(painter, end - start, globalMax + 1);
    double const step = qMax(1.0 / mZoomFactor, 1.0);
    int const barWidth = qMax(mZoomFactor, 1.0);
    int selectedBar = floor(toAbsolute(mSelectedH));
    for (int i = mHistogram->min; i < mHistogram->max; ++i, ++x)
    {
        int max  =  0;
        int min  =  std::numeric_limits<int>::max();
        int sum  =  0;
        int count = 0;
        for (unsigned j = x; j < static_cast<unsigned>(x + step) && j <= end; j++)
        {
            int const val = mHistogram->data[j];
            sum += val;
            if (val > max)
                max = val;
            if (val < min)
                min = val;
            count++;
        }
        if (count == 0)
            continue;
        sum /= count;
        painter.setPen(Qt::blue);
        painter.setBrush(Qt::blue);
        painter.drawRect(toRelative(i), h - 1, barWidth, -(max * scaleY));
        painter.setPen(Qt::black);
        painter.setBrush(Qt::black);
        painter.drawRect(toRelative(i), h - 1, barWidth, -(sum * scaleY));
        painter.setPen(barWidth > 1 ? Qt::darkGreen : Qt::green);
        painter.setBrush(Qt::green);
        painter.drawRect(toRelative(i), h - 1, barWidth, -(min * scaleY));
        if (i == selectedBar)
        {
            painter.save();
            painter.setOpacity(0.3);
            painter.setPen(Qt::yellow);
            painter.setBrush(Qt::yellow);
            painter.drawRect(toRelative(i), h - 1, barWidth, - h + 2);
            painter.restore();
        }
    }
    int bar = 0;
    if (getBarByX(floor(toAbsolute(mSelectedH)), &bar))
    {
        painter.setPen(Qt::black);
        if (bar < (mHistogram->max - mHistogram->min) / 2)
            painter.drawText(mSelectedH, (h - 1) / 2, 200, 20, Qt::AlignLeft, QString("%1 %2").arg(bar).arg(mHistogram->getData(bar)));
        else
            painter.drawText(mSelectedH - 200, (h - 1) / 2, 200, 20, Qt::AlignRight, QString("%1 %2").arg(bar).arg(mHistogram->getData(bar)));
    }
    painter.save();
    painter.setOpacity(0.5);
    if (mPreZoneStart > std::numeric_limits<int>::min())
    {
        painter.setBrush(QColor(248, 168, 255));
        int const zoneStart = mZoneStart > mPreZoneStart ? mZoneStart : width();
        painter.drawRect(toRelative(mPreZoneStart), 0, toRelative(zoneStart) - toRelative(mPreZoneStart), h - 1);
    }
    if (mZoneStart > std::numeric_limits<int>::min())
    {
        int const zoneEnd = mZoneEnd > mZoneStart ? mZoneEnd : width();
        QLinearGradient gradient(QPointF(toRelative(mZoneStart), 0), QPointF(toRelative(mZoneEnd), 0));
        gradient.setColorAt(0, Qt::yellow);
        gradient.setColorAt(0.5, Qt::green);
        gradient.setColorAt(1, Qt::blue);
        QBrush brush(gradient);
        painter.setBrush(brush);
        painter.drawRect(toRelative(mZoneStart), 0, toRelative(zoneEnd) - toRelative(mZoneStart), h - 1);
    }
    if (mZoneEnd > std::numeric_limits<int>::min())
    {
        int const clickZoneEnd = mClickZoneEnd > mZoneEnd ? mClickZoneEnd : width();
        painter.setBrush(QColor(128, 0, 0));
        painter.drawRect(toRelative(mZoneEnd), 0, toRelative(clickZoneEnd) - toRelative(mZoneEnd), h - 1);
    }
    painter.restore();
}
void HistogramWidget::preZoneChanged (int zone) [signal]
Referenced by mousePressEvent(), and setZone().
void HistogramWidget::recalculateFrame () [private]
Definition at line 202 of file histogramwidget.cpp.
References corecvs::Histogram::data, mFrameLeftBorder, mHistogram, corecvs::Histogram::min, and mZoomFactor.
Referenced by notifyHistogramChange().
{
    /* Searching right and left borders */
    int min = std::numeric_limits<int>::max();
    int max = std::numeric_limits<int>::min();
    for (int i = mHistogram->min; i < mHistogram->max; ++i)
    {
        if (min > i && mHistogram->data[i - mHistogram->min] > 0) {
            min = i;
        }
        if (max < i && mHistogram->data[i - mHistogram->min] > 0) {
            max = i;
        }
    }
    mFrameLeftBorder = min;
    if (max != min) {
        mZoomFactor = width() / static_cast<double>(max - min + 1);
    }
}
void HistogramWidget::resizeEvent (QResizeEvent * event) [private, virtual]
Definition at line 368 of file histogramwidget.cpp.
{
}
void HistogramWidget::setZone (int zoneBorder) [private]
Definition at line 310 of file histogramwidget.cpp.
References clickEnd, clickZoneEndChanged(), getBarByX(), mClickZoneEnd, mPreZoneStart, mZoneEnd, mZoneSettingState, mZoneStart, none, preZone, preZoneChanged(), zoneEnd, zoneEndChanged(), zoneStart, and zoneStartChanged().
Referenced by mouseMoveEvent(), and mousePressEvent().
{
    int recalculated = 0;
    switch (mZoneSettingState) {
    case none: return;
    case preZone:
        {
            if (zoneBorder > mZoneStart)
                return;
            mPreZoneStart = zoneBorder;
            if (getBarByX(mPreZoneStart, &recalculated))
                emit preZoneChanged(recalculated);
            break;
        }
    case zoneStart:
        {
            if (zoneBorder < mPreZoneStart || zoneBorder > mZoneEnd)
                return;
            mZoneStart = zoneBorder;
            if (getBarByX(mZoneStart, &recalculated))
                emit zoneStartChanged(recalculated);
            break;
        }
    case zoneEnd:
        {
            if (zoneBorder < mZoneStart || zoneBorder > mClickZoneEnd)
                return;
            mZoneEnd = zoneBorder;
            if (getBarByX(mZoneEnd, &recalculated))
                emit zoneEndChanged(recalculated);
            break;
        }
    case clickEnd:
        {
            if (zoneBorder < mZoneEnd)
                return;
            mClickZoneEnd = zoneBorder;
            if (getBarByX(mClickZoneEnd, &recalculated))
                emit clickZoneEndChanged(recalculated);
            break;
        }
    }
    update();
}
void HistogramWidget::setZones (int zoneStart, int zoneEnd, int preZoneStart, int clickZoneEnd)
Definition at line 356 of file histogramwidget.cpp.
References mClickZoneEnd, mPreZoneStart, mSettingZone, mZoneEnd, mZoneStart, zoneEnd, and zoneStart.
{
    if (mSettingZone || preZoneStart > zoneStart
        || zoneStart > zoneEnd || zoneEnd > clickZoneEnd)
        return;
    mZoneStart = zoneStart;
    mZoneEnd = zoneEnd;
    mPreZoneStart = preZoneStart;
    mClickZoneEnd = clickZoneEnd;
    update();
}
void HistogramWidget::setZoneSettingState (ZoneSettingState state)
Definition at line 305 of file histogramwidget.cpp.
References mZoneSettingState.
{
    mZoneSettingState = state;
}
double HistogramWidget::toAbsolute (double const & x) const [private]
Definition at line 380 of file histogramwidget.cpp.
References mFrameLeftBorder, and mZoomFactor.
Referenced by mouseMoveEvent(), mousePressEvent(), and paintEvent().
{
    return x / mZoomFactor + mFrameLeftBorder;
}
double HistogramWidget::toRelative (double const & x) const [private]
Definition at line 385 of file histogramwidget.cpp.
References mFrameLeftBorder, and mZoomFactor.
Referenced by drawGrid(), and paintEvent().
{
    return (x - mFrameLeftBorder) * mZoomFactor;
}
void HistogramWidget::wheelEvent (QWheelEvent * event) [private, virtual]
Definition at line 372 of file histogramwidget.cpp.
References zoomIn(), and zoomOut().
{
    if (event->delta() > 0)
        zoomIn();
    else
        zoomOut();
}
void HistogramWidget::zoneEndChanged (int zone) [signal]
Referenced by mousePressEvent(), and setZone().
void HistogramWidget::zoneStartChanged (int zone) [signal]
Referenced by mousePressEvent(), and setZone().
void HistogramWidget::zoomIn () [slot]
Definition at line 390 of file histogramwidget.cpp.
References mFrameLeftBorder, mSelectedH, mZoomFactor, and zoomSpeed.
Referenced by wheelEvent().
{
    double const mOldZoomFactor = mZoomFactor;
    mZoomFactor *= zoomSpeed;
    mFrameLeftBorder += static_cast<double>(mSelectedH) / mOldZoomFactor - static_cast<double>(mSelectedH) / mZoomFactor;
    update();
}
void HistogramWidget::zoomOut () [slot]
Definition at line 398 of file histogramwidget.cpp.
References mFrameLeftBorder, mSelectedH, mZoomFactor, and zoomSpeed.
Referenced by wheelEvent().
{
    double const mOldZoomFactor = mZoomFactor;
    mZoomFactor /= zoomSpeed;
    mFrameLeftBorder += static_cast<double>(mSelectedH) / mOldZoomFactor - static_cast<double>(mSelectedH) / mZoomFactor;
    update();
}
Member Data Documentation
double HistogramWidget::mClickZoneEnd [private]
Definition at line 53 of file histogramwidget.h.
Referenced by mousePressEvent(), paintEvent(), setZone(), and setZones().
double HistogramWidget::mFrameLeftBorder [private]
Definition at line 58 of file histogramwidget.h.
Referenced by mouseMoveEvent(), recalculateFrame(), toAbsolute(), toRelative(), zoomIn(), and zoomOut().
Histogram* HistogramWidget::mHistogram [private]
Definition at line 48 of file histogramwidget.h.
Referenced by drawGrid(), getBarByX(), mouseMoveEvent(), mousePressEvent(), notifyHistogramChange(), paintEvent(), and recalculateFrame().
QPointF HistogramWidget::mPrevMousePos [private]
Definition at line 59 of file histogramwidget.h.
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
double HistogramWidget::mPreZoneStart [private]
Definition at line 52 of file histogramwidget.h.
Referenced by mousePressEvent(), paintEvent(), setZone(), and setZones().
int HistogramWidget::mSelectedH [private]
Definition at line 45 of file histogramwidget.h.
Referenced by mouseMoveEvent(), notifyHistogramChange(), paintEvent(), zoomIn(), and zoomOut().
bool HistogramWidget::mSettingZone [private]
Definition at line 55 of file histogramwidget.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setZones().
Ui::HistogramWidgetClass* HistogramWidget::mUi [private]
Definition at line 46 of file histogramwidget.h.
Referenced by HistogramWidget(), and ~HistogramWidget().
bool HistogramWidget::mUseMargin [private]
Definition at line 47 of file histogramwidget.h.
Referenced by notifyHistogramChange(), and paintEvent().
double HistogramWidget::mZoneEnd [private]
Definition at line 51 of file histogramwidget.h.
Referenced by mousePressEvent(), paintEvent(), setZone(), and setZones().
ZoneSettingState HistogramWidget::mZoneSettingState [private]
Definition at line 54 of file histogramwidget.h.
Referenced by setZone(), and setZoneSettingState().
double HistogramWidget::mZoneStart [private]
Definition at line 50 of file histogramwidget.h.
Referenced by mousePressEvent(), paintEvent(), setZone(), and setZones().
double HistogramWidget::mZoomFactor [private]
Definition at line 57 of file histogramwidget.h.
Referenced by drawGrid(), mouseMoveEvent(), paintEvent(), recalculateFrame(), toAbsolute(), toRelative(), zoomIn(), and zoomOut().
The documentation for this class was generated from the following files:
utils/corestructs/histogramwidget.h
utils/corestructs/histogramwidget.cpp