DeepView: CaptureParameter Class Reference
CaptureParameter Class Reference
#include <cameraControlParameters.h>
Public Member Functions
CaptureParameter ()
CaptureParameter (bool autoSupported, int maximum, int defaultValue, int minimum, int step)
int maximum () const
void setMaximum (int const &maximum)
int defaultValue () const
void setDefaultValue (int const &defaultValue)
int minimum () const
void setMinimum (int const &minimum)
int step () const
void setStep (int const &step)
bool active () const
void setActive (bool active)
bool isMenu () const
void setIsMenu (bool isMenu)
bool autoSupported () const
void setAutoSupported (bool autoSupported)
bool hasMenuItems () const
unsigned getMenuItemNumber () const
const QString getMenuItem (int index) const
int getMenuValue (int index) const
void pushMenuItem (QString name, int value)
Private Attributes
bool mActive
bool mAutoSupported
int mMaximum
int mDefaultValue
int mMinimum
int mStep
bool mIsMenu
vector< QString > mMenuItems
vector< int > mMenuValue
Detailed Description
Definition at line 8 of file cameraControlParameters.h.
Constructor & Destructor Documentation
CaptureParameter::CaptureParameter () [inline]
Definition at line 11 of file cameraControlParameters.h.
    : mActive (false)
    , mAutoSupported(false)
    , mMaximum(0)
    , mDefaultValue(0)
    , mMinimum(0)
    , mStep(0)
    , mIsMenu(false)
    {}
CaptureParameter::CaptureParameter (bool autoSupported, int maximum, int defaultValue, int minimum, int step) [inline]
Definition at line 21 of file cameraControlParameters.h.
      :
      mActive (true)
    , mAutoSupported(autoSupported)
    , mMaximum(maximum)
    , mDefaultValue(defaultValue)
    , mMinimum(minimum)
    , mStep(step)
    , mIsMenu(false)
    {}
Member Function Documentation
bool CaptureParameter::active () const [inline]
Definition at line 51 of file cameraControlParameters.h.
References mActive.
Referenced by CapSettingsDialog::refreshDialog(), CapSettingsDialog::resetAllPressed(), and setActive().
{ return mActive;   }
bool CaptureParameter::autoSupported () const [inline]
Definition at line 58 of file cameraControlParameters.h.
References mAutoSupported.
Referenced by CapSettingsDialog::refreshDialog(), and setAutoSupported().
{ return mAutoSupported;          }
int CaptureParameter::defaultValue () const [inline]
Definition at line 41 of file cameraControlParameters.h.
References mDefaultValue.
Referenced by CapSettingsDialog::resetPressed(), and setDefaultValue().
{ return mDefaultValue;         }
const QString CaptureParameter::getMenuItem (int index) const [inline]
Definition at line 63 of file cameraControlParameters.h.
References mMenuItems.
Referenced by CapSettingsDialog::refreshDialog().
{ return mMenuItems[index]; }
unsigned CaptureParameter::getMenuItemNumber () const [inline]
Definition at line 62 of file cameraControlParameters.h.
References mMenuItems.
Referenced by hasMenuItems(), and CapSettingsDialog::refreshDialog().
{ return (unsigned)mMenuItems.size(); }
int CaptureParameter::getMenuValue (int index) const [inline]
Definition at line 64 of file cameraControlParameters.h.
References mMenuValue.
Referenced by CapSettingsDialog::refreshDialog().
{ return mMenuValue[index]; }
bool CaptureParameter::hasMenuItems () const [inline]
Definition at line 61 of file cameraControlParameters.h.
References getMenuItemNumber().
Referenced by CapSettingsDialog::refreshDialog().
{ return getMenuItemNumber() != 0;    }
bool CaptureParameter::isMenu () const [inline]
Definition at line 54 of file cameraControlParameters.h.
References mIsMenu.
Referenced by CapSettingsDialog::refreshDialog(), and setIsMenu().
{ return mIsMenu;   }
int CaptureParameter::maximum () const [inline]
Definition at line 38 of file cameraControlParameters.h.
References mMaximum.
Referenced by CapSettingsDialog::refreshDialog(), and setMaximum().
{ return mMaximum;    }
int CaptureParameter::minimum () const [inline]
Definition at line 45 of file cameraControlParameters.h.
References mMinimum.
Referenced by CapSettingsDialog::refreshDialog(), and setMinimum().
{ return mMinimum;    }
void CaptureParameter::pushMenuItem (QString name, int value) [inline]
Definition at line 66 of file cameraControlParameters.h.
References mMenuItems, and mMenuValue.
Referenced by UEyeCaptureInterface::queryCameraParameters(), DirectShowCameraDescriptor::queryCameraParameters(), and V4L2CameraDescriptor::setFromQueryCtrl().
    {
        mMenuItems.push_back(name);
        mMenuValue.push_back(value);
    }
void CaptureParameter::setActive (bool active) [inline]
Definition at line 52 of file cameraControlParameters.h.
References active(), and mActive.
Referenced by UEyeCaptureInterface::queryCameraParameters(), DirectShowCameraDescriptor::queryCameraParameters(), DirectShowCameraDescriptor::setFromCameraParam(), and V4L2CameraDescriptor::setFromQueryCtrl().
{ mActive = active; }
void CaptureParameter::setAutoSupported (bool autoSupported) [inline]
Definition at line 59 of file cameraControlParameters.h.
References autoSupported(), and mAutoSupported.
{ mAutoSupported = autoSupported; }
void CaptureParameter::setDefaultValue (int const & defaultValue) [inline]
Definition at line 42 of file cameraControlParameters.h.
References defaultValue(), and mDefaultValue.
Referenced by UEyeCaptureInterface::queryCameraParameters(), DirectShowCameraDescriptor::queryCameraParameters(), DirectShowCameraDescriptor::setFromCameraParam(), and V4L2CameraDescriptor::setFromQueryCtrl().
{ mDefaultValue = defaultValue; }
void CaptureParameter::setIsMenu (bool isMenu) [inline]
Definition at line 55 of file cameraControlParameters.h.
References isMenu(), and mIsMenu.
Referenced by UEyeCaptureInterface::queryCameraParameters(), DirectShowCameraDescriptor::queryCameraParameters(), and V4L2CameraDescriptor::setFromQueryCtrl().
{ mIsMenu = isMenu; }
void CaptureParameter::setMaximum (int const & maximum) [inline]
Definition at line 39 of file cameraControlParameters.h.
References maximum(), and mMaximum.
Referenced by UEyeCaptureInterface::queryCameraParameters(), DirectShowCameraDescriptor::queryCameraParameters(), DirectShowCameraDescriptor::setFromCameraParam(), and V4L2CameraDescriptor::setFromQueryCtrl().
{ mMaximum = maximum; }
void CaptureParameter::setMinimum (int const & minimum) [inline]
Definition at line 46 of file cameraControlParameters.h.
References minimum(), and mMinimum.
Referenced by UEyeCaptureInterface::queryCameraParameters(), DirectShowCameraDescriptor::queryCameraParameters(), DirectShowCameraDescriptor::setFromCameraParam(), and V4L2CameraDescriptor::setFromQueryCtrl().
{ mMinimum = minimum; }
void CaptureParameter::setStep (int const & step) [inline]
Definition at line 49 of file cameraControlParameters.h.
References mStep, and step().
Referenced by UEyeCaptureInterface::queryCameraParameters(), DirectShowCameraDescriptor::queryCameraParameters(), and DirectShowCameraDescriptor::setFromCameraParam().
{ mStep = step; }
int CaptureParameter::step () const [inline]
Definition at line 48 of file cameraControlParameters.h.
References mStep.
Referenced by setStep().
{ return mStep; }
Member Data Documentation
bool CaptureParameter::mActive [private]
Definition at line 75 of file cameraControlParameters.h.
Referenced by active(), and setActive().
bool CaptureParameter::mAutoSupported [private]
Definition at line 76 of file cameraControlParameters.h.
Referenced by autoSupported(), and setAutoSupported().
int CaptureParameter::mDefaultValue [private]
Definition at line 78 of file cameraControlParameters.h.
Referenced by defaultValue(), and setDefaultValue().
bool CaptureParameter::mIsMenu [private]
Definition at line 81 of file cameraControlParameters.h.
Referenced by isMenu(), and setIsMenu().
int CaptureParameter::mMaximum [private]
Definition at line 77 of file cameraControlParameters.h.
Referenced by maximum(), and setMaximum().
vector<QString> CaptureParameter::mMenuItems [private]
Definition at line 82 of file cameraControlParameters.h.
Referenced by getMenuItem(), getMenuItemNumber(), and pushMenuItem().
vector<int> CaptureParameter::mMenuValue [private]
Definition at line 83 of file cameraControlParameters.h.
Referenced by getMenuValue(), and pushMenuItem().
int CaptureParameter::mMinimum [private]
Definition at line 79 of file cameraControlParameters.h.
Referenced by minimum(), and setMinimum().
int CaptureParameter::mStep [private]
Definition at line 80 of file cameraControlParameters.h.
Referenced by setStep(), and step().
The documentation for this class was generated from the following file:
utils/framesources/cameraControlParameters.h