DeepView: corecvs::DistortionCorrectTransform Class Reference
corecvs::DistortionCorrectTransform Class Reference
#include <distortionCorrectTransform.h>
Public Types
typedef Vector2d< int32_t > InputPoint
typedef Vector2d< double > OutputPoint
Public Member Functions
DistortionCorrectTransform ()
DistortionCorrectTransform (Vector2dd const &centre, int r)
DistortionCorrectTransform (Vector2dd const &centre, int r, int z)
DistortionCorrectTransform (const Vector2dd &centre)
virtual ~DistortionCorrectTransform ()
G12Buffer * doCorrectionTransform (G12Buffer *inputBuffer)
Vector2dd map (Vector2dd const &v) const
Vector2dd map (int32_t y, int32_t x) const
void setRadius (Vector2dd const &point1, Vector2dd const &point2, Vector2dd const &point3)
void setRadius (double r)
OutputPoint map (const int32_t &, const int32_t &)
Private Member Functions
bool isInteriorPoint (double x, double y) const
void setZ ()
Private Attributes
Vector2dd mCenter
double mRad
double mZ
Detailed Description
Definition at line 6 of file distortionCorrectTransform.h.
Member Typedef Documentation
typedef Vector2d<int32_t > corecvs::DeformMap< int32_t , double >::InputPoint [inherited]
Definition at line 81 of file abstractBuffer.h.
typedef Vector2d<double > corecvs::DeformMap< int32_t , double >::OutputPoint [inherited]
Definition at line 82 of file abstractBuffer.h.
Constructor & Destructor Documentation
corecvs::DistortionCorrectTransform::DistortionCorrectTransform () [inline]
Definition at line 9 of file distortionCorrectTransform.h.
References mCenter, mRad, and mZ.
    {
        mRad = 0;
        mCenter = Vector2dd(0, 0);
        mZ = 300;
    }
corecvs::DistortionCorrectTransform::DistortionCorrectTransform (Vector2dd const & centre, int r) [inline]
Definition at line 16 of file distortionCorrectTransform.h.
References mCenter, and setRadius().
    {
        mCenter = centre;
        setRadius(r);
    }
corecvs::DistortionCorrectTransform::DistortionCorrectTransform (Vector2dd const & centre, int r, int z) [inline]
Definition at line 21 of file distortionCorrectTransform.h.
References mCenter, mRad, and mZ.
    {
        mRad = r;
        mZ = z;
        mCenter = centre;
    }
corecvs::DistortionCorrectTransform::DistortionCorrectTransform (const Vector2dd & centre) [inline]
Definition at line 27 of file distortionCorrectTransform.h.
References mCenter.
    {
        mCenter = centre;
    }
virtual corecvs::DistortionCorrectTransform::~DistortionCorrectTransform () [inline, virtual]
Definition at line 31 of file distortionCorrectTransform.h.
    {
    }
Member Function Documentation
G12Buffer* corecvs::DistortionCorrectTransform::doCorrectionTransform (G12Buffer * inputBuffer) [inline]
Definition at line 35 of file distortionCorrectTransform.h.
References corecvs::AbstractContiniousBuffer< ElementType, IndexType >::doReverseDeformationBl(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
    {
        return inputBuffer->doReverseDeformationBl<G12Buffer, DistortionCorrectTransform>(
                                 this, inputBuffer->h, inputBuffer->w);
    }
bool corecvs::DistortionCorrectTransform::isInteriorPoint (double x, double y) const [inline, private]
Definition at line 140 of file distortionCorrectTransform.h.
References mRad.
Referenced by map(), and setZ().
    {
        return (pow(mRad, 2) >= pow(x, 2) + pow(y, 2));
    }
Vector2dd corecvs::DistortionCorrectTransform::map (Vector2dd const & v) const [inline]
Definition at line 41 of file distortionCorrectTransform.h.
References isInteriorPoint(), mCenter, mRad, mZ, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by corecvs::DisplacementBuffer::DisplacementBuffer(), and map().
    {
        if (mCenter.x() == 0)
        {
            return v;
        }
        double x = v.x() - mCenter.x();
        double y = v.y() - mCenter.y();
        double k = 1;
        if (isInteriorPoint(x, y))
            k = 2 * mRad * mZ / (mZ * mZ + pow(x, 2) + pow(y, 2));
        //qDebug() << k;
        return Vector2dd(mCenter.x() + x * k, mCenter.y() + y * k);
    }
Vector2dd corecvs::DistortionCorrectTransform::map (int32_t y, int32_t x) const [inline]
Definition at line 55 of file distortionCorrectTransform.h.
References map().
    {
        Vector2dd v(x, y);
        return map(v);
    }
OutputPoint corecvs::DeformMap< int32_t , double >::map (const int32_t & , const int32_t &) [inline, inherited]
Definition at line 85 of file abstractBuffer.h.
{}
void corecvs::DistortionCorrectTransform::setRadius (Vector2dd const & point1, Vector2dd const & point2, Vector2dd const & point3) [inline]
Definition at line 60 of file distortionCorrectTransform.h.
References corecvs::Matrix::a(), corecvs::Matrix::inv(), mCenter, mRad, setZ(), ClusteringDirectionType::X, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by DistortionCorrectTransform(), and DistortionWidget::doInversionTransform().
    {
        double k = 1; // try k = mCenter.y() / mCenter.x()
        Vector2dd p1((point1.x() - mCenter.x()) * k,
                     point1.y() - mCenter.y());
        Vector2dd p2((point2.x() - mCenter.x()) * k,
                     point2.y() - mCenter.y());
        Vector2dd p3((point3.x() - mCenter.x()) * k,
                     point3.y() - mCenter.y());
        Matrix X(3, 1);
        double const firstR = 500;
        mRad = firstR;
        X.a(0, 0) = 0;
        X.a(1, 0) = 0;
        if (p1.x() * p2.y() - p2.x() * p1.y() != 0)
        {
            X.a(0, 0) = (p1.y() * (firstR + sqrt(firstR * firstR - p2.x() * p2.x() - p2.y() * p2.y())) -
                    p2.y() * (firstR + sqrt(firstR * firstR - p1.x() * p1.x() - p1.y() * p1.y()))) /
                    (p1.x() * p2.y() - p2.x() * p1.y());
            X.a(1, 0) =  - (p1.x() * (firstR + sqrt(firstR * firstR - p2.x() * p2.x() - p2.y() * p2.y())) -
                         p2.x() * (firstR + sqrt(firstR * firstR - p1.x() * p1.x() - p1.y() * p1.y()))) /
                         (p1.x() * p2.y() - p2.x() * p1.y());
        }
        X.a(2, 0) = firstR;
        Matrix *W = new Matrix(3, 3);
        for (int i = 0; i < 10; i ++)
        {
            W->a(0, 0) = p1.x();
            W->a(0, 1) = p1.y();
            W->a(0, 2) = 1 + X.a(2, 0) / sqrt(
                        X.a(2, 0) * X.a(2, 0) - p1.x() * p1.x() - p1.y() * p1.y());
            W->a(1, 0) = p2.x();
            W->a(1, 1) = p2.y();
            W->a(1, 2) = 1 + X.a(2, 0) / sqrt(
                        X.a(2, 0) * X.a(2, 0) - p2.x() * p2.x() - p2.y() * p2.y());
            W->a(2, 0) = p3.x();
            W->a(2, 1) = p3.y();
            W->a(2, 2) = 1 + X.a(2, 0) / sqrt(
                        X.a(2, 0) * X.a(2, 0) - p3.x() * p3.x() - p3.y() * p3.y());
            Matrix invW(3, 3);
            invW = W->inv();
#ifdef DEBUG
            Matrix testE(3, 3);
            testE = invW * (*W);
#endif
            Matrix F(3, 1);
            F.a(0, 0) = X.a(0, 0) * p1.x() + X.a(1, 0) * p1.y() + X.a(2, 0)
                    + sqrt(X.a(2, 0) * X.a(2, 0) - p1.x() * p1.x() - p1.y() * p1.y());
            F.a(1, 0) = X.a(0, 0) * p2.x() + X.a(1, 0) * p2.y() + X.a(2, 0)
                    + sqrt(X.a(2, 0) * X.a(2, 0) - p2.x() * p2.x() - p2.y() * p2.y());
            F.a(2, 0) = X.a(0, 0) * p3.x() + X.a(1, 0) * p3.y() + X.a(2, 0)
                    + sqrt(X.a(2, 0) * X.a(2, 0) - p3.x() * p3.x() - p3.y() * p3.y());
            X = X - invW * F;
            double farPointNorm = max(max(p1.l2Metric(), p2.l2Metric()), p3.l2Metric());
            if (X.a(2, 0) <= farPointNorm)
            {
                // something terrible
                X.a(2, 0) = farPointNorm + (i + 11) * 0.1;
            }
            else
            {
                mRad = X.a(2, 0);
            }
        }
        setZ();
        delete W;
    }
void corecvs::DistortionCorrectTransform::setRadius (double r) [inline]
Definition at line 129 of file distortionCorrectTransform.h.
References mRad, and setZ().
    {
        mRad = r;
        setZ();
    }
void corecvs::DistortionCorrectTransform::setZ () [inline, private]
Definition at line 145 of file distortionCorrectTransform.h.
References isInteriorPoint(), corecvs::VectorOperationsBase< RealType, ElementType >::l2Metric(), mCenter, mRad, mZ, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by setRadius().
    {
        mZ = mCenter.l2Metric();
        if (isInteriorPoint(mCenter.x(), mCenter.y()))
        {
            mZ = mRad + sqrt(mRad * mRad - mCenter.x() * mCenter.x() - mCenter.y() * mCenter.y());
        }
    }
Member Data Documentation
Vector2dd corecvs::DistortionCorrectTransform::mCenter [private]
Definition at line 136 of file distortionCorrectTransform.h.
Referenced by DistortionCorrectTransform(), map(), setRadius(), and setZ().
double corecvs::DistortionCorrectTransform::mRad [private]
Definition at line 137 of file distortionCorrectTransform.h.
Referenced by DistortionCorrectTransform(), isInteriorPoint(), map(), setRadius(), and setZ().
double corecvs::DistortionCorrectTransform::mZ [private]
Definition at line 138 of file distortionCorrectTransform.h.
Referenced by DistortionCorrectTransform(), map(), and setZ().
The documentation for this class was generated from the following file:
core/alignment/distortionCorrectTransform.h