DeepView: XmlSetter Class Reference
XmlSetter Class Reference
#include <xmlSetter.h>
Public Member Functions
XmlSetter (QString const &filename)
template<class Type >
void visit (Type &field, Type defaultValue, const char *fieldName)
template<typename inputType , typename reflectionType >
void visit (inputType &field, const reflectionType *fieldDescriptor)
template<>
void visit (int &intField, int, const char *fieldName)
template<>
void visit (bool &boolField, bool, const char *fieldName)
template<>
void visit (double &doubleField, double, const char *fieldName)
template<>
void visit (float &floatField, float, const char *fieldName)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (float &field, const FloatField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
template<>
void visit (void *&, const PointerField *)
template<>
void visit (int &field, const EnumField *fieldDescriptor)
template<>
void visit (int &intField, int defaultValue, const char *fieldName)
template<>
void visit (double &doubleField, double defaultValue, const char *fieldName)
template<>
void visit (float &floatField, float defaultValue, const char *fieldName)
template<>
void visit (bool &boolField, bool defaultValue, const char *fieldName)
template<>
void visit (int &field, const IntField *fieldDescriptor)
template<>
void visit (double &field, const DoubleField *fieldDescriptor)
template<>
void visit (float &field, const FloatField *fieldDescriptor)
template<>
void visit (bool &field, const BoolField *fieldDescriptor)
template<>
void visit (void *&field, const PointerField *fieldDescriptor)
template<>
void visit (int &field, const EnumField *fieldDescriptor)
string getCurrentPath ()
string getChildPath (string child)
void pushChild (const string child)
void popChild ()
Public Attributes
string separator
T elements
STL member.
Static Public Attributes
static string SEPARATOR_DEFAULT = "."
Private Member Functions
void saveValue (const char *fieldName, QString value)
Private Attributes
QString mFileName
Detailed Description
Definition at line 17 of file xmlSetter.h.
Constructor & Destructor Documentation
XmlSetter::XmlSetter (QString const & filename)
Definition at line 7 of file xmlSetter.cpp.
References mFileName.
{
    mFileName = filename;
}
Member Function Documentation
string corecvs::BasePathVisitor::getChildPath (string child) [inline, inherited]
Definition at line 35 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getCurrentPath(), and corecvs::BasePathVisitor::separator.
Referenced by corecvs::BasePathVisitor::pushChild().
    {
       string newPath = getCurrentPath();
       if (!newPath.empty())
           newPath.append(separator);
       newPath.append(child);
       return newPath;
    }
string corecvs::BasePathVisitor::getCurrentPath () [inline, inherited]
Definition at line 28 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
    {
        if (empty())
            return "";
        return back();
    }
void corecvs::BasePathVisitor::popChild () [inline, inherited]
Definition at line 55 of file basePathVisitor.h.
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        pop_back();
    }
void corecvs::BasePathVisitor::pushChild (const string child) [inline, inherited]
Definition at line 50 of file basePathVisitor.h.
References corecvs::BasePathVisitor::getChildPath().
Referenced by DefaultSetterOld::visit(), corecvs::PropertyListWriterVisitor::visit(), and corecvs::PropertyListReaderVisitor::visit().
    {
        push_back(getChildPath(child));
    }
void XmlSetter::saveValue (const char * fieldName, QString value) [private]
Definition at line 36 of file xmlSetter.cpp.
References mFileName.
{
    QFile file(mFileName);
    if (!file.open(QFile::ReadWrite))
        return;
    QDomDocument doc("document");
    doc.setContent(&file);
    QDomElement element = doc.elementById(fieldName);
    if (element.isNull())
    {
        QDomElement root = doc.documentElement();
        if (root.isNull())
        {
            root = doc.createElement("Parameters");
            doc.appendChild(root);
        }
        element = doc.createElement(fieldName);
        root.appendChild(element);
    }
    element.setAttribute("value", value);
    QTextStream textStream(&file);
    doc.save(textStream, 0);
    file.close();
}
template<> void XmlSetter::visit (int & intField, int , const char * fieldName)
Definition at line 13 of file xmlSetter.cpp.
{
    saveValue(fieldName, QString::number(intField));
}
template<> void XmlSetter::visit (bool & boolField, bool , const char * fieldName)
Definition at line 19 of file xmlSetter.cpp.
{
    saveValue(fieldName, boolField ? "true" : "false");
}
template<class Type > void XmlSetter::visit (Type & field, Type defaultValue, const char * fieldName) [inline]
Definition at line 22 of file xmlSetter.h.
    {
        pushChild(fieldName);
           field.accept(*this);
        popChild();
    }
template<> void XmlSetter::visit (double & doubleField, double , const char * fieldName)
Definition at line 25 of file xmlSetter.cpp.
{
    saveValue(fieldName, QString::number(doubleField));
}
template<typename inputType , typename reflectionType > void XmlSetter::visit (inputType & field, const reflectionType * fieldDescriptor) [inline]
Definition at line 30 of file xmlSetter.h.
    {
        pushChild(fieldDescriptor->getSimpleName());
           field.accept(*this);
        popChild();
    }
template<> void XmlSetter::visit (float & floatField, float , const char * fieldName)
Definition at line 31 of file xmlSetter.cpp.
{
    saveValue(fieldName, QString::number(floatField));
}
template<> void XmlSetter::visit (int & intField, int defaultValue, const char * fieldName)
template<> void XmlSetter::visit (double & doubleField, double defaultValue, const char * fieldName)
template<> void XmlSetter::visit (float & floatField, float defaultValue, const char * fieldName)
template<> void XmlSetter::visit (bool & boolField, bool defaultValue, const char * fieldName)
template<> void XmlSetter::visit (int & field, const IntField * fieldDescriptor)
template<> void XmlSetter::visit (double & field, const DoubleField * fieldDescriptor)
template<> void XmlSetter::visit (float & field, const FloatField * fieldDescriptor)
template<> void XmlSetter::visit (bool & field, const BoolField * fieldDescriptor)
template<> void XmlSetter::visit (int & field, const IntField * fieldDescriptor)
Definition at line 64 of file xmlSetter.cpp.
{
    saveValue(fieldDescriptor->name.name, QString::number(field));
}
template<> void XmlSetter::visit (void *& field, const PointerField * fieldDescriptor)
template<> void XmlSetter::visit (double & field, const DoubleField * fieldDescriptor)
Definition at line 70 of file xmlSetter.cpp.
{
    saveValue(fieldDescriptor->name.name, QString::number(field));
}
template<> void XmlSetter::visit (int & field, const EnumField * fieldDescriptor)
template<> void XmlSetter::visit (float & field, const FloatField * fieldDescriptor)
Definition at line 76 of file xmlSetter.cpp.
{
    saveValue(fieldDescriptor->name.name, QString::number(field));
}
template<> void XmlSetter::visit (bool & field, const BoolField * fieldDescriptor)
Definition at line 82 of file xmlSetter.cpp.
{
    saveValue(fieldDescriptor->name.name, field ? "true" : "false");
}
template<> void XmlSetter::visit (void *& , const PointerField *)
Definition at line 94 of file xmlSetter.cpp.
{
}
template<> void XmlSetter::visit (int & field, const EnumField * fieldDescriptor)
Definition at line 100 of file xmlSetter.cpp.
{
    saveValue(fieldDescriptor->name.name, QString::number(field));
}
Member Data Documentation
template<typename T> T std::deque< T >::elements [inherited]
STL member.
QString XmlSetter::mFileName [private]
Definition at line 37 of file xmlSetter.h.
Referenced by saveValue(), and XmlSetter().
string corecvs::BasePathVisitor::separator [inherited]
Definition at line 26 of file basePathVisitor.h.
Referenced by corecvs::BasePathVisitor::getChildPath().
string corecvs::BasePathVisitor::SEPARATOR_DEFAULT = "." [static, inherited]
Definition at line 24 of file basePathVisitor.h.
The documentation for this class was generated from the following files:
utils/visitors/xmlSetter.h
utils/visitors/xmlSetter.cpp