DeepView: core/clegacy/math/matrix.h File Reference
core/clegacy/math/matrix.h File Reference
Classes
struct Matrix_TAG
This structure holds the arbitrary size dense matrix.
Defines
#define ELEM(M, i, j) ((M)->data[(i) * (M)->n + (j)])
This macro is used for fast matrix access.
#define VECELEM(V, i) ((V)->data[i])
This macro is used for fast vector access.
Typedefs
typedef struct Matrix_TAG Matrix
This structure holds the arbitrary size dense matrix.
Functions
Matrix * matrixCreate (int n, int m)
This function creates a matrix with all zero elements.
Matrix * matrixCreateFromRaw (int m, int n, double *raw)
This function creates a matrix filling it with values form the given array line by line.
void matrixDelete (Matrix *toDelete)
This function deletes a matrix.
void matrixAdd (Matrix *A, Matrix *B, Matrix *result)
void matrixSubstract (Matrix *A, Matrix *B, Matrix *result)
void matrixPrint (Matrix *A)
void matrixMultiply (Matrix *A, Matrix *B, Matrix *result)
Multiplies the two matrices.
Matrix * matrixMultiplyNew (Matrix *A, Matrix *B)
Multiplies the two matrices and return it's product.
void matrixCopy (Matrix *A, Matrix *B)
Copies the matrix The destanation have to be prepared.
Matrix * matrixCopyNew (Matrix *A)
Clones the matrix The destanation have to be prepared.
void matrixTranspose (Matrix *A, Matrix *B)
Transpose the matrix.
Matrix * matrixTransposeNew (Matrix *A)
Transpose the matrix.
void matrixFillIdentity (Matrix *A)
This function fills a square with identity matrix.
int matrixSolveGaussian (Matrix *A, Matrix *B)
Solves the linear equation.
Matrix * matrixSolve (Matrix *A, Matrix *B)
Define Documentation
#define ELEM (M, i, j) ((M)->data[(i) * (M)->n + (j)])
This macro is used for fast matrix access.
Definition at line 29 of file matrix.h.
Referenced by corecvs::LevenMarq::createMatrix(), corecvs::LevenMarq::doLevMarFit(), doLMFit(), matrixAdd(), matrixMultiply(), matrixSubstract(), and matrixTranspose().
#define VECELEM (V, i) ((V)->data[i])
This macro is used for fast vector access.
Definition at line 32 of file matrix.h.
Typedef Documentation
typedef struct Matrix_TAG Matrix
This structure holds the arbitrary size dense matrix.
Function Documentation
void matrixAdd (Matrix * A, Matrix * B, Matrix * result)
Definition at line 108 of file matrix.c.
References ASSERT_FAIL, ELEM, Matrix_TAG::m, and Matrix_TAG::n.
{
#ifdef ASSERTS
        // Assert that the matrix has same sizes
        if (A->n != B->n || A->n != result->n || A->m != B->m || B->m != result->m)
                ASSERT_FAIL("Matrices have wrong sizes");
#endif
        int row, column;
        for (row = 0; row < A->m; row ++)
        {
                for (column = 0; column < A->n; column++)
                {
                        ELEM(result, row, column) = ELEM(A, row, column) + ELEM(B, row, column);
                }
        }
}
void matrixCopy (Matrix * A, Matrix * B)
Copies the matrix The destanation have to be prepared.
Parameters:
A a matrix to clone
B a matrix to put clone to.
Definition at line 192 of file matrix.c.
References ASSERT_FAIL, Matrix_TAG::data, Matrix_TAG::m, and Matrix_TAG::n.
Referenced by corecvs::LevenMarq::doLevMarFit(), doLMFit(), and matrixCopyNew().
{
#ifdef ASSERTS
        // Assert that the matrices are same size
        if (A->n != B->n || A->m != B->m)
                ASSERT_FAIL("Matrices have wrong sizes");
#endif
        memcpy(B->data, A->data, sizeof (double) * A->m * A->n);
}
Matrix* matrixCopyNew (Matrix * A)
Clones the matrix The destanation have to be prepared.
Parameters:
A a matrix to clone
Returns:
a matrix to put clone to.
Definition at line 209 of file matrix.c.
References Matrix_TAG::m, matrixCopy(), matrixCreate(), and Matrix_TAG::n.
{
        Matrix *toReturn = matrixCreate(A->m, A->n);
        matrixCopy(A, toReturn);
        return toReturn;
}
Matrix* matrixCreate (int m, int n)
This function creates a matrix with all zero elements.
Parameters:
m the height of the matrix
n the width of the matrix
Definition at line 30 of file matrix.c.
References Matrix_TAG::data, dv_calloc, dv_malloc, Matrix_TAG::m, and Matrix_TAG::n.
Referenced by corecvs::LevenMarq::createMatrix(), corecvs::LevenMarq::doLevMarFit(), doLMFit(), matrixCopyNew(), matrixMultiplyNew(), matrixSolve(), and matrixTransposeNew().
{
        Matrix *toReturn = (Matrix  *) dv_malloc (sizeof (Matrix));
        toReturn->m = m;
        toReturn->n = n;
        toReturn->data = (double *) dv_calloc(n * m , sizeof(double));
        return toReturn;
}
Matrix* matrixCreateFromRaw (int m, int n, double * raw)
This function creates a matrix filling it with values form the given array line by line.
Parameters:
m the height of the matrix
n the width of the matrix
raw the line by line raw values of the matrix
Definition at line 48 of file matrix.c.
References Matrix_TAG::data, dv_malloc, Matrix_TAG::m, and Matrix_TAG::n.
{
        Matrix *toReturn = (Matrix  *) dv_malloc (sizeof (Matrix));
        toReturn->m = m;
        toReturn->n = n;
        toReturn->data = (double *) dv_malloc(n * m * sizeof(double));
        memcpy(toReturn->data, raw, n * m * sizeof(double));
        return toReturn;
}
void matrixDelete (Matrix * toDelete)
This function deletes a matrix.
And free the memory allocated for it.
NB! Matrix should not be used in any way after being deleted
Parameters:
toDelete a matrix to be disposed.
Definition at line 66 of file matrix.c.
References Matrix_TAG::data, and dv_free.
{
        if (toDelete->data != NULL)
                dv_free(toDelete->data);
        dv_free(toDelete);
}
void matrixFillIdentity (Matrix * A)
This function fills a square with identity matrix.
Definition at line 77 of file matrix.c.
References ASSERT_FAIL, Matrix_TAG::data, Matrix_TAG::m, and Matrix_TAG::n.
{
#ifdef ASSERTS
        // Assert that the matrix is square
        if (A->m != A->n)
                ASSERT_FAIL("Matrix is not square");
#endif
        int row, column;
        for (row = 0; row < A->m; row ++)
        {
                for (column = 0; column < A->n; column++)
                {
                        A->data[row * A->n + column] = (row == column) ? 1.0 : 0.0;
                }
        }
}
void matrixMultiply (Matrix * A, Matrix * B, Matrix * result)
Multiplies the two matrices.
Definition at line 148 of file matrix.c.
References ASSERT_FAIL, Matrix_TAG::data, ELEM, Matrix_TAG::m, and Matrix_TAG::n.
Referenced by corecvs::LevenMarq::doLevMarFit(), doLMFit(), and matrixMultiplyNew().
{
#ifdef ASSERTS
        // Assert that the matrix is square
        if (A->n != B->m || A->m != result->m || B->n != result->n)
                ASSERT_FAIL("Matrices have wrong sizes");
#endif
        int row, column, runner;
        for (row = 0; row < result->m ; row++)
                for (column = 0; column < result->n ; column++)
                {
                double sum = 0;
                for (runner = 0; runner < A->n; runner++)
                {
                        sum += ELEM(A, row, runner) * ELEM (B, runner, column);
                }
                result->data[row * result->n  + column] = sum;
        }
}
Matrix* matrixMultiplyNew (Matrix * A, Matrix * B)
Multiplies the two matrices and return it's product.
NB!! Do not forget to delete the product with matrixDelete()
Parameters:
A a matrix to multiply
B a matrix to multiply by
Returns:
a new matrix with the multiplication result
Definition at line 178 of file matrix.c.
References Matrix_TAG::m, matrixCreate(), matrixMultiply(), and Matrix_TAG::n.
{
        Matrix *toReturn = matrixCreate(A->m, B->n);
        matrixMultiply(A, B, toReturn);
        return toReturn;
}
void matrixPrint (Matrix * A)
Definition at line 94 of file matrix.c.
References Matrix_TAG::data, Matrix_TAG::m, and Matrix_TAG::n.
{
        int row, column;
        for (row = 0; row < A->m; row ++)
        {
                printf("[");
                for (column = 0; column < A->n; column++)
                {
                        printf(" %lf", A->data[row * A->n + column]);
                }
                printf("]\n");
        }
}
Matrix* matrixSolve (Matrix * A, Matrix * B)
Definition at line 320 of file matrix.c.
References ASSERT_FAIL, Matrix_TAG::data, Matrix_TAG::m, matrixCreate(), and Matrix_TAG::n.
{
        if (A->m != A->n || A->n != B->m || B->n != 1)
                ASSERT_FAIL("Matrix has wrong sizes");
        int n = A->m;
        int i, j, k;
        for (i = 0; i < n - 1; i++)
        {
                for (j = i + 1; j < n; j++)
                {
                        double value = A->data[n * j + i];
                        for (k = i; k < n; k++)
{
                                A->data[j * n + k] = A->data[j * n + k] - A->data[i * n + k] * value
                                                                         / A->data[i * n + i];
                        }
                        B->data[j] -= B->data[i] * value / A->data[i * n + i];
                }
        }
        Matrix * solution = matrixCreate(n, 1);
        solution->data[n - 1] = B->data[n - 1] / A->data[n * n - 1];
        for (i = n - 2; i >= 0; i--)
        {
                solution->data[i] = B->data[i];
                for (j = i + 1; j < n; j++)
                {
                        solution->data[i] -= A->data[i * n + j] * solution->data[j];
                }
                solution->data[i] = solution->data[i] / A->data[i * n + i];
        }
        return solution;
}
int matrixSolveGaussian (Matrix * A, Matrix * B)
Solves the linear equation.
Definition at line 252 of file matrix.c.
References ASSERT_FAIL, Matrix_TAG::data, Matrix_TAG::m, and Matrix_TAG::n.
Referenced by corecvs::LevenMarq::doLevMarFit(), and doLMFit().
{
#ifdef ASSERTS
        // Assert that the matrix is square and the second matrix is a vector
        if (A->m != A->n || A->n != B->m || B->n != 1)
                ASSERT_FAIL("Matrix has wrong sizes");
#endif
        int row, column, rowRunner, runner;
        int n = A->m;
        // Walk thought the matrix from left to right
        for (column = 0; column < n; column++)
        {
                int rowWithMax = -1;
                double maxInColumn = 0;
                for (row = 0; row < n; row ++)
                {
                        double absA = fabs (A->data[row * n + column]);
                        if (absA > maxInColumn)
{
                                maxInColumn = absA;
                                rowWithMax = row;
                        }
                }
                if (rowWithMax == -1) {
                        if (B->data[column] != 0)
                                return 1;
                        for (rowRunner = 0; rowRunner < n; rowRunner++)
                                if (A->data[column * n + rowRunner] != 0)
                                        return 1;
                }
                // Now we will work with the row of the same number as the column
                row = column;
                // Now put the row to the i-th position by interchange
                if (rowWithMax != row)
                {
                        double tmp;
                        for (rowRunner = column; rowRunner < n; rowRunner ++)
{
                                tmp = A->data[row * n + rowRunner];
                                A->data[row * n + rowRunner] = A->data[rowWithMax * n + rowRunner];
                                A->data[rowWithMax * n + rowRunner] = tmp;
                        }
                        tmp = B->data[row];
                        B->data[row] = B->data[rowWithMax];
                        B->data[rowWithMax] = tmp;
                }
                // And now do the correction of all the rows
                // First divide all the row by the value of (column, row)
                double a = A->data[row * n + column];
                double ia = 1 / a;
                for (rowRunner = column; rowRunner < n; rowRunner ++)
                        A->data[row *n + rowRunner] *= ia;
                B->data[row] *= ia;
                for (runner = 0; runner < n; runner++)
                        if (runner != row) {
                        double d = A->data[runner * n + column];
                        for (rowRunner = column; rowRunner < n; rowRunner++)
                                A->data[runner * n + rowRunner] -= A->data[row * n + rowRunner] * d;
                        B->data[runner] -= B->data[row] * d;
                }
        }
        return 0;
}
void matrixSubstract (Matrix * A, Matrix * B, Matrix * result)
Definition at line 126 of file matrix.c.
References ASSERT_FAIL, ELEM, Matrix_TAG::m, and Matrix_TAG::n.
{
#ifdef ASSERTS
        // Assert that the matrix has same sizes
        if (A->n != B->n || A->n != result->n || A->m != B->m || B->m != result->m)
                ASSERT_FAIL("Matrices have wrong sizes");
#endif
        int row, column;
        for (row = 0; row < A->m; row ++)
        {
                for (column = 0; column < A->n; column++)
                {
                        ELEM(result, row, column) = ELEM(A, row, column) - ELEM(B, row, column);
                }
        }
}
void matrixTranspose (Matrix * A, Matrix * B)
Transpose the matrix.
The transposition will be put to already existing matrix
Definition at line 220 of file matrix.c.
References ASSERT_FAIL, ELEM, Matrix_TAG::m, and Matrix_TAG::n.
Referenced by corecvs::LevenMarq::doLevMarFit(), doLMFit(), and matrixTransposeNew().
{
#ifdef ASSERTS
        // Assert that the matrices have good sizes
        if (A->n != B->m || A->m != B->n)
                ASSERT_FAIL("Matrices have wrong sizes to transpose");
#endif
        int row, column;
        for (row = 0; row < B->m ; row++)
                for (column = 0; column < B->n ; column++)
                {
                double value = ELEM(A, column, row);
                ELEM(B, row, column) = value;
        }
}
Matrix* matrixTransposeNew (Matrix * A)
Transpose the matrix.
Definition at line 240 of file matrix.c.
References Matrix_TAG::m, matrixCreate(), matrixTranspose(), and Matrix_TAG::n.
{
        Matrix *toReturn = matrixCreate(A->n, A->m);
        matrixTranspose(A, toReturn);
        return toReturn;
}