DeepView: core/clegacy/math/geometry.c File Reference
core/clegacy/math/geometry.c File Reference
implementation of some geometrical functions
#include <math.h>
#include <stdio.h>
#include "global.h"
#include "geometry.h"
Functions
vector3Dd crossProduct (vector3Dd *a, vector3Dd *b)
This function implements the vector cross product.
double dotProduct (vector3Dd *a, vector3Dd *b)
This function implements the vector dot product.
void vectorNormalize (vector3Dd *a)
This function normalizes the 3d vector It is computed as follows:
void vectorHomogeniousNormalize (vector3Dd *a)
void vectorPrint (vector3Dd *v)
This function prints the vector to stdout.
vector3Dd vector3DdCreate (double x, double y, double z)
vector2Dd vector2DdCreate (double x, double y)
void vector2DdIncrement (vector2Dd *a, vector2Dd *b)
double vector2DdLength (vector2Dd *a)
vector3Dd vector3DdAdd (vector3Dd a, vector3Dd b)
vector3Dd vectorMultiplyConst (vector3Dd a, double b)
void vector2Dswap (vector2Dd *p1, vector2Dd *p2)
TriangleIterator triangleIteratorCreate (vector2Dd p1, vector2Dd p2, vector2Dd p3)
int triangleIteratorNext (TriangleIterator *iterator, vector2Ds32 *pos)
Detailed Description
implementation of some geometrical functions
Date:
Apr 20, 2009
Author:
Alexander Pimenov
part of the code comes form wikipedia
Definition in file geometry.c.
Function Documentation
vector3Dd crossProduct (vector3Dd * a, vector3Dd * b)
This function implements the vector cross product.
It is computed as follows:
  [  i   j   k  ]
  [ a.x a.y a.z ]
  [ b.x b.y b.z ]
Parameters:
[in] a the first vector
[in] b the second vector
Returns:
vector a x b
Definition at line 33 of file geometry.c.
References corecvs::vector3Dd_tag::x.
{
        vector3Dd toReturn;
        toReturn.x = + a->y * b->z - a->z * b->y;
        toReturn.y = - a->x * b->z + a->z * b->x;
        toReturn.z = + a->x * b->y - a->y * b->x;
        return toReturn;
}
double dotProduct (vector3Dd * a, vector3Dd * b)
This function implements the vector dot product.
It is computed as follows:
Parameters:
[in] a the first vector
[in] b the second vector
Returns:
vector a . b
Definition at line 56 of file geometry.c.
{
        return a->x * b->x + a->y * b->y + a->z * b->z;
}
TriangleIterator triangleIteratorCreate (vector2Dd p1, vector2Dd p2, vector2Dd p3)
Definition at line 144 of file geometry.c.
References corecvs::TriangleIterator_TAG::p1, vector2Dswap(), and corecvs::vector2Dd_tag::y.
{
        /* Sort points in ascending order by y*/
        if (p1.y > p2.y)
                vector2Dswap(&p1,&p2);
        if (p1.y > p3.y)
                vector2Dswap(&p1,&p3);
        if (p2.y > p3.y)
                vector2Dswap(&p2,&p3);
        TriangleIterator toReturn;
        toReturn.p1 = p1;
        toReturn.p2 = p2;
        toReturn.p3 = p3;
        toReturn.y = ceil(toReturn.p1.y) - 1;
        toReturn.lpos = 0;
        toReturn.rpos = 0;
        toReturn.x = 1;
        return toReturn;
}
int triangleIteratorNext (TriangleIterator * iterator, vector2Ds32 * pos)
Definition at line 168 of file geometry.c.
{
        iterator->x++;
        while (1)
        {
                /* Go throw the horizontal line*/
                if (iterator->x <= iterator->rpos)
                {
                        pos->x = iterator->x;
                        pos->y = iterator->y;
                        return 1;
                }
                iterator->y++;
                /*We could be in the lower or on the upper part of the triangle*/
                if (iterator->y <= iterator->p2.y)
                {
                        if (iterator->p2.y == iterator->p1.y)
{
                                iterator->lpos = iterator->p1.x;
                                iterator->rpos = iterator->p2.x;
                        } else
{
                                double delta = iterator->y - iterator->p1.y;
                                iterator->lpos = iterator->p1.x + (iterator->p2.x - iterator->p1.x) / (iterator->p2.y - iterator->p1.y) * delta;
                                iterator->rpos = iterator->p1.x + (iterator->p3.x - iterator->p1.x) / (iterator->p3.y - iterator->p1.y) * delta;
                        }
                } else {
                        if (iterator->y > iterator->p3.y)
{
                                /* We finished */
                                return 0;
                        }
                        if (iterator->p2.y == iterator->p3.y)
{
                                iterator->lpos = iterator->p2.x;
                                iterator->rpos = iterator->p3.x;
                        } else
{
                                double delta = iterator->p3.y - iterator->y;
                                iterator->lpos = iterator->p3.x + (iterator->p2.x - iterator->p3.x) / (iterator->p3.y - iterator->p2.y) * delta;
                                iterator->rpos = iterator->p3.x + (iterator->p1.x - iterator->p3.x) / (iterator->p3.y - iterator->p1.y) * delta;
                        }
                }
                if (iterator->lpos > iterator->rpos)
                {
                        double tmp = iterator->lpos;
                        iterator->lpos = iterator->rpos;
                        iterator->rpos = tmp;
                }
                iterator->x = ceil(iterator->lpos);
        }
}
vector2Dd vector2DdCreate (double x, double y)
Definition at line 107 of file geometry.c.
Referenced by correctLens().
{
        vector2Dd toReturn = {x, y};
        return toReturn;
}
void vector2DdIncrement (vector2Dd * a, vector2Dd * b)
Definition at line 113 of file geometry.c.
{
        a->x += b->x;
        a->y += b->y;
}
double vector2DdLength (vector2Dd * a)
Definition at line 119 of file geometry.c.
{
        return sqrt(a->x * a->x + a->y * a->y);
}
void vector2Dswap (vector2Dd * p1, vector2Dd * p2)
Definition at line 136 of file geometry.c.
Referenced by triangleIteratorCreate().
{
        vector2Dd tmp;
        tmp = *p1;
        *p1 = *p2;
        *p2 = tmp;
}
vector3Dd vector3DdAdd (vector3Dd a, vector3Dd b)
Definition at line 124 of file geometry.c.
References corecvs::vector3Dd_tag::x.
{
        vector3Dd toReturn = {a.x + b.x , a.y + b.y , a.z + b.z };
        return toReturn;
}
vector3Dd vector3DdCreate (double x, double y, double z)
Definition at line 101 of file geometry.c.
{
        vector3Dd toReturn = {x,y,z};
        return toReturn;
}
void vectorHomogeniousNormalize (vector3Dd * a)
Definition at line 82 of file geometry.c.
{
        if (a->z == 0)
                return;
        a->x /= a->z;
        a->y /= a->z;
        a->z = 1;
}
vector3Dd vectorMultiplyConst (vector3Dd a, double b)
Definition at line 130 of file geometry.c.
References corecvs::vector3Dd_tag::x.
{
        vector3Dd toReturn = {a.x * b, a.y * b, a.z * b};
        return toReturn;
}
void vectorNormalize (vector3Dd * a)
This function normalizes the 3d vector It is computed as follows:
Parameters:
[in,out] a the vector to normalize
Definition at line 71 of file geometry.c.
{
        double normSquare = a->x * a->x + a->y * a->y  + a->z * a->z;
        if (normSquare == 0)
                return;
        double norm = sqrt(normSquare);
        a->x /= norm;
        a->y /= norm;
        a->z /= norm;
}
void vectorPrint (vector3Dd * v)
This function prints the vector to stdout.
Parameters:
[in] v vector to print
Definition at line 96 of file geometry.c.
{
        printf("[%lg : %lg : %lg ]\n", v->x, v->y, v->z);
}