DeepView: corecvs Namespace Reference
corecvs Namespace Reference
Design is heavily based on http://glorfindel.mavrinac.com/~aaron/school/pdf/prescott97_linelens.pdf.
Classes
class AngleFunction
class AnglePointsFunction
This class describes the cost function that shows how a set of lines differ from the model.
class CamerasCalibrationFunc
class CurvatureFunc
class DistortionCorrectTransform
class DistPointsFunction
This class describes the cost function that shows how a set of lines differ from the model.
class LensCorrectionParametres
This structure holds the parameters to correct the image.
class RadialCorrection
class ModelToRadialCorrection
class RadialFunc
function to optimize
class StraightFunc
class FCostFunction
class FlowVectorInformation
class FlowSimuator
class AdaBoostInputData
Input data element of the training set for AdaBoost.
class AdaBoostInput
This template will hold the whole vector of inputs.
class ClassifierStatistics
The statistical result of the classifier.
class Classifier
class AdaBoostedClassifier
This class contains the boosted classifier.
class WeakHypothesisGenerator
This class describes the weak hypothesis generator.
class AdaBoost
Template for generic AdaBoost algorithm.
class CascadeClassifier
class DetectedObject
class ParallelGetBestClassifier
class VJInputImage
The data that is needed for fast classification.
class PatternCorner
A part of the pattern.
class VJPattern
Viola-Jones generic Haar wavelet.
class VJSimpleClassifier
class VJPatternGenerator
Base class for pattern generator.
class HorizontalPattern2
HorizontalPattern2.
class HorizontalPattern3
HorizontalPattern3.
class VerticalPattern2
VerticalPattern2.
class VerticalPattern3
VerticalPattern3.
class SquarePattern2
SquarePattern2.
class VJResult
AnyPattern2.
class VJSimpleClassifierGenerator
class VJAdaBoostedClassifier
class GenericMap
This class holds the mapping function that is applied to the buffer element to get another buffer element.
class BufferMap
class DeformMap
This class holds the mapping function from coordinate domain to the other coordinate domain.
class AbstractBufferParams
This is a basis part of the AbstractBuffer template - serializable buffer params.
class AbstractBuffer
This is a common buffer template.
class AbstractContiniousBuffer
This template class describes a buffer for which it is possible to interpolate the result between cells.
class AbstractKernel
Template class that holds the convolution kernel.
class BooleanBuffer
class Buffer3d
class BufferFactory
Singleton for buffer loading.
class GainOffsetMapper
class ShiftMaskMapper
class IntervalMapper
class YUYVtoG12
class YUYVtoG12G12
class ColorConverters
class DerivativeBuffer
class DisparityBuffer
class DisplacementBuffer
This buffer stores a buffer deformation - a shift of the buffer pixels.
class DirectRemapper
TODO: rewrite this based on AbstractBuffer This class caches the image transformation.
struct BilinearMapPoint
This function holds the data for fast bilinear transform computation.
class FixedPointDisplace
class DepthBuffer
class Element6D
This class holds fully or partially reconstructed 6D point at disparity level.
class FloatFlow
class FloatFlowBuffer
class FlowBuffer
This is actually a version of Displacement Buffer.
class FloatFlowVector
class PunchedBufferOperations
class SixDBuffer
6D buffer that hold all the information extracted form the images
class ConverterYUYV2G12
class G12Buffer
TODO: Add consts where it should go.
class G12Buffer3d
class G8Buffer
class Histogram
Histogram class.
class IntegralBuffer
So each element of the integral buffer will hold the sum of the elements in a rectangle.
class G12IntegralBuffer
class G8IntegralBuffer
class Splain3Interpolator
class BilinearInterpolator
class PolynomInterpolator
class BinaryElementwiseOperation
A FastKernels class that has common code for binary operations.
class SumBuffers
class MixBuffers
class SubtractBuffers
class DifferenceBuffers
class ParallelPrepareBlurBuffers
class BlurProcessor
class CopyKernel
class DummyReader
class DummyWriter
class BufferConverter
This is a main template that provides fast processing of buffers It uses two approaches - an algebra and a fallback algebra.
class DummyAlgebra
This class does nothing.
class BaseAlgebraMulti
This class describes the basic operations and function prototypes to work with input and output buffers.
class BaseKernel
A base class for FastKernel kernels.
class BufferProcessor
This is a main template that provides fast processing of buffers It uses two approaches - an algebra and a fallback algebra.
class ScalarAlgebraMulti
ScalarAlgebraMulti is a crucial part of fastKernels.
class TraitGeneric
class TraitG12Buffer
class TraitG8Buffer
class G12BufferAlgebraScalar
class G12BufferAlgebra
class G8BufferAlgebra
class ScalarAlgebraUInt16_t
class ScalarAlgebraInt16_t
class ScalarAlgebraDouble
class ScalarAlgebraFloat
class Gaussian3x3
class Gaussian3x3int
class Gaussian3x3Kernel
class Blur5
Computes (a + b * 2 + c * 4 + d * 2 + e) / 10.
class Blur5Horisontal
class Blur5Vertical
class GenericFastKernel
class LogicKernels
class LogicAnd
class LogicOr
class LogicXor
class LogicSubt
class SobelVertInt
Old style (AbstractKernel style) Kernel for Vertical Sobel operator for integer buffers.
class SobelHorInt
Old style (AbstractKernel style) Kernel for Horizontal Sobel operator for integer buffers.
class SobelHorizontalKernel
Cool new style (FastKernels) Horizontal Sobel filter.
class SobelVerticalKernel
Cool new style (FastKernels) Vertical Sobel filter.
class EdgeMagnitude
class ScalarAlgebraVector33
class SpatialGradient
This class holds the spatial gradient matrix square elements.
class ThresholdBinariseKernel
class ObjectBlock
This class is a class that holds a memory block with it's reference count.
class ObjectRef
This class is an smart pointer to the memory block.
class ScopedRef
Temporary solution for scoped pointer.
class AbstractMipmapPyramid
Template class that holds the pyramid of the reduced size buffers.
class Morphological
This class holds morpological transformations
.
class ErodeKernel
class DilateKernel
class AbstractPainter
class HardcodeFont
class HersheyVectorFont
This class contains vector font from here - http://paulbourke.net/dataformats/hershey/ License is public domain, so we will use it.
class RGB24Buffer
class RGBColor
I use inheritance because no new data members will be added.
class TransformationCache
This class is caching the transformation of the buffer.
class SlicedSpace
class VoxelBufferBase
class CameraIntrinsics
This class describes the parameters of the ideal pin-hole camera TODO: Should be a child of a DeformMap or something similar.
class EnergyBuffer
class ImagerState
class ContolInput
class ImagerControl
class ImagerProperties
class GenericRadiusDeformer
class SphericalCorrection
class RadiusCorrectionLUT
class SphericalCorrectionLUT
struct vector2Ds16_tag
struct vector2Ds32_tag
struct vector2Du16_tag
struct vector2Dd_tag
struct vector3D_tag
struct vector3Dd_tag
struct TriangleIterator_TAG
This class implements the triangle iterator that iterates over all the integer points in the triangle.
class LevenMarq
class Cloud
class CloudCluster
struct CloudClusterSort
class Clustering3D
class SwarmPoint
struct SortSwarmPointX
struct SortSwarmPointY
struct SortSwarmPointZ
struct SortSwarmPointTexY
struct SortSwarmPointTexX
class BMPHeader
class BMPLoader
class BufferLoader
Common interface for loaders for the particular format.
class PPMLoader
class RAWLoader
class AbstractFilter
class BackgroundFilter
class BinarizeBlock
class BitSelectorFilter
class CompoundFilter
class FilterBlock
class FilterGraph
class Pin
class G12Pin
class TxtPin
class InputPin
class OutputPin
class ExtraG12Pin
class ExtraTxtPin
class CannyFilter
class FiltersCollection
class GainOffsetFilter
class InputFilter
class MaskFilterBlock
class OperationFilter
class OutputFilter
class SobelFilter
class ThickeningBlock
class TxtFilter
class FunctionArgs
This class is a virtual version of a .
class IdentityFunction
class ScalerFunction
class Map2DFunction
class LengthFunction
class FunctionStatic
class EllipticalApproximation
This class searches the ellipse that looks like a given blob.
class EllipticalApproximationUnified
class Segment
Line segment based on 2 points.
class BaseRay
Ray2d is a template of the class that holds the description of the ray in the space.
class Ray2d
Ray2d is 2D version of Ray.
class Ray3d
Ray2d is 3D version of Ray.
class Line2d
This class represents the line in 2D space.
class Plane3d
class AxisAlignedBox3d
class Mesh3D
class GenericTriangle
class PointPath
class Poligon
class Rectangle
class Cholesky
Class that implements Cholesky decomposition.
class ClassicKalman
TODO: Could be nice to make this template.
class COOSparseMatrix
COOSparseMatrix is efficient matrix made in Matlab style - http://en.wikipedia.org/wiki/Sparse_matrix#Coordinate_list_.28COO.29.
class UDUTDecomposed
class UpperUnitaryMatrix
This class holds the upper part of the triangular unitary matrix.
class KLTCalculationContext
class KLTGenerator
class Affine3D
Template class that holds the affine transformation of the space in form of rotational/shear part and shift part.
class Int16x16
class EulerAngles
Inside the project angles are in radians.
class CameraAngles
As rotation depends on the order of application of the rotations of Euler angles this class specifies one of possible orders that will be used for camera rotation description.
class ShiftRotateTransformation
This should be merged with Affine class.
class FixedPoint24p8
class GenericMath
Some functions are not expressed with binary operators, so we need to add functions as static functions.
class GradientDescent
class GradientDescentRnToRm
This class implements a solver that uses Gradient descent for functions .
class RosenbrockFunction
http://en.wikipedia.org/wiki/Rosenbrock_function
class LevenbergMarquardt
class SpeedupFunction
class SqrtFunction
class LUTable
Almost POCO.
class LUTGenerator
class DiagonalMatrix
This class stores square diagonal matrix.
class HomographyReconstructor
class Matrix
class Matrix33
Class describes the 3 by 3 matrix.
class Matrix44
This class is mostly for representing Projectrive Transformations in 3D.
class MatrixOperationsBase
class Float32x4
class Int16x8
class Int32x4
class Int32x8
class Int64x2
class SSEMath
This class provides the base functions for SSE (and probably NEON) this creates common interface for SSE and ordinary integer types.
class ProjectiveTransform
Projective transform is a wrapper around Matrix33 class that allows to implement the projective deformation of the Abstract Continuous Buffer.
class PuzzleBlock
class GenericQuaternion
class Int8x16
class IntBase16x8
This class is a wrapper around data type that stores 8 16bit integers in 128 register.
class IntBase8x16
class SSEInteger
This template class holds the base class for integer sse types.
class UInt16x8
class UInt8x16
class FixedArrayBase
class FixedArray
class FixedVectorBase
This class is a template for a vector of the fixed length.
class FixedVector
class Vector2d
class Vector3d
class VectorOperationsBase
class AbstractMeanShiftKernel
class MeanShiftCalculator
class MeanShiftWindow
class CFlowBufferToucherOperator
class PrimitiveCorrespondance
class CorrespondanceList
class DerivedCorrespondanceList
DerivedCorrespondanceList is a wrapper around CorrespondanceList that allows to modify the contense, yet remembering the pointer to the origin.
class EssentialEstimator
class EssentialDecomposition
This class stores the relative position of first and second camera.
class EssentialMatrix
Both essential and fundamental matrices hold the following property:
class IterativeEstimator
class Ransac
This template class is used to implement classic RANSAC algorithm is a generic form.
class Model8Point
class ModelFundamental8Point
class ModelEssential8Point
class RansacEstimator
class StereoTransformation
class StereoAligner
class ParallelTriangulate
class RectificationResult
This class contains all the output information about rectification process.
class Triangulator
Swarm point is a class that holds the information about single point in space Associated with color and etc.
class DefaultSetter
class DeserializerVisitor
class PrinterVisitor
class ReflectionNaming
We have several styles of nameing.
class BaseField
This class is a core class for the reflection.
class SimpleScalarField
This is a simple scalar field.
class StringField
class EmbedSubclass
class Reflection
class CompositeField
class EnumOption
class EnumReflection
class EnumField
class PointerField
struct ReflectionHelper
Now traits that allow getting reflection from basic type.
struct ReflectionHelper< int >
struct ReflectionHelper< double >
struct ReflectionHelper< float >
struct ReflectionHelper< int64_t >
struct ReflectionHelper< bool >
struct ReflectionHelper< std::string >
struct ReflectionHelper< void * >
class BaseReflectionStatic
class BaseReflection
This is a common parent for a reflection enabled class basically it just transforms dynamic Reflection class into static field.
class SerializerVisitor
class BaseSegment
This is a generic class that desribes the part of the whole connected component.
class Segmentator
This class implements a generic approach to the segmentation - Connected Component Labeling Base problem statement can be seen here.
class CornerSegment
class CornerSegmentator
class ClusteringTile
class SegmentParameters
class SegmentPayload
For information on moments see http://en.wikipedia.org/wiki/Image_moment.
class TileSegment
class TileSegmentator
class TileGrid
class Serializer
class Serializable
class PropertyListSerializer
struct SingleStat
struct UnitedStat
class Statistics
class BaseTimeStatisticsCollector
class BlockedRange
class PreciseTimer
class PreciseTimerEx
class PropertyList
class binary
This is a helper meta-programming template to represent binary constants.
class binary< 0 >
class BasePathVisitor
Base class for visitors that iterate over the hierarchy of types.
class PropertyListWriterVisitor
Visitor that serializes the type hierarchy into the PropertyList - the internal human readable format for CVS core.
class PropertyListReaderVisitor
Visitor that de-serializes the type hierarchy from the PropertyList - the internal human readable format for CVS core.
class FilterExecuter
class DecoupleYUYV
Typedefs
typedef
AbstractContiniousBuffer
< uint8_t, int32_t > BooleanBufferBase
typedef
AbstractContiniousBuffer
< SwarmPoint *, int32_t > Buffer3dBase
typedef AbstractBuffer
< Vector2d< int16_t > > DerivativeBufferBase
typedef uint16_t DisparityElement
typedef
AbstractContiniousBuffer
< DisparityElement, int32_t > DisparityBufferBase
typedef
AbstractContiniousBuffer
< Vector2dd, int32_t > DisplacementBufferBase
typedef
AbstractContiniousBuffer
< BilinearMapPoint, int32_t > FixedPointDisplaceBase
typedef
AbstractContiniousBuffer
< double, int32_t > DepthBufferBase
typedef
AbstractContiniousBuffer
< FloatFlow, int32_t > FloatFlowBufferBase
typedef Vector2d16 FlowElement
typedef
AbstractContiniousBuffer
< FlowElement, int32_t > FlowBufferBase
typedef FlowBuffer DisparityBuffer
typedef
AbstractContiniousBuffer
< Element6D, int32_t > SixDBufferBase
typedef
AbstractContiniousBuffer
< uint16_t, int32_t > G12BufferBase
typedef
AbstractContiniousBuffer
< SwarmPoint *, int32_t > G12Buffer3dBase
typedef
AbstractContiniousBuffer
< uint8_t, int32_t > G8BufferBase
typedef IntegralBuffer
< Vector3dd, Vector3dd,
uint32_t > SpatialGradientIntegralBuffer
typedef ObjectBlock< uint8_t > MemoryBlock
typedef ObjectRef< uint8_t > MemoryBlockRef
typedef
AbstractContiniousBuffer
< RGBColor, int32_t > CRGB24BufferBase
typedef uint16_t fixed8in16
typedef uint32_t fixed16in32
typedef struct
corecvs::vector2Ds16_tag vector2Ds16
typedef struct
corecvs::vector2Ds32_tag vector2Ds32
typedef struct
corecvs::vector2Du16_tag vector2Du16
typedef struct
corecvs::vector2Dd_tag vector2Dd
typedef struct
corecvs::vector3D_tag vector3D
typedef struct
corecvs::vector3Dd_tag vector3Dd
typedef struct
corecvs::TriangleIterator_TAG TriangleIterator
This class implements the triangle iterator that iterates over all the integer points in the triangle.
typedef std::vector< SwarmPoint > CloudBase
typedef int PinId
typedef Segment< Vector2dd > Segment2d
Line segment in 2D and 3D.
typedef Segment< Vector3dd > Segment3d
typedef GenericTriangle< int32_t > Triangle
typedef Rectangle< int32_t > Rectangle32
typedef Affine3D< Quaternion > Affine3DQ
typedef Affine3D< Matrix33 > Affine3DM
typedef
PrimitiveCorrespondance
< Vector2dd, Line2d > CorrespondancePointLine
typedef
PrimitiveCorrespondance
< Vector2dd, Segment2d > CorrespondancePointSegment
typedef AbstractBuffer< double,
int32_t > MatrixBase
typedef GenericQuaternion< double > Quaternion
typedef FixedArray< double > Vector
typedef Vector2d< double > Vector2dd
typedef Vector2d< uint32_t > Vector2du32
typedef Vector2d< uint16_t > Vector2du16
typedef Vector2d< int32_t > Vector2d32
typedef Vector2d< int16_t > Vector2d16
typedef Vector3d< double > Vector3dd
typedef Vector3d< uint32_t > Vector3du32
typedef Vector3d< uint16_t > Vector3du16
typedef Vector3d< int32_t > Vector3d32
typedef Vector3d< int16_t > Vector3d16
typedef std::vector< std::pair
< unsigned, unsigned > > WindowPath
typedef
PrimitiveCorrespondance
< Vector2dd, Vector2dd > Correspondance
typedef SimpleScalarField< int > IntField
typedef SimpleScalarField
< int64_t > TimestampField
typedef SimpleScalarField< double > DoubleField
typedef SimpleScalarField< float > FloatField
typedef SimpleScalarField< bool > BoolField
typedef
AbstractContiniousBuffer
< ClusteringTile > TileGridBase
Functions
RadialCorrection getRadial (const double in[])
void getModel (const RadialCorrection &correction, double in[])
template<typename BufferType , typename MappingType >
bool assignmentOptimal (const BufferType *A, MappingType *mapping)
This assignment algorithm uses the highly optimized version proposed by Daniel Shved.
void assignOptimal (AbstractBuffer< int, int > *input, AbstractBuffer< int, int > *output)
void assignOptimal (AbstractBuffer< uint16_t, int > *input, AbstractBuffer< int, int > *output)
void assignOptimal (AbstractBuffer< double, int > *input, AbstractBuffer< int, int > *output)
void assignOptimal (AbstractBuffer< float, int > *input, AbstractBuffer< int, int > *output)
template<typename IntegerType >
ostream & write_integer_bin (ostream &os, IntegerType value)
These are useful methods to serialize integer types not depending of the current endianess.
template<typename IntegerType >
istream & read_integer_bin (istream &is, IntegerType &value)
ostream & operator<< (ostream &out, const G12Buffer &buffer)
template<template< typename > class KernelType>
static void process (G12Buffer *input[KernelType< DummyAlgebra >::inputNumber], G12Buffer *output[KernelType< DummyAlgebra >::inputNumber], const KernelType< DummyAlgebra > &kernel=KernelType< DummyAlgebra >())
This function is a copy of the one in G12Buffer.cpp.
template<template< typename > class KernelType>
static void process8 (G8Buffer *input[KernelType< DummyAlgebra >::inputNumber], G8Buffer *output[KernelType< DummyAlgebra >::inputNumber], const KernelType< DummyAlgebra > &kernel=KernelType< DummyAlgebra >())
G12Buffer * findCornerPoints (G12Buffer *input)
uint8_t getDirection5bit (int16_t dx, int16_t dy)
uint8_t getMagnitude7bit (int16_t dx, int16_t dy)
Expecting two Sobel derivatives of the 12bit image This will make the range 12 + 3 bits for the derivatives (due to Sobel matrix coefficients)
double getLengthStable (double a, double b)
int clipCohenSutherland (int16_t x1, int16_t y1, int16_t x2, int16_t y2, vector2Ds16 *a, vector2Ds16 *b)
vector3Dd crossProduct (vector3Dd *a, vector3Dd *b)
double dotProduct (vector3Dd *a, vector3Dd *b)
void vectorPrint (vector3Dd *v)
vector3Dd vector3DdCreate (double x, double y, double z)
vector2Dd vector2DdCreate (double x, double y)
void vectorNormalize (vector3Dd *a)
void vectorHomogeniousNormalize (vector3Dd *a)
void vector2DdIncrement (vector2Dd *a, vector2Dd *b)
double vector2DdLength (vector2Dd *a)
vector3Dd vector3DdAdd (vector3Dd a, vector3Dd b)
vector3Dd vectorMultiplyConst (vector3Dd a, double b)
TriangleIterator triangleIteratorCreate (vector2Dd p1, vector2Dd p2, vector2Dd p3)
int triangleIteratorNext (TriangleIterator *iterator, vector2Ds32 *pos)
FORCE_INLINE Int16x16 operator& (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator| (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator^ (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 andNot (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator&= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator|= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator^= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 andNotThis (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator+ (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator- (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator+= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator-= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator<< (const Int16x16 &left, uint32_t count)
FORCE_INLINE Int16x16 operator>> (const Int16x16 &left, uint32_t count)
FORCE_INLINE Int16x16 shiftArithmetic (const Int16x16 &left, uint32_t count)
FORCE_INLINE Int16x16 operator<<= (Int16x16 &left, uint32_t count)
FORCE_INLINE Int16x16 operator>>= (Int16x16 &left, uint32_t count)
FORCE_INLINE Int16x16 operator<< (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator>> (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 shiftArithmetic (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator<<= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator>>= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator< (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator> (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator== (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 productLowerPart (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 productHigherPart (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator* (const Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator*= (Int16x16 &left, const Int16x16 &right)
FORCE_INLINE Int16x16 operator* (int16_t left, Int16x16 &right)
FORCE_INLINE Int16x16 operator* (const Int16x16 &left, int16_t right)
FORCE_INLINE Int16x16 operator*= (Int16x16 &left, int16_t right)
int test1Main (void)
int fround (double value)
Useful round* stuff.
int roundUp (double dValue)
int roundSign (double dValue, bool bSign)
int roundSign (double dValue, int iSign)
int roundSign (double dValue, double dSign)
int roundSign (double dValue)
unsigned int ceilDiv (unsigned int iNum, unsigned int iDenom)
Integer division with rounding to the upper integer that works for non-negative integers only.
int roundDivUp (int nom, unsigned int nDenom)
int roundDiv (int nom, unsigned int nDenom)
int noroundShiftUp (int iVal, unsigned int nShift)
int roundShiftUp (int iVal, unsigned int nShift)
int roundShift (int iVal, unsigned int nShift)
int noroundShift (int iVal, unsigned int nShift)
template<typename Type >
void SwapXY (Type &a, Type &b)
Useful Swap* stuff.
template<typename Type >
void SwapInts (Type &a, Type &b)
On intel architecture there could be no gain in xor because often compiler can swap register aliases without any code generation.
template<typename Type >
Type randRanged (Type valMax, Type valMin=Type(0))
Function to get a random value in the given range.
unsigned getNearUpperPowerOf2 (unsigned value)
Useful function that finds nearest value equals to power of 2 that is not less of the given value.
unsigned getNearUpperPowerOf2 (unsigned value, unsigned &power)
double radToDeg (double angle)
Useful radian to degrees and back conversions.
double degToRad (double angle)
template<class TypeName >
TypeName lerp (TypeName x1, TypeName x2, double alpha)
template<class TypeName >
TypeName lerp (TypeName x1, TypeName x2, double value, double intervalStart, double intervalEnd)
double lerpLimit (double outStart, double outEnd, double value, double intervalStart, double intervalEnd)
ostream & operator<< (ostream &out, const HomographyReconstructor &reconstructor)
Matrix operator* (const Matrix &A, const Matrix &B)
Vector operator* (const Matrix &M, const Vector &V)
Vector operator* (const Vector &V, const Matrix &M)
Matrix operator*= (Matrix &M, const DiagonalMatrix &D)
Matrix operator* (const Matrix &M, const DiagonalMatrix &D)
Matrix operator* (DiagonalMatrix &D, const Matrix &M)
Matrix operator+ (const Matrix &A, const Matrix &B)
Matrix operator- (const Matrix &A, const Matrix &B)
ostream & operator<< (ostream &out, const Matrix &matrix)
Matrix33 operator* (const Matrix33 &m1, const Matrix33 &m2)
Negating the matrix - all elements are replaced with their negative values.
Matrix33 operator*= (Matrix33 &M1, const Matrix33 &M2)
Matrix33 Rotate (const Vector3dd &v, double alpha)
Creates a 3x3 matrix that rotates around the given axis in 3D.
Vector3dd operator* (const Matrix33 &matrix, const Vector3dd &V)
Vector by Matrix left multiplication .
Vector3dd operator* (const Vector3dd &V, const Matrix33 &matrix)
Vector by Matrix right multiplication .
Vector2dd operator* (const Matrix33 &matrix, const Vector2dd &V)
Apply projective transformation to 2D vector
.
Vector2dd operator* (const Vector2dd &V, const Matrix33 &matrix)
Apply projective transformation to 2D vector (vector is form the right)
.
Matrix44 operator* (const Matrix44 &M1, const Matrix44 &M2)
Could use Strassen - http://en.wikipedia.org/wiki/Strassen_algorithm but stability is more valuable now.
Matrix44 operator* (const Matrix44 &M1, const Matrix33 &M2)
This is in fact used only for 3D matrix convenience.
Matrix44 operator* (const Matrix33 &M1, const Matrix44 &M2)
Matrix44 operator*= (Matrix44 &M1, const Matrix44 &M2)
Matrix44 operator*= (Matrix44 &M1, const Matrix33 &M2)
FixedVector< double, 4 > operator* (const Matrix44 &m, const FixedVector< double, 4 > &v)
Vector3dd operator* (const Matrix44 &m, const Vector3dd &v)
FORCE_INLINE Float32x4 operator+ (const Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Float32x4 operator- (const Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Float32x4 operator+= (Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Float32x4 operator-= (Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Float32x4 operator* (const Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Float32x4 operator/ (const Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Float32x4 operator*= (Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Float32x4 operator/= (Float32x4 &left, const Float32x4 &right)
FORCE_INLINE Int32x4 operator/ (const Int32x4 &left, float divisor)
FORCE_INLINE Int32x4 operator/ (const Int32x4 &left, int divisor)
FORCE_INLINE Int32x4 operator/= (Int32x4 &left, float divisor)
FORCE_INLINE Int32x4 operator/= (Int32x4 &left, int divisor)
FORCE_INLINE Int16x8 operator& (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator| (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator^ (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 andNot (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator&= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator|= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator^= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 andNotThis (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator+ (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator- (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator+= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator-= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator<< (const Int16x8 &left, uint32_t count)
FORCE_INLINE Int16x8 operator>> (const Int16x8 &left, uint32_t count)
FORCE_INLINE Int16x8 shiftArithmetic (const Int16x8 &left, uint32_t count)
FORCE_INLINE Int16x8 shrAdd (const Int16x8 &accumulator, const Int16x8 &left, uint32_t count)
FORCE_INLINE Int16x8 operator<<= (Int16x8 &left, uint32_t count)
FORCE_INLINE Int16x8 operator>>= (Int16x8 &left, uint32_t count)
FORCE_INLINE Int16x8 operator<< (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator>> (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 shiftArithmetic (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator<<= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator>>= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator< (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator> (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator== (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 productLowerPart (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 productHigherPart (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator* (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator*= (Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int32x4 unpackLower4 (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int32x4 unpackHigher4 (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int32x8 productExtending (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int16x8 operator* (int16_t left, Int16x8 &right)
FORCE_INLINE Int16x8 operator* (const Int16x8 &left, int16_t right)
FORCE_INLINE Int16x8 operator*= (Int16x8 &left, int16_t right)
FORCE_INLINE Int32x4 operator& (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator| (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator^ (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 andNot (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator&= (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator|= (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator^= (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 andNotThis (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator+ (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator- (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator+= (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator-= (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator<< (const Int32x4 &left, uint32_t count)
FORCE_INLINE Int32x4 operator>> (const Int32x4 &left, uint32_t count)
FORCE_INLINE Int32x4 shiftArithmetic (const Int32x4 &left, uint32_t count)
FORCE_INLINE Int32x4 operator<<= (Int32x4 &left, uint32_t count)
FORCE_INLINE Int32x4 operator>>= (Int32x4 &left, uint32_t count)
FORCE_INLINE Int32x4 operator<< (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator>> (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 shiftArithmetic (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator<<= (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator>>= (Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator< (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator> (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x4 operator== (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int64x2 unpackLower2 (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int64x2 unpackHigher2 (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int32x8 operator>> (const Int32x8 &left, uint32_t count)
FORCE_INLINE Int32x8 operator>>= (Int32x8 &left, uint32_t count)
FORCE_INLINE Int16x8 shiftLogical (const Int16x8 &left, uint32_t count)
FORCE_INLINE Int16x8 shiftLogical (const Int16x8 &left, const Int16x8 &right)
FORCE_INLINE Int32x4 shiftLogical (const Int32x4 &left, uint32_t count)
FORCE_INLINE Int32x4 shiftLogical (const Int32x4 &left, const Int32x4 &right)
FORCE_INLINE Int64x2 shiftLogical (const Int64x2 &left, uint32_t count)
FORCE_INLINE Int64x2 shiftLogical (const Int64x2 &left, const Int64x2 &right)
FORCE_INLINE Int8x16 operator< (const Int8x16 &left, const Int8x16 &right)
FORCE_INLINE Int8x16 operator> (const Int8x16 &left, const Int8x16 &right)
FORCE_INLINE Int8x16 productLowerPart (const Int8x16 &left, const Int8x16 &right)
FORCE_INLINE Int8x16 productHigherPart (const Int8x16 &left, const Int8x16 &right)
FORCE_INLINE Int8x16 operator* (const Int8x16 &left, const Int8x16 &right)
FORCE_INLINE Int8x16 operator*= (Int8x16 &left, const Int8x16 &right)
FORCE_INLINE Int8x16 operator* (int8_t left, Int8x16 &right)
FORCE_INLINE Int8x16 operator* (const Int8x16 &left, int8_t right)
FORCE_INLINE Int8x16 operator*= (Int8x16 &left, int8_t right)
FORCE_INLINE UInt16x8 operator>> (const UInt16x8 &left, uint32_t count)
FORCE_INLINE UInt16x8 operator>>= (UInt16x8 &left, uint32_t count)
FORCE_INLINE UInt16x8 operator>> (const UInt16x8 &left, const UInt16x8 &right)
FORCE_INLINE UInt16x8 operator>>= (UInt16x8 &left, const UInt16x8 &right)
FORCE_INLINE UInt16x8 operator< (const UInt16x8 &left, const UInt16x8 &right)
FORCE_INLINE UInt16x8 operator> (const UInt16x8 &left, const UInt16x8 &right)
FORCE_INLINE UInt16x8 productHigherPart (const UInt16x8 &left, const UInt16x8 &right)
FORCE_INLINE UInt8x16 productLowerPart (const UInt8x16 &left, const UInt8x16 &right)
FORCE_INLINE UInt8x16 productHigherPart (const UInt8x16 &left, const UInt8x16 &right)
FORCE_INLINE UInt8x16 operator* (const UInt8x16 &left, const UInt8x16 &right)
FORCE_INLINE UInt8x16 operator*= (UInt8x16 &left, const UInt8x16 &right)
FORCE_INLINE UInt8x16 operator* (int8_t left, UInt8x16 &right)
FORCE_INLINE UInt8x16 operator* (const UInt8x16 &left, int8_t right)
FORCE_INLINE UInt8x16 operator*= (UInt8x16 &left, int8_t right)
template<class Type >
Vector2dd getInputDisparity (Type *input, int y, int x)
template<>
Vector2dd getInputDisparity< DisparityBuffer > (DisparityBuffer *input, int y, int x)
template<>
Vector2dd getInputDisparity< FloatFlowBuffer > (FloatFlowBuffer *input, int y, int x)
template<>
void DefaultSetter::visit< std::string, StringField > (std::string &field, const StringField *fieldDescriptor)
template<>
void PrinterVisitor::visit< std::string, StringField > (std::string &field, const StringField *fieldDescriptor)
template<>
BaseField::FieldType BaseField::getType< std::string > ()
template<typename IndexType , class Function >
void parallelable_for_notbb (IndexType begin, IndexType end, const Function &f)
This template provides the dummy call of the function over the interval without TBB.
template<typename IndexType , class Function >
void parallelable_reduce_notbb (IndexType begin, IndexType end, Function &f)
template<typename IndexType , class Function >
void parallelable_reduce (IndexType begin, IndexType end, Function &f)
void stdTerminateHandler ()
void setStdTerminateHandler ()
template<typename IndexType , class Function >
void parallelable_for (IndexType begin, IndexType end, const Function &f, bool=true)
This template provides the parallelable call of the function over the interval with or without TBB.
template<typename IndexType , class Function >
void parallelable_for (IndexType begin, IndexType end, std::size_t, const Function &f, bool=true)
Variables
static cchar * sFormatStr = "#dims:%d (%d) x %d x %u"
const int iterations = 100
const double lambda_factor = 1.5
const int dimention = 2
const double minXDif = 5
const int QUATERNION_DIMENTION = 4
int const tileSize = 15
Detailed Description
Design is heavily based on http://glorfindel.mavrinac.com/~aaron/school/pdf/prescott97_linelens.pdf.
Looks extremely unsafe because it depends on the order of static initialization.
Should check standard if this is ok
Also it's not clear why removing "= Reflection()" breaks the code;
Typedef Documentation
typedef Affine3D<Matrix33> corecvs::Affine3DM
Definition at line 78 of file affine.h.
typedef Affine3D<Quaternion> corecvs::Affine3DQ
Definition at line 77 of file affine.h.
typedef AbstractContiniousBuffer<uint8_t, int32_t> corecvs::BooleanBufferBase
Definition at line 29 of file booleanBuffer.h.
typedef SimpleScalarField<bool> corecvs::BoolField
Definition at line 294 of file reflection.h.
typedef AbstractContiniousBuffer<SwarmPoint*, int32_t> corecvs::Buffer3dBase
Definition at line 15 of file buffer3d.h.
typedef std::vector<SwarmPoint> corecvs::CloudBase
Definition at line 14 of file cloud.h.
typedef PrimitiveCorrespondance<Vector2dd, Vector2dd> corecvs::Correspondance
Definition at line 67 of file correspondanceList.h.
typedef PrimitiveCorrespondance<Vector2dd, Line2d> corecvs::CorrespondancePointLine
Definition at line 24 of file homographyReconstructor.h.
typedef PrimitiveCorrespondance<Vector2dd, Segment2d> corecvs::CorrespondancePointSegment
Definition at line 25 of file homographyReconstructor.h.
typedef AbstractContiniousBuffer<RGBColor, int32_t> corecvs::CRGB24BufferBase
Definition at line 31 of file rgb24Buffer.h.
typedef AbstractContiniousBuffer<double, int32_t> corecvs::DepthBufferBase
Definition at line 17 of file depthBuffer.h.
typedef AbstractBuffer<Vector2d<int16_t> > corecvs::DerivativeBufferBase
Definition at line 23 of file derivativeBuffer.h.
typedef FlowBuffer corecvs::DisparityBuffer
Definition at line 144 of file flowBuffer.h.
typedef AbstractContiniousBuffer<DisparityElement, int32_t> corecvs::DisparityBufferBase
Definition at line 20 of file disparityBuffer.h.
typedef uint16_t corecvs::DisparityElement
Definition at line 19 of file disparityBuffer.h.
typedef AbstractContiniousBuffer<Vector2dd, int32_t> corecvs::DisplacementBufferBase
Definition at line 29 of file displacementBuffer.h.
typedef SimpleScalarField<double> corecvs::DoubleField
Definition at line 292 of file reflection.h.
typedef uint32_t corecvs::fixed16in32
Definition at line 20 of file algebra.h.
typedef uint16_t corecvs::fixed8in16
Definition at line 19 of file algebra.h.
typedef AbstractContiniousBuffer<BilinearMapPoint, int32_t> corecvs::FixedPointDisplaceBase
Definition at line 53 of file fixedPointDisplace.h.
typedef SimpleScalarField<float> corecvs::FloatField
Definition at line 293 of file reflection.h.
typedef AbstractContiniousBuffer<FloatFlow, int32_t> corecvs::FloatFlowBufferBase
Definition at line 38 of file floatFlowBuffer.h.
typedef AbstractContiniousBuffer< FlowElement , int32_t> corecvs::FlowBufferBase
Definition at line 36 of file flowBuffer.h.
typedef Vector2d16 corecvs::FlowElement
Definition at line 35 of file flowBuffer.h.
typedef AbstractContiniousBuffer<SwarmPoint*, int32_t> corecvs::G12Buffer3dBase
Definition at line 12 of file g12Buffer3d.h.
typedef AbstractContiniousBuffer<uint16_t, int32_t> corecvs::G12BufferBase
Definition at line 21 of file g12Buffer.h.
typedef AbstractContiniousBuffer<uint8_t, int32_t> corecvs::G8BufferBase
Definition at line 20 of file g8Buffer.h.
typedef SimpleScalarField<int> corecvs::IntField
Definition at line 290 of file reflection.h.
typedef AbstractBuffer<double, int32_t> corecvs::MatrixBase
Definition at line 29 of file matrix.h.
typedef ObjectBlock<uint8_t> corecvs::MemoryBlock
Definition at line 201 of file memoryBlock.h.
typedef ObjectRef<uint8_t> corecvs::MemoryBlockRef
Definition at line 202 of file memoryBlock.h.
typedef int corecvs::PinId
Definition at line 25 of file filterBlock.h.
typedef GenericQuaternion<double> corecvs::Quaternion
Definition at line 329 of file quaternion.h.
typedef Rectangle<int32_t> corecvs::Rectangle32
Definition at line 82 of file rectangle.h.
typedef Segment<Vector2dd> corecvs::Segment2d
Line segment in 2D and 3D.
Definition at line 42 of file line.h.
typedef Segment<Vector3dd> corecvs::Segment3d
Definition at line 43 of file line.h.
typedef AbstractContiniousBuffer< Element6D , int32_t> corecvs::SixDBufferBase
Definition at line 27 of file sixDBuffer.h.
typedef IntegralBuffer<Vector3dd, Vector3dd, uint32_t> corecvs::SpatialGradientIntegralBuffer
Definition at line 43 of file spatialGradient.h.
typedef AbstractContiniousBuffer<ClusteringTile> corecvs::TileGridBase
Definition at line 198 of file tileGrid.h.
typedef SimpleScalarField<int64_t> corecvs::TimestampField
Definition at line 291 of file reflection.h.
typedef GenericTriangle<int32_t> corecvs::Triangle
Definition at line 31 of file polygons.h.
typedef struct corecvs::TriangleIterator_TAG corecvs::TriangleIterator
This class implements the triangle iterator that iterates over all the integer points in the triangle.
typedef FixedArray<double> corecvs::Vector
Definition at line 14 of file vector.h.
typedef Vector2d<int16_t> corecvs::Vector2d16
Definition at line 203 of file vector2d.h.
typedef Vector2d<int32_t> corecvs::Vector2d32
Definition at line 202 of file vector2d.h.
typedef struct corecvs::vector2Dd_tag corecvs::vector2Dd
typedef Vector2d<double> corecvs::Vector2dd
Definition at line 198 of file vector2d.h.
typedef struct corecvs::vector2Ds16_tag corecvs::vector2Ds16
typedef struct corecvs::vector2Ds32_tag corecvs::vector2Ds32
typedef struct corecvs::vector2Du16_tag corecvs::vector2Du16
typedef Vector2d<uint16_t> corecvs::Vector2du16
Definition at line 200 of file vector2d.h.
typedef Vector2d<uint32_t> corecvs::Vector2du32
Definition at line 199 of file vector2d.h.
typedef struct corecvs::vector3D_tag corecvs::vector3D
typedef Vector3d<int16_t> corecvs::Vector3d16
Definition at line 188 of file vector3d.h.
typedef Vector3d<int32_t> corecvs::Vector3d32
Definition at line 187 of file vector3d.h.
typedef struct corecvs::vector3Dd_tag corecvs::vector3Dd
typedef Vector3d<double> corecvs::Vector3dd
Definition at line 183 of file vector3d.h.
typedef Vector3d<uint16_t> corecvs::Vector3du16
Definition at line 185 of file vector3d.h.
typedef Vector3d<uint32_t> corecvs::Vector3du32
Definition at line 184 of file vector3d.h.
typedef std::vector<std::pair<unsigned, unsigned> > corecvs::WindowPath
Definition at line 19 of file meanShiftWindow.h.
Function Documentation
FORCE_INLINE Int32x4 corecvs::andNot (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 231 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vbicq_s32(left.data, right.data);
}
FORCE_INLINE Int16x8 corecvs::andNot (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 294 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return vbicq_s16(left.data, right.data);
}
FORCE_INLINE Int16x16 corecvs::andNot (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 301 of file int16x16.h.
References corecvs::Int16x16::data.
Referenced by corecvs::LogicSubt< Algebra >::process(), and corecvs::SSEMath::selector().
{
    return Int16x16(_mm256_andnot_si128(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::andNotThis (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 250 of file int32x4.h.
References corecvs::Int32x4::data.
{
    left.data = vbicq_s32(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::andNotThis (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 313 of file int16x8.h.
References corecvs::Int16x8::data.
{
    left.data = vbicq_s16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x16 corecvs::andNotThis (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 320 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_andnot_si128(left.data, right.data);
    return left;
}
template<typename BufferType , typename MappingType > bool corecvs::assignmentOptimal (const BufferType * A, MappingType * mapping)
This assignment algorithm uses the highly optimized version proposed by Daniel Shved.
at http://acm.mipt.ru/twiki/bin/view/Algorithms/HungarianAlgorithmCPP
First of all - this version uses the optimization that allows not to store the duplicate of the matrix.
All assignment manipulations are limited to adding or subtracting value to of from column or row in whole. In this version the subtraction values are stored in the v and u arrays.
Secondary - this algorithm processes matrix row by row.
If naive approach for assigning element in the newly added row doesn't work, (the column with the smallest element is already used in the assignment) * the algorithm analyzes the upper rows (markedI holds the currently analyzed row) until it will find a new collision-free assignment.
Staring new row analysis While attempting to resolve collision we could build a chain of zeros links will hold the connection between the rows mins visited - will hold the flags that the row is already visited
markedI holds the currently analyzed row. Analysis starts with the just added row
We will select 3 areas -
unvisied rows
visied rows and visited columns - the visited block
visied rows and un visited columns - the search block
Now we would update the information about the minimum in the un-visited columns mins[j] will hold the the minimum value in the j-th column among all the visited rows. Values in the visited columns do not matter.
(j,markedI) will hold the position of the minimum in the search block
We arrive here if the processed row in the j1 column holds the smallest element We update the mins array And create a horizontal link to the collision element
Now j hold the number of the unvisited column in which the minimum among the visited rows is achieved.
Thus delta will hold the minimum in the searchBlock.
Next code will - In search block (visited rows, unvisited columns) decrease all the search block by delta - a new 0 will appear at (j, markedI)
In visited block (visited rows, visited columns) leave all unchanged (+ delta to columns, -delta to rows)
In the visited columns, unvisited rows elements will increase. But there are no selected elements there
In the unvisited columns, unvisied rows nothing will happen
As said above (j, markedI) holds the new zero. Now we have two options either xy[j] will hold -1 (which means no selected ("starred") zeros in the column j) then we will leave the cycle or there is another 0 in the row xy[j] then we make it current and continue to build links list. The new collision element is (j, xy[j])
We exited the collision processing cycle and now we have a linked list of collisions
Links holds the collision columns numbers for "primed elements". It starts with the element in column j.
xy holds the map from columns to rows of the old assignment - the "stared elements"
We can now improve the list increasing it's size by new element and switching all the "stared" elements to "primed"
Definition at line 47 of file assignmentOptimal.cpp.
{
   typedef typename BufferType::InternalElementType Type;
   int i, j, j1;
   int h = A->h;
   int w = A->w;
   Type   *v = new Type[w];
   Type   *u = new Type[h];
   int    *xy = new int[w];
   int   *links = new int[w];
   Type  *mins  = new Type[w];
   bool *visited  = new bool[w];
   for (i = 0; i < h; i++)
   {
       u[i] = Type(0);
   }
   for (j = 0; j < w; j++)
   {
       v[j] = Type(0);
       xy[j] = -1;
   }
   for(i = 0; i < h; i++) {
       /**
        * Staring new row analysis
        * While attempting to resolve collision we could build a chain of zeros
        * links will hold the connection between the rows
        * mins
        * visited - will hold the flags that the row is already visited
        *
        * */
       for (j = 0; j < w; j++)
       {
           links[j]   = -1;
           mins[j]    = std::numeric_limits<Type>::max();
           visited[j] = false;
       }
      /**
       * markedI holds the currently analyzed row.
       * Analysis starts with the just added row
       *
       * We will select  3 areas -
       * <ol>
       *   <li> unvisied rows
       *   <li> visied rows and visited columns - the visited block
       *   <li> visied rows and un visited columns - the search block
       * </ol>
       *
       *
       * */
      int markedI = i;
      int markedJ = -1;
      while(markedI != -1)
      {
          /**
           * Now we would update the information about the minimum in the un-visited columns
           * mins[j] will hold the the minimum value in the j-th column among all the
           * visited rows. Values in the visited columns do not matter.
           *
           * (j,markedI) will hold the position of the minimum in the search block
           *
           *
           * */
         j = -1;
         for(j1 = 0; j1 < w; j1 ++)
         {
            if(!visited[j1])
            {
                Type current = A->element(markedI,j1) - u[markedI] - v[j1];
                if(current < mins[j1]) {
                    /**
                     * We arrive here if the processed row in the j1 column holds the smallest element
                     * We update the mins array
                     * And create a horizontal link to the collision element
                     * */
                    mins[j1] = current;
                    links[j1] = markedJ;
                }
                if(j == -1 || mins[j1] < mins[j])
                   j = j1;
            }
         }
        /**
          * Now j hold the number of the unvisited column in which the minimum among the
          * visited rows is achieved.
          *
          * Thus delta will hold the minimum in the searchBlock.
          *
          * Next code will -
          *    In search block (visited rows, unvisited columns )
          *               decrease all the search block by delta - a new 0 will appear at (j, markedI)
          *
          *    In visited block (visited rows, visited columns)
          *               leave all unchanged (+ delta to columns, -delta to rows)
          *
          *    In the visited columns, unvisited rows
          *                  elements will increase. But there are no selected elements there
          *
          *    In the unvisited columns, unvisied rows
          *                nothing will happen
          *
          *
          * */
         Type delta = mins[j];
         for(j1 = 0; j1 < w; j1++)
         {
            if(visited[j1]) {
               u[xy[j1]] += delta;
               v[j1] -= delta;
            } else {
               mins[j1] -= delta;
            }
         }
         u[i] += delta;
         /**
          *  As said above (j, markedI) holds the new zero.  Now we have two options
          *  either xy[j] will hold -1 (which means no selected ("starred") zeros in the column j)
          *        then we will leave the cycle
          *  or there is another 0 in the row xy[j]
          *         then we make it current and continue to build links list.
          *        The new collision element is (j, xy[j])
          *
          * */
         visited[j] = 1;
         markedJ = j;
         markedI = xy[j];
      }
      /**
       *  We exited the collision processing cycle and now we have a linked list of collisions
       *
       *  Links holds the collision columns numbers  for "primed elements". It starts with the element in column j.
       *
       *  xy holds the map from columns to rows of the old assignment - the "stared elements"
       *
       *  We can now improve the list increasing it's size by new element and
       *  switching all the "stared" elements to "primed"
       *
       *  */
      for(; links[j] != -1; j = links[j])
         xy[j] = xy[links[j]];
      xy[j] = i;
   }
   // Returning the result
   for(j = 0; j < w; j++)
   {
      if(xy[j] != -1)
         mapping->element(xy[j],0) = j;
   }
   delete[] v;
   delete[] u;
   delete[] xy;
   delete[] links;
   delete[] mins;
   delete[] visited;
   return true;
}
void corecvs::assignOptimal (AbstractBuffer< int, int > * input, AbstractBuffer< int, int > * output)
Definition at line 223 of file assignmentOptimal.cpp.
{
    assignmentOptimal<AbstractBuffer<int, int>, AbstractBuffer<int, int> >(input, output);
}
void corecvs::assignOptimal (AbstractBuffer< uint16_t, int > * input, AbstractBuffer< int, int > * output)
Definition at line 228 of file assignmentOptimal.cpp.
{
    assignmentOptimal<AbstractBuffer<uint16_t, int>, AbstractBuffer<int, int> >(input, output);
}
void corecvs::assignOptimal (AbstractBuffer< double, int > * input, AbstractBuffer< int, int > * output)
Definition at line 233 of file assignmentOptimal.cpp.
{
    assignmentOptimal<AbstractBuffer<double, int>, AbstractBuffer<int, int> >(input, output);
}
void corecvs::assignOptimal (AbstractBuffer< float, int > * input, AbstractBuffer< int, int > * output)
Definition at line 238 of file assignmentOptimal.cpp.
{
    assignmentOptimal<AbstractBuffer<float, int>, AbstractBuffer<int, int> >(input, output);
}
template<> BaseField::FieldType corecvs::BaseField::getType< std::string > () [inline]
Definition at line 210 of file reflection.h.
{ return TYPE_STRING;    }
unsigned int corecvs::ceilDiv (unsigned int iNum, unsigned int iDenom) [inline]
Integer division with rounding to the upper integer that works for non-negative integers only.
Definition at line 67 of file mathUtils.h.
{
    return (iNum + iDenom - 1) / iDenom;
}
int corecvs::clipCohenSutherland (int16_t x1, int16_t y1, int16_t x2, int16_t y2, vector2Ds16 * a, vector2Ds16 * b)
vector3Dd corecvs::crossProduct (vector3Dd * a, vector3Dd * b)
template<> void corecvs::DefaultSetter::visit< std::string, StringField > (std::string & field, const StringField * fieldDescriptor)
Definition at line 54 of file defaultSetter.cpp.
{
    field = fieldDescriptor->defaultValue;
}
double corecvs::degToRad (double angle) [inline]
Definition at line 159 of file mathUtils.h.
References M_PI.
Referenced by CameraScene::drawMyself(), Transform3DSelector::getTransform(), OpenGLTools::gluPerspective(), OpenGLTools::gluPerspectivePosZ(), CameraCalculatorWidget::lensNominalAngleChanged(), CameraCalculatorWidget::lensRealAngleChanged(), CloudViewDialog::resetCameraPos(), AutomatedRectifyControlWidget::updateFocalFromFOV(), and AngleEditBox::updateRagAngles().
{
    return angle / 180.0 * M_PI;
}
double corecvs::dotProduct (vector3Dd * a, vector3Dd * b)
G12Buffer* corecvs::findCornerPoints (G12Buffer * input)
int corecvs::fround (double value) [inline]
Useful round* stuff.
Unfortunately round is not supported by VSMS compiler. So we use fround instead
Definition at line 35 of file mathUtils.h.
Referenced by corecvs::DirectRemapper::_init(), GraphPlotDialog::addGraphPoint(), corecvs::Buffer3d::addPoints(), corecvs::G12Buffer3d::addPoints(), corecvs::DisplacementBuffer::CacheInverse(), corecvs::KLTGenerator< InterpolationType >::calculateFlowFromPrevLevelBuffer(), GraphPlotDialog::childRepaint(), AdvancedImageWidget::childWheelEvent(), corecvs::SegmentPayload::compensateDesync(), drawArc(), drawCircle(), drawLine(), drawPie(), corecvs::FixedPoint24p8::FixedPoint24p8(), corecvs::Buffer3d::getLength(), corecvs::KLTGenerator< InterpolationType >::kltIteration(), corecvs::CorrespondanceList::makePreciseCopy(), corecvs::RGBColor::rainbow1(), corecvs::VJPattern::scale(), corecvs::VJSimpleClassifier::scale(), GraphPlotDialog::setSnapshotValue(), and AdvancedImageWidget::widgetToImage().
{
    return (int)floor(value + 0.5);         // be careful: it's right only for positive values
}
uint8_t corecvs::getDirection5bit (int16_t dx, int16_t dy)
Todo:
So far use double. Later no double should be used.
Definition at line 51 of file algebra.c.
{
        uint8_t accumulator = 0;
        int16_t rx;
        int16_t ry;
        /* \todo TODO: Make this faster*/
        // Reduce the circle to the 1st quadrant
        if (dx < 0)
        {
                if (dy < 0)
                {
                        accumulator = 16;
                        rx = -dx;
                        ry = -dy;
                }
                else
                {
                        accumulator = 8;
                        rx =  dy;
                        ry = -dx;
                }
        }
        else
        {
                if (dy < 0)
                {
                        accumulator = 24;
                        rx = -dy;
                        ry = dx;
                }
                else
                {
                        accumulator = 0;
                        rx = dx;
                        ry = dy;
                }
        }
        // Do the tree search
        if (ry <= rx)
        {
                /// @todo So far use double. Later no double should be used.
                if (rx <= 0.414213562 * ry)
                {
                        if (rx <= 0.198912367 * ry)
                                return accumulator;
                        else
                                return accumulator + 1;
                }
                else
                {
                        if (rx <= 0.668178638 * ry)
                                return accumulator + 2;
                        else
                                return accumulator + 3;
                }
        }
        else
        {
                if (ry <= 0.414213562 * rx)
                {
                        if (ry <= 0.198912367 * rx)
                                return accumulator + 7;
                        else
                                return accumulator + 6;
                }
                else
                {
                        if (ry <= 0.668178638 * rx)
                                return accumulator + 5;
                        else
                                return accumulator + 4;
                }
        }
}
template<class Type > Vector2dd corecvs::getInputDisparity (Type * input, int y, int x)
Definition at line 86 of file triangulator.cpp.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
{
    return input->element(y,x);
}
template<> Vector2dd corecvs::getInputDisparity< DisparityBuffer > (DisparityBuffer * input, int y, int x)
Definition at line 92 of file triangulator.cpp.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    FlowElement *flowElement = &input->element(y,x);
    return Vector2dd(flowElement->x(), flowElement->y());
}
template<> Vector2dd corecvs::getInputDisparity< FloatFlowBuffer > (FloatFlowBuffer * input, int y, int x)
Definition at line 99 of file triangulator.cpp.
References corecvs::FixedVectorBase< RealType, ElementType, length >::element.
{
    return input->element(y,x).vector;
}
double corecvs::getLengthStable (double a, double b)
Definition at line 161 of file algebra.c.
Referenced by Triangulation::Point::length().
{
        double ma = (a > 0) ? a : -a;
        double mb = (b > 0) ? b : -b;
        if (ma == 0 && mb == 0) return 0;
        if (ma > mb)
        {
                double div = (mb / ma);
                return ma * sqrt(1.0 + div * div );
        }
        else
        {
                double div = (ma / mb);
                return mb * sqrt(1.0 + div * div );
        }
}
uint8_t corecvs::getMagnitude7bit (int16_t dx, int16_t dy)
Expecting two Sobel derivatives of the 12bit image This will make the range 12 + 3 bits for the derivatives (due to Sobel matrix coefficients)
Parameters:
dx - X Sobel derivative
dy - Y Sobel derivative
Definition at line 136 of file algebra.c.
References rootLUT.
{
    //                        24bit      +       24bit          = 25bit
        uint32_t distsq = ((int32_t)dx * dx) + ((int32_t)dy * dy);
        //   reduce to 14bits
        distsq >>= 11;
        //   And now use search in LUT
        uint8_t start = 0, end = 127;
        while (start != end) {
                uint8_t middle = (start + end) >> 1;
                if (rootLUT[middle] == distsq)
                        return middle;
                if (rootLUT[middle] > distsq)
                {
                        end = middle - 1;
                }
                else
                {
                        start = middle + 1;
                }
        }
        return start;
}
void corecvs::getModel (const RadialCorrection & correction, double in[])
unsigned corecvs::getNearUpperPowerOf2 (unsigned value) [inline]
Useful function that finds nearest value equals to power of 2 that is not less of the given value.
Definition at line 129 of file mathUtils.h.
References CORE_IS_POW2N.
Referenced by getNearUpperPowerOf2().
{
    if (CORE_IS_POW2N(value))
        return value;
    value |= value >>  1;
    value |= value >>  2;
    value |= value >>  4;
    value |= value >>  8;
    value |= value >> 16;
    return value ? value + 1 : 0;
}
unsigned corecvs::getNearUpperPowerOf2 (unsigned value, unsigned & power) [inline]
Definition at line 142 of file mathUtils.h.
References getNearUpperPowerOf2().
{
    power = 0;
    value = getNearUpperPowerOf2(value);
    if (value) {
        while ((value & (1 << power)) == 0) power++;
    }
    return value;
}
RadialCorrection corecvs::getRadial (const double in[])
template<class TypeName > TypeName corecvs::lerp (TypeName x1, TypeName x2, double alpha)
Definition at line 165 of file mathUtils.h.
{
    return x1 * (1.0 - alpha) + x2 * alpha;
}
template<class TypeName > TypeName corecvs::lerp (TypeName x1, TypeName x2, double value, double intervalStart, double intervalEnd)
Definition at line 171 of file mathUtils.h.
{
    return lerp<TypeName>(x1, x2, (value - intervalStart) / (intervalEnd - intervalStart));
}
double corecvs::lerpLimit (double outStart, double outEnd, double value, double intervalStart, double intervalEnd) [inline]
Definition at line 176 of file mathUtils.h.
Referenced by Scene3DMouse::drawMyself().
{
    if (value < intervalStart) return outStart;
    if (value > intervalEnd)   return outEnd;
    return lerp<double>(outStart, outEnd, value, intervalStart, intervalEnd);
}
int corecvs::noroundShift (int iVal, unsigned int nShift) [inline]
Definition at line 102 of file mathUtils.h.
{
    return iVal >= 0 ? (iVal >> nShift) : -(-iVal >> nShift);
}
int corecvs::noroundShiftUp (int iVal, unsigned int nShift) [inline]
Definition at line 87 of file mathUtils.h.
{
    return iVal >> nShift;
}
FORCE_INLINE Int32x4 corecvs::operator& (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 219 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vandq_s32(left.data, right.data);
}
FORCE_INLINE Int16x8 corecvs::operator& (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 282 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return vandq_s16(left.data, right.data);
}
FORCE_INLINE Int16x16 corecvs::operator& (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 289 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_and_si128(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::operator&= (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 235 of file int32x4.h.
References corecvs::Int32x4::data.
{
    left.data = vandq_s32(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator&= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 298 of file int16x8.h.
References corecvs::Int16x8::data.
{
    left.data = vandq_s16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator&= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 305 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_and_si128(left.data, right.data);
    return left;
}
FORCE_INLINE Float32x4 corecvs::operator* (const Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 92 of file float32x4.h.
References corecvs::Float32x4::data.
{
    return vmulq_f32(left.data, right.data);
}
Matrix corecvs::operator* (const Matrix & A, const Matrix & B)
Definition at line 94 of file matrix.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    ASSERT_TRUE (A.w == B.h, "Matrices have wrong sizes");
    Matrix result(A.h, B.w, false);
    int row, column, runner;
    for (row = 0; row < result.h ; row++)
        for (column = 0; column < result.w ; column++)
        {
            double sum = 0;
            for (runner = 0; runner < A.w; runner++)
            {
                sum += A.a(row, runner) * B.a(runner, column);
            }
            result.a(row, column) = sum;
        }
    return result;
}
Matrix44 corecvs::operator* (const Matrix44 & M1, const Matrix44 & M2)
Could use Strassen - http://en.wikipedia.org/wiki/Strassen_algorithm but stability is more valuable now.
49 multiplications instead of 64
Definition at line 98 of file matrix44.cpp.
References corecvs::Matrix44::a(), corecvs::Matrix44::H, and corecvs::Matrix44::W.
{
    Matrix44 result;
    int row, column, runner;
    for (row = 0; row < Matrix44::H ; row++)
    {
        for (column = 0; column < Matrix44::W ; column++)
        {
            double sum = 0;
            for (runner = 0; runner < Matrix44::H ; runner++)
            {
                sum += M1.a(row, runner) * M2.a(runner, column);
            }
            result.a(row, column) = sum;
        }
    }
    return result;
}
Vector corecvs::operator* (const Matrix & M, const Vector & V)
Definition at line 115 of file matrix.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, corecvs::FixedArrayBase< RealType, ElementType >::at(), corecvs::AbstractBufferParams::h, corecvs::FixedArrayBase< RealType, ElementType >::size(), and corecvs::AbstractBufferParams::w.
{
    ASSERT_TRUE (M.w == V.size(), "Matrix and vector have wrong sizes");
    Vector result(M.h);
    int row, column;
    for (row = 0; row < M.h; row++)
    {
        double sum = 0.0;
        for (column = 0; column < M.w ; column++)
        {
            sum += V.at(column) * M.a(row, column);
        }
        result.at(row) = sum;
    }
    return result;
}
Matrix44 corecvs::operator* (const Matrix44 & M1, const Matrix33 & M2)
This is in fact used only for 3D matrix convenience.
Definition at line 121 of file matrix44.cpp.
{
    return M1 * Matrix44(M2);
}
Matrix44 corecvs::operator* (const Matrix33 & M1, const Matrix44 & M2)
Definition at line 126 of file matrix44.cpp.
{
    return Matrix44(M1) * M2;
}
Vector corecvs::operator* (const Vector & V, const Matrix & M)
Definition at line 132 of file matrix.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, corecvs::FixedArrayBase< RealType, ElementType >::at(), corecvs::AbstractBufferParams::h, corecvs::FixedArrayBase< RealType, ElementType >::size(), and corecvs::AbstractBufferParams::w.
{
    ASSERT_TRUE (M.h == V.size(), "Matrix and vector have wrong sizes");
    Vector result(M.w);
    int row, column;
    for (column = 0; column < M.w ; column++)
    {
        double sum = 0.0;
        for (row = 0; row < M.h; row++)
        {
            sum += V.at(row) * M.a(row, column);
        }
        result.at(column) = sum;
    }
    return result;
}
Matrix33 corecvs::operator* (const Matrix33 & m1, const Matrix33 & m2)
Negating the matrix - all elements are replaced with their negative values.
Matrix multiplication ACCURATE version is slower 1.5 - 2 times
Definition at line 157 of file matrix33.cpp.
References corecvs::Matrix33::a().
{
   Matrix33 M;
#ifdef ACCURATE
   double sum;
   for (int i = 0;i < 3; i++)
     for (int j = 0;j <3; j++)
     {
       sum = 0;
       for (int k = 0; k < 3; k++)
         sum+= M1.x[i*3 + k] * M2.x[k*3 + j];
       M.x[i * 3 + j] = sum;
     }
#else
   return Matrix33(
           m1.a(0,0) * m2.a(0,0) + m1.a(0,1) * m2.a(1,0) + m1.a(0,2) * m2.a(2,0),
           m1.a(0,0) * m2.a(0,1) + m1.a(0,1) * m2.a(1,1) + m1.a(0,2) * m2.a(2,1),
           m1.a(0,0) * m2.a(0,2) + m1.a(0,1) * m2.a(1,2) + m1.a(0,2) * m2.a(2,2),
           m1.a(1,0) * m2.a(0,0) + m1.a(1,1) * m2.a(1,0) + m1.a(1,2) * m2.a(2,0),
           m1.a(1,0) * m2.a(0,1) + m1.a(1,1) * m2.a(1,1) + m1.a(1,2) * m2.a(2,1),
           m1.a(1,0) * m2.a(0,2) + m1.a(1,1) * m2.a(1,2) + m1.a(1,2) * m2.a(2,2),
           m1.a(2,0) * m2.a(0,0) + m1.a(2,1) * m2.a(1,0) + m1.a(2,2) * m2.a(2,0),
           m1.a(2,0) * m2.a(0,1) + m1.a(2,1) * m2.a(1,1) + m1.a(2,2) * m2.a(2,1),
           m1.a(2,0) * m2.a(0,2) + m1.a(2,1) * m2.a(1,2) + m1.a(2,2) * m2.a(2,2)
   );
#endif
}
Matrix corecvs::operator* (const Matrix & M, const DiagonalMatrix & D)
Definition at line 164 of file matrix.cpp.
References corecvs::Matrix::a(), corecvs::FixedArrayBase< RealType, ElementType >::at(), corecvs::AbstractBufferParams::h, corecvs::FixedArrayBase< RealType, ElementType >::size(), and corecvs::AbstractBufferParams::w.
{
    int32_t minDim = min(M.h,M.w);
    minDim = min(minDim, D.size());
    Matrix result(minDim, minDim, false);
    for (int i = 0; i < minDim ; i++)
    {
         for (int j = 0; j < minDim ; j++)
         {
             result.a(i,j) = M.a(i,j) * D.at(i);
         }
    }
    return result;
}
Matrix corecvs::operator* (DiagonalMatrix & D, const Matrix & M)
Definition at line 179 of file matrix.cpp.
References corecvs::Matrix::a(), corecvs::FixedArrayBase< RealType, ElementType >::at(), corecvs::AbstractBufferParams::h, corecvs::FixedArrayBase< RealType, ElementType >::size(), and corecvs::AbstractBufferParams::w.
{
    int32_t minDim = min(M.h,M.w);
    minDim = min(minDim, D.size());
    Matrix result(minDim, minDim, false);
    for (int i = 0; i < minDim ; i++)
    {
        for (int j = 0; j < minDim ; j++)
        {
            result.a(i,j) = M.a(i,j) * D.at(j);
        }
    }
    return result;
}
FixedVector<double, 4> corecvs::operator* (const Matrix44 & m, const FixedVector< double, 4 > & v)
Definition at line 185 of file matrix44.cpp.
References corecvs::Matrix44::a().
{
    FixedVector<double, 4> toReturn;
    toReturn[0] = v[0] * m.a(0,0) + v[1] * m.a(0,1) + v[2] * m.a(0,2) + m.a(0,3) * v[3];
    toReturn[1] = v[0] * m.a(1,0) + v[1] * m.a(1,1) + v[2] * m.a(1,2) + m.a(1,3) * v[3];
    toReturn[2] = v[0] * m.a(2,0) + v[1] * m.a(2,1) + v[2] * m.a(2,2) + m.a(2,3) * v[3];
    toReturn[3] = v[0] * m.a(3,0) + v[1] * m.a(3,1) + v[2] * m.a(3,2) + m.a(3,3) * v[3];
    return toReturn;
}
Vector3dd corecvs::operator* (const Matrix44 & m, const Vector3dd & v)
Definition at line 195 of file matrix44.cpp.
References corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
    FixedVector<double, 4> v4;
    v4[0] = v.x();
    v4[1] = v.y();
    v4[2] = v.z();
    v4[3] = 1.0;
    FixedVector<double, 4> r = m * v4;
    return Vector3dd(r[0],r[1],r[2]) / r[3];
}
FORCE_INLINE UInt8x16 corecvs::operator* (const UInt8x16 & left, const UInt8x16 & right)
Definition at line 344 of file uInt8x16.h.
References productLowerPart().
{
    return productLowerPart(left, right);
}
FORCE_INLINE Int8x16 corecvs::operator* (const Int8x16 & left, const Int8x16 & right)
Definition at line 349 of file int8x16.h.
References productLowerPart().
{
    return productLowerPart(left, right);
}
FORCE_INLINE UInt8x16 corecvs::operator* (int8_t left, UInt8x16 & right)
Definition at line 363 of file uInt8x16.h.
{
    return right * UInt8x16(left);
}
FORCE_INLINE UInt8x16 corecvs::operator* (const UInt8x16 & left, int8_t right)
Definition at line 367 of file uInt8x16.h.
{
    return left * UInt8x16(right);
}
FORCE_INLINE Int8x16 corecvs::operator* (int8_t left, Int8x16 & right)
Definition at line 368 of file int8x16.h.
{
    return right * Int8x16(left);
}
FORCE_INLINE Int8x16 corecvs::operator* (const Int8x16 & left, int8_t right)
Definition at line 372 of file int8x16.h.
{
    return left * Int8x16(right);
}
Vector3dd corecvs::operator* (const Matrix33 & matrix, const Vector3dd & V) [inline]
Vector by Matrix left multiplication .
Note:
ACCURATE version is slower with debug on
Parameters:
matrix input matrix
V input V
Definition at line 379 of file matrix33.h.
References corecvs::Matrix33::a(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
  double a,b,c;
  a = matrix.a(0,0) * V.x() +  matrix.a(0,1) * V.y() + matrix.a(0,2) * V.z();
  b = matrix.a(1,0) * V.x() +  matrix.a(1,1) * V.y() + matrix.a(1,2) * V.z();
  c = matrix.a(2,0) * V.x() +  matrix.a(2,1) * V.y() + matrix.a(2,2) * V.z();
  return Vector3dd(a,b,c);
}
Vector3dd corecvs::operator* (const Vector3dd & V, const Matrix33 & matrix) [inline]
Vector by Matrix right multiplication .
Note:
ACCURATE version is slower with debug on
Parameters:
V input vector
matrix input matrix
Definition at line 402 of file matrix33.h.
References corecvs::Matrix33::a(), corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
  double a,b,c;
  a = matrix.a(0,0) * V.x() + matrix.a(1,0) * V.y() + matrix.a(2,0) * V.z();
  b = matrix.a(0,1) * V.x() + matrix.a(1,1) * V.y() + matrix.a(2,1) * V.z();
  c = matrix.a(0,2) * V.x() + matrix.a(1,2) * V.y() + matrix.a(2,2) * V.z();
  return Vector3dd(a,b,c);
}
FORCE_INLINE Int16x16 corecvs::operator* (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 407 of file int16x16.h.
References productLowerPart().
{
    return productLowerPart(left, right);
}
FORCE_INLINE Int16x8 corecvs::operator* (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 422 of file int16x8.h.
References productLowerPart().
{
    return productLowerPart(left, right);
}
FORCE_INLINE Int16x16 corecvs::operator* (int16_t left, Int16x16 & right) [inline]
Definition at line 436 of file int16x16.h.
{
    return right * Int16x16(left);
}
FORCE_INLINE Int16x16 corecvs::operator* (const Int16x16 & left, int16_t right) [inline]
Definition at line 440 of file int16x16.h.
{
    return left * Int16x16(right);
}
Vector2dd corecvs::operator* (const Matrix33 & matrix, const Vector2dd & V) [inline]
Apply projective transformation to 2D vector
.
Parameters:
matrix input matrix
V input V
Returns:
Definition at line 445 of file matrix33.h.
References corecvs::Matrix33::mulBy2dRight().
{
    return (Vector2dd) matrix.mulBy2dRight(V);
}
FORCE_INLINE Int16x8 corecvs::operator* (int16_t left, Int16x8 & right) [inline]
Definition at line 448 of file int16x8.h.
{
    return right * Int16x8(left);
}
FORCE_INLINE Int16x8 corecvs::operator* (const Int16x8 & left, int16_t right) [inline]
Definition at line 452 of file int16x8.h.
{
    return left * Int16x8(right);
}
Vector2dd corecvs::operator* (const Vector2dd & V, const Matrix33 & matrix) [inline]
Apply projective transformation to 2D vector (vector is form the right)
.
Parameters:
matrix input matrix
V input V
Returns:
Definition at line 465 of file matrix33.h.
References corecvs::Matrix33::mulBy2dLeft().
{
    return (Vector2dd) matrix.mulBy2dLeft(V);
}
FORCE_INLINE Float32x4 corecvs::operator*= (Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 100 of file float32x4.h.
References corecvs::Float32x4::data.
{
    left.data = vmulq_f32(left.data, right.data);
    return left;
}
Matrix44 corecvs::operator*= (Matrix44 & M1, const Matrix44 & M2)
Definition at line 131 of file matrix44.cpp.
{
    M1 = M1 * M2;
    return M1;
}
Matrix44 corecvs::operator*= (Matrix44 & M1, const Matrix33 & M2)
Definition at line 137 of file matrix44.cpp.
{
    M1 = M1 * M2;
    return M1;
}
Matrix corecvs::operator*= (Matrix & M, const DiagonalMatrix & D)
Definition at line 150 of file matrix.cpp.
References corecvs::Matrix::a(), corecvs::FixedArrayBase< RealType, ElementType >::at(), corecvs::AbstractBufferParams::h, corecvs::FixedArrayBase< RealType, ElementType >::size(), and corecvs::AbstractBufferParams::w.
{
    int32_t minDim = min(M.h,M.w);
    minDim = min(minDim, D.size());
    for (int i = 0; i < minDim ; i++)
    {
         for (int j = 0; j < minDim ; j++)
         {
            M.a(i,j) *= D.at(i);
         }
    }
    return M;
}
Matrix33 corecvs::operator*= (Matrix33 & M1, const Matrix33 & M2)
Definition at line 191 of file matrix33.cpp.
{
    M1 = M1 * M2;
    return M1;
}
FORCE_INLINE UInt8x16 corecvs::operator*= (UInt8x16 & left, const UInt8x16 & right)
Definition at line 348 of file uInt8x16.h.
References productLowerPart().
{
    left = productLowerPart(left, right);
    return left;
}
FORCE_INLINE Int8x16 corecvs::operator*= (Int8x16 & left, const Int8x16 & right)
Definition at line 353 of file int8x16.h.
References productLowerPart().
{
    left = productLowerPart(left, right);
    return left;
}
FORCE_INLINE UInt8x16 corecvs::operator*= (UInt8x16 & left, int8_t right)
Definition at line 371 of file uInt8x16.h.
{
    left = left * right;
    return left;
}
FORCE_INLINE Int8x16 corecvs::operator*= (Int8x16 & left, int8_t right)
Definition at line 376 of file int8x16.h.
{
    left = left * right;
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator*= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 411 of file int16x16.h.
References productLowerPart().
{
    left = productLowerPart(left, right);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator*= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 426 of file int16x8.h.
References productLowerPart().
{
    left = productLowerPart(left, right);
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator*= (Int16x16 & left, int16_t right) [inline]
Definition at line 444 of file int16x16.h.
{
    left = left * right;
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator*= (Int16x8 & left, int16_t right) [inline]
Definition at line 456 of file int16x8.h.
{
    left = left * right;
    return left;
}
FORCE_INLINE Float32x4 corecvs::operator+ (const Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 73 of file float32x4.h.
References corecvs::Float32x4::data.
{
    return vaddq_f32(left.data, right.data);
}
Matrix corecvs::operator+ (const Matrix & A, const Matrix & B)
Definition at line 196 of file matrix.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    ASSERT_TRUE (A.w == B.w && A.h == B.h, "Matrices have wrong sizes");
    Matrix result(A.h, A.w, false);
    for (int row = 0; row < result.h ; row++)
    {
        for (int column = 0; column < result.w ; column++)
        {
            result.a(row, column) = A.a(row, column) + B.a(row, column);
        }
    }
    return result;
}
FORCE_INLINE Int32x4 corecvs::operator+ (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 255 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vaddq_s32(left.data, right.data);
}
FORCE_INLINE Int16x8 corecvs::operator+ (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 318 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return Int16x8(vaddq_s16(left.data, right.data));
}
FORCE_INLINE Int16x16 corecvs::operator+ (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 325 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_add_epi16(left.data, right.data));
}
FORCE_INLINE Float32x4 corecvs::operator+= (Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 81 of file float32x4.h.
References corecvs::Float32x4::data.
{
    left.data = vaddq_f32(left.data, right.data);
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator+= (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 263 of file int32x4.h.
References corecvs::Int32x4::data.
{
    left.data = vaddq_s32(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator+= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 326 of file int16x8.h.
References corecvs::Int16x8::data.
{
    left.data = vaddq_s16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator+= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 333 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_add_epi16(left.data, right.data);
    return left;
}
FORCE_INLINE Float32x4 corecvs::operator- (const Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 77 of file float32x4.h.
References corecvs::Float32x4::data.
{
    return vsubq_f32(left.data, right.data);
}
Matrix corecvs::operator- (const Matrix & A, const Matrix & B)
Definition at line 213 of file matrix.cpp.
References corecvs::Matrix::a(), ASSERT_TRUE, corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    ASSERT_TRUE (A.w == B.w && A.h == B.h, "Matrices have wrong sizes");
    Matrix result(A.h, A.w, false);
    for (int row = 0; row < result.h ; row++)
    {
        for (int column = 0; column < result.w ; column++)
        {
            result.a(row, column) = A.a(row, column) - B.a(row, column);
        }
    }
    return result;
}
FORCE_INLINE Int32x4 corecvs::operator- (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 259 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vsubq_s32(left.data, right.data);
}
FORCE_INLINE Int16x8 corecvs::operator- (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 322 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return Int16x8(vsubq_s16(left.data, right.data));
}
FORCE_INLINE Int16x16 corecvs::operator- (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 329 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_sub_epi16(left.data, right.data));
}
FORCE_INLINE Float32x4 corecvs::operator-= (Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 86 of file float32x4.h.
References corecvs::Float32x4::data.
{
    left.data = vsubq_f32(left.data, right.data);
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator-= (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 268 of file int32x4.h.
References corecvs::Int32x4::data.
{
    left.data = vsubq_s32(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator-= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 331 of file int16x8.h.
References corecvs::Int16x8::data.
{
    left.data = vsubq_s16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator-= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 338 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_sub_epi16(left.data, right.data);
    return left;
}
FORCE_INLINE Float32x4 corecvs::operator/ (const Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 96 of file float32x4.h.
References corecvs::Float32x4::data.
Referenced by operator/(), and operator/=().
{
    return vmulq_f32(left.data, vrecpeq_f32(right.data));
}
FORCE_INLINE Int32x4 corecvs::operator/ (const Int32x4 & left, float divisor) [inline]
Definition at line 111 of file float32x4.h.
{
    Float32x4 invDivisor(1.0f / divisor);
    return (Float32x4(left) * invDivisor).trunc();
}
FORCE_INLINE Int32x4 corecvs::operator/ (const Int32x4 & left, int divisor) [inline]
Definition at line 116 of file float32x4.h.
References operator/().
{
    return operator / (left, (float) divisor);
}
FORCE_INLINE Float32x4 corecvs::operator/= (Float32x4 & left, const Float32x4 & right) [inline]
Definition at line 105 of file float32x4.h.
References corecvs::Float32x4::data.
Referenced by operator/=().
{
    left.data = vmulq_f32(left.data, vrecpeq_f32(right.data));
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator/= (Int32x4 & left, float divisor) [inline]
Definition at line 120 of file float32x4.h.
References operator/().
{
    left = operator / (left, divisor);
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator/= (Int32x4 & left, int divisor) [inline]
Definition at line 125 of file float32x4.h.
References operator/=().
{
    return operator /= (left, (float) divisor);
}
FORCE_INLINE UInt16x8 corecvs::operator< (const UInt16x8 & left, const UInt16x8 & right)
Definition at line 137 of file uInt16x8.h.
References corecvs::SSEInteger< RealType >::data.
{
    return UInt16x8(_mm_cmplt_epi16(left.data, right.data));
}
FORCE_INLINE Int8x16 corecvs::operator< (const Int8x16 & left, const Int8x16 & right)
Definition at line 333 of file int8x16.h.
References corecvs::SSEInteger< RealType >::data.
{
    return Int8x16(_mm_cmplt_epi8(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::operator< (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 336 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vcltq_s32(left.data, right.data);
}
FORCE_INLINE Int16x16 corecvs::operator< (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 387 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_cmplt_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::operator< (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 402 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return Int16x8(vcltq_s16(left.data, right.data));
}
ostream& corecvs::operator<< (ostream & out, const G12Buffer & buffer)
Definition at line 51 of file g12Buffer.cpp.
References corecvs::AbstractBuffer< ElementType, IndexType >::element(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    out << "       ";
    for (int j = 0; j < buffer.w; j++)
    {
        out.width(5);
        out << j << " ";
    }
    out << endl;
    out << "     +-";
    for (int j = 0; j < buffer.w; j++)
    {
        out << "------";
    }
    out << "+" << endl;
    for (int i = 0; i < buffer.h; i++)
    {
        out.width(4);
        out << i;
        out <<" | ";
        for (int j = 0; j < buffer.w; j++)
        {
            out.width(5);
            out << buffer.element(i, j) << " ";
        }
        out << "| "<< endl;
    }
    out << "     +-";
    for (int j = 0; j < buffer.w; j++)
    {
      out << "------";
    }
    out << "+" << endl;
    //out.width(wasWidth);
    return out;
}
ostream& corecvs::operator<< (ostream & out, const HomographyReconstructor & reconstructor)
Definition at line 53 of file homographyReconstructor.cpp.
References corecvs::HomographyReconstructor::p2l, and corecvs::HomographyReconstructor::p2p.
{
    streamsize wasPrecision = out.precision(6);
    out << "// Points2Points " << endl;
    out << reconstructor.p2p.size() << endl;
    for (unsigned i = 0; i < reconstructor.p2p.size(); i++)
    {
        out << reconstructor.p2p[i].start << " " << reconstructor.p2p[i].end  << endl;
    }
    out << "// Points2Line " << endl;
    out << reconstructor.p2l.size() << endl;
    for (unsigned i = 0; i < reconstructor.p2l.size(); i++)
    {
        out << reconstructor.p2l[i].start << " " << reconstructor.p2l[i].end  << endl;
    }
    out.precision(wasPrecision);
    return out;
}
ostream& corecvs::operator<< (ostream & out, const Matrix & matrix)
Definition at line 229 of file matrix.cpp.
References corecvs::Matrix::a(), corecvs::AbstractBufferParams::h, and corecvs::AbstractBufferParams::w.
{
    streamsize wasPrecision = out.precision(6);
    for (int i = 0; i < matrix.h; i++)
    {
        out << "[";
        for (int j = 0; j < matrix.w; j++)
        {
            out.width(9);
            out << matrix.a(i, j) << " ";
        }
        out << "]\n";
    }
    out.precision(wasPrecision);
    return out;
}
FORCE_INLINE Int32x4 corecvs::operator<< (const Int32x4 & left, uint32_t count) [inline]
Definition at line 273 of file int32x4.h.
References corecvs::Int32x4::data.
{
    if ( __builtin_constant_p(count) )
        return vshlq_n_s32(left.data, count);
    else
        return vshlq_s32(left.data, vdupq_n_s32((int32_t)count));
}
FORCE_INLINE Int32x4 corecvs::operator<< (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 309 of file int32x4.h.
References corecvs::Int32x4::data.
{
    int count = vgetq_lane_s32(right.data, 0);
    return vshlq_s32(left.data, vdupq_n_s32(count));
}
FORCE_INLINE Int16x8 corecvs::operator<< (const Int16x8 & left, uint32_t count) [inline]
Definition at line 336 of file int16x8.h.
References corecvs::Int16x8::data.
{
    if ( __builtin_constant_p(count) )
        return vshlq_n_s16(left.data, (int)count);
    else
        return vshlq_s16(left.data, vdupq_n_s16((int)count));
}
FORCE_INLINE Int16x16 corecvs::operator<< (const Int16x16 & left, uint32_t count) [inline]
Definition at line 343 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_slli_epi16(left.data, count));
}
FORCE_INLINE Int16x16 corecvs::operator<< (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 365 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_sll_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::operator<< (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 375 of file int16x8.h.
References corecvs::Int16x8::data.
{
    int count = vgetq_lane_s16(right.data, 0);
    return vshlq_s16(left.data, vdupq_n_s16(count));
}
FORCE_INLINE Int32x4 corecvs::operator<<= (Int32x4 & left, uint32_t count) [inline]
Definition at line 291 of file int32x4.h.
References corecvs::Int32x4::data.
{
    if ( __builtin_constant_p(count) )
        left.data = vshlq_n_s32(left.data, count);
    else
        left.data = vshlq_s32(left.data, vdupq_n_s32((int32_t)count));
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator<<= (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 324 of file int32x4.h.
References corecvs::Int32x4::data.
{
    int count = vgetq_lane_s32(right.data, 0);
    left.data = vshlq_s32(left.data, vdupq_n_s32(count));
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator<<= (Int16x16 & left, uint32_t count) [inline]
Definition at line 355 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_slli_epi16(left.data, count);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator<<= (Int16x8 & left, uint32_t count) [inline]
Definition at line 358 of file int16x8.h.
References corecvs::Int16x8::data.
{
    if ( __builtin_constant_p(count) )
        left.data = vshlq_n_s16(left.data, (int)count);
    else
        left.data = vshlq_s16(left.data, vdupq_n_s16((int)count));
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator<<= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 377 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_sll_epi16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator<<= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 390 of file int16x8.h.
References corecvs::Int16x8::data.
{
    int count = vgetq_lane_s16(right.data, 0);
    left.data = vshlq_s16(left.data, vdupq_n_s16(count));
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator== (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 344 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vceqq_s32(left.data, right.data);
}
FORCE_INLINE Int16x16 corecvs::operator== (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 395 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_cmpeq_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::operator== (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 410 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return Int16x8(vceqq_s16(left.data, right.data));
}
FORCE_INLINE UInt16x8 corecvs::operator> (const UInt16x8 & left, const UInt16x8 & right)
Definition at line 141 of file uInt16x8.h.
References corecvs::SSEInteger< RealType >::data.
{
    return UInt16x8(_mm_cmpgt_epi16(left.data, right.data));
}
FORCE_INLINE Int8x16 corecvs::operator> (const Int8x16 & left, const Int8x16 & right)
Definition at line 337 of file int8x16.h.
References corecvs::SSEInteger< RealType >::data.
{
    return Int8x16(_mm_cmpgt_epi8(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::operator> (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 340 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vcgtq_s32(left.data, right.data);
}
FORCE_INLINE Int16x16 corecvs::operator> (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 391 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_cmpgt_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::operator> (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 406 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return Int16x8(vcgtq_s16(left.data, right.data));
}
FORCE_INLINE Int32x8 corecvs::operator>> (const Int32x8 & left, uint32_t count) [inline]
Definition at line 43 of file int32x8.h.
{
    return Int32x8 ( left[0] >> count, left[1] >> count);
}
FORCE_INLINE UInt16x8 corecvs::operator>> (const UInt16x8 & left, uint32_t count)
Definition at line 119 of file uInt16x8.h.
References corecvs::SSEInteger< RealType >::data.
{
    return UInt16x8(_mm_srli_epi16(left.data, count));
}
FORCE_INLINE UInt16x8 corecvs::operator>> (const UInt16x8 & left, const UInt16x8 & right)
Definition at line 128 of file uInt16x8.h.
References corecvs::SSEInteger< RealType >::data.
{
    return UInt16x8(_mm_srl_epi16(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::operator>> (const Int32x4 & left, uint32_t count) [inline]
Definition at line 280 of file int32x4.h.
References corecvs::Int32x4::data.
{
    if ( __builtin_constant_p(count) )
        return vshrq_n_u32((uint32x4_t)left.data, (int32_t)count);
    else
        return vshlq_u32((uint32x4_t)left.data, vdupq_n_s32(-(int32_t)count));
}
FORCE_INLINE Int32x4 corecvs::operator>> (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 314 of file int32x4.h.
References corecvs::Int32x4::data.
{
    int count = vgetq_lane_s32(right.data, 0);
    return vshlq_u32((uint32x4_t)left.data, vdupq_n_s32(-count));
}
FORCE_INLINE Int16x8 corecvs::operator>> (const Int16x8 & left, uint32_t count) [inline]
Definition at line 343 of file int16x8.h.
References corecvs::Int16x8::data.
{
    if ( __builtin_constant_p(count) )
        return vshrq_n_u16((uint16x8_t)left.data, (int)count);
    else
        return vshlq_u16((uint16x8_t)left.data, vdupq_n_s16(-(int)count));
}
FORCE_INLINE Int16x16 corecvs::operator>> (const Int16x16 & left, uint32_t count) [inline]
Definition at line 347 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_srli_epi16(left.data, count));
}
FORCE_INLINE Int16x16 corecvs::operator>> (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 369 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_srl_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::operator>> (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 380 of file int16x8.h.
References corecvs::Int16x8::data.
{
    int count = vgetq_lane_s16(right.data, 0);
    return vshlq_u16((uint16x8_t)left.data, vdupq_n_s16(-count));
}
FORCE_INLINE Int32x8 corecvs::operator>>= (Int32x8 & left, uint32_t count) [inline]
Definition at line 48 of file int32x8.h.
{
    left[0] >>= count;
    left[1] >>= count;
    return left;
}
FORCE_INLINE UInt16x8 corecvs::operator>>= (UInt16x8 & left, uint32_t count)
Definition at line 123 of file uInt16x8.h.
References corecvs::SSEInteger< RealType >::data.
{
    left.data = _mm_srli_epi16(left.data, count);
    return left;
}
FORCE_INLINE UInt16x8 corecvs::operator>>= (UInt16x8 & left, const UInt16x8 & right)
Definition at line 132 of file uInt16x8.h.
References corecvs::SSEInteger< RealType >::data.
{
    left.data = _mm_srl_epi16(left.data, right.data);
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator>>= (Int32x4 & left, uint32_t count) [inline]
Definition at line 300 of file int32x4.h.
References corecvs::Int32x4::data.
{
    if ( __builtin_constant_p(count) )
        left.data = (int32x4_t)vshrq_n_u32((uint32x4_t)left.data, (int32_t)count);
    else
        left.data = (int32x4_t)vshlq_u32((uint32x4_t)left.data, vdupq_n_s32(-(int32_t)count));
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator>>= (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 330 of file int32x4.h.
References corecvs::Int32x4::data.
{
    int count = vgetq_lane_s32(right.data, 0);
    left.data = (int32x4_t)vshlq_u32((uint32x4_t)left.data, vdupq_n_s32(-count));
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator>>= (Int16x16 & left, uint32_t count) [inline]
Definition at line 360 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_srli_epi16(left.data, count);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator>>= (Int16x8 & left, uint32_t count) [inline]
Definition at line 367 of file int16x8.h.
References corecvs::Int16x8::data.
{
    if ( __builtin_constant_p(count) )
        left.data = vshrq_n_s16(left.data, (int)count);
    else
        left.data = vshlq_s16(left.data, vdupq_n_s16(-(int)count));
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator>>= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 382 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_srl_epi16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator>>= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 396 of file int16x8.h.
References corecvs::Int16x8::data.
{
    int count = vgetq_lane_s16(right.data, 0);
    left.data = (int16x8_t)vshlq_u16((uint16x8_t)left.data, vdupq_n_s16(-count));
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator^ (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 227 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return veorq_s32(left.data, right.data);
}
FORCE_INLINE Int16x8 corecvs::operator^ (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 290 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return veorq_s16(left.data, right.data);
}
FORCE_INLINE Int16x16 corecvs::operator^ (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 297 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_xor_si128(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::operator^= (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 245 of file int32x4.h.
References corecvs::Int32x4::data.
{
    left.data = veorq_s32(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator^= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 308 of file int16x8.h.
References corecvs::Int16x8::data.
{
    left.data = veorq_s16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator^= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 315 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_xor_si128(left.data, right.data);
    return left;
}
FORCE_INLINE Int32x4 corecvs::operator| (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 223 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vorrq_s32(left.data, right.data);
}
FORCE_INLINE Int16x8 corecvs::operator| (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 286 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return vorrq_s16(left.data, right.data);
}
FORCE_INLINE Int16x16 corecvs::operator| (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 293 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_or_si128(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::operator|= (Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 240 of file int32x4.h.
References corecvs::Int32x4::data.
{
    left.data = vorrq_s32(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x8 corecvs::operator|= (Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 303 of file int16x8.h.
References corecvs::Int16x8::data.
{
    left.data = vorrq_s16(left.data, right.data);
    return left;
}
FORCE_INLINE Int16x16 corecvs::operator|= (Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 310 of file int16x16.h.
References corecvs::Int16x16::data.
{
    left.data = _mm256_or_si128(left.data, right.data);
    return left;
}
template<typename IndexType , class Function > void corecvs::parallelable_for (IndexType begin, IndexType end, const Function & f, bool = true)
This template provides the parallelable call of the function over the interval with or without TBB.
Tring to be faster
Definition at line 137 of file tbbWrapper.h.
References parallelable_for_notbb().
Referenced by corecvs::AbstractBuffer< SegmentType * >::doConvolve(), corecvs::AbstractBuffer< SegmentType * >::doConvolve1(), corecvs::AbstractContiniousBuffer< double, int >::doReverseDeformation(), corecvs::AbstractContiniousBuffer< double, int >::doReverseDeformationBl(), corecvs::G12Buffer::doReverseDeformationBlPrecomp(), corecvs::IntegralBuffer< uint32_t, G12Buffer::InternalElementType, int32_t >::rectangularBlur(), and corecvs::DirectRemapper::remap().
{
    parallelable_for_notbb(begin, end, f);
}
template<typename IndexType , class Function > void corecvs::parallelable_for (IndexType begin, IndexType end, std::size_t , const Function & f, bool = true)
Definition at line 143 of file tbbWrapper.h.
References parallelable_for_notbb().
{
    parallelable_for_notbb(begin, end, f);
}
template<typename IndexType , class Function > void corecvs::parallelable_for_notbb (IndexType begin, IndexType end, const Function & f)
This template provides the dummy call of the function over the interval without TBB.
Definition at line 106 of file tbbWrapper.h.
Referenced by parallelable_for().
{
    f(BlockedRange<IndexType>(begin, end));
}
template<typename IndexType , class Function > void corecvs::parallelable_reduce (IndexType begin, IndexType end, Function & f)
Definition at line 166 of file tbbWrapper.h.
References parallelable_reduce_notbb().
Referenced by corecvs::PunchedBufferOperations< SixDBuffer, SixDBufferBase::InternalElementType >::density(), and corecvs::Triangulator::triangulateHelperParallel().
{
    parallelable_reduce_notbb(begin, end, f);
}
template<typename IndexType , class Function > void corecvs::parallelable_reduce_notbb (IndexType begin, IndexType end, Function & f)
Definition at line 153 of file tbbWrapper.h.
Referenced by parallelable_reduce().
{
    f(BlockedRange<IndexType>(begin, end));
}
template<> void corecvs::PrinterVisitor::visit< std::string, StringField > (std::string & field, const StringField * fieldDescriptor)
template<template< typename > class KernelType> static void corecvs::process (G12Buffer * input[KernelType< DummyAlgebra >::inputNumber], G12Buffer * output[KernelType< DummyAlgebra >::inputNumber], const KernelType< DummyAlgebra > & kernel = KernelType< DummyAlgebra >()) [static]
This function is a copy of the one in G12Buffer.cpp.
But this is for a reason
Definition at line 108 of file g12Buffer.cpp.
{
    BufferProcessor<
        G12Buffer,
        G12Buffer,
        KernelType,
        G12BufferAlgebra
    > processor;
    processor.process(input, output, kernel);
}
template<template< typename > class KernelType> static void corecvs::process8 (G8Buffer * input[KernelType< DummyAlgebra >::inputNumber], G8Buffer * output[KernelType< DummyAlgebra >::inputNumber], const KernelType< DummyAlgebra > & kernel = KernelType<DummyAlgebra>()) [static]
Definition at line 35 of file morphological.cpp.
{
    BufferProcessor<
        G8Buffer,
        G8Buffer,
        KernelType,
        G8BufferAlgebra
    > processor;
    processor.process(input, output, kernel);
}
FORCE_INLINE Int32x8 corecvs::productExtending (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 439 of file int16x8.h.
References productHigherPart(), productLowerPart(), unpackHigher4(), and unpackLower4().
{
    Int16x8  lowParts;
    Int16x8 highParts;
    lowParts  = productLowerPart (left, right);
    highParts = productHigherPart(left, right);
    return Int32x8(unpackLower4(lowParts,highParts), unpackHigher4 (lowParts,highParts));
}
FORCE_INLINE UInt16x8 corecvs::productHigherPart (const UInt16x8 & left, const UInt16x8 & right)
Definition at line 145 of file uInt16x8.h.
References corecvs::SSEInteger< RealType >::data.
{
    return UInt16x8(_mm_mulhi_epu16(left.data, right.data));
}
FORCE_INLINE UInt8x16 corecvs::productHigherPart (const UInt8x16 & left, const UInt8x16 & right)
Definition at line 340 of file uInt8x16.h.
References corecvs::SSEInteger< RealType >::data.
{
    return UInt8x16(_mm_mulhi_epi16(left.data, right.data));
}
FORCE_INLINE Int8x16 corecvs::productHigherPart (const Int8x16 & left, const Int8x16 & right)
Definition at line 345 of file int8x16.h.
References corecvs::SSEInteger< RealType >::data.
{
    return Int8x16(_mm_mulhi_epi16(left.data, right.data));
}
FORCE_INLINE Int16x16 corecvs::productHigherPart (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 403 of file int16x16.h.
References corecvs::Int16x16::data.
Referenced by productExtending().
{
    return Int16x16(_mm256_mulhi_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::productHigherPart (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 418 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return vqdmulhq_s16(left.data, right.data);
}
FORCE_INLINE UInt8x16 corecvs::productLowerPart (const UInt8x16 & left, const UInt8x16 & right)
Definition at line 336 of file uInt8x16.h.
References corecvs::SSEInteger< RealType >::data.
{
    return UInt8x16(_mm_mullo_epi16(left.data, right.data));
}
FORCE_INLINE Int8x16 corecvs::productLowerPart (const Int8x16 & left, const Int8x16 & right)
Definition at line 341 of file int8x16.h.
References corecvs::SSEInteger< RealType >::data.
{
    return Int8x16(_mm_mullo_epi16(left.data, right.data));
}
FORCE_INLINE Int16x16 corecvs::productLowerPart (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 399 of file int16x16.h.
References corecvs::Int16x16::data.
Referenced by operator*(), operator*=(), and productExtending().
{
    return Int16x16(_mm256_mullo_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::productLowerPart (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 414 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return vmulq_s16(left.data, right.data);
}
double corecvs::radToDeg (double angle) [inline]
Useful radian to degrees and back conversions.
Definition at line 154 of file mathUtils.h.
References M_PI.
Referenced by StereoCameraScene::drawMyself(), CameraCalculatorWidget::lensFocalChanged(), UniversalRectifier::recalculate(), CloudViewDialog::resetCamera(), and AngleEditBox::updateDegreeAngles().
{
    return angle / M_PI * 180.0;
}
template<typename Type > Type corecvs::randRanged (Type valMax, Type valMin = Type(0)) [inline]
Function to get a random value in the given range.
Definition at line 122 of file mathUtils.h.
Referenced by corecvs::AbstractBuffer< SegmentType * >::fillWithRands().
{
    return (Type)(valMin + ((double)rand() / RAND_MAX * (valMax - valMin)));   // no round for int to fit into [min, max] range
}
template<typename IntegerType > istream& corecvs::read_integer_bin (istream & is, IntegerType & value)
Definition at line 108 of file abstractBuffer.h.
Referenced by corecvs::AbstractBufferParams::load(), and corecvs::AbstractBufferParams::read().
{
    value = 0;
    for (unsigned size = 0; size < sizeof(IntegerType); size++) {
        value |= is.get() << (8 * size);
    }
    return is;
}
Matrix33 corecvs::Rotate (const Vector3dd & v, double alpha)
Creates a 3x3 matrix that rotates around the given axis in 3D.
TODO: This is the same code as in Quaternion merge it
Parameters:
alpha an angle to rotate by
v an axis to rotate around
Returns:
the rotation matrix
Definition at line 349 of file matrix33.cpp.
References corecvs::Vector3d< ElementType >::x(), corecvs::Vector3d< ElementType >::y(), and corecvs::Vector3d< ElementType >::z().
{
    double c = cos(alpha);
    double s = sin(alpha);
    Vector3dd u = v / !v;
    return Matrix33(
     u.x() * u.x() + (1 - u.x() * u.x() ) * c,
     u.x() * u.y() * (1 - c) - u.z() * s,
     u.x() * u.z() * (1 - c) + u.y() * s,
     u.x() * u.y() * (1 - c) + u.z() * s,
     u.y() * u.y() + (1 - u.y() * u.y() ) * c,
     u.y() * u.z() * (1 - c) - u.x() * s,
     u.x() * u.z() * (1 - c) - u.y() * s,
     u.y() * u.z() * (1 - c) + u.x() * s,
     u.z() * u.z() + (1 - u.z() * u.z()) * c
    );
}
int corecvs::roundDiv (int nom, unsigned int nDenom) [inline]
Definition at line 82 of file mathUtils.h.
{
    return (nom + (nom >= 0 ? (nDenom >> 1) : -(int)(nDenom >> 1))) / nDenom;
}
int corecvs::roundDivUp (int nom, unsigned int nDenom) [inline]
Definition at line 77 of file mathUtils.h.
References _roundDivUp.
Referenced by DirectShowCaptureDecoupleInterface::memberCallback().
{
    return _roundDivUp(nom, nDenom);
}
int corecvs::roundShift (int iVal, unsigned int nShift) [inline]
Definition at line 97 of file mathUtils.h.
References roundShiftUp().
{
    return iVal >= 0 ? roundShiftUp(iVal, nShift) : -roundShiftUp(-iVal, nShift);
}
int corecvs::roundShiftUp (int iVal, unsigned int nShift) [inline]
Definition at line 92 of file mathUtils.h.
Referenced by roundShift().
{
    return (iVal + (1 << (nShift - 1))) >> nShift;
}
int corecvs::roundSign (double dValue, bool bSign) [inline]
Definition at line 45 of file mathUtils.h.
Referenced by roundSign().
{
    return (int)(dValue + (bSign ? .5 : -.5));
}
int corecvs::roundSign (double dValue, int iSign) [inline]
Definition at line 50 of file mathUtils.h.
References roundSign().
{
    return roundSign(dValue, iSign >= 0);
}
int corecvs::roundSign (double dValue, double dSign) [inline]
Definition at line 55 of file mathUtils.h.
References roundSign().
{
    return roundSign(dValue, dSign >= 0);
}
int corecvs::roundSign (double dValue) [inline]
Definition at line 60 of file mathUtils.h.
References roundSign().
{
    return roundSign(dValue, dValue);
}
int corecvs::roundUp (double dValue) [inline]
Definition at line 40 of file mathUtils.h.
{
    return (int)(dValue + .5);
}
void corecvs::setStdTerminateHandler ()
Definition at line 50 of file utils.cpp.
References stdTerminateHandler().
Referenced by main().
{
    std::set_terminate(stdTerminateHandler);
}
FORCE_INLINE Int32x4 corecvs::shiftArithmetic (const Int32x4 & left, uint32_t count) [inline]
Definition at line 287 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return vshlq_s32(left.data, vdupq_n_s32(-(int32_t)count));
}
FORCE_INLINE Int32x4 corecvs::shiftArithmetic (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 319 of file int32x4.h.
References corecvs::Int32x4::data.
{
    int count = vgetq_lane_s32(right.data, 0);
    return vshlq_s32(left.data, vdupq_n_s32(-count));
}
FORCE_INLINE Int16x8 corecvs::shiftArithmetic (const Int16x8 & left, uint32_t count) [inline]
Definition at line 350 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return vshlq_s16(left.data, vdupq_n_s16(-(int)count));
}
FORCE_INLINE Int16x16 corecvs::shiftArithmetic (const Int16x16 & left, uint32_t count) [inline]
Definition at line 351 of file int16x16.h.
References corecvs::Int16x16::data.
Referenced by corecvs::SSEMath::div().
{
    return Int16x16(_mm256_srai_epi16(left.data, count));
}
FORCE_INLINE Int16x16 corecvs::shiftArithmetic (const Int16x16 & left, const Int16x16 & right) [inline]
Definition at line 373 of file int16x16.h.
References corecvs::Int16x16::data.
{
    return Int16x16(_mm256_sra_epi16(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::shiftArithmetic (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 385 of file int16x8.h.
References corecvs::Int16x8::data.
{
    int count = vgetq_lane_s16(right.data, 0);
    return vshlq_s16(left.data, vdupq_n_s16(-count));
}
FORCE_INLINE Int64x2 corecvs::shiftLogical (const Int64x2 & left, uint32_t count)
Definition at line 133 of file int64x2.h.
References corecvs::Int64x2::data.
{
    return Int64x2(_mm_srli_epi64(left.data, count));
}
FORCE_INLINE Int64x2 corecvs::shiftLogical (const Int64x2 & left, const Int64x2 & right)
Definition at line 137 of file int64x2.h.
References corecvs::Int64x2::data.
{
    return Int64x2(_mm_srl_epi64(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::shiftLogical (const Int16x8 & left, uint32_t count)
Definition at line 161 of file int16x8.h.
References corecvs::Int16x8::data.
Referenced by corecvs::DecoupleYUYV::decouple().
{
    return Int16x8(_mm_srli_epi16(left.data, count));
}
FORCE_INLINE Int16x8 corecvs::shiftLogical (const Int16x8 & left, const Int16x8 & right)
Definition at line 179 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return Int16x8(_mm_srl_epi16(left.data, right.data));
}
FORCE_INLINE Int32x4 corecvs::shiftLogical (const Int32x4 & left, uint32_t count)
Definition at line 231 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return Int32x4(_mm_srli_epi32(left.data, count));
}
FORCE_INLINE Int32x4 corecvs::shiftLogical (const Int32x4 & left, const Int32x4 & right)
Definition at line 258 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return Int32x4(_mm_srl_epi32(left.data, right.data));
}
FORCE_INLINE Int16x8 corecvs::shrAdd (const Int16x8 & accumulator, const Int16x8 & left, uint32_t count) [inline]
Definition at line 354 of file int16x8.h.
References corecvs::Int16x8::data.
{
    return vsraq_n_s16(accumulator.data, left.data, count);
}
void corecvs::stdTerminateHandler ()
Definition at line 36 of file utils.cpp.
Referenced by setStdTerminateHandler().
{
      void *array[10];
      size_t size;
      // get void*'s for all entries on the stack
      size = backtrace(array, 10);
      // print out all the frames to stderr
      //fprintf(stderr, "Error: signal %d:\n", sig);
      backtrace_symbols_fd(array, size, 2);
      exit(1);
}
template<typename Type > void corecvs::SwapInts (Type & a, Type & b) [inline]
On intel architecture there could be no gain in xor because often compiler can swap register aliases without any code generation.
Definition at line 117 of file mathUtils.h.
{ a ^= b; b ^= a; a ^= b; }
template<typename Type > void corecvs::SwapXY (Type & a, Type & b) [inline]
Useful Swap* stuff.
Definition at line 110 of file mathUtils.h.
{ Type t = a; a = b; b = t; }
int corecvs::test1Main (void)
Definition at line 131 of file lutAlgebra.cpp.
References corecvs::LUTable::approxF(), corecvs::LUTGenerator::deviations(), corecvs::LUTGenerator::Deviations::devMax, corecvs::LUTGenerator::Deviations::devSqSum, corecvs::LUTGenerator::Deviations::devSum, corecvs::LUTGenerator::generate(), corecvs::LUTGenerator::Deviations::size, and corecvs::LUTGenerator::Deviations::valueMax.
{
    //LUTable lut;
    LUTGenerator *generator = new LUTGenerator();
    SqrtFunction *sqrtF = new SqrtFunction();
    LUTable *lut =  generator->generate(*sqrtF, string("sqrt"), 512);
    lut->approxF(7056);
    for (int i = 0; i < 0xFFFFFF; i+=0x7FF65 )
    {
        printf("%u %u %u\n", i, (uint32_t)sqrt((float)i), lut->approxF(i));
    }
    //lut->generateCCode();
    LUTGenerator::Deviations a = generator->deviations(lut, *sqrtF);
    printf("[%lf %lf %lf %u (of %u)]\n", a.devSum, a.devSqSum, a.devMax, a.valueMax, a.size);
    return 0;
}
TriangleIterator corecvs::triangleIteratorCreate (vector2Dd p1, vector2Dd p2, vector2Dd p3)
int corecvs::triangleIteratorNext (TriangleIterator * iterator, vector2Ds32 * pos)
FORCE_INLINE Int64x2 corecvs::unpackHigher2 (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 352 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return (int64x2_t)vzipq_s32(left.data, right.data).val[1];
}
FORCE_INLINE Int32x4 corecvs::unpackHigher4 (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 435 of file int16x8.h.
References corecvs::Int16x8::data.
Referenced by corecvs::Int16x8::expand(), and productExtending().
{
    return (int32x4_t)vzipq_s16(left.data, right.data).val[1];
}
FORCE_INLINE Int64x2 corecvs::unpackLower2 (const Int32x4 & left, const Int32x4 & right) [inline]
Definition at line 348 of file int32x4.h.
References corecvs::Int32x4::data.
{
    return (int64x2_t)vzipq_s32(left.data, right.data).val[0];
}
FORCE_INLINE Int32x4 corecvs::unpackLower4 (const Int16x8 & left, const Int16x8 & right) [inline]
Definition at line 431 of file int16x8.h.
References corecvs::Int16x8::data.
Referenced by corecvs::Int16x8::expand(), and productExtending().
{
    return (int32x4_t)vzipq_s16(left.data, right.data).val[0];
}
vector2Dd corecvs::vector2DdCreate (double x, double y)
Definition at line 107 of file geometry.c.
Referenced by correctLens().
{
        vector2Dd toReturn = {x, y};
        return toReturn;
}
void corecvs::vector2DdIncrement (vector2Dd * a, vector2Dd * b)
double corecvs::vector2DdLength (vector2Dd * a)
vector3Dd corecvs::vector3DdAdd (vector3Dd a, vector3Dd b)
vector3Dd corecvs::vector3DdCreate (double x, double y, double z)
Definition at line 101 of file geometry.c.
{
        vector3Dd toReturn = {x,y,z};
        return toReturn;
}
void corecvs::vectorHomogeniousNormalize (vector3Dd * a)
vector3Dd corecvs::vectorMultiplyConst (vector3Dd a, double b)
void corecvs::vectorNormalize (vector3Dd * a)
void corecvs::vectorPrint (vector3Dd * v)
template<typename IntegerType > ostream& corecvs::write_integer_bin (ostream & os, IntegerType value)
These are useful methods to serialize integer types not depending of the current endianess.
Definition at line 99 of file abstractBuffer.h.
Referenced by corecvs::AbstractBufferParams::dump(), and corecvs::AbstractBufferParams::write().
{
    for (unsigned size = sizeof(IntegerType); size != 0; size--, value >>= 8) {
        os.put(static_cast<char>(value & 0xFF));
    }
    return os;
}
Variable Documentation
const int corecvs::dimention = 2
Definition at line 13 of file levenmarq.cpp.
Referenced by corecvs::LevenMarq::doLevMarFit(), and doLMFit().
const int corecvs::iterations = 100
Definition at line 11 of file levenmarq.cpp.
Referenced by corecvs::LevenMarq::doLevMarFit(), UniversalRectifier::ransacMethod(), and AutomatedRectifyControlWidget::updateFinalSigma().
const double corecvs::lambda_factor = 1.5
Definition at line 12 of file levenmarq.cpp.
Referenced by corecvs::LevenMarq::doLevMarFit().
const double corecvs::minXDif = 5
Definition at line 14 of file levenmarq.cpp.
Referenced by corecvs::LevenMarq::doLevMarFit().
const int corecvs::QUATERNION_DIMENTION = 4
Definition at line 17 of file quaternion.h.
cchar* corecvs::sFormatStr = "#dims:%d (%d) x %d x %u" [static]
Definition at line 13 of file abstractBuffer.cpp.
Referenced by corecvs::AbstractBufferParams::dump(), and corecvs::AbstractBufferParams::load().
int const corecvs::tileSize = 15
Definition at line 17 of file meanShiftWindow.cpp.
Referenced by corecvs::MeanShiftWindow::moveWindow().