DeepView: Triangulation Namespace Reference
Triangulation Namespace Reference
Classes
class Point
class Edge
struct TriangulationBeginnings
struct EdgeCmp
struct PointGroup
Typedefs
typedef double ElementType
typedef list< Point >
::const_iterator Lpci
typedef list< Point >::iterator Lpi
typedef list< PointGroup > ListOfLists
Enumerations
enum {
LEFT = 0, RIGHT = 1, BEYOND = 2, BEHIND = 3,
BETWEEN = 4, ORIGIN = 5, DESTINATION = 6
}
Position of the point with respect to the directed edge.
enum {
COLLINEAR = 0, PARALLEL = 1, SKEW = 2, SKEW_CROSS = 3,
SKEW_NO_CROSS = 4
}
Functions
int orientation (const Point &p0, const Point &p1, const Point &p2)
bool doubleEqual (const double a, const double b)
comparison precise up to epsilon
int classify (const Point &dest, const Point &org, const Point &p2)
bool mate (const Edge &e, const vector< Point > &points, Point &p)
Searches for the the closest point on the right of the edge.
Edge hullEdge (const vector< Point > &points)
int updateFrontier (set< Edge, EdgeCmp > &frontier, const Point &a, const Point &b, set< Edge, EdgeCmp > &died)
bool isInsideTriangle (const Edge &e1, const Edge &e2, const Edge &e3, const Point &point)
Point findTriangleCenter (const Point &p1, const Point &p2, const Point &p3)
static void splitPoints (const vector< Point > &points, TriangulationBeginnings &tb, ListOfLists &listOfLists, const int maxDistance)
std::vector< Edge > triangulate4 (const vector< Point > &points, list< Point > &centers, TriangulationBeginnings &tb, const int maxDistance)
void printPoints (const vector< Point > &points)
std::vector< Edge > triangulate (const vector< Point > &points)
std::vector< Edge > vertexHull (const vector< Point > &points)
std::vector< Edge > vertexHullFromTriangulation (const std::vector< Edge > &edges, const int pointsCount, const TriangulationBeginnings &tb)
Variables
const double DEFAULT_MAX_DISTANCE = 200.0
const double EPSILON = 0.00001
Typedef Documentation
typedef double Triangulation::ElementType
Definition at line 47 of file triangulation.h.
typedef list<PointGroup> Triangulation::ListOfLists
Definition at line 310 of file triangulation.h.
typedef list<Point>::const_iterator Triangulation::Lpci
Definition at line 259 of file triangulation.h.
typedef list<Point>::iterator Triangulation::Lpi
Definition at line 260 of file triangulation.h.
Enumeration Type Documentation
anonymous enum
Position of the point with respect to the directed edge.
Enumerator:
LEFT
Point is to the left of the edge.
RIGHT
Point is to the right of the edge.
BEYOND
Point is on the same line as the edge but beyond the end.
BEHIND
Point is on the same line as the edge but before the start.
BETWEEN
The point is on the edge.
ORIGIN
The point is the origin.
DESTINATION
The point is the destination.
Definition at line 155 of file triangulation.h.
{
    LEFT = 0, /**< Point is to the left of the edge */
    RIGHT = 1, /**< Point is to the right of the edge */
    BEYOND = 2, /**< Point is on the same line as the edge but beyond the end */
    BEHIND = 3, /**< Point is on the same line as the edge but before the start */
    BETWEEN = 4, /**< The point is on the edge */
    ORIGIN = 5, /**< The point is the origin */
    DESTINATION = 6
/**< The point is the destination */
};
anonymous enum
Enumerator:
COLLINEAR
PARALLEL
SKEW
SKEW_CROSS
SKEW_NO_CROSS
Definition at line 167 of file triangulation.h.
{
    COLLINEAR = 0, PARALLEL = 1, SKEW = 2, SKEW_CROSS = 3, SKEW_NO_CROSS = 4
};
Function Documentation
int Triangulation::classify (const Point & dest, const Point & org, const Point & p2)
Definition at line 101 of file triangulation.cpp.
References BEHIND, BETWEEN, BEYOND, DESTINATION, LEFT, Triangulation::Point::length(), ORIGIN, RIGHT, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Triangulation::Edge::classify(), and hullEdge().
{
    Point a = dest - org;
    Point b = p2 - org;
    double sa = a.x() * b.y() - b.x() * a.y();
    if (sa > 0.0)
        return RIGHT;
    else if (sa < 0.0)
        return LEFT;
    else if ((a.x() * b.x() < 0.0) || (a.y() * b.y() < 0.0))
        return BEHIND;
    else if (a.length() < b.length())
        return BEYOND;
    else if (org == p2)
        return ORIGIN;
    else if (dest == p2)
        return DESTINATION;
    return BETWEEN;
}
bool Triangulation::doubleEqual (const double a, const double b) [inline]
comparison precise up to epsilon
Definition at line 65 of file triangulation.cpp.
References EPSILON.
Referenced by Triangulation::Edge::intersect().
{
    return (fabs(a-b) < EPSILON);
}
Point Triangulation::findTriangleCenter (const Point & p1, const Point & p2, const Point & p3)
Definition at line 239 of file triangulation.cpp.
References Triangulation::Point::color(), and Triangulation::Point::remoteness().
Referenced by triangulate4().
{
    Point result = (p1 + p2 + p3) * (1.0/3.0);
    double r1 = result.remoteness(p1);
    double r2 = result.remoteness(p2);
    double r3 = result.remoteness(p3);
    double r0 = r1 + r2 + r3;
    //result.color() = (p1.color() + p2.color() + p3.color())/3.0;
    result.color() = p1.color() * r1/r0 + p2.color() * r2/r0 + p3.color() * r3/r0;
    //cout << "Color1: " << p1.color() << " Color2: " << p2.color() << " Color3: " << p3.color()
    //        << " Result: " << result.color() << endl;
    return result;
}
Edge Triangulation::hullEdge (const vector< Point > & points)
Definition at line 164 of file triangulation.cpp.
References BETWEEN, classify(), and RIGHT.
Referenced by triangulate().
{
    size_t m = 0;
    size_t i;
    for (i = 1; i < points.size(); i++)
    {
        if (points[i] < points[m])
            m = i;
    }
    size_t min = m; // "minimal point"
    m = 0;
    i = 1;
    // processing the marginal situations, when "minimal point" is one of the first ones
    if (min == 0)
    {
        m = 1;
        i = 2;
    }
    else if (min == 1)
        i = 2;
    // serching for the seconf point of the "minimum edge"
    for (; i < points.size(); i++)
    {
        if (i == min)
            continue;
        int c = classify(points[min], points[m], points[i]);
        if (c  ==  RIGHT || c  == BETWEEN)
            m = i;
    }
    return Edge(points[min], points[m]);
}
bool Triangulation::isInsideTriangle (const Edge & e1, const Edge & e2, const Edge & e3, const Point & point) [inline]
Definition at line 228 of file triangulation.cpp.
References BETWEEN, Triangulation::Edge::classify(), ORIGIN, and RIGHT.
{
    //RIGHT BETWEEN ORIGIN DESTINATION
    if ( (e1.classify(point) == RIGHT || e1.classify(point) == BETWEEN || e1.classify(point) == ORIGIN) &&
             (e2.classify(point) == RIGHT || e2.classify(point) == BETWEEN || e2.classify(point) == ORIGIN) &&
             (e3.classify(point) == RIGHT || e3.classify(point) == BETWEEN || e3.classify(point) == ORIGIN))
        return true;
    return false;
}
bool Triangulation::mate (const Edge & e, const vector< Point > & points, Point & p)
Searches for the the closest point on the right of the edge.
Condition is that the circle around given 3 points should not contain other points
Definition at line 128 of file triangulation.cpp.
References Triangulation::Edge::classify(), Triangulation::Edge::dest, Triangulation::Edge::intersect(), RIGHT, Triangulation::Edge::rot(), SKEW, corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by triangulate().
{
    Point bestp(0,0);
        double t, bestt = std::numeric_limits<double>::max();
    Edge f = e;
    f.rot();      // f - perpendicular to the center of the segment ะต
    //cout << "enum {LEFT = 0,  RIGHT = 1,  BEYOND = 2,  BEHIND = 3, BETWEEN = 4, ORIGIN = 5, DESTINATION = 6};\n";
    for (size_t i = 0; i < points.size(); i++)
    {
        //cout << "    Classify: " << points[i] << " for " << e << " is: " << e.classify(points[i]) << endl;
        if (e.classify(points[i]) == RIGHT)
        {
            Edge g(e.dest, points[i]);
            g.rot();
            int intersect = f.intersect (g, t);
            //cout << "        enum {COLLINEAR = 0, PARALLEL = 1, SKEW = 2, SKEW_CROSS = 3, SKEW_NO_CROSS = 4 }\n ";
            //cout        << "intersecting: " << f << " and " << g << ". intersect = : " << intersect << ", t = " << t << endl;
            if (t < bestt && intersect == SKEW )
            {
                bestp = points[i];
                bestt = t;
            }
        }
    }
    if ((bestp.x() != 0) && (bestp.y() != 0))
    {
        p = bestp;
        return true;
    }
    return false;
}
int Triangulation::orientation (const Point & p0, const Point & p1, const Point & p2)
Definition at line 18 of file triangulation.cpp.
References corecvs::Vector2d< ElementType >::triangleOrientedAreaTo().
{
    Point a = p1  - p0;
    Point b = p2  - p0;
    //double sa = a.x() * b.y() - b.x() * a.y();
  double sa = a.triangleOrientedAreaTo(b);
    if (sa > 0.0)
        return 1;
    else if (sa < 0.0)
        return -1;
    return 0;
}
void Triangulation::printPoints (const vector< Point > & points)
Definition at line 513 of file triangulation.cpp.
{
    cout << "printPoints: ";
    for (vector<Point>::const_iterator i = points.begin(); i != points.end(); i++)
        cout << *i << endl;
    cout << endl;
}
static void Triangulation::splitPoints (const vector< Point > & points, TriangulationBeginnings & tb, ListOfLists & listOfLists, const int maxDistance) [static]
Definition at line 402 of file triangulation.cpp.
References Triangulation::TriangulationBeginnings::hullEdges, Triangulation::TriangulationBeginnings::numOfGroups, and Triangulation::PointGroup::push_back().
Referenced by triangulate4().
{
    list<Point> lpoints;
    for (vector<Point>::const_iterator i = points.begin(); i != points.end(); i++)
        lpoints.push_back(*i);
    // O(N^2)
    while (!lpoints.empty())
    {
        Point current = *lpoints.begin();
        lpoints.pop_front();
        //cout << "Current: " << current << endl;
        {
            PointGroup currentList;
            currentList.push_back(current);
            listOfLists.push_back(currentList);
        }
        for(Lpi i = lpoints.begin(); i != lpoints.end();)
        {
      if (listOfLists.back().isNear(*i, maxDistance))
            {
                listOfLists.back().push_back(*i);
                Lpi tmpPoint = i;
                i++;
                lpoints.erase(tmpPoint);
            }
            else
                i++;
        }
    }
    tb.numOfGroups = (int)listOfLists.size();
    tb.hullEdges.resize(tb.numOfGroups);
}
std::vector< Edge > Triangulation::triangulate (const vector< Point > & points)
Definition at line 521 of file triangulation.cpp.
References Triangulation::Edge::dest, hullEdge(), mate(), Triangulation::Edge::org, and updateFrontier().
{
    //printPoints(points);
    Point p;
    set<Edge,    EdgeCmp> frontier;
    set<Edge,    EdgeCmp> died;
    list<vector<Point> > triangles;
    cout << "Using simple triangulation\n";
    if (points.size() < 3)
    {
        cout << "(triangulate): No enought data!\n";
        return std::vector<Edge>();
    }
    Edge e = hullEdge(points);
    //cout << "Hull Edge: " << e << endl;
    frontier.insert(e);
    while (!frontier.empty())
    {
        e = *(frontier.begin());
        frontier.erase(e);
        if (mate(e, points, p))
        {
            //cout << "!!!Found mate for " << e << " is   " << p << endl;
            died.insert(e);
            int r = updateFrontier(frontier, p, e.org, died);
            r +=    updateFrontier(frontier, e.dest, p, died);
            //assert (r == 0);
            if (!r)
            {
                vector<Point> triangle(3);
                triangle[0] = e.org;
                triangle[1] = e.dest;
                triangle[2] = p;
            //cout << "    New triangle: " <<p << ", " << e.org << ", " << e.dest << endl;
            triangles.push_back(triangle);
             }
        }
    }
    std::vector<Edge> newEdges(triangles.size() * 3);
    //list<Edge> newEdges();
    //  cout << "Returning triangles\n";
    int j = 0;
    for (list<vector<Point> >::const_iterator i = triangles.begin(); i != triangles.end(); i++)
    {
        /*newEdges.push_back(Edge((*i)[0], (*i)[1]));
        newEdges.push_back(Edge((*i)[1], (*i)[2]));
        newEdges.push_back(Edge((*i)[2], (*i)[0]));*/
        newEdges[j].org = (*i)[0];
        newEdges[j++].dest = (*i)[1];
        newEdges[j].org = (*i)[1];
        newEdges[j++].dest = (*i)[2];
        newEdges[j].org = (*i)[2];
        newEdges[j++].dest = (*i)[0];
    }
    cout << "Triangles:" << triangles.size() << " Edges: " << newEdges.size() << " Points: " << points.size() << endl;
    return newEdges;
}
std::vector< Edge > Triangulation::triangulate4 (const vector< Point > & points, list< Point > & centers, TriangulationBeginnings & tb, const int maxDistance)
Definition at line 440 of file triangulation.cpp.
References findTriangleCenter(), Triangulation::TriangulationBeginnings::hullEdges, splitPoints(), and TRIANGULATE.
Referenced by vertexHull().
{
    ListOfLists listOfLists;
  //uint64_t microseconds;
  //PreciseTimer timer = PreciseTimer::currentTime();
  cout << "Using fast split algorithm\n";
  //cerr << "-----splitPoints started-----\n";
  splitPoints(points, tb, listOfLists, maxDistance);
  //cerr << "-----splitPoints finished-----\n";
  //microseconds = timer.usecsTo(PreciseTimer::currentTime());
  //cerr << "splitPoints Real time: " << microseconds << " microseconds, " << microseconds/1000000.0 << " secs\n";
    //return vector<Edge>();
    cout << "(triangulate4) Points: " << points.size() << endl;
    size_t countOfEdges = 0;
    vector<Edge> *edges = new vector<Edge> [listOfLists.size()];
    size_t t = 0;
    for (ListOfLists::const_iterator i = listOfLists.begin(); i != listOfLists.end(); i++, t++)
    {
    //cout << "    size:" << i->mList.size() << endl;
        //all += i->size();
    vector<Point> newpoints(i->mList.size());
        int k = 0;
    for (Lpci j = i->mList.begin(); j != i->mList.end(); j++)
            newpoints[k++] = *j;
    edges[t] = TRIANGULATE(newpoints);
        //edges[t] = vector<Edge>();
        if (edges[t].size() != 0)
            tb.hullEdges[t] = (int)countOfEdges;
        else
            tb.hullEdges[t] = -1;
        countOfEdges += edges[t].size();
    }
    cout << "Total edges: " << countOfEdges << endl;
    vector<Edge> result(countOfEdges);
    for (size_t l = 0, currentEdgesArray = 0, currentEdgesIndex = 0;
             currentEdgesArray < listOfLists.size() && l < countOfEdges;
             currentEdgesIndex++)
    {
        if (currentEdgesIndex >= edges[currentEdgesArray].size())
        {
      //cout << "!!! currentEdgesIndex:" << currentEdgesIndex << " currentEdgesArray:" << currentEdgesArray << endl;
            currentEdgesIndex = -1;
            currentEdgesArray++;
            continue;
        }
        result[l++] = edges[currentEdgesArray][currentEdgesIndex];
    }
  for (vector<Edge>::const_iterator it = result.begin(); it != result.end(); it += 3)
    centers.push_back(findTriangleCenter(it->org, it->dest,
      (it+1)->dest == it->dest ? (it+1)->org : (it+1)->dest));
    delete [] edges;
    return result;
}
int Triangulation::updateFrontier (set< Edge, EdgeCmp > & frontier, const Point & a, const Point & b, set< Edge, EdgeCmp > & died)
Definition at line 203 of file triangulation.cpp.
References Triangulation::Edge::flip().
Referenced by triangulate().
{
#if !defined(_MSC_VER) || (_MSC_VER > 1500)         // TODO: VS2008 doesn't compile this code!?
    Edge e(a,b);
    if (frontier.find(e) != frontier.end())
    {
        //cout << "[updateFrontier] erasing " << e << "from frontier\n";
        frontier.erase(e);
        died.insert(e);
    }
    else
    {
        e.flip();
        if (died.find(e) == died.end())
        {
            //cout << "[updateFrontier] inserting " << e << " with length: " << e.org.remoteness(e.dest)<< " to frontier\n";
            frontier.insert(e);
        }
        else
            return 1;
    }
#endif
    return 0;
}
std::vector< Edge > Triangulation::vertexHull (const vector< Point > & points)
Definition at line 588 of file triangulation.cpp.
References triangulate4(), and vertexHullFromTriangulation().
{
    if (points.size() < 3)
    {
        cout << "No enought data!\n";
        return std::vector<Edge>();
    }
    list<Point> tmp;
    TriangulationBeginnings tb;
    std::vector<Edge> triangulations = triangulate4(points, tmp, tb);
    return vertexHullFromTriangulation(triangulations, (int)points.size(), tb);
}
std::vector< Edge > Triangulation::vertexHullFromTriangulation (const std::vector< Edge > & edges, const int pointsCount, const TriangulationBeginnings & tb)
Definition at line 603 of file triangulation.cpp.
References Triangulation::Edge::cosAngle(), Triangulation::Edge::dest, Triangulation::TriangulationBeginnings::hullEdges, Triangulation::TriangulationBeginnings::numOfGroups, and Triangulation::Edge::org.
Referenced by vertexHull().
{
    int i = 0;
    std::vector<Edge> result(pointsCount);
    multimap<Point, Edge> edgeList;
    multimap<Point, Edge>::const_iterator it;
    pair<multimap<Point, Edge>::iterator, multimap<Point, Edge>::iterator> ret;
    // creating data structure in which it is easy to find the edges originating from a given point
    for (vector<Edge>::const_iterator i = edges.begin() + 1; i != edges.end(); i++)
        edgeList.insert(make_pair(i->org, *i));
    //cout << "========================\n";
    Point point0 = edges[0].org;
    //cout << "Point0 :" << point0 << " Point1 :" << edges[0].dest << endl;
    Edge cur;
    bool firstIteration = true;
    int groupCounter = -1;
    //cout << "tb.numOfGroups: " << tb.numOfGroups << endl;
    while (groupCounter < tb.numOfGroups)
    {
        if (cur.dest == point0 || firstIteration)
        {
            firstIteration = false;
            groupCounter ++;
            if (groupCounter == tb.numOfGroups)
                break;
            if (tb.hullEdges[groupCounter] == -1)
            {
                groupCounter++;
                continue;
            }
            //cout << "|||Next group : " << tb.hullEdges[groupCounter] << endl;
            cur.org = point0 = edges[tb.hullEdges[groupCounter]].org;
            cur.dest = edges[tb.hullEdges[groupCounter]].dest;
            result[i++] = cur;
            continue;
        }
        // searching all outgoing edges form the given point
        ret = edgeList.equal_range(cur.dest);
        //cout << "    " << cur.dest << ":::: \n";
        double maxAngle = -1.1;
        Edge maxEdge;
        for (it = ret.first; it!=ret.second; ++it)
        {
            //     cout << "        " << (*it).second << endl;
                 double angle = cur.cosAngle((*it).second); // cosinus
                 if (angle > maxAngle)
                 {
                     maxAngle = angle;
                     maxEdge = (*it).second;
                 }
        }
        //cout << "    maxAngle: " << maxAngle << " maxEdge: " << maxEdge << endl;
        cur = maxEdge;
        result[i++] = maxEdge;
    }
    return result;
}
Variable Documentation
const double Triangulation::DEFAULT_MAX_DISTANCE = 200.0
Definition at line 42 of file triangulation.h.
const double Triangulation::EPSILON = 0.00001
Definition at line 43 of file triangulation.h.
Referenced by doubleEqual().