DeepView: utils/corestructs/painterHelpers.cpp File Reference
utils/corestructs/painterHelpers.cpp File Reference
Add Comment Here.
#include <stdint.h>
#include "painterHelpers.h"
#include "mathUtils.h"
Functions
void drawLine (QPainter &painter, const Vector2dd &start, const Vector2dd &end)
void drawCircle (QPainter &painter, const Vector2dd &center, double radius)
void drawSquare (QPainter &painter, const Vector2dd &center, int size)
void drawArc (QPainter &painter, const Vector2dd &center, double radius, int start, int len)
void drawPie (QPainter &painter, const Vector2dd &center, double radius, int start, int len)
void uniteAnaglyph (const QImage *left, const QImage *right, QImage *result, uint32_t lmask, uint32_t rmask)
void disableComboBoxItem (QComboBox *box, int item)
Detailed Description
Add Comment Here.
Date:
Nov 5, 2011
Author:
alexander
Definition in file painterHelpers.cpp.
Function Documentation
void disableComboBoxItem (QComboBox * box, int item)
Definition at line 91 of file painterHelpers.cpp.
Referenced by BaseHostDialog::initParameterWidgets().
{
    QModelIndex index1 = box->model()->index(item,0);
    QVariant v1(0);
    box->model()->setData( index1, v1, Qt::UserRole -1);
}
void drawArc (QPainter & painter, const Vector2dd & center, double radius, int start, int len)
Definition at line 42 of file painterHelpers.cpp.
References corecvs::fround(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    painter.drawArc(
            fround(center.x() - radius),
            fround(center.y() - radius),
            fround(2.0 * radius), fround(2.0 * radius),
            start, len);
}
void drawCircle (QPainter & painter, const Vector2dd & center, double radius)
Definition at line 23 of file painterHelpers.cpp.
References corecvs::fround(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by PaintImageWidget::childRepaint(), CloudViewDialog::initializeGLSlot(), and TestbedMainWindow::loadImage().
{
    painter.drawEllipse(
            fround(center.x() - radius),
            fround(center.y() - radius),
            fround(2.0 * radius), fround(2.0 * radius));
}
void drawLine (QPainter & painter, const Vector2dd & start, const Vector2dd & end)
Definition at line 16 of file painterHelpers.cpp.
References corecvs::fround(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by PaintImageWidget::childRepaint().
{
    painter.drawLine(
            fround(start.x()), fround(start.y()),
            fround(end  .x()), fround(end  .y()));
}
void drawPie (QPainter & painter, const Vector2dd & center, double radius, int start, int len)
Definition at line 51 of file painterHelpers.cpp.
References corecvs::fround(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
{
    painter.drawPie(
            fround(center.x() - radius),
            fround(center.y() - radius),
            fround(2.0 * radius), fround(2.0 * radius),
            start, len);
}
void drawSquare (QPainter & painter, const Vector2dd & center, int size)
Definition at line 31 of file painterHelpers.cpp.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by PaintImageWidget::childRepaint().
{
    painter.drawRect(
            center.x() - (size / 2),
            center.y() - (size / 2),
            size,
            size
    );
}
void uniteAnaglyph (const QImage * left, const QImage * right, QImage * result, uint32_t lmask, uint32_t rmask)
Definition at line 60 of file painterHelpers.cpp.
Referenced by ImageResultLayer::drawImage().
{
    if (left  ->format() != right ->format() ||
        left  ->format() != result->format() )
        return;
    int hmin = left  ->height();
    if (hmin > right ->height()) hmin = right ->height();
    if (hmin > result->height()) hmin = result->height();
    int wmin = left  ->width();
    if (wmin > right ->width()) wmin = right ->width();
    if (wmin > result->width()) wmin = result->width();
    for (int i = 0; i < hmin; i++)
    {
        const uint32_t *src1 = (const uint32_t *)left ->scanLine(i);
        const uint32_t *src2 = (const uint32_t *)right->scanLine(i);
        uint32_t *dest       = (uint32_t *)result->scanLine(i);
       for (int j = 0; j < wmin; j++)
       {
           *dest = (*src1 & lmask) | (*src2 & rmask);
           dest++;
           src1++;
           src2++;
       }
    }
}