DeepView: utils/qtHelper.h File Reference
utils/qtHelper.h File Reference
#include <QtCore/QDebug>
#include <QtGui/QDoubleSpinBox>
#include "vector2d.h"
#include "vector3d.h"
Functions
QDebug & operator<< (QDebug &stream, const corecvs::Vector2dd &vector)
QDebug & operator<< (QDebug &stream, const corecvs::Vector3dd &vector)
void setValueBlocking (QDoubleSpinBox *box, double value)
Detailed Description
Date:
Apr 27, 2013
Definition in file qtHelper.h.
Function Documentation
QDebug& operator<< (QDebug & stream, const corecvs::Vector2dd & vector)
QDebug& operator<< (QDebug & stream, const corecvs::Vector3dd & vector)
void setValueBlocking (QDoubleSpinBox * box, double value)
Definition at line 26 of file qtHelper.cpp.
Referenced by AngleEditBox::updateDegreeAngles(), AutomatedRectifyControlWidget::updateFocal2(), and AngleEditBox::updateRagAngles().
{
    bool wasBlocked = box->blockSignals(true);
    box->setValue(value);
    box->blockSignals(wasBlocked);
}