DeepView: Triangulation::PointGroup Struct Reference
Triangulation::PointGroup Struct Reference
#include <triangulation.h>
Public Member Functions
PointGroup ()
void push_back (const Point &newPoint)
bool isNear (const Point &target, const int maxDistance) const
Public Attributes
double minX
double minY
double maxX
double maxY
list< Point > mList
Detailed Description
Definition at line 262 of file triangulation.h.
Constructor & Destructor Documentation
Triangulation::PointGroup::PointGroup () [inline]
Definition at line 269 of file triangulation.h.
                  :
            minX(std::numeric_limits<double>::max()), minY(std::numeric_limits<double>::max()), maxX(
                    -std::numeric_limits<double>::max()), maxY(-std::numeric_limits<double>::max())
    {
    }
Member Function Documentation
bool Triangulation::PointGroup::isNear (const Point & target, const int maxDistance) const [inline]
Definition at line 289 of file triangulation.h.
References Triangulation::Point::remoteness(), corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
    {
        if (target.x() > maxX + maxDistance || target.x() < minX - maxDistance
                || target.y() > maxY + maxDistance || target.y() < minY - maxDistance)
        {
            //cout << "quick found works\n";
            return false;
        }
        for (Lpci secondPoint = mList.begin(); secondPoint != mList.end(); secondPoint++)
        {
            if (target.remoteness(*secondPoint) < maxDistance)
                return true;
        }
        return false;
    }
void Triangulation::PointGroup::push_back (const Point & newPoint) [inline]
Definition at line 275 of file triangulation.h.
References corecvs::Vector2d< ElementType >::x(), and corecvs::Vector2d< ElementType >::y().
Referenced by Triangulation::splitPoints().
    {
        mList.push_back(newPoint);
        if (newPoint.x() > maxX)
            maxX = newPoint.x();
        if (newPoint.y() > maxY)
            maxY = newPoint.y();
        if (newPoint.x() < minX)
            minX = newPoint.x();
        if (newPoint.y() < minY)
            minY = newPoint.y();
    }
Member Data Documentation
double Triangulation::PointGroup::maxX
Definition at line 266 of file triangulation.h.
double Triangulation::PointGroup::maxY
Definition at line 266 of file triangulation.h.
double Triangulation::PointGroup::minX
Definition at line 265 of file triangulation.h.
double Triangulation::PointGroup::minY
Definition at line 265 of file triangulation.h.
list<Point> Triangulation::PointGroup::mList
Definition at line 267 of file triangulation.h.
The documentation for this struct was generated from the following file:
core/geometry/triangulation.h