DeepView: core/utils/util.c File Reference
core/utils/util.c File Reference
TODO.
#include <stdint.h>
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <execinfo.h>
#include "global.h"
Functions
void stackTraceHandler (int sig)
void setSegVHandler ()
Detailed Description
TODO.
Date:
Mar 23, 2010
Author:
alexander
Definition in file util.c.
Function Documentation
void setSegVHandler ()
Definition at line 115 of file util.c.
References stackTraceHandler().
Referenced by main().
{
    signal(SIGSEGV, stackTraceHandler);   // install our handler
}
void stackTraceHandler (int sig)
Definition at line 101 of file util.c.
References CORE_COUNT_OF.
Referenced by setSegVHandler().
{
    void *array[10];
    size_t size;
    /* get void*'s for all entries on the stack */
    size = backtrace(array, CORE_COUNT_OF(array));
    /* print out all the frames to stderr */
    fprintf(stderr, "Error: signal %d:\n", sig);
    backtrace_symbols_fd(array, size, 2);
    exit(1);
}